### ISSUE TITLE
IP missing in docs: 52.154.53.1

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#10002]
Today, I did an import in Central US and it failed because the following IP was missing in the docs: 52.154.53.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#run-an-import)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NenoLoje - thank you Neno for the feedback. I just got the confirmation from the engineer and am updating the article to include the missing IP address.
