### ISSUE TITLE
Extension manifest reference: Update values for Azure DevOps Server 2019

### ISSUE THREAD

**Issue by fleckert** [MicrosoftDocs/azure-devops-docs#10006]
Please add values for Azure DevOps Server 2019.
Please add information regarding Server Version and "demands" : "api-version".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Added values to table to Azure DevOps Server 2020, Added Tips = links to [Azure Devops Extension SDK](https://developer.microsoft.com/azure-devops/develop/extensions) and [REST API Reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1). Thanks for your feedback! This issue will automatically close once the PR goes live.
