### ISSUE TITLE
How to set Start Date and Target Date

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#10003]
The page says 
```
For work items that span one or more iterations, you can define the Start Date and Target Date. The plan displays cards that start and end according to the dates you set as shown in the following image.
```
But is nowhere to be seen how to do that. How am I supposed to set a Start Date and Target Date if such fields do not appear anywehre at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops&tabs=plans-preview)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JoseFMP - Thank you for your inquiry. First note that this feature is ONLY available with Azure DevOps Services, the cloud platform. If the Start and Target Dates are missing from a work item type, Feature, Epic, or custom, you can add them to the work item type by following the instructions given here:  https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=azure-devops#add-an-existing-field-to-another-wit.
