### ISSUE TITLE
Cycle Time incorrectly mentioned as Lead time

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/azure-devops-docs#10018]
Typo error: Cycle time is incorrectly mentioned as Lead time. 

Lead time: Days on average to complete deliverables from date created
**Lead time**: Days on average to complete deliverables from date work started
Number of outliers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb022ac7-a3a0-3437-bca4-0fa798bed82e
* Version Independent ID: db0d8280-120c-f4b4-0fcc-6fc47b3fc7ec
* Content: [View SAFe® progress, roadmaps, and metrics - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/safe-review-roadmaps-progress?view=azure-devops)
* Content Source: [docs/boards/plans/safe-review-roadmaps-progress.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/safe-review-roadmaps-progress.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
Addressing in PR: MicrosoftDocs/azure-devops-docs-pr/pull/2838

**Comment by vijay-gowda** [comment]
I do not see this fix reflecting yet. I believe this is still work in progress as part of some PR?

**Comment by TimShererWithAquent** [comment]
@vijay-gowda That's correct. The change will be reflected in a couple of days.
