### ISSUE TITLE
[DockerV2] Document DockerOutput output variable

### ISSUE THREAD

**Issue by beatcracker** [MicrosoftDocs/azure-devops-docs#10015]
DockerV2 task creates an output variable with path(s) to log files with the Docker command output. It can be used in the templates like this: `$(Docker.DockerOutput)`.

This variable is not documented, but it has a description in the task source:

> The path of the file(s) which contains the output of the command. This contains two file paths (separated by newline characters) in case of buildAndPush command, and one file path for any other command.

* https://github.com/microsoft/azure-pipelines-tasks/blob/9b971ed2102307f35d325ef9e0b86922fb72cbe2/Tasks/DockerV2/task.json#L135

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml#output-variables

Please check it out and let us know what you think. Thank you.
