### ISSUE TITLE
Azure CLI task Doc - Using 'argument's together with 'inlineScript' in the second code example is misleading

### ISSUE THREAD

**Issue by Smoovsky** [MicrosoftDocs/azure-devops-docs#10017]
If I don't take it wrong, 'argument' is meant to be used with the script file. If someone is using inline script, content put in the argument is simply disregarded. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by TimShererWithAquent** [comment]
@ramiMSFT Assigning to you, but you should check the author and ms.author on this topic.

**Comment by ramiMSFT** [comment]
@Smoovsky You can use `arguments` with both inline and file scripts. I'm adding two examples to the article.
