### ISSUE TITLE
Azure DevOps Server 2020 is missing in the matrix

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#10022]
The text implies this doc is up to date with Azure DevOps 2020, but Azure DevOps 2020 is missing from the compatibility matrix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5c0726-1492-650f-3ebb-08407acb21f9
* Version Independent ID: 53e88c46-86d7-74af-3b82-b630c3c9d689
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?WT.mc_id=DOP-MVP-5001511&view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by jessehouwing** [comment]
still open

**Comment by steved0x** [comment]
I believe this article has been updated with 202 in the table but I will give it a review to ensure it is up to date.

**Comment by steved0x** [comment]
I made a small update to the article that should be live shortly.
