### ISSUE TITLE
"Docker - Build and push an image to Azure Container Registry instaed of "Docker" only

### ISSUE THREAD

**Issue by gpdev-cso** [MicrosoftDocs/azure-devops-docs#10029]
In the "Connect and select repository" section, instead of
"When the Configure tab appears, select Docker."
it should be written
"When the Configure tab appears, select Docker - Build and push an image to Azure Container Registry"

Thiose are two different types of pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by ramiMSFT** [comment]
@gpdev-cso Thank you for your feedback!
