### ISSUE TITLE
Only Admin access on bitbucket repo works

### ISSUE THREAD

**Issue by okezieokpara** [MicrosoftDocs/azure-devops-docs#10037]
---
#### Document Details

I have an issue with the required access.
For this to work, the user must have admin rights to the repo. Currently, read/write access doesn't work.
Also only the use with the actual rights can edit the pipeline, so if you have 10 users you need to grant all 10 admin access to the repo instead of using one shared service connection.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf09cc7f-cd4d-6647-e47b-82744bd3d2dd
* Version Independent ID: 75e80c27-0e2e-41d1-272f-e3da856f5071
* Content: [Build Bitbucket Cloud repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/bitbucket.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/bitbucket.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@okezieokpara Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
