### ISSUE TITLE
IIS Basic Auth vs. Git using PAT information is misleading

### ISSUE THREAD

**Issue by CaringDev** [MicrosoftDocs/azure-devops-docs#10038]
The information makes it look like the base64 encoding approach is only needed if Basic Auth is enabled. IME Git does not work with plain PATs in general for the on-prem (that is Azure DevOps Server) scenario, as Windows Auth prevents the use of PATs as well. So this page should be updated to reflect the fact that the extraheader must be used for all Azure DevOps _Server_ installations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fa3b01-218c-9a5f-5b71-affdf65c945c
* Version Independent ID: 7c414686-f52d-51ce-87e1-794deade8506
* Content: [IIS Basic Authentication invalidates using PATs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/iis-basic-auth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/iis-basic-auth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/iis-basic-auth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by CaringDev** [comment]
see also https://docs.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops-2020#authentication

**Comment by CaringDev** [comment]
related: #8890

**Comment by chcomley** [comment]
I've just published an update, thanks so much for your feedback! Once it's live, this issue will automatically close.
