### ISSUE TITLE
Cannot delete Preview of Task Group

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/azure-devops-docs#10042]
It would be good to note in the documentation that once a Preview task group version is created that there is NO way to delete that Preview task group nor is it possible to edit a previous version. 

I think it's a bad design to prevent a Preview task group version from being deleted as this is a simple action that developers can do, but it locks the pipeline management in to having to on board to the new task group version. In our case, this simple mistake is causing us to have to update over 50 build pipelines to use the new published version; work that could have been avoided if it was possible to simply delete the accidentally created preview task group version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@W0GER We have this labeled as a doc request, but if you'd like to provide feedback on the product design, please [use this link](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
