### ISSUE TITLE
Karm link is outdated

### ISSUE THREAD

**Issue by frode** [MicrosoftDocs/azure-devops-docs#10046]
[Enter feedback here]

I would recommend to swap out the link to end to end testing for karma to the one that points to the latest release: https://karma-runner.github.io/latest/index.html as the current link is 4 major versions behind the latest.

Best
Frode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops&tabs=code)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @frode! This will be updated shortly.
