### ISSUE TITLE
.bypass is not working as documented

### ISSUE THREAD

**Issue by fabiostawinski** [MicrosoftDocs/azure-devops-docs#10040]
Hello, 

I used this doc to configure our agents, and we face this issue:
https://github.com/microsoft/azure-pipelines-tasks/issues/11061

Seems, there is a problem, either in the doc or in how the agent reads the bypass file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5d1372-3bf2-5733-25a4-eddbdfb7511c
* Version Independent ID: 2823a0ff-df57-4338-9b60-780beb8c7c74
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x The linked item isn't completely settled whether this is doc or code.

**Comment by fabiostawinski** [comment]
> @steved0x The linked item isn't completely settled whether this is doc or code.

It's my last comment in the link, it says about the problem with the documentation.
