### ISSUE TITLE
Where do related work items come from?

### ISSUE THREAD

**Issue by damianon** [MicrosoftDocs/azure-devops-docs#10041]
For a pipeline task at a specific stage I wanted to get all related workitems, since the last time the pipeline was deployed to that stage. 
E.g. Stage "Test" only deploys nightly, so if during the day 12 PRs get on master (and cause builds & deploys to the Dev stage), during the night only the latest build is deployed to test. Now I want a list of all related tasks compared to the last deploy to Test.

Not very relevant, but to do this with Releases I used a ps script to get the last deployed version and the difference in Work Items from the api.

Now with pipelines it seems "Related" is fixed for the whole run?

Also - and this is my main feedback for the docs - I couldn't find any information at all about how devops determines which items are related. It's not just the ones from the PR, because I've had runs where items from the previous run were also included. I have yet to find a reasoning on how this list is created as it is never explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@damianon I think this has been addressed by this new article, [Configure pipelines to support work tracking](https://docs.microsoft.com/azure/devops/pipelines/integrations/configure-pipelines-work-tracking?view=azure-devops&tabs=yaml).
