### ISSUE TITLE
Fixed termnology: TFS Data Import Service

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#10059]
This page still talks about "TFS", although it's relevant for the latest version of Azure DevOps Server.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ecc59-b30a-cb41-aa6b-7ba24fb6fa2a
* Version Independent ID: f5b6f454-7b3b-79cf-ab86-2cf0f043a660
* Content: [Resolve validation errors - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/resolve-errors?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/resolve-errors.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/import-process/resolve-errors.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NenoLoje - Thanks, Neno, for the feedback. I'll take a look and make any updates that are needed.
