### ISSUE TITLE
Not actual section

### ISSUE THREAD

**Issue by bblrlo** [MicrosoftDocs/azure-devops-docs#10058]
Hi All

The section "View the current values of all variables" (https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#view-the-current-values-of-all-variables) is not actual. The "Initialize job" step is always grey now on on-prem and on-line versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 810b2ae0-ebbc-9fe0-fabb-700a57f20c9d
* Version Independent ID: 3ba38edc-4990-5ef5-c10e-79f1be686d3f
* Content: [Classic release and artifacts variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@shashban Not sure whether this is an out of date screen cap or stems from a difference in configuration.
