### ISSUE TITLE
Post-deployment approvals

### ISSUE THREAD

**Issue by damianon** [MicrosoftDocs/azure-devops-docs#10055]
Hello,

what happened to post-deployment approvals? No mention anywhere and environments (except of being very light on features anyway) also don't have anything except approvals

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by shashban** [comment]
The YAML design is centered around pre-deployment protection for environments through approvals and checks. 
The deployment process and validation is not centrally controlled through environment properties. You can add manual validation in the job for verifying the deployment.

**Comment by damianon** [comment]
The YAML design seems really light on features. It's not even possible to tell a pipeline/environment to only deploy the latest version. We had a build that was waiting for the "business hours" and after that we switched to approval. Then, a day later that build just deploys even though the latest build on that environment was a couple versions newer.

**Comment by TimShererWithAquent** [comment]
@damianon This might be a question to bring to the relevant product team, rather than an issue with the documentation. The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
