### ISSUE TITLE
[azure-devops-docs] Update the external links to GitHub Actions documentation

### ISSUE THREAD

**Issue by martin389** [MicrosoftDocs/azure-devops-docs#10053]
The URLs for [GitHub Actions docs](https://docs.github.com/) were recently changed. The URLs previously contained a string for `free-pro-team@latest`, which has since been removed. Redirects were added to ensure that the old links still worked.

To help ease redirect processing, the URLs in this article should be updated to remove the `free-pro-team@latest` string:

- "Quickstart: trigger a pipeline run from GitHub Actions": [[Published article]](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions) - [[Markdown source]](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/github-actions.md).

### Action plan
For each doc listed above:
1. Remove the `free-pro-team@latest` string in each link to [docs.github.com](https://docs.github.com/).
2. Test the new link to confirm that it resolves correctly.

**Comment by martin389** [comment]
👋 We'll be working on this with @juliakm.

**Comment by juliakm** [comment]
The update is merged now.
