### ISSUE TITLE
Documentation of Fields in ADO Process Templates

### ISSUE THREAD

**Issue by El-Jeffe** [MicrosoftDocs/azure-devops-docs#10060]
It would be very helpful if there was a page/pages that documented not only the Work Item Types;

- Epic
- Feature
- User Story/PBI
- Task
but also the default Fields that are associated with each of these work item types.  It would help when trying to make a decision on which template to use to build your project.

If this already exists I could not find it and would appreciate a pointer to it.

Thank you.

Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 705dda6e-d073-7df4-eb99-33e3ef858e09
* Version Independent ID: 8fa9c990-26e8-742b-9446-0946d892307e
* Content: [Agile process template artifacts - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/agile-process?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/agile-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/agile-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@El-Jeffe - see https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azure-devops.

**Comment by KathrynEE** [comment]
@El-Jeffe - Thank you for your inquiry. I will update the articles to point to the Field Index. Note that because all processes - Agile, Scrum, Basic, and CMMI - are defined for all organizations/collections, all fields are available for use in all processes. You simply have to add it as an existing field to a work item form.
