### ISSUE TITLE
Enterprise access isn't defined

### ISSUE THREAD

**Issue by jspaith** [MicrosoftDocs/azure-devops-docs#10066]
I went to look at my Azure Dev ops project status, Visibility level.  When I click to get more info I'm taking to the page referenced in GitHub issue.

The issue is that I see `Enterprise` as a drop down option but there's no documentation about what this means either on the settings page itself or on this page linked below.  E.G. the link showing the public/private in visibility doesn't have Enterprise as an option.

I have a guess about what this does but would be great if this could be formally documented when you get a chance.

Thanks - John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a4e9e9-6773-fad2-23fb-8b44313f8ef3
* Version Independent ID: 33cbd1fc-2230-4e0b-2627-2a63bf7c634e
* Content: [Make your project public or private - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/organizations/public/make-project-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/make-project-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by MS-alsulli** [comment]
Spoke w/ John via Teams. Closing this per his request.
