### ISSUE TITLE
PAT Behavior changed - leaving private agents almost unusable

### ISSUE THREAD

**Issue by janlunddk** [MicrosoftDocs/azure-devops-docs#10065]
It should probably be mentioned in the documentation that the behavior of PAT have changed so that it requires the owner of the PAT to be logged on to Azure DevOps (or at least have an active Azure DevOps Auth token)

This also means that the Private Agents are unusable in DevOps pipelines - especially on weekends and holidays if the PAT owner does not regularly log in.

Please also look at this request, asking for a feature to be able to use service principals as auth method for the private agents:
https://developercommunity.visualstudio.com/idea/1216766/devops-self-hosted-agent-containers-allow-service.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cveld** [comment]
Have you looked into using Azure Active Directory to acquire a token for Azure DevOps?
https://github.com/microsoft/azure-devops-auth-samples/tree/master/NonInteractivePatGenerationSample

**Comment by janlunddk** [comment]
@cveld Thanks for your comment. I will definately take a look at that and check it out as it could be a first step towards a solution. 

However, I am not too happy about it, as there still is a dependency on a specific human, which is not a good thing in an automated world.

As we create the agents dynamically in an AKS cluster when a pipeline is run e.g. on a pull request, the developer making that pull request will most likely not have permission to register agents - and would still need to make the pipeline use his/her credentials somehow. On a team with a handful of developers this is far from optimal.

Then you could argue to store the credentials of a user that have those rights in a key vault, and let the pipeline read from that key vault. But seen from a security perspective that would probably mean that anyone with access to managing the pipeline in question could potentially read another users credentials.

This is why it would be perfect with having a service principal authentication for the agent registration instead of PAT.

But I might have overlooked something 😃

**Comment by steved0x** [comment]
There is a new feature that is live now, here: [Pipeline agents can be registered using Azure Active Directory instead of a PAT](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-227-update#pipeline-agents-can-be-registered-using-azure-active-directory-instead-of-a-pat). This page will be updated shortly.
