### ISSUE TITLE
Add further detail about automatically downloaded artifacts.

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/azure-devops-docs#10077]
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs

1. Add further detail about which lifecycle hooks of deployment jobs automatically download artifacts. If they all do, then state so, if some do then make it explicit.
2. Add further detail about whether agentless jobs within the deployment lifecycle hooks automatically download artifacts, or not (or link to documentation that already states the outcome).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@adriantorrie Thank you for your feedback. The download artifact task will be auto injected only when using the `deploy` lifecycle hook. See [lifecycle hooks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#descriptions-of-lifecycle-hooks) to learn about the other types of hooks.
We only support the tasks below for [agentless jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#agentless-tasks) but you can use extensions to add other agentless tasks:
- [Delay task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops)
- [Invoke Azure Function task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops)
- [Invoke REST API task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
- [Publish To Azure Service Bus task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-to-azure-service-bus?view=azure-devops)
- [Query Azure Monitor Alerts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-monitor?view=azure-devops)
- [Query Work Items task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/work-item-query?view=azure-devops)
