### ISSUE TITLE
Screnshots are outdated, the two options no longer appear to have differences. 

### ISSUE THREAD

**Issue by StephenWTurner** [MicrosoftDocs/azure-devops-docs#10074]
The documentation appears outdated. 

I created a provisioned wiki and a code wiki in a new project, both types of wiki have the same options in the menu associated with the page. 

The table of features also needs review as you can do more with a provisioned wiki if you use the Clone Wiki option to get to the hidden git repository. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @StephenWTurner, Thanks for reaching out. I've created a user story on my backlog to address this. Once the PR completes, this issue will automatically close. Thanks again!

**Comment by chcomley** [comment]
Reassigning to @amitkumariiit, thank you.

**Comment by chcomley** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than 3/21 with additional information.
We appreciate your contribution and encourage you to propose changes [using public PRs ](https://learn.microsoft.com/en-us/contribute/) or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
