### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by narinluangrath** [MicrosoftDocs/azure-devops-docs#10079]
> Azure Web Apps for containers offer the fastest and simplest way for you run a container instance in Azure.

Missing "to"

Azure Web Apps for containers offer the fastest and simplest way for you **to** run a container instance in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9fbc1a-8e3f-31c9-64c2-5a21cd9c5aec
* Version Independent ID: 692a9a5a-e49a-1295-6bd9-8a82410adaf0
* Content: [Deploy to Azure index to content - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/overview-azure?view=azure-devops)
* Content Source: [docs/pipelines/overview-azure.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/overview-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@narinluangrath Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation is now updated, expect changes to be released within the next few days.
