### ISSUE TITLE
Is this task still in preview?

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/azure-devops-docs#10078]
This page was last updated in April last year, is this task still in preview after nearly a year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd40694-540e-98c1-32ef-87af48fde27d
* Version Independent ID: d1b89b4b-e36e-9cd2-2010-f12b3e2506d6
* Content: [Container Structure Test Task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/container-structure-test-task?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/container-structure-test-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/container-structure-test-task.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @Additi
* Microsoft Alias: **admahesh**

**Comment by TimShererWithAquent** [comment]
@Additi I think this is more of a doc freshness issue than a product question.
