### ISSUE TITLE
Documentation on several pages about DownloadPipelineArtifact@2 is at odds with each other.

### ISSUE THREAD

**Issue by ChrisBurgessMS** [MicrosoftDocs/azure-devops-docs#10089]
Under the "Downloading artifacts" section there is this comment.

By default, files are downloaded to $(Pipeline.Workspace)/{artifact}, where artifact is the name of the artifact. The folder structure of the artifact is always preserved.

Then in the "Single artifact" section there is this comment "are downloaded under $(Pipeline.Workspace)/WebApp"

![image](https://user-images.githubusercontent.com/63321051/106186080-9c2ad080-6158-11eb-8743-cb171bedaa70.png)

And then later in "Migrating from build artifacts" this is said.

**By default, the Download Pipeline Artifact task downloads files to $(Pipeline.Workspace). This is the default and recommended path for all types of artifact**

Over on this page https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops  this is said about the "path" variable

Default value: $(Pipeline.Workspace)

The first two comments and the second two comments are at odds with each other.  Experience (usage of the task) shows that the default root is in fact $(Pipeline.Workspace)  This should be fixed either go into the $(Pipeline.Workspace/{artifact} location or the documentation needs to be updated to reflect the reality.  I highly suggest the $(Pipeline.Workspace)/{artifact} location as the $(Pipeline.Workspace) location doesn't have a good way to get cleaned between pipeline usages and if the content isn't from only that pipeline it causes issues that are hard to detect and harder to prevent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@vijayma is author for the other topic linked to in the description.

**Comment by ramiMSFT** [comment]
@ChrisBurgessMS Thank you for your feedback. The new version will go live shortly.
