### ISSUE TITLE
ci/cd implementation on azure data factory with code

### ISSUE THREAD

**Issue by suri1925** [MicrosoftDocs/azure-devops-docs#10083]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10b66e25-c091-9c59-c878-8e5b52493a76
* Version Independent ID: fd3c9c97-3186-7b05-db36-82407fa3572b
* Content: [Overview of CI/CD data pipelines on Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/cicd-data-overview?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/azure/cicd-data-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/azure/cicd-data-overview.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
Included with issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/10082.
