### ISSUE TITLE
STRATEGY_CYCLENAME & STRATEGY_NAME need to be documented

### ISSUE THREAD

**Issue by adriantorrie** [MicrosoftDocs/azure-devops-docs#10091]
When running a `runOnce` deployment strategy, I can see the vars `STRATEGY_CYCLENAME` and `STRATEGY_NAME` available within any bash task (by running `env` within the bash task).

- When on a `deploy` stage,  I can see `STRATEGY_CYCLENAME=Iteration`
- When on a `on: failure` stage, I can see `STRATEGY_CYCLENAME=PostIteration`

It would be good to know what available values are, as we use templates within the various stages, and reusing `STRATEGY_CYCLENAME` for suffixes on step names would be very handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@adriantorrie There is a reference to `strategy.name` [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops). I'm working on verifying with the engineering team that these are the options for `strategy.cyclename` and `strategy.name`:

Strategy.CycleName
- PreIteration
- Iteration
- PostIteration

Strategy.Name
- canary
- runOnce
- rolling

**Comment by juliakm** [comment]
I'll push a documentation update shortly.
