### ISSUE TITLE
Iterations not assigned to the Team still appear in filter

### ISSUE THREAD

**Issue by salipour1105** [MicrosoftDocs/azure-devops-docs#10094]
"Iteration: All Iteration Paths selected for the current team and for which there are work items assigned to that iteration"

This function does not seem to be working. When you remove the iterations for the Team, the removed iterations still appear in the filter list. If a work item is closed, the removed iteration still appears. How do you remove the iteration from the Filter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5017884-bcc0-3fa7-6bfd-73bb04ab7524
* Version Independent ID: cadea453-739a-6498-268a-ad3391a4f65b
* Content: [Filter your Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/filter-kanban-board?view=azure-devops)
* Content Source: [docs/boards/boards/filter-kanban-board.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/boards/filter-kanban-board.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@salipour1105 It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
