### ISSUE TITLE
workspace is incorrectly indented

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/azure-devops-docs#10095]
In this page, there is a section talking about `workspace`. One of the coding snippets it has `workspace` inside of `pool` which is miss-leading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
Fixing in PR MicrosoftDocs/azure-devops-docs-pr/pull/2841

Will close when change is merged.
