### ISSUE TITLE
Current version of Az Module outdated

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/azure-devops-docs#10093]
The latest version of Az modules is [5.4.0](https://www.powershellgallery.com/packages/Az/5.4.0), but the pages still mentions 3.5.0 for task version 4.* and 3.1.0 for task version 5.*

Which version is `latestVersion`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
Should be doc-bug. Looks like this is being addressed.

**Comment by TimShererWithAquent** [comment]
The merged PR above addresses this issue.
