### ISSUE TITLE
azure-devops-project-url must have no trailing slash

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-devops-docs#10100]
See https://github.com/Azure/pipelines/issues/16 for the details.

The documentation doesn't disclose the fact that `azure-devops-project-url` must have no trailing slash, otherwise an error will occur:

>##[error]Failed to parse project url:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ea192f-6f71-4f46-895a-9ea1c106d6c1
* Version Independent ID: fdbc829d-e137-11c6-c35f-626970e44cef
* Content: [Trigger a pipeline run from a GitHub action - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/github-actions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/github-actions.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @abatishchev! I'll update the article to make this clearer.
