### ISSUE TITLE
How to discover azure devops pull requests in jenkins Multibranch Pipeline

### ISSUE THREAD

**Issue by devopsmash** [MicrosoftDocs/azure-devops-docs#10103]
Hi, it seems that your doc about [Create a service hook for Azure DevOps with Jenkins](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/jenkins?view=azure-devops) is missing the way of how to discover azure devops pull requests on `Jenkins Multibranch Pipeline`.

it's really improtant for us to understand how can we achieve triggered jenkins pipelines when a new pull request is opened.

any chance that you can add some more information about how to handle this scenario on this guide?

some more info:
https://stackoverflow.com/questions/65957769/how-to-discover-azure-devops-pull-requests-in-jenkins-multibranch-pipeline
https://issues.jenkins.io/browse/JENKINS-64719

**Comment by usernkey** [comment]
after few days I solved it like this.
<img width="813" alt="Screen Shot 2021-08-16 at 18 14 21" src="https://user-images.githubusercontent.com/12896983/129595523-811e0f42-2aa2-49f0-a9ae-1ba855691c01.png">

**Comment by northbear** [comment]
@usernkey it works for me. Thanks!
