### ISSUE TITLE
Mention pipeline caching when comparing Microsoft and self hosted agents

### ISSUE THREAD

**Issue by BillHally** [MicrosoftDocs/azure-devops-docs#10117]
The section [Do self-hosted agents have any performance advantages over Microsoft-hosted agents?](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#private-agent-performance-advantages) should probably link to [Pipeline caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) since it provides a way to at least partially mitigate what the current text describes as:
>you don't get these benefits because the agent is destroyed after the build or release pipeline is completed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Good point I have added a link to caching in the section you pointed out.
