### ISSUE TITLE
-bash: printf: -s: invalid option

### ISSUE THREAD

**Issue by xukai871105** [MicrosoftDocs/azure-devops-docs#10115]
[Enter feedback here]
B64_PAT=$(printf -n":$MY_PAT" | base64)
-bash: printf: -s: invalid option

I think the right bash script is
printf "%s"":$MY_PAT"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @xukai871105, Thanks for your feedback. I've created a user story to address this. Once the updated article is published, this issue will automatically close. You can always @mention me if you have any further feedback or questions. Thanks again!
