### ISSUE TITLE
Sample code for nuget doesn't work

### ISSUE THREAD

**Issue by recumbent** [MicrosoftDocs/azure-devops-docs#10116]
The sample code for caching nuget defines a variable:

```
  NUGET_PACKAGES: $(UserProfile)/.nuget/packages
```

Which results in an error:

```
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(560,5): error : 'NUGET_PACKAGES' must contain an absolute path '$(UserProfile)/.nuget/packages'. [D:\a\1\s\WebApp.Tests\WebApp.Tests.fsproj]
```

If, instead, one follows the pattern for other package managers:

```
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
```

Caching then works as expected. I'm reluctant to put in a PR as I'm not certain if this is the preferred solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@recumbent Thank you for your contribution. The updated version will go live shortly
