### ISSUE TITLE
Feedback of a frustrated developer who just wants to connect to a TFS that works fine

### ISSUE THREAD

**Issue by eagle275** [MicrosoftDocs/azure-devops-docs#10112]
You've made everything overly complicated ... 

we have a simple TFS - I work as local admin for obvious reasons (WCF, folder access) ... so I simply want to connect to that existing TFS . I can even call the TFS-address in my browser - get asked for my credentials and see the project(s) of my company .. 
it could be sooo simple - alas even after setting devenv with my credentials .. I get told that VS2019 cant connect to said TFS (404 error ?? wtf ? - works in a simple web browser) and likewise VS for some mysterious reason doesnt offer to change / enter credentials JUST THERE ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35ee2378-8f25-6502-f86b-d4cae72366b7
* Version Independent ID: 811378aa-c2f2-c287-5a8e-afa8f95c48d6
* Content: [Connect to project from browser/supported client - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/connect-to-projects?view=azure-devops&tabs=visual-studio-2019)
* Content Source: [docs/organizations/projects/connect-to-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/connect-to-projects.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@eagle275 It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
