### ISSUE TITLE
Azure Git Repo vs GitHub Repo

### ISSUE THREAD

**Issue by abby-d** [MicrosoftDocs/azure-devops-docs#10129]
Can you clarify more clearly in the documentation that only Azure Git repos can be published to the Azure DevOps Wiki (if that's the case)? I think it would help to specifically call out that GitHub Repos cannot be published to the Azure Wiki. This is a question I have only been able to answer by reading between the lines of existing documentation and making some assumptions.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than 3/21 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
