### ISSUE TITLE
Version selector

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/azure-devops-docs#10131]
The product/version selector is no longer available in the current version of the docs.microsoft.com pages. So it would appear that the following section should be removed:

![image](https://user-images.githubusercontent.com/1765732/106930930-f1239500-66ca-11eb-9236-674162958ccc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@VitalyMCT - Thank you for your input. However, the version selector is still in operation. May I ask what browser you are using? Perhaps you could take a screenshot for us to troubleshoot. Here is the version selector I'm seeing for this article. 
![image](https://user-images.githubusercontent.com/10856840/106946839-7c5a5600-66de-11eb-9d6d-3a42fecad52e.png)

**Comment by VitalyMCT** [comment]
Sorry, my mistake! I am used to the selector being on the main page and missed that it's now on the TOC side. Please disregard.

**Comment by KathrynEE** [comment]
@VitalyMCT  - Not a problem. Closing issue.
