### ISSUE TITLE
A link to file matching patterns would be helpful for the -projects parameter.

### ISSUE THREAD

**Issue by jmaxson-ms** [MicrosoftDocs/azure-devops-docs#10130]
The documentation on this parameter provides a single example, but no link to the documentation on file matching patterns. I had to track that down separately, wasting a bunch of time.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by pulkitaggarwl** [comment]
@TimShererWithAquent I have approved the PR #2768 referenced above. Please help with merging of the PR and resolving this issue

**Comment by TimShererWithAquent** [comment]
@pulkitaggarwl Done! Thanks for your help -
