### ISSUE TITLE
Must have Basic Access Level in order to Edit the Project Wiki

### ISSUE THREAD

**Issue by successhawk** [MicrosoftDocs/azure-devops-docs#10138]
[Enter feedback here]

Prerequisites section needs to mention Basic access level.  I assume you need Basic to create the project wiki, and I know that you need it in order to modify the Project wiki, including add, edit, reorder, rename wiki pages.

Current content below:
```
You must have a team project. If you don't have a team project yet, create one in Azure DevOps.
You must have the permission Create Repository to publish code as wiki. By default, this permissions is set for members of the Project Administrators group.
Anyone who is a member of the Contributors security group can add or edit wiki pages. Anyone with access to the team project, including stakeholders, can view the wiki.

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973bb49c-7fcb-a953-21ff-82b03f899e73
* Version Independent ID: 507b2d8b-9560-9afb-4628-ae562832c7ce
* Content: [Create a project wiki to share information - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/wiki-create-repo.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-create-repo.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @successhawk, Thanks for bringing this to our attention. I've created a user story to address this. Once the update is published, this issue will automatically close. You can always @mention me if you have any further feedback or questions. Thanks again!
