### ISSUE TITLE
Basic Access Level is a pre-requisite for editing the Project Wiki

### ISSUE THREAD

**Issue by successhawk** [MicrosoftDocs/azure-devops-docs#10133]
Need to add the following to Pre-Requisites section:

**Must have Basic Access Level in order to edit the Project Wiki.**

![image](https://user-images.githubusercontent.com/3745327/106954537-f2bc7f80-6701-11eb-9c0d-663653b8aba8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder, manage wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops&tabs=browser#prerequisites)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback @successhawk, I've updated the article. Have a great day!
