### ISSUE TITLE
Broken link to the Azure DevOps .NET SDK API Reference

### ISSUE THREAD

**Issue by denious** [MicrosoftDocs/azure-devops-docs#10139]
The page linked in the issue contains the following text:

> **Reference**
> You can find detailed, up-to-date reference documentation in the Azure DevOps .NET SDK API Reference browser.

The link does not work and instead auto-redirects to the .NET API browser.
Where do I get the documentation for the client libraries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley I can't tell what the link is supposed to point to.

**Comment by chcomley** [comment]
I've updated the article, thanks for your feedback @denious. The .NET SDK for Azure DevOps is here: https://github.com/MicrosoftDocs/azure-devops-docs-sdk-dotnet
