### ISSUE TITLE
sirlei

### ISSUE THREAD

**Issue by Sirleid** [MicrosoftDocs/azure-devops-docs#10140]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5c6203e4-5a94-d265-783e-8525051324b5
* Version Independent ID: f03c2d8e-aa65-611c-b404-316b7e47ff47
* Content: [Enable Kanban board badge status for GitHub repo - Azure Boards](https://docs.microsoft.com/pt-br/azure/devops/boards/github/configure-status-badges?view=azure-devops)
* Content Source: [docs/boards/github/configure-status-badges.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/configure-status-badges.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@sirlei  Thank you for contacting **Microsoft Docs**.  

Please provide further context below and we can assign this to an author for further review.
