### ISSUE TITLE
Small spelling error in article, looka instead of looks

### ISSUE THREAD

**Issue by Tyfui90** [MicrosoftDocs/azure-devops-docs#10148]
Spelling mistake at the bottom of the page in the Notes section, 'looka' written instead of 'looks'
"Note
Don't copy/paste @mention users from a previous comment. While the resulting formatting _**looka**_ identical to a properly entered mention, it doesn't register as a true mention nor send an email notification."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Tyfui90, Thanks so much for the heads up! This fix will be published sometime today. Thanks again! Also, please consider [becoming a contributor](https://docs.microsoft.com/en-us/contribute/) to our docs!
