### ISSUE TITLE
Call attention to Personal access token expiration (inactive case)

### ISSUE THREAD

**Issue by ToruMakabe** [MicrosoftDocs/azure-devops-docs#10143]
Not only PAT expiration itself but also PAT auth fails after 90 days without using PAT. Due to failure to obtain an access token of identity on Azure AD as auth backend.

[Referenece](https://rajbos.github.io/blog/2020/08/07/ADAL-error-Azure-DevOps)

If we have non-frequent jobs such as making a semi-annual report, the jobs should fail. So, we have to log in or do something with auth periodically to avoid auth failure (or pre-auth with az devops login command). I think almost all users are unaware of Azure AD and OAuth's existence as an auth backend of PAT. I cannot find an article related to it.

Could you please call attention to this issue on this doc? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
hI @ToruMakabe, Thanks so much for this feedback. I've started a PR. Once this update goes live, this issue will automatically close. Thanks again!
