### ISSUE TITLE
Another step needed: upgrade the VMSS Instances

### ISSUE THREAD

**Issue by HoussemDellai** [MicrosoftDocs/azure-devops-docs#10149]
[Enter feedback here]
I followed the same steps, but couldn't get the Azure DevOps to connect to the agent.
In the Azure portal, there is a ⚠ icon saying there is an upgrade available.
I upgraded the VMSS instances, and then I got the agents shown in my devops dashboard.
I think you should mention this in the documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@HoussemDellai Was the VMSS previously existing in the Azure Portal with VMs that were used outside of Scale Set Agents? That would be one scenario that could cause the issue that you were seeing. I am looking into this.

**Comment by HoussemDellai** [comment]
Hello Steve. That happened with a new VMSS.
I did the same steps yesterday and I didn't got that warning on the Azure portal. It worked fine.
May be that happens only when an update is available after VMSS creation ?
