### ISSUE TITLE
New GIT stuff in 16.8 limited!

### ISSUE THREAD

**Issue by Seabizkit** [MicrosoftDocs/azure-devops-docs#10156]
[Enter feedback here]

I am really disliking the changes in 2019 ( 16.8) with regards to GIT

**How to you do rebase a branch in the newest version?**

This really is a step backwards and is not the only thing which has changed and is now either not there or make no sense... and it is highly annoying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf2704e-ef04-e4ab-88ba-48533fa62d21
* Version Independent ID: e59a9067-775b-d9df-94b7-29076dbfbf25
* Content: [Update your branch history with rebase - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/rebase?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/rebase.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/rebase.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by Seabizkit** [comment]
I much preferred the "older" way pre (16.8), it was so much easier, and quicker to get stuff down. could we not have the best of both!, please i really feel like this is a step backwards

**This is specially to the GIT options  in the Team Explorer**

**Comment by TimShererWithAquent** [comment]
@Seabizkit Thanks for your feedback! It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug](https://developercommunity.visualstudio.com/search?space=21) here.

**Comment by Seabizkit** [comment]
well i can say that it was all fixed which is great. 16.10.2 maybe have been one release before this. but its all working again, so thanks
