### ISSUE TITLE
DevOps Artifacts, NuGet Feed, and PowerShell

### ISSUE THREAD

**Issue by silbermano** [MicrosoftDocs/azure-devops-docs#10154]
the described procedure does not work, as NuGet API is now V3. PowerShell has problem with those versions:

**- V3 cannot be registered**
_Register-PSRepository -Name "PowershellAzureDevopsServices" -SourceLocation $artifactFeed -PublishLocation $artifactFeed -InstallationPolicy Trusted -Credential $credsAzureDevopsServices
Register-PSRepository: The specified Uri 'https://pkgs.dev.azure.com/<orgname>/_packaging/<project name>/nuget/v3' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements._

**- V2 cannot be resolved**
_Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to resolve package source 'https://pkgs.dev.azure.com/osipowershell/_packaging/osipowershell/nuget/v2'._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@silbermano It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
