### ISSUE TITLE
Documentation mistake, says "left side" but should say "right side"

### ISSUE THREAD

**Issue by jpickardsqr** [MicrosoftDocs/azure-devops-docs#10167]
The docs say:
> Click the pool on the left side of the page and then click Security.

The pools are actually shown on the right side of the page. The "settings" links are all on the left.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64ca92c-b7d5-3142-71fb-306d32a37281
* Version Independent ID: dfef40cf-2f50-4c03-bc97-bafa6c305108
* Content: [Deploy an Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@jpickardsqr Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
