### ISSUE TITLE
Pipeline source must be quoted if it contains whitespace

### ISSUE THREAD

**Issue by michaelelleby** [MicrosoftDocs/azure-devops-docs#10163]
The `source` property only works if the value is in quotes, when the name of the pipeline being referenced contains whitespace. This should be mentioned in documentation, because in most other places in the YAML file whitespace is tolerated as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@michaelelleby Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by steved0x** [comment]
@michaelelleby Thank you for letting us know. I am having trouble getting my test pipelines to work when there is a space in the name, can you share the repo name and the pipeline name of the triggering source repo (does the pipeline have the same name as the repo? this is the defaut), and whether you used single or double quotes in the target repo tat has the pipeline completion trigger?
