### ISSUE TITLE
Pipeline parameters not the same as template parameters

### ISSUE THREAD

**Issue by joshuapoq** [MicrosoftDocs/azure-devops-docs#10169]
The [Pipeline parameter section](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Ctemplate-example#parameters) should not mention they can be used in templates as they are functionally different in terms of usage.

I am looking for a way to template the **queue-time pipeline parameters** from a different repository. This document makes this misleading. As far as I can tell there is no way to do this because template parameters are specific to templates and so are unable to be presented at queue-time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by joshuapoq** [comment]
I think this is linked to https://github.com/MicrosoftDocs/azure-devops-docs/issues/9964.

**Comment by msebolt** [comment]
@joshuapoq Thank you for the update, please refer to https://github.com/MicrosoftDocs/azure-devops-docs/issues/9964 for further updates.

Closing this issue now.
