### ISSUE TITLE
LabelPosition is deprecated and has no effect in Azure DevOps Server 2020

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#10166]
In the section "Control element syntax" it reads:

```
<Control FieldName="FieldRefName" Type="DateTimeControl | FieldControl | 
HtmlFieldControl | LabelControl | WebpageControl&quot; Label="LabelText" 
LabelPosition="Top | Bottom | Left | Right" EmptyText="TextString" 
ReadOnly="True | False" Name="InstanceName" [Visible="false" | 
FieldName="ReplacementFieldRefName" Replaces="FieldRefName"] />
```

... which includes the `LabelPosition` attributes. That attribute is deprecated and ignored (see above) so we might want to remove if from the syntax for clarity.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04252798-9384-dd6c-ca58-b16ab8a8c5eb
* Version Independent ID: f9244f2b-c55d-c621-a16b-af848d0febef
* Content: [WebLayout XML elements reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/weblayout-xml-elements?view=azure-devops-2020)
* Content Source: [docs/reference/xml/weblayout-xml-elements.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/weblayout-xml-elements.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NenoLoje  - Thank you for the feedback. I'll take a look at this and update as needed.
