### ISSUE TITLE
Docker Cache Example Configuration Fails

### ISSUE THREAD

**Issue by derekrprice** [MicrosoftDocs/azure-devops-docs#10164]
The example docker cache configuration fails with a `file not found "caching-docker.yml"` error and I can't find any reference to that file name on the internet except on this page.  It requires, at the least, further explanation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#phpcomposer)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@derekrprice Thanks for the feedback! The updated content will go live shortly.
