### ISSUE TITLE
Documentation not up to date with version 5 of the task, and missing the pwsh parameter.

### ISSUE THREAD

**Issue by bowlerma** [MicrosoftDocs/azure-devops-docs#10175]
The documentation for the Azure PowerShell Task is not up to date with the latest version, version 5, of the task.

Documentation around the 'pwsh' parameter is missing, specifically that this must be set to 'true' if you wish to use PowerShell 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
The merged PR above addresses this issue.
