### ISSUE TITLE
Has any page explain the difference between parameter and variable?

### ISSUE THREAD

**Issue by dreaminzero-cell** [MicrosoftDocs/azure-devops-docs#10171]
FYI

**Comment by TimShererWithAquent** [comment]
@juliakm Assigning to you per discussion with @mijacobs.

**Comment by juliakm** [comment]
@dreaminzero-cell [Parameters](https://docs.microsoft.com/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script) are useful when you want to use data types and templates. They are only available when a template gets parsed so you should use variables if you need a value that is set during runtime.  

You may find these articles helpful. 
- [How to securely use variables and parameters in your pipeline](https://docs.microsoft.com/azure/devops/pipelines/security/inputs?view=azure-devops)
- [Runtime parameters](https://docs.microsoft.com/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#faq)
