### ISSUE TITLE
Document that ARM-based storage is broken and will not be fixed

### ISSUE THREAD

**Issue by scottcurrie** [MicrosoftDocs/azure-devops-docs#10182]
It should be documented that the following options don't actually work and should not be used:

- EnableAdvancedStorageOptions
- ARMConnectedServiceName
- ARMStorageAccount

See this issue for confirmation of the issue and Microsoft's decision to not fix it:

https://github.com/microsoft/azure-pipelines-tasks/issues/12766

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dfb5572-2d35-01cb-28c3-8cdffe823613
* Version Independent ID: 6675c176-2e40-3172-4daf-e72f15be0f8c
* Content: [Azure Cloud Service Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cloud-powershell-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cloud-powershell-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cloud-powershell-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by DaleyKD** [comment]
Any update on this? I've been fighting the old (might as well be deprecated) [Azure Cloud Service deployment](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCloudPowerShellDeploymentV1) task. It has a checkbox to support ARM Storage Accounts, but the task will fail if you try to use this. The source code tries to allow for it, but it fails.

**Comment by stateofgithub** [comment]
We ran into this, wasted a bunch of time because Microsoft never went back to remove or leave notes on the broken functionality.

**Comment by CVET-TJGutjahr** [comment]
Same> 'Please upgrade everything at the same time, thanks!' -Microsoft, probably.

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
