### ISSUE TITLE
阳光大道

### ISSUE THREAD

**Issue by pyg123456** [MicrosoftDocs/azure-devops-docs#10183]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b10281-bec5-1510-635f-57705972fb58
* Version Independent ID: 98d26279-c7af-85a2-24c0-9bffd8962842
* Content: [Sign up, sign in, invite teammates - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops)
* Content Source: [docs/user-guide/sign-up-invite-teammates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/sign-up-invite-teammates.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@pyg123456 Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
