### ISSUE TITLE
Link to site that is not used any longer

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#10191]
On this page, there's a link labeled "see the Azure data center map."

It navigates to: https://azuredatacentermap.azurewebsites.net/

That page is deprecated:

> As of November, 2020 this page is no longer in use and is not being updated. Customers should refer to Data Residency in Azure for the applicable information.

Let's replace this link with an updated site.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe4c7a5f-322f-2c35-bbd7-14db2aee8144
* Version Independent ID: 52442a88-9e7c-b50d-4643-23ed10a3d7c3
* Content: [Azure DevOps - data location - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/organizations/security/data-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/data-location.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @NenoLoje, I've created a user story to address this. This issue will automatically close when the change is published. Thank you!
