### ISSUE TITLE
Unclear what the different VS extension metrics refer to

### ISSUE THREAD

**Issue by mcollum1** [MicrosoftDocs/azure-devops-docs#10195]
Hello,

I am trying to better understand what the metrics refer to for the VS extension metrics. I can see the reporting page that provides acquisition. 

![Screen Shot 2021-02-12 at 1 28 00 PM](https://user-images.githubusercontent.com/49844116/107807746-92979000-6d36-11eb-9e16-a54da8e7bfbe.jpg)

I understand page views and I understand installs and reviews. 
It is not clear what total acquisition is (how is that number higher than installs? does that mean people have uninstalled?) Also what is till date? It's hard to understand why total acquisition, till date, and # of installs are all different. 
Also, is there a way to track uninstalls? 

Please help. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efabb28f-dde3-6955-f5b2-d43e28318fe2
* Version Independent ID: 9e456835-9faa-0434-bd51-b85c42e37bf2
* Content: [Extension Report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/extension-report?view=azure-devops#feedback)
* Content Source: [docs/extend/extension-report.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/extension-report.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by mcollum1** [comment]
Hi @chcomley I just wanted to follow up and see if there was any information available for this. We're having a really tough time figuring out what these metrics are telling us, but we know they are important. Thanks!

**Comment by chcomley** [comment]
Adding @jtpetty for input. Thanks!

**Comment by mcollum1** [comment]
Hi @jtpetty - I just wanted to follow up and see if there was any information available for this. We're having a really tough time figuring out what these metrics are telling us, but we know they are important. Thanks!

**Comment by jtpetty** [comment]
I am not familiar with those metrics. Adding @xavierdecoster for guidance.

**Comment by chcomley** [comment]
Hi there, if this is still an issue, to get some traction and timely feedback, your best route would be to report a problem in the [Developer Community](https://developercommunity.visualstudio.com/search?space=21). I'm sorry we weren't more helpful. If you feel the doc needs an update once you've engaged with Dev, we invite you to help us out and become a [contributor to our docs please](https://developercommunity.visualstudio.com/search?space=21)! Thank you.
