### ISSUE TITLE
Service Hooks ip addresses not working with Azure Storage Queue restrictions

### ISSUE THREAD

**Issue by PekkaJalonen** [MicrosoftDocs/azure-devops-docs#10193]
Based on the documentation, "Azure DevOps Services connecting to endpoints for Service Hooks" is listed under the Inbound connections. When we listed all of those addresses to Azure Storage Networking Firewall list, we get "Not Authorized" when testing connection to put message to storage queue. When allowing access from All networks in storage, the connection works. So this list or documentation has to be incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @PekkaJalonen, I wanted to give you an update on this, sorry for the delay, but I've engaged a PM and am awaiting feedback. Please stay tuned. Thanks so much for reaching out.

**Comment by chcomley** [comment]
I've updated the article. This issue will automatically close, once the PR closes. Here's a link to some more information that might be helpful, thank you! [Configure Azure Storage firewalls and virtual networks](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?toc=%2Fazure%2Fvirtual-network%2Ftoc.json&tabs=azure-portal)
