### ISSUE TITLE
token to base64 from linux terminal

### ISSUE THREAD

**Issue by NikolaDojic** [MicrosoftDocs/azure-devops-docs#10192]
this is a command for encoding plain string, in this case, personal access token to a base64.

`echo [PERSONAL_ACCESS_TOKEN] | base64`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c25888-f381-be7f-2673-62621fe80da2
* Version Independent ID: 3072da06-79cb-773a-f784-045babd04568
* Content: [Use npm to store JavaScript packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/get-started-npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-npm.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@NikolaDojic Thank you for your feedback. That command is already in the article ```echo -n "YOUR_PAT_GOES_HERE" | base64``` -n is to not print the trailing newline.

**Comment by NikolaDojic** [comment]
The command is in the article, but it just says "Mac" where it should be "Mac and Linux".
