### ISSUE TITLE
Ability to restore conditional on deletion mechanism?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/azure-devops-docs#10190]
> A project can only be restored if it was deleted from the Web or REST API.

I think this limitation needs to be expanded on for clarification. 

The statement seems to imply that projects deleted via some mechanisms cannot be restored. If so, what are these mechanisms? 

For example, the implication seems to be that projects deleted via the standard ADO Web UI cannot be restored. Is that true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b1cf79-de4e-500b-388a-64665e3af89b
* Version Independent ID: 2cdda8ac-9e42-eed7-8d0c-9ab8dfc2c5f8
* Content: [Restore a project - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/restore-project?view=azure-devops)
* Content Source: [docs/organizations/projects/restore-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/restore-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @VitalyMCT, Thanks for bringing this to our attention. I agree that it implies that there's another way to delete a project, which isn't the case, as I understand it. Once my PR is merged, this issue will automatically be closed. Thanks again.
