### ISSUE TITLE
Suggestion: Remove runtime expression syntax from example for macro syntax

### ISSUE THREAD

**Issue by seqdan** [MicrosoftDocs/azure-devops-docs#10203]
The example for macro syntax variables is awesome: It explains how to use variables in bash, powershell and and script tasks in a very simple way. In my opinion, it would be a little bit easier to understand if the various variable types were not mixed across the examples. I therefore suggest to remove the runtime expression syntax from this particular example. A static value would do perfectly fine here:

![image](https://user-images.githubusercontent.com/56939361/107997882-bdd8f280-7048-11eb-816e-b4c88c2b47b3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@seqdan Thanks! I appreciate your help making this article easier to understand. The article will be updated shortly.
