### ISSUE TITLE
clone wiki no longer exists

### ISSUE THREAD

**Issue by end-user** [MicrosoftDocs/azure-devops-docs#10208]
The instructions reference a "clone wiki" option in the menu that no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172eecd7-1a6b-30d0-96c0-fa6ae56b521c
* Version Independent ID: adc2c741-a41f-68d9-cdaf-dac696e68b9f
* Content: [Clone and update wiki content offline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-update-offline?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-update-offline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-update-offline.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley - I found a **Clone wiki** option after selecting the Wiki menu item, not immediately after selecting a project. The procedure implies that it's right there after you select the project.

**Comment by chcomley** [comment]
#sign-off
