### ISSUE TITLE
Suggestion: Clarify "Variables"

### ISSUE THREAD

**Issue by seqdan** [MicrosoftDocs/azure-devops-docs#10204]
On a page where different types of variables and their differences are explained, it would be desired to have the word "variables" not standing without further specification in a sentence like this one:

![image](https://user-images.githubusercontent.com/56939361/107998178-68e9ac00-7049-11eb-9cea-9b1962ae507e.png)

The current situation results in a potentially ambiguous understanding of the documentation:

- Maybe the note applies to all kinds of variables. In this case it should not be placed under the headline "Macro syntax variables", but preferably at a higher level in the document structure instead.
- Maybe the note applies to Macro syntax variables only. In this case the word "Variables" is confusing and should be more specific.

I suggest to either write "all types of variables" or be more specific, like "Macro syntax variables", depending on what the actual functionality of the application is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I believe that this applies to all variables but will confirm with the product team.
