### ISSUE TITLE
Inconsistent information regarding wildcard in paths

### ISSUE THREAD

**Issue by SebastianClaesson** [MicrosoftDocs/azure-devops-docs#10212]
In the Tips section of "Paths" it says:
"Wild cards are not supported with path filters."

However in the Wildcard section is says:
"For paths:
You may include * as the final character, but it doesn't do anything differently from specifying the directory name by itself.
You may not include * in the middle of a path filter, and you may not use ?"

Which information is correct?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x Hi Steve - Not sure whether these two pieces of information are truly at odds, but I could see possible confusion.

**Comment by ahaleiii** [comment]
I agree that this information is inconsistent and confusing, and would like to see clarification.

Specifically, when including a directory as a path filter, what should the standard way be to include that?
```yaml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'my_dir'
    - 'my_dir/'
    - 'my_dir/*'
```

When I do option 2 in VS Code, it says there is a problem:
`String does not match the pattern of "^[^\/~\^\: \[\]\\]+(\/[^\/~\^\: \[\]\\]+)*$".`

The [#paths](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths) section uses option 1 as its example.

The [#wildcards](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#wildcards) section uses option 3 as its example, but says it is the same as option 2.

**Comment by Slooz** [comment]
Related: https://github.com/microsoft/azure-pipelines-vscode/issues/372
