### ISSUE TITLE
No content about how to pause and resume a test in Test Runner

### ISSUE THREAD

**Issue by raydixon** [MicrosoftDocs/azure-devops-docs#10214]
In [Run tests for web apps](https://docs.microsoft.com/en-us/azure/devops/test/run-manual-tests?view=azure-devops#run-tests-for-web-apps), step 7 says the following:

When you've run all your tests, save the results and close Test Runner. All the test results are stored in Azure DevOps. [How do I resume testing, or run one or more tests again?](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#qanda)

That link takes you to a FAQ question about how to rerun a test, but doesn't say anything about how to pause and resume tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20ab28c-41a4-9fde-b8fb-ab814e0295b3
* Version Independent ID: a479d74e-9b8b-6bb0-407a-1ba07edd1b9b
* Content: [Run manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-manual-tests?view=azure-devops)
* Content Source: [docs/test/run-manual-tests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/run-manual-tests.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x There's nothing about "pause" or "resume" in the article or FAQ that it links to.
