### ISSUE TITLE
OverrideParameters example - AzureResourceGroupDeployment@2

### ISSUE THREAD

**Issue by rbabbar-agl** [MicrosoftDocs/azure-devops-docs#10220]
There is a space after colon ":" which makes the yaml invalid. Remove that space and it works. 
overrideparameters
-options ["option1"] -map {"key1": "value1" }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@RoopeshNair Roopesh, there are a couple of instances of key value pairs separated by colons with a space. The one mentioned above is the only code (the others are explanatory). I don't know whether you want to change them all for consistency.
