### ISSUE TITLE
Environment tags syntax not valid

### ISSUE THREAD

**Issue by nimro** [MicrosoftDocs/azure-devops-docs#10225]
The Environment section describes the syntax as follows:

```
environment:                # create environment and/or record deployments
  name: string              # name of the environment to run this job on.
  resourceName: string      # name of the resource in the environment to record the deployments against
  resourceId: number        # resource identifier
  resourceType: string      # type of the resource you want to target. Supported types - virtualMachine, Kubernetes
  tags: string | [ string ] # tag names to filter the resources in the environment
strategy:                 # deployment strategy
  runOnce:                # default strategy
    deploy:
      steps:
      - script: echo Hello world
```

Noe the "tags" line defines either a single string or an array of strings as valid. However, when defining an array of strings in an actual pipeline, the following warning is received:

`Incorrect type. Expected "string".`

Is the documentation wrong or is it the YAML parser that needs to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#environment)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x Steve - Can you take a look at this? I looked at the article, but can't verify whether this is a parser issue or what.

**Comment by bensgroi** [comment]
I've encountered this as well. I'm getting the "A sequence was not expected", so the docs appear to be inconsistent with the actual behavior. That said, I would hope to able to use arrays of strings here in the future.
