### ISSUE TITLE
Missing IP Range?

### ISSUE THREAD

**Issue by wshaddix** [MicrosoftDocs/azure-devops-docs#10226]
I am trying to allow Azure DevOps source ip ranges so that my build pipeline can access internal Sonarqube resource. I believe my DevOps pipeline agent is coming from 52.138.100.255. That IP range is not listed in the docs. Am I missing something? Looking at the wrong doc maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley I don't see that address falling in any of the ranges in this doc. Is it possible the lists are out of date?

**Comment by wshaddix** [comment]
Any idea on an eta for feedback on this? My company just wants assurance that we're opening up our network to a legitimate Microsoft ip address/range before we move forward.

**Comment by chcomley** [comment]
Hi @wshaddix, I've followed up with the PM and will get back to you ASAP. Thanks

**Comment by chcomley** [comment]
Hi @wshaddix, Pipeline agents aren't covered in our ranges. If you need to control the agent IP, we recommend [Azure virtual machine scale set agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops). Thank you!
