### ISSUE TITLE
JUnit: incorrect mapping according to XSD-schema

### ISSUE THREAD

**Issue by uas-divis** [MicrosoftDocs/azure-devops-docs#10246]
According to the linked [JUnit schema](https://raw.githubusercontent.com/windyroad/JUnit-Schema/master/JUnit.xsd) `system-out` is under `/Testsuites/testsuite/system-out` and not `/Testsuites/testsuite/testcase/system-out` which this page states under the section `Result formats mapping`.

Also the console log (`system-out`) does not seam to appear in Azure DevOps (see screenshot bellow) when using the `system-out` under `testsuite` specified by the schema. Am I missing something?
![image](https://user-images.githubusercontent.com/75643904/108982554-37e32a00-768e-11eb-87dc-acbdaefa81cb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@shashban Can you take a look? I looked at the json file and system-out was where @uas-divis described it, although this article has different versions, so I'm not sure I was looking in the right place.
