### ISSUE TITLE
Link to white paper on how to Mitigate Risk When Using Private Package Feeds

### ISSUE THREAD

**Issue by vatsan-madhavan** [MicrosoftDocs/azure-devops-docs#10249]
In the related articles list, we should probably link to https://aka.ms/pkg-sec-wp

**Comment by TimShererWithAquent** [comment]
@vatsan-madhavan Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by vatsan-madhavan** [comment]
Sorry about not realizing the source page wasn't linked when the issue got opened - this is the page I meant to open this issue against: https://github.com/MicrosoftDocs/azure-devops-docs/blob/cc9f6dab9520f6110e4466dab7a939b399626742/docs/pipelines/packages/nuget-restore.md

**Comment by ramiMSFT** [comment]
@vatsan-madhavan Thank you for your feedback!
