### ISSUE TITLE
Update Azure Powershell commands

### ISSUE THREAD

**Issue by dtupy** [MicrosoftDocs/azure-devops-docs#10254]
Page URL: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/automate-terraform?view=azure-devops

When copying the storage account key you provide outdated CLI commands (Get-AzureRmStorageAccountKey) it should be Get-AzStorageAccountKey

**Comment by TimShererWithAquent** [comment]
Fixing in this PR: MicrosoftDocs/azure-devops-docs-pr/pull/2844

Will close when it is merged.
