### ISSUE TITLE
Container resource doc missing options

### ISSUE THREAD

**Issue by Sefiris** [MicrosoftDocs/azure-devops-docs#10250]
I'm not sure when this was added but container resources(within pipelines) CMD can be overridden/added to, the docs however do not reflect this. After a couple of hours of trying to find a workaround for this we just decided to try out adding `command: [CMD ARGS]` to the container resource and it seemed to function perfectly fine looking at the docker create command that came out of it.

specific YAML example I am talking about can be found [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-containers)

Our working example in Azure Devops Server 2020 below:

```yaml
  # Include Atmoz Sftp container
  - container: atmozsftp
    image: atmoz/sftp:latest
    options: --tmpfs /var/lib/atmoz:rw
    command: foo:pass:1001
```

since this is a fairly well-used part of the docker run/create commands for these types of service containers I'm hoping I can save somebody else the hours of the headache of something not existing when it actually does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#faq)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@Sefiris  I've checked with the product team and there is no support for `command`. They expect that anything passed to `command` will be ignored by the task.

**Comment by Sefiris** [comment]
I have to reiterate then that for our current version of Azure DevOps Server 2020 on-premise the above example is a perfect test case, it will only work with the `command` defined. if needed on Monday I can even show agent logs that the `command:` argument is not ignored. it was quite literally the only thing stopping our integration testing pipeline from failing.

**Comment by juliakm** [comment]
Thanks @Sefiris. Flagging this for @vijayma.
