### ISSUE TITLE
Confusing and mismatched terms

### ISSUE THREAD

**Issue by bartsipes** [MicrosoftDocs/azure-devops-docs#10252]
The title on the left nav bar of this page is "Set up GitHub SourceLinking" but the title at the top of the page itself is "Use Index Sources & Publish Symbols task to publish your symbols".

Next, there is no clear distinction between SourceLinking and Symbol Server. Are those the same thing? Is SourceLinking the cloud based version of Symbol Server? What is the difference between them? Also, under the "Set up Visual Studio" section, step 4 says to check "Enable Source Link support". What about "Enable source server support" which is shows as already checked? Is that needed too? Why are there both options now?

Finally, under "Using Source Link in .NET projects" it gives snippets for projects hosted on GitHub and projects hosted on Azure Repos. What about Azure DevOps Server? Should the snippet for Azure Repos be used or should no snippet be used? This is not clear at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 454a2728-fe4c-5570-6c72-f8e4a615a77d
* Version Independent ID: 4c7cc7f3-9f97-8994-f370-1371931d28ec
* Content: [Publish symbols to Azure Artifacts symbol server - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/setting-up-github-sourcelinking?view=azure-devops)
* Content Source: [docs/artifacts/symbols/setting-up-github-sourcelinking.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/symbols/setting-up-github-sourcelinking.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@bartsipes Thank you for your feedback. [Source link](https://github.com/dotnet/sourcelink) is a set of packages to help with source debugging. Symbol servers are available with Azure Artifacts and are accessible by any user with access to the organization. 
Check **Enable source server support** to enable support for Windows PDB files on symbol servers, and check **Enable Source Link support** to enable support for portable PDB files. I added a section to set up Azure DevOps server projects.
