### ISSUE TITLE
azure key

### ISSUE THREAD

**Issue by TonyDJ59** [MicrosoftDocs/azure-devops-docs#10268]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* Content: [Authenticate with your Git repos - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops)
* Content Source: [docs/repos/git/auth-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/auth-overview.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by TimShererWithAquent** [comment]
Closing this for needs more info. Please at-mention me if you want to follow up on this issue.
