### ISSUE TITLE
Pages needs updating

### ISSUE THREAD

**Issue by rovin-ms** [MicrosoftDocs/azure-devops-docs#10265]
Several tools in this have been updated so this page should probably be updated also. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Canary deployment strategy for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@azooinmyluggage - I didn't see any specific version info from a quick look at this topic, but changes to the tools could change the procedure.

**Comment by azooinmyluggage** [comment]
The sample uses very basic features. Version should not matter.
