### ISSUE TITLE
General work item feature access - Permanently delete work items

### ISSUE THREAD

**Issue by seapeter** [MicrosoftDocs/azure-devops-docs#10275]
The documentation for Version 2019 of Azure DevOps under the General work item feature access section, it indicates that Team admins can permanently delete work items.  Can you verify this, as based on further reading and understanding of this permission, only Project-level admins have this set to allow.

https://docs.microsoft.com/en-us/azure/devops/boards/get-started/permissions-access-boards?view=azure-devops-2019#general-work-item-feature-access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3b3b65-bfe8-442f-c649-24c3157f0bc7
* Version Independent ID: caa7762c-6e14-4e5f-fa81-bfa2e1c85964
* Content: [Default work tracking permissions & access - Azure Boards & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access-work-tracking?view=azure-devops-2019)
* Content Source: [docs/organizations/security/permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@seapeter  - Thank you for your inquiry. You are correct, team admins don't have the delete work items permission by default. I will update the article accordingly.
