### ISSUE TITLE
Please document *not* to combine minimumExpectedTests and rerunFailedTests

### ISSUE THREAD

**Issue by 304NotModified** [MicrosoftDocs/azure-devops-docs#10277]
I noticed our build was very unstable. I found out after checking a strange result, if you combine 
rerunFailedTests with minimumExpectedTests (with more than 1), the whole thing fails if it needs the rerun 1 test.

I think this is bug, so also another user, but it's [closed as not a bug](https://developercommunity.visualstudio.com/t/Combination-of-rerun-tests-and-minimum-n/1236219) 

So please document this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by 304NotModified** [comment]
It's just documentation. Why is this taking ages? @shashban

**Comment by bormm** [comment]
This about documentation of a **bug** and even this is not working??

**Comment by 304NotModified** [comment]
IMO it's a but, but it's closed as not a bug.

https://developercommunity.visualstudio.com/t/Combination-of-rerun-tests-and-minimum-n/1236219

**Comment by eutychius** [comment]
@shashban For me this is also an issue, please fix or at least document.

**Comment by 304NotModified** [comment]
Sad
