### ISSUE TITLE
Customize @mention Email Text

### ISSUE THREAD

**Issue by ad1892** [MicrosoftDocs/azure-devops-docs#10279]
Is there any way to customise the text within these @mention emails? For searching/grouping purposes in outlook, it would be incredibly useful to have the Project Name and Work Item Title as a minimum in the Email subject/body. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@ad1892 Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
