### ISSUE TITLE
Typographical Error In The Page

### ISSUE THREAD

**Issue by usafowose** [MicrosoftDocs/azure-devops-docs#10281]
[The first paragraph of the docs on this page, it reads "In the end, you'll have a project the uses the Basic process for work tracking." which contains a typographical error. I believe the appropriate edition would be "In the end, you'll have a project that uses the Basic process for work tracking."]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c985016-9453-7c7f-bbbd-39252037b807
* Version Independent ID: ea8f7d65-dc88-d11d-4358-ac7b31a20827
* Content: [Start using Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops)
* Content Source: [docs/boards/get-started/sign-up-invite-teammates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/get-started/sign-up-invite-teammates.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@usafowose - thank you for the correction. Updating the article now.
