### ISSUE TITLE
Artifacts Documentation Suggests Unsecure Configuration of Upstreams

### ISSUE THREAD

**Issue by magleaso** [MicrosoftDocs/azure-devops-docs#10288]
On the upstream sources page under the 'order your upstream sources intentionally' heading (https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#order-your-upstream-sources-intentionally), "we recommend putting the public package managers first" in the case where there are mixed sources. This is contradicted by internal guidance and general security recommending that internal upstreams take precedence. Possibly this is moot with the new name-squatting protective upstream behavior.

**Comment by ramiMSFT** [comment]
@omokoh This is an older article, is this accurate?

**Comment by phil-hodgson** [comment]
With the introduction of the new upstream behavior, the public guidance seems good to me. The internal guidance should be updated to match.
