### ISSUE TITLE
url on page not working

### ISSUE THREAD

**Issue by RichieOpr** [MicrosoftDocs/azure-devops-docs#10282]
The link on this page : "Refining your Agile backlogs for success" is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdbe4c8-400b-0f3f-2214-4233a05c1752
* Version Independent ID: 4dafb9ad-de23-5d3c-130e-c1baa944ecb4
* Content: [Product and portfolio backlog best practices - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/best-practices-product-backlog?view=tfs-2018#refine)
* Content Source: [docs/boards/backlogs/best-practices-product-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/best-practices-product-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE I get a weird "access denied" message when I tested the link. You might consider removing the whole sentence, if people can get along without the external checklist.

**Comment by KathrynEE** [comment]
@RichieOpr - Thank you for the feedback. I'll be removing the link and republishing soon.
