### ISSUE TITLE
You can get the list of IP addresses for the Southeast Asia region by checking here?

### ISSUE THREAD

**Issue by edwardkuo** [MicrosoftDocs/azure-devops-docs#10307]
For this news "https://docs.microsoft.com/en-us/azure/devops/misc/migration?view=azure-devops"

I can't find any IP list for Southeast Asia region

**Comment by TimShererWithAquent** [comment]
@chcomley - Assigning to you because the page linked to is yours.

**Comment by chcomley** [comment]
Hi @edwardkuo, Southeast Asia (SEA) is not a supported geo yet. When we move out of East Asia, we will publish the IP addresses for SEA. Thank you.
