### ISSUE TITLE
Documentation for branch filter for pipeline resources is wrong

### ISSUE THREAD

**Issue by michaelelleby** [MicrosoftDocs/azure-devops-docs#10314]
> branch: string  # branch to pick the artifact, optional; defaults to all branches; Used only for manual or scheduled triggers

This is wrong. This filter is used for pipeline triggers as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by steved0x** [comment]
#reassign steved0x
