### ISSUE TITLE
Link to Docker Enterprise for Windows Server navigates to a 404

### ISSUE THREAD

**Issue by cytron201** [MicrosoftDocs/azure-devops-docs#10313]
The hyperlink under the section "https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#install-docker-for-windows" that should give more information installing Docker Enterprise edition redirects to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x This looks like a redirect at the Docker end. The link in the page is "https://docs.docker.com/install/windows/docker-ee"  which goes to "https://docs.mirantis.com/containers/v3.0/dockeree-products/mcr/dee-linux.html"
