### ISSUE TITLE
new example: bake Kustomize on build

### ISSUE THREAD

**Issue by yzorg** [MicrosoftDocs/azure-devops-docs#10319]
My devops team prefers we **bake** Kustomize on build, then store final YAML as a build artifact, download and deploy per environment.  A "full" example that includes these enterprise-y steps would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d0eccc-f436-7367-cb24-b6da66b3a049
* Version Independent ID: 9bc5ee0d-3f00-dc10-ad69-77effc928290
* Content: [Bake manifests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/bake?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/bake.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/kubernetes/bake.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@mlearned Not sure you're the right person for this, but the author is not coming up when I try to assign, even though I've assigned items to that person before.

**Comment by juliakm** [comment]
@yzorg I'm sorry for the delay in responding. We don't have docs on the scenario you describe but I've added it as a future idea. You might find this [article on Kubernetes canary deployments](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops&tabs=yaml) with a more detailed example helpful.
