### ISSUE TITLE
Link to "Work item query language (WIQL) syntax" is a 404

### ISSUE THREAD

**Issue by ferzkopp** [MicrosoftDocs/azure-devops-docs#10329]
On page
https://docs.microsoft.com/en-us/azure/devops/boards/queries/high-performing-queries?view=azure-devops
Link to "Work item query language (WIQL) syntax"
https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax.md
is a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c46b38-ba33-b411-1acf-d0a221349862
* Version Independent ID: e1136c17-154e-56e2-9eda-561cd00bcc93
* Content: [Learn how to create high-performing work item queries - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/high-performing-queries?view=azure-devops)
* Content Source: [docs/boards/queries/high-performing-queries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/high-performing-queries.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ferzkopp - Thank you for the feedback. I'll fix it today.
