### ISSUE TITLE
Move functionality not properly documented

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/azure-devops-docs#10325]
In your example for moving multiple items, you show a simplified dialog and provide no detailed explanation - this is the dialog you see when you want to move a single item. When I try the same thing, moving multiple items, if I select the same project but a different Area Path, the OK button is disabled with no explanation. The only thing I can seem to select is either to move to another project or to the existing location within the same project.

It is sadly another over-complicated implementation of something that should be much simpler. If a button is disabled, it needs to say why. I dn't understand why I can't move them to another area path/backlog and I don't want to move 50 items one-by-one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d7da26-5052-70ad-4b2a-7ccd2f02f012
* Version Independent ID: 7a0b1331-7ac9-9927-b96e-36c6f014391a
* Content: [Move work items, change work item type - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/move-change-type?view=azure-devops)
* Content Source: [docs/boards/backlogs/move-change-type.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/move-change-type.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@lukos - Thank you for your feedback. I can see that there are limitations that aren't documented. I'll work to update the article within the next few weeks.
