### ISSUE TITLE
Importing `Assigned To` field

### ISSUE THREAD

**Issue by CamyDee** [MicrosoftDocs/azure-devops-docs#10320]
Use of the "Assigned To" field deserves a little more detail - your example only shows empty cells.  If you don't put something that can be resolved immediately in the address book, the UI will hang at 100% while ostensibly importing the data. The correct format is what you can copy/paste from a resolved address book entry in Outlook, in this format:

`Cameron Stillion<camerost@microsoft.com>`

Anything else will hang the process with no hint as to what you might be doing wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Bulk import or update work items using CSV files - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@CamyDee - Thank you for the feedback. I'll update the article to provide greater clarity.
