### ISSUE TITLE
Documentation cleanup needed

### ISSUE THREAD

**Issue by pcarver** [MicrosoftDocs/azure-devops-docs#10326]
The Best Practices section of this document contains a lot of redundancy and also contradiction on the number of teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops&tabs=plans-preview)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pcarver - Thank you for the feedback. I'll update the article in the next few days to address the issues.
