### ISSUE TITLE
Updates to PowerShell Scripts

### ISSUE THREAD

**Issue by erikporter** [MicrosoftDocs/azure-devops-docs#10337]
This article should have the PowerShell scripts updated since the AzureRM and AzureRM.SQL Modules have been deprecated (for Az.Sql Module), and they don't work in Azure Pipelines (on my testing with the ubuntu-latest image) anyway.

The fix is to change the following calls:

New-AzureRmSqlServerFirewallRule -> New-AzSqlServerFirewallRule
Remove-AzureRmSqlServerFirewallRule -> Remove-AzSqlServerFirewallRule

I didn't test this since I was only trying to poke a whole in my SQL firewall for my build (using ARM), but I also believe you'll need to also change the follow:

Get-AzureSqlDatabaseServerFirewallRule -> Get-AzSqlServerFirewallRule

Thank you,
Erik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@erikporter Thanks for your input. We're looking into the issue.

**Comment by TimShererWithAquent** [comment]
@juliakm Thanks!

**Comment by juliakm** [comment]
I'm working on an update. For reference, this is the [depreciated code reference doc](https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/new-azurermsqlserverfirewallrule?view=azurermps-6.13.0) and this is the [current one](https://docs.microsoft.com/en-us/powershell/module/az.sql/new-azsqlserverfirewallrule?view=azps-5.6.0). Looks like `Get-AzureSqlDatabaseServerFirewallRule` in the same doc has already been updated.
