### ISSUE TITLE
Missing configuration information for yarn users

### ISSUE THREAD

**Issue by oscarmorasu** [MicrosoftDocs/azure-devops-docs#10339]
Although this instructions work ok, if you use yarn instead of npm you will get an error installing packages. In order to fix this you have to configure yarn by running this command:

``` sh
yarn config set registry "https://pkgs.dev.azure.com/<yourOrganization>/_packaging/<yourFeed>/npm/registry/"
``` 

I recommend including this information in this page and also in [this one](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops), since many organizations use yarn instead of npm

Hope that helps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c25888-f381-be7f-2673-62621fe80da2
* Version Independent ID: 3072da06-79cb-773a-f784-045babd04568
* Content: [Use npm to store JavaScript packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops)
* Content Source: [docs/artifacts/get-started-npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-npm.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@oscarmorasu Thank you for your feedback!
