### ISSUE TITLE
az pipelines: --output parameter used but not documented

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/azure-devops-docs#10345]
In the below mentioned page, all `az pipelines` command samples come with an `--output` argument. But that parameter is missing in the parameters list of those commands on the same page.

### Example

![Show pipeline](https://user-images.githubusercontent.com/9283914/111236658-b713b000-85f3-11eb-967d-1dfb27ebc5d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
--output is a global param in Azure CLI. 

@steved0x Maybe a link to this page about output formats: https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli 

This section has a tip I wrote when I revised this article recently: https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli#commands-in-a-subscription

**Comment by SetTrend** [comment]
Great idea!

My way lead me from learining Azure DevOps pipelines to Azure CLI, so that global parameter was something I wasn't aware of. So a brief hint would be very valuable, I guess.

**Comment by juliakm** [comment]
Thanks @TimShererWithAquent and @SetTrend! I'll push an updated article with Tim's tip shortly.
