### ISSUE TITLE
Project Configuration Location Is Wrong

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-devops-docs#10349]
In this section https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#open-project-settings-list-project-iterations

It says
> You define both areas and iterations for a project from the Project Settings > Boards > Project configuration.

In the "Browser" tab underneath it says:
> Define both areas and iterations for a project from the Project settings > **Work** > Project configuration.

The browser tab is listing the wrong information.
It is **Boards** not **Work**.
You can even see that from the screenshot below it in that section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044f4655-31fc-ef54-8d71-561d77447295
* Version Independent ID: 2c6dfd7c-3ca2-c63e-8010-d8d34aaf24f0
* Content: [Define iteration paths and configure team iterations - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/set-iteration-paths-sprints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-iteration-paths-sprints.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@opticyclic - Thank you for the feedback. I'll update the text so that it matches the screenshot.
