### ISSUE TITLE
Documentation incorrect. "Wiki security" option not available

### ISSUE THREAD

**Issue by tbergstedt** [MicrosoftDocs/azure-devops-docs#10348]
The documentation on how to set security for Azure DevOps wiki seems outdated. There is a reference to a "Wiki security" option under "More" for the wiki in question, but that is not available. The only options are "Rename  wiki" and "Unpublish wiki".
Using Azure DevOps Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley I see "Wiki security" when I look at a project. For the one that I was looking at, "Rename wiki" was grayed out. Does what you see depend on configuration or permissions?

**Comment by tbergstedt** [comment]
It seems it was permission-related. I was member of the "Project Administrators" group when checking, so I assumed that level to be sufficient. But when I inspected my access level to the project under "Organization Settings", it said "Custom Level". Applying "Project Administrator" access level to the project from there seems to have solved the problem.
