### ISSUE TITLE
"By default, users added to an organization can view all organization and project information and settings."

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/azure-devops-docs#10354]
When I add new users to the organization, they cannot see any projects by default. 
I have to add them as Readers or Contributors for each project before it shows up in their list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9a3085-d952-f4ba-e7c5-88e8ea7b3b29
* Version Independent ID: fb29b46c-3b07-ec11-f731-78c1371eef33
* Content: [Grant or restrict access to select features - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-access?view=azure-devops)
* Content Source: [docs/organizations/security/restrict-access.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/restrict-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tripleacoder - Thank you for your feedback. I'll clarify this information in the article.
