### ISSUE TITLE
Security for Wiki page lacks Add option

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/azure-devops-docs#10357]
My "Security for Wiki" page lacks the "Add" and shows only the "Inheritance" option. What am I missing? Documentation makes no mention of this scenario. Presumably something to do with permissions but my administrator indicates I have "full permissions" (whatever that means).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ScottWelker** [comment]
I've noticed that I am the only member of the Wiki's corresponding Azure DevOps "Project". That may be the issue. However I am not yet at liberty to add another member. When I do, I'll let you know if that enables the seemingly missing "Security for Wiki" page "Add" option.

**Comment by ScottWelker** [comment]
Adding another team member to my Azure DevOps "Project" made no difference, i.e. the "Security for Wiki" page still has no "Add", option, only the "inheritance" option. 

However, doing so suggests that I don't need to use this "Security for Wiki" page/screen. A bit confusing.

**Comment by chcomley** [comment]
Hi @ScottWelker Thanks for reaching out. I believe that this is more of a permissions issue, rather than documentation. Please ask your administrator to grant you the correct permissions so you can manage security for your wiki and add members. I'm going to close this issue, however if you feel an update should be made to the article, please don't hesitate to @mention me. Thank you!
