### ISSUE TITLE
Clarification on Collection-level Retention settings for Azure DevOps On-Prem

### ISSUE THREAD

**Issue by ppejovic** [MicrosoftDocs/azure-devops-docs#10355]
For Azure DevOps On-Prem (2020.0.1 in our case) there is no mention of what effect the Collection-level Retention settings have (accessed at `https://{your_server}/tfs/{collection_name}/_settings/buildqueue`). I *think* these settings are a relic of the XAML build system, but it would be good to clarify that either in the documentation or in the settings page itself as it's not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Retention policies for builds, releases, and test - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops-2020&tabs=yaml)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **rabououn**

**Comment by juliakm** [comment]
@ppejovic  Are these the settings you see?

![collection-retention-settings](https://user-images.githubusercontent.com/64906/120551420-016f2680-c3c4-11eb-9916-6477909ca15f.png)

**Comment by ppejovic** [comment]
That's correct @juliakm. Thanks.

**Comment by juliakm** [comment]
@ppejovic I've checked with the product team and non-yaml build pipelines can be configured with custom retention rules. This page governs the maximum values and the defaults. I'll add a note to the documentation.
