### ISSUE TITLE
Change Link To Track Bugs On Your Backlog

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-devops-docs#10353]
The section [here](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=azure-devops&tabs=agile-process#track-bugs-on-your-backlog) says:

>Track bugs on your backlog  
>  
> You can choose how you want to manage bugs. Some teams like to track bugs along with requirements on the backlog. Other teams like to track bugs as tasks performed in support of a requirement. The bugs then appear on their taskboard.  
>  
> Before deciding, review [Configure and customize, Treat bugs as requirements or tasks for guidance](https://docs.microsoft.com/en-us/azure/devops/boards/configure-customize?view=azure-devops).

Half way down that page you reach the section you are interested in
https://docs.microsoft.com/en-us/azure/devops/boards/configure-customize?view=azure-devops&tabs=agile-process#treat-bugs-as-requirements-or-tasks

This then links to another page.
You should just link directly to that page instead.

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/show-bugs-on-backlog?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8753a98e-77ca-265d-d5e3-91a4b1319e5e
* Version Independent ID: bed9697d-3bea-3202-0bf1-80f37aea0286
* Content: [Plan product backlog of stories, issues, & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=azure-devops&tabs=agile-process#open-your-backlog)
* Content Source: [docs/boards/backlogs/create-your-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/create-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@opticyclic - Thank you for the feedback. I'll add links to both articles. If you are new to customizing Azure Boards, it's useful to be aware of all the options.
