### ISSUE TITLE
Its Not Clear If This Is For Scrum, Agile Or Both

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-devops-docs#10351]
The page says:
> Your product backlog corresponds to your project plan, the roadmap for what your team plans to deliver. You create your product backlog by adding user stories, backlog items, or requirements. As shown in the following image, your backlog consists of a flat list of work items.

The screenshot shows "Backlog Items"

I don't have that in my view.
Is that because I am using the Agile process for my project?

If the view is different for Scrum and Agile then you need to highlight that the screenshot only applies to one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8753a98e-77ca-265d-d5e3-91a4b1319e5e
* Version Independent ID: bed9697d-3bea-3202-0bf1-80f37aea0286
* Content: [Plan product backlog of stories, issues, & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/create-your-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/create-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@opticyclic - Thank you for the feedback. The screenshot shown is for the Scrum process. I'll update the article to make that clear.
