### ISSUE TITLE
Missing the the scope(s) required to POST to `_apis/wit/attachments`.

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/azure-devops-docs#10358]
The doc is missing the the scope(s) required to POST to `_apis/wit/attachments`.

At best, this is covered under a vague catch-all statement about "other work item tracking related metadata" (in which the list is missing the preceding comma for this phrase). I don't think of attachments as metadata. They're artifacts.

I was having a permissions issue and needed to know about this this specifically, and even ADO PMs provided incorrect suggestions that I 'might' need `work_full`, (but turns out to be `work_write`, as intuition would suggest).

It would be great to have this clarified what permissions are needed for each specific end point. At the least, mention the word "Attachment" somewhere in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you @Paul-Dempsey, I've created a work item to address this. This issue will automatically close once the doc is updated. Thanks again!
