### ISSUE TITLE
Cache location and costs are unclear

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/azure-devops-docs#10368]
I don't see documented where the cache is stored, and whether developers are billed for the storage or network traffic costs

This is especially relevant for hosted agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@hansmbakker Thank you for reaching out. The cache is stored in a blob storage in Azure. Currently, you don't get charged for cache storage. I will be adding a note to the docs
