### ISSUE TITLE
Modified versions of the public package isn't clear as to who modified the package.

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10361]
"This ensures that you look for OSS packages from the public repos before checking any upstream sources, which could contain modified versions of public packages."

Instead of modified versions wouldn't it better to say "newer updated versions of the public packages".

Otherwise; the statement seems to imply that I may have my own modified version of a public package. And if that is the case looking up stream is not what I want to do.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72b4d1-30d9-4e08-c9bf-cb8457a3d05f
* Version Independent ID: 7d9e328b-8bf7-1706-b0e1-061eb221023c
* Content: [Upstream sources - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#search-order)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for the feedback! This article has been updated several times since this issue was filed and it no longer contains that statement.
