### ISSUE TITLE
PRIVACY

### ISSUE THREAD

**Issue by Te-bajt** [MicrosoftDocs/azure-devops-docs#10365]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8633dcca-a842-9a00-a5c1-5a86ad9f31e5
* Version Independent ID: 11207fe4-0a68-b988-3ea3-582cd6a527a1
* Content: [Add privacy policy URL to comply with the GDPR - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-privacy-policy-url?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-privacy-policy-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-privacy-policy-url.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@Te-bajt - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
