### ISSUE TITLE
How to use volumes mounted from other containers

### ISSUE THREAD

**Issue by trailstrider** [MicrosoftDocs/azure-devops-docs#10373]
Doc Location: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-containers

How to use volumes mounted from other containers

**Comment by TimShererWithAquent** [comment]
@trailstrider Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please provide more context.

**Comment by trailstrider** [comment]
If there is more than one container in the pipeline, how do we share volumes between them? Or even just mount folders from one container into another that we're operating in?

**Comment by juliakm** [comment]
@trailstrider I'm sorry for the delay on this. You can find more information on volumes in our [service container article](https://docs.microsoft.com/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#volumes). I'll add a link to it from the resources page.
