### ISSUE TITLE
Use Azure Key Vault secrets in Azure Pipelines - missing steps

### ISSUE THREAD

**Issue by ColeSiegelTR** [MicrosoftDocs/azure-devops-docs#10372]
Starting from **Run and review the pipeline** the steps don't make sense and reference echo commands and publish artifacts steps that were never explained. The doc never actually shows how to reference the secrets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Use Azure Key Vault secrets in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@ColeSiegelTR Thank you for your feedback! I updated the content and added the YAML pipeline which shows the steps to fetch the secret from Azure key vault, write it to secret.txt and publish the build Artifact.
