### ISSUE TITLE
Wiki Markdown paragraph formatting inconsistent with documentation.

### ISSUE THREAD

**Issue by kalebpederson** [MicrosoftDocs/azure-devops-docs#10382]
Maybe I'm not understanding the docs, but the current paragraph markdown behavior isn't what I would expect based on the documentation. The referenced document says the following:

> Make your text easier to read by breaking it up with paragraphs or line breaks. 

> In pull request comments, select Enter to insert a line break, and begin text on a new line.

> In a Markdown file or widget, enter two spaces before the line break to begin a new paragraph, or enter two consecutive line breaks to begin a new paragraph.

I understand that in such a way that the following text (assumed to be in a file called Readme.md) will be a single paragraph:

```
This is a single sentence
broken across multiple lines
that forms into a single paragraph.
```

Despite that, the wiki view within ADO displays the content as three different paragraphs (i.e., each line starts a new line regardless of browser/display width). I would instead expect the above to show up as a single line on monitors that are sufficiently wide.

I understand the docs the way I do because in the first quote above, it uses a Plural, "Make your text easier to read by breaking it up with paragraphs or line **breaks**" (emphasis added).  The last part of the quote explicitly states that if you want a new paragraph "...enter two spaces before the line break to begin a new paragraph, or **enter two consecutive line breaks to begin a new paragraph**" (emphasis added).

This behavior is inconsistent with the markdown preview view within JetBrains IntelliJ and Rider, the [CommonMark](https://commonmark.org/help/tutorial/03-paragraphs.html) guidance, and the [markdowndownguide.org guidance](https://www.markdownguide.org/basic-syntax/#paragraphs-1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#paragraphs-and-line-breaks)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by kitsu** [comment]
I reported this about a year ago on User Voice IIRC?
The response involved [children holding spacebar down in a northern climate](https://xkcd.com/1172/)...

**Comment by chcomley** [comment]
Hi @kalebpederson, I've just completed a PR with updates. I've removed the talk about entering two consecutive line breaks to begin a new paragraph. Once this is live, the issue will automatically be closed. If you think it needs further updates, please don't hesitate to @mention me. Thanks so much!
