### ISSUE TITLE
Add examples how to create a pipeline from the UI instead of only CLI

### ISSUE THREAD

**Issue by stil4m** [MicrosoftDocs/azure-devops-docs#10381]
The page does not contain any examples how to create a pipeline from a YAML file from the UI.

It would be helpful for less CLI-skilled users. I personally need to refer to this documentation for my peers, but at this moment the page is too technical.

For example this page contains such examples https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@stil4m You can find an overview of how to deploy with the UI in our [Classic release pipelines article](https://docs.microsoft.com/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops). I'll add a link in the get started article to make this clearer.
