### ISSUE TITLE
Incorrect deprecation message 

### ISSUE THREAD

**Issue by tbergstedt** [MicrosoftDocs/azure-devops-docs#10386]
The **Note** at the top of the page states that this task is deprecated for TFS 2017 and onwards. The problem is that the intended replacement, _pipeline artifacts_ is still not available for (on-prem) Azure DevOps 2020. So this task should still be the one used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Thanks for bringing this to our attention. We are updating the doc so that the warning only shows when Azure DevOps is selected for viewing the docs.
