### ISSUE TITLE
ADO > Move Work Item: Does Not Document Supported Work Types and Feature Does NOT Support Test Case

### ISSUE THREAD

**Issue by bjoropeza** [MicrosoftDocs/azure-devops-docs#10390]
[My org uses https://<orgName>.visualstudio.com/ (Version Dev18.M183.1)and has the need to move Test Cases from one ADO Project/TestPlan/TestSuite to another ADO Project/TestPlan/TestSuite.  

The Move Work Item Feature available from a single Test Case OR from the ADO Query appears to be a viable solution but when attempting this use case, the Move work item dialog box returns the following warning message: "Work item type Test Case cannot be moved because it is disabled, hidden or not supported in the source project <ProjectName>."

From the Type drop down list, Test Case is NOT a selectable option.  The existing documention, https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/move-change-type?view=azure-devops, does NOT describe the supported uses cases.  

Will the Test Case be supported in a future release for the Move Work Item feature?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d7da26-5052-70ad-4b2a-7ccd2f02f012
* Version Independent ID: 7a0b1331-7ac9-9927-b96e-36c6f014391a
* Content: [Move work items, change work item type - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/move-change-type?view=azure-devops)
* Content Source: [docs/boards/backlogs/move-change-type.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/move-change-type.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**
![2021-03-22_14-37-10](https://user-images.githubusercontent.com/16073032/112051386-e0669b80-8b1f-11eb-8d32-9f29bd77c9f0.png)
![2021-03-22_14-03-36](https://user-images.githubusercontent.com/16073032/112051406-e52b4f80-8b1f-11eb-85ee-61c631b8d565.png)

**Comment by KathrynEE** [comment]
@bjoropeza -  Thank you for your inquiry. I checked with the product team and they indicated that Test-related work item types aren't supported for the Move work item feature. The fact that you can access the feature for these work item types is a bug.
