### ISSUE TITLE
How can I change the name for a work item type for a inherited process?

### ISSUE THREAD

**Issue by maritzace** [MicrosoftDocs/azure-devops-docs#10398]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140c89b0-d6c4-025e-a755-576b47ea2a16
* Version Independent ID: 530eb620-64f1-70d5-7b62-5182498d13ea
* Content: [Customize work item type for inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-work-item-type?view=azure-devops-2020)
* Content Source: [docs/organizations/settings/work/customize-process-work-item-type.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/customize-process-work-item-type.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@maritzace -  Thank you for your inquiry. Renaming work item types isn't a supported feature for the Inheritance process model. You can't rename inherited work item types nor custom work item types. You can only create a new work item type with the name you want and customize it as needed. You then disable the work item type with the name you don't want.

**Comment by maritzace** [comment]
Thanks @KathrynEE , since the work item type name cannot be changed, can I copy all fields of this work item type to create a new one?

**Comment by KathrynEE** [comment]
@maritzace - Unfortunately no. I believe it's been suggested as a feature to add on our [Developer Community Page](https://developercommunity.visualstudio.com/search?space=21), but I can't say for sure. Also, I don't know of any extension that addresses this need. The only solution I know of is to use the REST APIs that support getting and creating and updating work item types. [Work Item Types](https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/work%20item%20types?view=azure-devops-rest-6.0).

**Comment by maritzace** [comment]
Thanks @KathrynEE
