### ISSUE TITLE
please improve table of file name restrictions

### ISSUE THREAD

**Issue by harridu** [MicrosoftDocs/azure-devops-docs#10394]
WRT File Name & Path Length Reference Table, File Name Restrictions: Since '/' is a reserved char for all 3 platforms, it should go to a dedicated line (if it has to be mentioned at all). Its a common restriction for all platforms. The other chars and names are restricted for Windows-only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e6ce09-5215-e1fa-74ca-9314fcfc2eb4
* Version Independent ID: 10e6cc00-4584-8c9c-e0ad-3107ace823d1
* Content: [Cross-Platform Compatibility - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/os-compatibility?view=azure-devops)
* Content Source: [docs/repos/git/os-compatibility.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/os-compatibility.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@harridu -- thank you for your feedback.  I see your point that `/` is common to all 3 OSs and so could be noted across the board.  I just read that table and the treatment of `/` seems unequivocally explained for each OS.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @vijayma for awareness
