### ISSUE TITLE
Where is the closing square bracket for {collection}

### ISSUE THREAD

**Issue by etidalgo** [MicrosoftDocs/azure-devops-docs#10391]
In this example, where is the closing square bracket for {collection}? I am assuming {collection} is independent of everything following it. 
`VERB https://{instance}[/{collection}[/{team-project}]/_apis[/{area}]/{resource}?api-version={version}`

This shows in another page. https://docs.microsoft.com/en-us/azure/devops/integrate/how-to/call-rest-api?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e79787-34f0-9978-4042-0235ebb85070
* Version Independent ID: dca00566-cce3-7488-207b-6c71af738d10
* Content: [REST APIs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/rest-api-overview?view=azure-devops)
* Content Source: [docs/integrate/rest-api-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/rest-api-overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @etidalgo, Thanks for the heads up on this. I've created a PR with the fix, and so this issue will automatically be closed once the updates go live. Thanks again!
