### ISSUE TITLE
ManualValidation task does not support displayName

### ISSUE THREAD

**Issue by KarlKl** [MicrosoftDocs/azure-devops-docs#10407]
The `ManualValidation` task does not support the `displayName`. 

This should **either be fixed or at least noted** on the docs page.
Because [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps) about the YAML schema clearly says, that all steps support the `displayName`..
```
All steps, regardless of whether they're documented in this article, support the following properties:
-     displayName
-     name
-     condition
-     continueOnError
-     enabled
-     env
-     timeoutInMinutes
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by raiyanalam** [comment]
I am no longer in this team. Adding @pulkitaggarwl

**Comment by Josh-01** [comment]
This is a bug, the fix has been created and should be deployed in the coming weeks.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here: 

Please check it out and let us know what you think. Thank you.
