### ISSUE TITLE
Deprecated URL 

### ISSUE THREAD

**Issue by SilviaDoomra** [MicrosoftDocs/azure-devops-docs#10404]
This URL is going to be deprecated: https://azuredatacentermap.azurewebsites.net/

Please update it to this page: https://azure.microsoft.com/en-us/global-infrastructure/data-residency/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe4c7a5f-322f-2c35-bbd7-14db2aee8144
* Version Independent ID: 52442a88-9e7c-b50d-4643-23ed10a3d7c3
* Content: [Data locations for Azure DevOps - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops)
* Content Source: [docs/organizations/security/data-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/data-location.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- please review this update in [private PR 2991](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2991).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
