### ISSUE TITLE
Step 2 appears to be out of date

### ISSUE THREAD

**Issue by michelamarie** [MicrosoftDocs/azure-devops-docs#10413]
Step 2 on this page, "In the Azure Portal, choose Create a resource, Web, then choose Web App for Containers.", under the heading, "Create an Azure Web App to host a container", appears to be out of date.

When I click "Create a new resource" in the Azure portal, then click "Web", there is no option called "web app for containers". It could be that the correct option to choose for this tutorial is now, "app service environment", though I am not sure yet (I expect to have that confirmed after completing the tutorial myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* Content: [Deploy a Docker container app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by michelamarie** [comment]
I've done some looking around the new resource menus and now see that the web app for containers item is now under the containers menu.

So step 2 should say, "In the Azure Portal, choose Create a resource, **Containers**, then choose Web App for Containers."

**Comment by WilliamAntonRohm** [comment]
@michelamarie -- Michela, thank you for your thorough feedback.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- please review this update in [private PR 2992](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2992).

**Comment by michelamarie** [comment]
You're very welcome, @WilliamAntonRohm.

Thanks for updating the document, and have a great weekend!

Michela
