### ISSUE TITLE
stageDependencies unavailable in AzDo 2019.1

### ISSUE THREAD

**Issue by wyarde** [MicrosoftDocs/azure-devops-docs#10418]
Documentation for AzDo 2019 mentions stageDependencies, though those are not available unfortunately:
```
An error occurred while loading the YAML build pipeline. Unrecognized value: 'stageDependencies'
```
Which probably is expected since the feature was only added in sprint [168](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-168-update)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops-2019&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @wyarde! I'll update the article.
