### ISSUE TITLE
Mermaid diagram types incorrect

### ISSUE THREAD

**Issue by dstretch** [MicrosoftDocs/azure-devops-docs#10429]
This page states you can only use Sequence and Gannt diagrams, but I'm successfully using the *graph* (flowchart) diagram, so I think this might need updating.

Would also be good to find out if it's possible to configure the diagrams inside of the mermaid block, e.g. set nodeSpacing etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @dstretch, Thanks for the heads up. I've just completed a PR with the fix, which will automatically close this issue once it's published. Adding @amitkumariiit to answer your question. Thanks!
