### ISSUE TITLE
Inform that this command is not supported for Azure Devops Server 2019/2020 On Prem environment

### ISSUE THREAD

**Issue by mmj78** [MicrosoftDocs/azure-devops-docs#10421]
We should clarify in this documentation that this command is not supported for Azure Devops Server 2019/2020 On Prem environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@mmj78 Which command are you referring to? Can you provide more info

**Comment by ramiMSFT** [comment]
More information is needed. Issue inactive
