### ISSUE TITLE
Mistake in the documentation

### ISSUE THREAD

**Issue by Jorrit05** [MicrosoftDocs/azure-devops-docs#10420]
I believe there is an error in the chapter 'Configure manual validation' for YAML pipelines.

It is stated that the 'myPostValidationJob' will not run untill the pipeline is approved. This is incorrect since this job is not dependent on the job that does the waiting so it will just run.

Kr.
Jorrit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5b870a-5ea3-402f-e40f-4c05bbd10531
* Version Independent ID: 20497cc1-7311-d41b-cf6b-bc84708d1963
* Content: [Control deployments with approvals and gates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-using-approvals?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-using-approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deploy-using-approvals.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
@shashban -- Shashank, please review this change in [private PR 2993](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2993).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
