### ISSUE TITLE
Image seems out of place

### ISSUE THREAD

**Issue by adba-msft** [MicrosoftDocs/azure-devops-docs#10422]
Below is line 43 in [source](https://github.com/MicrosoftDocs/azure-devops-docs/blob/321fb33724d3e19b7f0ee84e493a3ee963d71f31/docs/pipelines/get-started/pipelines-sign-up.md):

    ![New project, select Azure Pipelines](../media/new-project-select-pipelines.png)

The above image seems out of place. Does it belong there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebc49d4-ce18-c3d1-fc91-ea68fcbc4f1a
* Version Independent ID: daa9f424-3286-4877-83a4-6e0350d0196f
* Content: [Sign up for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started/pipelines-sign-up.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/pipelines-sign-up.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley I'm not sure, but I think the graphic does belong here. It is not introduced in the text. Maybe that's a little jarring.

**Comment by chcomley** [comment]
I've added annotation for the image, a step for selecting Pipelines once your project is created. Thanks so much for the heads up on this. This issue will automatically close when the PR is published. Thanks!
