### ISSUE TITLE
Azure Artifacts documentation is missing out on the hard limit of 384000 bytes of Maven pom.xml files

### ISSUE THREAD

**Issue by j-tim** [MicrosoftDocs/azure-devops-docs#10426]
I recently ran into the issue of the hard limit of 384000 bytes Azure Artifacts regarding the max size of a Maven `pom.xml` files.
This issue prevents me from resolving legitimate pom files like:

* [Lucene grandparent](https://repo1.maven.org/maven2/org/apache/lucene/lucene-solr-grandparent/8.8.1/)
* [Quarkus](https://repo1.maven.org/maven2/io/quarkus/quarkus-universe-bom/1.12.2.Final/)
* [Wildfly]( https://repo1.maven.org/maven2/org/wildfly/wildfly-parent/23.0.0.Final/)

from Maven central via my Azure Artifacts feed public upstream source. And probably many more big `pom.xml` files from open-source projects). 
The Azure Artifacts documentation is missing out on this hard limit of 384000 bytes on Maven `pom.xml` files 

See also: 
* https://developercommunity.visualstudio.com/idea/809379/remove-or-increase-the-hard-limit-of-384000-bytes.html

In my opinion, this should be documented [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops).

**Comment by TimShererWithAquent** [comment]
@j-tim Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.

**Comment by j-tim** [comment]
@TimShererWithAquent I don't understand your question. 
This issue about the limit is not documented. See my pull request to add it to the documentation.

The details about the issue with the hard limit (384000 bytes) on Maven project `pom.xml files itself can be found here: https://developercommunity.visualstudio.com/t/remove-or-increase-the-hard-limit-of-384000-bytes/809379.

**Comment by ramiMSFT** [comment]
Ref: https://github.com/MicrosoftDocs/azure-devops-docs/pull/10427
