### ISSUE TITLE
Bulk Imprort/Export should should clarify the ID field

### ISSUE THREAD

**Issue by e067881** [MicrosoftDocs/azure-devops-docs#10435]
Need to provide explicit documentation on what happens if the Work ID is used for the import.
When you export from a project and import into another project, and you use the Work ID as part of the import, your work items are moved to the new project, not cloned/copied. This is very important to point out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Bulk import or update work items using CSV files - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@e067881 - Thank you for the feedback. I'm updating the article to make a note about import and export to a new project.
