### ISSUE TITLE
Documentation is incorrect for issecret, fails to note secret variables do *not* get set as env vars

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/azure-devops-docs#10430]
The documentation mentions:
> This doesn't update the environment variables, but it does make the new variable available to downstream steps within the same job.
> 
> When issecret is set to true, the value of the variable will be saved as secret and masked from the log.
> ...
> Subsequent steps will also have the pipeline variable added to their environment.

This is confusing an inaccurate in two ways:
1. Environment variables *are* updated, just not immediately for the running job. Subsequent jobs have access to the new variable in YAML via `$(MACRO_SYNTAX)` **and** in tasks via environment variable.
2. Secret variables are only available via `$(MACRO_SYNTAX)` not via environment variable, and this is not mentioned in this documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-scripts)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @stewartadam! I'm updating the docs now. For the second issue raised (that you can only use macro syntax with secret vars), I need to follow-up with the product team.
