### ISSUE TITLE
Docs about the Scopes of Personal Access Token need updated

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/azure-devops-docs#10439]
In the document about "[**Scopes**](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops#scopes)" of PAT, we can see the scope "**Release (read)**" grants the ability to read release environment.
![Release-Scope](https://user-images.githubusercontent.com/46307996/112953783-55fde780-9170-11eb-816b-cc760c3605d6.png)

But according my test, actually this scope can't read environments. I try the following API to list all the Virtual machines in an environment.
```
GET https://dev.azure.com/{organization}/{project}/_apis/pipelines/environments/{environmentId}/providers/virtualmachines?api-version=6.1-preview.1
```
When using the PAT that only has the scope "**Release (read)**", the API returns "401 Unauthorized".

When creating a PAT, I find the scope "**Environment (Read & manage)**", then I create a PAT only contains this scope to execute the API. The API can work fine and return the list of the Virtual machines in the specified environment.
![Environment_Read_manage](https://user-images.githubusercontent.com/46307996/112956342-f1905780-9172-11eb-9d4a-fca5c92baeb2.png)

So, the actual scope to grant the ability to read release environment should be "**Environment (Read & manage)**". But this scope is not mentioned and listed in the document about "**Scopes**".

I think the document need to be updated to add the introduction of the scope "**Environment (Read & manage)**", and remove the incorrect introduction about "**Release**" scope.

**Comment by BrightRan** [comment]
Hello @chcomley , is there any update on this issue?

**Comment by chcomley** [comment]
Hi @BrightRan, Thanks for reaching out. I reached out last week and hope to hear back from a SME within the next few days and will keep you posted. Thank you.

**Comment by chcomley** [comment]
Hi @BrightRan, In the list of scopes, we do list environment as seen in the screenshot below. And it’s rightly not supposed to be in the Release category, as the environment really falls in the Agent Pools category. 
![image](https://user-images.githubusercontent.com/35748196/117691924-4ad7a780-b171-11eb-972e-051758f75044.png)
