### ISSUE TITLE
Missing Link?

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10437]
"Service accounts: Internal Azure DevOps accounts used to support a specific service, such as Agent Pool Service, PipelinesSDK. For descriptions of service accounts, see [Security groups, service accounts, and permissions](permissions.md#collection-level groups). "

Where do I find Permissions.md?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851595a3-32b8-c0e4-ff4f-aa84cf436175
* Version Independent ID: c2cb9c6c-de29-a7a9-9728-fbbc1d223a4f
* Content: [About security, authentication, authorization, and security policies - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?view=azure-devops)
* Content Source: [docs/organizations/security/about-security-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-security-identity.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@D-Moonesinghe - Thank you for your inquiry. The link you want is [Security groups, service accounts, and permissions](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#collection-level-groups). I will update the article to fix the broken link.
