### ISSUE TITLE
Confusing Instructions.

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10433]
It seems like information in this document needs to be broken down to 3 documents.
First document explains overall what is common between 
          connecting Azure DevOps to GitHub
          connecting Azure DevOps to GitHub Enterprise Server.
 2nd documents explaining  steps to take when connecting Azure DevOps to GitHub.
3rd document explaining steps to take connecting Azure DevOps to GitHub Enterprise Server.

Just listing everything you need  to do to connect in all scenarios piled together doesn't help someone who is not as familiar with the subject matter as your team of writers are.

As a first time reader you spend in ordinate amount of time trying to figure out what steps to take and what steps to ignore in each scenario.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@D-Moonesinghe  - Thank you for this feedback. Another reader also mentioned that his article was confusing. We have plans to update it to increase clarity.
