### ISSUE TITLE
YAML file for exercise appears to have a bug

### ISSUE THREAD

**Issue by michelamarie** [MicrosoftDocs/azure-devops-docs#10431]
In step 4 of this document "(Select Starter pipeline. Replace the contents of azure-pipelines.yml with this code.)," there appears to be a bug. When I paste the sample YAML code provided into a test pipeline and run it, Azure Pipelines returns an error:
> /azure-pipelines.yml: (Line: 4, Col: 9, Idx: 33) - (Line: 4, Col: 9, Idx: 33): While parsing a block collection, did not find expected '-' indicator.

I have tried a few different troubleshooting steps but have been, so far, unable to identify exactly how the YAML file must be changed in order to make the pipeline run properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/build-image.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@mijacobs please reassign if necessary. Not always sure who Atul's articles should go to -
