### ISSUE TITLE
Wrong information on bulk universal package downloads

### ISSUE THREAD

**Issue by miped** [MicrosoftDocs/azure-devops-docs#10446]
At https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops#bulk-download-universal-packages it says

> If you want to download a large number of universal packages, you can use the --file-filter wildcard filter to bulk-download a group of universal packages.
> The following example uses wildcards to download all .exe and .dll files from our feed.

This does not seem correct. Since the package name is required in the CLI, what this actually does is download a subset of files inside a single package. At worst, this section is plain wrong, and at best it is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops#feedback)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@miped Thank you for your feedback! The article is being corrected
