### ISSUE TITLE
`jdkVersionOption` has undocumented dependency on environment variables on agents.

### ISSUE THREAD

**Issue by yevster** [MicrosoftDocs/azure-devops-docs#10452]
We had a customer struggling to use the Maven task on their self-hosted agent. They were not aware they had to set a `JAVA_HOME_<version>_<architecture>` variable on the agent to coincide with the `jdkVersionOption` parameter. Neither error messages for the task nor the documentation make this explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@vijayma for review of associated PR.
