### ISSUE TITLE
Azure Artifacts doesn't work as a source fo PowerShell Core on Mac

### ISSUE THREAD

**Issue by tillig** [MicrosoftDocs/azure-devops-docs#10451]
This page has a tutorial showing how you can use Azure Artifacts as a Powershell module repo. However, at least on MacOS with PowerShell Core, it doesn't really work as shown.

For example, I get my personal access token and start the `Register-PSRepository` command as shown. It ends up like this:

```text
 pwsh> Register-PSRepository `
>>   -Name "MyRepoName" `
>>   -SourceLocation "https://pkgs.dev.azure.com/MyOrg/GuidHere/_packaging/FeedName/nuget/v2" `
>>   -PublishLocation "https://pkgs.dev.azure.com/MyOrg/GuidHere/_packaging/FeedName/nuget/v2" `
>>   -InstallationPolicy Trusted `
>>   -Credential $credentials
Unknown option: -V
.NET SDK (5.0.102)
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET application.

runtime-options:
...
```

(I truncated the help text from the dotnet CLI that gets fully echoed there.)

What I end up with is some sort of NuGet error. [There's a PowerShellGet issue that talks about it.](https://github.com/PowerShell/PowerShellGetv2/issues/619#issuecomment-563343305). It also seems to require that you pass `-Credential` whenever you install a module. For example, the command shown in the tutorial...

```powershell
Install-Module -Name MyModule -Repository MyRepoName
```

If it was run in this environment (with an appropriate module name), you'd get:

```text
WARNING: Cannot access 'https://pkgs.dev.azure.com/MyOrg/GuidHere/_packaging/FeedName/nuget/v2'. Are you missing 'Credential' parameter in the cmdlet?
WARNING: Unable to resolve package source 'https://pkgs.dev.azure.com/MyOrg/GuidHere/_packaging/FeedName/nuget/v2'.
```

There is a note in the tutorial that you might have to exit PowerShell and create a new session. That doesn't make a difference, you get the same "Unable to resolve package source" error.

If you pass `-Credential` as it suggests (again, with your PAT credentials as shown in the tutorial)...

```powershell
Install-Module MyModule -Scope CurrentUser -AllowPrerelease -Credentials $credential
```

Then you get a null reference exception.

```text
Install-Package: /usr/local/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Object reference not set to an instance of an object.
```

This whole thing appears to be totally broken, at least on a non-Windows machine.

I _am_ able to use `Find-Module` to locate my module just fine _as long as I provide the credentials_. So some of it works, but... not all?

```pwsh
Find-Module MyModule -Credential $credentials -AllowPrerelease
```

[I'm not the only person who's noticed this.](https://github.com/PowerShell/PowerShellGetv2/issues/619#issuecomment-590242186)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by juliakm** [comment]
@tillig What version of PowerShell are you using? I was just able to work through the tutorial after upgrading to 7.1.5 ([Homebrew](https://brew.sh/) version).   

In addition, I found that I didn't need to install all of the listed `FunctionsToExport`. Here's what my `FunctionsToExport` and `FileList` look like. I'll update the article to make this clearer. 

```ps 
# Functions to export from this module
FunctionsToExport = @(./Get-Hello.psm1)

# List of all files packaged with this module
FileList = @(./Get-Hello.psm1)
```

**Comment by tillig** [comment]
At the time (in March?) I don't know what version of PowerShell I was using. I'm currently on 7.1.5, also via Homebrew.

I already have a PowerShell module, an Azure Artifacts repo, and a PAT that has full control over read and publish for the feed.

Running this in PowerShell:

```powershell
Register-PSRepository -Name "XXX" -SourceLocation "https://pkgs.dev.azure.com/XXX/_packaging/XXX/nuget/v2" -PublishLocation "https://pkgs.dev.azure.com/F-DC/_packaging/nexus/nuget/v2" -InstallationPolicy Trusted -Credential $credsAzureDevopsServices
```

(where I've anonymized the URL and naming there) yields this warning four times:

```text
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet--V does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

My ambient .NET Core version is 6.0.100-rc.2.21505.57. NuGet is 5.9.0.7134. However, it seems like there's something else going on because it appears - _appears_ - to be doing something with `dotnet` instead of just NuGet.

Anyway, after I get the four blocks of `Could not execute...` text, I can do `Get-PSRepository` and I see my added repo. Cool.

But if I try to do `Install-Module` on a module I know is in the feed, it doesn't succeed:

```text
 pwsh> Install-Module NAMEOFMYMODULE
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet--V does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet--V does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
WARNING: Cannot access 'https://pkgs.dev.azure.com/XXX/_packaging/XXX/nuget/v2'. Are you missing 'Credential' parameter in the cmdlet?
WARNING: Unable to resolve package source 'https://pkgs.dev.azure.com/XXX/_packaging/nexus/nuget/v2'.
Install-Package: /usr/local/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'NAMEOFMYMODULE'. Try
     | Get-PSRepository to see all available registered module repositories.
```

So it doesn't seem to matter what version of PowerShell I have.

Now, something that may be confusing things is I have the [Azure Artifacts Credential Provider for NuGet](https://github.com/microsoft/artifacts-credprovider) also installed. Is it trying to be a credential helper here since it's a NuGet operation? I don't know. I don't think so? Shouldn't this work regardless?

That said, as linked in the initial comment, I'm not the only one who's seen this. It looks like just within the last six days [this has started getting traction](https://github.com/PowerShell/PowerShellGetv2/issues/619#issuecomment-954103875) and it sounds like it has something to do with the .NET Core version and the ability for PowerShell to persist credentials (or not).

Anyway, long story long, this still doesn't work for me.

**Comment by juliakm** [comment]
@tillig I'm sorry this has been such a pain. I was just able to install on a Mac but I think that there's something going on with the authentication (as you've pointed out). To get authentication to work correctly, for `Register-PSRepository`, I ran the `Register-PSRepository` command on its own and entered values as I was asked. I was then prompted to authenticate with Visual Studio. 

I was able to install using this (not ideal!) process. 

1. Delete the interim repo I created for authentication. 
`Unregister-PSRepository -Name "PowershellAzureDevopsServices"`

2. Register without passing authentication credentials. 
`Register-PSRepository -Name "PowershellAzureDevopsServices" -SourceLocation "https://<org_name>.pkgs.visualstudio.com/<project_name>/_packaging/<feed_name>/nuget/v2" -PublishLocation "https://<org_name>.pkgs.visualstudio.com/<project_name>/_packaging/<feed_name>/nuget/v2"`

3. Set up the `$credsAzureDevopsServices` value as described in the article. 

4. Verify the module exists. 
`Find-Module * -Repository PowershellAzureDevopsServices -Credential $credsAzureDevopsServices`

5. Install my PowerShell module.   
`Install-Module Get-Hello -Repository PowershellAzureDevopsServices -Credential $credsAzureDevopsServices`

Note that this was for a NuGet V2 module. I noticed that you said you are running NuGet V5. The article says that PowerShell does not support version 3 of NuGet. I'm checking if that is still accurate.

**Comment by tillig** [comment]
The NuGet CLI I'm using is v5. The _protocol_ is v2, as you can see in my (slightly anonymized) URL.

If I pass the credential _on the `Find-Module` or `Install-Module` command line_, it **does work!** Unfortunate that it prompts me to log in (which adds a new PAT during device authentication) and then doesn't save that. I think I have like 20 of these temporary PATs to clean out from testing and trying things.

Hopefully the process for this becomes easier with the fixes coming in PowerShellGet. I'm not sure I can direct a team of a few hundred on how to install and regularly update modules from a repo if it involves getting a PAT, creating the credentials, and passing the credentials manually every time. We'd probably need a script for that, which would be really convenient to distribute from a central location, like... in a module. 🙈 😆 

But at least we've cracked the code here. I'm not sure why I keep getting that warning:

```text
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet--V does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I got it four times during the `Register-PSRepository` command. I haven't dived into the PowerShellGet code, maybe it's trying to do something in there.

**Comment by juliakm** [comment]
@tillig We're following up with the product team and appreciate all of your help troubleshooting this. We will let you know what we find out and update the article with a correct workflow for MacOS.

**Comment by embetten** [comment]
For Powershell Get, you need to use the v2 not v3 endpoint for the Azure Artifacts feed. Otherwise you will get a 404 not found everytime. The register and install both need credentials. To utilize the cred provider on the install so you do not have to pass the -Credential flag on every single install command, please see this https://github.com/PowerShell/PowerShellGetv2/issues/619#issuecomment-1267259273 and the instruction here: https://github.com/microsoft/artifacts-credprovider#installation-on-linux-and-mac
