### ISSUE TITLE
Supported Azure DevOps Server versions

### ISSUE THREAD

**Issue by huntleyh** [MicrosoftDocs/azure-devops-docs#10457]
[Enter feedback here]
The document mentions support for Azure DevOps Server 2019 1.1 will end on Monday March 5th. Can we confirm this date? The last Monday March 5th was 2018 so can we double check this timeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-overview.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@huntleyh - Thank you for your inquiry. The Date should be April 5th and not March 5th. I will update the article accordingly.
