### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10456]
Did you mean to stages or jobs here?  Because if you meant to say stages; its bit confusing to have it under jobs.  When you are in the middle of talking about jobs.  That's like changing the subject in the middle of a conversation.

"Stages are most useful when you want to parallelize jobs or run a series of steps in different environments."
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@D-Moonesinghe That's correct but I'll make the transition clearer. We've had some confusion from customers about when to use stages or jobs. Thanks for flagging this.
