### ISSUE TITLE
Relative Link Documentation Wrong

### ISSUE THREAD

**Issue by andrewatfornax** [MicrosoftDocs/azure-devops-docs#10450]
"Relative path: [text to display](/target.md)"

Isn't that an absolute link to to the target.md file in the root of the Wiki?

A relative path seems to start with no leading / character, from what I can tell...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @andrewatfornax, Thanks for the heads up on this. I've just complete a PR, which fixes this, which should go live shortly. Thanks again!
