### ISSUE TITLE
R

### ISSUE THREAD

**Issue by denisdeoniss** [MicrosoftDocs/azure-devops-docs#10464]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by TimShererWithAquent** [comment]
@denisdeoniss Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
