### ISSUE TITLE
Task ManualValidation@0 is non-existent for DevOps Server - but has docs anyway

### ISSUE THREAD

**Issue by zleight1** [MicrosoftDocs/azure-devops-docs#10467]
Task ManualValidation@0 is non-existent for DevOps Server - but has docs anyway both for 2020 and 2019.

See also this thread: https://developercommunity.visualstudio.com/t/Manual-Validation-task-not-available-in/1340627?space=22&q=Manual+Validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops-2020&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by juliakm** [comment]
Thanks @zleight1! I'll update the versioning.

**Comment by juliakm** [comment]
Hi again @zleight1. I looked again and realized that there is versioning that might not be obvious. This task is for Azure Pipelines only. 

![Screen Shot 2021-04-12 at 4 43 09 PM](https://user-images.githubusercontent.com/64906/114459273-4d64d280-9bae-11eb-8e08-6c15639a2c8a.png)
