### ISSUE TITLE
I do not see description for the variable $(System.TaskInstanceId), why?

### ISSUE THREAD

**Issue by KarenTazayan** [MicrosoftDocs/azure-devops-docs#10475]
Hello,

The documentation page says: "This is the comprehensive list of predefined variables."

I do not see description for the variable "**$(System.TaskInstanceId)**"

Why?

Also it says: "System.JobId - A unique identifier for a single attempt of a single job."

For the every new pipeline run a get the same ID for a job.

Is the documentation wrong or the product work incorrectly?

The mentioned above is the same for **System.TaskInstanceId**

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&source=docs)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@KarenTazayan The value JobId should be unique to the current pipeline. I'll update the article. Also, I'm updating the description to be clearer that this is not a comprehensive list. Some variables such as `System.TaskInstanceId` are primarily used internally.
