### ISSUE TITLE
User Name not email

### ISSUE THREAD

**Issue by AbdullaAlajmi** [MicrosoftDocs/azure-devops-docs#10472]
you cant add name, only emails
for example Abdulla Alajmi what it shows and email is abdulla.alajmi@blabla.com
its difficult to explain. I will try again.
I can create user abdulla.alajmi@blabla.com but how to enter the name 'Abdulla Alajmi'

DevOps is not user friendly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc87179-e881-fa2e-992a-1580c4cba0ac
* Version Independent ID: 74c82336-1057-a0db-aa08-907885002a9b
* Content: [Add users and manage access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-organization-users?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/add-organization-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-organization-users.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@AbdullaAlajmi - It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
