### ISSUE TITLE
This page has a wrong link name on the left panel

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10479]
![Link to Azure Boards App](https://user-images.githubusercontent.com/60631350/113774450-4ee95300-96f5-11eb-81e6-540764e53a99.png)

It says "Connect to GitHub".  But actually this is an Azure Boards app that you install in GitHub account.  So it really should say connect From GitHub to Azure Boards.  The way you have it is confusing to readers.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffffb75a-67a8-f005-9980-de1270efbabf
* Version Independent ID: 4ae8f3f0-24e2-05f7-5c2e-d0a23aa330c0
* Content: [Learn how to connect/integrate GitHub with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/boards/github/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/index.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@D-Moonesinghe - THank you for this feedback. I have plans to update the content for this article and will address your feedback at that time.
