### ISSUE TITLE
Pricing for parallel jobs

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/azure-devops-docs#10477]
Please provide a link to the pricing for parallel jobs, I can't find the actual pricing anywhere.

For example it should actually show on the page where you purchase them

https://dev.azure.com/[ORG]/_settings/billing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by MS-alsulli** [comment]
Hey @paulaustin-automutatio 

In the doc you linked, there is actually two pricing calculators in the ["Tip" section under "How much do parallel jobs cost"](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#how-much-do-parallel-jobs-cost). A pricing calculator for Azure DevOps Services, and one for Azure all-up. 

Click the "Pricing calculator" for Azure, and the "Azure DevOps Pricing page" for Azure DevOps Services costs. Hope this helps!

**Comment by steved0x** [comment]
@paulaustin-automutatio I'll see if I can update that tip section and make this clearer. Thank you for letting us know.
