### ISSUE TITLE
Unclear how to determine details of triggering pipeline

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/azure-devops-docs#10474]
[Enter feedback here]
We have a generic pipeline configured to run continuous-deployment into different environments.
Previously, we used a REST API call to pass information from the triggering (upstream) pipeline (was in Jenkins) to the triggered (downstream) CD pipeline (was in Gitlab) such as, triggering project, version, branch, commit, image name:tag etc.

Now using ADO completion triggers, the onus seems to be on the downstream pipeline to "know" who might trigger it, and when that trigger occurs, obtain the triggering information.

What I see in the triggered environment seems to be information about the all of the possible completion pipelines, and nothing specific to identify exactly which one of those just completed and caused the trigger.  So the downstream pipeline needs to go back to the upstream one somehow and fetch that.

Could you please document the missing information on here:
(a) all of the `RESOURCES_PIPELINE_`_name_`_XXX` variables that the triggered pipeline can expect to find, and their purposes
(b) How the triggered downstream pipeline can identify which of those _name_ sets of env variables to use to fetch more information about the upstream
(c) How to obtain a build artifact from the upstream

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by steved0x** [comment]
These are documented now here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#pipeline-resource-metadata-as-predefined-variables
Thank you for letting us know.
