### ISSUE TITLE
Page is not updated to provide details about upcoming change

### ISSUE THREAD

**Issue by rumenavramov** [MicrosoftDocs/azure-devops-docs#10486]
AzureDevOps displays a warning that it "will stop supporting per-pipeline retention rules in an upcoming release" and provides a link to this page, but the page is not updated to provide details about that upcoming change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Retention policies for builds, releases, and test - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **rabououn**

**Comment by juliakm** [comment]
@rumenavramov Thanks for noting this. I'm updating the warning on the page to be clearer.
