### ISSUE TITLE
Dead link to the command reference

### ISSUE THREAD

**Issue by Sam-Rowe** [MicrosoftDocs/azure-devops-docs#10487]
Hi, I was looking at this page and tried to goto the command reference in the menu but got a 404.

<img width="851" alt="Screenshot 2021-04-07 at 17 14 13" src="https://user-images.githubusercontent.com/14168597/113899588-dc47a880-97c4-11eb-8439-6e3d931b15b1.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8708d95a-81fd-5656-2e49-5c0ce88d99fd
* Version Independent ID: b6414c76-9903-1b5e-a948-318320ff1e38
* Content: [Configure branch policies for Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/policy-configuration-file?view=azure-devops)
* Content Source: [docs/cli/policy-configuration-file.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/policy-configuration-file.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by eriawan** [comment]
I have submitted a PR #10489  to have the correct link to `az devops` CLI reference.

**Comment by KathrynEE** [comment]
@Sam-Rowe - Thank you for your feedback. This will get updated today. There are actually a number of misconfigured links as the URL for the azure devops CLI commands have changed.
