### ISSUE TITLE
Add the naming restrictions and conventions for Azure Pipelines in the document

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/azure-devops-docs#10481]
In the document about "[**Naming restrictions and conventions**](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?toc=%2Fazure%2Fdevops%2Freference%2Ftoc.json&bc=%2Fazure%2Fdevops%2Freference%2Fbreadcrumb%2Ftoc.json&view=azure-devops)", it has mentioned the naming restrictions for many things, such as Azure Repos, Azure Boards, Wiki, etc..

However, in this document, the naming restrictions for Azure Pipelines are never mentioned. Such as:
* Naming restrictions for pipeline name
* Naming restrictions for pipeline run (build) number, release name
* Naming restrictions for variables, parameters
* Naming restrictions for stages, jobs, steps

I think, the document should be updated to add these details.

**Comment by chirangaalwis** [comment]
@BrightRan thanks for bringing this up. Appreciate if the Azure DevOps team can look into this and perform the necessary documentation updates if such conventions exist.

**Comment by chirangaalwis** [comment]
@BrightRan @chcomley any update on this. Appreciate if we can get the details of the naming conventions ASAP.

**Comment by chcomley** [comment]
Adding @steved0x for input. Thanks Steve!

**Comment by chirangaalwis** [comment]
@chcomley @steved0x any update on this?

**Comment by chcomley** [comment]
Hi @chirangaalwis, Thanks for following up. I'm waiting on feedback from a PM, but I can share what I do know, which applies to deployment jobs.
•	Job and stage names cannot contain keywords (example: deployment).
•	Each job in a stage must have a unique name.
If there is a naming conflict, the job shows as pending indefinitely. 

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops

Thanks!

**Comment by chirangaalwis** [comment]
@chcomley @steved0x apart from these restrictions, do you have well defined naming best practices (not restrictions) for the constructs defined in https://github.com/MicrosoftDocs/azure-devops-docs/issues/10481#issue-852164666?

For example, I can see the usage of camel case for naming in the documentation [example](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#runonce-deployment-strategy-1).

Or are the user expected to stick to the restrictions and develop their own, preferred  best practices when using Azure DevOps Pipelines and their constructs?

**Comment by chirangaalwis** [comment]
@chcomley @steved0x any update on this?

**Comment by chcomley** [comment]
Hi @chirangaalwis, Not much of an update on this, as we're meeting with our SME mid-week. I'll keep you posted, thanks.

**Comment by chirangaalwis** [comment]
> Hi @chirangaalwis, Not much of an update on this, as we're meeting with our SME mid-week. I'll keep you posted, thanks.

Thanks @chcomley.

**Comment by chcomley** [comment]
I've updated the article, which will close this issue once it's live. Updated with the following information, hope this is helpful:

- A job or resources name must have this pattern: ^[-_A-Za-z0-9]*$
- A stage name or an environment can be any string - names may only contain alphanumeric characters and '_' and may not start with a number
- Job and stage names can't contain keywords (for example: deployment)
- Each job in a stage must have a unique name
- Expressions must start with a-Z or _AND followed by a-Z 0-9 or _
