### ISSUE TITLE
This article is very confusing.

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10480]
This article has confusing feel tech doc written by a committee.

1. It has to many things added together.
      Ex: Connectivity to GitHub.com and GitHub Enterprise server could easily be separated so into different articles to make it easier grab the points we need.

2. Tasks are in the wrong order.
    Ex: By reading this it seems like:
    First: Register Azure Boards in GitHub as an OAuth App.
    Second: Add an OAuth Config to Azure DevOps under org settings.
    Third:  Then make the connection from Azure Boards to GitHub.
    
   But this doc has all that in a confusing order; seems like those are different task that need to be done in a certain sequence for the connection to make.

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@D-Moonesinghe - Thank you for your feedback. I have plans to update this article to address the concerns you have raised.  I'll notify you once the updates have been made.
