### ISSUE TITLE
Dead link from Learn About Azure DevOps commands to Command Reference help.

### ISSUE THREAD

**Issue by airhed13** [MicrosoftDocs/azure-devops-docs#10497]
The `Command Reference` link in the `Related Articles` section is dead, it sends me to a 404-NotFound.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@airhed13 - Thank you for the feedback. The CLI URLs were changed recently.  Please see [Index to az devops examples](https://docs.microsoft.com/en-us/azure/devops/cli/quick-reference?toc=%2Fazure%2Fdevops%2Fdev-resources%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fdev-resources%2Fbreadcrumb%2Ftoc.json&view=azure-devops) for correct links.  I'll update the article with the dead link today.
