### ISSUE TITLE
How do I specify boolean operations in the "Filter by keyword" field?

### ISSUE THREAD

**Issue by pcarver** [MicrosoftDocs/azure-devops-docs#10490]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ce3e5c-e484-93aa-6e41-716fbbd62d57
* Version Independent ID: 9c147873-1605-db62-73f4-a1d30e23d98c
* Content: [Filter backlogs, boards, queries, and plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/filter-backlogs-boards-plans?view=azure-devops)
* Content Source: [docs/boards/backlogs/filter-backlogs-boards-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/filter-backlogs-boards-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pcarver - Thank you for your inquiry. Applying Boolean operators to filters is only supported for Tags - either ALL AND or ALL OR as descirbed in [Filter based on tags](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/filter-backlogs-boards-plans?view=azure-devops#filter-based-on-tags). All other filters are applied with an implicit AND operator. I'll update the article to clarify that.
