### ISSUE TITLE
bad link to file matching patterns

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-devops-docs#10499]
![image](https://user-images.githubusercontent.com/14079228/114097484-16c94800-988e-11eb-8ae5-4f4cc6cddc72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by spottedmahn** [comment]
Hi @TimShererWithAquent - was this closed on accident?

**Comment by TimShererWithAquent** [comment]
@spottedmahn It's fixed in the attached PR.

**Comment by spottedmahn** [comment]
🤦‍♂️

![image](https://user-images.githubusercontent.com/14079228/114197944-dc5cbb00-9920-11eb-9c5d-a85705f1eb3b.png)

thanks @TimShererWithAquent!

**Comment by spottedmahn** [comment]
commit for reference: https://github.com/MicrosoftDocs/azure-devops-docs/commit/444e8145869e38f00703d7a63f6ff6d1728ca2a6#diff-f64294218836a69fa679d3e485a599ce0b14801457133588c6d7cdd0281ff4d6

interesting... wonder why markdown links don't work here? 🤔

**Comment by TimShererWithAquent** [comment]
@spottedmahn Some tables are still formatted as html. Markdown links (and some formatting, I think) doesn't work in an html table. 

The longer term fix will be to convert the table to markdown.
