### ISSUE TITLE
Command reference link is broken

### ISSUE THREAD

**Issue by michaelwestbrook** [MicrosoftDocs/azure-devops-docs#10491]
Link points to : https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops?view=azure-cli-latest&preserve-view=true but returns a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@michaelwestbrook - thank you for the feedback. A fix is underway to address the broken links which arose from a change in the URL for the Azure DevOps CLI command reference.  The link is now https://docs.microsoft.com/en-us/cli/azure/devops.
