### ISSUE TITLE
https://drive.google.com/folderview?id=10Ulw-8nvQvQPKEUJRnxWK5Vc2BXl4iI7

### ISSUE THREAD

**Issue by mcelwee409** [MicrosoftDocs/azure-devops-docs#10498]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by TimShererWithAquent** [comment]
@mcelwee409 - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
