### ISSUE TITLE
Page doesn't answer it's own Title question

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/azure-devops-docs#10493]
What is An Azure Artifact?

Well I hoped this would have clear simple explanation of 
1. what is an artifact is?
2. How are artifacts created?
3. Who creates artifact?

But none of those basic questions are answered here despite the title claiming so.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5382202b-3007-32f0-6ba3-0061625ea079
* Version Independent ID: 60f7e250-5e0a-fcf6-8795-03897ad74def
* Content: [Azure Artifacts in Azure DevOps - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops)
* Content Source: [docs/artifacts/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/overview.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@D-Moonesinghe Thank you for your feedback! Adding a work item to address this issue.
