### ISSUE TITLE
The Build.TriggeredBy.* variables do not exist

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/azure-devops-docs#10496]
[Enter feedback here]
None of the Build.TriggeredBy.* variables documented on https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts seems to exist.
This is within a pipeline that was triggered by an upstream pipeline.
Perhaps there is some additional  condition also necessary?

Example environment and variables output by bash debug task in a triggered pipeline run:
```
ADO Variables:
System.TeamProjectId=004772e1-a3fa-40fc-...
System.DefinitionId=10722
Build.BuildId=567063
Build.TriggeredBy.BuildId=$(Build.TriggeredBy.BuildId)
Build.TriggeredBy.DefinitionId=$(Build.TriggeredBy.DefinitionId)
Build.TriggeredBy.ProjectID=$(Build.TriggeredBy.ProjectID)
Build.TriggeredBy.ProjectId=$(Build.TriggeredBy.ProjectId)

Environment variables:
	BUILD_BUILDID = 567063
	BUILD_REASON = ResourceTrigger
...
	RESOURCES_PIPELINE_MY-ALIAS_PIPELINEID = 2369
	RESOURCES_PIPELINE_MY-ALIAS_PIPELINENAME = my-pipeline-name
	RESOURCES_PIPELINE_MY-ALIAS_PROJECTID = 004772e1-a3fa-40fc-...
	RESOURCES_PIPELINE_MY-ALIAS_REQUESTEDFOR = Ed Randall
	RESOURCES_PIPELINE_MY-ALIAS_REQUESTEDFORID = 6677ae3f-5c70-...
	RESOURCES_PIPELINE_MY-ALIAS_RUNID = 567034
	RESOURCES_PIPELINE_MY-ALIAS_RUNNAME = 20210408.6
	RESOURCES_PIPELINE_MY-ALIAS_RUNURI = vstfs:///Build/Build/567034
	RESOURCES_PIPELINE_MY-ALIAS_SOURCEBRANCH = refs/heads/feature/mybranch
	RESOURCES_PIPELINE_MY-ALIAS_SOURCECOMMIT = 65f5d9f0ac21fbc6fc67674032e2b27effa58cd9
	RESOURCES_PIPELINE_CWP_CLOUD_DASHBOARD_SOURCEPROVIDER = TfsGit
	RESOURCES_TRIGGERINGALIAS = my-alias
	RESOURCES_TRIGGERINGCATEGORY = pipeline
...
	SYSTEM_DEFINITIONID = 10722	
	SYSTEM_TEAMPROJECTID = 004772e1-a3fa-40fc-...

```
None of the BUILD_TRIGGEREDBY.* are present.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
If you are triggering a YAML pipeline from another pipeline, you can use the `resources` variables instead. Here's the list of [available variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#the-pipeline-resource-metadata-as-predefined-variables). I'll update the article to make this clearer.
