### ISSUE TITLE
Permission conflicts of Readers / Project Administrators groups

### ISSUE THREAD

**Issue by yaegashi** [MicrosoftDocs/azure-devops-docs#10509]
Are the following statements still valid? Could you tell me the objects where the Readers group could deny permissions of other groups?

> > [!TIP]    
> > User accounts that are assigned to more than one security group are restricted to those permissions granting the **least access**. For example, if you add a user to the Readers group and the Project Administrators group, the effective permissions of the Readers group are enforced for the user. 

> **Don't:**  
> - Don't add users to the project **Readers** group that you've added to the **Project Administrators** group. Because the Readers group denies several permissions that the Project Administrators group allows, and deny takes precedence.  

I found the following comment [in this post in 2017](https://developercommunity.visualstudio.com/t/Permission-inheritance/67234):

> Thanks for providing this link. I believe this is a mistake in our documentation that needs to be fixed. The project readers group doesn't automatically deny any permissions.
> By default, permissions in the Project Administrators group are set to allow and these permissions can't be modified. Reader permissions are either not set or set to Allow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa32191d-6d0a-058f-2ffe-3ce1b58e2c59
* Version Independent ID: 858d1ed3-b2af-699f-9d51-86ac0962086b
* Content: [Get started with permissions, access levels, and security groups - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=current-page)
* Content Source: [docs/organizations/security/about-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@yaegashi  - I need to investigate these statements with the product team, but I suspect they changed the rules. I just added a member of the PRoject Admin group to the Readers group - and his permissions weren't affected. I will ensure the rules were changed and update the article accordingly.
