### ISSUE TITLE
POs & SM

### ISSUE THREAD

**Issue by zapper5626** [MicrosoftDocs/azure-devops-docs#10505]
It is a disservice to organizations trying to make a transformation to 'agility' to have PM listed here as a role.  Microsoft's definition of DevOps, includes Agile (item 3, Agile Software Development). Agile splits the historical role of the PM into product owner (content owner) and scrum master (wheel greaser) because of the work load that has historically been placed on PM.  Also, PO & SM roles provide a way of breaking away from waterfall project plans to iterative lean processes.

**Comment by TimShererWithAquent** [comment]
@zapper5626 Thanks for your feedback. Please let us know which specific article you're referring to.

**Comment by zapper5626** [comment]
the article is https://docs.microsoft.com/en-us/azure/devops/user-guide/roles?view=azure-devops

**Comment by chcomley** [comment]
Thanks for the feedback @zapper5626, publishing an update today!
