### ISSUE TITLE
.artifactignore file must be all lower case

### ISSUE THREAD

**Issue by serbrech** [MicrosoftDocs/azure-devops-docs#10501]
[Enter feedback here]

The documentation states : 

> To reduce the chances of publishing the .git folder, we automatically ignore this path. You can re-include it by adding the following line to your .artifactIgnore file:

`.artifactIgnore` -> this won't work it seems, the file must be all lowercase: `.artifactignore`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactIgnore file - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@ramiMSFT I don't know for sure how the casing works in this scenario, so I won't do a quick fix.

**Comment by ramiMSFT** [comment]
@serbrech Thank you for your feedback!
