### ISSUE TITLE
Incorrect information related to permission at org level under Boards

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/azure-devops-docs#10507]
Please note under section Boards, as shown in the highlighted red boxes in the attached snap, the it is mentioned that Stakeholders and Basic licensed users are granted these permission by default. It is not true as shown in another snap attached. All of these permissions under Board are set to Not Set which assume Deny by default. Please clarify.

![image](https://user-images.githubusercontent.com/39550075/114212919-fe395a80-997f-11eb-8caf-7653defb03bd.png)

![image](https://user-images.githubusercontent.com/39550075/114212242-3a1ff000-997f-11eb-8527-56aaf90ceb0a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default perm
![image](https://user-images.githubusercontent.com/39550075/114212207-2f655b00-997f-11eb-8ea9-7cf451cc1347.png)
issions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#collection-level-groups)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vijay-gowda  - Thank you for the feedback. I will update the article today to reflect correct defaults. I'm not sure why Stakeholder and Basic access was mentioned as having these permissions. They don't have them by default. Only members of the Project Collection Administrators group have permissions by default.

**Comment by vijay-gowda** [comment]
Thanks Kathryn. One query, I am helping with improving the product and had been doing it so far in other such issues. Is there a recognition or such we get when we do it where I am taking time to verify things in your product and logging issues when confirmed?

**Comment by KathrynEE** [comment]
@vijay-gowda - I'm checking with my manager and will get back to you.

**Comment by KathrynEE** [comment]
@vijay-gowda - We have an internal Content Contributor Success (CCS) team that is actively working on building a recognition program for contributors across docs.microsoft.com. They've launched a badging initiative with PNP for select contributors and are looking to expanding to Docs next by targeting a few groups within docs. If anything changes specific to Azure DevOps contributions, I'll let you know.
