### ISSUE TITLE
Multistage YAML pipeline does not apply environment-specific XML transformation if Release.EnvironmentName is not set

### ISSUE THREAD

**Issue by RobinDink** [MicrosoftDocs/azure-devops-docs#10503]
Hey,

if you are using multistage pipelines and want to apply XML transformation (e.g. web.config) you actually need to set the variable "Release.EnvironmentName" for the specific stage to the name of the environment (e.g. to Staging to apply web.Staging.config). 
For GUI based release pipelines this works without setting this variable if the stage name is equal to the environment name. Either fix this bug or add it to the documentation.

Cheers,
Robin

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Benutzer Funktionalität für mehrstufige Pipelines - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs-pr.de-DE/blob/live/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@RobinZergiebel Thanks for your question. We'll look at whether to add this point to the docs.

As for the issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
