### ISSUE TITLE
[Documentation Error] Missing colon in pipeline-decorator-context.md code example causes sample not to run

### ISSUE THREAD

**Issue by cytron201** [MicrosoftDocs/azure-devops-docs#10512]
Error in decorator conditional code example, line 116:

`- ${{ if ne(variables['skipInjecting'], 'true') }}`

This is missing a colon at the end of the line, so should be:

`- ${{ if ne(variables['skipInjecting'], 'true') }}:`

That caught me out for a good 30mins :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f7712f-f527-4326-21d5-34f1c300bdd7
* Version Independent ID: d3e588cc-8552-ddae-1f82-0856cc84f2d9
* Content: [Pipeline decorator context - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops)
* Content Source: [docs/extend/develop/pipeline-decorator-context.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/pipeline-decorator-context.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by juliakm** [comment]
Thanks @cytron201! This will be fixed shortly.
