### ISSUE TITLE
Screenshots need to be updated

### ISSUE THREAD

**Issue by sussexrick** [MicrosoftDocs/azure-devops-docs#10519]
The screenshots on this page need to be updated to reflect the new UI of Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb7276b-e7ab-8d3f-f89c-4f5130808f61
* Version Independent ID: f11655e2-14f9-7755-dffa-61b21db1be67
* Content: [Add users to Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/set-permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/set-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/set-permissions.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@sussexrick Thank you for your feedback! The updated version will go live shortly
