### ISSUE TITLE
Cannot display Epics/Features on a Preview Plan

### ISSUE THREAD

**Issue by glautrou** [MicrosoftDocs/azure-devops-docs#10513]
I configured my full backlog (Epic>Feature>US) with start dates and iterations, and wanted to use the "Plan" preview feature.

Unfortunately the preview plan view only display user stories, not epics and features.

My goal is to display the Epic and Feature view rollup, [as per documentation](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops&tabs=plans-preview#view-rollup-of-features-and-epics---plans-preview).

I also checked Settings>Fields>Show child rollup data.
When I go Settings>Teams, I can only select the only value "Stories" in the Backlog dropdown, I guess I should be able to select either Epic or Feature.

Is this a bug or is there something else to activate in projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops&tabs=plans-preview)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@glautrou - It looks like you have a question with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by KathrynEE** [comment]
@glautrou - To show Epics and Features, you need to add your team backlog for Epics and your team backlog for Features.  SImilar to that shown below. If you have added these different backlog levels and don't see the Epics and Features, then please report it as a bug.  The only other setting you might check is that the Team Settings supports features and backlogs - see second image. I just confirmed that if the backlog levels are not enabled for the team, then the Plans won't allow selection of those not selected. I'll add that clarification to the article. 

![image](https://user-images.githubusercontent.com/10856840/114447883-be44c400-9b87-11eb-92e9-9e3bee622d2a.png)

![image](https://user-images.githubusercontent.com/10856840/114448242-272c3c00-9b88-11eb-8f4a-8457d03b4be6.png)
