### ISSUE TITLE
Missing --global switch in command line

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/azure-devops-docs#10517]
[Enter feedback here]

To ignore files across all repos, you need to add the value to the GLOBAL configuration with the --global switch, which is missing from your command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f73e6a-75c9-6a8d-c2e1-08feeb9700c1
* Version Independent ID: 80570118-9b20-9999-6464-6e9e522c1ab7
* Content: [Ignore files in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/ignore-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/ignore-files.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@vijayma I think this is referring to this command: 

_git config core.excludesfile C:\Users\frank\.gitignore_global_

The git config docs put --global after config.
