### ISSUE TITLE
Dashboard and Kanban board can be added as a tab using the Azure DevOps icon

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/azure-devops-docs#10523]
Under the section **Configure Azure DevOps Services tabs in Microsoft Teams**, it says that I should use the Website icon to add the URL of a dashboard or a kanban board as a tab. It looks like I can also use the Azure DevOps icon to add a dashboard/kanban board - it will ask for the org/project for navigation instead of asking for the URL, and the resulting tab will not have the side menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Azure Boards with Microsoft Teams - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/integrations/boards-teams.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **karrg**

**Comment by KathrynEE** [comment]
@felixtsem5 - Thank you for the feedback. I'm updating the article to indicate the two options.
