### ISSUE TITLE
Task custom conditions and expression doc link is broken

### ISSUE THREAD

**Issue by mohamed-shehata-m** [MicrosoftDocs/azure-devops-docs#10528]
Hello,

I'm trying to look for the documentation of task custom conditions and expression, but the link is broken.

I tried accessing it from below links, but I'm getting 404. Also, in Azure DevOps, help url is broken

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions

![image](https://user-images.githubusercontent.com/25155380/114736802-b54e2100-9d46-11eb-9674-2446de974099.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@mohamed-shehata-m Thanks for your question. I haven't been able to find any broken links in the two pages you identify above or in the content link. Could you copy the link that you're trying to go to?

**Comment by mohamed-shehata-m** [comment]
They are now working. It seema that it was intermittent issue. Thank you.
