### ISSUE TITLE
Does not work: Tags Does Not Contain (blank)

### ISSUE THREAD

**Issue by reecebradley** [MicrosoftDocs/azure-devops-docs#10522]
According to this: [List Work Items with No Tags](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops#list-work-items-with-no-tags)

![image](https://user-images.githubusercontent.com/1536861/114449822-d96cff00-9b9a-11eb-9b47-f1e8bb6f0017.png)

I'm trying to do this right now and "(blank)" is basically being ignored, no syntax errors when running the query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf3ce0a-184f-ca49-5453-01317e23dde5
* Version Independent ID: 0af9b10e-1126-2fda-982b-63d5795f9213
* Content: [Add tags to work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops)
* Content Source: [docs/boards/queries/add-tags-to-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/add-tags-to-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@reecebradley - Thank you for the feedback. I just tried the query as shown and it returns some values, but it returns values that also contain tags. I'll investigate further to see if there is a work around, otherwise, I'll update the article to reflect what I find.

**Comment by KathrynEE** [comment]
@racebradley - On further investigation, this feature is not supported and I will make a note to that effect in the article. If you would like to upvote for this feature, see this entry in our Developer Community page, https://developercommunity.visualstudio.com/t/be-able-to-search-for-empty-tags/907425.  Closing this issue now as there is no further action.

**Comment by reecebradley** [comment]
Thanks for looking @KathrynEE 
I went and upvoted it, kind of bummed I must admit. Have a good day.
