### ISSUE TITLE
Clarification around adding the NODE.EXTRA.CA.CERTS variable

### ISSUE THREAD

**Issue by nadcraker** [MicrosoftDocs/azure-devops-docs#10529]
There is more than one way to add a variable to a pipeline. Can the section of the FAQ regarding the NODE.EXTRA.CA.CERTS variable be clarified? 

Is the syntax `NODE.EXTRA.CA.CERTS=file` or is it `NODE.EXTRA.CA.CERTS: file`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Thanks for the feedback. We are fixing the doc to include a link to the section on how to set variables in a pipeline. Any variable that is set in a pipeline is available as an environment variable in the process that runs the task.
