### ISSUE TITLE
Inconsistent information

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/azure-devops-docs#10536]
Same section of the page is giving contradicting information. Please clarify as per the snap.

![image](https://user-images.githubusercontent.com/39550075/114883866-ec920000-9e22-11eb-9f46-c3ca036dacf6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vijay-gowda - Thank you for the feedback. I'm updating the article to remove the inconsistencies.
