### ISSUE TITLE
The classic section says to put conditions in the YAML

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#10530]
![image](https://user-images.githubusercontent.com/15381181/114770925-00156c00-9d3a-11eb-8460-f4414b270260.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by StingyJack** [comment]
@juliakm @TimShererWithAquent  is there a PR attached to this? I don't see one linked.

**Comment by TimShererWithAquent** [comment]
@StingyJack I see a link to a merged PR.

**Comment by StingyJack** [comment]
In the sidebar

![image](https://user-images.githubusercontent.com/15381181/116926327-3ef75d00-ac28-11eb-92b2-beb9c3d02dd7.png)

-------------------------
in the conversation just above our posts

![image](https://user-images.githubusercontent.com/15381181/116926366-474f9800-ac28-11eb-8b07-c0b4771a951e.png)

-----------------

Thats what I see here. Am I really needing new glasses that badly?

I'm expecting to see something like Steve's link .
![image](https://user-images.githubusercontent.com/15381181/116927095-33586600-ac29-11eb-8b82-c861a87cc09a.png)

**Comment by StingyJack** [comment]
@TimShererWithAquent @juliakm - retagging because I don't know if tagging in an edit will notify.

**Comment by TimShererWithAquent** [comment]
@StingyJack Hi Andrew - I see this link in the upper right:

![image](https://user-images.githubusercontent.com/28902327/117158580-63605000-ad74-11eb-8d15-a5d719f7931f.png)

It goes to here: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3136

Is this what you're asking?

@juliakm for awareness.

**Comment by StingyJack** [comment]
I dont see that at all.  Screenshot from ~1 minute ago.
![image](https://user-images.githubusercontent.com/15381181/117170778-4e95b380-ad98-11eb-93a8-4309d4e72c49.png)

**Comment by TimShererWithAquent** [comment]
@StingyJack Oh, maybe it's because it's in a private repo.

@juliakm awareness.

**Comment by StingyJack** [comment]
@TimShererWithAquent - i can fork the repo that is listed for the content source on this issue. 
![image](https://user-images.githubusercontent.com/15381181/117237245-83395780-adf8-11eb-9609-239669e8cf73.png)

The link you shared with the PR is a 404 for me.  This seems like a bug or gap somewhere. I can raise a ticket with GH to try and get an explanation but I think its going to be more appropriate if you or @juliakm follow up on this. At this point I'd just want to satisfy my curiosity, but for MSFT this is probably creating customer confusion elsewhere.

**Comment by juliakm** [comment]
@StingyJack @TimShererWithAquent Apologies for the confusion! This is a challenge with our current PR system. The linked PR (which is in a private repo) removes the YAML references. In case you're curious, it was an include file that was accidentally added to both tabs. 

@StingyJack If you have ideas on what additional information would be helpful here, please feel free to raise a PR. When I looked through a few Classic tasks, I only saw **Control options** for specifying conditions.  

Here's what the [Classic tab](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=classic) looks like now.

![Screen Shot 2021-05-06 at 10 57 29 AM](https://user-images.githubusercontent.com/64906/117320067-e27b8400-ae59-11eb-82ef-faaa44d6c8c7.png)
