### ISSUE TITLE
Title doesn't match content

### ISSUE THREAD

**Issue by M3l3r0** [MicrosoftDocs/azure-devops-docs#10545]
Spanish title of https://docs.microsoft.com/es-es/azure/devops/organizations/billing/billing-faq?view=azure-devops is "Introducción a la facturación de Azure App Service en Azure Stack Hub y preguntas frecuentes" in the billing faq of Azure DevOps Services.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Preguntas frecuentes acerca de la administración de facturación - Azure DevOps](https://docs.microsoft.com/es-es/azure/devops/organizations/billing/billing-faq?view=azure-devops)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/azure-devops-docs-pr.es-ES/blob/live/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley - According to an online translator, the English equivalent to the title is: "Getting started with Azure App Service billing on Azure Stack Hub and FREQUENTLY asked questions"

The English title is "Billing FAQs"

**Comment by chcomley** [comment]
@M3l3r0 Gracias por notificarnos. He creado una solicitud de extracción con la corrección de título. Este problema se cerrará automáticamente una vez que se publique la corrección.
