### ISSUE TITLE
.artifactignore contradicting docs

### ISSUE THREAD

**Issue by mmankos-microsoft** [MicrosoftDocs/azure-devops-docs#10548]
Hello 👋 

A teammate and I were trying to debug `.artifactignore` and seeing how it followed `.gitignore`, we decided to create a simple example with `.gitignore` and get that working. I'm not sure if the artifactignore docs really follow git semantics. 

The example given in the docs 
```sh
**/*
!src/MyApp/bin/Release/**.*
```
says "we instruct the universal package task and the pipeline artifact task to ignore all files except the ones in the src/MyApp/bin/Release directory."

Yet when I tried this on git, it just ignored _all_ files. 

![image](https://user-images.githubusercontent.com/78061887/115058818-a20c9400-9eb3-11eb-9336-e4c1f24350f4.png)

I'm either misunderstanding something or there may be a contradiction in the docs. Either I did something wrong with git in my example, the wildcard pattern the example uses is incorrect, or `.artifactignore` doesn't follow `.gitignore` semantics. 

Seperately - it is probably worth mentioning in the docs "it is required that ignore file must be exacly in the folder where your publishments are, instead of under root". I've seen several people who spent a bit of debugging time only to figure out this was missing. It's not very clear in the docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@mmankos-microsoft Thank you for your feedback! Please make sure that the *.artifactignore* file is in the same directory as the path defined by the `targetPath` of your [Publish Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) task. That's how/when the file is processed by the task
