### ISSUE TITLE
Private and Public are NOT the only options

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/azure-devops-docs#10554]
Please update this documentation to cover all use cases.  For example, Enterprise Visibility is never covered in your documentation, but an important use case.

Please provide details on how this visibility setting impact feeds, scopes, and publishing to those feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thank you for your feedback! Can you elaborate on "enterprise visibility"? We cover different scenarios here: [Configure permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops). I'm closing this issue now but feel free to respond and I can reopen it.
