### ISSUE TITLE
olympic

### ISSUE THREAD

**Issue by masumh** [MicrosoftDocs/azure-devops-docs#10568]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#surface-test-results-in-the-tests-tab)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by masumh** [comment]
i am happy

**Comment by TimShererWithAquent** [comment]
@masumh - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

Or if you're just happy, we'll go with that -
