### ISSUE TITLE
NuGet task versioningSchemes doc section unclear

### ISSUE THREAD

**Issue by regaleagle** [MicrosoftDocs/azure-devops-docs#10563]
Regarding this information in the NuGet task doc about versioningSchemes:

> If you choose 'Use the build number', this will use the build number to version your package. Note: Under Options set the build number format to be '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'.
> Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber

Questions that I wanted to ask:
Where/What is "Options" as referred to in "Under Options set the build number format"?
Why don't I have the ability to set my own custom versioning (like having a pre-release tag) here similar to how I can in setting the whole pipeline name? 

Please make clear where to navigate to in order to answer the first question, for the second, if custom settings are only available through, say, "byEnvVar" please make that clear. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ramiMSFT Could you take a look at this one?

#reassign ramiMSFT
