### ISSUE TITLE
artifact name should mention restrictions

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#10565]
artifact name is documented as it can be anything you like, but `Artifact name is not valid: azure/os1-sandbox. It cannot contain '\', /', "', ':', '<', '>', '|', '*', and '?'` is an error i get, so the docs should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
I am fixing this, thank you for letting us know.
