### ISSUE TITLE
Org Policies - Outdated or incorrect content

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/azure-devops-docs#10574]
The page is showing options as,
![image](https://user-images.githubusercontent.com/39550075/115669941-7a5f7500-a366-11eb-999a-fa18be317f0b.png)

whereas the options actually appearing for me are,

![image](https://user-images.githubusercontent.com/39550075/115670268-daeeb200-a366-11eb-9d48-62f858bbe2dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite guest external users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by MS-alsulli** [comment]
Hi @vijay-gowda are you the PCA in that org? I am checking in **two** of my orgs, and I see "external guest access" in both of them.

Is your organization backed to AAD? If so, do you have permissions in your AAD to invite guests users? I believe this permission isn't appearing due to permissions, either in AAD or Azure DevOps Services itself.

Screenshot from one of my orgs below:
![image](https://user-images.githubusercontent.com/60909919/115793200-b7912a80-a399-11eb-979b-5118f6d0418c.png)

**Comment by vijay-gowda** [comment]
Hi Alec - Thanks for getting back. 

Currently we are not connected to AAD. However, last year one of our PCA made a mistake by connecting our Org to one of our experimental AAD. Most of the members lost access since it was not planned. After few hours we disconnected from AAD. Could this cause this issue? Does that indicate we have not fully got back to earlier state of the Org? What we need to do to address this cleanly? 

Also please note since that incident some of the users UserType field has been showing as below,
![image](https://user-images.githubusercontent.com/39550075/115819629-d97fc100-a41c-11eb-8166-ffcd33f1bd6a.png)

**Comment by MS-alsulli** [comment]
@vijay-gowda This policy will only show up if your org is tied to an AAD tenant. The policy simply allows external users (guests in your tenant, or users from another tenant) to be invited to the org.

If your org isn't linked to an AAD tenant, it won't show the policy. This is expected, please see below screenshot of a personal org that is **not** tied to an AAD - the policy isn't shown (as expected):
![image](https://user-images.githubusercontent.com/60909919/115871086-17291d80-a40e-11eb-9212-23462d64b1fa.png)

**Comment by vijay-gowda** [comment]
Ok it is only applicable for AAD linked Org. Thanks for clarifying.
