### ISSUE TITLE
"feedName", not "organizationName"

### ISSUE THREAD

**Issue by bladewolf55** [MicrosoftDocs/azure-devops-docs#10570]
[Enter feedback here]
pip.ini extra-index-url is showing as
`extra-index-url=https://pkgs.dev.azure.com/<organizationName>/_packaging/<organizationName>/pypi/simple/`

should be

`extra-index-url=https://pkgs.dev.azure.com/<organizationName>/_packaging/<feedName>/pypi/simple/`

"feedName", not "organizationName"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1736d421-eabc-fad7-60af-611d6cdd7050
* Version Independent ID: 0dfd27b1-12ad-1f4b-bd52-5886da18cd2a
* Content: [Publish and consume packages from the CLI - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-cli?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/python-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/quickstarts/python-cli.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@ramiMSFT It looks like there are two instances of this. I guess the issue applies to both -

**Comment by bladewolf55** [comment]
I think so.

**Comment by ramiMSFT** [comment]
@bladewolf55 Thank you for your feedback!
