### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by MarRich1** [MicrosoftDocs/azure-devops-docs#10595]
Is there any reason why the install guide for code search is so hidden that it is almost undetectable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974660d5-3253-709e-84bf-e21ca3a889d8
* Version Independent ID: 26adb3d2-272c-daea-c96a-bad099fd9d99
* Content: [Semantic search - get started - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/get-started-search?view=azure-devops-2020#separate-server)
* Content Source: [docs/project/search/get-started-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/search/get-started-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@MarRich1 - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

**Comment by MarRich1** [comment]
This one:
https://docs.microsoft.com/en-us/azure/devops/project/search/install-configure-search?view=azure-devops-2020

I tried to google it, but I wasn't able to find it. All google links lead me to

https://docs.microsoft.com/en-us/azure/devops/project/search/get-started-search?view=azure-devops

I know you can´t change google, but it looks to me that all links where forwarded from your site to the 2nd mentioned url

With best regards,
Markus Richtsfeld

Siemens Healthcare GmbH
Information Technology
Product Lifecycle Excellence
Development Platform Services
SHS IT LE ALM D
Siemensstr. 3
91301 Forchheim, Germany
Mobile: +49 1522 1828294
***@***.***
***@***.***D73AD5.83DB4770]
Siemens Healthcare GmbH: Management: Bernhard Montag, President and Chief Executive Officer; Darleen Caron, Jochen Schmitz, Christoph Zindel; Chairman of the Supervisory Board: Ralf P. Thomas; Registered office: Munich, Germany; Commercial Registry: Munich, HRB 213821 WEEE-Reg.-No. DE 64872105

Important notice: This e-mail and any attachment thereof contain corporate proprietary information. If you have received it by mistake, please notify us immediately by reply e-mail and delete this e-mail and its attachments from your system. Thank you.

**Comment by KathrynEE** [comment]
@chcomley - Can you look at this. Installing code search needs to be enabled for Azure DevOps Services as well as on-prem.

**Comment by chcomley** [comment]
Hi @MarRich1, Thanks for alerting us. I've added some metadata and updated a versioning header, so hoping this helps. This issue will automatically close when the PR gets published. Thanks again!
