### ISSUE TITLE
No documentation for section Services

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-devops-docs#10593]
Word `services` is mentioned only twice in the article. Here's all what it says: 

```yaml
services: { string: string | container } # container resources to run as a service container
```

There is no more documentation or clarification what it does or how it works whatsoever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by abatishchev** [comment]
hi @steved0x, pig on this issue, please.

**Comment by abatishchev** [comment]
hi @steved0x, ping on this issue, please.

**Comment by abatishchev** [comment]
hi @steved0x, ping on this issue, please.

**Comment by steved0x** [comment]
I'm closing this and moving it to an internal bug that I am tracking here: AB#1842392 and will update the docs once I have more information.

**Comment by juliakm** [comment]
@abatishchev The `services` keyword is a way of networking together containers. You can find more information in our [service container article](https://docs.microsoft.com/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#single-container-job). We're working on a way to include this in the schema.
