### ISSUE TITLE
Software dependencies not exact enough

### ISSUE THREAD

**Issue by MarRich1** [MicrosoftDocs/azure-devops-docs#10596]
Maybe it would be nice to mention that the search is only working with the Java version 8
Tried newer one but none of them worked, only the 8
Is there a plan to enable this also for newer versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b81d598-df12-9ef1-9821-71f240b5d0e9
* Version Independent ID: 9814578c-72d2-d0da-a0fb-051eab0b9bd9
* Content: [Install, configure Search - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/install-configure-search?view=azure-devops-2020)
* Content Source: [docs/project/search/install-configure-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/search/install-configure-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chcomley - please look at this issue as well and update the metadata for ms.author and author.

**Comment by chcomley** [comment]
Hi @MarRich1, Thanks for reaching out. I've updated the article and specified the version of Java as 8.
Once the PR is published, this issue will automatically be closed. Thanks again.
