### ISSUE TITLE
NodeJS tfx extension publisher command does not exist in tfx-cli v0.9.2

### ISSUE THREAD

**Issue by FilBot3** [MicrosoftDocs/azure-devops-docs#10600]
# The information

Following the [Publish from commandline](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line) documentation, it lists that `tfx extension publisher` should be a sub-command available. However, this is not the case. The output listed is...

```bash
node@7b663a415155:/workspaces/company_rfc_azdo$ npx tfx extension --help          
(node:9871) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
TFS Cross Platform Command Line Interface v0.9.2
Copyright Microsoft Corporation

Available commands and command groups in tfx / extension:
 - create: Create a vsix package for an extension.
 - init: Initialize a directory for development of a new Azure DevOps extension.
 - install: Install a Azure DevOps Extension to a list of Azure DevOps Organizations.
 - publish: Publish a Visual Studio Marketplace Extension.
 - isvalid: Show the validation status of a given extension.
 - share: Share an Azure DevOps Extension with Azure DevOps Organizations.
 - show: Show info about a published Azure DevOps Services Extension.
 - unpublish: Unpublish (delete) an extension from the Marketplace.
 - unshare: Unshare a Azure Devops Extension with Azure DevOps Organizations.
 - resources: Commands for working with localization of extensions.


For help with an individual command, type tfx extension <command> --help
```

Upon going to the [npmjs/tfx-cli](https://www.npmjs.com/package/tfx-cli) package information site, it mentions using the Python Azure DevOps extensions. The documentation should be updated to reflect this change, or show both options.

I am also using a Container to do this development: `docker.io/library/node:15.14.0-buster`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2914b5-105a-32f7-c7be-5f1604775f61
* Version Independent ID: 0070cd88-c1f7-6a69-ef9c-fb5b4f3b8544
* Content: [Publishing and packaging an extension from the Command Line - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line?view=azure-devops)
* Content Source: [docs/extend/publish/command-line.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/publish/command-line.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ramiMSFT** [comment]
@FilBot3 Thank you for your feedback! Try this instead:

```
tfx extension publish --publisher <YOUR_PUBLISHER_ID> --manifest-js <YOUR_EXTENSION_MANIFEST> --share-with <ACCOUNT_NAME>
```
The `Accessing non-existent property 'padLevels'...` error is a compatibility issue with some node versions. Reference: [360](https://github.com/microsoft/tfs-cli/issues/360), [1077](https://github.com/foreversd/forever/issues/1077)
