### ISSUE TITLE
QueryExector 414 URI Too Long

### ISSUE THREAD

**Issue by zesameri** [MicrosoftDocs/azure-devops-docs#10602]
The request to get the work items is returning a 414. Here is the line of code I'm referring to: in the QueryOpenBugs method
`// get work items for the ids found in the query`
`return await httpClient.GetWorkItemsAsync(ids, fields, result.AsOf).ConfigureAwait(false);`

 Not sure if you want to update the code to use the GetWorkItemsBatchAsync method instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/quickstarts/work-item-quickstart?view=azure-devops)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/quickstarts/work-item-quickstart.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @zesameri, Thanks so much for your feedback. I've updated the article, based on your recommendation.
