### ISSUE TITLE
OData Queries aren't correct

### ISSUE THREAD

**Issue by grjohnston** [MicrosoftDocs/azure-devops-docs#10613]
The Odata queries in the samples are not properly formed for any of the Pipeline tests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b5ce20-40e9-3f32-fd63-3c6980ac4929
* Version Independent ID: eb6d654d-d773-b1ef-c03b-494f7e8a48bc
* Content: [Pipeline test summary sample Power BI reports - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-test-analytics-test-summary?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-test-analytics-test-summary.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-test-analytics-test-summary.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaghai**

**Comment by KathrynEE** [comment]
@grjohnston - Thank you for your feedback. I'm contacting the product team to request an update. Could you provide more details as to how the examples aren't working for you?

**Comment by KathrynEE** [comment]
@grjohnston - Closing this issue. Articles have been updated with the correct query syntax.
