### ISSUE TITLE
Missing example code of Key Vault Secret usage in pipeline

### ISSUE THREAD

**Issue by cima** [MicrosoftDocs/azure-devops-docs#10610]
This article has several insufficiencies:
* Step 6 in section #set-up-azure-key-vault-access-policies correctly instructs to setup policy but completely lack any clue which principal to slect. I have figured out that Azure Devops, but newbies might get lost.
* Step5 in section #create-a-new-pipeline is completely missing code demonstrating the usage of secrets from keyault
* Section #run-and-review-the-pipeline demonstrates that the secret traveled into pipeline execution but teaches people bad security practice on smuggling secrets. Exporting a checksum (SHA-1) of the secret variable and then demonstrating that SHA-1 of stored variable matches. By exporting checksums you don't have to change that secret after every debugging becuase of the artifacts containing them are laying all over the place.

Hint: the article should focus on utilizing secrets from keyvault but overwhelms reader with az commands. Showing couple of screenshots how Key Vault is create in web interface of portal.azure.com would be more convenient for reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Use Azure Key Vault secrets in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@cima Thank you for your feedback! The updated article will go live shortly. This tutorial is for education purposes only. For security best practices and how to safely work with secrets, see [Manage secrets in your server apps with Azure Key Vault](https://docs.microsoft.com/en-us/learn/modules/manage-secrets-with-azure-key-vault/).
