### ISSUE TITLE
Card customization does not allow for Style rule with Rule criteria Parent is Empty.

### ISSUE THREAD

**Issue by mousetwentytwo** [MicrosoftDocs/azure-devops-docs#10617]
Card customization does not allow for Style rule with Rule criteria Parent is Empty.
Field is selectable, but no operator is valid for it.
Please let me mark tickets on the board which are missing parent work items.

![image](https://user-images.githubusercontent.com/8767409/116446013-cfaff080-a856-11eb-824b-e2825947dd35.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6d2e51-6c3e-512a-0fcb-5141c0290663
* Version Independent ID: a25c921a-6ec4-eeed-fa93-1105d4444408
* Content: [Customize cards on a board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/customize-cards?view=azure-devops)
* Content Source: [docs/boards/boards/customize-cards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/boards/customize-cards.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mousetwentytwo - Thank you for the feedback.  To request an unsupported feature, please go to our [Developer Community page](https://developercommunity.visualstudio.com/search?space=21). I'll update the article to clarify that the Parent field can't be selected for Style rules.
