### ISSUE TITLE
Dockerfile line 18 missing \ (German translation)

### ISSUE THREAD

**Issue by schrotie** [MicrosoftDocs/azure-devops-docs#10636]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by TimShererWithAquent** [comment]
@schrotie Please let us know which article you're looking at and any other information you think might be helpful.

**Comment by schrotie** [comment]
Hi, very sorry, didn't check, I assumed the report would be somehow specific to the affected page. It's this one: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux (it's in at least English and German).

**Comment by steved0x** [comment]
@schrotie Thanks for letting us know, I will report this to our localization team and get it fixed.

**Comment by steved0x** [comment]
@schrotie Is it this one? If so it is missing in the English version as well - I will fix it there and that way all of the translations will get the fix.

![image](https://user-images.githubusercontent.com/1580889/117349674-abb56600-ae79-11eb-962f-ef0c30906412.png)
