### ISSUE TITLE
You can also map secret variables using the variables definition. This example shows how to use secret variables $(vmsUser) and $(vmsAdminPass) in an Azure file copy task.

### ISSUE THREAD

**Issue by CarlosAugustoDeSouzaJunior** [MicrosoftDocs/azure-devops-docs#10633]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by CarlosAugustoDeSouzaJunior** [comment]
I think you should tell that ...**When you are not using inline scripts**, you can refer to secret variable as you described. other wise is a little confusing.

**Comment by juliakm** [comment]
Thanks @CarlosAugustoDeSouzaJunior! I'll update the article to make this clearer today.
