### ISSUE TITLE
Passing Between Stages Is Not correct

### ISSUE THREAD

**Issue by dirtygooback** [MicrosoftDocs/azure-devops-docs#10637]
The example for passing a variable from a deployment task across stages is incorrect as is. However, even with the proper syntax it still does not work. Please update the example with a working way to pass vars between a deployment job and a stage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@dirtygooback Thanks for your question - Is there a specific error in the example? What error do you get attempt it? Any additional information could be helpful.

**Comment by juliakm** [comment]
I believe that this was solved in this commit: https://github.com/MicrosoftDocs/azure-devops-docs/commit/b2a87addbb2095c9af2d24e99d449fe396dbb90d
