### ISSUE TITLE
Battle of AzureResourceManagerTemplateDeployment and AzureResourceGroupDeployment

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/azure-devops-docs#10640]
Documentation(=the page I opened a bug report for) describes the usage of AzureResourceGroupDeployment task. But as far as I know this task is not available in the YAML pipeline UI at all.

UI display AzureResourceManagerTemplateDeployment task with a name ARM template deployment but the only documentation available for that task is task's Github README file. (Where is the documentation including YAML snippet?)

Which one is now the recommended one and why one is missing documentation and one is not available in the UI?

If tasks are supposed to share a common set of inputs then 

-documentation on the docs site should mention names of the BOTH tasks
- `About this task` link in the UI should be updated to ship YAML documentation for both tasks.

ref: https://github.com/MicrosoftDocs/azure-devops-docs/issues/7122

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by psfinaki** [comment]
Yes this whole thing is very confusing and the GitHub README for the AzureResourceManagerTemplateDeployment task is not something that can be called documentation, it doesn't even have a sample there, as mentioned.

**Comment by daemoneon** [comment]
So... who wins?

**Comment by jikuja** [comment]
I'm already using AzurePowerShell/AzureCLI tasks instead of multiple built-in tasks.

Fewer bugs, fewer documentation errors, handles updates faster.

This and delays with Bicep support made this task useless for me

**Comment by steved0x** [comment]
Both of these tasks are documented here in the new task reference:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.

**Comment by jikuja** [comment]
Cool.

One piece of feedback: currently there is no feature parity with template types those tasks support:
* AzureResourceGroupDeployment@2 support only ARM
* AzureResourceManagerTemplateDeployment@3 supports both ARM and bicep.

AzureResourceManagerTemplateDeploymentV3 task itself mentions bicep on parameter documentions: https://github.com/microsoft/azure-pipelines-tasks/blob/4718ac9183db21ba1e7526dea31dfb4ac9e67679/Tasks/AzureResourceManagerTemplateDeploymentV3/task.json#L156-L175

I wonder if bicep support should be mentioned or not.
