### ISSUE TITLE
Wrong variable name for Release.SkipArtifactsDownload

### ISSUE THREAD

**Issue by NF-Floyd** [MicrosoftDocs/azure-devops-docs#10646]
The name of the variable in section [Default variables - Release](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?tabs=batch&view=azure-devops#default-variables---release) should be "Release.SkipArtifactsDownload" (plural Artifacts) instead of "Release.SkipArtifactDownload"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 810b2ae0-ebbc-9fe0-fabb-700a57f20c9d
* Version Independent ID: 3ba38edc-4990-5ef5-c10e-79f1be686d3f
* Content: [Classic release and artifacts variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops-2020&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by shashban** [comment]
thanks for the feedback. A fix for this has been queued and should be live soon
