### ISSUE TITLE
Missing information about integration of Azure DevOps and Microsoft Teams

### ISSUE THREAD

**Issue by fabioharams** [MicrosoftDocs/azure-devops-docs#10657]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@fabioharams - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please provide more context around the general task.

**Comment by fabioharams** [comment]
This is an example about: Microsoft Teams with Azure DevOps Services (Collaborate, Communicate and Celebrate)

Link: https://azuredevopslabs.com/labs/vstsextend/teams/

This lab demonstrate how to use Microsoft Teams with Azure DevOps and I believe that is important just to mention on article tha Microsoft Teams could work together with Azure DevOps

**Comment by KathrynEE** [comment]
@fabioharams  - Thank you for this feedback. I agree and will update the article with the missing information, and include any additional clients that have been supported and aren't currently represented. I've added a user story to my backlog.
