### ISSUE TITLE
Old/bad instructions for removing project admin

### ISSUE THREAD

**Issue by neillindberg** [MicrosoftDocs/azure-devops-docs#10654]
[Enter feedback here]
There's no such ability to remove project admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add, remove team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@neillindberg - Are you asking if there is a way to remove a Project Administrator from being a team administrator? If so, the answer is no. All members of the Project Administrators security group have full permissions to manage and configure team settings. There's no way to remove those previliges.
