### ISSUE TITLE
In the headline there is one comma to much

### ISSUE THREAD

**Issue by GiuseppeSama** [MicrosoftDocs/azure-devops-docs#10655]
Hi,

This is my first issue im writing, so please bare with me :)

I think there is one comma to much in the headline:

The current headline is:
### About area paths, feature teams, and management teams

But shouldn't it be?
### About area paths, feature teams and management teams

This is the original link:
https://docs.microsoft.com/en-us/azure/devops/organizations/settings/about-teams-and-settings?view=azure-devops

BR Giuseppe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9452f-cace-54cc-a4e2-71add32baab3
* Version Independent ID: 681f7c2e-e24a-9bd9-ee3e-c7ec5ad96b15
* Content: [About teams & Agile tools - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/about-teams-and-settings?view=azure-devops)
* Content Source: [docs/organizations/settings/about-teams-and-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/about-teams-and-settings.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@GiuseppeSama Thanks for your question. Our style guide uses the Oxford or serial comma. I don't see anything in this context that would be different.

**Comment by TimShererWithAquent** [comment]
@GiuseppeSama You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

**Comment by GiuseppeSama** [comment]
Hi,
thanks for the advise :)
