### ISSUE TITLE
reconcile command is missing

### ISSUE THREAD

**Issue by ayeltsov** [MicrosoftDocs/azure-devops-docs#1066]
Unable to find documentation for reconcile command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052ab215-efa4-8cd6-fa3c-f08f8015b881
* Version Independent ID: 3aac0244-74a6-070a-dafe-f246aaad699c
* Content: [Use Team Foundation version control commands](https://docs.microsoft.com/en-us/vsts/tfvc/use-team-foundation-version-control-commands?view=vsts)
* Content Source: [docs/tfvc/use-team-foundation-version-control-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/tfvc/use-team-foundation-version-control-commands.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan
