### ISSUE TITLE
Fail Copy task if no files are matched

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/azure-devops-docs#10678]
The docs say this in the notes section:

> If no files are matched, the task will still report success.

I can't be the only person who would like the copy task to fail if no files are matched, so the docs having a suggestion on how to achieve this would benefit all of us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I agree that this sounds like a good option to have. Please file a feature request here for that task: https://github.com/microsoft/azure-pipelines-tasks
