### ISSUE TITLE
Docs do not specify allowable values for "default:" parameter values

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/azure-devops-docs#10672]
[Enter feedback here]
The documentation as written shows 28 examples of "default:" parameter values expressed as literals. It is implied, possibly incorrectly, through these examples that *only* literal expressions are allowed for parameter default values. If that is the case, then docs should clear state that limitation. If not the case, docs should specify the types of expressions (e.g. compile/run-time/variables) that are allowed and provide examples of each usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I've confirmed that only literals are allowed and will update the article.
