### ISSUE TITLE
Limitation for 10 branches not clear

### ISSUE THREAD

**Issue by eddie-zalar** [MicrosoftDocs/azure-devops-docs#10681]
Hi,

the last note in the section "Publish a Git repository to a wiki" states:

> You're limited to publishing 10 branches as code wikis.

What does this mean?
* 10 branches per published wiki?
* 10 published wiki's in total?

Please consider to rephrase to be more specific.

Thanks
Eddie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @eddie-zalar, I'll look into this and publish an update. Once complete, this issue will automatically close. Thanks!

**Comment by CameronBieganek** [comment]
@chcomley The updated text is as follows:

> You can publish up to 10 total wikis.

I still find that to be ambiguous. I still don't know which of the following it means:

- 10 branches per published wiki
- 10 published wikis per team project

Can you clarify which of those it is?

**Comment by chcomley** [comment]
Hi @CameronBieganek, Thanks for your patience on this. I've just heard back and am updating the article. You can publish up to 10 branches per code repository. Thanks!

**Comment by CameronBieganek** [comment]
Thanks!
