### ISSUE TITLE
Virtual machine scale set created via tutorial is missing Azure DevOps build dependencies

### ISSUE THREAD

**Issue by ColeSiegelTR** [MicrosoftDocs/azure-devops-docs#10687]
I followed the tutorial here - https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md

After attempting to use this virtual machine scale set with standard Azure DevOps tasks such as `DotNetCoreCLI@2` or `Docker@2` I find that the build dependencies `docker` and `dotnet` are missing.

What is the recommended approach? Is it expected that despite having the extension `Microsoft.Azure.DevOps.Pipelines.Agent | Microsoft.VisualStudio.Services.TeamServicesAgentLinux` installed on the vmss agent pool, I cannot perform out-of-the-box ADO tasks?

Not clear what is missing, please help to improve the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ColeSiegelTR Scale set agents are similar to other self-hosted agents - besides the agent software that is installed when configuring the agent, all other required software is installed by the user/admin that configures the agent. So for your example, with `DotNetCoreCLI@2` or `Docker@2`, you could either use the [tool installers](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#tool-installers) in your pipeline, or you could [pre-install the desired tools and frameworks onto the VM image](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-scale-set-with-custom-image-software-or-disk-size) before configuring the scale set agent pool to use that image.

I just went looking through that article and I see that is not very clear - I will make an update to clarify this, and it will be live soon, possibly as early as today.

Thank you,

Steve
