### ISSUE TITLE
Azure Artifacts - maximum limit of a package version

### ISSUE THREAD

**Issue by yauhen-l** [MicrosoftDocs/azure-devops-docs#10695]
Maximum version length is not covered by this page. We get error: "400 Bad Request - The package version is too long" which is very annoying and there is no evidence of what is a limitation.
People complain in the internet as well:
- https://developercommunity.visualstudio.com/t/http400-bad-request-the-package-version-is-too-lon/406288
- https://developercommunity.visualstudio.com/t/authenticate-maven-with-artifact-feed/387890
- https://stackoverflow.com/questions/63023330/the-package-version-is-too-long

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114bd05d-0737-79af-9446-41d87cdc3943
* Version Independent ID: 8396a896-9cbb-78ac-7ec4-9b6046a3e09f
* Content: [Size and count limits in Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops)
* Content Source: [docs/artifacts/reference/limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/reference/limits.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@yauhen-l Thank you for your feedback! The versioning process does not allow a one size fits all approach. The original string gets manipulated twice internally. First it gets converted into its canonical representation and then encoded to be ordered later.

**Comment by yauhen-l** [comment]
Hi @ramiMSFT ,
I don't understand your reasoning in closing this issue.
The two manipulations of the original version bring some constraints so you have to explain what these manipulations are (algorithms and examples) and how to avoid these constraints.
We constantly hit this constrains for short versions and for long versions and it is not possible to understand empirically how to proceed.
Please, re-open the issue.
