### ISSUE TITLE
Is it possible to edit the YAML in a release pipeline?

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/azure-devops-docs#10698]
Thank you very much for this excellent page on defining variables in an Azure Pipeline! This is very helpful.

I have a question about implementing this in an Azure Release Pipeline. In the section titled "Reference secret variables in variable groups" I tried to reference a variable group I defined in the Pipeline Library area. However, I couldn't find any way to edit the YAML. for the stage or job to declare the variable group and reference it as was done in that section with this code

```yaml
env:
  MY_MAPPED_TOKEN: $(token) # Maps the secret variable $(token) from my-var-group
```

Is that not possible when working with a release pipeline in Azure DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Hi @Rod-in-NM. For release pipelines, you'll want the Classic instructions. Please check out the [Use a variable group section](https://docs.microsoft.comazure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic#use-a-variable-group) in our Variables group editor. 

If you'd like you switch and use a YAML pipeline instead, here's our article on how to [migrate your classic pipeline to YAML](https://docs.microsoft.com/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops).
