### ISSUE TITLE
ADO CLI marked as supported for Server 2020

### ISSUE THREAD

**Issue by gauravsaralMs** [MicrosoftDocs/azure-devops-docs#10704]
👋🏼 seems like ADO CLI in this page https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops is incorrectly marked to be supporting ADO Server 2020.

I have only seen statement seeing that CLI is not supported for [ADO server 2019](https://github.com/Azure/azure-devops-cli-extension/issues/666#issuecomment-502097018).

In case I am missing something where CLI support was added for ADO server 2020 then do let me know.

cc: @KathrynEE

**Comment by KathrynEE** [comment]
@gauravsaralMs - Azure CLI supports Azure DevOps Server 2020. It was added with the [RTW release](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2020?view=azure-devops#general).
