### ISSUE TITLE
Environment variable names missing (e.g. "BUILD_ARTIFACTSTAGINGDIRECTORY")

### ISSUE THREAD

**Issue by craigsmitham** [MicrosoftDocs/azure-devops-docs#10700]
Many of the predefined variables are available as environment variables (as mentioned in the doc). However, they do not mention what casing/style to use when referencing the environment variable. For example, `Build.ArtfactStagingDirectory` should be referenced as `BUILD_ARTIFACTSTAGINGDIRECTORY` when it is used as an environment variables. Some variables in this doc make note of it, others do not. It would be helpful for this to be clear for every variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @craigsmitham! A doc update will be live today.
