### ISSUE TITLE
[LOC]Back-Translation "az ml 実験リスト"→"az ml experiment list" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10712]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml"
![azure-machine-learning_j](https://user-images.githubusercontent.com/40815708/118074347-a95a8b00-b3e8-11eb-80b7-b5b75419a82e.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml"
![azure-machine-learning_e](https://user-images.githubusercontent.com/40815708/118074353-ab244e80-b3e8-11eb-8879-6ba80c2faa0e.png)

#PingMSFTDocs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [データパイプライン、自動トレーニング、機械学習モデルのデプロイ - Azure Pipelines](https://docs.microsoft.com/ja-jp/azure/devops/pipelines/targets/azure-machine-learning?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/azure-devops-docs-pr.ja-JP/blob/live/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@hyoshioka0128 Thanks for finding this.
