### ISSUE TITLE
Provide an example of a customized process 

### ISSUE THREAD

**Issue by mmisqe** [MicrosoftDocs/azure-devops-docs#10719]
Please consider to include an example of a customized workflow with restricted state transitions. 
Example: show a user story where an "Active" can only move to "Resolved", and "Closed" can not move to any state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops#view-the-state-workflow-model)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mmisqe - Thank you for your request for an example. I've added this to my backlog of work and will address it within the coming weeks.
