### ISSUE TITLE
Delivery Plans - "Open a Plan" section of the age contains an outof date term and screenshot

### ISSUE THREAD

**Issue by asos-paulthorpe** [MicrosoftDocs/azure-devops-docs#10718]
The "Open a Plan" section of the age contains an out-of-date term and screenshot.  The documentation refers says "To open a plan, open Boards>Delivery Plans" it should be "To open a plan, open Boards>Plans". The screenshot shows "Delivery Plans" as a menu item under "Boards".  The screenshot should show "Plans" as a menu item under "Boards".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@asos-paulthorpe - Thank you for your feedback. However, the section is correct as wrriten. [Delivery Plans  2.0 is now GA](https://devblogs.microsoft.com/devops/delivery-plans-2-0-is-now-ga/). The updates will be rolling out to all organizations over the next 2 weeks. The old Delivery Plans based on the extension is still documented here: [Delivery Plans 1.0 Marketplace extension](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/delivery-plans?view=azure-devops).
