### ISSUE TITLE
Accepting all of npm init's default options does not work anymore

### ISSUE THREAD

**Issue by FurcyPin** [MicrosoftDocs/azure-devops-docs#10726]
While following the instruction in steps 1

> From within your buildAndReleaseTask folder, run the following command:
> ```
> npm init
> ```
> npm init creates the package.json file. You can accept all of the default npm init options.

I got the following error message:

```
name: (buildAndReleaseTask) 
Sorry, name can no longer contain capital letters.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @FurcyPin, My apologies for the delayed response. Are you still experiencing this? If so, what version of npm are you using? And are you creating a task or updating an existing one? Thanks so much.

**Comment by FurcyPin** [comment]
Hi @chcomley, my apologies, I should have documented what version of npm I was using.

It looks like the problem is gone with the most recent stable release of npm (6.14.13).
I tried again with this version and the folder name is automatically cast in lowercase to chose the default package name. 

Given that Node's package names only support lowercase, I would suggest renaming 
the example folder `buildAndReleaseTask` to lowercase `buildandreleasetask` in the documentation.

Thanks for your time.

**Comment by chcomley** [comment]
Hi @FurcyPin, thanks for the info. I've just published an update to the doc per your suggestion. Have a great day!
