### ISSUE TITLE
[LOC]Back-Translation "Azure パイプライン"→"Azure Pipelines" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10724]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops"
![scale-set-agents_j](https://user-images.githubusercontent.com/40815708/118217085-b8f0d700-b4af-11eb-8d1b-941984961833.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops"
![scale-set-agents_e](https://user-images.githubusercontent.com/40815708/118217096-bc845e00-b4af-11eb-9e50-8c15000bfa75.png)

#PingMSFTDocs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
This looks like a capitalization issue. "Azure Pipelines" is not translated (as a product name) elsewhere in the article, but this instance is "Azure pipelines" -

**Comment by hyoshioka0128** [comment]
related: https://github.com/MicrosoftDocs/azure-devops-docs/pull/10723 (capitalized - merged)
