### ISSUE TITLE
[LOC]Fixed inappropriate japanese "レポポ"→"リポジトリ" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10734]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/packages/nuget-restore?view=azure-devops"
![nuget-restore_j](https://user-images.githubusercontent.com/40815708/118383932-5f1e1780-b63d-11eb-91ad-c68e4a7719e7.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops"
![nuget-restore_e](https://user-images.githubusercontent.com/40815708/118383929-5c232700-b63d-11eb-9815-9ff582feb521.png)

#PingMSFTDocs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78a9f20-b8d2-4aa7-c52d-a968ab87315d
* Version Independent ID: 3880a787-8f70-8c13-176e-c732b619fb06
* Content: [Restore NuGet packages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/packages/nuget-restore.md)
* Product: **devops**
* Technology: **devops-cicd-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
The term "repository" is used elsewhere in the article. I'll change the one instance of "repo" to "repository".
