### ISSUE TITLE
[LOC]Fixed inappropriate japanese "レポポ"→"リポジトリ" (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10733]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops"
![utility_delete-files_j](https://user-images.githubusercontent.com/40815708/118383767-f7b39800-b63b-11eb-9bc6-57289513e326.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops"
![utility_delete-files_e](https://user-images.githubusercontent.com/40815708/118383771-fc784c00-b63b-11eb-89de-7dcacaba45cb.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Same issue in other article: MicrosoftDocs/azure-devops-docs/issues/10734
