### ISSUE TITLE
Step 2: Add the public key to Azure DevOps Services/TFS is out of date

### ISSUE THREAD

**Issue by DaveVoyles** [MicrosoftDocs/azure-devops-docs#10748]
In **Step 2: Add the public key to Azure DevOps Services/TFS**, the image shows:

![image](https://user-images.githubusercontent.com/1786053/118539822-e642bc80-b71d-11eb-9bc8-2166c7ba01b7.png)

However, that "New Key" button is no longer present in the current version of Azure Dev Ops. 

This is what it looks like at the moment:
![image](https://user-images.githubusercontent.com/1786053/118539731-c4493a00-b71d-11eb-8290-9d256b62d60d.png)

And therefore, a new public key cannot be generated. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Seems like the screen cap is out of date. I don't see the New Key button either.

**Comment by DaveVoyles** [comment]
As an alternative, I've learned that you don't actually need that button. Users can skip this step completely.

in the prior step, when generating your private SSH key with the `ssh-keygen` command within the `bash` prompt, you can copy the public key as well. 

`pbcopy < ~/.ssh/id_rsa.pub`

From there, the user can paste the key into Azure DevOps, as seen in step 3:

_"Copy the contents of the public key (for example, id_rsa.pub) that you generated into the Public Key Data field."_

 and proceed to pull down the repo.
