### ISSUE TITLE
Request to explicitly add that on stages, the MS agent will be discarded a new 1 used

### ISSUE THREAD

**Issue by rforster-dev** [MicrosoftDocs/azure-devops-docs#10752]
I think it would be really helpful to explicitly state that if you are using MS hosted agents, and your pipeline is split into stages, that the VM will be discarded and a new 1 used for each stage.

I have spent half a day trying to work out why my build isnt working and its because the VM is different on the stages...

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rforster-dev Sorry that you ran into trouble, I will make an update that article to specifically call that out. When using Microsoft-hosted agents, each job runs on a fresh agent virtual machine instance. So each job in the same stage will each get a fresh agent, and that applies to jobs spread across multiple agents. I will do a sweep and ensure this is called out in multiple places with regard to jobs and stages. Thank you for letting us know.

**Comment by rforster-dev** [comment]
Thanks for the updates looks good. It's one of those "gotchas" I imagine!

Cheers
