### ISSUE TITLE
Misspelling of 'Build.ArtifactStagingDirectory'

### ISSUE THREAD

**Issue by Loreno10** [MicrosoftDocs/azure-devops-docs#10762]
In the beginning of the article there is the following part:
> In YAML pipelines, you can reference predefined variables as environment variables. For example, the variable **Build.ArtfactStagingDirectory** becomes the variable BUILD_ARTIFACTSTAGINGDIRECTORY.

"Build.ArtfactStagingDirectory" should be changed to "Build.ArtifactStagingDirectory"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Loreno10** [comment]
I provided a PR: https://github.com/MicrosoftDocs/azure-devops-docs/pull/10763

**Comment by TimShererWithAquent** [comment]
@Loreno10 Thanks!

**Comment by juliakm** [comment]
Fixed with PR.
