### ISSUE TITLE
How to set upstream behavior in Azure Devops website? and How to update package version after set the allow external source versioning?

### ISSUE THREAD

**Issue by richieteh94** [MicrosoftDocs/azure-devops-docs#10761]
I saw there is a way to configure upstream behavior for an individual package in Azure DevOps but there is no way to change every package in the upstream to allow external source versioning. Please provide a way to do so and also there is no way to update the package version after configured to allow an external source versioning. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb8c20-fe29-a60c-dd6c-45c9e8278162
* Version Independent ID: ca24cdd8-dc94-6339-e2ef-95e5a84fa877
* Content: [Configure upstream behavior - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?preserve-view=true&tabs=npm&view=azure-devops#allow-external-versions)
* Content Source: [docs/artifacts/concepts/upstream-behavior.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/upstream-behavior.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@richieteh94 - Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
