### ISSUE TITLE
typo under Query-based dashboard widgets

### ISSUE THREAD

**Issue by tommyreinsmsft** [MicrosoftDocs/azure-devops-docs#10760]
There's a stray letter "m" in the section under Query-based dashboard widgets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedfad16-7c61-78e7-5470-39f835209383
* Version Independent ID: 5a3a4d49-e0d8-0b86-fc9a-4e3392967ea7
* Content: [Query support for cross-service, integration, and extensions - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-support-integration-cross-service-extensions?view=azure-devops)
* Content Source: [docs/boards/queries/query-support-integration-cross-service-extensions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/query-support-integration-cross-service-extensions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
Thanks @tommyreinsmsft
