### ISSUE TITLE
Clarify variable groups, secure files, and agent pools protected resources

### ISSUE THREAD

**Issue by poltj18** [MicrosoftDocs/azure-devops-docs#10776]
The documentation lists the following resources as "protected":
- variable groups
- secure files
- agent pools

The documentation notes that "protected" means:

_"You can run additional manual or automated checks every time a pipeline uses one of these resources."_

However, variable groups, secure files, and agent pools do not support "checks".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40fccec-c358-843c-10d5-7ea367f6e406
* Version Independent ID: 45390d5d-c1d7-c90e-ef3f-2768d406ba7b
* Content: [Pipeline resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/resources?view=azure-devops)
* Content Source: [docs/pipelines/security/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/resources.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@poltj18 Thanks for pointing this out. Variable groups, secure files, and agent pools support checks in a recent update. You can see a detailed overview of permissions in the [About resources article](https://docs.microsoft.com/azure/devops/pipelines/process/about-resources?view=azure-devops&tabs=yaml#use-resources-to-enhance-security). I'll add a link to it from this one.
