### ISSUE TITLE
Unclear documentation regarding pipeline definition source branch when using pipeline triggers

### ISSUE THREAD

**Issue by D4N14L** [MicrosoftDocs/azure-devops-docs#10778]
The linked page contains the following text:
`If the two pipelines are in the same repository, the triggered pipeline version in the same branch as the triggering pipeline is run, even if that branch is different than the Default branch for manual and scheduled builds, and even if that version does not have branch filters that match the completed pipeline's branch.`

This is accurate. However, I feel like the text should be clarified to point out that it will use the pipeline definitions specified in that branch *as of runtime*. This distinction is important because it is possible to get triggered runs that fail due to pipeline definitions being sourced from the target branch rather than the triggering pipeline source version.

For example, shortly after modifying the pipeline definitions in our `main` branch, a pipeline that was already running a build on `main` finished and triggered another pipeline using pipeline triggers. This triggered run sourced their pipeline definitions directly from `main` instead of from the source version that the triggering build performed with, causing it to fail (new definitions expected certain assets to be produced in the triggering pipeline, which were not present).

While I personally think this is an issue with how the pipeline triggers function (and would be resolved by sourcing the pipeline definitions from the source version), the documentation should be updated to clarify this pitfall of pipeline triggers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
investigating

**Comment by steved0x** [comment]
Agreed and this is fixed.
