### ISSUE TITLE
Broken Link - Release Flow

### ISSUE THREAD

**Issue by murraj** [MicrosoftDocs/azure-devops-docs#10777]
The following link from this page to the following is broken: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow.

**Comment by WilliamAntonRohm** [comment]
@murraj -- thank you for your feedback, and I as well see that link as a 404.  Please clarify the source page.

**Comment by murraj** [comment]
Sorry about that.  The source page is https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops.


Jeff Murray
Information Technology
William Blair
The William Blair Building | 150 North Riverside Plaza, Chicago, Illinois 60606
+1 312 364 8520 direct
***@***.******@***.***> | williamblair.com<http://www.williamblair.com/>
Facebook<https://www.facebook.com/WilliamBlairCo/> | LinkedIn<https://www.linkedin.com/company/166939> | YouTube<https://www.youtube.com/channel/UC7CPnCaTlZcLxOF7WFwY0uw> | Twitter<https://twitter.com/WilliamBlairCo>
