### ISSUE TITLE
Hub icon dark/light theme

### ISSUE THREAD

**Issue by agnieszka-puzio** [MicrosoftDocs/azure-devops-docs#10784]
Documentation: https://docs.microsoft.com/en-us/azure/devops/extend/develop/web-navigation?view=azure-devops&viewFallbackFrom=vsts#hub-icon

is lacking information on how to add different icons for bright/dark theme, like described here: https://stackoverflow.com/questions/57212260/how-do-hub-icons-change-according-to-the-theme-in-azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab519d8-dc41-91de-437a-4469edefddab
* Version Independent ID: edc98ac8-a89a-a79a-d75c-1435870a00d2
* Content: [Developing extensions for vertical web navigation - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/web-navigation?view=azure-devops&viewFallbackFrom=vsts#hub-icon)
* Content Source: [docs/extend/develop/web-navigation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/web-navigation.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by apawast** [comment]
@TimShererWithAquent I am no longer on the Azure devops team. @chcomley can you help find the right person?

**Comment by chcomley** [comment]
Thanks for your feedback, @agnieszka-puzio. I've created a user story to address this article update!
