### ISSUE TITLE
Accommodating changing versions in DevOps REST API

### ISSUE THREAD

**Issue by farjana15** [MicrosoftDocs/azure-devops-docs#10781]
To accommodate the changing API versions - Can we identify the latest stable version of the api everytime and use it in the API call? so that no api requests are rejected due to deprecation or changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84af2b0f-cd64-018f-585f-70d17f393f85
* Version Independent ID: 8b25aa9b-95b8-14d3-0348-8d8ffd6d2843
* Content: [REST API versioning for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops)
* Content Source: [docs/integrate/concepts/rest-api-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/rest-api-versioning.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @farjana15, 
The general guide is to use our released API version, and right now the latest version is 6.0. You can also specify the version of the API that you want to use in your clients and that would guarantee that the functions aren't being deprecated or changed.
If you want to always stay on the latest released version, you can use the APIs without specifying the version, but that would auto-update the version every time we release a new version and could lead to deprecated functions. 
Thank you for reaching out. If you happen to have any further questions, don't hesitate to @mention me. Thanks again!
