### ISSUE TITLE
Agile link broken

### ISSUE THREAD

**Issue by MrBenMyster** [MicrosoftDocs/azure-devops-docs#10786]
[Enter feedback here]
The link to the **What is Agile?** page  `https://docs.microsoft.com/en-us/azure/devops/learn/agile/what-is-agile` is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfec0e8f-68af-b619-e8bb-e32823a80d27
* Version Independent ID: 22a0c33a-44b1-904a-7eba-5a40d0bdc246
* Content: [Manage change, Agile methods - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cross-service/manage-change?view=azure-devops)
* Content Source: [docs/cross-service/manage-change.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cross-service/manage-change.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
Fixed in attached PR.

**Comment by KathrynEE** [comment]
@TimShererWithAquent - FYI, this PR, https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3234, addresses other broken links that resulted from the refactoring and rename of the /azure/devops/learn URL to /devops. These changes should be made shortly.
