### ISSUE TITLE
All steps requiring paid support should be listed in the Prerequisites section

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/azure-devops-docs#10790]
The guide mentions the following as a step after tenant change:
> Request that SSH keys be manually cleared by Support, and then recreate SSH keys. Complete the following steps.

On the other hand 
> You have 100 or fewer users in your organization. If your organization has more than 100 users, contact Support for help changing your Azure AD.
is listed as **Prerequisite**

In my opinion, **all steps requiring paid support** should **be listed in the Prerequisites section**. Trying if the problem is solved through Developer Community for free is not a good solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @jikuja, I've created a user story to address this feedback!
