### ISSUE TITLE
Broken link for 'plan your team's migration'

### ISSUE THREAD

**Issue by jasongiss** [MicrosoftDocs/azure-devops-docs#10794]
This link points to:
https://docs.microsoft.com/en-us/devops/git/centralized-to-git

Which goes to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Hi @jasongiss - Thanks for finding this broken link. This was one of several broken links that were fixed in this PR: MicrosoftDocs/azure-devops-docs-pr/pull/3234

The changes will go live soon.
