### ISSUE TITLE
Typo "リポジトリ****を含む組織とユーザーアカウント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10804]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml"
![repos_github_j](https://user-images.githubusercontent.com/40815708/119437894-fc71fd80-bd59-11eb-9d72-c58ebe3f61f5.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml"
![repos_github_e](https://user-images.githubusercontent.com/40815708/119437899-ff6cee00-bd59-11eb-952f-41f93ecab0f3.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
The four asterisks are clearly wrong. They don't occur elsewhere on the page. Here's the markdown:

GitHub's structure consists of \*\*organizations and user accounts** that contain \*\*repositories**.
