### ISSUE TITLE
Add working example in `Publish Python packages in Azure Pipelines`

### ISSUE THREAD

**Issue by thomassajot** [MicrosoftDocs/azure-devops-docs#10807]
Hi, 
It would be great to provide a full working example in the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c37d1cb4-805b-173c-ac62-1037c5bedb7f
* Version Independent ID: 91cfb14e-b752-93e2-52a7-25d8d3fe66d5
* Content: [Publish packages to Azure Artifacts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@thomassajot Thank you for reaching out. The updated article will go live shortly.

**Comment by thomassajot** [comment]
Thank you @ramiMSFT, looking forward to it.
