### ISSUE TITLE
[LOC]Back-Translation "/許可:"→"/allow:" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10801]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/repos/tfvc/git-permission-command?view=azure-devops"
![git-permission-command_j](https://user-images.githubusercontent.com/40815708/119435727-b4e97280-bd55-11eb-87e4-1c1ff061dcca.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/git-permission-command?view=azure-devops"
![git-permission-command_e](https://user-images.githubusercontent.com/40815708/119435732-b6b33600-bd55-11eb-8d59-b63c197a7543.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa3aa13-7e1e-b327-132b-26fdfd2c0f6e
* Version Independent ID: d62debf7-71cc-2f94-faf2-b83393aa85d9
* Content: [Git permission command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/git-permission-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/git-permission-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/git-permission-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **v-maksim**

**Comment by TimShererWithAquent** [comment]
Similar issue: MicrosoftDocs/azure-devops-docs/issues/10803
