### ISSUE TITLE
Project and Portfolio Management

### ISSUE THREAD

**Issue by mdathora** [MicrosoftDocs/azure-devops-docs#10809]
This is an issue concerning the Project and Portfolio Management related to [this link}(https://docs.microsoft.com/en-us/azure/devops/boards/extensions/migrate-integrate?view=azure-devops#project-and-portfolio-management)

The company AgileCraft is now part of Atlassian (Jira) and the AgileCraft extention for Azure DevOps has not been updated since 2018. Therefor this company should not be promoted by the Azure DevOps documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0946a25-5ea9-376e-be4e-679491fd2fa0
* Version Independent ID: 43473d55-c342-f9ff-3a24-bff441af8600
* Content: [Migrate to or integrate work tracking and Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/migrate-integrate?view=azure-devops#project-and-portfolio-management)
* Content Source: [docs/boards/extensions/migrate-integrate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/extensions/migrate-integrate.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE The **AgileCraft** link points to a product still called _AgileCraft_. There is a freshness question, though, about whether we should keep the link if the content isn't being updated.

**Comment by KathrynEE** [comment]
@mdathora - Thank you for the feedback. I agree it should be removed, will be updating the article later today.
