### ISSUE TITLE
Surprising error when running Install-Module with password instead of PAT

### ISSUE THREAD

**Issue by jonathanmbaker** [MicrosoftDocs/azure-devops-docs#10813]
I understand that the instructions under 'Connecting to the feed as a PowerShell repo' only mention the use of a PAT, but it does not state anywhere that Install-Module will fail if you use your password instead of a PAT. (I'm guessing this is a restriction by Azure Devops to encourage good security practices among its users)

To prolong the confusion in my case, the previous steps requiring credentials work with a normal password until you use Install-Module, which is when it fails with an opaque error that has no mention of the underlying issue with credentials:

`No match was found for the specified search criteria and package name 'XXXX'. Try Get-PackageSource to see all available registered package sources.`

I ended up spending hours tracking this down, assuming my credentials were ok because I successfully registered my repository and listed available modules (via Find-Modules) using credentials with a password instead of a PAT.

Any chance of updating the documentation to explitly mention the error Installing-Modules via password instead of PAT?

or should the Find-Module and Register-PSRepository functions be failing too when using a password for consistency?

I would understand if the problem lise being between the chair and the keyboard on this one :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jonathanmbaker Thank you for your feedback! Using a personal access token is the recommended approach in this scenario. Can you open a ticket about the error here: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/search?space=21). I'm adding a note to the article shortly.
