### ISSUE TITLE
Comparison table is inaccurate

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#10815]
Please update the comparison table to reflect the current state of wiki's. For example, provisioned wikis do allow for reverting of versions. Are there other items that have been brought closer to parity? This table greatly influences the decision to go with the provisioned option vs the code repo option, so it's important for it to be accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback @GaTechThomas. I've created a user story to address this!
