### ISSUE TITLE
What the fuck is this?

### ISSUE THREAD

**Issue by tsethk** [MicrosoftDocs/azure-devops-docs#10816]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654b64d-80e5-a28e-30d8-240b02bbe175
* Version Independent ID: c4f3eb8e-e203-7452-ba96-b0990107339a
* Content: [Save your changes with Git commits - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commits?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/commits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/commits.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Parts of this issue were edited because they violate the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
