### ISSUE TITLE
Inherited processes not supported but process-migrator no longer in line with what can be customized from web interface

### ISSUE THREAD

**Issue by Damandan** [MicrosoftDocs/azure-devops-docs#10811]
Hi all,

in the remark at the beginning of the page, it is stated that inherited processes are not supported, but that process-migrator might help. Since this is a tool, initially released by Microsoft. I thought that this would be kept up to date, but it isn't. There have been no bugfixes for the last 2 years.

Process-migrator has multiple bugs that have been in there for over a year, yet nobody seems to be fixing it.

In my case, the problem is that it is now possible, from the Azure DevOps Service UI, to change the name of the 'Completed' state to a custom name. This is however not processed correctly by process-migrator. (I suspect that there are new endpoints that were introduced when this functionality became available, but the process-migrator now uses the wrong endpoint.
See bug report here: https://github.com/microsoft/process-migrator/issues/42

Is there any way that someone at Microsoft gets assigned to fix this bug or is there some other way that this can be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b7e8f3-68f7-80f9-3cfb-6dca0002435b
* Version Independent ID: e37d3809-9ad8-e82b-71c1-543066fc105d
* Content: [Upload, download, or delete a process template - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/manage-process-templates?toc=%2Fazure%2Fdevops%2Freference%2Ftoc.json&bc=%2Fazure%2Fdevops%2Freference%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=visual-studio-2019)
* Content Source: [docs/boards/work-items/guidance/manage-process-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/manage-process-templates.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@Damandan - It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

I am going to keep this doc issue open, for now, in case we should change the remark about the process migrator.

**Comment by KathrynEE** [comment]
@Damandan - I've sent a message to the product team. I'll update you when I learn more.

**Comment by Damandan** [comment]
> @Damandan - I've sent a message to the product team. I'll update you when I learn more.

Great. Thank you very much.

**Comment by KathrynEE** [comment]
@Damandan - The product team has opened a bug on this issue. Unfortunately, it may take some time for them to address it.  I'll leave this issue open until I hear back that it's been fixed.

**Comment by danhellem** [comment]
The short story is that the tool was open sourced by a team member years ago, but it is not actively being work on. We are trying to fix that.

I am going to start looking into the bugs and fixing issues in the near future. But I don't have any guarantees on when this specific issue will get fixed.

**Comment by Damandan** [comment]
Thanks for the update!

**Comment by KathrynEE** [comment]
Closing this issue as it is being tracked by the product team.
