### ISSUE TITLE
No documentation on how to open or create a template task in ADO.  This is for TFS and the process has changed.

### ISSUE THREAD

**Issue by JeffreyWolford** [MicrosoftDocs/azure-devops-docs#10823]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Use work item templates to update stories & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JeffreyWolford - I don't understand what is lacking.  Are you sure you have the version selector for the content set to Azure DevOps Services? This is right above the TOC to the left of the content.
![image](https://user-images.githubusercontent.com/10856840/119704500-94c8ba80-be0c-11eb-8d0e-555fbdfa2cbb.png)

If you could provide more details as to what you believe isn't documented, I can try to help.
