### ISSUE TITLE
missing route documentation securefiles

### ISSUE THREAD

**Issue by slmagus** [MicrosoftDocs/azure-devops-docs#10829]
Still learning the azure-devops-api however, It seems that the documentation is missing the information for _apis/distributedtask/securefiles/ route.

I am looking for acknowledgement that this in fact missing, and that is the right repo to track this issue on, and if both those are true that the documentation is created.

This is related issue in another project, that seems to be the only place this api is somewhat documented. https://github.com/Microsoft/azure-pipelines-tasks/issues/9172

**Comment by TimShererWithAquent** [comment]
@slmagus - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

**Comment by slmagus** [comment]
> 
> 
> @slmagus - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

Respectfully the issue, as I see it, is that the route is missing from the documentation entirely.

The context for further elaborated upon here: https://github.com/microsoft/azure-pipelines-tasks/issues/9172#issuecomment-466024682 by one of Microsofts directory of engineering, @madhurig

**Comment by TimShererWithAquent** [comment]
@madhurig @damccorm Is there anything new on this? From microsoft/azure-pipelines-tasks#9172, it sounded like this was settled.

**Comment by slmagus** [comment]
Is there any more information I can provide or can we remove the needs more information label.

I feel that this should be a P1 documentation issue as this is an undocumented api route.

**Comment by TimShererWithAquent** [comment]
@slmagus It looks like this should be documented in a [different repo](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1). If you could open an issue there, that would be the place for it.

@mijacobs for awareness.
