### ISSUE TITLE
Shortcuts for the YAML editor

### ISSUE THREAD

**Issue by e14mattc** [MicrosoftDocs/azure-devops-docs#10820]
Could you add the shortcut keys that we can use in the Pipeline YAML editor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Keyboard shortcuts for web portal and Team Explorer - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@e14mattc - Thank you for your inquiry. I'm investigating with the product team to determine if there are any keyboard shortcuts to document.

**Comment by KathrynEE** [comment]
@e14mattc - The product team indicates that there are no keyboard shortcuts associated with YAML editor. Closing this issue.

**Comment by e14mattc** [comment]
lol. Err, ok.. so when I press F1 in the editor and it shows me all the keyboard shortcuts.. those don't really exist ;)

![image](https://user-images.githubusercontent.com/9819307/121858782-dd2e1680-ccee-11eb-869f-a365ab4abd33.png)

One example from that list is CTRL + / which toggles line comments .. that's a really useful one.
