### ISSUE TITLE
Retry-after header in a 200 ok response is misleading

### ISSUE THREAD

**Issue by ruifrvaz** [MicrosoftDocs/azure-devops-docs#10832]
Regarding TSTUs based throttling. If I understand correctly, when throttling begins, the response is still 200 but it comes with a retry-header. But the retry-after header in a 200 ok response is misleading, since the response already contains what we want. We do not need to retry, we need to wait until next call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @roferg
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@ruifrvaz - It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

If you think there are documentation changes for this issue, let me know and I'll reopen the issue.

**Comment by ruifrvaz** [comment]
Hi @TimShererWithAquent . thanks for looking into it and replying. I suppose this was an architectural decision that uses 200 instead of the standard http 429 which you even reference a link in the code to: https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers. 

I seriously doubt there will be changes made to use 429 instead, since this seems to have been a conscious decision.

Therefore I would suggest to mention that the response is http 200. You can even slightly update the paragraph "We recommend that you at least respond to the Retry-After header. If you detect a Retry-After header in any response, wait until that amount of time has passed before sending another request. Doing so helps your client application experience fewer enforced delays." adding something at the end like: "Keep in mind, that the response is 200, so you do not need to apply retry logic to the request."

**Comment by KathrynEE** [comment]
@chcomley - reassigning this issue to you as you handle usage monitoring.

**Comment by chcomley** [comment]
Hi @ruifrvaz, Thanks for the heads up on this. I've created a PR, adding the verbiage you recommended. Once it's live, this issue will automatically close. In the future, we'd love it if you considered [becoming a contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! Thanks again!

**Comment by ruifrvaz** [comment]
hi @chcomley . Good to know that my feedback was helpful. I will give that a look. best regards and keep it up!
