### ISSUE TITLE
Mermaid Diagrams in Server 2020

### ISSUE THREAD

**Issue by casey-stabler** [MicrosoftDocs/azure-devops-docs#10830]
The Section for Mermaid Diagrams is included in the DevOps Server 2020 version of this page, but then with a note that it is not available in DevOps Server, negating the point of different versions of the page for different versions of the product highlighted by the note at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops-2020)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @casey-stabler. Once the update's published, this issue will close.
