### ISSUE TITLE
"How are the identity variables set" section is misleading for GitHub repos

### ISSUE THREAD

**Issue by benjamincburns** [MicrosoftDocs/azure-devops-docs#10847]
Under the heading ["How are the identity variables set"](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#how-are-the-identity-variables-set) it states that unless using scheduled or manual triggering, when building from a git repository, the `Build.RequestedFor`, `Build.RequestedForId`, and `Build.RequestedForEmail` variables will be set to indicate the person who committed or pushed the change.

When I use these variables with a GitHub repository and push a new change, `Build.RequestedFor` is set to `'GitHub'`, `Build.RequestedForId` appears to be a UUID that (I think) maps internally to the GitHub repo that triggered the build, and `Build.RequestedForEmail` is an empty string.

None of those details indicate the person who committed or pushed the changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#identity_values)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@benjamincburns I'm seeing the same behavior and will reach out to the product team. I'm not sure if this is a documentation issue or a bug.

**Comment by juliakm** [comment]
Confirmed that these variables are designed for Azure Repos. I'll update the article.
