### ISSUE TITLE
 [LOC]Back-Translation "管理者"→"Administrator" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10848]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/process/environments?view=azure-devops"
![process_environments_j](https://user-images.githubusercontent.com/40815708/120261560-16b85800-c2d3-11eb-9383-62095adb4cf3.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops"
![process_environments_e](https://user-images.githubusercontent.com/40815708/120261564-191ab200-c2d3-11eb-936f-fb7f9d241fdc.png)

#pingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@juliakm There's nothing in the source markdown that looks like it should cause this. This might be a localization issue.

Also, notice that the column header "Role" is not translated. The "Description" header is.

**Comment by juliakm** [comment]
Thanks @hyoshioka0128. I've filed an issue with our translation team and am closing this issue since they work in a different queue.

**Comment by hyoshioka0128** [comment]
@juliakm - Thanks!

**Comment by hyoshioka0128** [comment]
@juliakm - Thaks! 
 But, Not Translated "Role"→"ロール" .
@TimShererWithAquent says - "_Also, notice that the column header "Role" is not translated._"
![process_environments_j](https://user-images.githubusercontent.com/40815708/156097826-9967032a-5ce0-4311-9396-49784083887a.png)
