### ISSUE TITLE
Integrate Site24x7 as a service hook

### ISSUE THREAD

**Issue by JasperPaul** [MicrosoftDocs/azure-devops-docs#10846]
Hi there,
 This is more of a request than an issue. Site24x7 is a monitoring product and it would be great if we can integrate with service hooks. This will give customers of Site24x7 who use Azure DevOps to integrate Site24x7 as part of their CI/CD pipeline. Would like to partner with you guys to implement this. Who can I reach out to?

-Jasper
PM, Site24x7
jasper.paul@zohocorp.com
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/overview?view=azure-devops)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by mijacobs** [comment]
Hi @JasperPaul,

Please fill out this form and someone will help get you connected:
https://azure.microsoft.com/en-us/overview/connect-to-partner/
