### ISSUE TITLE
Can no longer change pipelines retention settings, but the document says, that is what I should do

### ISSUE THREAD

**Issue by iwhp** [MicrosoftDocs/azure-devops-docs#10851]
Can no longer change pipelines retention settings, but the document says, that is what I should do.

**The following is written in the documentation.** at 
https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=classic

To remove your existing pipeline-level retention settings, edit your release pipeline. Then, remove the values on the Retention tab.

**The following is shown on the Retention tab**
Pipelines retention has been streamlined. Please go to the project settings to configure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Retention policies for builds, releases, and test - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **rabououn**

**Comment by juliakm** [comment]
Hi @iwhp. I'll remove that part of the documentation. If you see that message, your retention settings should already be removed. If this is not the case, please reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
