### ISSUE TITLE
Duplicate entry for the "View boards and open work items" task in "Boards feature access" detailed table

### ISSUE THREAD

**Issue by jfberanger** [MicrosoftDocs/azure-devops-docs#10855]
In "Boards feature access" detailed table, there is a duplicate entry for the "View boards and open work items" task.

![image](https://user-images.githubusercontent.com/85180967/120364720-df1ad180-c30d-11eb-8738-6c194dd91f95.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35602ee-9d11-9746-4b79-075e295a5fb8
* Version Independent ID: dbea8e30-e80b-8f13-987e-ef0ad3ba9b83
* Content: [Default permissions and access quick reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-access?view=azure-devops)
* Content Source: [docs/organizations/security/permissions-access.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions-access.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE I think the second line should probably be "Edit boards . . ." but I don't want to guess at the exact wording.

**Comment by KathrynEE** [comment]
@jfberanger - Thank you for the feedback. I'm correcting the article to remove the duplicate entry.

**Comment by jfberanger** [comment]
Thanks @TimShererWithAquent, thanks @KathrynEE
