### ISSUE TITLE
Parameter Descriptions Are Confusing

### ISSUE THREAD

**Issue by wfschneider** [MicrosoftDocs/azure-devops-docs#10852]
The `scriptLocatiopn` and `scriptPath` arguments are confusing. Both are required and both descriptions say it's the path to the script or the fully qualified path to the script. Why would I need both? The examples are not helpful since they are both using the `inlineScript` approach. Please clarify this.

The description of the values for `scriptType` are not clear. The text has `PowerShell/PowerShell Core/Bat/Shell`, `bash/pscore` and `batch/ps/pscore` are all highlighted. Are they all possible selections? A simple table(s) would make this much more clear indicating what the acceptable values are and to what agents they apply. Again teh examples are no help since they are both `ps`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by ramiMSFT** [comment]
@wfschneider Thank you for your feedback! I agree, the description was a little confusing.
`scriptLocation`: enter `scriptPath` to use a script file or `inlineScript` if you want to write your script inline.

`scriptPath` required when `scriptLocation = scriptPath`
`inlineScript` required when `scriptLocation = inlineScript`

`scriptType`: if your are using a windows agent you can use PowerShell, PowerShell core, or batch (select one). Select bash or PowerShell core if you are using a Linux agent.
