### ISSUE TITLE
Pipeline caching is not free, it is being billed as artifact storage

### ISSUE THREAD

**Issue by pearj** [MicrosoftDocs/azure-devops-docs#10856]
According to the Pipeline Caching page, it says:

> **Note**
> Caching is currently free, and caches are stored in Azure blob storage.

However, when I go to `https://dev.azure.com/<my org>/_settings/storage` you can see from the screenshot below, that pipeline caching is actually billed. Additionally, my builds started failing and prevented me from uploading artifacts `402 Payment Required - Artifact cannot be uploaded because max quantity has been exceeded or the payment instrument is invalid. https://aka.ms/artbilling for details. (DevOps Activity ID: 6674AB99-3D5A-4072-B2C4-64BB48E99AF9)`.

Also it looks like it [isn't possible to clear the caches](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#q-when-does-a-cache-expire) either. Considering there isn't a way to [delete a cache](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#q-can-i-clear-a-cache).

Is it expected that Pipeline Caching should be getting billed as Artifact Storage? As Artifact Storage is quite expensive, between 12 and 140 times the price of Azure Blob Storage, considering that caching is stored as Azure Blob Storage, shouldn't Pipeline Caching be billed using the Azure Blog Storage pricing?

Also the [Azure DevOps Services pricing page](https://azure.microsoft.com/en-au/pricing/details/devops/azure-devops-services/) makes no mention of Pipeline caching. The [Start using Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops#q-which-artifacts-count-toward-my-total-billed-storage) page also mentions that Pipeline Caching is not billable:
> You're not billed by Azure Artifacts for storage of Pipeline Artifacts, Build Artifacts, and Pipeline Caching.

![image](https://user-images.githubusercontent.com/237821/120421303-62d5cc00-c3a9-11eb-8d7f-6dedbaa77917.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@pearj - If a cache is being stored somewhere besides where we say it is, this may be an issue with the product. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

I'm going to assign this item in case we need to change wording, per the description above.

**Comment by pearj** [comment]
Thanks @TimShererWithAquent, I have [raised a bug](https://developercommunity.visualstudio.com/t/Pipeline-Caching-billed-as-Artifact-Stor/1439718?space=21&sort=newest) as you suggested.

**Comment by ramiMSFT** [comment]
@pearj Thank you for your feedback! What's your org name? we're investigating this issue and we need a little more information

**Comment by pearj** [comment]
@ramiMSFT I have since found out that our organisation uses a different Microsoft Support Channel, so I'll try that first.

But curiously when I created a personal devops organisation the "Artifact Storage - Organisation-level" page actually looks different, and specifically mentions that Pipeline caching should not be billed.

![image](https://user-images.githubusercontent.com/237821/120748660-7ff3d180-c546-11eb-8e02-2beccb318976.png)

The [View Artifacts Storage Consumption](https://docs.microsoft.com/en-au/azure/devops/artifacts/artifact-storage?view=tfs-2018) has same UI as my original post.

**Comment by ramiMSFT** [comment]
@pearj Ok I see. Pipeline caching is billable for internal customers (E.g. teams in Microsoft) but it's free for all external customers. That's why the org your created with your personal credentials (external customer) is showing "not billed". I'm assuming that the org showing caching being billed is an internal organization, right?

**Comment by pearj** [comment]
@ramiMSFT Oh thanks for that insight, this subscription was originally setup by someone from Microsoft Professional Services, even though we have setup regular billing now, there must be something left over inside the billing system.

I'll close this then.
