### ISSUE TITLE
No predefined variable for Build.ScheduleName?

### ISSUE THREAD

**Issue by wmcook-hex** [MicrosoftDocs/azure-devops-docs#10862]
Hello, I was investigating the ability to set two separate schedule triggers inside a yml pipeline: one to run on Monday/Wednesday/Friday, and the other to run on Tuesday/Thursday. I would like the to have two stages in my pipeline only run on the Tuesday/Thursday schedule while every stage is supposed to run on the Monday/Wednesday/Friday schedule. 

To me, the simplest solution appeared to be to set conditions for the stages based off of the schedule name used. For example, if the Tuesday/Thursday schedule had its displayName set to "Stagger", I could create a condition like eq(Build.ScheduleName, "Stagger"). Right now it seems that the closest functionality to this is Build.Reason -eq "Scheduled", but since I have another schedule trigger being used that doesn't provide what I need. I see that there is a way to access the schedule name by using the Azure DevOps rest api, but that would require more workaround than I would expect for something as simple as this. Is there any plan to include a predefined yml variable for the schedule names? Sorry if this is not the place to bring this up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?tabs=yaml&view=azure-devops)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@wmcook-hex - Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
