### ISSUE TITLE
This doesn't explain how to manage permissions for Code wiki's.

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#10867]
There is no "Wiki Security" option for a code wiki so this document doesn't help there.

 I go to the git repository for the code wiki and add a team, and make sure "Contribute" is set to "allow". However the team members still can't see the code wiki.

The team in question is a member of "Readers" and "Project Valid Users" groups. So I also added "Contributors" group. Still no joy. They can't browse the git repository on Azure Devops, or access the wiki.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by dazinator** [comment]
Turns out the user in question was a user with "Stakeholder" access level. They were in a team and had contribute permissions to the git repo published as a code wiki, but could not access it. I changed their user access level to a "Basic user" and now they can see the code wiki.

**Comment by dazinator** [comment]
> Users with Stakeholder access in a private project can read wiki pages and view revisions, however they can't do any edit operations. For example, stakeholders aren't able to create, edit, reorder, or revert changes to pages. These permissions can't be changed. They have full access to Wikis in public projects.

As above, this doesn't appear to be the case for code wiki's. Stakeholder user's can't access them at all irrespective of the repo permissions.

**Comment by chcomley** [comment]
Thanks so much for your feedback, @dazinator. I've updated the article and added some clarity. Thanks again!
