### ISSUE TITLE
Wiki for ExternalLinkFilter

### ISSUE THREAD

**Issue by jmediamanager** [MicrosoftDocs/azure-devops-docs#10877]
I believe that for the `ExternalLinkFilter` the valid value should be `Wiki page` instead of `Wiki`

I have tested this on Azure devops Server 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53aa48e0-7006-fa63-9915-c7d72dd5623d
* Version Independent ID: b3816d11-7cb9-1c56-4cfc-1158e05187cb
* Content: [LinksControlOptions XML elements reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/linkscontroloptions-xml-elements?view=azure-devops-2020)
* Content Source: [docs/reference/xml/linkscontroloptions-xml-elements.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/linkscontroloptions-xml-elements.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jmediamanager - Thank you for the feedback. I'll update the article with your correction.
