### ISSUE TITLE
Query issues when using history contain words and exact phrase

### ISSUE THREAD

**Issue by markanthonyraymond** [MicrosoftDocs/azure-devops-docs#10873]
[When using the querying functionality, I'm having issues using the history field and containing words with an exact phrase e.g., "changed state from Closed" however, it is pulling items that are not relevant i.e., pulling entities that do not contain this exact phrase. I've tried enclosing this using quotation marks for an exact match but to no avail. I've also tried without quotation marks. I've also checked to see if it was case sensitive or insensitive but the results were the same and not relevant to the exact match that I'm needing. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104a125c-c68d-e4fb-2d6b-ffd8fb7b7462
* Version Independent ID: be4e20fc-72bb-a2a8-a404-8048bd739bf1
* Content: [Query by history - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/history-and-auditing?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/boards/queries/history-and-auditing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/history-and-auditing.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@markanthonyraymond - Thank you for your inquiry.  As noted in the document for the History field:   
  > History field queries return work items whose Discussion comments or Description fields contain words that match the keywords entered. You can't use the History field to query on changes made to other fields.    

If you are looking at finding items that have been reactivated - were Completed or Closed - and are now not Completed or Closed, I recommend you create a Query using the State field.
![image](https://user-images.githubusercontent.com/10856840/120843274-c33c4900-c522-11eb-9435-70e95d208b6a.png)
