### ISSUE TITLE
Please provide more info on management of bugs when they are set to be handled as tasks.

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/azure-devops-docs#10874]
When bugs are set to be handled as tasks, and a new bug is found for a UserStory which have been running in production for a long time (completed & deployed).

You add the discovered bug as a child to the existing closed UserStory, and now you want to manage and plan this new bug you run into several issues, for example...
1. The bug does (obviously) not appear in the backlog since bugs are handled as a task.
2. The parent UserStory does not appear in the backlog since it is closed.

.
- So how do you plan and manage the newly added bug?
- How do you put it into an iteration/sprint?
- How do you make it appear on the sprint board?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58aacca7-05a2-e8dd-6a6f-3025d734ef20
* Version Independent ID: 3eea19c1-8bda-6b60-e77d-8c0e82c3f096
* Content: [Define, capture, triage, and manage bugs or code defects - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=azure-devops)
* Content Source: [docs/boards/backlogs/manage-bugs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-bugs.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Bartolomeus-649 - Thank you for your inquiry. In the scenario you describe, I recommend you open the closed User Story. You reactivate the User Story until all linked bugs are resolved and closed. The other method is to create a new User Story to track ongoing bugs that occur for that particular feature.
