### ISSUE TITLE
Broken Documentation Links in Dev Ops Pipelines for Docker Tasks

### ISSUE THREAD

**Issue by KanishkT123** [MicrosoftDocs/azure-devops-docs#10879]
Documentation Links in Azure Dev Ops Pipelines for the following tasks:

1. `Docker@2`
2. `DockerInstaller@0`
3. `DockerCompose@0`

Are all broken. The links in the task all point to `https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops`

Instead of pointing to the correct task documentation. See the attached screenshot for an example of where the link is broken. (Learn More about this task)

![image](https://user-images.githubusercontent.com/15843803/121039107-ce8bb080-c77e-11eb-8dd3-b1fe11fda1b1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@KanishkT123 Thanks - We're looking into this now -

**Comment by TimShererWithAquent** [comment]
It looks like these are supposed to link to the following pages:

Docker@2 https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker
DockerInstaller@0 https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/docker-installer
DockerCompose@0: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose

**Comment by TimShererWithAquent** [comment]
@KanishkT123 - Thanks for finding this. The links in the product aren't managed through this repo. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

@azooinmyluggage for awareness.

**Comment by TimShererWithAquent** [comment]
Closing issue in this repo. Please follow up with us, if needed.
