### ISSUE TITLE
Clarification on "Publish and download artifacts in Azure Pipelines"

### ISSUE THREAD

**Issue by elliot-nelson** [MicrosoftDocs/azure-devops-docs#10871]
On the page "Publish and download artifacts in Azure Pipelines", under the section on downloading artifacts, it shows the shortcut example and then includes a note:

```
 * current: download artifacts produced by the current pipeline run. Options: current, specific.
```

This note matches what is shown in the full [Download Pipeline Artifact Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops) doc, but it is missing a crucial third option: the name of a pipeline resource defined above in the YAML file, like so:

```
resources:
  pipelines:
    - pipeline: trigger_pipeline
      source: "Acme CI Build"
      trigger: true

steps:
  - download: trigger_pipeline
```

Including a note about this third option, like `or the name of a pipeline resource, as described [here]`, would make this much more discoverable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#use-artifacts-across-stages)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by DanielSpindler83** [comment]
Oh my goodness - this issue saved me. I spent 3 hours pouring over documentation trying to work out how to control download tasks in this way. massive kudos to @elliot-nelson . MS please get this fixed asap.

**Comment by ramiMSFT** [comment]
@elliot-nelson I think you are mixing 2 different scenarios. The *DownloadPipelineArtifact* task accepts 2 options for source: current or specific:

```
    "inputs": [
        {
            "name": "source",
            "aliases": [
                "buildType"
            ],
            "type": "radio",
            "label": "Download artifacts produced by",
            "defaultValue": "current",
            "required": true,
            "options": {
                "current": "Current run",
                "specific": "Specific run"
            },
            "helpMarkDown": "Download artifacts produced by the current pipeline run, or from a specific pipeline run."
        }
```
In your example you are referring to [resources](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema).

You can use [pipeline resources](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines) to define your resources in one place and use it anywhere in your pipeline.

**Comment by DanielSpindler83** [comment]
@ramiMSFT I don't think you have read and understood the original post correctly.

We are specifically talking about download options(as per the example provided).

The download documentation is missing a section - as per his post. I have implemented and tested this in a production environment. The doco is incomplete and misleading - causing me and likely others hours of lost productivity. 

Please take the time to re-read and ask for clarification if you do not understand.

**Comment by elliot-nelson** [comment]
I think the truth might be somewhere in the middle, unfortunately.

I think the disconnect is that explicitly calling the task `DownloadPipelineArtifact` _doesn't_ support a pipeline resource name.  Only the `download:` _shortcut_ supports it.  In this section describing the `download:` shortcut, it does list a pipeline resource name as a possible parameter:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#download

So I think the introductory paragraph, which states "...is a shortcut for the DownloadPipelineArtifact task", is not quite true... maybe it uses it under the covers, but it has a different set of options than the task itself does.  And if you enter the docs from the wrong end, it can be extremely frustrating to figure out what you're not understanding.

Maybe the solution would be to improve the "hint" paragraph in https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops, to make it much more clear that if you are looking for a way to download the artifacts of a named pipeline resource, you need to review https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#download.
