### ISSUE TITLE
How can I find where I'm mentioned across PRs and work items?

### ISSUE THREAD

**Issue by wireddown** [MicrosoftDocs/azure-devops-docs#10870]
How can I find where I'm mentioned across PRs and work items?

- ✅ I **can** visit https://dev.azure.com/{org}/_work to see my mentions in work items
- ❌ I **cannot** visit https://dev.azure.com/{org}/_pulls to see my mentions in PRs
  - I can only see what's assigned to me or my teams
  - the Customize view button doesn't offer a filter for _"PRs where I'm mentioned"_

I want another URL, maybe https://dev.azure.com/{org}/_mentions , where I can see a list with links to the the Azure DevOps items (PRs, work items, whatever else) where a colleague has mentioned me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@wireddown - Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
