### ISSUE TITLE
Incomplete guide

### ISSUE THREAD

**Issue by endk-awo** [MicrosoftDocs/azure-devops-docs#10882]
It is not described how to access keyvault secrets in a pipeline, once they have been downloaded. The guide shows a pipeline run that includes a CmdLine task which has not been described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Use Azure Key Vault secrets in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@endk-awo Thank you for your feedback! I updated the content and added the YAML pipeline which shows the steps to fetch the secret from Azure key vault, write it to secret.txt and publish the build Artifact.
