### ISSUE TITLE
Page doesn't explain what happens when a build with parameters is automatically triggered

### ISSUE THREAD

**Issue by Hammerite** [MicrosoftDocs/azure-devops-docs#10886]
This page doesn't explain what happens when a build with parameters (that are lacking default values) is automatically triggered (as a CI build or according to a schedule).

I can think of at least two things that might happen:
- The build might automatically fail with an error message.
- An arbitrary value (predictable or otherwise) might be assigned to the parameter.

If there were a statement somewhere, anywhere guaranteeing the second behaviour, I would be happy. As it is, even if I observe the second behaviour in practice, what guarantee do I have that you won't change the behaviour in future? None. You haven't said what the behaviour is anywhere, so any observed behaviour is unreliable.

One might infer from language elsewhere on the page (e.g. "If you do not make a selection, the default option, ubuntu-latest gets used") that the second behaviour described above is to be expected. But that's not good enough. You should tell us explicitly.

The lack of explanation on the page is particularly irritating because you apparently specifically went out of your way not to explain it ("The trigger is set to none so that you can select the value of image when you manually trigger your pipeline to run.")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Hammerite** [comment]
Why is my last paragraph big? I hate markdown. If I were in charge it would be made illegal.

**Comment by juliakm** [comment]
@Hammerite I'm updating the documentation now. If `default` is set to `false`, then you will be asked to select a value during the pipeline run. Otherwise, the first option in the list will be used.
