### ISSUE TITLE
Azure Function App task  "azure subscription" argument name wrong 

### ISSUE THREAD

**Issue by yehudamakarov** [MicrosoftDocs/azure-devops-docs#10885]
https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md#azure-function-app-task 

azureSubscription(Azure subscription) | (Required) Name of the&nbsp;Azure Resource Manager service connection.
-- | --

If the parameter is really asking for a "service principal", why is the argument name "azureSubscription"? Is this intentional? If so, why?

Cheers.

**Comment by yehudamakarov** [comment]
Kind of ridiculous, hopefully the issue was in fact ironed out

**Comment by steved0x** [comment]
@yehudamakarov Sorry for the long delay. We have a new autogenerated task reference now, which is up to date with the latest task parameters and their aliases. https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines For feedback on the names of the inputs, you can file an issue on the open source repo for the task themselves, which is here: https://github.com/microsoft/azure-pipelines-tasks
If these don't address your issue, please file a new doc feedback request, which will go into our new feedback system, and include a link to this new issue.
