### ISSUE TITLE
Page appears to be referring to a screen that no longer exists in Azure DevOps

### ISSUE THREAD

**Issue by kcaswick** [MicrosoftDocs/azure-devops-docs#10880]
The step is:
> 1. Select your project and open the Queries page of the Agile section in Azure DevOps

There is no "Agile" section in Azure DevOps, and the mentioned query does not exist under Boards / Queries in Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c99676a-7b74-8e92-d4e3-04040a0fd0cb
* Version Independent ID: 5b4f2ce3-d353-2080-6734-ce7eb1240ca2
* Content: [Track stakeholder feedback - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/track-stakeholder-feedback?view=azure-devops)
* Content Source: [docs/test/track-stakeholder-feedback.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/track-stakeholder-feedback.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by KathrynEE** [comment]
@kcaswick - Thank you for your feedback. Agree that the article is out of date. You can create the Feedback query as described here, https://docs.microsoft.com/en-us/azure/devops/project/feedback/get-feedback?view=azure-devops#review-feedback. We will be updating the article to reflect this information.
