### ISSUE TITLE
secrets.txt not in example

### ISSUE THREAD

**Issue by davehcdn** [MicrosoftDocs/azure-devops-docs#10884]
This documentation page has example steps for examining the secrets retrieved by exporting them to a secrets.txt file.  However 1) this is a pretty insecure practice and shouldn't be illustrated 2) there is actually no pipeline task demonstrated that is running the cmdline task to actually create the secrets.txt file.

I think this page needs a good read-through and an update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Use Azure Key Vault secrets in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@davehcdn Thank you for your feedback! The updated article will go live shortly. The example is for educational purposes to show how to consume a secret "mysecret" from Azure Key Vault and use it in your pipeline. For security best practices and how to safely work with secrets, see [Manage secrets in your server apps with Azure Key Vault]https://docs.microsoft.com/en-us/learn/modules/manage-secrets-with-azure-key-vault/)
