### ISSUE TITLE
Tracking Requirement progress in case of manual test case linked to requirement with link type as child in a static test suite in test plan

### ISSUE THREAD

**Issue by senthil6547** [MicrosoftDocs/azure-devops-docs#10892]
Tracking Requirement progress in case of manual test case linked to requirement with link type as child in a static test suite in test plan should also require to be explain or some reference books on how to frame a Odata query or power bi query with Azure Devops is needed as these examples doesnt help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d632ce-b7c8-fcc1-a612-6b961dd0fda7
* Version Independent ID: 16c0ab72-5af5-e258-afbe-7a825ca01f22
* Content: [Requirements tracking, Stories overview report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-stories-overview?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-stories-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-stories-overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **shdalv**

**Comment by KathrynEE** [comment]
@senthil6547 - THank you for the feedback. I've contacted the product team to request their help in updating the article and examples.

**Comment by shaaraddalvi** [comment]
Hi @senthil6547 , unfortunately we don't support requirement tracking in case of static test suites. The association between a requirement work item (like user story) and manual test execution is only formed when the test case is linked via a requirement-based test suite.

**Comment by ksmis-gh** [comment]
@senthil6547 Does the above answer satisfy your concern? Do you need additional help?

**Comment by KathrynEE** [comment]
@senthil6547 - Closing this issue. I've updated the article with a note indicating the support is only for requirement-based test suite. Thank you again for raising this issue.
