### ISSUE TITLE
Table formating issue for automated translations

### ISSUE THREAD

**Issue by jfberanger** [MicrosoftDocs/azure-devops-docs#10898]
Hello,

There is an HTML formating issue on the auto-generated translation (I quickly checked for French, Simplified Chinese, Spanish, German):
![2021-06-10_11-05-41](https://user-images.githubusercontent.com/85180967/121498770-098b1f80-c9dd-11eb-853d-e9d07d7ee7b7.png)
![image](https://user-images.githubusercontent.com/85180967/121499228-7b636900-c9dd-11eb-8204-dfd78a951071.png)
![image](https://user-images.githubusercontent.com/85180967/121499357-9930ce00-c9dd-11eb-97da-a6664251be6d.png)
![image](https://user-images.githubusercontent.com/85180967/121499753-f4fb5700-c9dd-11eb-9105-b5572f68073c.png)

English versions are ok:
![2021-06-10_11-05-05](https://user-images.githubusercontent.com/85180967/121498775-0b54e300-c9dd-11eb-938f-16bf8c833275.png)

Thanks!
JF
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52fb8a5-d949-dbe6-7e3f-56ac61984e8a
* Version Independent ID: 5e1aeb8b-35bd-8c40-769c-fdac56768b0d
* Content: [How are area and iteration paths used? - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/organizations/settings/about-areas-iterations?view=azure-devops)
* Content Source: [docs/organizations/settings/about-areas-iterations.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/about-areas-iterations.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE There is an underlying issue in the column formatting in the include file: area-iteration-paths.md. 

There are separators (---) that are making the markdown interpret the previous line as a header. I don't know why it doesn't happen in the English version. 

I don't know whether to find another way to format the "table" or if we need a tools fix that doesn't misinterpret the dividers.

**Comment by KathrynEE** [comment]
@TimShererWithAquent - I'm removing the separators (---) from the indicated article as well as in a number of other articles which are having the same problem. It doesn't happen in all places, but definitely happening in several places. I think there should be a tool issue raised - which I'll look into. Meanwhile, fix is in with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3329.
