### ISSUE TITLE
What's the meaning of "template syntax", in the context of conditional insertion?

### ISSUE THREAD

**Issue by sphanley** [MicrosoftDocs/azure-devops-docs#10893]
The documentation for "Conditional insertion" has the following to say (emphasis mine):

> You can use an if clause to conditionally assign the value or a variable or set inputs for tasks. **Conditionals only work when using template syntax.**
>
> For templates, you can use conditional insertion when adding a sequence or mapping. Learn more about conditional insertion in templates.

What does "template syntax" mean in this context? I haven't seen that terminology used elsewhere and I'm trying to understand where Conditional Insertion can/can't be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sphanley Template expressions use the `${{ }}` syntax. This section from our [Template types & usage article](https://docs.microsoft.com/azure/devops/pipelines/process/templates?view=azure-devops#template-expressions) may be helpful. I'll add a link from the expressions page to it.
