### ISSUE TITLE
Association support for junit selenium test result executed in azure pipeline execution to Test plan

### ISSUE THREAD

**Issue by saurabhdv** [MicrosoftDocs/azure-devops-docs#10906]
[Enter feedback here]
The test results in pipeline are hard to identify and map test in Test plan , therefore Association support for junit selenium test result executed in azure pipeline will be very helpful to analyze the test plan execution coverage by automation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@saurabhdv - Can you clarify your issue, a bit? According to the article, Selenium tests can be associated with the test case. Can you provide more context around the general task and what documentation issues it raises?
