### ISSUE TITLE
StartTime, FinishedTime missing for Operation Pipelines.DeploymentJobCompleted in DevOps Auditing Streaming

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/azure-devops-docs#10900]
Looking at the Data Property there seems to be missing the "StartTime" and FinishedTime" for pipeline deployments :
{
	"CallerProcedure": "Task.prc_UpdateEnvironmentDeploymentRequest",
	"DeploymentResult": "Succeeded",
	"EnvironmentName": "tst",
	"AnonymousAccess": "",
	"PipelineName": "ocp-release",
	"EnvironmentId": "8",
	"StageName": "communitypass_tst",
	"RequestId": "473",
	"RunName": "v1.0.118",
	"JobName": "webapp",
	"Result": "0"
}

and in some cases the fields are there but is missing the content for start time:
{
	"CallerProcedure": "Task.prc_UpdateEnvironmentDeploymentRequest",
	"DeploymentResult": "Succeeded",
	"EnvironmentName": "tst",
	"AnonymousAccess": "",
	"PipelineName": "ocp-release",
	"EnvironmentId": "8",
	"StageName": "communitypass_tst",
	"FinishTime": "6/4/2021 10:16:38 PM",
	"StartTime": "",
	"RequestId": "473",
	"RunName": "v1.0.118",
	"JobName": "webapp",
	"Result": "0"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2863bab9-d62b-d142-ae00-025ecbe174dd
* Version Independent ID: 4d20496b-f17f-d8c2-895e-6d091d1b08dc
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/audit/azure-devops-auditing?view=azure-devops&tabs=preview-page#limitations)
* Content Source: [docs/organizations/audit/azure-devops-auditing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/audit/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-audit**
* GitHub Login: @roferg
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@hecflores Can you provide some additional information about where you're expecting to find the Data Property in this article? Or give us some more context on the task you're trying to accomplish? Thanks - 

@chcomley for visibility.

**Comment by hecflores** [comment]
@TimShererWithAquent sure! The task is to generate reports on everything deployments across multiple projects in the org. To do this we are leveraging the audit streaming feature to capture deployment status and duration of pipelines and approval check information. 

The data expected is of course the deployment status, duration (Or start/end time), and check status information. We see the deployment status and check status information but when it comes to duration, that is missing. More specifically the duration is missing and when we try to calculate the duration based on the "StartTime" and "FinishedTime" we are unable to since the "StartTime" is populated with "". 

This is a very active requirement for our customer so we are exploring other options if we are not able to get a fix or workaround soon for this issue.

**Comment by chcomley** [comment]
Hi @hecflores, I'm told that this appears to be a product bug and that you need to post it in the Developer Community. Please go here: https://developercommunity.visualstudio.com/search?space=21 and select **Report a problem** > **Azure DevOps**. I'm going to go ahead and close this issue for the article. If we determine it needs an update after the Developer Community looks into it, I'll do that. Thanks so much for reaching out.
