### ISSUE TITLE
Image needs to be updated

### ISSUE THREAD

**Issue by bilalchraibi** [MicrosoftDocs/azure-devops-docs#10903]
[The image that is displayed in the page seems old and not up to date.
Here is a capture of the new image:
![image](https://user-images.githubusercontent.com/44674415/121563283-44468500-c9e8-11eb-93a3-f53916102fce.png)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f04bf6a-1455-8770-0a2e-da22f644bced
* Version Independent ID: d63dea23-3678-60c4-c028-c4b618fc3613
* Content: [Analytics permissions and security - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-security?view=azure-devops)
* Content Source: [docs/report/powerbi/analytics-security.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/analytics-security.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@bilalchraibi - Thank you for the feedback. You are correct, the image is out of date. I'll be updating it by the end of this week.
