### ISSUE TITLE
PowerBI Example query has the incorrect field selection

### ISSUE THREAD

**Issue by ploegert** [MicrosoftDocs/azure-devops-docs#10908]
In the following example/walk through, it references a sample query under this section:
https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=powerbi#sample-queries

If you look at the query, the sixth line references the select:

```
...
            &"&$select=WorkItemId,Title,WorkItemType,State,AreaSK "
...
```

I believe this is incorrect as it is missing the "Area,Iteration,AssignedTo" and should instead look like the following:
```
            &"&$select=WorkItemId,Title,Area,Iteration,AssignedTo,WorkItemType,State,AreaSK "
```

I made this comment due to if you go further down in the walk through under the transforms, it talks about the need to expand Area, Iteration,etc here: [Transform](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=powerbi#expand-area-iteration-assignedto-columns)

As a user following along, it wasn't immediately obvious why you didn't see those fields in the query until you slowed down and through about it. In either case, it's likely very minor detail, but might be confusing to some.

Thanks!
Justin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8719e400-4445-59a4-c68e-628243710c36
* Version Independent ID: d6a76999-81c0-33cb-47a5-9ca4d8be80c3
* Content: [Feature Progress rollup sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-boards-featureprogress.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-boards-featureprogress.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@ploegert Thanks for finding this - We'll look into it - 

If you want, you can make this change yourself. Use the edit icon to make your changes and create a PR.

**Comment by KathrynEE** [comment]
@ploegert - Thank you for the correction. I'm updating the article per your feedback today.
