### ISSUE TITLE
This page is outdated for the new repos. There is no import repository option

### ISSUE THREAD

**Issue by r4kris** [MicrosoftDocs/azure-devops-docs#10916]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by MS-alsulli** [comment]
@r4kris are you saying you do not see the "import repos" button in your DevOps organization?
As seen in below screenshot, the import button is clearly visible: 
![image](https://user-images.githubusercontent.com/60909919/122418371-28972d80-cf58-11eb-915e-0e8f2922bbdd.png)

If you don't see this I would recommend creating a support request, but the docs are accurate here. Closing this at this time.
