### ISSUE TITLE
documentation update for searchcriteria and waitForCompletion on AzureFunctionV1

### ISSUE THREAD

**Issue by xaviervv** [MicrosoftDocs/azure-devops-docs#10912]
[Enter feedback here]
waitForCompletion argument is missing from the docs. The name for the argument is really confusing as well. 
The name suggests that the task will keep on running, until the function invoke is completed.
Because of this we wasted a couple of hours, and we had to go through the actual implementation to find the correct meaning.

Actual meaning, if waitForCompletion is set to true, the task will wait for the callback, otherwise the api result is returned

There is also no documentation in regards to the success criteria. It would be good to mention that by default the task succeeds if a 200 response is returned for a get. 

Is it possible to use search criteria for a reponse that is a single string, not as a json object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788ade26-087e-737f-21fd-5cc9f36666a5
* Version Independent ID: 78733f37-e78e-e044-e2e9-5e67a2eae374
* Content: [Invoke a function task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-function.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/azure-function.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@xaviervv Thank you for your feedback! The updated article will be published shortly.

Can you elaborate on this:  "Is it possible to use search criteria for a response that is a single string, not as a json object?" i'm not sure I understood your question correctly
