### ISSUE TITLE
Highlight NuGet.config comment higher up

### ISSUE THREAD

**Issue by anton-dealmeida** [MicrosoftDocs/azure-devops-docs#10919]
There's a specific line here, that would be really nice to highlight a bit more.
In NuGet.config example this line of text:
`    
`

That is extremely important, because in our use-case we have multiple repos using the same URL with slightly different paths. It is important to highlight that a bit better - we struggled for more than 2 hours at the bank to get this auth task right when we migrated to a new repository feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7145130d-abba-fcfd-2016-e50c301c3f8b
* Version Independent ID: 900031bb-7389-2fee-7099-c3f48414efd1
* Content: [NuGet Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@anton-dealmeida Thanks! Anything that can cause problems should probably be covered in the text, not just the example code.

**Comment by anton-dealmeida** [comment]
Apparently, it's common knowledge according to a co-worker but I've been using .NET for quite a while and never encountered service connection auth related issues where the auth doesn't work (regardless of us authenticating using a service connection in the previous step) because our URL for artifactory differs _slightly_ (one is an api path the other the repo path, the only difference is the addition of /api/ in the URL string)
