### ISSUE TITLE
Linking to work items in pull request descriptions doesn't work

### ISSUE THREAD

**Issue by jgn-epp** [MicrosoftDocs/azure-devops-docs#10910]
Following the guide here doesn't seem to work and the editor seems to treat `#` as regular markdown instead of linking to a work item. I can also see the `#` button under the editor is missing, when comparing to the examples on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22780209-b809-62af-1d6e-ed4c91db867a
* Version Independent ID: 1d6afe6e-6420-2395-0e0b-05902572f7ab
* Content: [Link work items to other objects - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/add-links-to-work-items?view=azure-devops#link-to-work-items-from-pull-requests-commits-and-comments)
* Content Source: [docs/notifications/add-links-to-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/add-links-to-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @jgn-epp. Once I've published an update, this issue will close. Thanks again!

**Comment by chcomley** [comment]
Hi @jgn-epp, are you still experiencing issues? I've looked into this and the "link to work items" feature is available for Azure DevOps Services, Azure DevOps Server, and TFS 2015 and above.

**Comment by jgn-epp** [comment]
Maybe I am misunderstanding things, but I expected this to link to a work item, but instead it is acting like regular markdown. And also I am not seeing the `#` button from the documentation for linking to a work item. How can I check which version of Azure Devops the organization I'm part of is using?

![image](https://user-images.githubusercontent.com/10708799/125907756-6775b508-b327-4c72-ae2a-41a70bbd4994.png)
