### ISSUE TITLE
Adding users to team

### ISSUE THREAD

**Issue by ebusho** [MicrosoftDocs/azure-devops-docs#10915]
**_Add users to a team_** section of [Add users to a project or team](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project) article contains incorrect information in the **_Azure DevOps CLI_** tab. It has examples for listing team members and showing team details, but no information about ADDING user to a team.

[az devops team](https://docs.microsoft.com/en-us/cli/azure/devops/team) subgroup doesn't have a command for adding team members, so I guess it has to be done through [az devops security group membership](https://docs.microsoft.com/en-us/cli/azure/devops/security/group/membership).

Anyway, I think it's better to just say it's not yet supported(isn't it?), as stated in [Add users to a project](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops&tabs=azure-devops-cli#add-users-to-a-project) **_Azure DevOps CLI_** tab.

**Comment by TimShererWithAquent** [comment]
@KathrynEE There are examples of list and show, but no add.

**Comment by KathrynEE** [comment]
@ebusho - Thank you for the feedback. You are correct and I am in the process of updating this article to clarify the various options available that support adding users to teams or projects. The az devops CLI only supports adding users to an organization and is documented here:  [Add users to your organization](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-organization-users?view=azure-devops&tabs=azure-devops-cli#add-users-to-your-organization).  You can't use the CLI to add users to a project or team - that isn't a supported CLI function.  I'll be clarifying this with the updates that will be published this week.
