### ISSUE TITLE
Unsubscribe or opt out of team subscription steps are unclear

### ISSUE THREAD

**Issue by rebeccaleigh** [MicrosoftDocs/azure-devops-docs#10927]
Hi, I am trying to follow the steps to opt out of a team subscription but the instructions are not clear. In the "new account manager" view, I do not see the team subscription in my personal notification settings so there is no way for my to "opt out" of a team subscription other than leaving the team or turning off the team notifications for everyone. Can you add updated images or steps to explain this better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3982f11f-c9aa-26fe-0812-f56b855c0c0e
* Version Independent ID: 54a34df8-7172-b2cc-9466-d527f0f324da
* Content: [Manage personal notification settings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-your-personal-notifications?view=azure-devops&tabs=new-account-enabled)
* Content Source: [docs/notifications/manage-your-personal-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-your-personal-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your suggestion, @rebeccaleigh, Once the update's published, this issue will close.
