### ISSUE TITLE
Can you explain in more details why Logging secrets to file in pipeline is not secure?

### ISSUE THREAD

**Issue by marcinpraczko** [MicrosoftDocs/azure-devops-docs#10921]
[Request for more explanation]

On this document - https://docs.microsoft.com/en-us/azure/devops/pipelines/security/infrastructure?view=azure-devops there is information:

> Microsoft-hosted pools offer isolation and a clean VM for each run of a pipeline. If possible, use Microsoft-hosted pools rather than self-hosted pools.

With my understanding this is clear info that VM are clean for each run of a pipeline.

However on this document: https://docs.microsoft.com/en-us/azure/devops/pipelines/security/misc?view=azure-devops there is information that secrets should be not logged to file (when running pipeline). 

This is not fully clear for me what is a risk when I am running clean VM for each run and I should not save secrets to a file? As I agree that secrets should be kept in KV - however problem which I am facing is that a lot of secrets has been added manually to multiple KVs. One way of finding out what was added is to have solution which dump secrets, parse them and generate report related with secret values (whether values are correct). 

Could you give an example (in this doc) - why logging secrets to file in pipelines is 'consideration' and should be avoided, please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcea6ccb-570f-da20-f9ba-97894cc91cbf
* Version Independent ID: 0444933a-f1c6-cd0c-8386-e0da3bd0fd9c
* Content: [Other security considerations - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/misc?view=azure-devops)
* Content Source: [docs/pipelines/security/misc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/misc.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cveld** [comment]
The first document is scoped to Microsoft hosted agents which are fresh on every run.
The second document is scoped more broadly. I believe the logging to files is only problematic in cases where the agent is reused for other pipeline runs. This counts for agent pools with custom build agents that are shared across various teams.
