### ISSUE TITLE
Download Build Artifacts task: downloadType: all in documented badly

### ISSUE THREAD

**Issue by KUGA2** [MicrosoftDocs/azure-devops-docs#10926]
#downloadType: 'single' # Choose whether to download a single artifact or all artifacts of a specific build. Options: single, specific

downloadTypeDownload type | (Required) Choose whether to download a single artifact or all artifacts of a specific build. Default value: single
--| --

You should document, that "all" is a valid option. "all" should be in `monospaced ` letters to amplify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops&viewFallbackFrom=azure-devops-2020)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
This seems confusing. "specific" means "all artifacts of a specific build". "specific" and "all" don't usually mean the same thing. 

We can't put "all" in the code typeface - it's not a value for the argument. 

Why are we using the word "all" at all, instead of "the artifacts of a specific build"? 

@RoopeshNair

**Comment by KUGA2** [comment]
But 'all' works fine! It is pretty simple to understand.

You are saying that 'specific' does what I want? This is very misleading, I would interprete 'all' and 'specfic' as opposites, and 'single' and 'specific' as synonyms

**Comment by TimShererWithAquent** [comment]
Hi @KUGA2 - The two listed options are _single_ and _specific_. I don't think "all" should be in a different typeface because it isn't listed as an option. We may need to reword the sentence.

@RoopeshNair for visibility.

**Comment by KUGA2** [comment]
Well then you need to explain the difference between _single_ and _specific_. They sound like synonyms to me.

**Comment by steved0x** [comment]
I have updated this with some notes on downloadType. The task input dependency for artifactName is also specified. This is part of our new task reference, which is generated from the task source, and includes all inputs, aliases, required/optional status, defaults, allowed values, and dependencies on other inputs. Please check it out and let us know that you think,

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines

Thank you.
