### ISSUE TITLE
How often does the Agent_version change

### ISSUE THREAD

**Issue by gsxmax** [MicrosoftDocs/azure-devops-docs#10930]
Hi team,

One question about how often does the Agent_version change? Our user have concern about if the version always changes, they have to update their agent again and again.

Do we have plan to release some stable version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by gsxmax** [comment]
hi @TimShererWithAquent  no, I am asking about document, I understand that the agent version may change. The question is about how often the document gets updated.

**Comment by azilber** [comment]
@gsxmax I think what they're trying to say is, you need to create your own code to keep the agent updated.  Generally, the agent self-updates, so there's no need to keep rolling a new version as long as it's still running.

We roll a new version automatically every week if you're interested:  https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent
