### ISSUE TITLE
Question - Why validate the subscription this way?

### ISSUE THREAD

**Issue by mattboothman** [MicrosoftDocs/azure-devops-docs#10935]
Is anyone able to shed light on why this validation technique is used? It causes issues where users are granted permission with a custom role definition/assignment but the validator doesn't allow them to set up billing because the role definition isn't named "Contributor" or "Owner".

Where can I take my grievance to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3770d0-5b22-f550-d7fa-fe7e851eb617
* Version Independent ID: 484ee77c-14dd-f2f4-f0cb-dc5d106f306b
* Content: [Set up billing for your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/set-up-billing-for-your-organization-vs?view=azure-devops&viewFallbackFrom=tfs-2018)
* Content Source: [docs/organizations/billing/set-up-billing-for-your-organization-vs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/set-up-billing-for-your-organization-vs.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by mattboothman** [comment]
Possible duplicate of #2412

**Comment by TimShererWithAquent** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
