### ISSUE TITLE
Mermaid flowchart is not completely supported

### ISSUE THREAD

**Issue by mkrsbl** [MicrosoftDocs/azure-devops-docs#10939]
graph TD
ShortArrow --> WorksInDevOps
LongArrow ----> DontWorkInDevOps

The long arrow is supported in Mermaids live editor, but not in DevOps:
Image from DevOps:
![image](https://user-images.githubusercontent.com/78595034/122397595-68224180-cf79-11eb-8d83-44d708144f53.png)

Graph from mermaid Live editor:
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblNob3J0QXJyb3cgLS0-IFdvcmtzSW5EZXZPcHNcbkxvbmdBcnJvdyAtLS0tPiBEb250V29ya0luRGV2T3BzIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/edit##eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgSWRlYWxIZWRnZSVcbiAgICBwYXJ0aWNpcGFudCBQb3J0Zm9saW9zXG4gICAgcGFydGljaXBhbnQgQ2VydFRvRGlzdHJpYnV0ZVxuXG4gICAgcGFydGljaXBhbnQgMjAgYXMgUG9ydGZvbGlvMSBTb2xkIDIwJVxuICAgIHBhcnRpY2lwYW50IDMwIGFzIFBvcnRmb2xpbzIgU29sZCAzMCVcbiAgICBwYXJ0aWNpcGFudCA0MCBhcyBQb3J0Zm9saW8zIFNvbGQgNDAlXG5cbiAgICBDZXJ0VG9EaXN0cmlidXRlLT4-UG9ydGZvbGlvczogQW1vdW50IG9mIENlcnRzXG4gICAgUG9ydGZvbGlvcy0-PlBvcnRmb2xpb3M6IFN0b3AgaWYgMTAwJSBvYnRhaW5lZFxuICAgIENlcnRUb0Rpc3RyaWJ1dGUtPj4rUG9ydGZvbGlvczogU3RvcCBpZiBlbXB0eSBmb3IgY2VydHNcbiAgICBJZGVhbEhlZGdlJS0-PlBvcnRmb2xpb3MgOiA1MCVcbmxvb3BcbiAgICAyMC0-PjMwOiBBZGQgdm9sdW1lIHRvIHJlYWNoIFBvcnRmb2xpbyAyXG5lbmRcbmxvb3BcbiAgICAyMC0-PjQwOiBBZGQgdm9sdW1lIHRvIHJlYWNoIFBvcnRmb2xpbyAzXG4gICAgMzAtPj40MDogQWRkIHZvbHVtZSB0byByZWFjaCBQb3J0Zm9saW8gM1xuZW5kIFxubG9vcFxuICAgIDIwLT4-SWRlYWxIZWRnZSU6IEFkZCB2b2x1bWUgdG8gcmVhY2ggSWRlYWxIZWRnZSVcbiAgICAzMC0-PklkZWFsSGVkZ2UlOiBBZGQgdm9sdW1lIHRvIHJlYWNoIElkZWFsSGVkZ2UlXG4gICAgNDAtPj5JZGVhbEhlZGdlJTogQWRkIHZvbHVtZSB0byByZWFjaCBJZGVhbEhlZGdlJVxuZW5kIFxubG9vcFxuICAgIDIwLT4-MjA6IGFkZCAwLDEgb2YgcG9ydGZvbGlvcyB2b2x1bWUgdG8gZWl0aGVyIGZ1bGwgcG9ydGZvbGlvIG9yIG5vIGNlcnRzIGxlZnRcbiAgICBQb3J0Zm9saW9zLT4-UG9ydGZvbGlvczogU3RvcCBpZiAxMDAlIG9idGFpbmVkXG4gICAgQ2VydFRvRGlzdHJpYnV0ZS0-PitQb3J0Zm9saW9zOiBTdG9wIGlmIGVtcHR5IGZvciBjZXJ0c1xuZW5kXG5sb29wXG4gICAgMzAtPj4zMDogYWRkIDAsMSBvZiBwb3J0Zm9saW9zIHZvbHVtZSB0byBlaXRoZXIgZnVsbCBwb3J0Zm9saW8gb3Igbm8gY2VydHMgbGVmdFxuICAgIFBvcnRmb2xpb3MtPj5Qb3J0Zm9saW9zOiBTdG9wIGlmIDEwMCUgb2J0YWluZWRcbiAgICBDZXJ0VG9EaXN0cmlidXRlLT4-K1BvcnRmb2xpb3M6IFN0b3AgaWYgZW1wdHkgZm9yIGNlcnRzXG5lbmRcbmxvb3BcbiAgICA0MC0-PjQwOiBhZGQgMCwxIG9mIHBvcnRmb2xpb3Mgdm9sdW1lIHRvIGVpdGhlciBmdWxsIHBvcnRmb2xpbyBvciBubyBjZXJ0cyBsZWZ0XG4gICAgUG9ydGZvbGlvcy0-PlBvcnRmb2xpb3M6IFN0b3AgaWYgMTAwJSBvYnRhaW5lZFxuICAgIENlcnRUb0Rpc3RyaWJ1dGUtPj4rUG9ydGZvbGlvczogU3RvcCBpZiBlbXB0eSBmb3IgY2VydHNcbmVuZCIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @mkrsbl, I'll make the update. Once published, this issue will automatically close. Thanks again.
