### ISSUE TITLE
Generate a PAT (personal access token) link is misleading

### ISSUE THREAD

**Issue by curiousan** [MicrosoftDocs/azure-devops-docs#10937]
[Enter feedback here]

Generate a PAT (personal access token)  the link points to https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-187-update which i belive is not intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf151c2-25db-ec5c-2a54-ad8cd7b83d08
* Version Independent ID: 34d221d6-1e35-f95e-30a6-fb62e2b6c98e
* Content: [Publish Packages with Jenkins & Azure Artifacts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/jenkins?view=azure-devops)
* Content Source: [docs/pipelines/packages/jenkins.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/packages/jenkins.md)
* Product: **devops**
* Technology: **devops-cicd-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by MS-alsulli** [comment]
@curiousan that definitely doesn't seem right! I raised a PR for this. @ramiMSFT when you get a chance can you have a look? ping me on Teams to discuss if needed.

Sandesh, in the meantime I think the docs that you would want to look at are here: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#create-a-pat

**Comment by MS-alsulli** [comment]
Closing as a fix is pending to be merged.
