### ISSUE TITLE
Please specify how this guidance can be implemented using the .NET client libraries. 

### ISSUE THREAD

**Issue by newOnahtaN** [MicrosoftDocs/azure-devops-docs#10934]
Please specify how this guidance can be implemented using the .NET client libraries. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @roferg
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@newOnahtaN - Can you provide more details on what guidance you're looking for? The article refers to rate limits imposed on use of REST API commands. I'm not understanding how this relates to the .NET client.

**Comment by newOnahtaN** [comment]
Hey Kathryn!

You're right, I probably put this request on the wrong page. My request is
that the guidance on this page regarding using the 'Retry-After' header
have some corresponding documentation that specifies how to implement the
advice given the Azure DevOps client libraries since it is not obvious how
to access and respond to these header values via those programming
interfaces.


Nate

**Comment by KathrynEE** [comment]
@chcomley - could you take a look at this issue? Thanks, Kathryn.

**Comment by chcomley** [comment]
Thanks @KathrynEE, I've reached out and will be in touch soon. Thank you!

**Comment by chcomley** [comment]
Hi @newOnahtaN, I'm not aware of any corresponding documentation about **using** the 'Retry-After' header. We do list some recommendations at the bottom of the article, for what it's worth:

"We recommend that you at least respond to the `Retry-After` header. If you detect a `Retry-After` header in any response, wait until that amount of time has passed before sending another request. Doing so helps your client application experience fewer enforced delays. Keep in mind that the response is 200, so you don't need to apply retry logic to the request.
If possible, we further recommend that you monitor `X-RateLimit-Remaining` and `X-RateLimit-Limit` headers. Doing so allows you to approximate how quickly you're approaching the delay threshold. Your client can intelligently react by spreading its requests out over time."

I'm closing this issue, however if you have any further questions, please @mention me. Thanks and have a great day.
