### ISSUE TITLE
Screenshot should not include "Check for credentials and other secrets"

### ISSUE THREAD

**Issue by DaveBurnisonMS** [MicrosoftDocs/azure-devops-docs#10946]
There is a screenshot for "Repository Policies". The last one is "Check for credentials and other secrets". That is not available to the pubic and is only part of a 1ES customization on top of the publicly available offering. I have had two different customers ask about why they do not see that option. Please update the screen shot. 
![project-repo-policies-browser-2020](https://user-images.githubusercontent.com/53453038/122487158-72e7d100-cf8f-11eb-9cd3-0793f21b8744.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ba72fe-98e6-cb93-f4e4-6950573a2a8c
* Version Independent ID: 260aaae9-0df1-74e6-9d39-7723d2bc7d2c
* Content: [Git repository settings - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/repository-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/repository-settings.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
These two are also about screenshots in this article, but not this specific point:

MicrosoftDocs/azure-devops-docs/issues/10458
MicrosoftDocs/azure-devops-docs/issues/9648

This one is also about freshness, including screenshots:

MicrosoftDocs/azure-devops-docs/issues/6236

@steved0x - FYI - I saw some comments from you about one of these.
@vijayma for awareness.

**Comment by vijayma** [comment]
Adding @Stephen Danielson ***@***.***> to update the image.
