### ISSUE TITLE
Build.Reason variable missing BuildCompletion event

### ISSUE THREAD

**Issue by MrOwen** [MicrosoftDocs/azure-devops-docs#10943]
In the possible events for the `Build.Reason` variable, `BuildCompletion` is missing. This event is different from `ResourceTrigger` and occurs when there is a manual trigger configured for the pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @MrOwen! I'll update the documentation shortly.
