### ISSUE TITLE
`additionalImageTags` required syntax not clear

### ISSUE THREAD

**Issue by JasonBodley** [MicrosoftDocs/azure-devops-docs#10942]
Can the `additionalImageTags` parameter description be updated to include the fact that each tag must be separated by a line feed (\n) and or include multiple tags in the example?

As per: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerComposeV0/dockercomposebuild.ts

It's not clear in the documentation.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by juliakm** [comment]
@JasonBodley Thanks for flagging this. The documentation will be updated shortly.
