### ISSUE TITLE
Misleading documentation on job names

### ISSUE THREAD

**Issue by balazsszabados** [MicrosoftDocs/azure-devops-docs#10949]
According the docs, job names must comply the following pattern: ^[-_A-Za-z0-9]*$
According my experience hyphen is not a valid character in job names as the previous pattern would suggest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82305566-bf0a-20ca-46b0-4a011ea65e0b
* Version Independent ID: 59b2347e-dc58-ee34-0000-c2c8eb309901
* Content: [Restrictions and conventions for naming objects - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/naming-restrictions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/naming-restrictions.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @balazsszabados, sounds good. Once the update's published, this issue will automatically close. Thanks again.

**Comment by steved0x** [comment]
@balazsszabados I am taking a look at this now - that pattern is the regular expression that the YAML pipeline editor uses to validate the name of a job (and several other properties in addition to job) and was added to the schema recently, see https://github.com/microsoft/azure-pipelines-vscode/pull/382 - however, I can reproduce your issue easily. I wonder if there was a regression - let me follow up on this.

**Comment by steved0x** [comment]
I am removing the bullet with the regular expression, since the other bullets in that section do accurately describe the naming constraints for a job.
