### ISSUE TITLE
-P is not supported in "mavenOptions"

### ISSUE THREAD

**Issue by anbuanand** [MicrosoftDocs/azure-devops-docs#10944]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by TimShererWithAquent** [comment]
@anbuanand - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

**Comment by anbuanand** [comment]
This is my simple Maven pipeline below, I have a spring boot application that needs a profile to be passed in the build -Pprod, -Pdev etc. but this option is not recognized. It works on a command line without Azure pipeline

trigger:
- mainbranch

pool:
  vmImage: ubuntu-18.04

steps:
- script: sudo ./mvnw -Pprod clean verify -DskipTests
  workingDirectory: #
  displayName: #
- script: echo Done Buidling JAR, now we have to transfer it!

**Comment by TimShererWithAquent** [comment]
Probably here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops

@vijayma for awareness.
