### ISSUE TITLE
'Add Mermaid diagrams to a Wiki page' links to incorrect Mermaid documentation.

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/azure-devops-docs#10956]
The [Add Mermaid diagrams to a Wiki page](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page) section's links to the Mermaid diagram types (Sequence, Gantt Charts, and Flowcharts) links to a newer version of Mermaid and those pages include syntax that is not supported by Azure DevOps Wiki's Mermaid diagrams.

**Comment by TimShererWithAquent** [comment]
@chcomley - There are a couple of other open Mermaid issues on this topic. I don't think they're duplicates, but maybe they're related.

**Comment by chcomley** [comment]
Thanks for the feedback @ScottWelker. I've created a work item to address this, which will automatically close this issue, once published. Thanks!

**Comment by trey-white** [comment]
@chcomley Is the intention to detach Microsoft documentation from Mermaid's site, or to extend ADO's feature to render these other Mermaid diagram types (ex. class and entity relationship diagrams)?

**Comment by ScottWelker** [comment]
Closed? Unfortunately the [#3696](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3696) link yields 404: Page not found. 

Any chance of getting a summary?
