### ISSUE TITLE
документ####

### ISSUE THREAD

**Issue by irinazheltisheva** [MicrosoftDocs/azure-devops-docs#10950]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths and assign to a team - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@irinazheltisheva - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
