### ISSUE TITLE
Missing info about which APIs support PAT

### ISSUE THREAD

**Issue by kevbry** [MicrosoftDocs/azure-devops-docs#10957]
The answer to this question:
`Q: Can I use basic auth with all of Azure DevOps REST APIs?`
links to this page:
https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1

It seems to imply that there is information about which Devops APIs support personal access tokens on that page, but that information does not seem to be there. Additionally, many of the links on the linked page are broken ("Device Profile" under the Authorization section, or most of the "Overview" links in the left nav), meaning it's difficult to find that information if it does exist elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
These two links were broken, per the description above:

- Device Profile https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-deviceprofile/?v=17.23h
- Azure DevOps Services Extension https://www.visualstudio.com/en-us/docs/integrate/extensions/get-started/node#files

**Comment by chcomley** [comment]
Thanks for the heads up @kevbry. Once the update's published, this issue will automatically close.

**Comment by chcomley** [comment]
I've created a GHI in the rest-api repository for those broken links. Also, I've updated the previously mentioned link to [Manage PATs using REST API](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-personal-access-tokens-via-api?view=azure-devops). Thanks!
