### ISSUE TITLE
Misleading description for AAD CAP

### ISSUE THREAD

**Issue by rikat-ms** [MicrosoftDocs/azure-devops-docs#10961]
This is related to the issue - [https://github.com/MicrosoftDocs/azure-devops-docs/issues/4898](url)

The page I opened this issue and the following page has the same expression for the "Enable Azure Active Directory (Azure AD) Conditional Access Policy (CAP) validation" setting. 
https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?view=azure-devops#application-connection-and-security-policies

Expression: "This policy doesn't apply for CAPs set in Azure AD, no matter the settings in Azure DevOps."

I understood that what this statement wanted to say was "Azure AD Conditional Access policy settings are always applied to the web flow regardless of this policy setting". However, many users are confused by this description that CAP cannot be used in Azure DevOps although this page explains CAP can be used in Azure DevOps. So, it would be better if the expression would be changed like:

1: Azure AD Conditional Access is applied for the web flow regardless of this policy setting.
2: This policy doesn't apply to the web flow. Azure AD Conditional Access is always enforced for it.
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18e09c1-5c84-4fd6-9d62-2299a3bd53cd
* Version Independent ID: c1627714-5e55-1be0-4ba5-63f264b96e5c
* Content: [Change application access, security policies for organizations - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-application-access-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-application-access-policies.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Thanks @rikat-ms - We'll look into your suggestion.

Or if you like, you can make the change yourself using the Edit icon in the upper right corner. This will create a PR for the author to merge.

**Comment by chcomley** [comment]
The update has been published, thank you.
