### ISSUE TITLE
Docs page needed with screenshots showing how to run build and set variable values

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/azure-devops-docs#10967]
I want to send a link to a customer so they can see how to manually run a pipeline and change a variable value. Preferably with screenshots.

I can't find such a docs page. Even the "pipeline basics"  section doesn't seem to have anything mentioning it's possible to manually run a pipeline.

**Comment by zivkan** [comment]
manually running a pipeline, and being able to change parameters and variables seems like basic functionality that should be documented 🤷

**Comment by cebundy** [comment]
Created work item: https://dev.azure.com/msft-skilling/Content/_workitems/edit/250932

**Comment by cebundy** [comment]
#please-close
