### ISSUE TITLE
Add info on this page to Azure Data Residency page

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/azure-devops-docs#10965]
Would be helpful if the info on this page was added to (or linked to) the Azure Data Residency page (https://azure.microsoft.com/en-us/global-infrastructure/data-residency/).

On that page, Devops is listed as "non-regional", and that same page states that data of non-regional pages may end up in "any datacenter".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe4c7a5f-322f-2c35-bbd7-14db2aee8144
* Version Independent ID: 52442a88-9e7c-b50d-4643-23ed10a3d7c3
* Content: [Data locations for Azure DevOps - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops)
* Content Source: [docs/organizations/security/data-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/data-location.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @Rvvhub, sounds like a good idea. Once the update's published, this issue will automatically close. Thanks again.
