### ISSUE TITLE
Self Hosted VSTS Container Agents updated here: 👇

### ISSUE THREAD

**Issue by azilber** [MicrosoftDocs/azure-devops-docs#10966]
We've published a 100% legacy compatible [VSTS Self-Hosted Agent Container](https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent).

Enjoy!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Hi @azilber - thanks for your input. I'm going to close this issue because there are no documentation actions for us to take -
