### ISSUE TITLE
Inconsistency in capabilities per permission

### ISSUE THREAD

**Issue by olenitsj** [MicrosoftDocs/azure-devops-docs#10963]
The introduction of the page it says "All users can create and edit their own queries and save them under My Queries. Only you can view queries saved under your My Queries space".

While in the table the "Readers" permission does not have the "Create and save managed My queries" check mark. This means that a user with only the Read permission is not able to "create and edit their own queries and save them under My Queries." as mentioned in the introduction. 

Task | Stakeholders | Readers | Contributors | Project admins
-- | -- | -- | -- | --
View and run managed queries | ✔️ | ✔️ | ✔️ | ✔️
Create and save managed My queries | ✔️ |   | ✔️ | ✔️
Contribute, delete, and manage permissions of Shared queries and folders(Stakeholders can't save Shared queries even if granted permissions) |   |   |   | ✔️
View query charts |   | ✔️ | ✔️ | ✔️
Create query charts |   |   | ✔️ | ✔️
Powerful semantic work-tracking search | ✔️ | ✔️ | ✔️ | ✔️

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/set-query-permissions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@olenitsj  - Thank you for the feedback. You are correct, Readers don't have permission to save anything. I'll update the introduction to rephrase accordingly.
