### ISSUE TITLE
Azure pipeline Git repo trigger resolution rules unclear

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#10978]
Hello,
for me the trigger rules are unclear if the yml file is present in different branches and in the branches different repo triggers are defined. Which trigger definition is then the winner. Get more details of the problem here: https://stackoverflow.com/questions/68110745/azure-pipeline-git-repo-trigger-resolution-rules-unclear

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Please check out this FAQ at the bottom of the article:
https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#a-wrong-version-of-the-yaml-file-is-being-used-in-the-pipeline-why-is-that
