### ISSUE TITLE
Missing "Resolved" state category

### ISSUE THREAD

**Issue by gocoelho** [MicrosoftDocs/azure-devops-docs#10976]
This article don't explain the "Resolved" state category

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e813268-5e00-7c84-2479-3068e27ea443
* Version Independent ID: 269b0352-2a6a-d5c9-96a3-68d5ce93c616
* Content: [Cycle time and lead time control charts - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops)
* Content Source: [docs/report/dashboards/cycle-time-and-lead-time.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/cycle-time-and-lead-time.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
The only place in the article that refers to "Resolved" is a diagram.

In [this article ](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=basic-process) (linked to in the article) Resolved is explained in a table, along with some other terms. 

Maybe a link near the diagram to that article?

**Comment by gocoelho** [comment]
"Resolved state" is different from "Resolved category state". How this can impact on lead time and cycle time widgets? When we customize the process template, the "Resolved category state" is there, but we can't find reference about it.

**Comment by KathrynEE** [comment]
@gocoelho - Thank you for the feedback. I'll update the article to clarify.  The Resolved State category isn't listed in the diagram, which I can see can lead to confusion. The Resolved State category is treated the same as In Progress state category.
