### ISSUE TITLE
Suggest having an "Allow transition to only" States instead of Restrict

### ISSUE THREAD

**Issue by salipour1105** [MicrosoftDocs/azure-devops-docs#10970]
I have discussed this before with the developer who worked on this feature. I was just wondering if there is an Action in progress for Allowing a Transition to only specific states. With Restriction, you have to create a lot of Actions. I think it is limited to 10-15 Actions, which if you have a lot of states, this function will not work for you and is very cumbersome to setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe3c173-e8cc-7172-7331-11c3fc0f9724
* Version Independent ID: ee6e18ae-8ec3-613d-3644-35f1f2199e77
* Content: [Restrict workflow transitions, apply rules to workflow states - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/apply-rules-to-workflow-states?view=azure-devops)
* Content Source: [docs/organizations/settings/work/apply-rules-to-workflow-states.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/apply-rules-to-workflow-states.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@salipour1105 -  Thank you for your feedback. There is no such action on the roadmap for Azure Boards. As people use the Kanban board to update the State of work items, allowing any-to-any tranisitions was deemed best, particularly if someone made a mistake in advancing a state. You can always suggest a feature on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=suggestion).
