### ISSUE TITLE
Queries are wrong

### ISSUE THREAD

**Issue by Laith-Said** [MicrosoftDocs/azure-devops-docs#10982]
The queries shared in this page does not work with Power Bi desktop. Power Bi desktop gives a syntax error because there are 2 "in"  in the query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b5ce20-40e9-3f32-fd63-3c6980ac4929
* Version Independent ID: eb6d654d-d773-b1ef-c03b-494f7e8a48bc
* Content: [Pipeline test summary sample Power BI reports - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-test-analytics-test-summary?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-test-analytics-test-summary.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-test-analytics-test-summary.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaghai**

**Comment by TimShererWithAquent** [comment]
There's an open related issue with the OData queries: MicrosoftDocs/azure-devops-docs/issues/10613

**Comment by KathrynEE** [comment]
@Laith-Said - Thank you for the feedback. You are correct that these queries are wrong. I've reached out to the product team to get them corrected. I'll update this Issue once the updates are published.

**Comment by KathrynEE** [comment]
@Laith-Said - Closing this issue. The article has been updated to correct the query.

**Comment by KathrynEE** [comment]
@Laith-Said -  Articles have been updated with the correct query syntax.
