### ISSUE TITLE
Focus on Component rather than Delivery Teams

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/azure-devops-docs#10986]
The visuals created here focus on creating teams as Component Team! This focus will have a negative impact on a teams ability to mitigate dependencies by maximizing them. This is not within the recommendations of SAFe but is what lots of people do.
![image](https://user-images.githubusercontent.com/5205575/123299299-47299580-d511-11eb-9435-c43a23c7b936.png)

I would recommend that the graphics present the intent of SAFe and show Feature Teams as the breakdown. We want to encourage folks to succeed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6453330a-c521-d143-3850-a960e85f687e
* Version Independent ID: 8e4ae075-b04d-b087-5412-a90270b2d917
* Content: [Scaled Agile Framework (SAFe®) and Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/safe-concepts?view=azure-devops&tabs=scrum-process)
* Content Source: [docs/boards/plans/safe-concepts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/safe-concepts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MrHinsh - Thank you for the feedback. I'm not sure I understand how to make the correction. I thought that the above graphic shows a breakdown of Feature teams - as you suggest. I don't understand what is meant by a Component team. Please clarify and I'll do what I can to update the content. Thanks again., Kathryn.
