### ISSUE TITLE
ManualValidation not supported on-premise

### ISSUE THREAD

**Issue by sergiomcalzada** [MicrosoftDocs/azure-devops-docs#10985]
Add the comment/warning

ManualValidation task is not supported in "Azure Devops Server" (aka on-premise)

https://developercommunity.visualstudio.com/t/Manual-Validation-task-not-available-in/1340627?space=22&q=Manual+Validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops-2020&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by raiyanalam** [comment]
I am no longer with the team... adding @pulkitaggarwl to take this forward.
