### ISSUE TITLE
Title rewrite suggestion

### ISSUE THREAD

**Issue by alex-cloud** [MicrosoftDocs/azure-devops-docs#10997]
[Enter feedback here]

Can I use a single command at the command line to run multiple pipelines in Azure DevOps Services? -> Can I run multiple pipelines in Azure DevOps Services using a single command?

The original title focuses on "single command", where as I guess it should be "multiple pipelines".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks, the article will be updated shortly.
