### ISSUE TITLE
Grammatical issues in the doc

### ISSUE THREAD

**Issue by alex-cloud** [MicrosoftDocs/azure-devops-docs#10990]
[Enter feedback here]

This page:  Azure Pipelines automatically builds and tests ... -> Azure Pipelines automatically build and test ...

The heading of a topic is What do **I** need to use Azure Pipelines?
The next sentence is: To use Azure Pipelines, **you** need

Suggestion: What do **You** need to use Azure Pipelines?

On https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops, under Concepts, the link text is **What _is_ Azure Pipelines?**. Suggestion: **What are Azure Pipelines?**

There are many other similar issues. Looks like you are using a variable for the "Azure Pipelines" term.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15f40a4-bae9-154b-752a-2e9f453d79e3
* Version Independent ID: 3b937e0b-f919-f227-742f-dc740ad4e6f9
* Content: [What is Azure Pipelines? - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/get-started/what-is-azure-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/what-is-azure-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the feedback @alex-cloud. We treat Azure Pipelines as singular since it's a product but you can have one or more pipelines (the actual YAML pipeline in the app).
