### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alex-cloud** [MicrosoftDocs/azure-devops-docs#10992]
[Enter feedback here]

Typo: to integrate your **CI/CI** process with most Azure services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9fbc1a-8e3f-31c9-64c2-5a21cd9c5aec
* Version Independent ID: 692a9a5a-e49a-1295-6bd9-8a82410adaf0
* Content: [Deploy to Azure index to content - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/overview-azure?view=azure-devops)
* Content Source: [docs/pipelines/overview-azure.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/overview-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@alex-cloud Thanks! Fix will go live soon.
