### ISSUE TITLE
Add users to crate a pipeline?

### ISSUE THREAD

**Issue by alex-cloud** [MicrosoftDocs/azure-devops-docs#10994]
[Enter feedback here]

Do I need to add users to create a pipeline? I don't think so. Maybe you can add "Optional" over there.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebc49d4-ce18-c3d1-fc91-ea68fcbc4f1a
* Version Independent ID: daa9f424-3286-4877-83a4-6e0350d0196f
* Content: [Sign up for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops)
* Content Source: [docs/pipelines/get-started/pipelines-sign-up.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/pipelines-sign-up.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @alex-cloud, sounds like a good idea. Once the update's published, this issue will automatically close. Thanks again.

**Comment by chcomley** [comment]
#sign-off
