### ISSUE TITLE
Clarity required

### ISSUE THREAD

**Issue by alex-cloud** [MicrosoftDocs/azure-devops-docs#10995]
[Enter feedback here]

Give them the same name if you want alignment between them. - No idea what does this means. Who's them here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
The "them" stopped me while reading. Maybe: "If you want alignment between your Azure DevOps organization and your GitHub organization, give them the same name."

Also, that explanation shouldn't be in parens. Could it be moved into the following paragraph?

**Comment by juliakm** [comment]
Thanks @alex-cloud, the article will be updated shortly.
