### ISSUE TITLE
It are gut english

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/azure-devops-docs#11008]
[Enter feedback here]

> What is Azure Artifacts?

This is incorrect. The correct title should be

What are Azure Artifacts?

Thank you for listening! I tried to be funny with the title, hope it wasn't offensive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5382202b-3007-32f0-6ba3-0061625ea079
* Version Independent ID: 60f7e250-5e0a-fcf6-8795-03897ad74def
* Content: [Azure Artifacts in Azure DevOps - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops)
* Content Source: [docs/artifacts/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/overview.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@ramiMSFT This title sounds funny, although "Azure Artifacts" is the name of the product. There's another issue that the article doesn't talk about artifacts. https://github.com/MicrosoftDocs/pipelines-dotnet-core-docker I don't know if there's a good fix for these in our current services doc structure.

**Comment by jgwinner** [comment]
I'm not changing the name of the product. The name of the product starts with a vowel, so the word before it should be "are" not "is".

**Comment by ramiMSFT** [comment]
@jgwinner Thank you for your feedback! It's referring to the service: "Azure Artifacts". Adding a work item to update the content.
