### ISSUE TITLE
Step 5 uses unnecessary placeholder text without context

### ISSUE THREAD

**Issue by ChristianMay21** [MicrosoftDocs/azure-devops-docs#11004]
In step 5, the user is instructed to copy and paste code for a `nuget.config` file, exactly as shown on the page. This step provides a config file that's non-specific to the user and has placeholders included - these placeholders are never mentioned and might be a source of confusion for someone following the documentation. 

What the user should instead do is copy and paste the code provided in the "Project Setup" section that's visible after completing Step 3 -  this is the same config file, already pre-populated with the correct URL. 

I personally think the docs should change to tell the user to just copy and paste that instead. Easier, and more specific to the user, with less chance of confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f386bad4-494d-fcd3-b3f3-44a33601e866
* Version Independent ID: c1fe07ab-8092-26b7-f3f0-a3fce718da51
* Content: [Publish a NuGet package using the command line - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thank you for the feedback!
