### ISSUE TITLE
Unclear documentation for Authorization Scopes

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-docs#11003]
>  On the Options tab, on the Build job authorization scope menu, select either:
> 
> Project collection to use the Project Collection Build service account
> 
> Current project to use the Project Build Service account.

The Options tab of what?

**Comment by TimShererWithAquent** [comment]
@MisinformedDNA Is this the page you are referring to?

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git

**Comment by MisinformedDNA** [comment]
Oh sorry. Yes, specifically at https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#authenticated-submodules

**Comment by TimShererWithAquent** [comment]
@MisinformedDNA Thanks - the issue usually picks up the page.
