### ISSUE TITLE
Limitation on the capacity of Artifacts in Multi Organization Billing

### ISSUE THREAD

**Issue by ueda-kohei1994** [MicrosoftDocs/azure-devops-docs#11009]
When setting up Multi Organization Billing and linking subscriptions to multiple organizations, there is no clear statement whether the capacity of Artifacts for one organization is 2GiB or 2GiB per subscription. Please add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 720a8e4d-9922-c1e5-9802-7637475c9307
* Version Independent ID: dce78e5e-3339-5c86-460f-da79d11f4153
* Content: [View Artifacts storage - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/artifact-storage?view=azure-devops)
* Content Source: [docs/artifacts/artifact-storage.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/artifact-storage.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@ueda-kohei1994 Thank you for your feedback! Azure Artifacts offers 2GiB of free storage for every organization.
