### ISSUE TITLE
Outdated example repo link

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#11007]
[Enter feedback here]

The example repo used in the #Docker section of this page contains no Dockerfile as described. It appears that the link should be changed to the following (confirmation needed):

https://github.com/MicrosoftDocs/pipelines-dotnet-core-docker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by GaTechThomas** [comment]
Update: 

I submitted the problem for the wrong page. The page I referenced led to the following page, which is where the problem exists:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml#docker

**Comment by steved0x** [comment]
I believe this has been fixed in our new task reference - please check the new page and let us know (I don't see a GH repo link there)

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=trx%2Ctrxattachments%2Cyaml&viewFallbackFrom=azure-devops#docker

Thank you
