### ISSUE TITLE
Wrong repository URL

### ISSUE THREAD

**Issue by roger-waldner** [MicrosoftDocs/azure-devops-docs#11017]
According to https://docs.microsoft.com/en-US/azure/devops/pipelines/artifacts/maven?view=azure-devops, point 4 the URL for the repository is https://pkgs.dev.azure.com/[ORGANIZATION_NAME]/_packaging/[ORGANIZATION_NAME]/maven/v1

I think it should be https://pkgs.dev.azure.com/[ORGANIZATION_NAME]/_packaging/[FEED_NAME]/maven/v1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03a84e2-22c7-6899-5ac1-c1ed79c05ba6
* Version Independent ID: 405e0a0e-b12b-3fd3-7135-5deb022cd9c3
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-US/azure/devops/pipelines/artifacts/maven?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@roger-waldner Thank you for your feedback! PR will be merged shortly
