### ISSUE TITLE
Which version of Mermaidjs ?

### ISSUE THREAD

**Issue by pedautreppe** [MicrosoftDocs/azure-devops-docs#11019]
It would be great to find in that WIKI documentation the version of MermaidJS that is supported in AzureDevOps.
Thus we could easily refer to the documentation of Mermaid to know in more detail which syntax is supported or not.
And of course, it would be even greater to update to the latest version of Mermaid ! :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@pedautreppe Thanks for your question. We'll look into updating the article. As for supporting the current version of Mermaids, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by trey-white** [comment]
@TimShererWithAquent @chcomley - I see direction to submit bugs but I'm not sure the issue I am having is a bug. We are wanting to know if Microsoft is intending to have the wiki able to render the other diagram types (ex. class diagrams). I do not see any info about Mermaid on the Azure DevOps roadmap since 2019. Thanks ahead of time.

**Comment by chcomley** [comment]
Hi @pedautreppe, 
We don't intend to add major new features to the Wiki product in Azure DevOps moving forward, but we do intend to round out and improve the existing feature set. This includes updating the version of Mermaid charts that Wiki uses, and will likely include adding support for additional Mermaid chart diagram types. We don't yet have that work scheduled, but expect to add it to the roadmap within the next month or two.
I'll be closing this issue now. Thanks so much for reaching out.

**Comment by chcomley** [comment]
Hi @pedautreppe and @trey-white, check it out: https://docs.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-200-update#support-for-additional-diagram-types-in-wiki-pages

Thanks!

**Comment by trey-white** [comment]
Fantastic. Thanks for the update, @chcomley.


Trey White | Solutions Architect | CDFA

**Comment by trey-white** [comment]
@chcomley - We read through the release notes and ADO's features timeline. The timeline shows the "Support for additional diagram types in wiki pages" feature as Released on 2/28, yet the release notes you've linked (also dated 2/28) say they will be implemented over the following 2-3 weeks. We are at 4 weeks now and are still getting the "Unsupported diagram type" error messages when we use State Diagrams, Pie Charts, Class Diagrams, Entity Relationship Diagrams, and User Journey Diagrams. I realize some of these are not intended to work yet (ex ERD), but wanted list them here for clarity/posterity. Does the team have an update on when the intended diagrams will render?

Trey White | Solutions Architect | CDFA

**Comment by trey-white** [comment]
Thanks. You too @chcomley!
