### ISSUE TITLE
Document way to depend on specific step/task result

### ISSUE THREAD

**Issue by TimtationOne** [MicrosoftDocs/azure-devops-docs#11024]
Hi,

I've couldn't find a way in the documentation how to create a condition in a step which only is true if a certain another step failed.

Example:
```
- bash: echo "Do some Step A stuff
  name: A
- bash: echo "Do some Step B stuff
  name: B
- bash: echo "Do some Step C stuff
  name: C
- bash: echo "Do some Step D stuff if B was executed and failed
  name: D
```
I want D to be executed only if B was executed and failed. But not if A or C failed.
I know I could introduce a variable which is set at the end of B and used as a condition in D, but this seems to be more like a workaround.
Is there way how I can access the result of B?
Or do something like this:
```
- bash: echo "Do some Step D stuff
  name: D
  condition: failed('B')
```
or
```
- bash: echo "Do some Step D stuff
  name: D
  condition: eq(B.result,'SucceededWithIssues')
```

Thanks and Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@TimtationOne Thanks for your question. This issue might be better handled as a product question - or a feature suggestion. To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).
