### ISSUE TITLE
Azure Boards Directions

### ISSUE THREAD

**Issue by Scribblee** [MicrosoftDocs/azure-devops-docs#11021]
Page "Sign up and invite some teammates" skips the updated "Advanced settings" step to set up an agile azure boards. The next page "Plan and track work" walks through the agile boards without the context of how to set up agile boards. Generic set up boards are automatically "basic" instead of "agile". Updating the instructions on creating agile boards and other boards would help prevent confusion for new users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375cc9d2-c7e5-2401-0e8f-285350c04982
* Version Independent ID: 2b6cea97-59ff-af6c-33a4-7db28e03821a
* Content: [Plan & track work, Agile, Basic, Scrum, or CMMI process - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/get-started/plan-track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/get-started/plan-track-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Scribblee - Thank you for this feedback. I agree that the content needs updating to support the various processes available. I've added an item to my backlog to update the article within the next month.

**Comment by Scribblee** [comment]
Thanks for the quick response!
