### ISSUE TITLE
Missing documentation indicating not supported on-prem

### ISSUE THREAD

**Issue by arcdev** [MicrosoftDocs/azure-devops-docs#11029]
When trying to use this task on Server, on-prem, it reports:
`Pipeline Artifact Task is not supported in on-premises. Please use Build Artifact Task instead.`

Could not documentation to that extent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops&viewFallbackFrom=azure-devops-2020)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
Thanks for your feedback!
