### ISSUE TITLE
Stakeholders unable to reorder cards vertically on Kanban boards

### ISSUE THREAD

**Issue by ntvbsrene** [MicrosoftDocs/azure-devops-docs#11039]
We have recently begun adding stakeholders to collaborate via the Kanban boards. But for some reason they can't change the order of the cards vertically. They are able to change the cards horizontally, to move it to different columns. 

After searching I saw that the option to drag and drop on the boards for stakeholders was added last year. But I see no one mentioning this issue. Is there an option or setting I'm missing? Or is this done deliberately?

**Comment by TimShererWithAquent** [comment]
@ntvbsrene 
Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.

@KathrynEE @mijacobs for awareness -

**Comment by ntvbsrene** [comment]
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/boards/sprint-173-update

This one explains that dragging between columns had been added last year.
Our stakeholders would very much like the ability to also reorder the cards vertically within the same column.

**Comment by KathrynEE** [comment]
@ntvbsrene - Thank you for your inquiry. The ability to reorder items within columns is directly connected to placing work items by priority order. This isn't a supported feature for those with Stakeholder access. If you want to request a feature change, please log it on our [Developer Community page](https://developercommunity2.visualstudio.com/report?space=21&entry=suggestion).
