### ISSUE TITLE
Lack of clarity on the default behavior of the run condition of jobs in a stage

### ISSUE THREAD

**Issue by Cutuy** [MicrosoftDocs/azure-devops-docs#11033]
> You can specify conditions under which a step, job, or stage will run.
    * Only when all previous dependencies have succeeded. This is the default if there is not a condition set in the YAML.

Per my understanding, 

Jobs in a stage, by default, if not specified with any explicit `dependsOn` nor `condition` values, can run without waiting or depending on any other jobs in that stage. Therefore, for jobs in a stage, the statement that "Only when all previous dependencies have succeeded" is not correct.

This understanding comes from the given example in the [Dependencies page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#dependencies):

![image](https://user-images.githubusercontent.com/9101928/124363908-0ad1f580-dbf3-11eb-8573-8b49beb4b9e2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @Cutuy! You're right, jobs can run in parallel when they have different agents. I'll make an update to the article to make this clearer.
