### ISSUE TITLE
Unpack the agent into the directory of your choice.

### ISSUE THREAD

**Issue by solmateusz** [MicrosoftDocs/azure-devops-docs#11030]
You really should add o this text "Unpack the agent into the directory of your choice." that directory cannot have spaces in the name, otherwise releases are failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425b68d1-4ba0-5657-4e09-f3aac361ea09
* Version Independent ID: f8044e9d-98e2-6e00-b513-a91e772b2ef8
* Content: [Deploy an Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@solmateusz I'll fix that today, thank you for letting us know.
