### ISSUE TITLE
.well-known/openid-configuration

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [MicrosoftDocs/azure-devops-docs#11048]
For Azure Active Directory apps there is Open ID Connect configuration endpoint available
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

I can't see any mention of this feature for DevOps REST API. It simplifies client configuration when dedicated libraries are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by jan-tosovsky-cz** [comment]
I specifically miss the supported values for these properties:

- issuer
- authorization_endpoint
- token_endpoint
- token_endpoint_auth_methods_supported
- jwks_uri
- userinfo_endpoint
- response_modes_supported
- response_types_supported
- end_session_endpoint

**Comment by jan-tosovsky-cz** [comment]
Some background can be found in related feature request: https://developercommunity.visualstudio.com/t/Add-support-for-OpenID-Connect-Discovery/1472583

**Comment by chcomley** [comment]
Thanks for your feedback, @jan-tosovsky-cz, I've added this info to the article. Once published and live, this issue will automatically close. Thanks again!
