### ISSUE TITLE
Does not work with locally hosted installs

### ISSUE THREAD

**Issue by jeparrish** [MicrosoftDocs/azure-devops-docs#11040]
Docs should mention this only works with hosted DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Azure Boards with Microsoft Teams - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/integrations/boards-teams.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **karrg**

**Comment by KathrynEE** [comment]
@jeparrish - Thank you for the feedback. For clarification, are you indicating that Microsoft Teams doesn't work with on-premises Azure DevOps Server deployments? Which version are you working with? Are you finding that none of the features work or select features don't work?

**Comment by jeparrish** [comment]
Yes, on-premises Azure Devops does not work with Teams in any way.  When adding any of the Devops apps on teams, it only allows you to choose hosted installs. Very disappointing.

**Comment by KathrynEE** [comment]
@jeparrish - I double-checked with the product team and confirmed that the integration with Microsoft Teams is only supported for the cloud version. I'm updating the article accordingly.
