### ISSUE TITLE
Parameters - enum?

### ISSUE THREAD

**Issue by nexxai** [MicrosoftDocs/azure-devops-docs#11046]
In the `Parameters` section, the single Schema example uses `enum` as a type but it isn't listed in the list of types below nor in any other documentation.

![Screen Shot 2021-07-07 at 3 29 33 PM](https://user-images.githubusercontent.com/4316564/124832180-7f7d9a80-df39-11eb-9ca3-2aa6a4448e0a.png)

Can someone update the docs to either remove the wrong type, or add the type with the appropriate description and provide an example of how to use it in the list of examples right below the list of types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#parameters)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@nexxai In this example, the allowable values are the set of values in the following table that make up the enum. The enum's members represent a list of allowable types that are listed in the following table. I'll see if I can get that updated with a better example to make it more clear.

**Comment by steved0x** [comment]
I have added some clarification to that section and it should be live later today.
