### ISSUE TITLE
Misleading DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE

### ISSUE THREAD

**Issue by shizhMSFT** [MicrosoftDocs/azure-devops-docs#11057]
The documentation should explicitly mention that `DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE` refers to the passphrase for the signing key. It could be the repository key or the delegation key.

Orignal feedback from @monishguru

> The issue is with the passphrase which is mentioned in the documentation. The documentation states the passphrase to be used after initialization is Repository Passphrase, whereas when we initialize the image repo with a private delegate key, it looks for the private key's passphrase, but not the repository passphrase. Please correct this in documentation, as this is misleading.

Related: https://github.com/Azure/acr/discussions/556

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971cc718-07a5-eaf3-f0bc-f85590309faf
* Version Independent ID: c10c998c-e2cb-6946-3513-4efcad549fed
* Content: [Docker Content Trust in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/content-trust?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/content-trust.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/content-trust.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by ramiMSFT** [comment]
@shizhMSFT Thank you for your feedback! The article will be updated shortly
