### ISSUE TITLE
'Enterprise' visibility option

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/azure-devops-docs#11056]
When trying to create a new Azure DevOps project today (12 July 2021), there is a third option for project visibility: Enterprise. This article should be updated to include this option and how it compares to Private and Public options.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993e00a3-b7d1-8095-5960-f6f12e8606a4
* Version Independent ID: e125d539-3678-2ab4-3591-f055e7225cbc
* Content: [Create a project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/create-project?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/projects/create-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/create-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Customery, Thanks for your feedback. "Enterprise" isn't an option for visibility when you're creating a project. This may have once been an internal MSFT option. Thanks again!
