### ISSUE TITLE
non-internet joined machines

### ISSUE THREAD

**Issue by PCfromDCSnippets** [MicrosoftDocs/azure-devops-docs#11051]
how would one get an extension added to a server that is not internet facing?

-PC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for on-premises servers - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2020)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@PCfromDCSnippets This looks like a product question / suggestion, rather than a documentation issue. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
