### ISSUE TITLE
AzureDevOps - Setup Billing REST API

### ISSUE THREAD

**Issue by ktdixit** [MicrosoftDocs/azure-devops-docs#11053]
Hi, 

Can you please share the AzureDevOps Services REST API reference for **_Billing (GET, SET)_** - https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1

Documentation from WebPortal: https://docs.microsoft.com/en-us/azure/devops/organizations/billing/set-up-billing-for-your-organization-vs?view=azure-devops

We have multiple ADO Services Organizations and any information on getting the list of organizations which do not have "billing" enabled, want to know and later want to setup billing for those ADO organizations. 

Note: Already raised this in Powershell forum also - https://github.com/Azure/azure-powershell/issues/15445

Regards,
Krishnamurthy

**Comment by chcomley** [comment]
Hi @ktdixit, I'm so sorry for this delayed response, however we don't have a billing-related API. I recommend submitting a feature request here: https://developercommunity.visualstudio.com/search?space=21. Thank you!
