### ISSUE TITLE
Due to a bug in OneGet, this won't work without an additional step

### ISSUE THREAD

**Issue by richshadman** [MicrosoftDocs/azure-devops-docs#11061]
[Enter feedback here]

Due to a bug in oneget (located here: https://github.com/OneGet/oneget/issues/403) One must run Register-PackageSource with -SkipValidate on the same source and repository name or installing the module will fail with an error like the following:

```PackageManagement\Install-Package : Unable to resolve package source```

To expand on the example in the article, this bit needs to be run after Register-PSRespository:

```Register-PackageSource -Name "PowershellAzureDevopsServices" -Location "https://<org_name>.pkgs.visualstudio.com/<project_name>/_packaging/<feed_name>/nuget/v2" -SkipValidate```

Without this additional registration the repo can be registered and searched but nothing will install. I am using PowershellGet 2.2.4.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@richshadman Thanks for the feedback! You may need to start a new session after registering your repository. Also I recommend running the `Register-PackageSource` command with the -Trusted flag instead of the -SkipValidate. I'm updating the article shortly

**Comment by richshadman** [comment]
@ramiMSFT That does not solve the issue. Please read through the details a bit closer - the issue is the bug in OneGet (I linked it in the description). I actually have the **Trusted** flag already however that doesn't get around the issue of the credentials issue in the bug posted above when trying to download the file from the package server.

I just ensured I was updated to latest powershell get and verified the issue is still there by:
1. uninstalling the package source and ps repository
2. closing powershell
3. reopening
4. reinstalling the repo and source
5. closing powerhsell
6. reopening, and try to install.

Please see the screenshots below. The first one is attempting to do so without SkipValidate -it fails. The second attempt includes SkipValidate and it succeeds. Because of the bug in OneGet, this is necessary.

**Image 1 (no skip validate):**
In this scenario if I close and reopen the powershell window and do a get package source, call, it shows the nuget source for the gallery however the IsTrusted is false. I can at this point unregister the nuget source and register with SkipValidate, and everything works as expected.
![image](https://user-images.githubusercontent.com/59030423/146846904-f0434b41-809f-4785-8078-b26f68a0ccfa.png)

**Image 2 (with skip validate):**
In this scenario when I close and reopen powershell I get the same response for get-packagesource, and am able to install the package without issues.
![image](https://user-images.githubusercontent.com/59030423/146846909-dc72620a-31cd-4d2d-9d5a-e37f4d5530f9.png)
