### ISSUE TITLE
Typo in Getting Started > Step#6

### ISSUE THREAD

**Issue by surighanta** [MicrosoftDocs/azure-devops-docs#11068]
Step number#6 in Getting started section says 'When the list of repositories appears, select your Java sample repository.' while this page is about Python Anaconda Distr.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba99893-154c-bb0d-6d84-9093175b6f43
* Version Independent ID: e792fbe8-cbd7-c760-706f-f59478895db0
* Content: [Build Java apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/java.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@surighanta Thanks for your issue - can you verify which page you mean? The only step 6 in this article reads "You might be redirected to GitHub to install the Azure Pipelines app. If so, select Approve & install." My searches for the text you quote aren't turning up results.

**Comment by TimShererWithAquent** [comment]
I think this issue is about this topic: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda

**Comment by surighanta** [comment]
That’s right, its in the anaconda page.

**Comment by juliakm** [comment]
Thanks @surighanta. This will be fixed today.
