### ISSUE TITLE
Moved our DevOps to another M365 Tenant Today

### ISSUE THREAD

**Issue by TomFranciosi** [MicrosoftDocs/azure-devops-docs#11067]
Worked like magic!  No problems to report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@TomFranciosi, this is fantastic, thank you for letting us know!
