### ISSUE TITLE
`updatePullRequest` requires higher scope than the documented

### ISSUE THREAD

**Issue by balazsorban44** [MicrosoftDocs/azure-devops-docs#11065]
The documentation below suggests the required scope for updating a Pull Request is `vso.code_write`.

Using the [`azure-devops-node-api`](https://github.com/microsoft/azure-devops-node-api)

The Personal Access Token I generated with `Code: Read&Write` in Azure DevOps resulted in a `401` error when calling the `updatePullRequest()` method to update the `description` field.

![](https://i.imgur.com/koy9SX7.png)

Updating to `Code: Read, Write & Manager` resolved the issue, so I either suggest updating the documentation or review the implementation if for some reason a higher scope is required than what would actually be needed:

![](https://i.imgur.com/3xx3RkM.png)
So this worked

Link to wrong docs:
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/update?view=azure-devops-rest-6.0#security

https://github.com/microsoft/azure-devops-node-api/issues/456 might be related?

**Comment by TimShererWithAquent** [comment]
@balazsorban44 Thanks for your question - The article that you point to is in the REST api docs, so not this repo. We're looking into getting it to the right people.

@mijacobs for awareness.

**Comment by balazsorban44** [comment]
Either that, or the documentation is not updated correctly to reflect the required scope. I wasn't sure where to post. I hope it finds the right people, thanks. 🙂
