### ISSUE TITLE
Azure Pipelines trigger paths have contradicting documentation about wildcards

### ISSUE THREAD

**Issue by Slooz** [MicrosoftDocs/azure-devops-docs#11079]
Under [`#paths`](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths), it says:

> Wild cards are not supported with path filters.

Under [`#wildcards`](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#wildcards), it says:

> - For paths:
>   - You may include `*` as the final character, but it doesn't do anything differently from specifying the directory name by itself.
>   - You may **not** include `*` in the middle of a path filter, and you may not use `?`.

This documentation seems to contradict itself and is a little confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Hi @Slooz - Thanks for your question. It looks like this one is already on our radar: MicrosoftDocs/azure-devops-docs/issues/10212
