### ISSUE TITLE
yaml snippet missing codeCoverageTool property

### ISSUE THREAD

**Issue by misidoro** [MicrosoftDocs/azure-devops-docs#11075]
yaml snippet was missing: `codeCoverageTool: 'Cobertura'` in order to show the coverage tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@misidoro - Thanks for your question. It looks like this issue is already on our radar: MicrosoftDocs/azure-devops-docs/issues/10580
