### ISSUE TITLE
Text about opening links in same tab is not sufficient

### ISSUE THREAD

**Issue by steinmr** [MicrosoftDocs/azure-devops-docs#11073]
`The default behavior of the Link element is to open the hyperlink in the work item form or Web page. If the hyperlink is authored to open in a new window (target="_blank"), then an external browser is opened.`

What does this text mean? My experience is that the default is to add **target="_blank"** and it is not explained how to change this behavior. `if the hyperlink is authored` does not make any sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d0841dc-0d20-29c7-54cc-2ee84899a6e4
* Version Independent ID: fe023f6e-e16c-c632-a135-260f54074c6b
* Content: [Link and Param XML elements reference - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/link-param-xml-elements-reference?view=azure-devops-2020)
* Content Source: [docs/reference/xml/link-param-xml-elements-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/link-param-xml-elements-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@steinmr - I'm closing this issue as this article has been archived and is no longer being updated. You might get help from our [Developer community page](https://developercommunity.visualstudio.com/AzureDevOps/report).
