### ISSUE TITLE
"Microsoft's online GuidGen tool" - that's not Microsoft's tool

### ISSUE THREAD

**Issue by scale-tone** [MicrosoftDocs/azure-devops-docs#11077]
That's some third-party web site, which probably only uses GuidGen internally.
It is even showing ads, so the owners seem to actively monetizing it. 
Stop providing free advertisement to those guys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley - This might not be the best thing to link to. I use PS new-guid if I need a guid, but people can find on-line GUID generators.

**Comment by chcomley** [comment]
Thanks so much for your feedback, @scale-tone. I've removed the link, which will be live shortly.
