### ISSUE TITLE
typo fyi 'Tenant' vs. 'Tenet'

### ISSUE THREAD

**Issue by CrustierPaper60** [MicrosoftDocs/azure-devops-docs#11087]
The following section uses 'tenant' in place of 'tenet' which is a common error and super not a big deal.
https://www.merriam-webster.com/words-at-play/tenant-vs-tenet-difference-usage

>Manage culture changes mindfully. People want to do their best work—a core tenant underlying Kanban and its associated disciplines. Apply change management principles as you adopt new practices. Create greater ownership within the team for the success of implementing WIP limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c08de8-e2c0-cb19-2dfb-d4f92826a639
* Version Independent ID: 067a9b2d-4099-b48b-a00d-01cbd6de3d86
* Content: [Kanban best practices - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/best-practices-kanban?view=azure-devops)
* Content Source: [docs/boards/boards/best-practices-kanban.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/boards/best-practices-kanban.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@CrustierPaper60 Thanks for finding this! Fix is in progress.
