### ISSUE TITLE
Use "-w 0" for base64 command

### ISSUE THREAD

**Issue by mangeg** [MicrosoftDocs/azure-devops-docs#11086]
Under [Credential setup](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#credentials-setup) and step 3 for Linux/Mac:

It would be good to change the base64 encoding to include the parameter "-w 0" to prevent the base64 command from adding newlines in the base64-coded token.
When using $(System.AccessToken) in Pipelines that token is much larger compared to personal access tokens. When converting $(System.AccessToken) to base64 several new lines are added. When concatenating this into strings, many times only the first line is used. This results in failed authentications towards the NPM feed with the error ```Unable to authenticate, need: Basic realm="https://pkgsprodcus1.pkgs.visualstudio.com/"```

This results in only the first line from the base64 coded token being added to the _password section in .npmrc
```bash
export base64pat=`echo -n "${System.AccessToken}" | base64`
echo "//pkgs.dev.azure.com/{org}/_packaging/{feed}/npm/registry/:_password=${base64pat}" >> .npmrc
```

See [this](https://developercommunity.visualstudio.com/t/systemaccesstoken-not-working-with-npm/1238199) Developer Community issue where the reporter probably was having this problem but the issue was closed as not a bug with no solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@mangeg Thank you for your feedback! The updated version will be published shortly
