### ISSUE TITLE
remove admin no longer works as described

### ISSUE THREAD

**Issue by gunnboy** [MicrosoftDocs/azure-devops-docs#11084]
you cannot remove admins from overview, you must go to permissions, project admins and remove user there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add, remove team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
I looked at the New Teams Page tab for removing an administrator. I don't see the "x" for deleting, although I'm looking at a project where I'm not an admin.

The minigraphic in the tab doesn't have a border and doesn't look current.

**Comment by KathrynEE** [comment]
@gunnboy - Thank you for this feedback. You are correct, the page is titled **Settings** and not **Overview**. I'll update the article today.
