### ISSUE TITLE
[LOC]Unnecessary asterisks are displayed (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#11089]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/pipelines/create-first-pipeline?view=azure-devops-2020&tabs=java%2Ctfs-2018-2%2Cbrowser"
![create-first-pipeline_j](https://user-images.githubusercontent.com/40815708/126097533-223f0ee6-f7fb-4681-a2b5-9927008b145b.png)

enus:"https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops-2020&tabs=java%2Ctfs-2018-2%2Cbrowser"
![create-first-pipeline_e](https://user-images.githubusercontent.com/40815708/126097537-6427c08c-6b13-4c2b-bcba-339b609dbcb8.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops-2020&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@steved0x - I've looked closely at the markdown and I don't see any problems there or in the English version. We may need to reach out to loc about this.

**Comment by juliakm** [comment]
@hyoshioka0128 Closing this issue because I'm not seeing the extra characters anymore. 

![Screen Shot 2021-09-02 at 3 58 26 PM](https://user-images.githubusercontent.com/64906/131908162-94d254b9-c861-4b6b-a171-6ccaba5a6335.png)

Source: https://docs.microsoft.com/ja-jp/azure/devops/pipelines/create-first-pipeline?view=azure-devops-2020&tabs=java%2Ctfs-2018-2%2Cbrowser
