### ISSUE TITLE
Wrong capitalization on the description of the expression `or`

### ISSUE THREAD

**Issue by norihiro** [MicrosoftDocs/azure-devops-docs#11088]
The description of `or` says as below.
```
Evaluates True if any parameter is true
```
Should `true` be `True`?

It is not clear whether the expressions `and` and `or` are case-sensitive or case-insensitive.
It's also not clear whether there are types such as string and boolean. If types exist, should it be boolean type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
This is the only lc "true" in the section about [Functions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#functions).

**Comment by norihiro** [comment]
I should have commented that the built-in function `and` says as below. Both 3rd and the last words `True` start from upper case `T`, which is not consistent with the description for the function `or`.
```
Evaluates to True if all parameters are True
```

**Comment by juliakm** [comment]
@norihiro You're right and a fix is on the way. Everything is a technically a string for variables so there isn't a boolean type. If you need to have typed values, [parameters](https://docs.microsoft.com/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#parameter-data-types) have data types.
