### ISSUE TITLE
Parameters schema does not show displayName, but it is listed under examples

### ISSUE THREAD

**Issue by jdholbrook81** [MicrosoftDocs/azure-devops-docs#11094]
The Parameters schema does not show displayName, but it is listed under examples.

Also when you search the document it will only find results for the active tabs (ie: Schema, YAML Example, Template Example). You have to know where to find what you're looking for when using the search which makes the search somewhat useless. If you know where it is you aren't searching for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#parameters)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@jdholbrook81 - Thanks for your input. It looks like this one is already on our radar: MicrosoftDocs/azure-devops-docs/issues/10104
