### ISSUE TITLE
Is there a max no. of charaters for universal package format. Can we extend major version to infinite characters? How many are supported

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/azure-devops-docs#11092]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a370ac20-91b7-d052-0dfd-e630130e9c55
* Version Independent ID: 0ac81fea-e03e-2d67-7de7-104c721b5d4c
* Content: [Publish & download Universal Packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml#package-versioning)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@Ahetejaz - It looks like you have a question about the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
