### ISSUE TITLE
Update documentation for Azure Resource Manager Service Connection types

### ISSUE THREAD

**Issue by LockTar** [MicrosoftDocs/azure-devops-docs#11096]
The documentation states that you have 2 options for creating an Azure Resource Manager Service Connection but there are 4 options. Explain what the differences are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#common-service-connection-types)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by LockTar** [comment]
Still valid. ARM Service connections are even extended without any update in the documentation.

**Comment by steved0x** [comment]
@Locktar I am reactivating this issue - we will review this article and update that section.

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
