### ISSUE TITLE
Resource Type in Permission Report when is organization level (collection)

### ISSUE THREAD

**Issue by turbotmy** [MicrosoftDocs/azure-devops-docs#11109]
the [Resourcetype ](https://docs.microsoft.com/en-us/rest/api/azure/devops/permissionsreport/permissions%20report/create?view=azure-devops-rest-6.0#resourcetype)of permission report is seems inaccurate, it doesn't mention if need to provide argument of GUID and Name of collection id , and it doesn't work it return 

`"Permissions report request should contain one Resource of type 'Repo', 'Ref', 'Release', 'Tfvc' or 'ProjectGit'.`

**Comment by TimShererWithAquent** [comment]
@turbotmy It looks like you're referencing a REST api page, not a page in the DevOps repo. I'm going to ping the author.

@wnjenkin - I think this is the page in question: https://docs.microsoft.com/en-us/rest/api/azure/devops/permissionsreport/permissions
