### ISSUE TITLE
yarn cache folder location

### ISSUE THREAD

**Issue by clough360** [MicrosoftDocs/azure-devops-docs#11112]
The examples given show the location of the yarn cache file as 
```bash
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
```
However, when running the cache restore task it fails because the location doesn't exist.

Running `yarn cache dir` shows that the actual location is `/home/vsts/cache/.yarn/v6` (on ubuntu).

Are the examples supposed to work as-is, or should further instructions be given to to either use `/home/vsts/cache` or to use `yarn config set cache-folder $Pipeline.Workspace/.yarn` to set the path to what the examples are expecting?

If it is the former, how volatile is the cache location?

**Comment by TimShererWithAquent** [comment]
@clough360 - Is this the page you're referring to?

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

Issue creation usually links to the page, but didn't this time. I want to make sure we're looking at the right page. 

Thanks -
