### ISSUE TITLE
Downloading the latest version unclear that quotes are necessary for wildcard version argument

### ISSUE THREAD

**Issue by nrichard-neudesic** [MicrosoftDocs/azure-devops-docs#11115]
It would be helpful for users new to universal packages for this documentation to state that quotes around the wildcard for version numbers are necessary in a shell script. It is stated:
"you can use wildcards **in the string you pass** to the version argument."

But as a newcomer, an exact example would be helpful.

Thank you so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
In addition to the example request, [this section](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops#downloading-the-latest-version)  has some formatting and grammar issues. For instance, I think the three version instances are supposed to be a list, but they are not displayed as such.

**Comment by ramiMSFT** [comment]
@nrichard-neudesic Thanks for the feedback!
