### ISSUE TITLE
unclear explanation about feature branch at the end of §Scheduled triggers

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/azure-devops-docs#11119]
At the end of the § "Scheduled triggers" there are explanation about the trigger of a `release` branch : "_Because release was added to the branch filters in the main branch, but not to the branch filters in the release branch, the release branch won't be built on that schedule_".

But then the next sentense is confusing because we are talking about a `feature` branch : "_Only when the feature branch is added to the branch filters in the YAML file in the feature branch will the scheduled build be added to the scheduler._".

Shouldn't we be talking about the `release` branch also ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?tabs=yaml&view=azure-devops)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Yes, thank you for letting us know. This has been fixed.
