### ISSUE TITLE
How to make service endpoint retrieve custom parameters

### ISSUE THREAD

**Issue by tatyana-kostromskaya** [MicrosoftDocs/azure-devops-docs#11129]
Looks like this page does not contain information how to use custom parameters in custom endpoints like in this solution:
https://developercommunity.visualstudio.com/t/Is-there-a-way-to-use-custom-endpoint-pa/61533?space=21&entry=problem&q=custom+endpoint&viewtype=all
So it is not clear how to provide such inputs to the endpoint.

It would be useful to this add info to the docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Create service endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops#customendpoint)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @tatyana-kostromskaya, Thank you for your feedback. Once the update gets published, this issue will automatically close. Thanks again!
