### ISSUE TITLE
Set approval checks for resources - Bug with approval checks on Environments

### ISSUE THREAD

**Issue by UsmanMohammad** [MicrosoftDocs/azure-devops-docs#11128]
I've noticed a bug with resources when using approval checks on environments.

A user who is not approved to deploy to an environment is also not able to manually select a resource. The error message is shown on resources. 
![image](https://user-images.githubusercontent.com/6882993/127291906-e664d645-e7c4-4de1-9c9e-b1dd9bc03050.png)

This shouldn't be the case as they should be able to choose a resource regardless of the environments it will get deployed to.

They can run a new pipeline build without selecting a specific resource, but we would expect them to be able to select specific resources, regardless of their environment permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@UsmanMohammad - Thanks for your question. It looks like you've found an issue with the product itself, rather than the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
