### ISSUE TITLE
The YAML pipeline editor page doesn't discuss the pipeline's default agent pool

### ISSUE THREAD

**Issue by moswald** [MicrosoftDocs/azure-devops-docs#11121]
Designer pipelines (classic editor) specify the agent pool in the settings. Yaml pipelines have the same setting, but it is _usually_ overridden in the yaml file. However, the setting still exists and is used in a couple of cases:

* Post-run cleanup tasks will be sent to the pipeline pool specified in the pipeline settings, _not_ the one(s) specified in the yaml file.
* If the yaml file does not include a pool, the run will happen on the default pipeline pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3e0c4d-0102-cb51-1794-f8569009aa5b
* Version Independent ID: 17f843b2-c55c-0bd7-dadf-1c5e16908783
* Content: [Azure Pipelines YAML pipeline editor guide - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor?view=azure-devops)
* Content Source: [docs/pipelines/get-started/yaml-pipeline-editor.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/yaml-pipeline-editor.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by geekzter** [comment]
investigating

**Comment by steved0x** [comment]
Added
