### ISSUE TITLE
Az login does not automatically log me in to az devops 

### ISSUE THREAD

**Issue by LauraArmitage** [MicrosoftDocs/azure-devops-docs#11134]
The documentation states that if I login using `az login` then I do not have to log in separately to az devops, but this does not seem to be true.

I have updated to the latest azure CLI this morning, `az -v` returns:
```
azure-cli                         2.26.1

core                              2.26.1
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
```

I already had Azure CLI installed and was already logged in for other purposes. This morning I installed Azure devops, configured my default organisation and project, and tried to use commands such as `az pipelines list`, receiving an error:
```
ERROR: TF400813: The user '[guid]\[user email address]' is not authorized to access this resource.
```

I then ran `az devops login` but now whenever I run `az pipelines list` I receive the same error but without my guid/email address in, as if it's actually logged me out. Running `az login` again does not fix this (that one appears to work as it shows me my subscriptions).

This question on StackOverflow shows someone else with the same issue: https://stackoverflow.com/questions/64323731/az-devops-login-with-az-login-still-requests-personal-access-token

Is this functionality broken or is there a mistake in the documentation? I have seen the same message in multiple places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3bebb5-3c18-a905-67b7-a1c6bd4f4522
* Version Independent ID: d6c7802a-dfdf-9852-a51b-d2ba30be70fe
* Content: [Sign in with a Personal Access Token (PAT), Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows)
* Content Source: [docs/cli/log-in-via-pat.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/log-in-via-pat.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ LauraArmitage - I'm sorry you're having problems logging in. I believe this is a product service issue and not a documentation issue. Please report your problem to our [Developer Community page](https://developercommunity.visualstudio.com/search?space=21).
