### ISSUE TITLE
The docs should indicate the VSBuild task only works on Windows

### ISSUE THREAD

**Issue by kdubau** [MicrosoftDocs/azure-devops-docs#11136]
It's not immediately clear this task doesn't work on MacOS.  Visual Studio for Mac is a MS product, and Azure Pipelines has macOS agents, one would assume this should work. Since it doesn't, it should explicitly mention so. 

On further thought - why doesn't it work? If the task is just MSBuild with the Visual Studio version property set, wouldn't that be useful on macOS too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@kdubau Thanks for your question. While we look into the docs, it looks like you also have a product question or suggestion ( that is, "why doesn't it"). To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by ramiMSFT** [comment]
@kdubau Thank you for your feedback! This task should only be used with agents running Windows. I will be updating the docs shortly.
