### ISSUE TITLE
Change Master to Main

### ISSUE THREAD

**Issue by simonua** [MicrosoftDocs/azure-devops-docs#11140]
In light of recent nomenclature changes, I suggest to change all references and imagery of _master_ to _main_. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8630b8-08ea-d706-e51c-03863b33d49e
* Version Independent ID: ad8a3b91-7b41-a6af-0d5c-b26355a49c7b
* Content: [Manage branches in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-your-branches?view=azure-devops)
* Content Source: [docs/repos/git/manage-your-branches.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/manage-your-branches.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by KathrynEE** [comment]
@simonua - Thank you for your suggestion. Will implement this by end of week.
