### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by pengfei-ye-2020** [MicrosoftDocs/azure-devops-docs#11143]
_Both States and Kanban columns are used to track the status of work. Workflow states are shared across a project while Kanban columns are shared within a team. **Only project collection admins can add custom states**, while team admins can add Kanban columns._

Users being granted with edit right to inherited process can also add custom states. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd97771-b2cf-b722-99c6-c33ca064423c
* Version Independent ID: 9ff61b2f-db48-999e-c6be-6eadad9939e9
* Content: [Backlogs/boards workflow states & state categories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/work-items/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/workflow-and-state-categories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
@pengfei-ye-2020 thank you for the feedback
