### ISSUE TITLE
Add some note to describe work items in Closed State

### ISSUE THREAD

**Issue by Haruka6002** [MicrosoftDocs/azure-devops-docs#11164]
Work items are maintained in a project as long as the project is active. 
Even if you set them to Closed, Done, or Removed, a record is kept in the data store. 
Upon testing,  work items in Closed state older than one year will disappear from board, you may only view them via queries.

Could you please add the below description to [this page](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=agile-process#removed-closed-and-done-states)?

Description: Work items in Closed state older than one year will disappear from board, you may only view them via queries.

Thanks for your help.

**Comment by gh-andre** [comment]
Just for context, this is the original issue that was logged against Azure DevOps:

https://developercommunity.visualstudio.com/t/Old-closed-items-disappear-from-boards-w/1482358

**Comment by TimShererWithAquent** [comment]
@Haruka6002 Thanks for your input. 

If you want, you can make the change yourself. Just click the pencil icon on the page. I think it's self-explanatory from there. Also, link back to this issue.

**Comment by KathrynEE** [comment]
@Haruka6002 - Thank you for this feedback. I'll update the article with the note you provided.
