### ISSUE TITLE
Example at "Run if a variable is null" checks for empty string not null

### ISSUE THREAD

**Issue by alexs77** [MicrosoftDocs/azure-devops-docs#11168]
Title was "Run if variable is **null**". In the example, `testNull` was assigned an empty string.

YAML spec at https://yaml.org/spec/1.2/spec.html#id2803362 states:

> Note that a null is different from an empty string.

See https://github.com/MicrosoftDocs/azure-devops-docs/pull/11167
The change changes the section name and variable name to better reflect what's actually done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@alexs77 Thanks for the feedback. Unlike [parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters), all pipeline variables are evaluated as strings. I'll update the heading to make it clearer that this is not a true null value.
