### ISSUE TITLE
Test Case Delete requires 'Permanently delete work items' set

### ISSUE THREAD

**Issue by Lexmark-nelsonr** [MicrosoftDocs/azure-devops-docs#11162]
To be able to delete Test Cases, you must be a member of the Project Administrators group or have the project-level permission "Permanently delete work items" set to "Allow". 

This should be in addition to the Basic+Test access level.  Unsure if Manage test plans and Manage test suites permissions set to to Allow is required to delete, but with that set and not setting the Permanently delete permission the user who created the Test Case could not delete it.

At minimum, should update the documentation for the 'Permanently delete work items' permission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93c8b9-8f57-5ee7-cf6f-a81644bd962b
* Version Independent ID: bcc7bdf0-7f4d-b22d-083e-0721565efce3
* Content: [Delete test plans, cases, & other test artifacts - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/delete-test-artifacts?view=azure-devops)
* Content Source: [docs/boards/backlogs/delete-test-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/delete-test-artifacts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@Lexmark-nelsonr - You should make a product suggestion. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

We'll look into the documentation fix you suggest -

**Comment by KathrynEE** [comment]
@Lexmark-nelsonr - Thank you for the feedback. I'll update the article this week.
