### ISSUE TITLE
Not clear how to specify source pipeline when pipelines are organized folders

### ISSUE THREAD

**Issue by PatrickMessierGoC** [MicrosoftDocs/azure-devops-docs#11177]
[Enter feedback here]

Need clarifications on how to reference a given pipeline as source when pipelines are organized in folders and subfolders.

Examples:

1. Should '/' or '\' character be used to separate folders? 
2. Should the value be quoted or not? Any particular cases or exceptions? 
3. Are all characters supported for pipeline names (ex: space)?
4. Is the source value case sensitive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
That is great feedback, sorry for the great delay in responding to this one. I am updating our reference documentation along with this article. The syntax is `\folder\pipeline name`, no quotes needed, spaces ok, starting with a `\`., with source not case sensitive. This will be live shortly.
