### ISSUE TITLE
Query Results widget

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/azure-devops-docs#11173]
Can you expand on this Query Results widget? Is dynamic filtering allowed on the widget, or only static filtering on the backend query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of widgets you can add to a dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops#query-results-widget)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@eschrader - Only static filtering is supported through the query itself.
