### ISSUE TITLE
HTML shortcuts to other wiki pages

### ISSUE THREAD

**Issue by mdathora** [MicrosoftDocs/azure-devops-docs#11181]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#yaml-tags)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

This issue relates to [an earlier issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/1298).

When I make a shortcut in Azure DevOps, I get correct shortcuts when using the instructions from the documentation:
`[Test](/Azure-DevOps)`
In this example, the root of my wiki project is called `Azure DevOps`. 

When using HTML, I want to achieve the same thing. When I use the exact shortcut from the documentation:
`<a href="/Azure-DevOps" target="_blank" title="test">Test</a>`
In this situation the shortcut leads to `https://dev.azure.com/Azure-DevOps`. How can I make the HTML link to the correct page, in the same wiki?

**Comment by chcomley** [comment]
Hi @mdathora, 
Within Markdown files, anchor IDs are assigned to all headings when rendered as HTML. The ID is the heading text, with the spaces replaced by dashes (-) and all lower case. In general, the following conventions apply:
- Punctuation marks and leading white spaces within a file name are ignored
- Upper case letters are converted to lower
- Spaces between letters are converted to dashes (-)
In your wiki, you can reference a heading in another page, for example:
[text to display](/page-name#section-name)
Please let me know if you have further questions by @mentioning me. Thanks for reaching out!
