### ISSUE TITLE
Add limitation item to docs: YAML template files should exist on filesystem

### ISSUE THREAD

**Issue by Jeej** [MicrosoftDocs/azure-devops-docs#11190]
Hi there!

Maybe you think this is a bit silly question, but it would helped me if I would have read this before I tried some stuff.

Template files should be available on disk. So for instance, when you have templates in an artifact you download, you cannot use them. Azure DevOps will give a warning about missing files.

Is it possible that you add to the section "Imposed limits" the following bullet:
- TAML files should exist on the filesystem before the start of the pipeline (it is not possible to use YAML files retrieved from consumed artifacts)

Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@Jeej Thanks for your suggestion!

**Comment by juliakm** [comment]
@Jeej  Thanks for the suggestion. I'll update the article today.
