### ISSUE TITLE
PublishPipelineArtifact@1 and DownloadPipelineArtifact@2 versus `publish` and `download` single line tasks

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/azure-devops-docs#11191]
On [this recent doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#how-do-i-consume-artifacts) edited on  02/19/2021 it is recommend that:

> We recommend upgrading from build artifacts (PublishBuildArtifacts@1 and DownloadBuildArtifacts@0) 
> to pipeline artifacts (PublishPipelineArtifact@1 and DownloadPipelineArtifact@2) for faster output storage speeds.

I have run into some mixed messaging on if these should be used because on this [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml), the less verbose single line `publish` and `download` YAML tasks are used as examples for how to Publish and download artifacts in Azure Pipelines. This was last updated on 07/13/2020. I like this less verbose approach and wonder if they use the same `PublishPipelineArtifact@1` and `DownloadPipelineArtifact@2` logic behind the scenes?

Here's the single line publish

```yml
steps:
- publish: $(System.DefaultWorkingDirectory)/bin/WebApp
  artifact: WebApp
```

Here's the single line download
```yml
steps:
- download: current
  artifact: WebApp
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@gregdegruy The `download`  and `publish` keywords are shortcuts to the [Download Pipeline Artifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops) and [Publish Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) tasks. See the [YAML schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#publish) for reference.
