### ISSUE TITLE
Repository link goes to environment page

### ISSUE THREAD

**Issue by jmiddleton** [MicrosoftDocs/azure-devops-docs#11193]
In the list of resources if you client on "repository" it goes to "environment" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40fccec-c358-843c-10d5-7ea367f6e406
* Version Independent ID: 45390d5d-c1d7-c90e-ef3f-2768d406ba7b
* Content: [Pipeline resource protection - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/resources?view=azure-devops)
* Content Source: [docs/pipelines/security/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/resources.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@jmiddleton Thanks for finding that one! Fix will go live soon.
