### ISSUE TITLE
State for Tasks is missing from Page

### ISSUE THREAD

**Issue by dennisl68-castra** [MicrosoftDocs/azure-devops-docs#11192]
Tasks also have states, but they are omitted from this page...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd97771-b2cf-b722-99c6-c33ca064423c
* Version Independent ID: 9ff61b2f-db48-999e-c6be-6eadad9939e9
* Content: [Backlogs/boards workflow states & state categories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/work-items/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/workflow-and-state-categories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dennisl68-castra - Thank you for the feedback.  The States for Tasks and other work item types is documented here: https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=agile-process#workflow-states-transitions-and-reasons.  I'll look into adding this section to the article you mention.
