### ISSUE TITLE
OData query parameter typo

### ISSUE THREAD

**Issue by brandonmpetty** [MicrosoftDocs/azure-devops-docs#11206]
You have this:
```
WorkItems?$filter=Count ge 100$apply=groupby((WorkItemType), aggregate($count as Count))&&$orderby=Count&top=5
```

But your **&** is not in the right spot.  Notice it is at the end of the parameter, leading to **&&**.
It needs to be like this:
```
WorkItems?$filter=Count ge 100&$apply=groupby((WorkItemType), aggregate($count as Count))&$orderby=Count&top=5
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c923a7-9e1f-d0fe-badc-c68facc63ab5
* Version Independent ID: 381a3f9c-c068-2eba-9f61-58f98e0bd868
* Content: [Supported OData functions and clauses - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/odata-supported-features?view=azure-devops)
* Content Source: [docs/report/extend-analytics/odata-supported-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/odata-supported-features.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@brandonmpetty  - Thank you for the correction. Am updating the article today.
