### ISSUE TITLE
Not mentioned: Migrator.exe iplist 

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#11211]
This page doesn't mention the (new) `migrator.exe iplist` command, while talking about the firewall/IP address configuration.

Let's get this added!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5d628-57bf-3b49-2b36-01a5ba4b6854
* Version Independent ID: fade1a23-443a-1e5a-575b-73461b82775c
* Content: [Import process for large collections from Azure DevOps on-premises - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import-large-collections?view=azure-devops)
* Content Source: [docs/migrate/migration-import-large-collections.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import-large-collections.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NenoLoje - Thanks for the feedback. I'm looking into it and will update soon.

**Comment by ramrajesh** [comment]
The public documentation updated with the iplist details.
https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#restrict-access-to-azure-devops-services-ips-only
