### ISSUE TITLE
Please clarify how to delete projects completely

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#11212]
On the page it reads:

> If you have projects in the soft-deleted stage, remove them completely or restore them back before running data import.

But there's no explanation of how to remove a project completely. The UI only offers an option to restore.

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff3fd07-3d7b-1244-88e4-c2cfbb3fa204
* Version Independent ID: 63f4392f-2dc6-4620-a24f-c02070dd7115
* Content: [Troubleshoot migration import to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-troubleshooting?view=azure-devops&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/migrate/migration-troubleshooting.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-troubleshooting.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE - Not sure how to address this. This is the page that describes deleting a project (next to the current article): 

https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project

_Problem_: It doesn't tell you how to remove a project completely (except to wait up to 28 days). The Azure CLI command doesn't have a **--force** parameter. 

Is restoring the only option for this failure?

**Comment by KathrynEE** [comment]
@NenoLoje - Thanks for the feedback. Updating the article today.

**Comment by NenoLoje** [comment]
@KathrynEE @TimShererWithAquent If it helps: for admins, it seems that the UI way is to first restore the project, and then delete it using the **Azure DevOps Admin Console** on the application tier itself. This will skip the "soft delete" and completely delete the project.

**Comment by MarioMajcicaAtABNAMRO** [comment]
Is there a way do bypass the soft delete or force a flush on Azure DevOps?
