### ISSUE TITLE
Clarification on the API Security 

### ISSUE THREAD

**Issue by chehabz** [MicrosoftDocs/azure-devops-docs#11216]
I'm just wondering if it should be allowed to send an authenticated Cookie in the header to call this [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/wiki/Wikis/Get?view=azure-devops-rest-5.0#oauth2) as to what is actually documented and it states oauth2.

I have tried `--header 'cookie: cookie:VstsSession=` and it worked. Is this supposed to happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chehabz - Thanks for your question. This looks like a product question - maybe a suggestion. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

If there are documentation issues around this, we can reopen this issue.
