### ISSUE TITLE
This page seems to have been copied and pasted from the Classis Release task

### ISSUE THREAD

**Issue by DSBloom** [MicrosoftDocs/azure-devops-docs#11229]
This page's documentation is not complete. The fields in the YAML snippet don't match the field names under the Arguments heading. This page is clearly copy and pasted from the Classic Release task!

The worst example?
![image](https://user-images.githubusercontent.com/5799503/129987831-689089e0-c945-416b-a971-227b3b2ad2e3.png)

There is no YAML field called 'Add Bindings.' And how can I click a button in a YAML file?

This page hasn't been touched since 12/07/2018? And there is no page available for Azure DevOps Server 2020 even though that's what I'm using and the task is available there.

This page needs some serious help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
Related but not duplicate: MicrosoftDocs/azure-devops-docs/issues/10694 - there were duplicate entries in the table. For instance, there are 3 Host name entries in the table, identical except that two are optional. There are 3 hostnameX params in the snippet, but we're left to guess if these are the same.
