### ISSUE TITLE
Incorrect description for the "Import test suites" option

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/azure-devops-docs#11233]
In this document page: https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#test-suites-tree

It mentions:
> _Import test suites_: Use this option to import test cases present in other suites from same or other test plans and even across projects.
It is now easier to reuse the suites you have created already and import them into the current suite/plan.

![document](https://user-images.githubusercontent.com/46307996/130092054-d5955806-427b-4a16-bdb4-697f06d8de54.png)

According to this description, users should be able to use the "**`Import test suites`**" option to import test suites in the same test plan.
But, according to my test, the "**`Import test suites`**" option only supports to import test suites from a test plan into a different test plan. When using the "**`Import test suites`**" feature, we can't see the current test plan is listed for the option "**`Select a test plan`**", we can only select other test plans.

![example](https://user-images.githubusercontent.com/46307996/130090778-0611ad33-9484-444a-8c3e-0b307c902a76.PNG)

**Comment by TimShererWithAquent** [comment]
@BrightRan Thanks for finding this. You might want to bring this up in the dev community. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
