### ISSUE TITLE
Typo in YAML Snippet Documentation

### ISSUE THREAD

**Issue by illflavored** [MicrosoftDocs/azure-devops-docs#11242]
There's a typo in the YAML snippet on the referenced page
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet

#versionEnvVar: # Required when versioningScheme == ByEnvVar

This should instead be

#versionEnvVar: # Required when versioningScheme == byEnvVar

as the versioningScheme is case sensitive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by pulkitaggarwl** [comment]
@aaronhallberg  can you please have someone in the team to look at this.

**Comment by TimShererWithAquent** [comment]
@aaronhallberg I will make the change and at-mention you in the PR.
