### ISSUE TITLE
PowerShell Module MgGraph for MS Hosted Agents

### ISSUE THREAD

**Issue by andreasschild** [MicrosoftDocs/azure-devops-docs#11250]
Hi.
Is there a plan to have the PS Module [Microsoft Graph](https://www.powershellgallery.com/packages/Microsoft.Graph/1.6.1) pre-installed on the MS Hosted Agents? Currently, this PS Module has to be installed before using it within PowerShell and the installation takes sometimes over 6 minutes. I need to know that to make a decision if I should use the Microsoft Graph module or if I should write an own REST wrapper.
Thank you!

**Comment by TimShererWithAquent** [comment]
Hi @andreasschild - I don't see anything about it here https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline, but double-check. 

As for plans beyond that, the developer community would be the place to ask. [Post your question here](https://developercommunity.visualstudio.com/search?space=21).
