### ISSUE TITLE
some statement is not accurate anymore

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/azure-devops-docs#11259]
> Secret variables are not automatically decrypted in YAML pipelines and need to be passed to your YAML file with env: or a variable at the root level

Looks like the above statement in this page is not accurate anymore. Since in the example in the "Set secret variables" part on this page, it says we can use macro syntax to directly get the value of secret :
> `echo "Using an input-macro works: $(mySecret)"`

It also says we cannot pass the value of a secret variable to a normal variable at the root level:
> `GLOBAL_MYSECRET: $(mySecret) # this will not work because the secret variable needs to be mapped as env`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
The text referred to in this issue is in this article: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

**Comment by juliakm** [comment]
@kind03 Thanks, the article will be updated shortly.

**Comment by juliakm** [comment]
This issue has been resolved previously.
