### ISSUE TITLE
FAQ has NuGet related question

### ISSUE THREAD

**Issue by anton-dealmeida** [MicrosoftDocs/azure-devops-docs#11253]
The FAQ's last faq is related to a NuGet publish question of some kind.

That's not entirely relevant to the UseNode Tool task. It might be slightly mislocated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Those were part of a general include file that was included with all tasks. Our new task reference removes this and covers only the specific FAQs for a particular task. Please check out our new task reference and let us know what you think.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-tool-v0?view=azure-pipelines&viewFallbackFrom=azure-devops
