### ISSUE TITLE
Token Admin documentation on Azure DevOps REST API is not complete

### ISSUE THREAD

**Issue by jrossstocholm** [MicrosoftDocs/azure-devops-docs#11265]
Issue was originally created at https://github.com/MicrosoftDocs/feedback/issues/3640 and subsequently moved here by suggestion from @rootsmusic

I am trying to work out how to use the Token Admin "[Revoke Personal Access Token](https://docs.microsoft.com/en-us/rest/api/azure/devops/tokenadmin/token%20revoke%20personal%20access%20token/revoke%20personal%20access%20token?view=azure-devops-rest-6.0)" functionality of the Azure DevOps REST API's. However - most of the functionality is not documented in enough detail to understand how to use it.

An example is the page referenced above. It should be possible to revoke a token, but there is not enough documentation for the "Request Body" to understand how. It just says that the body is a `string`.

I have tried to guess how to use it - one of the guesses was to use this as the body:

```
[
  {
    "authorizationId": "<GUID authorizationId from existing PAT>"
  }
]
```

But it throws this error:

```
{
    "$id": "1",
    "innerException": null,
    "message": "Parameter 'accessTokenKey' cannot be omitted",
    "typeName": "Microsoft.VisualStudio.Services.TokenAdmin.Client.TokenAdminBadRequestException, Microsoft.VisualStudio.Services.WebApi",
    "typeKey": "TokenAdminBadRequestException",
    "errorCode": 0,
    "eventId": 3000
}
```

Please update the documentation such that it is possible to understand how to use the REST API's.

**Comment by TimShererWithAquent** [comment]
I'm not sure where this info would go. @steved0x can you take a look?

@wnjenkin for awareness.
