### ISSUE TITLE
failed('jobName') and succeeded('jobName') will that work?

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/azure-devops-docs#11268]
Microsoft forgot to mention whether failed('jobName') will work or not. A coincidence because in my experience it does not when used in conditions. The consistency in Microsoft products is not guaranteed. It is very difficult to guess what will work when using normal human logic. 
Even if they do not work for some weird reasons known only to Microsoft, it is nice to mention that it does not work to reduce the frustration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@sijucm - We'll look into addressing this in the docs. 

This sounds like something you should bring to the attention of the dev team. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
