### ISSUE TITLE
Stakeholder Code Repository Access

### ISSUE THREAD

**Issue by MFCKSweeney** [MicrosoftDocs/azure-devops-docs#11267]
According to this article, Stakeholders have access to the code repository. Not only have I wasted an hour trying to alleviate access to the code repository, but I finally found [this](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops) Microsoft Article contrarily stating that Stakeholders do not get access to the code repository.

## Article Error

> Access level: You can add up to five users with Basic access. You're included as one of the five users. Otherwise, you can add an unlimited number of users with Stakeholder access. In public projects, both **_Stakeholder and Basic access levels grant full access to Code_**, Work, and Build and Release. But, Stakeholders only get partial access to Test and Dashboards. For more information, see Default roles & access for public projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite guest external users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MFCKSweeney, Thanks for reaching out. I can confirm that in public projects, Stakeholders DO have full access to code.
The contradictory article that you referenced actually doesn't mention "public projects", so we're updating it today with clarifying verbiage.  I'm sorry for any frustration. Please @mention me if you have any further questions about this article. Thanks again!

**Comment by MFCKSweeney** [comment]
Hi, @chcomley. Are you saying that Stakeholders have repository access only for public projects? What about private projects?

Thank you,
--Kieran

**Comment by chcomley** [comment]
Hi @MFCKSweeney, Stakeholders have **limited** access to private projects. The limits have changed over time, but they're all cataloged in this article here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/stakeholder-access?view=azure-devops

**Comment by MFCKSweeney** [comment]
Thanks for the quick response, @chcomley. From that article, it appears that stakeholders do not have access to the repository

I highly suggest that Stakeholders are granted **at least** read-only access to private repositories. Consider trying to support a client from Azure DevOps.

Depending on the agreement with the VAR, clients are likely entitled to exclusive access to their code. There are only really three ways to accomplish this now (of which I am aware):
- Pay for the client to have a Basic License.
- Create a separate remote to another repository without such licensing constraints and maintain two separate repos.
- Manually export the repo contents to a Zip folder or a SharePoint folder.

Let me know if I'm missing anything, but none of these options are appealing.
