### ISSUE TITLE
PowerShell Script Errors in samples

### ISSUE THREAD

**Issue by skyfox46311** [MicrosoftDocs/azure-devops-docs#11288]
[Enter feedback here]
The -FirewallRuleName parameter is in fact -RuleName.  Also there is no -ResouceGroup parameter.  Corresponding changes would need to be made to the passed in parameters as well.

Call the ARM scripts did not work from my YAML and returned "unknown command' for the ARM command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
This issue might be duplicate: MicrosoftDocs/azure-devops-docs/issues/9069

**Comment by TimShererWithAquent** [comment]
@azooinmyluggage isn't assignable from here any longer. @steved0x Can you take or redirect?

**Comment by skyfox46311** [comment]
Yes it’s a duplicate.
