### ISSUE TITLE
 interesting behavior of conditional job dependencies

### ISSUE THREAD

**Issue by DmytroAndriychenko** [MicrosoftDocs/azure-devops-docs#11284]
Observed interesting behavior of conditional job dependencies, which I thought would be great addition to this page.
If a job does not have condition property set and has dependsOn property set to an array of jobs (fan-in scenario), some of which are conditional, it will be executed only when ALL and every parent jobs actually succeed. If some of those jobs end up "Skipped" because the condition did not satisfy, the dependant job does not run.

However, if we also include a condition property, then dependency is used only for sequencing purposes (as in completion) and the job gets to run whenever the condition is satisfied. 

So the following job Z will run when all of the "parent" jobs complete (including Skipped, Cancelled, Failed, etc):
    - job: Z
      dependsOn:
      - A
      - B
      condition: always()

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks, we'll consider adding that to the article in the future.
