### ISSUE TITLE
projekt1

### ISSUE THREAD

**Issue by Luks900** [MicrosoftDocs/azure-devops-docs#11290]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: accba4dc-047d-984e-1169-962ae2132ebc
* Version Independent ID: 2c3d2784-b1d4-a476-a188-9efa43e941df
* Content: [Create a readme for your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-a-readme?view=azure-devops)
* Content Source: [docs/repos/git/create-a-readme.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/create-a-readme.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@Luks900 Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.
