### ISSUE TITLE
Platforms are duplicated on the runtime-parameters page

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [MicrosoftDocs/azure-devops-docs#11296]
Platforms are duplicated. Ex:

> values:
>   - windows-latest
>   - windows-latest
>   - ubuntu-latest
>   - ubuntu-latest
>   - macOS-latest
>   - macOS-latest
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@DmitriyKirakosyan Thanks, this will be fixed shortly.
