### ISSUE TITLE
Possible values are missing for distributionBatchType option on vstest task page

### ISSUE THREAD

**Issue by joukevandermaas** [MicrosoftDocs/azure-devops-docs#11303]
The options for the `distributionBatchType` parameter on the vstest task list the possible options in English as if selecting them in a UI. But it does not mention the actual string that is supposed to go in the yaml file for any of the options.

I know they are different because the default value is mentioned, and is different from any of the options that are listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@joukevandermaas Thanks for your suggestion -

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
