### ISSUE TITLE
Subscribe to pull-request notifications seem to work even when project is private.

### ISSUE THREAD

**Issue by pedalocam** [MicrosoftDocs/azure-devops-docs#11305]
Hi! 

In your documentation you state that for the Azure Repos Teams app to work you need to allow public projects/repos. I created an subscription to an organisation with the policy "Allow public projects" to false. This seems to work fine. Has this changed? Is the documentation outdated?

The documentation was last updated in 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops#feedback)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @divya
* Microsoft Alias: **divais**

**Comment by TimShererWithAquent** [comment]
@pedalocam We'll look into possible changes for the content. You could also [ask a product question](https://developercommunity.visualstudio.com/search?space=21).

**Comment by KathrynEE** [comment]
@pedalocam - Thank you for your inquiry. Integration of Microsoft Teams with Azure Repos shouldn't require the project to be public. I'll update the content today.
