### ISSUE TITLE
agent pool selection using a condition

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [MicrosoftDocs/azure-devops-docs#11314]
I would like to know if and how is possible to dynamically (conditionally) select pool.

Reason for question:
for Cloud native infrastructure deployments using terraform we are happy with Azure agent pool but for on-pred deploymens we would like to use self-hosted agent pool.

In the first case pool configuration looks like:

```yml
  pool:
    vmImage: ''ubuntu-latest'
```

for the second option we need to specify pool name so it looks somethign like:

`  pool: some-name here`

My question is how it is possible to avoid repeating whole "job" definition using condition if only pool configuration differs.

I have tried a few cases:
1. using parameters next to the pool:
pool: ${{ parameters.adoAgentPool }} but it seems that if one specified then system starts to complain that vmImage is not expected.
2. tried to pass pool: ${{ parameters.adoAgentPool }}  with parameters.adoAgentPool with empty string as well as pool: ${{ parameters.adoAgentPool }} (no space between l: and $ to mimic completely empty definiton of a pull name but then gettign another sort of errors: 
![image](https://user-images.githubusercontent.com/75432520/132505334-9730eb16-fa42-466b-8784-2502520375fa.png)
or
![image](https://user-images.githubusercontent.com/75432520/132505388-0163ca67-d22f-44c8-b80d-1e7cb515d4e8.png)

Maybe you can suggest something? Main question is how to parameterize pool between selfhosted (where a name of self-hosted pool is used) and Azure Pipelines agent pool is used that requres definition of vmImage. 

the only solution I could think of is for now is duplicate the whole job but this seems an overkill to seprate who runs the job. Having multiple steps this makes our pipeline excessively big and hard to maintain. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by boris-tarasov-maersk** [comment]
found a solution

**Comment by AnFa1978** [comment]
I have exactly the same problem as described above. How was it resolved? I can't find any solution
