### ISSUE TITLE
Matching patterns

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#11319]
Doc states:

> You can use matching patterns to limit which files get downloaded.

Emphasis on 'patterns` plural. All the examples show using a single pattern:

```
 steps:
- download: current
  artifact: WebApp
  patterns: '**/*.js'
```

I tried using multiple patterns like this:

```
 - download: current     
      patterns: 
      - '$(artifactName)/Foo.zip'
      - '$(dockerArtifactName)/**'

```

However this fails validation.

How do I provide multiple patterns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@dazinator Try this. See [File matching patterns](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops) for more details.

```
steps:
- download: current
  artifact: WebApp
  patterns: |
    **/*.js
    **/*.zip
```

**Comment by dazinator** [comment]
> @dazinator Try this. See [File matching patterns](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops) for more details.
> 
> ```
> steps:
> - download: current
>   artifact: WebApp
>   patterns: |
>     **/*.js
>     **/*.zip
> ```

Thanks @ramiMSFT
I understand now that it wants the patterns specified as a single string value, where each pattern is separated with a  new line - which is what you've shown, I was trying to specify it as a yaml array which doesn't work. Thanks for clarifying.

**Comment by dazinator** [comment]
I've left this open just in case you wanted to add this example to the docs. Otherwise please feel free to close.

**Comment by ramiMSFT** [comment]
> I've left this open just in case you wanted to add this example to the docs. Otherwise please feel free to close.

I just added an example to the article.
