### ISSUE TITLE
No ability to process response, greatly limits usefulness

### ISSUE THREAD

**Issue by woter1832** [MicrosoftDocs/azure-devops-docs#11313]
I have raised a feature request: https://github.com/microsoft/azure-pipelines-tasks/issues/15260

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
Thanks @woter1832 - The feature request is how we will track this change, so I'll close this issue. If there is documentation follow up, we can reopen.
