### ISSUE TITLE
Server or Services?

### ISSUE THREAD

**Issue by avallesalas** [MicrosoftDocs/azure-devops-docs#11318]
[Enter feedback here]

it is not clear if this document is related to Azure Devops Services (at stated in the filter on the left pane) or to Azure Devops Server (as stated on the header)

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4956039a-8296-c5e7-107e-9f42f1e39f33
* Version Independent ID: aae5a90e-0fc7-ed33-0936-10e37782d0dc
* Content: [Work tracking, process, and project limits - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops)
* Content Source: [docs/organizations/settings/work/object-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/object-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE In the article, it's tagged as all versions from TFS 2013 on. Should just the server versions be listed?

**Comment by KathrynEE** [comment]
@avallesalas - Thank you for the feedback and apologies for the confusion.  The article applies to all versions - cloud and on-prem versions of Azure DevOps. I'm updating the article today.
