### ISSUE TITLE
Incorrect statement about code access license requirements.

### ISSUE THREAD

**Issue by tinylabspace** [MicrosoftDocs/azure-devops-docs#11310]
This line is incorrect and contradicts the one directly above it:

_Users with Stakeholder access for a **_private project_** have full access to code, therefore they can search for code._

A corrected version is:

_Users with Stakeholder access for a **_public project_** have full access to code, therefore they can search for code._

To access code in a private project users always require a basic license or greater.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db5daa1f-1e5a-15e3-e121-cced95c23522
* Version Independent ID: b3318a1e-6eba-49dc-1772-fb0bd56ad857
* Content: [Functional code search options - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/project/search/functional-code-search?view=azure-devops)
* Content Source: [docs/project/search/functional-code-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/search/functional-code-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@chcomley This line of text was recently changed: MicrosoftDocs/azure-devops-docs-pr/pull/3672

Can you confirm that it is an intended?

**Comment by chcomley** [comment]
@tinylabspace You're absolutely right - thanks so much for notifying us. I updated this article yesterday and clearly missed this. Once I publish this update today, this issue will automatically close. Thanks again!
