### ISSUE TITLE
Possible typo in Task Inputs example

### ISSUE THREAD

**Issue by jsuvanto** [MicrosoftDocs/azure-devops-docs#11317]
I believe the colon (:) in the configurationStrings example is a typo:
![image](https://user-images.githubusercontent.com/31312451/132638619-f8043813-5f2d-4622-82fd-8131959eaa09.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4756ed74-d7d5-d4db-6e72-71f2910f7e1f
* Version Independent ID: 2413f407-8624-7843-a910-c610bd317319
* Content: [Azure Web App for Container task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by juliakm** [comment]
Thanks @jsuvanto. I was skeptical as well but it looks like that syntax is correct in the [task code](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureWebAppContainerV1).
