### ISSUE TITLE
Add more details about AAD Groups being expanded

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/azure-devops-docs#11322]
When viewing a Team or project membership that contains an AAD Group, can you elaborate on if you can see which users are in the AAD group, how users in the AAD group are invited and invites managed, etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07738454-4b1a-eff5-6c16-69e963ab2663
* Version Independent ID: a63f1dad-0378-5ce3-97e9-ec66afffb206
* Content: [Add users or groups to a team or project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/add-users-team-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/add-users-team-project.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chcomley - HI Chrystal, can you answer this customer's request for information?

**Comment by chcomley** [comment]
Hi @eschrader, Thanks for reaching out. If you want to see all of the members of the Azure AD groups, you can click on the Azure AD group contact card in the UI. I'm not sure what you mean by "how users in the Azure AD group are invited and invitees managed, etc...", but you might be looking for group rules. If that's the case, please check the following article out:  https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-by-group-membership?view=azure-devops&tabs=preview-page. Please let us know whether you have any further questions. Thank you!

**Comment by chcomley** [comment]
Hi @eschrader, I'm closing this issue, but again, please @mention me if you need any more clarification. Thank you!

**Comment by chcomley** [comment]
#sign-off
