### ISSUE TITLE
Add examples for additional hosted environments

### ISSUE THREAD

**Issue by asears** [MicrosoftDocs/azure-devops-docs#11321]
Add examples for setting up Conda with windows-2022 hosted agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b99fb08-2474-be71-62db-cbafec749cb3
* Version Independent ID: af525f70-f636-4fb2-e4e6-03a2dd759c24
* Content: [Run pipelines with Anaconda environments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-18-04)
* Content Source: [docs/pipelines/ecosystems/anaconda.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/anaconda.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Hi @asears. The Windows 2022 hosted agent environment doesn't include `conda` currently. The good news is that the 2019 environment does and I'm updating the article now. The 2022 hosted agent is under active development right now. Here's the [list of what's supported](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) in case you're curious.
