### ISSUE TITLE
Invalid Reference and Ambiguity

### ISSUE THREAD

**Issue by blatherscrossing** [MicrosoftDocs/azure-devops-docs#11333]
To whom it may concern: 

The definition for "Edit Release Environment" contains a reference to "Edit Release Definition" permission. This permission does not exist elsewhere in this document. 

Also, the definitions for "Manage Releases" and "Edit Release Pipeline" are very similar without discerning differences. Advise an update. 

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=current-page#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@blatherscrossing  - Thank you for the feedback. The **Edit release definition** should be **Edit release pipeline**. I'll update the article today. The **Manage releases** permission allows users to edit a release configuration, such as stages, approvers, and variables.
