### ISSUE TITLE
Can you define a custom Icon for the custom control?

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/azure-devops-docs#11339]
![image](https://user-images.githubusercontent.com/1866463/133106262-3be4eef1-ef48-47b2-87aa-bd8053728751.png)

Will the red boxes in the screenshot always be the icon of the extension?
What if you want to add more than one control to an extension and have different icons? Is this possible? If not can we add this limitation to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@matthid Thanks for your question. We'll look into the documentation issue. You might also want to do a feature request: 
To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by matthid** [comment]
To be honest it would be nice to have this feature and we would have used it, but for this issue we only wanted to know if it exists and I expected a sentence about this icon on the page in question :)
I have since moved to other projects so there is probably no point for me to follow this up. Thanks for your response.
