### ISSUE TITLE
AzurePowerShell@5 what is the number?

### ISSUE THREAD

**Issue by steveaf** [MicrosoftDocs/azure-devops-docs#11330]
What is the number 5 in AzurePowerShell@5 ?  Another Microsoft documentation example has @2.  Magic numbers don't help in understanding or debugging.  

This Microsoft documentation provides this sample tiny example but not the context.  Having documentation of complete, working, reference, best-practice pipelines would be much more valuable than these tiny snippets that only work when prior steps we can't see are run.  I run this step but get an error with any PowerShell executing related to service account usage, where the context would help.  

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by QuickScoP3s** [comment]
As far as I know, the number that comest after the '@' is the version number of the task
Though I can't seem to find any version history

**Comment by steved0x** [comment]
The `@5` references the major version of the task. Our new task reference includes reference documentation for all task versions, please check it out and let us know what you think, Here is the link for `AzurePowerShell@5`, and right under it in the TOC are the previous versions.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines
