### ISSUE TITLE
'inputs'-documentation of a custom control is confusing/wrong.

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/azure-devops-docs#11341]
> To define the inputs for your control contribution, use inputs property in the contribution object in the manifest. In the sample below you see two inputs, FieldName and Colors. FieldName specifies which field the control associates with.

That part is confusing because it can be understood as (note that the contribution json object also has 'properties'):
```jsonc
"contributions": [
    {  // <- The start of a contribution object
        "id": "sample-work-item-form-control",
        "type": "ms.vss-work-web.work-item-form-control",
        "description": "Custom work item form control",
        "targets": [
            "ms.vss-work-web.work-item-form"
        ],
        "properties": {
            "name": "My Control",
            "uri": "workItemControl.html",
            "height": 600
        },
        "inputs": [ // <- A property of the 'contribution' object
            {
                "id": "FieldName",
                "description": "The field associated with the control.",
                "type": "WorkItemField",
                "properties": {
                    "workItemFieldTypes": ["String"]
                },
                "validation": {
                    "dataType": "String",
                    "isRequired": true
                }
            },
            {
                "id": "Colors",
                "description": "The colors that match the values in the control.",
                "validation": {
                    "dataType": "String",
                    "isRequired": false
                }
            }
        ]
    }
]
```

But that is not how it works. I'd suggest adding `inputs` to the "properties" section above or to the full example, which would make it much clearer. Because currently when you read the docs you assume that the above list of values in the 'properties' section is exhaustive, which it obviously isn't given that 'input' needs to be part of the 'properties'-object as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @matthid, Thanks for your feedback. I'll look into this in the near future. If you're at all interested in making the update yourself, I invite you to [become a contributor](https://docs.microsoft.com/en-us/contribute/) to our docs! We'd love that! Either way, I'll keep you updated. Thanks again.

**Comment by chcomley** [comment]
I've made updates. This issue will close when they're published. Please feel free to @mention me if you feel it needs further clarification or modification. Thank you!
