### ISSUE TITLE
add more details on filters

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-devops-docs#11345]
the app says we can use filters but what are all the options?  what does `c:` mean? `tag:` is self-documenting

![image](https://user-images.githubusercontent.com/14079228/133284801-2b1127ed-5fe3-491c-8b6f-1f242f5f268b.png)

reference: [Search and share work items using compose extension](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops#search-and-share-work-items-using-compose-extension)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Azure Boards with Microsoft Teams - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops#search-and-share-work-items-using-compose-extension)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/integrations/boards-teams.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **karrg**

**Comment by KathrynEE** [comment]
@spottedmahn - Thank you for your inquiry. You should be able to used the options provided here, [Functional work item search](https://docs.microsoft.com/en-us/azure/devops/project/search/functional-work-item-search?view=azure-devops). I'll update the article to reflect this reference.
