### ISSUE TITLE
Wildcard docs need to be updated.

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#11349]
With the [Sprint 192 release](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters) it looks like the docs on wildcards could use an update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#wildcards)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Wildcards come up in several of the issues for this article. This page provides a summary:

MicrosoftDocs/azure-devops-docs/issues/10212

I don't want to mark this one as duplicate, because all the issues are slightly different. One fix might apply to all of them, though.
