### ISSUE TITLE
workItemFieldTypes is confusing in Custom Control documentation.

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/azure-devops-docs#11340]
Given the following part of the doc:

> workItemFieldTypes - Defines an array of field types that this input supports. Valid values are
> - String
> - Integer
> - Double
> - HTML
> - PlainText
> - Boolean
> - Guid
> - DateTime
> - TreePath

Because it is not perfectly obvious how they map to the field types you can create in a process:

![image](https://user-images.githubusercontent.com/1866463/133104904-e3b99963-87fe-4053-b067-2aa4df272936.png)

To increase the confusion multiple other reference pages even have different (enum) values: 
 - https://github.com/microsoft/azure-devops-extension-api/blob/bd06868b78a14b3840823b393f6fe3378b2be59d/src/WorkItemTracking/WorkItemTracking.ts#L435-L495
 - https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/fieldtype?view=azdevops-ext-latest

We found the correct type basically with trial/error instead of using the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e6cb0ed-c129-901c-10a2-909354aa562f
* Version Independent ID: ceb10d41-b306-0d3f-ccb2-124a3ba69332
* Content: [Add a custom control to the work item form - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops)
* Content Source: [docs/extend/develop/custom-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/custom-control.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up on this, @matthid. This  article hasn't been updated in 4 years, so it needs some more work! However, I've updated the list of workItemFieldTypes in the meantime. When the PR gets published, this issue will automatically close.
