### ISSUE TITLE
Dependent on VMSS Upgrade Policy

### ISSUE THREAD

**Issue by jb185t** [MicrosoftDocs/azure-devops-docs#11348]
After some struggling and made it work, it turned out that AzureVmssDeployment task was very powerful and useful one. 👍 

One of the biggest difficulty I had was that in the portal the VMSS Upgrade Policy should be set to "Automatic...." or "Rolling..." so that the custom_script can be downloaded and executed automatically.

Wish in this docs, mentioning about the upgrade policy be added. Sure it will help beginners like me save lots of time  

One more. In the code snippet in this doc, the value for vmssOsType was given linux which was rejected when I ran it. It was case sensitive and should have been Linux.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5233d9b7-e301-998a-f37b-91494dc55b10
* Version Independent ID: bcb2f43d-5b24-3df2-0515-9e724e03fb55
* Content: [Azure virtual machine scale set deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-vmss-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-vmss-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-vmss-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
I have added some information about the upgrade policy, and the parameter value has been corrected as part of our new task reference, which is built from the task source and includes all task inputs as well as their attributes such as required/optional, and dependencies on other task inputs. Please check it out and let us know what you think.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-vmss-deployment-v0?view=azure-pipelines&viewFallbackFrom=azure-devops
