### ISSUE TITLE
"CMMI" is used but never defined, and I at least have no idea what it means...

### ISSUE THREAD

**Issue by S-Lovell** [MicrosoftDocs/azure-devops-docs#11343]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916ec07a-d3fb-cfd5-0052-245296d69f49
* Version Independent ID: 5c87aa39-9a7b-6a84-c8f3-ae51f5465392
* Content: [View and add work items from Work Items page - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/view-add-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/work-items/view-add-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/view-add-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
We should at least spell out the abbreviation. There are pages we could link to - not sure if this is the best one: https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi/guidance-background-to-cmmi?view=azure-devops

**Comment by KathrynEE** [comment]
@S-Lovell  - Thank you for the feedback. CMMI stands for the Capability Maturity Model Integration (CMMI) as described in [Background to CMMI](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi/guidance-background-to-cmmi?view=azure-devops). CMMI is one of 4 process models that Azure DevOps supports. I'll do a sweep through the content to make sure that we spell out on first use or point to the [CMMI process](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi-process?view=azure-devops).
