### ISSUE TITLE
dependency-tracker is not working - how we can get support?

### ISSUE THREAD

**Issue by V-MTHOMAS6** [MicrosoftDocs/azure-devops-docs#11344]
dependency-tracker is not working - how we can get support?

Microsoft says, this extension is not belongs to them and they won't support.

Mentioned in market place.

"This extension is not supported by any product group. The longevity and support is not guaranteed, please use at your own risk."

So what we have to do here, this extension is published as Microsoft extension and if it not usable, why don't you remove it?

**Comment by TimShererWithAquent** [comment]
@V-MTHOMAS6 - Thanks for your suggestion. As product feedback, you should probably reach out to the dev team. 
To make sure it gets in front of the right people, please [submit your suggestion here](https://developercommunity.visualstudio.com/search?space=21).

@KathrynEE for awareness.
