### ISSUE TITLE
"Members of this role can use the environment when authoring yaml pipelines"?

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/azure-devops-docs#11351]
Can you elaborate more on this sentence "Members of this role can use the environment when authoring yaml pipelines."

What does "authoring yaml pipelines" exactly mean? It means users with "User" role of the target environment can run the pipeline to the stage containing deployment job of this environment or just means users can choose what stage to run when manually triggering the pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @kind03. I'm pushing an update now. You should be able to use the Environment when editing or creating a pipeline.
