### ISSUE TITLE
Typo in bold text: DevOps

### ISSUE THREAD

**Issue by RaymondHartog** [MicrosoftDocs/azure-devops-docs#11356]
[Enter feedback here]

Typo in text: *DevOps ** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
This looks like a simple formatting issue from a recent (7 hours) check in. Fixing now.

**Comment by TimShererWithAquent** [comment]
Thanks @RaymondHartog -

**Comment by RaymondHartog** [comment]
👍
