### ISSUE TITLE
Add proper example of using artifacts across stages

### ISSUE THREAD

**Issue by epa095** [MicrosoftDocs/azure-devops-docs#11368]
There is a section called "Use Artifacts across stages", but this does not give a good example of how to actually *use* artifacts across stages. I propose an example where 
- Stage 1 creates an artifact which is named using `$(system.JobId)`. The name of this artifact is properly written to a variable (not easy given all the quoting needed)
- Stage 2 reads the artifact name from the variable and uses it.

Related to #6677

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#use-artifacts-across-stages)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@epa095 I'm adding a detailed example shortly.
