### ISSUE TITLE
Should link the macos-11 image contents and note that for iOS 15 that image is REQUIRED

### ISSUE THREAD

**Issue by spoelstraethan** [MicrosoftDocs/azure-devops-docs#11369]
Should link the macos-11 image contents and note that for iOS 15 that image is REQUIRED. See #4060

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Related issue:
https://github.com/actions/runner-images/issues/4060

macOS-1015 image is fully unsupported and the image been removed from the article.
https://github.com/actions/runner-images/issues/5583

Thank you for the information in this issue and in the related 4060 issue.
