### ISSUE TITLE
Mixed approach for agent

### ISSUE THREAD

**Issue by kallsu** [MicrosoftDocs/azure-devops-docs#11361]
Is it possible use a mixed approach between self-hosted and MS-hosted agent ?

Context:

- the Release ( CD - continuous delivery ) is managed by the MS-Hosted agent, using the classic pipeline interface.
- the Pipeline ( CI - continuous integration ) is managed by the self-hosted agent

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@kallsu - This sounds like a product question. You should probably check with the dev team. To make sure it gets in front of the right people, please [submit your product question here](https://developercommunity.visualstudio.com/search?space=21).
