### ISSUE TITLE
Slack is translated!

### ISSUE THREAD

**Issue by zahollib** [MicrosoftDocs/azure-devops-docs#11362]
[Enter feedback here]
Hello,

The French translation of the page does not allow you to read it correctly; indeed, Slack is translated! Would it be possible not to translate Hook and Slack?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Create a service hook with Slack - Azure DevOps](https://docs.microsoft.com/fr-fr/azure/devops/service-hooks/services/slack?view=azure-devops)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by TimShererWithAquent** [comment]
@aaronhallberg "Hook" and "Slack" are used throughout, so it's not as easy as formatting them in backticks in one instance or in code. Do we need to reach out to localization for this issue?
