### ISSUE TITLE
Field "tagSource" incorrect optional values in GitHub Release task documentation

### ISSUE THREAD

**Issue by liwilliamnz2020** [MicrosoftDocs/azure-devops-docs#11386]
[Tag Source value not correct]
the page link is here https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops#arguments
For the field "tagSource" in GitHub Release task, When I run it in the pipeline, it says Only 'gitTag', or 'userSpecifiedTag' options are allowed. However in this documentation page it says Options: auto, manual.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed (only gitTag and userSpecifiedTag are allowed values) in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines
Please check it out and let us know what you think. Thank you.
