### ISSUE TITLE
Inaccurate information

### ISSUE THREAD

**Issue by brs713** [MicrosoftDocs/azure-devops-docs#11384]
Can I create a dashboard with information that spans two or more projects?
Yes. Project dashboards allow you to add widgets for any project and any team. To learn more, see Add, rename, and delete dashboards, Add a dashboard.

The referenced page contradicts that information - suggesting that team dashboards (not project) can use widgets that have access to other projects as long as the widget can refer to a team.  The previous paragraph states, "Use project dashboards to display information or status about **the** project".  And there's no other reference to widgets from other projects anywhere on the page.

This issue is almost 3 years old and indicates information between dashboards is limited at best - https://developercommunity.visualstudio.com/t/Single-Dashboard-for-Multiple-Projects/365500?space=21

So clearly, "Project dashboards allow you to add widgets for **any project** and **any team**" is a false & misleading statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6ba175-f805-0d7f-5b89-94aa82da9a11
* Version Independent ID: a7d55122-680e-4e4b-56e6-9a4d1b673c06
* Content: [Work across projects FAQ - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/work-across-projects-faqs?view=azure-devops)
* Content Source: [docs/project/work-across-projects-faqs.yml](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/work-across-projects-faqs.yml)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@brs713 - Thank you for your feedback. I have recently updated this article, [Widget catalog](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops), which indicates those widgets that are cross-project. Only two widgets support cross-project/team selection: Sprint Burndown and Sprint Burnup.  So, this is limited supported, to be sure. 

Regarding the Feature request, https://developercommunity.visualstudio.com/t/Single-Dashboard-for-Multiple-Projects/365500?space=21. this is overseen by the product team, and not something I can address. 

That said, there is a slight, albeit not elegant workaround, that you can use to collect information from different projects onto a dashboard. That is using the Embedded Webpage widget. You can add the URL from different projects to show data or reports from different projects or teams.  These pages remain fully interactive through the dashboard. Hope this helps.
