### ISSUE TITLE
An example would be helpful.

### ISSUE THREAD

**Issue by pyacobellis** [MicrosoftDocs/azure-devops-docs#11385]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeb2956-beca-447d-c9a6-a859f3cfc4bf
* Version Independent ID: 89f2a014-99bb-420d-265c-42515d30c80b
* Content: [Python Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/python-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/python-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
This issue is more specific: MicrosoftDocs/azure-devops-docs/issues/9982

We can probably close them both off this fix - @pyacobellis what do you think?
