### ISSUE TITLE
Azure Artifacts Extension no longer required

### ISSUE THREAD

**Issue by FokkoVeegens** [MicrosoftDocs/azure-devops-docs#11387]
The paragraph;

> Azure Artifacts
> If you used Azure Artifacts in your collection, then you will need to install the Azure Artifacts extension in your organization post import to view your Azure Artifacts data.

Is no longer required. It should be removed from this topic to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f16894d-2250-c822-d2b0-1b6bca92f871
* Version Independent ID: 0713dbbb-0cff-42f5-9659-04b12e82d6bb
* Content: [Post migration import steps to validate and configure an organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-post-import?view=azure-devops)
* Content Source: [docs/migrate/migration-post-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-post-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ FokkoVeegens - Thank you for the feedback. I'll update the article to reflect the change.
