### ISSUE TITLE
Link under Prerequisites section is not working

### ISSUE THREAD

**Issue by umhail** [MicrosoftDocs/azure-devops-docs#11394]
"what is Analytics" link under Prerequisites section is not working

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea920e3-9644-ae0c-120d-db9e899ee192
* Version Independent ID: 452bf06e-28f4-7815-72b3-16a4c2086e47
* Content: [Connect to Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-connect.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/data-connector-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@umhail Can you check the link again? I just tried it and this page opened without a problem - https://docs.microsoft.com/en-us/azure/devops/report/powerbi/what-is-analytics?view=azure-devops

I also don't see anything odd about the link in the markdown. - Thanks

**Comment by umhail** [comment]
Yes, it’s working now. I got document not found error before, not sure why….

**Comment by TimShererWithAquent** [comment]
@umhail - Glad to hear it - be sure to let us know about any broken links you find in the future. It's a big help to us -
