### ISSUE TITLE
fix "For organizations using the dev.azure.com domain":

### ISSUE THREAD

**Issue by iz4blue** [MicrosoftDocs/azure-devops-docs#11408]
[Enter feedback here]
Hi.

While building an azure devops agent,
A proxy allowed address was missing and a pull request was created.

https://github.com/MicrosoftDocs/azure-devops-docs/pull/11407

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64ca92c-b7d5-3142-71fb-306d32a37281
* Version Independent ID: dfef40cf-2f50-4c03-bc97-bafa6c305108
* Content: [Deploy an Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@iz4blue - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please provide more context about what you're trying to accomplish.

**Comment by iz4blue** [comment]
I tried to access the agent through a square proxy.
However, when I checked, there was a lack of domains that needed to be allowed.
Therefore, additional domains that needed permission were found and submitted.
