### ISSUE TITLE
Add JavaScript syntax to environment variable access examples

### ISSUE THREAD

**Issue by mtakemoto** [MicrosoftDocs/azure-devops-docs#11411]
I'm looking into scripting release pipelines with Gulp.js and found the following section:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#access-variables-through-the-environment

I know that the correct syntax for environment variable access is `process.env.VARIABLE_NAME` but thought it would be helpful to have for those that are new to JS and to show that Azure Pipelines supports the language.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @mtakemoto! We'll be sure to add that to the docs.
