### ISSUE TITLE
KubernetesManifest@0 examples are not valid

### ISSUE THREAD

**Issue by olljanat** [MicrosoftDocs/azure-devops-docs#11423]
All examples on this page misses `kubernetesServiceConnection` which is currently mandatory parameter for `KubernetesManifest@0` task `deploy` action.
![image](https://user-images.githubusercontent.com/6213926/135224843-43a18874-74e8-4dd0-96dc-9be754cbbb0e.png)

Some of examples also misses `namespace` which means that deployment will be done to default namespace which is against of best practices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@olljanat Thank you for flagging this! I'll work on an update.
