### ISSUE TITLE
Update example to use system variable for definition id

### ISSUE THREAD

**Issue by michael-livingston** [MicrosoftDocs/azure-devops-docs#11422]
Hi

The first example doesn't use definitionId = $(System.DefinitionId); It is hard-coded to 1.

Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a129c0-8a1c-40c3-47e6-8d95fbce5f26
* Version Independent ID: 8437e895-7164-8585-3b0d-adacd05e6851
* Content: [Using Tasks to Retain Runs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/run-retention?view=azure-devops)
* Content Source: [docs/pipelines/build/run-retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/run-retention.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @moswald
* Microsoft Alias: **maoswald**

**Comment by TimShererWithAquent** [comment]
@steved0x - Saw your name on a related article. Please reassign if necessary -
