### ISSUE TITLE
Associate Test Plans with a Github Repository

### ISSUE THREAD

**Issue by fjerrichiello** [MicrosoftDocs/azure-devops-docs#11427]
Is it possible to associate my tests with a test case through a github repository? Since the documentation was last updated two years ago, I was wondering if anyone has found a solution to this or if it was even possible. Our team would prefer to not have to store our repositories in two different places.

---
#### Document  

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@fjerrichiello - This seems like a product question. To make sure it gets in front of the right people, please [submit your question here](https://developercommunity.visualstudio.com/search?space=21).

I'm going to keep this issue open, in case we want to make doc changes.

**Comment by codytipton-hpg** [comment]
@fjerrichiello I will submit my own question per the link provided by @TimShererWithAquent 

If you happen to have received a solution or feedback would greatly appreciate it being shared here.

Thanks.
