### ISSUE TITLE
Documentation on usage of AzDevOps Pipeline Cache task with Docker fail

### ISSUE THREAD

**Issue by nickho** [MicrosoftDocs/azure-devops-docs#11425]
Using the cache configuration for docker as stated in the documentation fail with the error on the `Docker Save` step :
```
Error response from daemon: No such image: cache
```
I believe the cache usage is wrong or something is missing in the documentation.

You can reproduce with an empty pipeline and just the statements in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thank you for your feedback! Please let us know if you're still facing an issue with the new example.
