### ISSUE TITLE
'Use a PAT' Powershell Example Produces Incorrect Result

### ISSUE THREAD

**Issue by richaswr** [MicrosoftDocs/azure-devops-docs#11420]
In the 'Use a PAT' section, the Powershell script contains a typo. The following line:

`$B64Pat = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$MyPat"))`

Contains a colon before $MyPat is referenced in the call to UTF8.GetBytes, which produces a very different value.

The colon should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @richaswr. I'll fix this today, which will automatically close this issue. In the future, we'd love your help! Please consider becoming a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! Thanks again!
