### ISSUE TITLE
โครงสร้างพื้นฐานระบบคลาวด์ที่ยั่งยืนและเชื่อถือได้ด้วย Azure

### ISSUE THREAD

**Issue by GGuy001** [MicrosoftDocs/azure-devops-docs#11435]
วางใจระบบคลาวด์ของคุณ
รับการรักษาความปลอดภัยตั้งแต่เริ่มต้น—สนับสนุนโดยทีมผู้เชี่ยวชาญ และการปฏิบัติตามข้อกำหนดเชิงรุกที่ได้รับความไว้วางใจจากองค์กร รัฐบาล และสตาร์ทอัพ

อ่านอีบุ๊ก

การลงทุน 1B+ USD ในการวิจัยและพัฒนาด้านความปลอดภัยและผู้เชี่ยวชาญด้านความปลอดภัยในโลกไซเบอร์ 3,500 คน
ความปลอดภัยเป็นพื้นฐานสำหรับ Azure ใช้ประโยชน์จากการรักษาความปลอดภัยแบบหลายชั้นที่มีให้ในศูนย์ข้อมูลทางกายภาพ โครงสร้างพื้นฐาน และการดำเนินงาน โดยมีผู้เชี่ยวชาญด้านความปลอดภัยทางไซเบอร์คอยตรวจสอบเพื่อปกป้องทรัพย์สินและข้อมูลทางธุรกิจของคุณ

เรียนรู้เพิ่มเติมเกี่ยวกับการรักษาความปลอดภัย Azure

ข้อเสนอการปฏิบัติตามข้อกำหนดมากกว่า 90 รายการ
ปกป้องข้อมูลของคุณในเชิงรุกและปรับปรุงการปฏิบัติตามข้อกำหนดด้วยความครอบคลุมการปฏิบัติตามข้อกำหนดที่ครอบคลุมที่สุดของผู้ให้บริการระบบคลาวด์

เรียนรู้เพิ่มเติมเกี่ยวกับการปฏิบัติตามข้อกำหนดของ Azure

ความมุ่งมั่นแน่วแน่ต่อ ความเป็นส่วนตัว
ข้อมูลของคุณ ขับเคลื่อนประสบการณ์ของคุณ ควบคุมโดยคุณ หลักการความเป็นส่วนตัวหลักของเราคือคุณเป็นเจ้าของข้อมูลของคุณ เราจะไม่ใช้เพื่อวัตถุประสงค์ทางการตลาดหรือการโฆษณา รู้สึกมั่นใจในตำแหน่งที่ข้อมูลของคุณถูกจัดเก็บและรักษาความปลอดภัย

เรียนรู้เพิ่มเติมเกี่ยวกับความเป็นส่วนตัวและการปกป้องข้อมูล Azure

วิเคราะห์สัญญาณภัยคุกคาม 8 ล้านล้านทุกวัน
นำระบบคลาวด์และข่าวกรองขนาดใหญ่จากประสบการณ์ด้านความปลอดภัยของ Microsoft หลายทศวรรษมาใช้งาน ทำให้การตรวจจับภัยคุกคามและการตอบสนองของคุณฉลาดขึ้นและเร็วขึ้นด้วยสัญญาณความปลอดภัยที่ขับเคลื่อนด้วย AI ที่ปรับปรุงการดำเนินการด้านความปลอดภัยของคุณให้ทันสมัย

โครงสร้างพื้นฐานระบบคลาวด์ที่ยั่งยืนพร้อมผลกระทบในท้องถิ่น
ที่ Azure เรามองว่าความยั่งยืนและการตอบสนองของมนุษยชาติต่อการเปลี่ยนแปลงสภาพภูมิอากาศเป็นหนึ่งในความท้าทายที่ยิ่งใหญ่ที่สุดในชีวิตของเรา

เราเชื่อว่ายังไม่สายเกินไปที่จะวางแผนเพื่ออนาคตที่สะอาดและเป็นมิตรกับสิ่งแวดล้อมมากขึ้น เรามุ่งมั่นที่จะนำเทคโนโลยีที่ยั่งยืนมาเป็นหัวใจของนวัตกรรมของเรา เพื่อให้แน่ใจว่าเรากำลังปรับตัวและเติบโตไปพร้อมกับโลกที่มีผลกระทบต่อสิ่งแวดล้อมน้อยที่สุด

เรียนรู้วิธีที่คุณสามารถเข้าร่วมชุมชนระดับโลกที่มุ่งมั่นที่จะลดการใช้พลังงาน เปลี่ยนไปใช้กริดที่เป็นกลางมากขึ้น และส่งเสริมอนาคตที่เป็นมิตรกับสิ่งแวดล้อมมากขึ้นด้วยเทคโนโลยีที่ยั่งยืนและสร้างสรรค์จาก Azure

ประโยชน์ของคาร์บอนของระบบคลาวด์คอมพิวติ้ง
ผลการศึกษาในปี 2018 พบว่าการใช้แพลตฟอร์มคลาวด์ของ Microsoft Azure นั้นสามารถประหยัดพลังงานได้มากกว่าถึง 93 เปอร์เซ็นต์ และมีประสิทธิภาพคาร์บอนมากกว่าโซลูชันในองค์กรถึง 98 เปอร์เซ็นต์

อ่านการศึกษาความยั่งยืนและคลาวด์คอมพิวติ้ง
การพัฒนาที่เหนือกว่าแนวทางการปฏิบัติงาน
ความยั่งยืนมักถูกมองจากมุมมองของการปฏิบัติงาน โดยภารกิจด้านสิ่งแวดล้อมถือเป็นศูนย์ต้นทุนในธุรกิจ โดยถือเป็นความเสี่ยงหรือการปฏิบัติตามข้อกำหนดที่ต้องจัดการ แต่สำหรับ Azure ศูนย์ข้อมูลและโครงสร้างพื้นฐานระบบคลาวด์ที่ยั่งยืนนั้นเป็นมากกว่าธุรกิจ—พวกเขาให้โอกาสอันเหลือเชื่อในการตอบแทนชุมชนที่เราดำเนินการอยู่

สีฟ้ามีความมุ่งมั่นที่จะมุ่งเน้นไปที่สี่ประเด็นสำคัญของผลกระทบต่อสิ่งแวดล้อมให้กับชุมชนท้องถิ่นคาร์บอนน้ำเสียและระบบนิเวศ

100%

พลังงานหมุนเวียนภายในปี 2568

น้ำเป็นบวกภายในปี 2030

เติมน้ำให้มากกว่าที่เราบริโภคภายในปี 2030

ไร้ขยะ

รับรองภายในปี 2030

สุทธิศูนย์

การตัดไม้ทำลายป่าจากการก่อสร้างใหม่

ตอบแทนชุมชนท้องถิ่น
ด้วยความยั่งยืนที่เป็นแก่นของธุรกิจของ Microsoft เราได้ขยายเป้าหมายของเราเพื่อความยั่งยืนด้านสิ่งแวดล้อมนอกเหนือจากที่เราดำเนินการศูนย์ข้อมูล เรามีส่วนร่วมอย่างแข็งขันในกว่า 40 โครงการทั่วโลกเพื่อช่วยในการสร้างผลกระทบในท้องถิ่นและปรับปรุงผลลัพธ์ด้านสิ่งแวดล้อม

นี่คือตัวอย่างบางส่วน:

การใช้น้ำให้เกิดประโยชน์สูงสุด
ใช้มาตรวัดน้ำอัจฉริยะช่วยบรรเทาวิกฤตน้ำในโรงพยาบาลภูมิภาคแอฟริกาใต้

การฟื้นฟูป่าใหม่
ชุมชนสีเขียวที่มีป่าไม้พื้นเมืองในไอร์แลนด์

การปรับปรุงคุณภาพน้ำในชุมชนและความพร้อมใช้งาน
การฟื้นฟูแหล่งที่อยู่อาศัยตามธรรมชาติของบีเวอร์ในรัฐวอชิงตันตอนกลาง

ป่าไม้ในเขตเมือง
ปลูกต้นไม้และส่งเสริมการดูแลใน Des Moines, Iowa

ส่งเสริมประสิทธิภาพการใช้พลังงาน
โครงการการมีส่วนร่วมของชุมชนเพื่อปรับปรุงประสิทธิภาพการใช้พลังงานและการประหยัดพลังงานที่วิทยาลัยไอริช

ร่วมมือกับโครงการพลังงานหมุนเวียน
การเตรียมแรงงานที่มีทักษะเพื่อใช้ประโยชน์จากงานพลังงานแสงอาทิตย์ที่วิทยาลัยในรัฐเวอร์จิเนีย

เรียนรู้เพิ่มเติมเกี่ยวกับโครงการริเริ่มการพัฒนาชุมชนศูนย์ข้อมูลของเรา
สำรวจนวัตกรรมด้านพลังงานสำหรับเทคโนโลยีคลาวด์ที่ยั่งยืนรุ่นต่อไป
การแช่เย็นด้วยของเหลว
แบตเตอรี่ UPS แบบโต้ตอบกับกริด
เชื้อเพลิงสะอาดสำหรับสำรองไฟ
การแช่เย็นด้วยของเหลว

เรียนรู้ว่าวิธีการระบายความร้อนของเซิร์ฟเวอร์แบบใหม่สามารถช่วยลดผลกระทบต่อสิ่งแวดล้อมของศูนย์ข้อมูลทางกายภาพได้อย่างไร—ลดการใช้พลังงานในขณะที่ให้กำลังการประมวลผลที่สูงขึ้นและช่วยขจัดการใช้น้ำ

ดาวน์โหลด PDF
ดูวิธีที่ลูกค้าสร้างสรรค์นวัตกรรมด้วยโซลูชัน Azure ที่ยั่งยืน
บีอา
Buhler
จอห์นสัน คอนโทรลส์
Bee'ah ผู้บุกเบิกด้านพลังงานขับเคลื่อนการจัดการที่ยั่งยืน

ด้วยการลงทุนในอุตสาหกรรมต่างๆ ตั้งแต่การจัดการขยะและการให้คำปรึกษาด้านสิ่งแวดล้อมไปจนถึงพลังงานหมุนเวียน เทคโนโลยี การขนส่งที่ยั่งยืน และการฝึกอบรมและการพัฒนา บริษัท Bee'ah ผู้บุกเบิกสหรัฐอาหรับเอมิเรตส์ (UAE) ได้สร้างมาตรฐานใหม่ในด้านนวัตกรรมที่ยั่งยืนในตะวันออกกลาง ภาค.

นวัตกรรมฮาร์ดแวร์สำหรับคลาวด์
พลิกโฉมการพัฒนาฮาร์ดแวร์โอเพนซอร์ซแบบไฮเปอร์สเกลที่แชร์กันทั่วทั้งอุตสาหกรรม

ด้วย Open Compute Project และการทำงานร่วมกันที่แปลกใหม่อื่น ๆ Microsoft กำลังนำการออกแบบและการพัฒนาฮาร์ดแวร์มาสู่แบบเปิด ทำให้เกิดนวัตกรรมที่ไม่เคยมีมาก่อนที่เป็นประโยชน์ต่อทุกคน

เปิดโครงการคอมพิวเตอร์
Open Compute Project (OCP) เป็นชุมชนระดับโลกของผู้นำเทคโนโลยีที่ทำงานร่วมกันเพื่อปลดล็อกโครงสร้างพื้นฐานด้านไอทีที่เป็นกรรมสิทธิ์ เพื่อทำให้ฮาร์ดแวร์มีประสิทธิภาพ ยืดหยุ่น และปรับขนาดได้มากขึ้น ทำให้มีตัวเลือก ปรับแต่ง และประหยัดค่าใช้จ่ายมากขึ้นสำหรับลูกค้า

โมเดลการพัฒนาแบบเปิดระดับแนวหน้านี้ส่งเสริมระบบนิเวศอุตสาหกรรมที่มีชีวิตชีวาสำหรับการปรับใช้ศูนย์ข้อมูลทั่วโลกในระบบคลาวด์ เรากำลังแชร์เซิร์ฟเวอร์และการออกแบบศูนย์ข้อมูลเดียวกันที่ขับเคลื่อน Azure Hyperscale Cloud ของเรา เพื่อให้องค์กรทุกขนาดสามารถปรับปรุงประสิทธิภาพ ประสิทธิภาพ การใช้พลังงาน และค่าใช้จ่ายของศูนย์ข้อมูลได้

ฟังเกี่ยวกับประกาศล่าสุดจาก Kushagra Vaid วิศวกรผู้มีประสบการณ์กับทีมโครงสร้างพื้นฐานของเซิร์ฟเวอร์คลาวด์ และ Mark Russinovich หัวหน้าเจ้าหน้าที่ฝ่ายเทคโนโลยีของ Azure ดูวิดีโอ

อ่านประกาศ
โครงการโอลิมปัส
การออกแบบฮาร์ดแวร์คลาวด์ไฮเปอร์สเกลเจเนอเรชันถัดไปและโมเดลใหม่สำหรับการพัฒนาฮาร์ดแวร์โอเพนซอร์ซมอบนวัตกรรมในวงกว้าง ข้อกำหนดการออกแบบทั้งหมดเป็นโอเพ่นซอร์สและสนับสนุน OCP ซึ่งเป็นกุญแจสำคัญในการนำประโยชน์ของโอเพ่นซอร์สมาสู่อุตสาหกรรมในวงกว้าง

Project Olympus ช่วยให้ผู้ปฏิบัติงานด้านไอทีและศูนย์ข้อมูลสามารถใช้ประโยชน์จากนวัตกรรมที่พัฒนาโดยชุมชนและปรับขนาดการออกแบบฮาร์ดแวร์ที่ได้รับการพิสูจน์แล้วสำหรับรูปแบบการใช้งานเฉพาะของพวกเขา

อ่านประกาศ
MSFT-ProjectOlympus-19in-Universal-RackMSFT-ProjectOlympus-Server-Universal-Motherboard
เซอร์เบอรัส
มาตรฐานอุตสาหกรรมโอเพนซอร์สใหม่สำหรับการรักษาความปลอดภัยแพลตฟอร์มนี้ได้รับการพัฒนาร่วมกันโดยชุมชน OCP Cerberus มีส่วนประกอบที่สำคัญสำหรับการป้องกันความปลอดภัยที่หายไปจากฮาร์ดแวร์เซิร์ฟเวอร์: เพิ่มการป้องกัน การตรวจจับ และการกู้คืนจากการโจมตีบนเฟิร์มแวร์ของแพลตฟอร์ม Cerberus ช่วยให้ใช้งานเฟิร์มแวร์ได้อย่างปลอดภัยยิ่งขึ้นบนแพลตฟอร์มทุกประเภททั่วทั้งอุตสาหกรรม ตั้งแต่ศูนย์ข้อมูลไปจนถึงอุปกรณ์ IoT ข้อมูลจำเพาะของ Cerberus ยังสนับสนุนรากของความไว้วางใจตามลำดับชั้น ดังนั้นความปลอดภัยของแพลตฟอร์มจึงสามารถขยายไปยังอุปกรณ์ต่อพ่วง I/O ทั้งหมดได้โดยใช้หลักการทางสถาปัตยกรรมเดียวกัน

อ่านประกาศ
เดนาลี
Denali เป็นสถาปัตยกรรมโซลิดสเตตไดรฟ์ (SSD) ที่มีความคล่องตัวซึ่งกำหนดมาตรฐานอุตสาหกรรมใหม่ด้วย เช่น ปลดล็อกนวัตกรรม ปรับปรุงความน่าเชื่อถือ และเร่งเวลาออกสู่ตลาด เฟิร์มแวร์นั้นเรียบง่ายและอินเทอร์เฟซเป็นมาตรฐาน ลดความซับซ้อนของส่วนประกอบเหล่านี้ในขณะที่ลดต้นทุนเครื่องเสมือนและปรับปรุงประสิทธิภาพ Denali ช่วยให้ควบคุมพฤติกรรมของไดรฟ์ได้ใกล้ชิดยิ่งขึ้นและปรับแต่งไดรฟ์ให้เข้ากับปริมาณงานเฉพาะ ตลอดจนตรวจสอบความถูกต้องและปรับใช้เทคโนโลยีใหม่ได้รวดเร็วยิ่งขึ้น

ความน่าเชื่อถือเป็นความรับผิดชอบร่วมกัน
บรรลุเป้าหมายความน่าเชื่อถือขององค์กรของคุณสำหรับปริมาณงานทั้งหมดของคุณโดยเริ่มต้นด้วยรากฐานที่ยืดหยุ่นของแพลตฟอร์ม Azure cloud ออกแบบและใช้งานแอปพลิเคชันที่มีความสำคัญต่อภารกิจของคุณด้วยความมั่นใจ โดยรู้ว่าคุณสามารถไว้วางใจระบบคลาวด์ของคุณได้เนื่องจาก Azure ให้ความสำคัญกับความโปร่งใส—คอยแจ้งให้คุณทราบเสมอและสามารถดำเนินการได้อย่างรวดเร็วในระหว่างที่มีปัญหาด้านบริการ

หากคุณต้องการเพิ่มประสิทธิภาพแอปพลิเคชันที่มีอยู่บน Azure ให้เริ่มด้วยAzure Well-Architected Frameworkชุดหลักการชี้นำใน 5 เสาหลัก ได้แก่ ความน่าเชื่อถือ ความปลอดภัย ประสิทธิภาพการทำงาน การเพิ่มประสิทธิภาพต้นทุน และความเป็นเลิศในการปฏิบัติงาน

เริ่มต้นด้วยรากฐานที่เชื่อถือได้บนโครงสร้างพื้นฐาน Azure
เรียนรู้เกี่ยวกับการลงทุนอย่างต่อเนื่องของ Microsoft เพื่อรักษาและปรับปรุงความน่าเชื่อถือของแพลตฟอร์มระบบคลาวด์ใน Azure CTO และชุดบล็อก Advancing Reliabilityของ Technical Fellow Mark Russinovich ซึ่งเน้นที่สี่ประเด็นหลักเหล่านี้:

ความน่าเชื่อถือของเครือข่ายผ่านซอฟต์แวร์อัจฉริยะ
แนวทางปฏิบัติในการปรับใช้อย่างปลอดภัย
ความยืดหยุ่นของเครื่องเสมือน (VM)
การบำรุงรักษาต่ำและไม่มีผลกระทบ
เครือข่าย Microsoft เชื่อมต่อภูมิภาค Azure มากกว่า 60 แห่ง ศูนย์ข้อมูล Azure 220 แห่ง ไซต์ Edge 170 แห่ง และไฟเบอร์ภาคพื้นดินและใต้น้ำกว่า 165,000 ไมล์ทั่วโลก ซึ่งเชื่อมต่อกับอินเทอร์เน็ตที่เหลือ ณ จุดเชื่อมต่อเชิงกลยุทธ์ระดับโลก เรียนรู้เพิ่มเติมเกี่ยวกับความน่าเชื่อถือของเครือข่าย Microsoft ในบล็อกโพสต์สองส่วนนี้

ความน่าเชื่อถือเป็นความรับผิดชอบร่วมกัน
บรรลุเป้าหมายความน่าเชื่อถือขององค์กรของคุณสำหรับปริมาณงานทั้งหมดของคุณโดยเริ่มต้นด้วยรากฐานที่ยืดหยุ่นของแพลตฟอร์ม Azure cloud ออกแบบและใช้งานแอปพลิเคชันที่มีความสำคัญต่อภารกิจของคุณด้วยความมั่นใจ โดยรู้ว่าคุณสามารถไว้วางใจระบบคลาวด์ของคุณได้เนื่องจาก Azure ให้ความสำคัญกับความโปร่งใส—คอยแจ้งให้คุณทราบเสมอและสามารถดำเนินการได้อย่างรวดเร็วในระหว่างที่มีปัญหาด้านบริการ

หากคุณต้องการเพิ่มประสิทธิภาพแอปพลิเคชันที่มีอยู่บน Azure ให้เริ่มด้วยAzure Well-Architected Frameworkชุดหลักการชี้นำใน 5 เสาหลัก ได้แก่ ความน่าเชื่อถือ ความปลอดภัย ประสิทธิภาพการทำงาน การเพิ่มประสิทธิภาพต้นทุน และความเป็นเลิศในการปฏิบัติงาน

เริ่มต้นด้วยรากฐานที่เชื่อถือได้บนโครงสร้างพื้นฐาน Azure
เรียนรู้เกี่ยวกับการลงทุนอย่างต่อเนื่องของ Microsoft เพื่อรักษาและปรับปรุงความน่าเชื่อถือของแพลตฟอร์มระบบคลาวด์ใน Azure CTO และชุดบล็อก Advancing Reliabilityของ Technical Fellow Mark Russinovich ซึ่งเน้นที่สี่ประเด็นหลักเหล่านี้:

ความน่าเชื่อถือของเครือข่ายผ่านซอฟต์แวร์อัจฉริยะ
แนวทางปฏิบัติในการปรับใช้อย่างปลอดภัย
ความยืดหยุ่นของเครื่องเสมือน (VM)
การบำรุงรักษาต่ำและไม่มีผลกระทบ
เครือข่าย Microsoft เชื่อมต่อภูมิภาค Azure มากกว่า 60 แห่ง ศูนย์ข้อมูล Azure 220 แห่ง ไซต์ Edge 170 แห่ง และไฟเบอร์ภาคพื้นดินและใต้น้ำกว่า 165,000 ไมล์ทั่วโลก ซึ่งเชื่อมต่อกับอินเทอร์เน็ตที่เหลือ ณ จุดเชื่อมต่อเชิงกลยุทธ์ระดับโลก เรียนรู้เพิ่มเติมเกี่ยวกับความน่าเชื่อถือของเครือข่าย Microsoft ในบล็อกโพสต์สองส่วนนี้

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by TimShererWithAquent** [comment]
Based on web translation, this looks like some kind of marketing or promotional material. This board is for issues around documentation. I'm going to close this as not actionable. 

If I've misinterpreted, please let me know.
