### ISSUE TITLE
Incorrect description of Activated By/Date rules

### ISSUE THREAD

**Issue by aok-foss** [MicrosoftDocs/azure-devops-docs#11438]
The description of Activated By/Date rule states the following:

> When the workflow state changes to a _Proposed_ state category, **Activated By** and **Activated Date** are updated.

That looks like a mistake. The Proposed state category is for New/To Do work items. Activated By is set when an item moves to Active/Committed state, which is in "In Progress" category. The description should be like this:

> When the workflow state changes to an _In Progress_ state category, **Activated By** and **Activated Date** are updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd97771-b2cf-b722-99c6-c33ca064423c
* Version Independent ID: 9ff61b2f-db48-999e-c6be-6eadad9939e9
* Content: [Backlogs/boards workflow states & state categories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/work-items/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/workflow-and-state-categories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
Thanks so much for your feedback, @aok-foss. Better late than never! Once the update goes live, this issue will automatically close.
