### ISSUE TITLE
Update doc for Xunit data driven tests

### ISSUE THREAD

**Issue by upadhyayap** [MicrosoftDocs/azure-devops-docs#11433]
In  the document under data driven tests in View summarized test results heading it is mentioned that **"If the framework produces a hierarchy of results (for example, MSTest v1 and v2) they will be reported in a summarized view"** which is confusing customers. we need to remove this line from the doc to avoid the confusion.
Xunit data-driven tests are reported in a summarized view for clarity, It became the default in Azure devops server but this feature was not there in the azure on prem releases which is confusing the customers who have migrated from on prem to hosted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#view-summarized-test-results)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by upadhyayap** [comment]
@aaronhallberg Can you please help to update the documentation, please?

**Comment by TimShererWithAquent** [comment]
@mijacobs Can you take a look or redirect?
