### ISSUE TITLE
Automatically link work items included in this run - unable to wildcard branch policy

### ISSUE THREAD

**Issue by AAimson** [MicrosoftDocs/azure-devops-docs#11432]
The documentation suggests that when automatically linking work items, you can wildcard the branch option, which will use any branch, although this behaviour isn't available in Azure DevOps Services. Is this expected behaviour?

![image](https://user-images.githubusercontent.com/9111392/135607290-80a02ae1-de26-4a57-a612-7963f57232fd.png)

Default seems to be empty, and unable to save.
![image](https://user-images.githubusercontent.com/9111392/135607165-710cec68-a891-4dbb-bddd-81528990742b.png)

Unable to wildcard the branch.
![image](https://user-images.githubusercontent.com/9111392/135607207-534baf59-7620-4276-b764-9fb458c5dbb0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Duplicate: MicrosoftDocs/azure-devops-docs/issues/11357
