### ISSUE TITLE
Demands operators

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#11442]
There is -equals operator used as an example for demand:

>   - agent.os -equals Darwin  # check for specific string in capability

are there any other operators listed somewhere? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
The only operators supported are `exists` and `equals`. Exists is checking for the existence of a capability, and equals checks for the existence and that the capability's value matches the specified value.

https://learn.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
