### ISSUE TITLE
Unclear information about parameters for callback feature of Invoke HTTP REST API task

### ISSUE THREAD

**Issue by olivergrabinski** [MicrosoftDocs/azure-devops-docs#11445]
Hello,

I am trying to use the call back feature of the Invoke HTTP REST API task, but I cannot figure out what the necessary parameters are. There is a bit of explanation about this feature in the FAQ section of this task, but in my opinion not enough to get the feature to work. My questions are:

* What are: {planUri}, {projectId}, {hubName}, {planId}? I have tried looking up the distributedtask API documentation, but there does not seem to be any information on such a thing like "hubs".
* How to obtain {taskId} and {jobId}?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by olivergrabinski** [comment]
The information I was looking for is in fact given in the YAML snippet, in the `header` argument. This was noticed [by ste-fu](https://stackoverflow.com/questions/69403785/parameters-to-use-for-callback-to-invokerestapi-azure-pipeline-task).

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- please see the previous comment.
