### ISSUE TITLE
Wild cards in path filters are now supported

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-devops-docs#11446]
The article says the following:

> Wild cards are not supported with path filters.

However per [the change log](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters):

> This update fills this gap. Now, you can use wild card characters (**, *, or ?) when specifying path filters.

Please update the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Thanks @abatishchev -
