### ISSUE TITLE
Add Velocity PowerBI Sample

### ISSUE THREAD

**Issue by msftph** [MicrosoftDocs/azure-devops-docs#11441]
Currently the calculation for velocity in azure devops is contained in a widget. A customer I work with is looking for a sample report on how to externalize this data to Power BI. Please provide a sample for velocity. Examples of such reports are located here https://docs.microsoft.com/en-us/azure/devops/report/powerbi/overview?view=azure-devops#sample-reports-using-odata-queries, there is not currently one for velocity. 

Here is the azure devops widget for velocity https://docs.microsoft.com/en-us/azure/devops/report/dashboards/velocity-guidance?view=azure-devops&tabs=in-context

Here are examples of others asking for this feature in different channels:
* https://stackoverflow.com/questions/52446311/how-to-retrieve-velocity-data-thats-used-for-azure-dev-ops-analytics-velocity-d
* https://community.powerbi.com/t5/Desktop/How-to-pull-information-like-Velocity-Process-from-Azure-DevOps/td-p/1406387
* https://developercommunity.visualstudio.com/t/azure-boards-velocity-data-discrepancy-with-power/1270384

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a874f64-4330-f3c5-b75f-24bc474b2c83
* Version Independent ID: 9034e780-4edc-415c-db3a-64243f5775ea
* Content: [Learn about Power BI integration and supported connections methods - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/overview?view=azure-devops#sample-reports-using-odata-queries)
* Content Source: [docs/report/powerbi/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@msftph - Thank you for your inquiry. I've forwarded your request to our product team and will respond when I get more info from them.

**Comment by KathrynEE** [comment]
@msftph - I added this article, https://learn.microsoft.com/en-us/azure/devops/report/extend-analytics/view-odata-query-analytics-report?view=azure-devops, to provide some information on how to look at the Odata query behind a widget or built-in report.  I will look at providing a more thorough article on creating a velocity report in the future, but for now, I'm closing this issue as addressed.
