### ISSUE TITLE
The YAML sample for azure-pipelines.yml is missing $ResourceGroup as script argument

### ISSUE THREAD

**Issue by elninoisback** [MicrosoftDocs/azure-devops-docs#11444]
The YAML snippet mentioned for azure-pipelines.yml (Under the title: Add the following to your azure-pipelines.yml file to run a SQL script.) has the following step:

steps:
- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName)'
    azurePowerShellVersion: LatestVersion

The ScriptArguments is missing the $ResourceGroup argument which is required by the powershell script mentioned earlier in the doc.

It's missing in the other task which removes the firewall rule as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by ktoliver** [comment]
Hi @TimShererWithAquent - The PR review team works only with pull requests, not issues. I'll assign it to @steved0x on the content team. (I believe that the listed author is no longer working with the content.) Thanks.
