### ISSUE TITLE
Unclear how to order the backlog stories with features

### ISSUE THREAD

**Issue by hexagon06** [MicrosoftDocs/azure-devops-docs#11454]
# Situation
I am attempting to reorder my product backlog. We have Epics > Features > [stories, bugs] as structure. 
It is unclear to me how I can reorder my stories based on features. e.g.

I have
Epic / Feature 1 / Story A
Epic / Feature 2 / Story B
Epic / Feature 2 / Story C

## Current behaviour
I have my product backlog where I enable _Parents_ in story view.
Then I put Feature 2 before Feature 1 within the Epic
When I turn _Parents_ off, the order of the stories has not changed and Story B and C are still below Story A
It is unclear if that is desired behaviour or what the desired approach would be to do this.
This same issue goes for Epics and their children.
Note that if I drag story C above story B with Parent view on the order is ACB, and is working as expected and described in the article

# Request
An explanation on why this works this way and how to handle this kind of reorganisation work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899d58b-c8eb-0ab4-9126-54cbf0de4dc6
* Version Independent ID: ab4d7f52-536e-e3e2-77cf-47581f5cc2d6
* Content: [Organize product backlog into hierarchy of items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/organize-backlog?view=azure-devops)
* Content Source: [docs/boards/backlogs/organize-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/organize-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@hexagon06 - I'm closing this issue now. I've just published a new article which provides details on configuring your view options, [Configure your backlog view](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/configure-your-backlog-view?view=azure-devops).
