### ISSUE TITLE
Add description for built-in pipeline task "Static Web App"

### ISSUE THREAD

**Issue by svdHero** [MicrosoftDocs/azure-devops-docs#11455]
The catalog is missing the built-in task `AzureStaticWebApp`. At least I couldn't find it there. Please add it to the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@svdHero Thanks for catching that! I'm working on an update.

**Comment by juliakm** [comment]
#reassign juliakm

investigating
