### ISSUE TITLE
Links 404

### ISSUE THREAD

**Issue by Cisien** [MicrosoftDocs/azure-devops-docs#11456]
The "Get Upstreaming Behavior" and "Set Upstreaming Behavior" links located about half-way down the page lead to a 404 error

Relevant section: https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?view=azure-devops&tabs=nuget#allow-external-versions-using-the-rest-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb8c20-fe29-a60c-dd6c-45c9e8278162
* Version Independent ID: ca24cdd8-dc94-6339-e2ef-95e5a84fa877
* Content: [Configure upstream behavior - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?view=azure-devops&tabs=nuget)
* Content Source: [docs/artifacts/concepts/upstream-behavior.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/upstream-behavior.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@Cisien Thank you for your feedback!
