### ISSUE TITLE
Missing information about available variables

### ISSUE THREAD

**Issue by Mikebeem** [MicrosoftDocs/azure-devops-docs#11467]
I'm missing some information of the available options for using pipeline variables. 

For example, the **Schedule of change request**. For me, it would not make sense if I have to predefine an actual data/time value in here, as I want to automate work. I would expect it should be able to use a data/time variable in here. So for a startdate I would like to enter a current date/time, or the start date of the pipeline. For the scheduled end date somtehing like two days from now. I tried using $(pipeline.startdate) and $(Date:MM/dd/yyyy) in different formats, but none of them seem to be working.

What variables for date/time could we use here? Can you add examples for it, or give a more detailed explaination of the options we can use here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07f29c5-affb-47bb-5f68-fc49e691c741
* Version Independent ID: 661d3781-8784-868d-261f-1e994a154a35
* Content: [Control deployments by using ServiceNow - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/servicenow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/approvals/servicenow.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by mahi072** [comment]
Hi, I would like to work on this issue.

**Comment by WilliamAntonRohm** [comment]
@mahi072 -- Mahima, thank you for your offer of assistance.  You are welcome to research and create a PR.

**Comment by mahi072** [comment]
@WilliamAntonRohm, can you please provide me the details that how should I contribute here.
Is there any folder under doc in which I have to update Or it has to be completely different document under pipeline section.

Is there any slack group for this?

**Comment by mahi072** [comment]
After going through the pipeline variables, I found below examples:

" $[format('{0:ddMMyyyy}', pipeline.startTime)] " using this we will be getting the date/time in without '.' format so to get that we can use Build number format in the options tab with value $(DayOfMonth).$(Month).$(Year:yyyy) and then use variable $(Build.BuildNumber) directly to get the date/time.

@WilliamAntonRohm, please review this and let me know if I have to follow more specific material.

**Comment by mahi072** [comment]
After going through the pipeline variables, I found below examples:

$[format('{0:ddMMyyyy}', pipeline.startTime)] ,  
using this it will provide the date/time in without dot format. So for this we will use Build number format in options tab with value: (DayOfMonth).$(Month).$(Year:yyyy) and then use variable $(Build.BuildNumber) directly to get the date/time.

@WilliamAntonRohm, please review this and let me know if I have to follow any more specific material.

**Comment by WilliamAntonRohm** [comment]
@mahi072 -- Mahima, please see this article:
- [Microsoft Learn documentation contributor guide overview](https://learn.microsoft.com/en-us/contribute/)

I don't know if there is a slack group.
