### ISSUE TITLE
Generalize the VM ( flag /mode:vm)

### ISSUE THREAD

**Issue by diegodct** [MicrosoftDocs/azure-devops-docs#11483]
On step 6 to generalize a VM, we have the following sysprep command:

C:\Windows\System32\sysprep\**sysprep.exe /generalize /oobe /shutdown**

While on the another documentation we have this one:
https://docs.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-prepare-windows-vhd-generalized-image#generalize-the-vhd

c:\windows\system32\sysprep\**sysprep.exe /oobe /generalize /shutdown /mode:vm**

I recently had to use the **/mode:vm** flag to solve a problem when generalizing a VM with hyper-v role. Could we add the /mode:vm flag on this article as well ?
Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756d9c64-a802-61ad-ba6c-6061d2d747cf
* Version Independent ID: 012518b7-0282-f5b0-5206-8a9d1902b8d3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@diegodct I am reaching out to the product team to see if we should add that for all cases, or only to resolve certain issues. Can you share what issue it helped to solve, or what error you were getting before you added it (to help other customers find it if they search on that error?)

**Comment by steved0x** [comment]
I am closing this issue - If you can provide more details on the issue that using the `mode:vm' flag helped solve, I can include a note in the article. Customers will be able to see this issue as well. Thank you.
