### ISSUE TITLE
Step 6 in the document is mentioned as optional, but it's not

### ISSUE THREAD

**Issue by pkuma-msft** [MicrosoftDocs/azure-devops-docs#11488]
Step 6 in the below link is marked as optional,
https://docs.microsoft.com/en-us/azure/devops/organizations/billing/try-additional-features-vs?view=azure-devops

But this step seems to be required to get full access to test plans feature. So we should remove the word 'optional' from Step 6 above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3158764-60d5-4e9d-625e-24a6fbe72f29
* Version Independent ID: 636e44c3-8743-7a97-6ecc-cffb3b8c6aea
* Content: [Try Azure Test Plans for free - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/try-additional-features-vs?view=azure-devops)
* Content Source: [docs/organizations/billing/try-additional-features-vs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/try-additional-features-vs.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @pkuma-msft. I'm on it!
