### ISSUE TITLE
The page lists TFS 2017 and a few other versions.

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#11491]
And Policies were introduced only VERY recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c97706ad-840b-0c52-71e7-91b83739b6e5
* Version Independent ID: 884dbdab-5394-b4df-3221-eb966ecf747b
* Content: [Manage personal access tokens using policies - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-pats-with-policies-for-administrators?view=azure-devops&WT.mc_id=DOP-MVP-5001511#add-azure-ad-users-or-groups-to-the-allowlist)
* Content Source: [docs/organizations/accounts/manage-pats-with-policies-for-administrators.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/manage-pats-with-policies-for-administrators.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the heads up, @jessehouwing.  Updating now!
