### ISSUE TITLE
The documentation page for developing extension is using JavaScript, but you switched to React

### ISSUE THREAD

**Issue by mkabab** [MicrosoftDocs/azure-devops-docs#11490]
Can you provide us a documentation of how to create Azure DevOps Extension using React

also the sample that exist in GitHub [https://github.com/microsoft/azure-devops-extension-sample](url) use tfx cli
but it looks that this cli doesn't support Node 14 and it replaced with azure devops cli without new documentation! [https://github.com/microsoft/azure-devops-extension-sample/issues/65](https://github.com/microsoft/azure-devops-extension-sample/issues/65)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops&source=docs#feedback)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi mkabab, if you're interested, please consider becoming a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! Submit a PR and we'll happily approve it. Thanks so much for the help!
