### ISSUE TITLE
Remove Ubuntu 16 as an option, as it already has been removed from the service

### ISSUE THREAD

**Issue by gvaneck-move** [MicrosoftDocs/azure-devops-docs#11496]
Ubuntu 16.04 has been removed as a host option, as I discovered as my build failed.. There was no advance warning, or I must have missed it.

The doc hasn't been updated and still mentions the option.

https://github.com/actions/virtual-environments/pull/4313

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by williamscs** [comment]
On a more functional level, if no pool or vmImage is specified, it seems like the Pipeline will still default to "Ubuntu16" which breaks the pipeline. I'm not sure where a better place to bring this up would be. I would expect that the pipeline would either yell at me for not specifying a value, or provide 'ubuntu-latest'.
