### ISSUE TITLE
Document does not say when upstream sources is not supported

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/azure-devops-docs#11494]
I tried in vain to select upstream sources. After filing an ICM I learned it is not supported in public projects. Would be nice if this was in the documentation.

I suggest where it says:

"2. Select Upstream sources. If you don't have any upstream sources, you'll see a dialog where you can Add upstream source. If you already have it, you can select Add upstream source in the top menu."

... to add the sentence:

"Note: If your feed is in a public project, upstream sources is not supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for your feed - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops#add-public-upstream-sources-to-an-existing-feed)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@BruceHaley Thank you for your feedback! This feature is currently under development. Stay tuned!
