### ISSUE TITLE
average delivery rate calculation in Kanban (= without fixed iterations): How-To ?

### ISSUE THREAD

**Issue by EnterpriseCoach** [MicrosoftDocs/azure-devops-docs#11505]
Delivery Rate with fixed timeboxes (aka Velocity) is helpful, if you do Scrum. 
In Kanban we also would like to know mean(or avaerage) delivery rate, but without having fixed timeboxes (eg as rolling window average). That doesn´t seem to be supported. Balancing is a key principle in Kanban. Including balancing work arrival rate with work departure rate.
If that isn´t available out-of-the box, can you please 
either provide a HOW-TO  construct such dashboard 
or link to extensions, that solve that issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [View and configure team velocity - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azure-devops)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@EnterpriseCoach - Thank you for your inquiry and sorry for the delayed response. I believe the Cycle TIme widget would provide the data you're looking for. Please see [Lead Time and Cycle Time widgets](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops).

**Comment by merezano** [comment]
@KathrynEE could you elaborate, how Lead Time and Cycle Time widgets can be used to measure throughput / delivery rate? 

@EnterpriseCoach The workaround I have used to get you're looking for is via the velocity chart using count of items. The downside is that teams need to associate items to iterations, which is something Kanban teams might find annoying.
