### ISSUE TITLE
Update to required ssh config settings

### ISSUE THREAD

**Issue by jjeziorny** [MicrosoftDocs/azure-devops-docs#11507]
Latest version of openssh does not work with the sugested config exception
```
Host ssh.dev.azure.com
   PubkeyAcceptedKeyTypes=ssh-rsa
```

Instead the following two exceptions had to be put for it to work

```
Host ssh.dev.azure.com
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedAlgorithms +ssh-rsa

```
reference: https://githubmemory.com/repo/git-for-windows/git/issues/3468

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fde585e-edbd-c738-4d34-b1dfca1ef033
* Version Independent ID: 974698f8-cb53-24d4-f75f-a88c16f8e51c
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by bgianfo** [comment]
@vijayma Can we get this prioritized, I just lost a few hours to this after having to debug this after upgrading my ubuntu machine. It sounds like it will only become more prevalent.

**Comment by steved0x** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-devops-docs/pull/12769
