### ISSUE TITLE
Document should specify where the task is and is not supported

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/azure-devops-docs#11514]
The doc says the following about the "Index sources and publish symbols" task:

"Using Azure Pipelines, you can publish you symbols to Azure Artifacts symbols server, files shares, or portable PDBs."

However, it fails to say that the task is not supported in an Azure release pipeline. Two problems:, one with the documentation and one with the task:

1) The task: Because the task inevitably errors when running in a release pipeline, the task should not be made available to add to a release pipeline in the first place. I see this as a bug.

2) The documentation: I suggest after the sentence "Using Azure Pipelines, you can publish you symbols to Azure Artifacts symbols server, files shares, or portable PDBs.", add the sentence "This task is not supported in release pipelines."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2bfcb-0a0c-ce90-fa49-ad2e7fbaa57a
* Version Independent ID: 1a295877-ff8f-f8c2-0349-76a69a0f5cfc
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@BruceHaley Thanks for your issue. We'll look into changing the article. 

As for the bug, to make sure it gets in front of the right people, please [submit the issue here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by ramiMSFT** [comment]
@BruceHaley Thank you for your feedback! The product team is aware of this issue. I'm updating the article shortly.
