### ISSUE TITLE
Please document which characters are valid in `counter` expressions and how they are treated

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-docs#11512]
This is a follow-up issue for this issue, which seems to be muted because it's closed.

https://github.com/MicrosoftDocs/azure-devops-docs/issues/11323#issuecomment-946823878

The fix for the issue above just said that some unspecified set of special characters cannot be used, but didn't specify explicitly the valid set of characters, except that it mentioned that the `.` character cannot be used.

Can you please document which characters can be used for a prefix in the `counter` function as well as the behavior when invalid characters are used and whether they are replaced with some placeholder to form a prefix (i.e. `1.2.3` becomes `1_2_3`, if `_` is a placeholder) or removed (i.e. `1.2.3` becomes `123`) or left as unexpanded variable and used as is (i.e. `1.2.3+$(BLDN)` is left as a prefix `1.2.3+$(BLDN)` if `$(BLDN)` contains invalid characters).

There is no way to see the final prefix used inside `counter`, which makes troubleshooting of this issue extremely expensive - one needs to run a pipeline and see if the counter has been incremented or restarted for each sequence. It takes hours for all experiments.

It's very important to know which one of those 3 cases actually happens. Imagine if invalid characters, like `.` mentioned in the docs, are just removed. This would create cases with build numbers completely messed up. Imagine I use `1.12.4` as a prefix. If dots are removed, then `1.1.24` will produce the same sequence `1124` and the counter used as a build number between completely different version builds will mixed up.

Similarly, using a placeholder may produce unexpected results if different source sequences are replaced to use the same placeholder character, whatever the actual character is - it may be any Unicode character and this point would still stand.

Speaking of `.`, I tested a few sequences and it appears that `.`, `-`, `+` and a couple other punctuation characters work in that they are not removed and indeed participate in the prefix - each of the tests generated a new counter sequence. This makes the fix in the issue above questionable. However, I cannot possibly test if they are being replaced with some placeholders.

Can you please ask developers for this feature to describe exactly how `counter` treats the prefix sequence, what characters remain intact and which ones may be replaced in some way with placeholders?

`counter` in Azure DevOps is one of the best features that makes it possible to generate accurate build numbers for a number of build scenarios that other DevOps platforms lack. Documenting it well will go a long way. 

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops-2020#counter)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by aelray** [comment]
I think it just never counted altough the input was the same.

**Comment by juliakm** [comment]
I'm going to close this issue so that we can follow-up in the [original one](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11323). Here's where we are now as a summary: 
* @aelray used DevOps Server 2020 and the count value did not increment when  the `.` character was in the prefix. I'm going to check this in different server versions. 
* For DevOps Services, we're not seeing any reason in the code why any UTF-16 character would not work as a string prefix value.
