### ISSUE TITLE
Please update the YAML code block in section "Understand variable syntax"

### ISSUE THREAD

**Issue by THEdanielbaxter** [MicrosoftDocs/azure-devops-docs#11510]
Please update the YAML code block in section "Understand variable syntax" so that the bash example does not use single quotes, but double quotes as recommended in section "Set variables in scripts" later in the article. 

My experience with using single quotes for this operation has led to intermittent issues where single quotes get injected into the variable values, causing conditional statements assessing said variables to return false negatives. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@THEdanielbaxter Thanks for the feedback. This will be fixed shortly.
