### ISSUE TITLE
Could you illustrate more on how to use "variables" part in stage?

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/azure-devops-docs#11527]
Could you please illustrate more on how to use "variables" part in stage? Like add an example of it?
Could you put a link of the convention of following grammar syntax? Like what does curly bracket mean?

`variables: { string: string } | [ variable | variableReference ] `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@kind03 We have more details in the [schema documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/stages?view=azure-pipelines). I've added some links to the start of the article to help with navigating to related content.
