### ISSUE TITLE
Not following logical topic order

### ISSUE THREAD

**Issue by vlakshmi001** [MicrosoftDocs/azure-devops-docs#11520]
Need to follow logical topic order - DONT USE A TERM BEFORE YOU EXPLAIN WHAT IT IS!!!

In the table of work items types, you should reverse the order. e.g. First explain test case, then test suite and then test plan. So when you are explaining about test suite, one already has read and knows about test case and later while explaining test plan, one would have already read and knows about test suite. Currently you are starting with test plan where you are mentioning about test suites which are not known to the reader at that point and while you are explaining about test suites and using the term test cases, reader hasn't been yet told what test case is.

Please follow this concept through out your microsoft documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by KathrynEE** [comment]
@vlakshmi001 - Thank you for this feedback. We are actively updating Test Plans content. We recently added an article, [Test objects and terms](https://docs.microsoft.com/en-us/azure/devops/test/test-objects-overview?view=azure-devops), which I believe addresses some of your feedback. I agree that for a new user, it's useful to build on concepts in a logical order. As we update our content, I'll work to ensure we follow that principle.
