### ISSUE TITLE
dot net 6 information

### ISSUE THREAD

**Issue by figuerres** [MicrosoftDocs/azure-devops-docs#11528]
dot net 6 will be rtm in about a week, lets get the documentation ready!
also this doc seems to assume the code is in github , what about the devops repos?
or is this a sign that azure devops is going to change yet again and lose code repos?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4959fc1-212b-7d6a-df73-b0b2993df561
* Version Independent ID: fcecb4fc-6b16-e432-8f4a-f043e222bb41
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@figuerres I have a change in progress that will update this so that you build your project locally. You can host your repos in GitHub or Azure Repos.
