### ISSUE TITLE
DownloadBuildArtifacts task does not work in OnPrem if IIS has Basic Authentication enabled.

### ISSUE THREAD

**Issue by mmj78** [MicrosoftDocs/azure-devops-docs#11526]
Can we mention in DownloadBuildArtifacts task that it will **not work** in OnPrem Environment if Basic Authentication is enabled in IIS.

We have two reported cases and the troubleshooting came down to this. The logs would fail with 401 and this is the only task that would fail.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9927683a-6fad-ab3d-4a28-1a9c101bda83
* Version Independent ID: 7bccbe24-e106-1112-75a9-b093bb5ed012
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
Thank you for your feedback! I'll be updating this shortly
