### ISSUE TITLE
Service Hook is no longer an accepted category and should be updated in the 

### ISSUE THREAD

**Issue by greatestusername-splunk** [MicrosoftDocs/azure-devops-docs#11534]
Service Hook is no longer an accepted category.
```
  "categories": [
      "Developer samples"
  ],
```

When trying to upload an extension with this category to the marketplace an error will be presented to the user

Correct available categories are given here and should be updated in the tutorial overview for adding a new service hook.
https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#required-attributes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758bed7c-374d-996e-ebff-c68528a823ca
* Version Independent ID: 81777b37-38ab-a7df-6eaa-7aa6bcd1058c
* Content: [Create a consumer service for service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-service-hook?view=azure-devops)
* Content Source: [docs/extend/develop/add-service-hook.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-service-hook.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by greatestusername** [comment]
Hi @chcomley 
Noticed the changes but it leaves the documentation incomplete and unusable as far as I can tell? Is there any chance of getting an updated `vss-extension.json` that actually works for a new service hook? 
Google only has old docs that don't work anymore and it appears the implementation has changed significantly since: https://github.com/microsoft/vsts-extension-samples/blob/master/service-hooks-consumer/vss-extension.json

Which gives this message when followed:
![image](https://user-images.githubusercontent.com/26044432/139755105-15120306-894f-4487-9f06-a4c444beb7e7.png)
This seems to be a long running issue: 
https://github.com/MicrosoftDocs/azure-devops-docs/issues/3743


Appreciate any help/updates to these docs!

**Comment by greatestusername-splunk** [comment]
Much appreciated!!!
I'm very interested in getting this to a place where adding a Service Hook
is more straightforward. Also happy to work with you on any of the
specifics/details.

Thanks again!

**Comment by greatestusername-splunk** [comment]
Actually curious if this Service Hook method of interaction with Azure DevOps is being phased out in favor of more specific extensions?

If not, and you can share a complete example available for one of the current service hooks, I'll happily make the needed documentation changes. 🎉

**Comment by chcomley** [comment]
@greatestusername, Happy new year! Wanted to let you know that I've circled back on this and reached out for some help. Stay tuned and thanks for your patience.

**Comment by greatestusername-splunk** [comment]
Awesome, thanks for the update! I really appreciate it!

**Comment by chcomley** [comment]
Hi @greatestusername, as far as my PM knows, there aren't any plans to replace Service Hooks as a method of interaction with Azure DevOps.

I haven't received any further guidance, so I'll give you some links to more information with hopes that they help.

- Article: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops)
- Website: [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions)
- [Azure DevOps Extension Sample](https://github.com/microsoft/azure-devops-extension-sample)

Also, adding @pkuma-msft for input.

Thanks for your patience on this, I know it must be frustrating.

**Comment by olljanat** [comment]
@chcomley as far I understand the original issue here was fixed but #3743 still exits so maybe this should be closed and that one reopened?

**Comment by greatestusername-splunk** [comment]
Honestly the whole documentation for making a custom service hook from
start to finish could use updating and revalidating. Having an updated
tutorial and examples would be much appreciated!

Please add me to that ticket/issue for tracking if you close this ticket.

Thank you!

**Comment by chcomley** [comment]
Closing this issue and linking to https://github.com/MicrosoftDocs/azure-devops-docs/issues/3743
