### ISSUE TITLE
pipeline.startTime leads to misunderstanding due to the lack of documentation.

### ISSUE THREAD

**Issue by Pamela-1** [MicrosoftDocs/azure-devops-docs#11535]
Hi Team,

It's not clear in the document if the `pipeline.startTime` returns the time of build/run or the time of agent.

After testing with multi jobs, the time is the start time of agent.

Please add the detailed messages. Thank you!

Doc mentions `pipeline.startTime`: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter

**Comment by quasarea** [comment]
This should be addresses and renamed to job rather than pipeline
