### ISSUE TITLE
Clarification: Does "Deploy all in sequence" option look at commit sequence or build completion sequence?

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/azure-devops-docs#11533]
> Deploy all in sequence: Use this option if you want to deploy all the releases ***sequentially*** into the same shared physical resources. 

Could you please clarify what does ***sequentially*** mean in this sentence? Is it a sequentiality of commits, or the sequence in which builds were completed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
This is a sequence of builds. I'll update the article.
