### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by jeromesubs** [MicrosoftDocs/azure-devops-docs#11537]
Hello,

I am running Power BI Version: 2.98.882.0 64-bit (October 2021).
I followed the steps and tried the sample query.

I get a result when running from VsCode / Chrome, but I get an error when running it from Power BI saying "TotalCount" doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc728cf-76c0-7740-4fae-a4cba4170dfe
* Version Independent ID: 9e6040e3-bdec-0ea1-bf03-eaf91f7847bc
* Content: [Pipeline outcome summary sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-pipelines-outcome-summary?view=azure-devops&tabs=odata)
* Content Source: [docs/report/powerbi/sample-pipelines-outcome-summary.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-pipelines-outcome-summary.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaghai**

**Comment by KathrynEE** [comment]
.@jeromesubs - Apologies for the delayed response. I've recently updated the article and checked the queries. Please try again and feel free to reopen this issue or open a new issue if you are still running into issues.
