### ISSUE TITLE
Add .NET Core Sample

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/azure-devops-docs#11530]
It would be much helpful and useful if you add .NET Core sample within this documentation as it is mainstream technology nowadays for enterprise application development

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d73b50-b26b-3e9e-e8c2-37669424793c
* Version Independent ID: ebde85d2-1f0a-afa8-0597-d084c2b64870
* Content: [Deploy to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/deploy-linux-vm?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/ecosystems/deploy-linux-vm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/deploy-linux-vm.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks! I've added this in a different space.

**Comment by juliakm** [comment]
@RiadKatby To follow-up, I'd recommend following the [Windows VM quickstart](https://learn.microsoft.com/azure/virtual-machines/windows/quick-create-cli) and then following the same steps but selecting Windows for the virtual machine resource.
