### ISSUE TITLE
Need clearer permissions requirements

### ISSUE THREAD

**Issue by Bliyaal** [MicrosoftDocs/azure-devops-docs#11540]
In the Prerequisites sections, it says:

>Delete work items and Restore work items: Have the Delete and restore work items project-level permission set to Allow. Also, to restore work items, you must have Basic access or higher. Users with Stakeholder access can view the contents of the Recycle Bin, but can't restore or permanently delete items in the bin.

The wording implies that Basic access is needed only to destroy or restore work items. We lost some time to figure out that Basic access is also needed to delete a work item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9f02cb-f094-d6bc-ca7b-973db9de0082
* Version Independent ID: 1af6a7f5-9e99-ec99-081d-c0bf9e7ac5f5
* Content: [Remove, delete, and restore work items in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/remove-delete-work-items?view=azure-devops)
* Content Source: [docs/boards/backlogs/remove-delete-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/remove-delete-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Bliyaal - Thank you for the feedback. I'll update the article to clarify the required permissions within the next 7 days.
