### ISSUE TITLE
Should Windows 2016 be removed from the lists?

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-devops-docs#11541]
Re: https://github.com/actions/virtual-environments/issues/4312

Should 
> Customers are encouraged to migrate to **vs2017-win2016**
be
> Customers are encouraged to migrate to **windows-latest** ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
*latest has been added to the list of agent types in the classic pipeline editor UI and vs2017-win2016 has been removed from the article. Thank you.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1580889/00513523-8fe1-4893-8a2f-42c09dfd70f3)
