### ISSUE TITLE
Reutilizing Docker layer caching in ephemeral microsoft hosted agents is possible

### ISSUE THREAD

**Issue by TonnyWildeman** [MicrosoftDocs/azure-devops-docs#11552]
In the answer for 'Is reutilizing layer caching during builds possible on Azure Pipelines?' question it is stated that using Docker layer caching with the ephemeral Microsoft Hosted Agents is not possible. I've found a blog post where the writer suggests a way to use the caching mechanism in ephemeral build agents. I've implemented it in my azure-pipelines.yml with a semi standard .net 5 web application in Azure DevOps pipelines.

https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/

In short:
In a direct from template started .net 5 web app with docker build, you have a multi-stage build. In essence there are two images built. The builder image with the sdk and the application or final image with only the runtime and built application copied from the builder image. If you push both images to a registry and pull them as a first step in your CI pipeline, you can tell docker to use these images as your --cache-from layer cache source.

If the blog post is not clear, I can create a working Azure DevOps pipeline git repo that shows it all.

Please integrate the essence of the blog post in the answer. My build time went from 8 mins to 1.5 mins.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033adab-2220-0792-ebe1-4a316a4931f5
* Version Independent ID: 928fcffc-9dba-69bb-09cf-533d0055bf40
* Content: [Build an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/build-image.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by juliakm** [comment]
Thanks @TonnyWildeman for the suggestion!
