### ISSUE TITLE
Using parametereless VssClientCredentialStorage constructor in code example is not valid

### ISSUE THREAD

**Issue by RobSiklos** [MicrosoftDocs/azure-devops-docs#11574]
Trying to use the code sample from the "Pattern for Use" section, and it's got the following line of code:

`creds.Storage = new VssClientCredentialStorage();`

Unfortunately, this line of code does not compile with the latest libraries, because there is no parameterless constructor for this type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @RobSiklos, it's been quite a while since you submitted this issue, I'm so sorry for the inconvenience. Were you able to move forward? Does this updated example help? https://github.com/microsoft/azure-devops-dotnet-samples#sample-console-program

**Comment by RobSiklos** [comment]
Thanks. I was able to move forward, but the original documentation still seems to be invalid.

**Comment by chcomley** [comment]
Great, glad you were able to move forward! I'll update the article. Once it's live, this issue will automatically close. Thanks again.
