### ISSUE TITLE
Can we clarify if the notifyUsers list is email or UPN

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/azure-devops-docs#11585]
Can we clarify if the notifyUsers list is email or UPN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by juliakm** [comment]
@TravisEz13  I've confirmed that the list is email. I'll update the article.
