### ISSUE TITLE
Not all Az CLI commands work for Azure DevOps Server 2020

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#11584]
[Enter feedback here]
Az devops show user & az devops security group list commands do not seem to work for Azure DevOps Server 2020. Can the documentation be rectified to include only supported commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops&source=docs)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@kripa-2019 Thanks for your suggestion. You might also want to reach out to the dev community with more specifics. Maybe there's some other issue going on. To make sure it gets in front of the right people, please [investigate here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by hiredgunhouse** [comment]
@KathrynEE how is that investigation going? any updates? it's been over a month now.
BTW. It's "a bit" surprising to find that not all commands work especially if you consider this statement 
"The Azure DevOps Command Line Interface (CLI) is available for Azure DevOps Server 2020 and Azure DevOps Services." 
which you can see here https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops 
At the same time the CLI tool when run with --debug argument says
cli.azext_devops.dev.common.services: The Azure DevOps Extension for the Azure CLI does not support Azure DevOps Server.
I would suggest to resolve this finally and put a clear message that the CLI is not usable with DevOps Server just to save time for us and show some respect.

**Comment by KathrynEE** [comment]
@hiredgunhouse  - Thanks for checking in on this. I agree that a clear message is needed as to what is and isn't supported. I did some preliminary work, but am going to redouble efforts and get some definitive statements from the product team.  I hope to have that clear statement within the next week or so.

**Comment by KathrynEE** [comment]
[kripa-2019](https://github.com/kripa-2019), @hiredgunhouse - I received a definitive reply and learned that Azure CLI **does not** support the on-premises Azure DevOps Server 2020 and no plans exist for it to support the on-premises servers. Apologies for the confusion and delay for addressing this problem. I will be updating the content this week to clarify the limitation.
