### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by johndowns** [MicrosoftDocs/azure-devops-docs#11594]
[Version 3 of this task was released in May 2021](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3), but this page only refers to version 2. There are important differences between v2 and v3 that should be covered here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4bb5b-30b2-bb87-5a4d-d1fd4f8b9860
* Version Independent ID: aba4f40c-5b1d-404e-7594-aa8887ad5ce5
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
Thanks @johndowns - It looks like this update is already on our radar: MicrosoftDocs/azure-devops-docs/issues/8562
