### ISSUE TITLE
Upstream sources not supported in public feeds

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/azure-devops-docs#11593]
Why are they not supported in public feeds? Is there an ETA to when they can be supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72b4d1-30d9-4e08-c9bf-cb8457a3d05f
* Version Independent ID: 7d9e328b-8bf7-1706-b0e1-061eb221023c
* Content: [Upstream sources overview - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
Hi @miniksa - You should do a feature request. Search [here](https://developercommunity.visualstudio.com/search?space=21) to see if there's been any discussion about this, and submit a feature request, if you don't find any.

**Comment by miniksa** [comment]
Looks like they just aggressively close anything without upvotes so I'm not going to bother. Thanks though.
