### ISSUE TITLE
Reference to Jenkins TFS plugin is invalid

### ISSUE THREAD

**Issue by bellaar** [MicrosoftDocs/azure-devops-docs#11599]
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-pipelines-cicd?view=azure-devops&tabs=yaml

The documentation says - 
_Install the Team Foundation Server plugin on your Jenkins server._

However, this plugin is suspended - 
_Plugin distribution has been suspended, see INFRA-2751 for details._

Please correct documentation with correct steps that work.

Thanks,
Archana

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff6d510-8b84-5f11-87f5-a1a3dccef111
* Version Independent ID: 0d10bee5-1979-bb09-f00f-03d8d52ac0d2
* Content: [Deploy Jenkins CI builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-pipelines-cicd?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/release/integrate-jenkins-pipelines-cicd.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/integrate-jenkins-pipelines-cicd.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @mlearned
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
It looks like that plugin is no longer supported. Here's an alternative article on integrating with Jenkins: https://learn.microsoft.com/en-us/azure/developer/jenkins/deploy-to-linux-vm-using-azure-devops-services

**Comment by juliakm** [comment]
This article has been retired.
