### ISSUE TITLE
Handling of the Azure DevOps organization resource left visible in the Azure Portal after changing billing subscription

### ISSUE THREAD

**Issue by RuneORakeie** [MicrosoftDocs/azure-devops-docs#11608]
Hi all,

Not sure if this only applies to "legacy" AzureDevOps (ADO) organization creations or still applies, but the documentation should be amended with the information that the resource group (named `VS-<your ADO org name>-Group`) and ADO org. resource (named `<your ADO org name>`) visible in the Azure Portal can be deleted without any impact **AFTER** the change of the billing subscription. As per my observation a similar resource is not created in the new subscription either.
In addition it could be informed that deleting the ADO org. resource in the Azure Portal **BEFORE** changing to another billing subscription will cause the ADO org. to have its [billing removed](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops#remove-your-subscription) and it will return to the [Free tier](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#can-i-use-azure-devops-for-free-) with those limitations the Free tier has.

BR,
Rune Ovlien Rakeie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035f6441-6e6f-8ba3-a866-3f417e9ae223
* Version Independent ID: 2f7efb64-7db0-e45d-aaab-1d878a13da8b
* Content: [Change Azure subscription used for billing - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/change-azure-subscription.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much for your feedback, @RuneORakeie. This is on my May backlog and will automatically close this issue once the update goes live.
