### ISSUE TITLE
Document if it is possible to create a common view backlog for multiple teams in the same project ? 

### ISSUE THREAD

**Issue by eocern** [MicrosoftDocs/azure-devops-docs#11601]
Would be very informative to mention on that page if it is possible or not to create Backlog common view for several teams part of the same project. In our case we want all the teams to have the same "Column Options" enabled and set for all the backlogs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ab6fbc-4df4-bc2d-da58-19dee9395256
* Version Independent ID: e613f4a0-37a5-c2fa-fdf5-345c945de6db
* Content: [Use backlogs to plan your projects in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-overview?view=azure-devops#multi-team)
* Content Source: [docs/boards/backlogs/backlogs-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/backlogs-overview.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@eocern - Thank you for this question. It isn't possible to create a common Backlog view for several teams. Each team and in fact each user can customize the  Column Options for their backlog - providing flexibility based on their needs. I will clarify that in the article in the near future.
