### ISSUE TITLE
Migration Guide is out of date

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/azure-devops-docs#11621]
Can you please check on the plans to update the guide? It's excellent, however, at 2.5 years since the last update, also quite dated.

![image](https://user-images.githubusercontent.com/1765732/142259029-03fdf4ec-6198-44c1-8edb-a6db83930295.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops#supported-azure-devops-server-versions-for-import)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-overview.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
This is the link to the PDF referred to in the comment:

https://download.microsoft.com/download/7/C/9/7C903CEC-839A-415E-BBD4-5F84B876A291/Data%20Migration%20Tool%20for%20Azure%20DevOps%20Migration%20Guide.pdf

**Comment by KathrynEE** [comment]
@VitalyMCT - Thank you for your inquiry. I'm checking with the product team and will get back to you when I learn more.

**Comment by ramrajesh** [comment]
Thanks for reaching out. It wasn't in the top of our priority list but we will get this updated soon.

**Comment by KathrynEE** [comment]
@VitalyMCT - Closing this for now as product team has responded that an update is coming soon.

**Comment by VitalyMCT** [comment]
@ramrajesh  Thanks - can we please qualify "soon"? Are we talking calendar Y/E, calendar Q1 2022, etc.?

Just trying to see if we can afford to wait for release or instead need to source more current info from elsewhere in the documentation portfolio.
