### ISSUE TITLE
Change in environment creation - no documented workaround

### ISSUE THREAD

**Issue by rickardp** [MicrosoftDocs/azure-devops-docs#11623]
In the referenced documentation

> Previously, we handled this case by adding all the project contributors to the administrator role of the environment. Any member of the project could then change these permissions and prevent others from accessing the environment

We want the old behavior. Now we have to manually create the environment, and worse, only the creator gets admin access. We want all contributors to have access to it. The documentation does not say how to keep the old behaviour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
Hi @rickardp - Thanks for your suggestion. To make sure it gets to the right people, please [create an issue in the dev community](https://developercommunity.visualstudio.com/search?space=21). Also, do a search there - there might be relevant discussions.

**Comment by rickardp** [comment]
Not sure what is meant by the link above. I clicked the link to report an issue with the instructions I quoted, and this is where I got.
Why was the issue closed?

**Comment by rickardp** [comment]
To be clear, I expect the note to contain instructions for migrate if using the old workflow

**Comment by juliakm** [comment]
@rickardp I don't think that there is a migration but I will double-check with the product team. You can learn more about this security change [here](https://docs.microsoft.com/azure/devops/release-notes/2021/pipelines/sprint-188-update#changes-in-the-automatic-creation-of-environments).

**Comment by juliakm** [comment]
@rickardp The product team is working on an inheritance model. There is not a way to add all the project contributors to the administrator role of an environment now.
