### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by Gyarm** [MicrosoftDocs/azure-devops-docs#11624]
Hi!

First of all: Great introduction on CMMI!
Unfortunately assumably very interesting images were not shown in the last section of the page.

Thanks for looking into this.

Regards
Gyarm
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d114ba-d4fb-e212-f03c-90ba03843344
* Version Independent ID: d0f7dc78-1c55-b0c2-2963-bed21f77ed8d
* Content: [Capability Maturity Model Integration (CMMI), background notes - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi/guidance-background-to-cmmi?viewFallbackFrom=vsts&view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/cmmi/guidance-background-to-cmmi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/cmmi/guidance-background-to-cmmi.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
Thanks @Gyarm - an html tag was messing up half the page!
