### ISSUE TITLE
Keyboard shortcuts for mac OS

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#11626]
Can you add the keyboard shortcuts for mac OS? Most of the keyboard shortcuts work, but there are some differences in the keyboard layout and therefore they do not work. In some sections they are already available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Keyboard shortcuts for web portal and Team Explorer - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Closing this issue as completed, [macOS shortcuts](https://learn.microsoft.com/en-us/azure/devops/boards/get-started/keyboard-shortcuts?WT.mc_id=DOP-MVP-5001511&view=azure-devops#macos-shortcuts) section added to the article.
