### ISSUE TITLE
Feedback - Incorrect information for Azure DevOps Server 2020

### ISSUE THREAD

**Issue by tinylabspace** [MicrosoftDocs/azure-devops-docs#11620]
This feature does not seem to work as described for Azure DevOps Server 2020. This does work for Azure DevOps Services.

After selecting Azure DevOps Server 2020 from the version list this statement says that I should be able to @ mention a group, I can't. The identity picker does not find the group no matter how I format it

@[teamproject}\asdfasdf
etc.

_The @mention control allows you to quickly add a user **_or group_** to a work item or pull request discussion. Using the people picker of the @mention control, you can select a project member or group from the search list..._

The next paragraph refers to Azure AD but AzDO Server uses on premises AD as its identity source, not Azure AD.

_For organizations that manage their users and groups using Active Directory, people pickers provide support for searching all users **and groups** added to the **Azure AD**..._

The Warning in the Identity search selection section is also incorrect for AzDO Server. Restricting new user invitations is a AzDO Services feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops-2020#feedback)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hello from 5 months ago, @tinylabspace! Wanted to let you know that this issue is on my backlog for May and will close automatically once it goes live. Thanks so much for your feedback!
