### ISSUE TITLE
Should have a list of keywords - eg: how to specify  Not Equal, Greater than etc

### ISSUE THREAD

**Issue by simonhorridge** [MicrosoftDocs/azure-devops-docs#11638]
Should have a list of keywords - eg: how to specify  Not Equal, Greater than etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
You can find more details on our [expressions page](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops). I'll add a link to the article.
