### ISSUE TITLE
Page does not explain about Full Access PATs

### ISSUE THREAD

**Issue by balgillo** [MicrosoftDocs/azure-devops-docs#11635]
This page shows the radio buttons for "Full access" or "Custom defined" PAT permissions, but doesn't explain these options.  For some people "Full access" is disabled as an option - why?  What controls this?

Also it would be good if this page noted that there's a known issue where "Custom defined" permissions don't work for some API objects, so it's necessary to use "Full access" instead.  Issue link: https://developercommunity.visualstudio.com/t/401-on-Azure-Management-API-callback-unl/1503803#T-N1532577

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @balgillo, thank you for your valuable feedback. I've updated the article, which will automatically close this issue, once published. About the full-scoped PATs option being unavailable to you, you may be restricted from creating full-scoped PATs. If so, your Azure DevOps Administrator in Azure AD has enabled a policy which limits you to a specific custom defined set of scopes. For more information, see [Manage PATs with policies/Restrict creation of full-scoped PATs](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-pats-with-policies-for-administrators?view=azure-devops#restrict-creation-of-full-scoped-pats). Please feel free to @mention me if you have any further questions, thanks!

**Comment by balgillo** [comment]
Thanks for updating this @chcomley!  One follow-up comment, I've since learned that there are some PAT scopes that do not appear on the ADO GUI.  The required scope for accessing the Component Governance API, `vso.governance`, is an example of this.  I learned this information from https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1823755.

Should I raise another issue that this scope is not selectable when creating or editing a Custom defined PAT?  It's a security issue because it forces people to use Full access PATs.

**Comment by chcomley** [comment]
Hi @balgillo, I'll add a note to the article today! Thanks so much for the info.

**Comment by chcomley** [comment]
@balgillo I've published the additional info. If you feel it needs some tweaking, I'd love it if you'd submit an update! Here's how to [contribute to our docs](https://docs.microsoft.com/en-us/contribute/). If you don't have the time, I completely understand, but it's easy and kind of fun if you're into this stuff like I am. :) In that case, just let me know. Thanks!

**Comment by balgillo** [comment]
Thanks, what you've written makes the problem clear.  It doesn't give a way round it other than full access PATs.  I have found some workarounds but they are definitely not user-friendly, so not suitable for sharing in official documentation!  Written up here if you're interested https://dev.azure.com/msazuredev/AzureForOperators/_wiki/wikis/AzureForOperators.wiki/679/Personal-Access-Tokens-(PAT)?anchor=hidden-pat-scopes
