### ISSUE TITLE
Embedded video not working

### ISSUE THREAD

**Issue by andreas-nesheim** [MicrosoftDocs/azure-devops-docs#11632]
The embedded Channel 9 video on this page under the section "Videos" does not seem to be working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-overview.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andreas-nesheim - The video appears to have been removed.  You may find this video a better resource: [2020 Intro to Azure DevOps Migration Tools](https://www.youtube.com/watch?v=RCJsST0xBCE). I will be removing the link to the non-existing video from the article.
