### ISSUE TITLE
Example for Branch/Branches point to an example of TestPoints instead

### ISSUE THREAD

**Issue by AlphaAqua** [MicrosoftDocs/azure-devops-docs#11637]
Following the example next to the Branch/Branches section of
https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops#branch-pipelines-and-test-entitytypes-and-entitysets

We get to an example of TestPoints instead.

Wondering if this is because call to
https://analytics.dev.azure.com/{organization}/{project}/_odata/v4.0-preview/Branches
returns nothing ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0406dd-f852-001f-eba5-a665ed4ef7a0
* Version Independent ID: 51657f61-8b0c-3132-59d4-7d876b08af6d
* Content: [Data model for Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops)
* Content Source: [docs/report/extend-analytics/data-model-analytics-service.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/data-model-analytics-service.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AlphaAqua - Thank you for your inquiry and apologies for the delay in response. I've been actively updating the Analytics articles to provide more information and clarity.  I just exercised the query you specified: 

`https://analytics.dev.azure.com/{organization}/{project}/_odata/v4.0-preview/Branches`

And the system returned all data for branches defined in the project. The properties for **Branches** is now documented here: [Metadata reference for Azure Pipelines Analytics](https://review.learn.microsoft.com/en-us/azure/devops/report/analytics/entity-reference-pipelines?view=azure-devops&branch=pr-en-us-5128#branch-properties).

Please let me know if you have further questions on the Analytics service.

**Comment by KathrynEE** [comment]
@AlphaAqua - Closing this as addressed.
