### ISSUE TITLE
Add to "pool" that quotation marks are necessary

### ISSUE THREAD

**Issue by Jeej** [MicrosoftDocs/azure-devops-docs#11649]
Hi!

Is it possible to add to the section about [pool](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pool) that quotation marks are needed for the name of a pool, especially when your pool name contains spaces. See for instance [this](https://developercommunity.visualstudio.com/t/Pipelines-a-pool-specified-with-a-space/1591815?space=21&entry=myfeedback&viewtype=all) topic on the Developer Community.

A pipeline like:
```
pool:
  name: Build Agents
```
will run on the default Azure Pipelines. Somehow the pipeline thinks that the name of the pool is a demand and then it runs on the Azure Pipelines. Adding quotes is a workaround:
```
pool:
  name: 'Build Agents'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review this update in [private PR 4066](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4066).
