### ISSUE TITLE
Bug : French automatic translation translated "Stage" as "Étape"

### ISSUE THREAD

**Issue by vernou** [MicrosoftDocs/azure-devops-docs#11647]
In Azure DevOps, the term "Stage" is translated to French as "Index".
But the Azure DevOps documentation the term "Stage" is translated to French as "Étape".
A other Azure Pipeline concept, "Step", is also translated as "Étape". This is confusing.

Example :
[Azure Pipelines Nouveau guide de l’utilisateur-concepts clés - Azure Pipelines | Microsoft Docs](https://docs.microsoft.com/fr-fr/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops#stage)

In English :
> # Stage
>  A stage is a logical boundary in the pipeline....
> 
> # Step
> A step is the smallest building block of a pipeline...

In French :
> # Étape
>  Une étape est une limite logique dans le pipeline....
> 
> # Étape
> Une étape est le plus petit bloc de construction d’un pipeline...

Can you improve the translation by forcing the translation of related terms to Azure DevOps' concepts?
For example, by forcing the bot translator to translate "Stage" by "Index" in French.

The best will be to have a dictionary coherent between Azure DevOps and this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@vernou Thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
