### ISSUE TITLE
Authenticate access with personal access tokens documentation page is missing important part

### ISSUE THREAD

**Issue by NicoNBW** [MicrosoftDocs/azure-devops-docs#11645]
Feedback from my customer：
The powershell code to base 64 encode the PAT is missing the prepending of the semicolon:
[This line](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat):
$B64Pat = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("$MyPat"))
Should be:
$B64Pat = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$MyPat"))

I say this because the bash code properly prepends the semicolon and when I’ve tried the powershell code without the prepending it doesn’t seem to work. Thus, I think the powershell code is missing the prepending of the semi-colon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@NicoNBW - It looks like this one is already being fixed here: /MicrosoftDocs/azure-devops-docs/issues/11478

Thanks!
