### ISSUE TITLE
Typo of "Differs" keyed in as "Differes"

### ISSUE THREAD

**Issue by atobrandon** [MicrosoftDocs/azure-devops-docs#11653]
There is a typo in the Build.sourcesDirectory section.  "Differes" should be "differs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by noviicee** [comment]
I think the typo can be found at [docs/pipelines/build/includes/variables-hosted.md](docs/pipelines/build/includes/variables-hosted.md) and [docs/pipelines/build/includes/variables-server-2020.md](docs/pipelines/build/includes/variables-server-2020.md)

**Comment by WilliamAntonRohm** [comment]
@atobrandon -- this issue has been fixed & is now live.

@noviicee -- Anamika, thank you for your contribution.
