### ISSUE TITLE
.NET/NuGet example would only work for one project in the root of Build.SourcesDirectory

### ISSUE THREAD

**Issue by StephenBethke** [MicrosoftDocs/azure-devops-docs#11652]
Hi, in the .NET/NuGet example, the "key:" input parameter has the value "$(Build.SourcesDirectory)/packages.lock.json" as its last part.

This only works if you have one project directly in the Build.SourcesDirectory folder - so if you have multiple projects each in their own folder, this will fail with "file not found"

I suggest it be altered to: "$(Build.SourcesDirectory)/**/packages.lock.json" which should cover most scenarios.

HTH
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@StephenBethke Thank you for your feedback! it will be updated shortly.
