### ISSUE TITLE
Maximum extension upload file size is 25MB

### ISSUE THREAD

**Issue by taylor7302** [MicrosoftDocs/azure-devops-docs#11655]
Attempted to upload TFS Extension to our disconnected on-prem TFS instance, using this guide however the extension size is 28MB and I am receiving an error stating that the maximum size for upload is 25MB. Possibly needs a link to the solution for how to change this considering that is a very small file size limit for extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for on-premises servers - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=tfs-2018)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/get-tfs-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @taylor7302, It's been a while since you've submitted this documentation issue. Please accept my apology for the delay. Are you still experiencing problems with uploading the extension? I found a potential workaround here: https://techcommunity.microsoft.com/t5/azure-devops-blog/upload-error-the-extension-package-size-26272573-bytes-exceeds/ba-p/3048916. Please let me know whether this is helpful. Thank you.

**Comment by taylor7302** [comment]
@chcomley I did receive a similar fix from the Microsoft team directly that I'll add below. The following did work for us to upload the plug-in we needed. It sure would be nice to have this be a configuration available in UI.

```
EXEC dbo.prc_SetRegistryValue @partitionId = 1, @key = 
'#\Configuration\Service\Gallery\LargeExtensionUpload\MaxPackageSizeMB\', @value = 128, @identityName = null 
```

**Comment by chcomley** [comment]
Thanks @taylor7302, I'll make the update. If you're interested, you can request the UI feature [here](https://developercommunity.visualstudio.com/search?space=21). Thanks! Once the update is live, this issue will automatically close. Thanks again!
