### ISSUE TITLE
Make it clear that the developer must first install Gulp

### ISSUE THREAD

**Issue by lukepuplett** [MicrosoftDocs/azure-devops-docs#11651]
It doesn't make clear that this task doesn't Just Work™ and needs Gulp installing. The Example section is particularly unclear, lacking any descriptive English and I think the Build tab link is broken.

This all culminated in me raising an issue and wasting time with the VS / Azure Pipelines team.

https://developercommunity.visualstudio.com/t/gulp-task-fails-on-windows-2022-vm-image/1592547  

I'll be raising another issue to request Gulp be installed globally on the build VM image.

Tasks that assume the developer has first installed tooling should ideally preflight check the environment and produce an actionable error message.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5505c36a-de9a-fcc6-4a85-5cfb58debf68
* Version Independent ID: 270f33bc-d4ba-a9d8-7e99-9aafeb7ab049
* Content: [Gulp build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gulp?view=azure-devops#run-gulpjs)
* Content Source: [docs/pipelines/tasks/build/gulp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/gulp.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@lukepuplett -- Luke, thank you for your well-thought-out feedback, and for raising that issue.

@vijayma -- Vijay, please look into this issue.

**Comment by juliakm** [comment]
#reassign juliakm

Adding a warning message and link to preinstalled software for virtual machine images.
