### ISSUE TITLE
Language settings not clear

### ISSUE THREAD

**Issue by nephinj** [MicrosoftDocs/azure-devops-docs#11659]
Should be clearer what setting the language preference does.  I assumed it would flip the UI language but it seems to have no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [Set your preferences - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @nephinj. I'll make this clear in the article. You'll know when it's live, as this issue will automatically be closed at that point. Thanks again.
