### ISSUE TITLE
How do I grant a pipeline permissions to deploy to AKS from CLI?

### ISSUE THREAD

**Issue by cvdabbeele** [MicrosoftDocs/azure-devops-docs#11660]
This web page describes the problem that I am facing (see below), but it proposed to solve this via the WebUI.  In today's automated world, I need a way how to do this from bash ("e.g. az devops...." command)

Problem:
Why do I see the message that I need to authorize a resource before the run can continue?

Expected solution:
some CLI commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f0ae7d0-e5be-03c9-5296-95a10984a795
* Version Independent ID: 12d1cbdc-49ab-f4dd-2b21-1a1953bb1357
* Content: [Set pipeline permissions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@cvdabbeele Here's all the available pipelines Azure CLI commands: https://docs.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest. My understanding is that setting complex permissions with Azure CLI is not currently supported. For feature requests, please post in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by cvdabbeele** [comment]
@juliakm thank you for your answer
This is really not clear in the documentation.  The docs always point to a GUI 
Meanwhile a colleague helped me out.  I'm posting the answer here.
Hopefully this can help anyone else with the same issue
To allow a pipeline to deploy to AKS, I had to use the following command:
`az devops invoke --area pipelinepermissions --resource pipelinePermissions --route-parameters project=${APP_NAME} resourceType=environment resourceId=${ENVIRONMENT_ID} --in-file params.json --http-method PATCH --api-version "6.0-preview"`

with params.json:
```
{
      "pipelines": [
          {
              "id": "${PIPELINEID}",
              "authorized": "true"
          }
      ]
 }
 ```
and to get the ID of the environment:
`az devops invoke --area distributedTask --resource environments --route-parameters project=${APP_NAME} --org ${DEVOPS_ORGANIZATION} --api-version "6.0-preview" -o json | jq -r --arg PROJECT_ID ${PROJECT_ID} '.value[] | select(.project.id=$PROJECT_ID) | .id'`
