### ISSUE TITLE
Please review this sentence

### ISSUE THREAD

**Issue by fabarz** [MicrosoftDocs/azure-devops-docs#11667]
Please review this sentence for grammer correctness and clarity of communication:
"in case you create your pipeline run is created manually or by a scheduled trigger, the default version, branch, and tags get used to evaluate the CI pipeline version."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Define YAML resources for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
I can't tell what the sentence in question is trying to say - or the preceding one.

**Comment by juliakm** [comment]
#reassign @ramiMSFT 

Thanks @TimShererWithAquent and @fabarz. We're going to check with the product team on this one.

**Comment by silviuandrica** [comment]
#reassign @silviuandrica 

investigating
