### ISSUE TITLE
命令示例错误

### ISSUE THREAD

**Issue by carrieyang1212** [MicrosoftDocs/azure-devops-docs#11662]
此示例：
![image](https://user-images.githubusercontent.com/57127288/143533965-4d2e9ef8-f8c0-46b5-ab30-fbca0df1496a.png)
提示报错：
![image](https://user-images.githubusercontent.com/57127288/143534003-f9161365-aa61-40f7-99cd-c0a2688d102e.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a3813d-668f-f3f0-2a10-97eef5cda914
* Version Independent ID: 79f91447-90e1-716c-8ae0-ba4b09d356bb
* Content: [Organization and project-scoped queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/account-scoped-queries?view=azure-devops-2020)
* Content Source: [docs/report/extend-analytics/account-scoped-queries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/account-scoped-queries.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@carrieyang1212 - I'm closing this issue as there is insufficient information to address the feedback. I just tried the query, and it returned expected results: 

`https://analytics.dev.azure.com/{OrganizationName}/_odata/v4.0-preview/WorkItems?$filter=Project/ProjectName eq 'Fabrikam Fiber'&$expand=Parent `

I've recently refreshed and added several articles under the getting started section available here: [Data available from Analytics](https://learn.microsoft.com/en-us/azure/devops/report/powerbi/data-available-in-analytics?view=azure-devops). Please reference that. If you run into problems, you might get help from our [Developer community page](https://developercommunity.visualstudio.com/AzureDevOps/report).
