### ISSUE TITLE
The Japanese version of the Azure App Service Deploy task contains documentation descriptions and prerequisites at the bottom.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#11666]
The English documentation for azure app service deploy task is first described as follows:

----------------------------------------------------------------------------------------------------------
Azure Pipelines

Use this task to deploy to a range of App Services on Azure. The task works on cross-platform agents running Windows, Linux, or Mac and uses several different underlying deployment technologies.

The task works for ASP.NET, ASP.NET Core, PHP, Java, Python, Go, and Node.js based web applications.

The task can be used to deploy to a range of Azure App Services such as:

Web Apps on both Windows and Linux
Web Apps for Containers
Function Apps on both Windows and Linux
Function Apps for Containers
WebJobs
Apps configured under Azure App Service Environments
Prerequisites for the task
The following prerequisites must be set up in the target machine(s) for the task to work correctly.

App Service instance. The task is used to deploy a Web App project or Azure Function project to an existing Azure App Service instance, which must exist before the task runs. The App Service instance can be created from the Azure portal and configured there. Alternatively, the Azure PowerShell task can be used to run AzureRM PowerShell scripts to provision and configure the Web App.

Azure Subscription. To deploy to Azure, an Azure subscription must be linked to the pipeline. The task does not work with the Azure Classic service connection, and it will not list these connections in the settings of the task.

----------------------------------------------------------------------------------------------------------

However, the Japanese version of this document provides descriptions and prerequisites at the bottom.
In any language, it is desirable that this description appear first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b648a9b-9a8d-423f-94c9-cb56ec458273
* Version Independent ID: efe57b89-fbac-8a5c-4607-102ebfd57b54
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/ja-jp/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
I'm not sure what's causing this issue. 

The material before the table appears in the Japanese version at the end of the article. The table is an HTML table, not markdown.

**Comment by juliakm** [comment]
I've opened a translation issue for this in our separate system.
