### ISSUE TITLE
Team Foundation Server Plugin is no longer supported. Need to remove reference from this page.

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#11670]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db21cb79-befe-a47b-e30d-cdea09adb8e3
* Version Independent ID: 38683079-aaff-a782-6064-ac7289d6b83b
* Content: [Jenkins Queue Job build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops-2020&source=docs)
* Content Source: [docs/pipelines/tasks/build/jenkins-queue-job.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/jenkins-queue-job.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
Hi @kripa-2019 It looks like we're tracking this issue here: MicrosoftDocs/azure-devops-docs/issues/11518. Thanks for letting us know -
