### ISSUE TITLE
Possible typo in note

### ISSUE THREAD

**Issue by l-diazs** [MicrosoftDocs/azure-devops-docs#11679]
Hi

I think there is a typo in the first note:

 (...) If you're collection is configured (...)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afec182-d90d-9f34-90a7-1e70b99b3220
* Version Independent ID: 63cc67a6-6baf-e4ed-34aa-2fb87b9a189b
* Content: [Create Excel reports from a work item query - Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/report/create-status-and-trend-excel-reports?view=azure-devops-2020#create-an-excel-report-from-a-flat-list-query)
* Content Source: [docs/report/create-status-and-trend-excel-reports.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/create-status-and-trend-excel-reports.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@l-diazs - Thank you for calling out the typo. I'll get it corrected later today.
