### ISSUE TITLE
Artifacts not listed on the correct Access Levels pages in Azure DevOps Server 2020

### ISSUE THREAD

**Issue by borshlite** [MicrosoftDocs/azure-devops-docs#11688]
Hello, We are using Azure DevOps Server 2020 V 18.17.30910.2

In the access levels area, Artifacts is still only listed under VS Enterprise, and is not listed under Basic (default) and Basic + Test Plans.

This page states in it's note that Artifacts now is included with all Basic plans.

Just wanted to point this out, as it caused me some confusion (and panic as I was concerned my org. was going to be billed for VS Enterprise)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51babfa-569b-ef0a-469a-849a3835b21b
* Version Independent ID: 97a78c7b-dc57-f040-4cc2-66cd91f9851f
* Content: [Azure Artifacts overview - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **rabououn**

**Comment by chcomley** [comment]
Thanks for this, @borshlite, and sorry for your confusion. I'll update the article to reflect this info. Once it goes live, this issue will automatically be closed. Thanks!

**Comment by chcomley** [comment]
I've updated the article; however, I didn't find an access levels section within it. Were you referring to a separate article? If so, please let me know which one. It appears to be clear in this particular article that Azure Artifacts is part of Basic access. Thanks!
