### ISSUE TITLE
Mention that repository: requires a user/account

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/azure-devops-docs#11687]
This will not work on sites like DockerHub which require a user/org:
```
repository: contosoRepository
```
The example should show:
```
repository: user/contosoRepository
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77386c22-1c7f-ab78-f541-52d50fa9fd8e
* Version Independent ID: be836c7f-2b53-c59a-7252-dfc15ec63537
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by juliakm** [comment]
#reassign juliakm 
investigating
