### ISSUE TITLE
Link not found in git-branching-guidance.md

### ISSUE THREAD

**Issue by sebainones** [MicrosoftDocs/azure-devops-docs#11682]
Hi, 
I believe there's a broken link. 
While navigating the following url: 
https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-branching-guidance.md

There's linked being pointed by : "How we use Git at Microsoft."
--> https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/devops/develop/how-microsoft-develops-devops
This URL returns a 404.

**Comment by TimShererWithAquent** [comment]
Hi @sebainones - Thanks for reaching out.

The link works from the Microsoft Docs page:

https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops

Not all of the links work from the source repos. It might be a link to a different repo that's resolved on publishing.
