### ISSUE TITLE
Wiki Page - Sorting Comments

### ISSUE THREAD

**Issue by mehul19851** [MicrosoftDocs/azure-devops-docs#11680]
Hi Team,
Can we add feature of sorting comments on a wiki page?
The user should have option to sort comments as  latest first and other similar options.

Many Thanks & Regards,
Mehul Harji Bhadricha
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Hi @mehul19851 - thanks for your suggestion! To make sure it gets in front of the right people, please [submit your suggestion here](https://developercommunity.visualstudio.com/search?space=21).
