### ISSUE TITLE
In which step is the cache being uploaded?

### ISSUE THREAD

**Issue by ozomer** [MicrosoftDocs/azure-devops-docs#11699]
In DownloadPipelineArtifact@2 it is clear that the hash is being uploaded in the PublishBuildArtifacts@1 step.
What happens for Cache@2 ? Is the cache uploaded in the end of the pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@ozomer Please refer to this [example](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#configure-the-cache-task) fore more details

> After the last step, a cache will be created from the files in $(Pipeline.Workspace)/.yarn and uploaded. On the next run, the cache step will report a "cache hit" and the contents of the cache will be downloaded and restored.
