### ISSUE TITLE
Section missing for a link on page for UNC tip

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/azure-devops-docs#11697]
On the page you give a tipe with a link at the end which is pointing to a header on the same page. But that section does not exist.
Could you please correct this?

The link ist:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#unc-file-share

> Artifact publish location argument: Azure Pipelines/TFS (TFS 2018 RTM and older: Artifact type: Server) is the best and simplest choice in most cases. This choice causes the artifacts to be stored in Azure Pipelines or TFS. But if you're using a private Windows agent, you've got the option to [drop to a UNC file share](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#unc-file-share).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#unc-file-share)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@ramiMSFT I'm not sure where the link was supposed to point. Looking at the history, I don't see a section being cut or moved to another article, which is usually what causes this.

**Comment by ramiMSFT** [comment]
@SebastianSchuetze @TimShererWithAquent Thank you for your feedback! I'll take a look
