### ISSUE TITLE
Using PR coverage together with human readable cobertura coverage on the build report

### ISSUE THREAD

**Issue by attilabertok** [MicrosoftDocs/azure-devops-docs#11695]
Is it possible to use this together with the human-readable coverage report on the build page? This requires trx/VsTest coverage format, that requires JaCoCo/Cobertura. Is there a way to create and publish both?

I am thinking of something along the lines of a yaml build step that would include something like both
`--collect:"XPlat Code Coverage"` and `--collect:"Code Coverage"`, but I am afraid that I'd not be able to supply the required format parameters.

Can I configure this from a runsettings file? Should something like configuring two data collectors work? Something along the lines of...

```xml
<?xml version="1.0" encoding="utf-8"?>  
<RunSettings>
  <!-- Configurations for DataCollectors -->  
  <DataCollectionRunSettings> 
    <DataCollectors> 
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>
        </Configuration>
      </DataCollector>
      <DataCollector friendlyName="Code Coverage" />
    </DataCollectors> 
  </DataCollectionRunSettings>
</RunSettings>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa4f4c6-0a42-108e-79dd-5724e1049bd5
* Version Independent ID: f4a857d1-78bc-170b-b138-fcf490c85b38
* Content: [Code coverage for pull requests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops)
* Content Source: [docs/pipelines/test/codecoverage-for-pullrequests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/codecoverage-for-pullrequests.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@attilabertok Thanks for your question. While we look into changes for this article, you might want to [reach out to the dev team](https://developercommunity.visualstudio.com/search?space=21).
