### ISSUE TITLE
pipeline trigger with stage filter not triggering when not producing artifact (information missing)

### ISSUE THREAD

**Issue by m-v-k** [MicrosoftDocs/azure-devops-docs#11694]
Please add information, that the pipeline triggers only work if the triggering pipelin (the source) publishes an artifact. it's very confusing to me, because i use a pipeline trigger with 'stage' filter (2 stages) so i expect a triggers after those 2 stages are completed succesfully (and not the entire pipeline or a stage that creates a artifact for that matter), which doesn't happen. 

thanks a million!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Many of the test pipelines that I used for creating the documentation publish an artifact and their pipeline completion triggers work. It sounds like you may have found a bug in the stage completion filters portion of pipeline completion triggers? Please file an issue here with the details of your scenario so the product team can evaluate to determine if it is a bug: https://developercommunity.visualstudio.com/AzureDevOps

Thank you
