### ISSUE TITLE
The FAQ section does not apply to the Delay task described here

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#11708]
The FAQ section makes no sense for this particular task.

For example, it states "Do I need an agent?"

However, this task is an *agentless* task and does not require an agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccdb37b-b69b-b2cc-5050-7944571c7ebc
* Version Independent ID: 43fea8d1-d842-b59a-4029-e9ea77dd79d9
* Content: [Delay task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delay?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/delay.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/delay.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
I agree, a lot of the FAQs were boilerplate and included with all tasks.

This issue is fixed in our new task reference here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/delay-v1?view=azure-pipelines#remarks

Please check it out and let us know what you think. Thank you.

**Comment by NenoLoje** [comment]
Thanks, @steved0x. The new task reference is better, but is confusing readers with a different issue.

It states:

> "Use this task in an agentless job of a release pipeline to pause the execution of the pipeline for a fixed delay time."

That sounds like it can be only used in a release pipeline, which is not the case. Correct would be to say: `It can be used in an agentless job`. That's it. Those are available both in release pipelines and YAML pipelines.
