### ISSUE TITLE
Enterprise distribution AppCenter DER sign help / documentation ?

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/azure-devops-docs#11701]
We are doing an enterprise deployment and to do so on iOS 15 we need to sign the app with DER entitlements like shown here.
We have the build configured in AppCenter but how do we also sign it with the DER entitlements ?
Here is a solution we have used but it requires humans ...
https://stackoverflow.com/questions/68467306/the-code-signature-version-is-no-longer-supported

How do we configure the Build in AppCenter to DER sign our app on build ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cd709cc-3300-bc7e-558e-ff324c9f69c8
* Version Independent ID: 30949e82-ac17-6d15-49c2-4318bf8e2ffe
* Content: [Build, test, and deploy Xcode apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/xcode.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/xcode.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Hi @stephenhauck Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Consider reaching out to the [dev community](https://developercommunity.visualstudio.com/search?space=21). You can also create a feature request there, if your desired scenario is not supported.

**Comment by stephenhauck** [comment]
If you document how to do it with the App Store why is t there documentation on how to do enterprise deployment … geeze
