### ISSUE TITLE
How can I configure branch naming?

### ISSUE THREAD

**Issue by stevendick-work** [MicrosoftDocs/azure-devops-docs#11705]
That branch naming policy can only be set with tf.exe after all these years is crap. I do not have the ability to install tf.exe.

As tf.exe must be manipulating a REST API, why can this not be documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddce170-618e-1307-d9bd-7113921521cc
* Version Independent ID: d60a1133-34d9-8e56-e716-526584fd67e0
* Content: [Require branches to be created in folders - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/require-branch-folders.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@stevendick-swissre Thanks for your suggestion. While we look into documenting this, consider making [a feature request](https://developercommunity.visualstudio.com/search?space=21).
