### ISSUE TITLE
Markdown code block syntax highlighting

### ISSUE THREAD

**Issue by QCShen** [MicrosoftDocs/azure-devops-docs#11711]
Hi, 

Do you have a plan to upgrade support for code block syntax highlighting to the latest version of [highlightjs](https://github.com/highlightjs/highlight.js), v11.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Hi @QCShen Thanks for your question. I can only suggest you go to the [feature timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline). If it's not listed there, [look at the dev team site.](https://developercommunity.visualstudio.com/search?space=21). You can also create a feature request there.
