### ISSUE TITLE
Suggestion: More advanced guideline

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/azure-devops-docs#11715]
When I was reading this I thought if a more advanced guideline is wanted. If yes what should I do to suggest an additional guideline beside this?

I find this guideline good for a start, but not good for more advanced setup. Do I just art contributing like editing an existing page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @SebastianSchuetze, sorry for the super delayed response! The answer, is YES, please! Clearly, we need the help, so we'd love for you to contribute! Here's our guidance and thanks so much in advance: [Microsoft Docs Contributor Guide Overview](https://docs.microsoft.com/en-us/contribute/)
