### ISSUE TITLE
There used to be a section in this documentation that explained how to refer to these variables in tasks and scripts

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#11714]
Like in a powershell script, one would use `$env:BUILD_BUILD_NUMBER` or something like that, or in a shell script it would be something different. That article content needs to be restored or made clearly available to a doc page like this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
You can find that content [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts) and [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch).

**Comment by StingyJack** [comment]
Specifically, the content I was trying to find before is [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#set-variables-in-pipeline:~:text=You%20can%20set%20a%20variable%20for%20a%20build%20pipeline%20by%20following%20these%20steps%3A)
