### ISSUE TITLE
Release pipeline auth does not support Microsoft Account

### ISSUE THREAD

**Issue by kganesan1** [MicrosoftDocs/azure-devops-docs#11710]
I created a release pipeline and used my hotmail acct to login into azure for the connection. However, the release failed. On researching in the web, it seems Microsoft Account is not supported for this purpose. It has to be domain acct for credentials or else used certificate approach. This page does not mention about these issues or even talk about (or at least a link) to page describing how to create certificate based auth for release pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a95fd0f-578f-308a-489d-b90c9163530b
* Version Independent ID: 4958a19d-78f0-750e-3750-3297989f451a
* Content: [Deploy an ASP.NET Cloud Service app (Classic) - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-cloudservice-cloudservice?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-cloudservice-cloudservice.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-cloudservice-cloudservice.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@kganesan1 Not sure I really understand the issue you are facing here so if you can rephrase it that would be helpful. Is the account you used to log in AD backed? You **Can** actually use a Microsoft account to log in and use both Azure and Azure Pipelines
[Pipelines - Sign up with a Microsoft account](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops#sign-up-with-a-microsoft-account)
[Azure - Set up sign-up and sign-in with a Microsoft account using Azure AD](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-microsoft-account?pivots=b2c-user-flow)
