### ISSUE TITLE
Feedback on Note

### ISSUE THREAD

**Issue by Turnip75** [MicrosoftDocs/azure-devops-docs#11725]
Howdy

I believe the first "Note" section is inconsistent.

It states the Windows Server 2016/VS 2017 is being deprecated as of Sep 2021, whilst suggesting lower down that customers are encouraged to migrate to that version.  Believer the "target version" should be Windows Server 2019 or 2022.

Dean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Good catch, I will get that updated today, thank you/
