### ISSUE TITLE
Return custom fields?

### ISSUE THREAD

**Issue by AmberMartin** [MicrosoftDocs/azure-devops-docs#11727]
This was extremely helpful :) Thank you so much!!! Is there a way to return custom fields? 

Thank you, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c556b002-bd47-a20b-da31-442b42e952ef
* Version Independent ID: 5b23a7b3-2ae1-0167-9bb7-3ca9a54e4f23
* Content: [Work Items with Direct Links sample report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-directlinks?view=azure-devops&tabs=odata)
* Content Source: [docs/report/powerbi/sample-boards-directlinks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-boards-directlinks.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AmberMartin - Yes, you can return custom fields. You can retrieve the data available to query from the following query as documented in [Data model for Analytics](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops). 
`https://analytics.dev.azure.com/{OrganizationName}/{ProjectName}/_odata/v4.0-preview/$metadata` 

Most custom fields should have a Property Name of Custom__Name_. For example: 
Display Name: Rule Type
Reference Name: Custom.RuleType
Property Name: Custom_RuleType
