### ISSUE TITLE
Fix first sentence of "Testing Applications" section.

### ISSUE THREAD

**Issue by chumbers** [MicrosoftDocs/azure-devops-docs#11720]
At https://docs.microsoft.com/en-us/azure/devops/test/overview?view=azure-devops#testing-applications, the paragraph starts with a lower case t, and there is a period that doesn't belong after the word, "portal".  Even with those fixes, the sentence still doesn't make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b59c9dac-1730-b602-7543-c0aa19271de9
* Version Independent ID: a9785c7e-e9fe-48bc-f7db-7297cebb4e4d
* Content: [Exploratory and manual testing overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/overview?view=azure-devops)
* Content Source: [docs/test/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Thanks, @chumbers - I fixed the typo and we're looking into the wording.

**Comment by TimShererWithAquent** [comment]
This was fixed by another PR. Thanks again, @chumbers
