### ISSUE TITLE
Example for using pipeline cache with Anaconda is wrong

### ISSUE THREAD

**Issue by ant0nsc** [MicrosoftDocs/azure-devops-docs#11724]
The example for using pipeline cache with Anaconda is wrong. Caching the `.condarc` file is not doing anything. The correct setting is:
```
variables:
  CONDA_CACHE_DIR: /usr/share/miniconda/envs
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#pythonanaconda)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@ant0nsc Thank you for your feedback!

**Comment by JThinkable** [comment]
This does NOT work for a Windows environment (like vmImage: windows-2019).  Instead use: 
```
variables:
  CONDA_CACHE_DIR: C:\Miniconda\envs
```
