### ISSUE TITLE
A link on how to tag your git repo on devops release would be nice

### ISSUE THREAD

**Issue by AartBluestoke** [MicrosoftDocs/azure-devops-docs#11737]
A common trigger of tagging a git repo is doing a code release.
It would be good if this page could have details, or a link, to how to get azure devops release pipelines to tag your repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c96e564-2fbb-0399-dfdd-fa9570710ae2
* Version Independent ID: 413f688e-16bc-123f-5103-a0a0ea95b7e2
* Content: [Use Git tags - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-tags?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/git-tags.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-tags.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by thepaulmacca** [comment]
I had the same thoughts as yourself, and I found this useful [blog post](https://jazz-twk.medium.com/automate-versioning-in-cicd-with-azure-devops-a65a9a6f4e69) on how to do it

Hope that helps you for now
