### ISSUE TITLE
Nuget custom upstream source not available

### ISSUE THREAD

**Issue by slobo80** [MicrosoftDocs/azure-devops-docs#11731]
The instructions claim that custom upstream public sources are available for nuget: "For public sources, choose npmjs, NuGet Gallery, PyPI, or Maven Central". 
I dont see nuget available. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for your feed - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@slobo80 Thanks for your feedback! The article has been updated. Custom public upstream sources are only available with npm .
