### ISSUE TITLE
Make wiki pages sort alphabetically

### ISSUE THREAD

**Issue by Gybrsh** [MicrosoftDocs/azure-devops-docs#11741]
It should be possible to order wiki-pages alphabetically. I consider this to be a normal feature. You would think that the developers had to make some extra effort NOT making it alphabetically ;)

**Comment by TimShererWithAquent** [comment]
@Gybrsh Thanks for your question. You should create a feature request. To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).
