### ISSUE TITLE
Couple of minor issue in this guide

### ISSUE THREAD

**Issue by JohanKlijn** [MicrosoftDocs/azure-devops-docs#11746]
Hi,
I followed the full guide of “Add a custom pipelines task extension” on this page https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops and found a couple of minor issues in the guide:
1.	Path in vss-extension.json is case-sensitive when building in Azure DevOps
In the guide we are creating a directory buildandreleasetask (all lower case), but in the vss-extension.json the path is camel-case (buildAndReleaseTask). Now when you create a pipeline in Azure DevOps (as described in the guide), the build will fail, because the images being used is ubuntu, so the path will become case sensitive. Solution: make buildAndReleaeTask path in vss-extension.json lower case.

2.	Mocha should be added as dev dependency or install on build agent
In de guide we install mocha like:
npm install mocha --save-dev -g
npm install sync-request --save-dev
npm install @types/mocha --save-dev
The first line will install mocha globally on the system and not as a dev dependency. Meaning we should do that also on the build Agent (or install mocha as a dev dependency).
3.	The value of he vsixFile parameter of the PublishAzureDevOpsExtension@3 is invalid.
The value in the guide is '/Publisher.*.vsix' but it should be '$(PublisherID).$(ExtensionName)/$(PublisherID).*.vsix'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @JohanKlijn,
Thanks for pointing these issues out. I've updated the article with your suggestions. Would you please let me know if I've missed anything? In the future, we'd love for you to become a contributor, so you can update docs on our public repo as you please! If you're interested, it's quick and easy - [go here](https://docs.microsoft.com/en-us/contribute/). Thanks again!
