### ISSUE TITLE
Burndown filtering

### ISSUE THREAD

**Issue by sandyteenan** [MicrosoftDocs/azure-devops-docs#11749]
Burndown charts aren't able to be filtered by a custom boolean field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sandyteenan - I will update the article to indicate this feature limitation. If you'd like to file a feature request, please go to our [Developer Community page](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
