### ISSUE TITLE
Tag trigger with wildcard

### ISSUE THREAD

**Issue by jmiddour** [MicrosoftDocs/azure-devops-docs#11742]
We found a quirk that we believe should be documented regarding tag triggers.

When including a tag trigger definition like so:
trigger:
  tags:
    include:
    - error_v*

This trigger will not fire as expected.  When including * in the tag name, you _must_ also surround that tag name with double quotes for it to work.

So this does work:
trigger:
  tags:
    include:
    - "error_v*"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Couple of other issues about wildcards:

MicrosoftDocs/azure-devops-docs/issues/11349
MicrosoftDocs/azure-devops-docs/issues/10212
