### ISSUE TITLE
Kubernetes Resource for Private AKS Clusters?

### ISSUE THREAD

**Issue by zojovano** [MicrosoftDocs/azure-devops-docs#11757]
The document doesn't mention whether using Kubernetes Resource in the Environment supports connecting to private AKS clusters (Kubernetes Management API has only private IP address).
It is to be assumed that this scenario is not supported but it would not harm to document the limit if it exist (or to document that both public and private clusters are supported).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@zojovano Both public and private clusters are supported. I'll add a note in the docs.
