### ISSUE TITLE
Azure App Service Deploy task - ConfigurationSettings - remove colon

### ISSUE THREAD

**Issue by MarienMonnier** [MicrosoftDocs/azure-devops-docs#11768]
There is a colon that should be removed from the "Example" in the "ConfigurationSettings" sample :

```
ConfigurationSettings (Configuration settings)
(Optional) Edit web app configuration settings using the syntax -key value. Values containing spaces must be enclosed in double quotes. Example: -phpVersion 5.6 -linuxFxVersion: node|6.11
```

There should not be a colon after `-linuxFxVersion` and it should be `-phpVersion 5.6 -linuxFxVersion node|6.11` 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b648a9b-9a8d-423f-94c9-cb56ec458273
* Version Independent ID: efe57b89-fbac-8a5c-4607-102ebfd57b54
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@MarienMonnier -- Marien, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- Roopesh, please review this change in [private PR 4138](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4138).

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
