### ISSUE TITLE
Price for agents scal set agents?

### ISSUE THREAD

**Issue by anasoid** [MicrosoftDocs/azure-devops-docs#11766]
I can't find in documentation any link to how scale-set-agents price will be caclulate.

Only  Microsoft agent and self-hosted agents are present in pricing page https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756d9c64-a802-61ad-ba6c-6061d2d747cf
* Version Independent ID: 012518b7-0282-f5b0-5206-8a9d1902b8d3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@anasoid I'll get that clarified, it is similar to self-hosted agents - you pay for the VM(s) that host the agents, and pricing is dependent on the VM pricing tier you choose for your scale set agents, and through Azure Pipelines, you pay for the number of parallel jobs you need to run. I'll confirm this and get the article update, most likely at the very start of the new year.

**Comment by steved0x** [comment]
AB#1904459

**Comment by anasoid** [comment]
Thanks @steved0x ,
For @selfhosted, the payment will be for the max used VM, or max configured VM ... ? and it's 15$/month ?

**Comment by steved0x** [comment]
> Thanks @steved0x Steve Danielson FTE , For @SelfHosted, the payment will be for the max used VM, or max configured VM ... ? and it's 15$/month ?

I'm sorry I didn't see this, it is the actual VMs used, not the potential max.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#how-much-do-scale-set-agents-cost
