### ISSUE TITLE
Instead of saying what to do, show it

### ISSUE THREAD

**Issue by mikerains** [MicrosoftDocs/azure-devops-docs#11769]
The documentation says: "n the subsequent run (in this case run number 23), Kubernetes manifest task with action: deploy and strategy: canary would result in ...".  This is not helpful to the new user.  The documentation should have inline samples of whatever it says to do.  In this case, it should show a section of the manifest task with the action and strategy.  Documentation which contains complete information is much more likely to lead to success.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3afe7466-570b-5159-bfab-d75030c3fbd8
* Version Independent ID: 53ea4e5d-237a-17fa-92b1-833334d3f378
* Content: [Deployment strategies for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/deployment-strategies?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/deployment-strategies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/kubernetes/deployment-strategies.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@shashankbarsin, @chcomley -- please suggest an alternative assignee for Atul.

**Comment by chcomley** [comment]
Let's try @juliakm. Thanks @WilliamAntonRohm.

**Comment by juliakm** [comment]
@mikerains You can find a more detailed article on Canary [here](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/kubernetes/canary-demo).

**Comment by mikerains** [comment]
Thanks @juliakm !!!  I have a passion for mentoring and wiki documentation.  Best regards to you and everyone at MicrosoftDocs!
