### ISSUE TITLE
Obsolete screenshot

### ISSUE THREAD

**Issue by martindufresne-orc** [MicrosoftDocs/azure-devops-docs#11763]
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=classic#export-and-import-a-pipeline

Screenshot for point **2. Choose ... and select Export** does not correspond to the current GUI: "Export to json"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6a24a4-066b-caaf-551a-0d58097fea4b
* Version Independent ID: d2cbc919-38f3-8aaf-b3d6-ab26c4a0d260
* Content: [Clone or import a pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=classic#export-and-import-a-pipeline)
* Content Source: [docs/pipelines/get-started/clone-import-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/clone-import-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by steved0x** [comment]
@martindufresne-orc I'll get that updated today, thanks for letting us know.
