### ISSUE TITLE
Instead of ‘Main’ database is ‘master’ 

### ISSUE THREAD

**Issue by mcadenaroa** [MicrosoftDocs/azure-devops-docs#11760]
Reference to ‘main’ database should be ‘master’ . Same for reference to system table: it should be master.sys.databases:

USE [main]
  GO
  IF NOT EXISTS (SELECT name FROM main.sys.databases WHERE name = N'DatabaseExample')
  CREATE DATABASE [DatabaseExample]
  GO

should say:

USE [master]
  GO
  IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'DatabaseExample')
  CREATE DATABASE [DatabaseExample]
  GO

**Comment by TimShererWithAquent** [comment]
This is the page referred to: https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb

**Comment by juliakm** [comment]
Thanks @mcadenaroa. I'll work on an update.
