### ISSUE TITLE
Wrong information about which env variables are being populated by the task  

### ISSUE THREAD

**Issue by iamNoah1** [MicrosoftDocs/azure-devops-docs#11772]
The Page says that the following env variables are being populated by the task: `VSS_NUGET_URI_PREFIXES `, `VSS_NUGET_ACCESSTOKEN ` and `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS `. After turning the debug mode on for one of my pipelines I can say that `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS ` is not populated, unfortunately. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7145130d-abba-fcfd-2016-e50c301c3f8b
* Version Independent ID: 900031bb-7389-2fee-7099-c3f48414efd1
* Content: [NuGet Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/nuget-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@iamNoah1 - Thanks for your question. We'll look into updating the article.

**Comment by iamNoah1** [comment]
@TimShererWithAquent If you want I can open a PR :)

**Comment by iamNoah1** [comment]
there you go @steved0x :)
