### ISSUE TITLE
Mention that sharing stage variables only works for next stage in line

### ISSUE THREAD

**Issue by wkoeter** [MicrosoftDocs/azure-devops-docs#11776]
There is an example of stage B depending on a variable from stage A.
It is noteworthy to mention that a potential stage C cannot depend on a variable for stage A.

That is not supported. It might spare anyone else the time I've put into figuring that out. (e.g. I hoped I could have 1 stage that determines a version number, and multiple stages that do deployment to DEV, TEST, ACC, PRD)

A => provided variable
B => can depend on A
C => can depend on B, **but not on A**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@wkoeter Thanks for your suggestion!

**Comment by wkoeter** [comment]
Incorrect by me. Will close issue.
All stages (B and C) can reference stage A with the `dependsOn` property and reference the variable as needed.

E.g. to reference variable in A:
- B depends on A
- C depends on A and B
