### ISSUE TITLE
Stop recommending Feature Timeline

### ISSUE THREAD

**Issue by scottcurrie** [MicrosoftDocs/azure-devops-docs#11782]
You should stop recommending Feature Timeline as it is no longer being maintained (over 2 years since last commit) and has many serious issues that have gone unresolved with no indication that work will resume. While it is not an exact match in terms of functionality, you should recommend Delivery Plans instead (https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b348a89-811c-2d1f-62f6-029d67213ef2
* Version Independent ID: 7fbb4ab1-701d-c88a-a14f-d29bbadd6981
* Content: [View of features and epics on the Feature Timeline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/feature-timeline?view=azure-devops)
* Content Source: [docs/boards/extensions/feature-timeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/extensions/feature-timeline.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Closing as addressed.
