### ISSUE TITLE
Suggestions on PR page information and needs for better query  tools

### ISSUE THREAD

**Issue by AlewsonRyan** [MicrosoftDocs/azure-devops-docs#11795]
what I would like to see in AzureDevops in regards to PR and related data is an actual Query where I can list All the attributes associated with the PR ,  like :  its creator, create date, PR ID, PR state,  Commit number associated with it and Ticket if associated with it too.    

Can you Create such Query ?  I saw a mention of adding the API ....  really ?  that is too much... Improve the UI in your tool and make it more like JIRA ATlassian.  
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a277513e-8285-2c22-b6c6-35abdcc5207d
* Version Independent ID: a277513e-8285-2c22-b6c6-35abdcc5207d
* Content: [View, filter, and open pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/view-pull-requests?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/view-pull-requests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/view-pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@AlewsonRyan - Thanks for your input. For product suggestions, please reach out to the dev team. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
