### ISSUE TITLE
There is a bug in the first block of code

### ISSUE THREAD

**Issue by antsok** [MicrosoftDocs/azure-devops-docs#11790]
where definitionId equals to 1, it should actually be $(System.DefinitionId)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a129c0-8a1c-40c3-47e6-8d95fbce5f26
* Version Independent ID: 8437e895-7164-8585-3b0d-adacd05e6851
* Content: [Using Tasks to Retain Runs in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/run-retention?view=azure-devops)
* Content Source: [docs/pipelines/build/run-retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/run-retention.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @moswald
* Microsoft Alias: **maoswald**

**Comment by TimShererWithAquent** [comment]
See also MicrosoftDocs/azure-devops-docs/issues/11668
