### ISSUE TITLE
Missing footnotes

### ISSUE THREAD

**Issue by codylc** [MicrosoftDocs/azure-devops-docs#11796]
This page refers to several footnotes, but those footnotes don't ever appear on the page. For example, in the "Fields used to plan and prioritize work" you'll find that "Value Area" features a **1** footnote and the values feature a ** footnote. However, these never seem to be defined in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a7ad6d-e610-358e-57ab-65c139ec2fad
* Version Independent ID: a84f995c-6511-7e3a-c911-8dca8e1fb357
* Content: [Create queries based on rank and priority fields - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/planning-ranking-priorities?view=azure-devops)
* Content Source: [docs/boards/queries/planning-ranking-priorities.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/planning-ranking-priorities.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
There's a numbered list in a Note element after this section with 1 and 2 - which I assume is the intended notes.

The ** are mis-formatting.

**Comment by KathrynEE** [comment]
@codylc - I am updating the article to address the format issues. The Notes section is reformatted so that it is more clear that the footnotes are provided at the end of the table.
