### ISSUE TITLE
The Configure security step in the app service is not up to date 

### ISSUE THREAD

**Issue by Djeffl** [MicrosoftDocs/azure-devops-docs#11809]
FAQ  at the end of the page is not up to date. 
This image should be plugged in.
![image](https://user-images.githubusercontent.com/16119584/148303288-3f341287-7418-4629-b371-ce52ecb4bade.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfc7aa5-d9ff-ad64-d26e-d2bd10470025
* Version Independent ID: 9b4f02ea-dab9-f613-5345-496435ab2408
* Content: [Deploy containerized applications to App Service on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=java%2Cyaml)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @Djeffl! I'll update this momentarily.
