### ISSUE TITLE
No explanation of API key

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [MicrosoftDocs/azure-devops-docs#11805]
This document has no explanation of how or where to get an API Key. Without this, the document is not very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f386bad4-494d-fcd3-b3f3-44a33601e866
* Version Independent ID: c1fe07ab-8092-26b7-f3f0-a3fce718da51
* Content: [Connect to a feed and publish NuGet packages using the command line - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Which API? This article is a walkthrough guide on how to set up your project and connect to a feed. 
If you want to use Azure DevOps API, refer to the docs [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact-details?view=azure-devops-rest-6.0)
