### ISSUE TITLE
Sample code correction

### ISSUE THREAD

**Issue by chvrl** [MicrosoftDocs/azure-devops-docs#11808]
Under the section [Allow external versions with PowerShell](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?view=azure-devops&tabs=nuget#allow-external-versions-with-powershell), the second PS code block contains the following line:
```ps1
$token = [Convert]::ToBase64String(([Text.Encoding]::ASCII.GetBytes("username:$PatVar")))
```
Since `PATVAR` was set up as an environment variable in the prior code block, it should be:
```ps1
$token = [Convert]::ToBase64String(([Text.Encoding]::ASCII.GetBytes("username:$env:PatVar")))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb8c20-fe29-a60c-dd6c-45c9e8278162
* Version Independent ID: ca24cdd8-dc94-6339-e2ef-95e5a84fa877
* Content: [Configure upstream behavior - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?view=azure-devops&tabs=nuget)
* Content Source: [docs/artifacts/concepts/upstream-behavior.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/concepts/upstream-behavior.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@chvrl Thank you for your feedback!
