### ISSUE TITLE
Bad formatting in this page

### ISSUE THREAD

**Issue by sushruth** [MicrosoftDocs/azure-devops-docs#11801]
Badly formatted content in this page.

![image](https://user-images.githubusercontent.com/2114206/147972640-9821880f-2ceb-4d77-910d-c9c853c1b1f3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9ad545-99a7-459a-5331-54736c13f35a
* Version Independent ID: 8e049be1-80d7-b1c8-e311-25fea3ad7d3c
* Content: [Capability Maturity Model Integration (CMMI) requirements reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/cmmi/guidance-requirements-field-reference-cmmi?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/cmmi/guidance-requirements-field-reference-cmmi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/guidance/cmmi/guidance-requirements-field-reference-cmmi.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sushruth - Thank you for bringing this to our attention. I will get this fixed today.
