### ISSUE TITLE
This is not the way a pipeline should work.  The release pipeline should automatically unzip artifacts, as that's what most people need.

### ISSUE THREAD

**Issue by Zombiesmith** [MicrosoftDocs/azure-devops-docs#11807]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b39f83-67e9-bf24-a3c6-1352db22fb38
* Version Independent ID: c3837e1d-e5ea-e8b0-b0fe-54b5f07e10b0
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
HI @Zombiesmith - Thanks for your input. Just to clarify - are you saying that we describe this task differently or that the product should handle this differently?

**Comment by Zombiesmith** [comment]
Good question.  Maybe I posted this in the wrong place.  The product should handle it differently.  The task is ok, but you shouldn’t have to unpack in every release pipeline, it should be delivered to the release unpacked, as the vast majority of people are going to want it that way.

Of course, I could go in to a lot of ways to improve the product, but I would say take a look at Octopus deploy.  Look at the way they do infrastructure, environments, lifecycles, and gates.  These are the things my DevOps team is struggling with in ADO, which is making it very hard for our people to adopt.  We are continually starting a pipeline in ADO and then ending up in Octopus because its just so much easier and reliable. 

-Kevin

Sent from Mail for Windows

**Comment by TimShererWithAquent** [comment]
@Zombiesmith You should check out the [dev board](https://developercommunity.visualstudio.com/search?space=21). You can search existing options and suggest features there.

I'll close this issue, but if there are doc issues around this, we can reopen.
