### ISSUE TITLE
How to get extension's unique key?

### ISSUE THREAD

**Issue by lijianzhi01** [MicrosoftDocs/azure-devops-docs#11817]
[Enter feedback here]
https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth?view=azure-devops#get-your-extensions-key

Follow this step, it is jwt in Certificate, not key! Please correct this step, thanks.

**"To get this key, right-click a published extension and select Certificate."**

![image](https://user-images.githubusercontent.com/13809749/148545063-9899ed86-4d1a-44bf-acdc-331e2bd6b921.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add23736-f0a9-2cc7-8bd2-4b8720898552
* Version Independent ID: 3f763c47-317d-a32a-37dd-6507d3f630b5
* Content: [Auth and Security - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth?view=azure-devops)
* Content Source: [docs/extend/develop/auth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/auth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by lijianzhi01** [comment]
In addition, even if I take jwt, that certificate, as unique key, the token validation failed following the steps from that wiki.

https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth?view=azure-devops#net-framework
![image](https://user-images.githubusercontent.com/13809749/148802540-d176b676-34d0-4903-b7fb-82749110ffbb.png)

This is my code, which use the latest jwt pkg.
![image](https://user-images.githubusercontent.com/13809749/148802746-1f146807-fb91-4dd8-a9bd-c5edae6666b4.png)

**Comment by chcomley** [comment]
@lijianzhi01, Thanks for your feedback. Adding @pkuma-msft for guidance.

**Comment by chcomley** [comment]
We invite you to become a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! If you're interested, please make your suggested update and we'll happily approve it! Thanks so much for your help.

**Comment by AshwaniT** [comment]
@pkuma-msft , @chcomley , @lijianzhi01 
I am facing same issue, what was resolution? how did you get unique key?
