### ISSUE TITLE
Delete tenant.cache from AppData\Local\GitCredentialManager

### ISSUE THREAD

**Issue by yysun** [MicrosoftDocs/azure-devops-docs#1181]

**Comment by steved0x** [comment]
@yysun Thank you for your feedback. The GitHub issues in this repo are for documentation feedback. If this is documentation feedback, can you let me know what article the feedback is for?

If this GitHub issue has product feedback, please file that feedback/feature request here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you

**Comment by yysun** [comment]
Sorry for the confusion. It is for this doc:
https://docs.microsoft.com/en-us/vsts/git/set-up-credential-managers?view=vsts

Following the doc, many still cannot connect to VSTS git. The tip to fix it is:
Delete tenant.cache from AppData\Local\GitCredentialManager
