### ISSUE TITLE
Need to Disambiguate for Use on Azure DevOps vs Azure DevOps Server

### ISSUE THREAD

**Issue by Ziebell-INL** [MicrosoftDocs/azure-devops-docs#11813]
The [Publish symbols to Azure Artifacts symbol server](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops-2020#publish-symbols-to-azure-artifacts-symbol-server) section only works on Azure DevOps. It will not work on Azure DevOps Server.

Likewise,  the [Publish symbols to a file share](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops-2020#publish-symbols-to-a-file-share) section only works on Azure DevOps Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2bfcb-0a0c-ce90-fa49-ad2e7fbaa57a
* Version Independent ID: 1a295877-ff8f-f8c2-0349-76a69a0f5cfc
* Content: [Publish symbols with Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops-2020#faqs)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Azure DevOps Server only supports publishing to a file share but Azure DevOps services support publishing symbols to both symbol servers and file shares. The updated article will be published shortly.
