### ISSUE TITLE
Clarify recommended filename for README

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/azure-devops-docs#11810]
The page should clarify that the conventional or recommended readme filename is README.md (casing matters)

This is also the default used when creating a new git repo in Azure DevOps.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39391dc7-8b3f-4a9f-8f0c-0309e642a95f
* Version Independent ID: bf8ba797-34c9-2c7a-6771-627c8a73401b
* Content: [Create a readme for your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-a-readme?view=azure-devops)
* Content Source: [docs/repos/git/create-a-readme.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/create-a-readme.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by VanessaRussell** [comment]
This seems important.  I arrived here after my `README` file was not correctly displaying until I renamed it to `README.md` like this issue suggests.
