### ISSUE TITLE
Multiple triggers are not working as documented on YAML pipelines

### ISSUE THREAD

**Issue by Kimxu1111** [MicrosoftDocs/azure-devops-docs#11821]
1.My repository "A" has a branch named "pipeline-test", which I want to add to the YAML pipeline as a multiple trigger.

![image](https://user-images.githubusercontent.com/97455898/148783096-aea5de0c-0a0a-416e-964e-a40512f88b37.png)

2.My repository "self" has a branch named "azure-pipelines", and I create the YAML pipeline using the existing Azure pipeline YAML file in this branch. 

![image](https://user-images.githubusercontent.com/97455898/148783124-0081e488-5df8-433e-b82a-dc98cc82e141.png)

3.Now "azure-pipelines" branch has the .yml file, "main" branch not.

![image](https://user-images.githubusercontent.com/97455898/148783173-3e6f5cc3-3c2b-48fd-93c8-2d03e6c4047f.png)

![image](https://user-images.githubusercontent.com/97455898/148783192-aacee9c9-849d-4bd1-b64f-bf6046f3bfa2.png)

4.Here is my YAML pipeline sample:

trigger:
- azure-pipelines
resources:
  repositories:
     - repository: Self
    - repository: A
      type: git
      name: Name of repository A
      ref: pipeline-test
      trigger:
        - pipeline-test

5.I could trigger the YAML pipeline from "azure-pipelines" branch in repo "self", but I could not trigger the pipeline from "pipeline-test" branch in repo "A".

If I merge my .yml file in "azure-pipelines" to default branch in repo "self", the issue could be fixed and the trigger works.

I refer to the following official documents: 

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#define-a-repositories-resource

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#triggers

Could this be updated on the MS documentation as it does not mention the pipeline must be present in that branch?

**Comment by Mr-Silv** [comment]
I can confirm this has been resolved for me by exporting the .yml pipeline from the pipeline-test branch on the "Self" repo and then uploading it to the default main branch on the "Self" repo. Once the pipeline was present in the default branch for that repository the triggers started working as expected.

**Comment by ray007330** [comment]
Any updates on this feature? 
I encounter the same problem about multi-repo trigger and the pipeline cannot be triggered from code changes in other repositories.

**Comment by oviliz** [comment]
The same problem for me and I see many similar reports on stackoverflow, it is ridiculous... :(

**Comment by MiYanni** [comment]
@Kimxu1111 It does say that the **default branch** must have the YAML file. https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops&preserve-view=true#triggers
> If a change to any other repository resource triggers the pipeline, then the latest version of YAML from the **default branch** of `self` repository is used.

It seems to be working as intended for your situation.
