### ISSUE TITLE
Add a warning about not being able to reference pipelines in an artifact

### ISSUE THREAD

**Issue by CCostaT** [MicrosoftDocs/azure-devops-docs#11823]
In section **Insert a template** the second paragraph states:

`Template files need to exist on your filesystem at the start of a pipeline run. You can't reference templates in an artifact`

I think this should be made more explicit by changing it to either a information or warning box as this information is very usefull when starting to work with pipeline resources and could save a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @CCostaT. I'll make it a larger warning.
