### ISSUE TITLE
DevOps Services Organization connected to AAD could have more than 300 projects.

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/azure-devops-docs#11830]
The documentation says "Azure DevOps Services limits each organization to 300 projects per organization. Above 300 projects certain experiences, such as connecting to the organization from Visual Studio, start to degrade."

However, as per findings Azure DevOps Services that are backed up by AAD can have more than 500 projects. So, does it mean 300 is a safe limit and not a hard limit?

Also, is it a hard limit (300 projects) with MSA backed Azure DevOps Services Organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4956039a-8296-c5e7-107e-9f42f1e39f33
* Version Independent ID: aae5a90e-0fc7-ed33-0936-10e37782d0dc
* Content: [Work tracking, process, and project limits - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops)
* Content Source: [docs/organizations/settings/work/object-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/work/object-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@Ahetejaz Thanks for your question. While we look into whether the information in this article is current, you might want to reach out to the dev team for more details. [Ask your question here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by KathrynEE** [comment]
@[Ahetejaz](https://github.com/Ahetejaz) - The 300 projects is not a hard limit. It is a guideline to avoid performance issues.
