### ISSUE TITLE
Azure DevOps Extension for Azure CLI: Is Azure DevOps server supported or not? 

### ISSUE THREAD

**Issue by oocx** [MicrosoftDocs/azure-devops-docs#11834]
The documentation says: "The Azure DevOps Command Line Interface (CLI) is available for Azure DevOps Server 2020 and Azure DevOps Services."

However, when I run commands, I get the warning "The Azure DevOps Extension for the Azure CLI does not support Azure DevOps Server."

The command succeeds despite the warning.

The documentation is contradicting the output from running the tool.

```
az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.22.0"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@oocx - Thank you for reporting this issue. I will let the product team know of the error in their messaging.

**Comment by avazula** [comment]
Hi,

I also get this warning when trying to retrieve a variable group from a self-hosted instance, but mine does not succeed. 

Is it actually possible to run such commands on a self-hosted instance?

**Comment by KathrynEE** [comment]
@avazula - Azure CLI commands only work against the hosted service, Azure DevOps Services. They aren't supported for on-premises Azure DevOps Server. At one time, we had it documented that they were available on-premises, but that was incorrect and has since been updated to reflect that they only supported the hosted service.

**Comment by neolikecoding** [comment]
Is it going to be supported ever for on-prem Azure DevOps Server? Is there alternative?

**Comment by KathrynEE** [comment]
@neolikecoding - There are no plans to support azure cli commands for the on-premises server.  There isn't a comparable solution for all commands. Is there something specific you're trying to do?

**Comment by jblennon** [comment]
@KathrynEE I am trying to get permission groups and add users to an Azure Devops 2020 Server.    It is my understanding that Azure CLI and Graph APIs are not avilable for 2020 Server.  Is there anyway this can be accomplished?

**Comment by KathrynEE** [comment]
@jblennon - you can’t do this with Azure CLI, but you should be able to do it using TfsSecurity, https://learn.microsoft.com/en-us/azure/devops/server/command-line/tfssecurity-cmd?.toc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Fbreadcrumb%2Ftoc.json&view=azure-devops-2022&viewFallbackFrom=azure-devops
