### ISSUE TITLE
"upgrade command" does not include ChartPath in the list of parameters

### ISSUE THREAD

**Issue by PehrGit** [MicrosoftDocs/azure-devops-docs#11836]
See below image. In the example we can see that when choosing "filepath" as "charttype", we need to specify the path in "chartPath". However in the list of parameters, we only see "chartName" which leads one to believe that the chart path should be specified in "chartName" parameter both if "charttype" is "name" and when it is "filepath"

![image](https://user-images.githubusercontent.com/3782086/149311864-c330abba-8f50-4aca-8b29-85573a2c2c15.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dcde0ed-1d6e-1d31-7fb8-e91e8e9d200d
* Version Independent ID: 9320f59d-1ad5-80f1-a750-764cbf9d006a
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@PehrGit Thanks for finding this one. It looks like this is being tracked as MicrosoftDocs/azure-devops-docs/issues/11602, so I'm going to close this one just for neatness sake.
