### ISSUE TITLE
How many retries does Azure DevOps Server try to send an email until it gives up, if at all?

### ISSUE THREAD

**Issue by icnocop** [MicrosoftDocs/azure-devops-docs#11833]
Another reason why I may not receive an email from subscriptions or notifications is because the email server is down, unreachable, could not be authenticated, etc.

If the email server is down at the time Azure DevOps Server tries to send an email, does it keep trying to resend the email?

If so, how many retries does Azure DevOps Server try to send an email until it gives up, if at all?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330ab490-e22a-9f20-e80a-28cc42c79064
* Version Independent ID: be04876e-25a1-6670-8815-2457ef116dc8
* Content: [Why am I not receiving notification emails? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/troubleshoot-not-getting-email?view=azure-devops)
* Content Source: [docs/notifications/troubleshoot-not-getting-email.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/notifications/troubleshoot-not-getting-email.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@icnocop Thanks for your question. For product questions, to make sure it gets in front of the right people, please [address your issue here](https://developercommunity.visualstudio.com/search?space=21).
