### ISSUE TITLE
PublishSymbols@2 task documentation is missing `--indexableFileFormats` parameter

### ISSUE THREAD

**Issue by robpaveza** [MicrosoftDocs/azure-devops-docs#11843]
`PublishSymbols@2` supports an additional parameter, `--indexableFileFormats`. The command line help output specifies:

```cmd
 [   --indexableFileFormats <value>]  Which debug formats to publish. (Default, None, Pdb, SourceMap, All). The Default is Pdb
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6927d4e6-671c-454e-dbba-3aabbca3a761
* Version Independent ID: 548fd69e-e618-22e3-04a6-f6c92fc1926b
* Content: [Index Sources & Publish Symbols - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/index-sources-publish-symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/index-sources-publish-symbols.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by ramiMSFT** [comment]
@robpaveza Thank you for your feedback! The default value for `IndexableFileFormats` is default. I added `IndexableFileFormats` and `SymbolExpirationInDays`. I'm updating the task shortly
