### ISSUE TITLE
please clarify valid AccountLicenseType values

### ISSUE THREAD

**Issue by smholvoet** [MicrosoftDocs/azure-devops-docs#11844]
This page mentions the following access levels and their respective `AccountLicenseType` and `msdnLicenseType`:

| Access level (user interface)| AccountLicenseType | msdnLicenseType| 
| --------------------------|-----------------------------|-----------|
| Stakeholder | stakeholder | none | 
| Basic              | express  | none | 
| Basic + Test Plans | advanced | none | 
| Visual Studio subscriber | none | eligible | 
| Visual Studio Enterprise | none | enterprise | 

However, this is what I'm seeing in my org when I use the [User Entitlements - List REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/list?view=azure-devops-rest-4.1&viewFallbackFrom=azure-devops-rest-6.0):

| Access level (user interface)| AccountLicenseType | msdnLicenseType| 
| --------------------------|-----------------------------|-----------|
| Stakeholder | stakeholder | none | 
| Basic              | express  | none | 
| Basic + Test Plans | advanced | none | 
| 👉 Visual Studio **Subscriber** | ~none~ | ~eligible~ | 
| 👉 Visual Studio Professional **subscription** | **none** | **professional** | 
| 👉 Visual Studio Enterprise **subscription** | none | enterprise | 

- The "Visual Studio Professional subscription" is missing from this overview
- Both the "Visual Studio Professional" and "Visual Studio Enterprise" licenses mention "subscription" in the UI
- Visual Studio Subscriber has a capital S in the UI
- Users which have a "Visual Studio Subscriber" license assigned, can't actually be found programmatically (to be confirmed by the product team?), e.g. via the [User Entitlements - List REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/list?view=azure-devops-rest-4.1&viewFallbackFrom=azure-devops-rest-6.0). They will however be visible in the UI:

![image](https://user-images.githubusercontent.com/13507392/149562523-18db5be0-8be0-423d-9eaa-9065868040b0.png)

I'm guessing users which have a VS Professional or Enterprise license are initially assigned "Visual Studio Subscriber", which then gets changed to either "Visual Studio Professional" or "Visual Studio Enterprise" automatically once they sign in?

I'm willing to launch a PR for any pages which reference the license types above, once the above questions are cleared up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [About access levels - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops#programmatic-mapping-of-access-levels)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@smholvoet - Thank you for raising this issue.  I'm updating the article and changes should be visible by end of day.  FYI - I was able to use the REST API to query the accessLevel for a Visual Studio Subscriber. The relevant response was: 

`"accessLevel":{"licensingSource":"msdn","accountLicenseType":"none","msdnLicenseType":"eligible","licenseDisplayName":"Visual Studio Subscriber","`

Regarding _"I'm guessing users which have a VS Professional or Enterprise license are initially assigned "Visual Studio Subscriber", which then gets changed to either "Visual Studio Professional" or "Visual Studio Enterprise" automatically once they sign in?"_  - Yes, this is true.
