### ISSUE TITLE
Version quotation

### ISSUE THREAD

**Issue by a12com** [MicrosoftDocs/azure-devops-docs#11855]
_--version *_ parameter will not work because of paramether substitution (at least in bash):

![image](https://user-images.githubusercontent.com/41744861/149954074-d337d1ba-6566-451f-ad8e-12d20ee93721.png)

So it suppose to be quoted like _--version '*'_ then it will work corretly:

![image](https://user-images.githubusercontent.com/41744861/149954717-3feb4a98-6b53-4cef-9569-b216366fc46c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages with Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops#download-the-latest-version)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@a12com -- thank you for catching this.  I am updating the article.
