### ISSUE TITLE
Avoid trigger from CI and dependent pipeline

### ISSUE THREAD

**Issue by Qandelor** [MicrosoftDocs/azure-devops-docs#11859]
[Enter feedback here]
The article should point out that to get the dependent pipeline ONLY trigger based on the source pipeline one has to add the lines:

trigger: none
pr: none

to the dependent pipeline YAML.

This was not obvious as I was expecting an explicit trigger declaration  (inside the "resources") to override any default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This change will be live later today, thanks for letting us know.
