### ISSUE TITLE
More FAQs needed to describe upstream sources behavior

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/azure-devops-docs#11869]
There are a few behaviors I had to learn by trial and error because I could not find them covered in the documentation. To remedy that, I suggest the following additions to the FAQ. The first 2 I found in documentation, but it was not easy.  The third I could not find. That one is important for those of us who make the mistake of assuming the feed behaves like a cache for upstream sources, as is the behavior of upstream sources in MyGet.org.

Q: What entities can trigger a refresh from upstream sources of an ADO feed?
A: Any entity with a Contributor or higher role that downloads from the feed. 

Q: Can an entity with Reader role in an ADO feed download upstream sources?
A: No. The Reader role can only download those sources that have been saved to the feed. Upstream sources are saved to the feed when a Contributor role or higher downloads those sources from the feed. 

Q: If I delete or unpublish a package in the ADO feed that originally came from an upstream source, what is the effect?
A: That particular package version is no longer visible on the ADO feed and is blocked from being downloaded from the ADO feed. It also can no longer be refreshed or saved to the ADO feed from upstream. Earlier and later versions of the package are not affected. 

Q: If I deprecate a package in the ADO feed that originally came from an upstream source, what is the effect?
A: A warning message is shown whenever the package is installed from the ADO feed. Its visibility on the ADO feed and downloading it from the ADO feed are not affected.

Thank you.
--Bruce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72b4d1-30d9-4e08-c9bf-cb8457a3d05f
* Version Independent ID: 7d9e328b-8bf7-1706-b0e1-061eb221023c
* Content: [Upstream sources overview - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@BruceHaley Thank you for your feedback! I will be updating the article shortly. 

1/ Force refresh is not available yet. The team is looking into this

2/ download packages from an upstream source
Packages are saved to the feed when a **Collaborator**, a **Contributor**, or an **Owner** install those packages from upstream.
