### ISSUE TITLE
Missing link to more information about security changes

### ISSUE THREAD

**Issue by spoelstraethan** [MicrosoftDocs/azure-devops-docs#11867]
> For information on how to specify relative links from a Welcome page or Markdown widget, see Source control relative links.

The "Source control relative links" is in bold on the page but missing a link anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@spoelstraethan Thanks for finding this. I've done a fix.
