### ISSUE TITLE
No option to generate Bugs on failed builds

### ISSUE THREAD

**Issue by Allann** [MicrosoftDocs/azure-devops-docs#11864]
Whilst it is easily possible to export to YAML, it doesn't include a like for like experience.  this should be pointed out in the docs.  I have created numerous Classic dotnet core build pipelines and they will generate a bug if a build fails and assigns them to the requestor.  This is enabled by just selecting a checkbox.

If YAML is going to be the default and recommended approach for builds shouldn't it also include these "built-in" features from classic tasks?  I can understand that these tasks could be community driven and I wouldn't expect them to convert, but I specifically try to use tasks created by MS as I find they are usually of a higher quality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36333c89-6223-73cb-ce45-6fbb2638722e
* Version Independent ID: 286b8f96-6374-fedd-8d8d-a37fa5e1948e
* Content: [Migrate from Classic to YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/migrate/from-classic-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/migrate/from-classic-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-migrate**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
Thanks for your suggestion, @Allann - while we look at the docs, you might want to engage with the dev team about features. 
[Take a look here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by juliakm** [comment]
@Allann We don't have a built-in way to create a Boards bug on build failure with YAML pipelines. You have a couple of options for creating this functionality yourself. 
- You can use a script or powershell task and call our [REST API](https://docs.microsoft.com/rest/api/azure/devops/pipelines/?view=azure-devops-rest-7.1). 
- You can use Azure CLI. There's an example of using the CLI to create a bug on failure [in this article](https://docs.microsoft.com/azure/devops/pipelines/customize-pipeline?view=azure-devops#create-work-item-on-failure).

I'll update the article to make this clearer.
