### ISSUE TITLE
PublishPipelineArtifact@1 has different input names

### ISSUE THREAD

**Issue by imsh** [MicrosoftDocs/azure-devops-docs#11874]
This is what the editor on dev.azure.com suggests as task's parameters:
```
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: ''
    artifact: ''
    publishLocation: '...'
    fileSharePath: '...'
    parallel: true
    parallelCount: 1
```
And this is what you have in the docs:
```
    #targetPath: '$(Pipeline.Workspace)' # Required 
    #artifactName: 'drop' # Optional
    #artifactType: 'pipeline' # Required. Options: pipeline, filepath. Default value: pipeline
    #fileSharePath: '\server\folderName' # Required when artifactType = filepath
    #parallel: false # Optional. Default value: false
    #parallelCount: 1 # Optional. Value must be at least 1 and not greater than 128. Default value: 8
```
As you can see, parameters 'artifact' and 'publishLocation' are not described in the docs. 
In reality both variants of parameter names seem to work fine, but it would be nice if docs describe the recent version of the task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
@imsh Thank you for your feedback! The difference is that one is using *names* and one is using *aliases* but both are correct. I'm updating the task for consistency.
