### ISSUE TITLE
IDE clone clones to wrong branch

### ISSUE THREAD

**Issue by 72gm** [MicrosoftDocs/azure-devops-docs#11873]
When cloning a repo using the "clone in VS Code" option clones the repo in the "main" branch even though you are currently in "feature1" branch  

![image](https://user-images.githubusercontent.com/12847881/150511707-96f69133-187e-4a5b-9216-6f6c1309c7a9.png)

Clearly this should clone it to the feature branch and not the main branch....  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f05d5b-ace2-0681-9443-e8bb2500cc20
* Version Independent ID: 951c8c04-684c-cd89-fb34-ab9a42bdb03b
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/clone.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@72gm Thanks for your suggestion - to make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

I am going to keep this issue open, in case we should point this behavior out in the article.

**Comment by 72gm** [comment]
@TimShererWithAquent that's a link to reporting problems with Visual Studio, not VS Code... is there an equivalent or is it just the issues section of the github repo? thanks
