### ISSUE TITLE
Release Pipelines: Vertical (Artifact + Stages) Groups, when running prod, multiple integration branchs, develop branchs that

### ISSUE THREAD

**Issue by wesleyolis** [MicrosoftDocs/azure-devops-docs#11871]
When working in larger work flows of integration when many people.

Typically there is an integration release too, were by items are not official release but they are integration target candidates for a release.
Typically because so many things that go wrong in the integration, that usually goes over multiple sprints due to the size of the integration and number sprints to fix things up across multiple teams. Feature which are typically all to be release to gather are target as specific integration release. So you can have multiple integration release running at once, in which all could be live and deployed for testing at the same time. once something passing integration, it will be converted to a release.

Typically what one would like with the work flows, is each time a new integration target is created. is the a new release iteration is created for the develop stream, in which the same existing single release is retriggered.

Feature: 
When working with such complex systems, the issues, is every time create a new branch, you need the artifacts to be rebuild from that branch. therefor one has to have like prod, int, dev, release design. Which doesn't give one the bigger picture of things making it out to production for tracking.

There for the ability to with in a release have multiple release, maybe call it a release group, you have overview of exactly were things are in the larger process of testing and deployment and release. Also be great for management as lovely dash board, exatly where things are and which features are included and also how many iterations there were in develop, int, and bugfix to production for those features. It could all be tracked to the initial release candidate and presented nicely.

**Comment by TimShererWithAquent** [comment]
@wesleyolis - this looks like a [feature request](https://developercommunity.visualstudio.com/search?space=21), too.
