### ISSUE TITLE
Task Groups: Unusable in greater scope of things, Enable Checkbox for each group variable as well add variable.

### ISSUE THREAD

**Issue by wesleyolis** [MicrosoftDocs/azure-devops-docs#11870]
Good Day,

Please can you improve task groups, in its current form it basically can't be used with powershell scripts, as picks up the internal variables of the scripts. The only hack solutions are to export and re-import the Task groups and delete the powershell scripts variables, otherwise the scripts break, because azure pipelines injects the variables into power shell scripts and they readonly. So then the scripts all break.

Because you can't update a Task group from via an import, which could be a feature improvement, basically have to go 
relink all the stage in every single release to a new imported version of the task group, as given and new id on import.

even trying required:false, doesn't help, you have to remove powershell variables references which picked up and defined as variable groups.

This basically renders Task groups useless and limited to task groups that don't contain any scripts. It never happens that you won't have a script.

Feature:
Simplistic quick fix, add a checkbox enabled button for each group variable, you could also add an additional button to add other intermediate calculation variables. that everything else at least works.

After having to push all the boundaries of what azure pipelines is able to do, such that my work becomes simple, however, these flaws are heavy to change anything that should be simple.

Sadly, I will have to look at other products until all the Task Groups functionality is sorted out or suffer.

**Comment by TimShererWithAquent** [comment]
Hi @wesleyolis - Thanks for raising this. We only deal with the docs on this board. To make sure it gets in front of the right people, please [submit your suggestion here](https://developercommunity.visualstudio.com/search?space=21).
