### ISSUE TITLE
Storing build artifacts for later release

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/azure-devops-docs#11879]
I see this step is depracated in favour of pipeline artifacts

However pipeline artifacts only yield the most recently built artifact.

In classic pipelines we could publish an artefact from a build and then in a different deployment step (which might come many builds later) we could select an artefact published in the past and deploy that.

pipeline artefacts won't support this as they only yield the latest built artefact - can you suggest a different pattern that would support this? Or is the recommendation always to build from source prior to deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd43f88-bb0b-e6c1-3a1d-c34af9a11dfb
* Version Independent ID: 282eb416-bb03-9553-dbc2-71bb71191c73
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@ElectricLlama Thanks for your question. You should reach out to the dev community with product questions. Also, if you have a feature suggestion, you can make it [here](https://developercommunity.visualstudio.com/search?space=21).
