### ISSUE TITLE
Proper formation of http headers for successful authentication

### ISSUE THREAD

**Issue by micale-pgnig** [MicrosoftDocs/azure-devops-docs#11877]
It would be useful to modify shell snippets (both bash and powershell) including mandatory colon prepending actual PAT. I bet I am not the only one to find that it is actually
`$MyPat = ':ActualPatStringFromWebUI'
hard way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops-2020&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @micale-pgnig, thank you for pointing this out! I've made the update! This issue will automatically close once the updated article has been published. :)
