### ISSUE TITLE
Update Ubuntu Docker image to 20.04

### ISSUE THREAD

**Issue by mountain65** [MicrosoftDocs/azure-devops-docs#11880]
[Enter feedback here]
This page gives a sample Dockerfile with a Ubuntu:18.04 image. This image does not have the timezone info in the right place. If you run a unit test in your pipeline that tries to get a TimeZoneInfo, it will never be found. I updated the Dockerfile to Ubuntu 20.04 and now it works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thepaulmacca** [comment]
When I update the Dockerfile to 20.04, I get this error:

`E: Unable to locate package libicu60`

How did you resolve this? Having to stick with 18.04 for now
