### ISSUE TITLE
Default branch for Wiki - is there an undocumented way to control it?

### ISSUE THREAD

**Issue by EQDGL** [MicrosoftDocs/azure-devops-docs#11884]
When multiple versions of a branch are published to a wiki what determines the default version selected in the drop-down list of versions? It does not appear to be the default branch as designated in Git which would be useful I think - e.g. typically I want readers to default to seeing the doc for my latest product release so it would be useful to have a way to make that the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c697355f-1e75-27a9-8214-195c26ede4e7
* Version Independent ID: 3f62c207-5449-d7f3-f3b3-82d6fc8f014d
* Content: [Publish, select, or unpublish a wiki version - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-select-unpublish-versions?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-select-unpublish-versions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-select-unpublish-versions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@EQDGL You might want to reach out to the dev community with a feature request. To make sure it gets in front of the right people, please [enter your request here](https://developercommunity.visualstudio.com/search?space=21).
