### ISSUE TITLE
Error in Source Code

### ISSUE THREAD

**Issue by holbizmetrics** [MicrosoftDocs/azure-devops-docs#11888]
[Enter feedback here]

There's an error in Line 71:

This won't work:

`return await httpClient.GetWorkItemsBatchAsync(ids, fields, result.AsOf).ConfigureAwait(false);`

instead, it should be:

`return await httpClient.GetWorkItemsAsync(ids, fields, result.AsOf).ConfigureAwait(false);`

Because **_GetWorkItemsBatchAsync_** takes a _WorkItemBatchRequest_ as first parameter!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978322f-15ae-3a89-ae89-497cdfa5070a
* Version Independent ID: f8654902-e266-c12b-8e25-a2fa7a2ac626
* Content: [Get work items programmatically from Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/quickstarts/work-item-quickstart?view=azure-devops)
* Content Source: [docs/integrate/quickstarts/work-item-quickstart.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/quickstarts/work-item-quickstart.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@holbizmetrics, thank you so much for alerting us of this issue! Once my update gets published, this issue will automatically close. We'd love for you to become a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/), if you happen to find some discrepancies in the future. It's super quick and easy!
Thanks again!
