### ISSUE TITLE
Malicious Script embedded

### ISSUE THREAD

**Issue by dmedeiros-veracode** [MicrosoftDocs/azure-devops-docs#11897]
Within this bulleted statement there is a malicious script coming from the external source. The link is attached to the Node10 hyperlink.

The latest version of Node.js. The production environment uses only **Node10** or Node6 (by using the "Node" in the "execution" object instead of Node10).

When accessing the external site link: http://blog.majcica.com/2018/12/04/node10-provider-available-for-agent-v2-144-0/ a malicious script injection is launched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @dmedeiros-veracode, this is quite odd, thanks so much for bringing this to our attention. I'll make the update today! This issue will automatically close, once it's published. Thanks again and please consider becoming a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)!
