### ISSUE TITLE
TFVC Plugin is deprecated

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#11898]
The TFVC Plugin referenced in this article is deprecated.

https://plugins.jenkins.io/tfs/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db21cb79-befe-a47b-e30d-cdea09adb8e3
* Version Independent ID: 38683079-aaff-a782-6064-ac7289d6b83b
* Content: [Jenkins Queue Job build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/tasks/build/jenkins-queue-job.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/jenkins-queue-job.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@kripa-2019 Thanks for finding this. It looks like we're already tracking this here MicrosoftDocs/azure-devops-docs/issues/11518

@steved0x for awareness. It looks like there was a PR that was closed without merging. Not sure what's going on.
