### ISSUE TITLE
YAML pipeline support

### ISSUE THREAD

**Issue by roizentner** [MicrosoftDocs/azure-devops-docs#11895]
It says that the Deployment control does not support linking to release stages defined for a YAML pipeline, but there's no mention for an alternative or something to suggest that this is being considered in the roadmap.
How else are we supposed to understand which features and bug fixes are currently deployed and on which environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments and other objects - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@roizentner Thanks for your question. While we look into changes for the article, you should reach out to the [dev team](https://developercommunity.visualstudio.com/search?space=21) with product questions and feature requests.

**Comment by KathrynEE** [comment]
@roizentner - Thank you for your inquiry. I spoke with the Azure Boards PM and he indicated that there is discussion of adding support for YAML pipelines for the deployment control. There's no final decision yet. If support is planned, it will be added to the [Features Timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline) and the [Azure DevOps Roadmap](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_backlogs/backlog/AzureDevOpsRoadmap%20Team/Roadmap%20Items).

**Comment by roizentner** [comment]
@TimShererWithAquent I see other people have already reached out to the dev team (e.g. [here](https://developercommunity.visualstudio.com/t/report-deployment-status-to-boards/814914)) but there was no response from the dev team.
@KathrynEE Thank you for speaking with the PM. I hope you'll update the documentation with the plan once a final decision is taken.
In the meantime, I've thought of a work-around, putting it here in case others come across this:
I will trigger a classic release using a Build Artifact trigger (I will produce a dummy artifact from each stage in my multi-stage YAML pipeline). The classic release will report back to the boards and do nothing else.
Thanks again to both of you :)
