### ISSUE TITLE
Tipp is out of date

### ISSUE THREAD

**Issue by SeBaconStrip** [MicrosoftDocs/azure-devops-docs#11896]
The tipp "Make sure you check your .artifactignore file into the root of your repository." is not correct the .artifactignore file has to be in the specified publish folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
Hi @SeBaconStrip - Thanks for finding this. It looks like we're already tracking this as part of /MicrosoftDocs/azure-devops-docs/issues/10548

**Comment by ramiMSFT** [comment]
@SeBaconStrip Thank you for your feedback! The docs will be updated shortly.
