### ISSUE TITLE
Is only one level of inheritance supported? If so why not multiple levels like other devops tools?

### ISSUE THREAD

**Issue by vijay-gowda** [MicrosoftDocs/azure-devops-docs#11890]
Is only one level of inheritance supported? If so why not multiple levels like other devops tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@vijay-gowda - you should reach out to the dev community with this question. You can make feature requests, there. To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).
