### ISSUE TITLE
Where on earth is that button?

### ISSUE THREAD

**Issue by Hobbamok** [MicrosoftDocs/azure-devops-docs#11894]
"Navigate to the pipeline details page for your pipeline."
Yeah cool, where the F*** is that? How does that details page even look like? Wastes 15 minutes on what should've been a 5 minute task on any sane platform
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6a24a4-066b-caaf-551a-0d58097fea4b
* Version Independent ID: d2cbc919-38f3-8aaf-b3d6-ab26c4a0d260
* Content: [Clone or import a pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/get-started/clone-import-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/clone-import-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for your help! You can find more information on navigating our UI [in this article](https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser#view-pipeline-run-details).
