### ISSUE TITLE
Limit visibility within people pickers: Warning statement

### ISSUE THREAD

**Issue by jdkemme** [MicrosoftDocs/azure-devops-docs#11892]
The warning statement "When the Limit user visibility for projects preview feature is enabled for the organization...." is not entirely accurate.  Guest users placed into the limited group cannot search with people picker for ANY users- whether the searched users are directly added to the project or not, when guests are set to the default access level (limited access) in Azure AD.  When the preview feature is off, or guests aren't members of the limited group, guests can search all AD users as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [About projects and scaling your organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects?view=azure-devops#limit-visibility-within-people-pickers)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/projects/about-projects.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jdkemme, Thanks for your feedback. Once the article update goes live, this issue will automatically close. Consider [becoming a contributor to our docs](https://docs.microsoft.com/en-us/contribute/) for any future updates!
