### ISSUE TITLE
There's no git-credential-manager-core documentation for connecting to Azure Repos

### ISSUE THREAD

**Issue by coty-terumo** [MicrosoftDocs/azure-devops-docs#11909]
There's no git-credential-manager-core documentation for connecting to Azure Repos. These docs refer users to outdated, unmaintained software.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 440ae0b6-c701-1682-8540-c306d1221711
* Version Independent ID: 8ec9f10d-3ec2-0643-b4ac-ffa81d2f8ce3
* Content: [Authenticate with your Git repos - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops)
* Content Source: [docs/repos/git/auth-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/auth-overview.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
Hi @coty-terumo - Thanks for your question. Can you clarify a little? Which is the outdated software you're referring to?

Also, you're referring to an overview page. I wonder if there might be a better location, maybe https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops
