### ISSUE TITLE
SSH keys are of a deprecated type

### ISSUE THREAD

**Issue by alansill** [MicrosoftDocs/azure-devops-docs#11904]
Azure DevOps seems to be configured only to accept SSH-RSA keys, which are now deprecated. Are there plans to incorporate support for stronger key types, such as SSH-ED25519, ECDSA, etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fde585e-edbd-c738-4d34-b1dfca1ef033
* Version Independent ID: 974698f8-cb53-24d4-f75f-a88c16f8e51c
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@alansill - You should check with the [dev community](https://developercommunity.visualstudio.com/search?space=21) about this one. Also, you can enter a feature request there.
