### ISSUE TITLE
Example agent work directory looks wrong

### ISSUE THREAD

**Issue by sgtnuggets** [MicrosoftDocs/azure-devops-docs#11910]
This page has multiple instances where an example path is displayed as 'c:\agent_work' but to me it seems like it should be 'c:\agent\\_work'. Am I crazy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sgtnuggets The path can depend on your user agent. For example, it can also be `/home/vsts/work` for some agents. `agent_work` is a placeholder.
