### ISSUE TITLE
Npm task argument is wrong

### ISSUE THREAD

**Issue by kitzin** [MicrosoftDocs/azure-devops-docs#11918]
In the [npm](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/npm.md) ([in docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops)) documentation it describes the argument `customRegistries` which should be `customRegistry` as shown in the  `YAML snippet` section.

I'm only using it as a custom command so I can't speak for the other use cases but I assume it's also wrong there.

The `customFeed` argument should probably also be described when `customRegistry` is set to `useFeed`. I discovered it need to use the format `project/feed` when the artifact feed is scoped to your project.

**Comment by ramiMSFT** [comment]
@kitzin Thanks for your feedback! I'm updating the task shortly.
