### ISSUE TITLE
Will the 'Extract Files' DevOps task create the folder automatically?

### ISSUE THREAD

**Issue by PedroC88** [MicrosoftDocs/azure-devops-docs#11911]
Will the task create the folder if it doesn't exist? Or error out? Although this is something I can easily find out, its faster for others to just read it here rather than also repeating the test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b39f83-67e9-bf24-a3c6-1352db22fb38
* Version Independent ID: c3837e1d-e5ea-e8b0-b0fe-54b5f07e10b0
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@PedroC88 Thanks for your suggestion.
