### ISSUE TITLE
Docs don't show PublishCodeCoverageResults@2 task version

### ISSUE THREAD

**Issue by tillig** [MicrosoftDocs/azure-devops-docs#11913]
There is [a bug in the PublishCodeCoverageResults@1 task](https://github.com/microsoft/azure-pipelines-tasks/issues/12634#issuecomment-1024959466) where it incorrectly handles zero line coverage. It appears there's a V2 of the task that may not have the issue but the docs only show the @1 version of the task. Why don't the docs show the @2 version of the task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff16109-cc76-cea4-d41b-3fc9c4e9c534
* Version Independent ID: efd08832-ddbc-921a-f682-3ea68ecd27c3
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by steved0x** [comment]
@tillig I see that task in the open source tasks repo but it does not appear to have ever been released. The v2 task isn't available for use, or it would be in our new task reference which is located here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

The new task reference is autogenerated from the task source and metadata that are published to Azure DevOps Services (and the on-premises versions).

You can file an issue on the open source repo for tasks to see if they plan to release this task, but I think it has been stalled for quite some time. https://github.com/microsoft/azure-pipelines-tasks
