### ISSUE TITLE
How to create and manage azure pipeline environments from the cli

### ISSUE THREAD

**Issue by tl24** [MicrosoftDocs/azure-devops-docs#11921]
Is there a way to create and manage the environments for pipelines from the az cli?  It would be great to show examples or link to that.  I would also like to know how to set the security on them as well as add approvals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@tl24 Just to get a little more info, does this page cover some of what you'd like to know about: 

https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/manage-pipelines-with-azure-cli?view=azure-devops

Here's the CLI reference section, in case that helps:

https://docs.microsoft.com/en-us/cli/azure/azure-cli-reference-for-devops?view=azure-cli-latest

**Comment by tl24** [comment]
Unfortunately, no.  I'm looking for a way to create and manage deployment environments for a pipeline.
I believe this is the api endpoint that allows you to do so, I couldn't find any relevant commands for the cli
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments?view=azure-devops-rest-6.0

**Comment by TimShererWithAquent** [comment]
@tl24 - While we look into possible clarifications for the article, you might want to ask a product question [in the dev community here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by juliakm** [comment]
@tl24 I've checked with the product team and it doesn't sound like there is az cli support yet for managing environments. Here's documentation on [adding environments with the Rest API](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/add?view=azure-devops-rest-6.0).
