### ISSUE TITLE
Improvement for this documentation

### ISSUE THREAD

**Issue by joffreynurit** [MicrosoftDocs/azure-devops-docs#11929]
Hi,

I use your documentation to make a migration between to tenant, and that was useful !

But I have two suggestions :
- Maybe you can add a link for rename a project (https://docs.microsoft.com/en-us/azure/devops/organizations/projects/rename-project?view=azure-devops#rename-a-project). In fact, after a migration, peoples change organization name.
- If we use On premise Azure DevOps agent, and we made a migration and rename BEFORE agent reviews, it's a real problem. Cause an agent need to connect to the OLD tenant before remove. We can't remove an agent without that. So it's impossible... A warning can be useful, to delete agent before migration and / or rename.

I hope this can help peoples.

Have a nice day !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @joffreynurit, thanks so much for this info to help others! I'll add to the article and once it's live, this issue will automatically close. Thanks again!
