### ISSUE TITLE
Release notes no longer working

### ISSUE THREAD

**Issue by smholvoet** [MicrosoftDocs/azure-devops-docs#11937]
Hi 👋

It seems like the release notes, which used to be [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/index) are currently broken? Results in a `404 - Content Not Found`:

![image](https://user-images.githubusercontent.com/13507392/152356672-ff36a5ff-99ef-4bd5-abd3-c70b2425828d.png)

**Comment by steved0x** [comment]
I believe this is them:

https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline

I will look into the history and see if there was something else that used to be the index and see if I can figure out what may have happened.

**Comment by steved0x** [comment]
I did a sweep for outbound links to release-notes/index and also added a redirect, so that link should start working again very shortly. Do you recall where the link came fro, and I will see if I can get that updated. Thank you.

**Comment by smholvoet** [comment]
@steved0x The index page is one of my bookmarks so that's how I noticed it, but iirc I also had this issue when I clicked on the "What's new in Azure DevOps" link [here](https://docs.microsoft.com/en-us/azure/devops/?view=azure-devops).

Everything seems to be working fine now, thanks 👍
