### ISSUE TITLE
Broken link - How-much-do-parallel-jobs-cost

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/azure-devops-docs#11931]
The **Buy Self-hosted parallel jobs** link under the 'How-much-do-parallel-jobs-cost' section is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=self-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
Not sure what it's supposed to link to.

**Comment by steved0x** [comment]
It should go to here (later down on the same page)

https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=self-hosted#how-do-i-buy-more-parallel-jobs

I'll get that updated. Although starting with Azure DevOps Server 2019 customers don't have to pay for self hosted parallel jobs.
