### ISSUE TITLE
There is no script for Azure DevOps Server 2020

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#11933]
There is no script for Azure DevOps Server 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ce6aa4-6c9d-6deb-94c4-7953e339dede
* Version Independent ID: 4ced0e1c-a0f7-3139-d490-21bb34e24f63
* Content: [Manage Search, indexing - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/manage-search?view=azure-devops-2020&source=docs)
* Content Source: [docs/project/search/manage-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/search/manage-search.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @kripa-2019, Thanks for your feedback. I reported this in the Developer Community here: https://developercommunity.visualstudio.com/t/No-script-to-manage-Search-indexing-for/1690462?space=22&q=2020+search+index&entry=myfeedback

**Comment by chcomley** [comment]
The following link works. 
https://developercommunity.visualstudio.com/t/No-script-to-manage-Search-indexing-for/1692246?space=22&q=script+search+azure+devops+2020&entry=problem

For now, try out the scripts given for [Azure DevOps Server 2019](https://github.com/microsoft/Code-Search).
When there's a documentation update required, we can reopen this issue or create a new one. Thank you.
