### ISSUE TITLE
Several references to "master" branch but think it should be "main" now

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/azure-devops-docs#11943]
Although it's configurable, the default branch for Git repos is now `main`, so I was wondering if the topic is still current.

I first saw the note in [Use other repositories](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&source=docs#use-other-repositories) section speaks of the `master` branch being used by default, then found several other references in this topic to `master` branch.

Edit: Looks like it will be fixed when #11140 is addressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@juliakm I can just fix these for this article, if you want. I don't know if there's a larger project underway to do these updates.

Let me know if you want me to do these.

**Comment by juliakm** [comment]
Thank you @ChadMcCaffery! This will be fixed shortly. We had previously fixed the naming in our repo but I think these snuck in. 

@TimShererWithAquent Sorry for the delay in responding! Feel free to fix these if they happen again. I'm happy to fix them as well. The new automated checks will help us find them as well.
