### ISSUE TITLE
Status badge - something changed?

### ISSUE THREAD

**Issue by kschinspari** [MicrosoftDocs/azure-devops-docs#11947]
"2. On the upper right, select Edit to edit the pipeline build, and then select Options."

I am unable to find anything named "options" here - perhaps something changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad567ab-0513-570b-74dc-a0827815c6a1
* Version Independent ID: 5e549605-cac8-98ea-ac5b-89f4a40a5f3c
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=python%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by srednakun** [comment]
I found the badge section. Step 2 should be modified to say something like....On the upper right, select the 3 dot menu, and then select Status badge

![badge found](https://user-images.githubusercontent.com/13079246/153645981-0b79fbc8-358c-4195-adb3-0b8bd0678bef.png)
.

**Comment by steved0x** [comment]
This has been fixed. Thank you for letting us know.
