### ISSUE TITLE
Description of $(Rev:r) lacks meaning of $(Rev:.r) and its used on this page in most of examples

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#11941]
In $(Rev:r) definition there is no mention of adding dot, just r or rr as parameter.
Whats the meaning of $(Rev:.r) and how does it differs from $(Rev:r)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml&source=docs)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@quasarea Thanks, I'll add more details now. In Azure DevOps `$(Rev:r)` is a special variable format that only works in the Build Number field. When a build is completed, if nothing else in the build number has changed, the `Rev` integer value increments by one.
