### ISSUE TITLE
Remove outdated related extensions

### ISSUE THREAD

**Issue by IvoMerchiers** [MicrosoftDocs/azure-devops-docs#11957]
The  'Related extenstions' sections references to the two following packages that seem to be outdated (and have other support in VsCode now.

- [PyLint Checker](https://marketplace.visualstudio.com/items?itemName=dazfuller.pylint-task) (Darren Fuller)
- [Python Test](https://marketplace.visualstudio.com/items?itemName=dazfuller.pyunittest-task) (Darren Fuller)

I think they should therefore be removed from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545519f0-468e-e8cd-86e7-37f03ae82dc4
* Version Independent ID: d216e8fe-d5d6-f9e6-2115-37d32d03cf76
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thank you @IvoMerchiers! Those will be removed shortly.
