### ISSUE TITLE
Topic needs update for Choose Picture option being disabled.

### ISSUE THREAD

**Issue by BLDarren** [MicrosoftDocs/azure-devops-docs#11951]
As of Feb 2022  all users report that the _usersSettings/about page where the user can see their account profile now has the Choose image option disabled.

This documentation needs to be updated to explain to admins which setting has caused this to happen and how administrators can load an image on the employee's behalf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28a6661-50d4-527e-9727-ab5974da951d
* Version Independent ID: fdac329a-b9b4-77d0-916a-dee6d2576379
* Content: [Set your preferences - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/set-your-preferences.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/set-your-preferences.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by khaledxGo** [comment]
So good
