### ISSUE TITLE
Compare Branches Button is Disabled for the "Set as compare branch" branch

### ISSUE THREAD

**Issue by ermc** [MicrosoftDocs/azure-devops-docs#11963]
In ADO repo `/branches` and `/tags` view, the option to "compare branches" is disabled when you've selected the same branch that is marked as "set as compare branch". See screenshot below for example.

This should instead open the `/branchCompare` page with that branch selected as both sides of the comparison. Then I would be able to change one or the other to suit my need.

![image](https://user-images.githubusercontent.com/13042864/153659084-1c6dcf07-934d-451d-82f5-251a4a87e883.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6054287-f220-36d8-1524-66bb2f1245c3
* Version Independent ID: 033e68d1-8ac2-5ac3-2d56-843d8eb3c9e7
* Content: [Review your repo history - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/review-history?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/review-history.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/review-history.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@ermc Thanks for your suggestion. You should do a feature request - to make sure it gets in front of the right people, please [submit your suggestion here](https://developercommunity.visualstudio.com/search?space=21).
