### ISSUE TITLE
A little confused why user-defined variables are designed into three syntaxes

### ISSUE THREAD

**Issue by oakeswu** [MicrosoftDocs/azure-devops-docs#11967]
hi, in this page , ##
When you define a variable, you can use [different syntaxes (macro, template expression, or runtime)](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax) and what syntax you use will determine where in the pipeline your variable will render.##
i'm a little confused why user-defined variables are designed into three syntaxes，Is this designed to ensure a single responsibility?  for future evolution? i think it's simple and clear if i can always use macro syntax。thx!

**Comment by TimShererWithAquent** [comment]
@oakeswu Thanks for your question. You should reach out to the dev team about this. 
To make sure it gets in front of the right people, please [ask your question here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by oakeswu** [comment]
OK thank you for your reply!

**Comment by oakeswu** [comment]
> 
OK thank you for your reply!

**Comment by oakeswu** [comment]
> @oakeswu Thanks for your question. You should reach out to the dev team about this. To make sure it gets in front of the right people, please [ask your question here](https://developercommunity.visualstudio.com/search?space=21).

OK thank you for your reply!
