### ISSUE TITLE
Steps are only for YAML (no steps for Classic?)

### ISSUE THREAD

**Issue by PJLindsay** [MicrosoftDocs/azure-devops-docs#11964]
These steps are exclusive to the YAML approach - it would be nice to have instructions which can be followed using the "Classic Approach" to Azure DevOps. Is this only possible with the YAML approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Use Azure Key Vault secrets in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@PJLindsay Thanks for your feedback! I'm adding classic pipeline shortly
