### ISSUE TITLE
non-intuitive pipeline trigger behaviour

### ISSUE THREAD

**Issue by benjaminclewis** [MicrosoftDocs/azure-devops-docs#11971]
"Pipeline completion triggers use the [Default branch for manual and scheduled builds](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-default-branch?view=azure-devops) setting to determine which branch's version of a YAML pipeline's branch filters to evaluate when determining whether to run a pipeline as the result of another pipeline completing. By default this setting points to the default branch of the repository."

... this is really annoying and non-intuitive behaviour for pipelines in the same repo.  Is there any way this can be changed to evaluate pipeline yaml from the current branch rather than the default branch?  (especially given that it's the pipeline yaml in the current branch that will actually be run)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml#branch-considerations-for-pipeline-completion-triggers)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@benjaminclewis Thanks for your question. You should checkout the [dev team board](https://developercommunity.visualstudio.com/search?space=21). See if there's any discussion and - if not - enter feature request.
