### ISSUE TITLE
Azure pipeline parameters 

### ISSUE THREAD

**Issue by S-Rahemi** [MicrosoftDocs/azure-devops-docs#11988]
when you define parameters with multiple values it doesn't show drop down as Microsoft docs says but shows the radio button group 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@S-Rahemi What parameter type are you using? For strings, it should show as a drop-down. Can you include a sanitized version of your parameter code please.

**Comment by S-Rahemi** [comment]
Here is my parameter as string:
```
parameters:
- name: buildConfig
  displayName: Build Configuration
  type: string
  values:
    - Release
    - QA
    - Hotfix

```

 and it shows like this:
![image](https://user-images.githubusercontent.com/5569673/155356083-e413c542-275f-4ba5-baa7-c9dc739d2e0c.png)

**Comment by juliakm** [comment]
@S-Rahemi It looks like when there's 3 or fewer options, the values display as radio buttons. When I add a fourth option, I get a drop-down.

**Comment by S-Rahemi** [comment]
Thanks for your comments Julia
Yes Exactly, but here are two things:
1- There should be a way to show drop down for the three items
2- Wrong result screen shot for the code in the Microsoft docs see below link:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script

**Comment by juliakm** [comment]
Thanks for the clarification @S-Rahemi! I'll fix that example shortly. 

For the first item, can you submit a feature request in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? That space is actively monitored by our development team.
