### ISSUE TITLE
User Access level inconsistency 

### ISSUE THREAD

**Issue by dibbdob** [MicrosoftDocs/azure-devops-docs#11980]
The text shown for the Visual Studio Access level reads: Visual Studio **subscription** which is inconsistent to what is shown in ADO which is Visual Studio **Subscriber**

![image](https://user-images.githubusercontent.com/6143665/154271979-2459373c-3db7-4546-a069-73f80a990bba.png)

![image](https://user-images.githubusercontent.com/6143665/154272297-dede21fd-b63a-4454-a203-68027eddbc71.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [About access levels - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE - This one isn't a literal duplicate: MicrosoftDocs/azure-devops-docs/issues/11844

but it looks like they could be addressed together.

**Comment by KathrynEE** [comment]
@dibbdob - Thank you for raising this issue. I'm updating the article and changes should be visible by end of day.
