### ISSUE TITLE
Creator role repeated twice

### ISSUE THREAD

**Issue by simone-porcu** [MicrosoftDocs/azure-devops-docs#11996]
[Under "Role-based namespaces and permissions", Environment section:
**Creator** role is repeated twice in the description.
Below there is a copy of what is currently in Documentation:

Manages permissions to create and manage Environments. By default, the following permissions are assigned:

- **Reader** role (View permissions only) to all members of the Project Valid Users group
- **Creator** role (View, Use, and Create permissions) to all members of the Contributor group
- **Creator** role (View, Use, and Create permissions) to all members of the Project Administrators group
- **Administrator** role (all permissions) to the user who created a specific Environment.

ID: 83d4c2e6-e57d-4d6e-892b-b87222b7ad20]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d00cf58-20bf-036d-fa90-ab652a4553c0
* Version Independent ID: 982b9e56-62b7-673d-7f76-45b6e277d584
* Content: [Namespace reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/namespace-reference?view=azure-devops)
* Content Source: [docs/organizations/security/namespace-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/namespace-reference.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@simone-porcu -- Simone, thank you for your feedback.  It appears to me those roles are described for two separate groups:  Contributor, and Project Administrators.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
