### ISSUE TITLE
YouTube videos don't work in video html tag

### ISSUE THREAD

**Issue by jamescl604** [MicrosoftDocs/azure-devops-docs#11992]
It might be worth mentioning around the example of using  a video html tag that it generally only works with direct video files (i.e. links directly to an MP4 file).   Video urls from YouTube and Stream (and others) won't work with the video tag, you need to use the :::Video markup.   I spent an hour trying to figure out why the example in the doc wouldn't work with urls from YouTube but channel 9 videos would.   These other sites don't offer direct links to their MP4 files, they're always wrapped with html which the video tag doesn't like (this the need to use the iframe and ::Video tag)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @jamescl604. I'll update the article and once it's live, this issue will automatically be closed. Thanks again!
