### ISSUE TITLE
Size Limits on Universal Packages?

### ISSUE THREAD

**Issue by jdavis-prgs** [MicrosoftDocs/azure-devops-docs#11998]
This page mentions that universal packages up to 4 TB can be published to Artifacts, but the "[limits on package sizes](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops)..." page mentions that the limit is 1 TB.     Seems like one page or the other is incorrect.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages with Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jdavis-prgs Thank you for your feedback! Its up to 4 TB. I'll update the article shortly
