### ISSUE TITLE
No specification for what options are available for 'appType'

### ISSUE THREAD

**Issue by PontusMagnusson** [MicrosoftDocs/azure-devops-docs#12001]
When reading the documentation, it is very unclear what options are available for `appType`, since they are not listed. There are some options sprinkled throughout the page, but it would be very helpful if all the options are listed for the properties that have a limited amount of options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by ramiMSFT** [comment]
Investigating

**Comment by ramiMSFT** [comment]
@PontusMagnusson Thank you for your feedback! the updated article will go live shortly

**Comment by PontusMagnusson** [comment]
Thank you for updating! :)

**Comment by jgarplind** [comment]
Hi there! Hope you don't mind me commenting on a closed issue @ramiMSFT. I found this mentioned in another document: https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-devops `appType: 'workflowapp'`.

Could you confirm or deny that `workflowapp` is a valid option, and if it is, update the documentation accordingly?

**Comment by ramiMSFT** [comment]
@jgarplind Thanks for your feedback! `workflow` is not a valid option. Please see the task json below. I'll update the sample shortly.

```JSON
  {
      "name": "appType",
      "type": "pickList",
      "label": "App type",
      "defaultValue": "",
      "required": true,
      "options": {
          "functionApp": "Function App on Windows",
          "functionAppLinux": "Function App on Linux"
      }
  }
```
