### ISSUE TITLE
ci as a command name in npm task

### ISSUE THREAD

**Issue by naoak** [MicrosoftDocs/azure-devops-docs#12000]
[Enter feedback here]

> #command: 'install' # Options: install, publish, custom

I could use `ci` as a command name with no error. Might it be a valid command name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a3df0ae-70ac-af4c-1a65-999a3de5c9d4
* Version Independent ID: 6e72fbc7-7fc9-09d7-8039-a29636417f75
* Content: [npm task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
@naoak Thank you for letting us know. The recommended approach is to use command: custom, and then pass your command to customCommand.

**Comment by naoak** [comment]
@ramiMSFT Thank you for the information. I will follow your recommended approach. By the way, does this mean that we can use ci as a command now, but may not be able to use it in the future?

**Comment by naoak** [comment]
Oh, I see. Thank you for your reply!
