### ISSUE TITLE
No "Image Name" when adding docker task to pipeline stage.

### ISSUE THREAD

**Issue by timhodgson** [MicrosoftDocs/azure-devops-docs#12008]
"Provide an Image Name to your container image, and then select Validate and configure."  - After I add a docker task, there is no option to provide an "image name".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf0e2ac-c706-a08d-c667-ecbd073a8fdb
* Version Independent ID: 2b3a8b16-e689-8cc5-3134-af72f351e08d
* Content: [Build and push Docker images to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
I think it means the docker file which references the image name. Also I think this article may be using an older version of the docker task. Let me see if I can get more details for you.

**Comment by steved0x** [comment]
@timhodgson I am filing a work item on the author of this article to update it with the latest version of the docker task. Here is a link to the docker task documentation which has some examples covering the different uses of the task that may be helpful.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops

**Comment by ramiMSFT** [comment]
@timhodgson Select your Azure subscription and then select Continue
![image](https://user-images.githubusercontent.com/60942540/156262018-a18caf69-6ad3-40f2-bd38-85bcf2ca7dff.png)

Select a container registry and provide an image name as follows
![image](https://user-images.githubusercontent.com/60942540/156262347-df943716-ef32-428d-870b-85d713933deb.png)

I'll add some clarification to the article.
