### ISSUE TITLE
Free Microsoft-hosted parallel jobs can only run for up 60 minutes

### ISSUE THREAD

**Issue by PatrickMessierGoC** [MicrosoftDocs/azure-devops-docs#12004]
We created our Azure DevOps organization almost 2 years ago. We used it since then to host Public Projects code and build them using Microsoft-hosted parallel jobs. Based on our observations, Public Project free tier parallel jobs CANNOT run for more than 60 minutes at a time. This goes against what is stated on this page.

"For Microsoft-hosted parallel jobs, you can get up to 10 free Microsoft-hosted parallel jobs that can run for up to 360 minutes (6 hours) each time for public projects. When you create a new Azure DevOps organization, you are not given this free grant by default."
or further down in the table
"Up to 10 free Microsoft-hosted parallel jobs that can run for up to 360 minutes (6 hours) each time"

Hence, I believe the documentation doesn't reflect the reality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@PatrickMessierGoC -- thank you for your thorough feedback.

@steved0x -- please look into this issue.

cc @juliakm for awareness

**Comment by steved0x** [comment]
@PatrickMessierGoC I will verify the 360 minutes for free tier public project jobs, but there can be a shorter timeout configured on a per-pipeline basis. This is most common on classic pipelines, where the default is 60 minutes. If your pipeline is a classic pipeline, can you verify the timeout in the pipeline?

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts

For a YAML pipeline, there is a per job setting, `timeoutInMinutes`, and according to the article I linked, it defaults to 60 minutes (I didn't know that). If your pipeline is a YAML pipeline, could you try raising that to 360 (or set to 0 for max timeout). Let me verify that, and I will make an update in the docs to call that out, as I have seen folks with a classic pipeline get caught by the 60 minute default, but I didn't know it was also for YAML pipelines.

**Comment by PatrickMessierGoC** [comment]
@steved0x We used YAML pipelines. I wasn't aware of the default value for the `timeoutInMinutes` parameter. I will test it and report when done. Stay tuned...

**Comment by PatrickMessierGoC** [comment]
@steved0x Successfully tested with `timeoutInMinutes: 0`. The YAML pipeline can now run beyond 60 minutes. That being said, I would recommand adding a note/link to the documentation to clarify this point.
Thanks for your quick replies.

**Comment by steved0x** [comment]
@PatrickMessierGoC I am reopening this issue until I can make an update to the docs to clarify this issue. Thanks for getting back so quickly!

Steve

**Comment by steved0x** [comment]
AB#1924531
