### ISSUE TITLE
"Save" button greyed out, does not "activate".

### ISSUE THREAD

**Issue by gabemihu** [MicrosoftDocs/azure-devops-docs#12015]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a7de30-26a7-c7ac-2d62-620522bb2f64
* Version Independent ID: 35d7c5ce-6ebb-19ff-55e0-fd1fe385f462
* Content: [Rename a project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/rename-project?view=azure-devops)
* Content Source: [docs/organizations/projects/rename-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/projects/rename-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@gabemihu -- thank you for your feedback.  Are you following [these steps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/rename-project?view=azure-devops#rename-a-project)?  I think you'll need to change at least one character in the existing name, to have the Save button become enabled.
