### ISSUE TITLE
Receiving same-category error yet parent/child links are not in the same category

### ISSUE THREAD

**Issue by will-kr** [MicrosoftDocs/azure-devops-docs#12012]
I have user stories with parent links to Features, they exist on separate backlog levels (categories) I am still receiving the error that I cannot reorder the story backlog because the parent links are in the same category, yet they are not. How can I resolve this while still maintaining the parent/child relationship between stories and features? I prefer not to change the link type to related. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0f3ea-b59f-1f67-b0be-dfb773aafab0
* Version Independent ID: d5c25240-899d-e9b7-c4f5-1f157bcaa515
* Content: [Resolve Azure Boards nest, display, and reorder issues for work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/resolve-backlog-reorder-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/resolve-backlog-reorder-issues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/resolve-backlog-reorder-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@will-kr - If you've followed the information in the article, then I recommend you file an issue with the product team on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=problem).
