### ISSUE TITLE
Method of exporting yaml has changed

### ISSUE THREAD

**Issue by bennettnw2** [MicrosoftDocs/azure-devops-docs#12018]
I was just going through this tutorial and I had to download my yaml a different way. I had to edit the pipeline and then I was able to find the option to export the yaml.

I took a screenshot but I am not able to paste a picture here. But the option is called "Download full YAML". It is located under the three vertical dots on the pipeline edit screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36333c89-6223-73cb-ce45-6fbb2638722e
* Version Independent ID: 286b8f96-6374-fedd-8d8d-a37fa5e1948e
* Content: [Migrate from Classic to YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/migrate/from-classic-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/migrate/from-classic-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-migrate**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @bennettnw2! I'll update the screenshots.
