### ISSUE TITLE
Add details for collapsible section markup

### ISSUE THREAD

**Issue by msheets1** [MicrosoftDocs/azure-devops-docs#12016]
[Enter feedback here]

Super helpful tool that we don't cover here. Example coverage: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@msheets1 -- thank you for your suggestion.

@chcomley -- is this functionality available in our existing toolset?  If so, please consider adding it to the documentation.

**Comment by chcomley** [comment]
Hi @msheets1, Thanks so much for this! I've tested the functionality and added it to the article. Once it's live, this issue will automatically close. Thanks again!
