### ISSUE TITLE
No explanation on lists deeper than 2 layers

### ISSUE THREAD

**Issue by msheets1** [MicrosoftDocs/azure-devops-docs#12025]
[Enter feedback here]

Nested lists only shows how to nest ordered and unordered lists, not how to further nest within a given list type (e.g. two levels of unordered lists nested).

Good example: https://riptutorial.com/markdown/example/2219/nested-lists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @msheets1! I've made an update to the example, adding a nested nested list. :)
In the future if you find an article in need of an update, please consider becoming a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! Thanks again!
