### ISSUE TITLE
Issue with Group Assignment documentation

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/azure-devops-docs#12023]
There is an issue on this page's documentation that if you do group assignment for basic, even if the "default access level for new users" is set to Stakeholder, Basic will only appear for new users added to projects. The docuentation should have a note that if you set a group rule, it overwrites a lower "default access level for new users" setting with the lowest group rule.

**Scenario**-

1. Org Settings "default access level for new users" set to "stakeholder"
2. Group Rule created for Basic and Basic+ test plan users
3. Adding a new user to a project should default to "stakeholder" since that was set as default, but the group rule sets that user to "Basic" since unlimited licenses can be purchased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6fa5bb-ed52-b765-c7a2-70307dbc5afa
* Version Independent ID: 86f17782-98c7-ab62-0b00-d991be8c41bf
* Content: [Manage paid user access in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops)
* Content Source: [docs/organizations/billing/buy-basic-access-add-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/buy-basic-access-add-users.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @eschrader, Thanks for your feedback. I'll get back to you sometime next week on this.

**Comment by chcomley** [comment]
Hi @eschrader, I've added a note to the article, which will go live momentarily. Once it's live, this issue automatically gets closed. Thanks again for your feedback!
