### ISSUE TITLE
Exclude bin folder from lock file cache key item

### ISSUE THREAD

**Issue by cmeeren** [MicrosoftDocs/azure-devops-docs#12035]
I'm fairly certain that a previous version of the document included `,!**/bin/**` in the cache key, like so:

```yaml
key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
```

The current version does not have it:

```yaml
key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
```

The result is that in the post-job cache step, an additional `packages.lock.json` in the `bin` folder is picked up, the cache key is then different, and a build warning is emitted.

I think that `,!**/bin/**` should be added back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Bundled with #12037.

**Comment by cmeeren** [comment]
Please read again. #12037 was a question, but this issue requests a change in to what seems to me like incorrect documentation. Please either re-open or explain why this change to the docs is not needed.

**Comment by cmeeren** [comment]
Please read again. #12037 was a question, but this issue requests a change in to what seems to me like incorrect documentation. Please either re-open or explain why this change to the docs is not needed.
