### ISSUE TITLE
Remove condition from restore step

### ISSUE THREAD

**Issue by cmeeren** [MicrosoftDocs/azure-devops-docs#12036]
The guidelines contains this in the restore step:

```yaml
condition: ne(variables.CACHE_RESTORED, true)
```

With this, my build fails. This seems to make sense; even if you restore the packages, the aren't restored in the actual projects, so the restore step still needs to happen.

I therefore suggest removing this, as well as the `cacheHitVar: 'CACHE_RESTORED'` line which is then unused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Bundled with #12037.

**Comment by cmeeren** [comment]
Please read again. #12037 was a question, but this issue requests a change in to what seems to me like incorrect documentation. Please either re-open or explain why this change to the docs is not needed.
