### ISSUE TITLE
Add nuget.config to Cache task's cache key

### ISSUE THREAD

**Issue by cmeeren** [MicrosoftDocs/azure-devops-docs#12034]
I propose that the guidelines should instruct to add `nuget.config` to the cache key.

In other words, replace

```yaml
key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
```

with 

```yaml
key: 'nuget | "$(Agent.OS)" | **/packages.lock.json | nuget.config'
```

in the document. (At least I assume that would work, even if nuget.config is not present.)

A note should also be added about the inclusion of `nuget.config`. (For example, saying why it's there, that it can be removed if you don't use a nuget.config, and that it should be changed if the nuget.config is not at the repo root.)

The reason for the inclusion is that the NuGet config may impact how packages are resolved, e.g. which feeds they are installed from. For example, a private feed may override packages from a public feed.

I may be wrong; if so, please let me know why this is not a good idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Bundled with #12037.

**Comment by cmeeren** [comment]
Please read again. #12037 was a question, but this issue requests a change in to what seems to me like incorrect documentation. Please either re-open or explain why this change to the docs is not needed.
