### ISSUE TITLE
Following docs results in indefinitely growing cache

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/azure-devops-docs#12044]
The docs show using restoreKeys to allow partial matches, and then running nuget restore if it wasn't a complete match.

However, doing a restore in an existing directory results in more things being added to the directory, but nothing ever being removed (at least when using packages.config with a lock file, but likely any restore case).

Please confirm, but if so, I believe the docs should be updated to do one of two things:
1. Do not use restoreKeys, so it only restores with an exact cache hit.
2. If it's a partial cache hit, do a "prune" to remove any old packages no longer in use. (I don't believe such a command currently exists though.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@davidmatson Thank you for your feedback! Are you still experiencing this issue?
+@omokoh

**Comment by davidmatson** [comment]
@ramiMSFT - I think we may be misunderstanding one another. Given the way caching is designed, I don't think it's technically possible for the code in the docs to work correctly, without an indefinitely growing cache. Can you clarify what issue is resolved: the docs have been fixed? Or the product has been changed so that the same docs code doesn't grow the cache indefinitely? (I don't think the latter is technically possible.)

**Comment by ramiMSFT** [comment]
@davidmatson Thanks for the clarification. Your feedback actually coincided with the team pushing a fix to an issue with the cache size. I'm taking a look at the sample

**Comment by ramiMSFT** [comment]
Thanks for your feedback! I'm updating the YAML shortly
