### ISSUE TITLE
Consider removing Azure DevOps Wiki YAML tags

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/azure-devops-docs#12043]
[Enter feedback here]
Consider removing [YAML tags](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#yaml-tags) feature and documentation. It is apparently incomplete and unusable. See [Azure DevOps Wiki: What is the value of YAML atop a page's markdown?](https://stackoverflow.com/questions/66791439/azure-devops-wiki-what-is-the-value-of-yaml-atop-a-pages-markdown).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#yaml-tags)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ScottWelker, thanks so much for your feedback. I've removed the section from the article, as it's clear that the feature isn't complete. When my update goes live, this issue will automatically close. Thanks again.
