### ISSUE TITLE
Missing Details for the Resource Group and Server Name FQDN

### ISSUE THREAD

**Issue by kalalvishal** [MicrosoftDocs/azure-devops-docs#12054]
[Enter feedback here]

In the yaml section, to run the script to add and remove the ip from sql firewall, resourcegroup argument is required.

Also, to run sqlcmd, it requires sqlfqdn example servername.database.windows.net which can be passed as a additional variable. SQL Server name is required for the ps script hence I suggested to have an additional variable for sql fqdn.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@kalalvishal -- Vishal, thank you for your feedback.

@juliakm, @steved0x -- Julia, Steve, the author Atul is unassignable.  Please look into this issue.

**Comment by kalalvishal** [comment]
This should be ideal modification:

variables:
  AzureSubscription: '<Azure service connection>'
  ServerName: '<Database server name>'
  ServerFqdn: '<Database server fqdn example: server1.database.windows.net>'
  DatabaseName: '<Database name>'
  AdminUser: '<SQL user name>'
  AdminPassword: '<SQL user password>'
  SQLFile: '<Location of SQL file in $(Build.SourcesDirectory)>'

steps:
- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '-ServerName $(ServerName) -ResourceGroup $(ResourceGroupName)'
    azurePowerShellVersion: LatestVersion

- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    arguments: '-S $(ServerFqdn) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'

- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\RemoveAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName) -ResourceGroup $(ResourceGroupName)'
    azurePowerShellVersion: LatestVersion

Also resource group parameter "$ResourceGroupName" in all Classic PS script, should be changed to "$ResourceGroup" else the yaml pipeline task "AzurePowerShell@2" to add and remove firewall rule will fail as resource group parameter in both ARM and Classic are different.

**Comment by juliakm** [comment]
Thanks @kalalvishal! We'll take a look at updating the script.

**Comment by juliakm** [comment]
Updates will go out in the next day.
