### ISSUE TITLE
typo in 'Create the build task' code snippet

### ISSUE THREAD

**Issue by peterwie** [MicrosoftDocs/azure-devops-docs#12065]
The code snippet under Create the build task (https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops#create-the-build-task) has a typo.  I'm not sure if it's just a cosmetic issue, or if it impacts how the sample would run.

```
  "dataSourceBindings": [
    {
      "target": "project",
      "endpointId": "$(FabrikamService)",
      "dataSourceName": "Fabfrikam Projects"
    }
```

the `dataSourceName` should probably be "Fabrikam Projects", not "Fabfrickam Projects" (extra f)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Create service endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for this @peterwie, it also has an extra "F"! This issue will automatically close when my PR completes. Thanks again! If you're interested,[ consider becoming a contributor](https://docs.microsoft.com/en-us/contribute/) to our docs, so you can fix stuff, too! Have a good one.
