### ISSUE TITLE
Reserved keywords confusion

### ISSUE THREAD

**Issue by SergeiDavydov** [MicrosoftDocs/azure-devops-docs#12073]
On the page, there are 2 reserved keywords mentioned that should not be used in the deployment names:

```
Job and stage names cannot contain keywords (example: deployment).
```
and
```
jobs:
- deployment: string   # name of the deployment job, A-Z, a-z, 0-9, and underscore. The word "deploy" is a keyword and is unsupported as the deployment name.
```

At the same time word "deploy" is being used in the multiple examples provided on the page:
```
jobs:
- deployment: deploy
```
or
```
jobs:
- deployment: DeployWeb
```
and etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#use-pipeline-decorators-to-inject-steps-automatically)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @SergeiDavydov. That's a great point. Updating the examples now.
