### ISSUE TITLE
error in code sample

### ISSUE THREAD

**Issue by canufrank** [MicrosoftDocs/azure-devops-docs#12077]
section #create-a-new-branch
tab git-command-line
https://docs.microsoft.com/en-us/azure/devops/repos/git/create-branch?view=azure-devops&tabs=git-command-line#create-a-new-branch

`git checkout -b <existing branch name>`
should read
`git checkout -b <new branch name>`
as an existing branch name is a fatal error with the -b option
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779950e4-8595-2a9d-e46a-3853f74781f4
* Version Independent ID: 76a47784-0ff1-0759-c64a-0bfc574d8f44
* Content: [Create a new Git branch from the web - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-branch?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/create-branch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/create-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@canufrank -- thank you for catching this.  I am updating the article.
