### ISSUE TITLE
Broken sample in Pattern for use

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/azure-devops-docs#12084]
The first sample under Pattern for use no longer works; VssClientCredentialStorage no longer has a constructor that takes no parameters:
```c#
using Microsoft.VisualStudio.Services.Common;
using Microsoft.VisualStudio.Services.Client;
using Microsoft.TeamFoundation.SourceControl.WebApi;
using Microsoft.VisualStudio.Services.WebApi;

const String c_collectionUri = "https://dev.azure.com/fabrikam";
const String c_projectName = "MyGreatProject";
const String c_repoName = "MyRepo";

// Interactively ask the user for credentials, caching them so the user isn't constantly prompted
VssCredentials creds = new VssClientCredentials();
creds.Storage = new VssClientCredentialStorage();

// Connect to Azure DevOps Services
VssConnection connection = new VssConnection(new Uri(c_collectionUri), creds);

// Get a GitHttpClient to talk to the Git endpoints
using (GitHttpClient gitClient = connection.GetClient<GitHttpClient>())
{
    // Get data about a specific repository
    var repo = gitClient.GetRepositoryAsync(c_projectName, c_repoName).Result;
}
```

Compiler output:

    error CS7036: There is no argument given that corresponds to the required formal parameter 'storageKind' of 'VssClientCredentialStorage.VssClientCredentialStorage(string, VssTokenStorage)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by davidmatson** [comment]
Using the following packages/versions:
Microsoft.VisualStudio.Services.Client version 16.170.0
Microsoft.VisualStudio.Services.InteractiveClient version 16.170.0
(didn't try the package needed for GitRepository; skipped that part in local testing)

**Comment by chcomley** [comment]
Hi @davidmatson, I'm sorry for the delay on this issue, however I've looked at the current article and it appears that the first sample under Pattern for use has been updated and no longer contains VssClientCredentialStorage. I hope this is working for you. I'm closing this issue out, but please feel free to @mention me with any questions or concerns. Thanks!
