### ISSUE TITLE
Example is confusing and not helpful.

### ISSUE THREAD

**Issue by v-kentro** [MicrosoftDocs/azure-devops-docs#12086]
In the section "Use a template parameter as part of a condition", the example of passing a parameter to a template explains nothing, because both the parameter declarations are identical. If the intent was to inform, then a different parameter value should have been used so that it was clear which parameter declaration took effect and which did not.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @v-kentro. We have more detailed parameter examples in the [Templates article](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-templatecontext-to-pass-properties-to-templates) and I've added a link.
