### ISSUE TITLE
Ability to archive old sprints/iterations

### ISSUE THREAD

**Issue by PJLindsay** [MicrosoftDocs/azure-devops-docs#12081]
I cannot find any information related to archiving older sprints (for example if we are in 2022, I would like to 'hide' or 'archive' the older iterations from 2021 so that they do not appear in the drop-down lists) - to clean up the iterations/sprints that are visible/selectable when I am navigating from one iteration/sprint to another with the drop down list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths and assign to a team - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PJLindsay - Thank you for your inquiry. Some guidance on archiving sprints is provided in this section: [Archive iteration paths](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#archive-iteration-paths).  Let me know if you need more information than what is provided.

**Comment by PJLindsay** [comment]
thank you for quick follow up! It is really appreciated
