### ISSUE TITLE
Error in days of work items kept in board for closed/done

### ISSUE THREAD

**Issue by jose-bueno-microsoft** [MicrosoftDocs/azure-devops-docs#12090]
There is a comment that reads that the work items set to state closed/done stop appearing after a year. This is true for DevOps Server/TFS but not in DevOps Services. The behavior was changed to keep work items to 183 days in this pull request:

https://dev.azure.com/mseng/_git/AzureDevOps/pullrequest/251543

Please update doc accordingly.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd97771-b2cf-b722-99c6-c33ca064423c
* Version Independent ID: 9ff61b2f-db48-999e-c6be-6eadad9939e9
* Content: [Backlogs, boards, workflow states, and state categories in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process#state-categories)
* Content Source: [docs/boards/work-items/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/workflow-and-state-categories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jose-bueno-microsoft - Thank you for the feedback. I've updated the content to reflect the change and the changes should be live by EOD tomorrow.
