### ISSUE TITLE
Reference of "team room" feature, which is not available on the serivce anymore

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#12091]
> Why doesn't the team room show offline users?
>
> The team room shows Azure AD group members, but only when they're online.

The "Team room" feature was deprecated a long time ago and is not available on the service anymore.

▶ Let's remove this reference (at least from the service docs).

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eedc21a-4626-6f86-6972-c719a67848be
* Version Independent ID: 50e6989d-0cdf-fa10-dcbc-54afddcbef21
* Content: [Access via Azure AD FAQs](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-azure-access?view=azure-devops&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/organizations/accounts/faq-azure-access.yml](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/faq-azure-access.yml)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Good call, @NenoLoje. Thanks for the feedback. This issue will close once my PR is live. Thanks!

**Comment by chcomley** [comment]
FYI, we're sweeping our entire docset for other references to team rooms, along with other out-of-date content. This work will be completed within the next sprint. Thanks again!
