### ISSUE TITLE
´YAML is not yet supported in TFS.´ seems incorrect

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#12097]
The following shows when filter is Azure DevOps Server 2019 (or 2020) and seems incorrect/not up-tp-date:

> "YAML is not yet supported in TFS."

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?tabs=yaml&view=azure-devops-2020&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @NenoLoje. I think we've removed all of this wording.
