### ISSUE TITLE
Duplicate Internal Namespace Ids

### ISSUE THREAD

**Issue by sckissel** [MicrosoftDocs/azure-devops-docs#12108]
[Enter feedback here]
It looks like both Internal Namespaces of AccountAdminSecurity and BlobStorageBlobPrivileges have the same ID of '11238e09-49f2-40c7-94d0-8f0307204ce4', but the permissions are slightly different. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d00cf58-20bf-036d-fa90-ab652a4553c0
* Version Independent ID: 982b9e56-62b7-673d-7f76-45b6e277d584
* Content: [Namespace reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/namespace-reference?view=azure-devops&source=docs)
* Content Source: [docs/organizations/security/namespace-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/namespace-reference.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sckissel - Thank you for the feedback. I'm not sure this is a problem as the BlobStorageBlobPrivileges namespace isn't used by Azure DevOps. However, if you consider it a problem, could you raise this issue on our {Developer Communicty page](https://developercommunity.visualstudio.com/report?space=21&entry=problem).

**Comment by KathrynEE** [comment]
@sckissel - My apologies, I need to investigate this further. I'm reopening the issue.

**Comment by KathrynEE** [comment]
@sckissel - I've corrected the ID for the BlobStoreBlobPriveleges to ` 72E679C6-6073-4C9F-9693-548476B7C02E`. Thank you for bringing this to our attention.

**Comment by sckissel** [comment]
My mistake for calling it BlobStorage rather than BlobStore, but thank you for reopening and resolving! :)
