### ISSUE TITLE
Need a list of accepted build source type

### ISSUE THREAD

**Issue by junyin-ms** [MicrosoftDocs/azure-devops-docs#12107]
If you have an external CI build system that produces artifacts, you can consume artifacts with a builds resource. A builds resource can be any external CI systems like Jenkins, TeamCity, CircleCI, and so on.

resources:        # types: pipelines | builds | repositories | containers | packages
  builds:
  - build: string   # identifier for the build resource
    type: string   # the type of your build service like Jenkins, circleCI etc.

The documentation does not give a list of accepted types. For example, if I want to add a build resource for an external TFS build or an external Azure DevOps organization build, I do not know which value to put into the "type" field. This forces a user to guess and so far I do not know the accept the value or whether "external TFS build" is even accepted.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Define YAML resources for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by khaledxGo** [comment]
https://youtube.com/user/keko20101000

**Comment by juliakm** [comment]
@junyin-ms I believe that you can introduce new build types. Our YAML doc states that `You can write an extension to consume artifacts from your builds service and introduce a new type of service as part of builds` ([reference](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-builds-resource)). I'll add a link to this page.
