### ISSUE TITLE
Images on Clasic are not rendered

### ISSUE THREAD

**Issue by mgrigore** [MicrosoftDocs/azure-devops-docs#12103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26225103-344e-6ce2-e4bc-b400c07beff8
* Version Independent ID: 36784662-72a3-543f-9daa-9bad51b19843
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for letting us know, we are removing the broken image syntax.
