### ISSUE TITLE
Missing a piece in the 'Set an output variable in a future job' section.

### ISSUE THREAD

**Issue by robkendrick** [MicrosoftDocs/azure-devops-docs#12119]
This variable declaration:
```
    myVarFromJobA: $[ dependencies.A.outputs['passOutput.myOutputVar'] ]  
```

...is incorrect and will not parse, because the job name is missing in the actual variable name. This will work properly:
```
    myVarFromJobA: $[ dependencies.A.outputs['A.passOutput.myOutputVar'] ]  
```

Note the `A.` before `passOutput.myOutputVar`.

Please update.
Many thanks,
Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ad0d9b-2e51-de2e-a529-6cbe55692023
* Version Independent ID: 609b6196-cc6b-677a-c76f-f82bb7cce10a
* Content: [Set variables in scripts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/process/set-variables-scripts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/set-variables-scripts.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by robkendrick** [comment]
Update: This seems to be the case only when passing output variables from `deployment` jobs, not regular jobs.

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review this update in [private PR 4628](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4628.
