### ISSUE TITLE
runOnce strategy output variables do not use lifecycle-hookname, but the deployment job name

### ISSUE THREAD

**Issue by junyin-ms** [MicrosoftDocs/azure-devops-docs#12117]
This section of the documentation is incorrect or unclear:

For runOnce strategy: $[dependencies.<job-name>.outputs['**<lifecycle-hookname>**.<step-name>.<variable-name>']] (for example, $[dependencies.JobA.outputs['**Deploy**.StepA.VariableA']])
For runOnce strategy plus a resourceType: $[dependencies.<job-name>.outputs['**<lifecycle-hookname>**_<resource-name>.<step-name>.<variable-name>']]. (for example, $[dependencies.JobA.outputs['**Deploy**_VM1.StepA.VariableA']])

It should use the deployment job name instead of lifecycle-hookname, which is correctly mentioned in the documentation below.

For a runOnce job, specify the name of the job instead of the lifecycle hook:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks, I'll update that reference.
