### ISSUE TITLE
Release burndown issue

### ISSUE THREAD

**Issue by devamchakrabarty** [MicrosoftDocs/azure-devops-docs#12118]
In our ADO dashboard burndown widget I cannot view `Release` in the dropdown as shown in point 4 [(this image)](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/media/burndown-widget/burndownup-config-select-multiple-field-criteria.png?view=azure-devops) of this [page](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops#choose-the-teams-and-work-items-to-chart). 

Can you tell me what might be the possible reasons for that option missing? Is this a new feature that might not have been rolled out to all clients? It is worth mentioning that I am the administrator of the ADO project so I should not have any access related issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@devamchakrabarty - The **Release** field shown in the image is a custom field. You can only add custom fields that have been added to your process and project. To learn how to add a custome field, see [Add a custom field to a work item type](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=azure-devops).
