### ISSUE TITLE
Add New Mermaid Diagrams

### ISSUE THREAD

**Issue by JonathonRP** [MicrosoftDocs/azure-devops-docs#12113]
It would be nice to have support for the Entity Relationship diagram and Class diagram from mermaidjs in the projects wiki.

**Comment by WilliamAntonRohm** [comment]
@JonathonRP -- Jonathon, this repo is solely for documentation issues, and this seems product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by GeorgeS2019** [comment]
@JonathonRP @WilliamAntonRohm 

I wonder if this repo needs to open the discussion section so we could discuss something like this ==>

**How to update the Azure Wiki Mermaid by users (ourselves)**

The community here could share experiences how to go into the Azure DevOps server to change the mermaid.js file to the latest version
