### ISSUE TITLE
windows-latest => windows-2022

### ISSUE THREAD

**Issue by EenPOOL** [MicrosoftDocs/azure-devops-docs#12121]
I think that the information about vmImages is not correctly anymore.
Are you sure that "windows-latest" is still "windows-2019"? and not "windows-2022"?

Because our builds are failing with "windows-latest", but with "windows-2019" there are still working

So this part is wrong in the table I think:
windows-latest OR windows-2019

Should be: 
 windows-2019

and for 2022:
windows-latest OR windows-2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@EenPOOL -- Maciej, thank you for your feedback.  This issue is being tracked in #12120.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
