### ISSUE TITLE
Getting to Power BI Connector

### ISSUE THREAD

**Issue by joesessions** [MicrosoftDocs/azure-devops-docs#12129]
I'm studying these pages to use this functionality for the first time, and I feel this is written for someone who is already familiar with Power BI/Power BI Connector. I've been bouncing around in links and not making progress. I just thought I'd suggest to read through this with the perspective of someone who is just coming from Azure DevOps trying to do a custom query for a widget.   
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a534d66-c324-14d0-341a-966f7aec2e99
* Version Independent ID: b77a0e57-7330-45f0-1ba1-cb00b3c338ec
* Content: [What are Analytics views? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/what-are-analytics-views?view=azure-devops)
* Content Source: [docs/report/powerbi/what-are-analytics-views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/powerbi/what-are-analytics-views.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@joesessions - Thank you for your feedback. I've added a work item to improve the content to my backlog. I'll update this issue once that work is complete.

**Comment by KathrynEE** [comment]
Closing this issue as completed. Several articles have been revised and a new Get started section added to the content set.
