### ISSUE TITLE
Windows-Latest now points to windows-2022 not windows-2019

### ISSUE THREAD

**Issue by kjacobsen** [MicrosoftDocs/azure-devops-docs#12120]
Per https://github.com/actions/virtual-environments/issues/4856 

This change will be rolled out over a period of several weeks beginning on January, 17. We plan to complete the migration by March, 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ItzLevvie** [comment]
https://github.com/MicrosoftDocs/azure-devops-docs/pull/12114 fixes it.

**Comment by steved0x** [comment]
This is fixed and live now, thank you!
