### ISSUE TITLE
I cannot locate documentation for "regenerate token" function.

### ISSUE THREAD

**Issue by tomeks666** [MicrosoftDocs/azure-devops-docs#12122]
All I have found is "You can regenerate or extend a PAT, and modify its ". But what happens if i click it? I will get a new PAT string. BUt what will happen with agents already using this PAT? Will they get locked out, just like in case of "Revoke"? I googled a lot but I kept finding "you can regenerate if you forgot", but hard to find what are consequences of "regenerating".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Use personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Duplicate of #12123.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
