### ISSUE TITLE
Guidance to identify the possible IP ranges for Microsoft-hosted agents is inaccurate

### ISSUE THREAD

**Issue by PCNZ** [MicrosoftDocs/azure-devops-docs#12136]
The guidance on this page to grab the IP ranges from the weekly file is not accurate. If the agent is accessing an Azure resource in the same region as it, the agents may come from a private IP address (i.e. 10.x.x.x). Worse these cannot be added to firewalls for some Azure resources.
See issue https://github.com/MicrosoftDocs/azure-docs/issues/19456

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#to-identify-the-possible-ip-ranges-for-microsoft-hosted-agents)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@PCNZ Thank you for linking to that other thread with context, I am reaching out to the product team and will update when I have some guidance to share.

**Comment by adisaljusi** [comment]
Hi @steved0x.

Any updates on this issue? This issue still persists and there's simple way to allow Azure DevOps services. Any ETA on this issue or at least a confirmation if this issue was taken up or it's won't be a priority in the near future?

**Comment by geekzter** [comment]
Hi @adisaljusi, is this related to Azure Storage? Azure Storage can report RFC 1918 addresses when traffic originates in the same Azure region (e.g. as the hosted agent resides), see [docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal#grant-access-from-an-internet-ip-range).

**Comment by alenroki** [comment]
Any news on this? I'm also trying to deploy a Function App where with a storage account that has Firewall enabled and get 403 Forbidden when deploying the Bicep template.

**Comment by edwinvdb** [comment]
@alenroki see https://github.com/MicrosoftDocs/azure-docs/issues/19456 for this.
