### ISSUE TITLE
Wrong information regarding build agent VM windows-latest

### ISSUE THREAD

**Issue by nios87** [MicrosoftDocs/azure-devops-docs#12134]
[Enter feedback here]
Some of our pipelines stopped working. Seems windows-latest actually uses windows-2022 now, not windows-2019 as documentation says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
The documentation is updated to show that window-latest now refers to windows-2022 - it took a little while for the change to roll out to everyone.
