### ISSUE TITLE
Time Delay for AKS and ACR to show up up in dropdowns for Service Connections

### ISSUE THREAD

**Issue by pfgarvey** [MicrosoftDocs/azure-devops-docs#12147]
Is there a delay when trying to create AKS and ACR connections. The resources exist in the subscription, and I am owner of the subscription, but they do not show in the dropdowns. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@pfgarvey Thank you for your feedback! The team is looking into this issue. This is related to the replication of resources across regions. There is a minimal delay between the time you create new resources and the propagation to other regions.
