### ISSUE TITLE
Incorrect image or text

### ISSUE THREAD

**Issue by pkg01** [MicrosoftDocs/azure-devops-docs#12159]
This image does not align with the text provided above this image.
https://docs.microsoft.com/en-us/azure/devops/repos/git/media/pull-request-templates/additional-pull-request-template.png?view=azure-devops
Text says `dev.md` is the default template while image shows `pull_request_template.md` as default template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@pkg01 -- thank you for your close reading.

@vijayma -- please look into this issue.
