### ISSUE TITLE
Agent.MachineName should be Agent.ComputerName

### ISSUE THREAD

**Issue by djc5358** [MicrosoftDocs/azure-devops-docs#12154]
Hi

I have encountered a problem with this variable in one of our pipeline. I wanted to target a specific machine with demanding Agent.MachineName, however I got an error message that there is no eligible agents for this job. 

When I checked the capabilities of the agent I noticed that it has Agent.ComputerName variable instead the Agent.MachineName. 
When I use this in the demand, the job is populated to one of the agent on the machine. 

We have an Azure DevOps Server
Version Dev17.M153.5

Thanks
Zoltan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops-2019&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@djc5358 -- Zoltan, thank you for your feedback.  `Agent.ComputerName` is only used in 2017, and subsequent versions use `Agent.MachineName`.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
