### ISSUE TITLE
The option to Create work item on failure is only supported for Classic pipelines? 

### ISSUE THREAD

**Issue by royaza** [MicrosoftDocs/azure-devops-docs#12153]
Here it says that it is possible to create a work item on failure through YAML file. Instead in [this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/configure-pipelines-work-tracking?view=azure-devops&tabs=yaml#create-work-item-on-build-failure-classic)], it says like this:

**_Tip

The option to Create work item on failure is only supported for Classic pipelines. To accomplish this with a YAML pipeline, see the [Create Bug on Release failure](https://marketplace.visualstudio.com/items?itemName=AmanBedi18.CreateBugTask) marketplace extension._**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2935bf17-5685-5cc5-209f-fce7f4a8aa96
* Version Independent ID: a482912b-1fb4-49b8-59df-544b2719dd8a
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
@royaza Creating a bug or work item on failure isn't natively built into YAML pipelines, but you can implement it yourself using the techniques in the article, or you can use a marketplace extension like the one linked from the other article. I will add a link to that marketplace extension from the customize article, and link to the customize article from the one that you shared. thank you.
