### ISSUE TITLE
Python/Anaconda Windows example path does not work

### ISSUE THREAD

**Issue by michaelmariboe** [MicrosoftDocs/azure-devops-docs#12150]
The path for the cache task in the Windows example for Python/Anaconda does not work as it does not cache in the Post-job: Cache Anaconda step. The incorrect path is "path: $(Pipeline.Workspace)/miniconda/envs". The correct path is "$(CONDA)/envs".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@ramiMSFT -- Rami, please review this change in [private PR 4593](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4593).
