### ISSUE TITLE
ImageOS and ImageVersion predefined variables on Microsoft Hosted Agents

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/azure-devops-docs#12167]
It appears that these variables exist, and would be useful eg. as input to the caching task, but don't seem to be mentioned on this page. Could they be added or is there an alternative?

eg. 
```
ImageOS=win22
ImageVersion=20220316.1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@fowl2 Could you explain how you might use those variables a bit more? We use them internally, which is why they show up in the logs.

**Comment by ramiMSFT** [comment]
Thanks for your feedback! Those variables are only available for hosted agents. I'll add a link to artifacts variables.
