### ISSUE TITLE
Azure Boards connecting to GitHub Enterprise Server

### ISSUE THREAD

**Issue by huntleyh** [MicrosoftDocs/azure-devops-docs#12169]
[Enter feedback here]
The Note on this page (shown below) is ambiguous and confusing:
  _With the Azure Boards app for GitHub, Azure Boards and Azure DevOps Services support integration with GitHub.com and GitHub Enterprise Server repositories. Integration with other Git repositories is not supported._

Please update to ensure it is clear Azure Boards in Azure DevOps _Server_ can connect to GitHub Enterprise Server and not Azure DevOps _Services_
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db555e9d-f86e-be8e-be13-d9d10e1b54d0
* Version Independent ID: 21327f5a-4731-3004-86bf-05954134119e
* Content: [Add or remove GitHub repositories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/add-remove-repositories?view=azure-devops)
* Content Source: [docs/boards/github/add-remove-repositories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/add-remove-repositories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@danhellem - can you confirm the issuer's feedback and I'll update the content per same.
