### ISSUE TITLE
Variable NUGET_PACKAGES set to a different value in separate docs.

### ISSUE THREAD

**Issue by jptissot** [MicrosoftDocs/azure-devops-docs#12164]
On this page, the example states to set the `NUGET_PACKAGES: ''` variable to a blank string. But on this one: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget the example has it as `NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages` 

Which one is recommended.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Caching NuGet packages - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jptissot Thanks for your feedback! This should be the path: $(Pipeline.Workspace)/.nuget/packages. The fix will be published shortly.
