### ISSUE TITLE
page doesn't provide any real example

### ISSUE THREAD

**Issue by mowtschan** [MicrosoftDocs/azure-devops-docs#12160]
The page doesn't provide any real example how to implement `sample consumer service`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758bed7c-374d-996e-ebff-c68528a823ca
* Version Independent ID: 81777b37-38ab-a7df-6eaa-7aa6bcd1058c
* Content: [Create a consumer service for service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-service-hook?view=azure-devops)
* Content Source: [docs/extend/develop/add-service-hook.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-service-hook.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mowtschan, it looks like this article definitely needs an update, thank you for the heads up. Could you please let me know whether the following link helps you?
[Service hook consumers for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/consumers?view=azure-devops)

**Comment by chcomley** [comment]
I'm going to go ahead and close this issue, hoping the link previously provided helps. Feel free to @mention me, if needed. Thank you!
