### ISSUE TITLE
Mac shortcuts?

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#12168]
The page seems to cater for Windows users. Can we add the shortcuts for Mac as well?

Is that simply replacing `ctrl` with `cmd`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c7778d-779f-fd50-e836-19231bcd33f4
* Version Independent ID: e6fca9b3-ebff-f2f6-73b1-92ab0b475f11
* Content: [Keyboard shortcuts for Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/keyboard-shortcuts?WT.mc_id=DOP-MVP-5001511&view=azure-devops&viewFallbackFrom=azure-devops%E2%80%8B%0D%0A%0D%0A%E2%80%8B)
* Content Source: [docs/boards/get-started/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/get-started/keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Closing this issue as completed, {macOS shortcuts](https://learn.microsoft.com/en-us/azure/devops/boards/get-started/keyboard-shortcuts?WT.mc_id=DOP-MVP-5001511&view=azure-devops#macos-shortcuts) section added to the article.
