### ISSUE TITLE
Example for "Copy Files Over SSH" task is not working

### ISSUE THREAD

**Issue by DavidRadoorHummel** [MicrosoftDocs/azure-devops-docs#12172]
The example under "contents" does not work:

```
- Example: **/*.jar \n **/*.war includes all jar and war files (including sub folders) under the source folder.
```
The newline character breaks it, and nothing is matched.

What worked for me was to instead use:

```
**/*.*(jar|war)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71788382-82ac-c878-0768-fb602d9be9df
* Version Independent ID: 6651ef8d-5a5f-2785-e36b-5238fcbdc510
* Content: [Copy Files Over SSH task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/copy-files-over-ssh.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/copy-files-over-ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- Roopesh, please review this update in [private PR 4591](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4591).

**Comment by metu** [comment]
Facing the same issue. Using the exact examples from the documentation doesn't work. Seems like white spaces break the task.

**Comment by metu** [comment]
After going through a lot of trials and errors I'm proud to bring you the solution.......... use double quotes.

e.g.
```
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'DEV'
    contents: "!.git/**\n!.vscode/**\n!api/**"
    targetFolder: '~/some/path'
    readyTimeout: '20000'
```

**Comment by steved0x** [comment]
Fixed
