### ISSUE TITLE
Integration between Azure DevOps Server & GHES

### ISSUE THREAD

**Issue by martedesco** [MicrosoftDocs/azure-devops-docs#12176]
It is unclear for me if the integration can be achieved. It implies an integration between Azure DevOps Server and GitHub Enterprise Server is possible however it does mention the GH app which doesn’t seem to be available on GHES.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de566677-1564-4c64-f6af-7a418d0f0bed
* Version Independent ID: 38729236-f109-be7f-5cf9-e6b2fe941cd8
* Content: [Connect an on-premises project to a GitHub Enterprise Server - Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-on-premises-to-github?view=azure-devops-2020#connect-azure-de%5B%E2%80%A6%5Dnterprise-server)
* Content Source: [docs/boards/github/connect-on-premises-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/connect-on-premises-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by martedesco** [comment]
The title of the article **Connect an on-premises Azure DevOps Server to a GitHub repo** implies it regards integration of ADOS with any GitHub repo. I think it would be great with describe in the beginning that it is possible to integrate with GitHub.com using the GitHub App and with GitHub Enterprise Server using the ADO connector. 

The Prerequisites part mixes both and rarely will the reader have the need to configure that on both - usually it will be one or the other.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/3329307/162212256-b67918e0-0ed2-4f45-b87c-9163a817e11d.png">

**Comment by KathrynEE** [comment]
@danhellem - Can you provide some input to resolve this issue?

**Comment by KathrynEE** [comment]
@chcomley - reach out to Dan for help with this one. This is a difficult one to troubleshoot as you have to have a GitHub Enterprise account to test the steps.

**Comment by chcomley** [comment]
Hi there, since this ticket is over a year old and we haven't received any similar feedback, I believe this to be a non-issue. Closing, but do @mention me if you believe this needs attention, thank you.
