### ISSUE TITLE
TOC missing when viewing multiple pages in the Marketplace & Extensibility section

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/azure-devops-docs#12185]
Some of the pages have the TOC missing when I clicked into the page from the TOC, including the page in the details here. A few more examples:

https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops
And basically everything under the **Service hooks** tree

https://docs.microsoft.com/en-us/azure/devops/extend/develop/contributions-overview?view=azure-devops
And _some but not all_ pages under the **Develop extensions** tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/overview?view=azure-devops)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/service-hooks/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@felixtsem5 -- thank you for your feedback, and apologies for the delayed response.  This TOC is working for me now.
