### ISSUE TITLE
Incorrect maximum number of GitHub repositories to connect (250 vs 50)

### ISSUE THREAD

**Issue by HappyRashair** [MicrosoftDocs/azure-devops-docs#12182]
The page states:
> You can connect up to 250 GitHub repositories to an Azure Boards project.

However, we've recently started receiving following error when trying to connect additional repositories:

```
You have exceeded the maximum number of repositories for creating a connection. 
Please try selecting '50' repositories or less.
```

Did something change recently or the number was incorrect for a while?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect an Azure Boards or Azure DevOps project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops#add-a-github-connection-with-github-credentials)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- Kathryn, please review this change in [private PR 4592](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4592).

**Comment by KathrynEE** [comment]
@WilliamAntonRohm - I've sent an email to the PM to determine what the correct limit is. Please hold off until I get confirmation. 
Thanks, Kathryn.

**Comment by danhellem** [comment]
The limit should be 250. Is it possible you are selected more than 250 but the error message has a bug in it? Or are you selecting 51 and getting the error?

**Comment by HappyRashair** [comment]
No we didn't select more than 250 - we don't have that many in our organisation (116).

**Comment by danhellem** [comment]
@HappyRashair can you post some screen shots? We are not receiving any other reports of this issue. You can also email me directly if that helps. dahellem@microsoft.com.

**Comment by HappyRashair** [comment]
Sorry, but I'll have to close it for now - lots of our GH connections were actually redundant - for now we really need around 20.
 I am unable to investigate it properly given the time and resources I have and, atm., it works without problems.
 I will certainly get back with more info if the issue manifests itself again.
 Sorry for wasting your time.

**Comment by WilliamAntonRohm** [comment]
@HappyRashair -- Przemek, thank you for your follow-up, and no problem!
