### ISSUE TITLE
Incorrect translation to German: "abbreviated syntax" is getting translated to "keyboard shortcut"

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/azure-devops-docs#12198]
The below mentioned section (and I believe this is true for many other MS Docs documents as it's automatically translated), "shortcut" is translated to „Tastenkombinationen“ in German, which is supposedly rather known as "keyboard shortcut" in English.

So, the German translation "The PowerShell task also has two keyboard shortcuts in YAML:" doesn't make sense, particularly for YAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb6bb80-ad9e-525c-3cae-275955b00919
* Version Independent ID: 79d62477-08d2-f412-d59d-d8cbac75dc32
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#yaml-snippet)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@SetTrend -- Axel, thank you for bringing this to our attention.  I've created an [internal localization task](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/605577) for this issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
