### ISSUE TITLE
Using variable created from a step in a future step's condition and script wasn't clear

### ISSUE THREAD

**Issue by crookse** [MicrosoftDocs/azure-devops-docs#12191]
While I was creating Azure Pipelines and using conditions, it wasn't immediately clear how to create a pipeline variable from a step and using that variable in a future step's condition and script. After putting together my knowledge of different parts of the documentation (Conditions, Define variables, and Pipeline run sequence), I was able to find the solution I needed. I feel that the Conditions page should show how to do the following:

- Create the variable in the first step
- Use the variable in the future step condition via `variables.someVariable` or `variables['someVariable']`
- Use the variable in the future step script via `$SOMEVARIABLE`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@crookse -- Eric, thank you for your contribution.
