### ISSUE TITLE
VS Code extension "Deploy to Azure" is deprecated. 

### ISSUE THREAD

**Issue by yhdleung** [MicrosoftDocs/azure-devops-docs#12190]
The VS Code extension "Deploy to Azure" is deprecated and will be removed from VS code marketplace on 11 April 2022.
Please update the docs to show the alternatives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5604b66e-57ea-415a-c76b-54f4f2753ba4
* Version Independent ID: d9a8e5f3-cd00-bc37-2d2d-ea1ffadbd079
* Content: [Deploy to Azure App Service using Visual Studio Code - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/deploy-to-azure-vscode?view=azure-devops)
* Content Source: [docs/pipelines/targets/deploy-to-azure-vscode.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/deploy-to-azure-vscode.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by bishal-pdMSFT** [comment]
@azooinmyluggage shall we remove this page from docs?

**Comment by azooinmyluggage** [comment]
Yes we should

**Comment by ramiMSFT** [comment]
Thank you! Closing this issue now
