### ISSUE TITLE
No Users option for Admin Settings on Azure DevOps 2019

### ISSUE THREAD

**Issue by tjcst25** [MicrosoftDocs/azure-devops-docs#12207]
I don't have a Users section on my Azure DevOps 2019.  I can't export users since this section doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361c08ef-48be-de59-d223-595cadc65a7b
* Version Independent ID: 4bab93d0-8ee5-5e18-a217-c5f6a3eea441
* Content: [Export a list of users and their access levels - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/security/export-users-audit-log.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/export-users-audit-log.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tjcst25 - Please use the Content Version Selector to select the version of content that supports your platform. In this case, the mechanism for exporting users for on-premises server is very different. Use this link: https://docs.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=azure-devops-2019&tabs=browser. 

Content version selector is in the upper-left corner right above the Table of Contents. 

![image](https://user-images.githubusercontent.com/10856840/163028753-16756585-c3e5-4c1f-9e7a-fa9f19eb1a1f.png)
