### ISSUE TITLE
Connect to Analytics View instructions and screen shots are incorrect

### ISSUE THREAD

**Issue by enpeacps** [MicrosoftDocs/azure-devops-docs#12205]
in https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops  the 'Connect to Analytics View' screen shots seem to be connecting to DevOps, not Power BI - wrong screen shots?  Also, instructions say to select Azure DevOps Server.  Certainly for me, this does not work, but selecting Azure DevOps does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea920e3-9644-ae0c-120d-db9e899ee192
* Version Independent ID: 452bf06e-28f4-7815-72b3-16a4c2086e47
* Content: [Connect to Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-connect.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/powerbi/data-connector-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@enpeacps - Thank you for your feedback.  The screenshots are up to date. From Power BI you connect to Azure DevOps (cloud platform) or Azure DevOps Server (on-premises platform) and then choose an Analytics View that you want to use as the basis for your report.  I'll update the article to clarify when you choose what server. If you want to build a report on some other data other than an Analytics view, then you should read [Connect with data by using Power BI and OData queries](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/odataquery-connect?view=azure-devops).
