### ISSUE TITLE
Prerequisite to move a work item to another project missing

### ISSUE THREAD

**Issue by Bliyaal** [MicrosoftDocs/azure-devops-docs#12206]
Hi! 

I was trying to help a co-worker moving work items between project looking at his permissions he seemed to have everything needed including the *Move work items out of this project* permission but it didn't work. Since the audit logs didn't show that kind of error message I had to look elswhere. I finally figured that he needed more than the stakeholder license to do the move. It worked for me (Visual Studio Subscriber) and for him when I set his license to Basic.

I know there's a documentation page listing all the differences between licenses but it should be more clear on a page like this one here when you have a prerequisite section. Even on the access level page it's not entirely clear on this subject.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d7da26-5052-70ad-4b2a-7ccd2f02f012
* Version Independent ID: 7a0b1331-7ac9-9927-b96e-36c6f014391a
* Content: [Move work items and change the work item type in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/move-change-type?view=azure-devops)
* Content Source: [docs/boards/backlogs/move-change-type.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/move-change-type.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[Bliyaal](https://github.com/Bliyaal) - Thank you for your inquiry and feedback. Stakeholders don't have access to the Move work items to another project. I will update the article later today to clarify this restriction.
