### ISSUE TITLE
Incorrect domain listed for IPV4 endpoint

### ISSUE THREAD

**Issue by Nighteyez07** [MicrosoftDocs/azure-devops-docs#12214]
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4#domain-urls-to-allow
within the CommonDomainURLs block there is a domain listed for **https://windows.net**, this endpoint is not valid and the entry should instead be **https://*.windows.net**. Our group found this issue from our server that by default blocks external connections and we were attempting to deploy to an App Service within an ASE that connects to https://login.windows.net/ which wasn't allowed as our firewall team entered the literal value of https://windows.net 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Allowed address lists and network connections - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Nighteyez07, thanks so much for sharing this info. I've updated the article, which will automatically close this issue when it goes live. Thanks again!
