### ISSUE TITLE
Hw mods

### ISSUE THREAD

**Issue by HW-XMTeam** [MicrosoftDocs/azure-devops-docs#12219]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ca6c90-bf2c-6680-a229-8f679090b8d7
* Version Independent ID: a33d56c1-2000-864d-5fa4-028a0a9a2ef1
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#surface-test-results-in-the-tests-tab)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
