### ISSUE TITLE
Authorization issues not addressed

### ISSUE THREAD

**Issue by k3davis** [MicrosoftDocs/azure-devops-docs#12213]
Perhaps there is another document I'm not locating that addresses this issue, but as one of the admins of an Azure DevOps instance and signed into Visual Studio as that same user, I can see the feed items in the web interface but Visual Studio give me a 401 error. This document just generically tells me how to add a Nuget feed but doesn't address auth issues at all. Can you redirect me to the right place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6adfe12-e158-b022-57ee-f627c2a4e076
* Version Independent ID: ff4ae07b-3fd1-b3c0-8601-29b1b636a37a
* Content: [Install NuGet packages with Visual Studio - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/nuget/consume.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@k3davis - You might want to bring this up at the dev community. To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).
