### ISSUE TITLE
Discrepancy in backlog limits

### ISSUE THREAD

**Issue by cccinkc** [MicrosoftDocs/azure-devops-docs#12222]
As seen in the screenshot below, the table says that backlogs are limited to 1,000 work items, and the text below the table says that backlogs are limited to 10,000 work items.

![image](https://user-images.githubusercontent.com/69682749/164083349-e5b57c66-27f3-4310-be25-c55fb9666361.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4956039a-8296-c5e7-107e-9f42f1e39f33
* Version Independent ID: aae5a90e-0fc7-ed33-0936-10e37782d0dc
* Content: [Work tracking, process, and project limits - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops)
* Content Source: [docs/organizations/settings/work/object-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/work/object-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[cccinkc](https://github.com/cccinkc) - Thank you for the feedback.  Apologies for the confusion. I checked with the product team and the limit is 10,000 items. I'll update the article today.
