### ISSUE TITLE
What Service Principal did we create?

### ISSUE THREAD

**Issue by thewellington** [MicrosoftDocs/azure-devops-docs#12228]
[Enter feedback here]
Step 6 under "Configure Key Vault Access Permissions" says to "select to add a service principal and choose the one you created earlier"   The document makes no attempt at telling me what service principal to create.  How do I do that?  Specifically what access levels should this SP have?

The document is incomplete at best.  I mean, you could at least provide a link to the part of the tutorial where we created the SP.    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3744b8f-3cef-ded3-fe36-d1a12e9bce4f
* Version Independent ID: 277401bd-1701-d0db-9d83-9b5d3df27a8b
* Content: [Query and use Azure Key Vault secrets in your Pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/key-vault-in-own-project?view=azure-devops&tabs=portal)
* Content Source: [docs/pipelines/release/key-vault-in-own-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/key-vault-in-own-project.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@thewellington -- thank you for your feedback and questions.  Please see the first paragraph in this section:
- [Configure Key Vault access permissions](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/key-vault-in-own-project?view=azure-devops&tabs=portal#configure-key-vault-access-permissions)

which in turn refers to this how-to article:
- [[Create a service principal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#register-an-application-with-azure-ad-and-create-a-service-principal)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
