### ISSUE TITLE
Restore packages with NuGet restore point number three have a illegible image as reference

### ISSUE THREAD

**Issue by alexis19apl** [MicrosoftDocs/azure-devops-docs#12224]
Restore packages with NuGet restore-->Point number three-->There is an image as reference for the reader but, that image is barely ilegilleble therefore is required to be updated with one that can be properly visualized by the readers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5162e55f-4ab3-ad76-c5ad-300a71e4b733
* Version Independent ID: b22a98c8-57a7-258a-0941-70fabbca2ac2
* Content: [Restore NuGet packages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/packages/nuget-restore.md)
* Product: **devops**
* Technology: **devops-cicd-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@alexis19apl -- thank you for your feedback, and that image could be hard to read.  Please try right-clicking on the image and then `Open in new tab` to see it larger.

You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
