### ISSUE TITLE
ACR Push Trigger Required Managed Identity / Service Connection Permissions

### ISSUE THREAD

**Issue by chrihala** [MicrosoftDocs/azure-devops-docs#12233]
The [section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-containers-resource) about defining container resources which automatically triggers a pipeline on push to Azure Container Registry does not make any mention of the permissions needed for the automatic trigger to work. 

A mention of the mechanisms behind the automatic trigger (Webhook on the ACR resource, created by the Managed Identity backing the ARM service connection) or a description of the required permissions that the Managed Identity needs to have on the ACR resource in order for this to work would b helpful.

Azure Devops does not provide any meaningful error message when the assigned permissions are not sufficient, which makes it quite hard to debug this issue of the pipeline not being triggered. 

Please fix this to save people time in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Define YAML resources for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@chrihala Thank you for flagging this and I apologize for the delay. I'm updating the article now to include a reference to permissions.
