### ISSUE TITLE
"echo" in powershell is an alias. for clarity, one otta use "Write-Output" instead

### ISSUE THREAD

**Issue by LeeDailey** [MicrosoftDocs/azure-devops-docs#12236]
howdy y'all,

many of your examples use "echo" for the "script:" code. that has caused relatively new users to try to use "Write-Host" instead of "Write-Output". i recommend changing from the alias to the real cmdlet.

aliases should NEVER be used for anything other than one-off, throwaway code. if it will be reused or read by anyone ... the full cmdlet otta be used.

take care,
lee

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the feedback! We generally use "echo" because it works for bash and PowerShell (in limited capacity). The [script keyword](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting) runs Bash on Linux and macOS and cmd.exe on Windows on our agents.
