### ISSUE TITLE
Predefined variable Build.SourceVersionAuthor not documented

### ISSUE THREAD

**Issue by frbvianna** [MicrosoftDocs/azure-devops-docs#12248]
Hi,

I was looking into retrieving the username for the GitHub commit author as a predefined variable in my Azure DevOps pipeline. The pipeline builds in question are due to GitHub CI triggers.

I noticed there were some possible variables such as Build.RequestedFor, Build.QueuedBy, none of which return my actual GitHub username - even though I'm the author of the commit which triggered the build.

Then I stumbled into the **Build.SourceVersionAuthor** variable in a [Microsoft thread](https://developercommunity.visualstudio.com/t/how-to-retrieve-user-name-when-a-build-was-trigger/904870#T-N905249) which addressed how to retrieve the author from a build triggered by another build. I noticed that this variable works for me, since I can actually get the GitHub commit author, unlike the other variables.

However, this variable is not documented in [Use predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#identity_values). This causes concern because I'm not entirely sure if it's reliable to use this variable in first place. Should it not be properly documented if the user is able to consume it? Note that although it should be a relatively straightforward variable to use in the pipeline, I went through some trouble to spot it in that Microsoft thread.

Thanks

**Comment by juliakm** [comment]
@frbvianna We generally don't document predefined variables when their definition can change during a pipeline run. I'll reach out to the product team and see if this is one of those cases.

**Comment by juliakm** [comment]
This is one of those variables where the value can change. You can always see the variables that are present for your environment with this task:

```
- script: 'env | sort'
```

**Comment by RussKie** [comment]
@juliakm could you please elaborate how this variable can change during a build?
