### ISSUE TITLE
Azure DevOps Administrato role - active

### ISSUE THREAD

**Issue by RTudosa** [MicrosoftDocs/azure-devops-docs#12245]
On the Prerequisites section: 
**Azure DevOps Administrator** role assigned to reclaim ownership it must of type "active" and not "eligible" in AAD, otherwise it is not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378ad220-599b-e802-f084-851277cc208d
* Version Independent ID: 8b041bf4-ec98-78bd-99e1-93e9f11225df
* Content: [Resolve inactive organization owner and project collection administrator - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?msclkid=77dda4f0c56611ecbb75935d5c77536c&view=azure-devops)
* Content Source: [docs/organizations/accounts/resolve-orphaned-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/resolve-orphaned-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @RTudosa, thanks so much for your feedback. If you're interested, we'd love for you to become a [contributor to our docs](https://docs.microsoft.com/en-us/contribute/)! You can make the update and I'll approve it. If not, I can add a user story to my backlog, no worries. Thanks again!

**Comment by RTudosa** [comment]
Hi @Chrystal ***@***.***>,

Thank you! I have made a PR and yes, I'll love to become a contributor!

Thank you
Have a great day ahead,
Robert
