### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by micale-pgnig** [MicrosoftDocs/azure-devops-docs#12256]
There is literally nothing about uploading or downloading process template in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b7e8f3-68f7-80f9-3cfb-6dca0002435b
* Version Independent ID: e37d3809-9ad8-e82b-71c1-543066fc105d
* Content: [Upload, download, or delete a process template - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/manage-process-templates?view=azure-devops&tabs=visual-studio-2019)
* Content Source: [docs/boards/work-items/guidance/manage-process-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/guidance/manage-process-templates.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@micale-pgnig - Thank you for your feedback. For Azure DevOps Services (cloud platform) there is no process template management functions as all is managed through the web portal and Inherited processes. To view the Azure DevOps Server (on-premises) platform content, please use the Content Version Selector located at the top-left above the table of contents.  The on-premises server content contains the management information you may be looking for. 

![image](https://user-images.githubusercontent.com/10856840/165821791-36632d7a-4b40-4fce-97c2-255c2e2d772c.png)

I will add some clarification to the existing article to reflect this. Thanks again.
