### ISSUE TITLE
Changing security for Areas and Iteration does not work as described

### ISSUE THREAD

**Issue by croban** [MicrosoftDocs/azure-devops-docs#12260]
The Feature for setting security policy for area and iteration does not work as described under:
https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#create-child-nodes-modify-work-items-under-an-area-or-iteration-path

Under Point 3) it should be possible to define custom policy for the users or groups
_Select the group or project member, and then change the permission settings. To add a user or group, enter their name in the search box._

This does not work as expected for our DevOps-Groups or ADD-Groups, because I don't know why but they must be also Team Administrators.  That means if the Group has Create Child etc. as described inside documentation they still won't be able to create new iterations or new areas. There are issues which are addressing this problem on developer communities but they have been closed as "Not a Bug" :(.
see: 
https://developercommunity.visualstudio.com/t/how-to-let-some-contributes-create-sprints-without/831523?viewtype=solutions
https://developercommunity.visualstudio.com/t/basic-user-unable-to-create-a-new-sprint/809552?viewtype=solutions

Now I am asking myself did I understand something wrong or this is a Bug inside DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022fb627-3fc3-e748-8431-a4597bb27ad5
* Version Independent ID: 0b56992a-b121-6095-5a60-65548fdd5a3b
* Content: [Set permissions for work tracking - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#set-permissions-area-path)
* Content Source: [docs/organizations/security/set-permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/set-permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by croban** [comment]
any news on this?

**Comment by KathrynEE** [comment]
@croban - Thank you for your inquiry. The article is correct as written. You don't have to be a team administrator to be granted permissions to create area paths or iteration paths. However, you do need to be a team administrator (or Project Administrator) to assign/select area paths and iteration paths for a team.   THis is documented here: 
- [Set team area paths](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=browser#set-team-area-paths)
- [Select team sprints and set the default iteration path](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#select-team-sprints-and-set-the-default-iteration-path)

All Area Paths and Iteration Paths that are created are defined at the Project Level. 
All Area Paths and Iteration Paths selected/assigned to a Team require Team Administrator role or Project Administrator membership. 

Let me know if this addresses your issue.

**Comment by croban** [comment]
@KathrynEE thank you for taking the time, I understand now, it was my mistake. 
Basically to give the user or the group control over the iterations (and/or areas) for the Team (Boards, Sprints) two security settings must be configured.
1) on the project level for iteration (and/or areas) node user/group must have create child...
2) on the team level this user or group must also admin
Then it works.

Thx, once again
