### ISSUE TITLE
wrong word used in sentence in Note area

### ISSUE THREAD

**Issue by maynard517** [MicrosoftDocs/azure-devops-docs#12266]
The incorrect word is used.  Should be "there" rather than "their".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c14bb1-b4a9-79de-4fa7-eb66f6ccaa63
* Version Independent ID: d227ffcb-775a-09c5-d8dd-0939aaec975a
* Content: [Connect Azure Boards to an Office client to track your work - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel#excel)
* Content Source: [docs/boards/backlogs/office/track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/track-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@maynard517 - Thank you for the feedback. Correction will be applied today.
