### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by Relinator** [MicrosoftDocs/azure-devops-docs#12267]
Code example to create container registry has mixed case in name, when I tried to create a registry with mixed case, received error:

PS /home/rel> az acr create --resource-group rel-ptc-rg --name ptcContainerRegistry --sku Basic
argument error: Connected registry name must use only lowercase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf0e2ac-c706-a08d-c667-ecbd073a8fdb
* Version Independent ID: 2b3a8b16-e689-8cc5-3134-af72f351e08d
* Content: [Build and push Docker images to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@Relinator -- Robert, thank you for bringing this to our attention.

@ramiMSFT -- Rami, please review this update in [private PR 4622](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4622).
