### ISSUE TITLE
Page not available for on-prem?

### ISSUE THREAD

**Issue by heoga** [MicrosoftDocs/azure-devops-docs#12272]
Page says it is not available for Azure Devops Server 2020 or 2019, but is linked from here: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops-2020

It was also previously available as I've been using this on-prem with this a reference for years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9927683a-6fad-ab3d-4a28-1a9c101bda83
* Version Independent ID: 7bccbe24-e106-1112-75a9-b093bb5ed012
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@heoga Thank you for your feedback! I'm getting this updated shortly
