### ISSUE TITLE
Wiki Stakeholder Access

### ISSUE THREAD

**Issue by simondmorias** [MicrosoftDocs/azure-devops-docs#12273]
This page has conflicting information under Stakeholder wiki access > Private projects.

The first paragraph reads: "Users with Stakeholder access in a private project can read project wiki pages"

The second reads "Stakeholders have zero access to read or edit code wiki pages in private projects"

I think the split should be to do with provisioned vs published wikis?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @simondmorias, Thanks for your feedback! I've created a work item on my backlog to address this. Once the update goes live, this issue will automatically close. Thanks again!
