### ISSUE TITLE
"Protect access to repositories in YAML pipelines" setting affects the usage of the Access Token

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#12280]
Greetings,

It would be good to include the reference to "Protect access to repositories in YAML pipelines" setting, as it affects the scope of the Access Token.

Reference : https://developercommunity.visualstudio.com/t/error-creating-repository-in-azure-devops-tf401027/1653143.

If you are okay, I am happy to update the FAQ with the details and submit a PR.

Please let me know.

Regards,
Vudaya

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd0749b-b681-8192-3849-f38e6fc7f138
* Version Independent ID: fb5170d3-2e45-3caf-be17-e012bd523660
* Content: [Understand job access tokens - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/access-tokens.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/access-tokens.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@vuvasira -- Vudaya, thank you for your feedback and kind offer.  Please do create that PR.  You are welcome to ask me for any assistance you need.

cc @vijayma for awareness
