### ISSUE TITLE
Microsoft does not support integration between cloud-hosted Azure DevOps and self-hosted GitHub Enterprise.

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#12287]
We need to include some information stating Microsoft does not support integration between cloud-hosted Azure DevOps and self-hosted GitHub Enterprise.  

This works only for github.com currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect an Azure Boards or Azure DevOps project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops&source=docs)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[kripa-2019](https://github.com/kripa-2019) - Thank you for your feedback. I've checked with the product team and they have confirmed that the scenario is supported. Please check the permissions of those attempting the connection and make sure they are a member of the Project Administrators group.
