### ISSUE TITLE
OAuth guidance should describe how to authenticate using an Azure Active Directory application

### ISSUE THREAD

**Issue by HolisticDeveloper** [MicrosoftDocs/azure-devops-docs#12283]
I needed to build an integration to some ADO APIs from an internal Blazor Web Assembly app. I found this documentation about how to register an application with ADO. However, I wanted to have an application registration that was owned by my organization rather than me as an individual. I have since discovered that this could be done by registering an application within our instance of Azure Active Directory. It would be helpful to document this as an option and provide links to the relevant docs for Azure AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @HolisticDeveloper, Thanks for your feedback. I've created a work item on my backlog to address this. Once the update goes live, this issue will automatically close. Thanks again!
