### ISSUE TITLE
Comments on Azure Artifacts overview

### ISSUE THREAD

**Issue by jeffsilverm** [MicrosoftDocs/azure-devops-docs#12290]
I have a question from Azure Artifacts overview https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops.

What does TFS stand for?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51babfa-569b-ef0a-469a-849a3835b21b
* Version Independent ID: 97a78c7b-dc57-f040-4cc2-66cd91f9851f
* Content: [Azure Artifacts overview - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@jeffsilverm -- Jeff, thank you for your question.  It was "Team Foundation Server", since renamed:
- [Team Foundation Server rebranded to Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/server/tfs-is-now-azure-devops-server)
