### ISSUE TITLE
Missing compose extension for Azure Devops Board app in Teams

### ISSUE THREAD

**Issue by sameer-kumar** [MicrosoftDocs/azure-devops-docs#12303]
I'm following the steps mentioned in article: https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops 

However, I can't see Compose extension in my Teams message toolbar as described here https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops#search-and-share-work-items-using-compose-extension

My Teams chat toolbar looks like this which clearly is missing the compose icon:

![image](https://user-images.githubusercontent.com/3660733/167517318-f820c21b-9226-48e3-b6ec-f1d5b23e8fcc.png)

I have Microsoft Teams Version 1.4.00.35564 (64-bit). It was last updated on 1/31/2022.
And I'm using Azure DevOps Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Use Azure Boards with Microsoft Teams - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/integrations/boards-teams.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **karrg**

**Comment by KathrynEE** [comment]
@sameer-kumar - Thank you for your inquiry. Depending on how many other extensions that are installed for Microsoft Teams, the icon may not be visible. Can you click the ... icon and see what options are available there. For example, this is what appears for me when I open ... (Messaging extensions).  Click on the Azure Boards icon and the options are available to you.

![image](https://user-images.githubusercontent.com/10856840/170141672-38549b9e-7739-4608-9138-82e6ff248e61.png)
