### ISSUE TITLE
Naming Restrctions: Azure Repos (Git) section does not include reserved keywords

### ISSUE THREAD

**Issue by sasakura-sora** [MicrosoftDocs/azure-devops-docs#12305]
Attempting to call a repository "server" will fail with the error "TF401025: 'repoName' is not a valid name for a Git repository. [...] or be a system reserved name"

None of the documentation indicates that system reserved names apply to repository names or provide any list of what these names are.

The Project names section contains a list of Reserved Names and a link to the documentation about it.  Something like this would be ideal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82305566-bf0a-20ca-46b0-4a011ea65e0b
* Version Independent ID: 59b2347e-dc58-ee34-0000-c2c8eb309901
* Content: [Restrictions and conventions for naming objects - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops)
* Content Source: [docs/organizations/settings/naming-restrictions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/naming-restrictions.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by KathrynEE** [comment]
@[sasakura-sora](https://github.com/sasakura-sora) - Thank you for the feedback. I am updating the article to provide more clarity on restrictions that apply to system reserved names, and specifically including Server.
