### ISSUE TITLE
Try your extension??

### ISSUE THREAD

**Issue by bospoort** [MicrosoftDocs/azure-devops-docs#12309]
This [article](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops) would be better with a bit of elaboration after "Try your extension". I had to go hunt for where the extension was under Repos/My Hub. A bit of explanation on next steps on how it ties back to the HTML might help to.

**Comment by WilliamAntonRohm** [comment]
[Develop a web extension](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node)

**Comment by chcomley** [comment]
Hi @bospoort, you're so right, thank you for the feedback. I'll update the article soon, and when it goes live, this issue will automatically close. Thanks again and have a great weekend.

**Comment by chcomley** [comment]
I've refreshed this article and articles related to it. Once these updates go live, this issue will automatically close. Please feel free to @mention me if you have any further questions or feedback. Thanks!
