### ISSUE TITLE
Azure DevOps examples of Epics are perpetuating confusion and misunderstanding, leading to dysfunctional implementations.

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/azure-devops-docs#12308]
Azure DevOps' documented examples of Epics are perpetuating confusion and misunderstanding, leading to dysfunctional implementations.

[This page](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/define-features-epics?msclkid=838a93f5b5b611ec9f09488bf9500f92&view=azure-devops&tabs=agile-process)
lists the following examples of "Epics":

- Increase customer engagement
- Improve and simplify the user experience
- Implement new architecture to improve performance
- Engineer the application to support future growth
- Support integration with external services
- Support mobile apps

Although the example Features on that page are fairly well worded, the Epics are not. None of these sound measurable. Does an Epic not represent a unit of work, just like Feature or User Story, albeit at a higher level? "Increase customer engagement" strikes me to be more of an area path, if anything, and that's if these are even mutually exclusive, which they clearly are not (judging by their titles, alone), and therefore can only be implemented as tags, I think. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d92157-ab0e-b538-c284-32c70da8e2dd
* Version Independent ID: 86d6c2eb-5931-27ee-3df9-a1d0889d510a
* Content: [Define features and epics, organize backlog items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/define-features-epics?msclkid=838a93f5b5b611ec9f09488bf9500f92&view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/define-features-epics.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/define-features-epics.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pabrams - Thank you for your feedback. I heard from one other customer and I've updated this article per your feedback. Thanks again for taking time to help us improve our content.
