### ISSUE TITLE
Wildcards for caching folders

### ISSUE THREAD

**Issue by pushkargupta9807** [MicrosoftDocs/azure-devops-docs#12300]
Hello, 
I understand that we do not have support for the input path to have wild cards. 

However it would immensely solve our problem if we added this enhancement, because in our use case we are having this mono-repo in which we need to cache a lot many of underlying folders. If we had support for wild cards to identify these underlying folders, it would be great. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@pushkargupta9807 Thank you for your feedback! Please feel free to request a feature on [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/report?space=21&entry=suggestion)
