### ISSUE TITLE
Missing documentation on useClusterAdmin option

### ISSUE THREAD

**Issue by Nikash** [MicrosoftDocs/azure-devops-docs#12307]
The `useClusterAdmin` option seems to have been added to the `HelmDeploy` task according to [the release notes page](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#support-for-cluster-admin-credentials-in-helmdeploy-task). But I don't see any mention of this option on the main documentation page. 

The release notes page also only specifies how to use it from the Classic Pipelines using UI and not from YAML. I had to create a task on the UI and view the YAML to find the yaml key to use. Would be nice to update both pages. But at a minimum [the official docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops) need to mention the option for the YAML pipelines along with the necessary explanation about the AD integrated cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dcde0ed-1d6e-1d31-7fb8-e91e8e9d200d
* Version Independent ID: 9320f59d-1ad5-80f1-a750-764cbf9d006a
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
