### ISSUE TITLE
Define vocabulary

### ISSUE THREAD

**Issue by FransUrbo** [MicrosoftDocs/azure-devops-docs#12317]
Please define the/your definition of *job*, *stage* and *step* as early as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95227592-b2a9-62be-59d1-fe8c7f4eae8e
* Version Independent ID: abf0c659-ce8c-b187-2784-22ddc061d69f
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the feedback. I'll add a reference to our [key concepts article](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops).
