### ISSUE TITLE
Add .gitattributes files to repos to normalize line endings

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-devops-docs#1231]
Hello 👋 - can you update the repo to address problems like #577?  Thanks 🙏

Apparently, there is a fix here: [MSFT Docs Issue 362](https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-402889434)

**Comment by steved0x** [comment]
Thank you for the reminder - I will get this fixed and will report back here on this issue when I do.

**Comment by spottedmahn** [comment]
FYI, [.gitattributes contents are here](https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-403932911)
