### ISSUE TITLE
'Conditional Insertion' does not work for Azure Devops Server -> remove from doc

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [MicrosoftDocs/azure-devops-docs#12311]
As 'Conditional Insertion' does not work for Azure Devops Server (Azure DevOps Server 2020 Update 1.1 as per https://developercommunity.visualstudio.com/t/Using-else-in-template-expression-d/1589150#T-ND10039004) and Microsoft has not provided feedback into this issue for 6 months the respective paragraph should be removed from the documentation to not lead other users into thinking this would work and the following frustration trying to get it to work.

File
docs/pipelines/process/expressions.md, paragraph 'Conditional Insertion'

**Comment by aelray** [comment]
+1

**Comment by WilliamAntonRohm** [comment]
@d5UtQvp8QQU9 -- thank you for your feedback.

@juliakm -- please look into this section:
- [Conditional insertion](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions#conditional-insertion)

**Comment by d5UtQvp8QQU9** [comment]
Clarification: Conditional insertion **does** work (partially), but only the `if` expression. The `else` and `elseif` expressions **do not** work with Azure Devops Server. Sorry for the confusion.

**Comment by psulek** [comment]
Shouldn't this be fixed rather than removed from docs? Just curious.

**Comment by d5UtQvp8QQU9** [comment]
> Shouldn't this be fixed rather than removed from docs? Just curious.

You're welcome to upvote the linked issue in the Visual Studio developer community.

> A bug that doesn't get fixed should at least get documented

me, 2022

**Comment by d5UtQvp8QQU9** [comment]
We have an official confirmation from a MS dev (2022-06-29):

> Microsoft Resolution - 
[Silviu Andrica [MSFT]](https://developercommunity.visualstudio.com/user/359620/profile)  
Closed - Not a Bug
Thanks for reporting the issue on Developer Community. Unfortunately, the {{else}} template expression is not available in Server 2020.

Source: https://developercommunity.visualstudio.com/t/Using-else-in-template-expression-d/1589150#TPIN-N10083681

**Comment by mwasson74** [comment]
@d5UtQvp8QQU9 so what is the outcome of this? Will this be fixed or is it just going to be removed from the documentation?

**Comment by d5UtQvp8QQU9** [comment]
If it says
> Closed - Not a Bug

my guess is that it won't be fixed...

Lets keep this issue on the topic *documentation*, though. I'm not going to reply to this ticket anymore because for me its done.

**Comment by psulek** [comment]
> @d5UtQvp8QQU9 so what is the outcome of this? Will this be fixed or is it just going to be removed from the documentation?

I think it should be fixed (backported from newer version of devops if new version has such feature)

**Comment by d5UtQvp8QQU9** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-devops-docs/commit/012560451b0a9643fa22854c5ada566f1ab2f858.
FYI: Feature is planned for Azure Devops Server 2022 (yay!)

**Comment by psulek** [comment]
@d5UtQvp8QQU9  so no backport to DevOps 2022 :-(

**Comment by juliakm** [comment]
The feature is in Azure DevOps 2022 but not Azure DevOps 2020. I'll update the article shortly.
