### ISSUE TITLE
Getting original commit hash from Github PR

### ISSUE THREAD

**Issue by tomasfejfar** [MicrosoftDocs/azure-devops-docs#12321]
On https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml:

There is a documented variable `Build.SourceVersion` that should hold the commit hash. But for Github pull request it does not contain the HEAD of the PR branch, but the hash of the PR's merge commit. The documentation is missing of how to get the actual commit hash.

**Comment by juliakm** [comment]
@tomasfejfar You're right, `Build.SourceVersion` returns the commit hash of the merge commit of the PR branch. You'll need to use a custom script to get the actual commit hash of the HEAD of the PR branch.

**Comment by tomasfejfar** [comment]
Wouldn't it be nice if pipelines would be able to give me the actual commit in a different variable?

**Comment by WilliamAntonRohm** [comment]
@tomasfejfar -- Tomáš, thank you for your suggestion.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
