### ISSUE TITLE
It's very hard to find nuget.org url

### ISSUE THREAD

**Issue by SiyuanZhang** [MicrosoftDocs/azure-devops-docs#12324]
See the comments in this question:
(https://stackoverflow.com/questions/5693139/what-is-the-url-for-nuget-gallery-to-access-nuget-org-from-vs2010)

Many developers found the official nuget.org url very very hard to find which is very very basic. It's critical to make resource easily accessible for the thrive of community. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c6f275-bf70-e3d3-fe44-b42e82d00343
* Version Independent ID: 14e91c65-4c89-3ef7-2e12-3cbec1da1f28
* Content: [Use packages from nuget.org - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/upstream-sources?view=azure-devops#enable-the-upstream-on-an-existing-feed)
* Content Source: [docs/artifacts/nuget/upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/nuget/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@SiyuanZhang Thank you for your feedback! I'm updating the article shortly
