### ISSUE TITLE
Execute multiple commands in single line SSH Deployment Task

### ISSUE THREAD

**Issue by abelkbil** [MicrosoftDocs/azure-devops-docs#12325]
As per document, I executed below command in Win 10 remote azure vm machine from my Azure release pipeline.
task - SSH Deployment task
type - command
`cd C:\ConatinerApp;stop-docker.bat`

Expectation was, the terminal cursor will move to specified director and they run the bat file. Instead I get exception, both command execute in different  process on user home directory;  

I did as per documentation, separated by ; 

**How to execute above step**; 
I tried `C:\ConatinerApp\stop-docker.bat` too. Though it is executing. other references inside the folder is not accessible so, not performing as designed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8529ee1d-6da2-f0c9-f9a1-3c312e4c13d7
* Version Independent ID: 3f4ea75f-a4a1-d248-b4ce-3de1a58185c7
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@abelkbil -- Abel, thank you for your thorough feedback.  In the [**Arguments**](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops#arguments) section of that article, there's the following Note in the **Command** option description:
>NOTE: Each command runs in a separate process. If you want to run a series of commands that are interdependent (for example, changing the current folder before executing a command) use the Inline script option instead.


Please try changing `runOptions` to `inline` and then put your commands as the value of the `inline` input, and let me know if this works for you.

cc @RoopeshNair for awareness
