### ISSUE TITLE
Rename a column

### ISSUE THREAD

**Issue by SeryioGonzalez** [MicrosoftDocs/azure-devops-docs#12326]
Is it possible to rename a column?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca21a0ba-3186-64e6-bb2f-de7eaa2f8513
* Version Independent ID: bff68ece-559e-be19-ec2b-817bfe61a70f
* Content: [Add or remove columns within a work item list in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/set-column-options?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/set-column-options.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/set-column-options.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SeryioGonzalez - Thank you for your inquiry.  Short answer is no. The Column names correspond to the names assigned to the fields on which they are based. While you can change the label that appears in the work item form for a field, the name of the field and column name will correspond to the name assigned to the field upon its creation.
