### ISSUE TITLE
Protect your Environment from Malicious Pipeline Changes in Azure DevOps

### ISSUE THREAD

**Issue by fardarter** [MicrosoftDocs/azure-devops-docs#12329]
I really think this blog should be used (with credit) as a foundation for an advice set on how to protect an environment from malicious pipeline changes in Azure DevOps: https://dscottraynsford.wordpress.com/2021/01/24/protect-your-environment-from-malicious-pipeline-changes-in-azure-devops

It's taken a LOT of work to understand all the necessary parts and where they are configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d9788c-8717-37d4-aca2-7f054b7b96eb
* Version Independent ID: ffc61e1c-b46a-26fd-6498-28481b344f80
* Content: [Plan an approach to secure your YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/approach?toc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fsecurity%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/pipelines/security/approach.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/security/approach.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@fardarter  Thanks for sharing this great resource!
