### ISSUE TITLE
Some parts are confusing

### ISSUE THREAD

**Issue by craigbrown** [MicrosoftDocs/azure-devops-docs#12322]
Just some feedback - I've been trying to migrate from classic pipelines to the new-style YAML pipelines and I found this article pretty confusing.

Some pointers to the specific things I found confusing:
- The 'Note' that starts "Deleting or overwriting Pipeline Artifacts is not currently supported..." is in a completely unrelated section about how artifacts are automatically downloaded in deployment jobs. It also contains the advice: 
    > The recommended workflow if you want to re-run a failed pipeline job is to include the job ID in the artifact name. 
    
    This is contradicted by an earlier section which states: 
    > A good way to approach this if you want to be able to rerun failed jobs without facing an error _package already exists_, is to use Conditions to only run if the previous job succeeded.
- The "Use Artifacts across stages" section seems to suggest artifacts can be passed between stages using a variable, rather than having to use the `publish` and `download` tasks. That doesn't seem right, given the entire rest of the article is dedicated to explaining how to do it using `publish`/`download`.
- The "Artifacts in release and deployment jobs" section says that "The download artifact task will be auto injected only when using the deploy lifecycle hook in your deployment". But it's not clear where the artifact gets downloaded to in this case, or how it knows what artifacts are needed. Some additional explanation would be nice, and an example would be even better.
- In the "Migrate from build artifacts" section it says:
   > For build artifacts, it's common to copy files to `$(Build.ArtifactStagingDirectory)` and then use the Publish Build Artifacts task to publish this folder. With the Publish Pipeline Artifact task, you can just publish directly from the path containing the files.
   
   This suggests that copying files to `$(Build.ArtifactStagingDirectory)` before publishing is not best practice for the new Pipeline Artifacts. But the code example directly above this section does exactly this.

Hope that is helpful to improving this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@craigbrown Thanks for your feedback! It's now possible to leverage `dependsOn` to publish an artifact in one stage and download it/use it in another stage. I'm updating the article shortly
