### ISSUE TITLE
Asterisk does not work for packages in Release view

### ISSUE THREAD

**Issue by flarsmar** [MicrosoftDocs/azure-devops-docs#12339]
https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&source=docs#download-the-latest-version

As specified above this does not work.

az artifacts universal download --organization "https://dev.azure.com/ahitapplicationteam/" --feed "wms" --name "ah-customizations-v2" --version '*' --path .
Did not find any versions of 'ah-customizations-v2' that matched the pattern '*' (Pre-release versions are not currently matched by wildcard patterns)
Process ['C:\\Users\\pnl0ph2p\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.236\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/ahitapplicationteam/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'wms', '--package-name', 'ah-customizations-v2', '--package-version', '*', '--path', '.'] with PID 1640 exited with return code 18
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8d339f-11e6-7474-b24f-6f5b6866d75a
* Version Independent ID: 00679a6a-3c45-afd8-cb70-33198412cee5
* Content: [Publish and download universal packages with Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&source=docs#downloading-the-latest-version)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@flarsmar -- Martin, thank you for your feedback.

@ramiMSFT -- please look into this issue & related issue #12337.

**Comment by ramiMSFT** [comment]
@flarsmar Wildcard patterns are not supported with pre-release versions (packages with a dash in their version number).
