### ISSUE TITLE
System.PullRequest.PullRequestNumber & System.PullRequest.PullRequestId Not Populating ?

### ISSUE THREAD

**Issue by v1ferrarij** [MicrosoftDocs/azure-devops-docs#12335]
The two variables are not populating: 

System.PullRequest.PullRequestNumber
System.PullRequest.PullRequestId

My code **IS in GitHub**, I have a Pipeline in Azure DevOps which triggers from PR's against the master branch. 

These variables were working last week and all of a sudden they have stopped working recently.

I am not using these variables in templates.

Here is a simple example of me trying to echo out the vars:

```bash
- bash: |
      echo "$(System.PullRequest.PullRequestNumber)"
      echo "$(System.PullRequest.PullRequestId)"

OUTPUT:
/home/vsts/work/_temp/d41f5d87-7736-423c-96df-9ac6494c7668.sh: line 1: System.PullRequest.PullRequestNumber: command not found

/home/vsts/work/_temp/d41f5d87-7736-423c-96df-9ac6494c7668.sh: line 2: System.PullRequest.PullRequestId: command not found
```

**Comment by v1ferrarij** [comment]
Sorry, this can be closed, was user error.

**Comment by djiangnz** [comment]
Hello @v1ferrarij , do you mind to post a snippet? I'm have the trouble of getting the pullrequestId, cheers
