### ISSUE TITLE
Download packages asterisk for latest version do not work in @local release

### ISSUE THREAD

**Issue by flarsmar** [MicrosoftDocs/azure-devops-docs#12337]
Download packages asterisk for latest version do not work in @local release as well

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops#arguments

vstsPackageVersion , do not work with packages in local releases. 

Error:
Did not find any versions of 'ah' that matched the pattern '*' (Pre-release versions are not currently matched by wildcard patterns)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @arob98
* Microsoft Alias: **angrobe**

**Comment by WilliamAntonRohm** [comment]
@flarsmar -- Martin, thank you again for your clear feedback.

@arob98, @ramiMSFT -- Angela, Rami, please look into this issue and related issue #12339.

**Comment by arsovski-ahnl** [comment]
Hello, 

any update on this?

**Comment by flarsmar** [comment]
Hello,

Any update on this?

**Comment by ramiMSFT** [comment]
@flarsmar Thanks for your feedback! Wildcard patterns are not supported with pre-release versions (packages with a dash in their version number). I'm updating this shortly
