### ISSUE TITLE
Note section verbiage

### ISSUE THREAD

**Issue by MichaelDell** [MicrosoftDocs/azure-devops-docs#12338]
In the `Note` section of this page I find the verbiage confusing. Does this line refer to the NuGet Authenticate task or the DotNetCoreCLI task
`The restore and push commands of this task no longer take new features and only critical bugs are addressed.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c454e1c5-3f67-75c2-26eb-34a7a719304b
* Version Independent ID: 106edc87-3be1-a9bd-fcaf-78cc893a6686
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by sonnvel** [comment]
Please unsubscribe me from your mailing list.
Thanks

**Comment by WilliamAntonRohm** [comment]
@sonnvel -- you can unsubscribe yourself with GitHub's `Notifications` settings:
![image](https://user-images.githubusercontent.com/27738025/171281175-ef1c7ea2-ec15-4c3f-8fc7-60e54afffe96.png)
