### ISSUE TITLE
Choose a query filter section, In and Not In Group link

### ISSUE THREAD

**Issue by OutstandingBillNeal** [MicrosoftDocs/azure-devops-docs#12334]
I'm looking at the "Choose a query filter" section on this page: https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops&tabs=browser

The page linked for "In and Not In Group searches" doesn't describe how to specify multiple elements for the "in" list.  The UI seems to limit the list to a single item because it uses a dropdown which doesn't allow multiple items to be selected, and following the link seems like the logical way to find how to do it.  I am imagining there is a more appropriate page that could be linked here.  Alternatively, perhaps the linked page content could be augmented to include something like "to specify multiple items, type the item names correctly, separated by commas".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309b3b5f-7355-57ac-3775-b441f6e037f1
* Version Independent ID: 0d30ed27-9dc4-e8de-ef7e-c71842c9b4c3
* Content: [Define a work item query with the Query Editor in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/queries/using-queries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/using-queries.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@OutstandingBillNeal - Thank you for the feedback. To use the **In** and **Not In** operators, you enter the names of the groups you want to include or not include as a comma-separated list. I will look at updating the article to clarify.  Currently, there is this example, but I believe more clarity is needed. 

![image](https://user-images.githubusercontent.com/10856840/170104074-b20c8ea7-1d7b-40d4-9085-c4eea20ab65d.png)
