### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by vraulet** [MicrosoftDocs/azure-devops-docs#12333]
These 2 lines are repeating the same thing:

"Azure DevOps Services supports integration with GitHub.com **and GitHub Enterprise Server repositories**. Azure DevOps Server supports integration **with GitHub Enterprise Server repositories**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2197a6a8-ecda-b647-6cbf-c08defccc54b
* Version Independent ID: c66fa15d-cb16-b734-d73b-701acf368f95
* Content: [What is Azure DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/what-is-azure-devops?toc=%2Fazure%2Fdevops%2Fserver%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fserver%2Fbreadcrumb%2Ftoc.json&view=azure-devops-2020)
* Content Source: [docs/user-guide/what-is-azure-devops.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/user-guide/what-is-azure-devops.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @vraulet, Thanks for your feedback! I've published a fix, but please note that it wasn't a repeat, it was two separate lines about Azure DevOps Services, and then Azure DevOps Server. I italicized _Services_ and _Server_, to better clarify. Thanks!
