### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-devops-docs#12340]
The article does not mention at all that JSON is also supported. E.g. to define variables you can use both yml and JSON

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@yahorsi Do you mean using PowerShell to create a JSON object with `Convert-FromJson`? Please give an example.

**Comment by yahorsi** [comment]
No, I mean that you can use JSON to pass parameters to, for instance template

**Comment by juliakm** [comment]
I'll reach out to the product team. I'm not seeing JSON as an [officially supported data type](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/parameters-name?view=azure-pipelines).

**Comment by yahorsi** [comment]
JSON is supported variouse ways in the various places.
Sample 1 we use right now:
parameters:
- name: DeploymentType
  displayName: Type of the deployment to be performed
  type: string
  default: Deployment
  values:
  - Deployment
  - DeploymentWithoutDb
  - Maintenance

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: build-pipeline
    source: 'build-code-web'
    branch: GMI-Edge-Staging
    trigger: none
 
variables:
  - group: code-global-vars
  - template: variables.json   

extends:
  template: ../code-template.yml
  parameters:
      DeploymentType: ${{ parameters.DeploymentType }}
      IsLegacyPipeline: true


Please note in the 1st case we use template: variables.json...

This is very important as it let's you to share same variables across different deployment pipelines, e.g. code deployment pipeline and infrastructure deployment pipeline
