### ISSUE TITLE
Blocked field values

### ISSUE THREAD

**Issue by t-hmatei** [MicrosoftDocs/azure-devops-docs#12341]
[Enter feedback here]
In this documentation, at the section **Fields used to plan and prioritize work**, for the blocked field, it is mentioned that the accepted values are **Yes** or **No**. This is true for the CMMI process, but for the Scrum process, you can leave the field either empty, or you can specify ** Yes**.  In the Scrum process the value "No" for the blocked field is not in the list of accepted values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a7ad6d-e610-358e-57ab-65c139ec2fad
* Version Independent ID: a84f995c-6511-7e3a-c911-8dca8e1fb357
* Content: [Create queries based on rank and priority fields - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/planning-ranking-priorities?view=azure-devops#fields-used-to-plan-and-prioritize-work)
* Content Source: [docs/boards/queries/planning-ranking-priorities.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/planning-ranking-priorities.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[t-hmatei](https://github.com/t-hmatei) - Thank you for your feedback. I'm updating the article today to reflect the difference between the Scrum and CMMI processes.
