### ISSUE TITLE
The section in "Custom Fields" is incomplete. They can be names by AzDo as Custom.GUID

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/azure-devops-docs#12350]
The section in "Custom Fields" is incomplete. I've had custom fields name with the format Custom.GUID when creating a new inherited process. (e.g. Custom.5766d65c-9f0c-4df9-b1e0-28b44864bce0 )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7a0948-ee09-8734-ed6e-bc45bd78ce01
* Version Independent ID: da9ac11c-958d-f5dd-efad-0c20c2d7cf2f
* Content: [List work item fields and attributes in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-fields.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/work-item-fields.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dombat - Thank you for this feedback. I'll investigate this and update as needed. However, it is odd for a custom field to be named with a GUID string. Could you provide more information as to what process you used, when you added the custom field, and what is the display name or friendly name that you gave it. Thanks.

**Comment by KathrynEE** [comment]
@dombat - I'm going to close this issue as there is no action for documentation. If you believe there is still an issue, I recommend you visit our [Developer Community page](https://developercommunity.visualstudio.com/search?space=21) to report a bug or request help on an issue.
