### ISSUE TITLE
Velocity Chart

### ISSUE THREAD

**Issue by domenicr** [MicrosoftDocs/azure-devops-docs#12358]
The documentation for the completed and completed late values indicate that only work assigned before the start date will affect the completed and completed late but this is not the case. This can be easily verified by adding work past the start date and completing it either before or after the end date and you will either see the completed or the completed late values affected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [View and configure team velocity - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azure-devops)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[domenicr](https://github.com/domenicr) - Thank you for this feedback. I looked into this issue and updated explanations for the velocity bars. The updates are published.
