### ISSUE TITLE
Github pipeline doc claims to check out from Azure Repos Git repositories

### ISSUE THREAD

**Issue by anno1985** [MicrosoftDocs/azure-devops-docs#12365]
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#checkout

> When a pipeline is triggered, Azure Pipelines pulls your source code from the Azure Repos Git repository. 

Shouldn't that read "...from the GitHub repository" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@anno1985 -- Christian, thank you again for your interest.  Please see the resources I mentioned in your first issue #12364.
