### ISSUE TITLE
This page doesn't explain how to truncate dates in filtering

### ISSUE THREAD

**Issue by bergamin** [MicrosoftDocs/azure-devops-docs#12363]
This page doesn't explain how to truncate dates to ignore time in wiql. TRUNC or TRUNCATE don't work, so I assume there is a wiql specific way of achieving that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [Work Item Query Language (WIQL) reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[bergamin](https://github.com/bergamin) - Thank you for your inquiry. There isn't a comparable TRUNC or TRUNCATE function in WIQL. I recommend you reach out to the Developer Community for a specify query you're trying to run. Closing this as non-acitonable from a documentation point of view.

**Comment by bergamin** [comment]
Thank you @KathrynEE. I was able to work this limitation around by using the start of the date as a way to truncate it. Thanks!
