### ISSUE TITLE
docs: don't use the term "main pipeline"

### ISSUE THREAD

**Issue by anno1985** [MicrosoftDocs/azure-devops-docs#12369]
On the [template types and usages](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories) page, the docs state:

> You may also use `@self` to refer to the repository where the main pipeline was found. 

This comes right after the following Note:

> If no ref is specified, the pipeline will default to using refs/heads/main.

At this point, it's a bit confusing what the "main" pipeline is: the one with the entry point that's run, or the one in the "main" branch.
The next sentence makes it clear, but maybe the first one could be reworded...

> This is convenient for use in extends templates if you want to refer back to contents in the extending pipeline's repository. For example:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@anno1985 Thanks! I'll update the wording.
