### ISSUE TITLE
Status Slack Blockchain

### ISSUE THREAD

**Issue by feliciousity** [MicrosoftDocs/azure-devops-docs#12373]
``
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f2bb3a-6619-88c0-ba29-23af30fcb301
* Version Independent ID: 0ede4455-b1df-ffef-743f-126a5e9a1a00
* Content: [Service status - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/service-status-info?view=azure-devops)
* Content Source: [docs/user-guide/service-status-info.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/user-guide/service-status-info.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@feliciousity -- Felicia, thank you again for writing to us.  Please clarify your question or issue.
