### ISSUE TITLE
Updating Principal Client Secret for Existing Service Connections is not Documented

### ISSUE THREAD

**Issue by mister-liss** [MicrosoftDocs/azure-devops-docs#12381]
This document explains how to setup and manage connections but does not explain how to get the Service Connection to re-authenticate when the Principal's secret has changed.

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml

This requires a work-around explained in this blog post. The workaround should be noted in the documents until this bug is fixed.

https://rlevchenko.com/2022/03/04/azure-devops-update-service-connection-expired-secret/

**Comment by rlevchenko** [comment]
+1 

Used the workaround multiple times. Works fine. 
We should have an option to switch between Automatic to Manual and vice versa on the fly.
