### ISSUE TITLE
Self-Hosted agent configuration will ambiguously fail authorization when organization URL has trailing slashes 

### ISSUE THREAD

**Issue by cutecycle** [MicrosoftDocs/azure-devops-docs#12388]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#required-options

It may be helpful to point out that the CLI doesn't seem to take trailing slashes; it just gives a `VS30063: You are not authorized to access $url` error.

**Comment by WilliamAntonRohm** [comment]
@cutecycle -- Nina, thank you for your suggestion.

@steved0x -- Steve, please look into this issue.
