### ISSUE TITLE
Link to Rest-Documentation of Endpoints (AzureDEVOPS)

### ISSUE THREAD

**Issue by picpromusic** [MicrosoftDocs/azure-devops-docs#12386]
It would be great to have an helpfull link to 
https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create
instead of the uninfomative 
"Create endpoint of same type from UI and capture its network trace (using tool of your preference like Fiddler, Chrome Developer tool)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe5c6b81-0205-01ee-41fc-fced8b578f12
* Version Independent ID: 8b152b96-e645-a4db-53c8-c052faaea856
* Content: [Create service endpoint using Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/service-endpoint?view=azure-devops)
* Content Source: [docs/cli/service-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/cli/service-endpoint.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[picpromusic](https://github.com/picpromusic) -  Thank you for this feedback. I agree that more helpful links are warranted and am in the process of updating the article to support your request. Updates should be published by end of day.
