### ISSUE TITLE
Incorrect or outdated Link

### ISSUE THREAD

**Issue by jpwalters1** [MicrosoftDocs/azure-devops-docs#12385]
[The link is broken or irrelevant.  Instead of instructions on WinRM it is a general discussion about setting up VMs in general]
[
](https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-configure-winrm-after-vm-creation)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2860c61-13f0-71bc-6532-76100aa3eeaa
* Version Independent ID: 411881eb-bf52-02f8-cf2a-15b7d96af3f0
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@jpwalters1 -- thank you for your feedback.  It seems that link should be a subheading, as the next steps explain the indicated procedure.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
