### ISSUE TITLE
set variables

### ISSUE THREAD

**Issue by garylogin** [MicrosoftDocs/azure-devops-docs#12384]
Hi
I struggled with this documentation because i always tried to set the variable and read the variable in the one task! 
I was testing...
It wasn't clear to me that you set the variable in one task and read it in another task, maybe its clear to other but it wasn't to me :-)
Hope this helps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ad0d9b-2e51-de2e-a529-6cbe55692023
* Version Independent ID: 609b6196-cc6b-677a-c76f-f82bb7cce10a
* Content: [Set variables in scripts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/process/set-variables-scripts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/set-variables-scripts.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for pointing this out. I'll add a sentence to the intro to make it clearer.
