### ISSUE TITLE
explicitly naming a resource is required although documentation suggests otherwise

### ISSUE THREAD

**Issue by thinkOfaNumber** [MicrosoftDocs/azure-devops-docs#12398]
Hi,

I came across what I thought was a bug with azure pipelines and noted it here: https://developercommunity.visualstudio.com/t/YAML-release-pipeline-deploy-stage-not-d/10053723

Essentially if I don't specify a resource, I get errors as the pipeline tries to create one for me, instead of deploying to all existing resources in the environment.

The result was it's "not a bug", however the documentation suggests that I should be able to do this in this section: https://developercommunity.visualstudio.com/t/YAML-release-pipeline-deploy-stage-not-d/10053723

_"A deployment job can be used to target an entire environment (group of resources) as shown in the following YAML snippet."_

Not sure if it's because I'm using an on-prem VM in the environment or not? It would be good to remove this section in the documentation or state which configurations it applies to.

thanks,
Iain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@thinkOfaNumber Thanks! I apologize for the delay and am adding a note in the article now.
