### ISSUE TITLE
Why is there no keyboard shortcut for creating a new user story from the Work Items board?

### ISSUE THREAD

**Issue by L13w** [MicrosoftDocs/azure-devops-docs#12397]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3955e8-20ca-18ad-172a-bce3b4374b92
* Version Independent ID: 92133948-fb31-db82-6d60-7cebb8c05bcc
* Content: [Add user stories & other work items to help manage your project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/add-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/add-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/add-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[L13w](https://github.com/L13w) - Thank you for your inquiry. I recommend that you post your question/request for this keyboard shortcut on our [Developer Community Page](https://developercommunity.visualstudio.com/search?space=21).
