### ISSUE TITLE
"powershell...will only work on a Windows agent" appears to be false

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/azure-devops-docs#12393]
The document says "`powershell` runs Windows PowerShell and will only work on a Windows agent."

My testing with the latest OS environments shows this claim to be false. It shows the task signature `-powershell:` runs in all agent OS environments, not just in Windows.

Could it be the document is correct for older build agent environments? I did not test that.

### Details:

I tested 10 different inline Powershell scripts for generating a directory listing. For one set of 10, I used the task signature `- task: PowerShell@2`. For another set of 10, I used the task signature of `- powershell:`. I put the 20 scripts in a YAML ADO pipeline. I ran the pipeline in the latest versions of Windows, macOS, and ubuntu. Those were: Windows Server 2022, macOS 11.6.6 20G624, and Ubuntu 20.04.4 LTS. In every case in every environment, the Powershell version being run and the directory listing behavior was identical between the two task signatures.

Conclusion: The task signature `- task: PowerShell@2` and the task signature `- powershell:`, when running an inline script, are functionally identical, and run equally well in all OS environments.

### Suggestion:

Revise the document, either removing the claim, or if the claim is partially true, qualifying the claim. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb6bb80-ad9e-525c-3cae-275955b00919
* Version Independent ID: 79d62477-08d2-f412-d59d-d8cbac75dc32
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#yaml-snippet)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by geralexgr** [comment]
Indeed @BruceHaley is correct. 

You can execute the powershell command on the `ubuntu-latest` image. The documentation can be improved further.

```
pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $PSVersionTable
```

![image](https://user-images.githubusercontent.com/3514710/193782557-d8e5b377-2c77-482b-8b7b-57fddb14cbd4.png)

**Comment by steved0x** [comment]
Thank you for letting us know. This issue is fixed in our new task reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines

Please check t out and let us know what you think. Thank you.
