### ISSUE TITLE
define "built-in Maven feeds" (and differentiate Maven task's `mavenFeedAuthenticate` argument from `MavenAuthenticate`'s `artifactsFeeds`

### ISSUE THREAD

**Issue by anno1985** [MicrosoftDocs/azure-devops-docs#12392]
The [docs for the Maven task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops#arguments) describe the `mavenFeedAuthenticate` argument as follows:

> Authenticate built-in Maven feeds |
> (Required) Automatically authenticate Maven feeds from Azure Artifacts. If built-in Maven feeds are not in use, deselect this option for faster builds.Default value: falseArgument aliases: `mavenAuthenticateFeed`

It's not quite clear what "built-in Maven feeds" are; the term isn't used elsewhere (for as far as I can tell).

To my mind, it's Maven Central - the repo maven uses when nothing else is defined. What is probably meant, though, is Maven feeds defined in [Azure Artifact Feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops), including [public feeds for Maven Central](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/upstream-sources?view=azure-devops#add-maven-central-upstream), if configured.

A clarification in the docs for the Maven pipeline task would be nice, along with links to the right documentation for the sort of feeds it refers to. Maybe also an explanation how that parameter relates to the [Maven Authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops)'s `artifactsFeeds` - they both seem to do the same thing...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81921de1-7801-99b8-30ff-92530ceb49b2
* Version Independent ID: 50fb21ad-2049-fd80-db73-3d78c305cdac
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
@anno1985 Thank you for your feedback!

+@ankit348 @daneshbadlani @jorfde

**Comment by ramiMSFT** [comment]
@ankit348 @daneshbadlani @jorfde - Any updates on this?
