### ISSUE TITLE
Link to https://visualstudio.com/ is not valid anymore

### ISSUE THREAD

**Issue by Gismork** [MicrosoftDocs/azure-devops-docs#12408]
This documentation page explains that we can go to the profile page using address : https://visualstudio.com/

![image](https://user-images.githubusercontent.com/2140163/173888254-a7cd987a-bf15-4ef8-bcd5-ed5ca53017bb.png)

https://visualstudio.com/ now redirect to Visual Studio product home page: https://visualstudio.microsoft.com/

Could you fix this page to link to the profile page instead ? 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc61b61-ed67-8313-99d4-d736e7f48234
* Version Independent ID: 3e0fcf87-9744-cec8-24f8-9f68371959c6
* Content: [Integrate with service hooks - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/overview?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/service-hooks/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/service-hooks/overview.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
