### ISSUE TITLE
"It can be used to mark separation of concerns (for example, Build, QA, and production)"   how is production a stage? Sound like an environment. If I have it wrong sorry, but I think something like "Build, Run Tests, Package and Deploy" are better sounding as steps here

### ISSUE THREAD

**Issue by baxternicholas** [MicrosoftDocs/azure-devops-docs#12419]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@baxternicholas -- Nicholas, thank you for your feedback.  If I understand correctly, production is the final stage, covering both packaging and deployment.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.


cc @juliakm for awareness
