### ISSUE TITLE
extend screenshot

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/azure-devops-docs#12413]
Can you please extend screenshot that is on the page.  It is not possible to see in what ADO category velocity chart belongs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e01fac-6a61-00a9-b914-2d42aa270bf8
* Version Independent ID: 6cc94467-d5d8-ff66-290f-c37304a83ccc
* Content: [Velocity metrics and usage guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/velocity-guidance?view=azure-devops&tabs=in-context)
* Content Source: [docs/report/dashboards/velocity-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/velocity-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[iricigor](https://github.com/iricigor) - I don't understand what you mean by  "It is not possible to see in what ADO category velocity chart belongs."  Can you provide more context or information.

**Comment by iricigor** [comment]
Sorry for unclear report. For example, on this screenshot [here](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops), I can see that I need to find Boards under Boards category on the left side. From this article and the screenshot, it is unclear where to find Velocity chart. 

Something like this that includes the menu on the left would be better, I think
![image](https://user-images.githubusercontent.com/15923171/174270836-46ecfc06-d68a-4618-a5ea-8aa07caf12f7.png)

**Comment by KathrynEE** [comment]
@iricigor - Thank you for the clarification. I will update the article to provide the needed clarification. For now, steps to take to open the Velocity chart are provided here: [View or configure team velocity](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azure-devops#open-your-backlog-from-the-web-portal).   Basically you access it from the **Backlogs** or **Boards** hub and the **Analytics** tab.
