### ISSUE TITLE
Add missing git tags example to Build.SourceBranchName documentation for clarity

### ISSUE THREAD

**Issue by Taoquitok** [MicrosoftDocs/azure-devops-docs#12417]
The [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) for `Build.SourceBranchName` does not explicitly state that _if the trigger is a new tag, it'll return purely the tag name from the end of the triggering ref._  
This can be inferred from the definition of `Build.SourceBranch`, but it would be useful to explicitly state so users do not need to test to confirm this  
  
Optional suggested change:  
  
```diff
- Git repo branch or pull request: The last path segment in the ref. For example, in refs/heads/master this value is master. In refs/heads/feature/tools this value is tools.
+ Git repo branch, pull request, or tag: The last path segment in the ref. For example, in refs/heads/master this value is master. In refs/heads/feature/tools this value is tools. In refs/tags/your-tag-name this value is your-tag-name.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review this update in [private PR 4789](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4789).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
