### ISSUE TITLE
"Remove additional files at destination" should not delete other WebJobs/web services in the same Azure App Service

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/azure-devops-docs#12420]
It does not make sense that enabling "Remove additional files at destination" for a WebJob/web service should delete other WebJobs/web service in the same Azure App Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b648a9b-9a8d-423f-94c9-cb56ec458273
* Version Independent ID: efe57b89-fbac-8a5c-4607-102ebfd57b54
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#web-deploy)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by pabrams** [comment]
Why not?  Don't those other things consist of files at the destination?

**Comment by catmanjan** [comment]
Maybe? I suppose thats a question for Microsoft as to how they have implemented the app service sandbox

Its still unintuitive

**Comment by pabrams** [comment]
I guess I don't understand why you would enable "delete additional files at destination" unless you understood what additional files existed at the destination.

**Comment by catmanjan** [comment]
It’s unexpected that by default, files other than the ones that were ever part of a given project would exist at a projects publish destination

The fix to this should probably be to not deploy WebJobs to the same destination as the web app

**Comment by pabrams** [comment]
Sounds pretty reasonable when you put it that way.
