### ISSUE TITLE
Please show who to change the unit of Original Estimate.

### ISSUE THREAD

**Issue by weiliu-ivy** [MicrosoftDocs/azure-devops-docs#12421]
[Enter feedback here]

Hi, this page mentioned that "You can specify work in hours or in days." Could you provide me the specific steps to specify/change the unit? Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f85f904-14c5-c520-edc3-b8af6826b4fc
* Version Independent ID: 414874f2-1e30-04da-0feb-e459a4e51be8
* Content: [Agile process work item types & workflow in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/agile-process-workflow?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/agile-process-workflow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/guidance/agile-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@weiliu-ivy -- thank you for your question.  My understanding is that the unit of time is your decision when setting up the tasks.  From that section:
> [Original Estimate](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-numeric?view=azure-devops)
> The amount of estimated work required to complete a task. Typically, this field doesn't change after it's assigned.
> You can specify work in hours or in days. There are no inherent time units associated with this field.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
