### ISSUE TITLE
Unable to see new "New release progress views" in preview features as per the documentation

### ISSUE THREAD

**Issue by prathyusha-mandala** [MicrosoftDocs/azure-devops-docs#12433]
[Enter feedback here]
Unable to see new "New release progress views" in preview features as per the documentation
"New release progress views" is unavailable in Preview features in azure devops services.

Also the Release(Old view) functionality is not loading(blank page) and there is no option to disable the new feature.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Manage preview features - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[prathyusha-mandala](https://github.com/prathyusha-mandala) - Thank you for your feedback. The  **New release progress views** option should appear as documented in Preview features. I recommend you post your issue with the product team on our [Developer community page](https://developercommunity.visualstudio.com/search?space=21).
