### ISSUE TITLE
Bulk Update User's Notification Email Address

### ISSUE THREAD

**Issue by YourWifeCallYou** [MicrosoftDocs/azure-devops-docs#12434]
Azure DevOps lacks the function for company administrator to bulk update all user's notification email address, following company's domain change.
Such function is definitely useful as we have few thousands users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c94a78f-77de-a612-1fc8-749518195166
* Version Independent ID: fba4f685-1c59-e1e6-2138-aaa5477e476d
* Content: [Change your preferred notification email address - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/change-email-address?view=azure-devops&tabs=preview-page&source=docs)
* Content Source: [docs/notifications/change-email-address.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/notifications/change-email-address.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@YourWifeCallYou -- thank you for your feedback.  [Please add it here](https://developercommunity.visualstudio.com/search?space=21).


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
