### ISSUE TITLE
set-up-the-build-task step is unnecessary in SourceLink doc

### ISSUE THREAD

**Issue by pharring** [MicrosoftDocs/azure-devops-docs#12436]
I think the set-up-the-build-task step is unnecessary in the SourceLink documentation. This step says to set the SourceLinkCreate property to true (via `/p:SourceLinkCreate=true` on the MSBuild command line).

As far as I can tell, it has no effect on whether SourceLink is included or not in the final build.

By default, once they've added the appropriate Microsoft.SourceLink NuGet package from the preceding step, users shouldn't need to control SourceLink inclusion manually. The Microsoft.SourceLink NuGet packages automatically determine whether SourceLink should be enabled.

Users _can_ override the default behavior -- perhaps to disable SourceLink completely in certain build flavors -- but it's done via a different property: EnableSourceLink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb2bfcb-0a0c-ce90-fa49-ad2e7fbaa57a
* Version Independent ID: 1a295877-ff8f-f8c2-0349-76a69a0f5cfc
* Content: [Publish symbols with Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops#set-up-the-build-task)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by pharring** [comment]
@tmat can you keep me honest here?

**Comment by tmat** [comment]
Agreed - the property shouldn't be needed.

**Comment by pharring** [comment]
#sign-off

**Comment by ramiMSFT** [comment]
@pharring Thank you for your feedback! I agree! Setting up the build task in not needed anymore.
