### ISSUE TITLE
WindowsMachineFileCopy Doc States MachineNames are optional, yet pipeline fails with Required error

### ISSUE THREAD

**Issue by cdodrzywolski** [MicrosoftDocs/azure-devops-docs#12447]
The Doc states:
![image](https://user-images.githubusercontent.com/68967069/176198242-799e3230-f6f3-4713-87f5-ca99c929ab66.png)

Yet when run:
![image](https://user-images.githubusercontent.com/68967069/176198340-f2ffdcbb-ab6e-4004-ace2-d2e46e6255d5.png)

The error is produced:
![image](https://user-images.githubusercontent.com/68967069/176198414-8dc28117-e9cb-4d99-b656-2159582fcc57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd94385e-60ae-d9ca-be76-ee7f97f3dfde
* Version Independent ID: 03eeae39-e3be-b10f-0ee5-9b8a312aae98
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- Roopesh, please review this update in [private PR 4810](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4810).

**Comment by steved0x** [comment]
@cdodrzywolski Thanks for reporting this. This issue is fixed in our new task reference - this task input is marked as required,

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/windows-machine-file-copy-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.

**Comment by cdodrzywolski** [comment]
You're very welcome, thanks for updating!
