### ISSUE TITLE
Cross-check the correct date format that works in ADO queries

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/azure-devops-docs#12450]
The section `Date-based queries` has screenshots displaying date format using slash character. It doesn't work for me. I tried all sequences of date, month, and year in the x/y/z format. What works is hyphen-separate format. For example, 01-01-2022 works instead of 01/01/2022. Please cross-check the format documented in this article and elsewhere in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops#date-based-queries)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[ashishguptaiitb](https://github.com/ashishguptaiitb)- Thank you for your feedback. Could you check that the date format that works for you is the same as that set through your personal preferences? I do have this statement in the article: _Enter dates in the Date Pattern you set for your personal profile. (See [Set personal preferences](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops) for details.)_  However, maybe I need to draw more emphasis to it.
