### ISSUE TITLE
Documentation for AzureFunctionApp task and managed identity

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [MicrosoftDocs/azure-devops-docs#12457]
It is now possible to configure a function app with a managed identity instead of a connection string, which is great! But it does not appear to be supported by the devops AzureFunctionApp task :(

We have a function app with system assigned managed identity, where the managed identity is granted the appropriate permissions and is configured with the following in app settings:

```
AzureWebJobsStorage__accountName: <storageAccountName>
```

This appears to work fine in the app. When we try to deploy via azure devops, we get the error:

```
Error: Unable to find the storage account associated with the function app
```

Indeed, looking at the code for the task, it only checks for `AzureWebJobsStorage`. 

It would be good if the documentation explicitly said that using the task does not support host storage connections using managed identity and that it requires `AzureWebJobsStorage` in the app settings. It would also be good to have a description of the `Unable to find the storage account associated with the function app` error.

It would also be great if the error message were more descriptive, i.e. "Unable to find the storage account associated with the function app. App setting AzureWebJobsStorage not found" or similar, to avoid the wild goose chase I have been on.

Even better would be if we could finally get away from copying connection strings everywhere, but it appears that day has not yet come.

Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
@jeffw-wherethebitsroam -- Jeff, thank you for your thorough feedback.  I am investigating.

**Comment by fardarter** [comment]
Is this correct?

This is very frustrating
