### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/azure-devops-docs#12461]
In the section [What syntax should I use?](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#what-syntax-should-i-use), there is a paragraph that essentially says:

> Choose a runtime expression if [first scenario]. The exception to this is if [second scenario]. In that case, you should use a runtime expression.

Unless I'm having cognitive issues, then this appears to amount to "If X then use a runtime expression.  Otherwise, also use a runtime expression."

I assume one of those instances of "runtime" was supposed to be "template" or "macro," but I'm too new to YAML to know which instance should be replaced, and with which alternative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @ronwarner! This will be fixed shortly.
