### ISSUE TITLE
No mention of .NET 6 for collecting code coverage metrics with Coverlet

### ISSUE THREAD

**Issue by duyn9uyen** [MicrosoftDocs/azure-devops-docs#12467]
This section should mention and give an example for .NET 6.
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive#collect-code-coverage-metrics-with-coverlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4959fc1-212b-7d6a-df73-b0b2993df561
* Version Independent ID: fcecb4fc-6b16-e432-8f4a-f043e222bb41
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @duyn9uyen! An update will go out shortly. You can use the same tasks (with an update for .NET 6( described in the .NET 5 section for Coverlet.
