### ISSUE TITLE
Missing my Followed Work Items query

### ISSUE THREAD

**Issue by brika7** [MicrosoftDocs/azure-devops-docs#12479]
[Enter feedback here]
Please show how to recreate this query for Followed Work Items. Mine is missing and I cannot find it in the location per this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates to a user story, bug, or other work item - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@brika7 - Thank you for your inquiry. I'll update the article to provide instructions on how to create the query. For now, enter the clause with `ID = @Follows` as shown below.  

![image](https://user-images.githubusercontent.com/10856840/178567343-d898a70c-71b1-4cca-a184-4dc6fc8cabaa.png)

**Comment by brika7** [comment]
> @brika7 - Thank you for your inquiry. I'll update the article to provide instructions on how to create the query. For now, enter the clause with `ID = @Follows` as shown below.
> 
> ![image](https://user-images.githubusercontent.com/10856840/178567343-d898a70c-71b1-4cca-a184-4dc6fc8cabaa.png)

Thank you! Also, I found another reference that indicates it is one of the options under the drop-down menu on the Work Items page in the top left corner: 
![image](https://user-images.githubusercontent.com/21017779/178581640-20dbb516-2d52-41fb-a08e-4e67e9b20ec9.png)

**Comment by KathrynEE** [comment]
CLosing this issue. Updated two articles.
