### ISSUE TITLE
Tags that start with @ cannot be queried

### ISSUE THREAD

**Issue by mahomedalid** [MicrosoftDocs/azure-devops-docs#12475]
Tags cannot start with @. As reported here https://developercommunity.visualstudio.com/t/Cannot-query-workitems-that-have-a-tag-t/10073439#T-ND10090041 tags cannot start with @, as this is a special character used for macros, and query those tags is impossible. At very least there should be a clear indication/warning here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf3ce0a-184f-ca49-5453-01317e23dde5
* Version Independent ID: 0af9b10e-1126-2fda-982b-63d5795f9213
* Content: [Add tags to work items to categorize lists and boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops)
* Content Source: [docs/boards/queries/add-tags-to-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/add-tags-to-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mahomedalid - Thank you for providing this feedback. I agree that we should document the restrictions on using tags in queries when using an @ symbol. I'll get this updated soon.

**Comment by mahomedalid** [comment]
Thank you for the promptly response @KathrynEE. Won't be better to close the issue once the updated documents get updated? It could be useful to use that status for tracking purposes.

**Comment by KathrynEE** [comment]
@mahomedalid - Reopening per your suggestion.

**Comment by mahomedalid** [comment]
This is really helpful @KathrynEE ! Thank you!

**Comment by KathrynEE** [comment]
Closing this issue as article has been updated.

**Comment by mahomedalid** [comment]
@KathrynEE  that is amazing, thank you!
