### ISSUE TITLE
`succeeded()` parameter is undocumented

### ISSUE THREAD

**Issue by Eonasdan** [MicrosoftDocs/azure-devops-docs#12470]
I couldn't find any documentation that indicated `succeeded` allowed a parameter reference to a particular job. E.g. `succeeded('JobName')`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by kohithms** [comment]
Ho @Eonasdan Those are system predefined methods for comparing/decision-making methods. I believe the system doesn't have any method which takes parameters as inputs.

**Comment by juliakm** [comment]
Thanks @kohithms! @Eonasdan `succeeded()` is a job status functions. You can learn more about it and other job status functions in our [expressions article](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#job-status-functions). They do not take arguments.
