### ISSUE TITLE
Azure Static Web App Task - output_location is RELATIVE to app_location, documentation should reflect that

### ISSUE THREAD

**Issue by Jawz84** [MicrosoftDocs/azure-devops-docs#12488]
[Enter feedback here]
Both in the `yml` snippet and in the explanation for all arguments, the `output_location` argument needs the remark that it is RELATIVE to the `app_location` folder.

```
output_location    Output location | (Optional) String. Directory location of the compiled application code after building. Specify this location _relative_ to the 'app_location'.
```

This has cost me 1,5 hours and countless pipeline runs today to figure that out. My app does not live in the root of the repo, for various reasons, and it was hard figuring out how to adapt the expample based on the explanation in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Version Independent ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Content: [Azure Static Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-static-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-static-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/azure-static-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by dzenis-zigo** [comment]
+1

**Comment by WilliamAntonRohm** [comment]
@Jawz84 -- Jos, thank you for your feedback, and apologies for the delay in responding.

@steved0x -- Steve, please review this update in [private PR 307](https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/307).

**Comment by steved0x** [comment]
We'll get this updated. In the YAML Syntax block, the comments reflect the name of that task input from the task designer (so it gets the value from the [task source code there](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureStaticWebAppV0/task.json#L39)) so they aren't editable (unless they get edited in the task itself), but the task input description is editable, so this has been updated there.

**Comment by steved0x** [comment]
We'll put a note in the remarks as well to really call it out.

**Comment by steved0x** [comment]
@Jawz84 To confirm, `output_location` is relative to `app_location` and not `workingDirectory`?  I want to make sure we have this correct. I am heading over to the task to check it out further, but that sounds like a possible bug in the task (unless I am misunderstanding).

**Comment by Jawz84** [comment]
I'd positively like to help but this is long ago for me. From memory: I believe it's not so much the task that's at fault, but the docs.
Thank you for taking a good look at this, appreciate it!
