### ISSUE TITLE
Is feature in preview or is it GA??

### ISSUE THREAD

**Issue by swieder** [MicrosoftDocs/azure-devops-docs#12486]
The Table of Contents says:  Extend Analytics with Odata (Preview).  but the article itself never mentions being in Preview.   Typically the word (Preview) is in the title of the article when it is in preview but this title is just:  "Extend Analytics with OData quick reference".

So is this still in Preview??  If so, what's that GA planned date??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287fee66-f430-efc8-ab4d-4479c3ecf361
* Version Independent ID: 648d575d-3256-ddf1-a92a-f1bbbdf5bc64
* Content: [Tasks & concepts using Data & Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/quick-ref?view=azure-devops)
* Content Source: [docs/report/extend-analytics/quick-ref.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/extend-analytics/quick-ref.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@swieder - Thank you for this inquiry. I checked with the Product Manager and he has indicated that the feature is no longer in Preview. I will update the content to reflect that in the coming days.

**Comment by KathrynEE** [comment]
@[swieder](https://github.com/swieder) - closing this issue as the TOC and articles have been updated to reflect that Analytics/Extend and OData are not in preview for  Azure DevOps Services and Azure DevOps Server 2020 and later versions.

**Comment by swieder** [comment]
Thank you!!

Thanks,
Steve Wiederrich
Mobile: 214-642-9333

**Comment by stevenoneill-jmfamily** [comment]
@swieder @KathrynEE -- when I enable this feature in a test org, it still has 'preview' messaging.  Can this message about 'prevew' be ignored?

![image](https://user-images.githubusercontent.com/50223480/181371626-9e1c4bc8-aab2-43ae-b094-76d8bd78fb77.png)

**Comment by KathrynEE** [comment]
@[stevenoneill-jmfamily](https://github.com/stevenoneill-jmfamily) - Yes , you can ignore this. I'll work on updating the other article on OData.  Analytics views continues to be under the Preview features set, but it works as described.

**Comment by stevenoneill-jmfamily** [comment]
"Analytics views continues to be under the Preview features set."

Help me understand I guess?  Are these statements accurate?

1. Analytics Views (preview) makes use of Analytics Service (production).

2. To make Analytics Service available for use in an Azure DevOps org, one must enable 'Analytics Views' for the whole org.

**Comment by KathrynEE** [comment]
@[stevenoneill-jmfamily](https://github.com/stevenoneill-jmfamily) - 1 is accurate. 2 is not. Enabling Analytics Views simply enables the Analytics views hub in the UI. Analytics is automatically enabled for all cloud organizations, and is enabled for on-prem according to https://docs.microsoft.com/en-us/azure/devops/report/dashboards/analytics-extension?view=azure-devops-2020.

**Comment by stevenoneill-jmfamily** [comment]
> @[stevenoneill-jmfamily](https://github.com/stevenoneill-jmfamily) - 1 is accurate. 2 is not. Enabling Analytics Views simply enables the Analytics views hub in the UI. Analytics is automatically enabled for all cloud organizations, and is enabled for on-prem according to https://docs.microsoft.com/en-us/azure/devops/report/dashboards/analytics-extension?view=azure-devops-2020.

That helps a ton, thank you @KathrynEE 

When is **Analytics Views** scheduled/anticipated to go GA?  That has also been in preview a long time it seems?
