### ISSUE TITLE
Closes https://github.com/microsoft/rushstack/issues/3047

### ISSUE THREAD

**Issue by Azooz2538** [MicrosoftDocs/azure-devops-docs#12491]
Closes https://github.com/microsoft/rushstack/issues/3047
Chat room: https://rushstack.zulipchat.com/#narrow/stream/279883-contributor-helpline/topic/.5Brush.5D.20Request.20for.20bump.20type.20even.20if.20the.20policy.20is.20lockedVe/near/263324638

## Summary

The change is fully backwards compatible.
`rush publish -a` reads the changefiles and bumps the package versions, but only works with `individualVersion` policies.
I'm changing that to also update a package set for `lockStepVersion` when no `bumpType` is specified.

## Details

In order to achieve this I did the following changes:
- `bumpType` is now optional for the `lockStepVersion` policies (including schema changes)
  > when `bumpType` is not empty there is no behavior change in any of the following comands (fully backwards compatible)
- `rush version --bump` now ignores all `lockStepVersion` that have no `bumpType` (same as `individualVersion`)
- `rush change`: if a package has a policy of `lockStepVersion without bumpType`, it will prompt the question about the scope of the change
  > by doing this, we get the changeType information that we can use later to programatically determine the `bumpType`
- added `none` as a type of change from the UI (it was only available when using `--bulk` but fully supported in the code)
  > ![image](https://user-images.githubusercontent.com/10807051/144472876-7a612bd7-64e1-4340-871a-4dfde9c23b9b.png)
- `rush publish -a` will now:
  - iterate over the changes and detect the proper `ChangeType` for each policy (`lockStepVersion without bumpType`)
  - bump all the projects from the updated policies to the new version
  - update the `version-policies.json` file with the new version

## How it was tested

I did a small repository following this structure to test:

- `@ui/core` (no dependencies, policy UI)
- `@ui/components` (depends on `@ui/core`, policy UI)
- `@data/core` (no dependencies, policy DATA)
- `@data/react` (depends on `@data/core`, policy DATA)
- `widget1` (depends on all `data` and `ui` packages, policy WIDGETS)
- `widget2` (depends on all `data` and `ui` packages, policy WIDGETS)

With the following policies:

```json
{
    "definitionName": "lockStepVersion",
    "policyName": "UI",
    "version": "0.1100.0"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "DATA",
    "version": "0.1200.0"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "WIDGETS",
    "version": "0.1300.0"
  }
```

In this example, changing @ui/components will prompt for the change type and when running `rush publish -a` it will also bump @ui/core and set the version-policies.json file. Widget projects (downstream) will also update because they depend on @ui too.

__Originally posted by @isc30 in https://github.com/microsoft/rushstack/pull/1.1.200

**Comment by WilliamAntonRohm** [comment]
@Azooz2538 -- Azooz, thank you for this contribution!

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
