### ISSUE TITLE
Install link says `Maven Apache` instead of `Apache Maven`

### ISSUE THREAD

**Issue by raydixon** [MicrosoftDocs/azure-devops-docs#12493]
**Steps to Repro**

1. Go to [Get started with Maven packages and Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven).
2. In the [Prerequisites](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#prerequisites) section, observe the text for the link to the download page for _Apache Maven_.

**Expected Results**
The text of the link refers to the product name as _Apache Maven_.

**Actual Results**
The text of the link is `Install Maven Apache`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b7f1e-c844-54ae-97b8-de3e033d9dbd
* Version Independent ID: b9e49894-7cb8-6305-01ef-983135e1c62a
* Content: [Get started with Maven packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops#feedback)
* Content Source: [docs/artifacts/get-started-maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/get-started-maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@raydixon -- Ray, thank you for catching this and for your PR.

@ramiMSFT -- Rami, please review [public PR 12494](https://github.com/MicrosoftDocs/azure-devops-docs/pull/12494).

**Comment by ramiMSFT** [comment]
@raydixon Thank you for your feedback and your contribution!
