### ISSUE TITLE
Ambiguity in argument names

### ISSUE THREAD

**Issue by taypo** [MicrosoftDocs/azure-devops-docs#12501]
Argument names in the yaml snippet and the table below do not match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81921de1-7801-99b8-30ff-92530ceb49b2
* Version Independent ID: 50fb21ad-2049-fd80-db73-3d78c305cdac
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@taypo -- Bahadır, thank you for your feedback.  Most argument names have an alias, which is listed in each description.  For example, see the description for `mavenPOMFile`, which has an alias `mavenPomFile`:
- [Arguments](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven?view=azure-devops#arguments)
