### ISSUE TITLE
SLA for Parallelism Provision

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#12506]
[Enter feedback here]

Hi,
I'm from the CSS team and have a cx that noticed a 30 min + delay from the time of his purchase till the parallelism was provisioned for him. Could we please have the delay/SLA documented here? I also reached out to the PM who agreed this needs to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @kripa-2019! I'll add a note.
