### ISSUE TITLE
Documentation still lacking...

### ISSUE THREAD

**Issue by boblechat** [MicrosoftDocs/azure-devops-docs#12511]
Hi,

I've been looking for a way to manage approvals and checks on my AzDo environments using the client libraries.
Of course, I had no hit on this documentation, nor on StackOverflow...

Fortunately, every decent web browser now contains a _web developer tool_ which allows us to find a way on how to use your libraries and REST APIs.

So, would you be so kind to add in your documentation the **Microsoft.Azure.Pipelines.Policy.Client** package?
Could you also explain why this is the only package that has only .NET Framewrok (4.6.2) dependencies and not .NET Standard?
May I also impose on your kindness by asking you to add a few samples? Because it took me a few tries to put together the following classes: `ApprovalSettings`, `ApprovalConfigSettings`, `ApprovalCheckConfiguration` or `CheckType `(this one was particularly challenging as the Guid was hardcoded in the REST API call).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@boblechat -- Bob, thank you for your feedback.  Please consider this resource:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 


@chcomley -- Chrystal, please look into this issue.

**Comment by ransagy** [comment]
This was closed, But none of the questions here were answered?
I've came across a need to use the policy APIs as well, and this is the only client provided.
Are there any actual details to the OP's questions?

**Comment by StingyJack** [comment]
@boblechat 
[Approvals and Checks REST API reference](https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/approvals?view=azure-devops-rest-7.0)

I dont see anything in the .net client libraries regarding Approvals and Checks

@ransagy 
"Policy API's" could be referring to a few things, but if it exists, its probably one of [these](https://learn.microsoft.com/en-us/search/?scope=REST&view=azure-devops-rest-7.0&terms=Policy&expanded=%2Fdevrel%2F68ec7f3a-2bc6-459f-b959-19beb729907d&products=%2Fdevrel%2F5bd2b3fa-c186-4b92-a3c8-09f22a249d37) 

There are several "Policy" things in the .net client libraries, Not sure which one you are looking for but ILSpy/DotPeek/Object Browser should help you locate the one you need.

**Comment by ransagy** [comment]
@StingyJack At least in my case, the request for documentation/examples and not to explain the product's workings or technical design decisions for the APIs.
I _think_ i ended up using two APIs (git policy configurations and PR policy evaluations) strictly through REST and own-made POCOs because anything official was very lacking in those areas.
