### ISSUE TITLE
Add Agent.Diagnostic variable

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#12514]
A new variable named Agent.Diagnostic is now showing up in the YAML pipeline Run dialog under the Variables section. I'm unable to find any description regarding the effect of setting this variable's value to true or false.

Please add explanation of the Agent.Diagnostic variable to this page.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- Thomas, thank you again for your keen eye.

@juliakm -- Julia, please look into this variable.

**Comment by steved0x** [comment]
The addition of this variable is going live today.
