### ISSUE TITLE
Deployment control is absent for Azure DevOps Server 2019 Version

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#12516]
The deployment option is not present in Azure DevOps server 2019 version as depicted in the doc : 
![image](https://user-images.githubusercontent.com/47343377/180881388-7daec383-cd40-4869-996b-deb0a3d87574.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba7c85b2-fb57-aefe-af67-fcdcbb94e595
* Version Independent ID: ea532ac5-f00b-d570-80b4-781190c9b4ed
* Content: [Link work items to support traceability in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-work-items-support-traceability?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/queries/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/link-work-items-support-traceability.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@[kripa-2019](https://github.com/kripa-2019) - Thank you for providing this information. I'll update the article this week.

**Comment by KathrynEE** [comment]
@kripa-2019 - Upon review of the article, the image you show above doesn't show when you select the content version selector for Azure DevOps Server 2019.  Here is the image shown in that case: 

![image](https://user-images.githubusercontent.com/10856840/181117025-f6303790-d458-4ab4-b666-ccf707c731b5.png)
 
 I'm closing this issue as addressed.

**Comment by kripa-2019** [comment]
https://docs.microsoft.com/en-us/azure/devops/boards/queries/link-work-items-support-traceability?view=azure-devops-2019&tabs=browser#work-items-linked-to-git-code-development

Navigate to the link above. You can see I have the selector as 2019. My screen shot is from the sub-topic I have linked above. 

(Scroll down to - "Work items linked to Git code development" - you will notice the screenshot that I previously attached)

**Comment by KathrynEE** [comment]
@kripa-2019 - Thanks for the additional info. I see the issue now and am correcting it in this article and this one as well: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/connect-work-items-to-git-dev-ops?view=azure-devops-2019.
