### ISSUE TITLE
Inconsistent targetPath vs. Destination Folder

### ISSUE THREAD

**Issue by diegum** [MicrosoftDocs/azure-devops-docs#12522]
Notice that the *YAML snippet* has a `targetPath` input, while the *Arguments* section lists a `Destination Folder` entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd94385e-60ae-d9ca-be76-ee7f97f3dfde
* Version Independent ID: 03eeae39-e3be-b10f-0ee5-9b8a312aae98
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@diegum -- Diego, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
