### ISSUE TITLE
Mismatched parameter name

### ISSUE THREAD

**Issue by mikeb-ah** [MicrosoftDocs/azure-devops-docs#12521]
The "Example" names the Working Directory parameter as **workingDirectory**, but the "Arguments" block names it as **cwd**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcfcf6fc-d48d-4758-06e4-df7235aa3f9d
* Version Independent ID: 6a0ddf0d-221a-9cfd-9602-34614a43ed61
* Content: [CMake build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/cmake?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/cmake.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/cmake.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
