### ISSUE TITLE
Incorrect Value Documented

### ISSUE THREAD

**Issue by mickey-philips** [MicrosoftDocs/azure-devops-docs#12530]
[Enter feedback here]
The correct value for Release.Reason on a schedule is "Schedule" and not "Scheduled"  as documented:
From the agent log:
RELEASE_REASON                 Schedule 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 810b2ae0-ebbc-9fe0-fabb-700a57f20c9d
* Version Independent ID: 3ba38edc-4990-5ef5-c10e-79f1be686d3f
* Content: [Classic release and artifacts variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
