### ISSUE TITLE
Support Case link provides a bot service but loops

### ISSUE THREAD

**Issue by Donovand4** [MicrosoftDocs/azure-devops-docs#12536]
The support case link for the below prerequisite provides a bot service but does not provide any method of raising a ticket after answering all the questions from the bot. 

Have 100 or fewer users in your organization. If your organization has more than 100 users, [contact Support](https://azure.microsoft.com/support/devops/) for help with connecting to Azure AD.

Customer provided a demo and the bot appears to loop back to the article to raise a support ticket which opens up the bot.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@Donovand4 -- Donovan, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
