### ISSUE TITLE
Issue in querying the bugs closed in last week

### ISSUE THREAD

**Issue by hemanth1504** [MicrosoftDocs/azure-devops-docs#12535]
[Enter feedback here]

---
#### Document Details
i need bugs closed in last week im using query 

- workitemtype = Bug
and
-  closed >= StartOfWeek - 1

the result is its listing the bugs which are closed today

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @hemanth1504
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@hemanth1504 -- thank you for your feedback.  Please try `closed >= StartOfWeek - 7` instead, and let me know if that works for you.

**Comment by hemanth1504** [comment]
Its giving the result for past 7weeks

**Comment by WilliamAntonRohm** [comment]
@hemanth1504 -- thank you for your follow-up.  Please try `closed >= Today - 7`.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
