### ISSUE TITLE
SVG Images are supported

### ISSUE THREAD

**Issue by DougboGodsoe** [MicrosoftDocs/azure-devops-docs#12542]
[Enter feedback here]
There is a tip on this page that says SVG files are not supported in Azure Devops Wiki, but they are now supported.

https://developercommunity.visualstudio.com/t/referenced-svg-images-dont-work-in-azure-devops-wi/619280

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Tip reads: We don't support SVG file types.

Just before _Checklist or task list_.

**Comment by chcomley** [comment]
Thanks for your feedback, @DougboGodsoe. When my update goes live, this issue will automatically close. Have a great day!

**Comment by MB175** [comment]
SVG files still don't work in the markdown renderer ?
