### ISSUE TITLE
Missing Custom properties documentation

### ISSUE THREAD

**Issue by selism** [MicrosoftDocs/azure-devops-docs#12543]
What about the "Custom properties" argument of this task?
There is no explanation on what it's for, and (more important) how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
@selism `properties` is used to add custom properties to associate with your published artifact. I'm adding an example to the article shortly.

**Comment by ryanhubbell** [comment]
Was this ever updated anywhere? I can't find any documentation on how to use custom properties on pipeline artifacts.

**Comment by Oskar1818** [comment]
I agree with @ryanhubbell there’s no documentation available and it’s not clear how to use. @ramiMSFT

**Comment by zola-25** [comment]
I'm also wondering this too. It's hugely frustrating. 

@ramiMSFT
