### ISSUE TITLE
vsts-npm-auth assumptions

### ISSUE THREAD

**Issue by reecebradley** [MicrosoftDocs/azure-devops-docs#12551]
I am in the process of authoring guidance for my organization due to what I think is a false assumption that breaks tooling.

Running this command:

```ps1
vsts-npm-auth -config .npmrc
```

Outputs a `.npmrc` file that has stored credentials but not in the location the documentation states: `%USERPROFILE%/.npmrc`, `~/.npmrc` or `$HOME/.npmrc`

Instead, in the `vsts-npm-auth` source code:

```csharp
public string UserHomeDrive => this.IsUnixStylePlatform ? Environment.GetEnvironmentVariable("HOME") : Environment.GetEnvironmentVariable("HOMEDRIVE") + Environment.GetEnvironmentVariable("HOMEPATH");
```

So an organization may have this set to `HOMEDRIVE=U:` and `HOMEPATH=\`. Which is not the same as `USERPROFILE`. You would have to be keen on paying attention to the command's output because it does say it wrote to `U:\.npmrc`. The reason why this is a problem won't become immediately apparent until you run `npm install` and get unauthorized. NPM doesn't look at `HOMEDRIVE` or `HOMEPATH`, you can observe it via `npm config ls` and it will say `HOME = c:\users\jdoe` and also `; "user" config from C:\Users\jdoe\.npmrc`.

To avoid the potential problem altogether, I am recommending to run the tool as:

```ps1
vsts-npm-auth -c ".\.npmrc" -v Detailed -t "$HOME\.npmrc"
```

Unless someone can change the defaults in `vsts-npm-auth`. Or perhaps explain the `TargetConfig` a little more in detail and what it assumes and the approach to override it.

Thank you for your time.
Reece

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows%2Cclassic)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@reecebradley -- Reece, thank you for your well-researched feedback.  For your suggestion regarding "change the defaults in vsts-npm-auth", please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

@ramiMSFT -- Rami, please look into this potential documentation issue.

**Comment by reecebradley** [comment]
I did as suggested @WilliamAntonRohm 
Here is my post: https://developercommunity.visualstudio.com/t/vsts-npm-auth-uses-HOMEDRIVE--HOMEPATH/10112804?space=21&q=vsts-npm-auth

**Comment by ramiMSFT** [comment]
@reecebradley Thank you for your feedback! I'm updating the command shortly.
