### ISSUE TITLE
powershell task verbosePreference parameter does not work

### ISSUE THREAD

**Issue by yangxinyun** [MicrosoftDocs/azure-devops-docs#12556]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops-2019&fireglass_rsn=true#fireglass_params&tabid=a72a3d8c170676b3&start_with_session_counter=3&application_server_address=euroclear11.prod.fire.glass

following setting takes no effect on the job's powershell session configuration
- task: PowerShell@2
  inputs:
    verbosePreference:  continue

**Comment by WilliamAntonRohm** [comment]
@yangxinyun -- Xinyun, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
