### ISSUE TITLE
Azure Repos "sign in" doesn't work as expected

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/azure-devops-docs#12555]
When I follow the instructions on this page, I perform the `@azure repos signin` step. After I've selected my user name, I see a "Signing-in..." dialog that shows indefinitely and doesn't progress anywhere.

![image](https://user-images.githubusercontent.com/40315783/183050918-417e5ab9-2205-4f13-97fa-4f18728aa446.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
[drk-mtr](https://github.com/drk-mtr) - Thank you for raising this issue. However, this appears to a problem with the produce or service and not the documentation. Please raise your issue on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=problem).
