### ISSUE TITLE
Resource URL incorrect for build.complete event message

### ISSUE THREAD

**Issue by missymessa** [MicrosoftDocs/azure-devops-docs#12550]
The Resource URL in the documentation contains a URL with `_apis/build-release`, however, real event messages we are getting contain `_apis/build` not `_apis/build-release`. In order to avoid confusion, this should be corrected. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- Chrystal, please review this update in [private PR 4930](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4930).

**Comment by WilliamAntonRohm** [comment]
@missymessa -- Missy, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
