### ISSUE TITLE
Migration of team boards

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#12569]
Hello,

This topic is not included in this thread. Is it possible to migrate Team Boards from one project to another (in different org)?
Or we can just migrate processes and work items, but team board needs to be recreated manually?

Many thanks!
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0946a25-5ea9-376e-be4e-679491fd2fa0
* Version Independent ID: 43473d55-c342-f9ff-3a24-bff441af8600
* Content: [Migrate to or integrate work tracking data in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/migrate-integrate?view=azure-devops)
* Content Source: [docs/boards/extensions/migrate-integrate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/extensions/migrate-integrate.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@roofiq - Thank you for your inquiry. You can only migrate work items from one project to another. All work item IDs will be updated. You can't migrate teams or team configuration. However, if you're working in the cloud, you may find the [azure cli commands](https://docs.microsoft.com/en-us/azure/devops/cli/quick-reference?view=azure-devops#azure-boards) useful in capturing the details of a team and then recreating the teams in the new project.
