### ISSUE TITLE
Include naturally related requirements for VSTest@2 Task

### ISSUE THREAD

**Issue by d-vs** [MicrosoftDocs/azure-devops-docs#12563]
Very helpful page, but would be far better if the information that will naturally be required next would be included, namely what is then needed to use this tool to run the unit tests. This information is not easy to come by, but is specified in this other documentation, for the `vsTestVersion` property: 

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#arguments

The result is that the VSTest@2 task requires:

```json
vsTestVersion: 'toolsInstaller'
```

Would save many people like myself a lot of trouble.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d8b59f-3c05-9934-c385-9c1939bafd5f
* Version Independent ID: 3659a0ba-aa8e-d1a2-1527-accce4927bc5
* Content: [Visual Studio Test Platform Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/tasks/tool/vstest-platform-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/tool/vstest-platform-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
@d-vs -- Devious, thank you for your clear feedback.


@shashban -- Shashank, please look into this issue.
