### ISSUE TITLE
Tip: You can create an empty environment and reference it from deployment jobs

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/azure-devops-docs#12568]
The document contains this tip:

"Tip: You can create an empty environment and reference it from deployment jobs"

I would like to do that, meaning I would like to run a deployment job that does not actually move any files but just records the deployment.

However, when I try, I get the error:

"No resource were found in the environment with ID 24 matching the specified criteria: ResourceId , ResourceName , ResourceType VirtualMachine, Tags ."

Where can I find more information about using empty environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by tripleacoder** [comment]
I found out why it did not work.

I had specified

environment: 
          name: 'Empty environment'
          resourceType: VirtualMachine

After I deleted resourceType, it worked.

**Comment by WilliamAntonRohm** [comment]
@tripleacoder -- thank you for your feedback and solution :^)
