### ISSUE TITLE
Setting --default values with the given command is invalid

### ISSUE THREAD

**Issue by sujitsneb** [MicrosoftDocs/azure-devops-docs#12577]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by sujitsneb** [comment]
Following Command should be: 
From >> az devops configure --defaults organization=https://dev.azure.com/contoso project=ContosoWebApp 
**>> Error: usage error: invalid default value setup. Supported values are ['organization', 'project'].**

To >> az devops configure --defaults organization='https://dev.azure.com/contoso', project='ContosoWebApp'

**Comment by KathrynEE** [comment]
@sujitsneb - Thank you for your feedback. I investigated this issue and didn't receive an error. The command works as documented. The only time you need to enclose an organization or project in quote marks is when there is a space within the entry.  If you still consider this an issue, please submit it on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=problem). 

Closing this as not actionable.
