### ISSUE TITLE
Can I import a CSV file that has parent-child links?

### ISSUE THREAD

**Issue by SparkyUX** [MicrosoftDocs/azure-devops-docs#12572]
The import fails if you use Task1 and Task2 for headings as shown in your example. I changed them both to Title and the import worked. I was adding tasks to PBIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items in bulk by using CSV files - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SparkyUX - Thank you for your inquiry. I'm not seeing Task 1 or Task 2 in the examples documented. If you are importing a hierarchy of work items, then the example shows to use Title 1 and Title 2, as indicated in this section, [Can I import a CSV file that has parent-child links?](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#can-i-import-a-csv-file-that-has-parent-child-links). 

I'm closing this issue as I don't believe there are any updates or corrections to make. If there are specific areas of the article that you believe are in error, please feel free to reopen this and add the information. Again, thanks for your inquiry.

**Comment by SparkyUX** [comment]
I should have said Title1 and Title2 not task1 and task2.

**Comment by KathrynEE** [comment]
[SparkyUX](https://github.com/SparkyUX) - Thanks for the clarification. I'll update the article to use Title and TItle, instead of Title 1 and Title 2.
