### ISSUE TITLE
Two doc bugs - validate command and azure storage region missing UKS.

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/azure-devops-docs#12573]
Hello Team,

With ADO Server 2020.1.1 and ADO Server 2020.1.2 validate command example will not work for the basic validate command:
"Because this is your first time validating a collection, let's keep it simple. Your command should have the following structure:
cmdline
**Migrator validate /collection:{collection URL}** 
Now it is mandatory to provide tenantDomainName.

Second doc issue is with Azure DevOps and Azure Storage account regions:

Azure DevOps:
United States | Central United States | CUS
Europe | Western Europe | WEU
**United Kingdom | United Kingdom South | UKS**
Australia | Australia East | EAU
South America | Brazil South | SBR
Asia Pacific | South India | MA
Asia Pacific | Southeast Asia (Singapore) | SEA
Canada | Central Canada | CC

Azure Storage account regions: 
Desired import region | Storage account region
Central United States | Central United States
Western Europe | Western Europe
Australia East | Australia East
Brazil South | Brazil South
India South | India South
Canada Central | Canada Central
Asia Pacific (Singapore) | Asia Pacific (Singapore)

There is no entry for **United Kingdom | United Kingdom South | UKS**

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#step-3-upload-the-dacpac-file)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Ahetejaz** [comment]
@KathrynEE fyi.

**Comment by sheetalsk17** [comment]
Hello @KathrynEE and @WilliamAntonRohm 
Hope you both are doing well.
Please provide an update on the doc bug.
Thanks, Sheetal
Cc: @Ahetejaz

**Comment by KathrynEE** [comment]
@Ahetejaz, @sheetalsk17  - I'm closing this issue as I've opened a Bug, [Bug 1978987](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1978987): Validation and import processes [Update] to track the issue. In the future, please open a Bug in the [TechnicalContent project](https://dev.azure.com/mseng/TechnicalContent/) and assign the Area path to /TechnicalContent/Azure DevOps. Thanks.
