### ISSUE TITLE
What access does Visual Studio Dev Essentials give to Azure DevOps Server

### ISSUE THREAD

**Issue by ToreDemant** [MicrosoftDocs/azure-devops-docs#12583]
Could you help me clarify what Access Level the (free) Visual Studio Dev Essentials entitles to?

I am in doubt if the Visual Studio Dev Essentials makes people eligible to access Azure DevOps Server. On this on-prem version of Azure DevOps we need to register the license manually as there are no automatic functionality that automatically senses licenses.

Previously I would say no as it is a free 'subscription' that you can just click to get, but "Azure DevOps - basic level" is now listed as a benefit on my.visualstudio.com/subscription:
![image](https://user-images.githubusercontent.com/51123426/184885314-bafc5c47-45bd-4058-9c92-af97d8d1fa6b.png)

Page "About access levels" says "and to users for whom you're paying for Basic access in an organization"
https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops-2020

Terms and Conditions does not mention this either:
https://visualstudio.microsoft.com/license-terms/devessentials/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [About access levels - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops-2020)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ToreDemant - Thank you for your inquiry. According to this page, [Visual Studio Dev Essentials](https://visualstudio.microsoft.com/dev-essentials/), the benefits listed are for Azure cloud services. So, it doesn't extend to Azure DevOps on-premises.

**Comment by ToreDemant** [comment]
Hi @KathrynEE 

Thank you for a quick answer.

My confusion revolves from the fact that the screenshot says that it includes "Azure DevOps Basic Level" and the access level page says ", and to users for whom you're paying for Basic access in an organization.". I guess the word "paying" is key here but easily missed.
