### ISSUE TITLE
Delivery Plans 2.0 dependency question

### ISSUE THREAD

**Issue by neustupa** [MicrosoftDocs/azure-devops-docs#12581]
Hello. 

I was recently reading a new release notes for Azure DevOps Server 2022 RC1 [here](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2022?view=azure-devops#delivery-plans), where I stumble upon this image:
<img width="352" alt="187-boards-04" src="https://user-images.githubusercontent.com/43957815/184576416-04ca6b79-959b-4b1d-af8c-24ed12143f91.png">

I would like to ask what is the dependency with the "badge ribbon like" icon with text "Top Customer Asks" ? I cannot find it as the  work item in ADOS and according to the context of the image the object which the mentioned icon represents looks something like an insight for the epic. Is this a new WI or its some kind of custom process template modification which was used for the image? 

Reason I am asking this is because we are looking for insights tracking in relation to epics or features like in Product Board and it would be really cool if we can do that without integrating Product Board with ADOS. 

Thank you very much for any response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d30dee-f1ca-f648-defa-87b8f394cac4
* Version Independent ID: b518d1be-9ad4-7cc2-bb29-330ec693b598
* Content: [Track dependencies by using Delivery Plans in Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/track-dependencies?view=azure-devops)
* Content Source: [docs/boards/plans/track-dependencies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/plans/track-dependencies.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
[neustupa](https://github.com/neustupa) - Thank you for your inquiry. The "badge ribbon like" icon with text "Top Customer Asks" indicates that it is a Parent of Delivery Plans 2.0 which in turn is a Parent of Delivery Plans 2.0: Dependency Tracker.  In this case, the work item types are: 
- Initiative (custom work item type): Top Customer Asks
- Epic: Delivery Plans 2.0
- Feature: Delivery Plans 2.0: Dependency Tracker

To learn more about adding custom work item types as a portfolio backlog, see [Customize your backlogs or boards (Inheritance process)](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops).

**Comment by neustupa** [comment]
Thank you kindly for your fast response.
Excellent.

Kind regards.
