### ISSUE TITLE
The "important" note in the "Secret variable in the UI" section is misleading

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#12580]
It says...
> We never mask substrings of secrets. If, for example, "abc123" is set as a secret, "abc" isn't masked from the logs. This is to avoid masking secrets at too granular of a level, making the logs unreadable. 

While this message is in a specific section, it speaks as if it applies to any log masking, whether the secret is entered from the UI or Azure Key Vault.  

When using the Azure Key Vault task, even secret values like the number `2`  are masked throughout the logs. See [this issue](https://github.com/microsoft/azure-pipelines-agent/issues/1207#issuecomment-1066023954) for more information. (this handling does make the logs quite unreadable, **and allows those reading the logs to correctly infer the values of some secrets**).

Whether that is correctly deemed as a bug and fixed* or not, this article should have that Information note updated to clarify the scope its speaking of, or a similar note added to the Azure Key Vault task section that describes the current behavior, or both, or some other clarifying information added to the article so that its clear what organizations should be doing with regard to secret value handling. 

_* this is allowing those without access to the secret values to be able to guess them based on the masking in the logs, so I would have expected it to be fixed right away but it seems to have stalled. A bump would be appreciated._

> For this reason, secrets should not contain structured data. If, for example, "{ "foo": "bar" }" is set as a secret, "bar" isn't masked from the logs

What is masked in the logs then?  Any string that matches `{"foo": "bar" }` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c23ec51-0ccb-6fb1-52fb-7250284b807f
* Version Independent ID: 4c23ec51-0ccb-6fb1-52fb-7250284b807f
* Content: [Set secret variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash)
* Content Source: [docs/pipelines/process/set-secret-variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/set-secret-variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by dtmdl** [comment]
Note that 'abc' is a substring of the secret 'abc123'.

If the string 'abc' appears in the output, then the output is a substring of the secret, so it will not be masked.

If the string 'zyxabc123456' appears in the output, then the secret 'abc123' is a substring of the output and will be masked.

If the secret is '2' there are no possible (non-empty) substrings of the secret.

If the output contains 'abc123xyz', then the secret '2' is a substring of the output and will be masked.

**Comment by StingyJack** [comment]
> If the string 'abc' appears in the output, then the output is a substring of the secret, so it will not be masked.
> If the output contains 'abc123xyz', then the secret '2' is a substring of the output and will be masked.

Excerpt from a recent pipeline's NPM install task. From this, I know that some of the secret values are the number 2 and the string "Dev".  If I look up the task version at the time this pipeline executed it would mean that "8" is a secret (version is 1.208.9) . The number 32 by itself may be a secret since its replaced by a single `***`
```
Starting: npm install
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.***0***.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/***ops/pipelines/tasks/package/npm
==============================================================================
C:\Windows\system***\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" --version" npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead. 8.11.0
```
And this is a short

**Comment by juliakm** [comment]
Reassigning to @geekzter since it sounds like this has been discussed in other places.
