### ISSUE TITLE
Note for Azure DevOps Auditing Still Being in Public Preview

### ISSUE THREAD

**Issue by SCsnwbrdr** [MicrosoftDocs/azure-devops-docs#12596]
Good Afternoon!

I have found multiple announcements on other platforms that the auditing piece is GA and there are no warnings in the Azure DevOps portal that auditing is still in preview. Is the note "Auditing is still in public preview" still accurate? Can the note be removed if it went GA?

Thank you!

Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2863bab9-d62b-d142-ae00-025ecbe174dd
* Version Independent ID: 4d20496b-f17f-d8c2-895e-6d091d1b08dc
* Content: [Access, export, filter audit logs for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/audit/azure-devops-auditing?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/audit/azure-devops-auditing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/audit/azure-devops-auditing.md)
* Product: **devops**
* Technology: **devops-audit**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @SCsnwbrdr, thanks for reaching out. No, Azure DevOps Auditing is not yet GA. It is still in Public Preview. 
You can keep your eye on the following reliable resources for up-to-date information:

- [Azure DevOps blog](https://devblogs.microsoft.com/devops/)
- [Azure DevOps Feature Timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline)

Thank you! Please @mention me if you have any further questions! Have a great day!

**Comment by SCsnwbrdr** [comment]
Hi @chcomley, Thanks for the update! Are there any details around what that feature being in preview means specifically? We had our security team flag it as a potential concern that we couldn't use the feature for SOC compliance activities for providing evidence to auditors that certain processes were being followed.

**Comment by chcomley** [comment]
Hi @SCsnwbrdr, I've reached out to my PM and will be in touch ASAP. Thank you.

**Comment by chcomley** [comment]
Hi @SCsnwbrdr, so in theory, being in "preview" means the feature may change before it becomes GA. For auditing specifically, the only reason we haven’t made it to GA is that there are a couple of important bugs we're fixing. My PM doesn't know when we'll get to GA. This is all the information I have; I hope it helps. Thank you!

**Comment by SCsnwbrdr** [comment]
Thank you @chcomley! I'll let our security team know.
