### ISSUE TITLE
Several of the documented mermaid diagram types don't work

### ISSUE THREAD

**Issue by feustpat** [MicrosoftDocs/azure-devops-docs#12597]
I'm unable to create several mermaid diagram types in the Wiki, namely:

- Pie charts
- Requirement diagrams
- State diagrams
- User Journey

Instead, I get the following message: `Unsupported diagram type.`

[Here](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page), you describe that these diagram types are supported. This was also announced with the [release notes of Sprint 200 (February 28, 2022)](https://docs.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-200-update#support-for-additional-diagram-types-in-wiki-pages) but never went really live for us (or was rolled back).

Could you provide a screenshot from the Wiki of a rendered Pie Chart, Requirements Diagram or State Diagram with the related mermaid code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @feustpat, thanks for reaching out. I'm going to do some research and get back to you early next week, thank you so much. Enjoy your weekend.

**Comment by chcomley** [comment]
@feustpat, I've followed up again today. Thanks!

**Comment by feustpat** [comment]
@chcomley Thx. Any news on this? I'd still be interested :)

**Comment by chcomley** [comment]
Hi @feustpat, I've been introduced to a PM and am awaiting their feedback. If I don't hear back by EOD Friday, I'll re-ping. I know this is frustrating, thank you for your patience. Have a great day.

**Comment by chcomley** [comment]
Re-pinged

**Comment by manuelaen** [comment]
@chcomley - thank you for investigating this! Just wanted to hop on the thread to say that I'm also very interested in getting support for all types of Mermaid diagrams, especially class diagrams which would aid in building up our team's documentation.

**Comment by dbollish1** [comment]
I am also having the same issue with creating stateDiagrams with sprint 209 version of Azure DevOps Service. Any update would be appreciated.

**Comment by chcomley** [comment]
Hi all, Adding @bjanousek for input, thank you for your patience.

**Comment by bjanousek** [comment]
Hello all, I'll update as soon as update is available from the team

**Comment by bjanousek** [comment]
We've added support for the following diagram types:
- Flow chart
- Class diagram
- State diagrams
- User Journey
- Pie charts
- Requirement diagrams

In addition we've added support for the two experimental diagrams (To use this requires a flag to be switched on):
- Git graph
- ER diagrams

This will be available in the OnPrem server 2022 and in a few weeks in the hosted Azure DevOps.

**Comment by chcomley** [comment]
Hi all, I've tested the following diagram types myself and they aren't working for me either:
•	User journey
•	State diagram
•	Pie chart
•	Requirement
I've removed these diagram types from the published article until we can confirm that they actually function in Azure DevOps. Once the update goes live, it will automatically close this issue.
There are many [active requests in the Developer Community](https://developercommunity.visualstudio.com/search?space=21&q=mermaid&stateGroup=active), which you can upvote if you feel it's appropriate. When I get more information, I'll reply to this issue. When we add more diagram types to the article, I'll add working examples as well. 

I'm sorry for the inconvenience you've been experiencing.

**Comment by bjanousek** [comment]
@chcomley - Can you confirm where you've been testing this? It may not have been deployed to your instance yet.

**Comment by BitawareUnleashed** [comment]
I'm sorry but the classDiagram doesn't work. The message is:  **Unsupported diagram type.**

**Comment by bjanousek** [comment]
@BitawareUnleashed - in what org you're seeing this? The functionality may not be yet available in your org due to usual deployment scheme. It takes couple of weeks before the functionality is available to everyone.

**Comment by BitawareUnleashed** [comment]
> @BitawareUnleashed - in what org you're seeing this? The functionality may not be yet available in your org due to usual deployment scheme. It takes couple of weeks before the functionality is available to everyone.

Ok thank you for info. My organization is a corporate.
