### ISSUE TITLE
Outdated RestApi

### ISSUE THREAD

**Issue by zioalex** [MicrosoftDocs/azure-devops-docs#12602]
Hi,
according to https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/universal/update-package-version?view=azure-devops-rest-6.0 the RestAPI to promote a package view is different from what documented at least for the universalpackage.

Please update the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e5618c-1223-3699-3dc6-24caeabeb9fc
* Version Independent ID: e8ea6291-0eee-825f-64fa-48ca5abd49bb
* Content: [Use feed views to share packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops&tabs=new-nav&source=docs#use-release-views-with-continuous-integrationdelivery)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@zioalex Thanks for your feedback! Will get those updated
