### ISSUE TITLE
Contradictory statements about work item query permissions

### ISSUE THREAD

**Issue by azuwani** [MicrosoftDocs/azure-devops-docs#12606]
At the beginning of this page, it's stated:

> All users, **except those users assigned to the Readers group**, can create and edit their own queries and save them under My Queries. Only the signed in user can view queries saved under their My Queries space.

But in the [Default query permissions table](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops#default-query-permissions), there is a ✔️ mark for the "Create and save managed My queries, query charts" task under both _Readers_ and _Contributors_.

That ✔️ for _Readers_ contradicts **this** part of the initial statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions in Azure Boards and Azure DevOps - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/set-query-permissions.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@azuwani - Thank you for this feedback. Readers don't have permissions to create and save queries. I will update the article today.
