### ISSUE TITLE
Project is created in .NET 6 but UseDotNet@2 is utilizing NET 5 preview version. Also .NET 5 is no more a preview version.

### ISSUE THREAD

**Issue by rijwanansari** [MicrosoftDocs/azure-devops-docs#12619]
Web app is created using .NET 6 but UseDotNet@2 is utilizing NET 5 preview version. 

![image](https://user-images.githubusercontent.com/25387035/186692579-f8e79df9-2b1b-48f1-8c33-cb3c044d1371.png)

![image](https://user-images.githubusercontent.com/25387035/186692646-1c42b34c-82cc-4a3b-866a-5ee0b0a4991c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4959fc1-212b-7d6a-df73-b0b2993df561
* Version Independent ID: fcecb4fc-6b16-e432-8f4a-f043e222bb41
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by rijwanansari** [comment]
Project is created in .NET 6 #12620

**Comment by WilliamAntonRohm** [comment]
@rijwanansari -- Rijwan, thank you for creating that PR!

**Comment by juliakm** [comment]
Thanks for the fix!
