### ISSUE TITLE
Path filters can exist without branch filters

### ISSUE THREAD

**Issue by mijpeterson** [MicrosoftDocs/azure-devops-docs#12617]
>When you specify paths, you must explicitly specify branches to trigger on. You can't trigger a pipeline with only a path filter; you must also have a branch filter, and the changed files that match the path filter must be from a branch that matches the branch filter.

I don't believe this section is necessarily true anymore, as I currently have pipelines running with only a path filter that trigger on every branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@mijpeterson Thank you for letting us know. It looks like this was true in Azure DevOps Server 2019 and 2019. (and Azure DevOps Services from back then) but starting with 2020 you can leave the branches blank. In the earlier versions you can specify '*' for the branches to include and it would have the same effect. I'll get this updated today.

**Comment by mijpeterson** [comment]
Problem has been addressed. Thank you @steved0x! Closing the issue
