### ISSUE TITLE
devops-new-user

### ISSUE THREAD

**Issue by npgfh** [MicrosoftDocs/azure-devops-docs#12627]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b4734-b75e-95c3-73d2-78216e166bf1
* Version Independent ID: e4404510-ff79-aabf-1214-1d1ccb968aba
* Content: [What is Azure Boards? Tools to manage software development projects. - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops)
* Content Source: [docs/boards/get-started/what-is-azure-boards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/get-started/what-is-azure-boards.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@npgfh - I'm closing this issue as there is no actional information. If you have some feedback on this article, [What is Azure Boards? Tools to manage software development projects. - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops), please feel free to provide it and reopen this issue.
