### ISSUE TITLE
50 subscription limit

### ISSUE THREAD

**Issue by vanmash** [MicrosoftDocs/azure-devops-docs#12635]
[Enter feedback here]

Instead of suggesting a strange workaround please **increase the limit** of 50 subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@vanmash -- Maciek, thank you for your suggestion.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by vanmash** [comment]
@WilliamAntonRohm — I found at least two, already closed, entries on Developer Community. How can I mention you there?

This bug or “design decision” is really annoying and the permanent solution (free text for SUBID) is so easy. Why not fix it?

**Comment by WilliamAntonRohm** [comment]
@vanmash -- Maciek, thank you for your follow-up.  I'm not sure how to be mentioned; please add their URLs here.

Your second question is outside the scope of documentation, as it relates to product internals, and so belongs in the Developer Community.  This repo has limited support options.

**Comment by vanmash** [comment]
William @WilliamAntonRohm 
I managed to find a couple

https://developercommunity.visualstudio.com/t/Remove-Azure-DevOps-Subscription-GUI-lim/1608174
https://developercommunity.visualstudio.com/t/Increase-limit-of-the-subscription-selec/1242724
https://developercommunity.visualstudio.com/t/Service-Connection-Subscription-Choices/1691768
https://developercommunity.visualstudio.com/t/Remove-50-subscription-limit-in-dropdown/10136608
