### ISSUE TITLE
Add options to the "targetType"

### ISSUE THREAD

**Issue by gerardmik** [MicrosoftDocs/azure-devops-docs#12632]
It would be helpful to see all the options for `targetType` in the table of Arguments. `filePath` is mentioned in that table, but `inline` is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb6bb80-ad9e-525c-3cae-275955b00919
* Version Independent ID: 79d62477-08d2-f412-d59d-d8cbac75dc32
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@gerardmik There are two possible values: `inline` and `filePath`. We just published a new task reference that will officially be going live next week, and these values are both listed there, in the YAML snippet as well as the Inputs table.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines
