### ISSUE TITLE
Sign Out should be Sign Off in post-deployment approvals

### ISSUE THREAD

**Issue by patrick-king** [MicrosoftDocs/azure-devops-docs#12633]
The term "sign out" is being used in two places, where I think it would make more sense to say "sign off".
A user must manually _sign out_ after deployment before the release is triggered to other stages.
After deployment, a team wants to wait for a specified time before prompting users to _sign out_.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492fb56b-00c9-9e6f-2d11-0220212a4e8b
* Version Independent ID: 0a019f21-3609-f7d6-af7f-1832b4c7470e
* Content: [Understand release gates, checks, and approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/approvals/index.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
@patrick-king -- Patrick, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
