### ISSUE TITLE
Would you please help to let me know how to get the Planned work item data in a iterations?

### ISSUE THREAD

**Issue by boy29729** [MicrosoftDocs/azure-devops-docs#12638]
Hi team, we still need to get the planned work item to count in power bi ? Would you please help to provide any method or apis?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [View and configure team velocity - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azure-devops)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by boy29729** [comment]
The planned data is like in the veloctiy chart.

**Comment by boy29729** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/49057985/187569588-ceedf692-6a51-4fab-a6a1-9de3767115b4.png">

**Comment by KathrynEE** [comment]
@boy29729 - Here is an example of the kind of OData info you can get. The WorkItemSnapshot entity type will aggregate the data based on the assignment made on the specified date - start of the iteration. The WorkItems entity type can aggregate values of the work items per state. 


{"@odata.context":"https://analytics.dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_odata/v4.0-preview/$metadata#WorkItemSnapshot(IterationSK,AggregationResult)","value":[{"@odata.id":null,"IterationSK":"4933928f-3e08-4cf9-901a-13cc32201944","AggregationResult":71},{"@odata.id":null,"IterationSK":"5b25cc74-aeb3-4f13-8084-1e899d7383b5","AggregationResult":83},{"@odata.id":null,"IterationSK":"a9219cb0-21c0-48f4-8c88-83d0ae3187db","AggregationResult":84},{"@odata.id":null,"IterationSK":"4bbc15f7-51c5-49e8-ae9f-a3ef05d90558","AggregationResult":62},{"@odata.id":null,"IterationSK":"2c29f724-465d-42c8-87f8-e46416a868e0","AggregationResult":67},{"@odata.id":null,"IterationSK":"8668264f-465d-4d69-b2b5-f5de742447d4","AggregationResult":86}]}
--batchresponse_9862c81d-4eaa-4d54-bb1b-15d4739e0315--



{"@odata.context":"https://analytics.dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_odata/v4.0-preview/$metadata#WorkItems(StateCategory,IterationSK,AggregationResult)","value":[{"@odata.id":null,"IterationSK":"4933928f-3e08-4cf9-901a-13cc32201944","StateCategory":"Completed","AggregationResult":65},{"@odata.id":null,"IterationSK":"5b25cc74-aeb3-4f13-8084-1e899d7383b5","StateCategory":"Completed","AggregationResult":68},{"@odata.id":null,"IterationSK":"a9219cb0-21c0-48f4-8c88-83d0ae3187db","StateCategory":"Completed","AggregationResult":87},{"@odata.id":null,"IterationSK":"4bbc15f7-51c5-49e8-ae9f-a3ef05d90558","StateCategory":"Completed","AggregationResult":79},{"@odata.id":null,"IterationSK":"2c29f724-465d-42c8-87f8-e46416a868e0","StateCategory":"Completed","AggregationResult":67},{"@odata.id":null,"IterationSK":"8668264f-465d-4d69-b2b5-f5de742447d4","StateCategory":"Completed","AggregationResult":81},{"@odata.id":null,"IterationSK":"2c29f724-465d-42c8-87f8-e46416a868e0","StateCategory":"InProgress","AggregationResult":13},{"@odata.id":null,"IterationSK":"a9219cb0-21c0-48f4-8c88-83d0ae3187db","StateCategory":"Proposed","AggregationResult":1},{"@odata.id":null,"IterationSK":"2c29f724-465d-42c8-87f8-e46416a868e0","StateCategory":"Proposed","AggregationResult":4},{"@odata.id":null,"IterationSK":"8668264f-465d-4d69-b2b5-f5de742447d4","StateCategory":"Proposed","AggregationResult":3}]}
--batchresponse_bee03aed-00f1-4e40-a560-6dc0c9732225--

**Comment by boy29729** [comment]
@KathrynEE  Many thanks. The info is very useful.
