### ISSUE TITLE
Cache2 task, key input needs to be updated to include what the max length should be.

### ISSUE THREAD

**Issue by JimSuplizio** [MicrosoftDocs/azure-devops-docs#12637]
I work on the Engineering Systems team for the Azure-SDK. One of the things we noticed is that we'd changed our key, adding a list to make it unique, and as a result the string became rather long. One of the things we'd noticed after this was that started failing to create the cache with the new, longer fingerprint. We'd ended up creating a SHA256 of the aforementioned list and it's able to create the cache again. There's clearly a max limit to the length of the string and it would be good to know, in the documentation, what the length limits are for the key are. 

Trying to hunt things down, you can find the [Cachev2 task in the sources](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CacheV2/task.json#L60) linked on the page but it unfortunately uses an agent task that lives in another repository that isn't linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4422fc0a-f980-9967-1157-d780b644a3ca
* Version Independent ID: adaf52da-a9b7-1057-0c61-d3498b3d3e3c
* Content: [Cache task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/cache.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/cache.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@JimSuplizio That plugin looks like it is part of the Agent software, which is open source but in a different repo:
https://github.com/microsoft/azure-pipelines-agent/blob/b93f8f1f4e53ddf5d9cd25090db6f71b092d177c/src/Agent.Plugins/PipelineCache/SavePipelineCacheV0.cs

However I didn't find any clues there. I will see if I can find out this limit and when I do I'll add it to the docs.

**Comment by JimSuplizio** [comment]
@steved0x, I definitely appreciate you taking a look this.

**Comment by steved0x** [comment]
Closing this issue and I sent a message offline.
