### ISSUE TITLE
load-balancer/--lb: expected one argument

### ISSUE THREAD

**Issue by leandromsft** [MicrosoftDocs/azure-devops-docs#12642]
The command az vmss create resulting error: **--load-balancer/--lb: expected one argument**

```
❯ az vmss create `
> --name vmssagentspool `
> --resource-group $rgNameScale `
> --image UbuntuLTS `
> --vm-sku Standard_D2_v3 `
> --storage-sku StandardSSD_LRS `
> --authentication-type SSH `
> --generate-ssh-keys `
> --instance-count 2 `
> --disable-overprovision `
> --upgrade-policy-mode manual `
> --single-placement-group false `
> --platform-fault-domain-count 1 `
> --load-balancer ''
argument --load-balancer/--lb: expected one argument
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756d9c64-a802-61ad-ba6c-6061d2d747cf
* Version Independent ID: 012518b7-0282-f5b0-5206-8a9d1902b8d3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@leandromsft -- Leandro, thank you for your feedback.  Please try this, with double quotes (that is, an empty string value), and let me know it is successful:
```
> --load-balancer '""'
```

**Comment by leandromsft** [comment]
Hi @WilliamAntonRohm 
Thank you for help! I used your suggestion and working fine!

The command result a warning about load balance

 **It is recommended to use parameter "--lb-sku Standard" to create new VMSS with Standard load balancer. Please note that the default load balancer used for VMSS creation will be changed from Basic to Standard in the future.** 

I think I can ignore that, right?

Thank you!

**Comment by WilliamAntonRohm** [comment]
@leandromsft -- Leandro, you're welcome -- glad to help!  That warning would only be relevant (as it says) if you need to change the type of the load balancer, currently Basic.  It is something to note if Standard will not be your choice later on.
