### ISSUE TITLE
Example for "split" not working

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-devops-docs#12649]
The example described in the [split section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#split) is not working. I copied the example into a fresh pipeline and encounter the following error: `Unrecognized value: 'split'. Located at position 1 within expression: split(variables.environments, ','). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@RobinZergiebel -- Robin, thank you for your feedback.  Please see the discussion in related issue #12650.
