### ISSUE TITLE
azure-rm-web-app-deployment -- deploymentMethod 'runFromPackage' option should be 'runFromZip'

### ISSUE THREAD

**Issue by DotNetSparky** [MicrosoftDocs/azure-devops-docs#12641]
In the example on the docs page, the value for `deploymentMethod` should be `runFromZip`, not `runFromPackage`. Although the label in the UI is "Run from Package", the value is `runFromZip`, and using the wrong value will cause an error during deployment (but the error is... not obvious?... as to why:  Cannot read property 'PreDeploymentStep' of undefined 🙃).

**Comment by WilliamAntonRohm** [comment]
@DotNetSparky -- Shaun, thank you for catching this.  To which article are you referring?  Please let me know, and I will update it.

**Comment by DotNetSparky** [comment]
> @DotNetSparky -- Shaun, thank you for catching this. To which article are you referring? Please let me know, and I will update it.

LOL, I really did forget to include the most important detail, didn't I? Really sorry about that!

It's the page for the `AzureRMWebAppDeployment@4` here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops

The text is in an example block just below this bullet point:

![image](https://user-images.githubusercontent.com/7200854/187809418-4fda5323-c18c-474b-b243-6cae23a70489.png)

**Comment by DotNetSparky** [comment]
It also should be named `deploymentType` (I didn't notice that earlier, but it's mentioned earlier in the page as that name)

**Comment by WilliamAntonRohm** [comment]
@RoopeshNair -- Roopesh, please review this update in [private PR 5031](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5031).

**Comment by steved0x** [comment]
The task reference is autogenerated now and these issues are fixed:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines

https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/blob/main/README.md#contributing-to-the-tasks-content
