### ISSUE TITLE
Split expression example fails with error "unrecognized value 'split'"

### ISSUE THREAD

**Issue by arkein** [MicrosoftDocs/azure-devops-docs#12650]
Hello,

The documentation provides the following example for [split expression](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#split):

```yml
variables:
- name: environments
  value: prod1,prod2 
steps:  
  - ${{ each env in split(variables.environments, ',')}}:
    - script: ./deploy.sh --environment ${{ env }}
```

I have created the following YAML pipeline:

```yml
parameters:
  - name: environments
    displayName: 'Environments CSV'
    type: string
    default: 'prod3,prod4'

pool:
  vmImage: windows-latest

variables:
- name: environments
  value: prod1,prod2

steps:
  - ${{ each env in split(variables.environments, ',')}}:
    - pwsh: Write-Host "var environment ${{ env }}"
  - ${{ each env in split(parameters.environments, ',')}}:
    - pwsh: Write-Host "param environment ${{ env }}"
```

In Azure DevOps Services I get the following errors:

```text
/split-string-expression.yml (Line: 17, Col: 5): Unrecognized value: 'split'. Located at position 1 within expression: split(variables.environments, ','). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996

/split-string-expression.yml (Line: 19, Col: 5): Unrecognized value: 'split'. Located at position 1 within expression: split(parameters.environments, ','). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#split)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@arkein I apologize for the confusion! It looks like this functionality hasn't fully deployed yet. Deployment is in progress over the next few days so you should be able to use the split() function soon.

**Comment by abatishchev** [comment]
This explains why I'm getting this bizarre error that contradicts all available documentation :(

**Comment by juliakm** [comment]
_Update_: We're going to rollback this article for now since the feature appears to be very popular. I apologize again for the confusion. Rollout is in progress.

**Comment by juliuscarlo** [comment]
I'm also eagerly waiting for the rollout of this feature. Do you have an updated timeline for when this is going to be available?

**Comment by RobinZergiebel** [comment]
The week is coming to an end - when can we expect this feature?

**Comment by juliakm** [comment]
The feature is live now.

**Comment by jdwirrenga** [comment]
@juliakm what do I need to update in our on-prem instance of ADO to get these changes?

**Comment by kbhagat-ansys** [comment]
@juliakm  What version of ADO server is the fix available in?

**Comment by SPSamL** [comment]
@juliakm, is this available on DevOps Server and if so, what is the version required?
