### ISSUE TITLE
1.208.0 broke JSONvariableSubstitution

### ISSUE THREAD

**Issue by anthonyolearyairswift** [MicrosoftDocs/azure-devops-docs#12652]
hello, my pipeline scripts worked fine last week for 1.206.0
now i am getting this error

[warning]Resource file haven't been set, can't find loc string for key: JSONvariableSubstitution

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by dancoupar** [comment]
We've also begun experiencing this issue in the last 24 hours, with multiple pipelines failing. The issue affects the `FileTransform@1` task. Whilst the task reports success, it produces warning messages similar to the one shown and no variable substitution occurs. In our case, we're transforming XML config files.

We've had some success in using the newer version `FileTransform@2` as a workaround.

**Comment by atroiano-glue** [comment]
Hi,

Same issue here.. 
Was working correctly on 1.206.00 . 
Now our FileTransform task is not substituting the JSON values and marking the FileTransform as "Succeeded" with Warnings.
Therefore, the Parameters not being substituted are breaking our Environments.

Warning message:" [warning]Resource file haven't been set, can't find loc string for key: JSONvariableSubstitution"

We request this to be fixed ASAP please, or roll back to 1.206.00

Thanks

**Comment by WilliamAntonRohm** [comment]
@anthonyolearyairswift, @atroiano-glue -- thank you for your feedback.  This seems to be product-related, rather than documentation-related; please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

cc @RoopeshNair, @steved0x, @chcomley for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by WilliamAntonRohm** [comment]
Related to https://github.com/microsoft/azure-pipelines-tasks/issues/16821
