### ISSUE TITLE
Add suport to add draw io files

### ISSUE THREAD

**Issue by Diaskhan** [MicrosoftDocs/azure-devops-docs#12665]
There is free diagraming toolkit.
https://app.diagrams.net/

formely Draw.io
Its possible to add support attach files with extension *.drawio
Its the same as Visio files.

I dont know exactly whome I must addresses this issue!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by Diaskhan** [comment]
![files___](https://user-images.githubusercontent.com/15046677/188797173-7d18c799-cb01-45ee-8121-c806cc718d8f.png)

**Comment by WilliamAntonRohm** [comment]
@Diaskhan -- thank you for your suggestion.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
