### ISSUE TITLE
Please document all git configuration variables

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-docs#12668]
Please document all git configuration variables, such as the ones found here: https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/GitSourceProvider.cs#L326-L336

The only place I found mention of `agent.source.git.lfs` was in that source file. And I found it by searching for the other variable, which is mentioned on the documentation page in question, but the mention acts like it's somewhere else on the page too. And it's not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@carlin-q-scott -- Carlin, thank you again for your feedback and this suggestion.

@steved0x -- Steve, please look into this issue.
