### ISSUE TITLE
Priority Matrix integration with Azure boards

### ISSUE THREAD

**Issue by pablodiazgutierrez** [MicrosoftDocs/azure-devops-docs#12669]
Hello, I would like to humbly suggest a mention of [Priority Matrix](https://appfluence.com/productivity/synchronize-azure-devops-work-items-priority-matrix/) as a 3rd party tool that integrates with Azure Boards. It automatically syncs work items with Priority Matrix to facilitate prioritization using the Eisenhower matrix method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@pablodiazgutierrez -- Pablo, thank you for your suggestion.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
