### ISSUE TITLE
Closing out sprint

### ISSUE THREAD

**Issue by sandeepantony** [MicrosoftDocs/azure-devops-docs#12672]
This documentation is not clear on how the sprints are closed. I'm assuming its automatic, based on the current write up. It would be good to understand what the exact rules are for sprints to close.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbeeb04-899a-4915-798f-9d6285c535ca
* Version Independent ID: c23d061e-9544-ec2b-c870-6802dbc44fb2
* Content: [Track progress and individual items on the Taskboard - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/task-board?view=azure-devops)
* Content Source: [docs/boards/sprints/task-board.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/sprints/task-board.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sandeepantony - Thank you for the feedback. You are correct, there is no explicit guidance on closing a sprint. Nothing occurs automatically at the end of a sprint. You must manually update incomplete work items to a new iteration path and archive older sprints if you want to declutter your Iteration Path list as suggested in [Define iteration paths (sprints) and configure team iterations, Archive iteration paths](https://docs.microsoft.com/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#archive-iteration-paths).  

I will add an item to my backlog to provide more guidance in this area.

**Comment by sandeepantony** [comment]
> @sandeepantony - Thank you for the feedback. You are correct, there is no explicit guidance on closing a sprint. Nothing occurs automatically at the end of a sprint. You must manually update incomplete work items to a new iteration path and archive older sprints if you want to declutter your Iteration Path list as suggested in [Define iteration paths (sprints) and configure team iterations, Archive iteration paths](https://docs.microsoft.com/azure/devops/organizations/settings/set-iteration-paths-sprints?view=azure-devops&tabs=browser#archive-iteration-paths).
> 
> I will add an item to my backlog to provide more guidance in this area.

Thank you!
