### ISSUE TITLE
Web Extension not working in modal

### ISSUE THREAD

**Issue by Gurpritsingh793** [MicrosoftDocs/azure-devops-docs#12679]
When We open WorkItem in popup then my extension is not working. While debugging I noticed then VSS. Ready event is not triggering. Can you suggest any solution!!!!!

![image](https://user-images.githubusercontent.com/59950925/189311439-3ef164ec-d83d-42a4-a09a-f9d6a534736c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
<img width="942" alt="extenstion issue" src="https://user-images.githubusercontent.com/59950925/189311766-13207a64-a258-4d72-a8ae-14eb53c68ddc.png">

* Microsoft Alias: **chcomley**

**Comment by Gurpritsingh793** [comment]
@WilliamAntonRohm Thanks for the reply.

My requirement is in azure devops we added our own "time log extension". I attached the extension code. I observed following root cause of the issue. 

VSS.Ready method is not executing. 

[Timelog code.docx](https://github.com/MicrosoftDocs/azure-devops-docs/files/9638212/Timelog.code.docx)

**Comment by WilliamAntonRohm** [comment]
@Gurpritsingh793 -- thank you for your follow-up.  This repo is solely for documentation issues, with limited help options.  Please see the resources I mentioned earlier.


cc @chcomley for awareness
