### ISSUE TITLE
Incorrect info - PAT notifications not available for on prem

### ISSUE THREAD

**Issue by michaeljurek-ext95167** [MicrosoftDocs/azure-devops-docs#12671]
The page misleading offers PAT notifications for on premises version (Server 2019/2020/2022). As far as i know PAT notifications work only with the cloud service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Use personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops-2020&tabs=Windows#notifications)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @michaeljurek-ext95167, thank you for reaching out.  I've added a link to more information for Azure DevOps Server notifications, which will be live shortly. Here's the link provided in the article: [Configure an SMTP server and customize email for alerts and feedback requests](https://docs.microsoft.com/en-us/azure/devops/server/admin/setup-customize-alerts?view=azure-devops-2022).
