### ISSUE TITLE
No reference to old repo?

### ISSUE THREAD

**Issue by stunt02** [MicrosoftDocs/azure-devops-docs#12685]
Hi

I haved read the instructions but I did not see any reference to the old repo, how is it possible to move the old to a new one without refering to it?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795dbe37-ed87-714d-e5f1-4b85d6b0ed7a
* Version Independent ID: 977de330-22d6-aa67-28b6-fe107c9a21b2
* Content: [Move Git repositories between projects - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops)
* Content Source: [docs/repos/git/move-git-repos-between-team-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/move-git-repos-between-team-projects.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@stunt02 -- thank you for your feedback.  The old repo is `FabrikamOld`, and is referred to as the "local (source) repository" here:
- [Mirror the repository](https://learn.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects#mirror-the-repository)

And as the "original repo" here:
- [Configure the new repo](https://learn.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops#configure-the-new-repo)

This article also refers to the "existing" or "source" repo:
- [Import a Git repo](https://learn.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops#configure-the-new-repo)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
