### ISSUE TITLE
How is it possible to give friendly names to the returned SELECT columns

### ISSUE THREAD

**Issue by santhoshbomma9** [MicrosoftDocs/azure-devops-docs#12687]
How is it possible to give friendly names to the returned SELECT columns

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [Work Item Query Language (WIQL) reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops&viewFallbackFrom=vsts%3Fview%3Dvsts)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@santhoshbomma9 - Can you say more about what you are trying to accomplish? If you enter a WIQL query, the results should present column fields that use the friendly names. I'd need to know more in terms of what you are seeing in order to address your issue.

**Comment by santhoshbomma9** [comment]
The docs say "You can specify either the friendly name or reference name." My question is how can we do that?

**Comment by KathrynEE** [comment]
@santhoshbomma9 - The following Select clause based on friendly names: 
```
SELECT
    [Id],
    [Node Name],
    [Work Item Type],
    [Title],
    [Parent],
    [Assigned To],
    [State],
    [Risk Assessment],
    [Iteration Path],
    [Tags]
```
Is equivalent to this one based on reference names: 
```
SELECT
    [System.Id],
    [System.NodeName],
    [System.WorkItemType],
    [System.Title],
    [System.Parent],
    [System.AssignedTo],
    [System.State],
    [Custom.RiskAssessment],
    [System.IterationPath],
    [System.Tags]
```

Does that address your question?

**Comment by santhoshb-msft** [comment]
Sorry my question was can we do any of the below?

```
SELECT
    [Id] AS [Identity], // Adding Alias?
    [Node Name],   // Adding CASE statement?
    [Work Item Type],
    [Title],
    [Parent],
    [Assigned To],
    [State],
    [Risk Assessment],
    [Iteration Path],
    [Tags]

```

**Comment by KathrynEE** [comment]
@santhoshb-msft - I don't believe you can. I recommend you install the WIQL extension and play around with it based on what you are trying to achieve. If you want to query on other fields than those listed - you might be able to do that from the Analytics service -- see https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/wit-analytics?view=azure-devops. If you're wanting to list the aliases of users, then I recommend using the Azure CLI command as documented here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=azure-devops&tabs=azure-devops-cli#export-a-list-of-users.

**Comment by KathrynEE** [comment]
@santhoshb-msft - Closing this as addressed.
