### ISSUE TITLE
Azure web hosting

### ISSUE THREAD

**Issue by Vgapachecovgapacheco** [MicrosoftDocs/azure-devops-docs#12689]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of Out Of Box widgets you can add to a dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops#new-work-item-widget)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@Vgapachecovgapacheco -- thank you for your feedback.  I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
