### ISSUE TITLE
date-time ASOF example not working

### ISSUE THREAD

**Issue by asgeroverby** [MicrosoftDocs/azure-devops-docs#12686]
[Enter feedback here]

The date string below does not parse. 
```
SELECT
    [System.Id],
    [System.Title],
    [System.State],
    [System.IterationPath]
FROM workitems
WHERE
    [System.TeamProject] = @project
    AND [System.WorkItemType] <> ''
    AND ([System.IterationPath] UNDER 'Fabrikam Fiber\Release 1'
    AND [System.AssignedTo] = 'Jamal Hartnett <fabrikamfiber4@hotmail.com>') 
    ASOF  '01-05-2022T00:00:00.0000000'`
```
I think it is suppose to be '2022-05-01T00:00:00.0000000'` i.e. ISO8601 format. That at least works for me :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [Work Item Query Language (WIQL) reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@asgeroverby -- thank you for catching this.

@KathrynEE -- if you like, I can fix this for you.

**Comment by KathrynEE** [comment]
@WilliamAntonRohm - please hold off on any fixes. The Date entries are dependent on the user's date-and-time-pattern as described in the corresponding section: [Date and time pattern](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#date-and-time-pattern).  It is more than likely that the user's profile settings differ from that which is used in the documentation.

**Comment by asgeroverby** [comment]
The `T` in the date designates ISO8601 format which is not subject to localization by definition.


________________________________

**Comment by KathrynEE** [comment]
@asgeroverby - closing this as addressed. Please feel free to reopen if you believe that is in error.

**Comment by asgeroverby** [comment]
The example is still wrong.If you want the example to be correct, you have need either to remove the `T` to make it subject to localization or keep the `T` and use correct ISO 8601 format.

To summarize, correct examples are:

- `01-05-2022 00:00:00.0000000` is valid in e.g. Danish locale
-  `2022-05-01T00:00:00.0000000` is ISO 8601 format and thus valid no matter the locale

**Comment by KathrynEE** [comment]
@asgeroverby - Thank you for the clarifying comments. I've updated the article to reflect the required corrections. Closing this issue as completed.
