### ISSUE TITLE
Information about evolution of the product is mangled together with current implementation

### ISSUE THREAD

**Issue by illia-karpenkov** [MicrosoftDocs/azure-devops-docs#12695]
Historical aspects mangled together with current implementation which is not very good user experience. 
For example, article starts like:
> Previously, Azure Artifacts feeds used to be scoped to an organization.

As a developer, who is new to this product and who tries to make sense of how things are working, I would recommend moving all historical information into a separate article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops#feedback)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for your feedback!
