### ISSUE TITLE
Service Connections - Approvals and checks

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/azure-devops-docs#12691]
The "Approvals and checks" functionality of service connections seems undocumented.

Especially it'd be great to mention their incompatibility with Release Pipelines (classic/non-YAML), which results in this error message:

> The stage refers to resources like service endpoint 'name of service endpoint', that have been protected with checks. Protected resources can only be used in YAML pipelines. For more details, refer to https://aka.ms/pipelinechecks.

(also raised https://github.com/MicrosoftDocs/azure-devops-docs/issues/12690 about the unhelpful URL)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5284952-75a7-b6c1-69e6-be179bb94e02
* Version Independent ID: aac8216a-6c50-c614-540b-24a5f93cdb5a
* Content: [Service connections in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#secure-a-service-connection)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
Closing as closely related to #12690.

cc @juliakm, @RoopeshNair for awareness
