### ISSUE TITLE
feed term is undefined

### ISSUE THREAD

**Issue by illia-karpenkov** [MicrosoftDocs/azure-devops-docs#12694]
Concept of 'feed' is not clearly defined in the document.
Concept of 'feed' is used often when it would be more appropriate to use 'artefacts repository' term.
Feed is a mechanism for streaming changes and subscribing to change notifications. Such changes happen in 'artefacts repository' which is a managed service in azure cloud. Unfortunately there is no clarity around that in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b51babfa-569b-ef0a-469a-849a3835b21b
* Version Independent ID: 97a78c7b-dc57-f040-4cc2-66cd91f9851f
* Content: [Azure Artifacts overview - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **rabououn**

**Comment by chcomley** [comment]
Thanks for your feedback, @illia-karpenkov. I've added a hyperlink to the Feeds Overview article at the first mention of feeds. If you feel more edits are needed, please [become a contributor to our docs ](https://learn.microsoft.com/en-us/contribute/)and help us out! We'd love it! Thank you! When the update goes live, this issue will automatically close. Thanks again.
