### ISSUE TITLE
Add info about how to fail the build from AzurePowerShell task

### ISSUE THREAD

**Issue by robhalevt** [MicrosoftDocs/azure-devops-docs#12704]
It would be really helpful to include a **Write an error** section that documents the Azure PowerShell task requires the code to use
```powershell
[Environment]::Exit(1);
```
if the developer wants the error to fail the build. 

The PowerShell task's documentation includes a [**Write an error** section](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#write-an-error) with a tip documenting that to fail a build developers should use:
```powershell
exit 1;
```

We have used the PowerShell task a bunch in our pipelines. The first time we used the Azure PowerShell task we lost a lot of time trying to figure out why the Azure PowerShell task wasn't failing the build even though the exit code was being set.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcda4373-62ae-e1ae-c15d-63f441179b47
* Version Independent ID: 305f78c0-2e89-78f2-d2d1-89471602610c
* Content: [Azure PowerShell task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@robhalevt -- Rob, thank you for your considered feedback.

@RoopeshNair -- Roopesh, please look into this issue.
