### ISSUE TITLE
What environments are available? Is there a Python310?

### ISSUE THREAD

**Issue by cbare** [MicrosoftDocs/azure-devops-docs#12709]
The page shows Python environments for 2.7, 3.6, and 3.7 which are all obsolete. Please add some explanation of how to know which environments are currently available. I know there's a Python38 and Python39. Is there a 310, yet? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 545519f0-468e-e8cd-86e7-37f03ae82dc4
* Version Independent ID: d216e8fe-d5d6-f9e6-2115-37d32d03cf76
* Content: [Build and test Python apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thank you for flagging this. An update will go out shortly. `ubuntu-latest` supports 3.7.14, 3.8.14, 3.9.14, 3.10.7. You can see the list [here](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).
