### ISSUE TITLE
Wrong permissions level: PCA instead of PA

### ISSUE THREAD

**Issue by BrendonLP** [MicrosoftDocs/azure-devops-docs#12706]
Hi. Looks like the following statement is not 100% correct:
You must be a member of the [**Project Collection Administrators group**](https://learn.microsoft.com/en-us/azure/devops/organizations/security/change-organization-collection-level-permissions?view=azure-devops) and the project's [Contributors group](https://learn.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops). If you created the project, you have permissions.

The required level for Azure DevOps appears to be **Project Administrator** (PA) and not Project Collection Administrator (PCA). Can anyone confirm this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect an Azure Boards or Azure DevOps project to a GitHub repository - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrendonLP - Thank you for the feedback. THe required permissions to make the connection is to be a member of the Project Administrators group and have Administrator permissions on the GitHub Repository. I'll update the article this week.

**Comment by KathrynEE** [comment]
Updating the article with PR https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5054
