### ISSUE TITLE
Can I get help on these two problems?

### ISSUE THREAD

**Issue by viveknuna** [MicrosoftDocs/azure-devops-docs#12716]
I looking for help on these two issues. There is no documentation, no community support. Please help.

I am posting the questions which I asked on stackoverflow. 

https://stackoverflow.com/questions/73818920/how-to-check-whether-a-commit-is-present-in-a-branch-in-azure-dev-ops

https://stackoverflow.com/questions/73797671/how-to-get-the-parent-branch-of-a-branch-from-azure-devops

**Comment by WilliamAntonRohm** [comment]
@viveknuna -- thank you for your feedback.  Please consider this resource:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 

This article may be related to your questions -- please let me know either way:
- [Review updates to your brances](https://learn.microsoft.com/azure/devops/repos/git/manage-your-branches?view=azure-devops#review-updates-to-your-branches)

**Comment by viveknuna** [comment]
@WilliamAntonRohm is there any GitHub repo related to azure devops service?

**Comment by WilliamAntonRohm** [comment]
@viveknuna -- thank you for your follow-up.  This repo (documentation) is the only one I'm aware of.  What repo content are you looking for?

**Comment by WilliamAntonRohm** [comment]
@viveknuna -- thank you for following up.  Please see my previous reply and question.
