### ISSUE TITLE
Suggest 'ubuntu-latest' for the build agent image

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-docs#12712]
The pool.vmImage should be 'ubuntu-latest' as recommended by the pipeline when it runs. 

I also found it unclear why I needed vmImage and container to be ubuntu-18.04 and ubuntu:18.04 respectively. Most build systems just have you select the docker **image**. I think it should clarify that the pool specifies the agent vmImage to use to host the docker container, and container specifies the docker container and image to run the job in.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @carlin-q-scott! That's a good suggestion. I'll make the update now.
