### ISSUE TITLE
What, exactly, is the set of invalid characters for a build number?

### ISSUE THREAD

**Issue by fourpastmidnight** [MicrosoftDocs/azure-devops-docs#12723]
In this documentation, with respect to the token `$(Build.DefinitionName)`, the following note is provided in the table:

> Note: The pipeline name must not contain invalid or whitespace characters.

But this article fails to define what are invalid characters.

For example, I want to set the date _and time_ in my build number. Are colons valid characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by fourpastmidnight** [comment]
Well, it turns out that (at least, Azure DevOps Server 2019) will tell you, but only after you attempt to queue a build, the set of invalid characters (which I suspect, is because I was using a variable format specifier, e.g. `$(DateTime:yyyy-MM-dd\THH\:mm\:ss)`. Anyway, it would be great if the docs would just outright list the set of invalid characters so I wouldn't have to "guess".

**Comment by juliakm** [comment]
@fourpastmidnight I'm updating the article with a list of invalid characters now. Unfortunately, it's not an exhaustive list because there are unicode and other variations that aren't include. But, I think this should help you get started.
