### ISSUE TITLE
Cache NuGet instructions don't work.

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/azure-devops-docs#12727]
Having NuGet restore be skipped when caching is used doesn't seem to work. When the VSBuild step runs, you'll get an error message such as:

```
C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5)
: error NETSDK1004: Assets file 'C:\git\repo\proj\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\git\repo\proj.csproj]
```

I believe the docs should be updated to:
1. Remove the condition on the NuGet restore task.
2. Explicitly document the need not to have a condition here, in order to ensure project.assets.json is generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Cache NuGet packages to reduce build time - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@davidmatson Thank you for your feedback! I ran through the setup again and it's working as expected. in your scenario, you can remove the condition from the restore task and generate your json file. I will be adding a note to the article shortly
