### ISSUE TITLE
Error in pipeline when using noTags value 

### ISSUE THREAD

**Issue by ArtourK** [MicrosoftDocs/azure-devops-docs#12728]
Hello! 

I was trying to enable the the fetch of tag's in our pipeline.

![image](https://user-images.githubusercontent.com/23549448/192713221-9d1e53df-4f49-4ac3-add6-5842d9f192f2.png)

BR,
Artour 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@ArtourK -- thank you for your feedback.  This issue is being addressed in #12717.
