### ISSUE TITLE
Unclear passage in document

### ISSUE THREAD

**Issue by GitHubUser1339** [MicrosoftDocs/azure-devops-docs#12722]
In the create agent pool section of this document, the first typical situation that is described is:

![image](https://user-images.githubusercontent.com/17045753/192292792-9f3e4126-20f8-4c37-928b-4f2f287fe0dc.png)

The scenario is creation of an agent pool in an individual DevOps project. Yet, the text seems contradicting. 'First, make sure you've the permissions to _**create pools in your project**_.... Add pool and select the option _**to create a new pool at the organization level**_.'. 

Not sure if this is a typo or not, but it's confusing imho.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Create and manage agent pools - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thank you for pointing this out, that step is for creating a pol at the project level, and the fix will be live today.
