### ISSUE TITLE
Microsoft Learn style Alerts, Notes, Tips, Important, Caution, Warning etc.

### ISSUE THREAD

**Issue by SudoCerb** [MicrosoftDocs/azure-devops-docs#12730]
I was disappointed to find that DevOps Wikis don't have support for Alerts, Notes, Tips, Important, Caution, Warning etc.

https://learn.microsoft.com/en-us/contribute/markdown-reference#alerts-note-tip-important-caution-warning

Why are there disparate implementations of Markdown support? I know that these are two different products but this is frustrating, as I would like to create rich content in my DevOps wiki but have limited options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@SudoCerb -- thank you for your feedback.  This seems more product-related than documentation-related; please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
