### ISSUE TITLE
Azure Pipeline shallow fetch =1 by default

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/azure-devops-docs#12732]
Newly created pipelines now have shallow fetch enabled and set to 1 by default:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/22429087/192843241-908465fc-9756-42b3-96cd-73a722a5cd0d.png">

I don't think it's the latest update: https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/pipelines/sprint-209-update?tabs=yaml because `noTags` still doesn't work

I find this one quite important, would be great if it could be mentioned somewhere =)

**Comment by steved0x** [comment]
This has been added to the documentation and should be live shortly.

https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#remarks

https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch

Thank you for letting us know.
