### ISSUE TITLE
Show user story pane in backlog view

### ISSUE THREAD

**Issue by ohn8** [MicrosoftDocs/azure-devops-docs#12738]
Jira has this functionality and it is a huge time saver

An option to show in the Backlog view an editable User Stories pane.  The same has already been implemented in the Queries view:

![image](https://user-images.githubusercontent.com/48983722/193067768-8ee24650-029e-4625-bbf7-0422e8dcf8b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c430085-0b81-836a-ad27-57c0d7c02eaf
* Version Independent ID: 5c430085-0b81-836a-ad27-57c0d7c02eaf
* Content: [Configure your backlog view in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/configure-your-backlog-view?source=recommendations&view=azure-devops)
* Content Source: [docs/boards/backlogs/configure-your-backlog-view.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/configure-your-backlog-view.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ohn8 - Thank you for your feedback. Since this is a feature request, please post it on our [Developer community page](https://developercommunity.visualstudio.com/report?space=21&entry=suggestion) for it to be considered. 

Closing this issue as it is not a documentation issue.
