### ISSUE TITLE
Should System.ArtifactsDirectory be changed to Pipeline.Workspace in the automatic deployment jobs?

### ISSUE THREAD

**Issue by kmasalski** [MicrosoftDocs/azure-devops-docs#12741]
"Artifacts are only downloaded automatically in deployment jobs. By default, artifacts are downloaded to System.ArtifactsDirectory"

Shouldn't it be changed to "downloaded to Pipeline.Workspace"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for your feedback! Yes, [Download Pipeline Artifacts](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#arguments) defaults to $(Pipeline.Workspace)
