### ISSUE TITLE
Does Azure Boards support MS Team GCC?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/azure-devops-docs#12768]
We found out that Azure Boards does not support the MS Team GCC.
And there is no documentation in this regard or a note in this page regarding MS Team GCC Integration.
Can you please add some note on this page for MS Team GCC integration and whether it is supported or not?
If it is documented at other places, please share the link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Use Azure Boards with Microsoft Teams - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/integrations/boards-teams.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @KathrynEE
* Microsoft Alias: **karrg**

**Comment by danhellem** [comment]
@Anand-Moghe correct, GCC is not supported. @KathrynEE  can we add a note to the page stating that Teams GCC integration is not supported?

**Comment by KathrynEE** [comment]
@danhellem, @Anand-Moghe - I'm reluctant to add such a note for the following reasons: 
- It's very unclear to me how Teams GCC would integrate with Azure Boards - what functionality is missing? 
- We typically don't list everything that isn't supported. We document what is supported. To list everything that isn't supported takes us down a very odd path. 
I'm closing this issue as addressed. Feel free to add further comments as needed.
