### ISSUE TITLE
Potential error in a note about the wiki count limit

### ISSUE THREAD

**Issue by Arturace** [MicrosoftDocs/azure-devops-docs#12762]
There is a note on the page, in the "publish a Git repository to a wiki" section, that says the following (on all pages per the version of the product):
> You can publish up to 10 total wikis.

I have tested that claim in both Azure DevOps Services and Azure DevOps Server 2022. I have created 11 git repositories and published every single one as a Wiki on both platforms. I also had a project wiki. No issue whatsoever.

Could I please have a clarification if I misunderstood the note or if this is an outdated information in the docs? If it's the latter, I would be happy to remove the note or update it if necessary.

Screenshot of the note:
![image](https://user-images.githubusercontent.com/36833825/194737188-dc27b589-f448-4705-8abd-c989dfcc506f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/publish-repo-to-wiki.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Arturace, Thanks for reaching out. I'm looking into this and will be in touch.

**Comment by chcomley** [comment]
I've updated the article! The clarification is: You can publish up to 10 branches per published code wiki.
Thanks for your feedback, @Arturace!
