### ISSUE TITLE
pipeline name after import

### ISSUE THREAD

**Issue by arambazamba** [MicrosoftDocs/azure-devops-docs#12776]
When importing yaml pipelines from GitHub repos the name of the imported pipeline is always:

GitHub_Username-repo#name from yaml

When importing many pipelines from a monorepo in the overview they all have the GitHubUsername-Repo name which makes the somehow hard to distinguish :-)

Is there a way to set a default import name pattern? I would like the pipeline to just take the name from the yaml file if present. 

Actually this behaviors  annoys me for some years now - I always have to rename the pipelines manually.

I'vs added a pic to illustrate the issue: If I hadn't renamed the pipelines in the purple box manually the all would have the default name: arambazamba.food-app

![image](https://user-images.githubusercontent.com/16348023/195841272-8c3fba39-2cb9-47c7-b0f9-2ad178e33386.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6a24a4-066b-caaf-551a-0d58097fea4b
* Version Independent ID: d2cbc919-38f3-8aaf-b3d6-ab26c4a0d260
* Content: [Clone or import a pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/get-started/clone-import-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/clone-import-pipeline.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@arambazamba -- Alexander, thank you for your thorough feedback.  As this is a product-related issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

@juliakm -- Julia, is there a way to change the default naming pattern?
