### ISSUE TITLE
Not sure how some of the items in Organization-level permissions work in Azure DevOps Services in the cloud.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12784]
The organization-level permissions, user can set permissions that are common to DevOps services in the cloud and DevOps servers on-premises.
However, the description seems to assume on-premises, and there are items that are unclear how use in cloud.
This confuses users.

If it only works on on-premises, please specify that cloud doesn't need to work with it.
Or, if the DevOps services has a any feature, I want you to modify the document correctly.
 
Example: 
General - Alter trace settings

The linked documentation is intended for an on-premises environment and has no information about how tracing is used in the cloud.
(I '&lt;tfsserver&gt;&lt;port&gt;' tried 'dev.azure.com/<organization name>' instead of, but it didn't work)

Service Account
- Make requests on behalf of others
- Trigger events
- View system synchronization information

'Make requests on behalf of others' is clearly stated to be for use in an on-premises environment, but not in the other two.
I believe that service accounts do not need to be added by users in the cloud.
If everything is used in an on-premises environment, I want it to be written correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - Thank you for the feedback. The information for **Alter trace settings** permission does need to be updated. I'm working to get an answer from the product team to get clarity. For now, I believe that these settings are only valid for on-premise servers.  I'll update this issue once I get clarification.

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
