### ISSUE TITLE
I set 'view instance-level information' to deny, but the user can view membership and project.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12786]
I want know how organization-level permissions work, I set 'View instance-level information' to deny.
The documentation says permission and membership, and project cannot be displayed.
However, the user does not see the permission, but succeeds in displaying the membership and project.
If the documentation is outdated, please correct it.

Steps to reproduce:
- PCA step
1) access to [Organization Settings] - [Permissions]
2) change users tab.
3) Search for the user (one of the valid users).
4) 'View instance-level information' change to deny

- user step
1) access to [Organization Settings] - [Permissions]
2) Select any security group.
3) Check permissions is not displayed.
4) Change to the members tab.
5) Check members is displayed.
6) Access any project.
7) Check the project displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - Thank you for your inquiry.  When you set the **View instance-level information** to **Deny**, the user is no longer able to view permission information for any other user or group. They receive the following information: 
![image](https://user-images.githubusercontent.com/10856840/197891302-8e6f5581-ded8-4808-a5f6-452e605c6527.png)


When you set the **View project-level information** to **Deny**, the user is no longer able to view the project at all - therefore, not able to sign in or access the project.  

I'm in the process of updating the permissions.md article and will update this issue once that is published.

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
