### ISSUE TITLE
I set the 'delete team project' to deny in organization-level permissions, but the user can delete the project.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12785]
I set the 'delete team project' to deny from organization-level permissions for one of the project administrator user.
But when the user tried to remove the project, it succeeded.
How do this permission work? Could you please correct the description.
 
Steps to reproduce:
- PCA step
1) access to [Organization Settings] - [Permissions]
2) change user tab.
3) Search for the user (one of the project administrators).
4) 'Delete team project' change to deny

- project administrator step
1) access to [Project Settings] - [Overview]
2) push delete button.
3) write project name.
4) push delete button.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by tomaeda** [comment]
One of project administrator with 'delete team project' set to deny, he successfully deleted the project using the button in 'Organization Settings' > 'Projects'.
I don't know how else to delete the project.

**Comment by KathrynEE** [comment]
@tomaeda - I was able to replicate your steps and you are correct that a user with Deny set at the Project Collection level can still delete a project. There are cases where permissions assigned to a Project Administrator can't be overwritten. If you believe this should be considered a bug, please report it on our [Developer Community page](https://developercommunity.visualstudio.com/AzureDevOps/report).
