### ISSUE TITLE
Incorrect scentence in the Azure artifacts page

### ISSUE THREAD

**Issue by timijntema** [MicrosoftDocs/azure-devops-docs#12780]
The scentence in the image below is not correct.

![artifacts](https://user-images.githubusercontent.com/16646976/196164371-c72884c2-1362-4ddf-98cf-36a074436914.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76e5618c-1223-3699-3dc6-24caeabeb9fc
* Version Independent ID: e8ea6291-0eee-825f-64fa-48ca5abd49bb
* Content: [Use feed views to share packages - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/feeds/views.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for your feedback!
