### ISSUE TITLE
'View build resources' is affecting the display of Azure Pipelines settings, that is undocumented.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12793]
There is written in documentation, the organization-level permission 'View build resources' controls the display of build controllers and build agents.
However, in addition to these two, the [Organization Settings] - [Pipelines] - [Settings] menu changes depending on this permission.
I opened the configuration with 'View build resources' to deny, it never finished loading.
If the documentation is outdated, please change it to the correct description.

Steps to reproduce:
- PCA step
1) access to [Organization Settings] - [Permissions]
2) change users tab.
3) Search for the user (one of the valid users).
4) 'View build resources' change to deny

- user step
1) access to [Organization Settings]
2) Select [pipelines] - [settings]
3) Check settings never finished loading.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda -  I'm not sure what corrections need to be made to the documentation. If you find that the system does not complete a step as written - it is more likely that you are encountering a bug or need to refresh your browser and retry. I was able to set the View build resources for a user to Deny as shown: 

![image](https://user-images.githubusercontent.com/10856840/197308446-14d9d814-a19b-4333-ae29-4760bf7e453e.png)

If you believe you've encountered a bug, please report the issue using the REport a bug tool:
