### ISSUE TITLE
'Manage enterprise policies' in organization-level permissions do not work

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12797]
The documentation is written that 'Manage enterprise policies' are permissions for changing application connection policies.
I tested this permission.

I believe that editing the organization's policies, including application connection policies, is only allowed to PCA by default.
Set 'manage enterprise policies' to deny for one of the PCA users, but that user could change the application connection policies.
Also, set 'manage enterprise policies' to allow for one of the non-PCA users, but that user could not change the application connection policies.

I think both behave differently than the 'manage enterprise policies' settings.
Please update the documentation with a correct description of how this permission works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - Thank you for your inquiries. I'm looking into getting you some answers. Can you let me know if you are working in the cloud or on-premises?

**Comment by tomaeda** [comment]
@KathrynEE - Thank you for confirmation. I work in cloud. If you have any information, please let me know.

**Comment by KathrynEE** [comment]
@tomaeda - Permissions assigned to the **Project Collection Administrators** and **Project Administrators** group can't be changed. While you can change the permission assignments for a member of these groups, there effective permissions will still conform to those assigned to the administrator group for which they are a member. I am updating the documentation to clarify this.

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
