### ISSUE TITLE
Missing end of sentence

### ISSUE THREAD

**Issue by Sherrec** [MicrosoftDocs/azure-devops-docs#12791]
Under the heading 'Mark a checklist item as done' .  The text states 'The State of the work item is updated from Active to Closed for Agile and CMMI projects and from To Do to Done for Scrum projects, and'

sentence after 'and' is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa6053a3-546f-b48c-9bca-69b4dfbd7bd6
* Version Independent ID: f1d24b19-5716-be97-08ab-5be69881b96e
* Content: [Add tasks or other child work items to checklists - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/boards/add-task-checklists?view=azure-devops)
* Content Source: [docs/boards/boards/add-task-checklists.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/boards/add-task-checklists.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Fixing this with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5181.
