### ISSUE TITLE
Missing codeCoverageRestoreOriginalPomXml  property in documentation

### ISSUE THREAD

**Issue by meehaws** [MicrosoftDocs/azure-devops-docs#12795]
This documentation is missing codeCoverageRestoreOriginalPomXml option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81921de1-7801-99b8-30ff-92530ceb49b2
* Version Independent ID: 50fb21ad-2049-fd80-db73-3d78c305cdac
* Content: [Maven build and release task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/build/maven.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
@meehaws That task input has been added in our new task reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-v4?view=azure-pipelines

Thank you for letting us know.
