### ISSUE TITLE
I changed 'Administer build resource permissions' in organization-level permission, but it doesn't work

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12792]
In the documentation, 'Administer build resource permissions' states that it includes the following operations:
- Set retention policies
- Set resource limits for pipelines
- Add and manage agent pools
- Add and manage deployment pools

However, I believe that all four of these features can set permissions for each.
I've tested it, but per-features permissions work regardless of whether 'Administer build resource permissions' is allow or deny.
If the documentation is outdated, please change it to the correct description.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - You are correct that permissions can be set at the object level, project level, and even role-based that can affect access to the build resources. I am in the process of updating the article to reflect this and will update this issue when that is done.

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
