### ISSUE TITLE
There is an item in organization-level permission that is not documented.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12790]
There is an item in organization-level permission that is not documented.

I compared doumented organization-level permission with [organization settings] - [permissions].
There was an undocumented 'Manage pipeline policies' permission.
Please write a description of this permission in the documentation.

I think this is the permission to allow editing [organization settings] - [pipelines] - [settins].

![image](https://user-images.githubusercontent.com/79292498/196608572-7738a9bc-4e22-473a-841f-e56e2d797a66.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - Thank you for bringing this to our attention.  You are correct that the Manage pipeline permissions controls who can manage the features listed under **Organization settings>Pipelines>Settings.** I'm updating the permissions.md article and will close this issue when published. We will be adding an article that will provide more detail on the settings in the next month or so.

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
