### ISSUE TITLE
'Edit instance-level information' permission to allow, but cannot add users or groups.

### ISSUE THREAD

**Issue by tomaeda** [MicrosoftDocs/azure-devops-docs#12798]
'Edit instance-level information' is written in document that can add users and groups and edit organization-level permissions.
However, I change to allow this permission to one of the non-PCA users, who could not add users or groups.
The user could only edit organization-level permissions.
If the documentation is outdated, please correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tomaeda - Thank you for the feedback. The information about Edit instance-level information is indeed incorrect as written. I'm updating the article to correct it.  For now, here is the essential information:

**Comment by KathrynEE** [comment]
@tomaeda - Closing this issue as article has been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5179.
