### ISSUE TITLE
fileSharePath should lead with double backslash

### ISSUE THREAD

**Issue by rbancroft** [MicrosoftDocs/azure-devops-docs#12805]
Hello,

The fileSharePath needs to have a leading double backslash. The documentation as written specifies `\server\folderName`, however the agent writes it to that folder on the local machine, and not a share. should be `\\server\folderName`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@rbancroft -- Ryan, thank you for your feedback and PR!

**Comment by steved0x** [comment]
This will be live today, in the new task location:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines
