### ISSUE TITLE
Sample Powershell script needs updating

### ISSUE THREAD

**Issue by PhilEmpyrean** [MicrosoftDocs/azure-devops-docs#12809]
This article has just saved me a lot of effort thanks :)
However, I think there's an issue with the PowerShell scripts to add/remove the firewall rules, according to the docs, -FireWallRuleName should be RuleName and -ResourceGroupName is unnecessary in each of the function calls:

-       Get-AzureSqlDatabaseServerFirewallRule
-       New-AzureSqlDatabaseServerFirewallRule
-       Set-AzureSqlDatabaseServerFirewallRule
-       Remove-AzureSqlDatabaseServerFirewallRule

_-FirewallRuleName $FirewallRuleName -ResourceGroupName $ResourceGroupName_ 

should actually be:
_-RuleName $FirewallRuleName -ResourceGroupName $ResourceGroupName_ 

Ref:
https://learn.microsoft.com/en-us/powershell/module/servicemanagement/azure.service/new-azuresqldatabaseserverfirewallrule?view=azuresmps-4.0.0
https://learn.microsoft.com/en-us/powershell/module/servicemanagement/azure.service/set-azuresqldatabaseserverfirewallrule?view=azuresmps-4.0.0

etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/azure-sqldb.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-targets**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@PhilEmpyrean Thank you for the great feedback!
