### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by papiermache** [MicrosoftDocs/azure-devops-docs#12807]
totally useless and incomplete - at least for 'yaml' version. please finish this page!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5162e55f-4ab3-ad76-c5ad-300a71e4b733
* Version Independent ID: b22a98c8-57a7-258a-0941-70fabbca2ac2
* Content: [Restore NuGet packages in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/packages/nuget-restore.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@papiermache -- thank you for your feedback.  Please provide some additional details about what you would like to see included.
