### ISSUE TITLE
Alphabetical list has translation problems.

### ISSUE THREAD

**Issue by jonas-delleske** [MicrosoftDocs/azure-devops-docs#12816]
The alphabetical list is not ordered correctly in translations. 
It should be dynamically orderd by the localized names.

Please just stop those automatic translations. You obviously dont really care about the quality (this is not the first case i stumbled apon). And developers dont care either. The first click for me (and anyone on my team) is to get the english text. Please stop delivering the translated pages to google.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12084832-5567-c723-2e87-aeaac920aa31
* Version Independent ID: 7620ba4b-7bbd-0c1d-882f-374b9278a315
* Content: [Learn default and system work item field descriptions - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/work-item-field.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/guidance/work-item-field.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@jonas-delleske -- Jonas, thank you for your considered feedback.  You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
