### ISSUE TITLE
In Azure DevOps Server 2020, contrary to what is stated in the online help under "Set run retention policies", it is not possible, to for example set the symbols retention time.

### ISSUE THREAD

**Issue by kkluwehkg** [MicrosoftDocs/azure-devops-docs#12817]
**What is shown in the Online Help:**
![image](https://user-images.githubusercontent.com/40393091/197524107-7330e058-9dbc-4f34-b65f-7dd025d84635.png)

**What is shown in Azure Devops Server 2020**
![image](https://user-images.githubusercontent.com/40393091/197524316-a67270df-542d-4877-abce-72f0bb203180.png)

_Tested with Azure DevOps Server 2020, Update 1.2, 18.181.32404.7_

**Comment by WilliamAntonRohm** [comment]
This is the article in question:
- [Set retention policies for builds, releases, and tests](https://learn.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops-2020&tabs=yaml)

**Comment by juliakm** [comment]
@kkluwehkg Thanks for the detailed report. While I don't see the settings for DevOps Server 2019.1, I do see them for DevOps Server 2020 and 2020.1. 

I'll update the article to not show this section for DevOps Server 2019, which has been incorrectly displaying. 

![Screenshot 2023-06-21 at 4 02 58 PM](https://github.com/MicrosoftDocs/azure-devops-docs/assets/64906/96a993a5-9d19-4014-8dc5-7e6d58898ebf)
