### ISSUE TITLE
"What is" a deployment ring

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/azure-devops-docs#12812]
Why not include something, _anything_, that actually says **what** **a** **deployment** **ring** **actually** **is**???????  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 076cd358-0935-41ac-ed07-96ac5ce4c914
* Version Independent ID: 17f39a3c-db2f-37d1-05d1-e1387e0297e8
* Content: [Progressively expose your releases using deployment rings - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/migrate/phase-rollout-with-rings?view=azure-devops)
* Content Source: [docs/migrate/phase-rollout-with-rings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/phase-rollout-with-rings.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-migrate**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by KathrynEE** [comment]
@zissbilloutlook - Thank you for your inquiry and apologies for the lack of clarity. **Deployment rings** are groups of devices used to initially pilot, and then to broadly deploy, each feature update in an organization.  I'll make sure to update the article with this explanation.  Here are a few more resources: 

- [How Microsoft develops with DevOps](https://learn.microsoft.com/en-us/devops/develop/how-microsoft-develops-devops)
- [Shift right to test in production](https://learn.microsoft.com/en-us/devops/deliver/shift-right-test-production)
- [Considerations for updating a multitenant solution](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/updates)
