### ISSUE TITLE
Azure Static Web App documentation page exists twice?

### ISSUE THREAD

**Issue by chriswue** [MicrosoftDocs/azure-devops-docs#12829]
Why does https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-static-web-app?view=azure-devops
exist in addition to
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-static-web-app-v0?view=azure-pipelines?

The latter seems more complete in terms of documentation. It's confusing to have two documentation pages for seemingly the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Version Independent ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Content: [Azure Static Web App task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-static-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-static-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/azure-static-web-app.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@chriswue -- thank you for your feedback.  I'm not sure of the difference myself.

@steved0x -- please look into this issue.

**Comment by steved0x** [comment]
@chriswue Hi Chris, the 2nd one is a new autogenerated task reference from the tasks source code, that combines the examples and remarks from the original manually authored tasks, combined with autogenerated YAML syntax block and task input list. The initial release of the new tasks was done in preview, but it has officially released now and the older task reference has been retired, and redirects to the new task reference.
