### ISSUE TITLE
Effects of removing a user from the organization 

### ISSUE THREAD

**Issue by JJKW1984** [MicrosoftDocs/azure-devops-docs#12824]
Can we add the effects of removing a person from the organization and/or project on the work items, comments, queries etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27d0fe85-7e69-29b7-206f-797a168505c1
* Version Independent ID: 0e1f085d-0d1f-32bf-51e2-c60bc3f0a763
* Content: [Delete, remove users from team, project, organization - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/delete-organization-users?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/accounts/delete-organization-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/delete-organization-users.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @JJKW1984, absolutely. Thanks for the suggestion. I've created a user story for this update. Once my changes go live, this issue will automatically close. Thanks again!
