### ISSUE TITLE
Is there any way to setup column width in wiki?

### ISSUE THREAD

**Issue by fazhong-ms** [MicrosoftDocs/azure-devops-docs#12827]
https://learn.microsoft.com/en-gb/azure/devops/project/wiki/markdown-guidance?view=azure-devops#tables

![image](https://user-images.githubusercontent.com/71804222/198202136-c441ae42-182e-496b-8dd4-1d2c7edad101.png)

This is the default width, we need to make the third one with longer width.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://learn.microsoft.com/en-gb/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by fazhong-ms** [comment]
And remove the scroll bar.

**Comment by WilliamAntonRohm** [comment]
@fazhong-ms -- thank you for your question.  My research indicates that each browser decides the column width when rendering tables.  

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
