### ISSUE TITLE
UsePythonVersionV0 task has new inputs that are not documented.

### ISSUE THREAD

**Issue by twinter-amosfivesix** [MicrosoftDocs/azure-devops-docs#12832]
[This PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16217) added new inputs around automatic downloading of Python versions (such as `disableDownloadFromRegistry`, `allowUnstable`, `githubToken`). Those are not listed here. In fact the entire automatic download feature is not even mentioned here. 

Though I cannot get it to work on my self-hosted agent. Perhaps it's not entirely working? :-) (Not asking for help with that. This issue is just about the docs.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d52f9bd-a63c-d65f-ad92-7f245e4eb5c0
* Version Independent ID: 51ce0fb6-3195-6593-bd62-57c1c0157989
* Content: [Use Python Version task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/tool/use-python-version.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@twinter-amosfivesix Please check out the new task reference that is currently in preview. The UsePythonVersion@0 there has the 3 new task inputs that were introduced in the PR that you reference. Does that info help?

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines
