### ISSUE TITLE
No Pipeline Template for 'Node.js Function App to Windows on Azure'

### ISSUE THREAD

**Issue by m365ken** [MicrosoftDocs/azure-devops-docs#12844]
https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=javascript%2Ctfs-2018-2%2Cbrowser

I am testing a deployment for a node.js Windows function app. After I select the appropriate repo, the Configure step does not offer a template for 'Node.js Function App to Windows on Azure'. I've resorted to modifying a yaml file for the 'Node.js Function App to Linux on Azure' template but would be nice if there were an official template for this. Thanks.

**Comment by WilliamAntonRohm** [comment]
@m365ken -- thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
