### ISSUE TITLE
Purhase instructions for Microsoft-hosted jobs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/azure-devops-docs#12842]
Regarding

> Select Parallel jobs under Pipelines, and then select either Purchase parallel jobs for Microsoft-hosted jobs or Change for self-hosted jobs.

This does not match the current UI. Here's how it looks:

![image](https://user-images.githubusercontent.com/1765732/199357733-7bce5100-e4db-4e62-86e9-f3e67e2b8f0f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#how-do-i-buy-more-parallel-jobs)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/licensing/concurrent-jobs.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@VitalyMCT Thanks! I'll update the screenshot now.
