### ISSUE TITLE
How can I refer and/or link to Work Items in another project of the same organization

### ISSUE THREAD

**Issue by svdHero** [MicrosoftDocs/azure-devops-docs#12851]
I could not find any instructions in the text how to create links between work items across projects. Also, I would like to reference to work items in a different project via Hash-Item-Number. How do I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0aa4019-9343-7791-d5e6-d68063cea6c4
* Version Independent ID: a165a19b-2caa-f7f3-d202-1ca4d1e20049
* Content: [Link user stories and issues to other work items in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/add-link.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/add-link.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@svdHero - Thank you for your inquiry. The first paragraph states:  _"You can link work items within your project or to work items within another project in your organization."_ All regular links you can use to link work items within your project you can use to link to work items defined in other projects within your organization or collection. To link to work items in another organization linked by Azure Active Directory, you need to use a Remote link type as described in [Link to a remote work item](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/add-link?view=azure-devops&tabs=browser#link-to-a-remote-work-item). 

As for using #ID to link to work items, you can do that in the Description or Discussion field (or any HTML field).  The process is the same as described here: [Link work items to other objects](https://learn.microsoft.com/en-us/azure/devops/notifications/add-links-to-work-items?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops).  You enter # and the ID of the work item and then click on the option that it shows. Note that the link will appear in the Rich Text box you place it in, but not be counted or show up on the LInks tab. 

![image](https://user-images.githubusercontent.com/10856840/199838490-8a742a9f-15c5-4836-a6e0-c3bddbe51b85.png)

**Comment by svdHero** [comment]
@KathrynEE Unfortunately, this does not work for me. When linking or mentioning work items, only items from within the same project are shown/suggested. Although I am Project Administrator of both projects, I cannot link work items across projects.

Let's assume we have a project one called "ProjA" with Work Item 4000 and project two called "ProjB" with Work Item 5000. Could you please explain in detail how I would mention Work Item 5000 in the description for Work Item 4000?

If I just type
```
See item #5000
```
it does not show up in the autocomplete suggestion list.

So what am I doing wrong?

**Comment by KathrynEE** [comment]
@svdHero - I'm sorry you're running into difficulties. The linking should work as indicated. The only possibilities I can think of are: 
- You've been added to a group that is limiting your permissions to view or edit work items in ProjB. 
- You may have encountered an issue with the New Boards Hub preview feature - mentioned here: [New Boards Hubs now available in public preview](https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-202-update#new-boards-hubs-now-available-in-public-preview). Several bugs have been reported here: [New Boards Hub, Sprint 209 Update](https://devblogs.microsoft.com/devops/new-boards-hub-sprint-209-update/). If it is enabled, I recommend you disable the preview feature, refresh your browser, and see if that resolves the issue. If is the issue - please report the problem. 

If neither of these issues are the problem, I recommend you report your issue on our [Developer Community page](https://developercommunity.visualstudio.com/AzureDevOps).
