### ISSUE TITLE
No mention of Cache post-job that gets added and is required to run.

### ISSUE THREAD

**Issue by lzandman** [MicrosoftDocs/azure-devops-docs#12855]
There isn't any mention of the fact that there's a required Cache post-job that gets automagically added to a pipeline, but only if it succeeds succesfully.

See: https://github.com/MicrosoftDocs/azure-devops-docs/issues/12854

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4422fc0a-f980-9967-1157-d780b644a3ca
* Version Independent ID: adaf52da-a9b7-1057-0c61-d3498b3d3e3c
* Content: [Cache task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/cache.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/cache.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Related to #12854.
