### ISSUE TITLE
Make it more clear there's a post-job, but only if a pipeline has run succesfully!

### ISSUE THREAD

**Issue by lzandman** [MicrosoftDocs/azure-devops-docs#12854]
In my opinion the Pipeline Caching documentation should state more clearly that there's a required post-cache job that auto*magic*ally gets added to the pipeline, but only when the pipeline has finished succesfully!

I found this out the hard way, after trying to add caching to an existing pipeline, that had many other long-running tasks after the caching part, which didn't need to run for me to test caching. To make my pipeline finish faster while developing it, I had my pipeline purposely fail after the caching task. But by doing so the post-job was never run!

The current article says:
> "After all steps in the job have run and assuming a successful job status, a special "save cache" step is run for each "restore cache" step that wasn't skipped. This step is responsible for saving the cache."

But this text is rather hidden. In my opinion it warrants a separate paragraph or maybe even one of those specially highlighted note sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd39237-2778-c4f1-3ce4-bde343ecb59d
* Version Independent ID: e3daf460-128d-cb57-e899-ca0c841dff07
* Content: [Pipeline caching - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/caching.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Related to #12855.

**Comment by ramiMSFT** [comment]
@lzandman Thanks for your feedback! The updated version will be available soon.
