### ISSUE TITLE
Inaccuracy in Analytics view screenshot

### ISSUE THREAD

**Issue by saimtiruvuri** [MicrosoftDocs/azure-devops-docs#12857]
We noticed that the Analytics views is under the overview section in our production ADO account but the screenshot in the document shows that its under "Boards" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1556d72-e3dc-2d47-f326-ff0b24f879cb
* Version Independent ID: 2e4122d2-2292-8488-f36f-8feb0ce3e450
* Content: [Create an Analytics view - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/powerbi/analytics-views-create?view=azure-devops)
* Content Source: [docs/report/powerbi/analytics-views-create.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/powerbi/analytics-views-create.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@saimtiruvuri - Thank you for bringing this to our attention. I will update the article and close this issue once the updates are published.

**Comment by KathrynEE** [comment]
@saimtiruvuri - The screenshot has been updated to reflect the correct image.

**Comment by saimtiruvuri** [comment]
Thank you for the prompt action @KathrynEE
