### ISSUE TITLE
"go get" via https can omit "_git/" from repo URL

### ISSUE THREAD

**Issue by codeout** [MicrosoftDocs/azure-devops-docs#12869]
[Enter feedback here]

In "Go get with private projects" -> "HTTPS" section, there are possible typos.

```
go get dev.azure.com/<organization>/<project>/_git/<repo>.git
                                              ^^^^^
```

```
go get dev.azure.com/<organization>/<project>/_git/<repo>.git/subfolder1
go get dev.azure.com/<organization>/<project>/_git/<repo>.git/subfolder1/subfolder2
                                              ^^^^^
```

- Those don't match with "instedOf" config of git
- Those don't match with the URL for SSH

Tested with `go version go1.19.2 darwin/amd64` and `go get` worked without `_git/`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/go-get.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@codeout -- Shintaro, thank you for researching this issue.

@vijayma -- Vijay, please review this change in [private PR 5247](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5247).
