### ISSUE TITLE
How to create a serviceEndpoint via Azure DevOps REST API with an approver or group of approvers?

### ISSUE THREAD

**Issue by neok-g** [MicrosoftDocs/azure-devops-docs#12861]
I am using the Azure DevOps REST API to create a serviceendpoint/serviceconnection which works fine. I am using the following endpoint: https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-6.0&tabs=HTTP

However we would like to specify a group of approvers as you can do via the Azure DevOps portal like shown below:

![image](https://user-images.githubusercontent.com/3228810/200327794-462bad2d-a8e0-4364-903e-35d28b9b2588.png)

Project Settings->Serviceconnections-> Approvals and check

Can this be done via the Azure DevOps REST API?

**Comment by neok-g** [comment]
These are pretty general resources. But anyway I found a solution so I will close this issue.

**Comment by WilliamAntonRohm** [comment]
@neok-g -- thank you for your follow-up.  For future reference, what is your solution?

**Comment by neok-g** [comment]
> @neok-g -- thank you for your follow-up. For future reference, what is your solution?

@WilliamAntonRohm https://stackoverflow.com/questions/74348387/how-to-create-a-serviceendpoint-via-azure-devops-rest-api-with-an-approver-or-gr
