### ISSUE TITLE
Maximum number of Service Connections and scope for that limit

### ISSUE THREAD

**Issue by garysxiq** [MicrosoftDocs/azure-devops-docs#12868]
[Enter feedback here]
Can this page be updated with the maximum number of service connections and the scope for that limit e.g. X number per project or organisation?
If there is no upper limit that should be listed as well. This may influence the project and service connection distribution strategy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99b303fd-35ac-93bc-13d0-eb9b5a544166
* Version Independent ID: 531bc055-0e2f-2176-887c-d81260a08325
* Content: [Service and rate limits - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/user-guide/service-limits?view=azure-devops)
* Content Source: [docs/user-guide/service-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/user-guide/service-limits.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@garysxiq - Thank you for your inquiry. With regards to service connections - are you referring to the number of users from an organization or project that can be active at any one time? I don't think there is a limit on this number, but I will check with the product group. Other resources you might check are: [Usage monitoring](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/usage-monitoring?view=azure-devops) and [Rate limits](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops). 

I believe that the limits imposed have to do with overall usage per person.

**Comment by garysxiq** [comment]
> @garysxiq - Thank you for your inquiry. With regards to service connections - are you referring to the number of users from an organization or project that can be active at any one time? I don't think there is a limit on this number, but I will check with the product group. Other resources you might check are: [Usage monitoring](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/usage-monitoring?view=azure-devops) and [Rate limits](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops).
> 
> I believe that the limits imposed have to do with overall usage per person.

Hi Kathryn thanks for getting back to me so quickly. I'm referring to the number Service Connections that can be created against a given project e.g. for Azure these would usually be linked to the deployment Service Principal. This screen - https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints

**Comment by KathrynEE** [comment]
@garysxiq - Thank you for the clarification. I've contacted the product team and will respond when I hear back from them.

**Comment by jjnanthakumar** [comment]
Please let us know if there are any limitations in Service Connections (numbers) and variable groups.

**Comment by KathrynEE** [comment]
@garysxiq, @jjnanthakumar - We don't have any limits from the Azure DevOps Services side on creating the service principal, however, there may be limits which are imposed through Azure Active Directory. Please see the following articles: 
- [Azure AD service limits and restrictions](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/directory-service-limits-restrictions) 
-  [Azure subscription and service limits, quotas, and constraints](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits)

I will update the referenced article above with links to these articles and close this issue once those updates are made.

**Comment by jjnanthakumar** [comment]
@KathrynEE I am not asking about the service principal in Azure. I need to know the limits in Azure DevOps **Service Connections** (Genric type).

**Comment by garysxiq** [comment]
Thanks @KathrynEE  for confirming that the Azure DevOps service connections do not have any limit per project.

> @garysxiq, @jjnanthakumar - We don't have any limits from the Azure DevOps Services side on creating the service principal, however, there may be limits which are imposed through Azure Active Directory. Please see the following articles:
> 
> * [Azure AD service limits and restrictions](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/directory-service-limits-restrictions)
> * [Azure subscription and service limits, quotas, and constraints](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits)
> 
> I will update the referenced article above with links to these articles and close this issue once those updates are made.

**Comment by garysxiq** [comment]
Sorry accidentally closed. I'll leave you to close post doc update
