### ISSUE TITLE
Mac OS Excel connector?!

### ISSUE THREAD

**Issue by JulessZ** [MicrosoftDocs/azure-devops-docs#12862]
When will be developed a connector for MAC Excel? is this feature on the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Modify Azure Boards work items in bulk with Microsoft Excel - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@JulessZ -- Juless, thank you for your question.  If support is planned, it will be added to the [Azure DevOps Roadmap](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline) and the [Azure DevOps Roadmap backlog items](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_backlogs/backlog/AzureDevOpsRoadmap%20Team/Roadmap%20Items).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by JulessZ** [comment]
@KathrynEE, thanks for the answer. It's sad to hear that it will not support it. I think there are and there will be a lot of people with mac's working on Azure DevOps. I know the CSV is a solution but honestly not the sweetest. Is there a possibility to reopen the old votation to not start a new one?

Kind regards, Julius
