### ISSUE TITLE
Collaborator or Contributor?

### ISSUE THREAD

**Issue by worldspawn** [MicrosoftDocs/azure-devops-docs#12871]
After you add the build user to the feedback as a Collaborator the user appears in the list as a Collaborator. Then when you refresh the permission list the user becomes a Contributor. Highly confusing

![Animation](https://user-images.githubusercontent.com/819581/201048976-a5d6a2ae-be73-4fc9-ac8f-b59158bb3d08.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0bcda9e-abbb-0570-2397-61f2eeb23dfa
* Version Independent ID: ed85a958-f5fb-59b4-3f1f-cd754bec508e
* Content: [Allow Pipelines to access project-scoped feeds that are scoped to a different project - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/project-scoped-feeds-pipeline-project-permissions?view=azure-devops)
* Content Source: [docs/artifacts/how-to/project-scoped-feeds-pipeline-project-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/how-to/project-scoped-feeds-pipeline-project-permissions.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@worldspawn -- Sam, thank you for your graphic feedback!  If you feel this is a product issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

@ramiMSFT -- Rami, please look into this potential documentation issue.

**Comment by worldspawn** [comment]
Well I'm not sure what it is. After adding the account and it flips to Contributor the build _can_ authenticate with the feed.

**Comment by ramiMSFT** [comment]
@worldspawn Thank you for the great feedback! 

@daneshbadlani FYI

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
