### ISSUE TITLE
More detailed information about target path

### ISSUE THREAD

**Issue by dbyte** [MicrosoftDocs/azure-devops-docs#12879]
There is no information as to whether an **existing** relative path must be specified for the target `path` parameter or whether a non-existent (relative) directory or tree  is created automatically.

In general, one would wish that the path logic for uploaded and downloaded artifacts was described in more detail. The examples alone are not enough.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and download artifacts in your pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/pipeline-artifacts.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@dbyte Thanks for the feedback! I'm adding clarifications shortly
