### ISSUE TITLE
Where is witadmin in Visual Studio community 2022?

### ISSUE THREAD

**Issue by JohnDelisle** [MicrosoftDocs/azure-devops-docs#12876]
Your documentation is out of date, and does not apply to Visual Studio 2022.

Where can I find the witadmin tool, in current versions of Visual Studio 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1b1b597-3b63-8f19-56a7-d14285553983
* Version Independent ID: 36c11397-2887-731a-3262-35a07b699aa1
* Content: [Manage work item fields using witadmin - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/reference/witadmin/manage-work-item-fields?view=azure-devops)
* Content Source: [docs/reference/witadmin/manage-work-item-fields.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/reference/witadmin/manage-work-item-fields.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JohnDelisle  - Thank you for the feedback. You can find **witadmin** in the following paths depending on your version:  
```
- \Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
- \Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
- \Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer```
- 
I will update the article to reflect this in the coming week.

**Comment by JohnDelisle** [comment]
Thank you - appreciate your help.

**Comment by KathrynEE** [comment]
Closing this issue as articles have been updated with https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5293.
