### ISSUE TITLE
NuGet References

### ISSUE THREAD

**Issue by thegreatpeon** [MicrosoftDocs/azure-devops-docs#12874]
Some of the documentation still references NuGet documentation (command).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/universal-packages.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @arob98
* Microsoft Alias: **angrobe**

**Comment by steved0x** [comment]
@thegreatpeon We just published a new task reference tat is autogenerated based on the task source code and task metadata database in Azure DevOps Services (and Azure DevOps Server versions). I took a look at the new version of the task and I didn't see any references to the NuGetCommand task. Could you check out the new version of the article, and let us know if the issue you noted has not been resolved with this update?

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/universal-packages-v0?view=azure-pipelines

Thank you

**Comment by thegreatpeon** [comment]
It looks like the documentation still references NuGet in the Command section
![image](https://user-images.githubusercontent.com/1681916/207169548-edaef6fe-9364-4645-ba0e-255efef14f47.png)
