### ISSUE TITLE
Azure Repos bot: pull request subscription instructions don't explain how to get a valid reviewer group

### ISSUE THREAD

**Issue by 2BitSalute** [MicrosoftDocs/azure-devops-docs#12884]
We have more than 100 groups, so the dropdowns don't work.
I tried various formats and permutations, but all I get in the end is this unhelpful error message:

![image](https://user-images.githubusercontent.com/23589257/201539879-293b0305-0ea5-4021-9c17-16fcbc664d05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/integrations/repos-teams.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@2BitSalute - Apologies for the problems you are seeing. I'm not able to help on the documentation side. I recommend you post the issue you're seeing on our [Developer Community page](https://developercommunity.visualstudio.com/AzureDevOps/report).
