### ISSUE TITLE
Azure Repos + Teams instructions are confusing

### ISSUE THREAD

**Issue by 2BitSalute** [MicrosoftDocs/azure-devops-docs#12883]
[Enter feedback here]

The key is that you can't just paste any of the commands.
In order to get a response from the bot, you have to type the command and let Teams resolve the bot's name.

This may be obvious, but it wasn't obvious to me. "Run command" to me means I can paste it.

It's also not clear *where* you "run the command". Answer: you can run it in reply to the bot's post, for example.

I finally got somewhere with https://superuser.com/questions/1533925/how-to-use-azure-repos-app-on-ms-teams
The official doc was unhelpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/integrations/repos-teams.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@2BitSalute - Thank you for your feedback. I have added a work item to update the content with more helpful information. I'll close this issue once the article is updated.

**Comment by KathrynEE** [comment]
@Chcomley - I reached out to the Respositories Teams channel to see if someone can help with this issue. 
Once you've addressed [User Story 38428](https://dev.azure.com/msft-skilling/Content/_workitems/edit/38428): How to use Azure Repos with Microsoft Teams [Update] you can close this issue.

**Comment by bjanousek** [comment]
I believe the details about how to interact with the application is explained in the documentation here (https://learn.microsoft.com/azure/devops/repos/integrations/repos-teams#add-the-azure-repos-app-to-your-team-in-microsoft-teams). Cite:
Use the `@azure repos` handle to start interacting with the app.

Should we explain more what this means here? I believe this (what mans to use the handle and that you need the Team to recognize the handle and thus need to type that in) is kind of known to anyone using the Teams application.
