### ISSUE TITLE
Sample payload for "Work item updated" is wrong

### ISSUE THREAD

**Issue by SimonLuckenuik** [MicrosoftDocs/azure-devops-docs#12893]
The payload shown is for `git.push` event type, should be payload for `workitem.updated`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks events - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#workitem.updated)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/service-hooks/events.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-service-hooks**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you @SimonLuckenuik, I've created a user story to cover this work!
