### ISSUE TITLE
Pipeline resource variable documentation is wrong

### ISSUE THREAD

**Issue by dpowling** [MicrosoftDocs/azure-devops-docs#12899]
Hey, so I have noticed that to use the pipeline resource variables such as; 
- resources.pipeline.{Alias}.runID
that the syntax is actually wrong. The start of each word needs to be capitalised as such;
- Resources.Pipeline.{Alias}.RunID

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Define YAML resources for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/resources.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@dpowling That shouldn't be the case. Can you share a part of your pipeline? What task are you using?

**Comment by juliakm** [comment]
Closing because I cannot reproduce and there has been no response for 2 weeks.
