### ISSUE TITLE
Needs clarity on "consume"

### ISSUE THREAD

**Issue by ThinkElevenDave** [MicrosoftDocs/azure-devops-docs#12890]
It is not clear what is meant by "consume".  Today I bought two parallel jobs and ran a release pipeline.  Once finished, my count was back to zero.  However, the terminology used in the view page was "monthly" so I expected the parallel functionality to be available for an entire month.  Otherwise this will cost thousands of dollars per month to save a few minutes each release...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/licensing/concurrent-jobs.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ThinkElevenDave If you use release or YAML pipelines, then a run consumes a parallel job only when it's being actively deployed to a stage. While the release is waiting for an approval or a manual intervention, it doesn't consume a parallel job. Please see the section, [How is a parallel job consumed in DevOps Services?](https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#how-is-a-parallel-job-consumed-in-devops-services).

**Comment by ThinkElevenDave** [comment]
Hi.  Please let me describe our situation then I'll return to your post.  I'm new to DevOps and this is not intended as a rant.

Currently we're using the free tier and have a release pipeline with around 60 steps (6 steps x 10 clients who have their own transformed version of the same app) - its a big flow chart IMHO.

Sometimes jobs start immediately.  Other times, like today, I've been waiting 14 minutes for an agent which eventually started and finished the first task.  Then I'm sat waiting for an agent again for the next step.  So in total this entire pipeline looks like it will take about 3 hours to deploy using current wait times, which is frustrating when our previous in-house ad-hoc PowerShell routine took about 15 minutes.

So I was investigating purchasing parallel jobs as a way to speed things up (based on recommendations from other forums).  However the DevOps portal where I configure this gives me no information about what a parallel job costs, nor what I actually get for it (e.g. a single parallel job / N number of jobs for a period / 1800 minutes of jobs valid for a week/month?):

![image](https://user-images.githubusercontent.com/7942280/234900830-59be65d3-638c-46d9-8ea7-5dc34f69112e.png)

Clicking on the link takes me around in circles and back the above page. There is no information (that I can find) that explains what I can do to shorten these wait/deployment times and what the repercussions might be (especially financial, because the invoice doesn't go to me).  Perhaps my search terminology is incorrect, but I feel like there's not enough information to-hand where it's most needed.

I'll gladly take any advice you can offer on streamlining things for us - premium or otherwise!

**Comment by ThinkElevenDave** [comment]
Please reopen this as I do not feel that the clarity has been provided.
