### ISSUE TITLE
The steps to  link a set of related notifications of azure pipeline in teams channel are not provided.so please provide the steps to solve this. https://github.com/MicrosoftDocs/azure-devops-docs/issues/11815

### ISSUE THREAD

**Issue by krishna1733** [MicrosoftDocs/azure-devops-docs#12897]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@krishna1733 -- please see https://github.com/MicrosoftDocs/azure-devops-docs/issues/11815#issuecomment-1318150793.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
