### ISSUE TITLE
Image links broken.

### ISSUE THREAD

**Issue by sartoriusnoel** [MicrosoftDocs/azure-devops-docs#12910]
Image links broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26c14bb1-b4a9-79de-4fa7-eb66f6ccaa63
* Version Independent ID: d227ffcb-775a-09c5-d8dd-0939aaec975a
* Content: [Connect Azure Boards to an Office client to track your work - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel)
* Content Source: [docs/boards/backlogs/office/track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/track-work.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@sartoriusnoel -- thank you for your feedback.  I'm not seeing any broken image links in this article.  Which links are not showing for you?

**Comment by sartoriusnoel** [comment]
> @sartoriusnoel -- thank you for your feedback. I'm not seeing any broken image links in this article. Which links are not showing for you?

Hi, it's the [](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel) 
page in the "open query in excel" tab half way down.

**Comment by WilliamAntonRohm** [comment]
@sartoriusnoel -- thank you for your followup!  I see that broken image link and I'm updating this article.
