### ISSUE TITLE
exit 1 vs task.complete result=Failed

### ISSUE THREAD

**Issue by san7hos** [MicrosoftDocs/azure-devops-docs#12919]
This document has been advocating for years to use `exit 1` when issuing `task.logIssue type=error`. I am wondering why when you can achieve the same thing by issuing `task.complete result=Failed`. The main advantage of using `task.complete` seems to be that it does not produce an additional error in the ADO build UI.

When `exit 1` is used, there's an additional error that may say something like `PowerShell command exited with 1`. In my opinion, this is not something you'd like to present to the user/developer in most of the cases. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#complete-finish-timeline)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/scripts/logging-commands.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@san7hos I apologize for the delay in responding. I checked with the product team and their feeling is that `exit 1` is more representative of what happens when a pipeline fails. I'll double-check to make sure that `task.logIssue type=error` is also mentioned in our docs.
