### ISSUE TITLE
Test Suite types definitions are confusing

### ISSUE THREAD

**Issue by pashaBerd** [MicrosoftDocs/azure-devops-docs#12913]
Link to the page https://learn.microsoft.com/en-us/azure/devops/boards/queries/build-test-integration?view=azure-devops
Link to the section on the page https://learn.microsoft.com/en-us/azure/devops/boards/queries/build-test-integration?view=azure-devops.

Issue:
Find "Test Suite Type 1" definitions under the section (link is above)
Take a look at Static and Requirement Based test suites.
The problem is that the Static suite has a description from the Requirement-based suite and vice versa.

![image](https://user-images.githubusercontent.com/21027347/203413602-a2479bcb-9200-4470-b738-0969ad8253b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc1abec4-edfe-b170-259b-cd1fa37dead0
* Version Independent ID: 66792b32-3ed8-5d33-82be-66a77f8c35fb
* Content: [Build and test integration queries - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/boards/queries/build-test-integration?view=azure-devops)
* Content Source: [docs/boards/queries/build-test-integration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/build-test-integration.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@pashaBerd -- thank you for catching this.

@KathrynEE -- please review this update in [private PR 5271](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5271).
