### ISSUE TITLE
خاص

### ISSUE THREAD

**Issue by Khaledhfjv** [MicrosoftDocs/azure-devops-docs#12916]
**@****
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 91d0174c-2ab8-1e50-9566-e1366cb39ded
* Version Independent ID: 8ab7e84f-c738-56dc-64a1-55d2cb4c4ed6
* Content: [Migrate from Azure DevOps on-premises to Azure DevOps Services - Azure DevOps](https://learn.microsoft.com/ar-sa/azure/devops/migrate/migrate-from-tfs?view=azure-devops)
* Content Source: [docs/migrate/migrate-from-tfs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/migrate-from-tfs.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@Khaledhfjv -- خالدبخيت, thank you for your feedback.  Please create a new issue with your desired information.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Khaledhfjv** [comment]
> @Khaledhfjv- خالدبخيت ، شكرًا لك على ملاحظاتك. يرجى إنشاء مشكلة جديدة بالمعلومات التي تريدها.
> 
> أنا أغلق هذه القضية الآن. أنتم مدعوون إلى @ ذكرني لأي متابعة. نأمل أن نسمع منك
