### ISSUE TITLE
Stages dependencies

### ISSUE THREAD

**Issue by ThongNCT** [MicrosoftDocs/azure-devops-docs#12920]
"Say you have the following YAML pipeline. Notice that, by default, stage1 depends on stage2 and that stage2 has a condition set for it."

Why do we have "stage1 depends on stage2"?
Should it be: "stage2 depends on stage1"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ThongNCT You're right, fixing this now. Thanks!
