### ISSUE TITLE
Cannot skip "Restore nuget" task even if nugets are restored from cache

### ISSUE THREAD

**Issue by bjarte** [MicrosoftDocs/azure-devops-docs#12926]
I have a problem with the section "Restore cache".

If I understand this correctly, it shouldn't be necessary to run the Restore task if the nuget packages are restored from cache.

That is not my experience. If the nuget packages _are in cache_, but I don't run Nuget restore, I get a million error messages like this in the build task:
[error]NHO.Core\IdentityServerClientStartup.cs(32,12): Error CS0246: The type or namespace name 'OwinStartupAttribute' could not be found (are you missing a using directive or an assembly reference?)

However, if I run the nuget restore task as normal after restoring the nuget packages from cache, it is super quick (~25 seconds instead of 2 minutes).

Does that make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Version Independent ID: 94a47e28-d827-dd09-61f4-7198941d2cb5
* Content: [Cache NuGet packages to reduce build time - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/caching-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/caching-nuget.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@bjarte -- Bjarte, thank you for your clear feedback.

@ramiMSFT -- Rami, please look into this issue.

**Comment by diptim01** [comment]
I'm experiencing the same thing. With MSBuild, you could skip NuGet restore but you must use the /t:restore.
Without that, you get a lot of errors which isn't what we have in MSFT docs

**Comment by ramiMSFT** [comment]
You can use the caching task without the second restore task. This was an example to illustrate the difference in performance when using no caching, a cache miss, and a cache hit. Please refer to this article to [Cache NuGet packages](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget) without the extra restore step. Feel free to leave a comment if you're still experiencing issues.

**Comment by bjarte** [comment]
Here is my pipeline.yml. 

When I run this the last build step crashes with the following error message for each nuget package:
##[error]ProjectName\MyClass.cs(33,12): Error CS0246: The type or namespace name 'OwinStartupAttribute' could not be found (are you missing a using directive or an assembly reference?)

I can see that the nuget packages are cached and stored in the packages directory, but the build step are not able to use them, for some reason, unless I run the nuget restore step _every time_, even if I get a cache hit.


`variables:
  solution: 'MySolution.sln'
  webProjectDirectory: '$(System.DefaultWorkingDirectory)/NHO.Framework.Web'
  publishDirectory: '$(System.DefaultWorkingDirectory)/wwwroot'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

  - checkout: self
    clean: true
    persistCredentials: true

  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget.exe'

  - task: Cache@2
    displayName: 'NuGet cache'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
      restoreKeys: |
        nuget | "$(Agent.OS)"
        nuget
      path: $(NUGET_PACKAGES)
      cacheHitVar: 'CACHE_RESTORED'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    condition: ne(variables.CACHE_RESTORED, true)
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      restoreSolution: '$(solution)'

  # This step is just to confirm that there are packages in the nuget directory
  - task: CmdLine@2
    displayName: Are there packages in the nuget directory?
    inputs:
      script: |
        cd $(NUGET_PACKAGES)
        pwd
        dir

  - task: VSBuild@1
    displayName: 'Build solution, publish files in wwwroot'
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      maximumCpuCount: false
      msbuildArchitecture: x64
      vsVersion: latest
      clean: true
      msbuildArgs:
        /p:DeployOnBuild=True
        /p:WebPublishMethod=FileSystem
        /p:DeployDefaultTarget=WebPublish
        /p:SkipInvalidConfigurations=true
        /p:PublishProvider=FileSystem
        /p:ExcludeApp_Data=False
        /p:publishUrl=$(publishDirectory)
        /p:DeleteExistingFiles=False
        /p:AutoParameterizationWebConfigConnectionStrings=false
        /p:MarkWebConfigAssistFilesAsExclude=False
