### ISSUE TITLE
Define 'inactive' account

### ISSUE THREAD

**Issue by jd1984** [MicrosoftDocs/azure-devops-docs#12936]
Hello, 

Please can you define what is considered an _inactive_ account, for the following two lines.

https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?view=azure-devops
- When the organization owner and all project collection administrators are _inactive,_ the organization is considered orphaned. 

https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?view=azure-devops#prerequisites
- The Azure DevOps Administrator role can only claim ownership of organizations when the current owner and all members of the Project Collection Administrators group are _inactive_ in the backing Azure AD.

https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?view=azure-devops#when-your-azure-devops-administrator-is-a-member-of-the-target-organization
screenshot 3. has a yellow banner to show the owner is _inactive_.

How is this determined? For example: 
- an account which has disabled in AAD?
- an account which has not signed in for _x_ number of days?
- an account which has been deleted from AAD?

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 378ad220-599b-e802-f084-851277cc208d
* Version Independent ID: 8b041bf4-ec98-78bd-99e1-93e9f11225df
* Content: [Assign an owner to an orphaned organization - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/resolve-orphaned-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/resolve-orphaned-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/resolve-orphaned-organization.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jd1984, Thanks for reaching out. I'm working on the article, but here's a link to how Azure AD describes an "inactive" account. Once I've solidified the definition for an inactive Azure DevOps owner/PCA, I'll publish an update to the article, which will include links to both definitions. Thank you!

[What are inactive Azure AD user accounts?](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-manage-inactive-user-accounts#what-are-inactive-user-accounts)

**Comment by jd1984** [comment]
Thanks @chcomley
