### ISSUE TITLE
Ubuntu latest is not pointing to ubuntu 20.04, but to ubuntu 22.04

### ISSUE THREAD

**Issue by popsicleslayer** [MicrosoftDocs/azure-devops-docs#12940]
[Enter feedback here]
Hey! 

Since 1st December, the ubuntu-latest vmImage points to ubuntu 22.04, and not as stated in this doc page to 20.04. This is a breaking change, as the 22.04 uses Python 3.10, which might cause problems for users. I only discovered it because the pipelines that I ran the day before and worked perfectly started breaking in places that are not changed for a long time. Hardcoding the vmImage to 20.04 solved the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by PreslavPetkov-TomTom** [comment]
Same issue here, this change broke our docker push job 
```
Pushing Docker image
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
```
had to manually revert to 20.04
It was a bit confusing since it is not reflected in the docs 
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by steved0x** [comment]
The doc page is updated with 22.04 as ubuntu-latest
