### ISSUE TITLE
In addition to Restrict to only certain states, include "Allow transition to Only Certain States"

### ISSUE THREAD

**Issue by susanalipour** [MicrosoftDocs/azure-devops-docs#12943]
In addition to "Restrict transition to selected states", can you also include an option to "Allow transition to selected states"?
By default, transition to all other states would be restricted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbe3c173-e8cc-7172-7331-11c3fc0f9724
* Version Independent ID: ee6e18ae-8ec3-613d-3644-35f1f2199e77
* Content: [Restrict workflow transitions, apply rules to workflow states - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/apply-rules-to-workflow-states?source=recommendations&view=azure-devops)
* Content Source: [docs/organizations/settings/work/apply-rules-to-workflow-states.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/work/apply-rules-to-workflow-states.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@susanalipour -- thank you for your suggestion.  

@KathrynEE -- is this a documentation issue, or a product enhancement?

**Comment by KathrynEE** [comment]
@susanalipour - By default, with no restriction rules defined, _users can move from one State to any other State, both forward and backward within the sequence_. So, the only rules you need to define are ones that would restrict select state transitions. 

Closing this as addressed. If you have a feature request, then you would have to request that on our [Developer Community page](https://developercommunity.visualstudio.com/AzureDevOps/suggest).
