### ISSUE TITLE
Pipeline output variables documentation is incorrect

### ISSUE THREAD

**Issue by DonadoJuan** [MicrosoftDocs/azure-devops-docs#12942]
The following documentation is not correct.

```
Use outputs in a different stage
To use the output from a different stage at the job level, you use the stageDependencies syntax:

At the stage level, the format for referencing variables from a different stage is dependencies.STAGE.outputs['JOB.TASK.VARIABLE']

At the job level, the format for referencing variables from a different stage is stageDependencies.STAGE.JOB.outputs['TASK.VARIABLE']
```
 The right syntax to share an output variable between stages is `stageDependencies.STAGE.JOB.outputs['TASK.VARIABLE']`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review [private PR 5304](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5304).

**Comment by richardsavenok** [comment]
The documentation issue has not been resolved.

**Comment by WilliamAntonRohm** [comment]
@richardsavenok -- thank you for catching this.  The update went live on 12/15/2022, but as you note it is not in the current documentation.  I am updating this article.
