### ISSUE TITLE
Non existent fields listed

### ISSUE THREAD

**Issue by r8der** [MicrosoftDocs/azure-devops-docs#12955]
In this section https://learn.microsoft.com/en-us/azure/devops/boards/queries/linking-attachments?view=azure-devops&tabs=browser#link-attachment-count-and-comment-fields

"The following table describes fields associated with links and attachments. Most of these fields don't appear within the work item form, but are tracked for all work item types."

This statement assumes these fields exist and can be referenced in a WIQL query.  However, the fields without the *** are not available.  I tried "System.Links.Comment" in a WIQL REST API and got this error "message": "TF51005: The query references a field that does not exist. The error is caused by «[System.Link.Comment]»."

This also occurs for     "message": "TF51005: The query references a field that does not exist. The error is caused by «[System.Links.Description]».",
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6226d23d-0ce9-1f42-1e33-33639b0f58fe
* Version Independent ID: d9629cec-7fd7-5ed4-b51f-5da3a26c0115
* Content: [Query work items by link or attachment count in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/linking-attachments?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/queries/linking-attachments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/linking-attachments.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@r8der - Thank you for your feedback. The Link Comment and Link Description fields aren't available for queries. Their descriptions indicate that with this entry as part of the description: **(Not supported in query editor.)**  

These fields aren't available from the query UI, WIQL, or REST API queries. 

Let me know if you have further questions. Otherwise, I'm closing this as answered.
