### ISSUE TITLE
Please cross reference change to shallow fetch in sept 2022 release

### ISSUE THREAD

**Issue by martillodecampo** [MicrosoftDocs/azure-devops-docs#12959]
The change to the [shallow fetch behavior in the Sept 2022 release as described here ](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=classic#shallow-fetch) has caused us some pain. It would be nice if it was referenced on this page as well.

Thank you. We love Azure DevOps Pipelines!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/pipeline-options-for-git.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@martillodecampo -- Keith, thank you for your actionable feedback and kind words!

@steved0x -- Steve, please look into this issue.
