### ISSUE TITLE
pypirc for pushes instead of for pulls

### ISSUE THREAD

**Issue by inigohidalgo** [MicrosoftDocs/azure-devops-docs#12953]
Minor quirk but in [Connect to feed](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops#connect-to-feed) section, should it read ".pypirc for pushes and pip.ini for pulls" instead? As pypirc is the config file for upload tools like twine or flit, and pip.ini is the config for pip to download the packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6cca7b9-7fe5-bc14-c7da-08983e920f81
* Version Independent ID: 7d8cf191-b229-0e2e-8cb3-01a80c4842fd
* Content: [Get started with Python packages in Azure Artifacts - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/python-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/quickstarts/python-packages.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@ramiMSFT -- Rami, please review this update in [private PR 5522](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5522).

**Comment by ramiMSFT** [comment]
Thanks for your feedback!
