### ISSUE TITLE
How to connect tests and Test Suites/Plans?

### ISSUE THREAD

**Issue by AlexandreGielowPhilips** [MicrosoftDocs/azure-devops-docs#12957]
[Enter feedback here]
Hello, i am trying to understand how to connect the Tests, Test Runs and Test Results with Test Plans or Test Points, but i can't find the relationship, could you help?
![image](https://user-images.githubusercontent.com/93941361/206170670-7311f0e0-7298-42ed-acb7-2826cea43317.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a429e12b-44d1-3c39-a6c9-2c84b043acda
* Version Independent ID: a429e12b-44d1-3c39-a6c9-2c84b043acda
* Content: [Test metadata reference for Analytics - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/analytics/entity-reference-test-plans?view=azure-devops)
* Content Source: [docs/report/analytics/entity-reference-test-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/analytics/entity-reference-test-plans.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@AlexandreGielowPhilips - Have you reviewed the information provided here, [Test objects and terms](https://learn.microsoft.com/en-us/azure/devops/test/test-objects-overview) and specifically the information on [Test terms](https://learn.microsoft.com/en-us/azure/devops/test/test-objects-overview?view=azure-devops#test-terms)?

**Comment by KathrynEE** [comment]
@AlexandreGielowPhilips - I'm closing this issue as it can't be addressed without more information.  The connection of tests, test runs, and test results are automatic. I recommend you post your issue to our [Developer community page](https://developercommunity.visualstudio.com/AzureDevOps/report) if you continue to have problems.
