### ISSUE TITLE
Docs missing for creating publicly readable NuGet feeds

### ISSUE THREAD

**Issue by YarekTyshchenko** [MicrosoftDocs/azure-devops-docs#12961]
The docs say
> Artifact feeds can be private to share your packages with your team and specific users, or public to share them publicly with anyone on the internet.

However, I can't see how to make a feed publicly readable without authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5b066ca-c13e-9f25-3add-844012d105f1
* Version Independent ID: 47ac81a1-d4a7-8d74-b59a-2cf143a9684c
* Content: [Get started with NuGet packages and Azure Artifacts - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/get-started-nuget.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@YarekTyshchenko Public feeds are project-scoped feeds in a public project. Please refer to this article: [Use public feeds to share your packages publicly](https://learn.microsoft.com/en-us/azure/devops/artifacts/tutorials/share-packages-publicly?view=azure-devops). I will be updating the get started one as well.
