### ISSUE TITLE
unecessary task "PublishTestResults" in "Build Python apps" documentation

### ISSUE THREAD

**Issue by ChristopheLallement** [MicrosoftDocs/azure-devops-docs#12960]
It seems that task PublishTestResults is not necessary anymore thanks to  the pytest-azurepipelines plugin.
As stated in  the[ documentation of the pytest-azurepipeline plugin](https://pypi.org/project/pytest-azurepipelines/) :
> Automatically formats code coverage and uploads coverage data if pytest-cov is installed

I followed your example from "[Build Python apps](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)"  
 
But with the addition of the  option `--test-run-title='Test results for Python $(python3.version)'`  in the  pytest command :

```
- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --test-run-title='Test results for Python $(python3.version)'
  displayName: 'pytest'
```

This allows me to remove  the "[Publish test results] step to my pipeline:

```
#- task: PublishTestResults@2
#  condition: succeededOrFailed()
#  inputs:
#    testResultsFiles: '**/test-*.xml'
 #   testRunTitle: 'Publish test results for Python $(python.version)'
```

The test result and code coverage are correctly published anyway.

![image](https://user-images.githubusercontent.com/32416736/206332051-a3d3dd7e-e700-4e6e-a68f-1e130fad194f.png)

![image](https://user-images.githubusercontent.com/32416736/206332209-e2935631-11de-45fd-851f-5c53fec579ce.png)

I was confused and lost a lot of time by the fact that the azure pipeline documentation advises to add the result publication task while the pytest-azurepipeline plugin mentions that there is no need. Then I suggest you modify the documentation in order to be consistent and not to lose your readers with unnecessary steps

**Comment by WilliamAntonRohm** [comment]
@ChristopheLallement -- Christophe, thank you for your thorough feedback.

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
@ChristopheLallement Thanks for the feedback! Looks like we removed that task when we updated the article.
