### ISSUE TITLE
This page offers misleading take on how packages are versioned and released

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-docs#12972]
I do realize that this documentation just reflects the flawed Azure Artifacts functionality, which is built without full understanding of how build maturity works, but I want to highlight that this page solidifies this flawed approach and many people start believing that version components can be used to track build maturity just because Microsoft said so, which is not how it works.

The build process is not supposed to change version components, only the build number. The Product Owner defines what's in the next release and gives it a version to reflect the amount of change, as described in Semantic Versioning.

The dev team starts working on planned features/bugs, producing packages as they move along the backlog. All those packages have *the same version* that the Product Owner said they are working on. What's changing is the build number, which is what is used to track _build maturity_.

This is how your diagram is supposed to look to reflect this process:

![az-release-cycle](https://user-images.githubusercontent.com/7843659/207375779-62c7a1df-b9db-41ec-a3f5-9029ce61e88b.png)

This currently cannot be implemented because Azure Artifacts is implemented as if it's a public package repository, not as a development repository, so it won't accept build numbers, which makes this DevOps functionality not useful for tracking build maturity, even though it uses correct terms, like "promotion".

A couple of related notes, if you got this far in this post.

> There are workarounds to pre-validate (e.g. consume the build's DLLs directly before they're packaged and publish the packages to a "debug" or "CI" environment

This is quite bad, even with a note that it's not advised further in the text. Build pipelines are supposed to build the candidate package every time, so each of them can potentially be released, if it passes the internal validation.  Testing assorted DLLs from the build directories from a build shouldn't be advised, even as a workaround.

> When creating release packages, it's important to convey three pieces of information: the nature of the change, the risk of the change, and the quality of the change.

The example for this paragraph is `1.2.3-beta2`, which is described as if prereleases contribute to a build maturity. They don't. A prerelease is no different from any other release from the build process perspective - it's a public release, with a possible upgrade path for users, just with lower quality.

For prereleases, the Product Owner announces a prerelease public availability and the dev team works towards a prerelease the same way as they would work towards any release - they keep building packages until one of them passes internal validation, which is getting released for wider user testing as an alpha, beta, etc, release.

As the final word, what DevOps Artifacts architects are missing is that development package repositories are are different than public package repositories for released packages. The former takes new builds and makes them available for automated testing, QA and staging environments using build metadata for guidance of what's the latest, so standard tools, like `npm` can be used to manage those packages. Artifactory is a good example of the former. The latter uses only package versions and disregards build numbers, just like any public repository behaves today.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28b723c2-424c-263a-292e-95547303b95f
* Version Independent ID: ef570f9d-0cf4-6afb-2796-0d2a838289ae
* Content: [What are feed views? - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops)
* Content Source: [docs/artifacts/concepts/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/concepts/views.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@gh-andre Thank you for your feedback! Please feel free to [Request a feature](https://developercommunity.visualstudio.com/AzureDevOps/suggest) on Azure DevOps Developer Community.

**Comment by gh-andre** [comment]
@ramiMSFT  Thanks for responding.

I did and it's not going anywhere and the docs keep misleading people with incorrect information.

https://developercommunity.visualstudio.com/t/Make-Azure-DevOps-Artifacts-usable-in-CI/1597091

People keep referring to this page in various conversations and I keep telling them that this page is incorrect and should not be referenced for build maturity management because it's the Product Owner who determines what version is going to be released, not the Build Manager and the build process.

Don't take my word for it and read about _build maturity_ and _build promotion_ in Artifactory docs. It's just incredibly sad that Azure Pipelines can produce artifacts that are perfectly suitable for build maturity management, while Azure Artifacts is completely unusable in any dev build environment because that team thinks that _build promotion_ is intended to work against package versions, not build numbers.

It's unfortunate that Microsoft, one of the leaders in dev tools, provides no way to manage build maturity and instead forces people to misuse version components for this purpose.
