### ISSUE TITLE
The plus (+) and minus (-) on diffs are not obvious

### ISSUE THREAD

**Issue by MScottAdams** [MicrosoftDocs/azure-devops-docs#12974]
[Enter feedback here]
I thought the green plus or minus on the diff meant lines were added or subtracted to that side. But sometimes I see + and sometimes minus and it is not clear at all why
![Example1](https://user-images.githubusercontent.com/59447805/207666820-6e3fcc96-605d-4855-89e5-870b66d3acaf.jpg)
![Example2](https://user-images.githubusercontent.com/59447805/207666857-47960d9a-43bd-48fb-acd7-bf194553b053.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3cfc74-27af-298a-e4a6-7777fbaacbca
* Version Independent ID: ac0163dc-cd4d-82a8-6ab8-56fa09f4c99a
* Content: [Compare files using Team Foundation Version Control - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/compare-files?view=azure-devops)
* Content Source: [docs/repos/tfvc/compare-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/tfvc/compare-files.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@MScottAdams Thanks for your question. We'll look into any changes for the article.
