### ISSUE TITLE
Using REST API to set a longer retainment period is not possible!

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/azure-devops-docs#12987]
The information here is contradicted by this FAQ question and by my own experience, as well as by what Microsoft support tells me.

https://learn.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml#my-organization-requires-us-to-retain-builds-and-releases-longer-than-what-is-allowed-in-the-settings-how-can-i-request-a-longer-retention

_My organization requires us to retain builds and releases longer than what is allowed in the settings. How can I request a longer retention?_

_The only way to retain a run or a release longer than what is allowed through retention settings is to manually mark it to be retained indefinitely. **There is no way to configure a longer retention setting**._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46a129c0-8a1c-40c3-47e6-8d95fbce5f26
* Version Independent ID: 8437e895-7164-8585-3b0d-adacd05e6851
* Content: [Using Tasks to Retain Runs in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/run-retention?view=azure-devops&tabs=powershell)
* Content Source: [docs/pipelines/build/run-retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/run-retention.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @moswald
* Microsoft Alias: **maoswald**

**Comment by WilliamAntonRohm** [comment]
@tripleacoder -- thank you for your thorough feedback.

@juliakm -- please look into this issue.  I am assigning this to you as Matt is not assignable.

**Comment by juliakm** [comment]
@tripleacoder I've checked with the product team and they say that you are right. You need to reach out to support for longer retention. I'll update the article.
