### ISSUE TITLE
These instructions do not work

### ISSUE THREAD

**Issue by waiholiu** [MicrosoftDocs/azure-devops-docs#12984]
I'm able to follow the instructions until I create a service hook and attempt to enter a user token retrieved from Trello.

I get the following error message 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/8047097/208430066-95e9cfb7-519f-438b-b5f1-5d8cd2db9470.png">

Seems the trello user token provided is an incorrect length to what is expected from DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1402b59d-915f-2457-e198-60898fd66191
* Version Independent ID: af8951ef-3bc1-8748-81a5-03696c6f5e85
* Content: [Create a service hook with Trello - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/service-hooks/services/trello?view=azure-devops)
* Content Source: [docs/service-hooks/services/trello.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/service-hooks/services/trello.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-service-hooks**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by kjagh-panagora** [comment]
Bump for this, duplicate issue - Trello token exceeds DevOps token input length (Trello is 76, DevOps maxes at 64).

**Comment by WilliamAntonRohm** [comment]
@kjagh-panagora -- thank you for your followup.  This appears to be a product-related issue, rather than documentation-related; please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
