### ISSUE TITLE
Instructions indicate user should click on "Profile" when they should really click on "Notifications"

### ISSUE THREAD

**Issue by MattRuwe** [MicrosoftDocs/azure-devops-docs#12999]
This page has an image that indicates user's should click on their **Settings** button and then their **Profile** button.  The image following confirms this.  However, The next section assumes that the user has clicked on the **Notifications** button

> From your home page, select  Settings, and then select Profile.

followed by

> The notifications you're subscribed to are indicated with the the blue toggle under State.

But clicking on the profile doesn't automatically take the user to their notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3fac729-92a7-0f85-3e28-3a2515b77fca
* Version Independent ID: 3038ace1-8e10-9d2f-5e8b-2d883d4dd718
* Content: [View subscribed notifications - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/notifications/unsubscribe-default-notification?view=azure-devops)
* Content Source: [docs/organizations/notifications/unsubscribe-default-notification.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/notifications/unsubscribe-default-notification.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-notifications**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @MattRuwe, I'll get this article updated! Once live, this issue will automatically close. Thanks again!
