### ISSUE TITLE
Use Azure Kubernetes Service deprecated since k8s 1.24

### ISSUE THREAD

**Issue by prutsert** [MicrosoftDocs/azure-devops-docs#12996]
As of kubernetes 1.24, the steps provided in the paragraph "Use Azure Kubernetes Service" in this document, don't work anymore. The reason for this is that a secret is no longer automatically created when a new service account is added to kubernetes. Several Azure Devops issues have been logged on this issue, and contain detailed information on possible workarounds, for example:
https://developercommunity.visualstudio.com/t/New-Kubernetes-service-connection-causes/10138123
https://developercommunity.visualstudio.com/t/MS-DevOps-Environment--Cannot-Add-Resou/10154315
https://developercommunity.visualstudio.com/t/Adding-AKS-124x-to-Environment/10170723

The Azure Devops team keeps closing these issues since other options/workarounds are available. However, as the documentation (this document) has not been updated with the specific change in kubernetes 1.24, anyone referring to this document when creating new AKS environments in Azure Devops, might run into the same trap.

My suggestion would be to add a warning to the paragraph about adding an Azure Kubernetes resource, stating that this option is not available from kubernetes 1.24 onward. It might also be a good idea to rename the sub paragraph "Add a non-AKS Kubernetes resource", because this is now the way to add an AKS resource as well.

It might be appropriate to mention a specific difference in the way the old "Use Azure Kubernetes Service" (using linked Azure subscription magic) and the "Use an existing service account" (using manual copying and pasting) options work, as well:
- When adding an Azure Kubernetes resource using Azure subscription dropdowns, the resource within an environment is actually linked to a namespace. This makes it obsolete to add a namespace parameter to the KubernetesManifest task in a deployment, as the namespace is already part of the environment.
- When adding an environment using the manual service account steps, filling in a namespace is required, but it isn't used or recognized inside the KubernetesManifest task in the pipeline. Adding a namespace parameter to the KubernetesManifest task is now required, or the task will use the `default` namespace:
```
##[debug]kubernetesServiceConnection=58xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx1778
##[debug]58xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx1778 data namespace = undefined
##[debug]Namespace was not supplied nor present in the endpoint; using "default" namespace instead.
```
This last thing might be a bug, but given the amount of bugs that get closed as 'not a bug' on the developercommunity, whenever a workaround is available, documenting this probably has a better chance.

Please contact me if you need any more info.
Peter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments-kubernetes.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@prutsert -- Peter, thank you for your thorough feedback.

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
@prutsert There's a fix in place now that should be deployed to everyone. I was just able to add a Kubernetes environment. 

Here are more details on what happened from a [blog post](https://devblogs.microsoft.com/devops/service-connection-guidance-for-aks-customers-using-kubernetes-tasks/). An Azure Resource Manager Service Connection now gets created. 

I'll also update this section of the article.
