### ISSUE TITLE
Error in the documentation ? Pipeline decorator target

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-devops-docs#12993]
The documentation says this regarding target " this target runs before checkout in a YAML pipeline **but after  checkout in a classic build pipeline**."

|Target | Description|
|--- | ---|
ms.azure-pipelines-agent-job.pre-job-tasks | Run before other tasks in a classic build  or YAML pipeline. Due to differences in how source code checkout  happens, this target runs before checkout in a YAML pipeline **but after  checkout in a classic build pipeline**.

I created a dummy decorator with this manifest:
```json
{
    "contributions": [
        {
            "id": "my-required-task",
            "type": "ms.azure-pipelines.pipeline-decorator",
            "targets": [
                "ms.azure-pipelines-agent-job.pre-job-tasks"
            ],
            "properties": {
                "template": "banner-decorator.yml"
            }
        }
    ],
}
```

When I install it and run it on a classic pipeline (with designer), the injection happens **before** the checkout and not after.

![image](https://user-images.githubusercontent.com/6757079/209374490-523f4031-c3b0-4b34-a096-8d6f74f5e6f8.png)

And on the opposite, when I run a YAML pipeline, the injection happens after checkount
![image](https://user-images.githubusercontent.com/6757079/209375418-df60e473-4cc4-4c61-9b2d-36abfbb4a799.png)

### conclusion

The documentation seems to be the perfect opposite of the reality

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-pipeline-decorator.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by lgmorand** [comment]
Hi Chrystal 

Since, it can be boring to repro. Here are two pipelines to show the result :)

Classic: https://dev.azure.com/lgmorand/Demo%20Pipeline%20Decorators/_build/results?buildId=3150&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=78db2542-c627-4140-8a7a-d06178fff4e4

YAML: https://dev.azure.com/lgmorand/Demo%20Pipeline%20Decorators/_build/results?buildId=3151&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by chcomley** [comment]
Thanks so much for the repro and for reaching out, @lgmorand. I'll update the article, which will automatically close this issue, once it goes live. Thanks again!
