### ISSUE TITLE
Wrong Info in the documentation

### ISSUE THREAD

**Issue by SrikanthNani** [MicrosoftDocs/azure-devops-docs#13006]
[Enter feedback here]

The build process whatever has been referred in the documentation was maven but in the project repo of the pet-clinic app there is no pom.xml file. Please check and make the necessary changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37e987a0-b751-8e83-f08c-489148310ba4
* Version Independent ID: 757f6af5-398a-5bbc-a22f-4d6314e39314
* Content: [Build and deploy to a Java web app on Linux - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-webapp?source=recommendations&view=azure-devops&tabs=java-tomcat)
* Content Source: [docs/pipelines/ecosystems/java-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/java-webapp.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@SrikanthNani I see a pom.xml file in both of the referenced repos: https://github.com/spring-petclinic/spring-framework-petclinic and https://github.com/spring-projects/spring-petclinic. I apologize for any confusion. I wonder if this changed recently.
