### ISSUE TITLE
vsmarketplacebadge.apphb.com/ -> https://vsmarketplacebadges.dev/

### ISSUE THREAD

**Issue by jan-dolejsi** [MicrosoftDocs/azure-devops-docs#13004]
The badge source vsmarketplacebadge.apphb.com/ seems to have migrated to https://vsmarketplacebadges.dev/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/manifest.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@jan-dolejsi -- Jan, thank you for your feedback.  This substitution is mentioned in the Note in the following section:
- [Supported badge services](https://learn.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#supported-badge-services)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
