### ISSUE TITLE
condition check for main is improperly written 

### ISSUE THREAD

**Issue by leasley199** [MicrosoftDocs/azure-devops-docs#13013]
(condition: contains(variables['build.sourceBranch'], 'refs/heads/main')) step in 'Pipeline behavior when build is canceled' should read as (condition: eq(variables['build.sourceBranch'], 'refs/heads/main')), since the task is meant to only run on main branch. However, it will run on branches that contain main-*** which is not a desired task. As well the follow-up steps proceed to call out that validation step via eq() over contains()

:) thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e5cee4-eaae-3a96-db91-540ac759e83a
* Version Independent ID: 9bdc837c-ffe0-d999-f922-f3a5debc7f92
* Content: [Conditions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/conditions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@leasley199 Thanks, that's a good addition. I'm updating the example now.
