### ISSUE TITLE
Misleading statement about 'skip ci' tag on merge commits

### ISSUE THREAD

**Issue by aolmosj** [MicrosoftDocs/azure-devops-docs#13029]
Hello,

This doc states:
`Finally, after you merge the PR, Azure Pipelines will run the CI pipelines triggered by pushes to the target branch, even if some of the merged commits' messages or descriptions contain [skip ci] (or any of its variants).`

I can confirm that, as for now, this is not true. I'm using Bitbucket as code repository, and when a PR is merged (merge commit), if there is a commit with the message "[skip ci]", the Azure Pipelines CI won't trigger.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/azure-repos-git.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This article is for Azure Repos Git repositories; for Bitbucket repos, please see: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits
