### ISSUE TITLE
it should be clear if ONLY the end customer can purchase (after being given permissions)

### ISSUE THREAD

**Issue by mariatancu** [MicrosoftDocs/azure-devops-docs#13027]
hello team,

i had a CSP ask if they as CSP can purchase on behalf of the customer.
i deduce from the document that only the end customer can, once enabled, but this is not specified as such, can you please add something like "ONLY the end customer can purchase (after being given permissions)" so that it is clear ?

thank you,
Maria

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1374a33c-7899-522a-e640-8e2ab0500a0b
* Version Independent ID: 844c798d-3406-b182-5943-6ad9049950f9
* Content: [Buy Azure DevOps for Cloud Solution Providers - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/csp/buy-csp-azure-devops?view=azure-devops)
* Content Source: [docs/organizations/billing/csp/buy-csp-azure-devops.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/csp/buy-csp-azure-devops.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mariatancu, thanks for reaching out. I've followed up on this with my PM and will confirm ASAP. Thanks!

**Comment by chcomley** [comment]
I've added to the article that "the CSP can't make purchases on a customer's behalf." Thanks for your feedback! This issue will close once the update goes live. Have a great weekend!

**Comment by chcomley** [comment]
#sign-off

**Comment by mariatancu** [comment]
Thank you!
