### ISSUE TITLE
Inconsistency between these docs and the inline help text

### ISSUE THREAD

**Issue by grantbowering** [MicrosoftDocs/azure-devops-docs#13022]
This issue probably needs to be forwarded to an internal team repo, as it's a problem with the inline documentation inside the application not matching this documentation on Microsoft Learn.

The `Path Filters` section of the Learn documentation is almost identical to the inline help text on DevOps itself, with mostly the same phrasing and examples, so it's quite clear they originate from the same source.  However, the major confusion that leads to unvalidated builds is only made explicit in the Learn version, not in the inline `i` version!

If there is no path filter on a branch policy, it's semantically equivalent to a path filter of `/*`.
If you come into that field with the intention to filter it down to only explicitly include specific paths, your assumption would be that it doesn't include `/*` anymore and would only include those paths.
But if you come into that field with the intention to explicitly *exclude* specific paths, and knowing that `/*` is already coming in by default, you wouldn't assume that you have to explicitly specify `/*` first, because a path filter that is just an exclude makes no sense and has no meaning. 

The Learn version of this documentation makes this a bit clearer, by having two examples and comparing and contrasting their results:

> ![image](https://user-images.githubusercontent.com/2152220/211623948-509889f8-769c-4fd2-a734-e4576d650b12.png)

By contrast, the inline version has only one example without the counterexample and does not explain its results.

> ![image](https://user-images.githubusercontent.com/2152220/211623969-a6dcbc56-90f9-46b0-bb00-d3ce9ebab899.png)

This makes it significantly less obvious what will happen if you only specify an exclude (i.e. nothing and your branch policy is broken).

First of all, I think that a Path Filter that only consists of excludes without any includes should be a validation error, because it can't ever mean anything or apply to anything and there's no scenario it could possibly be what the user intended.

But to be at least tangentially in-scope to the documentation repo here where I can actually report this problem, the inline documentation should absolutely be updated to state the example the way the Learn documentation in this repo states it.  

(They may have made it different because they couldn't do any formatting inside their tooltip so they didn't know how to make the examples and their explanation as clear as it is in these docs, but that's not much of an excuse, given that they've used commas and the word `or` in the first example and expected us to be able to understand and parse that without any formatting separating it, so I reject that as an excuse 🤣)

Anyway, sorry for not being able to put this issue in exactly the right place, but I hope that rather than it just being closed or anything, it finds its way to a good home where someone can action it.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47abb6d4-0fe9-ddd2-f48b-31fdc040eb7f
* Version Independent ID: a65b02a0-9885-c0e0-b829-e2e66aabbd91
* Content: [Git branch policies and settings - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#path-filters)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/branch-policies.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@grantbowering -- Grant, thank you for your thorough feedback.  I am looking for the appropriate place to forward this issue.

**Comment by WilliamAntonRohm** [comment]
@grantbowering -- Grant, apologies for the very long delay in responding.  I have opened a [Developer Community ticket](https://developercommunity.visualstudio.com/t/Product-help-text-does-not-match-documen/10570472) for this issue.
