### ISSUE TITLE
obsolete sdkmanager in "test on the android emulator"

### ISSUE THREAD

**Issue by ulfandersson** [MicrosoftDocs/azure-devops-docs#13030]
In the "Test on the Android Emulator" section, the recommended bash script uses the obsolete sdkmanager which doesn't work on java >8. 

It seems that cmdline-tools is preinstalled on the build instances, so suggest changing:
`$ANDROID_HOME/tools/bin/sdkmanager`

to the new sdkmanager:
`$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9f69815-b798-2328-7e55-c67865505623
* Version Independent ID: 2ece0f9a-c3f8-2a47-71ef-c9e22e2a02c9
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/android.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@vijayma -- Vijay, please review this update in [private PR 5427](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5427).

**Comment by steved0x** [comment]
This fix will go live in a few moments. Thank you for letting us know.
