### ISSUE TITLE
Path missing for Azure DevOps Server 2022

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#13039]
Public URL: https://learn.microsoft.com/en-us/azure/devops/server/command-line/tfsconfig-cmd

In section **Command-line tool location**, the following needs to be added:

```
Azure DevOps Server 2022: %programfiles%\Azure DevOps Server 2022\Tools
```

**Comment by WilliamAntonRohm** [comment]
@NenoLoje -- Neno, thank you for your continued interest!  Please consider creating a PR for this issue.  If you prefer, I will create one.

**Comment by WilliamAntonRohm** [comment]
@NenoLoje -- Neno, you're right, of course.  It's an internal-only repo, and I've created a PR there with your update.
