### ISSUE TITLE
Adding Check Configuration is missing request body details

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#13034]
The docs for [adding a Check Configuration](https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/check-configurations/add?view=azure-devops-rest-7.0&tabs=HTTP) are missing all the details about the settings parameter in the request body. You can see some examples of it on that page but the model details are missing.

**Comment by WilliamAntonRohm** [comment]
@davidcorrigan714 -- David, thank you for your feedback.


@wnjenkin -- please look into this issue.  For some reason, I can't assign this issue to you, as you're not in the Assignees dropdown.

**Comment by davidcorrigan714** [comment]
I've been digging into the api for Approvals & Checks and they're just wrong all over the place in the docs in the client APIs. AFAIK it's just plain broken right now. For example the v5 api has the Settings field in the data models, but v6 doesn't. Then v6 has some more data models for checks but none of the client request functions actually accept or return them so they're useless. Hopefully v7 can clean that up so the official API can properly support Approvals and Checks.

**Comment by WilliamAntonRohm** [comment]
@JanaVPetrova -- Yana, please look into this issue.
