### ISSUE TITLE
git svn show-ignore fails

### ISSUE THREAD

**Issue by jkruse** [MicrosoftDocs/azure-devops-docs#13038]
The command `git svn show-ignore > .gitignore` fails. The correct command seems to be `git svn show-ignore --id=origin/trunk > .gitignore`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6688e78b-62ba-dd5d-2771-9bac0c03d4bc
* Version Independent ID: 5cd2c314-2dfc-d910-6935-79636b3696ca
* Content: [Migrate from Subversion (SVN) to Git - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/perform-migration-from-svn-to-git.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@vijayma -- Vijay, please review this update in [private PR 5425](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5425).

**Comment by steved0x** [comment]
This will be live later today. Thanks for letting us know.
