### ISSUE TITLE
Where to see Process parameters ?

### ISSUE THREAD

**Issue by sybaris** [MicrosoftDocs/azure-devops-docs#13037]
In this documentation, here the sentence : "You can link all important arguments for tasks used across the build definition as process parameters, which are then shown at one place - the Pipeline view"

1 - Where do we set or view  these process parameters ?
2 - Where is the pipeline view ?

A screenshoot should be appreciated...

PS : After creating this issue, I found the answer here : https://stackoverflow.com/questions/43362079/visual-studio-team-services-edit-link-settings
This prouve that the explanation needs to be clarified

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec7e5a9-e22e-a329-14cf-6e21e65cc85f
* Version Independent ID: c96aaf4e-f5ec-c42f-05cb-e2366167fbc6
* Content: [Process parameters - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=azure-devops)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/parameters.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @sybaris! I'll add a screenshot now.
