### ISSUE TITLE
Include `parameters` field on `az pipelines run`

### ISSUE THREAD

**Issue by mrcity** [MicrosoftDocs/azure-devops-docs#13069]
I found this page first when trying to look for examples on how to launch a pipeline using Azure DevOps CLI. It doesn't mention that you can use `parameters` as an argument, thus I went through a rather annoying process of trying to accept both parameters to variables in my latter pipeline, coalescing them depending on how the latter was triggered, then finding out the coalesced value could not be used to form the name of a variable group I wanted to reference (since variable groups need to be named at compile time). Anyway, I went through a process that could've been avoided and cost me time chasing an alternate solution.

In continuing to search, I found a [feature request on GitHub](https://github.com/Azure/azure-devops-cli-extension/issues/972) showing that this was indeed incorporated a while ago, and then found [additional Microsoft documentation](https://learn.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest#az-pipelines-run) (resembling this page quite a bit) that showed exactly how to use the `parameters` field from the CLI.

My request here is that this field (plus any others) gets reconciled between the two pages, or else this documentation page simply gets replaced with the other one. The latter would save having to update the same information in multiple places.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df5d17e2-0f83-b115-5bfc-1a1691441dc2
* Version Independent ID: df5d17e2-0f83-b115-5bfc-1a1691441dc2
* Content: [Manage your pipeline with Azure CLI - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/manage-pipelines-with-azure-cli?view=azure-devops#run-a-pipeline)
* Content Source: [docs/pipelines/get-started/manage-pipelines-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/manage-pipelines-with-azure-cli.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @silviuandrica
* Microsoft Alias: **sandrica**

**Comment by WilliamAntonRohm** [comment]
@mrcity -- Stephen, thank you for your thoughtful feedback.

@silviuandrica -- Silviu, please look into this issue.

cc @rloutlaw for awareness
