### ISSUE TITLE
how many tags can be created?

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/azure-devops-docs#13065]
Is there a limit in the number of git tags that can be created? I don't see that info in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c96e564-2fbb-0399-dfdd-fa9570710ae2
* Version Independent ID: 413f688e-16bc-123f-5103-a0a0ea95b7e2
* Content: [Use Git tags - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/git-tags?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/git-tags.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/git-tags.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@ilantom -- thank you for your question.  At least 500 tags can be created, and I don't think there's an upper limit.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
