### ISSUE TITLE
cron format is incorrect - should use  single quotes 

### ISSUE THREAD

**Issue by melezhik** [MicrosoftDocs/azure-devops-docs#13075]
cron format is incorrect, there is a big in Ado that when double quotes are used for cron times pipeline does not run by cron or run incorrectly, user should use single quotes 

```yaml
cron: '0 12 * * 0'
``` 

microsoft should either fix this bug or at least update documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/scheduled-triggers.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by melezhik** [comment]
so, does it mean, it is fixed?

**Comment by WilliamAntonRohm** [comment]
@melezhik -- Alexey, the article has been updated and the new version should be live later today.

**Comment by melezhik** [comment]
Thanks!
