### ISSUE TITLE
Keep hierarchy with filters option not visible

### ISSUE THREAD

**Issue by kdotdk** [MicrosoftDocs/azure-devops-docs#13071]
Hi
[Keep hierarchy with filters](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/configure-your-backlog-view?view=azure-devops#filter-your-backlog-and-maintain-the-hierarchy) is not visible in my View setting menu.

![image](https://user-images.githubusercontent.com/5041290/215442041-83532718-15a5-4fa5-94d3-9f851b823db9.png)

Under that conditions should it be visible?

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c430085-0b81-836a-ad27-57c0d7c02eaf
* Version Independent ID: 5c430085-0b81-836a-ad27-57c0d7c02eaf
* Content: [Configure your backlog view in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/configure-your-backlog-view?view=azure-devops#filter-your-backlog-and-maintain-the-hierarchy)
* Content Source: [docs/boards/backlogs/configure-your-backlog-view.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/configure-your-backlog-view.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kdotdk - This feature is available with Azure DevOps Services. It isn't available with on-premises servers. Also, you must have the New Boards Hub preview feature enabled. You enable it using the instructions provided in this article: [Manage or enable features](https://learn.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled).  I will add a note to the article to clarify this requirement.

**Comment by KathrynEE** [comment]
Closing this issue as addressed.
