### ISSUE TITLE
Updated on the inside 

### ISSUE THREAD

**Issue by power591** [MicrosoftDocs/azure-devops-docs#13070]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b4734-b75e-95c3-73d2-78216e166bf1
* Version Independent ID: e4404510-ff79-aabf-1214-1d1ccb968aba
* Content: [What is Azure Boards? Tools to manage software development projects. - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops)
* Content Source: [docs/boards/get-started/what-is-azure-boards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/get-started/what-is-azure-boards.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by KathrynEE** [comment]
@power591 - We closed this issue as there was no actionable feedback. If you have feedback or an inquiry, you can open a new issue.
