### ISSUE TITLE
Document how to escape characters within logging commands

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/azure-devops-docs#13078]
Logging commands are obviously parsed at some point, which means their must be specific characters that need to be escaped in some fashion.  For example, it is not documented how to handle a message that contains a newline character, and semicolons at various points in the logging command would also appear to be problematic (e.g. if a property value itself contained a semi-colon, it would be interpreted as the start of a new property).

Document:
1. What characters need to be escaped in what contexts (e.g. message vs property context if there is a relevant distinction)
2. How to escape said characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/scripts/logging-commands.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by davisnw** [comment]
Possibly related to #9371 with the `:` character.

**Comment by davisnw** [comment]
Possibly related to https://developercommunity.visualstudio.com/t/Error-when-setting-vsobuildaddbuildt/10163239

**Comment by WilliamAntonRohm** [comment]
@davisnw -- thank you for your well-researched feedback.

@juliakm -- please look into this issue.

**Comment by juliakm** [comment]
@davisnw My understanding is that Azure DevOps doesn't provide an added ability to escape a pipeline variable. You can try to use the escape characters in YAML ([reference](http://yaml.org/spec/1.2-old/spec.html#id2788097)).  

We have had customers suggest ways to clean values with PowerShell or Bash script tasks that are then combined with logging commands. I think your best next step is to add to an existing [Developer Community post](https://developercommunity.visualstudio.com/AzureDevOps) or create a new feature request. 

I'll double-check with the product team that this is the case and re-open the issue if I learn there is a way to escape chars in logging commands.

**Comment by davisnw** [comment]
@juliakm  - I discovered that one of the built - in pipeline tasks actually *does* do some sort of escaping, though it's not documented.  I'll try to find that again.

**Comment by davisnw** [comment]
The escaping might be happening in [`dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll`](https://github.com/microsoft/azure-pipelines-tasks/blob/47c5036e1a7825ff94cece82b72505618acd92ec/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L112)

At any rate, it is clear that at the very least newlines are somehow being escaped, since the build templates provided by Microsoft in Azure DevOps are capable of multi-line logging messages.
