### ISSUE TITLE
How can i add "Automation status" = 'Completed" 

### ISSUE THREAD

**Issue by kisame3003** [MicrosoftDocs/azure-devops-docs#13080]
Hi,

I would like to customize my AzureDevops instance with additional field for automation status:
Automation status" = 'Completed" into TestCase dropdown screen

![image](https://user-images.githubusercontent.com/124061031/215779849-0ecd1cdb-e723-4f9c-a5fd-afc9479e30a9.png)

Justification 

Currently the choice is 
_not automated_  
_planned_

we would like to incorporate also _completed_ state

Please let me know if you need more info on AzureDevops instance we are using. Thanks!

reference link: https://learn.microsoft.com/en-us/azure/devops/boards/queries/build-test-integration?view=azure-devops

**Comment by WilliamAntonRohm** [comment]
@kisame3003 -- thank you for your detailed feedback.  This repo is solely for documentation issues, and this seems implementation-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

cc @KathrynEE for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by kisame3003** [comment]
I cannot create a ticket in that [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

Would you kindly help me with that? which section should i use?

**Comment by KathrynEE** [comment]
@kisame3003 - If your project uses the Inherited Process model, You can't modify an inherited field to add more entries to the pick list. You need to add a custom field that contains the pick list items you want. Information is provided here: [Add a custom field to a work item type (Inheritance process)](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/add-custom-field?view=azure-devops). 

If your project uses an On-premises XML process model, then you can modify the picklist as described here: [Add or modify a field to track work](https://learn.microsoft.com/en-us/azure/devops/reference/add-modify-field?view=azure-devops-2022&viewFallbackFrom=azure-devops) .
