### ISSUE TITLE
This product has been removed from the marketplace. The article needs an update to note that, or simply to be removed.

### ISSUE THREAD

**Issue by mmBPCS** [MicrosoftDocs/azure-devops-docs#13088]
Same as the subject line:
This product has been removed from the marketplace. The article needs an update to note that, or simply to be removed.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b348a89-811c-2d1f-62f6-029d67213ef2
* Version Independent ID: 7fbb4ab1-701d-c88a-a14f-d29bbadd6981
* Content: [View of features and epics on the Feature Timeline - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/boards/extensions/feature-timeline?view=azure-devops)
* Content Source: [docs/boards/extensions/feature-timeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/extensions/feature-timeline.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mdell-seradex** [comment]
Note that the live page seems to be stuck in a redirect loop at this time.

**Comment by WilliamAntonRohm** [comment]
@mmBPCS, @mdell-seradex -- thank you for your feedback.

@KathrynEE -- please look into this issue.

**Comment by KathrynEE** [comment]
@mmBPCS - Thank you for bringing this to our attention. I recently deprecated the articles but made a few errors. I've just published the latest changes and the articles are now fully archived and links should now work as expected. Here are the articles for reference: 
- [View progress using the Epic Roadmap](https://learn.microsoft.com/en-us/previous-versions/azure/devops/all/extensions/epic-roadmap?view=tfs-2017)
- [View portfolio progress with the Feature Timeline](https://learn.microsoft.com/en-us/previous-versions/azure/devops/all/extensions/feature-timeline?view=tfs-2017)
