### ISSUE TITLE
Work Item Templates - Dynamic Content

### ISSUE THREAD

**Issue by jeffsdata** [MicrosoftDocs/azure-devops-docs#13082]
Hi, I'm trying to figure out how to use Templates to set the title of a work item to be the same as the parent. Is there documentation for setting fields to dynamic content?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Use Azure DevOps work item templates to update work items in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/work-item-template.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jeffsdata - Thank you for your inquiry.  The Work Item Templates feature doesn't support dynamic content.  You may be able to do something using Logic Apps, Power Automate, or Power Apps - as documented here: [Azure DevOps](https://learn.microsoft.com/connectors/visualstudioteamservices/).  However, I don't think the scenario you mention is doable. 

This extension, [1-Click Child-Links](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-child-links), may be of help to auto create child items.
