### ISSUE TITLE
please update rest-api-versioning page for Azure DevOps Server 2022 / API version to 7.x

### ISSUE THREAD

**Issue by davecaraway-microsoft** [MicrosoftDocs/azure-devops-docs#13083]
Currently the REST API versioning > Supported versions table only covers to Azure DevOps Server 2020.

Also I'm told there's an API version beyond 6.0 (guessing 7.x) that needs to be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84af2b0f-cd64-018f-585f-70d17f393f85
* Version Independent ID: 8b25aa9b-95b8-14d3-0348-8d8ffd6d2843
* Content: [REST API versioning for Azure DevOps - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops)
* Content Source: [docs/integrate/concepts/rest-api-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/rest-api-versioning.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by michha** [comment]
2022 comes with version 7.0 as calling the API with an higher version results in _The requested REST API version of 100.0 is out of range for this server. The latest REST API version this server supports is 7.0._

**Comment by chcomley** [comment]
The article is updated, thanks so much for your feedback. Let me know if we need any further updates by @mentioning me. Thanks!
