### ISSUE TITLE
Permissions error when using Azure DevOps API to create an Elasticpool for Agent Pools | Manage Permissions needed

### ISSUE THREAD

**Issue by dawsonar802** [MicrosoftDocs/azure-devops-docs#13093]
I am using the [API](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools?view=azure-devops-rest-7.0) to try and create a new agent pool at the org level.  When doing so, the following error is thrown:

```
     | {"$id":"1","innerException":null,"message":"Access denied. <username> needs Manage permissions to perform the action.
     | For more information, contact the Azure DevOps Server
     | administrator.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.AccessDeniedException, Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"AccessDeniedException","errorCode":0,"eventId":3000}

```

Things I have tried:
- Add the account as an Admin at the org level to the Agent Pool > Security
- Add the account as an Admin at the org level to the Deployment Pools > Security
- Add the account as an Admin at the project level where the service connection is: Service Connections > Security
- Tried various permissions for the account from the permissions doc here: https://learn.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page
    - `Edit instance-level information`
    - `Administer build resource permissions`
    - Various other permissions individually for the account being used.
- In a last ditch effort, I created a new group at the org level and added every permission available (which seems to mimic what the Project collection Administrators group has, but it still seems to fail.

What actually works to get around the error is to add the account to the `Project Collection Administrators` group.  This seems like more permission than should be needed.  

My question is, what is the `Manage` permission that be being referenced in the error and/or is it a requirement that the account be in the Project Collection Admins group to provision a Org level Agent Pool?

This does not seem to be a new issue, see other references here:
- https://stackoverflow.com/questions/64330052/can-not-create-agent-pool-by-code-no-permissions-at-azure-devops-2019
- https://developercommunity.visualstudio.com/t/access-denied-user-needs-manage-permissions-for-po/924818
- https://github.com/Microsoft/tfs-cli/issues/64

**Comment by WilliamAntonRohm** [comment]
@dawsonar802 -- Andrew, thank you for your thorough feedback.

@KathrynEE -- Kathryn, please look into this potential documentation issue.

cc @wnjenkin for awareness

**Comment by KathrynEE** [comment]
@steved0x - Assigning this to you to look at this as it deals with pipeline permissions.

**Comment by dawsonar802** [comment]
Thank you both.  If it helps I can provide the PowerShell I am using if you would like to reproduce the issue, but just an API request to create a new pool should do it.  Thanks again for the fast reply.

**Comment by dawsonar802** [comment]
Hello, I just wanted to check on the status of this.  Thanks.
