### ISSUE TITLE
Yeah, sorry, I don't have a "+ New repository" choice, so this does not help me.

### ISSUE THREAD

**Issue by swellhunter** [MicrosoftDocs/azure-devops-docs#13104]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08f3f084-bd67-ddfe-0744-7b67d556af7b
* Version Independent ID: e2035fdc-56da-899b-4018-901d6fa5d86a
* Content: [Create a new Git repo in your project - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/create-new-repo?view=azure-devops)
* Content Source: [docs/repos/git/create-new-repo.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/create-new-repo.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@swellhunter -- Matthew, thank you for your succinct feedback.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
@swellhunter -- Matthew, I believe this may be a permissions issue.  Apologies for the delay in responding.  From the article, under Prerequisites:
> You must have the Create repository permission, which is granted by default to project administrators. For more information, see [Set Git repository permissions](https://learn.microsoft.com/en-us/azure/devops/repos/git/set-git-repository-permissions?view=azure-devops).

@vijayma -- Vijay, please look into this issue.
