### ISSUE TITLE
Verify option listed is not available in Azure DevOps interface

### ISSUE THREAD

**Issue by marknoble** [MicrosoftDocs/azure-devops-docs#13102]
When following the instructions here: https://learn.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops#service-principals-token-expired

Step 3 refers to selecting an option to verify.

I don't see such an option in Azure DevOps on the page for my service connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops#failedToObtainJWT)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/azure-rm-endpoint.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@marknoble You should be able to see it as shown below. Make sure you have the right permissions to manage service connections for your team/org. See [Manage service connections](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml) for details.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/60942540/2a37e1c5-7f17-4cd1-b790-612cdeebf684)
