### ISSUE TITLE
Difference between copy and clone of testcases

### ISSUE THREAD

**Issue by tigerkungen** [MicrosoftDocs/azure-devops-docs#13100]
The cloning of test cases is not defined. The tool gives only copy as alternative but copy/cloning is used in the description. Is copy and clone the same thing?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb42105-a17b-39f2-49a8-712ae7f5e503
* Version Independent ID: 91426199-6db1-19ac-8e55-9fc7747323f6
* Content: [Navigate Test Plans - Azure Test Plans](https://learn.microsoft.com/en-us/azure/devops/test/navigate-test-plans?view=azure-devops)
* Content Source: [docs/test/navigate-test-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/test/navigate-test-plans.md)
* Service: **azure-devops-test-plans**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tigerkungen - Sorry for the confusion. Copy and Clone operations are very similar. Oftentimes, the clone process refers to copying links made to/from objects. Please review [Copy or clone test plans, test suites, and test cases](https://learn.microsoft.com/en-us/azure/devops/test/copy-clone-test-items?view=azure-devops&tabs=browser) as it may clear up some of the confusion.
