### ISSUE TITLE
Missing new versions of API and Products

### ISSUE THREAD

**Issue by Nighteyez07** [MicrosoftDocs/azure-devops-docs#13105]
The matrix table under https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops-2022#supported-versions is missing references to API version 7.0 and does not list Azure DevOps Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84af2b0f-cd64-018f-585f-70d17f393f85
* Version Independent ID: 8b25aa9b-95b8-14d3-0348-8d8ffd6d2843
* Content: [REST API versioning for Azure DevOps - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops-2022)
* Content Source: [docs/integrate/concepts/rest-api-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/rest-api-versioning.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @Nighteyez07. Once I publish the update, this issue will automatically close. Thank you!
