### ISSUE TITLE
Markdown checklists are not functional

### ISSUE THREAD

**Issue by timfoote** [MicrosoftDocs/azure-devops-docs#13119]
Markdown checklists are not functional by clicking the checklist item.  Only by editing the markdown and modifying the syntax manually.

Details about the issue can be found here https://developercommunity.visualstudio.com/t/wiki-function-check-list-should-allow-check-wiki-c/789279

The documentation page states the following:

>After you've added a task list, you can check the boxes to mark items as completed. These actions are expressed and stored within the comment as [ ] and [x] in Markdown.

This is incorrect as it does not work that way.  Please update the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?source=recommendations&view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you, @timfoote. I've published an update! Have a great day!
