### ISSUE TITLE
Package badge is not retrieving latest version

### ISSUE THREAD

**Issue by facusantillo** [MicrosoftDocs/azure-devops-docs#13116]
Description:

When trying to retrieve a badge from Azure DevOps API using the request as described in the [documentation](https://learn.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact-details/get-badge?view=azure-devops-rest-7.0), the badge is not retrieving the one marked with the property **isLatests: true**

Expected: Should retrieve the latest available version

Result: Is retrieving the badge based on the semantic version

Notes: I think this happens because it's retrieving the package based on the semantic version. Some packages in universal packages don't have a final version so when you need to retrieve the package badge it's only listing the ones with a final version. (for more detail see the example in the screenshots below)

![package-list](https://user-images.githubusercontent.com/32923328/218437080-89a0492f-c6a7-4a72-9666-7fa8f9e073a8.png)
![package-retrieved](https://user-images.githubusercontent.com/32923328/218437092-d824eb62-576f-48f8-a071-0436f78c7414.png)

**Comment by WilliamAntonRohm** [comment]
@facusantillo -- Facundo, thank you for your thorough feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

cc @wnjenkin for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
