### ISSUE TITLE
Importing SVN repository into Git - "$author not defined in authors-transform.txt"

### ISSUE THREAD

**Issue by rjfalconer** [MicrosoftDocs/azure-devops-docs#13124]
Hi,

when following the otherwise excellent `perform-migration-from-svn-to-git` guide on a Windows machine I've twice encountered an error where the initial `git svn clone` command fails when parsing the first svn revision, giving an error about missing author, despite the author being present in authors-transform.txt generated in step 1.

It seems git for Windows does not correctly parse the UTF-16 authors file generated by svn-log. The fix is to re-save the file as UTF-8, as described in this answer:
https://stackoverflow.com/a/49004634/28411

Until this is fixed I suggest the guide be updated to include a remark at the end of [Retrieve a list of all Subversion authors](https://learn.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#retrieve-a-list-of-all-subversion-authors) to convert the output to UTF-8:
> Open authors-transform.txt and change the encoding to UTF-8
> Notepad > File > Save As > Encoding: UTF-8

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6688e78b-62ba-dd5d-2771-9bac0c03d4bc
* Version Independent ID: 5cd2c314-2dfc-d910-6935-79636b3696ca
* Content: [Migrate from Subversion (SVN) to Git - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/perform-migration-from-svn-to-git.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@rjfalconer -- Richard, thank you for your valuable feedback.  There is already a Note at the end of that section:
> Encoding can be adjusted by appending the `-Encoding` option to the command above, for instance, `OutFile 'authors-transform.txt' -Encoding utf8`.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by rjfalconer** [comment]
@WilliamAntonRohm thanks for your fast response. I confess I didn't process that note when following the article. 

I suggest that the encoding parameter be added by default (remove note, update svn log command), or a stronger call-to-action given to the user to prompt them to perform the note. As is written the note is out of place; the reader has no motivation to change the encoding unless they're aware of the fault in git-for-Windows.

**Comment by WilliamAntonRohm** [comment]
@rjfalconer -- Richard, thank you for your followup and suggestion.  I've updated the command and wording accordingly.
