### ISSUE TITLE
numbers not matching in the screenshot

### ISSUE THREAD

**Issue by martinman-hrbl** [MicrosoftDocs/azure-devops-docs#13125]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/82173761/219755581-24a5697b-fc5f-4d2f-84e0-5a5eadb7ff03.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd3e188-c59c-c204-fa15-d5ec7b7deebd
* Version Independent ID: f5d79338-4296-c9b1-9979-762101d2976a
* Content: [Status and trend work item, query-based charts - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/dashboards/charts?view=azure-devops)
* Content Source: [docs/report/dashboards/charts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/charts.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@martinman-hrbl -- thank you for catching this discrepancy.  This is an example, and while the numbers should match, the intent is clear.  

cc @KathrynEE for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by KathrynEE** [comment]
@martinman-hrbl - The image is correct as is. The Legend shows the Priority values which are defined as Priority 1, 2, and 3. So there are **4** Priority 2 items, **3** Priority 1 items, and **1** Priority 3 item.  This adds up to **8** items total.
