### ISSUE TITLE
Need improvements in CSV import article to talk about tags

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/azure-devops-docs#13129]
Consider answering these queries in the article to improve the article.

How to add multiple tags?
Can it be a comma-separated list in itself or will it confuse ADO?

How to add tags with spaces or hyphens in them? An example shows double quote usage but there is no explicit mention in the article of this method. It requires a nuanced observation to find + it mars the SEO.

What if these multiple tags are a combination of single words and words with spaces or hyphens?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items in bulk by using CSV files - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/import-work-items-from-csv.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ashishguptaiitb** [comment]
I mistakenly removed the automatically added labels. Restored those now.

**Comment by KathrynEE** [comment]
@ashishguptaiitb - Thank you for this feedback. I've added a backlog item to update the article. We'll close this issue once that is completed.

**Comment by KathrynEE** [comment]
@chcomley - Please close this bug once you've completed [User Story 65615](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65615): Import or update work items in bulk by using CSV files [Update].

**Comment by chcomley** [comment]
Thanks for your suggestions, @ashishguptaiitb. I've updated the article in the FAQs section. Once live, this issue will automatically close. Thanks again and have a great day!
