### ISSUE TITLE
SqlPackage error while using latest version of SqlPackage.exe (161.8089.0)

### ISSUE THREAD

**Issue by pietergheysens** [MicrosoftDocs/azure-devops-docs#13135]
Using the recommended sqlpackage command gives an error while using the latest version of SqlPackage
More details logged here: https://medium.com/into-alm/sqlpackage-error-while-exporting-dacpac-6789adf301b7

It would be good to provide more context on this page for other people hitting this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/migration-import.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-migrate**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@pietergheysens -- Pieter, thank you for your clear feedback.

@chcomley -- Chrystal, please look into this issue.

**Comment by FokkoVeegens** [comment]
To "fix" this, `;Encrypt=False;TrustServerCertificate=True` needs to be added to the connectionstring of the sqlpackage statement. While not ideal, it does work. It would of course be better to enable encryption and have a certificate in place, but as this is part of a migration and not used for a whole lot longer, this might be sufficient.
