### ISSUE TITLE
 '&gt' vs '>' html errors in the git code examples

### ISSUE THREAD

**Issue by PhilipOakley** [MicrosoftDocs/azure-devops-docs#13132]
The code examples need the  '&gt' errors in the git code examples changed to '>' ! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dab94c0-0de4-3eab-2e55-cf407313b333
* Version Independent ID: 0f4e4abb-ba6b-225b-a9aa-4ea9d054859f
* Content: [Understand Git history simplification - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/git-log-history-simplification?view=azure-devops)
* Content Source: [docs/repos/git/git-log-history-simplification.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/git-log-history-simplification.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@PhilipOakley -- Philip, thank you for catching these.  I have updated the documentation and it should be live by tomorrow.
