### ISSUE TITLE
"Fixed AB#5" auto transitions AB work item only on default branch?

### ISSUE THREAD

**Issue by Fitzbert-Fitz** [MicrosoftDocs/azure-devops-docs#13131]
Auto transitioning Azure Board items with mentions like "Fixed AB#5" seems to be working only for commits to main/default branch. 
If I commit to any other branch the transition does not work. After Merging the branch into main/default all transitions are executed. Is that intended? If yes, you might want to document this. If no, where can I create a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c82842d8-dd84-249f-cce1-9e93ecf703bf
* Version Independent ID: eaf9a299-4492-8e09-287a-f10b63d15e29
* Content: [Link GitHub commits, PRs, and issues to work items - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops)
* Content Source: [docs/boards/github/link-to-from-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/link-to-from-github.md)
* Service: **azure-devops-boards**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@Fitzbert-Fitz -- Martin, thank you for your feedback.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
