### ISSUE TITLE
"Authorized As" may be unused but it would still be nice if you can include the system reference name for it in the docs...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#13144]
... so I dont have to debug calls to GetWorkitemTypes() and run through all the resultant type fields to find the reference name for it _just to put it in an exclusion list_. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12084832-5567-c723-2e87-aeaac920aa31
* Version Independent ID: 7620ba4b-7bbd-0c1d-882f-374b9278a315
* Content: [Learn default and system work item field descriptions - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/guidance/work-item-field?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/work-item-field.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/guidance/work-item-field.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by danhellem** [comment]
@StingyJack can you explain more about what you are trying to do here?

**Comment by chcomley** [comment]
Hey there, as far as my PM is aware, we don't use "Authorized As" anywhere. Closing this issue, thanks so much!
