### ISSUE TITLE
More about geo-replication in the Asia-Pacific geography

### ISSUE THREAD

**Issue by tomoshi-ms** [MicrosoftDocs/azure-devops-docs#13148]
To protect data during hardware or service failures, Azure Storage geo-replicates customer data between two regions in the same geography. And customer data in Brazil is replicated to the South Central US region for disaster recovery purposes since there is only one region in Brazil.

Now, I found the following issue that explains EA region has been discontinued. 

> [https://github.com/MicrosoftDocs/azure-devops-docs/issues/13138]
>     .... We no longer support creating organizations in East Asia,

It means that there is only one region (SEA) in Asia Pacific geography now. But it is not clearly stated where the customer data in the SEA region will be replicated to.
**As well as Brazil, the destination for replication of customer data for the SEA region should be clearly indicated in the documentation.**

Also, as of 2023/03/01, there are a few organizations that still have EA as the region notation in the Organization Settings.
Since the EA region has been discontinued, I assume that these region designations will be updated to SEA in future DevOps rollout, but this may be confusing to users.
**I think it is necessary to announce from the official documentation that the data center itself has already moved to SEA and that the region designations in organization settings will be updated to SEA from time to time.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Data protection overview - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/data-protection.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@tomoshi-ms -- Tomomi, thank you for your considered feedback.

@chcomley -- Chrystal, please look into this issue.  This article may be related:
- [Data locations for Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops)

**Comment by chcomley** [comment]
Thanks for reaching out, @tomoshi-ms. I'm looking into this.

**Comment by chcomley** [comment]
Hi @tomoshi-ms, the primary region for our Asia geo is the SEA region (Singapore) and the secondary is SE region (HK). The secondary is on standby mode and available in case of regional disaster in SEA region and therefore there are no IP addresses available. 
  
For more info on Azure region pairs, please use this page: [https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Freliability%2Fcross-region-replication-azure%23azure-cross-region-replication-pairings-for-all-geographies&data=05%7C01%7CChrystal.Comley%40microsoft.com%7C7931072f9ba54870924208db1b866658%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134036284861282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KYJL11BKMsNj0j36FxRGLr3dzYVClYzq%2B1mgb5%2BNKwU%3D&reserved=0) 

I'll be closing this issue, but do let me know if you feel the article needs an update please. You can @mention me. Thank you!

**Comment by chcomley** [comment]
Hi @tomoshi-ms, the primary region for our Asia geo is the SEA region (Singapore) and the secondary is SE region (HK). The secondary is on standby mode and available in case of regional disaster in SEA region and therefore there are no IP addresses available. 
  
For more info on Azure region pairs, please use this page: [https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Freliability%2Fcross-region-replication-azure%23azure-cross-region-replication-pairings-for-all-geographies&data=05%7C01%7CChrystal.Comley%40microsoft.com%7C7931072f9ba54870924208db1b866658%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134036284861282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KYJL11BKMsNj0j36FxRGLr3dzYVClYzq%2B1mgb5%2BNKwU%3D&reserved=0)

**Comment by tomoshi-ms** [comment]
Hello @chcomley , thank you very much for your detailed answer.  Your answers helped me to understand the following:

- In the Asia Pacific geography, the primary region is SEA (Singapore) and the secondary region is SE (Hong Kong).
- However, the secondary region is in standby mode and is only enabled during regional disasters in the SEA region. Therefore, during normal operation, the IP address of the secondary region is disabled.

[Data locations for Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops) page also has a proviso to refer to [Data residency in Azure](https://azure.microsoft.com/global-infrastructure/data-residency/#overview) page for more information, but for most users this is unfriendly information.

> [Data locations for Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops)
> ..... For more information, see [Data residency in Azure](https://azure.microsoft.com/global-infrastructure/data-residency/#overview).

By reading [Data locations for Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops) page and [Data residency in Azure page](https://azure.microsoft.com/global-infrastructure/data-residency/#overview), it is difficult for users to understand the above two points by themselves.
In fact, I have identified several organizations around me that still have East Asia as their region. They still believe that their data resides in the SE region. Thus, when they are told that the primary region is SEA and the secondary region SE is only valid during regional disasters, they will be confused, "But my organization still exists in the SE region, right?".

For this reason, I think the following statement should be added to either [Data locations for Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops) page or [Data protection overview](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops) page.
Would you consider adding it to the Learn site?

- Currently, all of the organization's customer data in the Asia Pacific geography is deployed in the SEA region data center.
- Some organizations in the Asia-Pacific geography still show "EA" as region designation, but these will be changed to "SEA" from time to time.
- In the Asia Pacific geography, the primary region is SEA (Singapore) and the secondary region is SE (Hong Kong).
- The secondary region is in standby mode and is only enabled during regional disasters in the SEA region. Therefore, during normal times, the IP addresses of the secondary regions are disabled.

**Comment by tomoshi-ms** [comment]
Hello @chcomley , do you have any updates?  Our important customers are very eager for these informations to be released by Microsoft.

- Currently, all of the organization's customer data in the Asia Pacific geography is deployed in the SEA region data center.
- Some organizations in the Asia-Pacific geography still show "EA" as region designation, but these will be changed to "SEA" from time to time.
- In the Asia Pacific geography, the primary region is SEA (Singapore) and the secondary region is SE (Hong Kong).
- The secondary region is in standby mode and is only enabled during regional disasters in the SEA region. Therefore, during normal times, the IP addresses of the secondary regions are disabled.

**Comment by chcomley** [comment]
Hi @tomoshi-ms, I've contacted the PM again.  Feel free to reach out to my Microsoft email address and I can connect you, otherwise I will update you as soon as possible.

**Comment by chcomley** [comment]
Hi @tomoshi-ms, here's some information:

 For these two bullets:
•	Currently, all of the organization's customer data in the Asia Pacific geography is deployed in the SEA region data center.
•	Some organizations in the Asia-Pacific geography still show "EA" as region designation, but these will be changed to "SEA" from time to time.

We are aware that there is a bug that incorrectly displays data location in EA, when the data is actually stored in SEA. We have an existing WI to address this bug and the estimated fix should be live no later than 4/21. 

For the remaining 2 bullets:
•	In the Asia Pacific geography, the primary region is SEA (Singapore) and the secondary region is SE (Hong Kong).
•	The secondary region is in standby mode and is only enabled during regional disasters in the SEA region. Therefore, during normal times, the IP addresses of the secondary regions are disabled.

These suggestions are already captured in our existing documentation (data protection) and [Data residency in Azure](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fglobal-infrastructure%2Fdata-residency%2F%23overview&data=05%7C01%7CChrystal.Comley%40microsoft.com%7C01e123212b4b485b0af008db23fda978%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638143344599000364%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0qbVd0poe8ftHzMBmAgfUve4K92fNSaZT9bHPCzor%2FY%3D&reserved=0).

Hope this is helpful.
