### ISSUE TITLE
Typo in sampleappcontinerregistry.azurecr.io

### ISSUE THREAD

**Issue by marcinwasilewski** [MicrosoftDocs/azure-devops-docs#13158]
I think it should be sampleappcontainerregistry.azurecr.io

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfc7aa5-d9ff-ad64-d26e-d2bd10470025
* Version Independent ID: 9b4f02ea-dab9-f613-5345-496435ab2408
* Content: [Deploy a web app to Azure Web App for Containers - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=java%2Cyaml)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@marcinwasilewski -- Marcin, thank you for spotting this.  I have updated the documentation and it should be live by tomorrow.
