### ISSUE TITLE
Authors are *not* sorted

### ISSUE THREAD

**Issue by biergit** [MicrosoftDocs/azure-devops-docs#13157]
The script that is supposed to created a sorted list of author names does not sort the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6688e78b-62ba-dd5d-2771-9bac0c03d4bc
* Version Independent ID: 5cd2c314-2dfc-d910-6935-79636b3696ca
* Content: [Migrate from Subversion (SVN) to Git - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/perform-migration-from-svn-to-git.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@biergit -- thank you for your feedback.  The existing command:
```
svn.exe log --quiet | ? { $_ -notlike '-*' } | % { "{0} = {0} <{0}>" -f ($_ -split ' \| ')[1] } | Select-Object -Unique | Out-File 'authors-transform.txt' -Encoding utf8
```

should include `Sort-Object` as follows; I am updating this article.
```
svn.exe log --quiet | ? { $_ -notlike '-*' } | % { "{0} = {0} <{0}>" -f ($_ -split ' \| ')[1] } | Select-Object -Unique | Sort-Object | Out-File 'authors-transform.txt' -Encoding utf8
```
