### ISSUE TITLE
Why are you using :::

### ISSUE THREAD

**Issue by jdhenckel** [MicrosoftDocs/azure-devops-docs#13161]
Do not use colon, use backtick instead.

Do not use :::mermaid::: that is stupid. every other tool on the planet uses ```mermaid```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@jdhenckel -- thank you for your considered feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
