### ISSUE TITLE
about fixing linux line endings

### ISSUE THREAD

**Issue by WithHolm** [MicrosoftDocs/azure-devops-docs#13173]
when runing linux container and you want to make sure that a shell script has LF line endings, you can run the command `RUN sed -i 's/\r$//' start.sh`. 
it removes all `\r` at start of lines, making the script linux compatible even if you have touched it from windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops-2022)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/docker.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@WithHolm -- Philip, thank you for your feedback and proposed solution.  `dos2unix` also does this, as mentioned under [Common errors](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops-2022#common-errors).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
