### ISSUE TITLE
Resource group name is missing from the YAML example

### ISSUE THREAD

**Issue by OBD-ChrisWeaver** [MicrosoftDocs/azure-devops-docs#13178]
The Remove and Set Azure firewall scripts require the `$(ResourceGroupName)` pipeline variable but it is not set in the example YAML file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81f4ee44-6500-b0e6-62d8-7a23e5b461fa
* Version Independent ID: 75bd021b-fed5-f258-315d-0ef8628fb887
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/azure-sqldb.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-targets**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for your feedback! The updated snippet should be published soon.
