### ISSUE TITLE
Note Diction

### ISSUE THREAD

**Issue by jakubojo** [MicrosoftDocs/azure-devops-docs#13183]
<<<"In case you are have a lost changes during a PR reviewing, please ensure the multiple merge bases is not the root cause."

>>>"In the case of lost changes during a PR review, please ensure multiple merge bases is not the root cause."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96d5a205-a099-2349-c3db-fa8cd748b406
* Version Independent ID: 3ac3817a-88ff-ced4-ca28-c9d34e7aa487
* Content: [Merge strategies and squash merge - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops#multiple-merge-bases)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/merging-with-squash.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@jakubojo, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
