### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by iomwildflowers** [MicrosoftDocs/azure-devops-docs#13180]
Not true that the -powershell task will only work on a Windows agent. Guessing outdated information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acfc2d3a-e665-f90d-bf3c-c2e81f0e72aa
* Version Independent ID: ea7dcfb7-cc63-43d6-939e-62b657b567d8
* Content: [Use PowerShell scripts to customize pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/scripts/powershell.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks! I'll fix that now.
