### ISSUE TITLE
Add documentation about new table of subpage contents [[_TOSP_]]

### ISSUE THREAD

**Issue by mnieto** [MicrosoftDocs/azure-devops-docs#13195]
This feature was added on Jan-2023
https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-215-update#support-for-subpages-table

It would be nice to have a small mention to this useful feature in this page alongside the 'traditional' [[_TOC_]]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mnieto, thanks so much for reaching out. I've documented the feature, which will automatically close this issue once the update goes live. Thanks again!
