### ISSUE TITLE
Do agentless jobs support AzureLoadTest@1 tasks?

### ISSUE THREAD

**Issue by jdholbrook81** [MicrosoftDocs/azure-devops-docs#13203]
I don't see azure load test tasks under the supported list of tasks for agentless. I thought it would be here as it's just an api call to kick off the job and potentially can be long running so it may tie up an agent? If you wish to go agentless do you have to manually call the api to start a load test?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95227592-b2a9-62be-59d1-fe8c7f4eae8e
* Version Independent ID: abf0c659-ce8c-b187-2784-22ddc061d69f
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#server-jobs)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/phases.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@jdholbrook81 I've confirmed with the product team that agentless jobs don't support AzureLoadTest@1. They suggest that you try using the REST API or an Azure Function. If you'd like to propose that agentless jobs to include support for AzureLoadTest@1, you can create a feature request in our [Developer Community](developercommunity.visualstudio.com/spaces/21/index.html).
