### ISSUE TITLE
Is the data displayed on this page delayed by one hour?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#13202]
Its currently about 10AM where I am, in the Eastern time zone.  My org HQ is located in the central time zone, so it would be 9AM there. 

When I look at the usage page for myself it only shows data up to 9AM. Is it delaying the reporting of all usage data for one hour, or is it showing me up to the moment usage data but with the wrong time zone for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b209c52c-a977-d3c5-1fa6-b94e57667a86
* Version Independent ID: 3e717f00-72b6-39b2-b28e-3c43f1951247
* Content: [Monitor usage of Azure DevOps Services - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/usage-monitoring?view=azure-devops)
* Content Source: [docs/organizations/accounts/usage-monitoring.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/usage-monitoring.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi, did you still need help with this? I imagine it was showing the wrong time zone. Please let me know if you need more info. Thanks
