### ISSUE TITLE
There is no information how to use OData's maxpagesize functionality

### ISSUE THREAD

**Issue by sadedil** [MicrosoftDocs/azure-devops-docs#13218]
Please mention `odata.maxpagesize` and `Prefer` HTTP Header somewhere inside the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 150a3eb9-8219-43ee-8b75-556eede96dee
* Version Independent ID: 024e9fb4-f187-6ff7-6fa9-c27b961a93f3
* Content: [OData Analytics query guidelines - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/extend-analytics/odata-query-guidelines?view=azure-devops)
* Content Source: [docs/report/extend-analytics/odata-query-guidelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/extend-analytics/odata-query-guidelines.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @sadedil. I added a link to more information about this. Here it is: [ODataPreferenceHeader.MaxPageSize property](/dotnet/api/microsoft.odata.odatapreferenceheader.maxpagesize?view=odata-core-7.0). Please @mention me if I need to look into this more.
