### ISSUE TITLE
Change Continuous Delivery to Continuous Deployment

### ISSUE THREAD

**Issue by Oscarce10** [MicrosoftDocs/azure-devops-docs#13224]
The documentation says that "Continuous Delivery (CD) is a process by which code is built, tested, and deployed to one or more test and production environments" this is not entirely true since Continuous Delivery doesn't include the deployment process to any environment. It is only achieved by Continuous Deployment. I suggest changing the description and any occurrences of the sentence Continuous Delivery to Continuous Deployment because it is more accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f15f40a4-bae9-154b-752a-2e9f453d79e3
* Version Independent ID: 3b937e0b-f919-f227-742f-dc740ad4e6f9
* Content: [What is Azure Pipelines? - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/get-started/what-is-azure-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/what-is-azure-pipelines.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@Oscarce10 -- Oscar, thank you for your suggestion.  The term "continuous delivery" is the preferred term; for example, see:
- [Azure Pipelines documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
