### ISSUE TITLE
Semantic search doc not identifying web portal .md header

### ISSUE THREAD

**Issue by ethanknights** [MicrosoftDocs/azure-devops-docs#13221]
For the [semantic search documentation](https://learn.microsoft.com/en-us/azure/devops/boards/queries/search-box-queries?view=azure-devops) this markdown heading is not being correctly identified: [### From the web portal](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/search-box-queries.md?plain=1#L177)

Happy to edit & send PR, but not sure of the cause - the header looks okay in markdown preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47213512-6329-54d7-2a27-5d06a5e56549
* Version Independent ID: 5dbf0ad2-1ed9-c5b2-c303-779ccc94b3c7
* Content: [Use semantic searches in Azure Boards and Azure DevOps - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/search-box-queries?view=azure-devops)
* Content Source: [docs/boards/queries/search-box-queries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/search-box-queries.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@ethanknights -- Ethan, thank you for your close reading and your offer.  I suspect a spacing issue is confusing our renderer -- try adding a blank line before `:::moniker-end`, or removing the blank line after the `<a` tag.  Please let me know it that works; this is a puzzler.

```
4. Narrow your search to specific types
   and states, by using the drop-down selector lists at the top of the results page.
::: moniker-end

<a id="start-an-improvised-search-and-use-shortcut-filters" />
 
### From the web portal 
```

**Comment by ethanknights** [comment]
Hey @WilliamAntonRohm thanks for the support!
I've added a new line after ```::: moniker-end```  in the above [commit](https://github.com/ethanknights/azure-devops-docs/commit/908c87cf3df9a38b8de481ca9e421cc8fb602fcf), as that seems to be the convention in the documentation generally.

The header remains correct in markdown preview (but I don't know how to test rendering the .html page - I guess I can't without system access?).

I'll open a PR in the meantime.

**Comment by chcomley** [comment]
Thanks so much for your help, @ethanknights! We love having you contribute! Reviewing the PR now. It will close this issue, once it's merged. Thanks again.
