### ISSUE TITLE
No mentions of vso.threads_full

### ISSUE THREAD

**Issue by bichuga** [MicrosoftDocs/azure-devops-docs#13237]
https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-thread-comments/update?view=azure-devops-rest-7.0
Requires vso.threads_full. Scopes docs do not mention this scope

**Comment by WilliamAntonRohm** [comment]
@bichuga -- thank you for your feedback.

@JanaVPetrova -- Yana, who is the documentation author for this article?

**Comment by bichuga** [comment]
Sorry I see now that my original posting wasn't clear. @JanaVPetrova I'm referring to vso.threads_full missing from https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/includes/scopes.md
