### ISSUE TITLE
Azure Artifacts Settings Access Permissions are Incorrect

### ISSUE THREAD

**Issue by magleaso** [MicrosoftDocs/azure-devops-docs#13231]
[In this doc](https://learn.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops) we need to change ln 25 to "> The Azure Artifacts settings icon will only be visible if you are a **Project Collection Administrator** or if you are included in the list of users who can administer feeds in the Azure Artifacts settings panel."

I tried to make a PR but got 403'd. Is engineering supposed to have access to make PRs?

@ramiMSFT

**Comment by WilliamAntonRohm** [comment]
@magleaso -- thank you for raising this issue.  Have you tried editing the article directly, using the pencil icon in the upper right?  That takes you to the source markdown file, with its own pencil icon, and when you edit that souce you'll create a new PR.  You may just tried this approach.  Another method is to work in the private repo azure-devops-docs-pr, which is the staging repo that is in turn merged into the live files; you may need additional GitHub perms to fork and use that repo.

if you prefer, I'll fix this myself.

**Comment by ramiMSFT** [comment]
Thank you @magleaso! For smaller changes the easiest option is to do a quick edit in GitHub. For substantial changes you can submit PRs to the private repo but you should definitely have access once you complete the prerequisite setup. I'll share the internal guide with you shortly.
