### ISSUE TITLE
Docker registry service connection Managed Identity Option is not visible in Azure Devops 

### ISSUE THREAD

**Issue by SiddheshDesai06** [MicrosoftDocs/azure-devops-docs#13239]
---
According to this document:-
https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/publish-to-acr?view=azure-devops&tabs=javascript%2Cportal%2Cmsi&fbclid=IwAR2bV28HzRs8v-qTXuo592KU5KxOFnNsOvhxpNx0ZCBYfz2OPnYXWh7rqUs#create-a-docker-registry-service-connection While creating service connection in this step, the Option to select Managed service identity is not visible in Azure DevOps service connection refer below:-

https://i.imgur.com/NNJ2skx.png

Refer the complete issue posted in this SO post below:-
https://stackoverflow.com/questions/75384558/no-option-to-use-managed-identity-in-azure-devops-to-connecti-with-container-reg/75397069#75397069

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26a4af57-5460-0ebf-93f1-f92f549406a8
* Version Independent ID: 26a4af57-5460-0ebf-93f1-f92f549406a8
* Content: [Create a service connection and build and publish Docker images to Azure Container Registry - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/publish-to-acr?view=azure-devops&tabs=javascript%2Cportal%2Cmsi&fbclid=IwAR2bV28HzRs8v-qTXuo592KU5KxOFnNsOvhxpNx0ZCBYfz2OPnYXWh7rqUs)
* Content Source: [docs/pipelines/ecosystems/containers/publish-to-acr.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/containers/publish-to-acr.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@SiddheshDesai06 -- Siddhesh, thank you for your thorough feedback.

@ramiMSFT -- Rami, please look into this issue.

**Comment by ramiMSFT** [comment]
@SiddheshDesai06 Thanks for your feedback! We are aware that a subset of users are experiencing this behavior. Please stay tuned for more details.
