### ISSUE TITLE
Which zip should we use there is 2020 and 2022 files ?

### ISSUE THREAD

**Issue by rifaterdemsahin** [MicrosoftDocs/azure-devops-docs#13234]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/5270036/230716539-e691333a-0c2c-442f-898b-668e37fa8363.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/migration-overview.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-migrate**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@rifaterdemsahin -- Erdem, thank you for your question.  I recommend using the most recent version.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
