### ISSUE TITLE
"Trigger an Azure Pipelines run from GitHub Actions - Azure Pipelines" page references what appears to be an unmaintained GitHub Action

### ISSUE THREAD

**Issue by deejgregor** [MicrosoftDocs/azure-devops-docs#13241]
Hello, [Trigger an Azure Pipelines run from GitHub Actions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops) references the [`Azure/pipelines` GitHub Action](https://github.com/marketplace/actions/azure-pipelines-action) which appears to be effectively unmaintained at this point (a new release hasn't been made since [v1.2](https://github.com/Azure/pipelines/releases/tag/v1.2) in 2019 and no commits have been made in the last year). That GitHub Action will stop working on 2023-06-01 because it uses `set-output`:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
-- ([source](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))

You probably should see that key issues [like this one](https://github.com/Azure/pipelines/issues/70) are addressed before June in the `azure-pipelines-action` or change this page to refer to another solution (or delete this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78ea192f-6f71-4f46-895a-9ea1c106d6c1
* Version Independent ID: fdbc829d-e137-11c6-c35f-626970e44cef
* Content: [Trigger an Azure Pipelines run from GitHub Actions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/github-actions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/github-actions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @deejgregor! I've verified this is an issue. Can you file a bug in our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)? I'll also let the product team know.

**Comment by juliakm** [comment]
Hi @deejgregor. Just wanted to update you that the product team is aware and looking into this. I'll add a note to the article that the action is not currently working.
