### ISSUE TITLE
Are there any plans to allow for the linking of test binaries located in another project?

### ISSUE THREAD

**Issue by JonathonFord** [MicrosoftDocs/azure-devops-docs#13245]
This is an awesome feature and I would love to use it. Unfortunately I can only point to build pipelines located in the same project and we keep our automated tests in a separate automation project in ADO. Rather than a separate repo in the same project. We run smoke tests in the build pipeline by linking artifacts from across projects already, are there any plans to allow that same functionality to happen here for linking test binaries/release pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e96b9876-8444-39f4-57de-7b686c1c1182
* Version Independent ID: e1e22e40-f772-9524-e100-992cb838d9b7
* Content: [Run automated tests from test plans - Azure Test Plans](https://learn.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/test/run-automated-tests-from-test-hub.md)
* Service: **azure-devops-test-plans**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@JonathonFord -- Jonathon, thank you for your feedback.  This is the best place to suggest a feature:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
