### ISSUE TITLE
Please also include reference for explaining a bit on "azureServiceConnectionId"

### ISSUE THREAD

**Issue by sushaanttb** [MicrosoftDocs/azure-devops-docs#13255]
Generally, when we are generating the pipeline as per the shared steps, it automatically sets the "azureServiceConnectionId"
variable. However, when someone wants to configure the pipeline for some other connectionId, it's difficult to locate the Id,
unless one has the knowledge about locating it from URL from following StackOverflow link.
Even when one searches in Microsoft docs, there isn't much references available 
https://stackoverflow.com/questions/68842459/how-to-view-or-get-the-service-connection-id-in-azure-devops

Hence, suggestion to have some details about this parameter in the docs.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744eaf3c-85c6-2092-823a-8a709018b5f7
* Version Independent ID: 3ed6d4b4-334f-775b-f783-912b76124557
* Content: [Build and deploy Python web apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/python-webapp.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sushaanttb The easier way to update the azureServiceConnectionId is through the task select **Settings** for the `AzureWebApp@1` task and update the **Azure subscription** value. I'll add a note in the article as well. We generally don't recommend pulling from URL strings.
