### ISSUE TITLE
Azure DevOps Pipelines Common service connection types does not include ACR

### ISSUE THREAD

**Issue by arindam0310018** [MicrosoftDocs/azure-devops-docs#13251]
Hello Team,

I was referring to MS documentation - https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml and I then realized that there is no connection type "Azure Container Registry" (ACR) available in the documentation.

# Below follows Screenshots:-

## List of connection types available mentioned in your documentation:- 
![image](https://user-images.githubusercontent.com/29681063/232309458-6c0c2a36-442b-4173-a23d-1df0959fb0e1.png)

## Options Available in Azure DevOps :-
![image](https://user-images.githubusercontent.com/29681063/232309196-f3b08e66-82ef-436a-a1bf-b65a440b6328.png)

Hoping for an explanation incase if my understanding is incorrect.

Many Thanks
Regards, Arindam Mitra

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5284952-75a7-b6c1-69e6-be179bb94e02
* Version Independent ID: aac8216a-6c50-c614-540b-24a5f93cdb5a
* Content: [Service connections in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/library/service-endpoints.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@arindam0310018 -- Arindam, thank you for your well-researched feedback.  I believe you are correct.

@RoopeshNair -- Roopesh, please look into this issue.

**Comment by arindam0310018** [comment]
Hello @WilliamAntonRohm 
Thank you for your kind reply and confirming on my observation.

Hello @RoopeshNair, When You find time, Please do update.

Many Thanks
Regards, Arindam Mitra

**Comment by arindam0310018** [comment]
Hello @WilliamAntonRohm, @RoopeshNair 
Request you to kindly update.

Many Thanks
Regards, Arindam Mitra

**Comment by arindam0310018** [comment]
Hello @WilliamAntonRohm, @RoopeshNair 
Kindly update when you find time.

Many Thanks
Regards, Arindam Mitra

**Comment by steved0x** [comment]
It is in the doc here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#azure-container-registry

I have added it to the list up at the top in the area right before "Docker and others". This change should be live today.
