### ISSUE TITLE
Replace mention of legacy MS Test Manager

### ISSUE THREAD

**Issue by CloudHotShot** [MicrosoftDocs/azure-devops-docs#13256]
All mentions of Microsoft Test Manager should be updated to mention Azure Test Plans instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e55c8bac-57f4-50c9-486a-a64fda62674f
* Version Independent ID: 0c23aa35-7906-28ce-9467-2d78464da2bf
* Content: [Associate automated tests with test cases - Azure Test Plans](https://learn.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/test/associate-automated-test-with-test-case.md)
* Service: **azure-devops-test-plans**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@CloudHotShot -- Mark, thank you for your suggestion.  I'm not sure how to disentangle this in the article.

@steved0x -- Steve, please look into this issue.
