### ISSUE TITLE
Instructions for actions icon need to be updated

### ISSUE THREAD

**Issue by sdcushina** [MicrosoftDocs/azure-devops-docs#13253]
The actions icon ... is no longer available on this page for certain changes.  
For example 
Step 2 on [Update Work Items](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-basic-to-agile?view=azure-devops#update-work-items) states

Choose the ... actions icon and then select **Column options**.   
But Column options is now part of the menu bar 
![image](https://user-images.githubusercontent.com/105375471/232423682-f78efa09-cfa3-484d-aaa6-8d9ccab5aaa5.png)

Similarly the following sentence in Step 4 needs to change since **Save items** is also part of teh menu bar above
Choose the  actions icon and select **Save items**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 365bff0e-8532-ae8a-f1c9-37ea7017e5b1
* Version Independent ID: a324129d-0edb-00ce-1217-819be9fda4f6
* Content: [Change process from Basic to Agile - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/change-process-basic-to-agile?view=azure-devops)
* Content Source: [docs/organizations/settings/work/change-process-basic-to-agile.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/work/change-process-basic-to-agile.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback! The article's been updated, including the addition of a note that explains how the basic functionality remains, while screenshots may differ slightly from what you see, based on updates made to Azure DevOps. Thanks again.
This issue will close when the PR gets merged.
