### ISSUE TITLE
For the love of Christ, please fix the Dependencies mess

### ISSUE THREAD

**Issue by gswallow** [MicrosoftDocs/azure-devops-docs#13259]
Everything about https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies is terrible and you are doing a disservice to all of your users by leaving it as it has been for so long.

I waste so much time grappling with what should be the simple task of declaring a variable once in the pipeline and reusing it elsewhere, and *every other vendor* has made this a trivial task.  See: Github Actions (which you *own*).

**Comment by WilliamAntonRohm** [comment]
@gswallow -- Greg, thank you for your considered feedback.  Can you provide additional details regarding inaccuracies or missing information in that article?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
