### ISSUE TITLE
the procedure to lookup a user is not accurate

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-devops-docs#13260]
If the project administration is done using groups, then the user search will not find any user.
There is an additional step after typing the user name, *Expand search*.
And a big search limitation: the expanded search will find the user name only if it starts with what the portal user typed!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce8b2923-a3dc-7055-6550-d4943faa5a68
* Version Independent ID: fce8bd86-a25c-341e-5be4-61f19e4dd08f
* Content: [View permissions for yourself or others - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/view-permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/view-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/view-permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, I am in the process of updating this article.
