### ISSUE TITLE
migrator /import fails with javascript check

### ISSUE THREAD

**Issue by liampkemp** [MicrosoftDocs/azure-devops-docs#13264]
Migrator /import fails to load login screen with the message 
"Your browser is security restricted or JavaScript is disabled. Do you want locations required for sign-in to be automatically added to your Trusted Sites list?"

This occurs even if the trusted sites list is populated with the sign-in urls, and the /validate step is able to load the sign in page.

Clicking OK just causes to tool to crash, and no additional sites are added to Trusted Sites

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bff3fd07-3d7b-1244-88e4-c2cfbb3fa204
* Version Independent ID: 63f4392f-2dc6-4620-a24f-c02070dd7115
* Content: [Troubleshoot migration import to Azure DevOps Services - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/migrate/migration-troubleshooting?view=azure-devops)
* Content Source: [docs/migrate/migration-troubleshooting.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/migrate/migration-troubleshooting.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-migrate**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@liampkemp -- Liam, thank you for your feedback.  This issue seems more product-related than documentation-related -- please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
