### ISSUE TITLE
Wrong Text: "Screenshot to" should be removed

### ISSUE THREAD

**Issue by horazius77** [MicrosoftDocs/azure-devops-docs#13268]
Under Heading: "List work items added after the start of the sprint"
No 1: Screenshot to Open the velocity chart

"Screenshot to" should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcb22f37-3dc2-e54c-13c5-a2753901fad4
* Version Independent ID: a39daaa2-8d90-8bab-833e-6106b3939b4b
* Content: [Implement Scrum work practices in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/sprints/scrum-overview?view=azure-devops)
* Content Source: [docs/boards/sprints/scrum-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/sprints/scrum-overview.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@horazius77 -- Daniel, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@horazius77 -- Daniel, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
