### ISSUE TITLE
Text references branch 'master', but it is 'main' in the yaml

### ISSUE THREAD

**Issue by Amleto** [MicrosoftDocs/azure-devops-docs#13269]
In the doc text there are three references to the 'master' branch, but in the yaml examples, the branch is now called 'main'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/azure-repos-git.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@Amleto -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
