### ISSUE TITLE
Update the document on ADO build/release task extension creation as its pretty out dated

### ISSUE THREAD

**Issue by a-aarchana** [MicrosoftDocs/azure-devops-docs#13274]
[Enter feedback here]
The document recommends es6, which is quite outdated, as ts seems to be supporting es2023. 

It would also tremendously help to leverage the below document that talks about the various task runners, and how to include the latest node version it in the task.json.

https://devblogs.microsoft.com/devops/node-runner-update-guidance-for-azure-pipelines-task-authors/#upcoming-changes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback. I'll be publishing updates today. Have a great weekend!
