### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by j-martens** [MicrosoftDocs/azure-devops-docs#13278]
Might need a refresh. :-) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26c14bb1-b4a9-79de-4fa7-eb66f6ccaa63
* Version Independent ID: d227ffcb-775a-09c5-d8dd-0939aaec975a
* Content: [Connect Azure Boards to an Office client to track your work - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel)
* Content Source: [docs/boards/backlogs/office/track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/track-work.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @j-martens. I've updated the article!
