### ISSUE TITLE
error in verbiage - grammer 

### ISSUE THREAD

**Issue by maynard517** [MicrosoftDocs/azure-devops-docs#13287]
[Enter feedback here]
The note section reads " then you're collection".  It should read " then your collection".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa7a0948-ee09-8734-ed6e-bc45bd78ce01
* Version Independent ID: da9ac11c-958d-f5dd-efad-0c20c2d7cf2f
* Content: [List work item fields and attributes in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-fields.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/work-items/work-item-fields.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@maynard517, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
