### ISSUE TITLE
Don't use doughnut or pie charts as this page gives them validity

### ISSUE THREAD

**Issue by AlanGraham0** [MicrosoftDocs/azure-devops-docs#13288]
Beginners in data visualisation will see Learn pages as authorative.  John Tukey and Edward Tufte disagree.  Please don't use doughnut or pie charts in Learn pages, consider converting them to bar charts.

[Why pie charts are evil](https://www.ataccama.com/blog/why-pie-charts-are-evil)

[Pie charts - good, bad, or ugly?](https://xviz.com/blogs/pie-charts-good-bad-or-ugly/)

[The case against the pie chart](https://towardsdatascience.com/the-case-against-the-pie-chart-43f4c3fccc6)

[Edward Tufte](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00018S)

[Melbourne Uni](https://scc.ms.unimelb.edu.au/resources/data-visualisation-and-exploration/no_pie-charts)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 624755d0-ee11-e9e4-ea2b-26444f50259d
* Version Independent ID: 02ef07f5-8054-f6a3-9a55-34acd967f10d
* Content: [Manual test progress status sample Power BI report - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/powerbi/sample-test-plans-progress-status?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-test-plans-progress-status.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/powerbi/sample-test-plans-progress-status.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @chcomley
* Microsoft Alias: **shdalv**

**Comment by WilliamAntonRohm** [comment]
@AlanGraham0 -- Alan, thank you for your considered feedback.

@chcomley -- Chrystal, please look into this issue.
