### ISSUE TITLE
DevOps2022 ES Java information and update process is incorrect

### ISSUE THREAD

**Issue by lennybacon** [MicrosoftDocs/azure-devops-docs#13292]
[Enter feedback here]

1. To update JAVA for elastic search it is required to run the command `& "C:\Program Files\Azure DevOps Server XXX\Search\ES\vX.XX\bin\elasticsearch-service.bat" manager`. This opens a configuration UI where the path to the JAVA version which is actually used. `JAVA_HOME` is just ignored.
2. The DevOps2022 ES requires JRE 11 or higher. I got it working with 11. Also tried 17/18 which failed.
3. There is a Microsoft distribution of the JDK which might also be favored over the 3rd party one: https://learn.microsoft.com/en-us/java/openjdk/download

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b81d598-df12-9ef1-9821-71f240b5d0e9
* Version Independent ID: 9814578c-72d2-d0da-a0fb-051eab0b9bd9
* Content: [Install, configure Search - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/search/install-configure-search?view=azure-devops-2022)
* Content Source: [docs/project/search/install-configure-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/search/install-configure-search.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-search**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by bballpaul4work** [comment]
How did you get JRE 11 to work? When you run Configure-TFSSearch.ps1 and ES_JAVA_HOME is set to 11, it complains that JAVA_HOME is not set. If you set JAVA_HOME to the version 11 directory, it compains that the installed JAVA version is incompatible.

**Comment by lennybacon** [comment]
I did not set `ES_JAVA_HOME` and selected the 11:

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/272164/38f9d532-a744-457f-8a31-4e81e6656446)

**Comment by chcomley** [comment]
Hi @lennybacon, this issue is old and dusty, and our resources are scarce...do you have any interest in helping us update this article? Please consider becoming a contributor to our docs. It's fast and easy and hopefully rewarding. Here's how you can [Edit our docs in the browser](https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits).

**Comment by lennybacon** [comment]
I created a PR at https://github.com/MicrosoftDocs/azure-devops-docs/pull/13836
