### ISSUE TITLE
Typo makes resource type targeting ambiguous

### ISSUE THREAD

**Issue by Brubning** [MicrosoftDocs/azure-devops-docs#13308]
The example under "Use VM in pipelines" has a typo in the YAML - this makes the result of targeting by resource type unclear.

The text reads:

```
  environment: 
   name: VMenv
   resourcesNAme: VMenv
   resourceType: virtualMachine
```

But should read:

```
  environment: 
   name: VMenv
   resourceType: virtualMachine
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Brubning** [comment]
Nope. Not sure why the link to the content that automatically added when I raised the issue is incorrect. The live document is here: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops

And in the "Use VM in pipelines" section it is still incorrect.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/28068804/92606758-6b3d-4bfe-9596-d5ca1ba6a225)

**Comment by WilliamAntonRohm** [comment]
@Brubning -- thank you for your followup; I'll update the article.  It is odd that the wrong page showed up.

**Comment by juliakm** [comment]
@Brubning Thanks, a fix will go out shortly.
