### ISSUE TITLE
Non-RSA SSH keys

### ISSUE THREAD

**Issue by mandtbacka** [MicrosoftDocs/azure-devops-docs#13301]
is it possible to use, e.g., an ed25519 SSH key for authentication to Azure Repos, and if so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fde585e-edbd-c738-4d34-b1dfca1ef033
* Version Independent ID: 974698f8-cb53-24d4-f75f-a88c16f8e51c
* Content: [Use SSH key authentication - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?source=recommendations&view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by Okeanos** [comment]
The answer to that is [no](https://developercommunity.visualstudio.com/t/support-non-rsa-keys-for-ssh-authentication/365980).

**Comment by WilliamAntonRohm** [comment]
@Okeanos -- Nikolas, thank you for your definitive contribution to this discussion.
