### ISSUE TITLE
Where is the Delete REST API operation?

### ISSUE THREAD

**Issue by smaglio81** [MicrosoftDocs/azure-devops-docs#13310]
On the [Delete and Recover Packages](https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=nuget#unlist-a-nuget-package-by-using-nugetexe) page, there is a note that:

> Azure DevOps and Visual Studio Team Foundation Server interpret the nuget.exe delete command as an unlist operation. To delete a package, you must use the REST API or the web interface.

There isn't a link to the delete operation within the note, and I am unable to find a Delete operation on the [Artifacts API](https://learn.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact-details?view=azure-devops-rest-7.0) page.

Where can I find documentation on the Delete REST API operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=nuget)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/how-to/delete-and-recover-packages.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@smaglio81 Thanks for your feedback! Here is the api ref to delete: https://learn.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/delete-package-version?view=azure-devops-rest-7.0
I'll add it to the docs
