### ISSUE TITLE
Could you please provide an example how to register an Agent with a SP

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/azure-devops-docs#13319]
Hey guys,
it seems to be possible to register an agent with an SP. Please update this documentation, so that I know how I can do this and how I have to enter the client-secret.

https://learn.microsoft.com/en-gb/azure/devops/release-notes/2023/sprint-221-update#pipeline-agents-can-be-registered-using-a-service-principal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Version Independent ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Content: [Use Azure Active Directory service principals & managed identities - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/service-principal-managed-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/get-started/authentication/service-principal-managed-identity.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @Wonga
* Microsoft Alias: **wonga**

**Comment by dm-shlandii** [comment]
Also looking into using auth SP, but it seems like it will be available when this PR will be merged: https://github.com/microsoft/azure-pipelines-agent/pull/4255
