### ISSUE TITLE
Note about Android emulator being available on only macOS agent is out of date

### ISSUE THREAD

**Issue by nayanshah** [MicrosoftDocs/azure-devops-docs#13331]
The page has following note which is out of date: 

    > The Android Emulator is currently available only on the Hosted macOS agent.

`windows-2022` agents also have Android emulator installed, just an older version - https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#android

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9f69815-b798-2328-7e55-c67865505623
* Version Independent ID: 2ece0f9a-c3f8-2a47-71ef-c9e22e2a02c9
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/android.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@vijayma -- Vijay, please confirm this update in [private PR 6013](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/6013).
