### ISSUE TITLE
vs403191  - Unable to cast COM object of type

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/azure-devops-docs#13344]
It would probably be useful to link/incorporate this article, to help people experiencing this issue:
 
https://learn.microsoft.com/en-gb/archive/blogs/dau-blog/how-to-solve-unable-to-cast-com-object-of-type-microsoft-office-interop-excel-applicationclass-to-interface-type-microsoft-office-interop-excel-_application

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c6dd3-d2d2-0d41-9958-d3f7d85b5c05
* Version Independent ID: e5e4a28f-30b8-0dab-b94b-d94fe6d341fe
* Content: [Resolve common Azure DevOps Office integration issues - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/office/tfs-office-integration-issues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/tfs-office-integration-issues.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for the great idea, @fowl2. I've updated the article accordingly.
