### ISSUE TITLE
What is <PACKAGE_SOURCE>??

### ISSUE THREAD

**Issue by craiggeil** [MicrosoftDocs/azure-devops-docs#13353]
What does `<PACKAGE_SOURCE>` indicate???

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f386bad4-494d-fcd3-b3f3-44a33601e866
* Version Independent ID: c1fe07ab-8092-26b7-f3f0-a3fce718da51
* Content: [Connect to a feed and publish NuGet packages - NuGet.exe - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/nuget/publish.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@craiggeil -- Craig, thank you for your question.  I agree the surrounding prose could make that clearer.  I am investigating.

**Comment by ramiMSFT** [comment]
@craiggeil It's the name of the source. And then in the second command, you'll be using the name of the source that you added to your config file to push your package. See [nuget sources](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources) for more details. Thanks for your feedback, I'm fixing the article shortly.
