### ISSUE TITLE
 Self hosted agent doesn't work on MacOS 13.3.1 

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/azure-devops-docs#13351]
Self hosted agent cannot be run on MacOS 13.3.1 on M1 chip. Error message says: 
“Agent.Listener” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49277eea-6b0a-43a0-a8cb-c67ff268d639
* Version Independent ID: 49277eea-6b0a-43a0-a8cb-c67ff268d639
* Content: [Deploy a build and release agent on macOS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/osx-agent?view=azure-devops)
* Content Source: [docs/pipelines/agents/osx-agent.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/osx-agent.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@cagrimunyas -- Cagri, thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
