### ISSUE TITLE
vSphere Management SDK 6.0 is too old?

### ISSUE THREAD

**Issue by ffonz** [MicrosoftDocs/azure-devops-docs#13359]
On our agent we have installed VS2022. Due to this installation vSphere Management SDK 6.0 cannot find java 8 anymore. This is because VS has added "Microsoft Build of OpenJDK with Hotspot 11.0.12+7 (x64)" to the PATH and this is conflicting with java 8. For java 11, vSphere Management SDK 7.0 U3 (or higher) is needed. So can this page be rewritten to this SDK 7.0 U3 or 8.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd29732f-6c8a-327c-307b-db7897fc0250
* Version Independent ID: 5db35e15-2bbf-7a9f-8f7d-0dd32b6b92b0
* Content: [Deploy to VMware - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/targets/vmware?view=azure-devops)
* Content Source: [docs/pipelines/targets/vmware.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/targets/vmware.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-targets**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@ffonz -- thank you for your clear feedback. 

@RoopeshNair -- please look into this issue.

**Comment by ffonz** [comment]
I have to clearify it a little bit: I am trying to use SDK 7.0 U3f in **combination with java 11**, but I have not managed to get it right.
