### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by craiggeil** [MicrosoftDocs/azure-devops-docs#13352]
This does not work. Your instructions do match what is given in the Artifacts NuGet.exe instructions. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f386bad4-494d-fcd3-b3f3-44a33601e866
* Version Independent ID: c1fe07ab-8092-26b7-f3f0-a3fce718da51
* Content: [Connect to a feed and publish NuGet packages - NuGet.exe - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/nuget/publish.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@craiggeil Could you provide further details about your issue and the section that's not working for you?

**Comment by ramiMSFT** [comment]
Closing this issue for now. Feel free to leave a comment if you're still experiencing issues.
