### ISSUE TITLE
Checkout Files from LFS, need to escape % signs

### ISSUE THREAD

**Issue by rob-avalon** [MicrosoftDocs/azure-devops-docs#13361]
In the section [Check out files from LFS](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#using-git-lfs-with-submodules) 

I had to add extra % signs in order to escape the % so my code ended up looking like this:
```
steps:
- script: |
    git config --global --add filter.lfs.required true
    git config --global --add filter.lfs.smudge "git-lfs smudge -- %%f"
    git config --global --add filter.lfs.process "git-lfs filter-process"
    git config --global --add filter.lfs.clean "git-lfs clean -- %%f"
  displayName: Configure LFS for use with submodules
- checkout: self
  lfs: true
  submodules: true
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#using-git-lfs-with-submodules)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/pipeline-options-for-git.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@rob-avalon -- Rob, thank you for bringing this to our attention.  I am updating the article.
