### ISSUE TITLE
Mention of feature branch in place of Release branch

### ISSUE THREAD

**Issue by anjanchidige** [MicrosoftDocs/azure-devops-docs#13374]
On [Port changes back to the main branch](https://learn.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops&source=docs#port-changes-back-to-the-main-branch) section, under 2nd paragraph, mentioned below, The "**feature branch**" should be "**Release branch**". 

"_Merging the **feature branch** into the main branch can bring over release-specific changes you don't want in the main branch__._"

Regards
Anjan
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d81cb742-b96c-ab35-50f9-877a824de1e2
* Version Independent ID: 1cfb9766-2a25-ded7-4c52-33c93cc69e97
* Content: [Git branching guidance - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops&source=docs)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/git-branching-guidance.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@anjanchidige -- Anjan, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
The article has been updated and is now live.
