### ISSUE TITLE
Some documentation is needed around "open access" permissions

### ISSUE THREAD

**Issue by gertvdh** [MicrosoftDocs/azure-devops-docs#13381]
Some documentation is needed around "open access" permissions. Only project collection administrators can open access on environments it seems. Can this be added somewhere in the documentation?

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/24321244/6fe36420-58ea-406f-bfbe-1b9eaf813d54)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops&tabs=yaml#security)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@gertvdh -- thank you for your clear feedback.

@juliakm -- please look into this issue.

**Comment by juliakm** [comment]
@gertvdh Thanks for flagging this. While I work on adding documentation, here's [more information from our release notes](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-216-update#restrict-opening-protected-resources-to-resource-administrators).

**Comment by stevenoneill-jmfamily** [comment]
@ShannonLeavitt @juliakm  -- please re-open this?  Creator is not sufficient to Open Access on environments.  Project Collection ADministrator is needed.

This was our observation by trying each of the following with a user:
User as Creator -> fail
User as Project Administrator -> fail(!)
User as Project Collection Administrator -> Success

**Comment by ShannonLeavitt** [comment]
@stevenoneill-jmfamily - Reopening issues isn't in our purview. This issue was closed automatically by a PR submitted by @juliakm, who is the right person to ask about reopening this issue.

**Comment by Slooz** [comment]
I can confirm what @stevenoneill-jmfamily is seeing, and it's frustrating that the documentation doesn't clearly state this.

> Azure Pipelines requires the Administrator role when opening up access to a resource to all pipelines for all protected resources except for Environments. For Environments, you'll need the Creator role.

This is incorrect, neither the Creator role or the Administrator role are sufficient for opening up access to all pipelines for Environments. Is this a bug within Azure DevOps, or is the documentation wrong?

@juliakm @ShannonLeavitt @WilliamAntonRohm
