### ISSUE TITLE
Permission access given in docs did not work, but alternative worked. 

### ISSUE THREAD

**Issue by pavinan** [MicrosoftDocs/azure-devops-docs#13386]
In point number 5, it is mentioned to give permission to Project Collection Build Service ({your organization}). But it did not work, i have added permissions to {{Your Project Name}} Build Service ({your organization}) then it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb008b3-663d-0698-9f39-65cbfde34dcf
* Version Independent ID: ddcd9666-1517-866c-4cee-f79fccaf0663
* Content: [Run Git commands in a script - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/scripts/git-commands.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review this update in [private PR 5385](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5835).
