### ISSUE TITLE
Ubuntu Image 18.04 no longer valid

### ISSUE THREAD

**Issue by svaenn** [MicrosoftDocs/azure-devops-docs#13380]
Hello,

the code samples for output variables still use 
`vmImage: 'ubuntu-18.04'`
as this image is no longer available this lead to a job simply not starting without any error message for me.
Please update the samples to use current or maybe latest vm-images.

Thank you!

Best regards,
  Sven

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@svaenn -- Svaen, thank you for your feedback.  I am updating this article to use `ubuntu-latest`.
