### ISSUE TITLE
Clarify Service Principal Login

### ISSUE THREAD

**Issue by bushelofsilicon** [MicrosoftDocs/azure-devops-docs#13396]
The page states "_However, you can't sign in as the service principal via az login. In that scenario, a PAT is required._"

But logging in with `az login --service-principal -u <app id> -p <password> --tenant <tenant id>` does work for using a service principal for az devops cli, but `az login --identity` for managed identities does not work for the azure devops cli. In order to log in an azure access token needs to be used as the PAT, however in this scenario the wording between documentation is a bit conflicting since this document says "_In that scenario, a PAT is required_" but in https://learn.microsoft.com/en-gb/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops#use-the-azure-ad-token-to-authenticate-to-azure-devops-resources it states "_Service principals can't create tokens, like personal access tokens (PATs) or SSH Keys._" When the reality is you can use an access token as the PAT for the az devops login for a Managed Identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af3bebb5-3c18-a905-67b7-a1c6bd4f4522
* Version Independent ID: d6c7802a-dfdf-9852-a51b-d2ba30be70fe
* Content: [Sign in with a Personal Access Token (PAT), Azure DevOps CLI - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows&source=docs)
* Content Source: [docs/cli/log-in-via-pat.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/cli/log-in-via-pat.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-reference**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@bushelofsilicon -- thank you for your well-researched feedback.

@chcomley -- please look into this issue.

**Comment by chcomley** [comment]
@angelwong can you please help clarify? Thank you!

**Comment by chcomley** [comment]
I've reached out again and will be in touch, thanks for your patience on this.

**Comment by chcomley** [comment]
Hi @bushelofsilicon, I'm updating the article today, thank you for your feedback. I'm sorry for the confusion, as it's out-of-date and I'm removing the referenced text. Thanks again!
