### ISSUE TITLE
The `tf workspace Beta1;jenh` example doesn't work, changing it to `tf workspaces Beta1;jenh` does

### ISSUE THREAD

**Issue by frankvaneykelen-work** [MicrosoftDocs/azure-devops-docs#13394]
Running this:

```
 tf workspace "Dev-Docker";"Frank" 
```

Returns:

```
Specify at least one of the following options: /newname, /newowner, /permission, /computer, /comment, /filetime, or /location.
Frank
```

Changing `workspace`  to `workspaces`:

```
 tf workspaces "Dev-Docker";"Frank" 
```

Returns the result I expect:

```
Collection: https://dev.azure.com/[....]
Workspace  Owner [...]
---------- ----- [...] 
Dev-Docker Frank [...]

Frank
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3ca043d-6320-37a3-140f-8ad9dfaec34f
* Version Independent ID: dbe8e735-864a-724a-968b-c677f29b6553
* Content: [TFVC workspace command - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/workspace-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/workspace-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/tfvc/workspace-command.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@frankvaneykelen-work -- Frank, thank you for research.

@vijayma -- Vijay, please review this update in [private PR 5834](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5834).
