### ISSUE TITLE
Inline image not loading in Get-Bagde docs

### ISSUE THREAD

**Issue by Ryno95** [MicrosoftDocs/azure-devops-docs#13405]
The tags in the get-status-badge are not rendering correctly, which causes some confusion.

The issue concerns this file: 
[azure-devops-docs/docs/pipelines/includes/get-status-badge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/6f82f42b5da4731b8f990299eea3b1060d552cff/docs/pipelines/includes/get-status-badge.md)

It concerns this line: **2. Select :::image type="icon" source="../../media/icons/more-actions.png":::, and then select **Status badge**.**

**Comment by WilliamAntonRohm** [comment]
@Ryno95 -- Ryno, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@Ryno95 -- Ryno, it's displaying correctly on my machine. 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
