### ISSUE TITLE
Incorrect documentation link

### ISSUE THREAD

**Issue by jeevanions** [MicrosoftDocs/azure-devops-docs#13419]
[Enter feedback here]
![Screenshot 2023-06-20 at 16 59 30 copy](https://github.com/MicrosoftDocs/azure-devops-docs/assets/95138087/de234416-8f43-4bee-9b4c-c74aefa81563)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df5d17e2-0f83-b115-5bfc-1a1691441dc2
* Version Independent ID: df5d17e2-0f83-b115-5bfc-1a1691441dc2
* Content: [Manage your pipeline with Azure CLI - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/manage-pipelines-with-azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/get-started/manage-pipelines-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/manage-pipelines-with-azure-cli.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @silviuandrica
* Microsoft Alias: **sandrica**

**Comment by WilliamAntonRohm** [comment]
@jeevanions -- thank you for your feedback.  Please clarify the difference between that link's destination, and your expected destination.
