### ISSUE TITLE
Running setup.py to build wheel is deprected.

### ISSUE THREAD

**Issue by gitmadness** [MicrosoftDocs/azure-devops-docs#13423]
When running "python setup.py bdist_wheel" the following message is shown:

 SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!

Should use "pip install build" and "python -m build -w" from the path setup.py is localted.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1736d421-eabc-fad7-60af-611d6cdd7050
* Version Independent ID: 0dfd27b1-12ad-1f4b-bd52-5886da18cd2a
* Content: [Publish and consume Python packages using the CLI - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-cli?view=azure-devops)
* Content Source: [docs/artifacts/quickstarts/python-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/quickstarts/python-cli.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Duplicate [13422](https://github.com/MicrosoftDocs/azure-devops-docs/issues/13422)
