### ISSUE TITLE
How can I create links to the subpages?

### ISSUE THREAD

**Issue by royaza** [MicrosoftDocs/azure-devops-docs#13428]
In [this section,](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-a-subpages-table) it has been explained how to create a subpage table, but I can't find any guide about how to create links to subpages. It is useful to explain also that part in this section. For example, how the "Subpage 1" is appeared in the subpages table in the example of this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-a-subpages-table)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@royaza -- Roya, thank you for your questions and follow-up.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
Roya, that link already exists, under **Related articles**:
- [Project wiki](https://learn.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
