### ISSUE TITLE
Is there a syntax error in Created Date>=Today-7

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/azure-devops-docs#13425]
Should this example 
Created Date>=Today-7

be
Created Date>=@Today-7

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, macros, and variables - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/query-operators-variables.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- Chrystal, please review this change in [private PR 5872](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/5872).

**Comment by WilliamAntonRohm** [comment]
@dombat -- Dominic, thank you for catching this.  I have updated the documentation and it should be live by tomorrow.
