### ISSUE TITLE
Running setup.py directly to build a wheel is deprecated. The examples should be updated.

### ISSUE THREAD

**Issue by gitmadness** [MicrosoftDocs/azure-devops-docs#13422]
When building a wheel package using "python setup.py bdist_wheel", the following message is shown:

SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!

Per blog, should "pip install build" and then run "python -m build -w" from the folder where setup.py is located.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c37d1cb4-805b-173c-ac62-1037c5bedb7f
* Version Independent ID: 91cfb14e-b752-93e2-52a7-25d8d3fe66d5
* Content: [Publish Python packages - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/pypi.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@gitmadness Thanks for your feedback! I ran this on my end and it passed. Your approach is also valid. Feel free to use our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/AzureDevOps) if you have any further questions.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/60942540/a4a5241f-f92f-4544-b7d8-2b69a73c9e7f)
