### ISSUE TITLE
Target directory in the code example is different from the one from the description

### ISSUE THREAD

**Issue by tihobrazov** [MicrosoftDocs/azure-devops-docs#13437]
In Artifact download section you have:
This example YAML file publishes the artifact WebSite and then downloads the artifact to $(Pipeline.Workspace)

But in Deploy job it has downloadPath: $(System.DefaultWorkingDirectory)

Is it a typo? Should be downloadPath: $(Pipeline.Workspace) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95227592-b2a9-62be-59d1-fe8c7f4eae8e
* Version Independent ID: abf0c659-ce8c-b187-2784-22ddc061d69f
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/phases.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@tihobrazov By default, the [PublishPipelineArtifact@1](https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines) task publishes artifacts to `$(Pipeline.Workspace)`. Interestingly, when I ran the example code, both `$(Pipeline.Workspace)` and `$(System.DefaultWorkingDirectory)` worked in the Deploy job. I'm updating the downloadPath for clarity to `$(Pipeline.Workspace)`. Thanks for bringing this to our attention!
