### ISSUE TITLE
Incorrect syntax in code snippet

### ISSUE THREAD

**Issue by dylanmccurry-msft** [MicrosoftDocs/azure-devops-docs#13441]
In the Project Setup section, under Other -> This command fails on my mac:

```
echo -n "YOUR_PERSONAL_ACCESS-TOKEN" | base64 -w 0
```

I believe it should instead be:

```
echo -n "YOUR_PERSONAL_ACCESS-TOKEN" | base64
```

The `-w` flag isn't recognized as a valid argument.

OSX 13.4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&viewFallbackFrom=vsts&tabs=windows%2Cclassic)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/npm/npmrc.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@dylanmccurry-msft -- Dylan, thank you for catching this.  I am updating the article.
