### ISSUE TITLE
Security visibility

### ISSUE THREAD

**Issue by Aparnex** [MicrosoftDocs/azure-devops-docs#13453]

**Comment by TimShererWithAquent** [comment]
@Aparnex Thanks for your feedback. We appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
