### ISSUE TITLE
Casting -> coercion

### ISSUE THREAD

**Issue by joostheijkoop** [MicrosoftDocs/azure-devops-docs#13476]
I think Type coercion is meant instead of Type casting in the examples with Boolean to Integer coercion

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@joostheijkoop -- thank you for your feedback.  I believe you are technically correct, as these conversions are not explicit.  In the context of this article, "casting" is also appropriate.

cc @juliakm for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
