### ISSUE TITLE
Can no longer link to GitHub issue

### ISSUE THREAD

**Issue by DBojsen** [MicrosoftDocs/azure-devops-docs#13484]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Since 2 weeks ago, @chcomley [made an update removing how to link to GitHub issues ](https://github.com/MicrosoftDocs/azure-devops-docs/commit/c45d3322865e5ce508ae7ec401e5206748d2d3d3)- even though it is still listed as an option in the header.

Why can we no longer link to issues?

**Comment by chcomley** [comment]
Hi @DBojsen, thanks for alerting us to this! This was an accidental occurence and the info was re-added. Thanks again!
