### ISSUE TITLE
Finding the correct AzureDevops HttpClient is too hard

### ISSUE THREAD

**Issue by scottg-at-igs** [MicrosoftDocs/azure-devops-docs#13485]
You should list the HttpClient types used to hit various APIs methods alongside the nugets in your docs. Here are the steps we had to follow to find the code search client and method:

1. Started here: https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops
2. Searched for "search" on this page, hoping the namespace was named similarly to the feature
3. Installed that Nuget package
4. Manually looked through dozens of namespaces trying to guess the ones that looked like it might house a client
5. Found the WebApi namespace with a SearchHttpClient in it
6. Instantiated that client in Visual Studio with the GetClient method
7. Used Intellisense to confirm it had the code search method we were looking for

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/dotnet-client-libraries.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback. I updated the article, adding a tip with links to info (which will publish shortly). If you would like to add more specific steps toward getting more information, I welcome you to become a contributor to our docs and help us out. Here's a link: https://learn.microsoft.com/en-us/contribute/
Thanks so much!
