### ISSUE TITLE
Webhook based triggers for incoming service connection do not work if JSON Path returns an array/object

### ISSUE THREAD

**Issue by reespozzi** [MicrosoftDocs/azure-devops-docs#13486]
I'm implementing a solution where an incoming service connection is used in ADO, and a JSON object is being passed to it via a webhook from GitHub with pull request information.

Problem:
 - If the JSON payload path results in an array or an object, the pipeline **silently** fails and stops the incoming webhook from triggering my build at all, which is not reasoned or listed anywhere, but found through trial and error. This does not happen if the result from the JSON path is a single value.

Steps to Reproduce:
 - Create a [simple yaml Azure Devops pipeline that uses a webhook resource to trigger the build](https://learn.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update#generic-webhook-based-triggers-for-yaml-pipelines) with a filter for closed PR only. (Though I suppose it doesn't matter here)
 - Create incoming service connection in ADO.
 - Configure Github webhook that sends pull_request events to this endpoint.
 - To see the issue, reference the object as:
   - `pr_labels: '${{ parameters.GithubPRClosed.pull_request.url }}'` which will work as it is a single value - pipeline runs will be triggered.
   - `pr_labels: '${{ parameters.GithubPRClosed.pull_request.labels }}` which will **NOT** work as the value is an array, pipeline runs will no longer be triggered.
   -  `pr_labels: '${{ parameters.GithubPRClosed.pull_request }}` which will **NOT** work as the value is an object, pipeline runs will no longer be triggered.

AFAIK I haven't missed anything obvious here, but please correct me if I have, as I've been working through all the other finicky issues with incoming service connections in ADO to get to this point.

**Comment by WilliamAntonRohm** [comment]
@reespozzi -- Rees,  thank you for your thorough feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by reespozzi** [comment]
@WilliamAntonRohm Hi - thanks for your response. I believe there's still some value to be added to the docs here. I got a reply in the developer community that when wishing to access anything other than a simple value from the incoming webhook, i.e an object or an array, I should use [convertToJson](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#converttojson). 

That resolved my particular issues, but the underlying problem remains I think - there is no documentation nor error within Azure DevOps to tell you this is an issue, the pipeline simply stops triggering, I only found out through trial and error. This is an obvious solution to the problem, once you know what's happening behind the scenes.

A one line addition to the documentation that the pipeline will not respond to incoming webhooks if you are attempting to access a JSON path that returns a complex object would help in my opinion and save time for others in the future.
Is there an FAQ / Troubleshooting guide this could be added into?

**Comment by reespozzi** [comment]
@WilliamAntonRohm just pinging again for visibility

**Comment by WilliamAntonRohm** [comment]
@Sid-ah, @chcomley -- Sidi or Chrystal, could you help with the documentation aspect here, or recommend someone who might?

**Comment by chcomley** [comment]
@ramrajesh can you help direct us to a SME please?

**Comment by WilliamAntonRohm** [comment]
#assign:@ramrajesh

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
