### ISSUE TITLE
Namespace is "Git Repositories", not "GitRepositories"

### ISSUE THREAD

**Issue by jeffrey-chongsathien-oxinst** [MicrosoftDocs/azure-devops-docs#13491]
The namespace includes a space between "Git" and "Repositories", as verified by inspecting the output of 

`az devops security permission namespace list`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d00cf58-20bf-036d-fa90-ab652a4553c0
* Version Independent ID: 982b9e56-62b7-673d-7f76-45b6e277d584
* Content: [Namespace reference - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/security/namespace-reference?view=azure-devops#analytic-views-namespace)
* Content Source: [docs/organizations/security/namespace-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/namespace-reference.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@chcomley -- Chrystal, please look into this issue.  None of the other namespace names include a space.
