### ISSUE TITLE
Incorrect permission specified for "Can create a team dashboard"

### ISSUE THREAD

**Issue by jeffrey-chongsathien-oxinst** [MicrosoftDocs/azure-devops-docs#13495]
Through experimentation (changing the user interface control and examining the effect on a default project team's permissions), I have not only reverse engineered the undocumented token format:

$/PROJECT_ID/TEAM_ID

but found that the permission for "Can create a team dashboard" (as presented in a project team's settings "Create dashboards")

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/90783201/c879734e-4ac1-42bb-a455-e2d8aa662ea4)

is "Create", not "MaterializeDashboards" as currently documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [Permissions, security groups, and service accounts reference - Azure DevOps](https://learn.microsoft.com/en-gb/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#dashboard-permissions)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for your feedback, we're glad you caught this! The updated article will publish shortly. Thanks again!
