### ISSUE TITLE
Image needs to be updated

### ISSUE THREAD

**Issue by sanjeev40084** [MicrosoftDocs/azure-devops-docs#13499]
I think it is about time the images from this page gets updated. Most or all of the screenshots are from old UI. 
https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops&preserve-view=true#create-an-azure-resource-manager-service-connection-using-automated-security
```[tasklist]
### Tasks
```

**Comment by sanjeev40084** [comment]
hmm.the issue is still there not sure why this issue is getting fixed.

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).

**Comment by sanjeev40084** [comment]
@juliakm how can i track the progress on this task in future?
