### ISSUE TITLE
Make it clear that the "Settings" and "Maintenance History" tabs are ONLY available when accessing the Pipelines view through the Organization and not through a Project

### ISSUE THREAD

**Issue by aurentzt** [MicrosoftDocs/azure-devops-docs#13490]
[Enter feedback here]
Please ensure it is clear that the "Settings" and "Maintenance History" tabs are ONLY available when accessing the Pipelines view through the Organization and not through a Project.

For example https://sampleorg.visualstudio.com/sampleproject/_settings/agentqueues will show all the queues but the noted tabs are not shown.

However, viewing the same Agent pools at https://sampleorg.visualstudio.com/_settings/agentpools will show the tabs in question.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Create and manage agent pools - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#what-is-a-maintenance-job)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/pools-queues.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
I will update that and it should be live today. Thank you for letting us know.
