### ISSUE TITLE
Add in section about the schedules display tab in Azure Devops only shows 7 days or increase the diplay time.

### ISSUE THREAD

**Issue by KeysAU** [MicrosoftDocs/azure-devops-docs#13492]
If I am to set my cron schedule to 0 0 1 * * (Run once a month) below and commit my yaml to azure devops repo. If the next execution time is more than 7 days away, I cannot easily verify the scheduled run on the website. Confirming it's scheduled to be run.

Can either the schedule page be updated to display all scheduled runs or add in some documentation to say that it only shows 7 days. 

I should be able to verify the pipeline is scheduled at the right time and the right date. 
Without displaying anything I get the impression that it's failed to read my schedule.

Schedule (I've listed a 0 0 * * *) so it shows 7 days as an example.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/38932932/0920d736-0a0f-47a9-944b-e50f79b71b08)

If I am to set this to 1 month - '0 0 1 * *', which is greater than 7 days from now. It does not show anything, as the next schedule time is greater than 7 days.

Yaml:
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/38932932/5b80797a-7364-4f45-910b-db8602a041c1)

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/38932932/9a6e34cb-117a-4d2e-a0ad-dc444c4f5aa1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://learn.microsoft.com/en-gb/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/scheduled-triggers.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@KeysAU -- Keith, thank you for your thorough feedback.  For the product-related suggestions, please add them here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

@steved0x -- Steve, please look into the possible documentation aspects of this issue.

**Comment by steved0x** [comment]
Thank you for letting us know. I can verify this and I have added a note to the documentation to indicate this, which will be live later today. To file a feature request to increase the scheduled runs view interval for longer than 7 days, please file a feature request here: https://developercommunity.visualstudio.com/AzureDevOps
