### ISSUE TITLE
"Markdown syntax for files, widgets, and wikis" HighlightJS version is very out of date

### ISSUE THREAD

**Issue by EmilDamsbo** [MicrosoftDocs/azure-devops-docs#13500]
This article specifies that Azure DevOps consumes highlightjs v.9.10.0:

> Set a language identifier for the code block to enable syntax highlighting for any of the supported languages in **[highlightjs](https://github.com/highlightjs/highlight.js/tree/9.10.0/src/languages), version v9.10.0**.

I see that this paragraph was changed in #5350, But this version is very old, 6+ years in fact, surely a newer version is used? 
https://github.com/highlightjs/highlight.js/releases/tag/9.10.0

Can you check with the engineering team that this information is up to date? Uptaking newer versions of HighlightJS would help provide highlighting for newer languages which weren't supported in v9.10.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @EmilDamsbo, thanks for your feedback. I've confirmed that we're still using version 9.10.0 of highlight.js. I see that the current version of highlight.js is 11.9.0. If you're interested, I'd recommend upvoting this suggestion here: https://developercommunity.visualstudio.com/t/Upgrade-Highlightjs-to-improve-code-hig/1391368?q=highlightjs
