### ISSUE TITLE
Add indication that GitHub Advanced Security for Azure DevOps is still in preview

### ISSUE THREAD

**Issue by kimjamia** [MicrosoftDocs/azure-devops-docs#13531]
The page doesn't mention anywhere that the feature is in preview and because of that the Advanced Security toggle under Project Settings > Repositories might not even appear. The [marketing page](https://azure.microsoft.com/en-us/products/devops/github-advanced-security) says the feature is in preview but even that doesn't say that you might not be able to see the feature.

It might also be useful to even more explicitly say that GitHub or GitHub Enterprise is not needed because at least Azure Support responded to me that I would need GitHub Enterprise to use this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Version Independent ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Content: [Configure GitHub Advanced Security for Azure DevOps features - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml)
* Content Source: [docs/repos/security/configure-github-advanced-security-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/configure-github-advanced-security-features.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks, I'll make it clearer that this feature is in public preview. We tried to make it clear that you don't need GitHub Enterprise with this purple note. We appreciate your feedback!

![Screenshot 2023-08-07 at 3 13 24 PM](https://github.com/MicrosoftDocs/azure-devops-docs/assets/64906/3f840ec1-ea65-4c59-856c-11adac0d7896)
