### ISSUE TITLE
Azure DevOps linux selfhosted agent offline update - documentation for linux path

### ISSUE THREAD

**Issue by stephane-julien** [MicrosoftDocs/azure-devops-docs#13545]
Please adjust the chapter https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops-2022#can-i-update-my-agents-that-are-part-of-an-azure-devops-server-pool step 2 with the linux folder and not the Windows one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a88243c7-cbb2-a735-5bf0-d2cd8d4384fe
* Version Independent ID: a88243c7-cbb2-a735-5bf0-d2cd8d4384fe
* Content: [Deploy an Azure Pipelines agent on Linux - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops-2022)
* Content Source: [docs/pipelines/agents/linux-agent.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/linux-agent.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@stephane-julien It looks like it is `usr/share/Microsoft/Azure DevOps/Agents` - let me verify this and I'll get the article updated.
