### ISSUE TITLE
Change Azure DevOps Services Resource Group

### ISSUE THREAD

**Issue by marck-s** [MicrosoftDocs/azure-devops-docs#13540]
While looking through the [documentation to change resource groups](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription) I was directed to the specific [Azure DevOps Services page](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops&toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json). This page however only mentions changes to the subscription and did not describe limitations or procedures to change the resource group.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 035f6441-6e6f-8ba3-a866-3f417e9ae223
* Version Independent ID: 2f7efb64-7db0-e45d-aaab-1d878a13da8b
* Content: [Change Azure subscription used for billing - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops&toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/change-azure-subscription.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @marck-s thanks for bringing this to our attention. I've added a sentence to the intro, along with a link to more information about how [changing resource groups isn't supported.](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#q--can-i-move-between-resource-groups--)
