### ISSUE TITLE
Azure Pipelines YAML arrays

### ISSUE THREAD

**Issue by matthew25187** [MicrosoftDocs/azure-devops-docs#13553]
Why is the use of arrays in Azure Pipelines YAML so poorly documented?  I only discovered there even was an array index syntax for these arrays quite by accident when reading this line from one of the examples:
`- script: echo ${{ replace(split(resourceId, '/')[8], '-', '_') }}_${{ env }}`

I'm assuming the "`[8]`" is a reference to a specific array element because there is not one mention elsewhere on the page that this syntax is an array index nor in any other article on Microsoft's web site can I find any mention of array indexes for Pipelines YAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
The product team says that if the value returned is an array, normal indexing rules apply. The [C# Indices and ranges 
 page](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/ranges-indexes) may be a useful reference. I'll add a note to this page as well.
