### ISSUE TITLE
Azure DevOps Office integration was working but now it stopped

### ISSUE THREAD

**Issue by hunyu** [MicrosoftDocs/azure-devops-docs#13552]
[Enter feedback here]
Technical background - Only apply the case where Azure DevOps Office integration was working but now it stopped

AAD determined the existing refresh token we store in User service (bound to the user) is no longer valid and that caused the user "forced sign-out" requiring any authentication token presented to server must be newer after the force sign-out (which is to make the user go through sign-in process again). And the AAD access token used in Excel integration appeared a long-living one so it kept get rejected by server.

The precise impact for the user is - on the same client machine s/he won't be able to connect to same organization using Excel, until the token naturally expiring and getting a new one. In the web the user will be redirected back to sign-in page as well but s/he might not even notice that and just sign-in again.

User can force resetting access token by clear out %LOCALAPPDATA%\.IdentityService

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c6dd3-d2d2-0d41-9958-d3f7d85b5c05
* Version Independent ID: e5e4a28f-30b8-0dab-b94b-d94fe6d341fe
* Content: [Resolve common Azure DevOps Office integration issues - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/office/tfs-office-integration-issues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/office/tfs-office-integration-issues.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@hunyu -- Hung-Chun, thank you for your detailed feedback.

@chcomley -- Chrystal, please look into this issue.

**Comment by hunyu** [comment]
If needed I can provide the DTS number and Developer who worked on the issue. I just didn't want to post those info on the public forum.

Hung-Chun Yu
***@***.******@***.***>
DevOps Customer Service & Support

My working hours are Monday to Friday 9am-6pm PST
If you need assistance outside of my working hours, please call and request to work with the next available engineer:

Our Premier Support line may be reached 24x7 at 1-800-936- 3100
Our Government Premier Support Number is 1-800-936-3200
Our Professional Support Number 1-800-936-5800
Providing excellent support is my primary objective.
Feel free to reach out to my manager to provide feedback:
Gary Ranne, ***@***.******@***.***>
For devops escalations please contact stacy gray
Stacy Gray, ***@***.******@***.***>

**Comment by chcomley** [comment]
@hunyu, I've reached out to our PM and will be in touch soon. Thank you!

**Comment by danhellem** [comment]
We updated the docs recently that speaks to this issue. Above cleaning out the ```%LOCALAPPDATA%\\IdentityService```, we don't expect to do any more with it.
