### ISSUE TITLE
This page is referencing a mostly abandoned WIQL marketplace addon.  Suggest revision

### ISSUE THREAD

**Issue by jamessammons** [MicrosoftDocs/azure-devops-docs#13566]
The tool references for the WIQL appears to be abandoned and recent reviews are not favorable.  What is Microsoft's position on extending this capability to users without this addin and without requiring development experience?  

https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@jamessammons -- Jim, thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
