### ISSUE TITLE
Is it an error to reference a nonexistent property of a parameter of type object?

### ISSUE THREAD

**Issue by ed-randall-blk** [MicrosoftDocs/azure-devops-docs#13564]
Consider this parameter:
  - name: my_param
    type: object
    default:
      a: false
      b: false
      c: false

Is it an error to check for a nonexistent object property `d`:
`${{ parameters.my_param.d }}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/runtime-parameters.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@ed-randall-blk -- Ed, thank you for your question.  I'm not sure, and I don't currently have the environment to test it.  Please try that statement and let me know the results.

**Comment by ed-randall-blk** [comment]
It seems OK.
The pipeline will blow up if I try to reference a non-existent top-level parameter, ie.
`${{ parameters.nonexistant }}`
but for my specific case it's fine to reference
`${{ parameters.m_param.nonexistant }}`
and the value just comes back empty.

```
parameters:
  - name: param4
    type: object
    default:
      aaa: true
      bbb: false
      ccc: 333
      ddd: 'text'

stages:
  - stage: StageA
    displayName: Stage one
    jobs:
      - job: JobA_1
        steps:
          - checkout: none
          - bash: |
              set -x
              p4a='${{ parameters.param4.aaa }}'
              p4b='${{ parameters.param4.bbb }}'
              p4c='${{ parameters.param4.ccc }}'
              p4d='${{ parameters.param4.ddd }}'
              p4e='${{ parameters.param4.eee }}'
              echo "p4a = [${p4a}]"
              echo "p4b = [${p4b}]"
              echo "p4c = [${p4c}]"
              echo "p4d = [${p4d}]"
              echo "p4e = [${p4e}]"
            displayName: 'Test object param4'
```

works fine, output:
```
p4a = [True]
p4b = [False]
p4c = [333]
p4d = [text]
p4e = []
+ p4a=True
+ p4b=False
+ p4c=333
+ p4d=text
+ p4e=
+ echo 'p4a = [True]'
+ echo 'p4b = [False]'
+ echo 'p4c = [333]'
+ echo 'p4d = [text]'
+ echo 'p4e = []'
```

Even if I blank-out all the attributes aaa, bbb, ccc, ddd at run/launch it still works fine, they are just blanked as expected:
```
p4a = []
p4b = []
p4c = []
p4d = []
p4e = []
```

**Comment by WilliamAntonRohm** [comment]
@ed-randall-blk -- Ed, thank you for your well-researched followup.

@juliakm -- Julia, please look into this issue.

**Comment by ed-randall-blk** [comment]
I'm happy that it works correctly and unsurprisingly right now.
I only raised as it appears to be a small gap in the documentation.  Thanks!
