### ISSUE TITLE
Small tweak to documentation

### ISSUE THREAD

**Issue by jbruneFei** [MicrosoftDocs/azure-devops-docs#13576]
> You can't perform certain functions on work items whose WITs belong to the [Hidden Types Category](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/agile-glossary?view=azure-devops#hidden-types).

It might be nice to document what a _WIT_ is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca74dfe-b281-987f-ca06-0ed3e51aa8d6
* Version Independent ID: 3b36bca7-53ae-655f-f836-581b893c813b
* Content: [Edit user stories and other work items in bulk in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/bulk-modify-work-items?view=azure-devops#edit)
* Content Source: [docs/boards/backlogs/bulk-modify-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/bulk-modify-work-items.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@jbruneFei -- Jonathan, thank you for your feedback.  WIT is an acronym for "work item type"; please see [Fields](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/agile-glossary?view=azure-devops#fields).

I am updating this article for clarification.

**Comment by WilliamAntonRohm** [comment]
@jbruneFei -- Jonathan, I added the following link in that paragraph; it should be live by tomorrow:
- [work item types (WITs)](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items)
