### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by NigeAtAnd** [MicrosoftDocs/azure-devops-docs#13579]
This page would benefit from examples on how to access these system variables from a YAML script. This is different from the examples already given on the [Define Variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables) page.

Specifically, nowhere does it state that `variables['variable_name']` must be used. The implication is that the variable can be accessed directly as `variable_name`, which is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@NigeAtAnd Thanks for your feedback. You might find our [Set variables in scripts](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash) or [Predefined variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables) articles helpful. I'll make the links clearer to these articles from the Define variables page.
