### ISSUE TITLE
The suggested extension does not work on modern versions of visual studio. 

### ISSUE THREAD

**Issue by jeffersoneagley** [MicrosoftDocs/azure-devops-docs#13577]
The suggested extension (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.msdevlabs-pte) does not work on modern versions of visual studio. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79a9c3fe-7f7a-6050-cc6b-79b1882478c0
* Version Independent ID: 7680f29b-c977-0c83-bbd5-c9ed35372527
* Content: [witAdmin Customize and manage objects for tracking work - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=azure-devops)
* Content Source: [docs/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @jeffersoneagley, I've removed the reference to that extension.
