### ISSUE TITLE
Details are missing regarding no notification when Azure AD group is specified for "Approvers"

### ISSUE THREAD

**Issue by miezure** [MicrosoftDocs/azure-devops-docs#13572]
As described in the following page, users in an Azure AD group specified as "Approvers" in "Pre-deployment approvals" are not notified. 
https://developercommunity.visualstudio.com/t/AAD-Groups-within-Azure-DevOps-groups-ar/1329414

However, this [document](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=azure-devops#pre-deployment-approvals) lacks the description of this known limitation. In addition, since the diagram in the document specifies an Azure AD Group, users expect that each member of AAD Group specified as Approvers will be notified, but they won't receive. So, I think this known limitation should be explained in this document to avoid confusion.
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/12386833/49f70900-c835-4ff8-9f04-3578703c97bb)

The related pull request is below.
https://github.com/MicrosoftDocs/azure-devops-docs/pull/13571

**Comment by ramiMSFT** [comment]
@miezure Thanks for your feedback! I'll get that updated
