### ISSUE TITLE
Questionable best practice to put public upstreams first

### ISSUE THREAD

**Issue by san7hos** [MicrosoftDocs/azure-devops-docs#13574]
> Place public upstreams FIRST in your resolution order:
> 
> This prevents other sources from overriding well-known packages with altered or incompatible versions.

I would argue that this practice makes you vulnerable towards overriding packages from your private feeds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d577f56d-c16e-dde5-68c3-81ee879c7c4d
* Version Independent ID: 0592e0da-1667-9ec7-60a8-d813477cba30
* Content: [Best practices when working with Azure Artifacts - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=azure-devops)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/concepts/best-practices.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jorfde any updates on the suggestions we discussed?

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
