### ISSUE TITLE
General Availability of templates support in YAML editor - Not available for Server but shown as such

### ISSUE THREAD

**Issue by Christ0phH** [MicrosoftDocs/azure-devops-docs#13584]
[Enter feedback here]

The documentation for "General Availability of templates support in YAML editor" and its availability for Azure DevOps Server (2019+2022) is misleading because its simply not released yet for 2022 (and wont ever be released to 2019)
[Reference](https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline-released) -> 12 Jan 2023: General Availability of templates support in YAML editor | Area: Pipelines | Server: Future

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3e0c4d-0102-cb51-1794-f8569009aa5b
* Version Independent ID: 17f843b2-c55c-0bd7-dadf-1c5e16908783
* Content: [YAML pipeline editor guide - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor?view=azure-devops-2022)
* Content Source: [docs/pipelines/get-started/yaml-pipeline-editor.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/yaml-pipeline-editor.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Christ0phH Sorry for the delay in responding to this issue. You are correct, this area of the article was incorrectly marked to support Azure DevOps Server 2022. I am updating that today. That feature has released in Azure DevOps Server 2022.1, so I have added a note to clarify that. These changes will be live today. Thank you for letting us know.
