### ISSUE TITLE
Documentation of upstream behavior does not apply to Azure DevOps Server 2020

### ISSUE THREAD

**Issue by OronDF343** [MicrosoftDocs/azure-devops-docs#13591]
None of the settings mentioned in the article exist in Azure DevOps Server 2020, however it claims to apply to TFS 2018 , Azure DevOps Server 2020-2022,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb8c20-fe29-a60c-dd6c-45c9e8278162
* Version Independent ID: ca24cdd8-dc94-6339-e2ef-95e5a84fa877
* Content: [Configure upstream behavior - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-behavior?view=azure-devops-2020&tabs=nuget%2Cget)
* Content Source: [docs/artifacts/concepts/upstream-behavior.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/concepts/upstream-behavior.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@OronDF343 Thank you for your feedback! Allowing externally-sourced packages is currently available only in Azure DevOps Services. However, we've recently pushed an update, so this feature will be available in the next release of Server 2022. I'm updating the docs shortly.
