### ISSUE TITLE
Deployment jobs on self-hosted agents not incrementing workspace?

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-devops-docs#13608]
Hey,

it seems there was a change in how deployment jobs on self-hosted agents use work spaces. Apparently they no longer create new workspaces for each run and reuse the same workspace. This causes issues in our pipelines and we have to clean the workspace for each run.

To clarify, what we are trying to do:
* Run a deployment job on a self-hosted agent where we download a build artifact and then deploy the zip file to IIS
* Run the same deployment job again

Expected result:
* The artifact from the first run is downloaded to \azagent\\_work\1
* The artifact from the first run is downloaded to \azagent\\_work\2

Actual result:
* Both artifacts are downloaded to \azagent\\_work\1 causing us problems

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/deployment-jobs.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@RobinZergiebel -- Robin, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

cc @juliakm for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by RobinZergiebel** [comment]
Hey @WilliamAntonRohm,

I agree that this is mostly a product and not a documentation question.
But is this difference documented somewhere? If not, it should be!

Cheers,
Robin

**Comment by WilliamAntonRohm** [comment]
@RobinZergiebel -- Robin, thank you for your follow-up.

@juliakm -- Julia, please look into this issue.

**Comment by juliakm** [comment]
@RobinZergiebel I'll reach out to the product team about this. I would suggest also posting in the [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps), which is actively monitored by the product and support teams.

**Comment by juliakm** [comment]
@RobinZergiebel It looks like you have a support issue for this too. I checked with the product team and they say to please follow-up with them.
