### ISSUE TITLE
Windows Docker Image Does not Work

### ISSUE THREAD

**Issue by ASHR4** [MicrosoftDocs/azure-devops-docs#13609]
The code supplied within the Windows Dockerfile pulls the manifest file from the artefacts repository rather than an actually container image causing the docker build to fail.

Can I suggest to use:

```
FROM  mcr.microsoft.com/windows/servercore:ltsc2019-amd64

WORKDIR /azp

COPY start.ps1 .

CMD powershell .\start.ps1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-azure-kubernetes-service-cluster)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/docker.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by eashenden** [comment]
thank you!!! 2019-amd64 works just fine for now

When I use the code provided (mcr.microsoft.com/windows/servercore:ltsc2022) I get `no matching manifest for windows/amd64 10.0.19045 in the manifest list entries`

When I use mcr.microsoft.com/windows/servercore:ltsc2022-amd64 I get `a Windows version 10.0.20348-based image is incompatible with a 10.0.19045 host`

**Comment by WilliamAntonRohm** [comment]
@eashenden -- Eric, thank you for your follow-up.

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
This is fixed with an internal PR to the following:
```
    FROM mcr.microsoft.com/windows/servercore:ltsc2022

    WORKDIR /azp/

    COPY ./start.ps1 ./

    CMD powershell .\start.ps1
```

Please open a new issue if this doesn't resolve the issue for you.
