### ISSUE TITLE
Keyboard shortcuts don't work from dev.azure.com.

### ISSUE THREAD

**Issue by Rikulf** [MicrosoftDocs/azure-devops-docs#13610]
The keyboard shortcuts work fine from mycompany.visualstudio.com. Very few work from dev.azure.com/mycompany.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Keyboard shortcuts for web portal and Team Explorer - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/navigation/keyboard-shortcuts.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@Rikulf -- Darryl, thank you for your feedback.  Please provide some examples.

@chcomley -- Chrystal, please look into this issue.

**Comment by Rikulf** [comment]
@WilliamAntonRohm, @chcomley -- I can't much beyond up and down to work. For example, if I go to a board, I get no response if I type "?" to bring a list of keyboard shortcuts. Ctrl-Home and Ctrl-End have no effect on work items.

**Comment by chcomley** [comment]
Hi @Rikulf, I'm so sorry for the delay here. You might have moved on already, but for what it's worth, I've tried to repo what you were experiencing, and it all works fine for me in dev.azure.com, including "?", Ctrl-Home, and Ctrl-End. If you're still experiencing this issue, be aware of the following:

- **Browser Compatibility:** Ensure that you’re using a supported browser. Azure DevOps works best with modern browsers like Google Chrome, Mozilla Firefox, or Microsoft Edge. If you’re using an older or less common browser, some features (including keyboard shortcuts) may not function correctly.
- **Focus and Input Control:** Keyboard shortcuts typically work when the focus is not on an input control (like a text box). If you’re actively typing in a comment or editing a field, the shortcuts might not respond. Try clicking outside any input fields and then use the shortcuts.
- Get support on the [Developer Community](https://developercommunity.visualstudio.com/home).

Thank you and have a great day.

**Comment by Rikulf** [comment]
Hi chcomley, I noticed a few months ago that your team fixed this issue.
Thank you for following up.

@Rikulf
