### ISSUE TITLE
There are footnote markers with no actual footnotes on the page

### ISSUE THREAD

**Issue by robbiesollie** [MicrosoftDocs/azure-devops-docs#13628]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6859c579-3383-e4b7-366e-69f49a8bd1b6
* Version Independent ID: 5b7af784-0698-b77a-342f-252986038e92
* Content: [Query by title, ID, or rich-text fields in Azure Boards and Azure DevOps - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/titles-ids-descriptions?view=azure-devops)
* Content Source: [docs/boards/queries/titles-ids-descriptions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/titles-ids-descriptions.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@robbiesollie -- thank you for your feedback.  Please see the Note at the end of this section:
- [Supported operators and macros](https://learn.microsoft.com/en-us/azure/devops/boards/queries/titles-ids-descriptions?view=azure-devops#supported-operators-and-macros)
