### ISSUE TITLE
Build Validation Not Triggered, because the PR source branch missing the pipeline code. 

### ISSUE THREAD

**Issue by jijeeshme** [MicrosoftDocs/azure-devops-docs#13626]
Hi, 
I have an issue scenario as explained below: 
Tool: Azure DevOps Service with Windows Agent 
1. Created a build validation YAML pipeline (build-validation.yml) in the 'dev' branch 
2. Set up the Build validation in the repo branch policy for 'dev' branch, it worked for every PR merge to dev branch. 
3. I have created a feature branch out of my 'master' branch 
4. Set up the Build validation in the repo branch policy for 'master' branch, similar to the 'dev' branch policy. 
5. The build validation trigger for the PR merge from feature branch to 'master' is not working. 
6. When I copied the  YAML pipeline (build-validation.yml) file to the 'feature' branch, the trigger started working. 
7. My concern is that:

- The pipeline is configured based on the YAML code which is in the dev branch. However, the build validation execution expects the pipeline code present in the PR source branch, which is not correct. 
- It’s an unreliable build validation process as the pipeline code is based on the PR source branch code. 

Hope this need a fix unless there is a strong reason to support the current behavior. 

Thanks,
Jijeesh 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47abb6d4-0fe9-ddd2-f48b-31fdc040eb7f
* Version Independent ID: a65b02a0-9885-c0e0-b829-e2e66aabbd91
* Content: [Git branch policies and settings - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/branch-policies.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@jijeeshme -- Jme, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
