### ISSUE TITLE
Enable GitHub Advanced Security option is missing from our Repos

### ISSUE THREAD

**Issue by simonpooley** [MicrosoftDocs/azure-devops-docs#13625]
Hi,

Now that GitHub Advanced Security is in public preview I wanted to enable it for my organisation.

I am following the instructions here:
https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml#enable-github-advanced-security

The Advanced Security option is missing entirely. Apologies I can't see how to easily add a screenshot.

Our repo is Git, and we have set up a billing method.

Why is the feature missing and how do we enable it? Could the documentation be updated to reference this scenario?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Version Independent ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Content: [Configure GitHub Advanced Security for Azure DevOps features - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml)
* Content Source: [docs/repos/security/configure-github-advanced-security-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/configure-github-advanced-security-features.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by thom-bringme** [comment]
I'm facing the exact same problem.
The Advanced Security option is missing entirely and I am definitely a member of the Project Collection Administrators group.

**Comment by juliakm** [comment]
@thom-bringme and @simonpooley I believe that you should see the feature even if you can't turn it on. I wonder if it hadn't rolled out yet to your organization. For reference, here's what it looks like when you can't turn on the feature. If you still can't see it, I'd reach out to [support](https://learn.microsoft.com/azure/devops/user-guide/provide-feedback?view=azure-devops). 

![Screenshot 2023-10-10 at 10 42 05 AM](https://github.com/MicrosoftDocs/azure-devops-docs/assets/64906/b4227ae3-8806-4470-ac46-7f943434ebcb)
