### ISSUE TITLE
Mistake in git workflow

### ISSUE THREAD

**Issue by RevathiShanmugam** [MicrosoftDocs/azure-devops-docs#13630]
[The following point in Git workflow should be reworded. "[Complete your pull request](https://learn.microsoft.com/en-us/azure/devops/repos/git/complete-pull-requests?view=azure-devops) and resolve any merge conflicts from changes other people made after you created your branch.". Developer should resolve merge conflicts and then complete the PR]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8bd7564-1e42-4cb2-3d2c-cf05095a2750
* Version Independent ID: 3c7948f2-3df4-5197-6924-39c472c09d10
* Content: [Azure Repos Git tutorial - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/gitworkflow?view=azure-devops)
* Content Source: [docs/repos/git/gitworkflow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/gitworkflow.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ramiMSFT** [comment]
@RevathiShanmugam Thanks for you feedback! Updating this shortly
