### ISSUE TITLE
Was ever is not in options for board column in queries

### ISSUE THREAD

**Issue by rrobertsor** [MicrosoftDocs/azure-devops-docs#13646]
Hi William
I am seeing something different. Noticeably the different reference to type of query: 
My screen says "My queries" yours says "Custom Queries"
Though the options appear the same in screen. Does that make a difference?
As you can see on the screenshot here, when I select board column and type was there is no operator for was it shows nothing. And if I just go through the list, it shows nothing. 
What could be restricting this?
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/336267ba-f7ac-4238-b629-35f6c311e579)

_Originally posted by @rrobertsor in https://github.com/MicrosoftDocs/azure-devops-docs/issues/13641#issuecomment-1723521143_

**Comment by WilliamAntonRohm** [comment]
Follow-on issue from #13641 -- returning this discussion to there
