### ISSUE TITLE
The string for Board Column was ever, does not work in queries. How can I get that to work in ADO?

### ISSUE THREAD

**Issue by rrobertsor** [MicrosoftDocs/azure-devops-docs#13641]
I've tried to use the query string for "Board Column was ever..." and it doesn't have was ever as an option. Am I doing something wrong? 
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/c8750abb-f130-43ad-bdd9-b43827922df7)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8acd801-cb9c-fa87-b4a7-5a44094bbd00
* Version Independent ID: e471c7e6-2ace-9029-ae22-62f1725168fa
* Content: [Query by account, user, workflow, or board changes in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/query-by-workflow-changes?view=azure-devops)
* Content Source: [docs/boards/queries/query-by-workflow-changes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/query-by-workflow-changes.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@rrobertsor -- thank you for your question.  "Was ever" is showing in my list of options for Board Column:

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/27738025/f5f0f136-1c89-4c1d-b851-4dda11cb6288)

I'm not sure how your situation may be different.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by rrobertsor** [comment]
> @rrobertsor -- thank you for your question. "Was ever" is showing in my list of options for Board Column:
> 
> ![image](https://user-images.githubusercontent.com/27738025/268434456-f5f0f136-1c89-4c1d-b851-4dda11cb6288.png)
> 
> I'm not sure how your situation may be different.
> 
> I am closing this issue now. You are welcome to @ mention me for any followup. We hope to hear from you again.

Hi William
I am seeing something different. Noticeably the different reference to type of query: 
My screen says "My queries" yours says "Custom Queries"
Though the options appear the same in screen. Does that make a difference?
As you can see on the screenshot here, when I select board column and type was there is no operator for was it shows nothing. And if I just go through the list, it shows nothing. 
What could be restricting this?
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/336267ba-f7ac-4238-b629-35f6c311e579)

**Comment by rrobertsor** [comment]
What I see are these options: 
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/5b2b11a1-278b-4370-8cb2-b630fbf3fbfa)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/32f66041-e914-4b56-b919-bcf962830aaf)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/145143470/eed4a54b-cbf5-433e-afaa-25ce6d8d3cd0)

**Comment by chcomley** [comment]
Hi @rrobertsor, I'm sorry for the delay here. I've reached out to our product group and will get back to you as soon as I hear from them. Thanks!

**Comment by chcomley** [comment]
Hi @rrobertsor, this is a bug in the New Boards Hub, which is now on by default. We've created an internal bug for our team to get it fixed! Thank you. Closing the issue, since it doesn't require an update to the article.
