### ISSUE TITLE
Understanding active committer count

### ISSUE THREAD

**Issue by segraef** [MicrosoftDocs/azure-devops-docs#13653]
Somehow the last part doesn't make sense to me, shouldn't it be 30 = 40 - 10 or just 30 ?
Or are you saying with having a second repository you get charged 30 + 10 = 40 ?
But then this wouldn't align with your statement " _... 10 of those 30 developers also committed to Fabrikam and don't consume more licenses._"

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/19261257/e7dded14-fd40-4218-9466-159856e42154)

To simplify my question, do you get charged via unique users for all repositories in your project or do you get charged per active and unique committer per each repository? If the latter then it's going to be quite expensive.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf1a4901-ad2d-e6d5-6d69-95d19c26e112
* Version Independent ID: cf1a4901-ad2d-e6d5-6d69-95d19c26e112
* Content: [Billing for GitHub Advanced Security for Azure DevOps - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-billing?view=azure-devops)
* Content Source: [docs/repos/security/github-advanced-security-billing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/github-advanced-security-billing.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by laurajjiang** [comment]
Hi @segraef - thanks for the issue. For Advanced Security on Azure DevOps, you are charged per active committer per repository you enabled, deduplicated across your organization. Meaning, I believe this simplifies down to being charged for unique active committers across all enabled repositories. 

In the above simplified example, Fabrikam has 20 active committers. In enabling AdventureWorks, a repo with 30 active committers, if we were not deduplicating you would be charged for 50 active committers. However, there is overlap between 10 of the committers in Fabrikam and AdventureWorks, so we still have the original 20 from Fabrikam and an additional 20 new, distinct active committers in AdventureWorks who have not committed at all to Fabrikam that will be billed for.  

Let me know if you have other questions.
