### ISSUE TITLE
Azure DevOps Pentest links not working

### ISSUE THREAD

**Issue by abymsft** [MicrosoftDocs/azure-devops-docs#13675]
[Enter feedback here]
The link to ADOs pen test reports is not working. 

<img width="428" alt="image" src="https://github.com/MicrosoftDocs/azure-devops-docs/assets/50873759/5c42fe82-32d5-4f96-a93c-677065cc1b26">

I get the below error when I sign-in with my Microsoft Id.

**`The document you are looking for is not available`**
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Data protection overview - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops#data-redundancy)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/data-protection.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@abymsft -- Abishek, thank you for catching this.  There are two links to the portal, only one of which is correct:
- [Microsoft Service Trust Portal](https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_SOC%20/%20SSAE%2016%20Reports).

I am updating the other instance.
