### ISSUE TITLE
Azure DevOps Web Extension guide is not working, as described.  Giving Error: azure-devops-extension-sdk SDK.min.js Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by maxg2k** [MicrosoftDocs/azure-devops-docs#13682]
Azure DevOps Web Extension guide is not working, as described.  Giving Error: 

```
azure-devops-extension-sdk SDK.min.js Uncaught ReferenceError: define is not defined
```
This issue is also reported to the the Support team. **Over a week has passed, but they are yet to respond back** 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/get-started/node.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@maxg2k -- thank you for your feedback.  Please follow up with the support team, as this repo is solely for documentation.
