### ISSUE TITLE
Add that 'Limit job authorization scope to current project' should be turned off

### ISSUE THREAD

**Issue by housten** [MicrosoftDocs/azure-devops-docs#13693]
When publishing from one project to another, in the same org, the relevant 'Limit job authorization scope to current project' needs to be turned off on the origination project - otherwise the system token is limited to that project. There is one for release pipelines and one for non-release pipelines.

You get to that setting from project settings / pipeline settings
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/14905544/8ea645cd-0893-4d21-8ed4-7f6491f3470a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://learn.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/feeds/project-scoped-feeds.md)
* Service: **azure-devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@housten Thanks for your feedback! I tested a couple of scenarios. I'm adding that to the docs

**Comment by ramiMSFT** [comment]
Hi @housten,  I'll be updating the docs to provide a more secure approach to accomplish this. Disabling the **Limit job authorization scope** is not the best security practice. The recommended approach is to configure both your downstream project and pipeline as follows:

On the pipeline generating the artifact (downstream project): select the ellipsis for more options > **Manage security** > search for your upstream project's build service and allow the following: **Update build information**, **View build pipeline**, and **View builds**.

On the downstream project: **Project Settings** > **Permissions** > **Users** > search for your upstream project's name and then select **Expand search** > select your upstream project's build service and allow the following: **View project-level information**.

**Comment by housten** [comment]
This isn't quite making sense to me. I am not using a pipeline in the 'upstream' project.

The build in Project_A builds, packages and pushes a Project_A repo's package to the feed in Project_Common.

Project_Common doesn't have a pipeline or process related to Project_A.

How would giving a build service in Project_Common viewing permissions in Project_A have any effect?
