### ISSUE TITLE
Poor security guidance to use Oauth?

### ISSUE THREAD

**Issue by webstandards** [MicrosoftDocs/azure-devops-docs#13707]
Hi! Why are new support pages being written directing people how to write their apps using Oauth? The legacy Oauth implementation in Azure DevOps is inherently insecure and represents a liability to any corporation using it due to the lack of any logging of the connection use giving no audibility. All other ADO authentication methods have basic security logging/audibility. We spoke directly to the ADO team lead Angel Wong and she told us she plans to deprecate the use of Oauth in ADO in favor of new more secure auth methods like managed identities, to which you should be strongly guiding developers to use instead of oauth connections.
Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorize access to REST APIs with OAuth 2.0 - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/get-started/authentication/oauth.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @webstandards, thanks so much for your feedback. I've also been in contact with Angel and she confirmed that they're planning to deprecate the use of Azure DevOps OAuth sometime in 2024. Have a great day.
