### ISSUE TITLE
Add Documentation Step for Resource Group Deletion after Migration

### ISSUE THREAD

**Issue by tareafina** [MicrosoftDocs/azure-devops-docs#13724]
Hi Team,
           Thanks for your time!

Would you please add as this extra step?

When you move your subscription to a new one, a new Resource Group is created into the new subscription and then the DevOps organization resource is moved to the new one.

Into the older subscription the resource group remains in there even after complete successfully the migration.

Would you please add into the documentation about that older resource group can be safety deleted or if it possible automatize the deletion operation of the older resource group?

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 035f6441-6e6f-8ba3-a866-3f417e9ae223
* Version Independent ID: 2f7efb64-7db0-e45d-aaab-1d878a13da8b
* Content: [Change Azure subscription used for billing - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/change-azure-subscription.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@tareafina -- thank you for your well-considered suggestion.

@chcomley -- please look into this issue.

**Comment by chcomley** [comment]
Thanks for the great suggestion, @tareafina! I've updated the FAQ article and linked to it from said article. Thanks again!
