### ISSUE TITLE
The provided sample wont work as it is: ERROR: SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by jonasta** [MicrosoftDocs/azure-devops-docs#13721]
After spending half a day I found the solution:

- 1st of all the problem is not clear at all: What happening is that the pipeline is **using an old node version (7 probably)** to run the extension - that's why modern syntax is not recognized
- SOLUTION: update your task.json file as per below:
```
"execution": {
    "Node16": {
      "target": "index.js"
    }
  }
```
This will make this and future problems that you would have to go away. 
reference: https://johnnyreilly.com/azure-pipelines-custom-pipelines-task-extension-node-16#migrating-a-task-to-nodejs-16

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#prerequisites)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you so much for this, @jonasta, I've updated the article (to go live shortly), so others don't have to search like you did. Thanks again!
