### ISSUE TITLE
painfully incomplete

### ISSUE THREAD

**Issue by djkingCanada** [MicrosoftDocs/azure-devops-docs#13738]
[Enter feedback here]

How do you know the URL that the app has been deployed to?  How do we know it is running?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfc7aa5-d9ff-ad64-d26e-d2bd10470025
* Version Independent ID: 9b4f02ea-dab9-f613-5345-496435ab2408
* Content: [Deploy a web app to Azure Web App for Containers - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=java%2Cyaml)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@djkingCanada -- Dave, thank you for your questions.  I believe you've seen our help resources in your previous issue.  Please consult them and let me know if they help answer.
