### ISSUE TITLE
Use UseNode@1 instead of NodeTool@0

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/azure-devops-docs#13748]
The YAML examples in the documentation should be updated to use `UseNode@1` instead of `NodeTool@0`.
Please update all relevant pages, e.g. the next page [Customize JavaScript for Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/customize-javascript?view=azure-devops) also contains `NodeTool@0`.

Related to https://github.com/MicrosoftDocs/azure-devops-yaml-schema/issues/239#issuecomment-1789493224

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f617d-59c1-f3d4-d322-88ae5301d9b2
* Version Independent ID: df0db0d1-21da-ce6f-1f74-34b4be1d9ff3
* Content: [Quickstart - Use Azure Pipelines to build and publish a Node.js package - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/javascript.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @cremor! I'll update the articles.

**Comment by cremor** [comment]
@juliakm Your commit 733f63823c1dd544da68a90ca35a8e13eedcb57f looks wrong. As far as I can tell there is no `NodeTool@1` task. It is called `UseNode@1`.

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please look into the previous comment's assertion.
