### ISSUE TITLE
The location to extract the CodeQL bundle to appears to be wrong

### ISSUE THREAD

**Issue by dstretch** [MicrosoftDocs/azure-devops-docs#13756]
The page says to extract the bundle as follows:

"Download and unzip the bundle to the following directory inside the agent tool directory, typically located under _work/_tool: ./CodeQL/0.0.0-[codeql-release-bundle-tag (i.e. codeql-bundle-v2.14.2)]/x64/"

The path I ended up needing to extract to was:

_work\_tool\codeql\0.0.0-codeql-bundle-v2.15.1\x64\codeql

...please note the additional \codeql folder at the end of the path.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Version Independent ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Content: [Configure GitHub Advanced Security for Azure DevOps features - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml#extra-prerequisites-for-self-hosted-agents)
* Content Source: [docs/repos/security/configure-github-advanced-security-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/configure-github-advanced-security-features.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @laurajjiang
* Microsoft Alias: **laurajiang**

**Comment by laurajjiang** [comment]
Hi @dstretch - thanks for the issue! You are correct that the contents of the bundle will need to land in `_work/_tool/codeql/0.0.0-codeql-bundle-v2.15.1/x64/codeql`.  

You should be able to unzip the contents into the parent directory of `_work/_tool: ./CodeQL/0.0.0-[codeql-release-bundle-tag (i.e. codeql-bundle-v2.14.2)]/x64/`, unpacking into its own `codeql` directory.
