### ISSUE TITLE
Replate 99+ with 3 digits on widget

### ISSUE THREAD

**Issue by jhwagemaker** [MicrosoftDocs/azure-devops-docs#13750]
When using the Lead and Cycle time widget for Epics (and sometimes also Features) they often exceed the 99 days. I would like to see the actual number of the result instead of 99+ by using 3 instead of 2 digits for the result. I think this would make a lot of users of this widget happy!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e813268-5e00-7c84-2479-3068e27ea443
* Version Independent ID: 269b0352-2a6a-d5c9-96a3-68d5ce93c616
* Content: [Cycle Time and Lead Time control charts - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops)
* Content Source: [docs/report/dashboards/cycle-time-and-lead-time.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/cycle-time-and-lead-time.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@jhwagemaker -- thank you for your suggestion.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
