### ISSUE TITLE
There two steps labeled step #3 

### ISSUE THREAD

**Issue by NinoCapo** [MicrosoftDocs/azure-devops-docs#13757]
There are 2 steps labeled step #3 in the "Configure managed identities and service principals" section of this document.  Its a bit confusing because some of the documentation is duplicated.  For example, there are two headers labeled "Get an Entra ID token"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Version Independent ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Content: [Use service principals & managed identities - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/service-principal-managed-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/get-started/authentication/service-principal-managed-identity.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @Wonga
* Microsoft Alias: **wonga**

**Comment by steved0x** [comment]
This will be fixed today. Thank you.
