### ISSUE TITLE
System.TaskDisplayName is not included

### ISSUE THREAD

**Issue by vanmash** [MicrosoftDocs/azure-devops-docs#13754]
A couple of useful variables are not included, for example 
`System.TaskDisplayName`
`System.TaskInstanceId`
`System.TaskInstanceName`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
This page is not a comprehensive list of variables. Some variables such as `System.TaskInstanceId` are primarily used internally and may change under some conditions.
