### ISSUE TITLE
Update email address confirmation

### ISSUE THREAD

**Issue by ratishkp** [MicrosoftDocs/azure-devops-docs#13763]
after the email address is updated, does it ask for confirmation to the new address or the old email address?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c94a78f-77de-a612-1fc8-749518195166
* Version Independent ID: fba4f685-1c59-e1e6-2138-aaa5477e476d
* Content: [Change your preferred notification email address - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/notifications/change-email-address?view=azure-devops)
* Content Source: [docs/organizations/notifications/change-email-address.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/notifications/change-email-address.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-notifications**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@ratishkp -- thank you for your question.  It's the new address.
