### ISSUE TITLE
Instructions about how to install extensions from the command prompt missing for on-prem setups

### ISSUE THREAD

**Issue by DennisL68** [MicrosoftDocs/azure-devops-docs#13765]
Instructions about how to install extensions from the command prompt missing for on-prem setups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4290c10-4f12-f4f2-a189-4395fbe5525b
* Version Independent ID: 41204723-bd4b-270d-f13f-df961c565ca9
* Content: [Install extensions - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops-2022&tabs=browser)
* Content Source: [docs/marketplace/install-extension.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/marketplace/install-extension.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @DennisL68, thanks for your feedback. I've updated the article, which should be live shortly. Thanks again and have a wonderful day!
