### ISSUE TITLE
Windows-2022 software link broken

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/azure-devops-docs#13789]
It appears that the Github repo documentation for the Windows build agent software has changed from `win` to `windows`. The current links to that documentation is broken now. The link needs to be updated to `https://github.com/actions/runner-images/blob/main/images/windows...` from `/images/win`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@CoolDadTx -- thank you for your feedback -- these links have been recently updated and they are working for me.
