### ISSUE TITLE
Windows info in the Linux specific doc

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/azure-devops-docs#13785]
There are Windows info in the Linux specific doc, like for instance:

* https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops#windows-only-startup
* https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops#check-if-the-windows-registry-key-is-recorded-and-saved-correctly
* https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops#check-if-windows-registry-keys-work-fine-on-your-machine

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a88243c7-cbb2-a735-5bf0-d2cd8d4384fe
* Version Independent ID: a88243c7-cbb2-a735-5bf0-d2cd8d4384fe
* Content: [Deploy an Azure Pipelines agent on Linux - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/linux-agent?view=azure-devops)
* Content Source: [docs/pipelines/agents/linux-agent.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/linux-agent.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@o-l-a-v -- Olav, thank you for catching this.

@steved0x -- Steve, please review the proposed changes in [private PR 6308](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/6308).

**Comment by steved0x** [comment]
@o-l-a-v Thank you for letting us know. I am removing this and this change will be live later today.
