### ISSUE TITLE
Wrong instructions for deleting a project wiki

### ISSUE THREAD

**Issue by bjorn-jarisch** [MicrosoftDocs/azure-devops-docs#13783]
The section "Delete project wiki" says to delete a project (not code) wiki using `DELETE .../wikis/{id}`, but that is not supported. Instead, the underlying repository must be deleted, see https://developercommunity.visualstudio.com/t/cannot-cancel-wiki-of-type-projectwiki/324195.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops#delete-project-wiki)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/provisioned-vs-published-wiki.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @bjorn-jarisch, I've addressed this in the article.
