### ISSUE TITLE
Broken links for windows and ubuntu.  Links are to GitHub and indicate what software is included in the images

### ISSUE THREAD

**Issue by billpieper** [MicrosoftDocs/azure-devops-docs#13788]
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

links to windows and ubuntu are broken in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by eriawan** [comment]
@WilliamAntonRohm 

Should this issue be closed? As of today, 11th December, those links to Windows and Linux agents are correct.

**Comment by WilliamAntonRohm** [comment]
@billpieper -- Bill, thank you for catching that.

@eriawan -- Eriawan, thank you for your followup.
