### ISSUE TITLE
Rust has now stabilized support for registry-auth

### ISSUE THREAD

**Issue by ronakj** [MicrosoftDocs/azure-devops-docs#13798]
https://learn.microsoft.com/en-us/azure/devops/artifacts/get-started-cargo?view=azure-devops

This article mentions we need nightly toolchain but I tested with the recently released 1.74.0 rust https://releases.rs/docs/1.74.0/ which stabilized support for registry-auth, and it seems to work fine.

**Comment by ronakj** [comment]
Created a PR to update the documentation #13799 in case you are interested in contributions. Thanks!

**Comment by WilliamAntonRohm** [comment]
@ronakj -- Ronak, thank you for your contribution!

@ramiMSFT -- please look into this issue.
