### ISSUE TITLE
Windows build agent readme path has changed

### ISSUE THREAD

**Issue by jonaslindholm** [MicrosoftDocs/azure-devops-docs#13793]
Under "Software", the "Windows Server 2022..." and 2019 "Included software" urls seem to have changed.

Gives 404: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
Exists at:    https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

Gives 404: https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
Exists at:    https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@jonaslindholm -- Jonas, thank you for your feedback -- these links have been recently updated and they are working for me.
