### ISSUE TITLE
Azure DevOps EU region...

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/azure-devops-docs#13806]
This page indicates that North Europe is the only EU option for hosting, but our instance (and the [status dashboard pages](https://status.dev.azure.com/_event/443741549)) indicate that it is West Europe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe4c7a5f-322f-2c35-bbd7-14db2aee8144
* Version Independent ID: 52442a88-9e7c-b50d-4643-23ed10a3d7c3
* Content: [Data locations for Azure DevOps - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops)
* Content Source: [docs/organizations/security/data-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/data-location.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by codegeass1** [comment]
I have the same question :)

**Comment by chcomley** [comment]
Thanks for your feedback. I'm looking into this, likely to have a resolution within the next week.

**Comment by chcomley** [comment]
I've updated the article to reflect Europe (EU). Thanks for your feedback. The page you referenced is historical. Please see the current [Status Page](https://status.dev.azure.com/) for data locations, which matches the data locations in this article. Thank you.
