### ISSUE TITLE
Missing authentication option SP 

### ISSUE THREAD

**Issue by ajfis** [MicrosoftDocs/azure-devops-docs#13813]
Missing authentication option SP. https://learn.microsoft.com/en-gb/azure/devops/release-notes/2023/pipelines/sprint-227-update#register-an-agent-using-a-service-principal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b046b22-2410-a840-5ca3-1f90c7120c2f
* Version Independent ID: 3b046b22-2410-a840-5ca3-1f90c7120c2f
* Content: [Deploy an Azure Pipelines agent on Linux (2.x) - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux-agent?view=azure-devops#authentication-options)
* Content Source: [docs/pipelines/agents/v2-linux-agent.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/v2-linux-agent.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
We have new content that covers this option in these two places:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agent-authentication-options?view=azure-devops#service-principal
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/service-principal-agent-registration?view=azure-devops
