### ISSUE TITLE
Description for AzDOS 2022 displays interface for Azure DevOps Services

### ISSUE THREAD

**Issue by DennisL68** [MicrosoftDocs/azure-devops-docs#13811]
Se title

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27d0fe85-7e69-29b7-206f-797a168505c1
* Version Independent ID: 0e1f085d-0d1f-32bf-51e2-c60bc3f0a763
* Content: [Delete, remove users from team, project, organization - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/delete-organization-users?view=azure-devops-2022&tabs=browser)
* Content Source: [docs/organizations/accounts/delete-organization-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/delete-organization-users.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @DennisL68. I've added a note, so customers won't be confused by differences in images, as the basic functionality remains the same.
