### ISSUE TITLE
This is not a "Hello World" for creating a pipeline.

### ISSUE THREAD

**Issue by scottcun** [MicrosoftDocs/azure-devops-docs#13829]
[Enter feedback here]
All of the examples are focused on building in different languages.  Where's the bare-bones "Hello World" example?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad567ab-0513-570b-74dc-a0827815c6a1
* Version Independent ID: 5e549605-cac8-98ea-ac5b-89f4a40a5f3c
* Content: [Create your first pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser#Create%20a%20build%20pipeline)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/create-first-pipeline.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks for your feedback. I'm adding it to an internal issue on reworking this article for the day 0 customer experience.
