### ISSUE TITLE
Which version of vss-web-extension-sdk did you use?

### ISSUE THREAD

**Issue by ibvhefe** [MicrosoftDocs/azure-devops-docs#13824]
This article uses an outdated version of `vss-web-extension-sdk`. Which one is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9c938-dde5-4eba-6e09-6e43ef0e8ee5
* Version Independent ID: 53f9961e-1c31-1080-1699-4ef901939b19
* Content: [Add a dashboard widget - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-dashboard-widget?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops)
* Content Source: [docs/extend/develop/add-dashboard-widget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-dashboard-widget.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ibvhefe, thanks for reaching out and sorry for the confusion. I'll update the article, but here it is for you:
https://github.com/Microsoft/azure-devops-extension-sdk

**Comment by ibvhefe** [comment]
Thank you
