### ISSUE TITLE
Duplicate IP listed

### ISSUE THREAD

**Issue by jeffpatton1971** [MicrosoftDocs/azure-devops-docs#13822]
In the [Azure DevOps Ip Allow List documentation](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/security/allow-list-ip-url.md), there is a duplicate IP address range '40.80.187.0/24'. This range is listed for both North Central US and North US. This will cause issues with firewalls as these ranges overlap. Can we get this issue addressed as soon as possible, please?

**Comment by jeffpatton1971** [comment]
It appears there are additional duplicate IP address ranges; please address these issues.

```
40.119.10.0/24 South Central US, South US
```

**Comment by WilliamAntonRohm** [comment]
@jeffpatton1971 -- Jeff, thank you for your feedback.  If you feel this is a product issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

@chcomley -- Chrystal, please look into this potential documenation issue.

**Comment by chcomley** [comment]
@jeffpatton1971 thanks so much for the feedback, we'll address this ASAP. @Jominana can you please address this?

**Comment by jeffpatton1971** [comment]
> @jeffpatton1971 -- Jeff, thank you for your feedback. If you feel this is a product issue, please add it here:
> 
> * [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
> 
> @chcomley -- Chrystal, please look into this potential documenation issue.

It would be a product issue if they wrote the documentation, but don't you all edit and review it?

**Comment by chcomley** [comment]
Hi @jeffpatton1971, sorry for any confusion from William's response, as it's not a product issue. I'm the writer and will be following through with updating this article. I've reached out to my PM for verification, and then I'll publish the update. When the update goes live, this issue will automatically close. I expect to do so within the next week! Thank you!
