### ISSUE TITLE
Update documentation / behavior for User Permissions and Open access for Pipelines

### ISSUE THREAD

**Issue by tareafina** [MicrosoftDocs/azure-devops-docs#13830]
Hello Team,

When you want to modify the Pipeline permissions to "Open Access" in an specific Environment, it is required that you needs to be Administrator at Environments level.

This is happening even if you created the Environment and even If you have the Creator user assigned permission.

Also, if you create the Environment (e.g. Test) , then into this Test environment you disabled the inheritance and add to you as an Administrator, or some of the groups as Administrator of this specific environment, you aren't able to modify the Open access option since it is grayed out as below image

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/63680060/030c3209-1289-4b94-b5d1-c876a27dac6c)

Is this an expected behavior? 

You can modify this setting only if you are added as Administrator at Environments top level.

Would you please specify this into the documentation to avoid confusion when you want to change the Pipeline permissions you needs to be an Administrator at Environment top level? It can possibly maybe into this table

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/63680060/163b9f63-2849-481b-aa6e-2e43782a32a2)

Also, how can we allow the permissions granularity to avoid be added as Administrator at top Environments level?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Create target environment - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#security)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/environments.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
As of February 2023, Azure Pipelines requires resource-type administrator role when opening up access to a resource to all pipelines. [Here's more information](https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-216-update#restrict-opening-protected-resources-to-resource-administrators). I'll update the article to make this permission more clear.
