### ISSUE TITLE
Unclear how to select multiple ADO items for bulk edit in board results or query results. 

### ISSUE THREAD

**Issue by msmarkglad** [MicrosoftDocs/azure-devops-docs#13840]
The article is very unclear about how to select multiple items from a board or a query result. From reading the article, I still have no idea how to select multiple items in either of those scenarios. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca74dfe-b281-987f-ca06-0ed3e51aa8d6
* Version Independent ID: 3b36bca7-53ae-655f-f836-581b893c813b
* Content: [Edit user stories and other work items in bulk in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/bulk-modify-work-items?view=azure-devops)
* Content Source: [docs/boards/backlogs/bulk-modify-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/bulk-modify-work-items.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by rufer7** [comment]
@msmarkglad does PR #13842 make it more clear?
