### ISSUE TITLE
Queuing Policies don't work if deferred

### ISSUE THREAD

**Issue by jp98** [MicrosoftDocs/azure-devops-docs#13846]
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic#specify-queuing-policies

This section doesn't explain that if you have queued a release for deployment and marked it to be deferred, then create a new release, it doesn't cancel the previous one straight away, instead it goes into the deployment queue and has both jobs sitting there. Reading through this, I had expected that if I had deferred a stage until a later time, and then a new release was created prior to the deferred release time, then the new release would then replace the existing scheduled deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/stages.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Closing due to lack of response.
