### ISSUE TITLE
There is no Edit option

### ISSUE THREAD

**Issue by vksf01** [MicrosoftDocs/azure-devops-docs#13853]
[Enter feedback here]

Your page does not appear to be the same as what I see in my screenshot.  There doesn't appear to be an Edit button 

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/7118846/dd40b697-471f-4786-9102-947de320dde3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6a24a4-066b-caaf-551a-0d58097fea4b
* Version Independent ID: d2cbc919-38f3-8aaf-b3d6-ab26c4a0d260
* Content: [Clone or import a pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/get-started/clone-import-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/get-started/clone-import-pipeline.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by rufer7** [comment]
@vksf01 the `Edit` button appears on pipeline level. Means you have to select one of the pipelines out of the list in your screenshot to edit it.

**Comment by WilliamAntonRohm** [comment]
@vksf01 -- thank you for your feedback.

@rufer7 -- thank you for those specifics.

**Comment by vksf01** [comment]
> @vksf01 -- thank you for your feedback.
> 
> @rufer7 -- thank you for those specifics.

are there any plans to update the screenshot?  it is very misleading.  that was the reason i opened this issue.

**Comment by WilliamAntonRohm** [comment]
cc @juliakm for awareness
