### ISSUE TITLE
unable to override container network configuration using options

### ISSUE THREAD

**Issue by vinodMS** [MicrosoftDocs/azure-devops-docs#13881]
The document states that when using a container to run the jobs, any options supported by the `docker create` command can be passed as options. 

"Running docker create --help will give you the list of supported options. You can use any option available with the [docker create command](https://docs.docker.com/engine/reference/commandline/create/)."

But this is not accurate, I want to do the following, 
```
        container:
          image: 'server.com:443/docker/devcontainer-python:${{ parameters.pythonVersion }}'
          options: --network my-network
```
This won't work, as the pipeline by default creates and assigns the container to a new network. 

Here's the log,
```
/usr/bin/docker network create --label dc9729 vsts_network_7e260da30b824d1d9a2707a210cf99bd
83cf11372e40ee58532841c04191e283166727b027ceea05225877809eee4707
/usr/bin/docker create --name d3cf7021183d4fbe9e9520d1e2980155_python39_2a5668 --label dc9729 --network vsts_network_7e260da30b824d1d9a2707a210cf99bd --network my-network -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/azagents/agent-server/_work/350":"/__w/350" -v "/azagents/agent-server/_work/_temp":"/__w/_temp" -v "/azagents/agent-server/_work/_tasks":"/__w/_tasks" -v "/azagents/server/_work/_tool":"/__t" -v "/azagents/agent-server/externals":"/__a/externals":ro -v "/azagents/agent-server/_work/.taskkey":"/__w/.taskkey" server.com:443/docker/devcontainer-python:3.9 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
Error response from daemon: Container cannot be connected to network endpoints: my-network, vsts_network_7e260da30b824d1d9a2707a210cf99bd
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/container-phases.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@vinodMS I checked with our platform team and they noted that we pass on the arguments to the invocation of Docker but there may be some limitations, primarily with hosted agents. They also suggested looking to see if there's an argument for the `container` property that you can use. Here's the [resources.containers.container schema](https://learn.microsoft.com/azure/devops/pipelines/yaml-schema/resources-containers-container?view=azure-pipelines). 

I'll update the article to make it clearer that Azure DevOps passes the arguments to Docker.

**Comment by vinodMS** [comment]
Hi @juliakm, thanks for checking. The limitation in this case is that docker run accepts only one --network argument during the creation of the container and this is already used by the agent. I've managed to get around this by mounting docker.sock and then attaching an additional network using the docker network command.
