### ISSUE TITLE
Typescript code getting compilation error

### ISSUE THREAD

**Issue by oltancolak** [MicrosoftDocs/azure-devops-docs#13888]
It's a small think but needs to be updated for being more developer friendly guidelines.

At related document's

`Create Custom Task` -> `Step 3`

```
import tl = require('azure-pipelines-task-lib/task');

async function run() {
    try {
        const inputString: string | undefined = tl.getInput('samplestring', true);
        if (inputString == 'bad') {
            tl.setResult(tl.TaskResult.Failed, 'Bad input was given');
            return;
        }
        console.log('Hello', inputString);
    }
    catch (err) { //This line causes error -> error TS2571: Object is of type 'unknown'.
        tl.setResult(tl.TaskResult.Failed, err.message);
    }
}

run();
```

In TypeScript 4.0, the ability to specify the type of catch clause variables as **unknown** has been introduced. Which means you can not access `err.message` directly. 

**Fix Ideas**

in `tsconfig.json` set the flag to `false` 

```
"compilerOptions": {
        "useUnknownInCatchVariables": false
    }
```

But tsconfig.json update not part of the this guideline so we can fix easily with this update of code

```
...  
catch (err){
...
```
with 

```
...  
catch (err: any){
...
```
 
You can find more info [Microsoft Dev Blog - Typescript](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#unknown-on-catch)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for this feedback, @oltancolak. I've added your fix, which should be live shortly. Have a wonderful day!
