### ISSUE TITLE
Problem to run tests from tutorial

### ISSUE THREAD

**Issue by gascorrea** [MicrosoftDocs/azure-devops-docs#13886]
There's a problem in the _suite.ts code.
It seems that "run" method doesn't exists anymore.
This method was deprecated.

<img width="508" alt="image" src="https://github.com/MicrosoftDocs/azure-devops-docs/assets/109249475/699bcad5-8294-4bc2-b5e9-087aa6a91b17">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Duplicate of #13900
