### ISSUE TITLE
https://apps.apple.com/app/id1479696509

### ISSUE THREAD

**Issue by hooooh2** [MicrosoftDocs/azure-devops-docs#13897]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54179351-62b2-c41b-949b-0652a0f1d354
* Version Independent ID: 1ffcd0b3-e67b-6cfe-caa6-814a699627db
* Content: [Set query permissions in Azure Boards and Azure DevOps - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/set-query-permissions?view=azure-devops)
* Content Source: [docs/boards/queries/set-query-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/set-query-permissions.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by hooooh2** [comment]
![Uploading IMG_0434.png…]()
