### ISSUE TITLE
"Build and deploy Java to Azure Kubernetes service" link goes to Javascript page/example

### ISSUE THREAD

**Issue by paulparkinson** [MicrosoftDocs/azure-devops-docs#13899]
"Build and deploy Java to Azure Kubernetes service" link goes to Javascript page/example.

The link at the bottom of https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java?view=azure-devops taht says "Build and deploy Java to Azure Kubernetes service" goes to https://learn.microsoft.com/en-us/azure/aks/devops-pipeline?view=azure-devops&tabs=cli&pivots=pipelines-yaml which has a Javascript example (ie not a Java example).

If this is correct then would be better to have more generic wording such as "Build and deploy to Azure Kubernetes" or simply the actual title of the page it links to which is "Build and deploy to Azure Kubernetes Service with Azure Pipelines" 

Ideally https://github.com/paulparkinson/pipelines-java would have the Dockerfile, etc. necessary to build and deploy to AKS in order to have a continuous/consistent example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47f8d3c5-c20f-a1d2-80c6-87856244be0e
* Version Independent ID: e1a8e10b-f04c-601b-c848-4c79786a7586
* Content: [Build Java apps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/java.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks! We'll update the link.
