### ISSUE TITLE
tl.run() in example is deprecated

### ISSUE THREAD

**Issue by ohlrogge** [MicrosoftDocs/azure-devops-docs#13900]
the tl.run() in the example is deprecated. Can you update it, so it is with runAsync()?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by benjamin-morris-91** [comment]
I created an issue without seeing this one first. So mine will probably be closed. I posted some details on how to work around this. Feel free to check it out.
https://github.com/MicrosoftDocs/azure-devops-docs/issues/13967

**Comment by chcomley** [comment]
Closing this issue, as a duplicate to https://github.com/MicrosoftDocs/azure-devops-docs/issues/13967. Thanks.
