### ISSUE TITLE
Add a group rule to assign access levels

### ISSUE THREAD

**Issue by Raijin766** [MicrosoftDocs/azure-devops-docs#13913]
Hi Doco team, 
Not sure if my team missed doco somewhere else that listed this issue but I thought it might be good to give some feedback on our experience following this doco. 

We created new projects and decided to use the group rule feature based off Entra ID groups to grant access and permissions to the new projects. 

We had no issues following the doco on creating and adding the groups but ran into issues when attempting to see the users in "all users" or assigning them to PBIs. 

We were able to work out that the user needs to attempt to sign in before we can do these actions as was listed in this feedback. 
https://github.com/MicrosoftDocs/azure-devops-docs/issues/2557

What I would like to see is a note added to the doco outlining that users will not appear until they attempt to log in for the first time. 
This appears to be a regular misunderstanding of the doco and I feel like this will resolve the issue going forward. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab08f86b-6991-b3f1-b07e-51048c503bc8
* Version Independent ID: 31556922-2ea2-791e-7508-6590762a0365
* Content: [Add group rule to assign access levels - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-by-group-membership?view=azure-devops)
* Content Source: [docs/organizations/accounts/assign-access-levels-by-group-membership.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/assign-access-levels-by-group-membership.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for your feedback, @Raijin766. I've updated the article, adding to the note. Thanks again!
