### ISSUE TITLE
CheckIndexingStatus.ps1 script does not exist for Azure DevOps Server 2022

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#13919]
In Section "Check indexing status" it says:

> 1. Execute the CheckIndexingStatus.ps1 script with administrative privileges. 

However, there is no such file for 2022 Server. Let's fix this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2ce6aa4-6c9d-6deb-94c4-7953e339dede
* Version Independent ID: 4ced0e1c-a0f7-3139-d490-21bb34e24f63
* Content: [Manage Search, indexing - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/search/manage-search?view=azure-devops-2022&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/project/search/manage-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/search/manage-search.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-search**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @NenoLoje. I've updated the article, which should be live shortly .
