### ISSUE TITLE
Need a way to install multiple provisioning profiles

### ISSUE THREAD

**Issue by gordingin** [MicrosoftDocs/azure-devops-docs#13929]
[Enter feedback here]

InstallAppleProvisioningProfile@1 will only allow us to install one profile, we need to install two sometimes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8bbfc6e-5571-ff0c-3e63-cfed6e0f12dc
* Version Independent ID: 1bdf5f64-e515-6e43-ddca-690586dfece7
* Content: [Sign Your Mobile App During CI - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/apps/mobile/app-signing.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@gordingin -- Ralph, thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
