### ISSUE TITLE
Request to add a limitation with Azure VM screen resolution

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#13925]
In this section, Why is not possible increase or change display resolution in Azure VM [https://learn.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#setting-screen-resolution](url)

Is it possible to add to the note stating that:

- The resolution util task does not work for Azure VMs. Azure VM agents and screen resolutions seem to have some restrictions.

I'm a front-line support engineer in CSS and we have seen several support tickets for this issue, and we have always been told by the Windows team that this is a limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c96ae1b3-ab4c-540e-c4ca-79075f55f202
* Version Independent ID: c7b3e395-c55e-51a1-0f7e-8f5fb0430ee8
* Content: [Configure for UI testing - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest)
* Content Source: [docs/pipelines/test/ui-testing-considerations.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/test/ui-testing-considerations.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-test**
* GitHub Login: @raviLiftr
* Microsoft Alias: **rbatra**

**Comment by kripa-2019** [comment]
I found this : [https://stackoverflow.com/questions/45829787/increase-the-screen-resolution-on-test-agent](url)

![Azure VM resize](https://github.com/MicrosoftDocs/azure-devops-docs/assets/47343377/1c02d666-e2f4-4ae5-a90c-f30c3e729813)

Also, found this : 
As of 2021, due to security concerns, Microsoft disabled RemoteFX vGPU by default on all Windows versions starting with the July 14, 2020, Security Update, and it was removed starting with the April 13, 2021, Security Update. This change means that RemoteFX is no longer a viable option for new deployments in Azure VMs or other environments using updated Windows versions.

**Comment by WilliamAntonRohm** [comment]
@kripa-2019 -- Kripa, thank you for your well-researched feedback.

@raviLiftr -- please look into this issue.

**Comment by WilliamAntonRohm** [comment]
reassign:@raviLiftr

**Comment by juliakm** [comment]
Thanks, we'll update the article to make this clearer.
