### ISSUE TITLE
Document Path to Success With ADO Environment Resource Pointing To Private AKS Cluster 

### ISSUE THREAD

**Issue by bbrandt** [MicrosoftDocs/azure-devops-docs#13922]
This note appears twice in this article:

> If you're using Azure Kubernetes Service, the [Azure Resource Manager service connection type](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#azure-resource-manager-service-connection) is the best way to connect to a private cluster, or a cluster that has local accounts disabled.

But these instructions do not say what to do differently to setup canary releases when "Azure Resource Manager service connection type" with a private cluster with local accounts disabled.  Please either add a 2nd article or a toggle for this set of instructions between private/public cluster to explicitly lead us through how to configure this successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Use a canary deployment strategy for Kubernetes deployments with Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for your feedback. I'm creating an internal work item for us to work on this in the future.

**Comment by bbrandt** [comment]
Thank you @juliakm!  Is there a way for us to monitor progress of this work item or will updates just be posted here?
