### ISSUE TITLE
Typo a Azure DevOp > an Azure DevOps

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#13927]
https://learn.microsoft.com/en-us/azure/devops/server/command-line/tfsconfig-cmd?view=azure-devops-2022
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/40815708/01f950bf-3e76-44d1-9ba8-2d0aa8232f28)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/40815708/9f34b04b-c88b-4a00-9180-13e6e03dd952)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/40815708/f0bc9613-dc50-45e4-ab55-c1afd434ac1b)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/40815708/fcdf901d-d507-4cc3-93a8-e68aa3f90552)
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/40815708/9d347b4a-0ce0-4135-887e-fe2505f08efc)

#PingMSFTDocs

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by juliakm** [comment]
Thanks, we'll fix this shortly.
