### ISSUE TITLE
Clarify if all historical commits are scanned by the Secret Scanner

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#13920]
I often get asked if the Secret Scanning scans all (potentially multiple years) of historical commits, or just the tip version. Let's clarify this in the docs.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31d2c1ae-7edd-18e3-c357-623acef69af8
* Version Independent ID: 31d2c1ae-7edd-18e3-c357-623acef69af8
* Content: [Secret Scanning for GitHub Advanced Security for Azure DevOps - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-secret-scanning?view=azure-devops&WT.mc_id=DOP-MVP-21138)
* Content Source: [docs/repos/security/github-advanced-security-secret-scanning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/github-advanced-security-secret-scanning.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @laurajjiang
* Microsoft Alias: **laurajiang**

**Comment by laurajjiang** [comment]
Hi @NenoLoje - this is mentioned in the introductory block of the documentation: 

> Secret scanning for your repository scans for any secrets that may already exist in your source code across history and push protection prevents any new secrets from being exposed in source code. 

If you have a recommendation on we can make this more clear, feel free to re-open the issue and provide a suggestion. Thanks!

**Comment by NenoLoje** [comment]
@laurajjiang Well, I don't know the answer to the question - so I'm not sure I can rephrase it without knowing it for sure. Can we first clarify how the product behavior is designed?

**Comment by NenoLoje** [comment]
Also, please reopen this issue, as it's not yet resolved.

**Comment by laurajjiang** [comment]
Yes, apologies - secret scanning will scan across all commits and branches, not just the tip version.
