### ISSUE TITLE
Example on running CodeQL on a self hosted runner (GHAzDO)

### ISSUE THREAD

**Issue by rajbos** [MicrosoftDocs/azure-devops-docs#13948]
The docs for running CodeQL on a self-hosted runner are rather confusing. This took me to long to figure out (multiple retries) so I [blogged about it](https://devopsjournal.io/blog/2024/01/22/Running-GHAzDO-CodeQL-on-selfhosted-runners) for the next time I need this.

Please update the docs and give an example of the folder name and locations.

## Original text: 
* Install the CodeQL bundle to the agent tool cache: Pick the latest CodeQL release bundle from [GitHub](https://github.com/github/codeql-action/releases).
* Download and unzip the bundle to the following directory inside the agent tool directory, typically located under `_work/_tool: ./CodeQL/0.0.0-[codeql-release-bundle-tag (i.e. codeql-bundle-v2.14.2)]/x64/`. Learn more about the [agent tool directory](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md#tool-cache).
* Create an empty file at `./CodeQL/0.0.0-[codeql-release-bundle-tag (i.e. codeql-bundle-20221105)]/x64.complete`

## Suggested changes:
With the long file paths it is hard to make out where to place what, and guessing the version setup does not make sense. Both  options below work:
* _work\_tool\CodeQL\0.0.0-codeql-bundle-v2.15.5
* _work\_tool\CodeQL\0.0.0-v2.15.5

My main two issues where:
1. Guessing and rerunning is pretty time consuming, so the logs of the CodeQL Init task can also be more helpful. 
2. I mostly made the mistake of placing the `x64.complete` file also in the `x64` folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Version Independent ID: 8c21f56a-170e-d33f-e568-7fc93e8e7d3c
* Content: [Configure GitHub Advanced Security for Azure DevOps features - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml)
* Content Source: [docs/repos/security/configure-github-advanced-security-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/security/configure-github-advanced-security-features.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @laurajjiang
* Microsoft Alias: **laurajiang**

**Comment by rajbos** [comment]
This s confusing. Why is this issue closed without any feedback? CC @laurajjiang  / @WilliamAntonRohm since you where interacting? 

Would be nice to at least indicate something like 'matched with internal system' if that is the case?

**Comment by laurajjiang** [comment]
Hi @rajbos - apologies! I didn't realize the PR link I merged was displaying as private. I've updated the self-hosted agent requirement in [Configure GHAzDO](https://learn.microsoft.com/en-us/azure/devops/repos/security/configure-github-advanced-security-features?view=azure-devops&tabs=yaml#extra-prerequisites-for-self-hosted-agents) to add an example per your suggestion. Thank you!

**Comment by rajbos** [comment]
Thanks for adding that context 🤗
