### ISSUE TITLE
Document how to troubleshoot dependencies

### ISSUE THREAD

**Issue by nulltoken** [MicrosoftDocs/azure-devops-docs#13942]
I've spent too much time fighting against variable outputs.

Could you please update this documentation and provide a way to easily dump the content of the dependencies object so that's easier to understand the expected naming in the expression and put under the light the potential missing dependsOn.

I came up with something like this:

```

 jobs:

 - job: A
   (...)

 - job: B
   (...)

 - job: C
   (...)

   variables:
     deps: $[ convertToJson(dependencies) ]

  - steps:
      - pwsh: |
           Write-Host "$(deps)"
```

A similar approachcan be leveraged for `stageDependencies`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@nulltoken Thanks! That's a great tip that I haven't seen before. I'll add it to the doc.
