### ISSUE TITLE
Date values do not allow to enter text like „@Today-5“ anymore

### ISSUE THREAD

**Issue by HerrDorsch** [MicrosoftDocs/azure-devops-docs#13951]
We used to highlight cards without updates for n days with a style rule, e.g. pink background, to easily/visually identify „cards of inactivity“. We have used rules like the example in the documentation like „@Today-5“. They still work, but can no longer be edited. Also, we can't add new date-based rules anymore, because the calendar helper always gets the focus. The value field of a style rule does no longer accept direct input.

Please allow direct input for date values again.

Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d807b7f-4e44-1e86-7f41-1e67f9c0e1bd
* Version Independent ID: 6798865e-0273-2991-9376-abe53725aaac
* Content: [Customize a sprint taskboard in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/sprints/customize-taskboard?view=azure-devops)
* Content Source: [docs/boards/sprints/customize-taskboard.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/sprints/customize-taskboard.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@HerrDorsch -- Herr Dorsch, please add this product feedback here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
