### ISSUE TITLE
Article doesn't mention Azure Devops groups have conditions

### ISSUE THREAD

**Issue by bt701** [MicrosoftDocs/azure-devops-docs#13955]
When using inbuilt Azure Devops groups, the group rules page does allow you to change project readers, but this does not save or persist. The UI doesn't provide indication this is the case.

Microsoft Support have informed this is by design, and is a documentation bug, so it should be documented here the limitations of groups such as 'Project Collection Valid User', when using group rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab08f86b-6991-b3f1-b07e-51048c503bc8
* Version Independent ID: 31556922-2ea2-791e-7508-6590762a0365
* Content: [Add group rule to assign access levels - Azure DevOps Services](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-by-group-membership?view=azure-devops)
* Content Source: [docs/organizations/accounts/assign-access-levels-by-group-membership.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/assign-access-levels-by-group-membership.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @bt701, I'm sorry for the trouble you experienced, but thank you for notifying us of this necessary update. I've added this information to a note in the article, which should be live shortly. Thank you so much.
