### ISSUE TITLE
There's no step provided to create the column "State Change Count - First Completed".

### ISSUE THREAD

**Issue by evelynchenwx** [MicrosoftDocs/azure-devops-docs#13966]
There's one step missing in "Add State Rework Time in Days".
The last step "Add State Rework Time in Days" points to a column ("State Change Count - First Completed") which is not provided any sample before. Could you please update the document and provide the sample?
There's a same ticket reporting the same issue before: https://github.com/MicrosoftDocs/azure-devops-docs/issues/7214.
Related document: https://learn.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report?view=azure-devops#add-state-rework-time-in-days

**Comment by Jeyeline** [comment]
@evelynchenwx , any update on my query?

**Comment by chcomley** [comment]
Hi @Jeyeline, sorry for the delay here. I've updated the article, which should be live shortly. Please @mention me if you need any further clarity. Thanks so much.
