### ISSUE TITLE
Broken link in Related Articles

### ISSUE THREAD

**Issue by xand3rx** [MicrosoftDocs/azure-devops-docs#13962]
Hi,

In the Related Articles at the bottom there is a broken link for 'How to mitigate risk when using private package feeds'.
Is there still a page to use for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5162e55f-4ab3-ad76-c5ad-300a71e4b733
* Version Independent ID: b22a98c8-57a7-258a-0941-70fabbca2ac2
* Content: [Restore NuGet packages in Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/packages/nuget-restore.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@xand3rx -- thank you for your question.  This is the correct link:
- https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/en-us/

I am updating the link in this article.
