### ISSUE TITLE
Unit Test code needs updated

### ISSUE THREAD

**Issue by benjamin-morris-91** [MicrosoftDocs/azure-devops-docs#13967]
Hi there,

I'm working through creating ADO tasks and this guide has been a great resource; however, it appears there were some recent updates to the azure-pipelines-task-lib/mock-test package that should be reflected in this article to allow a smooth creation and testing of the task.

I started running into issues in the Unit test your task scripts. It looks like the run() function was deprecated and replaced with runAsync() inside the azure-pipelines-task-lib/mock-test package. A link below to the commit in the package from September 19th, 2023 to back this up (hope links are okay to send).

If you want to review the commit manually it's found at microsoft/azure-pipelines-task-lib/node/mock-test.ts, commit: cea7412512a6980646350854731833f289553b5b. 
https://github.com/microsoft/azure-pipelines-task-lib/commit/cea7412512a6980646350854731833f289553b5b

I don't like to bring up issues without attempting a solution. It's easy enough to call the runAsync() function, but then the success tests were failing since the logging of the stdout happened before the runAsync() finished. So my (jr. dev) suggestion is to attach a callback to the runAsync() function:
```
    it('should succeed with simple inputs', function(done: Mocha.Done) {
        this.timeout(1000);

        let tp: string = path.join(__dirname, 'success.js');
        let tr: ttm.MockTestRunner = new ttm.MockTestRunner(tp);

        // tr.run(); //current, old function.
        tr.runAsync().then(() => {
            console.log(tr.succeeded);
            assert.equal(tr.succeeded, true, 'should have succeeded');
            assert.equal(tr.warningIssues.length, 0, "should have no warnings");
            assert.equal(tr.errorIssues.length, 0, "should have no errors");
            console.log(tr.stdout);
            assert.equal(tr.stdout.indexOf('Hello human') >= 0, true, "should display Hello human");
            done();
        }).catch((error) => {
            done(error); // Ensure the test case fails if there's an error
        });
    });
```
That small change got it working locally for me. I know this isn't a huge issue for experienced javascript developers, but it stumped me for a bit and I'm sure it could be of help to someone else.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/add-build-task.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@benjamin-morris-91, thanks so much for this detailed issue. I've added your workaround to the article, which will be published in the next day or so. Thanks for helping others be successful!
