### ISSUE TITLE
What if you're not using GitHub

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [MicrosoftDocs/azure-devops-docs#13968]
I'm using Azure DevOps and trying to use a variable group from Azure DevOps, in and Azure DevOps pipeline, with the yml file in an Azure DevOps repository. I find it more than a bit unusual that the documentation for this software assumes you're using a completely different paid service for a concept that this software provides.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5c4674-9e05-1381-8202-5225afd95e33
* Version Independent ID: 62b343f9-9b2a-0be0-2582-e3795e9cdef5
* Content: [Azure CLI sample for Azure Pipelines and variable groups - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/cli/pipeline-variable-group-secret-nonsecret-variables?view=azure-devops)
* Content Source: [docs/pipelines/scripts/cli/pipeline-variable-group-secret-nonsecret-variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/scripts/cli/pipeline-variable-group-secret-nonsecret-variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@ScottSlaughterBBNA -- Scott, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

cc @juliakm for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
