### ISSUE TITLE
To Table Does Not Exist In Modern Power BI Desktop

### ISSUE THREAD

**Issue by jacobgexigo** [MicrosoftDocs/azure-devops-docs#13970]
On the section that says to create a blank query, add the "= DateTime.LocalNow" function and then click the To Table button, that button does not exist under Transform in Power Query in the newer versions of Power BI Desktop anymore.  I'm not sure what to do to make it work at this time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35ad9d59-d3df-925d-f613-dd07270c72c4
* Version Independent ID: 681464d8-048e-6d74-f088-4f726fcb55a5
* Content: [Add last refresh date to a Power BI report - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/powerbi/add-last-refresh-time?view=azure-devops&tabs=private)
* Content Source: [docs/report/powerbi/add-last-refresh-time.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/powerbi/add-last-refresh-time.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by jacobgexigo** [comment]
Ah, I see.  What needs to be added to the page is to click the "Invoke" button, then it will let you click the To Table button.

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/29784949/63673c51-9a9f-468b-be6b-25f239786bca)

**Comment by chcomley** [comment]
Thanks for the feedback, @jacobgexigo, I've updated the document. Have a great day.
