### ISSUE TITLE
Incorrect advice for customizing the pipeline agent user `AzDevOps`

### ISSUE THREAD

**Issue by odegroot** [MicrosoftDocs/azure-devops-docs#13972]
The docs say:

> To customize the permissions of the pipeline agent user, you can create a user named AzDevOps, and grant that user the permissions you require. This user will be created by the scaleset agent startup script if it doesn't already exist.

This used to be true, but is now no longer correct advice.
If you do this, then `enableagent.sh` will **not** assign the correct permissions to the user, resulting in a misconfigured agent.
See microsoft/azure-pipelines-agent#4336 for details.

You'd need to run the entire user initialization code block from `enableagent.sh`, and _then_ do your customizations.

```sh
# Create our user account if it does not exist already
if id AzDevOps &>/dev/null; then
    log_message "AzDevOps account already exists"
else
    log_message "Creating AzDevOps account"
    sudo useradd -m AzDevOps
    sudo usermod -a -G docker AzDevOps
    sudo usermod -a -G adm AzDevOps
    sudo usermod -a -G sudo AzDevOps

    log_message "Giving AzDevOps user access to the '/home' directory"
    sudo chmod -R +r /home
    setfacl -Rdm "u:AzDevOps:rwX" /home
    setfacl -Rb /home/AzDevOps
    echo 'AzDevOps ALL=NOPASSWD: ALL' >> /etc/sudoers
fi
```

Can you remove this advice, or update it, or adjust the `enableagent.sh` to make the current advice true again?

References:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents#lifecycle-of-a-scale-set-agent
https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/15/enableagent.sh

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 756d9c64-a802-61ad-ba6c-6061d2d747cf
* Version Independent ID: 012518b7-0282-f5b0-5206-8a9d1902b8d3
* Content: [Azure Virtual Machine Scale Set agents - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-scale-set-with-custom-image-software-or-disk-size)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/scale-set-agents.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
