### ISSUE TITLE
If Condition Example Is Wrong

### ISSUE THREAD

**Issue by RoastedDonut** [MicrosoftDocs/azure-devops-docs#13973]
The documentation around using if conditions in yaml seems to be inconsistent across the pages and wrong on this specific page.  Copying the example for adding an if condition to the variables section would cause the a null reference exception to be thrown.  The example is missing a leading dash.

Original:
```
variables:
  ${{ if eq(parameters.x, 'x') }}:
```

Should Be:
```
variables:
  - ${{ if eq(parameters.x, 'x') }}:
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops-2020)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the feedback. The version in the documentation should work but we will double-check with the product team. 

We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
