### ISSUE TITLE
the GUID for the DownloadPipelineArtifact does not match the task GUID assigned when doing `preview run`

### ISSUE THREAD

**Issue by david-vankampen** [MicrosoftDocs/azure-devops-docs#13982]
On call to preview-run, what gets generated for download is `30f35852-3f7e-4c0c-9a88-e127b4f97211`, not `61F2A582-95AE-4948-B34D-A1B3C4F6A737` as this page describes.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2f7712f-f527-4326-21d5-34f1c300bdd7
* Version Independent ID: d3e588cc-8552-ddae-1f82-0856cc84f2d9
* Content: [Pipeline decorator context - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops)
* Content Source: [docs/extend/develop/pipeline-decorator-context.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/extend/develop/pipeline-decorator-context.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much for your feedback, @david-vankampen. I've updated the article. Have a wonderful day!
