### ISSUE TITLE
Outdated Marketplace Wiql Editor extension link

### ISSUE THREAD

**Issue by warren2k** [MicrosoftDocs/azure-devops-docs#13986]
The tip that includes a link to the Marketplace Wiql Editor points to an outdated extension that is currently unpublished. The published extension can be accessed at https://marketplace.visualstudio.com/items?itemName=ms-devlabs.wiql-editor. Can you please update this page to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 309b3b5f-7355-57ac-3775-b441f6e037f1
* Version Independent ID: 0d30ed27-9dc4-e8de-ef7e-c71842c9b4c3
* Content: [Define a work item query in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/queries/using-queries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/queries/using-queries.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by warren2k** [comment]
Thanks. How soon is shortly? Next week?

**Comment by chcomley** [comment]
It's live. "Shortly" meant sometime last Friday, but I was wrong. Thanks for following up and have a great day. In the future, we'd love it if you [contributed to our docs](https://learn.microsoft.com/en-us/contribute/)!
