### ISSUE TITLE
Wrong syntax in description of how to access outputs of another job in the same stage

### ISSUE THREAD

**Issue by andreasbuechel** [MicrosoftDocs/azure-devops-docs#13988]
In [this documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependency-syntax-overview), section "job to job dependency (same stage)", the syntax is described as:
`dependencies.<stage-name>.outputs['<step-name>.<variable-name>']`

I think, the following is correct:
`dependencies.<job-name>.outputs['<step-name>.<variable-name>']`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for catching this. We'll update the article.
