### ISSUE TITLE
[BUG] Dockerfile on Ubuntu

### ISSUE THREAD

**Issue by chris-briddock** [MicrosoftDocs/azure-devops-docs#13987]
Hi,

When using the documentation [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) I get a permissions issue.

I have fixed the issue [here](https://github.com/chris-briddock/azure-devops-agent-docker)

Thanks,

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/docker.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@chris-briddock -- Chris, thank you for your contribution!  Please consider adding your updates as a pull request (PR) to that article.

- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing this will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

**Comment by WilliamAntonRohm** [comment]
@chris-briddock -- Chris, as your PR (thank you) is in review, I'm closing this issue.
