### ISSUE TITLE
Docs about consuming python packages from Artifacts feed should mention PipAuthenticate task

### ISSUE THREAD

**Issue by aawadaptix** [MicrosoftDocs/azure-devops-docs#13984]
As far as I can see, the documentation about consuming python packages in Azure Pipelines only refers to using `artifacts-keyring` or a PAT to authenticate to your own feed. I find the PipAuthenticate task is a much easier way to do this, but I did not find it mentioned in the docs. I'm making this issue to suggest making this clearer. It could also be mentioned in the "connect to feed" area of the Azure Artifacts UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c37d1cb4-805b-173c-ac62-1037c5bedb7f
* Version Independent ID: 91cfb14e-b752-93e2-52a7-25d8d3fe66d5
* Content: [Publish Python packages to an Azure Artifacts feed - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/artifacts/pypi.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@aawadaptix Thanks for your feedback! I'll be adding a new scenario using the PipAuthenticate task in the near future. Stay tuned.
