### ISSUE TITLE
Python examples

### ISSUE THREAD

**Issue by dpadzensky** [MicrosoftDocs/azure-devops-docs#13992]
It would be great if you could add some python examples to the "azure-devops-auth-samples" repo.  The .NET libraries used do not really give good hints as to what needs to be done when trying to authenticate via python.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Version Independent ID: 65aa9b24-e20d-611b-8ef8-020d94550a20
* Content: [Use service principals & managed identities - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/service-principal-managed-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/get-started/authentication/service-principal-managed-identity.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @Wonga
* Microsoft Alias: **wonga**

**Comment by juliakm** [comment]
Thanks @dpadzensky. I'm adding this as a feature request. You'll see this issue close in the next month but we are tracking it internally.
