### ISSUE TITLE
Section that seems out of place

### ISSUE THREAD

**Issue by tony-box** [MicrosoftDocs/azure-devops-docs#13996]
The section **Share work items across your test experience** seems out of place on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://learn.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/test/create-a-test-plan.md)
* Service: **azure-devops-test-plans**
* GitHub Login: @rohit-batra
* Microsoft Alias: **rbatra**

**Comment by juliakm** [comment]
Thanks for your feedback. I've added this issue and the other two you created to an internal issue for when we update this documentation set.
