### ISSUE TITLE
Unused variable releaseBranchName in build pipeline tutorial/example

### ISSUE THREAD

**Issue by jvmap** [MicrosoftDocs/azure-devops-docs#13991]
Hi there,

In the given example YAML file, the global variable `releaseBranchName` is not used. I presume this is an oversight, that might confuse readers.

Best regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0851ffe4-d380-6ff4-a4c7-0557fa5ef84e
* Version Independent ID: 0851ffe4-d380-6ff4-a4c7-0557fa5ef84e
* Content: [Tutorial: Create a multistage pipeline with Azure DevOps - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/create-multistage-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/process/create-multistage-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/create-multistage-pipeline.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the feedback. It looks like releaseBranchName gets referenced in the pipeline but isn't used in any tasks. We'll keep this is mind as something to improve in future versions of this article.
