### ISSUE TITLE
Verification code shows, but what do i do with it?

### ISSUE THREAD

**Issue by v-mwalk** [MicrosoftDocs/azure-devops-docs#14005]
After I click Accept I am shown a screen with a code and text `Please enter this verification code in your chat application to complete the authentication.`

This is not mentioned in any instructions?!?!  What do i do withy it?  Tried entering it Slack, nothing.  Even tried it in my SMS/RCS app, nothing...???

Instrustions have kinda left me out on a limb....

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8b93c91-a6af-81ed-b9b3-d857dcc8d17b
* Version Independent ID: 60f9efcd-8c36-1f83-7ff3-c22e93308505
* Content: [Azure Repos with Slack - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/integrations/repos-slack?view=azure-devops#configuration-failed-please-make-sure-that-the-organization-organization-name-exists-and-that-you-have-sufficient-permissions)
* Content Source: [docs/repos/integrations/repos-slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/integrations/repos-slack.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-integration**
* GitHub Login: @divais
* Microsoft Alias: **Divais**

**Comment by juliakm** [comment]
@chcomley Could you take a look at this one?

**Comment by chcomley** [comment]
[like]  Chrystal Comley reacted to your message:
________________________________

**Comment by chcomley** [comment]
Hi @v-mwalk, I've updated this article for clarity, and am sorry for the confusion. The code is provided to you once you select **Sign in** in the Slack chat, and then select **Accept** on the resulting screen. You copy the code, and then go back to the Slack chat, select **Enter code**, paste the code, and then select **Submit**. The updated article should be live within the next half hour or so. Thank you and feel free to @mention me if you have any further questions. Thanks for your feedback!
