### ISSUE TITLE
Unconfigure Search on a separate server: incomplete

### ISSUE THREAD

**Issue by john-crouch** [MicrosoftDocs/azure-devops-docs#14004]
The "Unconfigure Search on a separate server" section (https://learn.microsoft.com/en-us/azure/devops/project/search/install-configure-search?view=azure-devops-2022#unconfigure-search-on-a-separate-server) is incomplete. The first and only step listed is "Go to the Manage Extensions page for each collection in your Azure DevOps Server instance." 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b81d598-df12-9ef1-9821-71f240b5d0e9
* Version Independent ID: 9814578c-72d2-d0da-a0fb-051eab0b9bd9
* Content: [Install, configure Search - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/search/install-configure-search?view=azure-devops-2022#unconfigure-search-on-a-separate-server)
* Content Source: [docs/project/search/install-configure-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/search/install-configure-search.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-search**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @john-crouch. There was a misplaced moniker, but I fixed it, so the remaining steps should be live shortly. Thanks again and have a great day!
