### ISSUE TITLE
Typo in third paragraph in page

### ISSUE THREAD

**Issue by markfaction** [MicrosoftDocs/azure-devops-docs#14003]
- Typo in third paragraph of page content (sentence - "For mroe information, see About access levels")
- Word 'mroe' should be 'more'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cda88f5-9302-af6e-273e-a81e6bef119f
* Version Independent ID: 4a0c729a-60ac-7f9f-829b-30008c93676a
* Content: [Default Wiki and social tool permissions - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/wiki-readme-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-readme-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/wiki-readme-permissions.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @markfaction, thanks so much for the heads up! The fix should go live shortly. In the future, if you're interested, we'd love for you to [contribute to our docs](https://learn.microsoft.com/en-us/contribute/)! It's fast and easy and we love it. Thanks again!

**Comment by markfaction** [comment]
Thanks @chcomley, will do so in the future :)
