### ISSUE TITLE
document out of date: macos-14 agent now available

### ISSUE THREAD

**Issue by frankfuu** [MicrosoftDocs/azure-devops-docs#14019]
According to the [azure hosted agents software page](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software), it says that macos 14 is not available, however, according to the [runner images page](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md), it says macos 14 is available.

**Comment by steved0x** [comment]
@frankfuu macOS-14 is not yet rolled out and available for Azure DevOps Services, but it should be very soon. As soon as it is, we will update the page (we already have the PR ready, just waiting to publish it)
