### ISSUE TITLE
pass once flag through docker command

### ISSUE THREAD

**Issue by lausserl** [MicrosoftDocs/azure-devops-docs#14014]
I discovered, that for passing the --once flag with the "docker run" command, the ENTRYPOINT has to be formatted this way:
`ENTRYPOINT [ "./start.sh" ]`
Otherwise the --once flag does not work when passing it via docker run

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/docker.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This will be updated today. Thank you.
