### ISSUE TITLE
easy way to only see yaml details (and hide any classing detail)

### ISSUE THREAD

**Issue by CharlyAndersonUK** [MicrosoftDocs/azure-devops-docs#14015]
There should be an easy way to only see Yaml pipelines. I have not used the older classic pipelines and I have not desire to, nor to I want to know about them. For many pages it takes a while to check on if the detail is about classic or yaml, just because you are coming from knowing about classic, it does not mean your reader has that background or is interested in that history

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c94beb75-1aa5-e9dc-fa49-0633f9fbea1f
* Version Independent ID: 413cc693-e9c5-37aa-00fa-d0267e53de5e
* Content: [Control deployments with release approvals - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/release/approvals/approvals.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-release**
* GitHub Login: @silviuandrica
* Microsoft Alias: **sandrica**

**Comment by WilliamAntonRohm** [comment]
@CharlyAndersonUK -- Charly, thank you for your feedback.  We are adding it to our internal backlog.
