### ISSUE TITLE
Mermaid ES Diagram would be nice

### ISSUE THREAD

**Issue by navistar2022** [MicrosoftDocs/azure-devops-docs#14018]
[I really like the option of adding the mermaid diagrams, but the most useful one - ES Diagram - isn't included. Mermaid ER diagram is one of the best tools for mapping out tables and fields before I actually start building them]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@navistar2022 -- thank you for your feedback.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
