### ISSUE TITLE
Agent version 3.x is supported on Azure DevOps Server 

### ISSUE THREAD

**Issue by kripa-2019** [MicrosoftDocs/azure-devops-docs#14012]
[Enter feedback here]

In the blue highlighted section which states : 
Important

This article provides guidance for using the [3.x agent software](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops) with Azure DevOps Services. If you're using Azure DevOps Server or TFS, see [Self-hosted Windows agents (Agent version 2.x)](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows-agent?view=azure-devops).

This is misleading, suggesting to Customers that 3.x Agent version is not supported on Azure DevOps Server whereas it is in fact supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfd11746-d49c-f249-38a5-c7ddf0863ffe
* Version Independent ID: cfd11746-d49c-f249-38a5-c7ddf0863ffe
* Content: [Deploy an Azure Pipelines agent on Windows - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/agents/windows-agent.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/windows-agent.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@kripa-2019 -- Kripa, thank you for your feedback.

@steved0x -- Steve, I would have just updated that paragraph, but I'm not what else may be affected by this change.

**Comment by steved0x** [comment]
@WilliamAntonRohm @kripa-2019  Thank you, I need to verify but I don't believe the 3.x agent is officially supported on Azure DevOps Server until the first release that includes that agent version (even though I am personally running it on my personal Azure DevOps Server 2022 installations)

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
