### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by csanghavi** [MicrosoftDocs/azure-devops-docs#14023]
I think following section needs correction:

Under **Development and Use Cases** section of this page
  First bullet point text should be
      Accelerating application development and deployment lifecycles.

Currently, it is Accelerating application development and **development** lifecycles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d936891e-731a-c6f0-c0a2-dcaa9dfb81df
* Version Independent ID: d936891e-731a-c6f0-c0a2-dcaa9dfb81df
* Content: [Azure Pipelines baseline architecture - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/architectures/devops-pipelines-baseline-architecture?view=azure-devops)
* Content Source: [docs/pipelines/architectures/devops-pipelines-baseline-architecture.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/architectures/devops-pipelines-baseline-architecture.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @mijacobs
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks! We will make this update shortly.
