### ISSUE TITLE
Single back-ticks incorrectly being displayed in example links.

### ISSUE THREAD

**Issue by cfframe** [MicrosoftDocs/azure-devops-docs#14021]
Unlike the examples under "Supported links for Welcome pages", the examples under "Supported links for Markdown widget" and "Supported links for Wiki" display back-ticks (see pic).  I suspect this is unintentional and that the back-ticks have been inadvertently escaped.

![Markdown single back-tick example](https://github.com/MicrosoftDocs/azure-devops-docs/assets/3910544/188c738a-d6f8-4f6b-9e11-4831dde9d85a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for your feedback. I've updated the article, which should be live shortly!
