### ISSUE TITLE
Example markdown incorrectly shows triple back-ticks

### ISSUE THREAD

**Issue by cfframe** [MicrosoftDocs/azure-devops-docs#14020]
Example text "\`\`\`To install the Microsoft Cross Platform Build & Release Agent, run the following: \`$ sudo npm install vsoagent-installer -g\`.
\`\`\` " should not display the bracketing triple back-ticks in the example box itself.  Using these gives a different result from that shown - the first set of triple back-ticks ends up being displayed as it becomes separated from the next set with the single back-ticks that bracket the code. Another side-effect is that text following the second set of back-ticks is interpreted as being a block of code.

I've seen these markdown effects in Azure DevOps and VSCode. See pic for example effect.

![Markdown triple back-tick example](https://github.com/MicrosoftDocs/azure-devops-docs/assets/3910544/9fea6fd6-c875-4e99-a5d2-8d9eae1fe036)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, wikis - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops&source=docs)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-wiki**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback. I moved the 3 backticks at the end of the example to the same line, and it now renders properly. This update should be live shortly.
