### ISSUE TITLE
Page outdated 

### ISSUE THREAD

**Issue by whmms** [MicrosoftDocs/azure-devops-docs#14024]
This page is more than 1 year old and the screenshots of the ADO UI is no longer the same

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcf0e2ac-c706-a08d-c667-ecbd073a8fdb
* Version Independent ID: 2b3a8b16-e689-8cc5-3134-af72f351e08d
* Content: [Build and push Docker images to Azure Container Registry with Docker templates - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/ecosystems/containers/acr-template.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @geekzter
* Microsoft Alias: **ericvan**

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
