### ISSUE TITLE
Permissions Do Not Work Correctly

### ISSUE THREAD

**Issue by tjmccurdy-arhaus** [MicrosoftDocs/azure-devops-docs#14031]
I am curious why DevOps decided to do permissions totally differently than all other Microsoft products.  For example, all other MS products, if a user is given access to a low-level permission set, then later, added to a higher-level permission set (more privileged access), that user will be afforded the compounded permissions based on ALL his/her access rights.  However, DevOps does the exact opposite and there are several issues (these are a few):

1. If I am a Project Admin, and I "accidentally" get added to a "Team" which has limited access, my rights are REDUCED and I no longer have the ability to be a Project Admin.  I then have to find all the Teams I am a part of and remove myself in order to get Project Admin permissions again.
2. If I add a user to a Team, but then later decide to give them more privileged access, such as being able to control Pipelines, or being able to manage Branches, this user will NOT acquire any of those rights, and will instead be stuck with "least privileged access" permissions instead of gaining the new permissions I've given them.  Until I completely remove that user from all Teams, clear out ALL of their other permissions and then FINALLY create a whole entire Team/Group for them to be in and assign the appropriate permissions... only then does the user get the access they need - but then they lose all other access to the other teams.

No one understands why DevOps does permissions like this.  Why doesn't it work the same way as AD Groups / MS Entra?  It's terribly confusing!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34a09840-ed5d-8a72-cb80-20bac219e065
* Version Independent ID: 8a686d5e-af9f-e269-2603-f122ab964d86
* Content: [User and permissions management FAQs - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management?view=azure-devops&source=docs)
* Content Source: [docs/organizations/accounts/faq-user-and-permissions-management.yml](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/faq-user-and-permissions-management.yml)
* Service: **azure-devops**
* Sub-service: **azure-devops-organizations**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@tjmccurdy-arhaus -- thank you for your feedback.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
