### ISSUE TITLE
Clarify the which role - Add users to Azure Pipelines

### ISSUE THREAD

**Issue by cblomart** [MicrosoftDocs/azure-devops-docs#14039]
title | description | ms.assetid | ms.topic | ms.date | monikerRange
-- | -- | -- | -- | -- | --
Add users to Azure Pipelines | Add users to Azure Pipelines and set permissions. | DCEDB5E6-B6FB-4814-B3B9-F688094EA88B | conceptual | 06/03/2021 | <= azure-devops

https://learn.microsoft.com/en-us/azure/devops/pipelines/policies/set-permissions?view=azure-devops

At the begining of the doc:
"You can manage security for different types of resources such as variable groups, secure files, and deployment groups by adding users or groups to *that role*. Project administrator can grant or restrict access to project resources. If you want to allow a team member to edit pipelines, you must be a project administrator in order to do so."

What is "*that role*" ? Should it be project administrator?

**Comment by steved0x** [comment]
I am updating that sentence to say "You can manage security for different types of resources such as variable groups, secure files, and deployment groups by granting permissions to that resource to users or groups.". The process is described in the next section of the article. This change should be live by later today.
