### ISSUE TITLE
Escaping double quotes in search is not working as described 

### ISSUE THREAD

**Issue by jschultz-grimmway** [MicrosoftDocs/azure-devops-docs#14032]
escaping " with \ does not seem to work correctly. This is the exact string I am looking for "managers/" so I do this "\"managers/\"" and it still finds all instances of managers without any quotes or forward slash....

Special characters

Escape the special characters (, ), [, ], :, *, and ? by enclosing them in a phrase delimited with double-quotes.
Include special characters in a search string, or search specifically for special characters, according to the following rules:
CodeA23?R finds files containing words that start with CodeA23
Have any alphanumeric character next, and end with R. For example, CodeA234R and CodeA23QR.
Search for any special character that isn't a part of the query language.
"flatten()" finds the literal string flatten(). Search for a literal occurrence of the double-quote character " by preceding it with the escape character \ and enclosing the search string in double-quotes.
"\"react-redux\"" finds the literal string "react-redux."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 883f11d6-35f4-c682-8256-dc6a0f8aa31b
* Version Independent ID: e755bc82-a445-7b24-ae06-0e7af0c2d7f3
* Content: [Search across Azure DevOps - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/project/search/get-started-search?view=azure-devops)
* Content Source: [docs/project/search/get-started-search.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/search/get-started-search.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-search**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@jschultz-grimmway -- Jake, please try this search string:  `"\"managers/\""`
