### ISSUE TITLE
Replace and join expressions return null when the match not found

### ISSUE THREAD

**Issue by hima-gadupudi** [MicrosoftDocs/azure-devops-docs#14048]
Hi I have a variable,

images: "genevafluentd_td-agent,genevamdm,kured". I am trying to use each expression on jobs
jobs:
          - ${{ each image in split(variables.images, ',')}}:
              #- job: ACR_${{ replace(variables.image,'-','_') }}_Replication
              - job: ACR_${{ join('_', split(variables.image,'-')) }}_Replication
                displayName: ${{ image }}_ImageReplication

It works as expected when the image name is: "genevafluentd_td-agent". When it is iterating over "genevamdm" and "kured" values, replace and join returns null.

**Comment by TimShererWithAquent** [comment]
@hima-gadupudi Does this issue refer to a specific article?
