### ISSUE TITLE
Create Azure Virtual Machine Scale Set agents incorrect instructions regarding unmanaged disks

### ISSUE THREAD

**Issue by ThomasHeijtink** [MicrosoftDocs/azure-devops-docs#14050]
The issue is regarding [this](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops) article.

And specifically [this](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-scale-set-with-custom-image-software-or-disk-size) chapter.

It states that in order to create scale set agents we must create a VM with an unmanaged disk. However, in [this](https://learn.microsoft.com/en-us/azure/virtual-machines/unmanaged-disks-deprecation) article it states that unmanaged disks will be retired.

Please provide correct instructions on how to create a VM for scale set agents without resorting to unmanaged disks.

Thank you!

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
