### ISSUE TITLE
Do Self-hosted Linux agents support Oracle Linux?

### ISSUE THREAD

**Issue by stefania-tsvetkova** [MicrosoftDocs/azure-devops-docs#14054]
For the [Self-hosted Linux agents (2.x)](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/v2-linux-agent.md#check-prerequisites) the list of supported Linux distributions included **Oracle Linux 8, 7**. In contrast, for the [Self-hosted Linux agents (3.x)](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/linux-agent.md#check-prerequisites) the list of supported Linux distributions doesn't include any **Oracle Linux**. 

However, the information about the upgrade from version 2 to version 3 in the [Agent software version 3 wiki page](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/v3-agent.md#upgrade-to-3x-agent-on-supported-operating-systems) includes this:
> If you're running your self-hosted agents on newer operating systems [supported by .NET 6](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md), the upgrade to the new agent version is automatic.

**Oracle Linux 7+** is supported by **.NET 6**, so based on the quoted sentence, if **Self-hosted Linux agents (2.x)** were used with **Oracle Linux 8, 7**, their upgade to **Self-hosted Linux agents (3.x)** should have been authomatic - it sounds like **Oracle Linux 8, 7** should still be supported.

Could you please confirm that **Self-hosted Linux agents (3.x)** support **Oracle Linux**? If yes, are the supported versions still 8 and 7 or is version 9 supported as well?

**Comment by stefania-tsvetkova** [comment]
Hello, @steved0x ! Do you have any update on the topic?

**Comment by steved0x** [comment]
@stefania-tsvetkova I will find out and should have an answer by today or first thing tomorrow morning.

**Comment by steved0x** [comment]
I don't have an answer yet but we will get one.

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
