### ISSUE TITLE
Pipeline Example

### ISSUE THREAD

**Issue by Varorbc** [MicrosoftDocs/azure-devops-docs#14064]
Documents miss pipeline examples and best practice examples.

If you can provide a series of examples such as how to build .NET, publish nuget package, publish docker image, deploy to K8S and other series of example code.

**Comment by juliakm** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
