### ISSUE TITLE
Max size is missing

### ISSUE THREAD

**Issue by cloudmelon** [MicrosoftDocs/azure-devops-docs#1520]
I tested Git LFS for a site of 20G,  the first time I want to commit all the files with LFS it didn't working. There is ' adding files error' .  I think it would be appreciable to mention the maximum size of the file to commit while using Git lfs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d0afd1-bce9-b05e-ff1d-2914f63e2884
* Version Independent ID: 4b69aa48-977c-cf18-bd30-17185814c8e5
* Content: [Work with large files in your Git repo](https://docs.microsoft.com/en-us/vsts/repos/git/manage-large-files?view=vsts)
* Content Source: [docs/repos/git/manage-large-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-large-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@cloudmelon I'll find out and get it added to the article, and reply here.

**Comment by hsluoyz** [comment]
Our team is also interested in this issue. Any update? Thanks.

**Comment by cloudmelon** [comment]
Hi Yang Guo, thank you for asking. Actually, It seems that Git LFS is only a “ Mega level “ tool while transferring files from local PC to remote server. Since I was facing a “ Gega level “ challenge , so I tried FileZilla ( yes very traditional way ) to transfer 20 G files ( Videos and static files such as css, pictures, js etc... now my website works well... let me know if you need any other updates :)

**Comment by jeffyoungstrom** [comment]
It would still be useful to know the maximum size of files that can be committed with LFS. Especially since the error message when a file is too big appears to be quite cryptic:

LFS: Client error: from https://dev.azure.com/myinstance/path_to_lfs_link_for_big_file HTTP 413

I just had a 278MB file fail in this way. This seems like a pretty small limit though, so maybe there's some other reason for this failure. I had a 120MB file succeed.

**Comment by erichfrazer** [comment]
I am seeing the same issue. pushing 240MB file, getting HTTP 413 error

**Comment by ssa3512** [comment]
I was able to determine a ~120MB file size limit using this method:

- Create new azure devops git repository
- Run the following powershell in an emtpy folder
```
git init
git lfs install
git remote add origin [remote url]
git lfs track *.bin
git add -A
git commit -m "Initial Commit"

for ($i = 10; $i -le 350; $i += 10) {
    Write-Host $i
    fsutil file createnew $("testfile_" + $i + "MB.bin") ($i * 1024 * 1024)
    git add -A
    git commit -m "Added $i MB file"
    git push origin master
}
```
This generates arbitrary files in increasing 10MB steps. A 120MB file will push fine, but a 130MB file and anything larger fails with an HTTP 413 error.

This seems like a crazy low limit for Git LFS as GitHub supports files up to 2GB.

**Comment by jeffyoungstrom** [comment]
I've submitted a Developer Community problem report for this issue. Please go upvote it if you are also affected by this limitation

https://developercommunity.visualstudio.com/content/problem/891932/azure-repos-git-lfs-file-size-limited-to-120mb.html

**Comment by cloudmelon** [comment]
Thanks all 😊

Melony QIN

**Comment by ssa3512** [comment]
This is a bug due to HTTP2. There are workarounds here: https://developercommunity.visualstudio.com/content/problem/862165/cant-push-large-git-lfs-files-to-repository-from-p.html and in #4179
