### ISSUE TITLE
Branch policy triggers missing section about 'Path Filters'

### ISSUE THREAD

**Issue by TekSiDoT** [MicrosoftDocs/azure-devops-docs#1521]
This seems a little outdated, VSTS options for branch policiy PR validation have extended to include a 'Path Filter'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/repos/git/branch-policies?view=vsts)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Karsonic** [comment]
In the meantime does anyone have an example of how to only exclude a particular directory?

**Comment by TclasenITVT** [comment]
` !/Test`
to exclude the Test Directory

**Comment by geevensingh** [comment]
That does not seem to work.

**Comment by TclasenITVT** [comment]
To cite the tooltip:

> If a path filter is set, the policy will only apply when files which match the filter are changed. Leaving this field blank means that the policy will always apply.
> 
> You can specify absolute paths and wildcards 
> Example: /WebApp/Models/Data.cs, /WebApp/*, or *.cs
> 
> You can specify multiple paths using ";" as a separator
> Example:
> /WebApp/Models/Data.cs;ClientApp/Models/Data.cs
> 
> Paths prefixed with "!" are excluded
> Example: /WebApp/*;!/WebApp/Tests/*
> 
> Order is significant

**Comment by Eddie-Hartman** [comment]
How do I ignore a single file?
*;!README.md does not work.
/*;!README.md does not work.

**Comment by Zhaph** [comment]
I found a comment on [an issue](https://developercommunity.visualstudio.com/content/problem/406365/tfs-20182-path-filters-not-working-correctly-in-br.html) that appears to solve the problem:

> Your first example is not going to work because if you apply a filter, we automatically exclude all files. [...] you aren't including anything, so that is why nothing runs.

You have to include everything, and then exclude the files/folders you don't want. This isn't clear from the tooltip.
