### ISSUE TITLE
Reconcile

### ISSUE THREAD

**Issue by GregB-Roberts** [MicrosoftDocs/azure-devops-docs#1561]
Please document the reconcile command and any setting changes it produces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd4706b5-aa61-ac24-6b0b-bf21522aa382
* Version Independent ID: 9e60aa55-6d5a-90d7-eb5a-e8e9072ee987
* Content: [Resolve Command](https://docs.microsoft.com/en-us/vsts/repos/tfvc/resolve-command?view=vsts)
* Content Source: [docs/repos/tfvc/resolve-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/resolve-command.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan
