### ISSUE TITLE
Singular folder names rather than plural

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/azure-devops-docs#1564]
consider aligning with standard gitflow naming and use singular rather than plural folder names e.g. bugfix, release and feature rather than bugfixes, releases and features. more letters, longer branch names, more typing = :( 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330532da-d568-b010-a154-62afb1844e4a
* Version Independent ID: 4efad37d-4ec2-033e-51b1-b9f588e675c6
* Content: [Require branches to be created in folders](https://docs.microsoft.com/en-gb/vsts/repos/git/require-branch-folders?view=vsts&tabs=vsts-tfs-web-portal)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/require-branch-folders.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by o-o00o-o** [comment]
this is a small quick change I think so not sure why it has gone stale?

**Comment by IeuanWalker** [comment]
Makes sense, branches should be for a single thing
