### ISSUE TITLE
Minimum TFS Version for Multiple version layout

### ISSUE THREAD

**Issue by huserben** [MicrosoftDocs/azure-devops-docs#1568]
Hi

is there a minimum version of TFS that is required to support the multiple version layout of an extension? I couldn't find any info on this. Background is that I changed my extension to the multiple version layout and it seems to have created a problem at least for a on prem TFS 2017 Update 1 installation.
See as well the following comment in the original issue: https://github.com/huserben/TfsExtensions/issues/90#issuecomment-413777117

If there is a minimum version needed it would be nice to have it in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83f7acc5-1222-7216-571b-913fa63298e4
* Version Independent ID: 15b2e074-4a8d-9ac8-8aa8-56a0c11be534
* Content: [Custom build/release task reference](https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts#bundle-multiple-versions-of-buildrelease-tasks-within-one-extension)
* Content Source: [docs/extend/develop/build-task-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/build-task-schema.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
@willsmythe hey Will, do you know if there is a minimum TFS version requirement to have multiple version layout of an extension?

**Comment by elbatk** [comment]
Hey @willsmythe , pinging here again to do some backlog cleanup, do you know if our multiple version layouts require a certain version of TFS?

**Comment by willsmythe** [comment]
You would need to check with the Build team (i.e. bryanmac). I vaguely recall this feature being introduced in/after TFS 2017 U2. Once you find the answer, we should update the docs with this. Might also be good to show how developers can set the "installation targets" (in the extension manifest) to limit the extension to only the versions of TFS it is supported in.
