### ISSUE TITLE
Identity Variables not setting correctly in Git with CI trigger?

### ISSUE THREAD

**Issue by rigratz** [MicrosoftDocs/azure-devops-docs#1866]
I'm using VSTS/Azure DevOps with CI from GitHub, and I'm running into a problem where I want to disable certain task groups of a build definition based on who committed the changes in GitHub. According to the docs:

"If the build is triggered... In Git or TFVC by the Continuous integration (CI) triggers Then the Build.RequestedFor and Build.RequestedForId values are based on... The person who pushed or checked in the changes."

... but I have found that this isn't the case, they are being populated with the same service identity values as the Build.QueuedBy variables. Is this an issue with the docs, an actual issue with the way variables are set, or potentially something on my end? I've been wrestling with this for a while now and figured this would be the best place to ask.

**Comment by iandvt** [comment]
Any traction on this issue @DavidStaheli?

**Comment by iandvt** [comment]
Any update on this issue @DavidStaheli?

**Comment by DavidStaheli** [comment]
Hi @iandvt.  Thanks for reporting this and I apologize for the delayed reply.  We're tracking this as a bug and I've made a note to reply here as soon as progress is made.

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by kim76** [comment]
Hi, I'm also trying to retrieve the user identity from Git but Build.RequestedFor and Build.QueuedBy both give me `GitHub` on my PR build.

**Comment by lalitkhoslarogers** [comment]
Hi,  

Is this issue resolved yet ? We are facing the same issue. On check in to Git repo.. It gives Github always

**Comment by Shaked** [comment]
Hey, any update about this issue? We are facing the same problem.

Triggering a CI/CD through a `git push` sets the `Build.RequestedFor` and `Release.RequestedFor` to `Microsoft.VisualStudio.Services.TFS` instead of the user that pushed the triggering commit.

**Comment by josch83** [comment]
I encounter the same as @Shaked, `Microsoft.VisualStudio.Services.TFS` with pipeline-triggered pipelines. `Build.RequestedForEmail` is null in that case. What is interesting: This seems to happen only for some users, means some user always are correctly resolved if they make a commit.

**Comment by donovanvanheerden** [comment]
I just ran into this same problem, any update on this?

Hoping to figure out if I need to set something so `Microsoft.VisualStudio.Services.TFS` gets replaced with actual commit author name...

**Comment by danlangford** [comment]
This would be a very nice thing to be fixed. Watching the issue intently

**Comment by metaswirl** [comment]
The same situation happens for https://dev.azure.com/apache-flink/apache-flink/_build

Is this something that can be fixed by changing the configuration?
