### ISSUE TITLE
Missing the button on m visual studio 2017, Still needs work

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/azure-devops-docs#1920]
The above, closed comment I think is pointing out a very confusing aspect of the Git support in VS. The gist of the response is that GitHub Extension for VS is different than Git support in VS and hence you see different views. But that is only partially true and/or the rules are confusing. Caveat: I have GitHub Extension for VS installed because I work with both VSTS Git repos and GitHub repos. Here's what I see.

1) Using Team Explorer go to the connections and then manage connections.
2) It pops up the list of repos in VSTS so select one.
3) You are now in VSTS "mode". You have the options mentioned in this document.

1) Using the command line clone a different repo from the same VSTS account.
2) Now open it in VS.
3) You are now in non-VSTS mode. You don't have the options listed earlier.

The only difference between these 2 modes is whether you used managed connections in VS. To verify that it is the same repo you can make changes, create branches, etc.

1) Go to manage connections.
2) Find the repo you are currently in and have made changes to.
3) Connect to it.

VS recognizes it is the same repo so everything is the same. But now you're back in VSTS mode so you have access to PRs and whatnot. The only change from before was you used VS's managed connection option to "connect" to the repo that was already cloned on your machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc40b8e-8a81-8213-d98e-a2c39d615f14
* Version Independent ID: 6d175def-aa48-ff2a-614f-4e9cf3324537
* Content: [Get started with Git and Visual Studio 2017 - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/gitquickstart?view=vsts&tabs=visual-studio#share-your-changes)
* Content Source: [docs/repos/git/gitquickstart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/gitquickstart.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@CoolDadTx Do you think we should add a note about using the Manage connections to connect to the already cloned repo from the command line to the doc - would that help folks? I am forwarding this feedback on the Visual Studio Team Explorer folks, but if you think a note would help I can get that added to the doc pretty quick? Thank you for the detailed post.

**Comment by CoolDadTx** [comment]
@steved0x, I think it would be good to put a note in the docs about it for now. Thanks.
