### ISSUE TITLE
Update 20180223 and applicable for On-Premise TFS 2017

### ISSUE THREAD

**Issue by cmontalbo** [MicrosoftDocs/azure-devops-docs#198]
Additional Updates. I setup "On-Premise" TFS 2017 with Slack. These are additional configuration to make it work. The major concept is that you map the TFS project to the Slack channel using web hooks. 

In web based Slack, the configuration can now be done in the application. Once the App (Visual Studio Team Services) is added to your channel. Click on it and then go to Settings. In Configurations, click on the pencil (bottom-right). You can then scroll down for the Webhook URL. In On-Premise TFS 2017, go to the web portal for TFS and follow the instruction mentioned here. You can only do this if you have the right permission. In this case, I have administrative permission.  Inside TFS 2017, you can run “Tests” and it should show the notification.  The notification is not only limited to Build completion but even when a comment is updated and many more.  Hope this helps - CM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* [Content](https://docs.microsoft.com/en-us/vsts/service-hooks/services/slack)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/slack.md)
* Service: unspecified

**Comment by elbatk** [comment]
Thanks @cmontalbo ! Looking into making this change ASAP!

**Comment by ScottHutchinson** [comment]
This article should indicate whether it applies to TFS 2018 or not. If not, it should suggest an alternative for messaging with an on-premises TFS 2018 system. Thanks!

**Comment by jnm2** [comment]
> In web based Slack, the configuration can now be done in the application. Once the App (Visual Studio Team Services) is added to your channel. Click on it and then go to Settings. In Configurations, click on the pencil (bottom-right). You can then scroll down for the Webhook URL.

@cmontalbo Slack has changed, or the free version is missing something. It doesn't appear to be possible to follow a current equivalent to these directions. Would you please update the instructions?

**Comment by mijacobs** [comment]
Assinging to @aaronhallberg, the current owner of the article.

**Comment by mijacobs** [comment]
Assigning to @aaronhallberg, the current owner of the article.
