### ISSUE TITLE
Needs update for version.

### ISSUE THREAD

**Issue by RajRKumar** [MicrosoftDocs/azure-devops-docs#2008]
Can you please update the document for "Azure DevOps" and "Xcode 10".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9dd5174-b1b4-575f-5985-adf603fd772e
* Version Independent ID: b8b070c3-2972-2e0f-b675-0033f6d741c0
* Content: [Share your Xcode project with Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/share-your-code-in-git-xcode?view=vsts)
* Content Source: [docs/repos/git/share-your-code-in-git-xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/share-your-code-in-git-xcode.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by azav** [comment]
It is not stale.  This documentation is outdated as of Xcode 9.
