### ISSUE TITLE
Documentation could use some improvement.

### ISSUE THREAD

**Issue by vadimcn** [MicrosoftDocs/azure-devops-docs#2163]
The inputs like `project`, `pipeline` and `buildId`  could use some explanation of where to find them and some examples.  I had to discover all that by trial and error.  The latter was especially bad: I tried passing build# that Azure Pipelines UI prominently displays (e.g.  `20181020.2`), but it turned out that this task wanted the numeric value from build page's URL (which is the only place it is shown, as far as I can tell).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by alexmullans** [comment]
@steved0x can you route this over to pipelines? Artifacts owns the new Pipeline Artifacts task and docs but Pipelines owns the older Download Build Artifacts task.

**Comment by TroySchmidt** [comment]
I had to find project by sniffing the network traffic and looking for it in the API calls that DevOps was doing behind the scenes.  I would have thought somewhere in the project settings I could find that GUID displayed.

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs?  If so, could you please assign this issue appropriately?

**Comment by Lovakumar** [comment]
@DavidStaheli Please assign this to me.

**Comment by andyjlewis** [comment]
@steved0x would you please invite @Lovakumar to this repo?

**Comment by elbatk** [comment]
Checking in here, I think the goal is to add @Lovakumar to this repo so they can own this GHI, checkin' in on ya for help here @steved0x :)

**Comment by mijacobs** [comment]
Closing this issue because it's been inactive for more than a year. If the issue still needs addressed, please reopen it.
