### ISSUE TITLE
Incorporate New Release Extension Points

### ISSUE THREAD

**Issue by ijabit** [MicrosoftDocs/azure-devops-docs#2292]
Add new release extension points as shown here: https://docs.microsoft.com/en-us/azure/devops/pipelines/preview/new-release-summary?view=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=vsts#service-hooks)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @ijabit , thank you! This is definitely on the radar for docs work in the extensions area. Adding @matthewisabel for awareness that we have another +1 to that :)

**Comment by chcomley** [comment]
Hi @ijabit, Please accept our apology for losing sight of this issue. There is a more recent issue for this article, however, which I've added your feedback to so we can be sure it's properly addressed. I'm closing this issue, so please reference [this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7728) and you can @mention me if you have any further questions or concerns.  
We understand how frustrating out-of-date or incomplete documentation; to fix these issues, we're working on a complete overhaul of this area. We're in the beginning phases of that work now.
Thank you!
