### ISSUE TITLE
Please elaborate on 'comment resolution drop-down', provide a link

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/azure-devops-docs#2328]
I often find myself explaining to PR authors and reviewers how to use the status filed of a PR comment (Active, Pending, Resolved, Wont Fix, Closed) so I'd like to 1) be able to provide a link to the section of this page that describes these values. 2) See more written about how to use them; for example, as a code author, convert a comment from "Active" to "Pending" when you plan to address the feedback, and change it to "resolved" once you post a new iteration that addresses the comment. And when resolving "won't fix" explain why in the comment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=vsts&tabs=new-nav#leave-comments)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ChrisGuzak There is a small section on comments down on that page here:

https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=vsts&tabs=new-nav#leave-comments

It is quite a large topic and it might be helpful to divide it into smaller groupings. I'm sending you an email for the other issues.

**Comment by ChrisGuzak** [comment]
@steved0x is this something you will be able to address?

**Comment by Aviw13** [comment]
If someone still need this: [Review pull requests => Use comments => Change comment status](https://learn.microsoft.com/en-us/azure/devops/repos/git/review-pull-requests?source=recommendations&view=azure-devops&tabs=browser#change-comment-status)

- **Active**: the default status for new comments.
- **Pending**: the issue in this comment is under review and awaits something else.
- **Resolved**: the issue in this comment is addressed.
- **Won't fix**: the issue in this comment is noted but won't be fixed.
- **Closed**: the discussion in this comment is closed.

For me just not clear why I can complete a PR when all the comments are resolved but not closed. What is the meaning of the **Closed** status when it is not taken into account by the system
