### ISSUE TITLE
Triggering a build from a webhook

### ISSUE THREAD

**Issue by falconmick** [MicrosoftDocs/azure-devops-docs#2366]
I have a statically rendered GatsbyJs app that I want to trigger deployment for when my CMS service prismic sends out it's webhook on content changing as my static files don't magically update!

Is there any way to trigger a pipeline via a webhook?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-gb/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by phatcher** [comment]
@falconmick, If it can't you could write a Azure Function which is triggered by the webhook, that can call the Azure DevOps REST API to trigger the build, issue is how you get the PAT in there securely.

**Comment by aniketprashar** [comment]
I have done this using function app. If u need any help I'll prepare a short tutorial for u

**Comment by phatcher** [comment]
@aniketprashar  Thanks, that would be helpful

**Comment by Abdulhakimsg** [comment]
> I have done this using function app. If u need any help I'll prepare a short tutorial for u

Hi aniketprashar , that would be awesome! i have been stuck on this problem for a long time!

**Comment by aniketprashar** [comment]
@Abdulhakimsg @phatcher I'll share it before monday (IST)

**Comment by aniketprashar** [comment]
@Abdulhakimsg @phatcher I'll share it before monday (IST)

**Comment by aniketprashar** [comment]
Hi @Abdulhakimsg @phatcher Really sorry for the delay...I'm extremely busy...can u please mail me @aniketprashar@hotmail.com for ur queries. I'll try to explain u what i have done.

**Comment by sheldonj** [comment]
@aniketprashar Any chance this happened. I'm in the same boat. Trying to trigger an Azure DevOps build from a webhook via GraphCMS.

I get that I will need to build a function app. Just not sure how to actually get the build churning from the function app.

**Comment by mcdafydd** [comment]
@aniketprashar @sheldonj I also needed this and hacked together an example in my fork of https://github.com/mcdafydd/go-azuredevops/tree/master/examples/webhook.  This example uses a "code pushed" event webhook from an Azure Devops team project and then queues a build in that same project.  You could pull the Builds.Queue() portion out of the code and give it a try.  One thing to note is that you need to supply the build ID in the API calls.

The az cli also supports triggering a build (`az pipelines build queue -h`)  It does a GET request to pull the build ID number from the supplied name first.

Best of luck!

**Comment by trickydisco78** [comment]
hi, I',m also wanting to do this. trigger a gatsby build from a webhook from prismic.

**Comment by spiraljacobs** [comment]
Ditto - any way to do this?
Want to trigger a build when content is pushed to prismic.

**Comment by bitsofinfo** [comment]
Same need

**Comment by aniketprashar** [comment]
Please refer to https://levelup.gitconnected.com/trigger-a-pipeline-using-webhook-586a664addd7

**Comment by aniketprashar** [comment]
@phatcher @falconmick @sheldonj @steved0x @bitsofinfo @trickydisco78 @Abdulhakimsg @mcdafydd

**Comment by danquirk** [comment]
I think the webhook resource type would do this now https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema

**Comment by eimerreis** [comment]
@danquirk Thanks a lot for pointing this out. Works for me!

**Comment by shrknt35** [comment]
@eimerreis how did you get this to work?

**Comment by gioce90** [comment]
I think this issue can be closed now. 

I can trigger an Azure Pipeline exactly how is described [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update?WT.mc_id=DOP-MVP-21138#generic-webhook-based-triggers-for-yaml-pipelines).

So
1. Create the new Incoming WebHook service in Service connection on Azure DevOps.
2. Include the new resource in the yaml of the choosen pipeline
3. Call with Postman this URL:
`POST https://dev.azure.com/<orgName>/_apis/public/distributedtask/webhooks/<WebHook Name>?api-version=6.0-preview`
with `Content-type:application/json` and an empty `{}` body.

Works well.
