### ISSUE TITLE
Provide some UI screens on how these would look and some usecases..

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/azure-devops-docs#2573]
No Screenshots.. its boring to read toomuch of text without knowing how the output looks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5515c697-786f-e5d2-60fa-a62192c2e9c1
* Version Independent ID: 1fc22c8f-1b7b-32fa-0ec2-05e0b741103e
* Content: [Use the Grid Control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/grido?view=vsts)
* Content Source: [docs/extend/develop/ui-controls/grido.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/grido.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by zankhanarana9** [comment]
That's true. Having some use case would be good.

**Comment by elbatk** [comment]
Hi @mganeshphani , thank you for the feedback. It may be a while before we get to updating this, but I completely agree. I'll add something to the backlog to get to when we have cycles.

**Comment by elbatk** [comment]
I haven't forgotten here, I agree we need to update a lot of our extensibility docs. Adding @matthewisabel for awareness.

**Comment by chcomley** [comment]
Hi @mganeshphani, I've added a tip within the article, containing a link to another site, which contains UI examples. Here it is for your reference: [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/). Thank you.
