### ISSUE TITLE
The variable after 'connectedService:' is not clear

### ISSUE THREAD

**Issue by xtu** [MicrosoftDocs/azure-devops-docs#2622]
In the `FabrikamService` input object of the task, the 'Fabrikam' in 'connectedService:Fabrikam' is actually the name of the endpoint, which is 'fabrikam' as declared in the contribution. The first letter is not in the same matching case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=vsts)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by almmechanics** [comment]
Agreed, since this is one of the default examples, highlighting the importance of the `connectedService` attribute and how it bridges between `endpoints` and `tasks` would be a great help.

**Comment by elbatk** [comment]
Ah, sorry people. It looks like this doc could use an update. Adding @willsmythe for awareness and input.

**Comment by chcomley** [comment]
Hi @xtu, Please accept our apology for losing sight of this issue. There is a more recent issue for this article, however, which I've added your feedback to so we can be sure it's properly addressed. I'm closing this issue, so please reference [this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7263) and you can @mention me if you have any further questions or concerns.  
We're working on a complete overhaul of this area and are in the beginning phases of that work now.
Thank you!
