### ISSUE TITLE
Show how to force push in Visual Studio

### ISSUE THREAD

**Issue by bpugh** [MicrosoftDocs/azure-devops-docs#2802]
The "Force push to update your remote branch" section should probably be updated to show how to enable a force push from within Visual Studio (as shown in this blog post: https://blogs.msdn.microsoft.com/devops/2017/03/06/new-git-features-in-visual-studio-2017/) along side the command line version just like the rebase example above it.

I can open a PR if you agree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf2704e-ef04-e4ab-88ba-48533fa62d21
* Version Independent ID: e59a9067-775b-d9df-94b7-29076dbfbf25
* Content: [Update your branch history with rebase - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/rebase?view=vsts&tabs=visual-studio)
* Content Source: [docs/repos/git/rebase.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/rebase.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@bpugh If you wanted to create a PR to add that content, that would be great and I'm sure many customers and readers would appreciate it. I check for new PRs 2-3 times a week, but you can also at mention me and I'll see it sooner. Link it to this issue and we can close them together.
