### ISSUE TITLE
Azure DevOps Services public endpoint has changed

### ISSUE THREAD

**Issue by myersnick** [MicrosoftDocs/azure-devops-docs#2874]
Instead of https://publisher.gallery.vsassets.io, during my development the endpoint https://publisher.gallerycdn.vsassets.io was used.  Trivial difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596a9783-261e-fecf-9857-4847e4921e84
* Version Independent ID: b62a583c-1348-f510-721d-47e7245b6b8d
* Content: [Static Content Hosting for Extension Content](https://docs.microsoft.com/en-us/azure/devops/extend/develop/static-content?view=vsts)
* Content Source: [docs/extend/develop/static-content.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/static-content.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @myersnick , thank you for the feedback! Adding @willsmythe to confirm this change and then I'll update the docs :)

**Comment by chcomley** [comment]
Hi @myersnick, This article has been updated to reflect your feedback, currently in a PR to go out today. Thank you!
