### ISSUE TITLE
Firewall Rule PowerShell Scripts Will Not Work For ARM Subscriptions

### ISSUE THREAD

**Issue by BStrat77** [MicrosoftDocs/azure-devops-docs#2894]
Had issues with getting SetAzureFirewallRule.ps1 and RemoveAzureFirewallRule.ps1. Updated to the following:

Set

```
[CmdletBinding(DefaultParameterSetName = 'None')]
param
(
  [String] [Parameter(Mandatory = $true)] $ServerName,
  [String] [Parameter(Mandatory = $true)] $ResourceGroupName,
  [String] $AzureFirewallName = "AzureWebAppFirewall"
)

$ErrorActionPreference = 'Stop'

function New-AzureSQLServerFirewallRule {
  $agentIP = (New-Object net.webclient).downloadstring("http://checkip.dyndns.com") -replace "[^\d\.]"  
  New-AzureRmSqlServerFirewallRule -StartIPAddress $agentIp -EndIPAddress $agentIp -FirewallRuleName $AzureFirewallName -ServerName $ServerName -ResourceGroupName $ResourceGroupName
}
function Update-AzureSQLServerFirewallRule{
  $agentIP= (New-Object net.webclient).downloadstring("http://checkip.dyndns.com") -replace "[^\d\.]"
  Set-AzureRmSqlServerFirewallRule -StartIPAddress $agentIp -EndIPAddress $agentIp -FirewallRuleName $AzureFirewallName -ServerName $ServerName -ResourceGroupName $ResourceGroupName
}

If ((Get-AzureRmSqlServerFirewallRule -ServerName $ServerName -FirewallRuleName $AzureFirewallName -ResourceGroupName $ResourceGroupName -ErrorAction SilentlyContinue) -eq $null)
{
  New-AzureSQLServerFirewallRule
}
else
{
  Update-AzureSQLServerFirewallRule
}
```

Remove

```
[CmdletBinding(DefaultParameterSetName = 'None')]
param
(
  [String] [Parameter(Mandatory = $true)] $ServerName,
  [String] [Parameter(Mandatory = $true)] $ResourceGroupName,
  [String] $AzureFirewallName = "AzureWebAppFirewall"
)

$ErrorActionPreference = 'Stop'

If ((Get-AzureRmSqlServerFirewallRule -ServerName $ServerName -FirewallRuleName $AzureFirewallName -ResourceGroupName $ResourceGroupName -ErrorAction SilentlyContinue))
{
    Remove-AzureRmSqlServerFirewallRule -FirewallRuleName $AzureFirewallName -ServerName $ServerName -ResourceGroupName $ResourceGroupName
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by RoopeshNair** [comment]
@BStrat77  Can you share more details about the issues?

**Comment by BStrat77** [comment]
The PowerShell commands in original doc example appear to be specific to Azure Classic. The syntax I provided above will work for subscriptions using Azure Resource Manager. The calls to create the Firewall have been changed to the command and an additional parameter was added to pass in the ResourceGroupName.

I was initially getting this error
```
New-AzureSqlDatabaseServerFirewallRule : No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.
At C:\script\SetAzureFirewallRule.ps1:16 char:3
+   New-AzureSqlDatabaseServerFirewallRule -StartIPAddress $agentIp -En ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureSqlDatabaseServerFirewallRule], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.SqlDatabase.Firewall.Cmdlet.NewAzureSqlDatabaseServerFirewallRule
```

**Comment by RoopeshNair** [comment]
The AzureSQL Databased Deployment task relies on the REST APIs to manage the firewall rules. You shouldn't have this issue with it.  Regarding the example in the doc, it does need an update.

**Comment by diberry** [comment]
Is the yaml script in the SQL scripts section correct to have the line as 

```
  displayName: Azure PowerShell script: FilePath
```

where `script: FilePath` is part of the line? Or is it supposed to be on the next line or is it missing some syntax around FilePath? 

As the line reads, I get a pipeline error: 

```
Could not queue the build because there were validation errors or warnings. /azure-pipelines.yml: (Line: 62, Col: 39, Idx: 2117) - (Line: 62, Col: 39, Idx: 2117): Mapping values are not allowed in this context.
```

**Comment by FionaHolder** [comment]
I gave your solution a try. You are missing a space on this line:

**Comment by BStrat77** [comment]
Thanks @FionaHolder! I have updated the code in my comment, glad it worked for you.

**Comment by thomps23** [comment]
@RoopeshNair Specific to your comment:

> The AzureSQL Database Deployment task relies on the REST APIs to manage the firewall rules. You shouldn't have this issue with it. Regarding the example in the doc, it does need an update.

Is this something we can get in the backlog so that we can close this issue out?

**Comment by FredFaust** [comment]
+1 Please update the documentation to use the RM version of the cmdlets

**Comment by ramiMSFT** [comment]
@BStrat77 Thank you for your feedback. The updated version will go live shortly.

**Comment by jetnet** [comment]
the provided above solution did work for me, those modules were not available in my Azure devops for some reasons.
I had to switch to `Az.Sql` module with:
```
Get-AzSqlServerFirewallRule
New-AzSqlServerFirewallRule
Set-AzSqlServerFirewallRule
Remove-AzSqlServerFirewallRule
```
