### ISSUE TITLE
tf vc status insists on reporting "add" files that have been added and a lot of others that will never be added

### ISSUE THREAD

**Issue by markyoung143** [MicrosoftDocs/azure-devops-docs#2920]
The docs say the status command shows files for "pending changes". I should be able to ignore any "add" files that that it thinks the user might want to add. If I wanted to add them they would have been added to source control already. There is no difference in the status output for a file the user actually added to source control and a temp file laying around that the user will never add. There should be a way to distinguish this. Pending Changes shows "file.ext [add]" for the ones I added and the "extra" files are in the "Detected: XXX add(s)" link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d796f92a-8065-b7da-6af3-1f61f52f37d9
* Version Independent ID: 2c7e9f56-ab32-c6c3-4eb2-26ac6a5dbfd8
* Content: [Status command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/status-command?view=vsts)
* Content Source: [docs/repos/tfvc/status-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/status-command.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by cfframe** [comment]
This issue persists and impacts negatively on cleaning up workspaces (particularly important when preparing to hand over projects to someone else, as well as generally good practice).

**Comment by RuslanRasulovAkv** [comment]
#reassign @RuslanRasulovAkv

**Comment by MaximMalygin** [comment]
@msebolt could you please close it, pr was merged for this issue
