### ISSUE TITLE
Get download URL for the latest successful build and its artifact?

### ISSUE THREAD

**Issue by zach-ovic** [MicrosoftDocs/azure-devops-docs#2966]
Is it possible to get download URL for the latest successful build and its artifact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by elbatk** [comment]
Hi @zach-ovic ,  which way are you wanting to download the artifact? Through the UI, the REST APIs, or via Azure Pipelines?

**Comment by zach-ovic** [comment]
Hey @elbatk, I would like to add link of the artifact of the latest successful build of some build pipeline to my wiki page. Page is tutorial how to setup some of our company utility software. It would say something like "And download latest build of XYZ" and I would like that XYZ was a link to the artifact. Is something like that possible? Even through REST API.

**Comment by elbatk** [comment]
Ah okay, adding @vijayma to help take a look for you, he would know better than me :)

**Comment by zach-ovic** [comment]
Great. Thank you.

**Comment by JohnTortugo** [comment]
I'm also interested on this. How can I create a link to an artifact container folder?

**Comment by elbatk** [comment]
Pinging @vijayma here, I'm not aware that this is possible but it would be nice to put it on Vijay's radar as a potential improvement!

**Comment by chunfantasy** [comment]
I have tried the REST API to download the artifact but it does not work, https://docs.microsoft.com/en-us/rest/api/azure/devops/build/artifacts/get%20artifact?view=azure-devops-rest-5.1

**Comment by chunfantasy** [comment]
I dont get the `downloadUrl` in the response as described in the doc.
```
{"id":4,"name":"nrf-ble-driver-macos","resource":{"type":"PipelineArtifact","data":"850045660D5D5A88FB10CED8AF2428AA84F2F179A5199479037E94E3419B215701","properties":{"RootId":"4E69256EE1933637020D40A90CBC5DE4DB5A7A82947A5AD6CB47818E75C3E5B202"},"url":"https://dev.azure.com/ChunFan/66d06ed9-b064-45b4-9e3e-458cd15cb887/_apis/build/builds/48/artifacts?artifactName=nrf-ble-driver-macos&api-version=5.1-preview.5"}}
```

**Comment by thomps23** [comment]
re-tagging as doc-bug per this comment:



> I dont get the `downloadUrl` in the response as described in the doc.
> 
> ```
> {"id":4,"name":"nrf-ble-driver-macos","resource":{"type":"PipelineArtifact","data":"850045660D5D5A88FB10CED8AF2428AA84F2F179A5199479037E94E3419B215701","properties":{"RootId":"4E69256EE1933637020D40A90CBC5DE4DB5A7A82947A5AD6CB47818E75C3E5B202"},"url":"https://dev.azure.com/ChunFan/66d06ed9-b064-45b4-9e3e-458cd15cb887/_apis/build/builds/48/artifacts?artifactName=nrf-ble-driver-macos&api-version=5.1-preview.5"}}
> ```

**Comment by joshmgross** [comment]
Hey, I'm from one of the pipelines teams that works with build artifacts.

For a while, Pipeline Artifacts weren't populating that `downloadUrl` field in the Build Artifact, but that should now be fixed as a couple of months ago.

**Comment by vijayma** [comment]
As Josh explained, you can view the artifacts now in the UI (enable multi-stage pipelines preview feature). You can find the URL by opening the browser tools and looking at the network call. It is of the form: https://dev.azure.com/<org>/<project-id>/_apis/build/builds/<buildid>/artifacts?artifactName=<artifactname>&api-version=5.1&%24format=zip

**Comment by jordwalke** [comment]
@vijayma Thank you but this doesn't answer the original question of being able to include a permanent URL that always points to the artifact for the latest build. For example, right now we cannot embed a link on a README that says "here's a link to the latest artifact". The solution you suggested: `https://dev.azure.com/esy-ocaml//esy-ocaml/_apis/build/builds/454/artifacts?artifactName=cache-Windows_NT-install-v1&api-version=5.1&$format=zip` requires that we still make a rest request to query the latest buildID which rules out being able to embed it on a README for example. Ideally we would have an API like:
`https://dev.azure.com/esy-ocaml//esy-ocaml/_apis/build/latest/artifacts?artifactName=cache-Windows_NT-install-v1&api-version=5.1&$format=zip` but that does not work.

**Comment by buckleyGI** [comment]
I can't explain better than jordwalke. A constant URL with the word latest in the query string for example, that one can share as a link is much needed. That's the original question I believe as well and we also need it for out projects. Thank you

**Comment by Onandon11** [comment]
I would also like this option for my companies wiki page .. could this please be reopened?

**Comment by bormm** [comment]
@vijayma @elbatk can someone please recheck this issue? How is it possible its being closed if nothing is solved here? Please read again the issue description.

**Comment by BrunoZell** [comment]
A _simple_ one liner will do.

You can just inline some html in a data url: `data:text/html,<a id="btn">download</a><script></script>`

And then write some script to talk to the api as discussed. However, this hardcodes a PAT (private access token), so anyone with this link can access any artifacts. Make sure to scope the PAT to artifacts only.

The PAT has to be base64 encoded in a form like this: `:[PAT]`. [example](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat-in-your-code)

```js
var o="[organization]/[project]";
var b="[branch]";
var p="[pipeline]";
var a="[artifact]"
var k="[authentication-header]";

var r=new XMLHttpRequest();
r.open("GET","https://dev.azure.com/"+o+"/_apis/build/latest/"+p+"?branchName="+b,false);
r.setRequestHeader("Authorization",k);
r.send(null);
var d=new XMLHttpRequest();
d.open("GET","https://dev.azure.com/"+o+"/_apis/build/builds/"+JSON.parse(r.responseText).id+"/artifacts?artifactName="+a, false);
d.setRequestHeader("Authorization",k);
d.send(null);
document.getElementById("btn").href=JSON.parse(d.responseText).resource.downloadUrl;
```

Finally remove all the new lines and fit the script into the `<script></script>` tag to get your download url:

`data:text/html,<a id="btn">download</a><script>var o="[organization]/[project]";var b="[branch]";var p="[pipeline]";var a="[artifact]"var k="[authentication-header]";var r=new XMLHttpRequest();r.open("GET","https://dev.azure.com/"+o+"/_apis/build/latest/"+p+"?branchName="+b,false);r.setRequestHeader("Authorization",k);r.send(null);var d=new XMLHttpRequest();d.open("GET","https://dev.azure.com/"+o+"/_apis/build/builds/"+JSON.parse(r.responseText).id+"/artifacts?artifactName="+a, false);d.setRequestHeader("Authorization",k);d.send(null);document.getElementById("btn").href=JSON.parse(d.responseText).resource.downloadUrl;</script>`

Hope it helps.

**Comment by therealshark** [comment]
@vijayma I think this is still an open issue. In my case i want to link from the Projects READE.md (inside azure devops) to the last successful build (or even better its artifacts) to help my less technically inclined colleagues find the build result of the Pipeline.  Using a similar approach as @BrunoZell doesn't work there (and inlineing the PAT feels very wrong aswell).

I feel this feature could be quite helpful for many projects, maybe the badge example could even be upgraded to make the badge a link directly bringing the user to the latest build.

**Comment by ChristophSchmidpeter** [comment]
I also think it is really fundamental to get the latest successful build. So much so that I assumed I just couldn't figure out how to do so. Could this please be implemented?

**Comment by Szwiti** [comment]
It's kinda disgusting that you have to write scripts for every API calls which should be included.
Hope this feature is in your scope.

**Comment by TimShererWithAquent** [comment]
I'm opening because of MicrosoftDocs/azure-devops-docs/issues/11400 which I am going to close.

@Asinin3 - There's a lot of discussion in this issue. From your point of view, what is it you want addressed? Also, in thinking about this, separate documentation fixes from feature requests. Feature requests should go [here](https://developercommunity.visualstudio.com/search?space=21).

@vijayma @steved0x for awareness

**Comment by Asinin3** [comment]
Just want to be able to have a static link to download the latest successful build's artifact without having to use scripts/api calls. e.g Bormm's suggestion.

**Comment by reunanen** [comment]
> Just want to be able to have a static link to download the latest successful build's artifact

In addition, would be nice if there was a separate link for (the latest successful build of) each branch.

For example: _build/results?**branch=develop**&buildId=**latestSuccessful**&view=artifacts&type=publishedArtifacts

**Comment by mijacobs** [comment]
@reunanen , @Asinin3--thank you for taking the time to share your feedback. We use these GitHub issues for documentation issues. To create feature requests, we're using our developer community site (we recently changed from User Voice). You can create the feature request here: https://developercommunity.visualstudio.com/search?space=21 
It's the best way to get a feature request on the product team's radar. I'm closing this issue since it's no longer a documentation request.
