### ISSUE TITLE
Explain advanced filtering modes: simple history, first parent, full history, and full history with simplified merges

### ISSUE THREAD

**Issue by manne** [MicrosoftDocs/azure-devops-docs#2998]
As a developer
I want to understand the functionality of each advanced filtering mode
So that I can efficiently use the history.

Possible solutions:
* provide the (git) command options of each advanced filtering mode.
* describe each filtering mode and give examples

The provided link https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History isn't very helpful, the mapping between the filtering modes and git commands is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de6ffd-afcc-17f9-8e89-6845c0a5bd6c
* Version Independent ID: caea7004-b42b-9084-befc-6b33168570b4
* Content: [View commit history - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commit-history?view=vsts)
* Content Source: [docs/repos/git/commit-history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/commit-history.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sancha**

**Comment by steved0x** [comment]
@manne I am forwarding this question to the author of that article.

**Comment by sandeepchads** [comment]
This is a great read on simplifying history and when to use which filter. The git history filters are pivoted around these use cases: https://docs.microsoft.com/en-us/azure/devops/articles/git-log-history-simplification?view=vsts

**Comment by manne** [comment]
@sandeepchads I read the article <https://docs.microsoft.com/en-us/azure/devops/articles/git-log-history-simplification?view=vsts>. I get the intention of the filters, but it's real functionality is hidden. For me it's sufficient to get a mapping between the filter and the git command. With the git commands, the details can be extracted from the official git documentation

Example of a mapping (filter ==> git command)

- first-parent ==> git log --first-parent
- full history ==> git log --full-history

**Comment by theonlypwner** [comment]
I wondered about this too. Here is my guess at the mapping:
| Option                         | Command                                    |
|--------------------------------|--------------------------------------------|
| Simple history (default)       | `git log`                                  |
| First parent                   | `git log --first-parent`                   |
| Full history                   | `git log --full-history`                   |
| Full history (simplify merges) | `git log --full-history --simplify-merges` |
