### ISSUE TITLE
Example: Where is that New Method? 

### ISSUE THREAD

**Issue by trongphan** [MicrosoftDocs/azure-devops-docs#3066]
"From the Tracking Changeset window, Julie can see that Chris checked in the method with changeset 50, and merged it to the Dev branch with changeset 51. But Julie cannot get the new code until changeset 50 is merged into the FeatureTeamB branch. So she drags the Dev branch onto the FeatureTeamB branch to launch the Source Control Merge Wizard, which she then uses to complete the merge."

Should it be "But Julie cannot get the new code until changeset 51 is merged into the FeatureTeamB branch. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6285c169-bbce-658f-5802-bf41398dd28c
* Version Independent ID: 91bf9aff-3dd6-943a-aed6-8314abac2439
* Content: [Merge folders and files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/merge-folders-files?view=vsts)
* Content Source: [docs/repos/tfvc/merge-folders-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/merge-folders-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan
