### ISSUE TITLE
Can we lock a branch when there is a continuous integration build is in progress? 

### ISSUE THREAD

**Issue by Geekays** [MicrosoftDocs/azure-devops-docs#3080]
Can we automatically lock a branch when there is a continuous integration build is in progress? Like, lock the branch, start the build process, unlock? This is because we have a build process that currently takes some time due to some additional tasks in the build pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ffea81-86af-46cb-a290-5ce83924f235
* Version Independent ID: 2ea32d72-75d8-42f9-bf33-756b1e00b3f2
* Content: [Lock a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/lock-branches?view=vsts)
* Content Source: [docs/repos/git/lock-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/lock-branches.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by rbprado** [comment]
We should be able to do that throught the REST API, but I'm also unable to find it on the doc. :(

**Comment by rbprado** [comment]
Found it, the title "update ref" isn't that intuitive:
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/update%20ref?view=azure-devops-rest-4.1
