### ISSUE TITLE
Use Secret File to store settings.xml

### ISSUE THREAD

**Issue by yevster** [MicrosoftDocs/azure-devops-docs#3161]
Service credentials should never be committed to a git repo in plain text, as demonstrated in steps 4-5 of "Creating the Maven Package Feed". The correct process would be to store the content of settings.xml in a Secret file, and download that Secret file inside the build pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f43544-e181-b021-b362-dd7c5c631d7c
* Version Independent ID: 01897be8-0c56-1e83-0e1e-8dea747911ec
* Content: [Configure package management for Maven with Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/labs/mavenpmvsts/?view=azdevops)
* Content Source: [docs/java/labs/mavenpmvsts/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmvsts/index.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by sugun999** [comment]
Hi,

Any steps to achieve this?

**Comment by yevster** [comment]
@sugun999, you would use the Secure Files feature in Azure Pipelines. [Full documentation here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops
).

**Comment by peichels** [comment]
Can you please adjust above sample steps to prevent people from putting plain text secrets in code repos (as @yevster is mentioning)?

**Comment by chasewilson** [comment]
Hi all! Thank you for the feedback. I've created a story in my backlog to fix this issue. If you have any more input, feel free to reach out. This should be taken care of shortly.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
