### ISSUE TITLE
410 Return Code for Reference Slot Mode URL

### ISSUE THREAD

**Issue by iokevins** [MicrosoftDocs/azure-devops-docs#3172]
Link "Matt Mitrik: Changing to Slot Mode in TFS 2010 Version Control" (https://blogs.msdn.microsoft.com/mitrik/2009/05/28/changing-to-slot-mode-in-tfs-2010-version-control/) for options /itemmode and /slotmode returns 410 "Gone". Please troubleshoot and resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff804ab-4a78-42e5-5325-2549f3d4a392
* Version Independent ID: eaddc86c-15c8-11d5-33e8-2bfc36e639e9
* Content: [History command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/history-command?view=azdevops)
* Content Source: [docs/repos/tfvc/history-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/history-command.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment]
@iokevins I can successfully navigate to this URL. Please confirm that the link is working for you now.

cc @apawast @steved0x @MaximMalygin

**Comment by iokevins** [comment]
Thank you, it works for me now.

**Comment by MaximMalygin** [comment]
@iokevins can you close the issue?
