### ISSUE TITLE
How can one achieve this from a CICD server?

### ISSUE THREAD

**Issue by lidermanrony** [MicrosoftDocs/azure-devops-docs#3202]
i need a non-GUI way to acheive this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops&viewFallbackFrom=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @lidermanrony , I'll need to reach out to the product team to find out more about this. For now, you could reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) which is monitored by the product team to see if you can get a solid answer there!

**Comment by cremor** [comment]
I agree that this page should be expanded to also explain (or at least link to) non-GUI configuration ways (so a nuget.config). This is not only required for build servers, but also for "git clone and it works" scenarios (new project members shouldn't have to configure their Visual Studio to get a freshly cloned project to build).

**Comment by int0x81** [comment]
Im especially interested on how to consume packages (located in my azure devops pipeline) from inside a docker container.

**Comment by edgarrs** [comment]
Look at https://github.com/MicrosoftDocs/azure-devops-docs/issues/3853

**Comment by ramiMSFT** [comment]
@lidermanrony Thank you for your feedback. Please check out the following articles:

- [Artifacts in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops)

- [How to publish and consume Artifacts (YAML/Classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml)

- [Publish to NuGet feeds (YAML/Classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml)

See also [NuGet Authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) and [NuGet task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops) for more details on Pipeline tasks.
