### ISSUE TITLE
Outdated doc - Missing Path filter

### ISSUE THREAD

**Issue by Makovec** [MicrosoftDocs/azure-devops-docs#3235]
Hi,
as mentioned in [#1521](https://github.com/MicrosoftDocs/vsts-docs/issues/1521) there is still missing part about Path filters.
I just came to that because I am trying to exclude path from policy but it doesn't work. If I use `!/_drafts` in the field it still wants to enforce policy when pushing from local repo to Azure Repos.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#configure-branch-policies)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by beavel** [comment]
Any chance the Path filter info is going to be added to the docs? Still missing and it is over a year later.

**Comment by vtbassmatt** [comment]
Closing in favor of #1521
