### ISSUE TITLE
Clarify how errors are handled 

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#3265]
In particular, is `set -x` prepended to the script for Linux? If not, then some advice should be given to make devs aware of that. Also, is the exit code of the script taken into account? What makes the task "fail"? The description only talks about "Fail on Standard Error" but that can't be the full story.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bkwdesign** [comment]
My wish for v3 of this task is to be able to specify something like a dictionary of strings to search stdOut for (with regex pattern support). If a key in the dictionary successfully matches stdOut, the value associated with that key is reported as the primary reason for failure. There might be an option to evaluate stdOut real-time and short-circuit, or, eval upon task-processing-complete.

**Comment by mkpankov** [comment]
OP talks about `set -x` but probably means `set -e`. If not, that need to be clarified as well.

Also it might be beneficial to have an option to `set -u`, too.

**Comment by letmaik** [comment]
Sorry, I meant `-e`, yes.

**Comment by SimonAlling** [comment]
> In particular, is `set -x` prepended to the script for Linux?

I did a bit of testing, arriving at the conclusion that it is not.

```yaml
    - task: CmdLine@2
      name: taskThatShouldFail
      displayName: Task that should fail
      inputs:
        script: |
          echo "Should fail now."
          false
          echo "Did not fail."
```

With the above task, **the pipeline succeeds** and the log contains this:

```
Should fail now.
Did not fail.
```

I then tried adding `set -e`:

```diff
     - task: CmdLine@2
       name: taskThatShouldFail
       displayName: Task that should fail
       inputs:
         script: |
+          set -e
           echo "Should fail now."
           false
           echo "Did not fail."
```

**The pipeline now fails** and the log contains this instead:

```
Should fail now.

##[error]Bash exited with code '1'.
```

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by mkpankov** [comment]
Hmmm, I think it was waiting for action on Azure Devops side?

**Comment by mijacobs** [comment]
@steved0x @juliakm  @ramiMSFT  can you take a look--should this be assigned to someone else?

**Comment by Dave-EMIS** [comment]
I just logged this duplicate issue for the docs: #10316

**Comment by sozercan** [comment]
looks like GitHub actions sets `set -eo pipefail` as default when `shell: bash` is explicitly specified. 

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

Can Azure Pipelines expose something like this?
