### ISSUE TITLE
Not Complete information about the deprecated task.

### ISSUE THREAD

**Issue by ashish2rathi** [MicrosoftDocs/azure-devops-docs#3268]
Why we should not use this deprecated task is not mentioned in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34301e0e-fc7e-bf7a-de61-c466756f22a3
* Version Independent ID: 2595a9cf-03b2-4206-6dda-43ac1b903add
* Content: [Copy and Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-and-publish-build-artifacts.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bukandu1** [comment]
Hello. Is there an update on this issue? I ran into the same issue where it refers me to this page on how to build artifacts. There are no instructions currently on how to copy and build artifacts in any of the pages related to Azure Pipelines.

**Comment by schenkjan** [comment]
The documentation seems indeed to be a bit weak regarding the steps on how to replace the "Copy and Publish Build Artifacts" task with "Copy files" and "Publish Build Artifacts" tasks.
After a bit of research I found the following page which helped me: [https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=classic#example-assemble-c-artifacts-into-one-location-and-publish-as-an-artifact](url)

@bukandu1 does that help?

So the information is there, it's just a bit hidden. Maybe the documentation for the task could be updated to link to the page containing the information.

**Comment by MarkIannucci** [comment]
the link in @schenkjan 's comment is dead :(

**Comment by MarkIannucci** [comment]
@schenkjan , thank you for updating your link.  That was very kind.  

I found that I could skip the copy portion of the task by using a minimatch pattern in the `FileCopyOptions` of the `PublishBuildArtifacts@1` task, like so:

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Caboodle X Artifact'
          inputs:
            pathtoPublish: 'Caboodle/CaboodleX'
            artifactName: 'Drop/Caboodle X'
            FileCopyOptions: '**/*'

**Comment by MarkIannucci** [comment]
@steved0x , somehow I unassigned @elbatk .  I have no idea how that happened, and I'm unable to reassign them.  I deleted a post that I made using the Microsoft Docs GitHub integration.  I suspect there may be a bug in there somewhere.  Can you point this out to the folks who work on that?

**Comment by ramiMSFT** [comment]
@ashish2rathi Thank you for your feedback. The updated content will go live shortly.
