### ISSUE TITLE
Misssing documentation for Microsoft.VSTS.Actions.StartWork and Microsoft.VSTS.Actions.StopWork

### ISSUE THREAD

**Issue by ttplaya** [MicrosoftDocs/azure-devops-docs#3285]
I'm using TFS2018 and I see in the Bug.xml that the transition from New to Active has an action Microsoft.VSTS.Actions.StartWork, and the transition from Active to New has the action Microsoft.VSTS.Actions.StopWork. However those actions are not mentioned here. What triggers those two actions by default? Does the StartWork get triggered when I link the bug to a Git branch, or something similar? How about StopWork?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faabc206-6ecf-ce78-0288-951b4c6241fb
* Version Independent ID: 1b820a61-e563-988b-b1ad-586bfbc86a6a
* Content: [Automate field assignments - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/automate-field-assignments-state-transition-reason?view=tfs-2018)
* Content Source: [docs/reference/xml/automate-field-assignments-state-transition-reason.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/automate-field-assignments-state-transition-reason.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ttplaya - Thank you for your inquiry and apologies for the delay in response. I'm updating the article today to provide an explanation of the three system actions used in the default work item types.  In a nutshell, the Microsoft.VSTS.Actions.CheckIn action automates changes in state of work items linked to a changeset when the changeset is checked in. The Microsoft.VSTS.Actions.StartWork and Microsoft.VSTS.Actions.StopWork transition the state of work items when a developer uses the My Work feature as described in [Day in the life of a devops developer: suspend work, fix a bug, and conduct a code review](https://review.docs.microsoft.com/en-us/azure/devops/repos/tfvc/day-life-alm-developer-suspend-work-fix-bug-conduct-code-review?view=azure-devops-2019).

**Comment by kosioreka** [comment]
Hi @KathrynEE, could you please specify if creating a PR in DevOps and linking a work item to this PR would activate a transition for this work item from New to Active using this action:
```
<TRANSITION from="New" to="Active">
  <ACTIONS>
    <ACTION value="Microsoft.VSTS.Actions.StartWork" />
  </ACTIONS>
  ...
```

**Comment by KathrynEE** [comment]
@kosioreka - The `Microsoft.VSTS.Actions.StartWork` is meant to work with the MyWork feature only. I recommend you review [Autocomplete work items with pull requests](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/auto-complete-work-items-pull-requests?view=azure-devops) for support provided for autocompleting work items with PRs.

**Comment by kosioreka** [comment]
@KathrynEE thank you for your reply. I do know about this feature. However the work items are not auto resolved when are set to New, instead of Active. Do you happen to know how to enable such validation?

**Comment by KathrynEE** [comment]
@kosioreka - No, I'm not sure that you can do that. I recommend you review posts or post what you are trying to do on our [Developer Community page](https://developercommunity.visualstudio.com/search?space=21&entry=problem&q=Auto+complete+work+items+PRs).
