### ISSUE TITLE
'vsts-agent' name needs to be updated.

### ISSUE THREAD

**Issue by ganrad** [MicrosoftDocs/azure-devops-docs#330]
Excellent set of hands-on labs!

The docker container image name for the VSTS agent should be 'microsoft/vsts-agent'.
==>>
docker run -e VSTS_ACCOUNT=<account> -e VSTS_TOKEN=<pat> -v /var/run/docker.sock:/var/run/docker.sock --name vstsagent -it microsoft/vsts-agent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3660a83d-0a9e-b864-6c9d-f2d846c1ef4a
* Version Independent ID: 5f4da709-3037-e566-e796-3ae69907de2c
* Content: [Configure a private Docker build agent for your Java project with VSTS | Microsoft Docs](https://docs.microsoft.com/en-us/vsts/java/labs/dockerbuildagent/#)
* Content Source: [docs/java/labs/dockerbuildagent/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/java/labs/dockerbuildagent/index.md)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by aaron-bozit** [comment]
I also had the same issue when running from the documentation.

Thanks.

**Comment by nschonni** [comment]
I think the name might be OK because it's not using the plain published image, but maybe it needs a line like:
```sh
docker build -t vsts/agent .
```
And maybe change the name to something like `colin/agent-with-phantom`

**Comment by robinmanuelthiel** [comment]
This is still an issue...

**Comment by mijacobs** [comment]
We're no longer updating this content--we've moved it to our archives.

**Comment by robinmanuelthiel** [comment]
Wait, what? The content is not outdated, it is simply wrong and never worked in that way. Even if we don't update it, we should fix the mistakes in there as long as it's still accessible or completely take it offline!
