### ISSUE TITLE
Trying to add $(Build.BuildNumber) to an inline powershell script task doesnt work

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#3305]
It has to be something like $BUILD_BUILDNUMBER or something like that (and some other representation for CMD.exe. 

Those descriptions used to be present in the docs pages, but I cant find them now. Where are they and why did they go away?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined build variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=tfs-2015)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by susanadomingos-falck** [comment]
Should be something like  $env:BUILD_BUILDNUMBER

**Comment by StingyJack** [comment]
thanks @susanadomingos-falck 

@andyjlewis or @steved0x - can these pages please be returned to thier prior completeness? I can understand the page being down for a day or two for rewrite, but its been a few weeks

**Comment by PirateBread** [comment]
@StingyJack 

The information is available here: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#set-in-script

**Comment by StingyJack** [comment]
@PirateBread - Thats not where the variables are documented, and I am only trying to _read_ them not set them so I wouldnt expect to look there.   The blurb you pointed out used to be on this page and now its not.

**Comment by PirateBread** [comment]
@StingyJack - Yes I understand you are trying to read them, as per your question:

>Trying to add $(Build.BuildNumber) to an inline powershell script task doesnt work

According to the paragraph which I linked directly:

> Variable names are transformed to uppercase, and the characters "." and " " are replaced by "_".
>For example, Agent.WorkFolder becomes AGENT_WORKFOLDER. On Windows, you access this as %AGENT_WORKFOLDER or $env:AGENT_WORKFOLDER. On Linux and macOS, you use $AGENT_WORKFOLDER.

If this isn't want you are looking for then I must be completely misunderstanding your question?

**Comment by StingyJack** [comment]
The problem is with where that information is now located in docs. It used to be in with the default variables and definitions, now it's in a non-intuitive place.

**Comment by andyjlewis** [comment]
Thank you for reporting this issue. I believe it might be fixed. @steved0x to confirm

**Comment by hamzacakir** [comment]
test

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by msebolt** [comment]
Status resolution is unconfirmed, per https://github.com/MicrosoftDocs/azure-devops-docs/issues/9736.

**Comment by juliakm** [comment]
Thanks for your feedback. We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
