### ISSUE TITLE
Instructions for feed authentication are inaccurate - mavenFeedAuthenticate must be enabled

### ISSUE THREAD

**Issue by vvoinov** [MicrosoftDocs/azure-devops-docs#3336]
Authentication does NOT happen automatically ! You MUST have 'mavenFeedAuthenticate: true' option set in your Maven task definition inside azure-pipelines.yml. It is 'false' by deafult - check [Maven task on GitHub](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/MavenV3/task.json)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60230978-ce5b-6964-23ba-1dd31b1fa1c9
* Version Independent ID: 9b1eb982-b07a-8b67-ab0b-b2a4d3dade12
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by jlanawalt** [comment]
I agree, this is a lot of extra work for what can be accomplished by adding 'mavenFeedAuthenticate: true' to the default Azure DevOps Pipeline Maven build.

These steps are needed to connect a local Maven install to the Azure DevOps Artifacts Maven feed, but not for pipeline builds.

**Comment by ramiMSFT** [comment]
@vvoinov Thank you for your feedback. The updated article will go live shortly.
