### ISSUE TITLE
Please add an example actually using the Azure Container Registry

### ISSUE THREAD

**Issue by jseward** [MicrosoftDocs/azure-devops-docs#3352]
I could not manage to figure out the fields to enter into the service connection properties. Just fell back to using simpler Docker Hub that works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by QuantumFractal** [comment]
Any updates on this? I still cannot use a custom private image from my ACR instance.

**Comment by cpolzer** [comment]
Yes, i found this is working: 

resources:
  containers:
  - container: my_container
    image: myregistry/mylabel:version
    endpoint: myregistryserviceconnectionnamestring

documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#resources

**Comment by strikeout** [comment]
It seems that the endpoint definition for the reg-connection-name can *not be set by a variable* at all. I have tried all three expression syntaxes. Can anybody confirm this?

**Comment by miks** [comment]
Yes, same here

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
