### ISSUE TITLE
it's possible to use LightboxOptions

### ISSUE THREAD

**Issue by gino983** [MicrosoftDocs/azure-devops-docs#3385]
Hi, it's possible to use LightboxOptions for enlarge my widget?
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4504a134-dfd7-0cc9-3292-6844d49b4fe8
* Version Independent ID: e121af02-6651-65bf-a953-fda719e90e3e
* Content: [Add a chart](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-chart?toc=/azure/devops/report/dashboards/toc.json&bc=/azure/devops/report/dashboards/breadcrumb/toc.json&view=azure-devops)
* Content Source: [docs/extend/develop/add-chart.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-chart.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by gino983** [comment]
is it possible to use in other widgets?

![enlarge](https://user-images.githubusercontent.com/7806035/52936727-59053780-335d-11e9-91ce-23bdacba9ba4.PNG)

**Comment by juangps96** [comment]
if it was written: 
 "contributions": [
        {
            "id": "chart",
on vss-extension.json 

It should also have been written:  
VSS.register("chart", function () { 
on the javascript 

but not: VSS.register("piechart"

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance/assistance, thank you!

**Comment by chcomley** [comment]
Hi @gino983, Please @mention me if you have any further questions and I'll be happy to help. Thank you!
