### ISSUE TITLE
Opening paragraph is incorrect/misleading (re: Cloned branches)?

### ISSUE THREAD

**Issue by Liquidream** [MicrosoftDocs/azure-devops-docs#3401]
Hi,
The second sentence says:
 - "**_Cloning a repo downloads all commits and branches in the repo..._**"
...but I don't think this is correct?

I too, used to think that cloning a repo would automatically create local copies of the remote branches, but I believe only the *master* branch is created/pulled (at least when using Visual Studio)?

This is actually *VERY* confusing - because when cloning a *specific* branch from Azure DevOps - I'd expect the clone operation to do the branch I clicked [Clone] from - not *master*.

Either way, just my two cents! :o)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/clone.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Canderson83** [comment]
I agree with this assessment. I'm not sure which branch I have clones from Azure DevOps as it isn't stated anywhere in Visual Studio (that I can find). I'd like to know which branch I have cloned.

**Comment by vtbassmatt** [comment]
The doc is correct, all refs are included in a clone (assuming you use the default refspec). You don't get _local_ refs for anything other than the default branch, but try `git checkout <some branch that exists at origin>` and Git is smart enough to look at `origin`'s refs.
