### ISSUE TITLE
PackageManagement Collaborator role is new in AzureDevOps 2019

### ISSUE THREAD

**Issue by japj** [MicrosoftDocs/azure-devops-docs#3415]
The documentation shows Collaborator role for PackageManagement (TFS 2017).
However, it seems this is a new role for AzureDevOps (Server) 2019.
TFS2018Update3 only contains Reader/Owner/Contributor role in the UI.

Side note: the dating of the documentation is incorrect (11/30/2017) as it mentions AzureDevOps which did not yet exist in 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chasewilson** [comment]
@elbatk Can you verify this?

**Comment by elbatk** [comment]
I think this is right. We rolled out Collaborator in May 2018 so it lines up.

**Comment by edgarrs** [comment]
According to the AzureDevOps Server 2019 release notes, the Artifacts role Collaborator was introduced for that release:

https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019?view=azure-devops

**Comment by ramiMSFT** [comment]
@japj Thank you for your feedback. The release notes line up with what's in the article. Also just as an FYI the article has been updated several times since this issue was opened.
