### ISSUE TITLE
Retention policy for Audit logs

### ISSUE THREAD

**Issue by PouyaPanahy** [MicrosoftDocs/azure-devops-docs#3435]
Hi,
I read at the beginning the following statement:
"You need audit history for all releases and their deployments."

This is very important point in our continous deployment pipelines. We would like to provide audit trail about the changes happenned to release pipeline and also on the deployment rolled out on our production environments. The audit trail happen every year in the first quartal and the auditor will look at the pased year. 

This means that the trail should be visible for more than one year.

I can see that the maximum retention policy is defined for the entire organisation as:
"Days to retain a release	365"
And we can change the default on any project to be less than this value.

My questions are:
- Is this value also related to audit trail (history of the deployments)?
- How long will the history be kept?
- Is there a way to change the retantion policy for the entire organisation? for more than 365 days ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Why use Azure Pipelines? - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/what-is-release-management?view=azure-devops)
* Content Source: [docs/pipelines/release/what-is-release-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/what-is-release-management.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Yuo can mark individual releases to be retained indefinitely, as shown in this screenshot.
![image3](https://user-images.githubusercontent.com/19287943/53157176-da0c3b00-35b8-11e9-8680-f6cb28bc014c.png)

Also see: https://docs.microsoft.com/azure/devops/pipelines/policies/retention#release.
 
Meanwhile, I have passed your questions on to the product team for additional comment.

**Comment by ramiMSFT** [comment]
Thank you @PouyaPanahy and @alexhomer1 for your contributions. This content: [Why use Azure Pipelines? - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/what-is-release-management?view=azure-devops) has been archived. Please see [Retention policies for builds, tests, and releases](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml) for up to date information.
