### ISSUE TITLE
The part of this page to connect the repo to Xcode is no longer accurate.  The Configure option is no longer available as of Xcode 9.

### ISSUE THREAD

**Issue by azav** [MicrosoftDocs/azure-devops-docs#3536]
Configure being available under Xcode's Source Control menu was last present as of Xcode 8.  Apple's Xcode is on version 10.1.  There is no clear path from Xcode's docs or from Microsoft for how to connect to Xcode 10 to a VSTS git repo and clone or check out a project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9dd5174-b1b4-575f-5985-adf603fd772e
* Version Independent ID: b8b070c3-2972-2e0f-b675-0033f6d741c0
* Content: [Share your Xcode project with Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/share-your-code-in-git-xcode?view=azure-devops#feedback)
* Content Source: [docs/repos/git/share-your-code-in-git-xcode.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/share-your-code-in-git-xcode.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@davidstaheli Do you have any feedback on this one?
