### ISSUE TITLE
Documentation appears to be missing explanations for column options

### ISSUE THREAD

**Issue by alexkokkinos** [MicrosoftDocs/azure-devops-docs#36]
The following column options from the conditional formatting example seem to be completely undocumented in the [Grid control reference](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/controls/grid):

`getCellContents`
`comparer`

I'm expecting those to be one of these that are described in the reference:
```
columns: [
            index: {any},
            name: {string},
            canSortBy: {boolean},
            canMove: {boolean},
            width: {number},
            headerCss: {string},
            rowCss: {string},
            text: {string},
            tooltip: {string},
            order: {string},
            hidden: {boolean},
            fixed: {boolean},
            format: {string}
        ]
```
In addition to those column options, most parameters in `getColumnValue` aren't directly documented, like:

`expandedState`
`indentIndex`
`level`
`columnOrder`

With these I understand the general idea of what they are and can probably infer the expected values, but the reference has no information on them in the context of the undocumented `getColumnValue` column property. For example, I would expect that `columnOrder` would give me `asc` or `desc` similar to the `order` property described in the reference, but there's nothing called `columnOrder` listed anywhere in the reference.

Apologies if I'm missing something or I'm wrong about this.

**Comment by steved0x** [comment]
@alexkokkinos Thank you for your contribution, we are reviewing it and will get back to you shortly. Please accept our apologies for this initial delay while we work though the initial backlog of contributions.

**Comment by mijacobs** [comment]
The page the issue is filed against is no longer available. If this issue is still relevant, please re-open it.
