### ISSUE TITLE
Working Directory Only Works with Build

### ISSUE THREAD

**Issue by Izzmo** [MicrosoftDocs/azure-devops-docs#3624]
For some odd reason, the `workingDirectory` parameter input only works on the build command. No others follow it like restore or publish.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by chasewilson** [comment]
@Izzmo are you still having this issue?

**Comment by Izzmo** [comment]
@chasewilson yes it continues to be a problem.

**Comment by chasewilson** [comment]
@Izzmo sorry for the late response, Would you mind clarifying what you're issue is with the working directory? What is the error you are getting when you define the `workingDirectory` with `publish` or `restore`?

**Comment by Izzmo** [comment]
No error, it just doesn't use it. @chasewilson

**Comment by chasewilson** [comment]
This sounds like a product issue, as I believe this should work. Have you reached out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) to see if they have any response? @pulkitaggarwl are you aware of any updates I should make here?

**Comment by ramiMSFT** [comment]
Closing this one out.

**Comment by Izzmo** [comment]
@ramiMSFT was it fixed?
