### ISSUE TITLE
Deployment Package size

### ISSUE THREAD

**Issue by jrudley** [MicrosoftDocs/azure-devops-docs#3643]
The limits should be documented that the build immutable image task cannot copy large files during its task. I am not sure what those file sizes are, but they exist as I can reproduce it. Only small files from the artifact staging directory can be copied over, else the copy step will hang until timeout happens.

**Comment by chcomley** [comment]
Hi @jrudley, thanks so much for your input. I've created a user story on my backlog to address this. Thanks again!

**Comment by chcomley** [comment]
@jrudley, could you please point me to the article this is in reference to? Many thanks!

**Comment by jrudley** [comment]
> @jrudley, could you please point me to the article this is in reference to? Many thanks!

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops

Thanks

**Comment by jrudley** [comment]
@chcomley https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops

Thanks

**Comment by RoopeshNair** [comment]
@azooinmyluggage  for Packer task

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
