### ISSUE TITLE
CI keeps the master branch clean

### ISSUE THREAD

**Issue by jessemcallister** [MicrosoftDocs/azure-devops-docs#3652]
CI _attempts_ to keep the master branch clean, but based on the process as outlined, you will only know if master is clean after committing to master and a resulting build passes/fails. In the event of failure, master is technically not clean and you've committed broken code to master. CI cannot guarantee a clean master, but helps to reduce how long it's not in a clean state.

I think the distinction is subtle but essential. This distinction is also why some CI products offer personal builds or pre-tested/delayed commits as a means to aid in ensuring your commit to master will be as error-free as possible, but those tools still cannot cleanly solve merge issue during concurrent contribution to a shared master.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc48620-03dc-7d0e-5e30-2e70fd114028
* Version Independent ID: 6142280a-a27b-aaf6-43ef-b91f7ae44084
* Content: [What is Continuous Integration? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-continuous-integration#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-integration.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-continuous-integration.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by joaosantana** [comment]
CI _will_ keep `master` branch clean with pull requests that passes in PR builds.

**Comment by jessemcallister** [comment]
> CI _will_ keep `master` branch clean with pull requests that passes in PR builds.

This assumes a particular workflow which is not included in the definition of CI. The first paragraph which defines CI includes explicit tense and verbiage that implies the validation is happening after commit to the master branch.

The second paragraph refers to an example which happens to support the flow you are describing (and is a more ideal strategy to protect the master branch). Not all version control systems implement a PR flow (although you can generally achieve a PR-like flow in any of them).

Also, any flow which requires a merge to master must also deal with merge conflicts. Depending on your merge strategy you likely need post merge verification. Any post-merge verification implies you could not guarantee a clean master. The first paragraph implies a post-merge/post-commit verification.

So no, CI as described _attempts_ to keep the master branch clean, however a specific implementation may enforce it to be clean. For the purposes of general documentation the wording should still be updated, in my opinion.

**Comment by msebolt** [comment]
@jessemcallister Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

Since `clean` is actually used as a git command, the terminology should probably just be replaced.  The documentation has been updated and is pending review.
