### ISSUE TITLE
Update screenshot (cur header from vsts)

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-devops-docs#3750]
https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/msbuildsourcelinkcreateproperty.png?view=azure-devops
https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/publishsymbolscheckbox.png?view=azure-devops
both were done in vsts, not in azure devops.
Probably it also require to update URL here https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/symbollocationoptionspanel.png?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b7c25-2ef7-3807-b898-b9024ba297e2
* Version Independent ID: 4b2eda64-1f32-fdf8-ee09-420dbb8b9f4d
* Content: [Setting up GitHub Source Linking with Azure DevOps Services Build & Azure DevOps Services Symbol Server](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/setting-up-github-sourcelinking?view=azure-devops)
* Content Source: [docs/artifacts/symbols/setting-up-github-sourcelinking.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/symbols/setting-up-github-sourcelinking.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Thanks @SychevIgor, I've created a work item to address this!

**Comment by ramiMSFT** [comment]
@SychevIgor Thank you for your feedback.

**Comment by SychevIgor** [comment]
nice reaction! issue was created in April 2019. (1.5 years ago)
