### ISSUE TITLE
Update screenshots from VSTS age

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-devops-docs#3751]
https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/vsdebugger1.jpg?view=azure-devops
new message 
![image](https://user-images.githubusercontent.com/578954/54866316-54300b00-4d83-11e9-9f3d-f2ec532f0d57.png)

https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/connectsymbolserver.png?view=azure-devops
new UI
![image](https://user-images.githubusercontent.com/578954/54866318-58f4bf00-4d83-11e9-90f4-6405b0089a07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d921846-31fc-69eb-edef-6c41c050f592
* Version Independent ID: 83678a41-bf22-2318-4867-710ab7a14494
* Content: [Debug with symbols in Visual Studio](https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/debug-with-symbols-visual-studio?view=azure-devops)
* Content Source: [docs/artifacts/symbols/debug-with-symbols-visual-studio.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/symbols/debug-with-symbols-visual-studio.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by SychevIgor** [comment]
and url here also require an update https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/_img/vsdebugger2.png?view=azure-devops

**Comment by chcomley** [comment]
Thanks @SychevIgor. I've created a work item to address this!

**Comment by AymenDaoudi** [comment]
It's been more than a year this hasn't been updated, the documentation has become ridiculous.

**Comment by ramiMSFT** [comment]
@SychevIgor Apologies for the delay and thank you for your feedback.
