### ISSUE TITLE
Can we get a list of the specific IPs used by vs-ssh.visualstudio.com?

### ISSUE THREAD

**Issue by scott1138** [MicrosoftDocs/azure-devops-docs#3769]
We need to be able to pull from our repo but the IP seems to change.  I'd rather not open all Azure IPs for SSH and adding to the list manually as it breaks is cumbersome.  Is there a published list of IPs for this service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by KNShrinidhi** [comment]
Warning: Permanently added 'ssh.dev.azure.com,65.52.8.37' (RSA) to the list of known hosts.
Why does this warning occur and how to resolve this issue?

**Comment by KNShrinidhi** [comment]
Team any update here?

**Comment by joesnyder** [comment]
This is a big need for us as well. We block SSH outgoing to all hosts unless specifically added. Adding all Azure IP's would create a huge security hole.

**Comment by rajrex205** [comment]
can restrict access to public azure repo based on SSH keys (No other machine other than the machine on which SSH keys are generated should have access to Repo)??

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
