### ISSUE TITLE
Access to variables

### ISSUE THREAD

**Issue by FerLuisxd** [MicrosoftDocs/azure-devops-docs#3785]
When running this code in the .yaml file
```
steps:

- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(mySecret)"

    # Using the env var directly:
    Write-Host "This does not work: $env:MYSECRET"

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: $(mySecret)
}
```
I can totally see my variable but when I try to access it on my .js file (using process.env.MY_MAPPED_ENV_VAR) it says undefined
Am I calling the env wrongly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by FerLuisxd** [comment]
Seems that I needed to set env in each step I wanted to use the variable, is there a way to set it basically globally?

**Comment by opncow** [comment]
> Seems that I needed to set env in each step I wanted to use the variable, is there a way to set it basically globally?

I stumbled upon this, because I was searching for a solution for exactly this question, too.  I was trying to assign an environment variable Job-wide but failed.

**Comment by juliakm** [comment]
Closing because we have information now on globally mapping environment variables and mapping them to a specific job. See the [secret variables section](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables).
