### ISSUE TITLE
'--force' from within Visual Studio

### ISSUE THREAD

**Issue by yannduran** [MicrosoftDocs/azure-devops-docs#3791]
"When enabled, this setting allows you to push --force from within Visual Studio" - how???

I've enabled the setting in Global Settings, but I see nowhere in the Sync Page UI that's any different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c28e08d-10ad-65f0-7145-0dcc9c94d780
* Version Independent ID: ca19fff9-06fa-6f95-a2fc-df12a7849112
* Content: [gitconfig files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-config?tabs=visual-studio&view=azure-devops#enable-push---force)
* Content Source: [docs/repos/git/git-config.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-config.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lg2de** [comment]
Any updates on this issue?
I'm confused like @yannduran.
When reading "enable" I expect to see a new option somewhere.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by lg2de** [comment]
I would like to reopen, but I can't.
The issue is not stalled from user side but Microsoft side.

**Comment by yannduran** [comment]
@lg2de 

Is this **still** not exposed in VS 2019 16.8's "new Git experience"? I haven't looked yet?

**Comment by lg2de** [comment]
I do not see any difference in the new git options.

**Comment by mijacobs** [comment]
@steved0x , can you take a look?
