### ISSUE TITLE
YAML Build Triggers

### ISSUE THREAD

**Issue by grecoe** [MicrosoftDocs/azure-devops-docs#3794]
Link: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

(Also in this repo)

Under Scheduled:
Scheduled builds are not yet supported in YAML syntax. After you create your YAML build pipeline, you can use pipeline settings to specify a scheduled trigger.

Except, there is no link to where to find that information and any search I'm performing (granted I'm not the best searcher) doesn't bring me to anything useful. If there is no documentation or way to do this, the documentation should be clear and not say to go find "pipeline settings to specify a scheduled trigger", which after some searching I can't find.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
