### ISSUE TITLE
How do i download Universal packages to client machines (not in pipeline)?

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/azure-devops-docs#3834]
Need information on how to programmatically download Universal packages on non-azure-pipeline machines.  All I can find is info about using the Azure Devops UI or Azure CLI which I do not want to impose on my users. The API documentation is silent on actually downloading a package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=designer)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by chasewilson** [comment]
@Paul-Dempsey Thanks for the question and I'm sorry for the late response. I believe the answer to your question is to use the Azure CLI. You can see the documentation for that here. https://docs.microsoft.com/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#download-a-universal-package

Feel free to open a new issue or respond here is you have any more questions.

**Comment by Paul-Dempsey** [comment]
yes, the whole point is to do this without the CLI.  If you look at the TOC under **Artifacts Package Types**, All of the Package types _except_ Universal  have a page named **Download Package**. Since the other nodes are actually calling the same API, it may be simply a matter that you're missing the corresponding page for Universal packages, but I took it to mean that you couldn't download Universal packages via the API. (I checked to see if it's just that the TOC is missing the entry, but hacking the URL shows that the page isn't there.

**Comment by chasewilson** [comment]
@Paul-Dempsey Thanks again for the feedback and I've had some communication with the engineering team and there will be some changes to make the documentation a bit clearer. I'll be closing this issue here but if you feel like there's more here, feel free to reach out.

**Comment by gintuoklis** [comment]
hey @Paul-Dempsey, 
Have you manged to find a way for dowloading(creating) unviverstal package?

**Comment by jaismeensandhu** [comment]
Hi @Paul-Dempsey  , Is there any other way now to download Universal packages ?

**Comment by cpyfferoen** [comment]
This is highly unfortunate. Bordering on silly and just plain difficult - I want to use a Universal Package feed for a lot of things - but if someone **HAS TO** have the Azure CLI installed - **AND** the azure-devops extension to the Azure CLI - then this just borders on (or crosses the boundary) of being **_practically_** useless. Because practicality matters in the real world.

**Comment by egbertp** [comment]
@Paul-Dempsey : could you please share with us how you've managed to download the Universal artifacts? If you didn't succeed, then please let us know. 

@chasewilson Where can we find the 'bit clearer documentation' that helps us solve this issue? There is no 'Download Package' section in the TOC to be found in the documentaion: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/universal/get%20package%20version?view=azure-devops-rest-5.1

Thanks in advance for your time!

**Comment by WilliamAntonRohm** [comment]
@chasewilson -- please look into this issue.

**Comment by cpyfferoen** [comment]
I have a "solution" working where our IT team pushed the Azure CLI out to every machine - then a UI utility i wrote 
1. installs the devops extension
2. uses the web API to query/list the packages and relevant info (after user enters PAT)
3. Calls the azure universal package commands using the web info

It is certainly functional, and wasn't that hard.. just exceptionally annoying to HAVE to lean on IT. And the authentication is separate (PAT for web API, and azure cli authenticates by loading a webpage)

**Comment by DerGary** [comment]
We would also need HTTP up and download support for our use case otherwise Universal Packages is unusable for us.

**Comment by eolamisan** [comment]
Looks like you could use PAT from file to login 
https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows#fetch-pat-from-a-file

**Comment by msebolt** [comment]
Until this is addressed by the product team, please refer to issue status [here](https://developercommunity.visualstudio.com/idea/616820/download-universal-package-rest-api.html).

The issue should remain open until the documentation can be updated accordingly.

@thomps23  Is there another alias for @alexmullans?  Possibly @infin8x?

**Comment by JeffSinclair** [comment]
You can get a download by drilling down, if you have the permissions.
Click on the package.
Click on the build on the right
Click on the Pipeline run Green Tick Icon.
The Job page comes up and should have an artifact link on it.
You can then hove over the artifact and on the right (three dots) menu the is a download artifacts link.
It even has a command to copy the download link. 

Why that link isn't right at the top? Who knows.

Jeff

**Comment by gintuoklis** [comment]
are you sure you are talking about universal packages, @JeffSinclair?

**Comment by JeffSinclair** [comment]
> are you sure you are talking about universal packages, @JeffSinclair?

@gintuoklis - ok you are right. That gives me a zip to download. In my case, I don't care because all I really want is a way to download the binaries. Perhaps there is a way for me to publish the Zip archive to the feed.

**Comment by tobiasmarciszko** [comment]
I'm in the same boat here. I have three repos where all has their own pipelines. The three artifacts from those compose a complete "install package". Since I cannot have a packaging pipeline (the packaging pipeline should just compose a install package using three pipeline artifacts), I'm using a release pipeline just to do the packaging. 

I'm struggling how to share this file via devops to whoever needs a download link (QA, other devs, PM, PO etc). I cannot tell all of them to use an obscure shell command to just download a zip file :)

How is this supposed to be handled if you can't download the package you've just created? If all other packages can be download by the click of a button, why can't universal packages?

**Comment by estebanes22** [comment]
I wonder if there's any 3rd party extensions out there for this. This is a real pain.

**Comment by mlathrop-bell** [comment]
Has anyone found a solution to this?

**Comment by cirib88** [comment]
3 years and still the same situation. All well and good, but what's the point if you can't download them via a "normal" way.

**Comment by jdorecae** [comment]
Bump. I'll be interested in being able to download a universal package directly from DevOps UI, just like the button "Download" that is available for NuGet packages.

![image](https://user-images.githubusercontent.com/45801053/162972046-8c81fd19-30d5-4132-89e9-14a39b4ebed7.png)

**Comment by ramiMSFT** [comment]
@Paul-Dempsey Thank you for your feedback! I'm going to discuss this issue with the product team, in the meantime you can upvote on this feature request [Download Universal Package REST API](https://developercommunity.visualstudio.com/t/download-universal-package-rest-api/616820). Closing this issue now.

 +@omokoh +@jorfde for awareness.

**Comment by ameinhardt** [comment]
also see https://github.com/NAVRockClimber/devops_cli_info
Organisations with projects need slight adjustment

**Comment by TimOlaleye** [comment]
one way around this to publish build artifacts with task @PublishBuildArtifacts@1 as well. this will allow you to access the build from the feed and download the files from the build. 

![tempsnip](https://github.com/MicrosoftDocs/azure-devops-docs/assets/93515174/f7ede113-9582-49a9-b1bd-66196cb45ca5)

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/93515174/a765215f-1ac9-40c3-9f81-330692036ee6)
