### ISSUE TITLE
The sdk referenced is the old sdk vss-web-extension-sdk

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#3848]
There is a new sdk that starts with Azure-devops--instead of vss-.

Plus it's pretty impossible to know from the docs which sdk to use for which server version and how to build an extension that works with tfs 2015 all the way up to azure devops server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by relexx** [comment]
The correct name is azure-devops-extension-sdk:
https://www.npmjs.com/package/azure-devops-extension-sdk

**Comment by Infinitism** [comment]
It is super frustrating since the github page for the new package references this outdated page. https://github.com/Microsoft/azure-devops-extension-sdk

**Comment by MisinformedDNA** [comment]
@elbatk ?

**Comment by elbatk** [comment]
@willsmythe this looks like a pretty popular one, may want to bring in a writer.

@MisinformedDNA hi there, I'm working over in Azure Artifacts now but Will should be able to point this one in the right direction.

**Comment by acsehi** [comment]
3 months later the doc is still outdated.

**Comment by pradeepgudipati** [comment]
It's November 2019 , And still has old documentation !!

**Comment by Diom** [comment]
Also hit this speedbump (along with #6956)

**Comment by pureliumy** [comment]
It's 2020 now, and the documentation is still old, it's just so hard to develop a dashboard widget with `azure-devops-extension-sdk`

**Comment by djeec** [comment]
I agree - it is very difficult to develop a dashboard widget without at least *one* example that show how `azure-devops-extension-sdk`, `azure-devops-extension-api` and `azure-devops-ui` work together

**Comment by chcomley** [comment]
Adding @apawast for guidance and updates to article. Thank you.

**Comment by juangps96** [comment]
May be some Forum in order to ask questions of this components? 

https://developer.microsoft.com/en-us/azure-devops/

**Comment by chcomley** [comment]
Hi everyone,
Our extensions articles on docs.microsoft.com are certainly in need of a refresh. Having said that, I don't know when we'll be resourcing this work. However, there's great news - we have guidance on extension development using the [Azure DevOps Extension SDK](https://developer.microsoft.com/azure-devops/develop/extensions) on our developer site. Please follow that link! I'll be closing this issue, as I've created a user story for my backlog. Don't hesitate to @mention me, however. Take care.

**Comment by MisinformedDNA** [comment]
@chcomley Does this not belong in docs.microsoft.com? Also, I can't find any way to navigate to [this page](https://developer.microsoft.com/azure-devops/develop/extensions) from https://developer.microsoft.com or https://docs.microsoft.com.

**Comment by chcomley** [comment]
Hi @MisinformedDNA, You're absolutely correct, that this issue is in the right place, however I don't know when we'll be resourcing for the extensions set of documentation improvements. I've heard next month. Either way, I have the user story to track the work, so I chose to close this issue. I added a note at the top of this article that has a link to the newest SDK information on the developer.microsoft.com website. Hope you're having a nice day. Thanks!

**Comment by GaTechThomas** [comment]
Can we please get an update on the status of Azure DevOps? This level of dilapidation of documentation has the markings of a product that is being retired. If that's the case, it would be devastating to many thousands of developers using the system, and hundreds at my company alone.

**Comment by MisinformedDNA** [comment]
@GaTechThomas GitHub is the future. There is still development happening for AZDO, but most of the work is happening in GitHub. In fact, Azure DevOps development is now done by GitHub.

**Comment by chcomley** [comment]
Hi @GaTechThomas, MisinformedDNA is not a Microsoft employee. We continue to invest in both GitHub and Azure DevOps and support the customers who use them today. Azure DevOps has an active and up to date roadmap found here: [Azure DevOps Feature Timeline](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Frelease-notes%2Ffeatures-timeline&data=04%7C01%7CChrystal.Comley%40microsoft.com%7C6ff958afca5a4a056bd808d93294225a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637596434084376017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qjKUpxBPeX8BPlDSmN3VGaRM4t0lJAmVKvDKf1s%2BVIM%3D&reserved=0)  and GitHub's public roadmap can be found [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgithub%2Froadmap%2Fprojects%2F1&data=04%7C01%7CChrystal.Comley%40microsoft.com%7C6ff958afca5a4a056bd808d93294225a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637596434084376017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wFvowIVm1l5Y2qGQNI%2Fs9%2B1eP8e%2B3Hd%2BiAVohtVTm9Y%3D&reserved=0). Additionally, we continue to invest in ensuring the products have native integrations between them to allow flexibility and choice.
The extensions documentation resourcing prioritization remains the same at this point. 
Thanks,
Chrystal

**Comment by MisinformedDNA** [comment]
@chcomley Yeah, but when was the last conference that AZDO was mentioned? It's always GitHub, GitHub, GitHub. This issue has been open for 3 years and there are countless other issues, bugs and feature requests that are all ghosted by the development team. I know development is still active, but, to me, it's obvious that AZDO isn't getting the same love that it once did.

**Comment by bjaging** [comment]
Yet another request for a follow up on this one @chcomley, or anyone else really. I get that there is a need of a cleanup now and then on stale issues but in what sense is this issue closed? If I search issues by "azure-devops-extension-sdk" and "widget" I get at least 3 of the same / similar complaints and they are all closed. It feels like screaming into the void at this point.

**Comment by chcomley** [comment]
Hi all, I've been in contact with a PM who will help me get an example that shows how azure-devops-extension-sdk, azure-devops-extension-api and azure-devops-ui work together as well as which sdk to use for which server version. I believe that sums up the ask here. Speak up if I'm missing something.

**Comment by jessehouwing** [comment]
Can you add how to service different server versions *and* the service from a single extension?

So, how to prevent having to build 6 different versions of the extension and publish them to the marketplace.

The end result would be a single extension with a single extension ID that can be installed in a range of server versions and won't give issues when upgrading servers ir importing them into the service.

**Comment by chcomley** [comment]
Got it. Thanks @jessehouwing!

**Comment by chcomley** [comment]
Adding @bjanousek, thank you

**Comment by MisinformedDNA** [comment]
Yay!

**Comment by chcomley** [comment]
@MisinformedDNA, I know, right?! :)
