### ISSUE TITLE
Incorrect compatibility information

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/azure-devops-docs#3857]
&gt; Windows agent using either a Batch script task or PowerShell script task.
&gt; macOS or Linux agent using a Shell script task.

Incorrect - both Powershell (`pwsh` task) and bash supported on all the platforms (although bash didn't work on Windows for me).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-au/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by juliakm** [comment]
Looks like this has already been fixed.
