### ISSUE TITLE
Documentation FIX for this process

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/azure-devops-docs#3864]
As other comments have noted this is not sufficient information to actually unlock a file for many people in current versions of the product, the most common "problem" is that the admin gets an error identifying the user associated with the workspace.  

To work around this they can add /format:xml to the workspaces command and that will make the returned info contain an ownerID string they can use to specify the user in subsequent commands, for ex.

tf workspaces /owner:* /computer:&lt;ComputerName&gt; /collection:&lt;ServerName&gt; /format:xml

Then when running the tf lock command they can use the OwnerID rather than the Name (which does not always resolve) on the /Owner Parameter.  

This is not an uncommon action and the documentation needs to cover this scenario.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8094c196-2710-d407-79b0-7e5b1a0a21fb
* Version Independent ID: 81eda8a8-71cd-b07d-0020-3a6c99e5aec3
* Content: [Lock and unlock folders or files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/lock-unlock-folders-files?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/repos/tfvc/lock-unlock-folders-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/lock-unlock-folders-files.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juangps96** [comment]
Is there any way to call the Lock Command from REST API?

**Comment by RuslanRasulovAkv** [comment]
#reassign @RuslanRasulovAkv
