### ISSUE TITLE
Azure PowerShell Az module

### ISSUE THREAD

**Issue by tpeiffer** [MicrosoftDocs/azure-devops-docs#3869]
Per documentation, all new cmdlets are only added to the Az module, not AzureRM.  Is there a way to use this task and have the Az module loaded?  For example, I'm trying to manage the azure blob storage lifecycle but am not sure that this is the right task to use in the new world.

Reference:
https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by tpeiffer** [comment]
For those who follow my breadcrumbs here, the solution as of this comment is to use v4 of the Azure Powershell task.  This loads the Az cmdlets.

**Comment by chrissans777** [comment]
Fantastic! Worked perfectly thank you for your input.

**Comment by mzaatar** [comment]
Worked! thanks

**Comment by alex-zyl** [comment]
Any ETA for upgrading agent pools to Az 1.1.0?

**Comment by fluffy-cakes** [comment]
This module is soooooooooooooooo far behind. Look at the current version!

https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.4.0&viewFallbackFrom=azps-2.1.0

**Comment by fluffy-cakes** [comment]
So even using the Preview version I am prompted with an error because it can't even log in to run commands:

`##[error]Could not find the modules: 'Az.Accounts' with Version: '1.0.0'. If the module was recently installed, retry after restarting the Azure Pipelines task agent.`

I've also tried this with v2.1.0, 2.4.0 and 'latest'. Anyone else actually get this going?

**Comment by MisinformedDNA** [comment]
Works for me.

**Comment by dannradkov** [comment]
Do we have any estimates for when Azure PowerShell v4 task in Azure DevOps will be out of preview? We need GA ;)

**Comment by akshaykg** [comment]
not working for me "This module requires Az.Accounts version 1.6.2. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your system. Please see https://aka.ms/azps-version-error for troubleshooting information."

**Comment by grlima** [comment]
Regarding the version 4 Preview - It looks like the module Az.ManagedServiceIdentity is not automatically installed with AZ . See https://github.com/Azure/azure-powershell/issues/8555 for details. 

Can this task be updated so it also installs that module?

**Comment by grlima** [comment]
Okay, version 4 is out of preview and it seems I can no longer use Az.ManagedServiceIdenty. The first thing I do in my script is to install it (Install-Module Az.ManagedServiceIdenty). This was working fine, but I now I get the following error (later in the script when I try to use one of the cmdlets):

The 'Get-AzUserAssignedIdentity' command was found in the module 'Az.ManagedServiceIdentity', but the module could not be loaded. For more information, run 'Import-Module Az.ManagedServiceIdentity'.

**Comment by sdavis3** [comment]
Have tried using version 4 and 5.* (preview) and get the same error: 

##[error]Could not find the modules: 'Az.Accounts' with Version: ''. If the module was recently installed, retry after restarting the Azure Pipelines task agent.

**Comment by sdavis3** [comment]
Reverting the task to version 3 solves the issue as a workaround for me. This implies something related to Az.Accounts is broken in version 4 and has not yet been resolved in version 5.* (preview).

**Comment by igor-teresco** [comment]
Just to clarify one possible confusion (had same issue today) - task until v4 does require a "azureps" demand from your build agent. V4 and v5 doesn't and this can confuse you that there is no need to install Az powershell module on build machine. But that is required anyway...
Solved "Сould not find the modules: 'Az.Accounts' with Version: ''.

**Comment by dshaevel** [comment]
When I use version 4.159.11 of the Azure PowerShell task on a self-hosted Windows Build agent, I get the following error:

`2020-01-31T04:31:41.5076616Z ##[error]Could not find the modules: 'Az.Accounts' with Version: ''. If the module was recently installed, retry after restarting the Azure Pipelines task agent.`

<img width="1041" alt="Azure_PowerShell_task_error" src="https://user-images.githubusercontent.com/1748035/73581043-8e5f4400-444d-11ea-8834-9b1f1732c3ed.png">

When I run the pipeline again, with this exact same Azure PowerShell task, but on a self-hosted Linux Build agent, the task executes successfully.

<img width="1170" alt="Azure_PowerShell_task_success_on_Linux" src="https://user-images.githubusercontent.com/1748035/73581274-3d038480-444e-11ea-89f5-60e18f86c5fd.png">

Here is what my Azure PowerShell task configuration looks like:

<img width="1178" alt="Azure_PowerShell_task_configuration" src="https://user-images.githubusercontent.com/1748035/73581453-e9456b00-444e-11ea-880c-04497935de71.png">

When I switch the Task version to "5.* (preview)", then the task successfully executes on the self-hosted Windows Build Agent.

I am suspicious that there is a bug in version 4 of the Azure PowerShell task that is specific to Windows Build Agents.

On my **self-hosted Windows Build Agent**, the following is installed:
- PowerShell 6.2.3
- Azure PowerShell module 3.3.0
- azureps capability is specified

On my **self-hosted Linux Build Agent**, the following is installed:
- PowerShell 6.2.4
- Azure PowerShell module 3.3.0
- azureps capability is specified

@Microsoft - Can you confirm that there is, indeed, an issue with version 4 of the Azure PowerShell task that is specific to Windows build agents?

Thanks,
-David Shaevel

**Comment by abatishchev** [comment]
No matter what version I try (4.x or 5.x preview) and what option I select I'm getting the following error:

>Could not find the modules: 'Az.Accounts' with Version: ''

When select use the latest version (of PowerShell Core), or

>Could not find the modules: 'Az.Accounts' with Version: 'x.y.z'

When select to use version x.y.z (again, not matter what I try, from 1.0.0 to 6.2.2).

**Comment by raghavkochhar** [comment]
Facing similar issue with Az.Accounts not found module error with Task versions 4 and 5.

Any resolution here?

Thanks

**Comment by abatishchev** [comment]
@steved0x I see the issue assigned to you. Can you please comment? Do you know who's the technical owner of this task?

**Comment by lucianogelasio** [comment]
I create an account here just for reply this because I'm stuck on this same exact problem for a while.

Here is what I did:
**Problem:**
Error message: `Could not find the modules: 'Az.Accounts' with Version: '' on Azure pipeline`
![image](https://user-images.githubusercontent.com/64201400/80094208-c4e4c080-855d-11ea-82be-4b171fc55b6a.png)

**Solution:**
1. In the host you want to run the PoweShell script (in my case an Azure VM) open PowerShell and run
`Get-InstalledModule Az.Accounts -AllVersions`

2. if that gave you an error that's your problem (it was mine) and you have to install the Az.Accounts basically. For that it's easy like this: 
`Install-Module -Name Az.Accounts -RequiredVersion 1.6.2` ([](https://www.powershellgallery.com/packages/Az.Accounts/1.6.2))

3. Reply 'Y' to everything.

4. Now if you try the `Get-InstalledModule Az.Accounts -AllVersions` again it will give you the version of your Az.Accounts

5. After that I run the pipeline again and the error goes away and the script run on server!
![image](https://user-images.githubusercontent.com/64201400/80094334-f78eb900-855d-11ea-80a4-5ba6e05277fa.png)


I used **version 5 Preview**

**Comment by jeremytbrun** [comment]
> When I use version 4.159.11 of the Azure PowerShell task on a self-hosted Windows Build agent, I get the following error:
> 
> `2020-01-31T04:31:41.5076616Z ##[error]Could not find the modules: 'Az.Accounts' with Version: ''. If the module was recently installed, retry after restarting the Azure Pipelines task agent.`
> 
> <img alt="Azure_PowerShell_task_error" width="1041" src="https://user-images.githubusercontent.com/1748035/73581043-8e5f4400-444d-11ea-8834-9b1f1732c3ed.png">
> 
> When I run the pipeline again, with this exact same Azure PowerShell task, but on a self-hosted Linux Build agent, the task executes successfully.
> 
> <img alt="Azure_PowerShell_task_success_on_Linux" width="1170" src="https://user-images.githubusercontent.com/1748035/73581274-3d038480-444e-11ea-89f5-60e18f86c5fd.png">
> 
> Here is what my Azure PowerShell task configuration looks like:
> 
> <img alt="Azure_PowerShell_task_configuration" width="1178" src="https://user-images.githubusercontent.com/1748035/73581453-e9456b00-444e-11ea-880c-04497935de71.png">
> 
> When I switch the Task version to "5.* (preview)", then the task successfully executes on the self-hosted Windows Build Agent.
> 
> I am suspicious that there is a bug in version 4 of the Azure PowerShell task that is specific to Windows Build Agents.
> 
> On my **self-hosted Windows Build Agent**, the following is installed:
> 
> * PowerShell 6.2.3
> * Azure PowerShell module 3.3.0
> * azureps capability is specified
> 
> On my **self-hosted Linux Build Agent**, the following is installed:
> 
> * PowerShell 6.2.4
> * Azure PowerShell module 3.3.0
> * azureps capability is specified
> 
> @microsoft - Can you confirm that there is, indeed, an issue with version 4 of the Azure PowerShell task that is specific to Windows build agents?
> 
> Thanks,
> -David Shaevel

@dshaevel I get the exact same behavior on my Windows agents.

**Comment by marchenm** [comment]
I've been trying to get this task to work with the provided Microsoft docker image of [Azure PowerShell](https://hub.docker.com/_/microsoft-azure-powershell) using the target container spec for the task and that errors out with the same error.

**Comment by abatishchev** [comment]
@steved0x gentle ping, please.

**Comment by rahg-bmake** [comment]
Facing the same issue with Azure Powershell v5 and v4. Eagerly waiting for resolution.

**Comment by abatishchev** [comment]
@mijacobs do you know who can help us on this, please?

**Comment by rahg-bmake** [comment]
Using Powershell from Azure CLI task worked.

**Comment by KenSpur** [comment]
Hey Guys,

For this issue
![image](https://user-images.githubusercontent.com/29839543/111835082-c85f0400-88f4-11eb-8199-16116503721e.png)

Making sure the Az module is installed for all or at least the agents user solved it for me.

**Comment by abatishchev** [comment]
The problem is with the Hosted Pool where users usually don't have access so can't install any additional software.

**Comment by KenSpur** [comment]
@abatishchev  Ok cool, thanks!

I ended up here googling the Error when working with a self hosted agent, so just for those who are in the same boat then ^^

**Comment by hectormmg** [comment]
Are there any updates on the status of this issue? Tried all of the workarounds discussed here and other forums and I haven't been able to run the Azure Powershell task successfully because of the ' 'Could not find the modules: 'Az.Accounts' with Version: ''. ' error.
