### ISSUE TITLE
Enforce a merge strategy Section Need Updates to reflect Sprint 150's work

### ISSUE THREAD

**Issue by denhsu** [MicrosoftDocs/azure-devops-docs#3936]
Enforce a merge strategy Section Need Updates to reflect Sprint 150's work

https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#new-merge-types-for-completing-pull-requests

Thanks,
Dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by abatishchev** [comment]
Ping. The doc is out-dated.
