### ISSUE TITLE
Merging also happens during a rebase

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/azure-devops-docs#3943]
I was doing a rebase and needed to merge. I was left confused about whether the code in my branch is the source or target pane in the Visual Studio's merge window. I feel it would help if this page explained that a bit more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e2ddbb-512d-fe28-55c2-bfc4ff8aad73
* Version Independent ID: 9b7770d7-7f5d-3cb7-c619-a5cd23b5da09
* Content: [Resolve Git merge conflicts - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/merging.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by tsahi** [comment]
Yes. It seems to me that when resolving rebase conflicts, e.g. from master to feature branch, the Target is the master and the Source is the branch.

**Comment by rroman81** [comment]
yes. when rebasing, you are essentially replaying the changes against the target branch "master", so your topic branch will be the source branch.  If merges cannot be fast-forwarded, you will be generating another commit, otherwise source commits can be added to the new history.  I would agree that Visual Studio should clear up and make it explicit for more novice developers.

**Comment by jrichview** [comment]
Yes, the terms "Source" and "Target" can be confusing if using GIT, especially when used in the context of a Rebase Onto operation. Until Visual Studio makes this less confusing, it would be very helpful for this documentation page to make very clear which is which. And it's not like DIFF tools make it obvious.

**Comment by tsahi** [comment]
This could be resolved soon by fixing the Visual Studio UI: https://developercommunity.visualstudio.com/idea/502400/resolve-conflict-source-and-target-is-confusing.html
