### ISSUE TITLE
Tool Installer for Python are not working on a self hosted Windows Agent

### ISSUE THREAD

**Issue by egde** [MicrosoftDocs/azure-devops-docs#3999]
The Tool Installer for Python (Task : Use Python Version) is not working on a self-hosted Windows Agent. It just notes that the Python version cannot be found.

I downloaded a Python 3.6 into the _tool folder and followed the scheme described [here](https://github.com/Microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md#tool-cache).

However no success....

##[error]Version spec 3.6 for architecture x64 did not match any version in Agent.ToolsDirectory.

![image](https://user-images.githubusercontent.com/4752846/56310574-864b4780-614c-11e9-9ab8-8f65d6087a6b.png)

Folder Setup in Tools:

![image](https://user-images.githubusercontent.com/4752846/56310660-bdb9f400-614c-11e9-9109-8e4b8d43598e.png)

**Comment by bharathidurairaj** [comment]
Hello All,

Is there any luck on the above issue.

Cheers,
Bharathi Durai Raj

**Comment by majorvin** [comment]
Any news on this?

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
