### ISSUE TITLE
deploy.sh is not found

### ISSUE THREAD

**Issue by syendev** [MicrosoftDocs/azure-devops-docs#4029]
https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=azure-devops

Following the [tutorial](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=azure-devops) I do not see a deploy.sh file as indicated at: 

`$(System.DefaultWorkingDirectory)/nodejs-sample/drop/deploy/deploy.sh`

Where is it? either fix the tutorial or provide steps to locate it prior to closing this issue.

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by eqinox76** [comment]
For other people coming here via search engine: 
The script seems to have moved according to https://github.com/MicrosoftDocs/azure-devops-docs/issues/2593 . Currently it's unclear what the deploy.sh contains.
