### ISSUE TITLE
Referencing images in "content" overview.md

### ISSUE THREAD

**Issue by praneetloke** [MicrosoftDocs/azure-devops-docs#4107]
I tried to reference screenshots that were local to my extension in my version of `overview.md` that I used with the `content` property. However, that doesn't render the image. I even tried to specify my screenshots folder using the `files` property to no avail. What is the correct way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#files)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @praneetloke, Thanks for submitting your question. I'm adding @willsmythe for his guidance. Thank you!

**Comment by praneetloke** [comment]
Thanks! As a workaround, I ended up uploading my screenshots to GitHub and using those links in my content file.

**Comment by chcomley** [comment]
Hi @praneetloke, Please accept our apology for losing sight of this issue. Glad you found a workaround! There is a more recent issue for this article, which I've added your feedback to so we can be sure it's properly addressed. I'm closing this issue, so please reference [this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6189) and you can @mention me if you have any further questions or concerns.  

Thank you!
