### ISSUE TITLE
Orphaned Page

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#4176]
Looks like this page got orphaned at some point, took forever to find it with google:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub-group?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b68bebb-14b6-8f83-b362-03d643d39538
* Version Independent ID: de6d224b-2a80-b093-0330-4f70b5892fe3
* Content: [Add a Hub](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-hub?view=azure-devops)
* Content Source: [docs/extend/develop/add-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-hub.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @davidcorrigan714, thanks so much for this feedback. I'm glad you actually found it! I'm looking into this now.

**Comment by chcomley** [comment]
Hi @davidcorrigan714, We published a fix for this issue sometime ago, so I'll be closing this issue. Thanks so much for your feedback!
