### ISSUE TITLE
Hub Icons

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/azure-devops-docs#4177]
Can we get this added to the docs?
https://stackoverflow.com/questions/53582701/manifest-icons-in-custom-azure-devops-extension-hubs-and-hub-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?toc=/azure/devops/extend/toc.json&bc=/azure/devops/extend/breadcrumb/toc.json&view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by davidcorrigan714** [comment]
Never mind, that answer seems to be outdated. It's just "Icon" in properties and I had messed up adding the file to the bundle.

**Comment by chcomley** [comment]
Thanks for your feedback, @davidcorrigan714. I'll go ahead and close this issue. Please @mention me if you have any further questions or feedback. Thank you!
