### ISSUE TITLE
Documentation for XCode 10 is out dated

### ISSUE THREAD

**Issue by philmartin83** [MicrosoftDocs/azure-devops-docs#4204]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Is there any chance you can update the documentation (https://docs.microsoft.com/en-us/azure/devops/repos/git/share-your-code-in-git-xcode?view=azure-devops#feedback) this no longer is applicable for XCode 10 and greater

**Comment by thomps23** [comment]
@philmartin83 is this related to the Azure Repos content, or the Azure Pipelines content, or both?

**Comment by philmartin83** [comment]
@thomps23 it's related to the Azure repo content, there is no longer an option to create a working copy anymore, I think this became redundant in the previous version of XCode (XCode 9)

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
