### ISSUE TITLE
Odler content?

### ISSUE THREAD

**Issue by ifucak** [MicrosoftDocs/azure-devops-docs#4208]
Please update this sentence:
Note that once a collection is imported, it is not possible to migrate a project to the Inheritance process model. That is on our roadmap for end of 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20e7fb4b-29e6-95b4-001c-7cffd985039d
* Version Independent ID: 24d7d477-d998-7544-a8f4-456f37698408
* Content: [Validation of process templates for migration import from https://marketplace.visualstudio.com/items?itemName=ms.feed# to Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-processtemplates?view=azure-devops#feedback)
* Content Source: [docs/migrate/migration-processtemplates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-processtemplates.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
