### ISSUE TITLE
Big picture how to provide build artifacts for download

### ISSUE THREAD

**Issue by mapfel** [MicrosoftDocs/azure-devops-docs#4228]
We have a build script to compile the projects, run additional tasks and create at the end an MSI.
With other CI systems, it was easily possible to provide these MSI at a drop location for the testers to download.

With Azure DevOps Pipelines and belonging tasks, I don't know how to start.
There are these "Publish Pipeline Artifact" and "Publish Build Artifacts" tasks. Both I cannot get to run in a proper way.

For "Publish Build Artifacts" there is the "Artifact publish location". In case to chose "File Share: what File Share should that be? From an Azure resource (VM??)
In the case of "Azure Pipelines/TFS": what means that? Later I can download a ZIP, but that is always empty. I tried a lot of different "Path to publish". 

It would be nice to have a quick start, how to build something and download it via drop location.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
