### ISSUE TITLE
How do I authorize a secure file for use in one specific pipeline

### ISSUE THREAD

**Issue by cilliemalan** [MicrosoftDocs/azure-devops-docs#4242]
The question of how to authorize a secure file for use in all pipelines is [answered above](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops#how-do-i-authorize-a-secure-file-for-use-in-all-pipelines).

But how does one authorize a secure file for use in *only one* pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops#how-do-i-authorize-a-secure-file-for-use-in-all-pipelines)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **madhurig**

**Comment by andyjlewis** [comment]
@thomps23 please assign to @madhurig

**Comment by madhurig** [comment]
Does this help? https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops

**Comment by haokanga** [comment]
@madhurig Secure files work for all pipelines in a project, and there is no way to use Secure files for only 1 specific pipeline. Probably Azure Key Vault can help.

**Comment by madhurig** [comment]
When you authorize the resources via the authorization prompt in the pipeline, the resource will be authorized just for that pipeline. This applies for secure files and service connections too.

**Comment by msebolt** [comment]
Closing this issue now.
