### ISSUE TITLE
Clarify whether existing service connection for GitHub during CI setup can be re-used

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#4260]
I'm getting:
> Step GitHubRelease input gitHubConnection expects a service connection of type github with authentication scheme OAuth,PersonalAccessToken but the provided service connection ... is of type GitHub using authentication scheme InstallationToken

This is very confusing to say the least. Do I really need to create a separate service connection?
I just tried to start doing that and when clicking on Authorize then GitHub asks me to grant the following permissions:
> This application will be able to read and write all public and private repository data. This includes the following:
    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
    Collaboration invites
This application will have full access to repository webhooks and services (no direct code access). 
This application will be able to read your private email addresses and read your private profile information.

And this would automatically include access for multiple organizations I'm a member of, including "microsoft" and "Azure".

All this seems way over the top and too risky to grant access. How can I limit access to just allow publishing releases for a specific repository or organisation? Because that's the only thing I want to do. Do I have to fall-back to using a PAT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
