### ISSUE TITLE
Project Collection Build Service doesnt exists as User

### ISSUE THREAD

**Issue by nlreturns** [MicrosoftDocs/azure-devops-docs#4267]
I can add a Project Collection Build Service(organisation name), but my agents dont seem to inherit these settings

https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml

**Comment by ramiMSFT** [comment]
@nlreturns Thank you for your feedback. Please see [Troubleshoot your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/troubleshooting?view=azure-devops) for more info on how to debug your build and release pipelines.
For product related issues, please post your questions on the [Azure DevOps developer community](https://developercommunity.visualstudio.com/spaces/21/index.html).
