### ISSUE TITLE
So what can you do with a menu action and how?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-docs#4303]
This page gives you just enough information to write a completely useless menu action. What now? What's the `actionContext` what can I do with it? Does it have a type? Does it change based on where the menu action is (i.e. PR menu vs Build menu)?

It should probably also have a link to https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#menus-and-toolbars or contain a list of available locations to use menus so that users can see what is available to them.

If there is some external documentation or samples you can send me in the meantime, I would appreciate that. I'd like to create a menu in PRs, but I'm totally dumbfounded on what to do next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c5725d-4a59-7019-7dd8-c77be8456e45
* Version Independent ID: b45dc1c1-3ba0-b517-8aa8-c947cfc1f2a2
* Content: [Add an Action](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-action?view=azure-devops)
* Content Source: [docs/extend/develop/add-action.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-action.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by juangps96** [comment]
Yes, please, put a reference, at least with this link:  https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#menus-and-toolbars

I could realize that this menu appeared in somewhere like: "Shared Queries" ... "More Actions"

Because of the target: 

"targets": [
                "ms.vss-work-web.work-item-query-menu"
            ],

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance, thank you!

**Comment by chcomley** [comment]
This issue is super old, however I've just published links to more information within the article, which should be live momentarily. Please @mention me if you have any additional feedback or questions. Thank you.
