### ISSUE TITLE
Explain 'publishWebProjects'

### ISSUE THREAD

**Issue by karataliu** [MicrosoftDocs/azure-devops-docs#4308]
Related https://stackoverflow.com/questions/53342200/azure-pipeline-publish-task-dotnetcorecli-with-specific-folder-or-project
If publishWebProjects==true, property is not used. Can this be documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by karataliu** [comment]
'This issue hasn't been updated in more than 180 days' because no one answers. it's still a valid, can you repoen it?
@mijacobs  @ramiMSFT

**Comment by mijacobs** [comment]
@ramiMSFT can you take a look?
@karataliu : We also accept contributions to the docs--if you'd like to see this updated sooner and have the info you need, please add the info and submit a PR. We have a team of PR reviewers standing by to help folks update the docs.

**Comment by ramiMSFT** [comment]
@karataliu My apologies for the delayed response. I will add that to the docs shortly.
