### ISSUE TITLE
Sample App Code URL doesn't exist

### ISSUE THREAD

**Issue by jamesmcroft** [MicrosoftDocs/azure-devops-docs#4341]
The URL provided for the sample app code (https://github.com/Microsoft/UWPQuickStart) doesn't appear to exist. 

Navigating to the URL provides a 404 on GitHub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b846f94-2bb5-d5a8-63c8-8227ab1b613b
* Version Independent ID: 5ba1aaac-6076-c5e0-fec0-c2ac2405b138
* Content: [Build your Universal Windows Platform app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/universal?view=azure-devops&tabs=vsts#feedback)
* Content Source: [docs/pipelines/apps/windows/universal.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/universal.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by scout208** [comment]
I can confirm it still doesn't exist

**Comment by jamesmcroft** [comment]
Looking at what has been cached in web history, the repo was last recorded as existing in January 2019 with the last commit history being September 2017.

I wonder if the repo became redundant with the UWP docs becoming better. That being said, this documentation could do to have a useful, simple sample app to work alongside the Azure Pipeline docs

**Comment by jamesmcroft** [comment]
Digging into this further, @rido-min seemed to be the last contributor to commit to the branch based on the archived history. 

The URL that was associated with the repo takes you to the **[Create a "Hello, world" app (XAML)](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)** documentation in the UWP docs. 

There's also a GitHub pages site for the UWP Quick Start project which also has links to the now missing repo - https://microsoft.github.io/UWPQuickStart/

**Comment by rido-min** [comment]
The repo has been marked as private. @karann-msft or @diverdan92  might know more

**Comment by MillerDan** [comment]
You can get the repo from here https://github.com/ValdimarThor/UWPQuickStart

**Comment by jamesmcroft** [comment]
I suppose this goes as a question to @andyjlewis or @chasewilson as to whether the documentation needs updating to remove the information, or we link to this fork of the repo? I assume there was a reason it was made private by Microsoft in the first place.

**Comment by MillerDan** [comment]
@jamesmcroft - I agree.  I was having the same issue going through the sample app and thought I would share this alternative repo.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by jamesmcroft** [comment]
This is still an issue. The live docs page for building UWP apps in DevOps refers users to download a GitHub repo that doesn't exist.

**Comment by mijacobs** [comment]
@ramiMSFT : can you take a look?
@jamesmcroft :  We also accept contributions to the docs--if you'd like to see this updated sooner and have the info you need, please add the info and submit a PR. We have a team of PR reviewers standing by to help folks update the docs.

**Comment by jamesmcroft** [comment]
@mijacobs the problem isn't really in the doc itself, it's that the link provided reaches a private repo which has previously been mentioned. 

I don't think there is another Microsoft sample UWP app for this which would be appropriate. 

I'd rather not want to rewrite the doc unless that is an option 😄

**Comment by mijacobs** [comment]
Thanks, @jamesmcroft. @ramiMSFT, I have contacts on the UWP team if you need them.

**Comment by ramiMSFT** [comment]
@jamesmcroft My apologizes for the delayed response and thank you for your feedback. A backlog item has been created and I will be updating the article shortly.
