### ISSUE TITLE
Can I run Tests from Test Suit from my CI/CD Pipeline

### ISSUE THREAD

**Issue by Planche95** [MicrosoftDocs/azure-devops-docs#4353]
Hi, 

I'm reading documentation and I'm confused about one thing:

[Associate automated tests with test cases](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)

>  Tests can be run in the CI/CD pipeline by choosing the test plan or test suite in the settings of the Visual Studio Test task.

But when I go to [Visual Studio Test task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)

> Test run: Use this option when you are setting up an environment to run tests from test plans. This option should not be used when running tests in a continuous integration /continuous deployment (CI/CD) pipeline.

Which statement is true? Should I use Test Run in CI/CD?

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
