### ISSUE TITLE
Link to turning off continuous deployment

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/azure-devops-docs#4421]
Once you've set up the pipeline, you should display the WebApp for Containers deployment, include above to https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ci-cd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* Content: [Deploy a Docker container app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@pulkitaggarwl - can you please take a look?

**Comment by pulkitaggarwl** [comment]
@phatcher  thanks for the input. 
If I understood correctly, you are suggesting to have link of [this ](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ci-cd)document [here ](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops)and vice-versa. 

Is there something more here that I am missing ?

**Comment by phatcher** [comment]
No that's about it - it would be useful to have something like

"Now you can turn off the Continuous Deployment setup when you configured Web App For Containers"

as on the first time through you are not familiar with the portal tabs.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by phatcher** [comment]
Would have thought it would be better to fix this than leave it open for 18 months
