### ISSUE TITLE
Should be a warning Toast that only a few tasks support Management Group service connection yet

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/azure-devops-docs#4450]
There should be a warning that not all tasks support the Management Group method yet. For instance AzFunctionApp fails with an obtuse error if you don't know what is going on:

0##[warning]Can\'t find loc string for key: SubscriptionIdCannotBeNull
11##[error]Error: SubscriptionIdCannotBeNull

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by thomps23** [comment]
@JustinGrote Thanks for the feedback. We'll see how we can address it in this topic, but by Toast did you mean a warning in the service itself? If so you can [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by JustinGrote** [comment]
No I just meant a callout or warning block in the documentation. Thank you.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by JustinGrote** [comment]
@thomps23 any update on getting this updated?

**Comment by JustinGrote** [comment]
"Unfortunately, we have been unable to review this issue in a timely manner. We apologize for the delayed response. We are closing this issue." 

So the fact that it wasn't reviewed makes it my fault and you're closing the issue so you don't have to address it? Not a good look...
