### ISSUE TITLE
Screen shot shows options that are not available on Azure Devops Server 2019 (on prem) or on Azure Devops (hosted)

### ISSUE THREAD

**Issue by abbottbd** [MicrosoftDocs/azure-devops-docs#4479]
This image at the top of the document,
![image](https://user-images.githubusercontent.com/19344687/59290902-86d4fb80-8c2e-11e9-8141-5bc8c64f09ea.png)

as well as the text around it:  

> can change this behavior by selecting one of the options to use the latest build from a specific branch by specifying the tags, a specific version, or allow the user to specify the version when the release is created from the pipeline.

Indicate that you should be able to filter the artifact source consumed from a build pipeline based on 'tags', however this option is not available in either the onprem or hosted versions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598465e1-85d4-4961-b8b6-902d6026c5e3
* Version Independent ID: 5ef1308a-3aeb-fcc4-dec7-6f10785612a3
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2019#teambuild)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by abbottbd** [comment]
Adding some supporting screen shots - this one is from my azure devops (hosted) account:
![image](https://user-images.githubusercontent.com/19344687/59302397-c3adec00-8c48-11e9-8fe7-b815d140813b.png)

This is from our on-prem trial upgrade to azure devops 2019 from TFS 2017 Update 3.
![image](https://user-images.githubusercontent.com/19344687/59302609-3323db80-8c49-11e9-9c73-eded23213660.png)

**Comment by thomps23** [comment]
@abbottbd Thanks for the additional examples.

**Comment by RoopeshNair** [comment]
@ashokirla  - can you please take a look?

**Comment by ashokirla** [comment]
@Lovakumar Can you please take a look.

**Comment by Lovakumar** [comment]
@abbottbd the options shown for default version drop down are controlled by the **repository type** of the build definition that is being linked.

"Specify at the time of release creation", "Specific version" and "Latest" are supported for all repository types.

"Latest from a specific branch with tags" and "Latest from the build pipeline default branch with tags" are supported for "TfsGit", "GitHub", "Bitbucket", "GitHubEnterprise" and "Git" repository types.

"Latest from the build pipeline default branch with tags" is **not** supported for XAML build definitions.

**Comment by ramiMSFT** [comment]
@abbottbd Thank you for the feedback. The new version of the article will go live shortly.
