### ISSUE TITLE
What about the basic logging commands?

### ISSUE THREAD

**Issue by johncrim** [MicrosoftDocs/azure-devops-docs#4480]
Eg `##[error]` or `##[warning]` (examples here: http://hauge.cloud/2018/06/22/improving-logs-in-visual-studio-team-services-vsts-with-special-tags/ )

They really should be included in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **alewis**

**Comment by deploymentking** [comment]
It's not clear from this doc...if you want to output a nice green message do this...
```
echo "##[section]message = ${local_variable}"`
```

**Comment by onstwedder** [comment]
Thanks @deploymentking I was looking for just that.

**Comment by ramiMSFT** [comment]
@johncrim Thank you for your contribution. The article has been updated.
