### ISSUE TITLE
Consume Artifacts

### ISSUE THREAD

**Issue by syonekura** [MicrosoftDocs/azure-devops-docs#4490]
Hi, I have a separate build that generates an artifact stored in Azure. Now I have a second pipeline that needs to consume that artifact, but there's no info about how to generate credentials to be able to consume the artifact repo in another isolated build. 

The ideal would be to have a step that generates some env variable with the credentials, that I could inject into the docker build that internally installs the dependency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **elbatk**

**Comment by noelbundick** [comment]
I was actually working on a PR to add this to docs when I saw your comment. Until it lands, please take a look at the following gist that I've extracted from a working pipeline

https://gist.github.com/noelbundick/0262aa0f37ec3f9a179137c622b6280d

**Comment by syonekura** [comment]
@noelbundick wow, that what's exactly that I was looking for! great gist, thank you for sharing. Hope that PR get merged soon

**Comment by ramiMSFT** [comment]
@syonekura Apologies for the delayed response and thank you for reaching out. It looks like Noel helped you with your issue. Closing this one now.
