### ISSUE TITLE
Add instruction on how to test SSH connection

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/azure-devops-docs#4513]
GitHub has a really good documentation on what command to run to test their SSH connection.  AzDO should provide the same 

https://help.github.com/en/articles/testing-your-ssh-connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
This works:

```bash
% ssh -T git@ssh.dev.azure.com
remote: Shell access is not supported.
shell request failed on channel 0
```

**Comment by nusrath432** [comment]
@vtbassmatt This was the lamest response to a command that informs the user that it is all working.

`
ssh -T git@ssh.dev.azure.com
Connection Successful.
<any security advisory>
`

**Comment by Ashish1981** [comment]
Failing while working from ZOS, where other git servers not failing while executing the git clone on ZOS.
```
ssh -T git@ssh.dev.azure.com
remote: Shell access is not supported.
FOTS1754 FOTS3313 shell request failed on channel 0
```
