### ISSUE TITLE
things changed, no longer an 'all release pipelines'

### ISSUE THREAD

**Issue by marct22** [MicrosoftDocs/azure-devops-docs#4550]
For me, I don't see an 'all release pipelines' anymore with a pulldown shortcut. Instead, I need to switch from the default 'View active release pipelines' to the folder view 'View all release pipelines'.  Then, on the right side of the pane, you should see a + New \/  (3 vertical dots).  CLick on the 3 vertical dots, and there is security for all pipelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by WilliamAntonRohm** [comment]
@marct22 -- thank you for your feedback.  We are investigating the article contents per your suggestion.

@andyjlewis -- please look into this issue.

**Comment by hartywillis** [comment]
What is the latest on this please? This is a critical issue. All devs are contributors and the permissions now mean all devs can approve releases all the way through to Production. What's the point of the Release Admin group? We have hundreds of pipelines, I need to be able to deny release approval by devs globally. This needs fixing asap.

**Comment by chasewilson** [comment]
Hi @hartywillis, I'm sorry for the late response I'm taking point on this issue. Are you still having this issue?

**Comment by chasewilson** [comment]
@vtbassmatt, Do you happen to know if this documentation is correct? It will definitely need some updates but if you have some scope to provide that would be great.

**Comment by vtbassmatt** [comment]
This is in RM's space - @RoopeshNair might be able to help.

**Comment by chasewilson** [comment]
@RoopeshNair Just giving this a bump.

**Comment by RoopeshNair** [comment]
Yes, getting to security settings for all pipelines is now few clicks away. We will look into this. However, no time lines at this point in time. We know this is important for you, we will continue to monitor this. At the moment we are prioritizing issues that impact broader set of customers

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
