### ISSUE TITLE
Use Docker's multi-stage function in Pipeline CICD

### ISSUE THREAD

**Issue by cuongdnv** [MicrosoftDocs/azure-devops-docs#4556]
I would like to create the following Pipeline construction :
https://ibb.co/mGNWMBV
The step of this Pipeline construction : 
1. Build works when committed with azure devops repo
1. The image of Debug version, Stage version, Production version is made by looking at tag name of git tags
2.. Two-stage build of common jar and war file which has been compiled and rebuilt by using Docker's multi-stage function is executed
3. Deployment destination is changed automatically by Debug version, Stage version, Production version

I don't understand about Docker's multi-stage function , are the jar and war file output of built Java code ?
Can you tell me the advise or the solution for this issue ? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
The document refers to multi-stage pipeline. Wherein each Stage represents a division of the release process viz. Dev, Test, Staging, Prod etc. 

I believe you are looking for Multi-stage Docker builds? @azooinmyluggage

**Comment by cuongdnv** [comment]
Yes i want to use Docker multistage to realize thí Pipeline construction https://ibb.co/mGNWMBV

**Comment by ramiMSFT** [comment]
Thank you Roopesh! closing this one now.
@cuongdnv feel free to post your questions, search for answers, or suggest a feature on our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)
