### ISSUE TITLE
Unable to build the image

### ISSUE THREAD

**Issue by bjuraga** [MicrosoftDocs/azure-devops-docs#4564]
The very first line:
FROM mcr.microsoft.com/windows/servercore:ltsc2019
is failing with 'no matching manifest for unknown in the manifest list entries'.
Please provide an alternative solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by profet23** [comment]
Any comments/fixes for this?

**Comment by slandsaw** [comment]
Having the same issue.

**Comment by profet23** [comment]
I needed to run all windows updates to get this working. Once I was on the proper version of windows, it built fine.

**Comment by nikitamakarovbl** [comment]
> The very first line:
> FROM mcr.microsoft.com/windows/servercore:ltsc2019
> is failing with 'no matching manifest for unknown in the manifest list entries'.
> Please provide an alternative solution
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
> * Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
> * Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
> * Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
> * Product: **devops**
> * Technology: **devops-cicd**
> * GitHub Login: @juliobbv
> * Microsoft Alias: **juliobv**

--

Your host OS version should correspond with the one inside the image. You can check your host version with the command `winver` and then find an appropriate image [here](https://hub.docker.com/_/microsoft-windows-servercore) (or update your OS)

**Comment by timmkrause** [comment]
Thank you so much for pointing this out @nikitamakarovbl! :)
Unfortunately it took me 4 hours to get here and find this lovely piece of information.

I have a few points to make:

1. This means when I want to run build agents with "Windows Server" (SAC), my Docker host system also needs to be "Windows Server" (SAC), same goes for LTSC, right?
2. Why is this even a thing? Is suppose this is a limitation of Docker for Windows?
3. As this information **is so crucial**, could this information please be added somehow to the docs to save other peoples time?

**Comment by GarethOates** [comment]
Also I'm not even sure why they're recommending doing this in a windows server container as well, it's so huge compared to an equivalent linux-based agent.
