### ISSUE TITLE
Needs more explanation on the task icon or schema definition for it necessary?

### ISSUE THREAD

**Issue by justinyoo** [MicrosoftDocs/azure-devops-docs#4571]
Hi, Team.

The extension manifest has a definition of icon location. However, the task schema doesn't have such definition. At least in this page, I was expecting how the task icons are handled &ndash; location, name, size, etc.

Do you have a plan to include this details in this page, or update the `task-schema.json` file?

Cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83f7acc5-1222-7216-571b-913fa63298e4
* Version Independent ID: 15b2e074-4a8d-9ac8-8aa8-56a0c11be534
* Content: [Custom build/release task reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/integrate-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/integrate-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @justinyoo, Thanks for your question. I'm checking in with the PM and will get back to you soon. Thanks!

**Comment by elbatk** [comment]
Hey Chrystal, I think Matt is checking this out from Twitter, just a heads up that he has some context I think :)

**Comment by matthewisabel** [comment]
Other Matt, should be me not @vtbassmatt but I can't reassign

**Comment by vanpyrzericj** [comment]
Anybody going to clarify how to get icons to appear for custom tasks? A file icon.png residing in the task folder does not work for me.

**Comment by chcomley** [comment]
Hi @justinyoo, Please accept our sincere apology on the delayed response for this issue. Checking in with @matthewisabel and adding @apawast for further guidance.

**Comment by vtbassmatt** [comment]
@stephenmichaelf what more is needed beyond laying down `icon.png` next to `task.json`? I couldn't figure out what our build scripts are doing here.

**Comment by stephenmichaelf** [comment]
@vtbassmatt @vanpyrzericj I just created a task with the following content:

![image](https://user-images.githubusercontent.com/450490/78709373-85716f80-78e1-11ea-8732-6668b2ef1776.png)

Uploaded it using `tfx`, and checked the UI:

![image](https://user-images.githubusercontent.com/450490/78709393-8f936e00-78e1-11ea-9896-957dc5a2309a.png)

And the icon is showing as expected.

@vanpyrzericj What steps are you following to upload and can you share the task folder structure?

**Comment by justinyoo** [comment]
Task icon and extension icon are different from each other. I raised this issue about a year ago, after I wrote my blog post:

https://devkimchi.com/2019/06/26/building-azure-devops-extension-on-azure-devops-1/#setting-up-icon-for-task

**Comment by vtbassmatt** [comment]
I think you're asking us to document the name and size requirement for the task icon, right? From the title and issue, I thought this was about the task, not the extension.

**Comment by chcomley** [comment]
Hi @justinyoo, I wanted to be sure you were aware of the last comment made on this issue. Could you please respond to @vbassmatt, so we can determine how to move forward with this issue? Thanks so much.

**Comment by justinyoo** [comment]
@vtbassmatt Yest, that's correct. It's about the task icon. This doc doesn't have information about the icon, including name, size and location.

**Comment by chcomley** [comment]
Hi all, I've updated the article, adding a note with this information. This update should go live momentarily. Please @mention me if you have any further feedback or have any questions. Thank you!

**Comment by justinyoo** [comment]
Thank you for your support!
