### ISSUE TITLE
Build variable `System.PullRequest.SourceCommitId` is not documented

### ISSUE THREAD

**Issue by moswald** [MicrosoftDocs/azure-devops-docs#4588]
See https://github.com/microsoft/azure-pipelines-tasks/issues/9801.

There may be others as well, but that's the one I know of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by moswald** [comment]
@juliakm Let's re-open this one. And when it comes time to update the docs, I'm available in Slack to chat about what needs to be done.
