### ISSUE TITLE
urlReplacementObject dialogOptions property

### ISSUE THREAD

**Issue by EmmanuelPliez** [MicrosoftDocs/azure-devops-docs#4595]
Since few days ago, the dialogOptions property urlReplacementObject is no more available in the dialog display event. 

Please help !

One solution is to add a new property in the dialogOptions object. So, how get the property after the dialog is loaded ...? (an issue exists for this issue)

Thanks a lot for your quick help !

**Comment by msebolt** [comment]
@EmmanuelPliez It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. 

To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by EmmanuelPliez** [comment]
Could you give me information about how used the dialogOptions when a page is displayed / loaded ?

**Comment by msebolt** [comment]
@EmmanuelPliez Please refer to [this](https://docs.microsoft.com/en-us/azure/devops/extend/develop/using-host-dialog?view=azure-devops) document (specifically the urlReplacementObject example).

Are you saying this example no longer works?

Also including https://github.com/MicrosoftDocs/vsts-docs/issues/4568 for reference to the second issue.

**Comment by EmmanuelPliez** [comment]
Thanks for answer.
But this exemple is no longer correct.
The query param is not passed to the dialog


Le lun. 24 juin 2019 20:47, Matthew Sebolt <notifications@github.com> a
écrit :

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
