### ISSUE TITLE
SNAPSHOT versions are not supported for upstreams

### ISSUE THREAD

**Issue by phil-hodgson** [MicrosoftDocs/azure-devops-docs#4616]
URL: https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops

When a feed is configured with a Maven upstream, it's important for users to understand that when pulling a SNAPSHOT version from the feed, Azure DevOps _does not_ search any upstream source for that (SNAPSHOT) version. This applies both to public upstreams (i.e. Maven Central) and other Azure DevOps feeds.

**Comment by phil-hodgson** [comment]
May also want to note this on https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/upstream-sources?view=azure-devops

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
