### ISSUE TITLE
Authorized users works weirdly with multiple policies with same status check

### ISSUE THREAD

**Issue by nishantsny** [MicrosoftDocs/azure-devops-docs#4656]
1. Create two status checks with "Status to check" but with different "path filters" and "Authorized users"
1. Post the status state using identities of both users, one of the them will say: 
Microsoft.VisualStudio.Services.Common.VssServiceException: Pull request status rejected by status policy. Status Author should match status policy configuration settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a3fce3-aa8f-c5e5-5b10-da912f6941fc
* Version Independent ID: c36e9af9-cc20-c264-0525-2ca7e7d9ad8e
* Content: [Configure a branch policy for an external service - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pr-status-policy?view=azure-devops)
* Content Source: [docs/repos/git/pr-status-policy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pr-status-policy.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by mmitrik** [comment]
@hross Can you have someone take a look at this?
