### ISSUE TITLE
Include visuals and improve the writing

### ISSUE THREAD

**Issue by adamdavies001** [MicrosoftDocs/azure-devops-docs#4669]
This document should have visuals to explain the parts of the Splitter control. The grammar and punctuation on this page are also very bad and makes most of it unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9457561a-2d75-b5fa-b0da-b66ec968c68d
* Version Independent ID: 58ab5fea-5d4f-8bf2-05de-ec774af32bcd
* Content: [Use the Splitter Control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/splittero?view=azure-devops)
* Content Source: [docs/extend/develop/ui-controls/splittero.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/splittero.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by chcomley** [comment]
Hi @adamdavies001, Please accept our sincerest apology for letting this issue go stale! We have plans to update the entire docset within the next quarter or two. Reassigning to @apawast for updates and user story creation. Thank you!

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance/assistance, thank you!

**Comment by chcomley** [comment]
Hi @adamdavies001, I've just published an update to the article, thank you for your feedback. I included a link to another site that you can use for reference, but I'll post it here as well. For more information, see this [Formula Design System page](https://azdevinternal.azureedge.net/components/splitter). Thank you!
