### ISSUE TITLE
Which tasks are supported for Server Jobs?

### ISSUE THREAD

**Issue by mjhilton** [MicrosoftDocs/azure-devops-docs#4672]
The current doco states under Server Jobs that "only a few tasks are supported in Server Jobs at present", but there's no way to find out what these are without trawling every task in the Tasks repo to see which agent type they support.

Can we get a list of the supported tasks please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#server-jobs)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
@RoopeshNair can you help with updating the doc to list the out-of-the-box tasks that work with server jobs in YAML and classic editor?

**Comment by RoopeshNair** [comment]
@shashban - can you please help with this?

**Comment by scgbear** [comment]
This is also hindering a partner engagement. @shashban any idea on when we can expect an update on this?

**Comment by eatdrinksleepcode** [comment]
I am trying to provide guidance to teams building pipelines on when they should use server jobs, but I can't do that without knowing what tasks are supported for Server Jobs.

**Comment by shashban** [comment]
Currently Invoke REST API, Invoke Azure function and Delay tasks would be functional in a server job.
Having said that tasks are extensible and can be added through extensions.
