### ISSUE TITLE
clarify documentation about "visibility" vs permissions for Azure Devops Server 2019.01

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/azure-devops-docs#4709]
Hi,

in this page [https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops-2019](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops-2019), it is said:

"_if you want to make the packages in a feed available to all users in your organization, create or select a view that contains the packages you want to share and ensure its visibility is set to People in my organization."

In Azure Devops Server 2019.01, When one create a feed, whatever the choice for Visibility - either "People in <collection>" or "Specific people" - The permissions for the feed are the same.

- Is this a awaited behavior ?
- Is visibility defined with another mechanism than permissions ? In this case which one ? 
- How an adminstrator can check/modify the visibility in this case after creation of the feed ?

This really needs clarification.
Thank you.

**Comment by ramiMSFT** [comment]
@spashx Thank you for your feedback. 2 important concepts to keep in mind here:
- Setting view permissions to Specific people without specifying any users or groups will cause the view permissions to default back to their parent feed permissions. 
- If a user have permission to a specific view, and even if they don't have permission to the feed, they will still be able to access and download packages through that view. If you want to completely hide your packages, you must restrict both feeds and views permissions.
Please check the [updated article](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops-2019#understanding-feeds-and-views-permissions) for more information on how to check and change your feed permission settings
