### ISSUE TITLE
Update screenshot from VSTS age

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-devops-docs#4712]
This screenshot was done few years ago https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/_shared/_img/set-up-first-build-from-code-hub.png?view=azure-devops
and UX absolutely different now. 
Please, actualize it to avoid confusion 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f80d77-da2a-3c8d-efcf-3095bf293f69
* Version Independent ID: 36dcf393-e28a-2bc4-61e6-5c93cdacb625
* Content: [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/dot-net?view=azure-devops&tabs=vsts)
* Content Source: [docs/pipelines/apps/windows/dot-net.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/windows/dot-net.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by SychevIgor** [comment]
@cxwtool @WilliamAntonRohm @msebolt @mijacobs @ramiMSFT Microsoft, did you fixed it or just closed? I don't see any changes!

**Comment by ramiMSFT** [comment]
@SychevIgor Thank you for your feedback. The updates will be available soon.
