### ISSUE TITLE
Request for clarification

### ISSUE THREAD

**Issue by TheBeardedLlama** [MicrosoftDocs/azure-devops-docs#478]
The hint text in TFS says:

"Variables defined in the Build or Release Definition will be matched against the 'key' or 'name' entries in the appSettings, applicationSettings, and connectionStrings sections of any config file and parameters.xml. Variable Substitution is run after config transforms. 
 Note: If same variables are defined in the Release Definition and in the Environment, then the Environment variables will supersede the Release Definition variables."

Could someone please clarify the "and parameters.xml" part? I see nothing here talking about that. Is that help text correct? How is it supposed to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution?view=vsts)
* Content Source: [docs/build-release/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/transforms-variable-substitution.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for investigation and I'll let you know their response.

**Comment by alexhomer1** [comment]
This feedback came from the product team:

Msdeploy.exe by default supports overrides values in web.config with values from parameters.xml. Our task does:
1)	Variable substitutions like Variable substitution and XML transformation first and 
2)	then invokes msdeploy.exe for deployment during which the web.config substitution happens from parameters.xml.

In this, Variable substitution in Step 1 is done on .config, .json and parameters.xml. The task can update values in parameters.xml before it is supplied to msdeploy.exe.

I will update the topic to reflect this. I hope this helps answer your question.

**Comment by TheBeardedLlama** [comment]
Thank you for the update @alexhomer1 
Unfortunately, that doesn't quite clarify things.
That's what the hint text in TFS says, but that's **not** how it works.
Is there a place where I can look at the source to see what is actually going on?

**Comment by TheBeardedLlama** [comment]
@alexhomer1 ?

**Comment by alexhomer1** [comment]
Thank you. I will request additional information.

**Comment by bledbet** [comment]
Thanks @seanoflynn-tie - I had the same struggle, and that fixed it.  Documentation is still wrong.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
