### ISSUE TITLE
System.ArtifactsDirectory should probably be Build.ArtifactStagingDirectory 

### ISSUE THREAD

**Issue by haacked** [MicrosoftDocs/azure-devops-docs#4808]
The article contains the following snippet:

> The snippet assumes that the build steps in your YAML file produce the zip archive in the `$(System.ArtifactsDirectory)` folder on your agent

However, I can't find any mention of `$(System.ArtifactsDirectory)` on the page about [Predefined variables for Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml).

I assume that should actually say `$(Build.ArtifactStagingDirectory)`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by bertrandpons** [comment]
You can refer to this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch

**Comment by ramiMSFT** [comment]
@haacked Thank you for your feedback. The new version will go live shortly.
