### ISSUE TITLE
Default kudu/scm access restrictions prohibit devops deployment

### ISSUE THREAD

**Issue by epizut** [MicrosoftDocs/azure-devops-docs#4847]
Unfortunatly the default 'deny all' rule in the App Service ➟ Networking ➟ Access Restrictions ➟ SCM prohibits all deployment from a Linux DevOps agent with a non intuitive error.

It will be great to mention this in the documentation.

Also as hosted agents have shared/moving IPs, it is very difficult to manage those access restrictions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?toc=%2Fazure%2Fdevops%2Fdeploy-azure%2Ftoc.json&%3Bbc=%2Fazure%2Fdevops%2Fdeploy-azure%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by tgolly** [comment]
We lost a couple of days on this with a lot of head-scratching.  Would be great if this could be mentioned in the doco, with a recommended workaround.

**Comment by ramiMSFT** [comment]
@epizut Thank you for your feedback. I added clarifications with links for more details. The updated article will go live shortly.

**Comment by epizut** [comment]
Your are welcome

Le mar. 8 sept. 2020 à 19:22, PRMerger12 <notifications@github.com> a
écrit :
