### ISSUE TITLE
Artifact name cannot be a variable

### ISSUE THREAD

**Issue by Izzmo** [MicrosoftDocs/azure-devops-docs#4851]
Doing something like this will not work. It gives an error `##[error]Value cannot be null. Parameter name: hashAndAlgorithm`

```
- download: current
  artifact: $(someVariable)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by amirschw** [comment]
Hi Izzmo, have you tried using `${{ variables['someVariable'] }}` ?

**Comment by msebolt** [comment]
@Izzmo  Thank you for the question.

My apologies on the delay, this issue has been assigned to the author.

**Comment by vtbassmatt** [comment]
This should work, but there may be a product bug. @willsmythe

**Comment by Izzmo** [comment]
> @Izzmo Thank you for the question.
> 
> My apologies on the delay, this issue has been assigned to the author.

That did not work. It's throwing this error:

>117639: "/build.yml (Line: 158, Col: 17): Unexpected value ''"

**Comment by baywet** [comment]
however parameters work if you're using a template: ${{parameters.somParam }}

**Comment by vtbassmatt** [comment]
@johnterickson is there anyone from your team who can look into this?

**Comment by arek-avanade** [comment]
@Izzmo It works in my case, but the variable needs to be declared in the YAML global scope, not in the job.

**Comment by johnterickson** [comment]
@Izzmo Can you share the whole log from the task failure?

**Comment by Izzmo** [comment]
I will get you this soon.. sorry I need to recreate this as it's pretty old and we went a different direction.

**Comment by smileyiori** [comment]
I have the same problem.

I define my variable as global:
![image](https://user-images.githubusercontent.com/8495055/73990681-b7c11980-48fe-11ea-80ce-160cf1337d68.png)

and my code:
![image](https://user-images.githubusercontent.com/8495055/73990703-d45d5180-48fe-11ea-9610-ae6f87b8e97f.png)

and the error:
![image](https://user-images.githubusercontent.com/8495055/73990724-e5a65e00-48fe-11ea-9399-da0953f35444.png)

**Comment by Izzmo** [comment]
There was someone who recreated this the other day @johnterickson but it looks like they deleted their comment?

**Comment by ssipola** [comment]
- download: current
      artifact: '$(artifactName)'
Works for me, declaration up top is:
variables:
- group: 'variables-lab-core'
and the variable group contains:
Name: artifactName
Value: arm_templates_labcore_infra
If you have spaces or the likes in your variable you might need to escape the $(Variable) with encasing quotes/double quotes
https://docs.octoprint.org/en/master/configuration/yaml.html

**Comment by damonbarry** [comment]
@johnterickson
I'm trying to convert a pipeline from build completion triggers to pipeline triggers. I have this task in my YAML (it's actually inside a yaml template that's called from the main YAML file):

```yaml
- download: images
  artifact: '$(az.pipeline.images.artifacts)'
  patterns: '$(az.pipeline.images.artifacts)/artifactInfo.txt'
```

`az.pipeline.images.artifacts` is a variable declared in the UI (and NOT marked as settable at queue time).

Full output from task:
```
##[debug]Evaluating condition for step: 'Download'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Download
==============================================================================
Task         : Download pipeline artifact
Description  : Download a named artifact from a pipeline to a local path
Version      : 1.2.4
Author       : Microsoft Corporation
Help         : Download a named artifact from a pipeline to a local path
==============================================================================
Download from the specified build: #29781926
Download artifact to: /home/vsts/work/1/images/core-linux
##[debug]Dedup parallelism: 192
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session cdc7a0fe-c14b-4025-96ca-845e046141c4
Information, ApplicationInsightsTelemetrySender did not correlate any events with X-TFS-Session cdc7a0fe-c14b-4025-96ca-845e046141c4
##[error]Value cannot be null. (Parameter 'hashAndAlgorithm')
##[debug]Processed: ##vso[task.logissue type=error;]Value cannot be null. (Parameter 'hashAndAlgorithm')
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.BlobStore.Common.DedupIdentifier.Create(HashAndAlgorithm hashAndAlgorithm)
   at Microsoft.VisualStudio.Services.BlobStore.Common.DedupIdentifier.Create(String valueIncludingAlgorithm)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsync(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Download
```

**Comment by johnterickson** [comment]
@damonbarry What's this REST endpoint dump for build 29781926? (fill in the curly brackets)

```
https://dev.azure.com/{organization}/{project}/_apis/build/builds/{buildId}/artifacts?api-version=5.1
```

**Comment by damonbarry** [comment]
```json
{
  "count": 2,
  "value": [
    {
      "id": 56368784,
      "name": "core-linux",
      "source": "94d73d66-1c7a-5d82-2913-9d2cb8aa138c",
      "resource": {
        "type": "Container",
        "data": "#/43189012/core-linux",
        "properties": {
          "localpath": "/home/vsts/work/1/b/publish",
          "artifactsize": "535715705"
        },
        "url": "https://dev.azure.com/msazure/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/build/builds/29781926/artifacts?artifactName=core-linux&api-version=5.1",
        "downloadUrl": "https://dev.azure.com/msazure/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/build/builds/29781926/artifacts?artifactName=core-linux&api-version=5.1&%24format=zip"
      }
    },
    {
      "id": 56370914,
      "name": "core-windows",
      "source": "2d2b3007-3c5c-5840-9bb0-2b1ea49925f3",
      "resource": {
        "type": "Container",
        "data": "#/43189012/core-windows",
        "properties": {
          "localpath": "C:\\agent\\_work\\5\\b\\publish",
          "artifactsize": "742296354"
        },
        "url": "https://dev.azure.com/msazure/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/build/builds/29781926/artifacts?artifactName=core-windows&api-version=5.1",
        "downloadUrl": "https://dev.azure.com/msazure/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/build/builds/29781926/artifacts?artifactName=core-windows&api-version=5.1&%24format=zip"
      }
    }
  ]
}
```

**Comment by WilliamAntonRohm** [comment]
@willsmythe -- please look into this issue.

**Comment by ramiMSFT** [comment]
@Izzmo Thank you for your feedback. The new version of the article will go live shortly. Also if you are using a variable name for `artifact` then you should use a single quotation mark:
exp: `artifact: '$(someVariable)'`

**Comment by GaTechThomas** [comment]
I've spent hours dealing with a variable passed into a template parameter and used as an the value in the artifact field. The only thing that works is to pass the artifact name to the template as a string, not in a variable (single and double quotes don't change that).

This seems to align with the last comment in the thread above, but history of this documentation article does not show an associated update of the article.

What is the status of this item?

Thank you.

**Comment by GaTechThomas** [comment]
I worked out my issue. Here's how I was able to call a YAML template, passing in a variable value for a template parameter:

```
- template: ./mytemplate.yml
  parameters:
    stageDependsOn: Build
    param2: ${{ variables.myVariableName }}
```

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- Thomas, thank you for your followup.  I'm glad it's working for you.

**Comment by GaTechThomas** [comment]
Wow, I thought that I was a quick learner. I just made the same mistake again that I did back in Feb and found my own response above.

**Comment by ShadowXVII** [comment]
I still can't get this to work with all variants of "'s and Parameters vs. Variables. .. Can we have some clear guidance on the documentation page?

**Comment by GaTechThomas** [comment]
@ShadowXVII Have you download the logs for the pipeline run and looked at the expanded pipeline? I've found that looking at the expanded pipeline often makes the problem much clearer. The vscode extension names Azure Pipelines is essential for pipeline work - just be sure the the language selected for the expanded yaml file is Azure Pipelines.
