### ISSUE TITLE
Please provide more information about using /user parameter

### ISSUE THREAD

**Issue by Elsewhere42** [MicrosoftDocs/azure-devops-docs#4882]
The following example returns all users:
tf status * /recursive /user:*

The following example returns an error:
tf status * /recursive /user:LastName, FirstName
Error:  There is an extra comma in option user.

Note:  I tried adding quotes but that produced an error as well.
tf status * /recursive /user:"LastName, FirstName"
Error: Option user requires exactly one value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d796f92a-8065-b7da-6af3-1f61f52f37d9
* Version Independent ID: 2c7e9f56-ab32-c6c3-4eb2-26ac6a5dbfd8
* Content: [Status command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/status-command?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/status-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/status-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by IlyaChistov** [comment]
#reassign @IlyaChistov

**Comment by PRMerger7** [comment]
GitHub user IlyaChistov has been removed from the MicrosoftDocs organization, so they were automatically removed as an assignee.

**Comment by MaximMalygin** [comment]
@msebolt could you please close it? Ilya fixed it in PR
