### ISSUE TITLE
Service connection reference / schema

### ISSUE THREAD

**Issue by BiribiriJaNai** [MicrosoftDocs/azure-devops-docs#4919]
Hi,
There's no documentation or reference about service connections. A json schema like the one available for tasks would be nice.
My use case: I need to create an endpoint similar to the SSH one (host, port, password...), without the standard URL field (or at least not visible). I'd also like to be able to drag'n'drop certificateS (with size &gt; 10k) but there's not a single documentation on this.
Anything in your backlog about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @BiribiriJaNai, Thanks for reaching out. I currently don't have anything in my backlog concerning this. I'm following up with a PM and will be in touch. Thanks again!

**Comment by jordynniara** [comment]
Has anything changed with this? I'm ussing the Token auth scheme in my service connection, but also do not need the Server Url. I want to hide it.

**Comment by BiribiriJaNai** [comment]
@jordynniara , if you just want to hide the default Server URL field, you can try something like this.
This example is what I used to create a service connection for Apache Kafka:
```
	"name": "kafka",
	"displayName": "Kafka Apache",
	"icon": "static/icon-kafka-endpoint.png",
	"url":  {
		"displayName": "Bootstrap Server URL",
		"value": "https://www.visualstudio.com",
		"isVisible": "false",
		"required": "false"
	},
	"inputDescriptors": [
		{
			"id": "hostname",
			...
		},
		{
			"id": "port",
			...
		}
	]
```
The important part is **"isVisible": "false** and **"required": "false"**.
You also have to set a **valid** URL by default, because even if the field is hidden, it's evaluated.

Which gives me the following, without the "Server URL" field:
![image](https://user-images.githubusercontent.com/29836717/66144766-be1a4e80-e609-11e9-8135-740f180aa99a.png)

**Comment by jordynniara** [comment]
That was exactly what I needed. Thanks @BiribiriJaNai

**Comment by chcomley** [comment]
@BiribiriJaNai, I'm glad you got what you needed! Closing this issue. Thanks!

**Comment by BiribiriJaNai** [comment]
@chcomley , I didn't get what I needed... I found **a part** of the solution to my problem, by myself.
There's still no documentation out there about the things I mentionned in my first post.
Thanks for **not** closing this issue.

**Comment by chcomley** [comment]
I’ve reopened the issue and will help you get to the bottom of this, @BiribiriJaNai.

**Comment by AdamCoulterOz** [comment]
Hey @chcomley - this is definitely needed, there seems to be many aspects of Service Connection Contributions `ms.vss-endpoint.service-endpoint-type`, which is unavailable to people trying to build contributions to the Azure DevOps marketplace.  Holistically, we really need a json schema for `vss-extension.json`.

**Comment by chcomley** [comment]
FYI, I've just circled back with the product group - hoping to have an update soon.

**Comment by AdamCoulterOz** [comment]
I've started a draft schema... its a dynamic schema for the full `vss-extension.json` config file. So it includes the custom service connections, and the whole rest of the file. Mostly generated by downloading every vis-extension.json on GitHub and aggregating them, then reverse engineering the schema. Working on it here in my forked repo here:

https://github.com/AdamCoulterOz/vsts-docs/pull/1

**Comment by AdamCoulterOz** [comment]
Could get some help expanding this section to include all the conditional subschemas:

https://github.com/AdamCoulterOz/vsts-docs/blob/vss-schema/docs/extend/develop/_shared/extn-types/typeReferences.schema.json

**Comment by ashokirla** [comment]
Here is the documentation for creating a custom service connection. 
https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops

**Comment by AdamCoulterOz** [comment]
@ashokirla we would really like official JSON Schema, I've started drafting one, but I am limited to inference from available examples. Could we get a full `vss-extension.schema.json`?

**Comment by romil07** [comment]
@BiribiriJaNai @AdamCoulterOz Did you check this doc?
https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/serviceEndpoints.md

This document is a guidance on how to create a new Service endpoint type.
If you haven't checked this, take a look once and let me know if this is answered or not.

If you have gone through this, can you tell me what you are looking for exactly?

Formally, this is the document that we direct customers to if they need any help. If you have any specific ask, I can update this doc.

**Comment by BiribiriJaNai** [comment]
@romil07 thanks for the link but I've already read this document.
As to what I'm looking for, it's in my initial post: 

> I'd also like to be able to drag'n'drop certificateS

it seems the UI for SSH service connection has been updated but a previous version looked like this:
![image](https://user-images.githubusercontent.com/29836717/73805256-73326280-47c6-11ea-815b-a2a0e10d185c.png)

See the "Upload SSH private key file..." link? It opened a popup similar to this one
![image](https://user-images.githubusercontent.com/29836717/73805884-336c7a80-47c8-11ea-91de-7fea03aa2d1a.png)

That's what I'm looking for.

**Comment by romil07** [comment]
@BiribiriJaNai Ok. As part of the UI refresh, the drag drop was probably not implemented.
@ashokirla Can you take a look at this ask and prioritize accordingly?

**Comment by chcomley** [comment]
I've reassigned this issue to @ashokirla. Thank you.

**Comment by chcomley** [comment]
Adding @narula0781 for further guidance/assistance, thank you!

**Comment by romil07** [comment]
@BiribiriJaNai This has been just made available. It's possible that the it hasn't started yet. Give it a week max, you should get it.

**Comment by BiribiriJaNai** [comment]
@romil07 thanks for the update but that's not what I asked for.

> I need to create an endpoint similar to the SSH one (host, port, password...), without the standard URL field (or at least not visible). I'd also like to be able to drag'n'drop certificateS (with size > 10k) but there's not a single documentation on this.

I need some reference documentation on how to achieve a similar behavior on a custom service connection, because unlike [built-in tasks](https://github.com/microsoft/azure-pipelines-tasks), definitions of built-in service connections are not available.

**Comment by romil07** [comment]
@BiribiriJaNai This is not yet possible. The file picker option and drag-drop on top of it is something that we haven't made extensible yet. 

@ashokirla to take a call on this.

**Comment by AdamCoulterOz** [comment]
> @BiribiriJaNai @AdamCoulterOz Did you check this doc?
> https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/serviceEndpoints.md
> 
> This document is a guidance on how to create a new Service endpoint type.
> If you haven't checked this, take a look once and let me know if this is answered or not.
> 
> If you have gone through this, can you tell me what you are looking for exactly?
> 
> Formally, this is the document that we direct customers to if they need any help. If you have any specific ask, I can update this doc.

@romil07 yes - I've seen this... but is very incomplete... there are many many attributes and objects which we need a real JSON schema for... I scraped every `VSS Extension json` configuration  I could from GitHub then inferred the schema here:

https://github.com/AdamCoulterOz/vsts-docs/pull/1

I'd really like Microsoft to fully document it (as an actual comprehensive JSON schema document) from their side, as we can only infer from the outside.

**Comment by chcomley** [comment]
This issue is stale for over 1.5 years and therefore will now be closed. If you need further assistance, please [report a problem in the Developer Community](https://developercommunity.visualstudio.com/search?space=21). Thank you.

**Comment by AdamCoulterOz** [comment]
@chcomley, @romil07 - we still haven't got a schema for AzDO extension points. It's been stale because we haven't heard back from Microsoft.
