### ISSUE TITLE
How set provenance details

### ISSUE THREAD

**Issue by jcanizalez** [MicrosoftDocs/azure-devops-docs#4960]
In the documentation I cannot found how I can set the provenance details from maven in the same way as in the nugget task

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 60230978-ce5b-6964-23ba-1dd31b1fa1c9
* Version Independent ID: 9b1eb982-b07a-8b67-ab0b-b2a4d3dade12
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/es-es/azure/devops/pipelines/artifacts/maven?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk, yebronsh**

**Comment by ramiMSFT** [comment]
@jcanizalez Thank you for your feedback. My apology for the late response. 
"set the provenance details" Not sure what you mean by this, can you provide more details?
What are you trying to accomplish?

**Comment by ramiMSFT** [comment]
@jcanizalez will close this issue for now. Please comment below with more clarification on what you want to accomplish and I will be happy to help.
