### ISSUE TITLE
`@fabrikam:registry=<your feed URL>` doesn't work

### ISSUE THREAD

**Issue by sdshou** [MicrosoftDocs/azure-devops-docs#4965]
When I did the change "@fabrikam:registry=&lt;your feed URL&gt;" in .npmrc file, then "npm publish", it reports login issue. Then if I delete the "@fabrikam:", it published successfully. 

I don't understand what does the "scopes" here mean actually. The npm package already can have a scope in package name in package.json. Are they the same thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484077fa-696c-63e1-a4ba-f2680d076bfd
* Version Independent ID: aa0f98e6-6b82-a848-de65-0c39af8f8650
* Content: [Use npm scopes for private packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/artifacts/npm/scopes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/scopes.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by NielsInc** [comment]
Same issue here - am I missing any additional configuration to use scoped registries or is this a bug in the authentication?

**Comment by nikitashalabaev** [comment]
Add @fabrikam namespace to your app name in package.json
{ "name": "@fabrikam/package-name" }

**Comment by ramiMSFT** [comment]
@sdshou Thank you for your feedback. The updated version will go live shortly.
