### ISSUE TITLE
Default and Compare Branch Information Incorrect

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/azure-devops-docs#5081]
I found this article when trying to clarify the differences between the default and compare branch settings. According to my testing, the compare branch defines both comparisons and the default branch for PRs. Setting the default branch doesn't appear to do anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8630b8-08ea-d706-e51c-03863b33d49e
* Version Independent ID: ad8a3b91-7b41-a6af-0d5c-b26355a49c7b
* Content: [Manage branches in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-your-branches?view=azure-devops)
* Content Source: [docs/repos/git/manage-your-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-your-branches.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by amereditSteelcase** [comment]
When I go to BRANCHES and click CREATE A NEW BRANCH, the branch that comes up in the dropdown (create a branch off of this branch) is not the default branch as I would expect. I am trying to have the default branch when creating a new branch be changed. How can I make this happen?

**Comment by cawoodm** [comment]
It would be helpful if there was a recommendation for which branch should *normally* be the default: master or develop??

**Comment by DamianSuess** [comment]
@cawoodm, it depends on you. Personally, I go by the following structure:
* Default branch is ``develop``. All pull requests from feature-branches merge into it.
* And have ``master`` used for releases and tagging. Only allowing ``develop`` to merge into it when a release or version is ready.

**Comment by steved0x** [comment]
I believe this documentation has been added: https://learn.microsoft.com/en-us/azure/devops/repos/git/manage-your-branches?view=azure-devops#change-your-default-branch
