### ISSUE TITLE
Different preconfigured Maven pipeline than in doc

### ISSUE THREAD

**Issue by Tr3yb0** [MicrosoftDocs/azure-devops-docs#5133]
Maven package Java project Web App to Linux on Azure no longer exists. I'm not sure what stages/jobs/steps are performed in that preconfigured pipeline, but when I run the currently available Maven pipeline, it only goes through the package goal. So, after running the pipeline, the jar isn't actually deployed anywhere. When I browser to the url for my site, it is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2464073a-cf55-d4c7-ad10-a7d7a889f03a
* Version Independent ID: af0afd6e-bdaf-de9a-18e7-50e4a1689a58
* Content: [Build and deploy to a Java web app on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/java-webapp?view=azure-devops&tabs=java-se#feedback)
* Content Source: [docs/pipelines/languages/java-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/java-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by lopezunwired** [comment]
Same thing happened to me. Everything shows green in pipelines and build but the app doesn't appear. Is there a start up command missing?

**Comment by juliakm** [comment]
@shashankbarsin When we follow the default instructions [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-webapp?view=azure-devops&tabs=java-se#feedback), the website comes up as empty. Should we include any subfolder under the URL to be able to browse to the website?

**Comment by shashankbarsin** [comment]
Apologies for missing the notification on this issue. Assigning to @azooinmyluggage @N-Usha who have worked on the sample associated with this doc

**Comment by kayosoufiane** [comment]
worked but not as documented :
check KUDO : https://my-app-name.scm.azurewebsites.net/
and look for the deployed app in wwwroot/webapps/
here ROOT is what we see in https://my-app-name.azurewebsites.net
and not what we deployed
so the other site is the on we are looking for
https://my-app-name.azurewebsites.net/<site-name>

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by juliakm** [comment]
Sorry for the delay @kayosoufiane. I'm updating the documentation now. The path for the build is http://my-app.azurewebsites.net/petclinic/.
