### ISSUE TITLE
HelmDeploy task documentation lacks tls settings

### ISSUE THREAD

**Issue by elsesiy** [MicrosoftDocs/azure-devops-docs#5140]
Hi there,

the `HelmDeploy@0` task documentation is very minimal and mentions not all available command options.

E.g. the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#upgrade-command) mentions TLS can be used but doesn't specify the command options or provide any further instructions.
The code though clearly shows a multitude of arguments that can be provided as  seen e.g. [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helmcommands/helmupgrade.ts).

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by elsesiy** [comment]
@cxwtool The issue has not been addressed and the docs are still outdated. Please do not close tickets without looking at them.

**Comment by mijacobs** [comment]
@steved0x @juliakm @ramiMSFT --should we reassign this issue to someone else?
@elsesiy : Our docs are open for public contributions. If you're interested, you can add the missing info that you found. Otherwise, we'll find someone to fix it.
