### ISSUE TITLE
Confused about whether jobs can be run in parallel unless a dependency is specified

### ISSUE THREAD

**Issue by FooBarWidget** [MicrosoftDocs/azure-devops-docs#5153]
The documentation seems to imply that, unless a dependency is specified, jobs can be run in parallel (given enough agents and enough Parallel Jobs available). But it isn't very clear about that.

What's also confusing is that Parallel Jobs are not a special type of jobs (the way "Normal" Jobs and Server Jobs are). Instead, Parallel Jobs appear to be some kind of resource management definition: a Parallel Job definition grants the system the right to run a job in parallel... or something like that.

It would be great if you can cleanup the terminology and explicitly document more stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by juliakm** [comment]
This is an older issue and it looks like we've added a reference to the parallel jobs page in the interim.
