### ISSUE TITLE
Github Release Drop cant be 'triggered'

### ISSUE THREAD

**Issue by danpetitt** [MicrosoftDocs/azure-devops-docs#5171]
It seems doing a release whenever a new 'GitHub Release' isnt supported

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/release/triggers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@danpetitt -- Dan, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by danpetitt** [comment]
> @danpetitt -- Dan, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

Sorry, what additional information do you need other than what has been detailed in the ticket ... this gives the documentation page I was commenting on.

Basically I would like to use a GitHub Release to 'trigger' an Azure DevOps Release Pipeline, but currently I cannot. The little lighting icon overlay on the GitHub Release Artifact task does not exist like it does on other Artifact Drop tasks.

**Comment by ashokirla** [comment]
@danpetitt - Thanks for the feedback. Today we don't have automated trigger support for github release artifact. However, we have it in our backlog. We will update you once the support is available.

**Comment by ramiMSFT** [comment]
Thank you for your feedback. The updated article will go live shortly.
