### ISSUE TITLE
distributionManagement/repository contains invalid XML tags.

### ISSUE THREAD

**Issue by yenbohuang** [MicrosoftDocs/azure-devops-docs#5173]
We should remove "releases" and "snapshots" in "distributionManagement" as follows since they are not valid to Maven POM:

`
<distributionManagement>
    
      <repository>
         <id>dev.azure.com-mseng-zcalvinmaven</id>
         <url>https://pkgs.dev.azure.com/mseng/_packaging/zCalvinMaven2/maven/v1</url>
      </repository>
   </distributionManagement>
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0448074b-9d76-435b-e3f2-df77c7367099
* Version Independent ID: 0d46b076-90ee-8112-1e07-5be2f592ea87
* Content: [Publish Maven artifacts to your feed using the Maven client](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/publish?view=azure-devops#feedback)
* Content Source: [docs/artifacts/maven/publish.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/maven/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by aasim** [comment]
The issue mentioned is not on this page, but on the connect to feed dialog. This should be a bug on the product not on documentation

**Comment by yenbohuang** [comment]
Thanks,I will close it.
