### ISSUE TITLE
Azure DevOps hook cannot be created by anyone

### ISSUE THREAD

**Issue by Russweb** [MicrosoftDocs/azure-devops-docs#5179]
When creating an Azure DevOps notification connector to the Teams channel, the user is not allowed to make it through the configuration the way this page describes.
At the point where it asks which team in the project to select, it will not load the drop down and tells the user:
"Failed to find teams for this project that had the required permissions to create service hook"
This user is already a member in Teams as well as a contributor in the Azure DevOps team and project space.
If this is suggesting that the user must be a Project Admin in Azure DevOps, and thus must have the "create webhooks" rights as well, that is a travesty and bottlenecks organizations from being free to subscribe to data they already have rights to.
It also does not point out that this level or permission is required in this document.
Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook for Azure DevOps Services and TFS with Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
Hi @Russweb. Thanks for your feedback! There is a note near the top of the page stating "You must be a member of Project Administrators or Project Collection Administrators to configure the connector." I know this doesn't fix your issue, however, does this address it in a documentation sense? 
If you would like to request a feature, you can reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) :)

**Comment by chasewilson** [comment]
I'll be closing this issue for now. If you have any more feedback, feel free to make a new issue :) Thank you again for your feedback!

**Comment by fhljys** [comment]
I am already the administrators of the project but I still hit this issue. The issue starts around 11/17. Feedback and IcM got no response.  What happened to Teams?

**Comment by RaptorCZ** [comment]
> I am already the administrator of the project but I still hit this issue. The issue started around 11/17. Feedback and IcM got no response. What happened to Teams?

I have the same problem.

**Comment by gscottwade** [comment]
Same issue with me also and it was working until around middle of November 2020. I am a project admin also. Something broke with azuredevops connector in Teams channel.
error - Failed to find teams for this project that had the required permissions to create service hook.

**Comment by fhljys** [comment]
@chasewilson any idea? can we reactivate this issue?

**Comment by chasewilson** [comment]
I am actually not the author anymore however, I'll reeopen the issue and the issue will be reassigned to the correct Content Dev.

**Comment by froens** [comment]
We've got the same issue.

See this thread (the bottom):
https://developercommunity.visualstudio.com/content/problem/1239563/azure-devops-connector-in-ms-teams-yields-a-client.html

**Comment by rafaelsantosxp** [comment]
I am project admin, and receive this message when i create a hook.
"Failed to find teams for this project that had the required permissions to create service hook."

**Comment by ethanx94** [comment]
> I am project admin, and receive this message when i create a hook.
> "Failed to find teams for this project that had the required permissions to create service hook."

Yes, everyone. and linking to the developer community has proved this has been an issue for at least 2 months now. How can we escalate this?

**Comment by lwpamihiranga** [comment]
> I am project admin, and receive this message when i create a hook.
> "Failed to find teams for this project that had the required permissions to create service hook."

Same here. I'm also having this issue

**Comment by anthraxn8b** [comment]
Helloooo? Anyone there who has an update for us? This is not what I expect as a customer... I am trying to create a connection in teams since months now and stepping from one bug to the next.
Maybe teams is not the best solution after all ...

**Comment by khushboo6** [comment]
Facing the same issue, cannot create any connectors in Teams. I have the project admin permissions as well.
Any update on this ? when can we expect a fix ?

**Comment by jonatastrife** [comment]
Got the same problem here, before having this problem I was stuck in another problem [https://techcommunity.microsoft.com/t5/microsoft-teams/can-t-configure-azure-devops-connector-in-teams-http-error-500/m-p/1614308/page/2](url) and now this...

> Helloooo? Anyone there who has an update for us? This is not what I expect as a customer... I am trying to create a connection in teams since months now and stepping from one bug to the next.
> Maybe teams is not the best solution after all ...

**Comment by daviddelven** [comment]
We have the same problem, and it previously was working well during the last months. 
Something got wrong in November - December.

**Comment by joekirsch** [comment]
Same problem here.  1 of our organizations work, the other 2 do not.  We have gone thru every item trying to compare and see a difference and there aren't any differences we can see.

Connector sees the user login, sees DevOps, see the projects but any project we select returns: Choose the Azure DevOps team that you want to receive notifications for...  Failed to find teams for this project that had the required permissions to create service hook.

**Comment by Reempje25** [comment]
The same problem here. It was working all very well, but a this moment when can't select teams.

**Comment by froens** [comment]
The fix is being rolled out now and all should be done by 16'th of December (read the last posts from the URL posted earlier).

Apparently we've received the fix now (we are on Western Europe), and everything seems to work (we've been waiting for 1.5 months now).

**Comment by anthraxn8b** [comment]
Working now. THX!

**Comment by ramiMSFT** [comment]
@Russweb My apologies for the delayed response and thank you for your feedback. A fix has ben release for this issue. Ref: [1239563](https://developercommunity.visualstudio.com/t/azure-devops-connector-in-ms-teams-yields-a-client/1239563#TPIN-N1291476)
