### ISSUE TITLE
Import issue might be on credentials

### ISSUE THREAD

**Issue by rasmuschristensen** [MicrosoftDocs/azure-devops-docs#5193]
I had some issues importing a repository, until I generated alternate credentials from the "generate GIT credentials" option located where you also get the clone url in devops. I think this should be put into the FAQ or error listing when importing. First I tried to use the credentials I use for devops but no luck, needed to generate a pair of git credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops#feedback)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by samcneal** [comment]
I tried that but I still get
Import request cannot be processed due to one of the following reasons:

clone URL is incorrect
Clone URL requires authorization

I am trying to ensure I can access code files in my github from azure devops. Any suggestions?
