### ISSUE TITLE
Actual YAML example

### ISSUE THREAD

**Issue by IainCoSource** [MicrosoftDocs/azure-devops-docs#5220]
provide an actual yaml example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops#example-setup-using-github)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
@IainCoSource -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.

**Comment by IainCoSource** [comment]
You show before after screen shots in the documentation and screen shot of the "Classic" ui, but nothing showing how to setup in the yaml directly

**Comment by sobi3ch** [comment]
Or/and add step by step instructions like you can see on github help docs. I.g. https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account.

**Comment by tdi** [comment]
@IainCoSource maybe this will help. https://dev.to/7d1/using-go-modules-from-private-repositories-in-azure-devops-pipelines-44dk
