### ISSUE TITLE
TwineAuthenticate Example Incorrect

### ISSUE THREAD

**Issue by tarrenj** [MicrosoftDocs/azure-devops-docs#5273]
You must use `artifactFeed` when specifying a single feed, `artifactFeeds` will not work.  Interestingly enough, the `PipAuthenticate@1` task requires the plural version regardless of the number of feeds...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638243e7-cdd6-7573-aa6a-87c39da1bb3d
* Version Independent ID: d0046f56-ed26-7af2-3b8f-3dd5ab6ab892
* Content: [Publish packages to PyPI - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pypi.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pypi.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **elbatk**

**Comment by aasim** [comment]
Have to update the artifactsFeeds key to just artifactFeed

**Comment by ramiMSFT** [comment]
@tarrenj Thank you for your feedback. The updated article will go live shortly.
