### ISSUE TITLE
Can we add the information on how about how long the deleted branches are available for restore?

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/azure-devops-docs#5297]
Can we add the information on how about how long the deleted branches are available for restore?

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops)
* Content Source: [docs/repos/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/restore-deleted-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by kaylangan** [comment]
Assign to @apawast

**Comment by ChristopherMank** [comment]
Confirmed there is no retention policy. Deleted branches are kept indefinitely. Created PR #6131 to update docs.

**Comment by RobJohnston** [comment]
PR #6131 was merged long ago.  Time to close this.
