### ISSUE TITLE
Running Windows containers? Or Linux containers? Confused

### ISSUE THREAD

**Issue by t-l-k** [MicrosoftDocs/azure-devops-docs#5306]
When specifying `vmImage: 'windows-latest'` as the build pipeline agent, I was half expecting the image to be running Linux containers. 

But it is fails:

```
failed to build: image operating system "linux" cannot be used on this platform
```

Digging about the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops), I can't seem to find a vmImage that has a Windows agent host, but is running Linux containers. As this is my desktop experience, I was kind of half expecting a prebaked build agent image to do the same?

As per this [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops):

&gt; By default, Docker for Windows is configured to use Linux Containers.

As per this [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#single-job):

&gt; You must specify "Hosted Ubuntu 1604" as the pool name in order to run Linux containers. Other pools won't work.

Would help if it was a bit clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by msebolt** [comment]
@thomps23 @steved0x Please re-assign.

**Comment by msebolt** [comment]
Also including @mijacobs

**Comment by juliakm** [comment]
@azooinmyluggage This is the issue I referenced. I'm running into the same issue as the customer during testing.

**Comment by juliakm** [comment]
Windows containers will only run on a Windows `vmImage`. I'm updating the article.
