### ISSUE TITLE
Expand documentation for dependsOn

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-docs#5313]
I think the concepts section could benefit from a page dedicated to `dependsOn`. It would explain how different parts can depend on other parts, but also how to access values from dependencies, whether it be a job, deployment job, stage, etc.

This all may be covered in another section, but it is difficult to find the right page. For instance, if I want to access a variable from a job dependency, do I go to "Jobs", "Templates", "Variables"? It's not intuitive at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916ab215-0c42-fd49-d600-52f2d9ed18ac
* Version Independent ID: a2d1f2b1-a9f0-7513-a52d-c48dc51e3ba7
* Content: [Learn how to build and deploy your apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/pipelines/get-started/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
