### ISSUE TITLE
Generate badge without version restrictions

### ISSUE THREAD

**Issue by josesimoes** [MicrosoftDocs/azure-devops-docs#5318]
Currently the badge creation seems to be possible only for packages that have stable version number. The message is:
`A badge cannot be generated until a SemVer released version (e.g. 1.2.3, not 1.2.3-beta) `

I can't see a good reason for this limitation. Preview, beta, (…) versions are part of a standard release cycle. Any other badge provider allows this.
Please allow creating badges for any valid version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f530be-df56-eb28-e9a5-9e076554277f
* Version Independent ID: 37367a1e-e655-14ee-dfe4-7270ad85c7eb
* Content: [Share your Azure DevOps Services packages with badges](https://docs.microsoft.com/en-us/azure/devops/artifacts/package-badges?view=azure-devops)
* Content Source: [docs/artifacts/package-badges.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/package-badges.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@josesimoes  Thank you for the feedback.

Moving the issue to the [VSTS forums](https://developercommunity.visualstudio.com/idea/703726/generate-badge-without-version-restrictions.html) since this is product-related.

**Comment by msebolt** [comment]
There is nothing further that can be done with the documentation.

Please direct feedback to the link posted above.

**Comment by worldbeater** [comment]
Well, almost a year has passed. Is there any news on this? Still wondering why the limitation described in this issue actually exists. Sorry for writing here, but folks from VSTS forums seem to be completely ignoring us, so GitHub seems to be a far better (and the only) place to get updated on this https://developercommunity.visualstudio.com/idea/703726/generate-badge-without-version-restrictions.html

**Comment by msebolt** [comment]
Assigning this to the author until the product team provides a response.

**Comment by ramiMSFT** [comment]
Thank you for your feedback. We are closing this issue as there is no action to take on our part to address the issue. It seems that you already filed a feature request but it didn't generate enough upvotes. Thank you
