### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by rrnielsen** [MicrosoftDocs/azure-devops-docs#5418]
https://docs.microsoft.com/en-us/azure/devops/learn/git/git-pull-requests#learn-more

"give a specific suggestions" should be "give a specific suggestion"

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
