### ISSUE TITLE
Improvement to section:  Lifecycle for Feature Flags

### ISSUE THREAD

**Issue by arunko34** [MicrosoftDocs/azure-devops-docs#5440]
Thanks for great knowledge and DevOps awareness.

"Many feature flags go away and the teams themselves take care of that They decide when to go delete the feature flags."

Arun:
Please revisit above statement but understood its context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d3d423-7069-b03e-cc30-0facb8ab8a9f
* Version Independent ID: e00f9545-4c96-7e52-915a-b1bd5cdbcfdc
* Content: [Progressive Experimentation with Feature Flags - Azure DevOps](https://docs.microsoft.com/en-in/azure/devops/learn/devops-at-microsoft/progressive-experimentation-feature-flags#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fprogressive-experimentation-feature-flags.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fprogressive-experimentation-feature-flags.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **buckh**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
