### ISSUE TITLE
Agents are not cleaned up when stopping the container

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/azure-devops-docs#5445]
When running docker stop &lt;container&gt; the agent it's not being cleanup from the pool

If I replace the last line of the start.sh script ( exec ./externals/node/bin/node ./bin/AgentService.js interactive ) with:

```
./bin/Agent.Listener run & wait $!
````
Then stopping the container also removes the agent from the pool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#environment-variables)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by plbenpeterson** [comment]
I am experiencing the same behavior, and for me the proposed solution to replace the last line of start.sh with 
```
./bin/Agent.Listener run & wait $! 
```
is not working

**Comment by mborders** [comment]
This solution worked well for me, thanks!

**Comment by plbenpeterson** [comment]
It turns out my start.sh file was CRLF, which was the problem. Changing to LF solved it and now this proposed solution works for me as well. Thanks!

**Comment by thielef** [comment]
Is the agent then still capable of automatic updates including restarts?

**Comment by hajtomoto** [comment]
my issue is a bit similar to this one.
Once agents auto-update themselves, they wont cleanup after job is finished, they will keep executing jobs. Manual restart of each agent temporary solve the problem and eventually I will have agents cleaned up after themselves while using this line:

**exec ./externals/node/bin/node ./bin/AgentService.js interactive --once & wait $!**

**cleanup**

It looks like there is no option to stop agents from auto-update themselves.

**Comment by msebolt** [comment]
@thomps23 @steved0x Please re-assign.

**Comment by msebolt** [comment]
Also including @mijacobs

**Comment by juliakm** [comment]
This was fixed in https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2590.
