### ISSUE TITLE
Improvement : Revist the following sentence.

### ISSUE THREAD

**Issue by arunko34** [MicrosoftDocs/azure-devops-docs#5448]
Please revisit the following.

"You also have to tune in production. If you put in limits for resource utilization and you don’t try them out in production, they you may not have the limits you think."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77aec82c-9b62-2ff0-2707-83f3f7576d85
* Version Independent ID: d68f4da2-4605-dce4-20b1-7789ae4febd3
* Content: [Patterns for Resiliency in the Cloud - Azure DevOps](https://docs.microsoft.com/en-in/azure/devops/learn/devops-at-microsoft/patterns-resiliency-cloud#get-the-fallback-method-right)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fpatterns-resiliency-cloud.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fpatterns-resiliency-cloud.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **buckh**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
