### ISSUE TITLE
Regarding the rev with leading zeros...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#5468]
Nuget pack will strip them out if you are using build number for package version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@StingyJack  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by StingyJack** [comment]
It's a note for others, so they don't get burned by it also.

**Comment by msebolt** [comment]
@StingyJack Are you using **byBuildNumber** as the versioning scheme (see [nuget](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#yaml-snippet))?

If so, this should be filed as a bug in the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.

@thomps23  Issue needs to be transferred.

**Comment by StingyJack** [comment]
@msebolt - the notice/warning is better served in the places where the bit of functionality at topic will run or be run afoul by a commonly used module.

It's not an issue to the nuget team, they expect to break several things with this version "normalization" and have done it by design - and are not willing to back down on that position.

It's not an issue worth fixing to the build task team because they have decided it's more important to remove functionality from the tasks rather than fix simple defects.


This leaves us with the undesirable solution of leaving warning notes in the hopes that others can avoid unexpected and possibly significant problems.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by StingyJack** [comment]
@msebolt  @WilliamAntonRohm  - I guess cxwtool is the new stalebot with the same community destructive feature of closing things as if the OP had abandoned them (I didnt).

Except that this one taunts me with a "please reopen it". 
![image](https://user-images.githubusercontent.com/15381181/100242148-76880d80-2f02-11eb-9db7-20a227b5d271.png)

**Comment by mijacobs** [comment]
@StingyJack If you have info that you'd like added to the doc, we accept contributions--you can open a PR against the article. We have a team of folks standing by to review and approve PRs.

**Comment by StingyJack** [comment]
Thanks @mijacobs, I'm familiar with that. I'm just perpetually busy and if I make an edit on this topic it will probably come with a hefty salty flavor and get rejected, but at this point I may be able to summon enough burn ointment to write something proper. Can you undo the evil action done by the cxwtool and reopen this so it can be linked against a PR?
