### ISSUE TITLE
Documentation Ambiguity

### ISSUE THREAD

**Issue by spatzner** [MicrosoftDocs/azure-devops-docs#547]
This is stated to merge just changeset 137
c:\projects>tf merge /version:C137~C137 branch1 branch2 /recursive

The following is stated to merge all changesets up to 137
c:\projects>tf merge /version:C137 branch1 branch2 /recursive

This is said to discard only changeset 137 but has the syntax similar to the earlier command to merge all changesets up to 137
c:\projects>tf merge /discard /version:C137 branch1 branch2 /recursive

This should either be fixed or otherwise clarified that the version parameter is handled differently when using the discard parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2a034e-46b4-0c59-9cc1-b34a199383c9
* Version Independent ID: 7022c4b2-7011-5cdc-1b57-f2ee3b594bdc
* Content: [Merge Command](https://docs.microsoft.com/en-us/vsts/tfvc/merge-command?view=vsts)
* Content Source: [docs/tfvc/merge-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/tfvc/merge-command.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
#assign MaximMalygin

**Comment by PRMerger14** [comment]
MaximMalygin is already assigned.

**Comment by IlyaChistov** [comment]
#reassign @IlyaChistov

**Comment by MaximMalygin** [comment]
@steved0x can you closed it? Ilya fixed it in PR

**Comment by MaximMalygin** [comment]
@msebolt can you closed it?
