### ISSUE TITLE
Missing instruction on consuming a package using the CLI

### ISSUE THREAD

**Issue by assafsl** [MicrosoftDocs/azure-devops-docs#5476]
https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops

It is not clear if and how you can add a package to your project using `dotnet package add...`

**Comment by ramiMSFT** [comment]
@assafsl Thank you for reaching out. For .NET CLI use the following command:
```
dotnet add package <PACKAGE_NAME>
```
For NuGet, use: 
```
nuget install <packageID> -OutputDirectory packages
```
