### ISSUE TITLE
incremental behavior not working as described.

### ISSUE THREAD

**Issue by syendev** [MicrosoftDocs/azure-devops-docs#5528]
```When you run a pipeline on a self-hosted agent, by default, none of the sub-directories are cleaned in between two consecutive runs. ``` does not seem to be the case. 
Linux Ubuntu android build job with Gradle@2 task running compileDebugSources, all folders are wiped clean and re-builds every time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines, Azure DevOps Server, and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by Tr3yb0** [comment]
This has also been my experience using a Maven build. Every stage runs git checkout and removes all of the artifacts from previous jobs. I am using checkout:none on every stage that needs the output on a previous build job, which is essentially all of them except the initial checkout.

**Comment by gforceg** [comment]
This is causing my builds to jump up from 1 minute to 27m (sometimes it even times out at 60m) when `npm install` executes.

I have tried adding this but it does not have any effect.

```yaml
steps:
- checkout: self
  clean: false
```

**Comment by gforceg** [comment]
Should I just go back to 'classic' builds until this is fixed? It seems like there is no documented work around yet.

**Comment by gforceg** [comment]
This may have been [fixed in Feb 2020](https://github.com/microsoft/azure-pipelines-agent/commit/886dd396a450fb6c1c7b1cb323c5bc38dc10e199).

**Comment by gforceg** [comment]
I can confirm that upgrading to latest agent version (2.166.4) fixed the issue I was having w/ incremental builds.

**Comment by juliakm** [comment]
Thanks for following up @gforceg. Closing the issue.
