### ISSUE TITLE
Publish to Symbol Server for OnPrem installs

### ISSUE THREAD

**Issue by jgillette** [MicrosoftDocs/azure-devops-docs#5536]
The wording is a bit confusing as to whether the "Publish to Symbol Server in this organization/collection" is available for the OnPrem version of AzDO 2019. It shows up as an option on the screen, but returns a 401 unauthorized when it tries to run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops-2019)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by llewis-wildtree** [comment]
What is the status of this?  Is this just considered a docs issue, or is the underlying 401 issue going to be addressed for on-prem?

**Comment by ramiMSFT** [comment]
@jgillette Thank you for your feedback. Sorry for the late reply. If this was a product issue, it should be resolved by now. If you need further assistance you can report your issue and/or suggest a feature in the [Azure DevOps developer community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fspaces%2F21%2Findex.html&data=02%7C01%7Crami.bououni%40microsoft.com%7C920459fa74914be23b8b08d807dc478c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637267989955266208&sdata=bhak%2B%2F7CxOkofeB%2B1tfIQMgCkBUrBPioCpRsUpRTbp8%3D&reserved=0)
