### ISSUE TITLE
Using http.extraheader still prompts for interactive credentials

### ISSUE THREAD

**Issue by ctj232** [MicrosoftDocs/azure-devops-docs#5540]
I was unsuccessful following the instructions for cloning a repository in the same project as your pipeline. The page currently says you can include the http.extraheader with a bearer token using this syntax:

git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" &lt;clone URL&gt;

However, this still prompted for credentials which is unacceptable in a non-interactive pipeline. What did work for us was including the System.AccessToken in the https clone url like so:

git clone https://&lt;user&gt;:$(System.AccessToken)@dev.azure.com/&lt;your_repo_url&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by pviotti** [comment]
For me it worked as in the docs (`git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" <url>`), but I had to check this box in the Job configuration panel - which would be useful to add to the documentation:

![image](https://user-images.githubusercontent.com/1350095/67201937-56cd0e80-f3ff-11e9-8b1b-5b9299b61dae.png)

**Comment by msebolt** [comment]
Per @DrSLDR you can also use `Basic` authentication, see https://github.com/MicrosoftDocs/azure-devops-docs/issues/9287.

**Comment by AlexChongMicrosoft** [comment]
There is a possibility that the base64 coded string needs : before your PAT.
For example, my PAT is 12345, so I encode  :12345 and get OjEyMzQ1 as the output.

**Comment by vijayma** [comment]
Thanks for the comments. We are rolling out two fixes to the doc: One is to use "basic" instead of "bearer" for PAT tokens. The other is to add a note calling out the need to "allow scripts to access OAuth token".

**Comment by gomker** [comment]
The documentation found [here ](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat)on how this PAT is used still does not work correctly and prompts for username

**Comment by DrSLDR** [comment]
@gomker Alternatively, mirroring the method [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#alternative-to-using-the-checkout-submodules-option), does it work if you prefix the PAT with "pat:", prior to base64-encoding?

I.e. for the bash code:
```bash
MY_PAT=yourPAT		# replace "yourPAT" with your actual PAT
B64_PAT=$(printf "%s""pat:$MY_PAT" | base64) 
git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone https://dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName
```

**Comment by asasine** [comment]
I got this working by adding an additional config for `credential.username` as recommended by https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455#issuecomment-439503194:

```bash
git \
  -c http.$repo_url.extraHeader="AUTHORIZATION: Basic pat:$(echo $MY_PAT | base64)" \
  -c credential.$repo_url.username='anything' \
  clone $repo_url
```

**Comment by RRohi** [comment]
> There is a possibility that the base64 coded string needs : before your PAT. For example, my PAT is 12345, so I encode :12345 and get OjEyMzQ1 as the output. Otherwise I get terminal prompts disabled error.

This is the missing part! By adding `:` or `pat:` before the PAT, the authentication worked.
This tiny but important part is described in the Linux example but not in the PowerShell example.
