### ISSUE TITLE
Set up authentication on production 

### ISSUE THREAD

**Issue by tommyJimmy87** [MicrosoftDocs/azure-devops-docs#5547]
Would be cool to have a documentation : "Set up authentication in your production environment". 
Use case is that we have a pipeline which should publish a node application in a web app service in azure.
We are struggling a bit to do that, because the personal access token is for definition personal, this means not useful in a Production use case. Same for the Auth code from vsts which is not accessible from the pipeline to create a jwt token. So.. what is the way to setup a Production environment in order to use the feed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=mac#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
@tommyJimmy87 This is a great question! Thanks for the input, I'm going to bring in the Artifacts PM @elbatk for his expertise. Elijah, do you have any input here?

**Comment by elbatk** [comment]
We have this [doc on npm with Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&tabs=yaml). It actually could use updating to not use npm but use the [npm authenticate task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops) instead. 

In short, your builds can use the System.AccessToken to authenticate with Azure Artifacts feeds.

**Comment by magleaso** [comment]
This refers to publishing an app to the web app service in azure (a node app), not publishing NPM packages. This is a general pipelines question about service connections

**Comment by ramiMSFT** [comment]
@tommyJimmy87 Thank you for your feedback. We might be able to add such an article in the future. In the meantime, see [npm feed](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&tabs=yaml) for more information on how to publish npm packages to your feed and check out our [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) where you can post questions or suggest new features.
