### ISSUE TITLE
How to configure deployment group and pool access control via Azure DevOps REST API

### ISSUE THREAD

**Issue by alexandre-rondeau** [MicrosoftDocs/azure-devops-docs#5623]
After creating a deployment group and deployment pool using the REST API. There is no documentation on how to setup access control for that group and pool using the API. I found nothing under the deployment group or in security talking about this. How can we configure those access control?

**Comment by msebolt** [comment]
@marautee  Thank you for the feedback.

Does the [Security REST API](https://docs.microsoft.com/rest/api/azure/devops/security/?view=azure-devops-rest-5.1) article cover your needs?

Assigning this to the REST API author.

**Comment by marautee** [comment]
Sadly no it doesn't. I've looked at this one and when getting the list of all SecurityNamespaceIds. There are no ids for deployment group/pool.

**Comment by vtbassmatt** [comment]
I think we're missing docs for the `securityroles` area, which seems to be what the UI is calling. That's a core framework concern, not specific to Pipelines. @ramrajesh would be a good contact.

**Comment by WilliamAntonRohm** [comment]
@rajrmicrosoft -- please look into this issue.
