### ISSUE TITLE
How would you update a variable in variabe group?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/azure-devops-docs#5652]
would ##vso[task.setvariable variable=myvar]val1 work for updating a group variable called myvar?if not, how can I manipulate a variable defined in a variable group? we have different pipelines in the project. ones would compute group variables and others will consume those variables. we need to be able to dynamically set values for group variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by Felipe-Banno** [comment]
I'm also looking for this information. I tried with echo "##vso[task.setvariable variable=NAME]VALUE" but that only updates the ENV VAR and not update the value in the Variable Group

**Comment by syndicatedshannon** [comment]
I would like to pass information from an ancestor triggering build, such as the authoritative commit ID or the build ID holding the authoritative artifacts, and it could be solved by this issue.

@sasanmcp what did you have in mind for the scope of the variable change? if you alter it, is it permanent, and does it affect other runs started concurrently? if so, it would be subject to race conditions.

**Comment by rusticMire** [comment]
I update the variable group via REST API calls. I retrieve the list of variables in a variable group and parse the list using a foreach condition. Use an If condition for the variable I want to update  and update the same inside the If block and then update the new list via REST API

**Comment by sasanmcp** [comment]
@syndicatedshannon honestly I have not thought of concurrent runs. we need some type of semaphore or lock or something otherwise the race will happen as you pointed out correctly. I don't know but we need a method for updating.

**Comment by syndicatedshannon** [comment]
Here is my use-case and a potential approach.

https://stackoverflow.com/a/58395995/608220

Given the ability to locate the specific run (Build ID) of a desired pipeline (Definition ID) that was an ancestral trigger of the current pipeline, we could use that Build ID to evaluate its variables.

**Comment by roofiq** [comment]
> I update the variable group via REST API calls. I retrieve the list of variables in a variable group and parse the list using a foreach condition. Use an If condition for the variable I want to update and update the same inside the If block and then update the new list via REST API


Are you doing it by powershell scripts? I am looking for a way to update global variables (defined in yaml variable templates) and those in library. Could you provide here a code snippet?
Thanks :)

**Comment by thfsilvab** [comment]
Also waiting for the ability to manipulate variables from a variable group in a release pipeline. API calls won't work for me in some situations.
