### ISSUE TITLE
Present full working azure-pipelines.yml examples

### ISSUE THREAD

**Issue by basickarl** [MicrosoftDocs/azure-devops-docs#5683]
It's quite annoying that the documentation always splits up every section of a azure-pipelines.yml file and never shows an actual full example. Leaving the user to waste hours trying to get the file to work after piecing together every little section of code.

Present full working examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b2fdca-9125-9720-3d03-3c6dd336f100
* Version Independent ID: b2a24e28-9858-fe1c-4527-745f1f387e4e
* Content: [Build, test, and deploy JavaScript and Node.js apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/javascript?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/javascript.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/javascript.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by tylerjames** [comment]
I agree. 
I'm not sure how to put these steps together, it would be nice to see a full example of something that builds, packages, and deploys something. Then maybe highlight the individual parts that can be modified based on your needs

**Comment by SrikanthSoma** [comment]
I agree azure DevOps documentation is very outdated I wasted lot of valuable hours figuring out small details.
