### ISSUE TITLE
Reporting deployment in a monorepo

### ISSUE THREAD

**Issue by ADringer** [MicrosoftDocs/azure-devops-docs#5685]
We using Azure DevOps as a monorepo and I believe you are well (as described here: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft)

One issue we have with this is that a a commit is created for User Story 1 related to Application A. This is deployed to Development and so the story now shows that this is deployed to the Application A environment (using Application A pipeline).

A different story is finished with a commit for Application B and this is deployed separately. However as this is a monorepo it is aware of the commit of Application A (even though it isn't interested) and reports back to User Story 1 that it has deployed to Application B environment.

Similarly we have the same issue when comparing releases (commits and work items). Comparing current release to previous release of Application B will show Application A stories even though it's not interested.

I'm just wondering how we can get round this (if it's even possible). We can trigger pipelines and releases based on the path that the code has changed, but will need something similar to explicitly associate a release to a story based on the path of commit. 

Have you done anything similar to this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [See release deployment information from the work item form - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @danhellem
* Microsoft Alias: **kaelli**

**Comment by clouddna-au** [comment]
Any updates on this when using a monorepo?

**Comment by danhellem** [comment]
Sorry, no current plans to invest in the deployments control in 2020.
