### ISSUE TITLE
Run from package should not be used for a webjob deploymetn

### ISSUE THREAD

**Issue by jcbrooks92** [MicrosoftDocs/azure-devops-docs#5711]
If run from package is used with a webjob deployment from DevOps, users will get a 404 when they try to stop, start, or use other webjob APIs to manage the app. The cause of this is run from package puts the site into a read only mode. Some of the management APIs directly modify the settings.job file located in the directory of the webjob. Since its in read only with run from package this file cannot be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by N-Usha** [comment]
Sure. We agree that despite the performance optimization that Run from Package (RFP) offers, it has its own limitations. And we are soon making a change to the [Azure Web App task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops) where Zip deploy method is used by default (when deployment method is not specified) and RFP is used only when explicitly chosen by the user.

**Comment by msebolt** [comment]
This issue has been reported again under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9075.
