### ISSUE TITLE
This page needs updating as it does not describe the possible usage of the File Transform task

### ISSUE THREAD

**Issue by danieltulp** [MicrosoftDocs/azure-devops-docs#5715]
The file transform task (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform) has the ability to transform entire arrays in JSON files. Which makes it no longer necessary to use `DBAccess.Users.0 = NewUser` but you can use `DBAccess.Users = ["NewUser1","NewUser2","EvenAddMoreUsersThanBeforeDemoUser"]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by N-Usha** [comment]
Sure, Thanks for calling out. We'll have the documentation updated.

**Comment by AngryVirginian** [comment]
I confirm that this document needs to be updated.  In particular, this bullet point - "Only String substitution is supported for JSON variable substitution" needs to be changed. Replacing content of an entire json array works in the File Transform task and not in the App Service Deploy task.  Note: this is about replacing the value of the entire array and not replacing value each element via the index position. E.g., replacing "ids": [1,2] from the build pipeline with "ids": [1,2,3,4,5] in the release pipeline.

**Comment by Hurtyto** [comment]
Is this available in version 1

**Comment by msebolt** [comment]
The latest change has been reported as ineffective with the syntax still requiring `DBAccess.Users.0` instead of `DBAccess.Users`.

Please refer to issues https://github.com/MicrosoftDocs/azure-devops-docs/issues/9129 and https://github.com/MicrosoftDocs/azure-devops-docs/issues/9173.
