### ISSUE TITLE
Deployment Groups

### ISSUE THREAD

**Issue by MS-Santi** [MicrosoftDocs/azure-devops-docs#5722]
Need to include the definition of deployment groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **jillfra**

**Comment by Styxxy** [comment]
And also for the related item **Deployment Pools**
