### ISSUE TITLE
Add note that git-svn authors-transform.txt should be saved as UTF-8

### ISSUE THREAD

**Issue by cpboyd** [MicrosoftDocs/azure-devops-docs#5755]
I generated this with the PowerShell command:
```powershell
svn.exe log --quiet | ? { $_ -notlike '-*' } | % { "{0} = {0} <{0}>" -f ($_ -split ' \| ')[1] } | Select-Object -Unique > authors-transform.txt
```
 and edited/saved in Visual Studio Code.  Without my knowledge, the file was formatted as UTF-16LE.

This caused the first line of the file to never be read.  Changing the formatting to "UTF-8" (note: *without* BOM) fixed this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops#feedback)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by msebolt** [comment]
@cpboyd  Thank you for the feedback.

The documentation has been updated.

**Comment by cpboyd** [comment]
@msebolt `-encoding utf8` will add the BOM in standard Powershell (this behavior wasn't changed until Powershell 6): https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom

**Comment by msebolt** [comment]
Sorry about that, I'll reassign this to the author.
