### ISSUE TITLE
Incorrect server public key fingerprints in the "SSH Public Keys" page

### ISSUE THREAD

**Issue by olivierdagenais** [MicrosoftDocs/azure-devops-docs#5782]
When trying to clone via SSH today, I visited

https://(account).visualstudio.com/_usersSettings/keys

...and noticed neither the SHA256 nor the MD5 versions of the public key fingerprints matched.  Since I hadn't used my account in a while (i.e before the re-re-branding), I thought I might have been getting the fingerprints for the old names, so I then signed in through dev.azure.com and visited

https://dev.azure.com/(account)/_usersSettings/keys

...and say the same fingerprints that didn't match:

Server MD5 Fingerprint bc:dc:10:5c:1a:48:a7:c5:16:70:43:72:46:a6:2c:37 (RSA)
Server SHA256 Fingerprint YGzJgZudZVkYdnmgPuLFFgWE6CLA+cTuTcm+Jbs7g0Q (RSA)

...you can see those same incorrect values in the screenshot for Step 2.2 (the image with the `ssh_accessing_security_key.png` file name) at https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops (where I'm leaving this feedback/issue from)

It wasn't until I searched the web for "SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og" that I re-stumbled onto this page and found that value (I hadn't read that far the first time, mostly because your screenshot matched what I saw in my view), as well as the MD5 value, which matched what I was seeing.

Cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by 5eb** [comment]
I second this. The GUI on https://dev.azure.com/company/_usersSettings/keys explicitly asks the user to check the server fingerprint. And the keys don't match. 
GUI: 
Server SHA256 Fingerprint YGzJgZudZVkYdnmgPuLFFgWE6CLA+cTuTcm+Jbs7g0Q (RSA)
SSH:
The authenticity of host 'ssh.dev.azure.com (20.41.47.137)' can't be established.
RSA key fingerprint is SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og.

**Comment by msebolt** [comment]
The documentation has been updated.

**Comment by olivierdagenais** [comment]
> The documentation has been updated.

Where?

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md and https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/_img/use-ssh-authentication/ssh_accessing_security_key.png were last updated 15 days ago and the https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops page looks the same.

Is there a pull request?

Thanks!

**Comment by msebolt** [comment]
@olivierdagenais  See https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/169 referenced above.

The private repo is synced daily with public, so changes should be publicly available now.

**Comment by olivierdagenais** [comment]
Ah, because the other repo is private, no such link is visible to us mortals.

Thanks!

**Comment by MarkusRich** [comment]
Documentation is up to date, but the website still shows the wrong one. 
Wow the docu team is faster as the admin guys ;)

**Comment by span** [comment]
I'm getting a new thumbprint as of today causing my connection to be refused.

`SHA256:hYyj0U55Ykow9dr+YK8I00fKazdpBgK0ZDQVDq9wGqE.`

The devops ssh public keys page still shows `SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og.` so I guess I'm stuck for today.

**Comment by span** [comment]
As of this morning, the `ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og` key is back. It is unclear if there was a MiTM or some server error at Azure DevOps.

**Comment by vtbassmatt** [comment]
This was fixed with a PR the other day, not sure why it didn't close the issue.
