### ISSUE TITLE
compare files shortcut menu tip documentationn

### ISSUE THREAD

**Issue by swiix** [MicrosoftDocs/azure-devops-docs#5784]
"Choose Compare with Workspace Version to see what changes you have made to the version you checked out.

Tip

You can also press Ctrl+Shift and then double-click the file."
---
Ctrl+Shift is false. Only Shift + Double Click is the shortcut.

Tested in Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318c9e4a-6c12-ab7d-4fc8-f4640f0bd755
* Version Independent ID: aa8d36c5-a69e-8bf4-83da-bc52a6b9f7f5
* Content: [Compare files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/compare-files?view=azure-devops&redirectedfrom=MSDN&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/repos/tfvc/compare-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/compare-files.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan

**Comment by MaximMalygin** [comment]
@msebolt could you please close it, it was fixed in PR
