### ISSUE TITLE
Documentation inconsistent with UI labels

### ISSUE THREAD

**Issue by shawnhernan** [MicrosoftDocs/azure-devops-docs#5863]
Often, throughout the Azure DevOps documentation the words used in the documentation do not match the labels in the UI, and this leads to tremendous confusion. For example, on this page, you describe "Portfolio, product, and sprint backlogs," but when you actually look in ADO in the process templates, the labels used in the UI are "Portfolio," "Requirements," and "Iteration." It would be much easier if you were consistent between documentation and UI labels. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca2985c-878e-ee5d-9df3-ad5755abd873
* Version Independent ID: cf61abed-bd24-817f-7d28-f9f8a0002926
* Content: [What tasks do backlogs, boards, & plans support? - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/backlogs-boards-plans?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/backlogs-boards-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/backlogs-boards-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by martinessiet** [comment]
Absolutely, there are a lot of inconsistencies in the documentation and what you actually see in the product. This, which i agree with the comment, leads to tremendous confusion. The documentation is as best hastily written, or at worst poorly written. The PDF is not of any use at all, utterly confusing and misleading. Oracle database and product documentations are far much better than this!

**Comment by KathrynEE** [comment]
@shawnhernan, @martinessiet - Thank you for this feedback. I've left this issue opened for as long as I have as I wasn't sure how to address it. I agree the PDF is of no use as it doesn't provide support for versioned content and instead includes all content for all versions. This is a known issue which is being investigated. Also, the problem with consistent terminology is being addressed and we hope to provide better and more consistent content in the future.
