### ISSUE TITLE
Make it clearer that automatically-generated source control tags are build artifacts

### ISSUE THREAD

**Issue by moswald** [MicrosoftDocs/azure-devops-docs#5877]
Build artifacts are cleaned up with the build, meaning that any tags generated through the Tag sources UI will be deleted when the build exits the retention period and is cleaned up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@moswald  Thank you for the feedback, assigning this to the author for review.

**Comment by o-o00o-o** [comment]
Wow, didn't realise that at all. Perhaps this is why we won't use these.. should definitely be an option or made clearer

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by moswald** [comment]
@juliakm Let's re-open this one. And when it comes time to update the docs, I'm available in Slack to chat about what needs to be done.

**Comment by vijayma** [comment]
Thanks @moswald. I made this change to the docs. It should be out soon.
