### ISSUE TITLE
What project role/rights are needed to create new repos

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/azure-devops-docs#5909]
Can you state what project role/specific rights are needed for team members to be able to create new repositories

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df523114-2647-3282-525e-a0e4fe605dfb
* Version Independent ID: 91af894a-fb2f-ac3f-311f-978cd7dbf359
* Content: [Create a new Git repo in your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-new-repo?view=azure-devops#feedback)
* Content Source: [docs/repos/git/create-new-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-new-repo.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
#reassign steved0x

**Comment by steved0x** [comment]
You need Create Repository permission, which is granted by default to Project Administrators. Instructions are here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops

I am updating this page and it should be live today. Thank you for letting us know.
