### ISSUE TITLE
doesnt apply to TFS

### ISSUE THREAD

**Issue by rocifier** [MicrosoftDocs/azure-devops-docs#593]
TFS 2015+ are listed here, but there is no branches window on the ui, you need to somehow use Source Control Explorer, the process is completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159cece6-ada6-e50c-a236-0d49aed6d1be
* Version Independent ID: f6cc8cee-f37e-e738-3143-aa7f185fb461
* Content: [Copy changes to a branch with cherry-pick](https://docs.microsoft.com/en-us/vsts/git/tutorial/cherry-pick?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/cherry-pick.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/tutorial/cherry-pick.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rocifier The Cherry-pick and revert experience in the web portal was added in [TFS 2017.1](https://docs.microsoft.com/en-us/vsts/release-notes/2016/oct-12-team-services#cherry-pick-and-revert) but you should still be able to do it in Visual Studio like the article shows.

We are working on revising these tutorials to show web portal steps where available as well as Visual Studio and Command Line. Were you able to get your cherry-pick scenario worked out, and should we add some extra steps to this article to make it a better experience for the next person that wants to do the same thing?

Thank you for your feedback!

**Comment by rocifier** [comment]
Hi thanks for your reply. I was able to successfully follow a "cherry
picking" line of thought in TFS by applying a merge operation and picking
the "selected changesets only" option. I would highly recommend adding this
for TFS versions prior to 2017 as for example our (large) organisation is
unable to upgrade to that version due to a complex series of technical
issues which I'm not really qualified to go into, but suffice to say are
not resolvable.



Cheers
Ryan

**Comment by Bosch-Eli-Black** [comment]
I'm also not seeing the cherry-pick option in VS 2017 using TFS.
