### ISSUE TITLE
Need to update email address in the "Compliance certifications" section. 

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#5930]
I tried to send an email to " [Azure DevOps ServicesSOCReports](mailto:AzureDevOpsServicesSOCReports@microsoft.com)". I received the following error: 
We won't be able to deliver this message to AzureDevOpsServicesSOCReports@microsoft.com X because the email address is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops#compliance-certifications)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by msebolt** [comment]
@DaveBurnisonMS Thank you for the feedback, assigning this to the author for visibility.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
