### ISSUE TITLE
Cloning Git Repo and Commits

### ISSUE THREAD

**Issue by trycatchdonothing** [MicrosoftDocs/azure-devops-docs#5991]
1) With having only one repo with a bunch of subfolders, do users end up cloning the entire repo to their local machines? 
2) When users work on individual projects within the repo, are changes still committed all under one "master" branch, or do you have a "master" for each component?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f4784d-1539-adc9-68e1-036cfc004722
* Version Independent ID: d02a6a52-e736-b411-b2f8-5be08ad3f5a0
* Content: [How We Use Git at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft#feedback)
* Content Source: [docs/devops-at-microsoft/use-git-microsoft.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/use-git-microsoft.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
