### ISSUE TITLE
Add State Changed example DAX is incorrect

### ISSUE THREAD

**Issue by rernst-IQ** [MicrosoftDocs/azure-devops-docs#5993]
The line: 'View Name'[State Previous] &lt;'View Name'[State] appears to be incorrect.
I think it should be: 'View Name'[State Previous] &lt;&gt; 'View Name'[State]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c046b7-9bc7-2b63-9401-72af0e1a577e
* Version Independent ID: d9d85ca9-74ba-63bd-0edf-8f95754d4991
* Content: [Add a time-in-state measure to a PowerBI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report?view=azure-devops#add-state-changed)
* Content Source: [docs/report/powerbi/create-timeinstate-report.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/create-timeinstate-report.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@rernst-IQ -- thank you for your feedback.  On further investigation I believe the "<" operator should instead be "=", as an assignment rather than a condition.

@KathrynEE -- please review the changes in the above-mentioned PR 5993.

**Comment by rernst-IQ** [comment]
@WilliamAntonRohm I still believe it should be `View Name'[State Previous] <> 'View Name'[State]`. This calculated column is supposed to be a boolean that identifies whether that row is a state transition. By using the 'Not Equal To` operator you will correctly catch rows where the previous state does not match the current state, which means the comparison will return `True` as expected. If you use `=` you will return False for state transitions which is not the intent of this column.

**Comment by WilliamAntonRohm** [comment]
@rernst-IQ -- I see your point of view.

@KathrynEE -- please resolve this thorny puzzle.

**Comment by kareldeman** [comment]
I also think this should be <> rather than = . In the current documentation it is stated as =,

**Comment by WilliamAntonRohm** [comment]
@kareldeman -- thank you for your feedback.

@KathrynEE -- please add a note regarding the example's logic.

**Comment by KathrynEE** [comment]
@kareldeman, @rernst-IQ - Thank you for the correction. I will update the article today as you have indicated.
