### ISSUE TITLE
Windows Docker Agents are not cleaned up 

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/azure-devops-docs#6019]
Also with the Windows Docker Container script provided here the docker agents are not cleaned up in the Pool after stopping the container. 
The finally block is never executed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by gabrielmccoll** [comment]
is there really not a solution for this yet ? ,  I'm too thick to figure out what to do to solve this

**Comment by gabrielmccoll** [comment]
Actually I might have figured it out. in the Try step we remove the Env variable for AZP_TOKEN_FILE Then we try to use it again in the Finally. But it's gone. So that part fails.   I found if I just swapped all the token file variables for just AZP_TOKEN it worked
Pasted below (also note I added the --once flag)
Please note. I do NOT know if this is bad security.   
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
if (-not (Test-Path Env:AZP_URL)) {
  Write-Error "error: missing AZP_URL environment variable"
  exit 1
}

if (-not (Test-Path Env:AZP_TOKEN_FILE)) {
  if (-not (Test-Path Env:AZP_TOKEN)) {
    Write-Error "error: missing AZP_TOKEN environment variable"
    exit 1
  }

  #$Env:AZP_TOKEN_FILE = "\azp\.token"
  #$Env:AZP_TOKEN | Out-File -FilePath $Env:AZP_TOKEN_FILE -verbose
}

#Remove-Item Env:AZP_TOKEN -verbose

if ($Env:AZP_WORK -and -not (Test-Path Env:AZP_WORK)) {
  New-Item $Env:AZP_WORK -ItemType directory | Out-Null
}

New-Item "\azp\agent" -ItemType directory | Out-Null

# Let the agent ignore the token env variables
$Env:VSO_AGENT_IGNORE = "AZP_TOKEN,AZP_TOKEN_FILE"

Set-Location agent

Write-Host "1. Determining matching Azure Pipelines agent..." -ForegroundColor Cyan

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$Env:AZP_TOKEN"))
$package = Invoke-RestMethod -Headers @{Authorization=("Basic $base64AuthInfo")} "$(${Env:AZP_URL})/_apis/distributedtask/packages/agent?platform=win-x64&`$top=1"
$packageUrl = $package[0].Value.downloadUrl

Write-Host $packageUrl

Write-Host "2. Downloading and installing Azure Pipelines agent..." -ForegroundColor Cyan

$wc = New-Object System.Net.WebClient
$wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")

Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"

try
{
  Write-Host "3. Configuring Azure Pipelines agent..." -ForegroundColor Cyan

  .\config.cmd --unattended `
    --agent "$(if (Test-Path Env:AZP_AGENT_NAME) { ${Env:AZP_AGENT_NAME} } else { ${Env:computername} })" `
    --url "$(${Env:AZP_URL})" `
    --auth PAT `
    --token "$Env:AZP_TOKEN" `
    --pool "$(if (Test-Path Env:AZP_POOL) { ${Env:AZP_POOL} } else { 'Default' })" `
    --work "$(if (Test-Path Env:AZP_WORK) { ${Env:AZP_WORK} } else { '_work' })" `
    --replace

  # remove the administrative token before accepting work
  #Remove-Item $Env:AZP_TOKEN_FILE

  Write-Host "4. Running Azure Pipelines agent..." -ForegroundColor Cyan

  .\run.cmd --once
}
finally
{
  Write-Host "Cleanup. Removing Azure Pipelines agent..." -ForegroundColor Cyan
  
  .\config.cmd remove --unattended `
    --auth PAT `
    --token "$Env:AZP_TOKEN"
}```

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by gabrielmccoll** [comment]
This isn't fixed

**Comment by sbaeurle** [comment]
isn't this a duplicate of #8696?

The workaround mentionend there (use `docker exec containerid powershell -Command Stop-Process -Name Agent.Listener` before removing the container) works until the behavior regarding `docker stop` is implemented correctly

**Comment by WilliamAntonRohm** [comment]
@sbaeurle -- Simon, thank you for making that connection.
