### ISSUE TITLE
SSH key authentication doesn't work on Mac

### ISSUE THREAD

**Issue by futie** [MicrosoftDocs/azure-devops-docs#6033]
Despite being a recommendation here this is not reliably working on Visual Studio for Mac. See https://developercommunity.visualstudio.com/content/problem/537655/version-control-operation-failed-this-operation-is.html for more details. Suggest documentation is revised until this is actually a working feature ..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by wwinogrodzki** [comment]
No matter what I do, I always get SSH authentication failure; or password prompt on https (password to what?). I'm on Catalina. NO TOOL works. VS, VS Code, Rider, sh, power shell: all fail the same way. Needless to say, on Windows it just rocks.
