### ISSUE TITLE
lack of documentation about 'Completion options' of "Automatically include reviewers"

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/azure-devops-docs#6088]
In the "Automatically include reviewers" windows (Azure DevOps site) there is a check-box "Requestors can approve their own changes" under "Completion options", but no information in this documentation § "Automatically include code reviewers", yet it complicates the comprehension of the function in relation to the general parameter with the same name ("Requestors can approve their own changes" under "Require a minimum number of reviewers")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@nicos99  Thank you for the feedback, assigning this to the author for review.

**Comment by jpreese** [comment]
We are also confused by this messaging!

**Comment by jpreese** [comment]
Oh no! @v-shils why was this closed?

**Comment by vtbassmatt** [comment]
@jpreese have no fear, it was a robo-action because a PR completed which will fix the doc. Unfortunately that PR completion is in a private repo so you can't see it here in the activity log 😞 But here's a screenshot!

<img width="853" alt="image" src="https://user-images.githubusercontent.com/714283/90039608-ded51b00-dc94-11ea-9a40-785f68871e19.png">
