### ISSUE TITLE
As additional info, this page should link to the MS hosted agents (vm Ubuntu) 

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/azure-devops-docs#6113]
This way, we can tell whether this is actually optional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb95406-322e-11db-41e0-7b8064c8295c
* Version Independent ID: 57fb95a8-385d-7548-ee6a-9a3a875a150e
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by katlimruiz** [comment]
I see that there is already a link, yet it is only that I know beforehand that it may already be installed that I've gone and see the details.

**Comment by WilliamAntonRohm** [comment]
@katlimruiz -- Kat, thank you for your feedback.

@vijayma -- Vijay, please look into this issue.
