### ISSUE TITLE
Run Test Option in Test Plans

### ISSUE THREAD

**Issue by GokulVijayan** [MicrosoftDocs/azure-devops-docs#6188]
I just wanted to known whether Run Test option has been disabled from Sprint 158-September 23 onward.
Earlier there was a run test option available under Test Plans in azure devops.But now i am not able to find such a option.I can only find options such as:
Execute test points against a web or desktop application
'Run with options' to leverage Microsoft Test Manager for execution

I was trying to run automated tests from test plans  by referring the following document:https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops

Any help will be appreciated.

**Comment by msebolt** [comment]
@GokulVijayan Thank you for the feedback, we're sorry for the confusion.

I can't seem to find **Run Test** mentioned in the topic so it's likely the feature was either moved or removed.  Is anything outdated in the document?

As for product feedback, please see [this post](https://developercommunity.visualstudio.com/content/problem/324010/test-runs-menu-item-where-all-test-runs-could-be-v.html) as a possible solution, else start another thread with the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.

**Comment by GokulVijayan** [comment]
Yes i did found the found the following document:https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops outdated as the documents specifies that there is a way to run tests using Run Test option.It is little bit confusing.

**Comment by msebolt** [comment]
Thank you for the confirmation, assigning this to the author for review.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
