### ISSUE TITLE
Does NOT follow .gitignore syntax strictly

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/azure-devops-docs#6201]
The statement that the gitignore and artifactignore syntax the same is erroneous and misleading. 

Maybe for simple scenarios, but the following scenarios are not the same.

For example, try:
```
/*/**
!/*.*
```

To exclude everything but files with an extension in the root directory. Works with gitignore but not with artifactignore.

`git check-ignore Gitversion.yml`
Gitversion.yml

`git check-ignore Tests`
&lt;&lt;blank result&gt;&gt;

However do the same in an artifact ignore, and you don't get the same result.

Or this example:
```
**/*
!*.zip
```

Which is basically the one in the documentation, only acting on the root folder rather than a subfolder. It will still capture zips in subfolders. If you try `!/*.zip` to explicity specify the root directory (even though you don't have to with .gitignore), it won't capture anything at all. `!test.zip` captures any test.zips in subdirectories as well when it should just capture in the root folder, suggesting an issue with the wildcards or the combination of ! with /.

So a lot of the gitignore syntax recommendations don't work, and it is misleading and frustrating to say that they will...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b39086-3718-419d-d850-914422097cde
* Version Independent ID: 4f23e54f-f59b-85ab-2eb0-6a58eb0ad088
* Content: [Use the .artifactignore file](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops)
* Content Source: [docs/artifacts/reference/artifactignore.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/reference/artifactignore.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by msebolt** [comment]
@JustinGrote Thank you for the feedback, assigning this to the author for review.

**Comment by Thilas** [comment]
Any news about this? Either publish a comprehensive documentation of `.artifactignore` behavior or do align with actual `.gitignore` one but right now this is really frustrating. Keep doing "try and error" is not a way to go for such things.

**Comment by Thilas** [comment]
I looked at the code that evaluates `.artifactignore` files (decompiling class `GlobFactory` in `Microsoft.VisualStudio.Services.BlobStore.Common`) and it appears that on Windows agents, backslash `\` is expected as directory separator (and slash `/` on *nix agents).

Could you please update the documentation and, ideally, could you also consider supporting slashes on Windows agents as well?

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by JustinGrote** [comment]
@msebolt can you confirm if @willsmythe is still active and if this needs to be assigned to a different person?

**Comment by mmankos-microsoft** [comment]
Just created a relevant issue here - https://github.com/MicrosoftDocs/azure-devops-docs/issues/6201
