### ISSUE TITLE
"Search all branches" is not available; can't restore deleted branches

### ISSUE THREAD

**Issue by soulis64** [MicrosoftDocs/azure-devops-docs#6229]
The "Search all branches" textbox is no longer available; instead there's a "Filter by keywords" textbox that does not provide the "Search for exact match in deleted branches" function. This has made the restore deleted branches functionality non-accessible.

![image](https://user-images.githubusercontent.com/19352132/68045385-5ce8a800-fca7-11e9-992e-c314539b0ff5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops)
* Content Source: [docs/repos/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/restore-deleted-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by soulis64** [comment]
Further investigation on our team showed that the issue is caused by the "New Repos landing pages" preview feature. Turning off the feature restored the old textbox and "Restore deleted branch" functionality.

![image](https://user-images.githubusercontent.com/19352132/68046897-08dfc280-fcab-11e9-8659-c1220503e798.png)

**Comment by WilliamAntonRohm** [comment]
@soulis64 -- Michael, thank you for your observations.

@kaylangan -- Kayla, please consider adding a note in the documentation.

**Comment by kaylangan** [comment]
@WilliamAntonRohm, you want @apawast. I don't work on Azure Repos anymore.

**Comment by haep1** [comment]
@apawast Please integrate this feature in the new repos landing page as there is no possibilty at the moment to restore deleted branches in the new theme.

**Comment by apawast** [comment]
@soulis64 @haep1 @WilliamAntonRohm Thank you for pointing out the issue and I apologize for your inconvenience! I am not updating the docs because we will be shipping this fix soon!

**Comment by SebastianSchuetze** [comment]
@apawast I currently still don't see this being fixed in the new repo UI. when is this being deployed?

**Comment by iamalexmang** [comment]
This comment comes after two and a half years on the latest information on "we will be shipping this fix soon".
FYI, there is still **NO** way to restore a deleted branch, a functionality which existed prior to the theme update. In my eyes, we're missing two major components, namely the ability to restore a branch and a confusing and not applicable documentation.
May I ask what the status is?

**Comment by mattfrear** [comment]
> FYI, there is still NO way to restore a deleted branch, a functionality which existed prior to the theme update. 

Hi @iamalexmang , you can restore a deleted branch, but you have to know it's exact name.
Go to Branches -> Search for the branch, and it will appear in the results under "Deleted branches". From there you can restore it.

![image](https://user-images.githubusercontent.com/169179/116941420-bf1ed080-acc3-11eb-9691-0bd98ccb647d.png)

**Comment by iamalexmang** [comment]
Thanks @mattfrear, had no clue about it. Might be worth an update in the docs too which are still referencing the old UI.

**Comment by Codare** [comment]
Can you please tell me why we cannot see a list of previously deleted branches by name?

Why should I be expected to search for a branch by its exact name before I can restore it.

Can you remember all of the branches exact names that you have ever deleted before?

I did not link the branch to a work item either.

You must be able to provide this functionality in Azure devops?

Thanks

Adrian

**Comment by johnatanstanley** [comment]
Hey, I know this might be an old issue, but is there any way to restore a deleted branch when you don't know the exact name? We're currently facing a problem with a deleted branch that seems untraceable. Any assistance would be greatly appreciated. Thanks!

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
