### ISSUE TITLE
Update the docs to the new repository options/policies

### ISSUE THREAD

**Issue by shayki5** [MicrosoftDocs/azure-devops-docs#6236]
Hi,
In the recent releases you changes the repo settings to "Options" and "Policies", you need to update the docs with updated photos and new info about the new policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ba72fe-98e6-cb93-f4e4-6950573a2a8c
* Version Independent ID: 260aaae9-0df1-74e6-9d39-7723d2bc7d2c
* Content: [Repository settings - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops#feedback)
* Content Source: [docs/repos/git/repository-settings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/repository-settings.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by NenoLoje** [comment]
This page seems heavily out of date. New options/policies have been added to the /_settings/repositories page which have not yet been reflected here.

**Comment by NenoLoje** [comment]
@apawast - could you share an update on this one?

**Comment by ToMakeSense** [comment]
I think corresponding documentations describe creating, deleting and renaming repositories operations are also required.

**Comment by WilliamAntonRohm** [comment]
@apawast -- please look into this issue.

**Comment by apawast** [comment]
Hi @shayki5, I plan to update this document this week, thank you for opening an issue.

**Comment by shayki5** [comment]
Hi @apawast, This is great! thank you!

**Comment by jfranki** [comment]
Please, provide "Commit author email validation" examples with wildcards.
