### ISSUE TITLE
`nuGetFeedType` and `packagesToPush` descriptions incorrect

### ISSUE THREAD

**Issue by brandonaut** [MicrosoftDocs/azure-devops-docs#6248]
In the [Arguments section](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#arguments), I think `packagesToPush` has the description for `nuGetFeedType` and the entry for `nuGetFeedType` is entirely missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#arguments)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ScotSalmon** [comment]
Related, the YAML snippet at the top of the page says:
`#packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg' # Required when command == Push`
But it looks like the value shown is the default when command is push, and it's not actually required if you are okay with that value (which is compatible with the default behavior of pack).

**Comment by ramiMSFT** [comment]
@brandonaut Thank you for your feedback. The article reference is being updated to address the issue.
