### ISSUE TITLE
Squash commits in Git using Visual Studio

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-devops-docs#6268]
>Interactive rebase is not currently supported in Visual Studio, but you can use the following command line steps to consolidate your commits.

As of VS 2019 we can squash commits in the UI 😀🎉

Reference Dev Community: [Squash commits in Git using Visual Studio](https://developercommunity.visualstudio.com/idea/351072/squash-commits-in-git-using-visual-studio.html)

[My documentation](https://github.com/spottedmahn/my-blog/issues/26)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf2704e-ef04-e4ab-88ba-48533fa62d21
* Version Independent ID: e59a9067-775b-d9df-94b7-29076dbfbf25
* Content: [Update your branch history with rebase - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/rebase?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/rebase.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/rebase.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@spottedmahn  Thank you for the feedback, assigning this to the author for review.
