### ISSUE TITLE
Multiple patterns

### ISSUE THREAD

**Issue by nelisbijl** [MicrosoftDocs/azure-devops-docs#6290]
Documentation states:  Supports multiple lines of match patterns

Would love to see an example. Everything I tried so far failed

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b2ea8b7b-44cb-e315-b086-c4e3361bf59a
* Version Independent ID: 5fcdaa72-ca89-2139-a8c9-2eb263b4824e
* Content: [FTP Upload task - Azure Pipelines](https://docs.microsoft.com/nl-nl/azure/devops/pipelines/tasks/utility/ftp-upload?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/utility/ftp-upload.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/ftp-upload.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@nelisbijl Thank you for the feedback, we apologize for the issues.

Assigning this to the author for review.

**Comment by HughDevlin** [comment]
also would love to see an example. issue opened 3 months ago. any update? thanks

**Comment by elmer-t** [comment]
Running into the same issue, a few examples would be awesome!

**Comment by elmer-t** [comment]
Searching some more on "yaml multiline" helped a lot. This seems to work:

filePatterns: |
  **
  !.git/**


Hope this helps

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by HughDevlin** [comment]
Please re-open this issue.

Please add a simple working example. Please add an example of supplying multiple lines of match patterns to the filePatterns argument.

**Comment by ramiMSFT** [comment]
@nelisbijl Thank you for your feedback! Try this. See [File matching patterns](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops) for more details.
  `
patterns: | 
    **/*.cs
    **/*.tar`
