### ISSUE TITLE
Improve docs for self-hosted agent

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#6305]
Maybe we can improve the docs by explicitly stating that ".complete" files need to be created. Whilet here is pointer to GitHub where this is explained, this requirement seems unusual and unexpected enough that it would be worth calling it out here.

see also: https://developercommunity.visualstudio.com/content/problem/804581/pipelines-how-to-configure-side-by-side-python-con.html?childToView=812906#comment-812906

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d52f9bd-a63c-d65f-ad92-7f245e4eb5c0
* Version Independent ID: 51ce0fb6-3195-6593-bd62-57c1c0157989
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @brcrista
* Microsoft Alias: **brcrista**

**Comment by vtbassmatt** [comment]
Someone already did this work, so I'll resolve the ticket.
