### ISSUE TITLE
Confusing statement in release-merge directions.

### ISSUE THREAD

**Issue by CNSKnight** [MicrosoftDocs/azure-devops-docs#6307]
&gt; Merging the feature branch into the master branch can bring over release-specific changes you **don't** want in the master branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#feedback)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by polshgiant** [comment]
I was very confused by this same exact statement.  I think they mean: "Merging the *release* branch into the master branch can bring over release-specific changes you don't want in the master branch."

**Comment by sarathy827** [comment]
To make it clear.Master should always have the production version of code and Release version of code should be merged only after the code is released to production that way the release specific changes will be kept in a separate branch that is not required to be in Master
