### ISSUE TITLE
Rebase and Force Push examples should be synced

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/azure-devops-docs#6308]
The section on rebase is demoing rebasing from master to dev. This should be made more clear as it is not obvious what you should be rebasing from and to unless you already understand how rebasing works.

The next section mentions that you then need to force push to update the branch but the example mentions a completely different branch name of `users/frank/myfiles` which has nothing to do with `master` or `dev`. As such someone who doesn't understand how rebase works is now left wondering what the correct command is to force push the changes they just made from `master` to `dev`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf2704e-ef04-e4ab-88ba-48533fa62d21
* Version Independent ID: e59a9067-775b-d9df-94b7-29076dbfbf25
* Content: [Update your branch history with rebase - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/rebase?view=azure-devops&tabs=visual-studio#when-to-rebase-vs-merge)
* Content Source: [docs/repos/git/rebase.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/rebase.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by rroman81** [comment]
completely concur here.  Rebasing is a tough concept for developers in general. A few of my team members also got confused looking there.  So when you UI shows rebase from the current branch, it's generally a topic branch. Then, replaying the commits onto another branch, generally a base branch i.e. master or development.  Then force pushing those changes via "git pull -f".  Furthermore, someone may still need to pull divergent history of the topic branch and that means showing how to "git fetch --all; git reset --hard origin/feature/topic"  would complete the entire flow.

**Comment by WilliamAntonRohm** [comment]
@apawast -- please look into this issue.
