### ISSUE TITLE
Update "Enforce a merge strategy" section with New merge types for completing pull requests

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#6344]
According to https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#azure-repos there re new merge types which are not yet reflected on this page.

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by NenoLoje** [comment]
This blog post can probably help: https://devblogs.microsoft.com/devops/pull-requests-with-rebase/

**Comment by corradin** [comment]
Please update the text and screenshots as suggested by @NenoLoje. It should be "Limit merge types".

**Comment by vtbassmatt** [comment]
Looks like this got done at some point without having this issue closed.
