### ISSUE TITLE
Container resource doc needs updating

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/azure-devops-docs#6356]
Per the Nov 4 release notes  https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-160-update#acr-as-a-first-class-pipeline-resource, the container resource now supports using an ACR container image as a trigger to a pipeline.    
The updated YAML schema (Resource section) needs documentation.  There is an example on the release notes page, but it does not provide detail for all of possible options. 
Please update this page to provide this updated information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by ashokirla** [comment]
We are working on the overall documentation for resources and triggers. It will be updated soon.
