### ISSUE TITLE
Docker task seems to overwrite itself when you have multiple dockerfiles

### ISSUE THREAD

**Issue by jholovacs** [MicrosoftDocs/azure-devops-docs#6376]
The docker task lets you specify a file pattern that will allow you to find multiple docker files.  It locates the docker files, builds the images, and then... names them all the same thing?  When pushed, you only end up with 1 docker image, because the other was just overwritten.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by Manojbhat-dot** [comment]
Any updates on this Issue

**Comment by anraghun** [comment]
@jholovacs @Manojbhat-dot The task can be used to push a single image to multiple registries but cannot be used to push multiple images. It will pick the first dockerfile it can find in the path provided. I have updated the doc to reflect the same.

**Comment by anraghun** [comment]
@msebolt Can we close this issue?
