### ISSUE TITLE
Set a Gate time delay above 48 hours

### ISSUE THREAD

**Issue by edgariscoding** [MicrosoftDocs/azure-devops-docs#6392]
I would like to be able to set a time delay of 94 hours (four days) for a post approval Gate. Is there a reason this delay is capped at 48 hours?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b27fd8-df35-5e98-8c6e-2924f541a504
* Version Independent ID: 4c6e6300-2354-a9ec-0cf3-7f935ea268ce
* Content: [Understand approvals and gates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/index?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by shashban** [comment]
Can you help me with the scenario? 

Delay before evaluation is meant to be the time samples from the gates might be unreliable. During this time, samples are collected for reference purpose.
If you need to delay start of gates overall, it is recommended to use a delay task in the deployment process.

**Comment by ramiMSFT** [comment]
@edgariscoding Thank you for your feedback. The updated article will go live shortly.
