### ISSUE TITLE
Click on "Generate Maven Credentials"

### ISSUE THREAD

**Issue by nerijusk** [MicrosoftDocs/azure-devops-docs#6417]
This button is nowhere to be found as described in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03a84e2-22c7-6899-5ac1-c1ed79c05ba6
* Version Independent ID: 405e0a0e-b12b-3fd3-7135-5deb022cd9c3
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?view=azure-devops#feedback)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by soccerjoshj07** [comment]
Use the [Maven Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops) task to create a settings.xml for you to use to authenticate to Feed.

**Comment by aasim** [comment]
As @soccerjoshj07 mentioned, we now recommend using the MavenAuthenticate task, which has the correct instructions. For the exact issue here, I think we can update the documentation like this:

1. Navigate to your Maven feed and click "Connect to Feed". Click on "Maven".
2. Edit your pom.xml file, and add the repository snippet to the <repositories> and <distributionManagement> sections.
3. Add or edit your local settings.xml file and add the <server> snippet in the <servers> section.
4. Generate a personal access token with Packaging read & write scopes and paste it into the <password> tag.

**Comment by ramiMSFT** [comment]
@nerijusk Thank you for your feedback. The updated article will go live shortly.
