### ISSUE TITLE
'artifact.upload' instead of 'PublishTestResults@2'

### ISSUE THREAD

**Issue by aktzbn** [MicrosoftDocs/azure-devops-docs#6427]
Example for 'artifact.upload' contains 'c:\testresult.trx'.  Does it mean that it is possible to use 'artifact.upload' instead of 'PublishTestResults@2'  task  without specification of format of a test report ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@aktzbn Thank you for the feedback.

Since this question goes beyond the scope of the provided example it would be better geared towards the tasks repo.

Can you please move this to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) issues?

Including @thomps23

**Comment by msebolt** [comment]
Closing now.  Please add comments below if there are further issues.

**Comment by aktzbn** [comment]
Why does the question go beyond the scope of the provided example? The purpose and behavior of the example is unclear that's why question appeared.

**Comment by msebolt** [comment]
@aktzbn Apologies for the delay.

The example `c:\testresult.trx` is really meant to illustrate uploading a set of results for use in custom logging processes such as changing format (see [this post](https://stackoverflow.com/questions/23446/how-do-i-format-visual-studio-test-results-file-trx-into-a-more-readable-form)), etc., not replacing the added functionality of the `PublishTestResults@2` task or similar tasks such as the [Visual Studio Test](https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest) task.

**Comment by aktzbn** [comment]
But it is still unclear if ADS is able to recognize format of uploaded file and display it properly, If not then better to replace file extension to something less confusing. If yes - then better to specify the behavior and supported formats.
