### ISSUE TITLE
Not clear how to consume build artifacts without an extra step

### ISSUE THREAD

**Issue by KSchlobohm** [MicrosoftDocs/azure-devops-docs#6437]
Documentation shows that you can download the build artifacts using the `DownloadBuildArtifacts` task which allows you to specify the folder where the content is stored.

However, when using the `Deployment` task the build artifacts are downloaded by default to a directory which does not appear to by specified by a [predefined variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml).

There appear to be two workarounds, you can use a root variable like `$(System.WorkFolder)` and hard code the rest of the path or you can duplicate the artifact download process using the `DownloadBuildArtifacts` task to put the artifacts in a known location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#how-do-i-consume-artifacts)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@KSchlobohm Thank you for the feedback, assigning this to the author for review.

For needed predefined variables, consider using **Suggest a feature** in the [Visual Studio community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) to hear from the product team.

**Comment by KSchlobohm** [comment]
Thanks @msebolt, looks like this is a [topic that was already discussed](https://developercommunity.visualstudio.com/content/problem/609949/multi-stage-yaml-pipeline-artifact-download-proble.html) and the solution is to use the `$(Agent.BuildDirectory)` which solves my problem.

I think it would be helpful to add a note that when using the deployment task you can reference the content with this variable. Another place that would have helped me is if the variable had been called out on [the deployment task's documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops).

**Comment by ramiMSFT** [comment]
@KSchlobohm  Thank you for your feedback. The updated version will go live shortly.
