### ISSUE TITLE
Stage/Job breakup with npm tasks is misleading

### ISSUE THREAD

**Issue by jason-ha** [MicrosoftDocs/azure-devops-docs#6463]
In Job/Stage re-use sections examples are given where `npm install` is in a different job than `npm test`.
Azure pipelines enforce a cleanup between jobs making this impractical. Perhaps there are cases when you can output sufficient artifacts to enable this, but the complexity is surely missing from the documentation. Examples don't even call out dependencies for those jobs.
In my practical experience most npm sequences are placed in the same job.
These examples should be changed to something more practical. (Or support needs added to enable such a nice pattern.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@jason-ha Thank you for the feedback, assigning this to the author for review.

**Comment by sanjeevmajgotra** [comment]
can someone please provide the correct yaml for example , it is suppose the fail the build for script step but it isnt.
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template

**Comment by jason-ha** [comment]
@sanjeevmajgotra Did you mean to comment on the this Job/Stage reuse examples issue? Maybe you meant to open a new issue? Your URL references a prior section. This issue mostly refers to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&source=docs#job-reuse.

**Comment by juliakm** [comment]
Thanks for the feedback. I'm pushing an update to the docs shortly. 

@sanjeevmajgotra The extends example template is also updated - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template.
