### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by SeanStL** [MicrosoftDocs/azure-devops-docs#6524]
It would be great if there was guidance on how to change existing org-scoped feeds to project-scoped feeds without having to recreate them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops#feedback)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@SeanStL Thank you for the feedback. What you can do to share a package with your org is that you can promote that package to a `view` and set its visibility to `People in my organization`. See [Get started with feed views](./views.md#get-started-with-feed-views) for details.

I added a note to the article and the new version will go live shortly.
