### ISSUE TITLE
Server side Auditability for Git unclear

### ISSUE THREAD

**Issue by mtimperley** [MicrosoftDocs/azure-devops-docs#6579]
In Server section, in the table's row for Auditability, column for Git, what does the statement: "You can identify which user pushed a commit. (Anyone can claim any identity as the author or committer.)" mean? Does this mean that a user with permission to commit, could commit using another user's name? In this case, the commit would appear to have been done by another user? If not, please explain. Can you provide a reference to further documentation that explains this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1dc9a4a-7828-f40f-4cf0-e0b1f5476ff2
* Version Independent ID: 278aed60-558e-3beb-2ed4-c2517c2cd05d
* Content: [Git and TFVC version control - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/comparison-git-tfvc?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/comparison-git-tfvc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/comparison-git-tfvc.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@mtimperley Thank you for the feedback, assigning this to the author for review.

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment]
@mtimperley That's correct! You can use any user name and email you want for a commit. GitHub, for example, is using the email from the commit to identify the user account.
You can find more info here:
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup (section: "Your Identity")
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#about-commit-email-addresses

**Comment by MaximMalygin** [comment]
@msebolt i think we can close the issue, author didn't respond, additional documents links were provided by Dmitry
