### ISSUE TITLE
Remove TFS Power Tools from current docs

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#6595]
The TFS Power Tools have been deprecated quite some time ago, let's remove them from the service docs.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6734489-29e0-48c7-20b7-329174a65346
* Version Independent ID: efc8ff4b-e0ed-0c81-ad8e-35c5e0637ed3
* Content: [What is the best tool to add, update, or link user stories, bugs, issues, and other work items? - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/best-tool-add-update-link-work-items?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/best-tool-add-update-link-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/best-tool-add-update-link-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @thomps23
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@NenoLoje Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@NenoLoje - Thank you for the suggestion. I'm updating the article to version the section to TFS 2015 and earlier. I'll also look at versioning it's mention in other articles. Thanks.
