### ISSUE TITLE
No examples or documentation on how to use type casting

### ISSUE THREAD

**Issue by GenesisCoast** [MicrosoftDocs/azure-devops-docs#6616]
The documentation mentions that type casting can be used alongside functions, however it doesn't actually specify any examples or the format in which to perform the type casting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@GenesisCoast Thank you for the feedback, assigning this to the author for review.

**Comment by Croydon** [comment]
In our template parameters we have numerical values like `10.0` which need to be mapped later on to environment variables.

The template parameter expression is implicitly casting this to `10` causing our build to fail.

How can I prevent implicit casting OR how can I explicit cast it (again) to a float?

**Comment by jdiekhoff** [comment]
Any update on this? Still see no examples on how to perform type casting.

**Comment by juliakm** [comment]
@GenesisCoast We apologize for the confusion on this. All variables are strings. As a result, when you use a variable, it will be output as a string. The good news is that you can now use typed parameters if you do not want to use strings. We're working on updating the docs to make this clearer. Here's more information on [using parameters in pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops).

**Comment by GenesisCoast** [comment]
@juliakm great thankyou. What about type casting with parameters? As not all parameters are strings. 

Also, is there any way to get the type of a parameter? E.g. `${{ parameter.MyParameter.GetType() }}`

**Comment by brandonh-msft** [comment]
I, too, am confused here. Docs say you can convert a string to a boolean, but no indication as to _how_ to do this. E.g. if I have a pipeline var that I set to `True`, `1`, or `true` how do I get `eq(variable('foo'), true)` to work?

**Comment by Crono1981** [comment]
> @juliakm great thankyou. What about type casting with parameters? As not all parameters are strings.

Can anyone answer this? I'm struggling with this as well.

**Comment by sit-md** [comment]
Why had this ticket been closed without any comment? The documentation still hasn't been updated in this regard.

**Comment by brandonh-msft** [comment]
It was closed with an internal PR that added [this chunk](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#type-casting)

**Comment by sit-md** [comment]
@brandonh-msft Tanks for the clarification. Is there any way to return a type different than string though? Yesterday I wanted to pass the result of an eq() expression to a bool parameter in a PowerShell script and failed miserably. I couldn't figure out how to do this conversion and ended up evaluating the environment variable in the script instead of passing in the actual value as parameter from the YAML part.

**Comment by brandonh-msft** [comment]
Sorry not sure. But I think it's a separate question to ask to maybe get more/different docs on the matter - if appropriate.
