### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChrisColeTech** [MicrosoftDocs/azure-devops-docs#6628]
This does not work on VSTS repos, or *.visualstudio.com repos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?tabs=visual-studio&view=azure-devops)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/clone.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ChrisColeTech Thank you again for the feedback.

Please refer to the process from https://github.com/MicrosoftDocs/vsts-docs/issues/6627 to resolve this issue also.

**Comment by msebolt** [comment]
Closing issue now.

**Comment by ChrisColeTech** [comment]
There is no 'Clone' button on VSTS repos' so step 2 fails. And you can't use GIT command, because it says "fatal error". Thanks for the reply.

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by vtbassmatt** [comment]
If this is the same as #6627, then it's because the screenshot is of a TFVC repo, not a Git repo. Only Git repos have a clone button.
