### ISSUE TITLE
Manually import a repo should include git-lfs info

### ISSUE THREAD

**Issue by rhughesjr** [MicrosoftDocs/azure-devops-docs#664]
As VSTS natively supports Git-LFS, the import section should include the necessary commands for that. 

Namely:
` git lfs fetch origin --all`
and
`git lfs push --all https://contoso-ltd.visualstudio.com/MyFirstProject/_git/new-contoso-repo`

Or, at least include a FAQ about that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your team project](https://docs.microsoft.com/en-us/vsts/git/import-git-repository?view=vsts#feedback)
* Content Source: [docs/git/import-git-repository.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/import-git-repository.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rhughesjr Do you mean in the manual import steps section? Good catch, I will get that added.

**Comment by suravi-afroz** [comment]
git clone https://<<username>>:<<password>>@<<remaining clone Url>>

**Comment by jjpepper** [comment]
@steved0x, is this going to happen?  Can I rely on this working?
