### ISSUE TITLE
Project scoped feed should be part of the ToC

### ISSUE THREAD

**Issue by johnterickson** [MicrosoftDocs/azure-devops-docs#6647]
Perhaps under "Concepts"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by magleaso** [comment]
I think it should go under Artifact Feeds, but I'll leave it up to the discretion of the doc writers in the end
