### ISSUE TITLE
There is no documentation about how to develop custom flaky tests detection methods

### ISSUE THREAD

**Issue by ligurio** [MicrosoftDocs/azure-devops-docs#6700]
Article in [Azure documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops) describes custom flaky tests detection methods:

> Detection - Auto detection of flaky test with rerun or extensibility to plug in your own custom detection method

 There is a [similar question](https://developercommunity.visualstudio.com/content/problem/722029/how-to-implement-custom-flaky-test-detection-in-az.html) without answer on forum. But there are no details about developing such custom methods. Please enhance documentation or share information here.

**Comment by msebolt** [comment]
@ligurio  Thank you for the feedback, assigning this to the author for review.

**Comment by KathrynEE** [comment]
@ligurio - The documentation to support custom detection relies on REST APIs which hadn't been completed prior to the publishing of this article. Since then, they've been published, https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/add?view=azure-devops-rest-5.1, and the product team is working on updating the article with an example.

**Comment by yunsong0922** [comment]
@KathrynEE Do you have the simple example before the product team updated the article? We are investigating to use it.

**Comment by KathrynEE** [comment]
Tracking this issue with Bug 1739319: Missing content on how to use custom detection to manage flaky tests.

**Comment by upadhyayap** [comment]
custom detection section in [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops) article has been updated to point to the rest api's which needs to be used to query the flaky data and then post it back to Azure Devops.

**Comment by upadhyayap** [comment]
Custom detection is all about bringing your own detection mechanism and then using Azure Devops [rest api's](https://docs.microsoft.com/en-us/rest/api/azure/devops/testresults/result%20meta%20data?view=azure-devops-rest-6.1) to query and mark/unmark flaky test.

**Comment by KathrynEE** [comment]
@ligurio, @yunsong0922 - The article has been updated to point to the REST API which you need to use to implement custom detection to query the flaky data and then post it back to Azure Devops. If you need more information, please reopen this issue and be as specific as you can as to what information is missing.
