### ISSUE TITLE
Custom detection documentation

### ISSUE THREAD

**Issue by buckleyGI** [MicrosoftDocs/azure-devops-docs#6708]
The documentation states flaky test management supports system and custom detection.
How do we implement custom detection? I can't find any documentation on how to proceed.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dfb3bf-8cce-7ad8-b2c6-40d6c2b9d441
* Version Independent ID: 53e2d39d-6808-70d5-9c26-bc4c5bb109e3
* Content: [Manage flaky tests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops)
* Content Source: [docs/pipelines/test/flaky-test-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/flaky-test-management.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@buckleyGI Thank you for the feedback, assigning this to the author for review.

**Comment by Jon889** [comment]
Is there an update on this?

**Comment by Jon889** [comment]
@msebolt @KathrynEE Can you help with this?

**Comment by KathrynEE** [comment]
@Jon889, @buckleyGI - I've reached out to the product manager for this feature to address the lack of documentation around custom detection. I will add a user story to the backlog to continue to follow up.

**Comment by Jon889** [comment]
Thanks!

**Comment by buckleyGI** [comment]
Looking forward to levering this

**Comment by KathrynEE** [comment]
@Jon889, @buckleyGI - FYI, the documentation to support custom detection relies on REST APIs which hadn't been completed prior to the publishing of this article. SInce then, they've been published, https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/add?view=azure-devops-rest-5.1, and the product team is working on updating the article with an example.

**Comment by Jon889** [comment]
Thanks! But last since last week I’ve been publishing the test results with reruns as TestSubResults and they haven’t been picked up as flaky.

**Comment by KathrynEE** [comment]
Tracking this issue with Bug 1739319: Missing content on how to use custom detection to manage flaky tests.

**Comment by KathrynEE** [comment]
@Jon889, @buckleyGI - - The article has been updated to point to the REST API which you need to use to implement custom detection to query the flaky data and then post it back to Azure Devops. If you need more information, please reopen this issue and be as specific as you can as to what information is missing.
