### ISSUE TITLE
Worth calling out that doing this will mean publishing and downloading artifacts

### ISSUE THREAD

**Issue by lukepuplett** [MicrosoftDocs/azure-devops-docs#6710]
Link to example bottom of page.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by lukepuplett** [comment]
Also worth adding `dependsOn` to examples as, IMO, its likely readers of this page will have their other job doing their build, so they're likely to be unsuccessful on their first go with this.

**Comment by msebolt** [comment]
@lukepuplett Thank you for the feedback, assigning this to the author for review.

**Comment by lukepuplett** [comment]
In fact, I've now spotted it automatically added a download step before Checkout. I just haven't been able to work out which predefined variable addresses the folder where it put, only 3 days spent on it so far, no problem...

**Comment by lukepuplett** [comment]
It's ($Pipeline.Workspace)

Finally, I can move onto tackling the next error.
