### ISSUE TITLE
task.setvariable - IsOutput docs

### ISSUE THREAD

**Issue by Materia-xx** [MicrosoftDocs/azure-devops-docs#6724]
task.setvariable looks like it's missing docs about the IsOutput Property.
Info can be found here if needed: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash&source=docs#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@Materia-xx Thank you for the feedback, assigning this to the author for review.

**Comment by IanKemp** [comment]
Is the author dead?

**Comment by msebolt** [comment]
This issue was similarly posted under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9311.

The documentation has been updated and is now pending review.
