### ISSUE TITLE
argument names and parameter names agreement

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#6740]
The names of the input arguments in the YAML snippet do not match the argument names in the argument column in the Argument section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Argument column is not meant to be YAML input names. You can use the task assistant to get the YAML snippet. 

![image](https://user-images.githubusercontent.com/1370480/71265407-29073600-236c-11ea-934d-2f9a66eeab68.png)

![image](https://user-images.githubusercontent.com/1370480/71265429-36242500-236c-11ea-8e59-e45211558828.png)

![image](https://user-images.githubusercontent.com/1370480/71265468-4c31e580-236c-11ea-91ea-d994d89e7bf4.png)

**Comment by HughDevlin** [comment]
The actual parameter names do not match the doc, and this is something we should all just get used to? Really?

**Comment by HughDevlin** [comment]
please re-open and address

**Comment by HughDevlin** [comment]
The task assistant offers help with exactly FOUR (4) parameters. This task has many more than four (4) parameters. This closure is unacceptable.

**Comment by ninallam** [comment]
@HughDevlin Once you select the destination type (Blob/VM)  in the task assistant, the additional fields that are applicable to that destination type appear. 

**Azure Blob**
![image](https://user-images.githubusercontent.com/50437471/76825662-91b56000-6840-11ea-8bb6-007d2cbbf25e.png)


**Azure VMs**
![image](https://user-images.githubusercontent.com/50437471/76825607-6fbbdd80-6840-11ea-814b-3bb9e0d5dcc9.png)

**Comment by HughDevlin** [comment]
is it Microsoft's position, that since the arguments to this task (all pipeline tasks?) are documented elsewhere (in the task assistant), that Microsoft's documentation on the web (this page) need not be maintained?

**Comment by stewartadam** [comment]
It's silly to expect everyone to have to use the task assistant just to put together the task.

The documentation here is on the task's **yaml configuration** and should document the **yaml configuration**. If I wanted help using the task assistant I'd just hover over the "(i)" buttons built-in to the UI.

**Comment by stewartadam** [comment]
It's silly to expect everyone to have to use the task assistant just to put together the task... The documentation here demonstrates the task's yaml configuration and so should document the yaml configuration syntax.

Why have this page showing the config options if they're left undocumented?

For help with the task assistant, the built-in "(i)" buttons pop-out with relevant help text. This page shouldn't need to document the use of the assistant.

**Comment by ninallam** [comment]
We are working on getting all the task docs updated to have the yaml arguments as well. Thanks for your feedback.
