### ISSUE TITLE
Pipeline triggers example give "Unable to resolve definition"

### ISSUE THREAD

**Issue by adamsj-oci** [MicrosoftDocs/azure-devops-docs#6742]
Using the example given at this link

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pipeline-triggers-1

My build results in an "Unable to resolve definition..." for the name of the pipeline in the same organization. What is the difference between the pipeline and the source names because the documentation seems to indicate that the pipeline name is the source name. Where should each of those names come from?

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
