### ISSUE TITLE
Explain project-scoped feed authentication

### ISSUE THREAD

**Issue by Korijn** [MicrosoftDocs/azure-devops-docs#6746]
The task does support project-scoped feeds but it doesn't explain how. Support was merged into the task in https://github.com/microsoft/azure-pipelines-tasks/pull/10657 but the docs were not updated. Looking at the changes in that PR it seems that you can prefix feednames with the project name and a forward slash, is that correct? Like this:

```
- task: PipAuthenticate@1
  inputs:
    artifactFeeds: projectName/feedName
```

I _also_ needed to manually add the "**project-scoped** build service" user to the feed permissions as a Reader to resolve this error:

```
https://pkgs.dev.azure.com:443 "GET /<organization>/<project>/_packaging/<feed>/pypi/simple/pip/ HTTP/1.1" 403 367
Status code 403 not in (200, 203, 300, 301)
Could not fetch URL https://build:****@pkgs.dev.azure.com/<organization>/<project>/_packaging/<feed>/pypi/simple/pip/: 403 Client Error: Forbidden - User '<guid>' lacks permission to complete this action. You need to have 'ReadPackages'. (DevOps Activity ID: DA44B94C-8794-4153-A26C-A2D440EFBF82) for url: https://pkgs.dev.azure.com/<organization>/<project>/_packaging/<feed>/pypi/simple/pip/ - skipping
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77227c6d-c042-d4b9-9801-ecb3547e1c33
* Version Independent ID: af8571a9-604a-6cf7-43ea-a714c42b95e7
* Content: [Python Pip Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/pip-authenticate?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/tasks/package/pip-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/pip-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by Korijn** [comment]
I can see how you would label this as doc enhancement but I think you should also update the default permissions for new project scoped feeds. They don't work out of the box.

**Comment by ramiMSFT** [comment]
@Korijn Apologizes for the delayed response and thank you for your feedback. The issue has been addressed and yes, you are correct: project scoped feeds must use the following syntax `projectName/feedName` and add permissions to the build service.
