### ISSUE TITLE
Private Repos Require GOPRIVATE

### ISSUE THREAD

**Issue by ScoGroMSFT** [MicrosoftDocs/azure-devops-docs#6784]
Referencing Go code in private repos will return HTTP/410 Gone due to the attempted lookup of the ADO code location using sum.golang.org/lookup that occurs by default. 

Setting the environment variable GOPRIVATE=dev.azure.com locally before building or running go get will suppress this lookup attempt and is needed for pulling code from private repos. We need to include this in the docs.

Here's a [doc](https://medium.com/mabar/today-i-learned-fix-go-get-private-repository-return-error-reading-sum-golang-org-lookup-93058a058dd8) that discusses this in the context private repos in general:

**Comment by WilliamAntonRohm** [comment]
@ScoGroMSFT -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing.

**Comment by ScoGroMSFT** [comment]
Looks like the context of the doc got lost when I jumped over to GitHub. This is in regard to [Using Go Get with ADO Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)

**Comment by WilliamAntonRohm** [comment]
@ScoGroMSFT -- thank you for clarifying.  Apologies for the delay.

@PRMerger18 -- please look into this issue.

**Comment by movergan** [comment]
+1

**Comment by WilliamAntonRohm** [comment]
@vtbassmatt -- Matt, please look into this issue.

**Comment by steved0x** [comment]
#reassign steved0x
