### ISSUE TITLE
You need to update this page

### ISSUE THREAD

**Issue by robertlagrant** [MicrosoftDocs/azure-devops-docs#6786]
CircleCI do a lot more now. Also, some of these criteria are pretty cynical!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01e26467-204d-f5b1-d735-1f57efd55656
* Version Independent ID: 4dfb3abc-b1d5-9d1b-cc4e-96f172381aaa
* Content: [Azure Pipelines vs CircleCI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/compare/azure-pipelines-vs-circleci)
* Content Source: [docs/compare/Azure-Pipelines-vs-CircleCI.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/compare/Azure-Pipelines-vs-CircleCI.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **davemcki**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
