### ISSUE TITLE
Document Working with Project-Scoped Artifact Feeds

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/azure-devops-docs#6793]
The current documentation does not appear to work with project-scoped artifact feeds. When attempting to publish to some feed specified by `vstsFeedPublish`, the operation fails with an error saying the indicated feed does not exist.

I was able to work around this by adding the project name as part of `vstsFeedPublish`.

```
# instead of this:
vstsFeedPublish: MyFeed

# do this:
vstsFeedPublish: MyProject/MyFeed
```

I feel that this behavior should be called out in the documentation for the `vstsFeedPublish` parameter, especially since project-scoped feeds are now the default. I'm also guessing that some other parameters to this task might also need their documentation updated similarly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@reynoldsbd Thank you for the feedback, assigning this to the author for review.

**Comment by jwikman** [comment]
Please also update the page https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml 

Above information was quite hard to find...

While you're updating both pages, take the chance to link them to each other.

**Comment by jaapcrezee** [comment]
```
# instead of this:
vstsFeedPublish: MyFeed

# do this:
vstsFeedPublish: MyProject/MyFeed
```
This worked for me after spending more than 60 minutes to debug this. MS please take more care about correct documentation....

**Comment by ramiMSFT** [comment]
@reynoldsbd  Thank you for your feedback. The new version will go live shortly.
