### ISSUE TITLE
What happens to the predefined Release Variables when we migrate to a multi-stage yaml pipeline?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#6795]
I suspect the answer is that they don't get populated.  If that is the case, it would be good for this documentation to state that and perhaps provide some advice on what they may map to so we can refactor our code as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by MarkIannucci** [comment]
In my experience, it seems that they do not get populated, and DevOps doesn't warn you about using deprecated variables in the release, so migrating my scripts to the multi-stage pipelines has been pretty painful.

**Comment by vtbassmatt** [comment]
This is correct, none of the `Release.*` variables are populated when you switch to YAML CD pipelines.
