### ISSUE TITLE
The Q & A mentions a maintenance window, but there's nothing about that in the actual documentation

### ISSUE THREAD

**Issue by moswald** [MicrosoftDocs/azure-devops-docs#6813]
I came to this page looking for the instructions on how to enable the maintenance job, but there's nothing explaining the option even exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by nguyenlamlll** [comment]
This page seems to miss the maintenance job part.
Anyways, here is how you enable the maintenance job for an agent pool.

1. From the root of your Azure DevOps website (https://dev.azure.com/{YOUR_COMPANY}), click on "Organization Settings" on the bottom left.
2. Select "Agent Pools" under the "Pipelines" section.
3. Select the pool that you want to enable the maintenance job.
4. On the pool's website, navigate to "Settings" tab. There is a section called "Maintenance job" and a switch to enable the feature. See the picture below.

![image](https://user-images.githubusercontent.com/20963684/71819817-bdd59780-30bf-11ea-8a9d-3a9e4290245f.png)

_Please note that if you navigate to the "Agent Pools" settings under a project (clicking on "Project settings"), you **might not see** the "Settings" tab of the agent pool._

Hope this helps you.

**Comment by msebolt** [comment]
@moswald  Thank you for the feedback, assigning this to the author for review.

Please comment if the solution from @nguyenlamlll solves the issue.

**Comment by moswald** [comment]
Yes, @nguyenlamlll is correct. However, we should have more documentation on what the maintenance job does, and why it should (or shouldn't) be enabled.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by moswald** [comment]
@juliakm Let's re-open this one. And when it comes time to update the docs, I'm available in Slack to chat about what needs to be done.
