### ISSUE TITLE
"?api-version=5.0-preview.1" vs. "?api-preview=5.0-preview.1"

### ISSUE THREAD

**Issue by SeanCLeavitt** [MicrosoftDocs/azure-devops-docs#6825]
I see both query strings "api-**version**" and "api-**preview**" mentioned in the recommended base URL retrieval techniques above - which is the singular recommendation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28256c7-e0d2-fc25-289e-55c64e23f27c
* Version Independent ID: c93daa34-b846-728f-a570-fa7764ab133b
* Content: [Working with URLs in extensions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/work-with-urls?view=azure-devops&tabs=http#feedback)
* Content Source: [docs/extend/develop/work-with-urls.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/work-with-urls.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@SeanCLeavitt Thank you for the question and feedback.

I would avoid the use of `api-preview` in any sort of production-type setting and recommend removing it from the examples to avoid confusion.

Assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @SeanCLeavitt, Thanks for your feedback. I've updated the article to reflect API-version, as "preview" isn't applicable. Thank you!
