### ISSUE TITLE
Missing Extension Points for new Test Plans Page

### ISSUE THREAD

**Issue by JanSera** [MicrosoftDocs/azure-devops-docs#6833]
Can we get information about extension points available on new Test Plans Page? None of Test Plans extension points seems to work on new page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@JanSera Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @JanSera, Please accept my apology for losing sight of this issue. There is a more recent issue for this article, however, which I've added your feedback to so we can be sure it's properly addressed. I'm closing this issue, so please reference [this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7728) and you can @mention me if you have any further questions or concerns.  
Thank you!
