### ISSUE TITLE
Is the Publisher namespace for TFSSecurity.exe still valid?

### ISSUE THREAD

**Issue by Debbus72** [MicrosoftDocs/azure-devops-docs#6838]
Creating the group succeeded in our Azure DevOps instance.
However, assigning the security (example 2, first commands) failed with the message:
`The security namespace Publisher does not exist.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d9ba03b-3328-d891-2d8f-f60eb4bb65e0
* Version Independent ID: 4fcd46a3-8f4a-8c0e-a1f9-8112389b15b9
* Content: [Manage extension permissions - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/how-to/grant-permissions?view=tfs-2015#feedback)
* Content Source: [docs/marketplace/how-to/grant-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/how-to/grant-permissions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@Debbus72 Thank you for the feedback, assigning this to the author for further review.

According to the [current documentation](https://docs.microsoft.com/azure/devops/server/command-line/tfssecurity-cmd?view=azure-devops-2019#permission-namespaces-and-actions) this namespace is still supported.

@chcomley @aaronhallberg

**Comment by chcomley** [comment]
Hi @Debbus72, Better late than never, here's our updated guidance, which I'm sure you're well-aware of now. Thank you for your feedback! 
The TFSSecurity command-line tool has been deprecated for use with Azure DevOps Services. While TFSSecurity may work for some Azure DevOps Services scenarios, it is not supported. The recommended method to make changes to security groups and permissions for Azure DevOps Services is either using the [Web portal ](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-users-team-project?view=azure-devops&tabs=preview-page) or the [Security REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-6.0).
