### ISSUE TITLE
show windows environment setup

### ISSUE THREAD

**Issue by KnicKnic** [MicrosoftDocs/azure-devops-docs#6851]
Setting up environment includes this quote
" Note: this script runs in bash on Linux and macOS agents, but must be modified for Windows."

It is very unclear to know what must be modified for windows. Documentation should be provided.

Also it is confusing is this now replaced by go tool? https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/go-tool?view=azure-devops if so please replace script with go tool reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86b5c3a-d266-e9fe-621e-eb6244199984
* Version Independent ID: 57ca9f4f-ad07-4ab5-3153-9853e6b24797
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/go.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/go.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@KnicKnic Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
I'm trying to track down more information about this one.

**Comment by juliakm** [comment]
The script provides support for older versions of Go, which requires a specific folder structure to operate. The script itself is written for UNIX shells. Because it is written for UNIX shells, it will not won’t work on windows agents. I'll update the docs to clarify this.
