### ISSUE TITLE
Not enough clarity on the direction of a service endpoint

### ISSUE THREAD

**Issue by kelsosharp** [MicrosoftDocs/azure-devops-docs#6853]
In your first sentences, it seems like the endpoint is outgoing, connecting to external services, which is what I thought a service connection was for, after your list of properties, the implication seems to be that its now incoming a way for extensions to acquire information... which is it? Also, the title of this document is Service Endpoints in Azure DevOps, but there is just a few sentences on the actual topic of Service Endpoints, this is a topic on the AZ-400, and should have a lot more depth and not just an example on creating an extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@kelsosharp Thank you for the feedback, assigning this to the author for review.

**Comment by chcomley** [comment]
Hi @kelsosharp, Please accept my apology for losing sight of this issue. There is a more recent issue for this article, however, which I've added your feedback to so we can be sure it's properly addressed. I'm closing this issue, so please reference [this issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7263) and you can @mention me if you have any further questions or concerns.  
We're working on a complete overhaul of this area and are in the beginning phases of that work now.
Thank you!
