### ISSUE TITLE
Automatically check out file from file system on edit?

### ISSUE THREAD

**Issue by MikeCheel** [MicrosoftDocs/azure-devops-docs#6863]
From the article: "It may be also be preferable to you if you do not need to work as part of a team and strongly prefer working with the filesystem in a manner similar to Git."

It is unclear if this means that if I edit or add a file directly in the file system that it will automatically be added or checked out. A few versions of TFS ago, it was said that instead of using the right click context menu to add / check out from the file system (via file explorer) that TFS would do this simply by adding or editing a new file inside the workspace. 

Is this assessment correct? 
How to enable / disable this with Azure Devops? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b16d189-fa47-b490-5186-76bc9acdcacc
* Version Independent ID: f8e87439-67ec-b342-7e2c-8bc162f53574
* Content: [Decide between using a local or a server workspace - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=azure-devops)
* Content Source: [docs/repos/tfvc/decide-between-using-local-server-workspace.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/decide-between-using-local-server-workspace.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@MikeCheel  Thank you for the feedback, assigning this to the author for review.

**Comment by StingyJack** [comment]
@mikecheel server workspaces require the explicit marking of files you wish to change. That can be done in solution explorer, by the code editor for a file that is version controlled in VS, by source control explorer, or by the windows explorer extension (if that's even still available). Local workspaces pickup any changes by those, as well as by anything that "touches" the files on the workspace hard enough. That one apparent benefit that makes TFVC act like Git for detecting changes does come with some of the drawbacks noted above that git does not have (like the >100k file problem, which can be easy to hit if you have a node_modules folder or any decent sized i18n implementation)

**Comment by MaximMalygin** [comment]
@MikeCheel do you need any help here?

**Comment by MikeCheel** [comment]
> @MikeCheel do you need any help here?

I think @StingyJack explained it well enough, thanks!

**Comment by MikeCheel** [comment]
Yes please
