### ISSUE TITLE
hard to understand what I need to do in order to run my build

### ISSUE THREAD

**Issue by ForrestTrepte** [MicrosoftDocs/azure-devops-docs#6868]
Whenever I create a new ADO repository and set it up from a .yml build definition I receive the error `The pipeline is not valid. Could not find a pool with name Default. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

This page has helpful information, but it wasn't immediately clear to me what steps I need to take in order to get my build running. The Authorize Resources button on the summary tab didn't work for me. I ended up going to Project Settings &gt; Settings &gt; General to turn off things that were limiting access and going to Agent Pools &gt; Default &gt; Security to turn on Grant access to all pipelines. I hate to admit it, but I didn't fully understand what I was doing--just changing settings until it worked even if there may be security implications that I didn't consider.

Would it be possible to link that error to more step-by-step instructions so that I don't need to read and understand advanced concepts about Azure DevOps resource security? Alternatively, could this feature be changed so that when I create builds through the Azure DevOps portal those builds work by default--presenting any options needed for security approval as the build definition is created?

Just passing along some feedback about what this feature was like from my perspective as a naive user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ForrestTrepte Thank you for the feedback, assigning this to the author for review.
