### ISSUE TITLE
Why is there a character limit for pull request templates?

### ISSUE THREAD

**Issue by StefanOssendorf** [MicrosoftDocs/azure-devops-docs#6870]
Why is there a limit on how many characters are allowed in a pull request template?

We are using the templates and I added to each of our checklist items links to our wikis. The text is truncated after 4_000 characters. Sounds like a lot but we it'S easily exceeded with a lot of links in the template. We have 24 links in it to point to our guidlines/wiki.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@StefanOssendorf  Thank you for the feedback, we're sorry for the inconvenience.

Assigning this to the author to include a note on these limitations.

As a feature enhancement, please consider engaging the product team by starting a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by StefanOssendorf** [comment]
Thanks for your quick answer. If anyone find this question please vote there: https://developercommunity.visualstudio.com/idea/365708/raise-the-character-limit-for-pull-request-descrip.html
