### ISSUE TITLE
Document consuming project-scoped feed from another project

### ISSUE THREAD

**Issue by trevorreeves** [MicrosoftDocs/azure-devops-docs#6872]
To consume a project scoped feed from another project you need to add the project Build Service account of the consuming project to the project team group of the project that the feed belongs to.

This took a long time to discover via a support request, so it would be valuable to have this included here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@trevorreeves Thank you for the feedback, assigning this to the author for review.

**Comment by ahaleiii** [comment]
I agree that this process adds additional complexity to sharing artifacts across projects in an organization. The documentation says that it recommends all new feeds to be project-scoped and not organization-scoped, but it doesn't say why. I think our organization will continue to create organization-scoped feeds until we have a better understanding of the Azure DevOps team's architecture goals.

New features should have a pit of success, not a wall of complexity. We are going to use whatever is easier.

**Comment by satbai** [comment]
In the docs there's now the following: "When connecting to a private project scoped feed from an Azure DevOps pipeline that is in the same organization but in a different project, the project that the feed is scoped to must allow access to the other project's build service. The build service must also be separately added to the feed permissions, regardless of the scope of the feed.". Should this be enough? Maybe screen shots would help? https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops

**Comment by ramiMSFT** [comment]
@trevorreeves Thank you for your feedback. Note added to the article.

**Comment by ggirard07** [comment]
Related to this, I think this is still not totally clear where to add the consuming project's build service (or reader) as part of the project owning the feed permissions. For now I got it to work by adding the "consuming project's build service" as a member of the "[MyProject]\Readers" group. But is the "[MyProject]\Project Valid Users" group enough?
Documentation could clearly indicate which permissions group is the minimum requirement here.
Multiple people in my company actually went over this article and still missed that point here and continued to use the org scope build service account in the end.
