### ISSUE TITLE
It's unclear what role the feed permissions plays for project-scoped feeds

### ISSUE THREAD

**Issue by trevorreeves** [MicrosoftDocs/azure-devops-docs#6873]
It would be useful to clarify what effect the feed permissions and feed view permissions have for project-scoped feeds.  For organisation-scoped feeds it is clear.  For project-scoped it's not clear what consequence they have, if any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@trevorreeves Thank you for the feedback, assigning this to the author for review.

**Comment by APIWT** [comment]
Hello! Is there any update on this? We are actually wondering if we should be assigning the "Any member of your organization can view the packages in this feed" option or the "Only users you grant access to can view the packages in this feed" option. Our goal is the following:
- Feed should be private to project (the project is also private)
- You can only publish to the feed if you have push access to repositories
- You may download/read from feed in you have read access to the repositories
- You may not view/read/write to the feed if you are an organization member but you have no access to the repositories for the project.

**Comment by ramiMSFT** [comment]
@trevorreeves Thank you for your feedback. Currently all the feeds created through the UI are project-scoped feeds. Projects feeds were made to interact with other public projects. It's worth mentioning that If a user have permission to a specific view, and even if they don't have permission to the feed, they will still be able to access and download packages through that view.
So If you want to completely make your packages private, you must restrict both feeds and views permissions.

I will be adding notes to the docs for clarification.
