### ISSUE TITLE
Add example for configuring TIA_IncludePathFilters 

### ISSUE THREAD

**Issue by josh-degraw** [MicrosoftDocs/azure-devops-docs#6877]
I wanted to tune the test impact analysis in my pipeline, and it took me way longer than I feel it should have to to figure out exactly where to set the `TIA_IncludePathFilters` variable.
Having a simple YAML example would go a long way to help people figure this out faster.

While I'm at it, is there a reason there is no simple, straightforward way to modify this property? I would assume situations such as not wanting to have to run a full build when the README.md file is changed are common enough that it would merit making this property a first-class citizen on the pipeline task.

Lastly, I could be wrong, but it seems like there is a typo where under **Manage Test Impact Analysis behavior** it states that the variable is `TI_IncludePathFilters`, when I believe it should be `TIA_IncludePathFilters`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e098a7-83b4-c389-3d30-21ad3446b76c
* Version Independent ID: cafbcbd5-3321-88cf-eeaf-038d49ec0ada
* Content: [Use Test Impact Analysis - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/test-impact-analysis?view=azure-devops#manage-test-impact-analysis-behavior)
* Content Source: [docs/pipelines/test/test-impact-analysis.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/test-impact-analysis.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@josh-degraw Thank you for the feedback, assigning this to the author for review.

**Comment by qujck** [comment]
Bumping this as I'm unable to find out where I should configure `tia_includepathfilters`. The documentation tells us we need to set it but not where. Anywhere? .runsettings? yml? It's a useless feature if you can't find it!

**Comment by josh-degraw** [comment]
@qujck It's been a while since I dealt with this, but if I remember correctly, I think I just put it at the top of the `azure-pipelines.yml` file.

**Comment by Polad10** [comment]
+1

**Comment by joshdenable** [comment]
Also bumping this as I've unsuccessfully attempted to use `TIA_IncludePathFilters` today. Following on from an above suggestion I included this at the top of my .yaml build file, but the build failed with the following message:

`Unexpected value 'tia_includepathfilters'`

I echo the comment that a simple YAML example would be useful.

**Comment by PBoraMSFT** [comment]
Adding @shashban to help.

**Comment by RamiSh** [comment]
+1 An example of this would be appreciated

**Comment by downflow311** [comment]
So, where do we set TIA_IncludePathFilters? In the project file of the test project?

**Comment by MarcinFrankowski** [comment]
If someone is still looking for a hint, here's an example of usage that works in my case
```
      - job: Build
        variables:
          - template: templates/variables.yml
          - name: TIA_IncludePathFilters
            value: "!**\*.csproj"
        steps:
          - template: templates/build.yml
```

**Comment by WilliamAntonRohm** [comment]
#reassign:@PBoraMSFT
