### ISSUE TITLE
Bundles are missing

### ISSUE THREAD

**Issue by carstenhag** [MicrosoftDocs/azure-devops-docs#6885]
There is no explanation on how to build, sign and release app bundles to the Play Store. Could you please add this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 454383d9-78ce-6203-2926-3449842d2f9f
* Version Independent ID: 947f872e-95b9-1691-acf0-e1a3f73b1e75
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/android.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by carstenhag** [comment]
Also see https://github.com/microsoft/google-play-vsts-extension/issues/155 please :)

**Comment by msebolt** [comment]
@carstenhag Thank you for the feedback, assigning this to the author for review.

In the meantime, please refer to [publish to Google Play store](https://docs.microsoft.com/appcenter/distribution/stores/googleplay) or [this post](https://stackoverflow.com/questions/58618500/azure-devops-projects-directly-publish-to-google-play-console) for further options.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by carstenhag** [comment]
Still no mention of bundles. Would be cool if the bot would first label it as stale, and then close it after some days, not just directly.

**Comment by mijacobs** [comment]
@juliakm Can you take a look?

**Comment by juliakm** [comment]
@carstenhag Sorry for the delay on this. I'm working on adding an example now. There's also this [blog post](https://devblogs.microsoft.com/xamarin/android-app-bundles-azure-devops/) that you may find helpful.

**Comment by carstenhag** [comment]
Hey Julia, no worries :). We had pretty much done the same thing as that Blog post says.
