### ISSUE TITLE
nothing about filtering groups

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#6899]
there's nothing in these docs about how filtering groups work and how to construct an and over or type setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeeb3695-9131-3598-c00b-0ae63fa6f33b
* Version Independent ID: 203d91ee-3831-0149-19e2-118de41ca5ae
* Content: [Get started with notifications in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/about-notifications?view=azure-devops#feedback)
* Content Source: [docs/notifications/about-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/about-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@drdamour  Thank you for the feedback, assigning this to the author for review.

In the meantime, please refer to **Notifications** and **Subscriptions** general description on the [Events and notifications](https://docs.microsoft.com/azure/devops/notifications/concepts-events-and-notifications) page.

**Comment by drdamour** [comment]
Nothing on that page about filtering

**Comment by chcomley** [comment]
Hi @drdamour, I'm going to assume that you may have moved on at this point, but wanted to leave a link to more information, just in case! Please reference the following article, [Manage notifications for a team or group](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops) and you can see how to [Follow a user story, bug, issue, or other work item or pull request](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops). Thank you and please @mention me if you have any further questions.

**Comment by drdamour** [comment]
@chcomley no havent moved on. Neither of those links describe how filter groups function from what i can tell. So still open issue

**Comment by chcomley** [comment]
@drdamour, I've just followed up with the PM, so I hope to be in touch shortly. Thanks for your patience. Hope you're having a great day.

**Comment by chcomley** [comment]
Hi @drdamour, Can you please further clarify what you're trying to accomplish? Thank you.

**Comment by drdamour** [comment]
@chcomley in the UX there's this option about grouping filters..i assume it has something to do with and's and ors, but i can't figure it out
![image](https://user-images.githubusercontent.com/1514496/104505819-ba61cf80-55a1-11eb-89f3-c0d201b38e17.png)
went to read the docs on it...but nothing there

**Comment by chcomley** [comment]
Hi @drdamour, This works the same as a query. You should be able to find the information you need here: https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops#group-clauses.

**Comment by drdamour** [comment]
indeed...seems like this page https://docs.microsoft.com/en-us/azure/devops/notifications/about-notifications?view=azure-devops or maybe more appropriately https://docs.microsoft.com/en-us/azure/devops/notifications/concepts-events-and-notifications?view=azure-devops#notifications should have "learn more about filtering" links in them to the page you just linked me.

thanks!

**Comment by chcomley** [comment]
@drdamour , I'll update the article with links. Thank you for your feedback, much appreciated.
