### ISSUE TITLE
Documentation incorrect?

### ISSUE THREAD

**Issue by kbrady-vibrato** [MicrosoftDocs/azure-devops-docs#6901]
Hi,

I followed the documentation and copied the example pretty much verbatim - it doesnt work when the cron expression is in double quotes, but does when in single quotes - I found this out from Damien's post here https://developercommunity.visualstudio.com/content/problem/607414/scheduled-trigger-for-yaml-pipeline-disabled.html.

Is this a bug, or should the documentation be updated to reflect this?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778de92d-261d-5ce4-1d8d-871ca3fa555c
* Version Independent ID: 3a377cf4-175c-3cda-7927-9131ae9e9bbf
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kbrady-vibrato Thank you for the feedback, we're sorry for any issues with the examples.

Assigning this to the author for review.

**Comment by abatishchev** [comment]
@steved0x ping on this, please.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by abatishchev** [comment]
@msebolt, @steved0x ping on this, please
