### ISSUE TITLE
What will happen when cache consumes all allocated organization storage

### ISSUE THREAD

**Issue by AElharouny** [MicrosoftDocs/azure-devops-docs#6902]
This might be an edge case question but I think it's important form product team to have an answer ready for that.
Since currently no maximum cache size per pipeline and no way to clean up cache.  What will happen in case of many pipelines in an organization uses that feature to store many files till  organization run out of reserved space or maximum quota?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@AElharouny Thank you for your feedback. Caches are scoped to a project, pipeline, and branch. A pipeline can have one or more caching task(s) and there is no limit on the caching storage capacity at the moment.
