### ISSUE TITLE
Screenshots Please

### ISSUE THREAD

**Issue by VRMartin** [MicrosoftDocs/azure-devops-docs#6911]
Subject is helpful, but screenshots would make it so much more helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c5d73c-b126-7271-5483-b58dbcf43476
* Version Independent ID: a78f6ee3-677e-f28f-ca9b-4d9bfddf483d
* Content: [Use TFVC and Git repos in the same project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/team-projects?view=azure-devops#feedback)
* Content Source: [docs/repos/git/team-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/team-projects.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@VRMartin Thank you for the feedback, assigning this to the author for review.
