### ISSUE TITLE
Scenario 4 and mail-enabled Azure AD group

### ISSUE THREAD

**Issue by hintbw** [MicrosoftDocs/azure-devops-docs#6925]
Considering a mail-enabled Azure AD group only returns results such as these - https://techcommunity.microsoft.com/t5/azure-active-directory/azure-ad-security-group-can-i-mail-enable-the-group/m-p/134353 - is it possible that you could link to documentation for where (or how) mail enabled Azure AD groups can be created?

Working with our Azure AD global administrators (when my team is the ADO administrator) means I'll likely need to help inform them on how to do this and it would be awesome to have some additional documentation or linking to help us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1e33b8c-093d-7e81-ea78-e8ab1d3babd6
* Version Independent ID: f2e2e255-bf18-bd5f-1089-fba5d3f88814
* Content: [How notification email recipients are determined - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/concepts-email-recipients?view=azure-devops#recipients-for-custom-team-and-group-subscriptions)
* Content Source: [docs/notifications/concepts-email-recipients.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/concepts-email-recipients.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@hintbw Thank you for the feedback, assigning this to the author for review.

From the note in the [AD documentation](https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-manage-groups) you can only manage mail-enabled security groups using [Office 365](https://docs.microsoft.com/office365/admin/create-groups/compare-groups?view=o365-worldwide#mail-enabled-security-groups) or [Exchange](https://docs.microsoft.com/exchange/recipients-in-exchange-online/manage-mail-enabled-security-groups), though check out this [post](https://stackoverflow.com/questions/25747961/creating-mail-enabled-security-group-in-azure-active-directory-or-exchange-onlin) on managing the groups and this [open item](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/31247662-enable-support-for-dynamic-mail-enabled-security-g) on the currently missing functionality.
