### ISSUE TITLE
"The following example discards changeset 137 as a candidate for merging into branch2" gives wrong exampl

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/azure-devops-docs#6943]
Example code:

c:\projects&gt;tf merge /discard /version:C137 branch1 branch2 /recursive

This should be:

c:\projects&gt;tf merge /discard /version:C137~C137 branch1 branch2 /recursive

The original example seems to discard everything up to C137.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2a034e-46b4-0c59-9cc1-b34a199383c9
* Version Independent ID: 7022c4b2-7011-5cdc-1b57-f2ee3b594bdc
* Content: [Merge Command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/merge-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/merge-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/merge-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@lvanvugt Thank you for the feedback and provided solution.

Assigning this to the author for further review.

**Comment by IlyaChistov** [comment]
#reassign @IlyaChistov

**Comment by MaximMalygin** [comment]
@msebolt could you please close it, it was fixed in PR
