### ISSUE TITLE
There is limit for the automerge

### ISSUE THREAD

**Issue by ashamrai** [MicrosoftDocs/azure-devops-docs#6962]
When you are trying to merge branches that contain big files, you can catch the following error:
TF401022: By policy, the Git object '&lt;GUID&gt;' is too large to materialize into memory. Its size, &lt;file_size&gt;, exceeds the threshold of 104857600 bytes.

However, it`s not documented here.

Additional info: https://github.com/libgit2/libgit2sharp/issues/1486

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e60bfd-765f-81ad-312d-f46ef9a66ddc
* Version Independent ID: c7ea62ca-1ba4-9a63-30d5-4788f4dce0c4
* Content: [Git limits - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/limits?view=azure-devops&source=docs#feedback)
* Content Source: [docs/repos/git/limits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/limits.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by ashamrai** [comment]
This is the error in our pull request
![2020-01-16_19-00-37](https://user-images.githubusercontent.com/18112719/72546552-9c309900-3893-11ea-875b-310da64e8708.png)

**Comment by ezequiel2611** [comment]
Any update on this?

**Comment by DylMatRees** [comment]
Any update on this?
