### ISSUE TITLE
vstsFeedPublish described incorrectly

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#6965]
this doc describes vstsFeedPublish as the name of the feed, but the task requires the guid of the feed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by ramiMSFT** [comment]
@drdamour Thank you for your feedback. The new version will go live shortly.
