### ISSUE TITLE
How are output variables handled from a task group?

### ISSUE THREAD

**Issue by t-l-k** [MicrosoftDocs/azure-devops-docs#6983]
I created a task group, and none of the tasks within it appear to have output variable support. This is a problem, I can't set an output reference name.

When the task group is added to a build pipeline, the task group does appear to support output variables. 

But how would the tasks within the task group, output values into the output variables of the task group?

I can't see this documented here. I'm left to experiment to find the answer. The documentation may be trying to imply that I can define output variables as "predefined variables"? 

&gt; All the '$(vars)' from the underlying tasks, excluding the predefined variables, will surface as the mandatory parameters for the newly created task group.
&gt;
&gt; For example, let's say you have a task input $(foobar), which you don't intend to parameterize. However, when you create a task group, the task input is converted into task group parameter 'foobar'. Now, you can provide the default value for the task group parameter 'foobar' as $(foobar). This ensures that at runtime, the expanded task gets the same input it's intended to.

Behaviours concerning output variables should be made explicitly clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by carlosgit2016** [comment]
I've the same problem.

I have  several tasks that use output variables, so when i create a task group the output variables just disappear.

**Comment by t-l-k** [comment]
I'm going to be picking up a lot of pipelines work in the next couple of weeks and having some guidance on this issue could save me a lot of time. 

Is it even possible and just not documented? 

If it's not possible, I better warm up my clipboard ... theres gonna be a lot of copy pasting between pipelines.

**Comment by t-l-k** [comment]
Yep just hit this issue again. Any updates?

**Comment by t-l-k** [comment]
Okay well through sheer will and determination I have figured it out. 

It appears as though each task in the task group can be referenced by some kind of task name + ordinal combination - e.g. if the 2nd task in the task group at the beginning of a pipeline job is a "PowerShell" task, then its outputs (produced by the `##vso` set variable syntax) can be later referenced using the syntax:

```
$(Powershell1.VariableName)
```

So yeah, that's super clear!!  I managed to approximately work this out by dumping out `gci env:` in a Powershell script.

It was also kind of eluded to in a weird way from this document, which is equally as clear:

https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md

**Comment by t-l-k** [comment]
@KJaunay thanks, yes I too had observed this behaviour. Interestingly, since I first recorded this issue, I have on further observation, the way classic pipelines work is now alot more alike how the `yaml` pipelines work, in that variables written with the syntax e.g. 

```
##vso[task.setvariable variable=foo;isSecret=false;]the_value
```

Are now available for later tasks using the syntax `$(foo)` in a task input field ... _I swear when I originally created this ticket, that this was not the case for classic pipelines using task groups!_

When an output value is written such that `isOutput=true` is specified:

```
##vso[task.setvariable variable=foo;isSecret=false;isOutput=true;]the_value
```

Then yes, the oddities of referencing this value using e.g. `POWERSHELL1_VARIABLENAME` style prefix applies. 

But I don't care about that anymore, as it now appears to behave just like how `yaml` pipelines behave, e.g. I can just reference using the expression `$(foo)`, when `isOutput=false`, which is _great_!

**Comment by SindhuriMarapureddy** [comment]
I need to pass the variables into templates.for example.ouput of small should be passed as input to medium.how is this possible?
  - template: windows-tests.yml
    parameters:
      integration_tests: ["Small", "Medium"]
      check_status: "$(Powershell1.var)"

**Comment by SindhuriMarapureddy** [comment]
inaddition to above,i would like to add

- o/p from build step with be stored in checkstatus variable and will be passed to template.

- Powershell1.var will be used by small test and then generated a value which needs to be used by medium.

**Comment by gchamon** [comment]
> $(Powershell1.VariableName)

I don't consider this working as intended, because the classic release UI doesn't interpret this as an internal variable. Instead, it interprets it as a parameter and forces you to fill it with a value when using the taskgroup in a release pipeline, overwritting the correct output value.

This SHOULD NOT BE USED like this. It does not work with the UI and is not documented. Microsoft should, however, port output variables to be used inside taskgroups just like we use it in classic release pipelines. Migrating everything to yaml is not feasible.

**Comment by oleksabor** [comment]
Just for future references (@gchamon you may find it useful)

The environment variables can be accessed in the classic release pipeline with powershell script like below

`$uploadedApp = $env:POWERSHELL1_UPLOADEDAPPSTR;`

this assigns the `POWERSHELL1_UPLOADEDAPPSTR` environment variable value to the `$uploadedApp` powershell variable.

However it would be nice to have Task group output variables to be accessed via reference name too. 
Using the powershell script execution order number like a part of a variable name looks a little bit messy.

**Comment by sijucm** [comment]
One of those classic rabbit-hole issue with Microsoft. If you selected the classic pipeline for some reason and decided to move to taskgroup, half way down the line you realize you cannot use the output variables of a task and now your choice is to go back and not use task groups or move to YAML and face another issue that blocks you. Microsoft should focus on giving logical products. I just cannot understand why output variables are not supported in a taskgroup. My work with Microsoft products feels like a house of cards with workarounds and hacks. Word of advice to Microsoft, create features in products only (bold letters) if it makes sense and not because it is easier to sell a product or because marketing is forcing you.

**Comment by gchamon** [comment]
@oleksabor 
> `$uploadedApp = $env:POWERSHELL1_UPLOADEDAPPSTR;`

that means you have to refactor code to use direct access variables instead of receiving by parameter, which makes it all that more troublesome to mock and test.

another thing, what if you need to include another script before the one that is writing to `POWERSHELL1`? Suddenly you have to refactor more code to account for some change that cannot be version controlled. Why should the topology of the release definition affect my internal code structure?

This SHOULD NOT be used like this. This is bad and leaves room for a lot of headache in the future.

**Comment by JoseFMP** [comment]
Same issue here. I think task groups should really get access to variables in a more convenient way.

**Comment by Shubhkishore** [comment]
Running into the same issue. They have this `ref name` for a task defined [here](https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md) as `{TaskName}_{Number}`

But not honestly this is very troublesome and confusing.

**Comment by DmytroSokhach** [comment]
I've tried all the combinations like
`$(DownloadSecureFile_1.secureFilePath)`
or
`$(DOWNLOADSECUREFILE1_SECUREFILEPATH)`

Simple scenario is
```
Task Group
- DownloadSecureFile
- ShellScript
```
What is the correct syntax if I want to use DownloadSecureFile, then just use it's output in the next task, which is Bash script in my case? Both of them inside same Task Group.

**Comment by dwoldo** [comment]
> I've tried all the combinations like `$(DownloadSecureFile_1.secureFilePath)` or `$(DOWNLOADSECUREFILE1_SECUREFILEPATH)`
> 
> Simple scenario is
> 
> ```
> Task Group
> - DownloadSecureFile
> - ShellScript
> ```
> 
> What is the correct syntax if I want to use DownloadSecureFile, then just use it's output in the next task, which is Bash script in my case? Both of them inside same Task Group.

It appears that the ordinal value is not required when there exists only one of that task type in the pipeline. Specifically for DownloadSecureFile, we used `DOWNLOADSECUREFILE_SECUREFILEPATH` (Bash).

**Comment by EricAllen-tr** [comment]
Okay, I'm experiencing a similar thing, and I've found something of a workaround.
I can't explain _why_ it works, but I'm recording it here, in the hopes that:
1. It might help someone else
2. I can maybe find the details when I need to do it again in a few months. 😳

I have a Task-Group.
1. Powershell task that sets an output variable via some degree of computation
   and ending with
   `Write-Host "##vso[task.setvariable variable=Narf;isoutput=true]$calculated"`
   where `$calculated` is a _PowerShell_ variable set earlier in the script.
2. Debugging helper: Command Line task with the following contents
   ```
   echo This is the output of all environment variables, and I mean all.
   rem Yes, the empty double quoted string is significant.
   set ""
   echo That's all folks!
   ```   
3. Some task that wants to use the value computed in the first task. What I do
   is use the syntax: `$(VariableThatIndirectlyNamesOutputVariableNarf)`.

When it comes time to stop debugging, task 2 will be deleted or disabled.

The syntax in task 3 causes the task group to gain a parameter with name
`VariableThatIndirectlyNamesOutputVariableNarf`. I give that a default value
of `$(VariableThatIndirectlyNamesOutputVariableNarf)` and a __Description__
that indicates my disgust at the necessity.

I have a Build Pipeline that consumes the above task group.
1. Fully expanded it has no other PowerShell Tasks (Relevant as per the keen
   observation of @dwoldo)
2. Its consumption of the Task Group leaves the __Reference name__ blank.
3. It has a few relevant variables.
   1. `despicable.hack.empty.string` has zero characters in the value column.
   2. `VariableThatIndirectlyNamesOutputVariableNarf` has the value
      `$(PowerShell.Narf)`.
   3. `PowerShell.Narf` has the value `$(despicable.hack.empty.string)`.

This works, for reasons I cannot express.

I further _assume_ the following:
- If the fully expanded pipeline had multiple instances of the PowerShell
  Task, I would need a digit identifier in the variables, such as
  `PowerShell1.Narf` and `$(PowerShell1.Narf)`.
- If I had multiple layers of task group, I'd have to drill the indirection
  parameter through all of them.
