### ISSUE TITLE
Docker Hub requires PAT, not password

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/azure-devops-docs#7003]
Under https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg, "Docker Hub and others" you mention a password is required. This didn't work for me, I had to create a PAT from my account page on Docker Hub (hub.docker.com/settings/security).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Added this note to the doc:
| Password | Required. The password for the account user identified above. (Docker Hub requires a PAT instead of a password.) |
