### ISSUE TITLE
Health-Check for containers

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/azure-devops-docs#7033]
Hey guys,
how can I configure my Healthcheck to check if my containerized build agent is still connected to azure devops? So that I can configure my orchestrator to spin up new instances of my container, when they lost connection.

I think this is even more intresting, if someone is using the --once parameter in his docker file in a kubernetes. This garantees new agents after every job...
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#run-interactively.

Your current linux agent isn't running the ./run.sh script anymore, it's using a node-based agent software. Is there any documentation for it yet?
Is this also able to run with a "-once" argument?
How can I health check this in kubernetes , when I run it with the "-once" parameter.

Is running a container with "-once" shutting down the container after the job completely?

Kind regards,
Bjego

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@Bjego -- Thanks for your question. You may find answers here:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@steved0x -- please look into this issue.

**Comment by Bjego** [comment]
@WilliamAntonRohm @steved0x  thank you for the hints. I think this should be part of the official docu to help your customers to run multiple agents in a kubernetes cluster.  
Maybe a section "How to run in kubernetes" with a common configuration would be nice. This should cover scaling and unregistering stopped agents.
Kind regards,
Bjego

**Comment by nextbenjy** [comment]
second Bjego's comment above - this would be most useful!

**Comment by Nirav-Bhadradiya** [comment]
@Bjego How did you make your linux agents forcing restart after each job ? did you find any documentation ? I was able to use --once for windows one but not in linux.

**Comment by Bjego** [comment]
@Nirav-Bhadradiya hey, sorry vor the very late response. 
I think it must be 
```
exec ./externals/node/bin/node ./bin/AgentService.js interactive
```
See the shellscripts ending:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux

**Comment by Lacerus** [comment]
Hi @Bjego ,

currently i have the same problem.
Did you found a nice solution for a livenessProbe and redinessProbe?
I would be very interested in it.
Cheers
Christian

**Comment by Bjego** [comment]
> Hi @Bjego ,
> 
> currently i have the same problem.
> Did you found a nice solution for a livenessProbe and redinessProbe?
> I would be very interested in it.
> Cheers
> Christian

Hi Christian,
unfortunally not as I had other topics to work on and this has not the highest priority at the moment. We are just preparing Azure Devops for our organisation and we still have to do quite a lot of paper work... But I thought the documentation for the agents could be better. Not sure when I do have time to fiddle around with the kubernetes based agents.
Cheers
Bjego

**Comment by Lacerus** [comment]
Hi Bjego,

to go on i solved this issue with a shell script. I just added a script like the following into the container and set a probe to it.

`
if [[ $(/bin/ps -ef | /bin/grep "/bin/AgentService.js" | /bin/grep -v grep | /usr/bin/wc -l) -ge "1" ]]; then 
 exit 0;
else
 exit 1;
fi
`
It is just looking if there is a process. 
Not a great and ideal solution, but i had no other idea.
Better would to communicate with the process to see if it really running.

**Comment by Bjego** [comment]
@Lacerus regarding to #8416, i've changed the last line of the start.sh script now to use not the AgentListener.js via node. I'm using now the official documented wrapper and shut down the container after every build (not yet tested in my on prem cluster):
`
exec ./run.sh --once
`

old:
```
# `exec` the node runtime so it's aware of TERM and INT signals
# AgentService.js understands how to handle agent self-update and restart
exec ./externals/node/bin/node ./bin/AgentService.js interactive
```

**Comment by WilliamAntonRohm** [comment]
cc @steved0x

**Comment by afeld** [comment]
I was experimenting with deploying the agent to [Google Cloud Run](https://cloud.google.com/run/) (for various internal reasons), which [requires a startup health check](https://cloud.google.com/run/docs/configuring/healthchecks). I got a bit fancy and implemented a health check endpoint in the container that ensures the agent is in fact registered with Azure DevOps.

First, I implemented [Flask](https://flask.palletsprojects.com/) server that grabs the information from the `.agent` file (generated when the agent starts) and calls [the Azure DevOps API to get that agent's status](https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/get?view=azure-devops-rest-7.1):

```python
import json
import os
import time

import requests
from flask import Flask
from requests.auth import HTTPBasicAuth

token = os.environ["AZP_TOKEN"]
# https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Linux#use-a-pat-in-your-code
basic = HTTPBasicAuth("", token)


def get_agent():
    with open(".agent", encoding="utf-8-sig") as f:
        return json.load(f)


def get_live_agent(agent):
    base_url = agent["serverUrl"]
    pool_id = agent["poolId"]
    agent_id = agent["agentId"]

    # https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/get?view=azure-devops-rest-7.1
    response = requests.get(
        f"{base_url}_apis/distributedtask/pools/{pool_id}/agents/{agent_id}",
        auth=basic,
        params={"api-version": "7.1-preview.1"},
    )
    response.raise_for_status()

    return response.json()


app = Flask(__name__)


@app.route("/")
def healthcheck():
    agent = get_agent()

    # takes a few seconds to come online, so do a retry loop
    NUM_ATTEMPTS = 10
    for i in range(NUM_ATTEMPTS):
        print("Checking if online...")
        live_agent = get_live_agent(agent)

        enabled = live_agent["enabled"]
        status = live_agent["status"]
        response = {"enabled": enabled, "status": status}
        if enabled and status == "online":
            return response
        elif i == NUM_ATTEMPTS - 1:
            return response, 504

        time.sleep(1)
```

Used Python since that's the language we use elsewhere, but could implement it in any language really. Then, modified [the Dockerfile + start script provided in the documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1) to run that server:

```diff
diff --git a/terraform/azure_pipeline_agent/Dockerfile b/terraform/azure_pipeline_agent/Dockerfile
index 0ac46189..d3b30dcc 100644
--- a/terraform/azure_pipeline_agent/Dockerfile
+++ b/terraform/azure_pipeline_agent/Dockerfile
@@ -1,9 +1,11 @@
-FROM alpine
+FROM python:3-alpine
 
 RUN apk update
 RUN apk upgrade
 RUN apk add bash curl git icu-libs jq
 
+RUN pip install flask gunicorn requests
+
 ENV TARGETARCH="linux-musl-x64"
 
 WORKDIR /azp/
@@ -11,6 +13,8 @@ WORKDIR /azp/
 COPY ./start.sh ./
 RUN chmod +x ./start.sh
 
+COPY ./status.py ./
+
 RUN adduser -D agent
 RUN chown agent ./
 USER agent
diff --git a/terraform/azure_pipeline_agent/start.sh b/terraform/azure_pipeline_agent/start.sh
index 9be8e699..36e63884 100644
--- a/terraform/azure_pipeline_agent/start.sh
+++ b/terraform/azure_pipeline_agent/start.sh
@@ -91,4 +91,10 @@ chmod +x ./run.sh
 
 # To be aware of TERM and INT signals call ./run.sh
 # Running it with the --once flag at the end will shut down the agent after the build is executed
-./run.sh "$@" & wait $!
+./run.sh "$@" &
+RUN_PID=$!
+
+echo "Starting status check server..."
+AZP_TOKEN=$(cat $AZP_TOKEN_FILE) gunicorn --bind=0.0.0.0:80 -w 1 --daemon status:app
+
+wait $RUN_PID
```

Hope that's helpful!

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
