### ISSUE TITLE
Use checkout to access repositories in the same workspace but different projects

### ISSUE THREAD

**Issue by jeffpatton1971** [MicrosoftDocs/azure-devops-docs#7039]
In the following document they talk about using git to grab additional repos, is it not possible to checkout a repository in the same workspace but different project?

- checkout: self
  persistCredentials: true
- checkout: git://otherProject/otherRepository

This returns the following:

remote: TF401019: The Git repository with name or identifier otherRepository does not exist or you do not have permissions for the operation you are attempting

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml

**Comment by jeffpatton1971** [comment]
If you need to checkout repositories from different projects within the same Organization, you may need to add the project to the Organization's "Project Collection Build Service". This should enable the cross project check-out to work.

`
resources:
  repositories:
  - repository: otherRepository
    type: git
    name: otherProject/otherRepository
    ref: refs/heads/someBranch

steps:
- checkout: self
- checkout: otherRepository
`

In my testing there was no need to leverage the persistCredentials flag on self for this to work.

Ideally, as the repos are in the same org, it seems that the pipelines should be able to reference them. I know in a regular devops release, I can add repositories from multiple projects without updating group memberships.

**Comment by msebolt** [comment]
@jeffpatton1971 Thank you for the feedback.

This example is similar to a solution posted [here](https://stackoverflow.com/questions/52365812/push-to-local-azure-devops-git-from-build-pipeline), with another alternative being to integrate the PAT in the git connection string.

Assigning this to the author for further review.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
