### ISSUE TITLE
Unable to use PAT in an environment variable

### ISSUE THREAD

**Issue by Attoy** [MicrosoftDocs/azure-devops-docs#7041]
Following the instruction in [this](https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows) article even if I set an environment variable with my PAT:
```
# set environment variable for current process
$env:AZURE_DEVOPS_EXT_PAT = 'xxxxxxxxxx'
```
when I run
`$az devops login --organization https://dev.azure.com/contoso`
I've been always asked a token. Am I doing something wrong?

Thanks

**Comment by msebolt** [comment]
@Attoy  Thank you for the question.

Assigning this to the author for review.

**Comment by KathrynEE** [comment]
@geverghe - Could you address this issue?

**Comment by KathrynEE** [comment]
Created BUG 1739596 to track this issue in AzureDevops.

**Comment by KathrynEE** [comment]
@Attoy - is this still an issue for you? I have been able to get this to work using Windows Power Shell. I'm closing this issue as this is not a doc issue. If you are having problems still, please reach out to the [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
