### ISSUE TITLE
Retention policy clarification

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/azure-devops-docs#7061]
I think I understand "maximum number of versions per package".  This is to prevent Azure DevOps hosting old packages versions back to the dawn of time (save on space etc).

But I'm less clear on "Days to keep recently downloaded packages".  Is this a "caching" setting for the client?  I note the next section is titled "Recover a deleted package from the recycle bin" and also uses the same value of 20....just wanted to check that "downloaded" wasn't a typo (should have been "deleted")?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@DrGriff  Thank you for the question.

Assigning this to the author for further review.

**Comment by okoudje** [comment]
@msebolt , is it possible to recover in a single action all deleted packages from Recycle Bin ? Doing it one by one cane take time if you are deleted several packages

**Comment by ramiMSFT** [comment]
@DrGriff Thank you for your feedback. `days to keep recently downloaded packages` allow you to effectively manage your packages and artifacts storage. Example: if you set `days to keep recently downloaded packages` to 10, this means that any package that hasn't been downloaded in 10 days will be deleted automatically.
For `recovering deleted packages` section: the recycle bin will show you any packages that have been deleted from your feed in the past 30 days.

**Comment by okoudje** [comment]
I ask again :  is it possible to recover in a single action all deleted packages from Recycle Bin ? Doing it one by one cane take time if by mistake  you are deleted several packages @ramiMSFT .
