### ISSUE TITLE
Missing Explanation for how default branch for trigger impacts Pipeline Resource Trigger

### ISSUE THREAD

**Issue by Mr-Ev-H** [MicrosoftDocs/azure-devops-docs#7065]
The pipeline trigger only fires if the 'default branch for trigger' on the pipeline settings panel points to a branch with a matching pipeline definition. Despite this needing to be static, both the upstream and downstream pipelines are evaluated on the branch specified by the filter. It would be helpful for future developers if this was documented in any meaningful way.

The information posted in this bug report helped me understand this restriction.

https://developercommunity.visualstudio.com/content/problem/864701/pipeline-trigger-not-working-as-expressed-in-docum.html?childToView=897210#comment-897210

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Mr-Ev-H Thank you for the feedback.

Assigning this to the author for further review.

**Comment by steved0x** [comment]
@Mr-Ev-H Thank you for reporting this, and I will get the documentation updated to reflect this.

**Comment by steved0x** [comment]
This one has been on the backlog for a while, my apologies, we just updated the article with a new section to address this, thank you for letting us know and sorry that you ran into trouble.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml#branch-considerations-for-pipeline-completion-triggers
