### ISSUE TITLE
What pipeline build for .NetStandard 2.x?

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/azure-devops-docs#7093]
I have a solution with a .Net Standard 2.0 library and 3 Test projects (.Net Core 3.1 + NUnit).

I want a pipeline to build all 4 projects and then to execute the tests

It's not clear from the documentation whether I should be running MSBuild, VSBuild or what....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
It looks like this issue predates some updates to the [Build, test, and deploy .NET Core apps article](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#build-your-project). Closing.
