### ISSUE TITLE
Service Hooks Payload

### ISSUE THREAD

**Issue by wjdavis5** [MicrosoftDocs/azure-devops-docs#7097]
Looking at both the documentation and example service hooks there is little to no explanation about what the contents of the payload is.

For example, I create a Release Started and a Release Completed Service hook, and when I look at the payload none of the included guids actually represent the id of the release pipeline that triggered the alert.

Here is an obfuscated payload I receive:

```
{
    "subscriptionId": "000-000-000-000-000",
    "notificationId": 12,
    "id": "000-000-000-000-000",
    "eventType": "ms.vss-release.deployment-started-event",
    "publisherId": "rm",
    "message": {
        "text": "Deployment of release Release-430 to stage Test started.",
        "html": "Deployment on stage <a href='https://TESTAcentral.visualstudio.com/TESTA/_release?_a=environment-summary&definitionId=362&definitionEnvironmentId=1230'>Test</a> started.",
        "markdown": "Deployment on stage [Test](https://TESTAcentral.visualstudio.com/TESTA/_release?_a=environment-summary&definitionId=362&definitionEnvironmentId=1230) started."
    },
    "detailedMessage": {
        "text": "Deployment of release Release-430 on stage Test started.\r\nTrigger: After successful deployment of Dev",
        "html": "Deployment on stage <a href='https://TESTAcentral.visualstudio.com/TESTA/_release?_a=environment-summary&definitionId=362&definitionEnvironmentId=1230'>Test</a> started.<br>Trigger: After successful deployment of Dev",
        "markdown": "Deployment on stage [Test](https://TESTAcentral.visualstudio.com/TESTA/_release?_a=environment-summary&definitionId=362&definitionEnvironmentId=1230) started.\r\nTrigger: After successful deployment of Dev"
    },
    "resourceVersion": null,
    "resourceContainers": {
        "collection": {
            "id": "000-000-000-000-000",
            "baseUrl": "https://TESTAcentral.vsrm.visualstudio.com/"
        },
        "account": {
            "id": "000-000-000-000-000",
            "baseUrl": "https://TESTAcentral.vsrm.visualstudio.com/"
        },
        "project": {
            "id": "000-000-000-000-000",
            "baseUrl": "https://TESTAcentral.vsrm.visualstudio.com/"
        }
    },
    "createdDate": "2020-01-29T13:49:01.1293269Z",
    "resource": null
}
```

How should I identify the pipeline that actually triggered this webhook? Please dont tell me that the intention is to parse the markdown or html fields and break apart that url. The utility of this entire process is compromised if you dont include the triggering identifier!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@wjdavis5 Thank you for the feedback.

Assigning this to the author for review.

**Comment by wjdavis5** [comment]
Wanted to add this for awareness:
https://developercommunity.visualstudio.com/content/problem/900507/azuredevops-service-hooks-not-saving-all-values.html

**Comment by MisinformedDNA** [comment]
WRT: 

> no explanation about what the contents of the payload

Does the payload map to any known, published schema?

**Comment by wjdavis5** [comment]
We openes a support ticket through our EA. This was determined to be a bug in the preview feature where it did not honor saving options such as detailed hooks. Disabling the preview feature for the new service hook experience was a valid workaround. But i believe they have fixed the underlying issue at this point.
