### ISSUE TITLE
Misleading documentation with az login and az devops login

### ISSUE THREAD

**Issue by tlentine** [MicrosoftDocs/azure-devops-docs#7100]
There is a fairly glaring issue with the documentation at the following url:
https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows#use-environment-variables

Specifically, the following block is not completely accurate:

> Note
> 
> If you have already signed in with az login, then you don't have to provide a token as az devops commands now support sign in through az login.

If you have logged in using a `service principal`, as would typically be the case when using the Azure CLI task in Azure DevOps, the az devops extension does not recognize the service principal and will fail with cryptic error messages such as: 

> ERROR: The requested resource requires user authentication: {url to resource}

This [issue](https://github.com/Azure/azure-devops-cli-extension/issues/905) tracks the feature request, which as far as I can tell, is the only place that documents the fact that `az login --service-principal` is not compatible with the `az devops` extension.

Further, if using `az devops` extension as part of the Azure CLI Task within Azure Pipelines it is not necessary to invoke `az devops login` at all provided you have set the Personal Access Token (PAT) in the environment variable `AZURE_DEVOPS_EXT_PAT`. See this [issue](https://github.com/Azure/azure-devops-cli-extension/issues/486) for details.

I've unfortunately wasted quite a bit of time trying to get this to work within an Azure CLI task.

**Suggested Text:**
> Note
> 
> If you have already signed in with az login, then you don't have to provide a token as az devops commands now support sign in through az login provided you are not using a service principal to log.

It would also be helpful to specify within the article how to actually authenticate to Azure DevOps when invoking the `az devops` extension from within an Azure CLI task within Azure DevOps pipelines.

**Comment by KathrynEE** [comment]
@tlentine - Thank you for the feedback. I'm updating the article now.

**Comment by Tingle01** [comment]
Hi sorry to re-open this ticket but the documentation is still very confusing with reference to the bug.  In the [documentation](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops) you are still stating that you need to use the az devops login command which still fails on Windows agents.

Is there any chance you can change the documentation to show a working example?

**Comment by claireelyse** [comment]
Agreed! I have probably spent 5 hours on this issue. Turns out you can't use az login with a service principal - you must use a PAT(Which seems like a non-production ready solution). You also can't pipe the token to az devops login in a Devops CLI Powershell task. You have to set the environment variable. You also must add "az devops project list --org https://dev.azure.com/<yourorg>" or you get " ERROR: The requested resource requires user authentication: https://dev.azure.com/Intertribal/Intertribal/_apis/distributedtask/variablegroups
" when you try to write to variable group. The solution that finally worked for me is this:

    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: '$(connectionName)'
        scriptType: ps
        scriptLocation: inlineScript
        arguments: "$(test-functionDeploymentPAT)"
        inlineScript: |
          $env:AZURE_DEVOPS_EXT_PAT = "$(test-functionDeploymentPAT)"
          az extension add --name azure-devops
          az devops project list --org https://dev.azure.com/Intertribal

**Comment by KathrynEE** [comment]
@claireelyse - thank you for this feedback. I'm reopening the issue and will look into updating the article.
