### ISSUE TITLE
Requirements to display branch name in commit details page?

### ISSUE THREAD

**Issue by yorhpokie** [MicrosoftDocs/azure-devops-docs#7107]
What are the requirements to display branch name in commit details page, when the branch is not master?  For example, we'd like to display the release branch name in the commit details page.  Currently, no branch name is displayed for commits in the release branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6255243-5e5e-424c-5527-ec792c9b950e
* Version Independent ID: 2033d250-5385-1e02-d111-c47e44fdc8ef
* Content: [View commit details - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commit-details?view=azure-devops)
* Content Source: [docs/repos/git/commit-details.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/commit-details.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sancha**

**Comment by msebolt** [comment]
@yorhpokie Thank you for the question.

Assigning this to the author for further review.

Please note if this feature is unavailable you should move this issue to the product forum [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by jgtech** [comment]
I agree with @yorhpokie, we need to see the branch name, this is pretty critical to our current workflow
