### ISSUE TITLE
Explanation of "If you want to use a self-hosted agent, it must be running Windows Server version 1803 or newer."

### ISSUE THREAD

**Issue by Beffyman** [MicrosoftDocs/azure-devops-docs#7120]
What is special about self-hosted windows server agents that let them use this functionality?  Is there a limitation that prevents self-hosted linux agents from using it that the microsoft-hosted linux agents seem to get around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@person Thank you for the question, assigning this to the author for review.

For issues that go beyond the scope of the referenced content, feel free to raise the issue with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by juliakm** [comment]
@Beffyman Windows Server 1803 is [no longer supported](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/) and this documentation is outdated. Thanks for flagging this! I'll update the docs shortly.
