### ISSUE TITLE
"Verify if the Service Principal used is valid and not expired." section links to archived blog post

### ISSUE THREAD

**Issue by Tyriar** [MicrosoftDocs/azure-devops-docs#7131]
![image](https://user-images.githubusercontent.com/2193314/73566234-3528ed80-4418-11ea-842c-107bceb1dc58.png)

Clicking that link sends the user to an archived blog post index:

https://docs.microsoft.com/en-us/archive/blogs/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
@ninallam  - can you track this one

**Comment by Tyriar** [comment]
Ping @ninallam

**Comment by iamsrivatsa** [comment]
@Tyriar are you saying you cannot access the link mentioned? Here is the link for your reference.
https://devblogs.microsoft.com/devops/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/.

**Comment by Tyriar** [comment]
The blog post is available via the link now
