### ISSUE TITLE
Example for using 'Null' literal?

### ISSUE THREAD

**Issue by MarkWTW** [MicrosoftDocs/azure-devops-docs#7137]
Document reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
Section: Literals

I'm trying to use the Null literal in an equality comparison to determine if a parameter has been defined.

From the description in documentation on this page, I would expect following to be valid:

`${{ if ne(parameter['myparam'], Null) }}:`
 
This fails to run, I get: 
`Unrecognized value: 'Null'. Located at position xx within expression: ne(parameter['myparam'], Null).`

Can we please have an example in the documentation that shows how null should be used?

**Comment by msebolt** [comment]
@MarkWTW Thank you for the feedback.

Please provide a link to the article in question and we will assign this to the author.

**Comment by MarkWTW** [comment]
original post updated to include link to document uri and section

**Comment by juliakm** [comment]
@MarkWTW I apologize for the delay. `Null` can be returned from an expression but cannot be used directly. We've added some content recently to explain better how type casting works with expressions. I'll make it clearer in the `Null` section that this isn't a value you can use as-is.
