### ISSUE TITLE
Unclear what the difference is between "pipeline resource" and "download"

### ISSUE THREAD

**Issue by Lawls91** [MicrosoftDocs/azure-devops-docs#7141]
Please can you clarify in the docs what the difference here is:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example

Why would I use the "download" task over "resource pipeline"? What are the benefits of "keyword pipeline"? what are the benefits of "DownloadPipelineArtifacts"?

What are the key use cases for both?

Are resources only allowed to be used in deployment jobs? Is that the main difference?

**Comment by ashokirla** [comment]
`pipelines` resource is a first class way to consume artifacts from a CI pipeline and also configure automated triggers. It gives you full visibility into the process by displaying the version consumed, artifacts, commits and work-items. When you define a pipeline resources, the associated artifacts are automatically downloaded in `deployment` jobs. But you can choose to download the artifacts in build jobs or override the download behavior in deployment jobs using `- download` shortcut. This task internally uses our DownloadPipelineArtifacts task prefilling all the required parameters.

You can directly use DownloadPipelineArtifacts task in your jobs if you choose to. Even though we don't recommend this approach as you will be missing out on traceability and triggers, there could be some scenarios where you would choose to use  the task directly. For ex. you might have a script task stored in a different template. And the script task required artifacts from some build to be downloaded. And you are not sure if those who use this template will add the pipeline resource. So to avoid dependencies, you would like to add a DownloadPipelineArtifacts task passing all the build info to the task.

**Comment by juliakm** [comment]
Thanks @ashokirla! I'm updating the docs to include FAQs that address these questions.

**Comment by juliakm** [comment]
#sign-off
