### ISSUE TITLE
How to use pipeline decorator in Deployment job

### ISSUE THREAD

**Issue by Mikebeem** [MicrosoftDocs/azure-devops-docs#7162]
I'm missing information about injecting the decorator inside the deployment jobs.

The Sprint 163 update says:

You can now add pipeline decorators to deployment jobs. You can have any custom step (e.g. vulnerability scanner) auto-injected to every life cycle hook execution of every deployment job.

How do I inject a decorator to a life cycle hook for deployment jobs?

Using the targets property, I get it to work with build jobs and release pipelines, but not with deployment jobs (from Yaml).

This page for the pipeline decorator:
https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#author-a-pipeline-decorator

And this page for the sprint 163 update: https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-163-update#use-pipeline-decorators-to-inject-steps-automatically-in-a-deployment-job

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by hbuckle** [comment]
Yes, please provide this information - it's no good announcing new features without any documentation on how to use them

**Comment by hbuckle** [comment]
@N-Usha @RoopeshNair - any update on this please?

**Comment by N-Usha** [comment]
Thanks for the feedback and apologies for the inconvenience @hbuckle. 

Pipeline decorator support for deployment jobs was released behind a feature flag which was progressively rolled out broadly to all accounts by last week. And there is no change in the decorator code needed explicitly for deployment jobs. If you have followed the documentation [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops#author-a-pipeline-decorator), all your existing decorators should automatically work for both regular as well as deployment jobs. 

Could you please try again and confirm if you are still seeing any issues? Thanks!

**Comment by n3wt0n** [comment]
I've tried and the decorators which target either 
``` 
ms.azure-pipelines-agent-job.pre-job-tasks  
```
or
```
ms.azure-pipelines-agent-job.post-job-tasks  
```
are actually injected also into the Deployment Jobs.

I guess we should at least add that bit to the documentation. There is no mention of "Deployment Job" anywhere in that page.

However, I have to say that I find it "weird" that a __build__ decorator is used in a deployment job. I would have found it more logical to have the __release__ decorator injected into a deployment job instead.

**Comment by vtbassmatt** [comment]
(PM for unified pipelines chiming in)

It's confusing because we evolved the older Build system to become the new unified pipelines system. All YAML-based builds are part of unified pipelines, which explains why that decorator is used. @n-usha do you think you could mention something about this in the docs?

**Comment by chcomley** [comment]
Adding @zachariahcox for further guidance, thank you!

**Comment by chcomley** [comment]
It looks like this article has been updated a few times since April! Please @mention me if it still needs more clarity. Thank you for your feedback!

**Comment by pinkfloydx33** [comment]
Are you able to target/add specific deployment lifecycle stages? For example to add a preDeploy or on.failure set of steps to all deployments. Or must those life cycle hooks be defined, and only then are tasks added to them unconditionally (pending any template logic)?
