### ISSUE TITLE
This document needs to explain that trigger paths are case sensitive

### ISSUE THREAD

**Issue by judemars** [MicrosoftDocs/azure-devops-docs#7165]
Lost a lot of time figuring this out :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@judemars I'm sorry that you ran into trouble, I will make a note to call that out.

**Comment by vijayma** [comment]
Next set of updates to this doc will have this note.

**Comment by WilliamAntonRohm** [comment]
@samrueby -- Sam, thank you for your follow-up.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
@vijayma -- Vijay, please review this update in [private PR 4623](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4623).

**Comment by richardhauer** [comment]
Will it surprise anyone to hear that the document was last updated in Jan 2023, and as at 10 Feb 2023 it STILL does not mention that trigger paths are case sensitive!

@steved0x  @vijayma  @WilliamAntonRohm 
What's going on? Seems like it can't be that hard to update this?

**Comment by PapaDers** [comment]
I just lost so much time on this. How is this not done. Is this something I can change?

**Comment by WilliamAntonRohm** [comment]
@PapaDers -- thank you for your followup.  Are you referring to documenting this behavior, or changing it in the product?  If this is product-related, please add it there:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

**Comment by richardhauer** [comment]
@WilliamAntonRohm @PapaDers  the issue (as I understand it) is that ADO runs on Linux, which is case sensitive, ergo files and branches are case sensitive.

I think we can all cope with that but the internal hosting arrangements for SaaS platforms can't be known to its users and so can't be used to anticipate these behaviours, which is why the documentation is so important.

**Comment by WilliamAntonRohm** [comment]
@richardhauer -- Richard, this article now has a Note following the initial paragraph; please let me know if there are other places in the documentation that could use this Note:
![image](https://user-images.githubusercontent.com/27738025/222835861-5d54d619-a441-4023-b3e0-eff47dea645a.png)

**Comment by richardhauer** [comment]
Thanks @WilliamAntonRohm  I did see the update - that's very prominent!
I do try to provide feedback where I spot things - I think that the MS documentation is amongst the best across the many systems that I have to use, so it's great to be able to contribute here and there when I can.

**Comment by WilliamAntonRohm** [comment]
@richardhauer -- Richard, thank you for your interest and that compliment!

**Comment by PapaDers** [comment]
> @richardhauer -- Richard, this article now has a Note following the initial paragraph; please let me know if there are other places in the documentation that could use this Note: ![image](https://user-images.githubusercontent.com/27738025/222835861-5d54d619-a441-4023-b3e0-eff47dea645a.png)

This is perfect! Thank you. I spent far too long digging into the nuances of why a pipeline trigger wasn't behaving correctly over a capitalization mistake. The reason I was so upset is I dug through the Microsoft docs for hours trying to figure out what the issue was.
