### ISSUE TITLE
Parameter "fillRegistryCredential" not documented

### ISSUE THREAD

**Issue by dalyup** [MicrosoftDocs/azure-devops-docs#7182]
The parameter "fillRegistryCredential" is not documented on the page, even though it is already available for use in a pipeline.

Here is the information given for it:

"Add registry credential for pushing docker images to deployment manifest"

I would be interested in how it gets the registry credentials. Does it just take them from the subscription somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by EliiseS** [comment]
Is this documented now?

**Comment by LarsKemmann** [comment]
This still hasn't been documented, more than two years later. I suggest we reopen the issue, @dalyup - or at least someone should post the answer here since this is what people will find by searching.

**Comment by WilliamAntonRohm** [comment]
@EliiseS, @LarsKemmann -- Eliise, Lars, thank you for your follow-up.

@vijayma -- Vijay, please look into this issue.
