### ISSUE TITLE
Discrepancy with Azure Devops Server 2019

### ISSUE THREAD

**Issue by sudhakarau1** [MicrosoftDocs/azure-devops-docs#7198]
This page says that the Kubectl task is not available on Azure Devops Server 2019 when in fact it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758684fd-c462-7f9a-8506-577dce083c1d
* Version Independent ID: 5267e318-25ec-01ba-5aa4-b84cdd267570
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by iamsrivatsa** [comment]
@sudhakarau1 The page is not available on the Azure DevOps Server 2019. The warning clearly says it is not available for Azure DevOps Server 2019 and hence defaults to Azure DevOps Services. PFB screenshot for your reference.

![2020-04-18_09-32-19](https://user-images.githubusercontent.com/44693716/79627661-cd9d5700-8157-11ea-9e30-67b0890f9904.png)

I'll be closing this issue. Feel free to open a new issue if you have any more feedback.
