### ISSUE TITLE
Determining which pipeline triggered the current pipeline

### ISSUE THREAD

**Issue by mmisztal1980** [MicrosoftDocs/azure-devops-docs#7218]
Assuming my pipeline has multiple pipeline triggers defined, is it possible to determine which trigger 'fired' the current pipeline execution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml&source=docs#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by chatelain-io** [comment]
Add the same issue and the only information you get is the Build.Reason == ResourceTrigger

https://developercommunity.visualstudio.com/content/idea/907849/pipeline-trigger-resource-variables.html

**Comment by WilliamAntonRohm** [comment]
@mmisztal1980 -- Maciek, thank you for your question.

@chatelain-io -- Alexandre, thank you for filing that report.

@steved0x -- Steve, please look into this issue.

**Comment by Michaelvsk** [comment]
It seems to be not available out of the box currently. But on VS dev community a workaround was discussed which uses the DevOps REST API. Hope it helps until a better solution is implemented.
https://developercommunity.visualstudio.com/idea/907849/pipeline-trigger-resource-variables.html

**Comment by mmisztal1980** [comment]
@steved0x just wanted to check if there's been any progress here? is it possible to determine which trigger was fired yet?
