### ISSUE TITLE
Note about System.PullRequest.SourceRepositoryURI possible inaccurate

### ISSUE THREAD

**Issue by collinbarrett** [MicrosoftDocs/azure-devops-docs#7253]
The documentation for `System.PullRequest.SourceRepositoryURI` says that "This variable is initialized only if the build ran because of an Azure Repos Git PR affected by a branch policy. It is not initialized for GitHub PRs." I believe this is inaccurate. I see this variable initialized from a GitHub PR. See [here](https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=2781&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=76467409-274e-589c-5c88-4286504c504b&l=12)

I stumbled across this while trying to solve [this](https://stackoverflow.com/q/60188806/2343739).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@collinbarrett I apologize for the delay. I'm working on confirming this with the engineering team.
