### ISSUE TITLE
How to handle Tokens in query strings?

### ISSUE THREAD

**Issue by vanpyrzericj** [MicrosoftDocs/azure-devops-docs#7263]
An extension I am trying to develop that would grab an API token stored in a service endpoint, and add it as a query string during a custom build task is needed. How would I go about this given that none of the pre-defined "closed list" of service endpoint types imply that we can pull the token into the URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90db6e4c-6240-fe2e-3043-0a7d186b9ca7
* Version Independent ID: a62ec500-3330-e28a-8019-118a3b9e261f
* Content: [Service Endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/service-endpoints?view=azure-devops)
* Content Source: [docs/extend/develop/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/service-endpoints.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @vanpyrzericj, Thanks for reaching out. I'm following up with the team and will be in touch.

**Comment by pksorensen** [comment]
Looking for the same answer, how to i add the oauth2 access token to the data source request?

**Comment by vanpyrzericj** [comment]
@pksorensen @chcomley I ended up figuring out this myself, since this issue went stale after more than a month.

In my vss-extension.json I have the following authenticationSchemes array:
```
"authenticationSchemes": [
          {
            "type": "ms.vss-endpoint.endpoint-auth-scheme-token",
            "inputDescriptors": [
              {
                "id": "apitoken",
                "name": "API Key",
                "description": "",
                "inputMode": "textbox",
                "isConfidential": true,
                "validation": {
                  "isRequired": true,
                  "dataType": "string"
                }
              }
            ]
          }
        ]
```

And then, in my case, I referenced that `apitoken` value in my JavaScript build task definition by calling `getEndpointAuthorizationParameter()`. I then manually used axios to make the request putting this in the header or requests as needed. But of course, one can do anything they wish once they've pulled in the `inputDescriptors` from their service endpoint(s) created with their extension.

This required a lot of digging into other folks' GitHub extension projects and on random super-outdated VSTS Extension (yes, that old) documentation in order to get right. Therefore, I still believe that the MS Docs team needs to do a better job for those of us who don't have enterprise contracts with Microsoft and are still trying to develop extensions for _their_ product(s).

**Comment by pksorensen** [comment]
@vanpyrzericj - thanks for the update. I am looking at oauth2 endpoints and having same experience that it feels like alot of undocumented features that i have to guess about. 

I am stuck at ado not refreshing my access token.

**Comment by chcomley** [comment]
Adding @narula0781 for further guidance/assistance, thank you!

**Comment by romil07** [comment]
@pksorensen Hi Poul, are you still blocked on this issue? Does the solution provided by @vanpyrzericj not suit your usecase?
If it doesn't, could you elaborate your issue a bit more for me to help you?

**Comment by chcomley** [comment]
Hi @vanpyrzericj, since there's no reply to romil07's previous question, asking whether you were still blocked, I assume you're unblocked at this point! I'll be closing this issue, however if you have any further feedback or questions, please @mention romil07. Thanks so much!
