### ISSUE TITLE
Deployment Badge Example in correct

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/azure-devops-docs#7264]
Hi There,

img src didn't work for me. It has to be markdown using ![Deployment](https://...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by iamsrivatsa** [comment]
The example is correct. Please check if you are passing the proper link. It worked for me using the below format <img>. For your reference below!

<img src = "https://vsrm.dev.azure.com/rubdevopson/_apis/public/Release/badge/c53ed56f-c130-470b-a6ae-3c4a93266530/36/86" />

**Comment by iamsrivatsa** [comment]
Closing thie issue now. Feel free to open a new issue if you have any more feedback.
