### ISSUE TITLE
addSpnToEnvironment variable names are incorrect

### ISSUE THREAD

**Issue by pholden77** [MicrosoftDocs/azure-devops-docs#7267]
The doco says that using the addSpnToEnvironment task input will add variable named as $servicePrincipalId, $servicePrincipalKey and $tenantId to the powershell script.

The correct names for these variables are;

$env:servicePrincipalId, $env:servicePrincipalKey and $env:tenantId

See: https://developercommunity.visualstudio.com/content/problem/836430/no-values-available-for-service-principal-variable.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by WilliamAntonRohm** [comment]
@pholden77 -- thank you for your feedback.

@N-Usha -- please review the above-mentioned PR.

**Comment by WilliamAntonRohm** [comment]
@mijacobs -- please review [PR 989](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/989)
