### ISSUE TITLE
Version required to install pre-release tools

### ISSUE THREAD

**Issue by cauldnz** [MicrosoftDocs/azure-devops-docs#7269]
We found that we needed to specify the 'version' in order to install the report generator in our pipeline
So;
`arguments: install --tool-path . dotnet-reportgenerator-globaltool`
becomes
`arguments: install dotnet-reportgenerator-globaltool --tool-path tools --version 4.4.7`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cauldnz** [comment]
Here's the build log error. 

```
"C:\Program Files\dotnet\dotnet.exe" tool install dotnet-reportgenerator-globaltool --tool-path tools
C:\Program Files\dotnet\sdk\3.1.101\NuGet.targets(123,5): error : Failed to retrieve information about 'dotnet-reportgenerator-globaltool' from remote source 'https://pkgs.dev.azure.com/LabCh/7f6101fd-4c9c-472f-b550-518907ae6aab/_packaging/e1f24fbc-156d-432a-b92e-ee33e4f64c0e/nuget/v3/flat2/dotnet-reportgenerator-globaltool/index.json'. [C:\Users\VssAdministrator\AppData\Local\Temp\rwrqzds1.gyh\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.101\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\VssAdministrator\AppData\Local\Temp\rwrqzds1.gyh\restore.csproj]
The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

**Comment by juliakm** [comment]
We've updated this article to use `DotNetCoreCLI@2` since this issue was filed. Closing issue for now.
