### ISSUE TITLE
Are there any characters that have to be escaped?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#7306]
like if I'm querying for `o'neil` in SQL, I would have to specify something like `'o''neil`.  Are there any characters that need to be escaped in WIQL? 

I'm asking because one of the things I search for using WIQL are web url's and sometimes I cant find things in a query but can by pasting the same string into the search interface in DevOps. I think its just some of the chars in the urls so I'd like to rule that out before opening a support case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#linked-work-items)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
@StingyJack I don't know all the characters that need to be escaped. But you could certainly start with the standards like ' and slashes. If you get stuck ping me on Teams.

**Comment by StingyJack** [comment]
@danhellem I don't think I can ping you on Teams?
