### ISSUE TITLE
Screen shot is out-of-date

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/azure-devops-docs#7335]
In the section "Create a repo using the web portal", the **New repository** button is no longer on the repo dropdown as shown in the screenshot. It is now on the dropdown that is opened by the "+" button to the right of the project name (which is not shown in the screenshot.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df523114-2647-3282-525e-a0e4fe605dfb
* Version Independent ID: 91af894a-fb2f-ac3f-311f-978cd7dbf359
* Content: [Create a new Git repo in your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-new-repo?view=azure-devops#feedback)
* Content Source: [docs/repos/git/create-new-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-new-repo.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
Someone may have fixed this behind my back. The current contents match how the service behaves.

**Comment by Rick-Kirkham** [comment]
No. The problem is not fixed. It is exactly as I originally described it. Here is a screen shot that shows there the **New Repository** button is actually located. You can see that it does not match the location in the screen shot in step 2 of the article. 
![image](https://user-images.githubusercontent.com/9088056/91240532-262cc400-e6f7-11ea-815d-77104fcde4e0.png)

**Comment by Rick-Kirkham** [comment]
@vtbassmatt Please reopen and fix.

**Comment by vtbassmatt** [comment]
The doc is correct as written. You can _also_ create a repo using the `+` button, but that's not what the directions instruct in this quickstart. And the reason for that is that down-level versions of TFS don't have the new vertical nav, so it's easier to offer a single set of instructions that work everywhere.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/714283/91245853-7a966a80-e71c-11ea-88d9-39e08dc3b4b8.png">

**Comment by Rick-Kirkham** [comment]
There’s no such button on my project. Here’s a screenshot. The Manage repositories button just navigates to another page where the same repos are listed.
[A screenshot of a cell phone  Description automatically generated]

**Comment by vtbassmatt** [comment]
Hmm, is that on-prem or something? If so, maybe 2019 RTW? I don't remember a time where we ever removed it from the repo picker, but it's possible we did that for a little while.

**Comment by Rick-Kirkham** [comment]
How would I determine if it is on prem? 
At any rate, if your documentation is supposed to be used by people with my version of Azure DevOps, then the docs need to take account of variable UI between versions.
