### ISSUE TITLE
Build.TriggeredBy.* doesn't work with pipeline trigger?

### ISSUE THREAD

**Issue by melcloud** [MicrosoftDocs/azure-devops-docs#7380]
When pipeline B is triggered by pipeline A through pipeline trigger, variables `Build.TriggeredBy.*` do not have any value. Looks like they only work with build completion trigger?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by melcloud** [comment]
Alright, found those variables in YAML schema doc... Can we please update this section of the doc to specify that `Build.TriggeredBy.*` is for completion trigger. `resource.pipeline.*` is for pipeline trigger, and document those variables here as well?

**Comment by chatelain-io** [comment]
Build.TriggeredBy.* should not be empty even if it is from resource pipeline.

In most case you want to know what triggered the pipeline so you can act accordingly.

**Comment by juliakm** [comment]
In Classic pipelines, this `Build.TriggeredBy.* ` variables are triggered by a build completion trigger. We have a note in the [pipeline triggers article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml). I'll add more info in the variable definitions as well.
