### ISSUE TITLE
Creator role cannot coexist with Adminstrator

### ISSUE THREAD

**Issue by archiebw-amido** [MicrosoftDocs/azure-devops-docs#7381]
I can only assign one of the roles from the security menu in the library page. I need to assign both these roles to the build service account - Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fe2521-cc98-8946-89b4-5a8199a6d898
* Version Independent ID: dbc4b6cf-ddb1-ac16-c634-eaf15072e111
* Content: [Library for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/index?view=azure-devops-2019#security)
* Content Source: [docs/pipelines/library/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
