### ISSUE TITLE
YAML Pipeline Retention

### ISSUE THREAD

**Issue by almisson** [MicrosoftDocs/azure-devops-docs#7382]
It's not clear from the documentation how these retention policies apply to pipelines defined in YAML. There's a section on "Release Retention" but how does that apply to pipelines defined in YAML?

More specifically,  the documentation states "The retention timer on a release is reset every time a release is modified or deployed to a stage." Is this applicable to any stage in a YAML pipeline? Or does the stage need to have a deployment type job in order to qualify the stage as a "release" stage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by fakhrulhilal** [comment]
I'm asking the same question. I don't see retention policy when using Azure Pipeline YAML. It's still visible when using classic UI. I'm using Azure DevOps Server 2019. Where I can get the detail?

**Comment by ashokirla** [comment]
cc @vijayma 

Retention policy for YAML pipelines is same as build pipelines. You can see that in Project Settings -> pipelines -> settings section.
And you pipeline retention unlike release retention cannot be controlled at definition level. You can set it at project level or you can choose to retain a specific run.
