### ISSUE TITLE
unclear

### ISSUE THREAD

**Issue by chlsmith** [MicrosoftDocs/azure-devops-docs#7389]
The "Mirror the Repository" step is very unclear.   What path does the user actually need to be in to do this?  The image shows everything being done in the "MigrationDemo" path, and I see nothing in these instructions that happens in the FabrikamOld path.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b779541e-e77e-38e7-7134-fa1f4c698899
* Version Independent ID: fe82ec27-4640-d0f2-3978-01400e2b719b
* Content: [Move Git repositories between Team Projects - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops#feedback)
* Content Source: [docs/repos/git/move-git-repos-between-team-projects.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/move-git-repos-between-team-projects.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @wpschaub
* Microsoft Alias: **sdanie**

**Comment by i-am-ahmed** [comment]
Totally agree I can't understand when should I put the old path !
