### ISSUE TITLE
unclear how workspaces really work

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/azure-devops-docs#7409]
This documentation is lacking in really helping users understand how workspaces work. Our pipeline doesn't seem to re-use workspaces, and so we get to a point where machines are running out of space. If the `clean` property on the workspace only cleans a workspace before it's used, then it won't help when old workspaces are left around. Overall, there is clearly a lot more to how workspaces work that needs to be documented so that your customers can be productive and not constantly run into issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#workspace)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by dvescovi1** [comment]
I totally agree, there does not appear to be a way to "clean" a workspace "after" a job is run. This seems so obvious and I do not understand why it is not included. My locally hosted agent's disk drive is constantly filling up because of job's left over residuals. I have to go in and manually clear things out every few weeks. A real pain.

**Comment by juliakm** [comment]
@stevenbrix You can use a maintenance job at the organization settings level to clean up your working directories. To set this up, go to **Organization Settings** > ** Pipelines** > **Agent pools** > ** Your Agent** > **Settings** and enable the agent maintenance job. We will work on making this clearer in the docs.

**Comment by steved0x** [comment]
The docs have been updated: [What is a maintenance job](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#what-is-a-maintenance-job)
