### ISSUE TITLE
Access team report site from Web Portal 

### ISSUE THREAD

**Issue by vladdanylko** [MicrosoftDocs/azure-devops-docs#7421]
This page states 'To access the team report site from Team Web Access, on the Home page, click  Reports.' There does not seem to be a Reports link in Team Web Access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf4e670-b5c1-5ef5-bc2f-ce540b2ade15
* Version Independent ID: 8dc91d99-ad1a-a03c-f422-a9664e7aa70a
* Content: [View, upload, and organize Reporting Services reports - TFS](https://docs.microsoft.com/en-us/azure/devops/report/admin/view-upload-organize-reporting-services-reports?view=azure-devops-2019#feedback)
* Content Source: [docs/report/admin/view-upload-organize-reporting-services-reports.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/admin/view-upload-organize-reporting-services-reports.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vladdanylko - Thank you for your inquiry. A link from Team Explorer to SQL Reporting Services will only be available if Reporting Services has been installed with your deployment. Also, the integration between SQL Reporting Services, Azure DevOps web portal, and Visual Studio/Team Explorer has changed with the start of TFS 2018 and Visual Studio 2019.  I recommend that you bookmark your Reporting Services web portal and not use the Team Explorer interface.  I've updated the article to indicate that it is only valid for TFS-2017 and earlier versions.
