### ISSUE TITLE
Status of a code review comment

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/azure-devops-docs#7430]
Regarding: https://docs.microsoft.com/en-us/azure/devops/repos/git/pullrequest?view=azure-devops#how-does-the-code-review-work 

The possible statuses for a comment are: Active, Pending, Resolved, Won't Fix and Closed.  I think it would be great to add some documentation giving examples of when you'd use each status (personally, I'm not clear on when to use "Closed").  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea32d3a-53e9-3e21-d419-6e8c8c055ef0
* Version Independent ID: 4942fd13-34c2-a2ef-5e2d-fff913a397ed
* Content: [Create a pull request - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pullrequest?view=azure-devops)
* Content Source: [docs/repos/git/pullrequest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pullrequest.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by bunsen32** [comment]
Yeah, I found this issue from a web search for explanation of what the statuses mean.

Documentation would be nice. Progressively-disclosed documentation in-app would be even better!

**Comment by norvegec** [comment]
This briefly explains it. Although, adding details about which statuses block autocompletion and which don't would be an improvement.
