### ISSUE TITLE
Failed instructions

### ISSUE THREAD

**Issue by WillGoldLO** [MicrosoftDocs/azure-devops-docs#7431]
This absolutely does not work at all.  This content on this page should be replaced with proper working instructions.  This is a common theme with Github connectivity and Azure repos.  Using Azure repos is a pretty terrible experience overall.  Clunky and on par with the most inaccurate instructions for any product I have used in the past 2 decades. Someone really needs to revisit the repos section in Azure.  It really stinks to configure and does not behave in a meaningful way with no feedback or errors.  Just completely missing functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffffb75a-67a8-f005-9980-de1270efbabf
* Version Independent ID: 4ae8f3f0-24e2-05f7-5c2e-d0a23aa330c0
* Content: [Learn how to connect/integrate GitHub with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/boards/github/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/github/index.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@WillGoldLO -- Will, thank you for your feedback.  You are welcome to [file your product issues here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

@KathrynEE -- Kathryn, please look into this issue.

**Comment by danhellem** [comment]
@WillGoldLO thanks for the feedback. Any chance you can be more specific on the issues you are having? This is the first I have heard about lacking documentation. So I am not sure where to start or the help.

Maybe the first issue we can address is...what issues are you running into? Errors? 

Then i can dig into the docs and see what we need to fix.

**Comment by WillGoldLO** [comment]
I completed the project a few weeks ago and we used GitHub and Azure Boards.  When I tried to link work items to pull requests, the links do not work as stated in the instructions.  Setting up the environments may or may not have been the issue but since we had time constraints we handled the merging and completing stories as separate manual processes.

On a positive note, my newest project using Azure repos and Azure boards, it all works great.

**Comment by WillGoldLO** [comment]
I think the video was changed to add more information that I don't recall the first time I watched.  I don't have a lot of time to re-test this as my new project uses native Azure for the full pipeline and is critically tight on schedule.  You can close this for now since I do not have ability to verify at this time.

**Comment by danhellem** [comment]
@will-bartlett sounds good. Feel free to ping me if you have any additional issues. dahellem@microsoft.com
