### ISSUE TITLE
Lifetime of the service principals

### ISSUE THREAD

**Issue by mslot** [MicrosoftDocs/azure-devops-docs#7436]
What is the lifetime for the service principal created? I cant find any docs anywhere that tells me the lifetime of the created service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-azure-resource-manager)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
@mslot The lifetime is 2 years. Azure DevOps generates a service principal in Active Directory. The principal can be renewed from both Azure DevOps and Azure Active Directory. See [this Developer Community post](https://developercommunity.visualstudio.com/content/problem/929344/azure-devops-service-connection-expired-and-cannot.html) for more discussion. 

I'll update the documentation as well.
