### ISSUE TITLE
What is required to choose the service connection?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#7468]
I have created a service connection but this task will not let me select it. If I click on the Manage link, I can see the service connection. I've also tried sharing the connection with Build Administrators as Administrator role and its still not visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8529ee1d-6da2-f0c9-f9a1-3c312e4c13d7
* Version Independent ID: 3f4ea75f-a4a1-d248-b4ce-3de1a58185c7
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by steved0x** [comment]
@StingyJack This sounds like a bug in the task. Please file an issue here: https://github.com/microsoft/azure-pipelines-tasks (Due to the age of this issue it may have been resolved already).
