### ISSUE TITLE
Analysis Services Server Mode

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/azure-devops-docs#7470]
This document needs to specify the correct mode to configure for Analysis Services: "Multidimensional and Data Mining Mode", "Tabular Mode", or "PowerPivot Mode".  This is really important to specify, as it cannot be changed once Analysis Services is installed (it requires a completely new install of Analysis Services).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24f144e6-8499-d786-4f80-9ae3704882e8
* Version Independent ID: 279488e8-f051-a346-c7a2-15f477b9b374
* Content: [Add reports to a team project - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/report/admin/add-reports-to-a-team-project?view=azure-devops-2019)
* Content Source: [docs/report/admin/add-reports-to-a-team-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/admin/add-reports-to-a-team-project.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PrometheusRising1  - Thank you for the feedback and need to clarify. I've added an item to my backlog to update the article and have contacted the product team to learn about which mode to choose.

**Comment by KathrynEE** [comment]
@@PrometheusRising1  - The Multidimensional and Data Mining Mode is the selection to make. I will update the article to reflect this.
