### ISSUE TITLE
Variables not expanded in repo names

### ISSUE THREAD

**Issue by vbrinza** [MicrosoftDocs/azure-devops-docs#7473]
I define variables both in templates and inline as you can see bellow:

variables:
- name: infraRepoName
  value: some-infra
- template: vars_it.yml
- template: vars_acc.yml

resources:
  repositories:
  - repository: some-infra
    type: git
    name: project_name/$(infraRepoName)
    ref: some-branch

The error I get:
The repository $(infraRepoName) in project project_name could not be retrieved. Verify the name and credentials being used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by fluffy-cakes** [comment]
This is not enabled;
https://developercommunity.visualstudio.com/idea/816606/allow-variables-at-resourcesrepositoriesrepository.html

**Comment by vtbassmatt** [comment]
As documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#macro-syntax-variables), not supported.
