### ISSUE TITLE
Path filter on Scheduled build  results in build not triggering (yaml)

### ISSUE THREAD

**Issue by KitsKlip** [MicrosoftDocs/azure-devops-docs#7485]
We want to schedule a build on a branch but only if code has changed in a certain path. But it does not work. No where in the doc can I get hold of such an example but the doc do not explicitly say it is not supported. It does have an 'always: boolean' flag but that is not really what we want.

Here is an example of what we want schedules in yaml. E.g
`
schedules:
 -cron: "5 * * * *"
  displayName: Run at 5 past
  branches:
    include:
    - some-specific-branch
  paths:
    include:
    - 'Monitoring/*'
`

(the github editor seems to mess up the formatting of the yaml content) 

Is this supported? If 'yes', what am I doing wrong. If 'no' will it be supported at some point?

Thanks in advance``

**Comment by WilliamAntonRohm** [comment]
@KitsKlip -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to process your issue, please let us know which docs.microsoft.com topic you’re referencing, or provide more context around your general task.

**Comment by KitsKlip** [comment]
@WilliamAntonRohm 
MS docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#scheduled-trigger

Context:

We want to run a task if changes was made in a certain part of a specific branch. But we want that task to be scheduled and not run right at that moment. But we do not want it to run if any change was made in the branch, only if a change was made in a specific location.

This works great with just normal branch triggers. But not with Schedules. On branch trigger if we add 'path: include' it works.
On Schedule if we add 'path: include' the task is never triggered. If you remove the 'path: include' the Schedule trigger works every time. 

I have tried multiple ways and syntax changes but always the same result. No error, just no task is triggered.

**Comment by steved0x** [comment]
@KitsKlip I'll find out if that is supported, and if so I'll update the doc, and if not, I can show you where to fie a feature request. I'll find out and report back shortly.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by andreasglaubitz** [comment]
I have the same problem. Is there a solution about this topic?

**Comment by devigo** [comment]
Looks like this is not implemented. I think everyone who is interested in this feature can vote here
https://developercommunity.visualstudio.com/t/add-path-filters-to-a-scheduled-build-trigger/366019

**Comment by woeterman94** [comment]
C'mon Microsoft it's been four years. How is this still not supported?
