### ISSUE TITLE
Distinguish between variables that are available at runtime only or available at both parsetime and runtime

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#7494]
The [expressions page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) states:

`Another common use of expressions is in defining variables. Expressions can be evaluated at compile time or at run time. Compile-time expressions can be used anywhere; runtime expressions are more limited.`

It continues:

`The difference between these syntaxes is primarily what context is available. In a parse time expression, you have access to parameters and statically-defined variables. In a runtime expression, you have access to more variables but no parameters.`

This page does not distinguish between variables that are only available at runtime and variables that are available at both parse and runtime.  Unfortunately, this makes determining if we can use specific variables in template expressions a time consuming guess and check effort.  See #4073, #7170, and #5279 where people have struggled with problems that may be alleviated by my request for additional documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by akempe** [comment]
Adding to this, it appears that variables defined outside of the YAML (so they can be passed from the CLI) are not available at parse time (i.e. available via ${{}} syntax), even though it feels like they should be,

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by MarkIannucci** [comment]
@juliakm , can you please reopen.  This continues to be a problem.  See #8062 for another example of someone having similar problems with this theme (with fewer upvotes)

**Comment by vtbassmatt** [comment]
Julia added this to the [predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables) tables a while back. You may have to scroll the table a bit to see the column.
