### ISSUE TITLE
This oDATA query returns error message

### ISSUE THREAD

**Issue by digikiwam** [MicrosoftDocs/azure-devops-docs#7500]
When I send this API query to our ADOS Server, this is the error message I receive.
"Using the Parent, Children, Descendants or Revision properties in a filter or expand is not recommended..Details on recommended query patterns are available here: https://go.microsoft.com/fwlink/?linkid=861060."
Seems this form of oData laid out on this page is bad practice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97a5d24-74dc-c495-5a48-0ccad5a61304
* Version Independent ID: 6e6e297e-8491-243e-6744-f5e96f5b2f20
* Content: [Query for linked work items - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/work-item-links?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/work-item-links.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/extend-analytics/work-item-links.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by roydebalina** [comment]
Can you please provide the OData query or the pattern used?

**Comment by KathrynEE** [comment]
@digikiwam - We need more information about the OData query /pattern used to help resolve your issue.  Otherwise - please report your issue on our [Developer Community page]( https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ksmis-gh** [comment]
@digikiwam  To elaborate, It should not be an error, rather it should be a warning. Descendants are equivalent to a SQL INNER JOIN and as such are costly. It is not recommended but it should still be usable

**Comment by roydebalina** [comment]
Can we close this issue, if there are no further queries?
