### ISSUE TITLE
task enabled

### ISSUE THREAD

**Issue by paulmarshall** [MicrosoftDocs/azure-devops-docs#7508]
Can an expression be used in the enabled property of a task?

I want to use the enabled property to prevent the execution of a task if a build agent.
I don't have access to the build agent so I can't add a "demand" on the agent to assert it has software installed on it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@paulmarshall The `enabled` property takes a boolean value. You can use expressions in the `condition` property. Here's the [relevant schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options).
