### ISSUE TITLE
This task does not list or use service connections properly

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#7510]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad03c70-4014-135f-ffd3-245c08b3ce32
* Version Independent ID: 42a84b54-9ab7-89b2-00b1-efcfc6ba6eef
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@StingyJack Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by StingyJack** [comment]
If I create an Azure Resource Manager service connection for this task like I would for every other release pipeline deployment task it does not work with this task. Yet the task asks for a service connection.

Apparently it needs a special SSH service connection (thats not mentioned anywhere), but that doesn't work like other service connections do and is effectively useless. I can't find any doc's about it either

**Comment by RoopeshNair** [comment]
@vijayma for SSH

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by StingyJack** [comment]
@cxwtool  - this was waiting for MSFT. I didnt leave it idle

**Comment by steved0x** [comment]
@StingyJack We just published a new task reference that is autogenerated from the task source and task metadata that is installed onto each on-premises version as well as regular updates run against the current Azure DevOps Service. This parameter is added to the ssh task in the new reference along with a link to the SSH service connection type. I am reviewing the backlog of tasks to see which ones are resolved now that we have the new task reference.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/ssh-v0?view=azure-pipelines#inputs

Please check out the new reference and let us know what you think.

**Comment by StingyJack** [comment]
LGTM now
