### ISSUE TITLE
Downloadpipelineartifact@2 -- bug?

### ISSUE THREAD

**Issue by greengumby** [MicrosoftDocs/azure-devops-docs#7516]
We have noticed that when we use the DownloadPipelineArtifact@2 specifying the artifact name it seems to correctly download the artifact but the contents get munged..

For instance if I specify a artifact called FooFact the files inside would become.

Original:   bar\testFooFact\run.bat
Becomes: bar\test\run.bat.

Seems to replaces the artifact name?

Very odd.

**Comment by WilliamAntonRohm** [comment]
@greengumby -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by greengumby** [comment]
Referring to the Azure pipeline task DownloadPipelineArtifact@2. 
Seems to be an issue where I have published an artifact correctly and downloading has changed the contents.

**Comment by WilliamAntonRohm** [comment]
@greengumby -- thank you for clarifying.  

@vijayma -- please look into this issue.  That task is in [this article](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops).

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
