### ISSUE TITLE
Location of described repo clean options not provided, please clarify

### ISSUE THREAD

**Issue by syndicatedshannon** [MicrosoftDocs/azure-devops-docs#7528]
Section " https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clean-the-local-repo-on-the-agent " describes various 4 options for cleaning the repo, but I cannot find these options. I'm using Azure Repos Git, and Azure YAML Pipelines, and I suspect the options this section describes are for some other combination of agents/services.

I only see one option available to me; "clean: true | false". The hover message is "Scorch the repo before fetching?". The notes at https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout clarify this flag, "clean: boolean  # if true, run `execute git clean -ffdx && git reset --hard HEAD` before fetching". This corresponds to one of the 4 listed options.

I also checked the options which are found (strangely hidden) in the Pipelines | [Pipeline] | Edit (YAML editor) | ... | Triggers | YAML | Get Sources | Azure Repos Git | Clean. (Side note, please send my condolences to the UX designer that laid this out &lt;grin&gt;.) Here, the hover message is "You can perform different kinds of cleaning of the working directory of your private agent before the build is run." The options are "true" or "false". It's unclear what these do. There are also other probably-helpful repo settings here (shallow fetch, checkout submodules), but it's unclear how these repo options interact with YAML "checkout" definition.

I tried using the Azure YAML Pipeline creation wizard in case I was missing something, but it didn't show any related options.

I found documentation on the Build.Clean Predefined Variable here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#buildclean . Because the documentation states it is deprecated I didn't investigate further, but it's possible this variable has interactions somehow.

Please clarify this documentation. Which options are available for YAML Pipelines, and where are these options found? If found in multiple places, how do the options interact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clone-a-second-repo)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by syndicatedshannon** [comment]
I can guess that there is some magic behind the scenes with the "clean: true | false" option on the pipeline.

Perhaps runs it before each YAML stage (to ensure every agent has this checkout), so a benefit to using the pipeline's outer definition would be that it can be defined once instead of at each stage. 

Also, I remember a difficulty in the past getting a YAML variable respected by the checkout process due to the order of initialization/evaluation, so another benefit of outer definition would be the ability to turn on and off cleaning. For example, running the same build once nightly with the clean option set, to clear the private build agent and verify no errors arise on clean builds... although I guess this would run in a separate build folder, and not perform as desired.

**Comment by syndicatedshannon** [comment]
I also just found https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables Build.Repository.Clean . Unsure if this is deprecated like the other above.

**Comment by syndicatedshannon** [comment]
https://developercommunity.visualstudio.com/comments/680963/view.html

**Comment by msebolt** [comment]
@syndicatedshannon Thank you for your contribution.  

Assigning this to the author for further review.

**Comment by kaanfurkan35** [comment]
Are there any updates regarding this topic?
