### ISSUE TITLE
Azure Devops Wiki Comments

### ISSUE THREAD

**Issue by dalehhirt** [MicrosoftDocs/azure-devops-docs#7560]
This is related to this page:  https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops

The documentation does not address three fundamental issues of comments:

1.  Where are comments stored?
2.  Are comments only applied against a certain published branch of the wiki, or do they show up for all branches?
3.  If the comments are not stored in the git repository, how can we export them?

**Comment by chcomley** [comment]
Hi @dalehhirt, Thanks for reaching out. We'll review and update the article accordingly. Adding @amitkumariiit for assistance and clarification. Thanks again!

**Comment by amitkumariiit** [comment]
Hi @dalehhirt 
Please find the answer below.

> 1. Where are comments stored?

They are stored in the internal database.
> 2. Are comments only applied against a certain published branch of the wiki, or do they show up for all branches?

Comment can be make in any wiki pages.
> 3. If the comments are not stored in the git repository, how can we export them?

This feature doesn't exists.

**Comment by dalehhirt** [comment]
> > 1. Are comments only applied against a certain published branch of the wiki, or do they show up for all branches?
> 
> Comment can be make in any wiki pages.
> 

Well, since this answer didn't make any sense, I had to do my own investigation.  The answer is comments are on a per-branch basis.  If I make a comment on a wiki page on the master branch, they won't show up in another published branch of a file of the same name.

![image](https://user-images.githubusercontent.com/2246127/94163426-b10af680-fe3c-11ea-8ddc-98abd983156c.png)

![image](https://user-images.githubusercontent.com/2246127/94163501-ca13a780-fe3c-11ea-889d-49cdbd7da522.png)

**Comment by chcomley** [comment]
Hi @dalehhirt, thanks for clarifying. I've added some information to the article, which should be live momentarily. Thanks!

**Comment by amitkumariiit** [comment]
Hi @dalehhirt ,
Thanks for clarifying. I had not understood your question correctly earlier.
Yes you are right. It is because comments are associated with the page id and each page has different id even if if published from different branch of a code wiki.

**Comment by chcomley** [comment]
Hi @dalehhirt, circling back on this issue, it looks like it can be closed, based on an article update. Please @ mention me if you have any further feedback or concerns. Thank you and happy new year!
