### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by abelsquidhead** [MicrosoftDocs/azure-devops-docs#7564]
[Enter feedback here]
Docs are out of date. The Build multiple configurations section is referencing the old visual UI while the previous instructions from create your first pipeline link (https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=net%2Cyaml%2Cbrowser%2Ctfs-2018-2)

created a yaml based pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=azure-devops)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@abelsquidhead Thanks for flagging this!
