### ISSUE TITLE
Build validation does not trigger a new build automatically for draft pull requests

### ISSUE THREAD

**Issue by ashamrai** [MicrosoftDocs/azure-devops-docs#7596]
However, documentation does not contain any description of that. This lack enforces questions on the forums like that: https://stackoverflow.com/questions/60666212/triggering-pull-request-builds-automatically-on-draft-pull-requests-in-azure-dev

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by jonathanpeppers** [comment]
General question: "Was this change intentional?"

Before this change, I had the habit of making all my PRs drafts to be sure the CI is green before asking for review.

Is there an option you can set in yaml to get the old behavior?

**Comment by vijayma** [comment]
This was always the behavior for PRs from Azure repos. The same is now true for GitHub repos as well.
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-173-update#github-draft-pull-requests-do-not-trigger-pipelines

**Comment by jonathanpeppers** [comment]
I only use Github, so that is why I noticed something changed recently.

How can I get the old behavior? Is there a setting?

**Comment by vijayma** [comment]
No, there is no setting to change that. You can queue those builds manually.

**Comment by jonathanpeppers** [comment]
So what seems odd to me about this:
1. I open a draft PR on Github
2. I comment `/azp run`
3. 2 hrs later. It's green, yay!
4. Mark the PR "Ready for Review", bringing it out of draft.
5. CI triggers _again_

Should I file a bug? or is this expected?

**Comment by elhoo** [comment]
I also would like to be able to configure that draft PRs should have automatic builds

**Comment by jonathanpeppers** [comment]
For us, at least, this issue has been fixed:
1. Github Draft PRs trigger builds.
2. Bringing a PR out of draft does not trigger a build.

However, we are using DevDiv's instance of Azure DevOps -- maybe someone on the team here would know if the public releases have this?

**Comment by vijayma** [comment]
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-176-update#configure-draft-pr-validation-for-github-repositories. This is rolling out now.
