### ISSUE TITLE
partially successful/warning condition

### ISSUE THREAD

**Issue by msfe** [MicrosoftDocs/azure-devops-docs#7597]
If a task fails with continue on error the job is triggered as partially successful. Is there a condition to pick up on this? I tried with failed() which didn't trigger and succeeded() which worked. But i don't really want it to trigger on true succeeded...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@msfe Did `eq(variables['Agent.JobStatus'], 'SucceededWithIssues')` work for you?

**Comment by msfe** [comment]
Hi,

No that didn't work for me. However, it was possible to extract in this way.

```
dependsOn: JobName1
condition: eq(dependencies.JobName1.result,'SucceededWithIssues')
```

Hope this helps!
