### ISSUE TITLE
"Security" of Microsoft-hosted agents

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/azure-devops-docs#7615]
> For example, an ill-intentioned script or unit test change might leak secrets or compromise the agent machine that's performing the build. 

I'd suggest splitting the two risks and discuss them separately.

> Use a Microsoft-hosted agent pool to build pull requests from forks. Microsoft-hosted agent machines are immediately deleted after they complete a build, so there is no lasting impact if they're compromised.

Otherwise, people might assume this measure mitigates the risk of leaking secrets which it doesn't. People might feel a false sense of security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Thanks for the suggestion. We updated the docs to clarify the two risks and the corresponding mitigations.
