### ISSUE TITLE
ACR 'endpoint myprivate.azurecr.io' not possible w/out preview

### ISSUE THREAD

**Issue by josiahlaivins** [MicrosoftDocs/azure-devops-docs#7623]
Add notice that accessing private ACR repositories requires an endpoint that is in preview currently. 

I was unpleasantly surprised by this and am now having to wait for support to give me access.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@josiahlaivins Could you send me a screenshot of what you ran into or more detailed steps? I'm looking at [this ACR doc ](https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints) for reference.

**Comment by juliakm** [comment]
Closing due to lack of response.
