### ISSUE TITLE
Mermaid support in azure devops server

### ISSUE THREAD

**Issue by chrisbardon** [MicrosoftDocs/azure-devops-docs#7624]
Looking at the documentation here (https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page) implies that I should be able to get mermaid diagrams in a published wiki.  Does this work on Azure Devops Server 2019 though?  I've got a wiki that I've tried to publish from a git repo, but even at 2019 update 1, it's just giving me the plain text.

**Comment by chcomley** [comment]
Hi @chrisbardon, Thanks for your question. Adding @amitkumariiit for assistance. Thanks again!

**Comment by Sebbl22** [comment]
Same here: Just plain text on Azure DevOps Server

**Comment by chcomley** [comment]
Hi @chrisbardon and @Sebbl22, Mermaid diagrams in wikis are only supported in Azure DevOps Services, not in Azure DevOps Server. Make sure your page is set to your version in the top left of your screen and the content will apply to your version. In the Azure DevOps Server version of this article, the Mermaid feature isn't mentioned. Thanks and have a great day!

**Comment by Sebbl22** [comment]
Hi @chcomley,
but Azure DevOps Server 2019 is mentioned, together with some TFS versions which didn't even have a wiki.
![grafik](https://user-images.githubusercontent.com/10319545/81001854-a11c5700-8e48-11ea-9fc7-e59e6b57205c.png)

**Comment by chcomley** [comment]
Hi @Sebbl22, It's mentioned on the left under "In this article" only when the Azure DevOps Services version is highlighted. When you select a different version, that option goes away.

**Comment by anb0s** [comment]
That is really a pity. We are using  Azure DevOps Server 2019 and cannot use Mermaid at own servers.

**Comment by anb0s** [comment]
No Mermaid, no PlantUML no other diagrams are supported?

**Comment by chcomley** [comment]
Hi @anb0s, I appreciate your comments. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **suggest a feature**. That'll get it in front of the developers. Thanks.

**Comment by anb0s** [comment]
@chcomley Thanks! I've created two feature requests for specific formats:
- [Mermaid](https://developercommunity.visualstudio.com/idea/1023488/mermaid-rendering-support-for-azure-devops-server.html)
- [PlantUML](https://developercommunity.visualstudio.com/idea/1023490/plantuml-rendering-support-for-azure-devops-server.html)

an one for generic solution:
- [Extension point for diagram rendering](developercommunity.visualstudio.com/idea/1023520/add-extension-points-for-diagram-rendering-wiki-gi.html)

From my point of view this would be good for "lightweight doc-as-code" feature for agile teams!

**Comment by chcomley** [comment]
@anb0s fantastic, thank you!

**Comment by Sebbl22** [comment]
@anb0s Mermaid is already on the roadmap for Azure DevOps Server 2020, whenever it will be realeased.
https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline
(see 23 September 2019), last item

**Comment by anb0s** [comment]
@Sebbl22 Thank you!

Now we have to wait until it's released...

**Comment by juwens** [comment]
ADS 2020 is released - without mermaid support.

**Comment by anb0s** [comment]
so sad :( it's time to move from Azure DevOps Server to other solution

**Comment by alanbelanger** [comment]
Why oh why oh why??? Seems like it ought to be such an easy thing to include. Pushing the cloud?

**Comment by aaronba** [comment]
Update: Azure DevOps Server 2022 RC1 now has this feature.
https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2022?view=azure-devops#wiki
