### ISSUE TITLE
What is the suggested way of caching in Azure DevOps Server?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/azure-devops-docs#7634]
Hello, 

What is the suggested way of caching in Azure DevOps Server?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops&viewFallbackFrom=azure-devops-2019)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by gojanpaolo** [comment]
Looks like the [Cache task is available for Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops-2019) but this page is not.

**Comment by ramiMSFT** [comment]
@gojanpaolo Thank you for your feedback. The [caching task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops-2019) is supported for DevOps Server. Will add a new section to this article

```YAML
# Cache
# Cache files between runs
- task: Cache@2
  inputs:
    key: 
    path: 
    #cacheHitVar: # Optional
    #restoreKeys: # Optional
```
