### ISSUE TITLE
Permissions to Add comments only

### ISSUE THREAD

**Issue by oulasvirta** [MicrosoftDocs/azure-devops-docs#7639]
We would like to give "Add comment" permissions all of project members at the same time that we want to restrict maintenance of the wiki content only for certain users. 

How can we achieve this or is even possible?

Under the hood... are the wiki comments some integral part of the Git repository related to the wiki or is the commenting funtionality separate entity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @oulasvirta,
Thanks for your question. I've added @amitkumariiit for assistance. Thanks again!

**Comment by amitkumariiit** [comment]
Hi @oulasvirta,
We don't have specific permissions model around the comment.
Comments are stored in the database tables and functionality lie with the same service as in wiki.

**Comment by chcomley** [comment]
@oulasvirta, I've added information to the article about where comments are stored, which should be live momentarily. Please let us know if you have any further questions. Thank you!

**Comment by Coco-Kong** [comment]
@chcomley @amitkumariiit Just wondering whether it is possible to achieve it in the future? Thank you!

**Comment by chcomley** [comment]
@Coco-Kong, you can always check out our [Roadmap](https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline). I'm not aware of anything further.
