### ISSUE TITLE
Apparently Organization-Scopes feeds are now unsupported

### ISSUE THREAD

**Issue by jkoplo** [MicrosoftDocs/azure-devops-docs#7674]
The section above, combined with other documentation, left me scratching my head on how to create a new organization-scoped feed. It's now a legacy feature and not supported in the UI.

https://developercommunity.visualstudio.com/content/problem/859583/can-no-longer-create-organization-scoped-feeds.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f46a54-1fe4-6b64-9479-022f3a06cd70
* Version Independent ID: 7f2e7006-865c-5ace-cd85-3b2936db9ffa
* Content: [Project scoped feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops#feedback)
* Content Source: [docs/artifacts/feeds/project-scoped-feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/project-scoped-feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by davrob01** [comment]
This week Icreated a new Organization in Azure Dev Ops. And I noticed it has an organization-scoped feed by default. So if MS is automatically creating Org scoped feeds for new organizations going forward. I'm guessing they still support it... I am currently debating which direction to go in myself. I'm really not sure.

**Comment by idjohnson** [comment]
For those that run into this going forward.. how you can create org feeds:

```
$ cat payload.json 
{
  "description": "Used for Team Awesome",
  "hideDeletedPackageVersions": true,
  "name": "TeamAwesomeShared",
  "upstreamEnabled": false,
  "fullyQualifiedName": "TeamAwesomeShared",
  "capabilities": "defaultCapabilities"
}
```

then use your PAT
```
curl -X POST -H "Content-Type: application/json" -u myusername:xxxxxxxxxxxxx-my-pat-xxxxxxxxxxxxxxxxxx -d @payload.json https://feeds.dev.azure.com/MYORG/_apis/packaging/feeds?api-version=5.1-preview.1
```

**Comment by ramiMSFT** [comment]
@jkoplo Thank you for your feedback. I 'm glad you found the answer on our Azure DevOps developer community. I'm adding the notes to this issue for future reference.

- All new feeds are recommended to be project-scoped. Creating a new feed through the create feed panel will create a project-scoped feed.

- You can use the [Create Feed API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/create%20feed?view=azure-devops-rest-5.1) to manually create a new organization-scoped feed. You will have to set the default permissions for the new feed manually either by using the [Feed Permission API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/set%20feed%20permissions?view=azure-devops-rest-5.1) or the Artifacts feed settings. Creating new organization-scoped feeds is not recommended.

Therefore, we currently don't support creating a new organization-scoped feeds through the UI.

A "Suggest a feature" ticket has been submitted here: [organisation-scoped-feeds](https://developercommunity.visualstudio.com/idea/863132/organisation-scoped-feeds.html)

You can up vote to increase the priority of this feature. Thank you

**Comment by Yanal-Yves** [comment]
@ramiMSFT, I am new in Azure Artifacts. The way I see team collaboration in my company is to have many small teams using one organization feed. I can see many benefits:
- Allow easy package sharing accros teams
- Avoid every team to configure their own feed
Could you explain why creating new organization-scoped feeds is not recommended?
