### ISSUE TITLE
Multiple custom email addresses

### ISSUE THREAD

**Issue by rasponien** [MicrosoftDocs/azure-devops-docs#7675]
Hello

There is no documentation of sending notifications to multiple custom email addresses.
It can be done by separating email addresses with semicolon. Please update the documentation if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1e33b8c-093d-7e81-ea78-e8ab1d3babd6
* Version Independent ID: f2e2e255-bf18-bd5f-1089-fba5d3f88814
* Content: [How notification email recipients are determined - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/concepts-email-recipients?view=azure-devops)
* Content Source: [docs/notifications/concepts-email-recipients.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/concepts-email-recipients.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @rasponien, Thanks for alerting us. I'll get the article updated shortly. Thanks again!
