### ISSUE TITLE
Better (detailed) description of custom conditions

### ISSUE THREAD

**Issue by LukaszGrela** [MicrosoftDocs/azure-devops-docs#7676]
I think that it is missing the section on available conditions and states of the task that can be used in condition. I'm looking for something that will resemble the built-in "Even if a previous task has failed, even if the build was canceled" condition, but instead of canceled part I need to test for "timeout". I think that section showing what task properties are available would help me to solve it e.g. `or(failed(), timeout())` :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by abatishchev** [comment]
+1. The doc doesn't appear to say anything about most popular checks - for `null` or `''` (empty).

**Comment by abatishchev** [comment]
@WilliamAntonRohm, @juliakm gentle ping.

**Comment by juliakm** [comment]
@LukaszGrela There's no way to specifically check for a timeout. Timeout looks like cancellation to a condition expression.

@abatishchev I'll add an example for a null value/empty string.
