### ISSUE TITLE
--path option documentation

### ISSUE THREAD

**Issue by alasrati** [MicrosoftDocs/azure-devops-docs#7683]
Please consider adding more detailed documentation or an example for the --path option for the "az boards area project create" command. Took a lot of trial and error to work out the proper format for the path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths for a project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?view=azure-devops&tabs=azure-devops-cli#feedback)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@alasrati - Thank you for the feedback. I'm updating the article to clarify the syntax.
