### ISSUE TITLE
Azure devops pipelines are using undocumented IPs

### ISSUE THREAD

**Issue by johku90** [MicrosoftDocs/azure-devops-docs#7684]
I created new release pipeline in azure devops. And when I try to connect sql database by commandline script, I get this error: "Cannot open server '...' requested by the login. Client with IP address '13.94.96.67' is not allowed to access the server."

I tried multiple times, and at least these IPs were used by devops: 52.169.95.204, 40.91.231.36

My old pipeline works though, and it uses documented ip addresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by chcomley** [comment]
Hi @johku90, 
I've reached out to the product group and someone will be in touch with you shortly. Thank you!

**Comment by chcomley** [comment]
Per internal communications, I'm closing this issue. Please feel free to @mention me for any further follow up.
