### ISSUE TITLE
Shortcut for toggle title display is not mentioned

### ISSUE THREAD

**Issue by xtu** [MicrosoftDocs/azure-devops-docs#7686]
Press 't' will show titles only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c79704-c69b-fb70-8000-98266c572d22
* Version Independent ID: 923f10d0-da3a-044e-6eaf-ed063d39ff6c
* Content: [Delivery plan keyboard shortcuts - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/delivery-plan-keyboard-shortcuts?view=azure-devops#feedback)
* Content Source: [docs/boards/plans/delivery-plan-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/delivery-plan-keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@xtu - Thank you for the tip, I'll add it to the article.
