### ISSUE TITLE
Task PublishPipelineArtifact@1 has no input named path

### ISSUE THREAD

**Issue by metoule** [MicrosoftDocs/azure-devops-docs#7701]
As far as I can tell,  PublishPipelineArtifact@1 has the following inputs:

* targetPath
* artifact
* fileSharePath
* parallelCount
* parallel
* publishLocation

and no input named `path`. Could you update the YAML (task) section, and also document all the possible inputs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml-task#downloading-artifacts)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@metoule Thank you for your feedback. `PublishPipelineArtifact@1` task has `targetPath` and `artifactName` as parameters, see [Publish Pipeline Artifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops#yaml-snippet) for more details. Also the updated version of the article will go live shortly.
