### ISSUE TITLE
SSH fingerprints inconsistent

### ISSUE THREAD

**Issue by mpmatti** [MicrosoftDocs/azure-devops-docs#7726]
The fingerprints mentioned in this document seem to be different from the ones listed in SSH keys page in dev.azure.com. This causes confusion and worries of man-in-the-middle attack. Please fix this.

MD5: 97:70:33:82:fd:29:3a:73:39:af:6a:07:ad:f8:80:49 (RSA)
SHA256: SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og (RSA) These fingerprints are also listed in the SSH public keys page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
Those aren't the actual fingerprints. I'll make it more clear.

**Comment by hooooh2** [comment]
![Uploading IMG_0095.jpeg…]()

**Comment by hooooh2** [comment]
https://apps.apple.com/app/id1598909871

**Comment by hooooh2** [comment]
> ### **__** https://apps.apple.com/app/id1598909871
