### ISSUE TITLE
Missing extensibility points for Build

### ISSUE THREAD

**Issue by karelkral** [MicrosoftDocs/azure-devops-docs#7728]
Hello, the next extensibility point is completely missing from this page. Your documentation is in a horrible state!
             "type": "ms.vss-build-web.build-results-tab",
            "targets": [
                "ms.vss-build-web.build-results-view"
            ],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @karelkral, Yes, we agree that our documentation needs a major facelift. We'll be addressing this in the coming months, so stay tuned. Thank you for your feedback, we appreciate it.

**Comment by chcomley** [comment]
This article's been archived. I've added a redirect to the [Contributions overview](https://docs.microsoft.com/en-us/azure/devops/extend/develop/contributions-overview?view=azure-devops) and you can find more up-to-date development information here: https://azdevinternal.azureedge.net/. Thanks for your feedback, we appreciate it.

**Comment by karelkral** [comment]
@chcomley So to this time we had incomplete documentation of extensibility points and now we do not have documentation of extensibility points at all. The original article was archived and I cannot find an equivalent in your links. I am not a Microsoft employee and I do not have access to any of Work items of  https://azdevinternal.azureedge.net/, no access to the linked repository https://github.com/Microsoft/azure-devops-ui. 

**Please fix it!**
