### ISSUE TITLE
Default Value does not match documentation - default is $(Agent.TempDirectory)

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/azure-devops-docs#7729]
we are seeing the default value use the temp directory:

yaml:

```yaml
- task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.0.x'
```

logs:

```
Found version 3.0.103 in channel 3.0 for user specified version spec: 3.0.x
Version 3.0.103 was not found in cache.
Getting URL to download .NET Core sdk version: 3.0.103.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'E:\B\Agent1\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.165.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/874a85a8-de9b-405d-b75e-9c3e9b3ddd0d/eb5f33724a7ba55d47fd12b2f1f8f764/dotnet-sdk-3.0.103-win-x64.zip
Extracting downloaded package E:\B\Agent1\_work\_temp\4c61ab91-723e-48d7-9de2-a6b4d6f17efc.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [Use .NET Core task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by cmeyertons** [comment]
I think this should be fixed. It could cause the next person who runs into this not waste 2 hours.

**Comment by mijacobs** [comment]
@steved0x should this be assigned to someone else?
