### ISSUE TITLE
Gradle example should be updated now that 10842 is marked fixed.

### ISSUE THREAD

**Issue by sarod** [MicrosoftDocs/azure-devops-docs#7743]
Gradle example suggests that a better config should be used once https://github.com/microsoft/azure-pipelines-tasks/issues/10842 is fixed. 

However 10842 is fixed since August 2019. The example should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#gradle)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by AceHack** [comment]
What does the new way look like?

**Comment by Moes81** [comment]
@ramiMSFT @WilliamAntonRohm  Any progress on the docs? Any example you can provide here?

**Comment by ramiMSFT** [comment]
@sarod Apologies for the delayed response. The updated content will go live shortly. Thank you for your feedback!

**Comment by rsilvareberth** [comment]
This problem is resolved? the example with gradle don't work

**Comment by eric-labelle** [comment]
Yeah, I removed all pipeline caching months ago, it just doesn't work and is so slow that you're better without it.
