### ISSUE TITLE
Please Provide Full YAML Schema Definition

### ISSUE THREAD

**Issue by CullenShannon-NavyFederal** [MicrosoftDocs/azure-devops-docs#7744]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops

The runtime parameter for your selected branch includes small text beneath the selection box that reads: Select the branch, commit, or tag. I'd like to add similar instructions to my parameters, but the documentation doesn't specify whether or not this is supported. I'm also interested in multi-select. 

Specifying the full YAML schema would answer these questions.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by steved0x** [comment]
@CullenShannon-NavyFederal We are working on adding more YAML schema examples, but in the meantime have you checked here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#parameters

Let me see if I can get more detail.
