### ISSUE TITLE
Link Broken for explanation of "/remap"

### ISSUE THREAD

**Issue by cb504** [MicrosoftDocs/azure-devops-docs#7753]
The link "phkelley's blog: tf get /remap" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b692dc59-b227-0dad-79f4-f8b8fabad507
* Version Independent ID: 7efc3f73-d605-0521-44ab-0109a563887b
* Content: [Use the Get command to download TFVC files/folders - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-command?view=azure-devops-2019#feedback)
* Content Source: [docs/repos/tfvc/get-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/get-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@cb504 -- thank you for your feedback.  There is related content [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c895ebb8-97e8-4f33-aef3-891f407efda4/tf-command-line-and-remap).

@apawast -- is there a new target for the existing old link to phkelley?

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment]
@MaximMalygin @apawast @WilliamAntonRohm,
The link is working for me. Could you please check if this issue is still actual?
Here is the link: https://docs.microsoft.com/en-us/archive/blogs/phkelley/tf-get-remap

I'm assuming that the docs.microsoft.com was down at the time the issue was created.

**Comment by WilliamAntonRohm** [comment]
Yes, that link works for me as well.  I am closing this issue.

**Comment by EricAllen-tr** [comment]
Requesting a re-open of this issue. As of 2020-12-07, From a Visual Studio 2019 command prompt, typing `tf msdn get` and following the link to <q>phkelley's blog: tf get /remap</q> has a few redirects followed by a `404 page not found`. Can either the direct link in the documentation or the backing redirect at `go.microsoft.com` be updated to direct to the archived copy of the blog on `docs.microsoft.com`?

**Comment by WilliamAntonRohm** [comment]
@EricAllen-tr -- Eric, thank you for the update.  The [destination link](https://docs.microsoft.com/archive/blogs/phkelley/tf-get-remap) in the article is still working for me.  It appears there may be a linkage issue between the command line and the documentation.

@DmitriyKirakosyan -- Dima, please look into this issue.

**Comment by EricAllen-tr** [comment]
In case it helps, the command line takes me to https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/fx7sdeyf(v=vs.120)?f1url=%3FappId%3DDev14IDEF1%26rd%3Dtrue%26l%3DEN-US%26k%3Dk(vs.tfc.sourcecontrol.CommandGet), which has a hyperlink to http://go.microsoft.com/fwlink/?linkid=253390, rather than the docs.microsoft.com @WilliamAntonRohm has above.
