### ISSUE TITLE
How to identify "the new ui"?

### ISSUE THREAD

**Issue by Mikkelcv** [MicrosoftDocs/azure-devops-docs#7762]
Hi,

Several locations refere to "the new ui" in this article, however I have a hard time to identify if I have access to this new UI.
When I look at my own organizations, then I have two, one that is more than a year old and one that is a few weeks. 
The one that is older, there the dialog for updating the service connection looks like the first picture in the article. 
In the newer organization then I get a dialog in the middle of the page. 
The next pictures in the article I have in both organizations, with exception of "Project permissions" on the security page of the service connection, which I do not have in any.

From the article:
- Based on the usage patterns, service connection security is divided into three categories in the service connections *new UI*.
- Now, as part of service connection *new UI*, we are moving to pure RBAC model i.e. using roles.
- This change is applicable only in Azure DevOps Services where *new UI* is available. Azure DevOps Server 2019 and older versions still follow the previous security model.

I have "New service connections experience" activated under preview features in both organizations.

Why is there a difference when I press edit Service Connection?

Also the option "Grant access permission to all pipelines" can only be seen in the older organization, during edit. I can see it in both when creating a new ServiceConnection, why is that?

Regards,
Mikkel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ashokirla** [comment]
Hi @Mikkelcv 

Can you share the new organization details. We will verify why you are getting a dialog instead of pane experience for edit service connection. Ideally, you should see the new edit view along with "Grant access to all pipelines" checkbox both at edit and create time. We will verify why this is happening.

As explained in the documentation, Project permissions feature is in preview mode and we are targeting to enable in the next deployment. After that you will see project permissions.

**Comment by Mikkelcv** [comment]
Hi @ashokirla 

Thank you for taking your time to look at it and explain. 

I have just tried to create a new organization again: cvation-mjv
Created a Project: DevOpsSandbox
And then created a ServiceConnection to Azure of the type:
"Azure Resource Manager"
"using service principal authentication"

Both the new dialog and edit dialog is the popup in the middle of the page.
The Edit dialog does not have the "Grant access to all pipelines" option

**Comment by Mikkelcv** [comment]
I can see that all my organizations are updated to use the same UI now. the panel on the right.
So can close this issue now.
