### ISSUE TITLE
Update Service Fabric Manifests task - Argument pkgArtifactName

### ISSUE THREAD

**Issue by Gerrilicious** [MicrosoftDocs/azure-devops-docs#7764]
Hi,
i'm zipping my applicationpackage to reduce space usage. Now i'm not sure what to supply for the task to run successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b41ba27-633a-37d4-ce78-a1444a99b5b1
* Version Independent ID: 387739fb-276b-d0c9-4848-45426b6e2319
* Content: [Update Service Fabric Manifests task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/service-fabric-versioning?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/service-fabric-versioning.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/service-fabric-versioning.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by abatishchev** [comment]
Yes, I'd like too learn what `pkgArtifactName` does. Doesn't seem though it has anything to do with zipping `pkg` into `sfpkg`

**Comment by Izzmo** [comment]
@abatishchev @Gerrilicious this allows you to specify a specific build artifact to target, since you can output many artifacts from a pipeline.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
