### ISSUE TITLE
Maven Package step fails

### ISSUE THREAD

**Issue by cristhianmurcia182** [MicrosoftDocs/azure-devops-docs#7771]
Hi, when trying to execute the pipeline I get the following error:
##[error]Unhandled: Not found mavenPOMFile: /home/vsts/work/1/s/pom.xml

By default the task is set to:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

I tried different mavenPomFile paths with no luck

**Comment by WilliamAntonRohm** [comment]
@cristhianmurcia182 -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
