### ISSUE TITLE
Documentation for conditional expressions (read: if) in pipelines and templates is not clear about the scope of the condition

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/azure-devops-docs#7792]
The documentation for pipeline and template expression syntax is not clear when it comes to the scope of a conditional expression `${{ if ... }}`

Some of the documentation [shows a conditional expression without an accompanying inverse compliment expression](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditionally-assign-a-variable) **(read: if w/o else)** and some of the documentation [has this explicit inverse compliment](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditionally-set-a-task-input) **(read: if ... else ...)** ([ex2](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#conditional-insertion)). 

There is no documentation explaining how the scope of these conditional insertions is managed. For instance, if I want to define a task in my template and have it conditionally inserted into the expanded pipeline based on the value of a boolean parameter, the [documentation]() would **suggest** that I need to duplicate every other task after the condition so that they appear in the scope of both the `true` and `false` cases where the conditional task only appears in the `true` case.

Please add documentation for how the scope of conditional expressions is closed.

I understand that I can use the conditional execution of the task to not run it based on the bool, but I don't want the task expanded at all unless the boolean is true, and documentation doesn't show me how to do that.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
