### ISSUE TITLE
Additional Related Article

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/azure-devops-docs#7805]
Please add this - https://docs.microsoft.com/en-us/azure/devops/server/admin/service-accounts-dependencies?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#related-articles)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@PrometheusRising1 -- thank you for your suggestion.  I have updated the document.

@KathrynEE -- please review [private PR 1194](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/11940).
