### ISSUE TITLE
Unable to set name field when using classic release.

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/azure-devops-docs#7813]
I was sent to this documentation page when adding a task of this type in classic release. Classic release doesn't allow you to set the name field which is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@haymansfield -- thank you for your feedback.  Please add a link to the source page that sent you here.

**Comment by jstawski** [comment]
I am having the same issue! How do I access the file when using the classic editor? I can't set the name

**Comment by haymansfield** [comment]
Hi Jonas,

As a workaround I found you could access the file directly from the agent using $(Agent.TempDirectory)

Thanks,
Andrew

**Comment by WilliamAntonRohm** [comment]
@haymansfield -- Andrew, thank you for that workaround.
