### ISSUE TITLE
Not obvious deployment goes to $(Pipeline.Workspace) instead of $(System.DefaultWorkingDirectory)

### ISSUE THREAD

**Issue by Izzmo** [MicrosoftDocs/azure-devops-docs#7837]
This is painful... it's not consistent that you decide to go to the root working directory instead of the default working directory for deployment jobs. Makes no sense. Make it more obvious in the documentation please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by dingobar** [comment]
I agree, took me long enough to figure this out.
This is what the docs say:
> Deployment jobs use the $(Pipeline.Workspace) system variable.
Not clear in my opinion.
