### ISSUE TITLE
Relative links to SVG files in the same repository are not supported

### ISSUE THREAD

**Issue by vadym-kl** [MicrosoftDocs/azure-devops-docs#7858]
It is possible to include SVG image via link to external server into Markdown file:
```
![410](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg)
```
however relative links will not render
```
![410](./410.svg)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @vadym-kl, Thanks for your feedback. Adding @amitkumariiit for confirmation. Thanks again!

**Comment by amitkumariiit** [comment]
Hi @vadym-kl 
SVG does render on the relative link those are internal to wiki only. To make it relative you need to attach the svg file to the wiki (by drag-drop or using markdown toolbar menu) and then you need to refer the svg file like something below. (just a sample)
![svg-file.svg](/.attachments/svg-file-320c608b-a566-4b77-ba4e-b647cc234ce7.svg)

**Comment by chcomley** [comment]
Hi @vadym-kl, Please @mention amit if you have any further questions. Thanks for reaching out!

**Comment by vadym-kl** [comment]
@amitkumariiit, I was hoping to use SVGs not in wiki pages, but in ADO repositories. There it does not work.

**Comment by Aaron-Corp00** [comment]
@amitkumariiit, @chcomley I've run into this issue as well. I would like to be able to display SVGs with internal documentation created in Markdown. This would be highly preferred over using static images as SVGs are smaller than images and can dynamically resize. If this is not the correct repo to note this concern, do you know which repo I could post this issue to?

**Comment by ericjmiller** [comment]
I too would love to be able to add a coverage.svg to my README in ADO.  It is always a broken link.

**Comment by seangwright** [comment]
@amitkumariiit We use SVGs generated by <https://www.diagrams.net/> to represent the infrastructure topology for an application. We can store and display these in a wiki, but documentation tends to stay more up to date the closer it is to the thing is represents or covers (eg the code).

So, having the ability to render these in markdown files displayed in the Files view of a repo or on a Project landing page in DevOps (when a markdown file is selected as the source for that page), would be very helpful.

It's poor UX/DX to have support of SVG rendering in wikis but not in other areas of the platform that render markdown.

**Comment by vadym-kl** [comment]
@chcomley Hope you don't mind reopening this issue given that it is an issue in context of ADO markdown rendering for repositories, but not wiki's and it is still not addressed.

**Comment by chcomley** [comment]
I absolutely understand @vadym-kl. @amitkumariiit can you please help us further? Thanks so much!

**Comment by amitkumariiit** [comment]
SVGs are not supported in repository (Files) . This should go a new feature request in repo. 
Its better to open a feedback request in the dev community here for ADO https://developercommunity2.visualstudio.com/report?space=21&entry=suggestion

**Comment by chcomley** [comment]
I've made an update to the doc, mentioning that we don't support SVG files. If you haven't already, I recommend submitting a feature request here:  https://developercommunity2.visualstudio.com/report?space=21&entry=suggestion
Thank you!

**Comment by MartinWickman** [comment]
Well, I see that the returned svg-file from the `<src>` tag has content-type `text/plain`. This is clearly wrong. 

Adding `&sanitize=true` at the end of the `src` tag works. So the fix should be simple enough. The returned svg now has proper content-type.

**Comment by Aaron-Corp00** [comment]
@amitkumariiit, @chcomley: Has there been any progress on this feature? The above link from @MartinWickman shows this functionality has been requested since Oct 24, 2018 and the requested change from [John Peterson](https://developercommunity.visualstudio.com/user/342193/profile), looks to be a working solution.

**Comment by chcomley** [comment]
@aaronhallberg or @bjanousek, do you have any insight to offer? Thanks

**Comment by janheindejong** [comment]
I agree, this would be a very useful feature to have.
