### ISSUE TITLE
packages is not an option resources

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/azure-devops-docs#7861]
it's confusing to see documentation about 'packages', while it's not a valid option 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@gintuoklis -- Gintautas, thank you for your feedback.

@juliakm -- Julia, if this assertion is correct, I can remove all references to "packages" from that article for you.

**Comment by juliakm** [comment]
@gintuoklis I'm reaching out to the product team to get more information on this.

**Comment by Justin-DynamicD** [comment]
Blog post released 4/28 once again mentions packages as a valid resource option.
https://devblogs.microsoft.com/devops/announcing-general-availability-of-azure-pipelines-yaml-cd/

This is actually a pretty big ask, so I'm holding my breath it was perhaps stealth rolled out.

**Comment by Justin-DynamicD** [comment]
dirty update:

resources:
  packages:
    - package: coolname
       <...>

This actually appears to work ... except I cant seem to guess what params it wants. This wqould be really _REALLY_ cool to know

**Comment by juliakm** [comment]
@gintuoklis and @Justin-DynamicD This feature is being deployed now and may not be available for your organization yet.  I'll get more info on the required parameters.

**Comment by gintuoklis** [comment]
hi @juliakm, 
I found examples within your design [documents](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md)

There you have parameter **Connection**
`connection: string   # service connection for your package repo.`

It is unclear how to use it, in case you want to download universal package hosted within the same project. Could you please make inquiries about it as well?

**Comment by HumanBug** [comment]
Hi @Justin-DynamicD 

Not the best and especially in this case, but sometimes it can help.
You can find the Yaml schema under https://dev.azure.com/{OrgName}/_apis/distributedtask/yamlschema?api-version=5.1

There I found these for packageResource.

"packageResource": {
      "type": "object",
      "properties": {
        "package": {
          "description": "Alias of package artifact",
          "$ref": "#/definitions/referenceName"
        },
        "type": {
          "description": "Type of the package. Ex - NuGet, NPM etc.",
          "$ref": "#/definitions/nonEmptyString"
        },
        "connection": {
          "description": "Name of the connection. This connection will be used for all the communication related to this artifact.",
          "$ref": "#/definitions/nonEmptyString"
        },
        "name": {
          "description": "Name of the package",
          "$ref": "#/definitions/nonEmptyString"
        },
        "version": {
          "$ref": "#/definitions/nonEmptyString"
        },
        "tag": {
          "$ref": "#/definitions/nonEmptyString"
        },
        "trigger": {
          "description": "Trigger a new pipeline run when a new version of this package is available.",
          "$ref": "#/definitions/packageResourceTrigger"
        }
      },
      "additionalProperties": false,
      "firstProperty": [
        "package"
      ],
      "required": [
        "package",
        "type",
        "connection",
        "name"
      ]
    }

**Comment by oliverstopp** [comment]
@juliakm any update on this?

**Comment by juliakm** [comment]
@oliverstopp - I'm still working on tracking down more information. In the meantime, here's an example of a working pipeline that uses a GitHub package resource. 

```yaml
resources:
  packages:
    - package: contoso
      type: npm
      connection: pat-contoso
      name: yourname/contoso 
      version: 7.130.88 
      trigger: true


pool:
  vmImage: 'ubuntu-latest'

steps:
- getPackage: contoso 
```

**Comment by oliverstopp** [comment]
@juliakm Thanks for the update.

Do you have any other examples of using a universal package and if the feed is within the same DevOps project what sort of connection needs to be set up?

**Comment by johncrim** [comment]
@oliverstopp - I want to know the same. I posted it here in case that helps:

https://developercommunity.visualstudio.com/idea/1154402/support-universal-packages-as-pipeline-resources.html

**Comment by juliakm** [comment]
The article includes [GitHub packages](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-packages) now. I apologize for not updating the issue earlier.  

For the question about universal packages, I'd recommend looking at the [Universal Packages task](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml#download-a-universal-package).
