### ISSUE TITLE
Schedule of change request - documentation format issue

### ISSUE THREAD

**Issue by acds** [MicrosoftDocs/azure-devops-docs#7868]
Were using:
ServiceNow: New York release - patch7-02-25-2020_03-02-2020_2243!
DevOps plugin: 4.161.0

per [Integrate with ServiceNow change management - Configure a Release Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops#configure-a-release-pipeline)

We believe from trial and error and SN variable configuration options the supported format are:
<img width="808" alt="Screen Shot 2020-04-08 at 11 53 23 AM" src="https://user-images.githubusercontent.com/1319833/78822365-cd4ed000-798f-11ea-8de1-fdd8360a1180.png">
note: no `z` option it seem for the last format set

We can only get `MM-dd-yyyy hh-mm-ss` to work.

The documented format of `yyyy-MM-ddTHH:mm:ssZ` fails with a ServiceNow, error as do other formats per above.

As an aside we set these dynamically (with Powershell):

```Powershell
$planned_start_time = (get-date).AddHours(4)
$planned_end_time = $planned_start_time.AddHours(1)
$requested_time = (get-date) 

$time_format = "MM-dd-yyyy HH:mm:ss"

Write-Host "##vso[task.setvariable variable=planned_start_time] $($planned_start_time.ToString($time_format))"
Write-Host "##vso[task.setvariable variable=planned_end_time] $($planned_end_time.ToString($time_format))"
Write-Host "##vso[task.setvariable variable=requested_time] $($requested_time.ToString($time_format))"
```

We're also using the REST api to update the release so it's picked up in other stages, given the issue #4729 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07f29c5-affb-47bb-5f68-fc49e691c741
* Version Independent ID: 661d3781-8784-868d-261f-1e994a154a35
* Content: [Control deployments by using ServiceNow - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/servicenow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/servicenow.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by acds** [comment]
Please see comment here https://github.com/MicrosoftDocs/azure-devops-docs/issues/4729

**Comment by mijacobs** [comment]
@azooinmyluggage Can you take a look?
