### ISSUE TITLE
Approval pending Slack notifications no longer have links

### ISSUE THREAD

**Issue by tonycosentini** [MicrosoftDocs/azure-devops-docs#7869]
It looks like links stopped showing up in the approval notification Slack messages. I was actually testing some deploy pipeline changes when this happened so I have a fairly precised window of time for when it started - we have a notification from 1:08 PM UTC that *does* have a clickable link and the next deploy at 1:29 PM does not have a clickable link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by tonycosentini** [comment]
Here's a screenshot to show the change:
![image](https://user-images.githubusercontent.com/23467/78844911-c2507a00-7a39-11ea-9a50-4bff11381a55.png)

Time in the screenshot is in Taiwan, I converted it to UTC in the issue description.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by tonycosentini** [comment]
Feedback / bug report issue (in case anyone ends up here from Google) - https://developercommunity.visualstudio.com/content/problem/987256/approval-pending-slack-notifications-no-longer-hav.html
