### ISSUE TITLE
Remove a VM from an Environment - Not up to date for Windows machine?

### ISSUE THREAD

**Issue by albertromkes** [MicrosoftDocs/azure-devops-docs#7875]
`./configure.sh remove` doesn't seem to work on a Windows machine. Instead you have to run `./configure.cmd remove` (and then supply your token)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@albertromkes -- Albert, thank you for your feedback. 

@juliakm -- Julia, please review [private PR 1234](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1234).  What is your preferred wording for supplying a token?
