### ISSUE TITLE
Task breaks folder structure when downloading pipeline artifact

### ISSUE THREAD

**Issue by leinoaa** [MicrosoftDocs/azure-devops-docs#7880]
If you are downloading a pipeline artifact (from another pipeline) and the name of the artifact is used in the folder structure of the artifact, it can cause the following issues.

Folder level removed, file renamed:
Solutions/ThisIsAnArtifact/url.runsettings
-&gt; ThisIsAnurl.runsettings

Folder level removed: 
Solutions/ThisIsAnArtifact/Obj/...
-&gt; Solutions/ThisIsAnObj/...

So it seems that the artifact name is deleted from the folder structure, which may result in lost folder-levels, changed folder names and changed file names. And the breaking only happens for only the folder that has similarities with the artifact name, rest of the folders stay as they should. Also if you check the built artifact, there the folder structure is correct. So the copying breaks it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
