### ISSUE TITLE
Options for TFVC CI triggers are not mentioned

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/azure-devops-docs#7890]
I found that below options for TFVC CI triggers are not mentioned
* Continuous integration
* Batch changes
* Path filters

You can find the documentation [Azure Repos Git # CI triggers # Classic](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=classic#batch-changes)

The documentation screenshot
![image](https://user-images.githubusercontent.com/6244148/78961941-a4604380-7b25-11ea-88bf-b81aad4bd20f.png)

Note that: I got the **Branch filters** section removed from the screenshot as it's not applicable for TFVC. And I think the font size of **Path filters** is incorrect, it should be the same as **Batch changes**. it should be typo in your markdown file. 
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: febd44ab-caac-85c9-23dc-c9d5fdc14891
* Version Independent ID: e08a8970-baaa-012c-cc98-827a49cd8000
* Content: [Build TFVC repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/tfvc?view=azure-devops#ci-triggers)
* Content Source: [docs/pipelines/repos/tfvc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/tfvc.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ToMakeSense Thank you for letting us know, I am adding some sections to TFVC triggers and fixing the font size on `Path filters`.
