### ISSUE TITLE
Needs to explain case of "Repos" not visible because of user status

### ISSUE THREAD

**Issue by manukautech** [MicrosoftDocs/azure-devops-docs#7891]
Referring to step 1 "From your web browser, open the team project for your Azure DevOps organization and choose Repos, then Files."
This page needs to clearly state that if "Repos" is not visible then you are a "StakeHolder" rather than a "Basic" user and this is probably because the Organisation owner has used up the free allocation of 5 "Basic" users. 

The 5 free Basic users rule needs to be better explained. The student also needs a better error message when attempting to clone as a "StakeHolder" from within Visual Studio. The present message is:
'Git failed with a fatal error, repository "https://dev.azure.com/etc-etc-etc" not found.'
A suggested better replacement message:
'​Gimme money! This 'Organisation' has hit its free use limit of 5 Basic Users!'

​Digging deeper I discover that to have more "Basic" members I need to pay 9.08 per month per student. That is not going to happen on an education budget in the best of times and certainly not as a surprise hit. Azure DevOps invites use from within Visual Studio and other documentation. There needs to be fair warning that it costs money for more than 5 effective participants so we can do appropriate student project training and demonstrations based on small group work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/clone.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@manukautech -- John, thank you for your considered feedback.  Please [submit your ideas]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

cc @apawast for awareness
