### ISSUE TITLE
Azure Pipeline Task Inovke Azure Function Misleading

### ISSUE THREAD

**Issue by predatorian3** [MicrosoftDocs/azure-devops-docs#7896]
# Issue

The documentation for Invoke Azure Function Pipeline Task says that it can be used for both Build and Release pipelines, but the Demands immediately say its only usable for Release pipelines. Which one is it? 

## References 

* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-function?view=azure-devops

**Comment by steved0x** [comment]
@predatorian3 The demands section is correct, I'll get this fixed, and I believe there may be a few more since I fixed another one yesterday, this was due to a bulk text change to the task intros. Thank you for letting us know.

**Comment by predatorian3** [comment]
Dang. I was hoping that we could use the Invoke Azure Function in a generic build pipeline.

**Comment by steved0x** [comment]
@predatorian3 If you look at the task.json for a task you can see where it can run, this one runs on Server and ServerGate, (which are for release pipelines, let me see if I can find an exact definition) but it doesn't list Agent which would be for a generic build pipeline.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFunctionV1/task.json#L14

![image](https://user-images.githubusercontent.com/1580889/79003976-c6f05d80-7b21-11ea-94fb-8cfc51e862c8.png)

You could file a feature request to ask for that task to be able to be run on a build pipeline [here](https://developercommunity.visualstudio.com/spaces/21/index.html) or you could file an issue on the [tasks repo](https://github.com/microsoft/azure-pipelines-tasks) to add that functionality.

**Comment by steved0x** [comment]
The 4 types of runsOn are:
* Server
* ServerGate
* DeploymentGroup
* Agent (this is the default and is the type I believe you are needing)

I've created a work item to see if I can add some more guidance about these (but there is some [here](https://github.com/microsoft/azure-pipelines-tasks/blob/0dc1d8b7255808bf506217428a80c28e1ab6f4e6/docs/authoring/gates.md) and [here](https://github.com/microsoft/azure-pipelines-tasks/blob/86def2bec0a194057b739c6165a7720d1aa57093/docs/authoring/servertaskauthoring.md)

I'm closing this issue and when the Azure Function task is updated to remove the incorrect intro sentence, that commit will be linked here. Thank you and sorry that you ran into trouble.
