### ISSUE TITLE
Cannot access mseng ADO org link

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#7902]
The roadmap item listed in Q&A is in the mseng org, which is not publicly accessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d92157-ab0e-b538-c284-32c70da8e2dd
* Version Independent ID: 86d6c2eb-5931-27ee-3df9-a1d0889d510a
* Content: [Define features and epics, organize backlog items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/define-features-epics?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/backlogs/define-features-epics.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/define-features-epics.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@GaTechThomas Can you try this link? We'll take a look at the article to fix the link (it looks like we may have put in the wrong format) but in the meantime this should take you to it:

https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1666194

There is not much in there however, just the title info.

**Comment by KathrynEE** [comment]
@GaTechThomas - the Project, AzureDevOpsRoadmap, is a public project which allows anonymous users to view work items.
