### ISSUE TITLE
New Work Item widget issue...

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#7904]
The New Work Item widget does not tie to the team's default area path as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of widgets you can add to a dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops#related-articles)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@GaTechThomas -- it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
