### ISSUE TITLE
Azure6c2f260d-9321-d669-172d-01289c233263

### ISSUE THREAD

**Issue by Samboy1990** [MicrosoftDocs/azure-devops-docs#7909]
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by WilliamAntonRohm** [comment]
@Samboy1990 -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
@Samboy1990 -- please clarify your title change, and add a link in a comment for the docs.microsoft.com topic you're reading.

**Comment by WilliamAntonRohm** [comment]
@Samboy1990 -- please leave this information in a comment in this issue.
