### ISSUE TITLE
Deprecated links

### ISSUE THREAD

**Issue by celambert** [MicrosoftDocs/azure-devops-docs#7915]
This site references deprecated docs and tasks. Worse is, the deprecated docs below also reference this site for 
alternative docs. Can you please update to ensure docs are up to date?

- https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-simple-cloud-load-test?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/cloud-based-load-test?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-jmeter-load-test?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/cloud-based-web-performance-test?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@celambert -- Charles, thank you for your feedback.  It appears to me that this article is clear on what is deprecated, including the links to other deprecated content.  Please clarify your concern.

**Comment by celambert** [comment]
You are correct. It is clear, bad case of skimming and not reading. Thanks @WilliamAntonRohm
