### ISSUE TITLE
Missing `az devops security permission update` 

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#7927]
In the tools used to set permissions there is no mention to the `az devops security permission` Azure CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa32191d-6d0a-058f-2ffe-3ce1b58e2c59
* Version Independent ID: 858d1ed3-b2af-699f-9d51-86ac0962086b
* Content: [How are permissions and groups defined? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page%2Ccurrent-page#feedback)
* Content Source: [docs/organizations/security/about-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jessehouwing - Thank you for this feedback. I will update the article to reflect usage of the az devops security commands which are documented here: [Add and manage security groups](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-manage-security-groups?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops) and [Manage tokens and namespaces](https://docs.microsoft.com/en-us/azure/devops/organizations/security/manage-tokens-namespaces?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops).
