### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by f3** [MicrosoftDocs/azure-devops-docs#7928]
The image [in the section for creating a publisher](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#create-a-publisher), is broken; the only thing shown on the page is:
```markup
![Create publisher](media/create-publisher.png)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#create-a-publisher)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by WilliamAntonRohm** [comment]
@apawast -- Apeksha, please review [private PR 1253](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1253).

**Comment by steved0x** [comment]
@WilliamAntonRohm Thank you for fixing this, @f3 Thanks for letting us know, this will be live shortly.
