### ISSUE TITLE
Documentation Outdated for SQL Server 2017+

### ISSUE THREAD

**Issue by seanwhitepc** [MicrosoftDocs/azure-devops-docs#7934]
SS2017 has Reporting Services moved to its own installer and this documentation does not include steps for how to configure that setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dece1d7-ee7c-7f55-976e-1edee80f60b6
* Version Independent ID: a5ab1200-d7ba-b70b-1d9a-26e5ddde3c85
* Content: [Add a report server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/admin/add-a-report-server?view=tfs-2018#feedback)
* Content Source: [docs/report/admin/add-a-report-server.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/admin/add-a-report-server.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@seanwhitepc - Thank you for the feedback.  I'll update the article to point to the instructions provided here: [Install SQL Server Reporting Services](https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/install-reporting-services?view=sql-server-2017) article.
