### ISSUE TITLE
provide a json that auto-updates like with other Azure services

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/azure-devops-docs#7936]
parsing a webpage is cumbersome and too prone for error.

Please provide a json download of all whitelisted domain urls and ip ranges like other azure services do so that we can programmatically keep our settings up-to-date, or amend the json that is being referred to in this article.

"Azure IP Ranges and Service Tags" does not contain some delcared ranges in this article (like 13.107.6.0/24), nor does it actually contain an ADO section.  Following a random article and hand assembling a whitelist is just not a reliable way to build white lists anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
