### ISSUE TITLE
Some checks are missing in the YAML section. I have a servicenow plugin installed for my organization. The service now change management task is visible in the release pipeline gate as shown below, but couldn't see under environment to integrate with multistage yaml pipeline 

### ISSUE THREAD

**Issue by karty333** [MicrosoftDocs/azure-devops-docs#7938]
Release Gate
![image](https://user-images.githubusercontent.com/33003618/79297234-ed970580-7f20-11ea-9081-4740a9c99d3c.png)
It is missing in environment check
![image](https://user-images.githubusercontent.com/33003618/79297275-02739900-7f21-11ea-9c17-05c85d6b9372.png)

Do we have any solution for this

**Comment by karty333** [comment]
@RoopeshNair @shashban , Do we have any solution for the above issue

**Comment by JordanRBG** [comment]
This is also the case for us in our Azure DevOps Services instance; is there any update on this?

Imagine a lot of people will want to use this feature against environments.

**Comment by JordanRBG** [comment]
@RoopeshNair @shashban @msebolt Any update on this?

**Comment by shashban** [comment]
@JordanRBG @karty333  The serviceNow support for YAML pipelines was recently released. Can you confirm if you are now unblocked on this?

**Comment by JordanRBG** [comment]
Hi @shashban, the ServiceNow gate now appears. Thanks for your help on this 👍

**Comment by shashban** [comment]
Thanks for a confirmation. I am closing this issue.
