### ISSUE TITLE
Add full support of Mermaid diagrams

### ISSUE THREAD

**Issue by LordGordonQ** [MicrosoftDocs/azure-devops-docs#7941]
It is possible to have full support of all Mermaid's diagrams? It would really help to use the wiki for better specifications and design documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @LordGordonQ, Thanks for reaching out. I've followed up with the product group and will be in touch soon.

**Comment by chcomley** [comment]
Hi @LordGordonQ, 
Enabling all features of a mermaid isn't currently possible and needs development. This hasn't been prioritized. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Suggest a feature**. Thank you!
