### ISSUE TITLE
Operational Differences outdated

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/azure-devops-docs#7946]
The table indicates that Wiki pages in repositories that are "publish code as Wiki" can't be edited in the Wiki UI, but this appears to be incorrect, as you can now do this. There are potentially other pieces on this page that are outdated too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MatthewSteeples, Thanks for your feedback. We'll update the article shortly and let you know. Thanks again.
