### ISSUE TITLE
An editor is mentioned twice in the "Preparation and required setup for this tutorial" step.

### ISSUE THREAD

**Issue by Falven** [MicrosoftDocs/azure-devops-docs#7947]
* A text editor. For many of the tutorials, we used Visual Studio Code, which can be downloaded here
...
* Visual Studio Code for intellisense and debugging support, which can be downloaded here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@Falven -- Francisco, thank you for your close reading.

@chcomley -- Chrystal, please review [private PR 1254](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1254).
