### ISSUE TITLE
provide a direct download for the json

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/azure-devops-docs#7949]
This json is updated weekly, but the download involves clicking a confirmation, and resulting in a time-stamped file if you direct download.

Again:  This is makes automating needlessly difficult.  Why dont we have an RSS feed or a static file? like AWS or GCP uses?  This is so 20 years ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by WilliamAntonRohm** [comment]
Please see #7936.
