### ISSUE TITLE
It's not clear why Stage runs parallel or not

### ISSUE THREAD

**Issue by adamtuliper** [MicrosoftDocs/azure-devops-docs#7955]
Both examples utilize 
  stages:
- stage: Build
and yet one runs in sequence and the last one runs in parallel but there's no description as to what makes this different than the one above it other than steps are omitted for brevity. 
stages:
- stage: BuildWin
  displayName: Build for Windows
- stage: BuildMac
  displayName: Build for Mac
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@adamtuliper -- Adam, thank you for your feedback.  As you noted, the article states:
> This example runs two stages in parallel. For brevity, the jobs and steps are omitted.

The previous example has jobs and steps under the stages, and the middle stage of that example defines two parallel instances of `job` under `jobs`.
```
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
```

It looks to me like the next example behaves the same way, with two parallel instances of `stage` under `stages`.  There could be multiple jobs under each stage, some defined in parallel, as shown in the first example.

I am closing this issue now.  You are welcome to @ mention me for any followup. We hope to hear from you again.
