### ISSUE TITLE
Error calling docker-compose from a powershell script

### ISSUE THREAD

**Issue by guillaume86** [MicrosoftDocs/azure-devops-docs#7958]
I have an issue when calling docker-compose from a powershell task in a pipeline.
It seems docker-compose writes to stderr and it makes the WinRM invocation fail.
I tried `failOnStderr: false`, `-ErrorAction Continue`, `2&gt;&1 | ForEach-Object { "$_" }` to redirect err to out but none seems to work.
Here's the error in the pipeline logs (not helpful):

+ CategoryInfo          : NotSpecified: (Pulling admin-cli-base ... :String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError

The docker-compose task is not an option for me because I need to do some stuff between docker-compose calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by guillaume86** [comment]
Seems like "pwsh" doesn't have from this issue, I'm switching to it.

**Comment by WilliamAntonRohm** [comment]
@guillaume86 -- Guillaume, thank you for your feedback and workaround. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit this bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

cc @vtbassmatt for awareness
