### ISSUE TITLE
Source branchname for artifacts when building against a pull request

### ISSUE THREAD

**Issue by nishants** [MicrosoftDocs/azure-devops-docs#7962]
Release.Artifacts.{alias}.SourceBranchName is returned as`refs/pull/<id>/merge` when consuming artifacts for a release pipeline. 

Can you please suggest how can I get the source branch name of the pull request instead ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by SinZ163** [comment]
While there isn't a 1:1 mapping of SourceBranchName, there is a 1:1 mapping for SourceBranch, which is `System.PullRequest.SourceBranch` which will give you values like `refs/heads/feature/branch-name`

**Comment by WilliamAntonRohm** [comment]
@nishants -- Nishant, thank you for your question.

@SinZ163 -- Trent, thank you for answering.

You're welcome to [add this feedback here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
