### ISSUE TITLE
Part of the text in the diagrams is unreadable in dark theme

### ISSUE THREAD

**Issue by jfranki** [MicrosoftDocs/azure-devops-docs#7963]
![image](https://user-images.githubusercontent.com/6547157/79471091-72a61b80-8002-11ea-88cb-93ac882efc72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d3f358-8883-0c64-5860-620eba5ff335
* Version Independent ID: 0d4d21a8-cfc4-8f0c-5d0d-dab651813804
* Content: [Constructing a complete package graph - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/package-graph?view=azure-devops)
* Content Source: [docs/artifacts/concepts/package-graph.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/package-graph.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@jfranki -- thank you for your feedback. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
