### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by whatisthejava** [MicrosoftDocs/azure-devops-docs#7965]
Hi, its not clear that Step 3: Create the extension manifest file should be done in the home directory (NOT BuildAndReleaseTask) folder 

I think if you make it clear VSO should be opened from the home folder and not the buildAndReleaseTask this would prevent the issue

You also dont state that the images folder with extension-icon.png needs created and this causes an issue when running  tfx extension create --manifest-globs vss-extension.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @whatisthejava, Thank you for your feedback. I've created a user story for my backlog to address this. Thanks again!

**Comment by chcomley** [comment]
I'm closing this issue, however please @mention me if you have any further feedback or questions. Thanks.

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance/assistance, thank you!

**Comment by chcomley** [comment]
I've just published an update, which should be live shortly. Thanks!
