### ISSUE TITLE
System.PullRequest.SourceBranch example should have refs/heads/ prefix

### ISSUE THREAD

**Issue by ian-craig** [MicrosoftDocs/azure-devops-docs#7970]
The `System.PullRequest.SourceBranch` is described with an example value `users/raisa/new-feature`

Variable | Description
-- | --
System.PullRequest.SourceBranch | The branch that is being reviewed in a pull request. For example: **users/raisa/new-feature**. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy.)

However, if you create a branch called `users/raisa/new-feature` and a pull request from that, the actual value in System.PullRequest.SourceBranch will be `refs/heads/users/raisa/new-feature`

Please update the example to match actual behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review [private PR 1266](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1266).

**Comment by adrian-skybaker** [comment]
The `refs/heads/` prefix is not present for Github pull requests, so the documentation is now incorrect for Github users.

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please advise.
