### ISSUE TITLE
Environment Resource Type "appService"

### ISSUE THREAD

**Issue by connelhooley** [MicrosoftDocs/azure-devops-docs#7971]
Environment Resource Types are documented on this page as follows:

``` yml
resourceType: string      # type of the resource you want to target. Supported types - virtualMachine, Kubernetes, appService
```
I can't see a way to create an "appService" resource. It wasn't created for me automatically and the ADO UI only allows me to create VM or Kubernetes resources. Is this actually supported? These two are the only options documented here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#environment)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@connelhooley -- Connel, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review [private PR 1319](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1319).
