### ISSUE TITLE
extends keyword missing

### ISSUE THREAD

**Issue by timothies** [MicrosoftDocs/azure-devops-docs#7972]
I couldn't find reference in here to the syntax for the extends: keyword (as in extends a template).   I think it's a pipeline level keyword as shown in the example here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pipeline)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by beatcracker** [comment]
Related: https://github.com/microsoft/azure-pipelines-yaml/issues/430

**Comment by juliakm** [comment]
@beatcracker I've confirmed with the product team that currently pool cannot be included in the top level pipeline when that pipeline uses extends. I'll update the docs but just wanted to let you know this is something that's being looked at.

**Comment by jikuja** [comment]
Seeing that this is not fixed on the product itself will there be a documentation update at some point? I also wrote templates with pool definition on the pipeline level and was really confused about the error messages.

**Comment by ramiMSFT** [comment]
@timothies Thank you for your feedback! Major updates in progress for the YAML schema. Stay tuned!
This [article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template) contains good examples on how to use `extends`

**Comment by addmnotlob** [comment]
I think the documentation might need updating here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/extends?view=azure-pipelines#examples

pool is included in the template.yml in the example

**Comment by WilliamAntonRohm** [comment]
@addmnotlob -- thank you for your follow-up.  Please provide additional context regarding what might need updating.
