### ISSUE TITLE
agent name logs

### ISSUE THREAD

**Issue by panospa** [MicrosoftDocs/azure-devops-docs#7977]
Hi, 

I am running vsts linux docker container and at the end of each job I exit and clean up as tracked from this[ issue post #5910](https://github.com/MicrosoftDocs/azure-devops-docs/issues/5910)

For some pools where I have a container(s) running with an always restart parameter, after each job finishes a new agent appears in a few seconds with same name. The only thing I have noticed is that under jobs I do get the agent name while the container is up and running  the job and once it exits I am loosing the name of it. 

![image](https://user-images.githubusercontent.com/29118488/79551878-92891e00-809a-11ea-80ab-2b30c08f1607.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
