### ISSUE TITLE
Enable Azure Virtual Machine Scale Set

### ISSUE THREAD

**Issue by bensaundersBRIT** [MicrosoftDocs/azure-devops-docs#7978]
How do I turn on this feature in our Azure DevOps tenancy? Do not have these features able to be enabled at the moment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@bensaundersBRIT Please see https://github.com/MicrosoftDocs/azure-devops-docs/issues/7665 for a contact that can assist you.
