### ISSUE TITLE
The example for NuGet package caching is incorrect

### ISSUE THREAD

**Issue by oising** [MicrosoftDocs/azure-devops-docs#7985]
See: https://github.com/MicrosoftDocs/azure-devops-docs/issues/6281#issuecomment-615432025

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by oising** [comment]
I see what the problem is now -- I bet everyone with this problem is using the GUI to create the pipeline, and not YAML. If you use YAML, the NUGET_PACKAGES variable from the docs example will implicitly create an environment variable and override the location from ~\.nuget\packages to a the writeable location under d:\a\1\ -- so the fix here is to create a pipeline variable for NUGET_PACKAGES to point to the new location, and then your pipeline will pick it up and the cache task will work.

I've leaving this open -- the docs should be more explicit for people using classic pipelines, and not YAML.

**Comment by ramiMSFT** [comment]
@oising Thank you for your contribution. The updated article will go live shortly.
