### ISSUE TITLE
Argument "name" is missing

### ISSUE THREAD

**Issue by pnwguy** [MicrosoftDocs/azure-devops-docs#7986]
It looks like argument/input "name" is missing, this is required for output variables/dependencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
@pnwguy -- thank you for your feedback.

@vtbassmatt -- please supply the prose, and I'll create a PR to update this article.

**Comment by vtbassmatt** [comment]
Any task can have a `name` (or `env`, or `displayName`, or one of several other properties). They are not documented on each task; they're documented in the [YAML schema section on "steps"](https://docs.microsoft.com/azure/devops/pipelines/yaml-schema#steps).
