### ISSUE TITLE
Issue with the example: vstsGit object not initialized properly

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#7988]
As `connection.getGitApi()` returns a promise are you really sure that

```
var vstsGit = connection.getGitApi().then( success => { console.log(success) }, error => { console.log(error) } )
```

gets `vstsGit` initialized correctly for further use down the source code?

The TypeScript compiler was complaining about `vstsGit.createPullRequestStatus`:

`Property 'createPullRequestStatus' does not exist on type 'Promise<void>'.ts(2339)`

So I implemented the call as follows, as part of the post handler:

```
connection.getGitApi().then( 
        vstsGit => {                                    
            vstsGit.createPullRequestStatus(prStatus, repoId, pullRequestId).then( result => {
                console.log(result);
            },
            error => {
                console.log(error);
            })
        }, 
        error => { 
            console.log(error);
        } 
    );
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server?view=azure-devops)
* Content Source: [docs/repos/git/create-pr-status-server.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/create-pr-status-server.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by WilliamAntonRohm** [comment]
@apawast -- Apeksha, please review [private PR 1320](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1320).
