### ISSUE TITLE
If there aren't any new features or functionality....

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#7989]
... a new layout was a waste of effort and a chance to have more bugs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  Please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
