### ISSUE TITLE
"Preview: Report deployment status to Boards" not shown1st image

### ISSUE THREAD

**Issue by KaiWalter** [MicrosoftDocs/azure-devops-docs#7993]
The 1st image / screenshot does not show the "Preview: Report deployment status to Boards" option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- please review [private PR 1322](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7993).
