### ISSUE TITLE
This page is a stub, with very little info compared to the equivalent .NET Core page

### ISSUE THREAD

**Issue by AnotherSadGit** [MicrosoftDocs/azure-devops-docs#7994]
Compare this page to the equivalent page for .NET Core, "Build, test, and deploy .NET Core apps", https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops

I created my first pipeline using the ASP.NET template in Azure Pipelines.  It generates a YAML file that defines a very basic build pipeline.  Wanting to learn how to add additional functionality to the pipeline I followed the link in the YAML file to this page.  However, the only thing this page says about the YAML file is "create a pipeline using the instructions in Create your first pipeline and select the ASP.NET template".  Which is what I previously did, and how I was able to follow the link to this page.  A disappointingly circular reference!

This page is pretty poor compared to the page for .NET Core, which explains in detail how to publish artifacts and perform a web deploy.  Unfortunately, the steps from that page cannot be used for legacy .NET Framework applications.

So Microsoft, no love for the thousands of developers supporting legacy .NET Framework applications?  If we're not on .NET Core you don't want to help us?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=azure-devops#feedback)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@AnotherSadGit -- thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
