### ISSUE TITLE
Backlogs shortcut: Move item to top (Ctrl+Home) does not work

### ISSUE THREAD

**Issue by Soren-Knudsen** [MicrosoftDocs/azure-devops-docs#7996]
The shortcut "Move item to top (Ctrl+Home)" doesn't seem to work on either a Windows or Mac machine. Nothing happens - I am able to move the item manually to the top or by right-clicking and choosing "Move to position".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fe0af-744d-e535-b300-8d1060945db6
* Version Independent ID: 10892c8d-ff0b-3072-46bd-cad31923c240
* Content: [Keyboard shortcuts for web portal and Team Explorer - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops)
* Content Source: [docs/project/navigation/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/navigation/keyboard-shortcuts.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
