### ISSUE TITLE
Extensibility points

### ISSUE THREAD

**Issue by JanSera** [MicrosoftDocs/azure-devops-docs#7997]
Journey part of this page is mentioning new extensibility points to be enabled, but it seems that it is not yet done. I already reported simillar issue here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/6833.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by ravishan-msft** [comment]
@JanSera  - this functionality has been completed and is part of the ongoing deployment, which should complete in 1-2 weeks. Please reactivate if you don't see this functionality post 2 weeks.
