### ISSUE TITLE
How do you turn off this new user experience?

### ISSUE THREAD

**Issue by tclayton72** [MicrosoftDocs/azure-devops-docs#8002]
I really don't like this and would like to turn it off.  

I want to view builds by branch, not all together in a single list.

It takes more clicks and pages to get the same information.

The job details now has the list of steps on the side no longer displaying the full title and the step output window doesn't show anything until after the step completes/fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by wqoq** [comment]
It used to be you could go to "User settings > Preview features", and set "Multi-stage pipelines" to "Off", but now it's locked to "On".

**Comment by mtamrakar** [comment]
+1. We really prefer the old design. Please bring back the toggle button.

**Comment by alechirsch** [comment]
+1, this new design is highly ineffective for my team.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by cwarne** [comment]
With this feature locked on, the option to clone a pipeline is no longer visible. Can we please get this functionality back? Or at least be able to toggle off the new design to clone a pipeline?

**Comment by WilliamAntonRohm** [comment]
@cwarne -- Chandler, thank you for your suggestions.  Please add them here:
https://developercommunity.visualstudio.com/content/idea/post.html?space=21
