### ISSUE TITLE
Agent Name in Build Summary Page

### ISSUE THREAD

**Issue by rofehaim** [MicrosoftDocs/azure-devops-docs#8003]
Hi, in the previous view we could see the agent name that the build was run on in the summary page and also we had a link to the appropriate Agent Pool, can you please add it to the new view also? maybe next to the 'Job Status'...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
