### ISSUE TITLE
Build.SourceVersionMessage only valid for master-branch?

### ISSUE THREAD

**Issue by gfoidl** [MicrosoftDocs/azure-devops-docs#8004]
When building PRs the `Build.SourceVersionMessage` contains something like
```
Merge 34395fddfd681ee89b9de06cde4a5d93cf5fbdea into c0817231785b2e27554eb0d7987e3788b554817c
```

For a build from master-branch the content shows the same as
```bash
git log -n1 --pretty=format:"%s"
```
which is what I would expect.

Either it's a product bug or it should be documented.

---

This is shows up on GitHup-Repos. Either public / private show the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by gfoidl** [comment]
Thanks -> https://developercommunity.visualstudio.com/content/problem/1002300/buildsourceversionmessage-for-prs-is-set-to-info-f.html

**Comment by markpalfreeman** [comment]
If nothing else, it would be helpful to understand that the `Build.SourceVersionMessage` commit for PRs is actually the _merge_ commit of a detached head, **rather than the source commit** (as referenced in the response above) ☝️

**Comment by WilliamAntonRohm** [comment]
@gfoidl -- Günther, thank you for adding your feedback.  I see that it has been answered.

@markpalfreeman -- Mark, thank you for clarifying.

@juliakm -- Julia, please look into this potential documentation issue.
