### ISSUE TITLE
Make Warnings section on Build Summary Page collapsible

### ISSUE THREAD

**Issue by robicide** [MicrosoftDocs/azure-devops-docs#8005]
The Warnings section on the Build Summary Page should be collapsible. Especially on builds that are still running.
That, or Jobs and Warnings should each be a tab on the page.

Usually when I'm looking at the Build Summary Page of a build that is still running, it's because I want to check on the progress, ie. which step(s) of which job(s) it is currently on.

I have a CD pipeline that is currently listing a lot of warnings (100+). Many of these are on a to-do list somewhere, many others are related to package version conflicts that cannot currently be resolved, some are vague and haven't been looked into yet, some of them are database procs that have references to views in the SYS schema.
Now, all these warnings are quite verbosely listed near the top of the Build Summary Page. That means I have to scroll past 100+ warnings that I have seen dozens of times already just to get to the Jobs overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
