### ISSUE TITLE
Please update this page to add pre-req @ Azure DevOps Organization level

### ISSUE THREAD

**Issue by nocheinlarry** [MicrosoftDocs/azure-devops-docs#8006]
Hi, as pointed out in #7231 by @dan-mill / @WilliamAntonRohm please add a section about organization pre-reqs , enable OAuth in Policy section of the Azure DevOps Organisation. Not having this lead to frustration in my Team @ T-Systems. Thanks to @WilliamAntonRohm giving to Right hint.
Thanks, Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by chcomley** [comment]
Hi @nocheinlarry, Thanks for this feedback. I've created a PR for this issue. Once the PR is published, this issue will automatically be closed. Please @mention me if you have any further questions. Thanks again!
