### ISSUE TITLE
Unable to call securefiles with same name even if there is a condition enabled

### ISSUE THREAD

**Issue by romeomorcia** [MicrosoftDocs/azure-devops-docs#8007]
Hello,

i've found out I cannot call 2 securefiles by assigning them the same "key" value.

issue in yaml pipeline file.

Below the example: 

- task: DownloadSecureFile@1
  displayName: 'Download build.key'
  name: key
  inputs:
    secureFile: build.key
  condition: ne(variables['Build.SourceBranchname'], 'master')

- task: DownloadSecureFile@1
  displayName: 'Download training.key'
  name: key
  inputs:
    secureFile: training.key
  condition: eq(variables['Build.SourceBranchname'], 'master')

the error is: job job: The step name key appears more than once. Step names must be unique within a job.

Looks like he understand "name" as name of the task instead of name of the secureFile.

If I give a different name for each securefile it will work properly and the files will be called that way.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
