### ISSUE TITLE
Add Area Paths

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/azure-devops-docs#8009]
It is not clear what functionality is actually added to the channel by using the addAreaPath command. Saying that the area paths are always available is ambiguous, as the create work item and add subscription interfaces allow users to select the available area paths. Please clarify what this function actually does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def2836e-b8c1-6ca0-0113-c72f53c17e18
* Version Independent ID: 58b6cb7c-df71-39c9-325d-b35e696ddf26
* Content: [Azure Boards with Microsoft Teams - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-teams?view=azure-devops)
* Content Source: [docs/boards/integrations/boards-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/integrations/boards-teams.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @RGKarthik
* Microsoft Alias: **karrg**

**Comment by divais** [comment]
PR Raised - https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1294
