### ISSUE TITLE
Agent IP Range section is mostly useless

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-devops-docs#8010]
This section talks about how to find the IP address ranges but it pretty much puts everything into step 3 as "find your IPs". This is a 40K JSON file. Exactly how are we supposed to find anything in here? It is nothing but a series of groupings with a region, platform and IP addresses. None of this makes any sense to anyone outside the people who wrote it. The docs say to include your geographic regions but nowhere in this file is that listed. The link to the docs doesn't really even say that other than in a tab. So I'm assuming that if you're in the US then you want the "Americas" geography. Great, now where is that in this 40K file that I have to parse every week?????

Seriously this is unacceptable if you expect us to use your hosted agents. Here's what we need. Here's your Dev Ops account, here's the IP addresses you need to release to it. Why is this so hard? Until we get this customer friendly solution then at least describe in exact detail the 20 steps it's going to take to convert this 40K JSON file to the EXACT IP addresses I need to allow my releases to be deployed. It is not sufficient to say "go find X" because X isn't in this file. We need exact steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#agent-ip-ranges)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@mtaylorfsmb We have received similar feedback and I have got a work item queued to see if we can make this better. Let me see if I can get an update.

**Comment by deyanp** [comment]
I think the problem is in the underlying technology, not documentation (the instructions to list all ip addresses of all regions in a geography are simply ridiculous - seems some poor soul was tasked to document something which makes no sense in reality!). Network Security seems to be an afterthought for MS, or at least incompatible by (MS-specific) design with all the serverless and SaaS offerings ... Am I forced to use my own hosted agents just to be able to organize a stable fixed IP address, so that I can secure properly my Azure Function Apps for example??

**Comment by rtaylor72** [comment]
Has anyone found the section for the build agents yet?  At lease if there was a step to search for something like "buildagents", then this would be more manageable.

**Comment by CoolDadTx** [comment]
@steved0x thanks

**Comment by mdtro** [comment]
I've been keeping an eye on the documentation for the updates because I really need this as well. Has anyone had success in getting the correct IPs parsed out?

**Comment by mdtro** [comment]
Thank you for submitting that fix. Am I correct in that there would currently be 1,410 network CIDRs in scope for the US regions?

**Comment by Yashuaa** [comment]
This is absolutely insane, if I want to deploy a release to a app service using devops releases I need to add these 50+ ip addresses? Is this a joke? And these change every week?
