### ISSUE TITLE
Using in a YAML Pipeline

### ISSUE THREAD

**Issue by predatorian3** [MicrosoftDocs/azure-devops-docs#8012]
Is this task able to be used in a YAML Pipeline if the Deployment Job is set to the `pool: server`? When you do this in the Classic Pipeline UI you can export the YAML for this task, but the documentation does not show the usage. Please clarify this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Manual intervention is not supported in YAML pipelines. You can find the Azure DevOps feature timeline [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline). And the specific [manual validation feature](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1663893) roadmap item

**Comment by ManuInNZ** [comment]
Looks like the feature is closed now.
Will there be a docs update to illustrate the YAML version ?
Although does not seem to like a simple ubuntu test.

```
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ManualIntervention@8
  inputs:
    instructions: |
      do this first.
      Then do that
```

![image](https://user-images.githubusercontent.com/7937408/104145395-b449e280-542b-11eb-8a79-1d5bbabf9a45.png)
