### ISSUE TITLE
Path and Branch pipeline trigger combination unclear

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#8013]
From the documentation it is not clear to me if a Path pipeline trigger is always firing a build even though the done changes are not in any of the defined include branches.
What I would like to achieve is to trigger a build for a given list of branches only if certain files/folders within these branches have been changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
> From the documentation it is not clear to me if a Path pipeline trigger is always firing a build even though the done changes are not in any of the defined include branches.
> What I would like to achieve is to trigger a build for a given list of branches only if certain files/folders within these branches have been changed.

Let me see if I can clear that up in the documentation. Your desired behavior is how it works: with respect to branch filters and path filters, a run is triggered, only if:

* It matches the branch filters - this is required
* If you have an optional path filter, the changed files (from a branch that matches the branch filter) must match the path filter
  * You can't have just a path filter, you must also have a branch filter

Only if both the branch filter and path filter are met, will a run be triggered. I'll make an update to the documentation to get that clarified.
