### ISSUE TITLE
Add Azure DevOps REST API version to Package and TFS version mapping table

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#8018]
Hi,

It would be great if the `Package and TFS version mapping table` contained a column for the REST versions mentioned in the [Azure DevOps REST API specifications](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1).  Specifically, I found that the [Work Item Comments API](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/comments/add?view=azure-devops-rest-5.1) appears to be in the 5.1-preview.3 version of the API, but which version of the SDK's packages will work with that version?

I can assume the [latest available on Nuget](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/16.166.0-preview), but if that package doesn't contain 5.1-preview.3, functionality, I'd prefer not to find that out by trial and error.

Thanks,
Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MarkIannucci, Thanks for your feedback. I've contacted a PM and will be in touch. Have a great day.

**Comment by chcomley** [comment]
Hi @MarkIannucci, I've created a user story for my backlog to address this. The PM has advised that we can address this in late July, early August. I'll be closing this issue, as the user story iteration is set for August. Don't hesitate to @mention me if you have any further questions about the article. Thanks so much! This may or may not be helpful, but here's a link to more SDK information: https://developer.microsoft.com/en-us/azure-devops/develop/extensions
