### ISSUE TITLE
Missing triggering properties on pipeline resources

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#8020]
The same pipeline trigger capabilities than the ones on ​[push trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#push-trigger) should be provided on pipeline resources. So I would say that at least the following properties are currently missing:

- tags
- paths (most useful to run related pipelines based on modified files!)

I also submitted the [corresponding suggestion](https://developercommunity.visualstudio.com/idea/1000094/missing-triggering-properties-on-pipeline-resource.html).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#environment-traceability)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@Thilas -- Thomas, thank you again for your feedback, and for filing that suggestion! Once that is implemented, we'll return to the docs and update them.
