### ISSUE TITLE
Will My Azure Build agents try cleanup before running the build ?? if so i can remove my post cleaning stuff

### ISSUE THREAD

**Issue by MangeshPersonal** [MicrosoftDocs/azure-devops-docs#8021]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=classic%2Cbrowser#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@MangeshPersonal If your agents are Microsoft-hosted agents, you get a new agent each time, and so you don't need to clean.

If you are using self-hosted agents, you can configure various options for cleaning before the job runs.

You can use [Workspace clean options](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace) to define several cleaning options, or you can use the clean option in the [Checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout) step.

It sounds like your question is "Do I need to clean at the end of my job" - if the provided options for cleaning before the job are sufficient, then you may not need to do any "post" cleanup, but that depends on your scenarios.

**Comment by pb6** [comment]
Please add option for workspace cleanup after the build. I get the idea, that you might need something to troubleshoot failed build, but usually we strive to successful builds etc. One of many microsoftish solutions to the problem :)
