### ISSUE TITLE
Velocity is not...

### ISSUE THREAD

**Issue by danavbaldwin** [MicrosoftDocs/azure-devops-docs#8026]
I think that we should define up front what velocity is and is not. Most organizations that are trying toi DO agile generally make the error of using velocity as a performance metric and this impedes their agile practice for a long time. This is one of the fundamental impediments to adopting an environment of improvement and the larger the org the more likely they are to screw it up.

Move this to the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e01fac-6a61-00a9-b914-2d42aa270bf8
* Version Independent ID: 6cc94467-d5d8-ff66-290f-c37304a83ccc
* Content: [Velocity metrics and usage guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/velocity-guidance?view=azure-devops&tabs=in-context#feedback)
* Content Source: [docs/report/dashboards/velocity-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/velocity-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@danavbaldwin - Thank you for the feedback. I'll do as you suggest and move towards the top of the article.
