### ISSUE TITLE
Planned work origin

### ISSUE THREAD

**Issue by joepurnell88** [MicrosoftDocs/azure-devops-docs#8028]
Need clarification in the article about how/when the "Planned" value is determined for the in-context chart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e01fac-6a61-00a9-b914-2d42aa270bf8
* Version Independent ID: 6cc94467-d5d8-ff66-290f-c37304a83ccc
* Content: [Velocity metrics and usage guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/velocity-guidance?view=azure-devops&tabs=in-context)
* Content Source: [docs/report/dashboards/velocity-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/velocity-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@joepurnell88 - THank you for your inquiry. I'm updating the article with the following additional information: 
- Planned velocity - calculated based on the amount of work scheduled for the sprint prior to the start of the sprint. This count includes work that was moved to a different sprint after the start of the sprint, but doesn't include work that was added later after the sprint started.
	 To list the work items included in the count, click the velocity bar. A query results page will open with the list of work items included.
