### ISSUE TITLE
Command example for removing a VM is incorrect.

### ISSUE THREAD

**Issue by odelljl** [MicrosoftDocs/azure-devops-docs#8031]
On my recently installed environment, the command to remove a VM was:

./config.cmd remove

... not ...

./configure.cmd remove

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops#remove-a-vm-from-an-environment)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- Julia, please review [private PR 1323](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1323).
