### ISSUE TITLE
Pwsh and powershell example use wrong syntax

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#8032]
In the examples for the "pwsh" and "powershell" tasks, it's using

`echo Hello $(name)`

That does not seem like a powershell command to me.

Maybe instead let's use:

`Write-Host "Hello $(name)"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- please review [private PR 1351](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1351).
