### ISSUE TITLE
Provide permalinks for weekly file

### ISSUE THREAD

**Issue by othke** [MicrosoftDocs/azure-devops-docs#8038]
Hi,
It maybe could be a good idea to provide two permalinks for weekly file (aka ServiceTags_Public_{Date}.json)
One link for current week and one link for next week.
If we want to make a script we have to test the file exists. I think some people have to make a job to weekly update their Network Security Group or Firewall to add the AzureCloud available IPs.

As the list of IPs are configurations information maybe theses permalink could avoid some hack and tests steps :)
Currently we only have a page with a button: https://www.microsoft.com/en-us/download/details.aspx?id=56519

I saw that you provide this powershell script as an example but you have to test the HTTP status. https://docs.microsoft.com/fr-fr/azure/storage/files/storage-sync-files-firewall-and-proxy

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by steved0x** [comment]
@othke Thank you for this feedback, please do submit this as a bug/feature request using the guidance in the previous comment. I am working with the engineering team to provide better instructions for the IP range process, and if or when new features are added, such as the one you request, I will make sure the article is kept up to date. Thank you.
