### ISSUE TITLE
What is the minimum number of agents when 'tear down after every use' is selected?

### ISSUE THREAD

**Issue by DiederickA** [MicrosoftDocs/azure-devops-docs#8039]
As answer to another question it is stated that machines idle for an hour may be teared down when above the minimum. If machines are teared down immediately after a pipeline has run I expect that a new one is started up when below minimum. However, that may imply that no idle machines are available when active machines is above minimum.
So, what I like to be able to set is "keep always x machines idle available", this 'minimum' equals 'min(busy machines + x, set maximum)'.
If this is already the case, the text may clearer on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

cc @steved0x for awareness
