### ISSUE TITLE
Usage of $(Time) is not documented

### ISSUE THREAD

**Issue by hz-aroan** [MicrosoftDocs/azure-devops-docs#8044]
It is not clear if there is a $(Time) token or not, or it can be used (similar to $Date) as $(Time:HHmm) or any other way.

It is unclear, that the $(Minute) and $(Hour) can or cannot be formatted somehow, for example $(Minute:mm) or $(Minute:#0) or any other way to achieve 2 digits format.

**Comment by WilliamAntonRohm** [comment]
@hz-aroan -- Zoltán, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by msebolt** [comment]
Closing this issue now.
