### ISSUE TITLE
git clone https://anything:{yourPAT}@dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName doesn't work

### ISSUE THREAD

**Issue by jbeesonnuva** [MicrosoftDocs/azure-devops-docs#8047]
That url format always returns fatal: Authentication failed on a confirmed working PAT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-your-personal-access-token)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jbeesonnuva I just tried cloning one of my repos with this format and was abe to do so.

Please check if any of the formats suggested [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455) work for you.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jbeesonnuva Any luck here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jbeesonnuva Hope you had a chance to check the above responses. Closing this issue for now.
