### ISSUE TITLE
"User and permission management" link in the sidebar results in 404

### ISSUE THREAD

**Issue by onlyutkarsh** [MicrosoftDocs/azure-devops-docs#8051]
The "User and permission management" link in the sidebar points to this [page](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management.md) in 404

![image](https://user-images.githubusercontent.com/2685029/80014352-19d5f780-84c8-11ea-8ed2-2c45a8ea15a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea7a0d9-bada-5278-e52d-ebd81c8eb976
* Version Independent ID: 0382d469-6c09-e327-4972-5e3b29d67e5c
* Content: [Troubleshoot creating and configuring an organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-configure-customize-organization?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/faq-configure-customize-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/faq-configure-customize-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by WilliamAntonRohm** [comment]
@onlyutkarsh -- Utkarsh, thank you for your feedback.  I am updating this topic.  The correct link is https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management?view=azure-devops.

**Comment by WilliamAntonRohm** [comment]
@chcomley -- Chrystal, please review [private PR 1310](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1310).

**Comment by onlyutkarsh** [comment]
@WilliamAntonRohm Awesome. Thank you!
