### ISSUE TITLE
Users can't edit Wiki

### ISSUE THREAD

**Issue by NorthHighlandNicole** [MicrosoftDocs/azure-devops-docs#8053]
Hello,

I have an issue JUST LIKE  #6047 

I have 2 users who see the "edit" button in the wiki grayed out. I checked both of their teams & permission groups to ensure they did not have "deny" set on either "contribute" or "read" for the repositories. 

As well I click on the "policies" button in the wiki & selected the user to see that they have inherited the "allow" permission for "read" and "contribute". These members are SCRUM master & project managers and cannot do their work for this project due to this blocker.

Please help resolve this immediately.

![image](https://user-images.githubusercontent.com/60410311/80018910-c1d9c980-84a4-11ea-8c8d-6f898f70867d.png)

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@NorthHighlandNicole -- it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
