### ISSUE TITLE
Why is `Build.Repository.Name` not available in templates?

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#8055]
I fail to understand why branch related variables (e.g. `Build.SourceBranch`) are available in templates but not informations on the repository itself (e.g. `Build.Repository.Name`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by Thilas** [comment]
Done: https://developercommunity.visualstudio.com/content/problem/1008977/variable-buildrepositoryname-is-not-available-in-t.html
Thanks

**Comment by whiskeysierra** [comment]
I've used it in templates successfully, but it only seems to work if you "import" the template, e.g.:

```yaml
stages:
  - template: my-template.yaml
```

But it doesn't seem to work when using `extends`.
