### ISSUE TITLE
Clarifying example for oauth token yaml

### ISSUE THREAD

**Issue by LittleBoxOfSunshine** [MicrosoftDocs/azure-devops-docs#8056]
While any arbitrary name for the environment variable can be used, we may reduce friction by suggesting that the default label used by the classic is also used in the YAML to ensure compatibility with legacy tasks and scripts and documenting the reason for the suggestion (best practice?). 

Example change:
env:
  SYSTEM_ACCESSTOKEN: $(system.accesstoken) # Any identifier may be used, however mirroring the value used in classic pipelines ensures backwards compatibility with existing tasks

This would also make the example consistent with https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by LittleBoxOfSunshine** [comment]
Similarly, it may be worth noting in the classic tab that when you "Select the Allow scripts to access OAuth token option in the control options for the job." the token will exist as the environment variable SYSTEM_ACCESSTOKEN.

**Comment by juliakm** [comment]
Thanks @LittleBoxOfSunshine! The update will go out shortly.

**Comment by juliakm** [comment]
#sign-off
