### ISSUE TITLE
Minimum Azure CLI requirement confusion

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/azure-devops-docs#8060]
This page states that 2.0.49 is required, but https://github.com/Azure/azure-devops-cli-extension states that 2.0.69 is required

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bc681f-09a5-d6ad-bf6f-46d644cd2c8e
* Version Independent ID: 0431d071-1fdd-70a2-25cd-742ddca6cfcc
* Content: [Learn about Azure DevOps command line interface extension - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/cli/?view=azure-devops)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/index.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by WilliamAntonRohm** [comment]
@KathrynEE -- please review [private PR 1350](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1350).
