### ISSUE TITLE
Doesn't work if target pipeline does not exist in default branch

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/azure-devops-docs#8068]
# Repro Steps:

1. Create a topic branch
2. In the topic branch, commit a new YAML definition (we'll call this the "Target Pipeline")
   * Include a pipeline resource trigger for some other pipeline; we'll call this the "Source Pipeline"
   * The "Source Pipeline" may already exist, or may also be created in this topic branch. It does not matter, this issue happens either way
   * The trigger should use a wildcard branch filter
3. Use the ADO UI to create the "Target Pipeline" from the new YAML definition that was just committed in the topic branch
4. Queue a run of the "Source Pipeline" on the topic branch

# Expected Behavior:

After the "Source Pipeline" run completes, the "Target Pipeline" is automatically triggered.

# Actual Behavior:

The "Target Pipeline" is not automatically triggered.

# Workaround:

I believe this is happening because the default branch for "Target Pipeline" is set to master, but the pipeline YAML itself only exists in the topic branch. If you reconfigure the default branch of the "Target Pipeline" to be the new topic branch, then triggering starts working as documented.

After much searching, I found a couple other cases in which folks seem to be impacted by this issue:

* [Pipeline trigger not working as expressed in documentation](https://developercommunity.visualstudio.com/content/problem/864701/pipeline-trigger-not-working-as-expressed-in-docum.html)
* [Resource pipeline default trigger(s) does not work](https://github.com/microsoft/azure-pipelines-yaml/issues/404)
* [Azure Pipeline resource triggers not working](https://developercommunity.visualstudio.com/content/problem/920292/azure-pipeline-resource-triggers-not-working.html)

Can we add some details to this page regarding how the default branch setting of a pipeline is used when evaluating whether to automatically trigger a pipeline from another "Source Pipeline"? Otherwise, folks setting up pipeline triggers in topic branches are going to be very confused when things don't work as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by reynoldsbd** [comment]
cc @kasubram, who seems to know a lot about this issue ;)

**Comment by hoffmanntravis** [comment]
Confirmed we are seeing the same issue.  Things get a little weird if you play around with this also.  From what I have proven out so far, the functional pipeline with the trigger does need to exist in master.  But you can actually _remove_ the pipelines section of yaml from the topic branch entirely.  Additionally, the stages and various control elements are fired out of the topic branch, not the default branch.  So you end up with this weird hybrid yaml where the pipeline trigger has to be in the default branch but the stages have to be in the topic branch.  

I'm not sure if the default branch can have _just_ the trigger.  I tried this once and it didn't work, but maybe I need to experiment more.  But I 100% confirmed that default branch had two stages, triggered a change in the topic branch with 1 stage, and only 1 stage executed.

**Comment by hoffmanntravis** [comment]
After further testing, the following YAML seems to be the minimum requirement (or very near to it, I pared it down a lot) in the default branch for either the default or topic branch to execute triggered stages.  While in most typical cases the contents of default and topic branches will likely be the same in terms of the deployment YAML, I found this information useful to understand what's happening in cases where that is not true relative to this reported bug.

resources:
  pipelines:
  - pipeline: deploy.trigger.test
    source: thoffmann.pipeline.triggers
    trigger: true
stages:
  - stage:
    jobs:
      - job:

@kasubram @WilliamAntonRohm Any update on when this will likely be fixed?  I would think whichever branch that had commit that triggered the CI trigger should be the branch evaluated in terms of any appropriate build completion triggers stages / pipelines etc based on the YAML defined in that branch, not the default branch.

**Comment by WilliamAntonRohm** [comment]
cc @ashokirla for awareness

**Comment by NorthHighlandNicole** [comment]
For anyone else facing the same issue, in spite of changing my topic branch to be the default, 

To get this to work as expected I still had to merge the changes in my topic branch into the default branch.

**Comment by m1o1** [comment]
I've been pretty confused by this as well. Diagrams for different hypothetical scenarios would be very useful to have in the docs. If this is the default branch for manual builds too, I expected the pipeline to be the one from this branch, even if I run the pipeline on a different branch.

It sort-of makes sense now to me, being that it's just the default and I was just overriding it in the UI, but "default branch for manual builds" does make it seem like the version of the pipeline that runs would be in this branch, even if I select a different branch to run the pipeline on (which contains the source I want to build).

**Comment by SerratedSharp** [comment]
I have an issue I suspect is related.  If I create a new pipeline on main branch, and set it's only trigger to `tags:`, then put a tag on a commit prior to the pipeline existing, then the pipeline does not trigger.  Basically, it seems like triggers can't look across branches nor backwards in time.  If I put the tag on a commit where the pipeline exists, then the pipeline runs fine.  Basically the pipeline performing the build isn't decoupled from the application code I want it to retrieve to perform the build.

Usually I'd expect the CI/CD pipeline to be able to retrieve the source to build against from anywhere I tell it to.  I.e. the script to perform the build(the pipeline YAML) and what code I want that script to build would be decoupled.

This is challenging when we maybe had a prod release a week before, and realize for the first time we need a hotfix build that pushes to a new environment but references a prior commit/tag(the one representing the previous production release).  So we create a new pipeline, but then when we try to run that pipeline and manually select a prior commit/tag, then it fails with "pipeline does not exist".

I recognize it's probably not something that can be changed, but a great way to spend the afternoon trying to figure out why it seems like my tag trigger silently isn't working until I realize it ignores them on older commits.  So something to consider for clarifying in documentation.

**Comment by steved0x** [comment]
@serratedsharp We have added a new section to this article to cover this: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#branch-considerations (although this new section is older than your recent feedback). I am keeping this issue open in our new feedback system to see if we can add more clarification.

I recommend that you file this same feedback as product feedback here: https://developercommunity.visualstudio.com/AzureDevOps

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
