### ISSUE TITLE
Activated By field is copied when copying a work item

### ISSUE THREAD

**Issue by seapeter** [MicrosoftDocs/azure-devops-docs#8069]
In regards to this post https://github.com/MicrosoftDocs/azure-devops-docs/issues/4940, this is also happening for the "Activated By" field when a work item is copied from a closed work item. We are on Azure DevOps Server 2019 Update 1.1.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
