### ISSUE TITLE
Small typo in https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions

### ISSUE THREAD

**Issue by asugaya-apx** [MicrosoftDocs/azure-devops-docs#8074]
This typo is found in https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions.

At the bottom of the page, there is an example for setting variables using bash. The following:

`MINOR_RUN=$(echo $BUILD_BUILDNUMBER | cut -d '.' -f2)
    echo "This is the major run number: $MINOR_RUN"`

should be:

`MINOR_RUN=$(echo $BUILD_BUILDNUMBER | cut -d '.' -f2)
    echo "This is the minor run number: $MINOR_RUN"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Chibuikekenneth** [comment]
Making a PR for this issue right away.
