### ISSUE TITLE
Update UseDotNet@2 availability

### ISSUE THREAD

**Issue by hangy** [MicrosoftDocs/azure-devops-docs#8076]
When you change the selected server version of the docs to Azure DevOps Server 2019, the website says that the feature is not available with this version of Azure DevOps Server:
![grafik](https://user-images.githubusercontent.com/87124/80157114-c944c400-85c5-11ea-873b-0ef41af2def5.png)

As discussed in https://github.com/microsoft/azure-pipelines-tasks/issues/12733#issuecomment-618710907, this is inaccurate. The task is actually not available with 17.143.28621.4, but after upgrading to 17.153.29522.3, it can be used. (Unfortunately, this isn't mentioned in the release notes.) Therefore, the docs should probably differentiate between Azure DevOps Server 2019, Azure DevOps Server 2019 Update 1, and Azure DevOps Server 2019 Update 1.1 to indicate availability of this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [Use .NET Core task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops&viewFallbackFrom=azure-devops-2019)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@hangy Thank you for providing this feedback.

The documentation has been updated and changes will be released in the next publish cycle.
