### ISSUE TITLE
v4.0 Preview?

### ISSUE THREAD

**Issue by nbrown02** [MicrosoftDocs/azure-devops-docs#8077]
I can see changing the OData URL to https://analytics.dev.azure.com/{OrganizationName}/{ProjectName}/_odata/v4.0-preview works - meaning a new version is in preview - are there any changes to the data available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0406dd-f852-001f-eba5-a665ed4ef7a0
* Version Independent ID: 51657f61-8b0c-3132-59d4-7d876b08af6d
* Content: [Data model for Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops)
* Content Source: [docs/report/extend-analytics/data-model-analytics-service.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/data-model-analytics-service.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@nbrown02 Thank you for the question.

For information on new features,  please refer to the [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline) or for feature ideas/concerns try soliciting feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

If you feel this information is missing or should be added to, please add additional comments below.

@gloridelmorales

**Comment by nbrown02** [comment]
Should all the Odata references in the documentation be changed to have v4.0preview rather than 3.0 ?

**Comment by ksmis-gh** [comment]
@nbrown02  we'll make sure that happens once we release the new version. For now you can explore v4.0-preview using the metadata endpoint.

**Comment by KathrynEE** [comment]
CLosed as answered.
