### ISSUE TITLE
nobuild not working for publish

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8079]
dotnet pack and dotnet publish cli commands both allow --no-build however the nobuild argument to this task only seems to influence dotnet build, it doesn't set dotnet publish --bo-build. I think it would be good to update the description for the nobuild argument on this task, explaining that if you wish to set dotnet publish --no-biuild you have to use custom arguments for that instead. In addition to fixing this in a future release of the task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@dazinator Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
