### ISSUE TITLE
Runtime parameters - out of date banner

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/azure-devops-docs#8087]
On the page with runtime parameters there is this banner:

![image](https://user-images.githubusercontent.com/17653648/80288083-c79a0e00-8735-11ea-9df5-ec72e90a933c.png)

I think this banner is out of date right now. This feature is probably available to almost all organizations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Mikilll94 Thank you for the feedback.

The documentation has been updated and is pending review.

**Comment by vtbassmatt** [comment]
Oh whoops, I see now that @msebolt had already prepared the fix.
