### ISSUE TITLE
icon_color_palette needs to be icon_palette

### ISSUE THREAD

**Issue by craigajohnson** [MicrosoftDocs/azure-devops-docs#8089]
The icon list is incorrect - was able to find the correct value for icon_palette from a bug report somewhere else but easiest to just fix it right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b6a631-c8d9-4e34-665d-88fe07517a8b
* Version Independent ID: b5077fd4-5271-647a-6d2d-528d10578714
* Content: [ProcessConfiguration syntax - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/process-configuration-xml-element?view=azure-devops#feedback)
* Content Source: [docs/reference/xml/process-configuration-xml-element.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/process-configuration-xml-element.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@craigajohnson - Thank you for the correction. I'm updating the article to reflect the correction today.
