### ISSUE TITLE
Note on scalar parameters not correct according to eq expression docs

### ISSUE THREAD

**Issue by PedroLamas** [MicrosoftDocs/azure-devops-docs#8090]
There's a note on this page that reads like this:

> Scalar parameters without a specified type are treated as strings. For example, eq(parameters['myparam'], true) will return true, even if the myparam parameter is the word false, if myparam is not explicitly made boolean. Non-empty strings are cast to true in a Boolean context. That expression could be rewritten to explicitly compare strings: eq(parameters['myparam'], 'true').

So according to this note, if `parameters['myparam']` is the string "false" (or any other non-empty string), that will convert to the boolean value `true` and then do `eq(true, true)`.

But unless I'm missing something here, this doesn't make much sense if we take into account what is said for the `eq` expression [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#eq):

> Converts right parameter to match type of left parameter. Returns `False` if conversion fails.

Given this, we should be doing `eq('false', 'true')`... so which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@PedroLamas Thank you for the feedback.

You are correct, the example in the [templates](https://docs.microsoft.com/azure/devops/pipelines/process/templates) doc seems to mistakenly have the parameters switched.  Please follow the guidelines stated in [expressions](https://docs.microsoft.com/azure/devops/pipelines/process/expressions?view=azure-devops#eq).

To see this in action try:

```
steps:
- ${{ if eq(true, true) }}:
  - script: echo this works

- ${{ if eq('false', false) }}:
  - script: echo this works because right becomes left

- ${{ if eq(false, 'false') }}:
  - script: echo this works because left becomes right
```



The documentation has been updated and is pending review.
