### ISSUE TITLE
No documentation for new checks

### ISSUE THREAD

**Issue by jamers99** [MicrosoftDocs/azure-devops-docs#8091]
I would like to use the new features released in April, but there is no documentation. I would like to see what variables are available to use in these checks, specifically in the Invoke REST task. 
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-167-update#additional-control-of-your-deployments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by Nirav-Bhadradiya** [comment]
@WilliamAntonRohm do you have plans to fix this, this is a blocker for lots of my cicd workflows using REST API checks on environments.

**Comment by WilliamAntonRohm** [comment]
@azooinmyluggage -- please look into this issue.

cc @ashokirla for awareness

**Comment by isaiasccruz** [comment]
I know this is from 2020, but it is still open, and I have the same questions as @jamers99. Is this been updated somewhere?
