### ISSUE TITLE
My team mates are not able to view +Add New Test Plan & Define tab

### ISSUE THREAD

**Issue by iShakeem** [MicrosoftDocs/azure-devops-docs#8093]
Hi, 
We are planning to start using the Test Plans. I'm able to create new test plans, suites and test cases but my team mates are not able to do the same and they are not able to see the define tab as well. We have the same user settings. Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by ravishan-msft** [comment]
@iShakeem , thanks for raising this issue. You would need "[Basic + Test Plan](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-access-tfs-test-hub?view=azure-devops-2019#buy-monthly-access-to-azure-test-plans)" access level for you to leverage the full functionality of Azure Test Plans. 

I will add this information to the "New test plans page" as well. Closing the issue now.
