### ISSUE TITLE
Clarify how to use release branchens together with continous integration?

### ISSUE THREAD

**Issue by xenod** [MicrosoftDocs/azure-devops-docs#8095]
It would be great if the part on deployment could elaborate on how to work with CI and release branches. A build pipeline in Azure DevOps for example is tied to a branch. What's the best practice here? To have one build for master branch and another build for release-branches, where we manually update the branch to build from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#feedback)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by sameer-kumar** [comment]
I agree, more guidance is needed with examples around [Managing Deployments](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops#manage-deployments) and how they are associated with release and master branch?
