### ISSUE TITLE
Does the jdkVersionOption support Java 12?

### ISSUE THREAD

**Issue by JimSuplizio** [MicrosoftDocs/azure-devops-docs#8100]
I'm looking at the following [yml snippet for the maven task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops#yaml-snippet) which lists the following jdk version options
`#jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6`
and I'm wondering if Java 12 is supported and, if not, when? I'm asking because we have a new library that is Java 12 only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@JimSuplizio Thank you for the question.

The product team is still working on its release, please vote and/or add comments [here](https://developercommunity.visualstudio.com/idea/552892/please-support-java-12-in-maven-tasks-of-azure-pip.html) to solicit additional feedback.

**Comment by JimSuplizio** [comment]
Thanks @msebolt for referring me to the correct place. I guess we can close this out.

**Comment by msebolt** [comment]
@JimSuplizio Sure, no problem.  

If you feel there are concerns with the documentation to address please comment below.
