### ISSUE TITLE
AZP_TOKEN is not adequately defined.  A list of needed perms is the minimum required to define the variable in a way that is implementable from the docs.

### ISSUE THREAD

**Issue by devops-brain** [MicrosoftDocs/azure-devops-docs#8104]
[Enter feedback here]
AZP_TOKEN is not adequately defined.  A list of needed perms is the minimum required to define the variable in a way that is implementable from the docs.

This type of error is prevented by walking through the documentation before releasing, just like Middle Schoolers do for their project before handing it into their teacher.  

I more often encounter a documentation that wouldn't be accepted by an elementary school teacher than useful and complete docs from Microsoft.  You have either a major problem in your release process, a widespread culture problem, or criminal intent (sabotaging products to push consulting services is illegal).  This is not just a one doc issue at this point.  

(updated formatting and spelling)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@devops-brain -- thank you for your feedback.  You can submit issues related to your overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

@steved0x -- please look into the documentation for AZP_TOKEN.

**Comment by msebolt** [comment]
Please also include differences between AZP_TOKEN and VSTS credentials as mentioned in [Deploy Azure Pipelines agent on Linux](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-linux), from https://github.com/MicrosoftDocs/azure-devops-docs/issues/8336.

**Comment by steved0x** [comment]
@devops-brain `AZP_TOKEN is not adequately defined. A list of needed perms is the minimum required to define the variable in a way that is implementable from the docs.` - sorry that you ran into trouble, we just updated this article to provide more information for AZP_TOKEN - it  is a Personal Access Token (PAT) with Agent Pools (read, manage) scope (this is the missing part), on the target Azure DevOps organization. The description added in the article includes links with guidance on creating a PAT and selecting custom scopes. It should be live tomorrow once I verify.
