### ISSUE TITLE
@myRecentActivity error

### ISSUE THREAD

**Issue by aaronleesmu** [MicrosoftDocs/azure-devops-docs#8113]
I found an answer via this link here, encounter @myRecentActivity error when opening Azure DevOps in excel.

https://medium.com/objectsharp/azure-devops-work-item-query-macros-ddf45257af3a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a718268-1105-4def-5f9e-20ea21afc0d7
* Version Independent ID: 0f08fa18-3075-4275-22c7-d5d1c1e260b0
* Content: [Query fields, operators, and macros/variables - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops)
* Content Source: [docs/boards/queries/query-operators-variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/query-operators-variables.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@aaronleesmu - Thank you for this feedback. I'll update the article to reflect the usage of certain macros only working in the web portal.
