### ISSUE TITLE
One needs to be Project collection Administrator to achieve this.

### ISSUE THREAD

**Issue by Ahetejaz** [MicrosoftDocs/azure-devops-docs#8120]
The article nowhere says about the access one needs to have to achieve what mentioned in the article. One needs to have Project collection admin to achieve this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f5446e-0797-3aa1-6503-1fcc08f906ed
* Version Independent ID: e059f72e-3b00-e5d1-3401-ba47240117d1
* Content: [Get list of organizations connected to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/get-list-of-organizations-connected-to-azure-active-directory?view=azure-devops)
* Content Source: [docs/organizations/accounts/get-list-of-organizations-connected-to-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/get-list-of-organizations-connected-to-azure-active-directory.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @Ahetejaz. I've just published an update, adding the prerequisite, which should be live shortly. Thanks again!
