### ISSUE TITLE
Git Repo with standard Service Connection templates in JSON? 

### ISSUE THREAD

**Issue by FilBot3** [MicrosoftDocs/azure-devops-docs#8121]
Is it possible for Azure DevOps to provide their standard, default JSON Templates for the Service Endpoints in a Git repo? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 209081c3-76a3-562e-3479-e6b63b7ec2c7
* Version Independent ID: c0be31ee-9568-cddd-2ee4-af196aa318d8
* Content: [Create Service Endpoint using Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops#feedback)
* Content Source: [docs/cli/service_endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/service_endpoint.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **gsaral**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

cc @KathrynEE for awareness
