### ISSUE TITLE
Pipeline Events in Azure DevOps Server 2019

### ISSUE THREAD

**Issue by mjwoodsphx** [MicrosoftDocs/azure-devops-docs#8123]
Since Pipelines using YAML are now in Azure DevOps Server 2019, are the pipeline events valid in 2019 as well?  Are the lists of events between 2019 and Services current to the products?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops-2019#feedback)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by chcomley** [comment]
Hi @mjwoodsphx, Thanks for posting your question. The “BuildCompleted” event would still work for YAML pipelines. It is generated when a pipeline run is completed. In addition to that, we will have new events for stage state changes. If I can help any further, please @mention me, as I'm now closing this issue. Thanks again!
