### ISSUE TITLE
Pipelines Agent, Windows SSL certificate management

### ISSUE THREAD

**Issue by doctorlard** [MicrosoftDocs/azure-devops-docs#8127]
Why does the Windows build of the Azure Pipelines Agent, which runs on Windows, not use the official Windows build of git, which includes the option in the installer to use the Windows SSL Certificate store, instead of a port of the OpenSSL store? For organistations that have a bunch of internal services set up and CA certs installed with Group Policy, this would make a lot more sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8554882-68f4-d60b-fe3f-ba4ca00bfdff
* Version Independent ID: 87839017-b47c-4bc2-1bba-e20bef0c3025
* Content: [Run the agent with a self-signed certificate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/certificate?view=azure-devops-2019#feedback)
* Content Source: [docs/pipelines/agents/certificate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/certificate.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
