### ISSUE TITLE
Duplicate Cron Syntax In "Supported cron syntax"

### ISSUE THREAD

**Issue by vanderby** [MicrosoftDocs/azure-devops-docs#8129]
0 18 * * Mon,Wed,Fri is listed twice in the following example:

Build every Monday, Wednesday, and Friday at 6:00 PM	0 18 * * Mon,Wed,Fri, 0 18 * * 1,3,5, 0 18 * * Mon,Wed,Fri, or 0 18 * * 1-5/2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#supported-cron-syntax)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@steved0x -- Steve, please review [private PR 1340](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1340).

**Comment by steved0x** [comment]
@vanderby Thanks for catching that, it is fixed and should be live very soon.
