### ISSUE TITLE
@Samboy1990 -- please clarify your title change, and add a link in a comment for the docs.microsoft.com topic you're reading.

### ISSUE THREAD

**Issue by Samboy1990** [MicrosoftDocs/azure-devops-docs#8130]
@Samboy1990 -- please clarify your title change, and add a link in a comment for the docs.microsoft.com topic you're reading.

_Originally posted by @WilliamAntonRohm in https://github.com/MicrosoftDocs/azure-devops-docs/issues/7909#issuecomment-620861634_

**Comment by WilliamAntonRohm** [comment]
duplicate of #7909
