### ISSUE TITLE
How to restrict work items assignment to only members of the project?

### ISSUE THREAD

**Issue by zynga7** [MicrosoftDocs/azure-devops-docs#8134]
How to restrict work items assignment to only members of the project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a197bf55-89c7-682d-bb1c-e82bec732349
* Version Independent ID: 5aa2afac-cb82-3f72-643c-25a0173cce98
* Content: [Using work items to track user stories, & more - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/about-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/about-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Akshayalg - Thank you for your question. Please review these 2 articles which provides details. 

- https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-access?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops

**Comment by JDGithubUser** [comment]
Hi @KathrynEE , sorry for reopening this thread, but I cannot seem to find the answers for the question in the links you provided.
I am experiencing the same issue as the person creating the thread.

When a user is assigning someone to a work item in Azure DevOps, then they can search and find all users in the Azure AD and not only users with access to the project which the work item belongs to.

Hope you can explain how to restrict who can be found when searching to people to assign to a work item.

**Comment by KathrynEE** [comment]
@JDGithubUser - Thank you for reopening this issue. I just confirmed the behavior which was unexpected from my part. I'm reaching out to our exprerts to see what the resolution is and will post it here and then get it documented.

**Comment by KathrynEE** [comment]
@JDGithubUser - I learned that this is a known issue and there is no workaround at the moment. However, it is being addressed and I'll update you here and the documentation once the fix is made.

**Comment by JDGithubUser** [comment]
Hi @KathrynEE Is there any timeline that you know of for the bugfix? 
This is a pretty bad bug as I see it.
It is possible to search for other guest users in the Azure Active Directory and the Azure Active Directory groups are exposed.

**Comment by KathrynEE** [comment]
@JDGithubUser - I'm not an expert in this area, and as this isn't a documentation issue, but a product issue, I recommend you raise it in our Developer Community page. There was this issue, https://developercommunity.visualstudio.com/content/problem/635240/assigned-to-field-showing-too-many-values.html, that was raised. It suggests turning the External User policy OFF. That may be where the bug is. 

I'm sorry I don't have more info to share. I'll continue to work with our product team to see if I can get a better answer.

**Comment by KathrynEE** [comment]
@JDGithubUser - You may find a workaround by applying rules to work item types. See https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/apply-rules-to-workflow-states?view=azure-devops.

**Comment by KathrynEE** [comment]
@Akshayalg, @JDGithubUser  - The issue raised here should be fixed within the next few sprints. Please review the [Azure DevOps Roadmap update for 2020 Q4](https://devblogs.microsoft.com/devops/azure-devops-roadmap-update-for-2020-q4/).
