### ISSUE TITLE
Inaccurate information regarding adding users to organization.

### ISSUE THREAD

**Issue by solomson** [MicrosoftDocs/azure-devops-docs#8137]
From the prerequisites section:

```
To add users to an organization, you must be a member of the Project Collection Administrators group. Organization owners are automatically members of this group.

To add users to a project, you must be a member of the Project Administrators or Project Collection Administrators groups.
```

I've found this to not be true / not exact

Project Admins can invite users in the same Active Directory tenant and assign them (default) stakeholder access. They are then part of the organization as far as I am concerned.

Is there a way to turn this off? I want project admins to be able to assign users to the project ONLY IF the users are already part of my organization, ideally through group rules set up by a project collection admin.

This causes governance issues for us, since we no longer control memberships through AD groups, which we use for several other services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f798c7a-540e-3df7-985d-f1a52a53231e
* Version Independent ID: fe9362a5-871d-9150-6e39-1e29d150f169
* Content: [Add members, contributors to projects, teams - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-team-members?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-team-members.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-team-members.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @solomson, Thanks for your feedback. I'm following up with the product group and will be in touch. Thanks again!

**Comment by chcomley** [comment]
Hi @solomson, I've created a user story to address the prerequisites, thank you. We're working on a feature that gives you a toggle to turn this off, so stay tuned! Please @mention me if you have any further questions. Have a great weekend!
