### ISSUE TITLE
Need details on how to handle execution bit on .sh scripts

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/azure-devops-docs#8139]
The warning on a "hosted" Windows agent is: 
`##[warning]Executable bit is not set on target script, sourcing instead of executing. More info at https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/bashnote.md`

However, that link is not very informative, and telling people to leave well-alone if they don't understand, is not really a satisfactory answer.

Even when the "execution bit" is set I still get the warning.

Please provide detailed steps on how to set the execution bit so your agent doesn't raise the warning.
The following doesn't work:
```
git config core.filemode false
chmod -x &lt;file&gt;
git update-index --chmod=+x &lt;file&gt;
chmod +x &lt;file&gt;

#check
git ls-files -s
```
I've confirmed in the `_work` directory that the file has the right permissions.

(Windows agent with git bash installed)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good find. This is a product bug, not a doc bug, so I will move it to the agent repo.

/move to microsoft/azure-pipelines-agent

**Comment by arcotek-ltd** [comment]
Thank you, but don't you think a "note" in the doc would be useful to make sure people do assign the "execution bit"?

**Comment by vtbassmatt** [comment]
Sure, I can add that. The bigger issue is the bug, though, and the easiest way to get that fixed was to use the Movebot command.
