### ISSUE TITLE
Only registering the repository does not work!

### ISSUE THREAD

**Issue by tarabishy2020** [MicrosoftDocs/azure-devops-docs#8145]
The "Connecting to the feed as a PowerShell repo" part did not work for me.

I do manage to see the packages in the feed after registering the repository, but installing any of them fails.
Only by adding this step, installing the modules works
```
Register-PackageSource -Name "PowershellAzureDevopsServices" -Location "https://pkgs.dev.azure.com/&lt;org_name&gt;/_packaging/&lt;feed_name&gt;/nuget/v2" -ProviderName NuGet -Trusted -SkipValidate -Credential $credsAzureDevopsServices
```
Prior to that I kept getting this error whenever I try 
```
Install-Module -Name &lt;ModuleName&gt; -Repository PowershellAzureDevopsServices
```
```
Install-Package: ***\Documents\PowerShell\Modules\PowerShellGet\2.2.4.1\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to resolve package source 'https://pkgs.dev.azure.com/&lt;org&gt;/&lt;repo&gt;/_packaging/&lt;feedName&gt;@Local/nuget/v2'.
```
When I added -verbose -debug to the installation, I noticed it was actually managing to download the package
```
DEBUG: 00:00:02.2640613 '1' packages received in the last request.
...
...
DEBUG: 00:00:02.9006338 Done calling powershell «Get-InstalledPackage» «PSModule»

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '0.0.1' of module '***'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
```
but then fails on 
```
DEBUG: 00:00:18.3736745 Source 'https://pkgs.dev.azure.com/&lt;org&gt;/&lt;repo&gt;/_packaging/&lt;feedName&gt;@Local/nuget/v2' is not one of the registered sources in 'NuGet' provider.
VERBOSE: Retry downloading 'https://pkgs.dev.azure.com/&lt;org&gt;/&lt;repo&gt;/_packaging/&lt;feedName&gt;@Local/nuget/v2' for '2' more times
VERBOSE: Retry downloading 'https://pkgs.dev.azure.com/&lt;org&gt;/&lt;repo&gt;/_packaging/&lt;feedName&gt;@Local/nuget/v2' for '1' more times
VERBOSE: Retry downloading 'https://pkgs.dev.azure.com/&lt;org&gt;/&lt;repo&gt;/_packaging/&lt;feedName&gt;@Local/nuget/v2' for '0' more times
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by bormm** [comment]
Unfortunately seems not to have a single test for such needed functionality and did not notice its broken since 2018: https://github.com/OneGet/oneget/issues/403

**Comment by ramiMSFT** [comment]
@tarabishy2020 Thanks for your feedback!
