### ISSUE TITLE
Cache Task Instructions - Value cannot be null. Parameter name: securityNamespace

### ISSUE THREAD

**Issue by jonstelly** [MicrosoftDocs/azure-devops-docs#8146]
Following instructions on this page on a multi-stage build, I got the error `Value cannot be null. Parameter name: securityNamespace` on the build.  I found this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/11291 and added a `securityNamespace: cache` input for the cache tasks and everything worked as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by hansmbakker** [comment]
@ramiMSFT @msebolt can you please look into this and reopen the issue? I encountered the same issue today

#please-reopen
