### ISSUE TITLE
Is it possible to get runtime parameters from rest api ?

### ISSUE THREAD

**Issue by tsaibabu4u** [MicrosoftDocs/azure-devops-docs#8147]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script

I dont see an example get parameters from a rest api or a script to populate. can we do that ?

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by juliakm** [comment]
@tsaibabu4u You can see the API docs [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run%20pipeline?view=azure-devops-rest-6.0#request-body). Parameters are `templateParameters `.
