### ISSUE TITLE
Download multiple secure files

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/azure-devops-docs#8154]
We have a requirement where we need to replace a list of files during a production build. These would contain production URLs and production keys which should not be checked into repository for security purposes and so these files should be stored in SecureFiles.  Since DownloadSecureFile is a pipeline task taking a single filename, it is not possible to include this in a loop, for example, from a powershell task.  How can I use DownloadSeecureFile task to download multiple files in a loop for the above requirement?  We need the list of files to be stored in an array so that we can add/remove as many files as needed without having to change the YML every time we have to replace a different production file or change the name of the production file and so this list will be in a group variable which we will parse in powershell.

If DownloadSecureFile task can take multiple file names, it would make it much easier to deal with such requirement.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36505533-7471-1f67-1a1d-4f3273bf4bf2
* Version Independent ID: abffb74f-97ab-c739-f39e-6138fdb5352b
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@srikcgaa2 Thank you for the feedback.

Looping tasks is not yet possible, instead please refer to [this post](https://stackoverflow.com/questions/61398206/azure-devops-yaml-pipeline-how-to-repeat-a-task) on how to repeat tasks.

To solicit feedback from the product team for support on this feature, please see [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
