### ISSUE TITLE
Preventing to get Error NU5012 

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8155]
Hi everyone.
I have successful build after which I place NuGet pack, but I get Error NU5012 for reason I don't understand. Please help me out.

Here is NuGet task log output:

```
C:\hostedtoolcache\windows\NuGet\5.5.1\x64\nuget.exe pack D:\a\1\s\CommonUtilities\MyComp.CommonUtilities\MyComp.CommonUtilities.csproj -NonInteractive -OutputDirectory D:\a\1\a\NuGet -Properties Configuration=Release -version 2.4.2431.20200430 -Verbosity Detailed
Error NU5012: Unable to find 'MyComp.CommonUtilities.dll'. Make sure the project has been built.
NuGet.Packaging.Core.PackagingException: Unable to find 'MyComp.CommonUtilities.dll'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
NuGet Version: 5.5.1.6542
Attempting to build package from 'MyComp.CommonUtilities.csproj'.
MSBuild auto-detection: using msbuild version '16.5.0.12403' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.

```

And here is my task:

```
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  condition: ne('${{ parameters.publish_nuget }}', '')
  inputs:
	command: pack
	configuration: $(configuration)
	packagesToPack: '${{ parameters.publish_nuget }}'
	packDestination: '$(Build.ArtifactStagingDirectory)\NuGet'
	versioningScheme: byBuildNumber
```

I understand that it might be related to nuget.exe directly, but anyway it related to NuGet task indirectly itself such as "it may be require some additional parameter to build such cases successfully" or something about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f447b8b0-80af-cd43-a7a1-a5a9ffd4cdd2
* Version Independent ID: 7805ee87-93b8-d9db-9a16-e521748803fc
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@VerdonTrigance Thank you for the question.

Unfortunately our forum can only provide support for documentation examples.

Please either reference an example from the documentation or see if the resolution from https://github.com/NuGet/Home/issues/7131 applies to your scenario.

For additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance Thank you for the question.
> 
> Unfortunately our forum can only provide support for documentation examples.
> 
> Please either reference an example from the documentation or see if the resolution from [NuGet/Home#7131](https://github.com/NuGet/Home/issues/7131) applies to your scenario.
> 
> For additional support options, see:
> 
> * [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
> * [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
> * [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

I already saw this issue. And as told in https://github.com/NuGet/Home/issues/7131#issuecomment-535497315 in it doesn't seems to be optional params and nowhere in docs told about this. That's why I want you to change docs related to this problem.

**Comment by msebolt** [comment]
Assigning this to the author for further review.

**Comment by VerdonTrigance** [comment]
I'm definitely sure that page should include caps lock red color alert about building and packaging nuget. Because I still can not force that damn NuGet Task pack my .csproj with or without passing configuration and platform parameters.

**Comment by VerdonTrigance** [comment]
Finally I discover that NuGet pack just doesn't work with .csproj. It full of bugs and unpredictable things. I was forced to use .nuspec which configuration was faster than all of these dances around .csproj. 
Shame on you NuGet!
