### ISSUE TITLE
Update Work Item dates field

### ISSUE THREAD

**Issue by kissferenc** [MicrosoftDocs/azure-devops-docs#8158]
I want to bring Issues from other tracking site. Can I somehow update the Create Date, Change Date and Closed Date values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kissferenc  - Thank you for your inquiry. No, changing the Create Date, Change Date and Closed Date values isn't possible. These are system fields controlled by the system. If you import work from another site, it will create new work items with the dates for that time of import.
