### ISSUE TITLE
Xamarin project

### ISSUE THREAD

**Issue by 24mu13** [MicrosoftDocs/azure-devops-docs#8159]
No mention about restoring packages for a single Xamarin project, instead of entire solution. You need a task for that, since restoring for Xamarin project is not supported by .NET restore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f447b8b0-80af-cd43-a7a1-a5a9ffd4cdd2
* Version Independent ID: 7805ee87-93b8-d9db-9a16-e521748803fc
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@24mu13 -- Samuel, thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
