### ISSUE TITLE
Referencing Output Variable from Dependency does not work as described

### ISSUE THREAD

**Issue by kluhman** [MicrosoftDocs/azure-devops-docs#8163]
I'm using the runOnce strategy with the deploy hook, but referencing an output from one of the tasks does not work using this syntax as described here. 

$[dependencies.&lt;job-name&gt;.outputs['&lt;lifecycle-hookname&gt;.&lt;step-name&gt;.&lt;variable-name&gt;']]

The only way I was able to get this to work was actually by using the following syntax

$[dependencies.&lt;job-name&gt;.outputs['&lt;job-name&gt;.&lt;step-name&gt;.&lt;variable-name&gt;']]

This seems to be corroborated by the comments in this GitHub issue 

https://github.com/MicrosoftDocs/azure-devops-docs/issues/4946#issuecomment-543366950

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@juliakm -- please review [private PR 1378](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/1378).
