### ISSUE TITLE
Interpolated Variables

### ISSUE THREAD

**Issue by DaveJarvis** [MicrosoftDocs/azure-devops-docs#8165]
Consider the following YAML document:

``` yaml
---
a: A 
b: $a$ B 
c: $b$ C $b$
d: $a$ $b$ $c$ D $a$
e:
  f: 
    g: G
h: H and $e.f.g$
```

I would like to reference those values within the Markdown. Moreover, I would also like to control the syntax whereby said values are referenced. I've written a YAML preprocessor named [yamlp](https://bitbucket.org/djarvis/yamlp/src/master/README.md) that can perform string interpolation.

Multimarkdown, pandoc moustache, and other systems allow authors to embed such constants inside their content. There is also an [open issue](https://github.com/jgm/pandoc/issues/1950) for pandoc that contains more information about how this works. Rather than repeat the details, please see my comments in that pandoc ticket. In particular:

* https://github.com/jgm/pandoc/issues/1950#issue-57878939
* https://github.com/jgm/pandoc/issues/1950#issuecomment-427664614
* https://github.com/jgm/pandoc/issues/1950#issuecomment-524521696
* https://github.com/getgrav/grav/issues/2672#issue-497459142

My blog post describes this concept at length:

* https://dave.autonoma.ca/blog/2019/07/06/typesetting-markdown-part-5/

The bottom of the following diagram shows a more general view of how variable interpolation can work by considering a variety of structured document formats as input:

![](https://i.stack.imgur.com/IEBOT.png)

What's needed is a convention that associates Markdown contents with interpolated data sources. This would allow different data sources and/or data formats to be swapped. For example:

* https://host.com/wiki/software/architecture/
* https://host.com/wiki/configuration/
* https://api.host.com/v1/config?export=json

Inside the wiki's configuration would be a setting that allows any data source (either to a local file or remote file) to be associated with one or more pages in the wiki. In this case, any pages underneath "/wiki/software/architecture" could embed references from the hierarchical data returned by the REST call. It would be the wiki server's responsibility to:

1. Check if any requested wiki page has an associated data source.
1. Fetch the data source.
1. Interpolate the strings within the data source.
1. Replace the references in the wiki page with the fully interpolated string values.
1. Render the wiki page as HTML for the browser.

Users would then have the option of associating different data sources with different sets of wiki pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @DaveJarvis, Thanks for your feedback. I'm assigning this to the product group for further assistance. Thanks again!

**Comment by mijacobs** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by DaveJarvis** [comment]
@mijacobs -- I don't wish to create a Microsoft Live account, sorry.
