### ISSUE TITLE
This task is not working

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#8175]
It prepends ** two asterisks to the image name and the push cannot find the images in the system. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a328e2-391c-843d-7442-932ec77b2a91
* Version Independent ID: 83eb4008-ded5-597c-8d54-2383bbf9d240
* Content: [Push an image - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/push-image?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/containers/push-image.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/push-image.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
