### ISSUE TITLE
How to trigger CD after CI

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/azure-devops-docs#8176]
I follow the document to create two pipelines, build and release. But whenever I commit change to a branch, it triggers both pipelines. How i can trigger release only after build pipeline completed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@kenakamu  Thank you for the question.

Assigning this to the author for review of changes to the documentation.

For help with user-specific scenarios and additional support options, please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by seeafish** [comment]
@kenakamu If I've understood you correctly, on your release pipeline definition, you can do something like this:

```yaml
trigger: none

resources:
  pipelines:
    - pipeline: upstream
      source: my-build-pipeline
      trigger:
        branches:
          include:
            - '*'
```
The `trigger: none` means that the release pipeline won't be triggered by anything. That is however overridden by the `resources` section, which triggers when a new successful build on `upstream` on `*` branches is detected.

**Comment by juliakm** [comment]
Thank you @seeafish. @kenakamu Please see [Triggers in Azure Pipelines](Specify events that trigger pipelines) to learn more about how to trigger a pipeline.
