### ISSUE TITLE
Please clarify "Wait for author"

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/azure-devops-docs#8180]
When this value is set, will the PR automatically be approved when the author resolved all my comments?
Otherwise this option should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@weitzhandler Thank you for the question.

Assigning this to the author to see if the article should be updated.

If this feature is not yet available, please use **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit further feedback from the product team.

**Comment by weitzhandler** [comment]
I will, first need to determine what's the "by design" here. Because currently setting status to "wait for author", doesn't actually do anything.
When we get feedback from article-author, will post a feature request for "approve when all comments resolved" state.

**Comment by xTavi** [comment]
@weitzhandler So... "Waiting for the author" actually means that the author should review his PR or review the comments?

**Comment by mastry** [comment]
The meaning of "Wait for author" [is in the docs](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#vote-on-the-changes)...

**Wait for author:** Don't approve the changes, and ask the author to review your comments. The author should let you know to review the code again after they address your concerns.

**Comment by vincentsels** [comment]
There's no way for the author to signal the reviewer that he's resolved the comments and wants the reviewer to have another look?

**Comment by cochi2** [comment]
I'd like to echo @vincentsels comments, this "Waiting for author" seems to translate to "I'm asking the author for comments and the author needs to ping me offline when he's done" which makes no sense.
One single tool should be enough to accommodate each scenario. 
I'd expect: Reviewer sets "Waiting for Author" -> Author resolves/replies each comment -> Reviewer gets a notification that the Author has replied.

**Comment by ranjanngc** [comment]
There should be status like "waiting for reviewer"

**Comment by joshjm** [comment]
@ranjanngc @cochi2 Please vote on the feedback in the developer community to give this issue some higher priority. I don't think any engineers on the team are going to see this closed issue. 
[Theres feedback suggested here](https://developercommunity.visualstudio.com/t/PR-Waiting-for-author-notification-to/1649892?space=21&q=wait+for+author)

**Comment by andersnicolai** [comment]
Yes, waiting for reviewer, or senior developer to approve, would be nice ;)

**Comment by Sleepingwell** [comment]
> The meaning of "Wait for author" [is in the docs](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#vote-on-the-changes)...
> 
> **Wait for author:** Don't approve the changes, and ask the author to review your comments. The author should let you know to review the code again after they address your concerns.

I think you mean [these docs](https://learn.microsoft.com/en-us/azure/devops/repos/git/review-pull-requests).

**Comment by WilliamAntonRohm** [comment]
@Sleepingwell -- Simon, thank you for catching this.  I am updating the link.

**Comment by WilliamAntonRohm** [comment]
Already noted in the current documentation.
