### ISSUE TITLE
Plugin Doesn't show what change occurred

### ISSUE THREAD

**Issue by KehindeOwens** [MicrosoftDocs/azure-devops-docs#8181]
Hello,

This app does most things right except one thing i've noticed. It'll inform you that a work item was updated and what it was updated to but it doesn't show what it was updated from. For example, I can assign a bug from John to Bill and people will see in the notification that the bug is assigned to Bill but there is nothing telling them that it was originally assigned to John. Is this something being looked into or on the roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54bed72-4266-7c72-ef20-d48968dcaddd
* Version Independent ID: a7109901-c230-b420-88b6-b3000faf002e
* Content: [Azure Boards with Slack - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/integrations/boards-slack?view=azure-devops)
* Content Source: [docs/boards/integrations/boards-slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/integrations/boards-slack.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @RGKarthik
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@KehindeOwens Thank you for the question.

This is a good candidate for the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

There the product-team can provide additional feedback on feasibility and release schedules if the feature is approved.

In the meantime, perhaps try using [custom fields](https://docs.microsoft.com/azure/devops/organizations/settings/work/add-custom-field) to store previous information such as the auditing information mentioned in the example above.

@RGKarthik

**Comment by divais** [comment]
Hi @KehindeOwens 

Adding history / audit details isn't in our plans currently. We strive to ensure only key elements are available in the notification to reduce signal to noise element. I would love to understand what key problem are you trying to solve here.

**Comment by msebolt** [comment]
Closing this issue now.
