### ISSUE TITLE
This page about automated tests sits under node "manual testing"

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-devops-docs#8183]
This page about automated tests sits under node "manual testing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ciufudean  Thank you for the feedback.

The document has been updated and is pending review.

**Comment by steved0x** [comment]
I got a little more context about this topic - the intended audience is customers that run manual test plans (for on-demand scenarios such as running selected tests on demand, or to rerun some tests)that have automated test cases, and that's why it is in with the other manual testing articles.
