### ISSUE TITLE
What permission is needed to have the context menu shown in step 4?

### ISSUE THREAD

**Issue by mprevdelta** [MicrosoftDocs/azure-devops-docs#8184]
I can see the users in the organization, but no context menu next to each name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aa416a-b842-77d0-e18a-bee7f7bf7205
* Version Independent ID: 65942145-45ca-48bb-6adc-c16bd662b80a
* Content: [Manage users and access levels - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-users-table-view?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/accounts/manage-users-table-view.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/manage-users-table-view.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@mprevdelta Thank you for the question.

Please make sure you are the organization owner, or have been assigned the Project Collection Administration (PCA) role.

See more information on the [PCA role](https://docs.microsoft.com/azure/devops/organizations/settings/about-settings?view=azure-devops#project-collection-administrator-pca-role-and-managing-collections-of-projects) and [transferring an organization](https://docs.microsoft.com/azure/devops/organizations/accounts/change-organization-ownership).

**Comment by msebolt** [comment]
Closing this issue now.
