### ISSUE TITLE
Resetting or modifying client npmrc set up

### ISSUE THREAD

**Issue by nieve** [MicrosoftDocs/azure-devops-docs#8185]
Would be great to add to the [Troubleshooting vsts-npm-auth](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#troubleshooting-vsts-npm-auth) some info on how can you reset the setup on your computer if you'd like to modify the way you set it up.

In my case, I have added an option (cannot remember which) when setting up a colleague computer, which made it so the her token is stored on the local project npmrc file rather than inside %USERPROFILE%  
Now since the rest of the team is set up with the latest, this creates issues when committing changes to our version control. Is there a way to undo this or modify it?

content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows)

**Comment by nieve** [comment]
Hello, any chance of getting some info on resetting a machine in order to reinstall vsts-npm-auth ?
Would appreciate any help on this, thanks.

**Comment by ramiMSFT** [comment]
@nieve Thank you for your feedback! I'm adding the steps to the article shortly.
