### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by kallsu** [MicrosoftDocs/azure-devops-docs#8191]
The information about the pricing, for the users/groups connected aren't clear or missing.

DevOps has a payment structure per users, if I connect my AD with existing users (1000 example), I will pay the fees for the users into DevOps, or not ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 031380a0-4f04-4105-199a-81715b42c653
* Version Independent ID: 570b2795-90ad-32b4-7ad0-1fceb186ffa3
* Content: [Connect organization to Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/connect-organization-to-azure-ad.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/connect-organization-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @kallsu, Thanks for reaching out for clarification. You will only pay for the users you invite to collaborate in Azure DevOps and if you assign them a Basic license. Thanks and have a great day!
