### ISSUE TITLE
Using wildcards in filtering criteria

### ISSUE THREAD

**Issue by Marco-Santoni** [MicrosoftDocs/azure-devops-docs#8194]
Is it possible to use wild cards in the filtering criteria? If so, could it be added to the page?
Example

```
Changes in folder = /path/to/*suffix/
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3982f11f-c9aa-26fe-0812-f56b855c0c0e
* Version Independent ID: 54a34df8-7172-b2cc-9466-d527f0f324da
* Content: [Manage personal notification settings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-your-personal-notifications?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/notifications/manage-your-personal-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-your-personal-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Marco-Santoni, Thanks for reaching out. I've followed up with the product group about using wild cards in the filtering criteria and will be in touch soon. Thanks!

**Comment by chcomley** [comment]
Hi @Marco-Santoni, I'm sorry it took so long for me to get confirmation, but it looks like we do not support using wildcards in filtering criteria. I welcome you to submit a feature request! Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Suggest a feature** > **Azure DevOps**. Thank you!
