### ISSUE TITLE
Old screenshot with alternate authentication credentials

### ISSUE THREAD

**Issue by pietergheysens** [MicrosoftDocs/azure-devops-docs#8196]
Alternate authentication credentials are not supported anymore. Update the screenshot to avoid confusion.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a18e09c1-5c84-4fd6-9d62-2299a3bd53cd
* Version Independent ID: c1627714-5e55-1be0-4ba5-63f264b96e5c
* Content: [Change app access policies for organizations - Azure DevOps Services](https://docs.microsoft.com/nl-nl/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops&viewFallbackFrom=vsts&source=docs#feedback)
* Content Source: [docs/organizations/accounts/change-application-access-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-application-access-policies.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @pietergheysens, Thanks for the heads up. I've created a PR, which should be live shortly with the latest and greatest UI. Thanks again!
