### ISSUE TITLE
How are Azure DevOps Public Projects discoverable?

### ISSUE THREAD

**Issue by successhawk** [MicrosoftDocs/azure-devops-docs#8199]
According to the definition of Public Projects they are discoverable.  How?

>     A project created within an Azure DevOps Services organization that is visible to the whole world. Everyone in the world can discover them and perform limited operations.

[Here is my related StackOverflow question](https://stackoverflow.com/questions/61483693/how-do-i-find-public-azure-devops-projects).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62cfc55-db49-3ad5-3d06-f3b98a41e3e6
* Version Independent ID: 84b6789b-a9ce-efc0-ef82-bbffff23f5ee
* Content: [Glossary for public projects in Azure DevOps - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/glossary-public?view=azure-devops)
* Content Source: [docs/organizations/public/glossary-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/glossary-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @successhawk, Thanks for reaching out. I've followed up with the product group for some clarity and will get back to you soon. Hope you're having a nice day. Thanks!

**Comment by chcomley** [comment]
I'll be updating the article today, but here's your answer, @successhawk. The best way would be to use Azure DevOps project list - https://docs.microsoft.com/en-us/azure/devops/organizations/projects/create-project?view=azure-devops&tabs=azure-devops-cli#list-projects, which would list the projects and their visibility. Thank you!

**Comment by successhawk** [comment]
Maybe I am confused on what a public Azure project is.  I thought Public projects meant public like this is public https://github.com/MicrosoftDocs/azure-docs on Github.  Can you give me a link to an example Public Azure Project?

@chcomley , to use your answer, I would have to know an org that contains public repos. How do I find orgs that have public projects?
Or are you saying that I can only find "public" projects where I am a member of the organization?

**Comment by chcomley** [comment]
@successhawk, Azure DevOps Public Projects aren’t generally discoverable to the general public. A project member needs to publicize the URL for it to be found. 

If you're interested, I'd recommend submitting a feature request. You can do so [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Select **Suggest a feature** > **Azure DevOps**, complete the form, and then choose **Post your feature suggestion**.  Thank you.
