### ISSUE TITLE
Missing information on package resources

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#8200]
Hi, above it is mentioned that there are "package" resources but I cannot find any documentation about it. Can you fix that?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@MTomBosch  Thank you for the feedback.

Please refer to the issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/7861 for further updates on the status of this.

Closing this issue now.
