### ISSUE TITLE
How can Stakeholders see the portfolio backlog?

### ISSUE THREAD

**Issue by jrybacek** [MicrosoftDocs/azure-devops-docs#8203]
In the article above, it claims Stakeholders can see the portfolio backlogs and Kanban boards.  Can you explain to me how I can set this up, our Stakeholders currently click on Backlogs, but they get a blank screen.

Agile Portfolio Management
Includes limited access to portfolio backlogs and Kanban boards. Stakeholders can't change the backlog priority order, and can't assign items to an iteration, use the mapping pane, or exercise forecasting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jrybacek - Stakeholders should automatically be able to see all backlog levels. If they are seeing a backlog but no work items, then I'd check what permissions have been placed on the area path. See [Create child nodes, modify work items under an area path](https://review.docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops&branch=users%2Fkaelli%2Fsafe-refresh#set-permissions-area-path) for details.  

It may be that someone disallowed Stakeholders to view the work items under one or more nodes. 

If this isn't the issue, then please raise the problem in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) page as it isn't a documentation issue.

**Comment by nassimdaoud** [comment]
![image](https://user-images.githubusercontent.com/32630246/140865491-ac1d7021-e281-4ae9-a93f-6de21b09af75.png)

You should allow the '**View project-level information**' permission at Organization settings level .
