### ISSUE TITLE
How/with who I can share the Artifacts?

### ISSUE THREAD

**Issue by PawcioCNCProfi** [MicrosoftDocs/azure-devops-docs#8204]
In the first sentence this page only says "...with teams of any size." but what are requirements/limitations of this?
This is a key thing and I can't find clear answer to it on any page in this documentation. 

I used to share package to my colleague through local file share.  The [Get started with NuGet packages in Azure DevOps Services and TFS](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/get-started-nuget?view=azure-devops#get-your-feeds-nuget-package-source-information) suggest that once I upload the packages to Artifacts I can add a link to it in VS Package Sources just like before. However after reading other pages I'm confused because it suggest that only DevOps users will be able to use my feed.

Especially I don't get what "Permissions" and "Views" do. The [Views on Azure DevOps Services feeds](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/concepts/views?view=azure-devops) page only say why you want different views but there's no mention about  how to use it in practice. Do I add different source urls  in VS Package Sources, or it uses default view or what? What are "feed users"? Do I need to be logged in as correct user in Visual Studio to use this feed (I have private and job account)?   What are "Permissions" for?

I see only options for DevOps users... eventually I want any user of my application to use my packages for crating extensions to app but I can't even figure out if I can use this artifacts for this. I've once been fooled that I can connect Github repo to DevOps but it turned out it just crated static copy and I just wasted time.... And now, once again, I'm jumping back and forward between doc pages trying to understand general concept how this all suppose to work together and I don't know if I'm not wasting my previous time...

I know that writing documentation for newcomer may be hard since all things are already obvious for someone who is writing it but... do you really think those two sentences under "Azure Artifacts overview" are enough for someone seen it first time? Yeas it requires work but people doing the docs are few and people reading it are in thousands... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with prerelease and release views - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by PawcioCNCProfi** [comment]
And I just realized I used wrong tab for this issue. It suppose to be linked to [What is Azure Artifacts?](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops) and not to "Communicate package quality with prerelease and release views - Azure Artifacts"

**Comment by herenhuang** [comment]
Hey there, 

No worries about the "wrong tab", this is a great piece of feedback. Your project-scoped feeds within a public project are available publicly. Which means that anyone can read them (and that it doesn't have to be a DevOps user). 

We're actually going through all of our docs right now to beef them up... so thanks for your patience here. Let me try to find the right folks to answer your other questions.

**Comment by ramiMSFT** [comment]
@PawcioCNCProfi Thank you for your feedback. See [feeds and views](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#understanding-feeds-and-views-permissions) to understand the difference between the two concepts.

I also recommend these two resources:

- [Share a package publicly](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/tutorials/share-packages-publicly?view=azure-devops)

- [Understand upstream sources](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops)

You can also post your question on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) if you need more help.
