### ISSUE TITLE
MFA and PATs

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/azure-devops-docs#8209]
hey Guys, 
Could you please confirm that I understood it right?

Let's say enable CAP for my AzureDevops organization. From that point users are required to use MFA to access our AzureDevops site. This change will not have any affect to self-hosted agents, that authenticates to AzureDevops using PAT. PATs will remain working without any CAP rules enforcement. 

Did I got it right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24bd6400-4207-6f85-8a4e-5c9b0cc99cff
* Version Independent ID: 0b018039-29d1-431a-1be9-4b46af7f084f
* Content: [Manage Conditional Access policies - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-conditional-access?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/manage-conditional-access.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/manage-conditional-access.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ramrajesh** [comment]
That is correct. Setting up a MFA policy will not impact our non-interactive flows that uses alternate credentials like PATs.  Here is the public facing documentation on this. 

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-conditional-access?view=azure-devops&tabs=preview-page

**Comment by chcomley** [comment]
Hi @gintuoklis, I'm closing this issue, however please @mention ramrajesh if you have any further questions. Thanks and have a great day!
