### ISSUE TITLE
Progress report shows "Not Run"

### ISSUE THREAD

**Issue by slbentley** [MicrosoftDocs/azure-devops-docs#8211]
Curious if there are any common reasons why my progress report, as well as my widget "Chart for test plans" always shows my test cases as not run? All test cases/work items are in the ready state. All tests are passing during my pipeline build. My unit test project is core 3.1 and I'm running it with a "core" pipeline task and the "test" parameter.  After each pipeline build I get a "tests" tab and it shows the outcome of the tests. Is there another parameter I need to add to my test task to gather the results for devops? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cfb51b-0b54-7d26-f9b2-4167915fba7a
* Version Independent ID: 5716194c-87f4-b1dc-7f31-592529a1fd3a
* Content: [Track test status - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/track-test-status?view=azure-devops)
* Content Source: [docs/test/track-test-status.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/track-test-status.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@slbentley Thank you for the feedback.

Please see if [this post](https://developercommunity.visualstudio.com/content/problem/911149/passed-test-cases-are-showing-in-dashboard-as-not.html) addresses the issue and if not, report this as a problem to the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

@steved0x

**Comment by slbentley** [comment]
There issue was different in that the test cases would show as executed, but the graphs would show as not run. I can't even get the test cases to show as executed. They just show as "ready". We have other devops projects where we've gotten this to work, and a side-by-side comparison of all settings doesn't reveal anything we've missed. I've followed the link and reported a problem as suggested. But is the community forum where you really report problems? Anyway thanks for the assistance. Fingers crossed.

**Comment by slbentley** [comment]
*Their issue. SMH.

**Comment by msebolt** [comment]
@slbentley No problem, thank you for posting the issue to the product team.  

Yes, unfortunately this forum is currently limited to the documentation. Support requests can be provided per issue with the examples, but all product issues are directed to use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

Please post the link to your reported problem for visibility on the status of the issue.

**Comment by slbentley** [comment]
https://developercommunity.visualstudio.com/content/problem/1021628/unit-tests-are-passing-but-associated-test-cases-s.html

**Comment by msebolt** [comment]
This appears to have been resolved by user with product team's support, closing the issue now.
