### ISSUE TITLE
DeleteFiles task Isn't working for me

### ISSUE THREAD

**Issue by derekantrican** [MicrosoftDocs/azure-devops-docs#8216]
Here's my yaml:

```
    - task: DeleteFiles@1
      displayName: 'Cleanup'
      inputs:
        contents: |
          F:\CSo\sdNugetCache
          F:\CSo\gitNugetCache
          F:\CSo\sd
          F:\CSo\git
```

But upon running this step in ADO pipeline it just says:

```
Starting: Cleanup
==============================================================================
Task         : Delete files
Description  : Delete folders, or files matching a pattern
Version      : 1.166.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/delete-files
==============================================================================
Finishing: Cleanup
```

And the folders are not deleted on the machine.

Am I using the syntax wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@derekantrican Thank you for the question.

Please try including the `SourceFolder` parameter, as this will default to the root folder of the repo which might interfere with the absolute paths.

**Comment by derekantrican** [comment]
Thanks for the help. For people in the future, this is my final task yml:

```
    - task: DeleteFiles@1
      displayName: 'Cleanup'
      inputs:
        SourceFolder: F:\CSo
        contents: |
          sdNugetCache
          gitNugetCache
          sd
          git
```

For @msebolt I would argue that this shouldn't have been a problem and that absolute paths should be allowed. Can this be improved?

**Comment by msebolt** [comment]
@derekantrican No problem, great to know you got this working.

For product-related issues and/or suggestions, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html). Here's an [example](https://developercommunity.visualstudio.com/content/problem/396088/project-template-absolute-path.html) of a previously suggested feature similar to your issue.

Closing this issue now.
