### ISSUE TITLE
Share Azure Artifacts for all organization

### ISSUE THREAD

**Issue by andre-f-paggi** [MicrosoftDocs/azure-devops-docs#8218]
I was not sure about it when reading the docs.

Can I share Azure Artifacts from one DevOps project to all organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf693ac-c5c3-96a6-7f4b-bbc2271a6375
* Version Independent ID: 4f76c74c-1d6c-644f-f00d-97d7738d7b01
* Content: [Using packages in Azure DevOps best practices - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=azure-devops)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/best-practices.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@andre-f-paggi Thank you for the question.

Yes, for more information please refer to [Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/?view=azure-devops).

For instance, one DevOps project can publish a [nuget feed](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml) and it's up to you whether you want limit access internally or publish to a public repo such as nuget.org where everyone can access.

**Comment by msebolt** [comment]
@andre-f-paggi Thank you for contacting Microsoft and have a nice day.
