### ISSUE TITLE
Reopen bugs or PBIs.

### ISSUE THREAD

**Issue by natyo** [MicrosoftDocs/azure-devops-docs#8219]
How do the cycle and lead time work if I need to reopen a bug or PBI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e813268-5e00-7c84-2479-3068e27ea443
* Version Independent ID: 269b0352-2a6a-d5c9-96a3-68d5ce93c616
* Content: [Cycle time and lead time control charts - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/cycle-time-and-lead-time.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/cycle-time-and-lead-time.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by harshit211997** [comment]
If a work item enters a Completed state and then is reactivated and moved out of that state, then any additional time it spends in a Proposed/In Progress state will contribute to its lead/cycle time when it enters a Completed state for the second time. Reference - https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops
