### ISSUE TITLE
Should promoting from @Prerelease to @Release result in removing the package from @Prerelease?

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/azure-devops-docs#8220]
I promoted a package to @Prerelease for testing.  Once it was verified to be solid, I promoted it to @Release.  The package is now in both views.  I wasn't sure if that was expected behavior or not, but wasn't too worried about it.  However, back in Visual Studio, when trying to add that package to a solution through the NuGet Package Manager GUI, the package only shows up when I check the "Include prerelease" box, even though I promoted it to @Release.  Is there some sort of caching issue with the package manager and my feed, or is having the package still in @Prerelease, in addition to @Release, keeping it from being seen as "not prerelease?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with prerelease and release views - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@ronwarner Thank you for the question.

This is built-in by design and you will also need to increment the version to avoid this issue.

Here's a recent [post](https://stackoverflow.com/questions/37174786/how-to-remove-prerelease-designation-on-nuget-package) that further highlights some work-arounds.

To solicit additional feedback from the product team, please refer to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ronwarner** [comment]
@msebolt - Thanks for your response.  To be certain I have understood you clearly, is the recommended approach to simply not promote from Prerelease to Release, but instead build another package (after verifying the Prerelease is stable) which is identical to the Prerelease package, except for an incremented version number, and to then promote the new package directly to Release, skipping Prerelease?  The workarounds in the post felt hackish to me, and I'd like to do my best to adhere to the practice Microsoft intends for us to use.  If I've understood you clearly, let me know, and I'll close this issue.  If not, I will take it to the community as advised.

**Comment by msebolt** [comment]
@ronwarner I agree that the referenced methodology is a work-around, I only meant by **Azure DevOps** design that to use a pre-release version, it will be included in addition to the release version.  

It would be under the assumption that developers prefer keeping a record of all releases versus having certain releases replace other (pre)releases.

Most topics involve [issue with the Visual Studio option](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=include+prerelease) so this would a relevant feature request to for **DevOps**.

**Comment by ronwarner** [comment]
@msebolt - Thanks.  Via that last link, I found evidence that there is not supposed to be a direct correlation between the Azure Artifact views, and the "include prerelease" checkbox in Visual Studio.  I did not previously realize this.  I think I have a better idea of what a proper workflow for my team should look like now, and so I'll close this issue.
