### ISSUE TITLE
Example manual subsitution for "don't sync sources"

### ISSUE THREAD

**Issue by MichaelBelousov** [MicrosoftDocs/azure-devops-docs#8221]
In [this article](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml), the documentation on the "Don't Sync Sources" option of the azure pipelines source fetch step is lightly documented. We are syncing sources manually with a script, and having issues authenticating (the git credential manager is prompting on the agent when the bearer auth should suffice, and we cannot figure out how to disable it). Can the documentation on "Don't sync sources" include a snippet on manually replacing the step? Or perhaps a link to the fetch task implementation wherever it may be to show how to manually sync sources for people with custom requirements?

**Comment by msebolt** [comment]
@MichaelBelousov Thank you for the feedback.

This subject appears to be included in a few sections, namely [Options for Git repos](https://docs.microsoft.com/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#dont-sync-sources-tfs-2017-and-newer-only), [Build repos](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#get-the-source-code), and [Build Azure repos](https://docs.microsoft.com/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#get-the-source-code).  

Assigning this to the authors for further review.  @steved0x @vijayma

**Comment by MichaelBelousov** [comment]
Any update on this?

**Comment by MichaelBelousov** [comment]
Perhaps another question is, is it possible to manually fetch a repository from my organization without generating and managing a PAT? I was hoping `System.AccessToken` could be used

**Comment by MichaelBelousov** [comment]
I returned to this, and I'm setting up a PAT based auth in PS script like so:

```powershell
$auth = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("pat:$PAT"))
git -c http.https://<URLSTUFF>/_git/REPO.extraheader="AUTHORIZATION: Bearer $auth" fetch origin
```

But whenever I run this, I get a 400 error, I think I may need to make an issue somewhere besides the docs. I'll reread all three articles but for this workflow I primarily referenced [Build Azure repos](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#get-the-source-code)

**Comment by MichaelBelousov** [comment]
this may help: https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455

**Comment by MichaelBelousov** [comment]
Alright, I've looked at #2455,  [this SO post](https://stackoverflow.com/questions/53106546/cannot-clone-git-from-azure-devops-using-pat/54147034#54147034), and [the api auth documentation](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&viewFallbackFrom=vsts&tabs=preview-page), Basic and Bearer, username, no username, empty username, http.<url>.extraheader, http.extraheader, http.extraHeader, and I'm just getting 400s. @steved0x could I get a correction on something I must be doing wrong here?

Here is the last thing I tried:
```powershell
$path = "pat"
$auth = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("anything:$pat"))
git -c http.extraheader="AUTHORIZATION: Basic $auth" fetch origin
```
