### ISSUE TITLE
fatal: Authentication failed for git clone with PAT

### ISSUE THREAD

**Issue by pauloqueiroga** [MicrosoftDocs/azure-devops-docs#8222]
For the git clone command using PAT, this page shows:
git clone https://anything:{yourPAT}@dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName
But that gives a "fatal: Authentication failed for ..." message. The correct syntax is as follows:
git clone https://{yourPAT}@dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName

Specifically: no username; no "anything"; and no colon ":".

Please correct the docs, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops-2019&tabs=preview-page#feedback)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @pauloqueiroga. I have this update in a PR, which should be live sometime today or early tomorrow. Thanks again and have a great day!
