### ISSUE TITLE
Does PublishPipelineArtifact@1 support wildcard or glob pattern?

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-devops-docs#8225]
The documentation doesn't say much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by abatishchev** [comment]
@msebolt, @vijayma gentle ping.

**Comment by abatishchev** [comment]
@msebolt, @vijayma ping.

**Comment by abatishchev** [comment]
@msebolt, @vijayma ping.

**Comment by vtbassmatt** [comment]
Wildcards are not supported. You can target a specific file or directory (and if the latter, you'll get everything in the directory).

**Comment by seanblonien** [comment]
@Alcas1 
I have this use case where there are multiple files that need to be published, and they all share a similar globbable path, but I just have to repeat the `PublishBuildArtifacts@1` task even tho they all look nearly identical.

However, because artifacts all require names, I assume each artifact having a unique name makes globbing `PathToPublish` to make sense, cause if you matched multiple files or directories, what would you name each Artifact? If you just wanted all of the files and folders published, then you'd just copy them to one folder and publish that folder with one name. So after thinking about it, only singular files/folders makes sense

**Comment by Alcas1** [comment]
@seanblonien 
I ended up discovering this solution myself with a bit of tinkering but it still seems like a workaround as of now. Our files are quite big and take up a couple gigs so it would be best if we could avoid needing to copy these files anywhere at all

**Comment by MaximBalaganskiy** [comment]
> So after thinking about it, only singular files/folders makes sense

Cannot agree. Whatever your glob picks up will be an artifact with a single name. Similar to publishing a folder as an artifact.

**Comment by CDixon0416** [comment]
I'm in a scenario where we use git commits for the actual package names so that versioning is part of the file name, being able to wildcard for packages would make this be a simple task instead we need to investigate a workaround to capture what the unique version is and pass that to the task.

**Comment by pmvelkov** [comment]
I needed to filter specific assets, which I needed to upload. The "workaround" I used is to copy the desired one and then upload the whole temp folder. 
Example:
          - task: CopyFiles@2
            displayName: 'move desired artifacts'
            inputs:
              sourceFolder: source_folder/
              contents: '**/?(*.log|*.jar)'
              targetFolder: 'source_folder/temp/'

          - task: PublishBuildArtifacts@1
            displayName: 'publish artifacts'
            inputs:
              pathToPublish: source_folder/temp/
              artifactName: filtered-artifacts
