### ISSUE TITLE
Enabling Dependency Bot notifications

### ISSUE THREAD

**Issue by sonal-b** [MicrosoftDocs/azure-devops-docs#8229]
The 'Dependency Bot' section doesn't provide enough details on what needs to be done to enable the notifications, and whether the notifications can be managed by users through their preferences.

Please add that detail.

For the record, I have not received any notifications to date for the scenarios handled by the Dependency Bot - hence I'm not sure its working properly/enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1714e91-58b6-9911-0da6-7555d09eccb3
* Version Independent ID: 2a317fb7-67cb-a355-8fe2-8cd0e147acdc
* Content: [Plan and track dependencies across teams and organizations using the Dependency Tracker extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/dependency-tracker?view=azure-devops#feedback)
* Content Source: [docs/boards/extensions/dependency-tracker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/extensions/dependency-tracker.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by soccerjoshj07** [comment]
I don't think the dependency bot is installed with this extension, or at least I've never seen it work? Not sure if this should be struck from the documentation or if anything needs to be added from dev team to make this work.

**Comment by KathrynEE** [comment]
@sonal-b, @soccerjoshj07 - Thank you for your feedback. I'm commenting out the information on the Dependency Bot for now. This extension isn't owned by a product team, so any issues should be forwarded to the extension website.  I will revisit this if/when updates are made to the extension.
