### ISSUE TITLE
Doesn't help at all !!

### ISSUE THREAD

**Issue by advent77** [MicrosoftDocs/azure-devops-docs#8230]
I know I need a PAT to link LCS and VSTS (DevOps). I've now got one, but the ridiculous situation is that when I try to set-up the link between LCS and my DevOps project, the poorly written UI tells me that I need a Personal Access Token and then directs me to this URL !! Absolute nonsense and typical of the circles we all run around to get any Microsoft Integration working as intended!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@advent77 Thank you for the feedback and we apologize for the issues you're having.

Please see if [this post](https://developercommunity.visualstudio.com/content/problem/868724/the-personal-access-token-configured-for-this-proj.html) addresses the issue and consider reporting this issue to the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

If there is a step in particular that is causing issue, please reference it below and we can assign an author to further investigate.

**Comment by advent77** [comment]
Thanks for response.
I got the issue fixed!

The problem is the form which is displaying the message that I need a token!

The form is not long enough! The field for entry of the token is “hidden” from view... you need to scroll down to see the input field! 

Can I suggest that this form gets FIXED!!


Regards
Joe

(iPhone mail)

**Comment by msebolt** [comment]
Closing this issue now.
