### ISSUE TITLE
"Request premission" 

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/azure-devops-docs#8231]
Is that "Request premission" thing documented somewhere?

"Your administrator can provision the Wiki Git repository or you can request that they elevate your permissions. Stakeholders can't create a wiki, as they have no permissions to work in Repos or Code."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973bb49c-7fcb-a953-21ff-82b03f899e73
* Version Independent ID: 507b2d8b-9560-9afb-4628-ae562832c7ce
* Content: [Create a project wiki to share information - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/project/wiki/wiki-create-repo?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/wiki-create-repo.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-create-repo.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @BrayanKhosravian, Thanks for reaching out. "Request permission" from your admin isn't documented, as there isn't a request permission feature in the product, like there is for requesting an extension, for example.  Please see this article, [Manage wiki permissions](https://docs.microsoft.com/en-gb/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops). Please @mention me if you have any further questions. Thanks again.
