### ISSUE TITLE
Build.BuildNumber

### ISSUE THREAD

**Issue by hdennen** [MicrosoftDocs/azure-devops-docs#8234]
It strikes me as odd that `Build.BuildNumber` can be used, "[...] but not as part of the build number [...]."

If we could use `Rev` anywhere other than `name` that would be great. But we can't. And since `name` is actually 'Build.BuildNumber' and `BuildNumber` is conveniently accessible from release pipelines it really makes it difficult not to use it as a build number.

Can someone explain why `name`, `Rev`, and `BuildNumber` exist they way they do? It makes no sense to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@hdennen Can you please post your question in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? That site is actively monitored by the product team. If there are documentation updates to make, we will be sure to update the docs.
