### ISSUE TITLE
For linux Not working now

### ISSUE THREAD

**Issue by kotaroino** [MicrosoftDocs/azure-devops-docs#8235]
The linux sample has stopped working.

Maybe there is no Link
`pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
`

It worked↓
`pip install azure-cli
`
Check it out

error log ↓
```
Login Azure DevOps Extension

View raw log

Starting: Login Azure DevOps Extension
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/b943a396-59e6-4b1b-beca-208db20f4856.sh
Unable to use secure credential store in this environment.
Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
using Environment variable
or use 'az login'
_run_pip() missing 1 required positional argument: 'extension_path'

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops#for-windows-azure-pipelines-steps-winyml)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by turbut** [comment]
Same issue here.
Debug does not give any more info....

**Comment by jf781** [comment]
Had same issue.  Modified steps as @kotaroino described and it is now working.

**Comment by kotaroino** [comment]
There was an update of azure-cli 2.6 on May 19, and it stopped working.

<https://pypi.org/project/azure-cli/#history>

It works by specifying the version.

```bash
pip install azure-cli==2.5.1
```

Is it necessary to update "az cli" in the first place?
Doesn't it work with the default version?

**Comment by ashishonce** [comment]
there was a breaking change in azure-cli, which broke the way  devops-extension uses dependent package,  azure.cli.core.extension and azure.cli.core.extension.operations
this was the change that broke, the way extension was installing packages. 
https://github.com/Azure/azure-cli/commit/76742362fc9c44ca968859f748ec3bb594d75271

a pull request to fix this was raised. will follow-up on its state. 
https://github.com/Azure/azure-devops-cli-extension/pull/1003

**Comment by KathrynEE** [comment]
@ashishonce - Can you follow up on the satus of the PR and if there are any changes to be made to the content? Thanks.

**Comment by KathrynEE** [comment]
@kotaroino, @turbut, @jf781 -  Closing this issue as the underlying problem has been fixed.
