### ISSUE TITLE
Custom package version

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#8236]
Above it is mentioned that also the custom package version can be specified while uploading a universal package.
Does it mean I can use a different version format than the semver major.minor.bugfix (all parts numbers) ?
When reading the documentation this is not clear to me.
Finally I am wondering if something like a 'head' version can be realized using universal packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish & download Universal Packages - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by magleaso** [comment]
Sorry I agree this is confusing as written. The options for publishing a new version are major, minor, patch, or custom. Custom allows you to input any SemVer 2 compliant version number for your package. The other options will get the latest version of this package from your feed and increment the chosen version segment by 1. So if you have testPackage v1.0.0, and you publish a new version of testPackage with the 'major' option, your newly published package will receive the version 2.0.0. Minor would result in 1.1.0, patch would result in 1.0.1.

**Comment by ramiMSFT** [comment]
@MTomBosch Thank you for your feedback. The updated article will go live shortly.
