### ISSUE TITLE
How to set up GPU VMs for CI?

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/azure-devops-docs#8240]
I search for keyword GPU under "Azure DevOps Services" but the search result is empty. Does it mean GPU machines are not available for CIs? If GPU machines are allowed, could you please share some documents? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf8bb33-e4cf-3dc5-5510-1111b8f1bdbf
* Version Independent ID: 3148d97d-2ff1-30f5-0487-dbfe93888a3f
* Content: [Deploy nginx to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=azure-devops&tabs=java#feedback)
* Content Source: [docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@wschin  Thank you for the feedback.

This feature is currently in **Preview**, please see [Deploy container instances that use GPU resources](https://docs.microsoft.com/azure/container-instances/container-instances-gpu) for more information.

**Comment by msebolt** [comment]
Closing this issue now.
