### ISSUE TITLE
Not clear how to publish to nuget.org

### ISSUE THREAD

**Issue by ahelwer** [MicrosoftDocs/azure-devops-docs#8246]
Apparently NuGetAuthenticate isn't necessary for nuget.org because it doesn't accept API key authentication. Publishing to nuget.org is an extremely common use case and should be covered explicitly in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by ahelwer** [comment]
Open?

**Comment by mijacobs** [comment]
@ramiMSFT Can you take a look? 
@ahelwer If you have the info that needs added to the doc, we accept contributors--if you open a PR to update the doc, we have team of reviewers standing by to review and accept your updates.

**Comment by ahelwer** [comment]
I don't have the info because I couldn't figure out how to make it work from the docs.

**Comment by ramiMSFT** [comment]
@ahelwer My apologizes for the delayed response and thank you for your feedback. A backlog item has been created and I will be updating the article shortly.

**Comment by ramiMSFT** [comment]
@ahelwer The new content is live: [Publish packages to NuGet.org](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish-to-nuget-org?view=azure-devops&tabs=dotnet)
