### ISSUE TITLE
"Override template parameters" how to pass an environment variable

### ISSUE THREAD

**Issue by sdg002** [MicrosoftDocs/azure-devops-docs#8247]
If it were a simple Release variable, I could use the structure $(somevariable)
But, what if I need to pass the value of an Environment variable
E.g. TEMP
Should I use $(TEMP) or $(env:TEMP) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@sdg002  Thank you for the question.

The syntax depends on the particular OS environment, see [environment variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables&tabs=yaml%2Cbatch#environment-variables).

Please comment below if you need additional information, or for help with user-specific scenarios, see [Azure DevOps support](https://azure.microsoft.com/support/devops/).

**Comment by sdg002** [comment]
@msebolt 

Please check the link on "**environment variables**" .

![image](https://user-images.githubusercontent.com/20245330/81748851-76fb1280-94a2-11ea-87e2-362f2efbe542.png)

Thank you

**Comment by msebolt** [comment]
@sdg002 Fixed link

**Comment by msebolt** [comment]
Closing this issue now.
