### ISSUE TITLE
There's no gradle relevant content on this document

### ISSUE THREAD

**Issue by edwardhu** [MicrosoftDocs/azure-devops-docs#8250]
In the Azure Artifacts, I saw the Gradle option but can not find any relevant content here.
Does the Gradle got fully support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 078a8c96-ec59-c10b-e48e-8c5586c8cb09
* Version Independent ID: 200f5723-2404-298d-e6bb-533592a28ff3
* Content: [Azure Artifacts in Azure DevOps - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops#feedback)
* Content Source: [docs/artifacts/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/overview.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@edwardhu Thank you for your feedback. Gradle has limited Artifacts support. Check out the below existing articles for the details:
* [Install a Maven artifact using Gradle](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/pull-package-gradle?view=azure-devops)
* [Publish a Maven artifact using Gradle](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/publish-package-gradle?view=azure-devops)
* [Build task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops)
