### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by orpitaPesto** [MicrosoftDocs/azure-devops-docs#8251]
I am a newbie to azure devops , I just want to know how to add plugin to an Azure Devops and how to see the working execution and debug it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4136c15d-672e-44b0-b42b-16b877deb381
* Version Independent ID: 16df8860-d655-b092-2f8b-aaa5d1b2e955
* Content: [FAQs about getting extensions for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/faq-extensions?view=azure-devops)
* Content Source: [docs/marketplace/faq-extensions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/faq-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@orpitaPesto Thank you for the question.

Please refer to [this tutorial](https://docs.microsoft.com/azure/devops/extend/develop/add-build-task?view=azure-devops) and post any questions or comments below if there are issues running the sample.

@chcomley

**Comment by msebolt** [comment]
Closing this issue now.
