### ISSUE TITLE
Build.DefinitionName ?

### ISSUE THREAD

**Issue by AndrewR66** [MicrosoftDocs/azure-devops-docs#8253]
Both $(Build.DefinitionName) and $(BuildDefinitionName) are mentioned. Is the first one a typo ? If not, could you explain the difference ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@AndrewR66 Thank you for the feedback.

Please refer to the correct usage as `$(Build.DefinitionName)`.

The documentation has been updated and is pending review, see about [becoming a contributor](https://docs.microsoft.com/contribute).
