### ISSUE TITLE
Runtime parameters for pipeline template 

### ISSUE THREAD

**Issue by jhoyosg5** [MicrosoftDocs/azure-devops-docs#8256]
Hi,

I love the idea of having runtime parameters, but when I add them to my templates, it doesn't work the same way, that when I add the runtime parameters directly to the pipeline, is there any way to add runtime parameters to the pipelines templates?

Thanks

**Comment by msebolt** [comment]
@jhoyosg5 Thank you for the question.

Please refer to [this issue](https://developercommunity.visualstudio.com/content/problem/872011/passing-variables-in-azure-pipelines.html) previously addressed by the product team in [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Or, for additional support refer [here](https://azure.microsoft.com/support/devops/), or provide a reference to one of the repo's articles.

**Comment by msebolt** [comment]
Closing this issue now.
