### ISSUE TITLE
Protected branch check.

### ISSUE THREAD

**Issue by sanjeevmajgotra** [MicrosoftDocs/azure-devops-docs#8257]
Can this check be added at pipelines?
I don't see this option approval and checks in pipeline.environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40fccec-c358-843c-10d5-7ea367f6e406
* Version Independent ID: 45390d5d-c1d7-c90e-ef3f-2768d406ba7b
* Content: [Pipeline resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/resources?view=azure-devops)
* Content Source: [docs/pipelines/security/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/resources.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@sanjeevmajgotra Thank you for the feedback.

Please see if any of [these posts](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=protected+branch) addresses the issue, or try soliciting direct feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

If there are any concerns or questions regarding the documentation, please comment below.

**Comment by msebolt** [comment]
Closing this issue now.
