### ISSUE TITLE
Move the Note to the pre-requisites if it is true, but please make it NOT true ;)

### ISSUE THREAD

**Issue by successhawk** [MicrosoftDocs/azure-devops-docs#8258]
[Enter feedback here]
Regarding: 
![image](https://user-images.githubusercontent.com/3745327/81459066-ee136c80-916b-11ea-8bec-63555dfe642a.png)

1. Why is this Note in the middle of the page?  Shouldn't this be in the pre-requisites?  I didn't see this until after I tried to subscribe and it misleadingly told me that my project had no git repos.  Inform users up front so that they don't waste their time if they only have private repos.
2. How do I make a repo public?  Can you link to instructions?
3. If this connector only supports public repos, then please make the error messages more accurate.
    1. When trying to subscribe to ALL repositories: No mention of **public** here
![image](https://user-images.githubusercontent.com/3745327/81459238-e607fc80-916c-11ea-8ffe-ee65efac6c56.png)
    2. When trying to subscribe to a specific repository: No mention of **public** here, and this repository definitely exists.
![image](https://user-images.githubusercontent.com/3745327/81459324-544cbf00-916d-11ea-8a2f-0c6ded743661.png)
1. Why do you only support public repos?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @divya
* Microsoft Alias: **divais**

**Comment by msebolt** [comment]
@successhawk Thank you for the questions and feedback.

For both DevOps and/or TFVC, repos are associated with projects, please see [Make your project public or private](https://docs.microsoft.com/azure/devops/organizations/public/make-project-public) on how to make the project public.

The documentation has been updated and is pending review.

Items 3 and 4 are valid considerations, however approval from the product team is required before new features are added to the timeline.  

Please use either **Suggest a feature** or **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback.
