### ISSUE TITLE
git push --mirror is dangerous

### ISSUE THREAD

**Issue by chriscortopassi** [MicrosoftDocs/azure-devops-docs#8259]
We ended up losing a bunch of branches because of --mirror (it will delete any branches not in the source repo). Please consider omitting --mirror and/or documenting that it can delete branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops#feedback)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@chriscortopassi Thank you for your feedback and our apologies for the issues this caused.

The documentation has been updated with a warning and is pending review.
