### ISSUE TITLE
Odata Inconsistent

### ISSUE THREAD

**Issue by nbrown02** [MicrosoftDocs/azure-devops-docs#8260]
I've found an issue with the guidance here - it appears there are inconsistencies between projects as to how the data is coming through. Issue logged at https://developercommunity.visualstudio.com/content/problem/1019488/odata-inconsistencies.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40bb3182-6622-0d21-31d8-db6db932cc8d
* Version Independent ID: 868c0e69-6528-a5d7-10f5-c0b384bc9310
* Content: [Requirements tracking, Stories overview rollup report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-stories-overview-rollup?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-stories-overview-rollup.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-stories-overview-rollup.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **shdalv**

**Comment by msebolt** [comment]
@nbrown02 Thank you for the feedback and for soliciting feedback from the product team.

We will provide the updates to documentation depending on how this is resolved.

**Comment by nbrown02** [comment]
If you check the link I posted we’ve found the source of the bug. If it can’t be fixed it’s probably worth updating the documentation here just so users are aware, otherwise they’re likely to have a moan 🙂

**Comment by KathrynEE** [comment]
@nbrown02 - THank you for your follow through on this issue. I'm updating the article today to reinforce the need to have *requirement-based test suites* defined.
