### ISSUE TITLE
How to access the selected branch name and ref of a repository resource?

### ISSUE THREAD

**Issue by djee-ms** [MicrosoftDocs/azure-devops-docs#8262]
The branch/ref of the repository resource can be configured at runtime via the Run dialog, but how can we access the actual branch name and ref that the user running the pipeline selected?

The job logs clearly show that there are such variables:
```
Evaluating: and(eq(resources['repositories']['self']['ref'], resources['repositories']['self']['defaultBranch']) ...
```

But no matter the syntax I tried, I cannot get any value.
- ${{resources['repositories']['self']['ref']}}
- $(resources['repositories']['self']['ref'])
- $[resources['repositories']['self']['ref']]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops&source=docs#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@djee-ms  Thank you for the feedback.

Please see if [this active post](https://developercommunity.visualstudio.com/idea/816606/allow-variables-at-resourcesrepositoriesrepository.html) in the **Azure DevOps** community addresses the issue.

If so, add this information there to solicit a response from the product team.

**Comment by djee-ms** [comment]
@msbolt the post is a feature request. That doesn't explain why the variable seem to exist looking at the logs of the job prepare, yet can't seem to be accessible. Any idea?

**Comment by msebolt** [comment]
@djee-ms Undocumented variables would require additional feedback from the product team.

Can `System.PullRequest.SourceBranch` from the [System variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables) not achieve this functionality here?

**Comment by djee-ms** [comment]
The secondary branch is not the source branch, I don't see how this variable would be any related with a repository resource. You can have (in theory) an unlimited number of repository resources in addition of the primary repository (where the yaml pipeline is stored), how could all of those ever map to a single variable?

**Comment by msebolt** [comment]
Assigning this to the author for a review of current functionality.

For unreleased product features, you'll need to direct this to the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by AlexDenton** [comment]
I'd like to bump this question. The linked thread is very tangentially related. Ability to know the branch name of the repository  resource is the opposite of setting the branch based on a variable.

**Comment by vtbassmatt** [comment]
@AlexDenton I don't think we had made the `resources` context variable available to pipeline authors before. It should be now. I've also [updated the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#repository-details) to reflect that.

**Comment by AlexDenton** [comment]
This is great news! Super helpful.
