### ISSUE TITLE
Task Docker@0 fails on Azure Pipeline vmimage windows-latest or windows-2019

### ISSUE THREAD

**Issue by thovipe** [MicrosoftDocs/azure-devops-docs#8264]
After serveral attempts to build an image with the task Docker@0 or Docker@2, the process fails every time.

The scenario is the following:

ymal build template with two stages
Stage 1 - builds the app
Stage 2 - builds the docker image and pushes to registry
Simple.

We use this task on other pipelines, but it only works when there is no other task. Besides a replace tokens task like:  colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1.

On the build pipeline with two stages the Docker task returns errors that can not find docker command.

Agent name: 'Hosted Agent'
Agent machine name: 'WIN-JSNSO4LLK4M'
Current agent version: '2.166.4'
Current image version: '20200430.2'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DownloadPipelineArtifact (2.3.0)
Downloading task: ReplaceTokens (1.2.178)
Downloading task: Docker (2.166.1)
Checking job knob settings.
Finished checking job knob settings.
Start tracking orphan processes.

![image](https://user-images.githubusercontent.com/44453054/81487268-92abb200-9231-11ea-9ba8-b1fc7a057935.png)
Task log, build pipeline with 2 stages:
##[error]Unhandled: Unable to locate executable file: 'docker'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

On the build pipeline that has only Replace tokens task runs fine.

Agent name: 'Hosted Agent'
Agent machine name: 'WIN-JSNSO4LLK4M'
Current agent version: '2.166.4'
Current image version: '20200430.2'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: ReplaceTokens (1.2.178)
Downloading task: Docker (0.157.0)
Checking job knob settings.
Finished checking job knob settings.
Start tracking orphan processes.

Log task sample:
C:\Program Files\Docker\docker.exe" build -f D:\a\1\s\Dockerfile -t
![image](https://user-images.githubusercontent.com/44453054/81487380-9855c780-9232-11ea-89b1-9ffe785d4a7b.png)

In both build pipelines the agents are the same.

I also did a test with self-hosted agents and the same issue.

**Comment by msebolt** [comment]
@thovipe Thank you for the feedback.

Please see if [this recent post](https://developercommunity.visualstudio.com/content/problem/926040/docker-build-task-in-azure-devops-for-windows-cont.html) addresses the issue.

**Comment by thovipe** [comment]
I am already using the latest versions, the point that is we have some other pipelines working. Today I did a adjust in a old pipeline definition and broke that one was well. Even removing the adjust did not solve. I had to revert the definition.

**Comment by thovipe** [comment]
Guys problem solved.
It was a bad variable name. 
Thanks for the support.
