### ISSUE TITLE
Tasks are not parallel, and scheduling is stupid.

### ISSUE THREAD

**Issue by da2018** [MicrosoftDocs/azure-devops-docs#8266]
strategy:
      matrix:
        stable:
          rustup_toolchain: stable
        beta:
          rustup_toolchain: beta
        nightly:
          rustup_toolchain: nightly

1. The tasks are not parallel
There're 9 pipeline jobs triggered by my project, and because the tasks are not parallel, so the task execution takes dozens of minutes, all the tasks are executed one by one.

2.After the task is cancelled, those in the back are still in the queue
Because the jobs takes so long time, I canceled the jobs, but the rest of the task were still in queue, why the scheduler is so stupid ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5552e8c4-b0c2-f3ff-c69a-607166afb611
* Version Independent ID: 8e73c13c-9b2b-0eac-45ec-4bd3a8d01bb1
* Content: [Create a multi-platform pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops#feedback)
* Content Source: [docs/pipelines/get-started-multiplatform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started-multiplatform.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by da2018** [comment]
![image](https://user-images.githubusercontent.com/16920793/81499527-dcae9980-92fe-11ea-97eb-3233e7e50890.png)

**Comment by msebolt** [comment]
@da2018  Thank you for the feedback and we apologize for any issues you're having.

Unfortunately we can only address concerns with documentation in this forum.  For product-related issues, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html). 

See if [this post](https://developercommunity.visualstudio.com/content/problem/994495/cancelled-builds-with-running-tasks.html) or one of [these posts](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=Cancelled+Builds+with+Running+tasks) relates to your issue and add your comments there to solicit feedback directly from the product team.

**Comment by msebolt** [comment]
Closing this issue now.
