### ISSUE TITLE
"HTML tags and fontawesome aren't supported in the Mermaid diagram syntax."

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8267]
This isnt exactly true. `&lt;br&gt;` tags work fine for breaking up longer lines of text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by StingyJack** [comment]
@msebolt  - oh, yeah. aka "submit a pr".  I've done that before and just forget that is an option from time to time.
