### ISSUE TITLE
Can't connect Power BI to Azure DevOps even with "View analytics" permission.

### ISSUE THREAD

**Issue by qzxpqbp** [MicrosoftDocs/azure-devops-docs#8268]
I can't connect Power BI to Azure DevOps. I still get the error "We couldn't authenticate with the credentials provided. Please try again." even when I have "View analytics" permission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f04bf6a-1455-8770-0a2e-da22f644bced
* Version Independent ID: d63dea23-3678-60c4-c028-c4b618fc3613
* Content: [Analytics permissions and security - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-security?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/analytics-security.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/analytics-security.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@qzxpqbp Thank you for the feedback, we're sorry for the issues you're experiencing.

Please go through the steps outlined in [this post](https://developercommunity.visualstudio.com/content/problem/788834/not-able-to-connect-power-bi-to-devops-project-oda.html) using an OData feed to find out which one is causing issues.

You can also try soliciting feedback from the Power BI product team [here](https://community.powerbi.com/t5/Issues/quot-We-couldn-t-authenticate-with-the-credentials-provided-quot/idi-p/791450) or try the [Azure DevOps community](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by msebolt** [comment]
Closing this issue now.
