### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by kubasiak** [MicrosoftDocs/azure-devops-docs#8270]
It would be very helpful to give any template/example/or even just description what is 'test' in 

- script: |
    pip install pytest
    pip install pytest-cov
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This topic isn't intended to walk you through PyTest or teach its concepts. The expectation is that someone would already be familiar with testing Python code or specifically with PyTest.
