### ISSUE TITLE
Documentation missing for metadata labels for self-hosted agent

### ISSUE THREAD

**Issue by nachiketrss** [MicrosoftDocs/azure-devops-docs#8271]
In the "Overview" section, under "Metadata added as labels" - The documentation for self-hosted agent metadata labels is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@nachiketrss Thank you for the feedback.

The documentation has been updated and is pending review.
