### ISSUE TITLE
Confluence space migration to Azure Wikis

### ISSUE THREAD

**Issue by KehindeOwens** [MicrosoftDocs/azure-devops-docs#8274]
I am attempting to migrate my confluence spaces to Azure wikis. Unfortunately when I do (I export the spaces in XML and convert them to Markdown) they are not readable. Has this migration been done successfully and if so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@KehindeOwens Thank you for the question.

Please try using tools with Atlassian to convert directly to markdown, then report any issues rendering in the MD in DevOps.  There are some descriptions in [this post](https://community.atlassian.com/t5/Confluence-questions/export-to-markdown/qaq-p/307481) for tools such as **Turndown** or **Markdown Exporter**.

**Comment by KehindeOwens** [comment]
Thank you @msebolt. Will do

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.

**Comment by ScottWelker** [comment]
This Q&A may be of some use to anyone attempting this: [StackOverflow: Is there a way transfer pages from “Confluence” to “Azure Devops Wiki”](https://stackoverflow.com/questions/61678087/is-there-a-way-transfer-pages-from-confluence-to-azure-devops-wiki)

**Comment by KehindeOwens** [comment]
There is an alternative that might be worth giving a shot. Thanks for the find @ScottWelker

**Comment by ViswaMohan88** [comment]
Hi Kehinde,
Did you found a way to migrate Confluence to Azure WIKI. If yes, Can you please share me the process.

**Comment by mmckanna-nuance** [comment]
@ViswaMohan88 I did find a tool in DevOps built specifically for this purpose using a pipeline, called InfoSys Knowledge Migrator. I have completed all steps but haven't been able to get it working myself as of yet. I just reached out to my SRE team for assistance today and will update if any headway is made. If any of you have used this or have functional pipeline, please reach out so I may see what I'm missing. Thanks in advance.

**Comment by rijssel** [comment]
@mmckanna-nuance Did you make progress on this? I tried to tool so far and got an unexpected token at position 0 in the JSON right away.

**Comment by aakanshaverma1310** [comment]
@ScottWelker - Hey, do you any way to migrate azure devops wiki docs to confluence?

**Comment by ScottWelker** [comment]
@aakanshaverma1310: I haven't gone the other direction. I am not fond of Confluence in large part because of their closed, non-standard system. I prefer the portability of markdown. However, I imagine you could leverage the Confluence API to go the other direction, i.e. recurse a cloned a Azure DevOps Wiki's git repository's .md files and transform their quasi-standard markdown into Confluence's proprietary format, via Confluence's RESTful API - and perhaps ancillary tools like those in the [remark.js.org collection](https://remark.js.org/) (or others). Not simple but I imagine that would work.
