### ISSUE TITLE
WIQL $Top Question

### ISSUE THREAD

**Issue by haiku08** [MicrosoftDocs/azure-devops-docs#8275]
I was wondering more about the "$top" function in WIQL (Work Item Query Language). I literally tried to put in a URL that triggers a query in WIQL to be this: "https://office.visualstudio.com/GSX/_workitems?_a=query&wiql=SELECT [System.ID], [System.Title], [System.State], [System.CreatedDate]
FROM WorkItems
WHERE [System.WorkItemType]='Bug'
ORDER BY [System.CreatedDate] desc with $top=1"

However, it says there is an error that "with" is not acceptable and causes an error. I'm thinking I am not putting the "$top=1" in the right spot. Where do I put the "$top=1" in this URL (for the purpose of limiting my query to the first row only)?

Or if there is an alternative method to only showing the most recent work item, I am open to hearing that as well.

**Comment by msebolt** [comment]
@haiku08 Thank you for the question.

According to the [WIQL reference](https://docs.microsoft.com/rest/api/azure/devops/wit/wiql/query%20by%20wiql?view=azure-devops-rest-5.1) `$top` is included in its own request line item:
```
POST https://dev.azure.com/{organization}/{project}/{team}/_apis/wit/wiql?$top={$top}
```

...so your example should be:

```
https://office.visualstudio.com/GSX/_workitems?_a=query&wiql=SELECT [System.ID], [System.Title], [System.State], [System.CreatedDate]
FROM WorkItems
WHERE [System.WorkItemType]='Bug'
ORDER BY [System.CreatedDate] desc&$top={$top}
```

**Comment by haiku08** [comment]
@msebolt Thank you very much for the response. However, this did not work. I tried "...&$top=1," "...&top=1," "...&1={$top}," and "&$top={1}," at the end of URL after the "desc" part. The URL seemed to just ignore the "$top" portion of it and still just printed the total amount of rows this applied to. Maybe I am not doing this correctly?

**Comment by msebolt** [comment]
@haiku08 The reference documentation includes the WIQL in the body of the POST as opposed to GET parameters, perhaps try using POST instead?

Also, there's an [editor](https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor) mentioned in [this post](https://developercommunity.visualstudio.com/content/problem/267364/work-item-and-direct-link-wiql-query.html) that could help diagnose.

**Comment by haiku08** [comment]
@msebolt okay wow. This makes sense why it does not work then. In terms of then writing a post URL, I have researched quite a bit for that last 2 days the difference between POST and GET and I am unbelievably overwhelmed on how to do this. I have also seen I can only input a "get" URL into a browser. So given that, any guidance on how to convert the above URL into a Post url and somehow displaying the results in a browser... which would in turn I would think convert the URL in the URL bar into a "GET" URL (but who knows, I'm making stuff up here)? I appreciate all the time you have put in already.

**Comment by msebolt** [comment]
@haiku08 No problem, see [this example](https://www.w3schools.com/xml/ajax_xmlhttprequest_send.asp) for a good explanation.
