### ISSUE TITLE
Typo in markdown to list shelvesets for all users

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/azure-devops-docs#8280]
> If you don't know the name of the owner, you can type ***** to list shelvesets for all users.

I am using visual studio 2019,  the description above is incorrect, only one `*` needed to list shelvesets for all users. I knew you want to bold the “*” in the description,  it's `**\***` via markdown not `*****`.

BTW, the same functionality is not available in **Azure DevOps** Repos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd36c9f-c60e-6191-f344-0cd8c0829bb6
* Version Independent ID: 25868222-c846-1e31-9373-a741df436cb6
* Content: [Suspend your work and manage your shelvesets - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/suspend-your-work-manage-your-shelvesets?view=azure-devops#find-a-shelveset)
* Content Source: [docs/repos/tfvc/suspend-your-work-manage-your-shelvesets.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/suspend-your-work-manage-your-shelvesets.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@ToMakeSense Thank you for the feedback.

The documentation has been updated and is pending review.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
