### ISSUE TITLE
Confusing comment

### ISSUE THREAD

**Issue by abij** [MicrosoftDocs/azure-devops-docs#8281]
In the code example in the section: [use-the-output-variable-from-a-job-in-a-condition-in-a-subsequent-job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#use-the-output-variable-from-a-job-in-a-condition-in-a-subsequent-job) is a comment which confuses me:

`echo "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #The variable doThing is set to true`

It's set to `Yes` value and not to `true`, or does isOutput do something? Can you explain the `isOutput` part more specific?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#use-the-output-variable-from-a-job-in-a-condition-in-a-subsequent-job)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by lukeb4** [comment]
Hi abij,
by using isOutput=true you can make a variable available to future jobs. You can read more about it here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable

**Comment by msebolt** [comment]
@abij Thank you for the feedback.

The documentation has been updated to avoid this confusion and is pending review.

@lukeb4 Thank you for the response, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

**Comment by abij** [comment]
thx
