### ISSUE TITLE
Is there a predefined variable in pipeline related to who run this pipeline?

### ISSUE THREAD

**Issue by muhualing** [MicrosoftDocs/azure-devops-docs#8282]
Like the red part in picture.
![image](https://user-images.githubusercontent.com/12086605/81659965-cd4d5e80-946c-11ea-9e48-b082ee854705.png)

**Comment by msebolt** [comment]
@muhualing Thank you for the question.

Please see if `Build.TriggeredBy` is what you need, under [Build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables).

Also note at the bottom of the topic is a useful table listing possible trigger scenarios.

To support a more out-of-box approach, please add your comments to [this post](https://developercommunity.visualstudio.com/idea/1014961/azure-devops-pipelines-teams-bot-include-who-trigg.html) in the product forum.

**Comment by msebolt** [comment]
Closing this issue now.
