### ISSUE TITLE
Does system.debug have an effekt on $VerbosePreference or $DebugPreference

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/azure-devops-docs#8283]
Will $VerbosePreference or $DebugPreference set to "Continue" if i set system.debug to true at queue time or do we have to implement this on our own?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You'll have to implement on your own.
