### ISSUE TITLE
Extensibility point

### ISSUE THREAD

**Issue by MarioMeldau** [MicrosoftDocs/azure-devops-docs#8284]
Hello,

is it possible to add a button or something like that at the marked positon in the image. I did not find any extensibility point for that. 

![extension](https://user-images.githubusercontent.com/50444578/81673302-b9453500-944b-11ea-898b-c1fe1c3d05ba.png)

**Comment by msebolt** [comment]
@MarioMeldau Thank you for your question.

This feature is not yet supported, so you'll need to use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback from the product team.

Until then, please refer to [extensibility points](https://docs.microsoft.com/azure/devops/extend/reference/targets/overview?view=azure-devops) for the latest on supported features.

@chcomley

**Comment by chcomley** [comment]
Hi @MarioMeldau, It would be helpful if you could comment on this issue with a link to your feature request! Thank you so much!

**Comment by chcomley** [comment]
@MarioMeldau, I'm closing this issue, however please @mention me if you have any further questions. Thank you and have a great day!
