### ISSUE TITLE
Fix "Use extends templates" example

### ISSUE THREAD

**Issue by sensslen** [MicrosoftDocs/azure-devops-docs#8287]
There seems to be an error in the first examle:
- ${{ each step in parameters.usersteps }} should be followed by a colon or am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f721e2df-f7e4-8db7-08cc-eab779477c99
* Version Independent ID: 95014030-e9eb-6425-2990-8f9fa2452e7e
* Content: [Security through templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/security/templates?view=azure-devops#set-required-templates)
* Content Source: [docs/pipelines/security/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/security/templates.md)
* Product: **devops**
* Technology: **devops-cicd-security**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
