### ISSUE TITLE
This should show an example on how to use variables in `condition`

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#8294]
something along the lines of

condition: eq(variables['Build.Reason'], 'PullRequest');

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#expansion-of-variables)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@trajano There are examples in the [expressions article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops). I'll add some links to it from the variables article to make the connection clearer.
