### ISSUE TITLE
Enterprise visibility

### ISSUE THREAD

**Issue by payneio** [MicrosoftDocs/azure-devops-docs#8295]
I was taken to this page from ADO project settings page-visibility dropdown. I hoped it would explain to me what "Enterprise" visibility is, but there is nothing about that here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a4e9e9-6773-fad2-23fb-8b44313f8ef3
* Version Independent ID: 33cbd1fc-2230-4e0b-2627-2a63bf7c634e
* Content: [Make your project public or private - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/organizations/public/make-project-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/make-project-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @payneio. "Enterprise Visibility" is deprecated for the vast majority of organizations...I believe you're a Microsoft employee, correct? Could you please contact Parsa Zand for more information? Thank you.

**Comment by sturlath** [comment]
Hi @chcomley I´m not a MS employee and I see this dropdown when I create a project when I´m using my "onmicrosoft.com" email (I will be adding my domain later on). Thought I´d let you know ;-)
