### ISSUE TITLE
Help With SSH Alternate Port 443

### ISSUE THREAD

**Issue by nadnoslen** [MicrosoftDocs/azure-devops-docs#8298]
Some company IT departments do weird stuff like prevent SSH traffic over port 22 but will allow the same traffic  over port 443 (🙄).  

GitHub, BitBucket, GitLab, etc. all allow ssh over port 443 to clone/push/fetch/pull repo data... however `ssh.dev.azure.com` doesn't seem to allow SSH over 443.  Can this be supported and added to this help document?

For example, to SSH-clone from a GitHub repo in one of these restricted corporate environments, we configure our `~/.ssh/config` to:

```shell script
Host github.com
  Hostname ssh.github.com
  Port 443
```

We would expect much of the same from an Azure hosted git repository:

```shell script
Host ssh.dev.azure.com
  Hostname ???.???.dev.azure.com
  Port 443
```

... however this times out.  Please make this convenient.  My Google search of this topic shows threads going back to 2018 so I gotta believe this has been resolved in some way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by nadnoslen** [comment]
Maybe I found a solution to my problem.  As I typed out my `~/.ssh/config` settings I discovered that the host `dev.azure.com` might be the problem; I've since changed my `~/.ssh/config` to have an azure section like this:

```shell script
Host azure.com
  Hostname ssh.dev.azure.com
  Port 443
```

...and it works.  I hope this helps others.  Wow.

**Comment by msebolt** [comment]
@nadnoslen Thank you for the feedback and apologies for any issues you're experiencing.

Please refer to [this post](https://stackoverflow.com/questions/52985167/git-ssh-public-key-authentication-failed-git-azure-devops) and I'll assign this to the author for review of the documentation.

**Comment by nadnoslen** [comment]
Hey @msebolt,

Thanks for your reply!  I took a glance over at this [Stackoverflow Question](https://stackoverflow.com/questions/52985167/git-ssh-public-key-authentication-failed-with-git-on-azure-devops) you linked to, but I don't think that has anything to do with my problem.

What I am trying to do, is tell ssh that all traffic to my repos hosted at `ssh.dev.azure.com` be tunnelled over port 443 instead of 22.  Many large organizations and enterprises block port 22 traffic while connected to their network.  In order to checkout with ssh in one of these environments, we require Azure Dev Ops to provide us some alternative host listening on port 443 for the SSH protocol.

**This is evidenced by every other major Git Repository provider; for example, GitHub (Microsoft's own partner company!) hosts it's repos at `github.com` and provides a host named `ssh.github.com` listening on port 443 for SSH requests.  Bitbucket, same thing, repos are hosted from `bitbucket.org` but there's an alternative host out there at `altssh.bitbucket.org` allowing SSH checkouts of code over port 443.**

I can always use the HTTPS URL, and in fact I've done just that.  But that's not ideal for a number of reasons:

1. On premise CI/CD tools may depend on using SSH keys to checkout code from Azure; if that SSH traffic can't be received at Azure's end on port 443 these CI/CD tools need to find alternative techniques to check out code...
1. Enterprise password policies cause developers to change their passwords frequently.  When these password changes are made, development tools/IDEs with the cached old password are likely to query the remote repo numerous times, failing each time, and then likely locking the developer's account; I've seen this probably a hundred times in numerous organizations...
1. All competing Git hosts have implemented this solution, so can you please follow their good example.

If I missed something in the Stackoverflow question, please let me know.  I've scanned it a couple times, followed some of the links in the question's answers, and still am without a solution.

**Comment by vtbassmatt** [comment]
This is a product feature request, not a doc bug. Please feel free to file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
