### ISSUE TITLE
Cannot subscribe when project name contains spaces

### ISSUE THREAD

**Issue by kornakar** [MicrosoftDocs/azure-devops-docs#8299]
We have an Azure Devops project that has two words ("Companyname DevOps"), so that a release pipeline url is https://dev.azure.com/companyname/Companyname DevOps/_build?definitionId=14 (note how the url breaks up even here in github).

The slack bot gives an error when running /azpipelines subscribe command:

`Configuration failed. Please make sure that the project 'Companyname> DevOps' exists and that you have sufficient permissions.`

Note the added **>** symbol at the end of Companyname in the error message which isn't in the original url when running the command.

If I add another project that doesn't have spaces in its name, the subscription is added successfully.

**Edit: when I replace the spaces with %20, then the subscription is added successfully.** So this is the workaround at the moment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by msebolt** [comment]
@kornakar Thank you for the feedback.

Please report this to the product team [here](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=slack+configuration+failed+space).

From what I can see, no one has yet reported on the spaces being an issue, so this information would be very helpful.

**Comment by msebolt** [comment]
Closing this issue now.  

Please provide a link to the support ticket if you decide to submit this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
