### ISSUE TITLE
NuGet Versioning

### ISSUE THREAD

**Issue by mrbrennonwilliams** [MicrosoftDocs/azure-devops-docs#8301]
I see nothing here that explains how to deliver CI with appropriate versioning in tool. Scenario being that a class library project is created, published in build pipeline as NuGet package. Other projects referencing this package in other Repo/Pipeline does not get an updated package with clear version dilatation. This is particularly challenging for multi dev team environments. Some thoughts and detailed process would be fantastic if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6846e8-96cf-eb56-c5b9-d02e14846eea
* Version Independent ID: d0fcd815-24b6-5f1d-a04c-80f1653ed9b3
* Content: [Set up a multi-developer NuGet environment - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/bootstrap-nuget?view=azure-devops)
* Content Source: [docs/artifacts/nuget/bootstrap-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/bootstrap-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@mrbrennonwilliams Thank you for your feedback. Please refer to [Publish to NuGet feeds (YAML/Classic)](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml) article for more details on how to publish your Artifacts using YAML and Classic.

Also check out the [Package versioning](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml#package-versioning) section for detailed information on the NuGet package versionning.
