### ISSUE TITLE
How to return message to Azure Devops Service Hook

### ISSUE THREAD

**Issue by calmzhu** [MicrosoftDocs/azure-devops-docs#8302]
[Enter feedback here]
In The service hook history. 
![image](https://user-images.githubusercontent.com/10286576/81798036-1e7b5200-9542-11ea-906d-ce8a49321b0f.png)

for events I can see it's success.But we need to return message and displayed in history so users can know execution status. How to ?
current, Onlt HTTP Status Code Is Parsed. But returned data was ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by msebolt** [comment]
@calmzhu Thank you for the question.

In this scenario, you will need to either setup additional [events, subscriptions, and notifications](https://docs.microsoft.com/azure/devops/notifications/concepts-events-and-notifications?view=azure-devops) or refer to the [service hook history](https://docs.microsoft.com/azure/devops/service-hooks/troubleshoot?view=azure-devops).

If this does not solve the issue or to request additional functionality added, please move this issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

@aaronhallberg

**Comment by msebolt** [comment]
Closing this issue now.
