### ISSUE TITLE
Wrong description for Universal Package

### ISSUE THREAD

**Issue by christofer-ja** [MicrosoftDocs/azure-devops-docs#8305]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops#package -&gt; Universal Package has wrong description that belongs to NuGet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops#tool)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@christofer-ja Thank you for the feedback.

The documentation has been updated and is pending review.
