### ISSUE TITLE
Is it possible to use multiple settings file?

### ISSUE THREAD

**Issue by DhirajKhot** [MicrosoftDocs/azure-devops-docs#8306]
We can have a scenario where there are certain integration test cases written which can run on some specific configuration mentioned in one setting file and some other integration test cases written which run on another settings file. 
Is it possible to run all of them by providing both the settings file and have a criteria which setting file should be used to run any particular integration test case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@DhirajKhot Thank you for the question, assigning this to the author for review of the current documentation.

If this feature is not yet supported, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback from the product team.

For additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by PBoraMSFT** [comment]
@DhirajKhot - take a look at the multi config setting for driving the VSTest task. You can use the config variable in different ways - to drive settings in the same file, use that to drive file path names, etc. to achieve your scenario.
https://devblogs.microsoft.com/devops/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/
