### ISSUE TITLE
No subscriptions found.

### ISSUE THREAD

**Issue by Style5000** [MicrosoftDocs/azure-devops-docs#8308]
When i type az login i got an error No subscriptions found.

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@Style5000 Thank you for the question, we're sorry for any issues you're having.

Please refer to [No subscriptions found](https://docs.microsoft.com/azure/cost-management-billing/manage/no-subscriptions-found) or contact [Azure DevOps support](https://azure.microsoft.com/support/devops/) for further assistance.

**Comment by msebolt** [comment]
Closing this issue now.
