### ISSUE TITLE
Forking is listed as a Preview Feature in Azure Repos - Can this be noted somewhere?

### ISSUE THREAD

**Issue by svengeance** [MicrosoftDocs/azure-devops-docs#8312]
Hey guys --

We spent a bit of time trying to find out how we could enable forking in cloud-hosted Azure DevOps. We were continually met with an error stating that we could not fork due to our Policy. There were no options in our repository settings to enable this policy. What we discovered is that Forking is actually a Preview Feature that has to be enabled *for the organization*, and only after that can you update your repository policies to enable forking.

Is it possible to note this somewhere? Please and thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/forks?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/forks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/forks.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by Aaron-von-Awesome** [comment]
Took forever to find out where to enable this, and current documentation is way out-of-date :-(

https://www.reddit.com/r/azuredevops/comments/ginxkt/question_how_does_one_fork_an_azure_git_repo/

**Comment by msebolt** [comment]
@svengeance Thank you for the feedback.

The documentation has been updated and is pending review.
