### ISSUE TITLE
How to import a new work item with an attachment

### ISSUE THREAD

**Issue by angiridhar** [MicrosoftDocs/azure-devops-docs#8313]
is it possible to add one or more attachments during import of work item? can be done via CSV or excel method mentioned here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@angiridhar - No, support for importing attachments while importing or updating work items isn't a supported feature. You may be able to programmatically add attachments using the REST API, https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.1#add-an-attachment.

**Comment by KathrynEE** [comment]
@angiridhar - On reflection, you can import new work items and add attachments using Excel. I'm in the process of updating the Bulk modify using Excel article to reflect this. 

To add attachments, choose the work item, then **Links and Attachments**, and then the **Attachments** tab. Choose the file you want to attach, then choose **OK** and then **Publish**.

![image](https://user-images.githubusercontent.com/10856840/82595492-80e3dc00-9b5a-11ea-9769-c280cd253514.png)

When finished, choose **Close** to dismiss the dialog.
To add the same attachment(s) to several work items, multi-select them by using **Ctrl-click** for consecutive rows, or **Shift-click** for non-consecutive rows.
