### ISSUE TITLE
How to Configure Nested Key-Value of AppSettings?

### ISSUE THREAD

**Issue by IndreamLuo** [MicrosoftDocs/azure-devops-docs#8314]
Hi,

I was trying to set connection strings so that I needed to set appsettings nested while it only provided root layer key-value option.

I tested:
-"ConnectionString myStringKey" myStringValue
-ConnectionString:myStringKey myStringValue
-ConnectionString::myStringKey myStringValue
-ConnectionString.myStringKey myStringValue
-ConnectionString_myStringKey myStringValue
-ConnectionString__myStringKey myStringValue
-ConnectionString "{ myStringKey: myStringValue }"
-SQLAZURECONNSTR_myStringKey myStringValue
But all not working.

Is adding nested k-v of appsettings not implemented?

The target instance is a Azure Web App in Linux Container (Docker).

Thank you.

**Comment by msebolt** [comment]
@IndreamLuo  Thank you for the question.

For product-related issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, please provide a reference to the documentation to where you think this information should be included.

For additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by IndreamLuo** [comment]
@msebolt Thank you for your reply.
I took time to tested with the application and found that the connection string was successfully passed to the Azure Web App Container(Docker). The thing was that, the passed connection string won't be shown on the Connection Strings part of the configuration of the Azure Web App but remain 'ConnectionStrings__MyDatabase' on Application Settings. In .net core runtime, the config value could be achieved as a nested config value.

This part of behaviour isn't mentioned in [https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-connection-strings](https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-connection-strings) or [https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops).

It's mentioned by Note in [https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-app-settings](https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-app-settings) but without mentioning the Azure Web App won't put the nested config in Connection Strings but remain 'ConnectionStrings__Child' it may be confusing while working on configuration of an Azure Web App Container(Docker) instance.

Thanks again.

**Comment by msebolt** [comment]
@IndreamLuo  Thank you for the detailed explanation.  

We'll have the documentation updated accordingly.

**Comment by KathrynEE** [comment]
@msebolt - I think this needs to be reassigned. And I'm not sure if this is in the azure-devops-docs repo. Not clear what article needs updating.

**Comment by msebolt** [comment]
@KathrynEE Thank you for the update.

Given this lies more in the realm of Azure App Service's functionality constraints, I'll assign this to the author from azure-docs.
