### ISSUE TITLE
It is not clear how the "Remove SourceFolder" works

### ISSUE THREAD

**Issue by ricardomomm** [MicrosoftDocs/azure-devops-docs#8316]
I didn't try it but I cannot tell by reading the documentation how it would work... if it would first try to remove the Source Folder entirely and if does not work fallback to the Contents specification, how this flag plays with the Contents specification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Doc PR is in progress. The design is a little strange - you MUST pass a pattern to `Contents` or else we'll early-out and never try to remove the source folder. I suggest `*` (and in fact that's what I put in the doc update).
