### ISSUE TITLE
Is path exclude required?

### ISSUE THREAD

**Issue by jason-ortiz** [MicrosoftDocs/azure-devops-docs#8317]
For CI triggers, if using path include, is exclude required too? From docs alone, I am not sure if only include alone can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@jason-ortiz It is not required, if you have exclude you must also have include with a greater scope than the exclude, or else it will never trigger. I'll take a look and see if I can add a clarification.
