### ISSUE TITLE
bitbucket.org

### ISSUE THREAD

**Issue by SegaGay** [MicrosoftDocs/azure-devops-docs#8319]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@SegaGay Please comment below if you have any questions or concerns with the documentation.

**Comment by SegaGay** [comment]
keybase://public/segagay/F68A3903-005A-4C40-8CF1-8D4BE52AFAC7-2463-0000015B1CBFC95B.txt
