### ISSUE TITLE
Clarity on when to create 'user' specific branches.

### ISSUE THREAD

**Issue by spmanjunath** [MicrosoftDocs/azure-devops-docs#8325]
It would be interesting to know in which context the 'user' specific branches are used.
From my own understanding this would come into play when a large 'feature' branch is being collaboratively developed by multiple developers, and the individual developers would branch from this 'feature' branch, they would frequently Push changes to their own branches, and use Pull request to merge with 'feature' branch.

Is there a different reason for having 'feature' branch? How is it used withing Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by steved0x** [comment]
#reassign steved0x

**Comment by steved0x** [comment]
> It would be interesting to know in which context the 'user' specific branches are used.
> From my own understanding this would come into play when a large 'feature' branch is being collaboratively developed by multiple developers, and the individual developers would branch from this 'feature' branch, they would frequently Push changes to their own branches, and use Pull request to merge with 'feature' branch.
> 
> Is there a different reason for having 'feature' branch? How is it used withing Microsoft?
> 

It is your preference how to use the different branching strategies. For our Azure DevOps documentation, we use `users/alias/description` as a branch naming guide, and we merge these into our default branch, and then we publish that branch to the `live` branch which triggers off publishing. But if there is a something coming up like the Build conference or Ignite and we are going to synchronize the release of documentation on those dates, we might use a feature branch, and everyone makes PRs from their user branches into that feature branch.

Here is an article covering how the Azure DevOps team uses Git: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft
