### ISSUE TITLE
Optional parameters are no longer correct

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/azure-devops-docs#8326]
In version 1 of the task, the MachineNames and adminUser parameters were optional. Apparently, they have become required in v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0ef2cf-ed52-6ded-bf14-4820d73b4ed0
* Version Independent ID: 7781e0f0-43aa-9008-abda-c03a37e2d7b4
* Content: [Windows Machine File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/windows-machine-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/windows-machine-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@PaulVrugt Thank you for the feedback.

Please double-check as the [repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/WindowsMachineFileCopyV2/task.json) appears to have them listed as not required.

If so, then this would be an issue for the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.  Please move the issue there and link back to this one.

**Comment by PaulVrugt** [comment]
@msebolt see https://developercommunity.visualstudio.com/content/problem/153260/windows-machine-file-copy-task-in-version-20-doesn.html

This was closed as not a bug, stating the parameters are required

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/windows-machine-file-copy-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
