### ISSUE TITLE
Organization name constraints

### ISSUE THREAD

**Issue by GenesisCoast** [MicrosoftDocs/azure-devops-docs#8328]
There's no mention on this page about organizational naming restrictions. E.g. name must only be lower and uppercase letters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b9dd76-4131-bf69-f9bc-c7f7ef562609
* Version Independent ID: 8d3bfbae-3398-c0a2-ca4d-c4782a3b4370
* Content: [Create a new organization, project collection - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/accounts/create-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/create-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by GenesisCoast** [comment]
I've just found out the naming constraints are `The given organization name is not valid. Organization names must start with a letter or number, followed by letters, numbers or hyphens, and must end with a letter or number.`

**Comment by msebolt** [comment]
@GenesisCoast Thank you for the feedback.

The documentation has been updated and is pending review, changes have been moved to the private repo.

Please consider [becoming a contributor](https://docs.microsoft.com/contribute).
