### ISSUE TITLE
Initial AD Step seems to be missing

### ISSUE THREAD

**Issue by TheBritz** [MicrosoftDocs/azure-devops-docs#8332]
This article seems to be missing a step. We have an Azure DevOps instance on a host that was joined to a domain after it was installed and we are unable to access and add users from AD through the Azure DevOps web client until those users are added via the Azure DevOps Server Management Console. 

Additionally, the Management Console appears to identify our security groups incorrectly as users meaning that we can only add individual users (less-than-optimal). I would also like to identify a way to do this Management Console action through Powershell or some other kind of scripting method. Does that capability exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f06e24b-9d7d-b79c-f75f-44032c529027
* Version Independent ID: d0707a11-f483-f192-14c6-cbbfbe5b8071
* Content: [Add AD/Azure AD groups to security groups - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-ad-aad-built-in-security-groups?view=azure-devops-2019&tabs=preview-page#feedback)
* Content Source: [docs/organizations/security/add-ad-aad-built-in-security-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/add-ad-aad-built-in-security-groups.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
Tracking this with [Bug 1739601: Initial AD Step seems to be missing](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1739601/) #8332.

**Comment by KathrynEE** [comment]
@TheBritz - Are you still having issues? I checked with the product team and they didn't have any additional information to provide. Please reopen this issue if you can provide more clarifying information as to what problem you are having. Or, go to our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html) to post a problem.
