### ISSUE TITLE
Difference between AZP and VSTS?

### ISSUE THREAD

**Issue by azilber** [MicrosoftDocs/azure-devops-docs#8336]
I noticed some Micrososft agents require VSTS credentials, while others AZP.   Is VSTS depracted?  Which one should be used?  For example, when we pull an image from mcr.microsoft.com/azure-pipelines/vsts-agent it uses VSTS.  But when we build our own they require AZP info.   What is the difference??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@azilber Thank you for the feedback.

Please refer to issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/8104 for further updates.

**Comment by steved0x** [comment]
@azilber Are you talking about this section of the article: [Authentication type](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops-2019#authentication-type)

You have several different choices - when using Azure DevOps Services, you use a PAT - when you are using Azure DevOps Server or TFS, you have a choice, which depends on the TFS version and how you have configured the authentication for that server.

Am I misunderstanding? Please provide more info if I have, and I'll try to answer. Thank you.

**Comment by steved0x** [comment]
I got some more context on this, vso, vsts, and azp, these are just the naming conventions for various artifacts and variables in the product, depending on the product name at the time that the item was added to the product (Visual Studio Online->VSO, Visual Studio Team Services->VSTS, Azure DevOps ->AZP). Also (as you see on some of the pages like variables) some of the old names map to the same variable as the new names (for backwards compat). Except in certain cases which would be called out (and I can't think of any offhand) if an older item was deprecated, it would be called out in the docs. Does this info help? Please reactivate this issue if you have more questions or a specific example you want us to look at. And thank you for your feedback.
