### ISSUE TITLE
PAT Tokens Traceability

### ISSUE THREAD

**Issue by ahmadabdalla** [MicrosoftDocs/azure-devops-docs#8337]
Where are PAT tokens audited so that if someone clones a repo using a PAT token, the action can be traced back like how it is with CAP policies for interactive logins? I cannot seem to find that information in the documents. This doco https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-conditional-access?view=azure-devops&viewFallbackFrom=vsts&tabs=preview-page has a section about PAT tokens:

"Azure DevOps enforces the usage of personal access tokens (PATs), OAuth, and SSH keys, and user policies. You can restrict Azure AD users from creating new organizations, and for Web flows, CAP is honored 100%. For third-party client flow, like using a **PAT with git.exe**, we support IP fencing policies - we don't support MFA policies. "

The examples in that are for UI based, which are honoured by CAP and Alternate Auth, which is no longer supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ahmadabdalla, I'm looking into this and will be in touch soon. Thanks for reaching out.

**Comment by chcomley** [comment]
@ahmadabdalla - Good news! Auditing for PATs is not released yet, but it's coming soon! Please @mention me if you have any further questions, thank you!
