### ISSUE TITLE
Error setting certificate verify location

### ISSUE THREAD

**Issue by R-Dboy** [MicrosoftDocs/azure-devops-docs#8338]
Hi,
Just finished setting up a build agent following the instructions on docs
 and when I tried running a job, got the error below. What exactly am I missing?

![Screen Shot 2020-05-15 at 12 00 53 pm](https://user-images.githubusercontent.com/31890121/82011553-ac794900-96b8-11ea-9a9e-00b1b24fc7d1.png)

**Comment by msebolt** [comment]
@R-Dboy Thank you for the question.  

Please see if [this post](https://stackoverflow.com/questions/51547858/vsts-git-fetch-failed-with-exit-code-128) helps resolve the issue.

Unfortunately we are unable to provide support in the documentation forum, for additional support options you'll need to refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
