### ISSUE TITLE
"SSH Public Key" is required, not optional

### ISSUE THREAD

**Issue by RiederAlex** [MicrosoftDocs/azure-devops-docs#8339]
'sshPublicKey' is a required input, as leaving it out gives the following error message:
"##[error]Error: Input required: sshPublicKey"

The documentation states that it is optional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@MilchDev Thank you for the feedback.

The parameter is still marked as **not required** in the [reference documentation](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/InstallSSHKeyV0/task.json).

Please consider moving the issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues) while this task is being reviewed.
