### ISSUE TITLE
maybe wrong screen shot

### ISSUE THREAD

**Issue by MarkAtAgilliance** [MicrosoftDocs/azure-devops-docs#8340]
in section *Add an area path*, an iteration panel is instead displayed.  https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=preview-page#add-an-area-path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41d9341-94a7-4df3-ea46-d76c5c39c14d
* Version Independent ID: 777f7374-ce28-d9d7-9d64-ba44603693c7
* Content: [Define area paths for a project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-area-paths?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/settings/set-area-paths.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-area-paths.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MarkAtAgilliance  - Thank you for the feedback and correction. I'll update the article today.
