### ISSUE TITLE
No such file or directory on raspberry pi

### ISSUE THREAD

**Issue by Bengkel** [MicrosoftDocs/azure-devops-docs#8344]
I changed the OS to: "arm32v7/ubuntu:16.04" and changed start.sh line 55 to "?platform=linux-arm"

When I run the container on a raspberry pi, I get the following error:
standard_init_linux.go:211: exec user process caused "no such file or directory"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Bengkel Thank you for the question.

There seems to be multiple solutions relating to the line style of the script, see [this post](https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory) or [this post](https://stackoverflow.com/questions/57366007/standard-init-linux-go211-exec-user-process-caused-no-such-file-or-directory).

Unfortunately the support options in this forum are limited to the documented examples only, please refer to the following options for additional help:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
