### ISSUE TITLE
Are settings added here incremental or will any settings omitted be removed?

### ISSUE THREAD

**Issue by APIWT** [MicrosoftDocs/azure-devops-docs#8346]
If I used this task to configure a couple settings at a slot level, will any settings that I omit be removed from the App Service or will they be retained? I hope the latter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a09e1d-5fe6-cac3-47c9-cb2f4422a473
* Version Independent ID: 4cf6d896-5421-d32f-5fca-90134ddcdfa1
* Content: [Azure App Service Settings task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-settings.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by msebolt** [comment]
@APIWT Thank you for the question, assigning this to the author for review.

Please note if settings are removed, we recommend using **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback from the product team.

**Comment by APIWT** [comment]
@msebolt So the good news is that they are incremental from my testing, but I would still suggest adding that information to this documentation to save someone some time in the future.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
