### ISSUE TITLE
Connect to Azure Devops Server

### ISSUE THREAD

**Issue by scs-tec** [MicrosoftDocs/azure-devops-docs#8347]
Dear all, 

just a question about the plugin: is it designed to work only on the could based version of azure devops or is it possible to connect azure devops server too?

Kind regards

**Comment by msebolt** [comment]
@scs-tec  Thank you for the question.

Please refer to tutorials on [how to install extensions for Azure DevOps Services](https://docs.microsoft.com/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser) versus [how to install extensions for Azure DevOps Server](https://docs.microsoft.com/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019).

If you have any further question please add them to the comments below.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
