### ISSUE TITLE
Facing issue in windows docker agent start.ps1 file.

### ISSUE THREAD

**Issue by ashutoshbarve** [MicrosoftDocs/azure-devops-docs#8349]
1. Determining matching Azure Pipelines agent...
Invoke-RestMethod : An error occurred while sending the request.
At C:\azp\start.ps1:32 char:12
+ $package = Invoke-RestMethod -Headers @{Authorization=("Basic $base64 ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...1.14393.100
   0
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeRestMethodCommand

Cannot index into a null array.
At C:\azp\start.ps1:33 char:1
+ $packageUrl = $package[0].Value.downloadUrl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

2. Downloading and installing Azure Pipelines agent...
New-Object : Cannot find type [System.Net.WebClient]: verify that the assembly
containing this type is loaded.
At C:\azp\start.ps1:39 char:7
+ $wc = New-Object System.Net.WebClient
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb
   jectCommand

You cannot call a method on a null-valued expression.
At C:\azp\start.ps1:40 char:34
+ $wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")
+                                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Expand-Archive : The path 'agent.zip' either does not exist or is not a valid
file system path.
At C:\azp\start.ps1:42 char:1
+ Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (agent.zip:String) [Expand-Arch
   ive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

3. Configuring Azure Pipelines agent...
Cleanup. Removing Azure Pipelines agent...
.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:68 char:3
+   .\config.cmd remove --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:48 char:3
+   .\config.cmd --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by atedsimple** [comment]
You need to enable TLS 1.2 by adding the following line to the top of your Start.ps1 script
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

**Comment by ashutoshbarve** [comment]
@atedsimple I have enabled TLS 1.2 as u have asked, now it is throwing different error. 
1. Determining matching Azure Pipelines agent...
https://vstsagentpackage.azureedge.net/agent/2.168.2/vsts-agent-win-x64-2.168.2.zip
2. Downloading and installing Azure Pipelines agent...
New-Object : Cannot find type [System.Net.WebClient]: verify that the assembly
containing this type is loaded.
At C:\azp\start.ps1:39 char:7
+ $wc = New-Object System.Net.WebClient
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb
   jectCommand

You cannot call a method on a null-valued expression.
At C:\azp\start.ps1:40 char:34
+ $wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")
+                                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Expand-Archive : The path 'agent.zip' either does not exist or is not a valid
file system path.
At C:\azp\start.ps1:42 char:1
+ Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (agent.zip:String) [Expand-Arch
   ive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

3. Configuring Azure Pipelines agent...
Cleanup. Removing Azure Pipelines agent...
.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:68 char:3
+   .\config.cmd remove --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

.\config.cmd : The term '.\config.cmd' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:48 char:3
+   .\config.cmd --unattended `
+   ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by atedsimple** [comment]
Seems like you don't have the correct versions of Framework in your base docker image
Have a look at what we use to build the Docker Image for both 2016 and 2019 server
https://docs.modalitysoftware.com/vsts-agent/customise.html

**Comment by ashutoshbarve** [comment]
@atedsimple thanks.

**Comment by msebolt** [comment]
@ashutoshbarve Thank you for the question.

@atedsimple Thank you for providing a solution, consider [becoming a contributor](https://docs.microsoft.com/contribute).

For further issues, please provide a reference to the specific documentation example and we will assign an author for review.

To receive general support, refer to the [Azure DevOps support](https://azure.microsoft.com/support/devops/) page.

**Comment by msebolt** [comment]
Closing this issue now.

**Comment by masoodamunchen** [comment]
Hi, I am having the same issue in 2021, as mentioned by @ashutoshbarve ashutoshbarve , tried the soluition by @atedsimple but it didn"t work. What was the final solution to solve the Invoke WebRequest problem?

**Comment by atedsimple** [comment]
@masoodamunchen with all due respect we have been using this daily in a production environment and it does work. What are you doing that is different? Maybe you are running this from behind an internet proxy? Also we are now only using Server 2019 hosts as they seem much better than 2016
