### ISSUE TITLE
Defining minor version

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/azure-devops-docs#8351]
Article discusses pinning the major version as mandatory, but no info is given on pinning the minor version.

As someone who just ran into this.... how do you pin a minor version?  task@1.2 will just spit out an error task reference must be in the format &lt;NAME&gt;@&lt;VERSION&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@Justin-DynamicD Could you give an example of the task that has a minor version? Looking at the [tasks repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks), I'm not seeing any. Thanks for your help!

**Comment by Justin-DynamicD** [comment]
That's the fun part, isn't it :)

Try **InstallSSHKey@0**  Obviously the major version is "0", but when you look at the logs output from the pipeline, it actually reports back running version *0.169.1*.  If I go back 2 weeks and look at older jobs, it had version *0.156.0*.  So there are minor release changes occurring in the modules that can be seen from the output of the executing pipeline.

![image](https://user-images.githubusercontent.com/8795183/82258712-315da000-990f-11ea-81da-24243f116056.png)

vs.

![image](https://user-images.githubusercontent.com/8795183/82258759-476b6080-990f-11ea-88b6-2ae54225d88e.png)

**Comment by juliakm** [comment]
@Justin-DynamicD I'll update the docs. The task name would change to something like `GoTool@0.3.1`. The warning is that you can only use the minor versions for tasks in your organization. Tasks start saving from the moment your organization is created. So, you should be able to access any task version that you have used previously in your organization.
