### ISSUE TITLE
Add physical machines to environment?

### ISSUE THREAD

**Issue by ipavlovi** [MicrosoftDocs/azure-devops-docs#8357]
Is it possible to define environment as set of physical machines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ipavlovi Thank you for the question, assigning this to the author for review.

If this feature is unsupported, we recommend soliciting feedback from the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
