### ISSUE TITLE
Typo: Ubuntu 18.06 is set here in the YAML file

### ISSUE THREAD

**Issue by mic-max** [MicrosoftDocs/azure-devops-docs#8359]
Should be Ubuntu 18.04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@mic-max  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
