### ISSUE TITLE
_apis/Settings/Entries/globalme "401 unauthorized"

### ISSUE THREAD

**Issue by VAllens** [MicrosoftDocs/azure-devops-docs#8361]
Scope required: "vso.settings".

Scope description of "vso.settings" and "vso.settings_write" is missing from this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @VAllens, Thanks for this. I have the update in a PR to be published sometime today. Thanks again!
