### ISSUE TITLE
Pass variables between stages

### ISSUE THREAD

**Issue by albertodall** [MicrosoftDocs/azure-devops-docs#8363]
Please, add docs on how to pass and refer variables between stages in a Multi-Stage Pipeline.
stageDependencies.&lt;stageName&gt;.&lt;jobName&gt;.outputs['&lt;taskName&gt;.&lt;variableName&gt;']
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@albertodall I think you may have created this issue before the expressions docs were updated. You can learn more about stageDependencies [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies).
