### ISSUE TITLE
Out of Date Information

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/azure-devops-docs#8364]
The conflict resolution process displayed on this page does not match Visual Studio 2019 16.5.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e2ddbb-512d-fe28-55c2-bfc4ff8aad73
* Version Independent ID: 9b7770d7-7f5d-3cb7-c619-a5cd23b5da09
* Content: [Resolve Git merge conflicts - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging?view=azure-devops&tabs=visual-studio#feedback)
* Content Source: [docs/repos/git/merging.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/merging.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by mcurko** [comment]
With VS 16.9.4 I can't find any way to resolve merge conflicts... (either with old or new git modules) Please update the documentation!

**Comment by steved0x** [comment]
This article has been updated with the steps for VS 2022 down through 2019, and Git command line.
