### ISSUE TITLE
Missing link to ADD docs.

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/azure-devops-docs#8365]
I found possible miss configured link in the section ["Q: Why can't I find members from my connected Azure AD, even though I'm the Azure AD global admin?"](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management?view=azure-devops#q-why-cant-i-find-members-from-my-connected-azure-ad-even-though-im-the-azure-ad-global-admin).

In the bullet bellow, I think "Can Azure AD B2B users be added as members instead of guests?" should be linked to the document in AAD documentation.

* Have the Azure AD admin remove you from the connected Azure AD and readd you. The admin needs to make you an Azure AD member rather than a guest. See **Can Azure AD B2B users be added as members instead of guests?**

So the fix would be something like:
* Have the Azure AD admin remove you from the connected Azure AD and readd you. The admin needs to make you an Azure AD member rather than a guest. See [**Can Azure AD B2B users be added as members instead of guests?**](https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties#can-azure-ad-b2b-users-be-added-as-members-instead-of-guests)

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a09840-ed5d-8a72-cb80-20bac219e065
* Version Independent ID: 8a686d5e-af9f-e269-2603-f122ab964d86
* Content: [Troubleshoot user and permissions management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management?view=azure-devops#q-why-cant-i-find-members-from-my-connected-azure-ad-even-though-im-the-azure-ad-global-admin)
* Content Source: [docs/organizations/accounts/faq-user-and-permissions-management.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/faq-user-and-permissions-management.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@mszixie Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by shunkino** [comment]
@msebolt 
Hi, thank your for taking initiative and fix the doc.
Thank you for your suggestion, I would love to become one. Next time I found something to add, I will write PR too.
