### ISSUE TITLE
Using same server for azure pipelines and azure devops install?

### ISSUE THREAD

**Issue by MikaelUmaN** [MicrosoftDocs/azure-devops-docs#8367]
Hi.

I have an azure pipelines setup that works well with a self-hosted Linux agent.

On the other hand, I would like to also use this same server for an azure devops server.

Is this possible? If so how ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@MikaelUmaN Thank you for the question.

The Azure DevOps server would require a Windows-based environment.  

From the there you would use the [Windows Subsystem for Linux](https://docs.microsoft.com/windows/wsl/install-win10) to install any sub-environment of your choosing that currently supports .NET core 2.1.  

For a list of Linux-agent supported environments see [here](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites).

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
