### ISSUE TITLE
Include information about publishing .pdb/symbol files. 

### ISSUE THREAD

**Issue by VladDerptastic** [MicrosoftDocs/azure-devops-docs#8369]
Azure Artefacts supports a symbol server that can be published to using Azure Pipelines ([as written in the documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops)).

There are **no** details on how to publish symbols from the CLI, nor even mention if its possible at all or why not. 

I believe it would be pretty helpful for this article to contain information on the topic, especially since [SourceLink ](https://github.com/dotnet/sourcelink) is now an official tool in the .NET ecosystem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec99483d-828e-093b-a5af-bd2d25ea27d1
* Version Independent ID: 36f67ced-654b-3cbb-2f4e-4f7b540959ba
* Content: [Publish a NuGet package from the command line - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by herenhuang** [comment]
This is going to need Core's help in getting done. Going to have to file a feature request here within our group to have more information on symbols overall: How to publish symbols from Azure CLI. Will update here with my findings!

**Comment by ramiMSFT** [comment]
@VladDerptastic Thank you for your feedback. We have a section on working with symbols in our Azure Artifacts docs. See [Artifacts landing page](https://docs.microsoft.com/en-us/azure/devops/artifacts/?view=azure-devops) for details.
You can [publish your symbols](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops) to a file share or in the build pipeline that produces the NuGet packages. However, publishing symbols from the CLI is not currently supported. The updated version of the article will go live shortly.
