### ISSUE TITLE
Set different values for secret variable depending on stage

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8370]
Hi there. In classic mode we were able to set secret variable's value for different stages. For example MyServicePass for dev equals "ABC" but for production equals "QWE". For different stage there was a single variable with different values. Now in yaml we can't do this, right? All what we have is 'Variables' tab in UI without any mention of stage.
And please... don't send me back to the same documentation page like you usually do, okey? In that case I will curse you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@VerdonTrigance Thank you for the question.

The intended use is secrets within [variable groups](https://docs.microsoft.com/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) for access across pipelines, though updating variable groups still requires REST, see https://github.com/MicrosoftDocs/azure-devops-docs/issues/5652 for the latest status.

For multi-stage variables within the same template you will need to adjust them manually, the idea of enums has been proposed see [here](https://developercommunity.visualstudio.com/idea/366261/change-build-and-release-variables-to-allow-for-en.html).

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance Thank you for the question.
> 
> The intended use is secrets within [variable groups](https://docs.microsoft.com/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml) for access across pipelines, though updating variable groups still requires REST, see #5652 for the latest status.
> 
> For multi-stage variables within the same template you will need to adjust them manually, the idea of enums has been proposed see [here](https://developercommunity.visualstudio.com/idea/366261/change-build-and-release-variables-to-allow-for-en.html).

Variables or variable groups - they are all named different, right? As so when I start my extreme long build with multiple stages and environments I wouldn't be able to use MySecretPass variable in my template (as I repeat these steps from stage to stage) because it stores only single value (for example only for dev environment/stage)? Looks not good. Is anyone faced with the same problem?

**Comment by msebolt** [comment]
Closing this issue now, for suggested changes to the documentation please comment below.

Otherwise, for additional support options, please refer:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
