### ISSUE TITLE
Will support be added for multiple cache paths?

### ISSUE THREAD

**Issue by covertbert** [MicrosoftDocs/azure-devops-docs#8372]
This is a feature common with most CI pipeline providers and is very useful for monorepos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@covertbert  This feature is not currently on the [roadmap](https://docs.microsoft.com/azure/devops/release-notes/features-timeline).

To solicit feedback from the product team, please move this issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

For suggestions or updates to the documentation, please add comments below.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
