### ISSUE TITLE
image out of date

### ISSUE THREAD

**Issue by jayy-mize** [MicrosoftDocs/azure-devops-docs#8373]
the image in "Continuous integration and deployment" is outdated and does not reflect the changes to Pipelines. Pipelines no longer have a Builds tab, just Pipelines now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc7a1aaa-9aee-2b23-d77f-634a42c94280
* Version Independent ID: 293f604b-9b00-7758-7645-67a7e296d585
* Content: [Features and services included - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/services?view=azure-devops#continuous-integration-and-deployment)
* Content Source: [docs/user-guide/services.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/services.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jayy-mize, Thanks so much for letting us know. I've created a user story to address this, which should be complete sometime today, 05/19. Thanks again and have a great day!
