### ISSUE TITLE
Wiki PR Improvements/Suggestion

### ISSUE THREAD

**Issue by patrick-truskowski-perficient** [MicrosoftDocs/azure-devops-docs#8374]
Hello, 

We are currently using Azure DevOps Wikis to drive collaboration in our company. We like the openness and ease-of-use that Wikis provide, especially with the Git backing. 

We also want to encourage scripting against the repo which could potentially update specific articles with metrics on the wiki. However, this opens the door for some "destruction" on the page. We'd like to utilize the Branch Policies, but only for commits done outside of the direct Wiki page. 

I'd like to see a feature added to the Branch Policies specific to Wiki pages (project Wikis or code Wikis). Here is how I envision the feature:

1. Changes made directly in the Wiki UI allow direct commit/push to master
    * Includes *.md files and .attachments
2. Changes made outside of the Wiki UI must follow branch policies
    * Includes changes to *.md files or .attachments
    * Includes any other changes against the repository

This will give teams the confidence that mass changes and scripting against the repository are largely safe behind a branch policy but also allows the flexibility of Wiki pages changes directly on the Wiki section. 

_Amendments Below_
[Frontend vs Backend control](https://github.com/MicrosoftDocs/azure-devops-docs/issues/8374#issuecomment-631533766)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cda88f5-9302-af6e-273e-a81e6bef119f
* Version Independent ID: 4a0c729a-60ac-7f9f-829b-30008c93676a
* Content: [Default Wiki and social tool permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-readme-permissions?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-readme-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-readme-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@patrick-truskowski-perficient Thank you for the feedback and suggestions.

This will require feedback from the product team, please visit the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for further discussion with a link back to this issue.

There you can view similar suggestions such as [this post](https://developercommunity.visualstudio.com/idea/365699/wiki-per-pagearticle-permissions.html) under discussion.

For additional documentation concerns, please comment below.

**Comment by patrick-truskowski-perficient** [comment]
Thank you @msebolt! I'll keep an eye on both these. 

I think my suggestion and your [provided suggestion](https://developercommunity.visualstudio.com/idea/365699/wiki-per-pagearticle-permissions.html) fall under a similar category related to permissions and access to Wiki pages. I know our Wiki could benefit from per page permissions also. 

### Terms I'll be using
PPP = Per page permissions (your ref)
PRI = PR Improvements (this suggestion)

### Follow-up
I do want to call out some differences between the PRI and the PPP suggestions. 

The **_PPP suggestion_** focuses more on protecting the "frontend" access to the Wiki pages. In my opinion, the biggest benefit of this suggestion is preventing some users from directly modifying Wiki pages. You may consider a couple of options (1) blocking access to Wiki pages for common users or (2) allowing common users to submit PRs after editing a Page (change "Save" to "Submit PR"). The second option still safe-guards the page but still allows contribution for all users.  

The **_PRI suggestion_** focuses more on protecting the "backend" access to the Wiki pages, and I think it could work in conjunction with the PPP. The PRI looks for ways to lock down commits directly from the backing Git repo.

#### Proposed Frontend access (PRI + PPP)
1. User opens a page in Azure DevOps - Wiki 
1. Azure DevOps checks to see if the page is protected by PPP
   * If "Allow all edits", user can edit the page and save changes directly
   * If "Allow PRs", user can edit the page directly but the save option becomes a "Submit PR"

#### Proposed Backend access (PRI + PPP)
1. Admin adds branch policy to master branch with added Wiki flag
     * "Allow branch policy bypass from direct Wiki edits"
     * This flag would be in addition to other branch policies
     * Azure DevOps would detect a commit is coming directly from a Wiki page and not enforce branch policy rules
     * Any other commits/pushes to master would need to follow branch policy rules
1. User 1 opens a Wiki page in Azure DevOps
1. Azure DevOps would do the Frontend checks as defined above
1. User 2 clones the Code wiki to their local machine
1. User 2 creates a script to analyze Wiki statistics (page views using API)
1. User 2 commits and pushes but is blocked by branch policies

### Summary
Currently, I'm more interested in the backend access due to some scripting ideas we had for our wiki. We are storing most of our content in Code Wikis, not the Project Wiki. This is in part because we don't have Build Pipeline access to Project Wiki but also because we want to separate our Wikis logically (technical, soft-skills, other categories).

Here are some of the scripting ideas we want to include:
1. Sort pages per business rules (alphabetically at first, will adapt to be smarter)
1. Adding the original author directly to the Wiki page (potentially another suggestion for Wikis)
1. Adding popular page views in the last week using the Wiki API
1. Adding a recently added pages article
1. Adding a recent contributors article
1. Script to analyze links and check if they are broken
1. Script to move images to an external source and update the wiki page with the new location (this will be helpful to manage disk usage in the Wiki but allow easy copy/paste for the basic user) 

Our goal is to write reviewable scripts (via PRs) that will access necessary data about the Wiki and having an automated commit back to the repo in the form of an article. This enhances the user experience common users and super users without requiring MS to add these features. Some of them may only be specific to our company so they may not make sense as fully-fledged features. 

If we find they would work out for other companies, I plan to submit additional suggestions for some of these automated ideas to be added as features.

**Comment by msebolt** [comment]
@patrick-truskowski-perficient  Thank you for providing these additional details on specific items the product team can address.  Including more details makes it easier when they assess whether the suggestion is feasible or not.

As an added precaution, please consider the use of [Developing extensions](https://docs.microsoft.com/azure/devops/extend/overview?view=azure-devops) to meet these needs.  Their specific intent is to allow further customization to support such needs, see [here](https://marketplace.visualstudio.com/search?term=wiki&target=AzureDevOps&category=All%20categories&sortBy=Relevance) for a few examples of wiki enhancements.

On a side note, we also need a confirmed objective to make documentation changes. Please add these comments and/or a link to this issue to the [referenced post](https://developercommunity.visualstudio.com/idea/365699/wiki-per-pagearticle-permissions.html), or start a new one within the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to keep this issue open.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
