### ISSUE TITLE
What happens when name of backlog level changes? 

### ISSUE THREAD

**Issue by tranimal** [MicrosoftDocs/azure-devops-docs#8376]
If someone changed the name of the backlog level in the Process, what does that do to the data?  Can it be changed back to the "default" name and still work?  I am not having luck on ways to pull data if the backlog level names have been changed.  For example:  Epics backlog is changed to Product backlog and then changed back to Epic backlog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 574443d9-7dc6-8fba-f549-2781def08395
* Version Independent ID: bfa2a8a3-f07a-0859-4282-0becc46e692f
* Content: [Create an Analytics view - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-views-create?view=azure-devops)
* Content Source: [docs/report/powerbi/analytics-views-create.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/analytics-views-create.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
@tranimal just to be clear so we understand. You went into the process configuration and changed the backlog level from one thing to another? And are you then having trouble getting data out of the power bi views?

**Comment by tranimal** [comment]
> @tranimal just to be clear so we understand. You went into the process configuration and changed the backlog level from one thing to another? And are you then having trouble getting data out of the power bi views?

@danhellem that is correct.  After the change of the name, I was unable to retrieve any data out of the power bi views.  I was only able to get data after following [steps ](https://stackoverflow.com/questions/61900545/powerbi-and-azure-devops-online-version-reporting-when-backlog-level-name-chan?noredirect=1#comment109533337_61900545)

**Comment by danhellem** [comment]
@KathrynEE I think the analytics team will know more here. If this is true, it feels like a bug. But it may take a little while (less than a few hours) for the changes in the process changes to make it's way into analytics.

**Comment by KathrynEE** [comment]
Closing as addressed.

**Comment by ksmis-gh** [comment]
Dan is right on this, it shouldn't take more than a few hours for those properties to reach analytics and get transformed.
