### ISSUE TITLE
Both "DownloadBuildArtifacts" and "DownloadPipelineArtifacts" tasks can be used in YAML pipelines now

### ISSUE THREAD

**Issue by mszixie** [MicrosoftDocs/azure-devops-docs#8381]
The doc says "At present, you cannot download artifact produced by a YAML pipeline in another YAML pipeline." however currently both "DownloadBuildArtifacts" and "DownloadPipelineArtifacts" tasks can be used in YAML pipelines to download the build artifacts from other YAML/classic pipelines. Can the document be updated accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#consume-artifacts-in-release-pipelines)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@mszixie Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
