### ISSUE TITLE
How to modify the retention period of Recycle for deleted workitems

### ISSUE THREAD

**Issue by manvendrautralia** [MicrosoftDocs/azure-devops-docs#8384]
In the Azure devops:- What is the default retention period of deleted work items in Recycle bin? Can we change this limit.

**Comment by msebolt** [comment]
@manvendrautralia Thank you for the question.

With no explicit statements made, it would be assumed that items are kept indefinitely until explicitly deleted, see [Remove delete work items](https://docs.microsoft.com/azure/devops/boards/backlogs/remove-delete-work-items).

I'll assign the author for further confirmation.

For new feature requests, please see [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

**Comment by manvendrautralia** [comment]
> @manvendrautralia Thank you for the question.
> 
> With no explicit statements made, it would be assumed that items are kept indefinitely until explicitly deleted, see [Remove delete work items](https://docs.microsoft.com/azure/devops/boards/backlogs/remove-delete-work-items).
> 
> I'll assign the author for further confirmation.
> 
> For new feature requests, please see [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

@msebolt Thanks for your inputs. Please help to get it verified, as we will have to plan our production workloads accordingly.

**Comment by KathrynEE** [comment]
@manvendrautralia: The items stay in the Recycle bin until someone permanently deletes them. So there is no explicit limit on the Retention Period and no way to change the limit. I'll update the article accordingly.
