### ISSUE TITLE
failure when secret expires

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/azure-devops-docs#8386]
When MS DevOps creates a service connector the secret in Azure is set to expire in 2yrs and you can't change it. In 2yrs when the secret expires the service connectors fails. How can you reset or set certificate to never expire as our engineers had to delete and create new service connectors then edit all release definitions to get DevOps-Azure (Pipelines) working again.

**Comment by msebolt** [comment]
@kcnighsurf Thank you for the feedback, we apologize for the issues you're having.

If you can provide a reference to a document in particular, or describe the connector you're using, see [this list](https://docs.microsoft.com/azure/devops/pipelines/library/service-endpoints), we will assign an author to add this to the documentation.

The documentation should also note issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/8387.

**Comment by kcnighsurf** [comment]
@msebolt  Azure Resource Manager service connection.
I can't find Azure doco on how to fix this issue/deal with the expired secret that breaks the Service Connection - (Azure Resource Manager). It should be here https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-azure-resource-manager . I logged a ticket with Microsoft and it's been a week and they are passing it around internally, still don't have an answer. Surely all customers are going to have this issue.

**Comment by msebolt** [comment]
@kcnighsurf Great, assigning this to the author for further review.

**Comment by jrpharis** [comment]
Anything on this? I'm not able to find how to update the secret on a Service Connection in Azure Devops after the original secret on the Service Principal expired.

**Comment by kcnighsurf** [comment]
Just checked my old ticket with MS Support where I told them to update the notes. This is what I wrote in the ticket back to Support.
My fix.
Delete the expired secret in Azure ADD-App registration. In Azure DevOps edit the existing broken Service Connector – Add a comment to the optional notes. Save. Behind the scenes this will create a new secret to last another 2yrs and fix the service connector. 
Recommend google more but hope that helps.

**Comment by jrpharis** [comment]
@kcnighsurf Yep, thanks, I was able to do that. I guess I just wasn't expecting to need to save on that edit section when I hadn't made any changes. I was looking for somewhere to paste in the new token value I had created.
