### ISSUE TITLE
instructions needed for when service connection secret expires

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/azure-devops-docs#8387]
Need to add steps to take when service connection secret in Azure expires. At creation it's set to expire after 2 yrs but should auto update or at lease provide clear instructions to update the connection so it works.

**Comment by msebolt** [comment]
@kcnighsurf Please refer to issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/8386 for including this in the documentation.
