### ISSUE TITLE
update this page to reference Maven Authenticate Task

### ISSUE THREAD

**Issue by HughDevlin** [MicrosoftDocs/azure-devops-docs#8388]
The Maven task doc needs to be updated to reference the Maven Authenticate Task

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by HughDevlin** [comment]
Please can the Maven build and release task documentation be updated to explain the relationship of the Maven build and release task task to the Maven Authenticate Task?

**Comment by herenhuang** [comment]
Just leave a pointer in the Maven build task doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops 

To this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops

Tagged ready-to-doc as part of Docathon.
