### ISSUE TITLE
The global notification subscribers are not being saved. It is not available if refresh the page

### ISSUE THREAD

**Issue by b-chandu** [MicrosoftDocs/azure-devops-docs#8390]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c845a7-d230-c0b0-e68c-174246f866bc
* Version Independent ID: a773099c-3af5-dc66-b303-335ccf9875dc
* Content: [Manage notifications for a team or group - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops)
* Content Source: [docs/notifications/manage-team-group-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-team-group-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@Chandrashekarachar Thank you for the feedback.

We will provide an update to the documentation.

In the meantime, please refer instead to **Admin settings** > **Notifications**:

![Capture](https://user-images.githubusercontent.com/6675884/82526125-037f8380-9ae8-11ea-9727-066bae77b0aa.PNG)
