### ISSUE TITLE
Delete Published Symbols

### ISSUE THREAD

**Issue by iKaew** [MicrosoftDocs/azure-devops-docs#8391]
Do you have any other way to delete the published symbols ?  

It would be good if you can provide information on how to see data stored on symbols server. Even delete almost every builds that published symbols, the Artifacts usage storage seems not reduce. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by herenhuang** [comment]
Hey there, 

Artifact retention is based on the retention of the pipeline run or release. There's guidance on how to delete symbols [here, Build and release retention policies.](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml). @ramiMSFT we should have a link here that points clearly to this. 

We're actively working on some new upcoming features that allow you to view symbols and the pipelines they are built from. I'm more than happy to do a walk-through of this if you are interested to be a pilot user! If you think that there's an actual problem with the deletion workflow, please file an issue within [DevCommunity](https://developercommunity.visualstudio.com/spaces/21/index.html) and we can take a look!

Thanks again!

**Comment by iKaew** [comment]
@herenhuang That's awesome. Let me know how to be your pilot user.

**Comment by ramiMSFT** [comment]
@herenhuang We already have a link that point to that article. See the `Important` note at the bottom of the page.

@iKaew Thank you for your feedback. You can [use the retention policies to clean up your build](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml#use-retention-policies-to-clean-up-your-completed-builds) or [delete the run manually](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml#delete-a-run).
