### ISSUE TITLE
CMMI V2.0

### ISSUE THREAD

**Issue by pedroltch** [MicrosoftDocs/azure-devops-docs#8395]
[Escreva aqui os seus comentários]

We would like to update this page description about CMMI to version V2.0 from CMMI. Could we do that?
pedroch@strongstep.pt

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: c14696f7-62b7-5426-7732-c3744c4edec2
* Version Independent ID: 72d177fb-3938-4946-06a4-269bc80448be
* Content: [Understand the CMMI process template artifacts - Azure Boards](https://docs.microsoft.com/pt-pt/azure/devops/boards/work-items/guidance/cmmi-process?view=tfs-2015)
* Content Source: [docs/boards/work-items/guidance/cmmi-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/cmmi-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@pedroltch Thank you for the feedback, assigning this to the author.

Please note this also applies to [Project management (CMMI)](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/cmmi/guidance-project-management).

**Comment by pedroltch** [comment]
Sorry, how does this work? How can I talk to the author?

**Comment by msebolt** [comment]
@pedroltch Apologies for the confusion.

Please add all details and/or issues you have with the documentation to comments below and an author will address what he/she thinks requires updating.

Please note that given the number of issues in the repo you can expect an average response time of between 10 to 30 days.

If this requires more immediate support, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@pedroltch - I'm closing this issue and opening a work item on my backlog to review and update the CMMI content as time permits. I reached out to you via email and am happy to work with you if you have specific suggestions. Other than that, you can contribute to the content by following the instructions provided here: https://docs.microsoft.com/en-us/contribute/.
