### ISSUE TITLE
Update of CMMI description to the current versions CMMI v2.0

### ISSUE THREAD

**Issue by pedroltch** [MicrosoftDocs/azure-devops-docs#8396]
Dear,

We would like to Update of CMMI description to the current versions CMMI v2.0. Can we do that?
We are a CMMI authorized partner, and will use current published descriptions. 

ok?

Regards,

Pedro Castro Henriques

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 03436429-e681-a098-c77d-2e985d38c838
* Version Independent ID: 91d24420-fa08-bb35-3c87-298a34c8df31
* Content: [CMMI process guidance, Project management - Azure Boards](https://docs.microsoft.com/pt-pt/azure/devops/boards/work-items/guidance/cmmi/guidance-project-management?view=tfs-2015#feedback)
* Content Source: [docs/boards/work-items/guidance/cmmi/guidance-project-management.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/cmmi/guidance-project-management.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@pedroltch Thank you for the feedback.

Please refer to issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/8395 for further updates.
