### ISSUE TITLE
The instructions only work for publishing in the pipeline's project feed

### ISSUE THREAD

**Issue by Gutza** [MicrosoftDocs/azure-devops-docs#8400]
Section "Publish your packages" on this page is the only clear explanation of the publishVstsFeed parameter for NuGetCommand@2 push – all other pages I could find on docs.microsoft.com don't explain the parameter better than its name explains it. This is the only page I could find that actually explains how to format it (the phrase «You must include the project name in the publishVstsFeed parameter: publishVstsFeed: '&lt;projectName&gt;/&lt;feed&gt;'.»)

Having said that, this only works for project feeds, and only if the pipeline resides in the same project as the feed. It does not explain how to publish to an organization feed, and publishing to a different project's feed in the same organization doesn't work using this example – and, as explained in the first paragraph, I could find no other documentation page that even attempts to address the issue, so I'm left in the dark.

Concretely, if I have organization Ao which contains project Ap1, which contains feed Af1, then I can set up a pipeline in Ap1 with publishVstsFeed: 'Ap1/Af1' in order to publish to feed https://pkgs.dev.azure.com/Ao/Ap1/_packaging/Af1/nuget/v3/index.json

However, if I also have project Ap2 under organization Ao, and I want to set up a pipeline in Ap2 to push to feed Af1 then setting publishVstsFeed: 'Ap1/Af1' in project Ap2 fails ("Could not create provenance session: %s; Cannot read property 'sessionId' of null; The nuget command failed with exit code(1) and error(Unable to load the service index for source https://pkgs.dev.azure.com/Ao/Ap1/_packaging/Af1/nuget/v3/index.json.").

It is also never explained how one would have to set up publishVstsFeed and/other parameters in order to publish to organization feeds (https://pkgs.dev.azure.com/Ao/_packaging/AfX/nuget/v3/index.json). You will notice I used "AfX" in order to denote the name of the organization feed, because it's also unclear how one manages organization feeds at all.

The current setup means I have to create a feed for each project – that's like having to set up a different feed for each package in nuget.org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#publish-your-packages)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by Gutza** [comment]
Figured out why I couldn't push to another project in the same organization: https://devops.stackexchange.com/questions/10843/project-pipeline-not-able-to-access-nuget-package-from-artifact-feed-in-differen

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
