### ISSUE TITLE
Instructions for installing agent behind proxy do not work

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/azure-devops-docs#8401]
This page https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?tabs=windows&view=azure-devops#feedback
says to do this to configure agent behind proxy:
`./config.cmd --proxyurl http://127.0.0.1:8888 --proxyusername "myuser" --proxypassword "mypass"`
My proxy doesn't take a username or password.  When I include my proxyurl, I can no longer connect to my Azure DevOps instance.  It says "Bad Request".  It's able to connect if I don't specify any --proxyurl.
How do I configure agent behind proxy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa5d1372-3bf2-5733-25a4-eddbdfb7511c
* Version Independent ID: 2823a0ff-df57-4338-9b60-780beb8c7c74
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?tabs=windows&view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@pabrams  Thank you for the question.

Please make sure no spaces are included around the proxy address, see [this post](https://stackoverflow.com/questions/49177142/trying-to-configure-build-agent-to-work-with-a-proxy-server) for possible resolutions.

For additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
