### ISSUE TITLE
Conflicting info? - Stakeholder access causes the problem so change access to stakeholder?

### ISSUE THREAD

**Issue by kayceejay** [MicrosoftDocs/azure-devops-docs#8403]
??

"This error indicates the user has a stakeholder license which does not grant permissions to writing shared queries"

"Fix: You should change the access level, from basic to stakeholder."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4208398-e77f-5bef-5739-6539c3ba53bb
* Version Independent ID: f09154ed-0d77-6ed6-3dc8-4b91e6563236
* Content: [Use Azure DevOps Demo Generator](https://docs.microsoft.com/en-us/azure/devops/demo-gen/use-demo-generator-v2?view=azure-devops#feedback)
* Content Source: [docs/demo-gen/use-demo-generator-v2.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/demo-gen/use-demo-generator-v2.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @mijacobs
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kayceejay Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
