### ISSUE TITLE
I need to delete an organisation immediately, not after 28 days

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/azure-devops-docs#8407]
[Enter feedback here]
As the title says, I need to delete a newly created orgnisation straight away. There is no data in the account or activity, so there's nothing to lose. The problem really started with the linking of the AZP account with github account. I created a new MS account and wanted to use this new account instead of the previous one that I used.

Really the best way to fix this issue is to delete the entire AZP account and all associations with my github account and the organisation (immedately). This will enable me to use my new MS account as the primary email in github so I can link it to a new AZP acoount set everything up again. I also need to delete the organisation I setup previously immediately, so I can use that same name in my new AZP account. How do I do this? My github account is lnked to a bad AZP account now so I need to break this link.

If its not possible to delete the organisation until 28-dys, then so be it. However, I stilll need to delete that AZP account, because its in an unknown state and linked to my github account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab1d1c9d-6fe1-e95a-fe78-8f194022d9a3
* Version Independent ID: a1c9d23e-0058-cb9d-e275-65c53b8dfe27
* Content: [Restore organization after it's removed, deleted - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/recover-your-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/recover-your-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/recover-your-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@plastikfan  Thank you for the feedback.

Deleting organizations is described in [Delete your organization](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-your-organization), is this information not included there?

If not, please let us know and we can assign an author for further review.

**Comment by plastikfan** [comment]
Well the information is included, but I need to delete an organisation immediately not after 28 days (so that I can re add it to my new AZP account). The organisation I initially created is new and there is no meaningful activity or data associated with it so there should be no issue in immediately deleting it.  The article doesn’t cover this. I was hoping there would be an immediate delete option in this scenario.

**Comment by chcomley** [comment]
@plastikfan, there's no limitation on when you can delete. You can delete an organization whenever you want. If this isn't clear, please @mention me. Thanks!

**Comment by plastikfan** [comment]
Hi @chcomley, thanks for your reply. I’m afraid it’s not clear from the documentation. As I understand it from the documentation, the organisation is deleted after 28 days not immediately as I would want it to be so I can add it to another account. However, I have deleted the organisation but I haven’t added to another account yet because I wanted to wait for advice, since any remediation action I take seems to dig me into a bigger hole!

**Comment by plastikfan** [comment]
Please can you reopen this. It is not resolved

**Comment by chcomley** [comment]
Now I'm following. Thanks @plastikfan. Adding @parsamzand for further clarification.

**Comment by chcomley** [comment]
Hi @plastikfan, Thanks so much for your patience on this. I've discovered that you'll have to wait up to the 28 days, unless you go through Support (who can free up your organization name). Otherwise, you can always re-name the organization before deleting it to free up the desired organization name. 

If you want to contact Support, please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem** > **Azure DevOps**. 

I'm adding an FAQ to this article, describing this scenario, which should be live sometime today. 

Please @mention me if you have any further questions about the article.

**Comment by plastikfan** [comment]
Hi @chcomley, thanks for your help in this regard. I am having a bit of a rough time with azure simply as a result of changing an email address associated with my github account linked to azure, which should be an easy operation but any time I try something, it just seems to make things worse. I have found that the azure organisation name was actually deleted (possibly somebody at azure support did it without notifying me) because I was able to re add it to to my azure account linked to the new Microsoft account I’m migrating to. However my azure account is still not linking up to github properly which means I can’t use azure in earnest  because this issue is still not sorted out.

**Comment by plastikfan** [comment]
I’ve been in touch with github and awaiting their response, but think this is an azure issue, because other 3rd parties authenticating with github works perfectly with my new Microsoft account, but when azure tries to authenticate via github, it still wants to authitecate using my old Microsoft email address which I thought I had removed all references to in azure and github. I don’t know what’s going on here and it’s preventing me from working on azure pipelines. At the moment I’m waiting for azure to do something but they keep fobbing me off, so I’m stuck saying I should take this up with GitHub.

**Comment by chcomley** [comment]
Hi @plastikfan, I just wanted to circle back on this, as I hope GitHub has helped you with this. Since this isn't an issue about the article, I'll be closing this issue However, please @mention me if you have any questions about the article. If you haven't had luck with GitHub, I'd contact Support. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem** > **Azure DevOps**.
