### ISSUE TITLE
Testing using Postman

### ISSUE THREAD

**Issue by dwjobling** [MicrosoftDocs/azure-devops-docs#8408]
For those looking to test this out I've found Postman doesn't work.  Had to use the Advanced Rest Client instead.  May be something to do with the http version used by default in Postman (2).  The url within the batch is also a little picky, I had an errant / which would work fine normally but caused a 404 to return from the batch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b558bc63-f66f-4e80-5d8e-091eb15d5deb
* Version Independent ID: e0afae7e-316a-9eb9-ea04-94e8d0a4f3fa
* Content: [OData batch support - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/odata-batch?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/odata-batch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/odata-batch.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by pradeepna** [comment]
@dwjobling - I was able to create an OData query using Postman and get valid results. Below is the exact query I ran (you need to replace PAT)

### Request
POST https://analytics.dev.azure.com/mseng/AzureDevOps/_odata/v3.0/$batch

### Header
Content-Type:multipart/mixed; boundary=batch_abc
Content-Transfer-Encoding:binary
Authorization:Basic <base64_encoded_pat>

### Body
--batch_abc
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://analytics.dev.azure.com/mseng/AzureDevOps/_odata/v3.0/WorkItemRevisions?$filter=(WorkItemId%20eq%201696440)&$select=Revision,State HTTP/1.1
Accept: application/json

--batch_abc

Regards,
Pradeep

**Comment by dwjobling** [comment]
Hi Pradeep,

Thanks for following up.  Retested using your code and discovered that the issue was with additional new lines at the end of the postman body following the final --batch line.  Can't locate the same message with ARC but it may have been smart to truncate it.  Either way though it is working now through postman.

**Comment by KathrynEE** [comment]
Closing as answered.
