### ISSUE TITLE
Classic Mode Custom Condition with parameters

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/azure-devops-docs#8409]
I've looked through a number of pages and it really isn't very clear. Most of these docs seem to be based around YAML mode even though there is a Custom conditions for a task. 

I have a parameter to my Task Group called Components. If Components contains "blah" then I want to run a powershell task

I've put a condition 
```
contains(parameters.Components, 'cube')
```

but it puts a red squiggly underneath but no error. Is this right or wrong? Where is the doc that will explain this?

Specifically this document talks about how to refer to variables and then says you can also use parameters that are typed, but doesn't point to how I refer to parameters. Also parameters in task groups do not seem to be typed. 

This is an area that badly needs more comprehensive documentation and examples for Classic mode. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@o-o00o-o Parameters are a YAML-only feature. I'll make that clearer in our docs. Thanks for flagging this! 

For specific implementation concerns and feature requests, I'd recommend that you ask in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
