### ISSUE TITLE
Import a build definition having tasks groups leads to an error "Task group is no longer installed"

### ISSUE THREAD

**Issue by mithsapurva** [MicrosoftDocs/azure-devops-docs#8413]
We need to migrate the build and release pipeline from Azure DevOps Services to Azure DevOps Server 2019. The build and release pipelines have various task groups as well. 
While migrating, task groups are first exported from Azure DevOps Services and imported to Azure DevOps Server. After successful import of task groups, the build pipeline is imported. This imported build pipeline, is showing errors for task groups. The error is "The task group is no longer installed. Re-install the task and remove it from the pipeline". Please note that the task group is present.
After comparing the exported and imported task group json file, some id attributes have different values. 
How can I import build or release pipelines having task groups without removing and re-inserting each of the task groups in the newly imported pipeline? Please help.

**Comment by msebolt** [comment]
@mithsapurva  Thank you for the question, we apologize the issues.

If you can refer to a document in question we can assign an author for review, else, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
