### ISSUE TITLE
Parameters dynamic expression based default value

### ISSUE THREAD

**Issue by stankolubomir** [MicrosoftDocs/azure-devops-docs#8415]
Hello,
is it possible to define dynamic default value of the runtime parameter?
For example. I'd like to run pipeline where I have version string parameter. I'd like to have this version parameter prefilled with a dynamic expression based value of the latest tag in the repository.

My example parameters definition:
    parameters:
      - name: version
        displayName: Version
        type: string
        default: '$[some expression to get the latest tag in the repository or an output variable from the previous pipeline]'
      - name: environment
        displayName: Environment
        type: string
        default: 'devel'
        values:
          - devel
          - stage
          - production
      ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#feedback)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@stankolubomir Thank you for the feedback.

Unfortunately, this forum's documentation options are limited to examples within the documents only.

Please provide a reference to the documentation, or for additional support options see:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
