### ISSUE TITLE
How does one conditionally set the value of a variable in Classic Pipelines?

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/azure-devops-docs#8420]
I'm trying to determine how to set up a variable in the Classic Editor to accomplish something like this pseudocode illustrates:

if (Build.SourceBranchName == 'master') then value = ''
if (Build.SourceBranchName == 'develop' then value = 'beta'
if (Build.SourceBranchName contains 'feature/' then value = 'alpha'

How does one accomplish this if not using YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ronwarner You can see the instructions for conditions in the Classic editor here - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=classic.

**Comment by jholovacs** [comment]
@juliakm that article does not appear to answer the question asked. @ronwarner was asking how to set a variable value in classic pipelines, and the document you linked to discusses how to conditionally run a task. They may be related, but I had the same question and the answer was not helpful to me.
