### ISSUE TITLE
Are limitations per build? or per artifact feed? or per package? 

### ISSUE THREAD

**Issue by dsyme** [MicrosoftDocs/azure-devops-docs#8424]
The limitations are mentioned, but are they  per build? or per artifact feed? or per package? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114bd05d-0737-79af-9446-41d87cdc3943
* Version Independent ID: 8396a896-9cbb-78ac-7ec4-9b6046a3e09f
* Content: [Size and count limits for Azure Artifacts - Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/limits?view=azure-devops#feedback)
* Content Source: [docs/artifacts/reference/limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/reference/limits.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@dsyme Thank you for your feedback. The size limits are per package/file.
