### ISSUE TITLE
Reordering work items within a tree level

### ISSUE THREAD

**Issue by randomITperson** [MicrosoftDocs/azure-devops-docs#8425]
For a tree list in excel, I need to reorder the new work items that are adding. Is there a way to use excel to reorder all tasks under a user story for example and publish it back ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify work items using Microsoft Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@randomITperson - Thank you for your question. Could you say more about why the order of work items is important?  That said, in general:
- If you are working with a flat list, you can use Excel features to sort your work items 
- If you are working with a tree list, you don't want to sort your work items as that will change your tree structure and change your hierarchical links
- if you want to use Excel to manage the order of your work items as they appear in a team backlog, you can do that (not recommended, but supported) by using the Stack Rank or Backlog Priority field (Agile or Scrum process). You can set values in these fields and that will reorder the work items based on lowest to highest number.  However, the next time the backlog is reordered, these values are subject to change. 
- If you want to maintain a certain order of work items, you might consider adding a custom field to manage the sort order
