### ISSUE TITLE
REST API call failed

### ISSUE THREAD

**Issue by webbwei** [MicrosoftDocs/azure-devops-docs#8426]
is there something else I should do before I call REST API. I just call it as below,  but it dosn't work:
 VSS.init();
            VSS.require(["VSS/Service", "TFS/WorkItemTracking/RestClient"], function (VSS_Service, TFS_Wit_WebApi) {
                // Get the REST client
                var witClient = VSS_Service.getCollectionClient(TFS_Wit_WebApi.WorkItemTrackingHttpClient);
                witClient.getWorkItems([1, 2], ["System.Title"]).then(
                    function (workItems) {
                        console.log(JSON.stringify(workItems));
                    });
            });

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f99e26d-54fa-ac2c-1814-e1b3f97a87b5
* Version Independent ID: 0ed84e7f-b46f-3a44-16f6-d9bcf77bf11d
* Content: [How to Call a REST API - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/call-rest-api?view=azure-devops)
* Content Source: [docs/extend/develop/call-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/call-rest-api.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@webbwei Thank you for the question.

Unfortunately this forum's support options are limited to documentation examples only.

Please provide a reference to the document, or additional support, refer to:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
