### ISSUE TITLE
Getting Error in Logs

### ISSUE THREAD

**Issue by SergioManchonIN2** [MicrosoftDocs/azure-devops-docs#8427]
Hi,

We are trying to execute a command (download a docker image and run it) through a SSH connexion (task SSH@0). This works but we are getting log errors in the execution:

![image](https://user-images.githubusercontent.com/64000806/82675328-f6c47200-9c44-11ea-8785-2768589f6b22.png)

But as you can see in the next image, the command works:

![image](https://user-images.githubusercontent.com/64000806/82675476-26737a00-9c45-11ea-9930-ba159b06e9a8.png)

How can i solve this?

Thanks.

**Comment by msebolt** [comment]
@SergioManchonIN2 Thank you for the question.

Unfortunately this forum's support options are limited to documentation samples only.

Please add a reference to the document below, or refer to the following support options:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
