### ISSUE TITLE
Restrict access to everything but the NuGet feed

### ISSUE THREAD

**Issue by Gabriel-Lacatus** [MicrosoftDocs/azure-devops-docs#8430]
How can we restrict an external user to access only a NuGet feed (read) but nothing else (boards, code, etc)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7145130d-abba-fcfd-2016-e50c301c3f8b
* Version Independent ID: 900031bb-7389-2fee-7099-c3f48414efd1
* Content: [NuGet Authenticate - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops#restore-and-push-nuget-packages-outside-your-organization)
* Content Source: [docs/pipelines/tasks/package/nuget-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
#reassign ramiMSFT

**Comment by ramiMSFT** [comment]
@Gabriel-Lacatus Thank you for your feedback. I don't think that level of granularity is currently supported/possible.

Please check out our [Azure DevOps developer community](https://developercommunity.visualstudio.com/spaces/21/index.html) where you can post all product related questions.
