### ISSUE TITLE
建议添加文档多国语言翻译

### ISSUE THREAD

**Issue by cttismine** [MicrosoftDocs/azure-devops-docs#8434]
[在此处输入反馈]
建议添加文档多国语言翻译，我的英语不好，读不懂文档

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8633dcca-a842-9a00-a5c1-5a86ad9f31e5
* Version Independent ID: 11207fe4-0a68-b988-3ea3-582cd6a527a1
* Content: [Add privacy policy URL to comply with the GDPR - Azure DevOps Services](https://docs.microsoft.com/zh-cn/azure/devops/organizations/accounts/add-privacy-policy-url?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-privacy-policy-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-privacy-policy-url.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@cttismine 感谢您的反馈和**Microsoft Docs**论坛的使用。

请移动这个问题 [这里](https://github.com/MicrosoftDocs/feedback/issues) 进行其他审查。

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
