### ISSUE TITLE
Clarify the Authentication Method.

### ISSUE THREAD

**Issue by aueda** [MicrosoftDocs/azure-devops-docs#8438]
In the section _Restoring packages from feeds in a different organization_, step 8:

> In the service connection dialog that appears, enter the feed URL (make sure it matches what's in your NuGet.config) and the PAT you created in step 3

It assumes the _ApiKey_ authentication method should be used for this connection, since it is the default selected option.

However, the documentation step should explicitly tell the user which authentication method must be selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78a9f20-b8d2-4aa7-c52d-a968ab87315d
* Version Independent ID: 3880a787-8f70-8c13-176e-c732b619fb06
* Content: [Restore NuGet packages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/packages/nuget-restore.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/packages/nuget-restore.md)
* Product: **devops**
* Technology: **devops-cicd-packages**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@aueda Thank you for your feedback. The screenshot for that step already shows the method that should be selected: **External Azure DevOps Server**.

![image](https://user-images.githubusercontent.com/60942540/92533296-ff868700-f1e6-11ea-9d02-6a00291e41f9.png)

I just added clarification to that step. The updated article will go live shortly.
