### ISSUE TITLE
iconName of vss-extension.json

### ISSUE THREAD

**Issue by ChiefOfUnicornExtermination** [MicrosoftDocs/azure-devops-docs#8440]
Needs more information for **add an icon** of **Menus and toolbars section**?
When I set iconName whichever random name from [Office UI Fabric Icons](https://uifabricicons.azurewebsites.net/) for example"WebAppBuilderSlot", it's not shown on the page. Very limited icons only in [ms.vss-features.ui-core-content.min.css](ms.vss-features.ui-core-content.min.css_ for example) for example "RustLanguageLogo" works.
There may be some extra steps required to register iconName on settings? Or are these all I can set as iconName there? If so, it needs a list of possible iconNames.
I know not so many people want to use existing something when they create a new custom extension, but..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ChiefOfUnicornExtermination, Thanks for reaching out. I've circled back with the product group for some clarity and have created a user story to address this for my backlog. Thanks again!

**Comment by chcomley** [comment]
Hi @ChiefOfUnicornExtermination,  For the icons, we support a subset of the MDL2 Icons.  This wiki has some info on it and how to add new ones: https://dev.azure.com/mseng/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/10456/Icons.
External extension developers can't add new ones, though. Please @mention me if you have any additional questions. Thank you!

**Comment by ChiefOfUnicornExtermination** [comment]
1.  I cannot access your useful wiki page. 401 "You do not have access"
2. I can use MDL2 Icons for pages, but not side bar, correct?
![image](https://user-images.githubusercontent.com/65433846/83068663-83907680-a01d-11ea-8b5e-3add9a9e6927.png)
3. If we cannot use most of Office UI Fabric Icons there by setting iconName, it's fine. Then the tutorial page was incorrect, right? Will it be fixed?

**Comment by altinoren** [comment]
@chcomley Thank you. That wiki from mseng might be private, I can't access it.

Anyone who needs a list of supported icons can check AzDevMDL2.woff file.
Check Netwok tab of browser's Developer Tools while browsing a project on dev.azure.com, look for something like
https://cdn.vsassets.io/v/M169_20200527.1/_ext/ms.vss-features/ui-core-content/Components/Icon/fonts/AzDevMDL2.woff

**Comment by LockTar** [comment]
This website helped for me:
[https://uifabricicons.azurewebsites.net/](https://uifabricicons.azurewebsites.net/)
