### ISSUE TITLE
Unclear where to set options of "Clean the local repo on the agent"

### ISSUE THREAD

**Issue by KarstenSchaeffer** [MicrosoftDocs/azure-devops-docs#8441]
The note above this section suggests "Click Advanced settings in the Get Sources task to see some of the above options".
However
* "Get Sources" task is very hidden (Pipeline -> Edit -> "..." -> Triggers -> YAML Tab -> Get Sources task)
* The "Get Sources" task found here does have the mentioned clean options (after setting Clean to true), but they do not have an effect on the agent.

And most importantly: How can a clean be enforced interactively when starting a job manually?
Like it was possible by overriding the Build.Clean variable.
Also the clean-option of the YAML checkout keyword only accepts true/false literals, but no variables. This again prevents any interaction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#clean-the-local-repo-on-the-agent)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Investigating

**Comment by steved0x** [comment]
@KarstenSchaeffer I will get that page updated, here is the information on cleaning, there are a couple ways to do it.

There are 3 clean options for workspace in a job:
```
- job: myJob
  workspace:
    clean: outputs | resources | all # what to clean up before the job runs
```

These are detailed here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace

You can also specify a clean option in the Pipeline settings UI, as you describe above, which is the same thing as specifying clean: true in the checkout step in your pipeline:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout

The Build.Clean variable is deprecated so let me see what an alternative would be to to specifying this when manually running a pipeline, you should be able to use parameters but let me test it first.

**Comment by steved0x** [comment]
You can add a parameters section at the top of your pipeline and use that value in the clean step. In this example it is false by default but you can override that when manually running a pipeline by checking the box for checkout clean. You could also use this same approach using one of the workspace clean options:

```
parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true

trigger:
- main

pool: FabrikamPool

steps:
- checkout: self
  clean: ${{ parameters.clean }}
```

![image](https://user-images.githubusercontent.com/1580889/102245516-a7d57700-3ecb-11eb-96b5-36d3161522b6.png)

I will get the documentation updated
