### ISSUE TITLE
vso.features and vso.features_write and vso.analytics

### ISSUE THREAD

**Issue by VAllens** [MicrosoftDocs/azure-devops-docs#8443]
Lack of `vso.features` and `vso.features_write` as well as `vso.analytics`'s scope description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @VAllens. I've added vso.analytics, however  vso.features and vso.features_write aren't meant for external use, so I'll be leaving the article unchanged for those. Please @mention me if you have any further questions or feedback. Thank you!
