### ISSUE TITLE
upgrading azure CLI fails with error "Failed building wheel for pynacl"

### ISSUE THREAD

**Issue by goblinfactory** [MicrosoftDocs/azure-devops-docs#8446]
When following the instructions in "Azure DevOps CLI in Azure Pipeline YAML", and using the sample yaml file that upgrades the CLI, the build pipeline fails with error

> Failed building wheel for pynacl

<img width="669" alt="Screen Shot 2020-05-25 at 20 55 33" src="https://user-images.githubusercontent.com/1073487/82840537-e291a680-9eca-11ea-902b-f99c6d7dca2f.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by goblinfactory** [comment]
Please tag this issue as "won't fix" instead of letting a bot close it as stale. If it has been fixed, then it would be courteous to please post a comment on where the fix can be found so that if anyone comes to this page because they searched for this exact error will find the correct resolution.

**Comment by steved0x** [comment]
I am updating this article to use a single pipeline vs the current template approaches, but I was able to successfully run the examples in this article as given. The one main different I can think of between now and when this issue was originally opened is updates in the software that is installed on the hosted agents. The new version is simpler and should have less trouble. Thank you.

**Comment by steved0x** [comment]
#assign steved0x
