### ISSUE TITLE
How does the .NET Core task support publishing of test code coverage data?

### ISSUE THREAD

**Issue by TysonMN** [MicrosoftDocs/azure-devops-docs#8447]
At the end of this page, it says
> [**Tasks**](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops#tasks)
> - ...
> - Built-in tasks such as Visual Studio Test, [.NET Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops), Ant, Maven, Gulp, Grunt, and Gradle provide the option to publish code coverage data to the pipeline.

I have tried to verify this claim for the linked .NET Core task, but I have failed to do so.

Can someone be more specific about what option of the .NET Core task exposes this behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by msebolt** [comment]
@TysonMN  Thank you for the feedback.

The `--collect "Code coverage"` option appears to have gone undocumented, please refer to [collect code coverage](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#collect-code-coverage) for a working example though note this is currently only supported on Windows.

The documentation has been updated and is pending review.
