### ISSUE TITLE
Documentation not clear 

### ISSUE THREAD

**Issue by agray** [MicrosoftDocs/azure-devops-docs#8448]
Documentation should make it clear that by disabling this option and specifying a redirect URL that:

1. For it to work at all the user must have no association WHATSOEVER with the org, otherwise they will be added as a stakeholder by default (which in itself is dumb)
2. When the process is working the user will still see the access denied page but in order for the redirect to happen they have to do a second action of clicking on the link under the red text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112fefce-9444-4cd0-d680-7960955e1d18
* Version Independent ID: bf19c853-7988-53f3-aaed-98479a522d14
* Content: [Disable Request Access policy - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/disable-request-access-policy?view=azure-devops)
* Content Source: [docs/organizations/accounts/disable-request-access-policy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/disable-request-access-policy.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @agray, Thanks for the heads up on this. I've created a user story to address this issue. Have a great day!

**Comment by chcomley** [comment]
Hi @agray, The 2nd one is correct. If you disable this policy and use a custom URL, any user who doesn’t have access will still see the 403 and they can click a link within the page to redirect their access request. 
We're looking into #1 at the moment and may follow up with you. 
I've created a user story to address the docs, thank you. Adding @parsamzand for additional input, if necessary. Thank you.

**Comment by agray** [comment]
I would suggest that it would be clearer if the documentation stated:
"The URL redirect will not occur until the user clicks the link presented on the no access screen"

Or something wordsmithed along these lines.

#LaunchAmerica

**Comment by parsamzand** [comment]
Hi @agray, could you elaborate on what you mean by  "no association WHATSOEVER with the org" as described in #1? Users shouldn't be added as stakeholders by default as a result of this, and I'd like to make sure there is not a bug here.

**Comment by chcomley** [comment]
#sign-off
