### ISSUE TITLE
When modifying permissions there's no "Save Changes" button

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#8450]
When modifying permissions there's no "Save Changes" button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 024e4ed9-cf8d-155f-5e4a-73c2effaaed8
* Version Independent ID: f19c0538-4aae-b3b4-82b9-422e76723b01
* Content: [Run Git commands in a script - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/scripts/git-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/git-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
Good catch, the permissions screens have been redesigned. This topic needs new screenshots and should no longer mention clicking "save" (at least for Azure DevOps 2020 and the hosted service -- need the old instructions for down-level servers).
