### ISSUE TITLE
Incorrect environment variable in gradle sample

### ISSUE THREAD

**Issue by hangy** [MicrosoftDocs/azure-devops-docs#8451]
The gradle sample uses invalid environment variable names:
```
                password System.getenv("Azure DevOps Services_ENV_ACCESS_TOKEN") != null ? System.getenv("Azure DevOps Services_ENV_ACCESS_TOKEN") : vstsMavenAccessToken 
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52da1009-6733-d555-3c00-1a1bd77f1759
* Version Independent ID: 72b916de-2836-460b-2889-67981ffea5a4
* Content: [Publish a Maven artifact using Gradle - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/publish-package-gradle?view=azure-devops)
* Content Source: [docs/artifacts/gradle/publish-package-gradle.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/gradle/publish-package-gradle.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by hangy** [comment]
FWIW, the username provided in that sample also differs from the one used here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops#we-use-the-mvn--s-switch-to-specify-our-own-settingsxml-file-how-do-we-authenticate-azure-artifacts-feeds-there

**Comment by gdurandrexel** [comment]
The correct user name is: Azure DevOps Services
The correct variable name is: AZURE_ARTIFACTS_ENV_ACCESS_TOKEN
See also https://developercommunity.visualstudio.com/content/problem/944561/publish-artifact-vstsmavenaccesstoken.html

**Comment by ramiMSFT** [comment]
@hangy Thank you for your feedback. The updated article will go live shortly.

**Comment by hangy** [comment]
Thank you, @ramiMSFT!
