### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by mlomat** [MicrosoftDocs/azure-devops-docs#8454]
Hello MS team, 

Looks like your documentation is outdated. I see that there is option right now to edit Wiki when it's published as a wiki in exactly this same way as Provisioned wiki. So section https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops#supported-features-and-operational-differences is no longer valid. 

Below screenshot from my Wiki in DevOps. Best Matt!

![image](https://user-images.githubusercontent.com/7577121/82905159-cc83f480-9f63-11ea-9e27-e60d2de35b19.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mlomat, Thanks for the heads up on this. I've created a user story to address the update. Thanks again!
