### ISSUE TITLE
Is there a way to add git commit hash to the build name?

### ISSUE THREAD

**Issue by jacum** [MicrosoftDocs/azure-devops-docs#8456]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by jacum** [comment]
the example goes like:
$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

Could we have something like
$(Date:yyyyMMdd)-$(Time:hhMMSS)-$(SourceCommitHash)
?

**Comment by jacum** [comment]
any updates on that?

**Comment by msebolt** [comment]
@jacum  Apologies for the delay.

Please try using `Build.SourceVersion` as referenced from [this post](https://www.hanselman.com/blog/AddingAGitCommitHashAndAzureDevOpsBuildNumberAndBuildIDToAnASPNETWebsite.aspx).  

A similar example i`$env:BUILD_SOURCEVERSION` is posted [here](https://developercommunity.visualstudio.com/content/problem/143021/git-commit-hash-on-build-name-is-empty.html).

**Comment by jacum** [comment]
Thank you for paying attention to my question.

I tried it and it works, but in case of Git I get long hash commits, not very usable as part of BuildNumber.

This proposal 
https://developercommunity.visualstudio.com/idea/1026034/add-support-substring-functions-in-azure-pipelines.html
contains solution, but it's not implemented yet... is it?

**Comment by msebolt** [comment]
You're welcome.

Thank you for providing the link, we can see if the product team will implement an easier way to handle this.

For now, directly formatting variable strings is not yet supported and the work-around is to use PowerShell, please refer to [this post](https://stackoverflow.com/questions/57817659/how-to-replace-in-variable-strings-inside-azure-pipelines-yaml).

**Comment by vtbassmatt** [comment]
I'd recommend something like:

```yaml
- bash: |
    HASH=$(git rev-parse --short $BUILD_SOURCEVERSION)
    echo "##vso[build.updatebuildnumber]mybuildname-$HASH"
```

**Comment by Dessix** [comment]
This is still undocumented on the [Run Number Documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml).

**Comment by WilliamAntonRohm** [comment]
@Dessix -- Zoey, thank you for your follow-up.

@juliakm -- Julia, please look into this issue.
