### ISSUE TITLE
How to copy files "from" Azure storage blob to local disk

### ISSUE THREAD

**Issue by alovera** [MicrosoftDocs/azure-devops-docs#8457]
This task is great for uploading artifacts to Azure blob storage, but it does not allow the reverse action (e.g. to download files from Azure blob storage to the local working directory).  Is there another DevOps task for this operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@alovera Thank you for the question.

You can use the [Blob service](https://docs.microsoft.com/rest/api/storageservices/blob-service-rest-api) and make the call using the [REST API task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api).

To recommend new tasks to the product team, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Or, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
