### ISSUE TITLE
[Suggestion] Azure DevOps Add Project Visibility - Organization Level

### ISSUE THREAD

**Issue by patrick-truskowski-perficient** [MicrosoftDocs/azure-devops-docs#8458]
Hello,

I'm interested in an additional visibility option when creating new projects: "Organization Level"

The idea is we want to be able to create new projects that are discoverable by the entire organization but not to the public. 

Public - anyone on the internet
Organization - anyone in the org
Private - access must be added per user

If a project was created with "Organization" visibility, all users would only have read access. If they wanted contributor access, they would either need to contact the Admin or there could be an option to "Request Contributor" for "Readers". 

**Proposed screenshot:** 

![image](https://user-images.githubusercontent.com/65569791/82935995-82931280-9f53-11ea-90a1-3e23c4cd4627.png)

Thank you,
Pat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a4e9e9-6773-fad2-23fb-8b44313f8ef3
* Version Independent ID: 33cbd1fc-2230-4e0b-2627-2a63bf7c634e
* Content: [Make your project public or private - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=azure-devops)
* Content Source: [docs/organizations/public/make-project-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/make-project-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@patrick-truskowski-perficient Thank you for the question.

For new features and suggestions, please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.

There the product team can offer general guidelines and feasibility of the request.
