### ISSUE TITLE
Complete example

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#8462]
[Enter feedback here]

Hi, thanks for the documentation of that feature. It would be helpful to have a complete example of a sample pipeline because for me it is not clear at what part of the pipeline the code-snipped should be used.

best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
The current author's alias cannot be found.

**Comment by mcalnd70** [comment]
One year later - I can't work out where to put this in relation to the larger pipeline - Any updates please
