### ISSUE TITLE
No docs on custom flaky test detection in Azure Pipelines

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#8464]
> Custom detection - You can integrate your own flaky detection mechanism with Azure Pipelines and utilize the reporting capability. 

How?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dfb3bf-8cce-7ad8-b2c6-40d6c2b9d441
* Version Independent ID: 53e2d39d-6808-70d5-9c26-bc4c5bb109e3
* Content: [Manage flaky tests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops)
* Content Source: [docs/pipelines/test/flaky-test-management.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/flaky-test-management.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@letmaik - This is a known issue and we are working with the feature PMs to get the content documented. Am closing this issue as we are tracking it with this one: https://github.com/MicrosoftDocs/azure-devops-docs/issues/6700.
