### ISSUE TITLE
Update "Set repository permissions for Git or TFVC"

### ISSUE THREAD

**Issue by PStoner3** [MicrosoftDocs/azure-devops-docs#8469]
Please update the documentation on adding users and/or groups to repository security. There is no `+` sign that I can see 

![Repositories - Settings](https://user-images.githubusercontent.com/17929362/83051963-ae2dff80-a01c-11ea-997d-8c2f30bc7748.png)

How do I add back a group that was removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5ce059-ec92-5413-0910-4e28033db034
* Version Independent ID: 540610d3-6073-664d-97f8-e7d8e0a21a20
* Content: [Set Git or TFVC repository permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/set-git-tfvc-repository-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/set-git-tfvc-repository-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@PStoner3 - Thank you for the feedback. The article has been updated since your feedback last May. Sorry for the delayed response. For some reason, I was just recently assigned this issue.
