### ISSUE TITLE
Agent.MachineName or Agent.ComputerName

### ISSUE THREAD

**Issue by a1exstr** [MicrosoftDocs/azure-devops-docs#8475]
Seems the page contains either a typo or outdated information.
Agent.MachineName does not really exist (at least from what I see on my agents)
It is Agent.ComputerName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops-2019&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mijacobs** [comment]
We tested Agent.MachineName and it works on current version of Azure DevOps. What version are you using?

**Comment by vtbassmatt** [comment]
`Agent.MachineName` is a predefined variable. `Agent.ComputerName` is a capability set by self-hosted agents. See my answer in https://github.com/MicrosoftDocs/azure-devops-docs/issues/9707
