### ISSUE TITLE
I think, There are some errors in the documention

### ISSUE THREAD

**Issue by Raffaello** [MicrosoftDocs/azure-devops-docs#8478]
[Enter feedback here]
section:

> userRepositoryRepository | (Required) Select the name of GitHub repository in which GitHub releases will be created.

should be something more like 
`Select the name of GitHub repository from which GitHub releases will be downloaded.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cebdaea-9b1f-e65a-a789-6571b5e28c03
* Version Independent ID: ca0de77d-d8a7-d766-90e6-929bdb2c877f
* Content: [Download GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-github-release.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-github-release.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@Raffaello Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
