### ISSUE TITLE
No information about packages as resources

### ISSUE THREAD

**Issue by slawekww** [MicrosoftDocs/azure-devops-docs#8485]
This doc describes packages: https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-resources.md

Please explain how to download packages from Azure Artifacts in YAML pipeline
and how to use them as triggers for YAML pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#resources)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@slawekww I'm about to push an update. The packages type currently only supports GitHub packages. Please check out [this article](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml) for using artifacts in pipelines.
