### ISSUE TITLE
Republish same package after deleting it.

### ISSUE THREAD

**Issue by contactvikasgupta** [MicrosoftDocs/azure-devops-docs#8488]
After creating artifacts, package was published but found some issue in that. So fixed it and wish to republish. Since this version is already known to whole organization so cannot change version number but after deleting the package from artifactory and attempting to republish yield this error

Ignoring --cache-directory because the cache is not yet supported on OS "Linux 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020".
The package <packagename> <packageversion> in <reponame> has been deleted, and cannot be republished

Any solution?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@contactvikasgupta Thank you for the question.

For product-related issues and/or support requests, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For concerns with the documentation, please include further references below.

Otherwise, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by tiny-dancer** [comment]
@contactvikasgupta running into same problem, is there a link to recommended resolution?

**Comment by msebolt** [comment]
A similar issue to this has been reported [here](https://developercommunity.visualstudio.com/content/problem/1087365/universal-package-download-does-not-exist-or-you-d.html).

**Comment by cyciopes** [comment]
Hi @contactvikasgupta, @tiny-dancer, may I know did you have a solution yet?

**Comment by contactvikasgupta** [comment]
You are little late in reply, this project went to production in Q1’2021.

**Comment by cyciopes** [comment]
@contactvikasgupta unfortunately, it appears again with error msg like below:

Response status code does not indicate success: 409 (Conflict - The version 16.1.0.1533 of WebClientSdk has been deleted. It cannot be restored or pushed. (DevOps Activity ID: 344A870B-4853-46DE-A3C6-CD47F98018BF)).
