### ISSUE TITLE
Outdated FAQs

### ISSUE THREAD

**Issue by DavidNorena** [MicrosoftDocs/azure-devops-docs#8491]
Docs FAQs says:

Q: Can I regenerate a PAT?
A: No, but you can extend a PAT or modify its scope.

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#q-can-i-regenerate-a-pat

I think that should be removed because now you are able to regenerate the pat without creating a brand new one.

![image](https://user-images.githubusercontent.com/26279057/83317087-e33e7b80-a1ef-11ea-920d-ad3f365daeee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @DavidNorena, Thanks for the heads up on this. I have a PR going now that addresses this issue. It should be live sometime today or tomorrow. Thank you!
