### ISSUE TITLE
Bug workflow diagram image for Agile is incorrect in connecting Closed to Active on regression

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-docs#8496]
Once a bug is closed, the fix is released and is referenced in release notes and is being actively used in deployments. One cannot reopen the same bug because it caused regression. Doing so would cause the same bug listed again in the release notes for the next release, which makes no sense. 

A bug may be transitioned from the Closed state to any state if it was closed in error, as you describe in the CMMI diagram, which is correct. It would be a good idea also to mention that this may happen _only_ before the fix is released. Otherwise a new bug should be created and linked to the old bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58aacca7-05a2-e8dd-6a6f-3025d734ef20
* Version Independent ID: 3eea19c1-8bda-6b60-e77d-8c0e82c3f096
* Content: [Define & manage bugs or code defects - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=azure-devops&tabs=new-web-form)
* Content Source: [docs/boards/backlogs/manage-bugs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-bugs.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gh-andre - Thank you for your feedback. I'm updating the article today to provide a tip on recommended practice.
