### ISSUE TITLE
Resources: packages example and schema are missing

### ISSUE THREAD

**Issue by samitkumarpatel** [MicrosoftDocs/azure-devops-docs#8497]
[Enter feedback here]

Resources: package documents is missing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
We just pushed an update to the [resources article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema) that should be live shortly. The packages type only is for to GitHub packages now.

**Comment by samitkumarpatel** [comment]
It looks good and well elaborate. Thanks
