### ISSUE TITLE
@plastikfan, there's no limitation on when you can delete. You can delete an organization whenever you want. If this isn't clear, please @mention me. Thanks!

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/azure-devops-docs#8499]
@plastikfan, there's no limitation on when you can delete. You can delete an organization whenever you want. If this isn't clear, please @mention me. Thanks!

_Originally posted by @chcomley in https://github.com/MicrosoftDocs/azure-devops-docs/issues/8407#issuecomment-636980133_

@chcomley, you closed my previous issue before I had a chance to respond to your reply. Please can you reopen that issue and see the comment I have made there, thank you

**Comment by msebolt** [comment]
The mentioned issue has been reopened, closing now.

**Comment by plastikfan** [comment]
It is clear to me that you have not understood this issue. Please re-open until this has been resolved. The problem is that organsiations are not deleted immediately, you have to wait 28 days.

**Comment by plastikfan** [comment]
I think somebody deleted the organisation, because I tried to recreate the same organisation in my new account and it worked.
