### ISSUE TITLE
GitHubRelease@0 tagPattern not documented

### ISSUE THREAD

**Issue by jakoch** [MicrosoftDocs/azure-devops-docs#8502]
The GithubReleaseTask has an optional key `tagPattern`.
It's documentation is missing in the Arguments section.

```
- task: GitHubRelease@0
  inputs:
    #tagPattern: # Optional          <-- ???
```

Update:
Ok, found some hints in the UI dialog of the task:
```
Specify the git tag pattern using regex(Eg. release-v1.*). 
GitHub release will be created only for commits that have matching git tag.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
