### ISSUE TITLE
document the behavior of spawned process 

### ISSUE THREAD

**Issue by ncourtiller** [MicrosoftDocs/azure-devops-docs#8505]
I think the behavior of spawned process should be documented : I notice indeed that all spawned process by the runned batch (for instance using `start my_program.exe`) are killed at the end of this task. This is not the case with the **command line** task and can be very confusing.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/batch-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
That's not the intended behavior. Any process spawned by the task is supposed to be ended at the end of the task, so you may have identified a product bug with the CmdLine task. You can file that over at [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
