### ISSUE TITLE
GIT Items : wrong url for Get a file api

### ISSUE THREAD

**Issue by jmrablat** [MicrosoftDocs/azure-devops-docs#8506]
Hi,
Just been using the Get a file api for TFS2017.3, it seems the url on the documentation contains a /repos after /_apis which not correct. From what I have been experienced just now the correct url ( for TFS2017.3) should look like this : 
https://{instance}/DefaultCollection/{project}/_apis/git/repositories/repository}/items?api-version={version}&scopePath={filePath}[&includeContentMetadata={bool}&lastProcessedChange={bool}]

Wrong url in documentaion is :
https://{instance}/DefaultCollection/{project}/_apis **/repos**/git/repositories/{repository}/items?api-version={version}&scopePath={filePath}[&includeContentMetadata={bool}&lastProcessedChange={bool}]

Thank's for your help
Jean-Marie
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6352e69f-5194-e602-7805-f84fa03fe133
* Version Independent ID: d025ce16-87e5-e6bd-0dea-f223c5720f4d
* Content: [Git Items - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/items?view=azure-devops-2019)
* Content Source: [docs/integrate/previous-apis/git/items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/previous-apis/git/items.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks so much for the feedback, @jmrablat. I'm working on a PR which should be live sometime this afternoon with your update. Thanks again!

**Comment by jmrablat** [comment]
Hi @chcomley, 

I have just spent some times to check the changes on the page. There are still some wrongs URL for some APIS I did not noticed before....
On the page [Get items](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/items?view=azure-devops-2019)

[Get a file](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/items?view=azure-devops-2019#get-a-file)
https://{instance}/DefaultCollection/{project}/_apis` /repos`/git/repositories/{repository}/items?api-version={version}&scopePath={filePath}[&includeContentMetadata={bool}&lastProcessedChange={bool}]

[Zip a folder](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/items?view=azure-devops-2019#zip-a-folder)
GET https://{instance}/DefaultCollection/{project}/_apis`/repos`/git/repositories/{repository}/items?api-version={version}&scopePath={folderPath}

[Get item metadata for](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/git/items?view=azure-devops-2019#get-item-metadata-for)
GET https://{instance}/DefaultCollection/{project}/_apis`/repos`/git/repositories/{repository}/items?api-version={version}&scopepath=/mywebsite/mywebsite/views/home/_home.cshtml

All theses give the message "no page found", but work without the `/repos` in the url !

For example: 
http://toto:8080/tfs/mytoto/tools/_apis/git/repositories/toto/items?api-version=3.2&scopePath=/toto

I might not have been precise enough on my first message, I hope it's clearer for you now.
Thank's for your help.

And have a nice day!

**Comment by chcomley** [comment]
Hi @jmrablat,  Thanks for this! I've updated the article. In the future, if you're feeling adventurous, I invite you to create your own PR in our public repo for fixes like these. No pressure! You can do so by selecting **Edit** at the top left of an article, and then creating a branch and pull request, and then it'll be reviewed. Here's some more info: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests.  Have a great day!
