### ISSUE TITLE
Template V3 Yaml

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/azure-devops-docs#8508]
Yaml example needs to be updated to v3 and not v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@cconrado Thank you for the feedback, I'm only seeing V2 listed [here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks) in the task repo.  

Please provide a reference to use of V3 and we can provide an update to the documentation.

**Comment by cconrado** [comment]
@msebolt actually it was meant for the azure resource template task but I didn't find it.

**Comment by steved0x** [comment]
Each version of a task has its own page in the new task reference, so this example is OK to stay at V2 on that page:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

We will prepare new examples for the new task in V3:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-manager-template-deployment-v3?view=azure-pipelines
