### ISSUE TITLE
There is nothing about changing work item state for stakeholders

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8513]
I spend more than hour trying to find if stakeholders can or can not change work item's state assigned to them.

Please clarify this!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@VerdonTrigance - Thank you for your inquiry. The section, [Features and functions available to Stakeholders](https://docs.microsoft.com/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process#features-and-functions-available-to-stakeholders) describes the functions that aren't available to Stakeholders. If it isn't listed there, you can assume that Stakeholders can use it. As Stakeholders can modify work items, that means they can update any field in the work item, unless a rule has been applied to restrict that. No rules are applied by default.
