### ISSUE TITLE
Mermaid Support Inaccurate

### ISSUE THREAD

**Issue by bryanloeper** [MicrosoftDocs/azure-devops-docs#8515]
There's a note in the mermaid section that says
>Current version of Mermaid used is 8.2.6
and three diagram types are called out as supported: flowchart, sequence, and gantt

However, based on this issues, it does not appear to be fully supported for at least flowcharts, possibly other issues:
* https://developercommunity.visualstudio.com/content/problem/889190/mermaid-flowchart-does-not-render-cylindrical-shap.html

I'm not sure how to best clarify what is/isn't supported, but it's definitely not the full featureset of 8.2.6 for those diagrams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @bryanloeper, Thanks for your feedback. We're looking into this and will get back to you shortly. Have a great day!

**Comment by chcomley** [comment]
I've removed the portion of the note causing confusion which insinuates that the entire feature set is supported. We'll update the article further as this develops. Thanks again!
