### ISSUE TITLE
can't seem to subscribe to any notifications. 

### ISSUE THREAD

**Issue by Nozziel** [MicrosoftDocs/azure-devops-docs#8516]
[Enter feedback here]
The documentation is not clear enough to me.
If I do an @Asure Repos and press space it emediatly starts searching trough the pull requests.
While I'm attempting to subscribe to a repo so we can get pull request notifications in that channel.

But I can't seem to add nor view current subscriptions or do anything else but search pull requests. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @divya
* Microsoft Alias: **divais**

**Comment by msebolt** [comment]
@thomps23 Author's GitHub alias cannot be found.
