### ISSUE TITLE
Is this process still valid for azure devops 2010 1.1?

### ISSUE THREAD

**Issue by stevenevans-j2** [MicrosoftDocs/azure-devops-docs#8517]
[Enter feedback here]
We have just upgraded our TFS 2017 server to azure develops 2010 1.1 this server was first created using either TFS 2008 or 2010 and has been updated several times, we have used the automatic updates only,  Having just found this article we are considering updating our process as documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06710957-b1e7-af87-c6f4-2d224abb3bf7
* Version Independent ID: 05d06cd2-800f-8ea9-bf86-044c991c304e
* Content: [Update a project - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/update-a-team-project-v4-dot-2-process-template?view=azure-devops)
* Content Source: [docs/reference/xml/update-a-team-project-v4-dot-2-process-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/update-a-team-project-v4-dot-2-process-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@stevenevans-j2 - If you're server was upgraded to TFS 2017, it's quite likely that you have all the process updates that are mentioned. The article is still valid. I would go through and first check to see if you need to add any changes.
