### ISSUE TITLE
Report Builder 2.0 References in a 2017 document

### ISSUE THREAD

**Issue by Zexks** [MicrosoftDocs/azure-devops-docs#8518]
I only bring this up because it sent me on a half hour trip through the web looking up Report Builder 2.0 and its differences between the most recent edition of simply Report Builder. RB 2.0 hasn't been updated since 2008 per the links on the page, while "Report Builder" the most recent that I can find being updated in 2019. With this article being written in 2017 this seems odd to point to software that was nearly a decade out of date at the time of writing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb3df5b8-1c1b-54c8-a081-2dfecdc8c67c
* Version Independent ID: 418ea1d6-984b-916a-4d9b-490c34070d59
* Content: [Create and manage Reporting Services reports - TFS](https://docs.microsoft.com/en-us/azure/devops/report/sql-reports/create-and-manage-reporting-services-reports?view=azure-devops-2019)
* Content Source: [docs/report/sql-reports/create-and-manage-reporting-services-reports.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/sql-reports/create-and-manage-reporting-services-reports.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Zexks - Thank you for the feedback. I'm updating the article today to provide more recent resources.
