### ISSUE TITLE
Missing error code: VS1640105

### ISSUE THREAD

**Issue by matthemo** [MicrosoftDocs/azure-devops-docs#8522]
While attempting to clone a process, I received the following:

VS1640105: Unrecognized value 'Active' for property condition.value. Try validating rules for these values.

As I'm trying to clone an existing process that's already running in the same org, I'm not sure how to go about validating it or addressing the issue. More assistance understanding what's happening and how to fix it would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ecc59-b30a-cb41-aa6b-7ba24fb6fa2a
* Version Independent ID: f5b6f454-7b3b-79cf-ab86-2cf0f043a660
* Content: [Resolve validation errors - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/resolve-errors?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/resolve-errors.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/import-process/resolve-errors.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@matthemo - I suggest you look at the comments for https://developercommunity.visualstudio.com/content/problem/374762/vs1640105-unrecognized-value-undefined-for-propert.html. If that doesn't help, please file a Support issue.
