### ISSUE TITLE
Pipeline keeps failing

### ISSUE THREAD

**Issue by dfi-838082** [MicrosoftDocs/azure-devops-docs#8535]
I followed the exact procedure without any changes and the pipeline failed. Since, it wasn't building with the default macOS vmImage, I modified the vmImage in YAML file to ubuntu-latest, but it still fails 

"##[error]Error: The process '/home/vsts/work/1/s/gradlew' failed with exit code 1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 454383d9-78ce-6203-2926-3449842d2f9f
* Version Independent ID: 947f872e-95b9-1691-acf0-e1a3f73b1e75
* Content: [Build, test, and deploy Android apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/android.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/android.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by juliakm** [comment]
@dfi-838082  I'm working on updating this article in the next couple of months. In the meantime, I'd recommend using a different code sample to start with. If you are using Android Studio, you can use their [basic project for Android](https://developer.android.com/training/basics/firstapp/creating-project). The Android auto-generated template that uses Gradle should work then.
