### ISSUE TITLE
How to specify target framework for VSTest task

### ISSUE THREAD

**Issue by TysonMN** [MicrosoftDocs/azure-devops-docs#8536]
The documentation says
> Tests that target the .NET core framework can be executed by specifying the appropriate target framework value.

How does one specify a target framework value for the VSTest task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by bender2k14** [comment]
Thanks @msebolt.

What do you think about improving the documentation by incorporating some of that information?  I for one know that I would find it more useful if the line...
> Tests that target the .NET core framework can be executed by specifying the appropriate target framework value.

...was more like
> Tests that target the .NET core framework can be executed by specifying the appropriate target framework value in the `.runsettings file`.

**Comment by msebolt** [comment]
The documentation has been updated.  Please comment below if there are any further issues.
