### ISSUE TITLE
Clarification for not allowing variables with service connection

### ISSUE THREAD

**Issue by scottvossen** [MicrosoftDocs/azure-devops-docs#8538]
Can you add a reason for why variables are not allowed with the service connection inputs? I see the warning bubble noting it, but there's no detail on why. 

This is a pretty frustrating limitation since I'd like to include it via a global variables template. Being able to target "testSubscription" and "prodSubscription" via a variable would avoid me having to update every pipeline when my subscriptions or the service connection name changes (which is happening).

Anyways, at least a little more detail here would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by arnoschuring** [comment]
That warning doesn't appear accurate. Basically all our (yaml) pipelines start with this preamble:

```
variables:
- name: AzureSubscription
  value: <service connection name>
```

And pretty much all our (Azure) support templates have this parameter specification:

```
parameters:
- name: azureSubscription
  type: string
  default: $(AzureSubscription)
```

Which means that all our deployments default to using a globally-defined variable, but the service connection can be overridden per-template. So far, this hasn't given us any troubles, but if this were to go away (because it isn't actually "supported") we would need to do some serious damage control.

**Comment by juliakm** [comment]
I'm not seeing a reference to variables not being allowed so I wonder if this is an old issue. If you're referring to a problem within the Pipelines UI, the best place to report an issue (or feature request) is in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Closing this issue for now.
