### ISSUE TITLE
Got everything 

### ISSUE THREAD

**Issue by Mannyg0420** [MicrosoftDocs/azure-devops-docs#8539]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@Mannyg0420 Thank you for the feedback.  

If you have any further questions or issues with the documentation please comment below.
