### ISSUE TITLE
Perms > Colctn-Lvl [APL] > 2 Mssng Subsectns + 1 in Err

### ISSUE THREAD

**Issue by dennis-thomas-o** [MicrosoftDocs/azure-devops-docs#8540]
In the [Collection-level permissions section](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions#collection-level-permissions), _Auditing_ and _Policies_ subsections are missing from documentation text and from the screenshot. Please add them. Thanks in advance.

In the _General_ subsection, the _View audit log_ item is mentioned but it’s not in that subsection on the web portal any more (as the screenshot also shows). It has been moved to the new _Auditing_ subsection. Please remove the item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#collection-level-permissions)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dennis-thomas-o  - Thank you for the feedback. I'm making the updates to the content today.
