### ISSUE TITLE
Document node requirement for linux containers on windows hosts

### ISSUE THREAD

**Issue by dferretti** [MicrosoftDocs/azure-devops-docs#8543]
The docs do say that container jobs require the prerequisites for running node be met, and that the agent will bring its own node executable. However, when running a linux container from a windows host, the agent will not be able to bring its own node (which makes sense). Maybe the windows agent could come with both windows and linux versions of node and supply the correct version when running the container? 
But until then it would be nice if the docs here mentioned that the linux container must come with node installed and available as `node` on the $PATH (unless otherwise specified in the `com.azure.dev.pipelines.agent.handler.node.path` LABEL)

https://github.com/microsoft/azure-pipelines-agent/blob/af907e5f6f077f98910c68863ae93742b8a28a0f/src/Agent.Worker/ContainerOperationProvider.cs#L353

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@dferretti Thank you for the feedback.

The documentation has been updated and is pending review.

For your suggested changes to the agent, please consider moving the issue to the [azure-pipeline-agent](https://github.com/microsoft/azure-pipelines-agent/issues) repo.

**Comment by dferretti** [comment]
Awesome thank you for the response!
I will take the other idea to the pipeline agent repo 👍
