### ISSUE TITLE
Extension selective enabling for user/groups

### ISSUE THREAD

**Issue by croban** [MicrosoftDocs/azure-devops-docs#8544]
Is there a possibility to disable installed extension for some user btw. groups?
Maybe documentation should contain info that extension can not be disabled/enabled for the specific user/groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4290c10-4f12-f4f2-a189-4395fbe5525b
* Version Independent ID: 41204723-bd4b-270d-f13f-df961c565ca9
* Content: [Install extensions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser)
* Content Source: [docs/marketplace/install-extension.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/install-extension.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by KathrynEE** [comment]
@croban - Enabling/disabling of extensions by user or group isn't a supported feature. Closing this issue.
