### ISSUE TITLE
No definition or comparison about @local, @Prerelease and @Release

### ISSUE THREAD

**Issue by haokanga** [MicrosoftDocs/azure-devops-docs#8545]
There is no explanation or comparison about `@local`, `@Prerelease` and `@Release`

Also, are these 2 links (w/ v.s. w/o `%40Local`) point to the same repository? 
or are they different in a way that `@Local` is a view/subset of the whole repository?

https://dev.azure.com/<org_id>/<project_id>/_packaging?_a=connect&feed=<feedname>%40Local
https://dev.azure.com/<org_id>/<project_id>/_packaging?_a=connect&feed=<feedname>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Use the prerelease and release views to publish your packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@haokanga Thank you for your feedback. We have couple of articles that explains feeds and views under the same section: "Artifact feeds".
By default, there are 3 views in a feed: `@local`, `@prerelease`, and `@release`. The latter two are suggested views that you can rename or delete as desired.
The @local view is the default view and it includes all the packages that were published directly to the feed as well as all the packages that were saved from the upstream sources.
See the following articles for more details:
- [What are feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops)
- [What are feed views](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops)
- [Set feeds and views permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops)
