### ISSUE TITLE
How do you specify from a parameter which branch to checkout of a repository?

### ISSUE THREAD

**Issue by MichaelGoulding** [MicrosoftDocs/azure-devops-docs#8546]
I would like to do something like the below to pick up a specific version of dependencies.

resources:
  repositories:
  - repository: myRepro
    type: git
    name: myRepro
    ref: ${{ parameters.TargetedBranch }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@MichaelGoulding Thank you for the question.

Please see if `System.PullRequest.TargetBranch` under [pipeline variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables) can handle this issue.

If not, please try **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit further feedback from the product team, see [here](https://developercommunity.visualstudio.com/idea/616094/branch-specific-build-variables.html) for a similar previously posted issue.

**Comment by polavishnu4444** [comment]
Hi,
Looking for similar feature, where I want to use the repository ref to a particular branch controlled by custom user input parameter value. Pipeline variables seems to be useful only in case when I have my pipeline definition in the repo resource that I am using. I have my pipeline definition outside in a different repo and the branches there doesn't correlate to branches in the repo resource I need. Is there a way currently for doing?

**Comment by e14mattc** [comment]
We're looking for exactly the same thing @polavishnu4444 .. did you get anywhere finding a solution to this?

**Comment by fleed** [comment]
Same problem here. Any solution?

**Comment by kaushikbbr** [comment]
I am looking for a solution too! Anybody any luck?

**Comment by e14mattc** [comment]
We found this actually worked fine..

`resources:
  repositories:
  - repository: myreponame
    type: 'github'
    name: 'orgname/myreponame'
    ref: $(BranchBinariesName)
    endpoint: 'GitHub (orgname)'

trigger: none

steps:
- checkout: myreponame`

Then we have a variable (in Library -> Variable Groups) that contains the branch name.. that works perfectly & fitted our needs.

**Comment by kaushikbbr** [comment]
> We found this actually worked for us..
> 
> ```
> resources:
>   repositories:
>   - repository: myreponame
>     type: 'github'
>     name: 'orgname/myreponame'
>     ref: $(BranchBinariesName)
>     endpoint: 'GitHub (orgname)'
> 
> trigger: none
> 
> steps:
> - checkout: myreponame
> ```
> 
> Then we have a variable (in Library -> Variable Groups) that contains the branch name.. that works perfectly & fitted our needs.
> 
> Hope this helps.

This again is a static variable set inside the library. How do you intend to take a parameter from user at runtime?

**Comment by e14mattc** [comment]
Oh, no, I'd not realised that was the intention :(

**Comment by prajeeshteck** [comment]
> Apparently I used below to resolve my use-case;
> 
> ```
> parameters:
> 
> - name: branch
>   displayName: Branch
>   type: string
>   default: ' '
> ```
> 
> ```
> steps:
> - checkout: git://project/repo@${{parameters.branch}}
> ```
> 
> and when you click on run or the build triggers;
> 
> ![image](https://user-images.githubusercontent.com/38374696/129934126-4c1fbd9e-9ed2-465a-9cb2-e1e8f7388cc6.png)
> 
> the code from the respective branch get pulled and worked up on. Hope this helps

Will this work for Github?
