### ISSUE TITLE
Stakeholder can not reorder cards on kanban board

### ISSUE THREAD

**Issue by croban** [MicrosoftDocs/azure-devops-docs#8547]
According to Prerequisites for the Stakeholder must be possible to move cards per drag&drop.
> You must be granted Stakeholder access or higher

Sadly but that is NOT TRUE. 
There is also an Uservoice https://developercommunity.visualstudio.com/idea/365539/allow-stakeholders-to-drag-and-drop-work-items.html

Can you please change Prerequisites or fix the bug/issue inside DevOps. 
FYI: This feature is only feature where a person gets "sense of achievement" when the WIT is moved to DONE. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e4d857-367f-7c57-f395-d872022f3214
* Version Independent ID: a18efd77-c3ed-0f3d-3635-aab551deb98c
* Content: [Set Kanban board card reordering - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/reorder-cards?view=azure-devops)
* Content Source: [docs/boards/boards/reorder-cards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/boards/reorder-cards.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by alsulli** [comment]
@croban You're correct. At the time of writing this seems to be incorrect. With that being said, per this doc: https://devblogs.microsoft.com/devops/azure-boards-summer-update/

The Boards team is currently working on changing this behavior in the upcoming sprints, so hopefully within the next few months.

**Comment by alsulli** [comment]
@croban This release notes doc shares that this is now in private preview. If you would like to enroll in the private preview there is a link to email the engineering team, please provide your DevOps org(s) in that email that you would like to be in the private preview.

If not, this should roll out to GA in the coming months (don't have an official time frame on that).

@msebolt @KathrynEE feel free to close this off, I don't think I have the authority to do so.

**Comment by KathrynEE** [comment]
@croban, @alsulli - I'll update the article to reflect what is true today, and update it later once the feature is GA and comes out of private preview.
