### ISSUE TITLE
From the Modeling tab, choose Sort by Column and then select the State Sort Order field.

### ISSUE THREAD

**Issue by farinhate** [MicrosoftDocs/azure-devops-docs#8550]
From the Modeling tab, choose Sort by Column and then select the State Sort Order field.

Add State Sort Order section, Step4. needs to be changed to From the Column Tools tab (Data view), choose Sort by Column and then select the State Sort Order field. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c046b7-9bc7-2b63-9401-72af0e1a577e
* Version Independent ID: d9d85ca9-74ba-63bd-0edf-8f95754d4991
* Content: [Add a time-in-state measure to a Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report?view=azure-devops)
* Content Source: [docs/report/powerbi/create-timeinstate-report.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/create-timeinstate-report.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@farinhate - Thank you for the feedback. I'll update the article later today.
