### ISSUE TITLE
API for pool settings

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/azure-devops-docs#8551]
Can the settings for `Maximum number of virtual machines in the scale set` and `Number of agents to keep on standby` be updated using the REST API? I want to set the number of standby agents to 0 at nights and weekends.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-a-virtual-machine-scale-set-agent-pool)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by hbuckle** [comment]
I can't see anything in the REST API docs, hence asking here, as a lot of the APIs in Azure DevOps seem to be undocumented.
Also, your own blog post says to [leave feedback on the documentation page](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-170-update#preview-of-scale-set-agents)?

**Comment by sean-redmond** [comment]
This feature would be really useful, I can see a demand for scale up at 8AM and scale down at 6PM during working days etc, if there is an API for this we can just run a call to the API at these times as needed.

**Comment by msebolt** [comment]
I can re-open the issue if an inquiry is made to the community as a reference to a change needed in the doc set.

Otherwise this remains a product issue unfortunately.

**Comment by fluxmunki** [comment]
FYI this is possible now.
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/elasticpools/update?view=azure-devops-rest-6.1
You can do a REST call to update setting desiredIdle

**Comment by litan1106** [comment]
@fluxmunki thanks for the link. we need to setup auto scale up before the workday and scale down the standby agents too.
