### ISSUE TITLE
Explanation of "named parameters" for arguments input

### ISSUE THREAD

**Issue by tylerwengerd-cr** [MicrosoftDocs/azure-devops-docs#8553]
The documentation for the `arguments:` input for the `bash` task is as follows:

> (Optional) Arguments passed to the Bash script. Arguments passed to the shell script. Either ordinal parameters or named parameters

I understand that **ordinal** parameters would be parsed by the bash script as `$1`, `$2`, etc., but what is meant by **named** parameters? 

I assume this might mean passing in something like `environment="dev"`, but as far as I know bash doesn't support this type of argument natively - I would normally use environment variables with the `env:` input for that, or would have to write extra logic into the script.

Can you clarify how named parameters are supported or expected to be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Whoops. Looks like a copy-paste from some other task that definitely doesn't belong. Thanks!
