### ISSUE TITLE
The file name restrictions are incorrect

### ISSUE THREAD

**Issue by wygoodin** [MicrosoftDocs/azure-devops-docs#8557]
Either the file name restrictions are incorrectly documented or there is a bug in the wiki page rendering. When I named a page/folder "App Authoring", the page failed to render, and mentioned that it was probably due to title. When I renamed it to "AppAuthoring", it started to work. I gather from this that spaces are not allowed in page titles, which isn't listed in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki files, structure, and conventions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by wygoodin** [comment]
(It does mention that it's a convention to have dashes for spaces, but doesn't mention that that is a strict requirement)

**Comment by msebolt** [comment]
@wygoodin  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
