### ISSUE TITLE
What is a Privacy URL?

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/azure-devops-docs#8560]
I was in the settings for an organisation in Azure DevOps. There is a field there titled "Privacy URL", I've no idea what a privacy URL is. Under the field in the settings page is a link titled "Learn more about the Privacy URL", this links to this page. This page simply tells me to enter the URL in the box that I was just looking at.

Having read the page I don't feel I've learned the fundamental thing which is: What is a Privacy URL? I can see how to set it, but why would I want to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8633dcca-a842-9a00-a5c1-5a86ad9f31e5
* Version Independent ID: 11207fe4-0a68-b988-3ea3-582cd6a527a1
* Content: [Add privacy policy URL to comply with the GDPR - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-privacy-policy-url?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-privacy-policy-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-privacy-policy-url.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @martingbrown, Thanks for your feedback. I've updated the article to include the following (will be live today): 

"A privacy policy is a legal requirement for all websites and apps that collect or use personal data from users. In this article, learn how to add your privacy policy URL to your organization in Azure DevOps for public projects. Your privacy policy URL links to the document that describes how you handle both internal and external guest data privacy."

Please @mention me if you have any further suggestions, thanks!

Thanks,
Chrystal

**Comment by martingbrown** [comment]
So does that mean if we leave it blank we just get a default Microsoft privacy policy?

**Comment by chcomley** [comment]
@martingbrown, The MS Privacy Statement is displayed throughout the Azure DevOps product. 

If an organization wants to display their custom Privacy Statement link, they can update this field in Azure DevOps. This is the only place/location where the new Privacy Statement link is displayed, i.e. it doesn’t replace the MS Privacy Statement.
