### ISSUE TITLE
Multi-stage pipelines option not available in user Preview Features

### ISSUE THREAD

**Issue by jitendra-25** [MicrosoftDocs/azure-devops-docs#8561]
Azure DevOps documentation mentions Multi-stage pipeline preview feature for user, however when I create a new project and go to Preview Feature options for logged in user I cannot see the Muti-stage pipelines option.
Is this option not available anymore? 
Can you please point me to the documentation related to Multi-staged pipeline feature and how to enable/disable it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jitendra-25 - Thank you for your inquiry. This preview feature is now generally available, so it has been removed from the Preview features list.  You can learn more from this blog post: https://devblogs.microsoft.com/devops/announcing-general-availability-of-azure-pipelines-yaml-cd/, and this article: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml.
