### ISSUE TITLE
Please update for version 3 of the task (AzureResourceManagerTemplateDeploymentV3)

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#8562]
Currently, the page shows the parameters and description for `AzureResourceGroupDeployment@2`, however, there is a **more recent version available** (although the task name was changed).
It's now called: `AzureResourceManagerTemplateDeploymentV3`.

The new task can be found here: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3

Lets updated this page to reflect this change.

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4bb5b-30b2-bb87-5a4d-d1fd4f8b9860
* Version Independent ID: aba4f40c-5b1d-404e-7594-aa8887ad5ce5
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
That version of the task has not been released, and is not available for use in Azure DevOps Services. The latest version is still 2, as covered in our new task reference:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops#troubleshooting

As soon as (or if/when) v2 is released, the documentation will appear in the task reference.

You can file an issue here to see if there are any updates as to when the v3 will be released: https://github.com/microsoft/azure-pipelines-tasks/
