### ISSUE TITLE
Docs Page is missing GitHub issues at the bottom

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#8563]
Dear docs team!

The [Azure DevOps features pipeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline) page seems to be [part of this repo](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/release-notes/features-timeline.md), but it's missing the usual GitHub issues at the bottom making it harder to report issues.

Thanks! :)
--Neno

**Comment by Sid-ah** [comment]
Github issues is an unofficial place to report issues for pipelines. Stackoverflow and Developer Community for Azure DevOps are the official channels.

**Comment by NenoLoje** [comment]
@Sid-ah This is not about issues for pipelines, this is about reporting docs issues. Most pages show an "Edit on GitHub" page and the current issues at the bottom of the page. This docs.microsoft.com is missing these.
