### ISSUE TITLE
Warn not to migrate history before I complete the steps

### ISSUE THREAD

**Issue by artemious7** [MicrosoftDocs/azure-devops-docs#8565]
First I have completed the steps to import the repository, and only then I got to the warning that migrating history is not recommended. I'd like to see the warning on the corresponding step

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24126ce-abfc-07d0-ceea-51534f745e55
* Version Independent ID: 60861ae7-4b6d-e360-8ab7-28b276326569
* Content: [Import repositories from TFVC to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-tfvc?view=azure-devops)
* Content Source: [docs/repos/git/import-from-TFVC.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-from-TFVC.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **atinb**

**Comment by msebolt** [comment]
@artemious7 Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
