### ISSUE TITLE
The import as CSv query is missing in DevOps since the weekend update. 

### ISSUE THREAD

**Issue by jessOSTC** [MicrosoftDocs/azure-devops-docs#8567]
Since the weekend update to Queries, the bulk import of work items as csv seems to be missing. We are trying to migrate our boards to a new project on a new server and seem unable to do so. Please update the article to confirm how this is now to be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jessOSTC Thank you for the feedback, assigning this to the author for further review.

If this is a confirmed product-related issue, please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

**Comment by KathrynEE** [comment]
@jessOSTC - Please check that you are on the Queries page, not a query Result or Editor page. If it isn't  appearing, and you are using Azure DevOps Services, then you should report a bug.

**Comment by jessOSTC** [comment]
Thanks @KathrynEE the button doesn't appear anywhere. I assumed it was due to the queries update and removed deliberately/ moved somewhere else.
