### ISSUE TITLE
The "Build Timeline" page no longer exists, or if it does, I cant find anything that looks like it

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8569]
This is all I see in regards to code coverage for a build
![image](https://user-images.githubusercontent.com/15381181/84033841-7f425280-a967-11ea-9568-4b4c3c4f08f8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbd5e2-993f-89da-665f-f39ab63d7c42
* Version Independent ID: 493c2582-69a4-1bbe-03b5-0bb5f1d41aed
* Content: [Review code coverage - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/test/review-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinodjo
* Microsoft Alias: **vinojos**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback, this issue was previously reported [here](https://developercommunityapi.westus.cloudapp.azure.com/content/problem/778450/code-coverage-is-not-showing-in-vso-azure-devops-u.html).

Please see if this resolves the issue, otherwise use *Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit help from the product team.

**Comment by StingyJack** [comment]
@msebolt  I don't think I understand. Is this docs page needing an update?

**Comment by msebolt** [comment]
@StingyJack Apologies for the confusion.

The page in question now reflects the screenshot posted above.

**Comment by StingyJack** [comment]
@msebolt the docs page still says I can view the summary, which is what I actually want to do. Is that really possible or is it now a download only thing?

**Comment by msebolt** [comment]
It was the **Build Timeline** feature that is no longer mentioned.

The Summary tab should still be available, can you provide a screenshot showing the discrepancy?
