### ISSUE TITLE
Missing Backslash

### ISSUE THREAD

**Issue by jordykrul** [MicrosoftDocs/azure-devops-docs#8570]
`**\bin** copies all files recursively from any bin folder ` should be `**\bin\** copies all files recursively from any bin folder `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c142b-869c-0f14-d67e-65e9e5c9c141
* Version Independent ID: b5e1ee58-4e89-255b-bb06-921955e1b9e9
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml#open-source)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thank you. A bad search-and-replace has bitten us over and over and over again, and this was another victim. Fixing.
