### ISSUE TITLE
Using the id of the variable group

### ISSUE THREAD

**Issue by snaquekiller** [MicrosoftDocs/azure-devops-docs#8573]
Hi,
i already use variable group. But i edit the name of the variable group in azure devops, i have to edit the name in all my project and yml pipeline. 
I would to know if you can refer a variable group by is Id and not is name.

Thanks :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by snaquekiller** [comment]
hi anybody know ? 
i will certainlky create a suggest feature so .

**Comment by msebolt** [comment]
@snaquekiller Thank you for the question.

You will need to create your own id variable under the `variables` parameter, see [here](https://docs.microsoft.com/cli/azure/ext/azure-devops/pipelines/variable-group?view=azure-cli-latest#ext-azure-devops-az-pipelines-variable-group-create). 

To request this be added as a feature, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.
