### ISSUE TITLE
Copy output

### ISSUE THREAD

**Issue by otofoto** [MicrosoftDocs/azure-devops-docs#8574]
> > Copy output
> 
> To copy the results of the build to Azure Pipelines or TFS, perform these steps:
> 
>     Click the Copy Files task. Specify the following arguments:

There is no such task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d36368-d41a-a377-2db2-556425c30173
* Version Independent ID: 600e6641-27f8-74dd-2f34-c79dc9813887
* Content: [Build C++ Windows apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=tfs-2018)
* Content Source: [docs/pipelines/apps/windows/cpp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/windows/cpp.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Adding a link to the task.
