### ISSUE TITLE
No discussion of authentication when driving Azure Machine Learning from Pipelines

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-docs#8579]
I am currently building a machine learning model using an Azure DevOps Pipeline.

I wish to migrate the training and evaluation of the model to Azure Machine Learning ("AML").

Nearly all documentation for AML assumes non-production use cases, with seemingly random excerpts of Python being executed without any source control, unit testing, static analysis etc..

Some useful documentation is provided by the example code in this project:
https://github.com/MicrosoftDocs/pipelines-azureml

However, when any script is submitted to AML (as per the example code) it will immediately encounter authentication errors.

Separately, there is discussion of creating an Active Directory service principal for AML here:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication

However, there is no discussion of how credentials should be (or even if they _can_ be) passed to AML from an Azure DevOps Pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa0194a9-ffa7-fa79-e6c7-8ecb5e8c93ec
* Version Independent ID: 4f5a9f04-b629-b8b1-1332-9260c95d13b7
* Content: [Azure Machine Learning training and deployment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-machine-learning?context=azure%2Fmachine-learning%2Fcontext%2Fml-context&view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-machine-learning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-machine-learning.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by juliakm** [comment]
The new version of the article addresses authentication.
