### ISSUE TITLE
OData Query Incomplete

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/azure-devops-docs#8580]
Area, and AssignedTo are not included into OData Query, you need to add
$extend=Area($select=AreaPath),Iteration($select=IterationPath),AssignedTo($select=UserName)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c5c777-f210-44b2-8269-0deeea02df9d
* Version Independent ID: a180a164-3ab7-00c7-b525-faff55f3d55f
* Content: [Use OData queries to generate Power BI reports - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-odata-overview?view=azure-devops)
* Content Source: [docs/report/powerbi/sample-odata-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-odata-overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ksmis-gh** [comment]
@RiadKatby  the documentation provides an example for filtering and not for grouping in the document. Can you confirm that this is the document which has the error?

**Comment by ksmis-gh** [comment]
@RiadKatby can you please detail what example what you were talking about

**Comment by ksmis-gh** [comment]
@KathrynEE @RiadKatby Should we close this issue?

**Comment by KathrynEE** [comment]
@RiadKatby - We're closing this issue due to lack of details as to which example you are inquirying about. If you can provide more details, please feel free to reopen this issuue.
