### ISSUE TITLE
Client address is not authorized and caller is not a trusted service. Client address: 40.74.28.0

### ISSUE THREAD

**Issue by ardacetinkaya** [MicrosoftDocs/azure-devops-docs#8581]
In my variable groups in Azure DevOps, I am using an Azure KeyVault to access secret values(secrets) even if all my service connections, permissions and access policies are valid, in variable groups I can not access the key vault.

> The specified Azure service connection needs to have "Get, List" secret management permissions on the selected key vault. Click "Authorize" to enable Azure Pipelines to set these permissions or manage secret permissions in the Azure portal.

Also in Azure KeyVault's networks restrictions all Azure DevOps IP(s) mentioned in doc. is added. By the way 'Allow trusted Microsoft services to bypass this firewall' is YES in my configuration.

So when I click "Authorize" in Azure DevOps Variable groups from UI, I got meaningless error

```
TF400898: An Internal Error Occurred. Activity Id: abc0000.......
```
I dig a little bit; and from browser's developer tool, I checked all responses. One response which is 200 OK caught my attention.

> {
   .......
   ....
   "statusCode":"forbidden",
   "errorMessage":"Failed to query service connection API: 'https://XXXXXXXXXXXXXXX.vault.azure.net/secrets?maxresults=1&api-version=2016-10-01'. Status Code: 'Forbidden', Response from server: '{\"error\":{\"code\":\"Forbidden\",\"message\":\"Client address is not authorized and caller is not a trusted service.\\r\\nClient address: **40.74.28.0**\\r\\nCaller: appid=..........................",\"innererror\":{\"code\":\"ForbiddenByFirewall\"}}}'"
}

The IP **40.74.28.0** seems the be new thing for me. So I added it into my Azure KeyVault's network restrictions.

And everything works as expected. When I check 40.74.28.0, I see that it is an IP from "Regional Identity Service - West Europe" for TFS to Azure DevOps import processes.

It would be nice if all IP rules and restrictions are described and updated as they should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by chcomley** [comment]
Hi @ardacetinkaya, Thanks for posting. I've reached out to the PM for some clarity and will be in touch.

**Comment by chcomley** [comment]
@ardacetinkaya, our PM would like to contact you...can you please provide your email address?

**Comment by ardacetinkaya** [comment]
Sure, [ardacetinkaya at gmail com]

**Comment by chcomley** [comment]
Hi @ardacetinkaya, I've passed your information onto our PM, who should be in contact with you shortly, if not already. Since we've taken this offline, I'm going to close this issue, however if you have any further questions or need any further engagement, I'm happy to help, so please @mention me. Thank you!

**Comment by nikhil0499** [comment]
Hi @chcomley , Good Day ! Will you be able to help me on this . since I am facing this similar issue.
Thanks ,
Nikhil

**Comment by nikhil0499** [comment]
Hi @chcomley, please find my email address.
nikhilarshath@gmail.com

Thanks,
Nikhil

**Comment by chcomley** [comment]
Hi @nikhil0499, I'm sorry for any confusion, but it's no longer possible for that PM to contact you. If you've added all the necessary IPs to the AKV allow list as mentioned in the article and you're still getting an error, then please create a support case.  Go here: https://developercommunity.visualstudio.com/AzureDevOps, and then select **Report a Problem**. Thank you.
