### ISSUE TITLE
I get an invalid request when getting new access token using refresh token.

### ISSUE THREAD

**Issue by MathewsNyirongo** [MicrosoftDocs/azure-devops-docs#8583]
I've been trying to get a new access token using a refresh token and this is the response I always get 

<code>
{
    "Error": "invalid_request",
    "ErrorDescription": "The access token is not valid"
}
</code>

I get the authcode using <code>
https://app.vssps.visualstudio.com/oauth2/authorize?client_id={my_client_id}&response_type=Assertion&state=active&scope=vso.project_manage%20vso.wiki_write%20vso.work_full&redirect_uri={callback_uri}</code>

I must mention that the browser is able to give me an authcode but gives a response saying
"Web page not found at {calback_uri}?code={authcode}&state=active"
</br>

I am able to use the authcode to get an access token with a refresh token using the endpoint <code>
https://app.vssps.visualstudio.com/oauth2/token
</code>
I am able to use the token throughout its life time. When the token expires, I call the endpoint <code>
https://app.vssps.visualstudio.com/oauth2/token
</code> to get a new access token. But then I am faced with the error above.
Please help!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MathewsNyirongo, Thanks for reaching out. It looks like this is an issue for Support. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem** > **Azure DevOps**. Since this isn't directly related to the article, I'm closing this issue, however please @mention me if you have any further questions about the article. Thank you!

**Comment by rguliaev** [comment]
Hi @MathewsNyirongo, I'm facing the same error, did you find a solution?

**Comment by courtzzz** [comment]
We are having the same issue - every time we request a refresh token we are met with:

"The access token is not valid". However during the initial request for access token and refresh using the code everything works fine?!
