### ISSUE TITLE
Post stage/environment approval

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8584]
In classic mode we had very useful feature - post stage approving. For example two different people are responsible for release: first for dev and test stages, second for production. If we deploy release to test and find a bug we have to cancel this deployment process. But second person doesn't know about it. He just see "approval" request for his stage/environment. He is ready to deploy and approve pipeline. This is simplest scenarios. Of cause real life pipelines more complicated and we want to have ability to "confirm" that build is ready to moving next stage.

How to make this in yaml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by msebolt** [comment]
@VerdonTrigance Thank you for the feedback.

This issue is currently being discussed in https://github.com/MicrosoftDocs/azure-devops-docs/issues/4497.  Please refer there for this issue's current status.

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance Thank you for the feedback.
> 
> This issue is currently being discussed in #4497. Please refer there for this issue's current status.

It's not about post stage approvals but ordinary pre-environment approvals. This is not solving my problem :(
