### ISSUE TITLE
Please compare and contrast with Azure App Service Deploy task

### ISSUE THREAD

**Issue by TheRealDuckboy** [MicrosoftDocs/azure-devops-docs#8586]
This task appears to be quite similar to the [Azure App Service Deploy task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops). Some discussion on why there are two similar tasks, and when one would use this over the other, would be most welcome, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@TheRealDuckboy Thank you for the feedback.

This issue has been previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/7614.

Please refer there for further updates.
