### ISSUE TITLE
No information about how to use 'package' resources

### ISSUE THREAD

**Issue by arlosi** [MicrosoftDocs/azure-devops-docs#8589]
I would like to consume packages as resources in my pipeline, but the documentation does not say how the `packages` resource type works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by AdrianSanguineti** [comment]
Possible duplicate of #7861?

**Comment by arlosi** [comment]
Yep, looks like it.
