### ISSUE TITLE
Undocumented IP addresses required for South UK

### ISSUE THREAD

**Issue by BlackstarSolar** [MicrosoftDocs/azure-devops-docs#8593]
When running `migrator.exe import /importfile:'import.json'` against South UK the following IP addresses are reported as required but are not doucumented on this page:

- 51.105.8.98
- 51.104.26.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#import-large-collections)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BlackstarSolar - Thank you for the correction. I'm updating the article to include the IP addresses.
