### ISSUE TITLE
No Prerequisites section

### ISSUE THREAD

**Issue by Kasikka-MS** [MicrosoftDocs/azure-devops-docs#8599]
Hello Team,

Shouldn't this documentation consist of a 'Prerequisites' section mentioning the permissions needed to delete a project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Kasikka-MS, Thanks for your feedback, you're absolutely right! I've created a user story to address this on my backlog. Thanks again.
