### ISSUE TITLE
User Policy "allow team and project ... invite new users" removed?

### ISSUE THREAD

**Issue by aestrad** [MicrosoftDocs/azure-devops-docs#8600]
I am a Project Collection Administrator with all the permissions enabled, including 
the  Manage enterprise policies and don't see the option "Allow team and project administrators to invite new users"

Is this policy enabled? depends on something like additional permissions? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca95db11-932f-d0e9-c240-8ad7c8c349fc
* Version Independent ID: d47e5df1-d313-9191-a280-3020fc713c4d
* Content: [Restrict Team and Project administrators from inviting new users - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/restrict-invitations?view=azure-devops)
* Content Source: [docs/organizations/security/restrict-invitations.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/restrict-invitations.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @aestrad, Thanks for reaching out. I'm looking into this and will be in touch soon.

**Comment by chcomley** [comment]
Hi @aestrad, I spoke with my PM and they told me that this feature hasn't fully rolled out yet, but you should see it within a few days! Thank you! I'm closing this issue, however please @mention me if you have any further questions! Thanks!
