### ISSUE TITLE
URL to ADO Service Connection is wrong

### ISSUE THREAD

**Issue by OliCSADoerr** [MicrosoftDocs/azure-devops-docs#8602]
The URL to the service connections is not correct. The following is the correct one:

https://dev.azure.com/{organization}/{project}/_settings/adminservices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml&source=docs)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by vtbassmatt** [comment]
This is correct.

**Comment by msebolt** [comment]
@vtbassmatt Are you referring to the current documentation or the proposed change?

**Comment by vtbassmatt** [comment]
Ha, sorry. The proposed change.
