### ISSUE TITLE
Examples mixed up

### ISSUE THREAD

**Issue by f7a6875** [MicrosoftDocs/azure-devops-docs#8603]
Fairly certain the examples for "The following example merges changeset 137 into branch2." and "The following example merges all the changesets up to changeset 137 into branch2." have been switched.  This should be the correct way: 

The following example merges changeset 137 into branch2.
c:\projects>tf merge /version:C137 branch1 branch2 /recursive

The following example merges all the changesets up to changeset 137 into branch2.
c:\projects>tf merge /version:C137~C137 branch1 branch2 /recursive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2a034e-46b4-0c59-9cc1-b34a199383c9
* Version Independent ID: 7022c4b2-7011-5cdc-1b57-f2ee3b594bdc
* Content: [Merge Command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/merge-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/merge-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/merge-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by RuslanRasulovAkv** [comment]
#reassign @RuslanRasulovAkv

**Comment by Abu441** [comment]
Abu Abed

**Comment by IlyaChistov** [comment]
#reassign @IlyaChistov

**Comment by MaximMalygin** [comment]
@msebolt could you please close it, Ilya fixed it in PR
