### ISSUE TITLE
Wrong Azure CLI command in scale set agents documentation

### ISSUE THREAD

**Issue by JoshuaBaunach** [MicrosoftDocs/azure-devops-docs#8605]
In [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#how-do-i-create-a-scale-set-with-custom-software-and-custom-disk-size) of the scale set agent docs, there is this snippet of Azure cli:

`az vm shutdown --resource-group <myResourceGroup> --name <MyVM>`

"az vm shutdown" does not exist. It might be "az vm stop" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This is fixed in https://github.com/MicrosoftDocs/azure-devops-docs/pull/8931, thank you for letting us know.
