### ISSUE TITLE
"Bearer" didn't work, but "basic" does, for personal access tokens

### ISSUE THREAD

**Issue by joshlang** [MicrosoftDocs/azure-devops-docs#8606]
The docs state:
```
git -c http.https://<url of submodule repository>.extraheader="AUTHORIZATION: Bearer <BASE64_ENCODED_STRING>" submodule update --init --recursive
```

But I was getting `400` access denied errors

Then I found https://stackoverflow.com/questions/51052720/how-to-authenticate-to-a-private-github-submodule-in-a-vsts-automated-build and it referenced the same command, but with `basic` instead of `Bearer`

This worked for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
This has been fixed in the docs. Thanks for bringing this to our notice.
