### ISSUE TITLE
System.PullRequest.PullRequestId says it's not available in YAML, but it seems to work (fortunately)

### ISSUE THREAD

**Issue by ScotSalmon** [MicrosoftDocs/azure-devops-docs#8610]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml says (bold added):
> System.PullRequest.PullRequestId | The ID of the pull request that caused this build. For example: 17. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy). **This variable is not available to be used in YAML.**

Fortunately, the bolded part doesn't seem to true. This variable does work in YAML. If it didn't, I'm not sure how I'd get the PR ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ScotSalmon You are right and I will update this shortly. Thanks!
