### ISSUE TITLE
SourceLink indexing portable pdb authenticated feed

### ISSUE THREAD

**Issue by czb182** [MicrosoftDocs/azure-devops-docs#8612]
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops#q-can-i-use-source-indexing-on-a-portable-pdb-file-created-from-a-net-core-assembly

2nd FAQ questions mentions that sourcelink does not support authenticate feeds, so shouldnt use for source indexing of portable pdb's.  On SourceLink repo, it mentions authenticated repos are support from VS 15.7+.  

https://github.com/dotnet/sourcelink#source-link

I think these are referencing the same thing, so should this doc be updated to say you can use, as long as you consume using VS 15.7+?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@czb182 Thank you for your feedback. Source indexing and sourceLink are not the same thing. Source indexing is the the process of adding a symbol to a symbol server file share. For example:
`"c:\Program Files\Debugging Tools for Windows\symstore" add /f "C:\myapp\etc\symbols\*.pdb"
/s \\symbolServer\symbols /t "adding myapp symbols to symbolServer" /r`
