### ISSUE TITLE
Add an Azure web app to an environment

### ISSUE THREAD

**Issue by Sergey-Nosov-GH** [MicrosoftDocs/azure-devops-docs#8614]
Hi, the 02/10/2020 edition of this document mentions that environments can include Azure web apps. How do you add an Azure web app to an environment? I can only see options to add Kubernetes and Virtual machines. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Sergey-Nosov-GH Thank you for the question.

Unfortunately, only Kubernetes and VMs are supported, refer to [this post](https://developercommunity.visualstudio.com/content/problem/992198/how-do-i-add-web-apps-to-a-pipeline-environment.html).

Additional environments such as Docker Swarm have been suggested, see [here](https://developercommunity.visualstudio.com/idea/684038/environment-support-for-docker-swarm.html).

The documentation has been updated and is pending review.
