### ISSUE TITLE
"Define Variables - Azure Pipelines" typo

### ISSUE THREAD

**Issue by srmagura** [MicrosoftDocs/azure-devops-docs#8617]
In the system variables section:

"As a pipeline author or end user, you change the value of a system variable.

System variables are read-only."

I assume it should say you CANNOT change the value of a system variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@srmagura Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The issue was previously noted, see https://github.com/MicrosoftDocs/azure-devops-docs/issues/8527 with a fix is pending.
