### ISSUE TITLE
Confusion regarding publishing/consumption of build and pipeline artifacts

### ISSUE THREAD

**Issue by PawelWMS** [MicrosoftDocs/azure-devops-docs#8620]
[Enter feedback here]

In the `Migrating from build artifacts` section you suggest that "pipeline artifacts are the next generation of build artifacts and mention that it's completely acceptable to download build artifacts through the `PublishPipelineArtifacts` task. However, when I use `DownloadPipelineArtifacts` to download artifacts published in a previous build through `PublishPipelineArtifacts` I get the following warning in my build logs:

```
##[warning]Please use Download Build Artifact task for downloading Build Artifact type artifact. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops
```

This is somewhat confusing and I'm not sure in that case what's the most up-to-date way of publishing and consuming artifacts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml&source=docs#publishing-artifacts)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@PawelWMS Thank you for the feedback.

This is issue is known to occur when using the `PublishBuildArtifacts` alongside the `DownloadPipelineArtifacts` task.

Please be sure to use the `PublishPipelineArtifacts` task and clear away all previous artifacts before attempting to republish/download your artifacts.

If the issue persists, please start a ticket with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.
