### ISSUE TITLE
Azure Devops server: No "pool" support at pipeline/stage level

### ISSUE THREAD

**Issue by WYarde** [MicrosoftDocs/azure-devops-docs#8623]
The documentation for Azure Devops Server 2019 states: 

```You can specify a pool at the pipeline, stage, or job level. The pool specified at the lowest level of the hierarchy is used to run the job.```

This seems to be incorrect.
- The concept of a stage doesn't exist in this version of the product
- When I define a pool at the pipeline level, it does not work unless there's only 1 job in the pipeline

Could you update the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@WYarde Thank you for the feedback, the documentation has been updated and is pending review.

For issues regarding jobs within the pool, please solicit feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
@WYarde We are making further updates to our documentation to clarify this, here is a summary:

* Azure DevOps Server 2019 - YAML pipeline support but no support for stages
* Azure DevOps Server 2019.1 - YAML support with stages, but pool can only be set at job level in the YAML, and at pipeline root level only in the pipeline settings UI
* Azure DevOps Server 2020 - YAML support with stages, and pool can be set in YAML at pipeline root, stage level, and job level, and in the pipeline settings UI at root level
* Azure DevOps Services - YAML support with stages, and pool can be set in YAML at pipeline root, stage level, and job level, and in the pipeline settings UI at root level

**Comment by WYarde** [comment]
Thanks for picking this up
