### ISSUE TITLE
Change Approval

### ISSUE THREAD

**Issue by SpencerK369** [MicrosoftDocs/azure-devops-docs#8625]
I feel there should be an option when approving/rejecting code reviews to change our approval status. For example I recently finished my review with suggestions and now I cannot go back and select to finish with approval after my comments have been addressed. Under my review it still says "Finished (With Comments)" but I want it to now say "Approved". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bb12a7-a20c-1dd5-bca0-4873f7ab9e36
* Version Independent ID: 360739fd-e98a-535f-9872-ed58ece28194
* Content: [Get your code reviewed with Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=azure-devops)
* Content Source: [docs/repos/tfvc/get-code-reviewed-vs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/get-code-reviewed-vs.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@SpencerK369 Thank you for the feedback, all feature requests are highly appreciated.

Unfortunately our support options are limited to documentation only.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to for guidance from the product team on having this added to the [features timeline](https://docs.microsoft.com/azure/devops/release-notes/features-timeline).

**Comment by SpencerK369** [comment]
@msebolt Thank you for the update.
