### ISSUE TITLE
State permission needed to Change individual or group permissions

### ISSUE THREAD

**Issue by djeec** [MicrosoftDocs/azure-devops-docs#8626]
In the page, it would be helpful to state what permissions are necessary to actually be able to change individual or group permissions.

e.g. You must be a member of XYZ to be able to change individual or group permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7810e46d-34ea-8bdf-4607-d295e23507e2
* Version Independent ID: 7637659b-3807-5689-3225-b2bcca5b0fc8
* Content: [Change individual or group permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/change-individual-permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/change-individual-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/change-individual-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@djeec - Thank you for your feedback. I'm updating the article per your request.
