### ISSUE TITLE
How are tags used for deployment filtering?

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-devops-docs#8629]
I can't find any info about this on this page or the YAML schema page.  How are multiple tags interpreted when filtering for a deployment?  If I specify my deployment environment with tags `tag1` and `tag2`, will it target all VMs that have *EITHER* of `tag1` or `tag2`, or will it only target machines that have both tags applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by FISHMANPET** [comment]
I see this has already been asked as #8202 but the list of issues referencing this specific page don't seem to be loading on the pages themselves.

**Comment by ISAF87** [comment]
Hi, We would like to add multiple tags to determine which machien to deploy to. But we can't even seem to add that:

environment:
      name: 'TEST'
      resourceType: VirtualMachine
      tags: [APP, TEST] => Unexpected type: Expected "string"
      
 Other ways we tried for completeness:
 tags: |
APP
TESTING

tags: ['APP','TESTING']

tags:
- APP
- TESTING

tags: 'APP, TESTING'

In our case, we would like the target VM have both tags
