### ISSUE TITLE
How to specify multiple tags for environment jobs?

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-devops-docs#8630]
This documentation says you can specify an array of tags for an environment deploy, but I can't figure out how to do that.
I've tried these two ways:
```
tags:
  - tag1
  - tag2
```
```
tags: [tag1,tag2]
```
In both cases I got the error `(Line: 76, Col: 15): A sequence was not expected` (Line 76 being where I specified the tag).

Is it actually possible to specify multiple tags?
This is also related to #8629 and #8202, if you can't actually specify multiple tags then the behavior of specifying multiple tags is irrelevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#demands)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@FISHMANPET Thank you for the feedback, we apologize for any inconvenience.

There is a similar issue previously reported with the product team [here](https://developercommunity.visualstudio.com/content/problem/1073745/when-attempting-to-use-more-than-one-tag-to-limit.html).  

If this is not the same, please comment below and/or start a new ticket with the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
