### ISSUE TITLE
The IP Address list for Regional Identity Service - Central United States is incomplete

### ISSUE THREAD

**Issue by veccsolutions** [MicrosoftDocs/azure-devops-docs#8631]
[Enter feedback here]

The IP Address list for Regional Identity Service - Central United States is incomplete. The last entry is probably missing a /24 on it. The missing IP's when trying to do an import (for me at least):

* 20.37.139.247
* 20.37.158.5

I didn't see anything in any of the lists that would have covered the 20.37.139.247 IP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by veccsolutions** [comment]
Tried again and instead of the 20.37.239.247 got 20.27.138.167 in the error.

**Comment by KathrynEE** [comment]
Tracking this with Bug 1765733: Import migrate process from on-premises to Azure DevOps - IP Address list for Regional Identity Service - Central United States is incomplete.

**Comment by KathrynEE** [comment]
@veccsolutions - Thank you for the feedback. I will update the article accordingly.
