### ISSUE TITLE
Container Jobs and self hosted agents

### ISSUE THREAD

**Issue by worldspawn** [MicrosoftDocs/azure-devops-docs#8632]
>You must specify "Hosted Ubuntu 1604" as the pool name in order to run Linux containers. Other pools won't work.

Does that effectively mean I cannot use this feature with a self hosted agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@worldspawn Thank you for the question.

Yes, the container jobs should be distinct from agent jobs, and the only current support for Linux container jobs is using `Ubuntu 16.04`.

The documentation has been updated to remove any confusion with `Red Hat agents` running inside the containers as opposed to actually running the containers.
