### ISSUE TITLE
Sprint burndown on historical charts is real time rather than historical for % completed and Story points remaining.

### ISSUE THREAD

**Issue by grjohnston** [MicrosoftDocs/azure-devops-docs#8635]
When looking at historical data, its clear that the % completion and remaining story points aren't historical but calculated in real-time.  As we move incomplete work to the subsequent sprint, historical reports alwasy show 100% completion and 0 remaining story points.  

I feel this is a bug.  The snapshot should be taken at the end time of the Sprint regardless of subsquent work item movement. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430ccc7-e8ea-d02d-b2e9-33b8138338da
* Version Independent ID: 0c0b7f9a-69fe-3edf-6216-a4784d4cb94b
* Content: [View and configure sprint burndown - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-sprint-burndown?view=azure-devops&tabs=remaining-work%2Cmay)
* Content Source: [docs/report/dashboards/configure-sprint-burndown.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/configure-sprint-burndown.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@grjohnston Thank you for the feedback.

Unfortunately, currently the only way to accomplish this is using [custom OData feeds](https://docs.microsoft.com/azure/devops/report/powerbi/odataquery-connect?view=azure-devops) with a tool like **Power BI**.

For feature requests and/or bugs, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html), see [here](https://developercommunity.visualstudio.com/idea/567877/sprint-historyburndown-log.html), [here](https://developercommunity.visualstudio.com/content/problem/415776/burndown-doesnt-match-total-hours-completedremaini.html), and [here](https://developercommunity.visualstudio.com/content/problem/322669/burndown-in-vsts-based-on-remaining-hours.html) for current examples.
