### ISSUE TITLE
vsts-npm-auth on-premise different screenshots / sections

### ISSUE THREAD

**Issue by lbazetto** [MicrosoftDocs/azure-devops-docs#8641]
I'm using the Azure DevOps Server on-premise.

My current version is:
Azure DevOps Server 2019 Update 1.1 Patch 2
Release Date: April 14, 2020

When I'm trying to connect to feed my view is:
![image](https://user-images.githubusercontent.com/5264906/84786279-70e9db80-afe4-11ea-87b4-e6ab444c48e2.png)

Differently from the Azure DevOps Service, the on-premise doesn't show the `vsts-npm-auth` instructions.
According to issue #5587 the `vsts-npm-auth` doesn't work on-premise.

Is it still a valid issue? If so, should the documentation have this information? Or even hide the section `Set up authentication on your development machine` when choosing `Azure DevOps Server`?

Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bbb17f-15a7-25d6-239c-2087d2b644b7
* Version Independent ID: f4949587-0bd0-6bfc-590f-0c4f6386dd7a
* Content: [Use npm to store JavaScript packages in Azure DevOps Services - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-npm?view=azure-devops-2019&tabs=windows)
* Content Source: [docs/artifacts/get-started-npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-npm.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@lbazetto Thank you for your feedback. Updates will go live shortly
