### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by toetang** [MicrosoftDocs/azure-devops-docs#8642]
There's a small typo on the 4th line "Prior to generating these reports, you must first connect to Analyticss using the Power BI data connector."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc092b-7e31-59c0-148c-6dd2508a9c25
* Version Independent ID: db29bd31-fa3f-b959-0ae7-40213bbfeda9
* Content: [Example reports for Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-examples?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-examples.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/data-connector-examples.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@toetang - Thank you for the correction. I'll update the article as needed.
