### ISSUE TITLE
Is CentOS 8 not supported?

### ISSUE THREAD

**Issue by lurifaxel** [MicrosoftDocs/azure-devops-docs#8647]
I'm surprised to see that CentOS 6 and 7 are supported for self-hosted Linux build agents but CentOs 8 is not! Is that true or is the document perhaps out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@lurifaxel Thank you for the question.

Currently CentOS 8 is only officially supported by [.NET Core](https://docs.microsoft.com/dotnet/core/install/linux-centos) with known issues, see https://github.com/dotnet/core/issues/3751.  **Azure DevOps** users have made recent posts [here](https://developercommunity.visualstudio.com/content/problem/990297/centos-8-dotnet-sdk-dont-provide-the-sdk.html) and [here](https://developercommunity.visualstudio.com/content/problem/1048536/artifact-tool-on-centos-8-unable-to-publish-to-uni.html).

Please use this for development purposes only and we will update the documentation once support is officially announced.

**Comment by sriramdasbalaji** [comment]
Hi,

Is CentOS 8 supported now?

**Comment by WilliamAntonRohm** [comment]
@sriramdasbalaji -- thank you for your question.  Please see [this article](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#supported-distributions), which includes this note:

> Warning

> CentOS 8 reached an early End Of Life (EOL) on December 31st, 2021. For more information, see the official [CentOS Linux EOL page](https://www.centos.org/centos-linux-eol/). Because of this, .NET 6 won't be supported on CentOS Linux 8.
