### ISSUE TITLE
Not clear for all arguments if they are optional and if ommited what the default is

### ISSUE THREAD

**Issue by edwin-hendriks** [MicrosoftDocs/azure-devops-docs#8649]
Not clear for all arguments if they are optional and if ommited what the default is. Could this be added to the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vtbassmatt** [comment]
When someone picks this up to doc, you can use the YAML snippet as your guide. The value listed on the right side of the `:` is the default which the task will use if that input isn't specified.

**Comment by msebolt** [comment]
The documentation has been updated and is pending review.
