### ISSUE TITLE
New Test Plan page is still busted, please don't turn off the old one

### ISSUE THREAD

**Issue by TinMoths** [MicrosoftDocs/azure-devops-docs#8650]
1. Copy/pasting text from this page doesn't work. I can't take text I type in a test case and paste it in another application. It doesn't even copy to the clipboard.

2. Having to switch between the 'Define' and 'Execute' is a pain. Sometimes we do exploratory testing and need to add details/summary as we go - we are literally writing and running the test at the same time. This isn't possible in the New Test Plan view

3. Pasting in grid view: It constantly complains that the target area isn't the right size. It still works, but it complains.
Additionally, there are no options to configure the columns on the grid (that I can see) I'm used to pasting in 4 columns (name, steps, result, tags) but now there's 'assigned to' and 'status'. Status previously defaulted to 'Design' - this is fine. Don't make me spell it out in my Excel file, which is what I'm pasting in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by ShubhamJain1992** [comment]
HI Tin,
Thanks for reaching out to us. Refer to my responses to your queries below:
1. _Copy/pasting text from this page doesn't work. I can't take text I type in a test case and paste it in another application. It doesn't even copy to the clipboard._
- Assuming that you are talking about the Test Case WIT, this is a known limitation. As a workaround we can export the test case to the excel sheet using "Import/Export CSV" and perform the bulk edit and copy paste operations from there.

2. _Having to switch between the 'Define' and 'Execute' is a pain. Sometimes we do exploratory testing and need to add details/summary as we go - we are literally writing and running the test at the same time. This isn't possible in the New Test Plan view_
- Splitting between 'Define' and 'Execute' tab based on persona's is a design decision we have taken for the new test plans page and plan to continue with this experience.

3. _Pasting in grid view: It constantly complains that the target area isn't the right size. It still works, but it complains. 
Additionally, there are no options to configure the columns on the grid (that I can see) I'm used to pasting in 4 columns (name, steps, result, tags) but now there's 'assigned to' and 'status'. Status previously defaulted to 'Design' - this is fine. Don't make me spell it out in my Excel file, which is what I'm pasting in_
Have you tried using the 'Import/Export CSV' feature? This feature allows a user to export the test cases to an excel file and you can make all the operations you need. details [here](https://pkuma-msft.github.io/azure-test-plans/articles/testcase-import-export-csv.html)

Hope it helps.

**Comment by msebolt** [comment]
Closing this issue now, for additional support please use [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.
