### ISSUE TITLE
Link work items to deployments within Azure CICD YAML

### ISSUE THREAD

**Issue by jamiehaywood** [MicrosoftDocs/azure-devops-docs#8651]
Would be great if you could update this documentation to show how we can link to work items in Azure-Pipelines YAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jamiehaywood - Thank you for your feedback. As noted in the article, "The release deployments control currently works with classic release pipelines and with Azure DevOps Services (cloud) only." Support for linking through YAML definitions isn't supported at this time. I recommend that you enter your feature request on our [Developer Community page](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
