### ISSUE TITLE
setting variables from secret variables doesn't fit the current yaml schema

### ISSUE THREAD

**Issue by JasonRitchie** [MicrosoftDocs/azure-devops-docs#8652]
Following the code examples in section https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables "Secret Variables" does not produce working parseable yaml.

The editor and the build process return either "first property must be name" or "Unexpected value" for the line after "variables:" in the yaml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@JasonRitchie For the YAML to work, you need to have the secret variable `mySecret` defined (using the UI). 

![Screen Shot 2020-06-17 at 3 20 50 PM](https://user-images.githubusercontent.com/64906/84940659-2896f000-b0ae-11ea-82b0-d3eefdeec284.png)
