### ISSUE TITLE
Add Documentation for "Generate Deployment Manifest" Task

### ISSUE THREAD

**Issue by jackt-moran** [MicrosoftDocs/azure-devops-docs#8656]
The title summarizes the issue well. The other 3 IoT Edge Tasks have documentation, but Generate Deployment Manifest does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by alevincenzi** [comment]
Hello.
Any update on this? I noticed that this documentation 

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment

includes some details about its usage so i imagine that it is still supported.

**Comment by marianan** [comment]
@jackt-moran thank you for reporting this issue. We are now tracking it in our backlog and will provide updates when available.
