### ISSUE TITLE
Generate Deployment Manifest Task Doesn't Resolve Vars in Module Twins

### ISSUE THREAD

**Issue by jackt-moran** [MicrosoftDocs/azure-devops-docs#8657]
The Generate Deployment Manifest Task does not resolve variables in the module twins within deployment templates passed to the task. For instance, a variable "${EXAMPLE_VAR}" resolves within the $edgeAgent section, such as a module's environment variable, but remains as "${EXAMPLE_VAR}" within the module's module twin section of the deployment manifest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@jackt-moran Thank you for the feedback.

Unfortunately we can only provide support for documentation examples.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team and link back to this issue to allow any changes necessary to be made to the documentation.
