### ISSUE TITLE
Signing and aligning APK file(s) Task v3 - Is there an output file?

### ISSUE THREAD

**Issue by LukaszGrela** [MicrosoftDocs/azure-devops-docs#8661]
I have a task to sign and align APK file, the aligning command is:

```
C:\android_sdk\build-tools\28.0.3\zipalign.exe -v 4 C:\_work\13\s\android\app\build\outputs\apk\release\app-release-unsigned.apk.unaligned C:\_work\13\s\android\app\build\outputs\apk\release\app-release-unsigned.apk
```
then the signing command runs
```
C:\windows\system32\cmd.exe /D /S /C "C:\android_sdk\build-tools\28.0.3\apksigner.bat sign --ks C:\_work\_temp\***.jks --ks-pass pass:*** --ks-key-alias key0 --key-pass pass:*** C:\_work\13\s\android\app\build\outputs\apk\release\app-release-unsigned.apk"
Finishing: Signing and aligning APK file(s)
```

In the `outputs\apk\release` folder there is no `app-release-signed.apk` only `app-release-unsigned.apk` does it mean that signing overrides the file and signed is the file wth `unsigned` in the name? Is there a way to specify signed file name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@LukaszGrela Thank you for the question.

Yes, currently the only way to specify your *.apk* name is passing the value to `apksignerArguments` as the `--out` parameter for [apksigner](https://developer.android.com/studio/command-line/apksigner).

Please move this issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo for further assistance.
