### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by Frederico-Mesquita** [MicrosoftDocs/azure-devops-docs#8664]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0210ea4f-8868-9655-1ab1-74945b7e8928
* Version Independent ID: eff251a3-a947-9a25-ed7d-2f9311e5dc1d
* Content: [Dates in Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-dates?view=azure-devops)
* Content Source: [docs/repos/git/git-dates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-dates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
Adding @apawast for kudos.
