### ISSUE TITLE
Extension Overview Link leads to Azure DevOps home page

### ISSUE THREAD

**Issue by C-Ross** [MicrosoftDocs/azure-devops-docs#8665]
The extension overview link in 1.a. leads me not to anything about extensions but to https://azure.microsoft.com/en-us/services/devops/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46557dc-2e49-b914-105e-9235c7dbf860
* Version Independent ID: 42901bac-88ea-acb6-cf5e-6086b3223a9a
* Content: [Developing extensions for Azure DevOps Services and TFS - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops)
* Content Source: [docs/extend/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @C-Ross, Thanks so much for alerting us! I've published an update, which should be live sometime within the next few hours or so. Thanks again!
