### ISSUE TITLE
Outdated .NET Core Windows Server Hosting bundle for .NET Core 3.1

### ISSUE THREAD

**Issue by marekott** [MicrosoftDocs/azure-devops-docs#8668]
Hi, great article for all newbies. In a section with PowerShell script (https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops#aspnet-core-app) your are pointing to DotNetCore.1.0.0-WindowsHosting.exe which if the app is developed with .NET Core 3.1 is causing: 
```
Internal Server Error Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list 
```

My proposition for a fix is to replace it with ASP.NET Core Runtime 3.1.5 Hosting Bundle which has IIS runtime support (ASP.NET Core Module v2). However, I am not able to find a link to that resource in the format "https://go.microsoft.com/fwlink/?LinkId=XXXXXX". If you could provide me with one, I will be glad to update the script. Direct link for the bundle is https://download.visualstudio.microsoft.com/download/pr/7c30d3a1-f519-4167-b850-b9c49bf2aa0e/dbfa957a76a41a1e1795f59d400d4ccd/dotnet-hosting-3.1.5-win.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1c5394-611b-b119-dbf3-b88404e351d5
* Version Independent ID: fcc23259-21ec-f9fa-4e25-f587e1e0f41b
* Content: [Deploy to IIS on a Windows VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-webdeploy-iis-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
Thanks for the feedback. I'm adding a link to more updated installation instructions.
