### ISSUE TITLE
IoT Edge tasks article missing 'Generate Deployment Manifest' task

### ISSUE THREAD

**Issue by ScarlettFalls** [MicrosoftDocs/azure-devops-docs#8669]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ScarlettFalls** [comment]
Please add the Azure IoT Edge 'Generate Deployment Manifest' task to this article

**Comment by msebolt** [comment]
This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8656.

Please refer there for further updates.
