### ISSUE TITLE
Integration with service hooks - webhook

### ISSUE THREAD

**Issue by IbrahimAbdulwahid** [MicrosoftDocs/azure-devops-docs#8673]
Working on setting up Integration with service hooks and utilize the webhook to send work item changes to external webhook url. How would I send work item attachment data via webhook. if this is not supported, what is the recommended solution ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by msebolt** [comment]
@IbrahimAbdulwahid Thank you for the question.

Please refer to the [WIT Attachment REST](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/attachments/get?view=azure-devops-rest-5.1) documentation which can be triggered with a web hook.

For additional support, please refer to:

-  [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
