### ISSUE TITLE
Business hours doesn't account for Daylight Savings

### ISSUE THREAD

**Issue by lhersman** [MicrosoftDocs/azure-devops-docs#8675]
The Business hours feature is great and we would love to leverage it, however, in testing I just noticed it doesn't account for Daylight Savings.  We are in UTC -6 (Central) and it evaluated our time as if it was UTC -5 because we are currently in DST.  I can account for this and set it to UTC -5, but it is all but assured that when DST ends in November, everything will be off by an hour.  I don't really want to have to set a reminder to change it twice a year on all our environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by msebolt** [comment]
@lhersman Thank you for the feedback.

For new features, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team and then provide the link back to this issue.

From searching through the tickets this issue has not yet been discussed.
