### ISSUE TITLE
misleading categorization - azure devops server 2019 does not support parameters

### ISSUE THREAD

**Issue by dmakvh** [MicrosoftDocs/azure-devops-docs#8677]
The selector in the upper left corner is misleading users - it is possible to select server 2019 but according to https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline it will only be supported in server 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@dmakvh Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by msebolt** [comment]
There might be an issue with the moniker values, need to re-confirm once changes are published.

**Comment by msebolt** [comment]
Changes confirmed, documentation no longer support 2019.  Thank you for your contribution.
