### ISSUE TITLE
Available in templates? for build and system variables missing explanation

### ISSUE THREAD

**Issue by Willem-J-an** [MicrosoftDocs/azure-devops-docs#8678]
The Build and System predefined variables contain a column called: Available in templates?

What does this mean exactly? Does this apply to cross repository templates, or any kind of template? Does this mean only the root pipeline file can mention these variables or wouldn't it work when any template calling is happening? Can I still inject the variable as a parameter into other templates? Et cetera..

I'm noticing some strange behavior with these predefined variables in templates; so I would like to see some clear cut documentation on this. If it's already there in another page, let me know where!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
The column refers to [Pipelines templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops). I'll add a note to make this clearer.

**Comment by Willem-J-an** [comment]
Hi @juliakm,

It was already clear this is about pipeline templates. I think there is no other kind of templates in this context. I'm sorry to say the added link doesn't really answer the questions raised in this issue.
