### ISSUE TITLE
Table of contents in Common service connection types section is wrong

### ISSUE THREAD

**Issue by craigbrown** [MicrosoftDocs/azure-devops-docs#8680]
It looks like the contents table at the beginning of the "Common service connection types" section has been replaced with a table of contents for the entire document which doesn't really make sense in that context, and makes it a bit more difficult to navigate that section. Seems like the change was introduced in commit a7772bf. Was that intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#common-service-connection-types)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
Thanks @craigbrown. Looks like this one has been fixed. Thanks for flagging.
