### ISSUE TITLE
Passing parameters between triggering pipelines

### ISSUE THREAD

**Issue by jiffypopjr** [MicrosoftDocs/azure-devops-docs#8683]
How do I pass (or receive) parameters between pipelines? My triggered pipeline has input parameters that need to be set from the 'build' pipeline that triggers it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@jiffypopjr Thank you for the question.

Currently only static variables are supported, for a good description see [this post](https://stackoverflow.com/questions/62357787/share-variables-across-build-pipelines-in-azure-devops).

For further questions, please solicit feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).  There you'll find a recently posted [work around](https://developercommunity.visualstudio.com/content/problem/701307/use-of-dynamic-variables-in-yaml-pipelines.html).
