### ISSUE TITLE
NuGet instructions folder possibly incorrect

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/azure-devops-docs#8685]
The instructions for setting up NuGet claim that the folder to use for caching is `$(Pipeline.Workspace)/.nuget/packages`, but when we restore the items they appear to be going to `C:\Users\VssAdministrator\.nuget\packages`, which is the user profile of the build agent.

We're using the hosted build images, and the NuGet restore task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
`Pipeline.Workspace` is the local path on the agent running your pipeline where all directories are created. This variable has the same value as `Agent.BuildDirectory`. See [Agent variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services) for details.
