### ISSUE TITLE
This is missing the important bits, the actual code review commentary

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8688]
This does not cover how to get the actual comments and the targets (text spans/files/overall)  for those comments. 

I dont see a linked article here that describes how to get those. There is a [developer community issue ](https://developercommunity.visualstudio.com/content/problem/472858/how-to-fetch-the-comments-added-in-discussion-tab.html)that links to this article and this is right API, but the results I am getting disagree with that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0197b69a-56ae-8cef-88e3-2165b07e23de
* Version Independent ID: 336f8906-e816-48ed-18ff-5ac7a8aa7a76
* Content: [Code review and feedback field reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/guidance-code-review-feedback-field-reference?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - I checked with the product team and they indicated that the actual code review comments are not stored in the work tracking data store but in another place which isn't accessible to the user. You can suggest this as a feature to be supported on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by StingyJack** [comment]
@KathrynEE  - There is already a developer community issue open that links here.   I opened a support request for this in the meantime and learned that there is a planned but unreleased API for this (makes sense, fiddler captured where VS was getting the comments from currently and its still using an old SOAP API).
