### ISSUE TITLE
processes

### ISSUE THREAD

**Issue by VitalikVaseyko** [MicrosoftDocs/azure-devops-docs#8689]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3466d1-72cc-2d47-d98b-7029639c0f79
* Version Independent ID: 4ff82210-6b5a-589d-261e-1ddbd3007e2a
* Content: [Choose a process like Basic, Agile, Scrum, or CMMI - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=basic-process)
* Content Source: [docs/boards/work-items/guidance/choose-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/choose-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@VitalikVaseyko Thank you for contacting Microsoft.

Please describe your issue below and we will direct this to the proper channel.

**Comment by msebolt** [comment]
Closing this issue now.
