### ISSUE TITLE
This page does not list that version control labels that were created by the build will also be deleted when the build is deleted

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8692]
That should be in giant screaming 50pt font, because thats they way that many of us trace the artifact version to the source version that built it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@StingyJack What version of Pipelines are you using? For TFS 2018 and below you can choose to keep a tag when the build is deleted.

**Comment by StingyJack** [comment]
I remember that from TFS, and I think I even remember seeing it in Azure DevOps (currently using).  I dont know on what planet deleting VC labels by default would ever be an OK thing to do. At best it would cause no disruption, but at worst its a **professional nightmare scenario** for anyone needing to make a hotfix that no longer has the VC labels the build applied.  Also having the build system reach into another system to alter or delete data is quite an unexpected thing considering the build pipeline is separate and independent of the version control system.  

The only way to avoid getting in this scenario is to [retain each and every build](https://github.com/StingyJack/AzureDevOps-BuildRetainer/tree/master).

**Comment by juliakm** [comment]
Adding a FAQ question to address this shortly.
