### ISSUE TITLE
publishLocation: pipeline

### ISSUE THREAD

**Issue by davux** [MicrosoftDocs/azure-devops-docs#8693]
Some sources specify `pipeline` as a possible value for `publishLocation`.  However, the documentation doesn't mention that value.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
I believe "pipeline" as a location is referring to the `container` option, which is listed in the task assistant as "Azure Pipelines". The new task reference provides the allowed values for task inputs, including both the YAML name and the task assistant UI name. Here is a link to the inputs for this task, in the new reference:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1?view=azure-pipelines&viewFallbackFrom=azure-devops
