### ISSUE TITLE
Retention policies explaination is confusing 

### ISSUE THREAD

**Issue by Yanal-Yves** [MicrosoftDocs/azure-devops-docs#8697]
The [documentation about retention policies](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven#automatically-delete-old-package-versions-with-retention-policies) is confusing:

1. The doc says "You can also set the number of days to keep recently downloaded packages" but when you activate retention policies a value should be enter. 
2. It's unclear if a package will be deleted if it has not been downloaded for a long time but the number of versions did not reach the **Maximum number of versions per package** threshold.
3. It's unclear if a package will be deleted if a package has been recently downloaded by the number of version has reach the **Maximum number of versions per package** threshold.

I made some quick tests and here is my understanding of the behavior of retention policies

With retention policies, you can configure an automatic deletion of packages. When the retention policies are enabled, a version of a package will be deleted if the number of versions of that package reaches the **maximum number of versions per package threshold** AND if it has not been downloaded within the number of **days to keep recently downloaded packages**.

1. Is my understanding correct ? If not could you clarify what's wrong ?
2. Could you update the doc to avoid confusion ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@Yanal-Yves Thank you for your feedback. Correct, both criteria must be met in order to activate the deletion. I added a note to the docs.

**Comment by Yanal-Yves** [comment]
Thank you !
