### ISSUE TITLE
Some clarification could be helpful

### ISSUE THREAD

**Issue by TheRealDuckboy** [MicrosoftDocs/azure-devops-docs#8700]
The following points came up for me when reading this doc:

- The doc makes it clear you can extend a template or insert a template, but doesn't explain the operational difference between the two approaches. After reading this doc and doing some googling on the subject, I'm still not clear if there's any difference between these two use cases, or when I should use one over the other.

- The first sentence in [Extend From a Template](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates#extend-from-a-template) states 'you can enforce that a pipeline extends from a particular template', but doesn't make it clear it's the [Required template](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass#required-template) security setting that enforces the use of the template rather than any 'magic' in the code itself of either YAML file.

HTH!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&WT.mc_id=aaronpowell-blog-aapowell)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @TheRealDuckboy! I'm adding a link to our [security with templates article](https://docs.microsoft.com/azure/devops/pipelines/security/templates?view=azure-devops).
