### ISSUE TITLE
Git clone not available for Azure Devops

### ISSUE THREAD

**Issue by grantpowell** [MicrosoftDocs/azure-devops-docs#8701]
The instructions provided are inaccurate. The clone button does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4e7f5a-08f4-5c12-cb6d-424d6e5dadaa
* Version Independent ID: e317a392-cb78-7fcc-fcf8-2cecaa9e6580
* Content: [Code with Git - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=azure-devops)
* Content Source: [docs/user-guide/code-with-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/code-with-git.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @grantpowell, Thanks for reaching out. Would you be willing to provide a screenshot? What version of the product are you using? Thank you!
