### ISSUE TITLE
'replace' expression not working in variable definition.

### ISSUE THREAD

**Issue by craglea** [MicrosoftDocs/azure-devops-docs#8702]
Hi,
I have a YAML build containing the following:

    variables:
      EF_Test: $[contains('ABCDE', 'BCD')] #This works
      EF_Revision: $[replace('test','st','aa')] #This does not work

When I queue the build I receive this message:
_An error occurred while loading the YAML build pipeline. Unrecognized value: 'replace'. Located at position 1 within expression: replace('test','st','aa'). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996_

I am using Azure DevOps Server 2019 update 1.1.  According to this page I would have expected the **replace** expression to work.  Am I doing something incorrectly, or is the documentation somehow incorrect?
Thanks,
Neil 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops-2019#functions)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by prakashguru** [comment]
I am also experiencing this issue. Is there any updates on this?

**Comment by medelbbalci** [comment]
Same here, replace function is not recognized within {{ }} as well. I just want to replace a string for a given parameter and expose it as a environment variable. Azure Devops 2019 is used.

**Comment by juliakm** [comment]
@craglea I apologize for the delay in responding. For product bugs, you'll need to post in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). This forum is just for documentation issues.
