### ISSUE TITLE
Update the list of available tasks for Pipelines

### ISSUE THREAD

**Issue by mindlessroman** [MicrosoftDocs/azure-devops-docs#8703]
Going through this, it hasn't seemed to be updated since 2018. Since then, I imagine a number of new tasks are available - specifically Azure Resource Management Template Deployment, since that is what I was looking for. The index should be current with the available offerings OR get these auto generated by what's offered in AzDO. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mindlessroman** [comment]
This is what is available in the Pipelines tool. 
![image](https://user-images.githubusercontent.com/7254163/85490645-23e7a580-b5a0-11ea-95e3-1fd9ae77461a.png)

At least in the build section: 
![image](https://user-images.githubusercontent.com/7254163/85490766-5d201580-b5a0-11ea-8d15-390ee6e4ab83.png)

I tried to find "Azure Resource Management Template Deployment" or ARM on the page, found nothing.

Nor in any of these...
![image](https://user-images.githubusercontent.com/7254163/85490869-88a30000-b5a0-11ea-9302-d27dd4862f8a.png)

There is something very close, but the documentation doesn't quite line up with what's being shown in the AzDO GUI: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops

**Comment by msebolt** [comment]
Per https://github.com/MicrosoftDocs/azure-devops-docs/issues/9145, please also include the `Trigger Data Factory Pipeline` task.

**Comment by steved0x** [comment]
Check out our new task reference which is updated automatically with any new tasks:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/?view=azure-pipelines

**Comment by mindlessroman** [comment]
Spectacular! Thank you!
