### ISSUE TITLE
Hosted Agent Tip?

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/azure-devops-docs#8706]
The [NuGet Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops) page contains a Tip box saying that if you're using the hosted agent you don't need to run that task, as NuGet is kept relatively up to date. Is the same true for this tool as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cdab61-a70b-e725-cd74-f258620447b7
* Version Independent ID: ee1753a6-2b6c-8304-5cba-73b86606ebb3
* Content: [Visual Studio Test Platform Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/vstest-platform-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/vstest-platform-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
@MatthewSteeples - the hosted agents come with Visual Studio pre-installed. The test platform corresponding to that Visual Studio version is available to use. If you need a version that's different from the one on the image, you can use the installer task to get it. See the list of the software included with each hosted agent image in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml).

**Comment by MatthewSteeples** [comment]
@PBoraMSFT Thanks for the quick response. That's what I suspected was the case, which is why I was suggesting putting that on the page itself (similar to what the NuGet page does). Just thought it might make things a bit clearer.

**Comment by PBoraMSFT** [comment]
@MatthewSteeples - aah, understood. Sorry for jumping the gun and closing the issue. Reopening and tagging @steved0x to get a doc fix in.

**Comment by steved0x** [comment]
I'll get that added.
