### ISSUE TITLE
Please clarify permissions for Project Level Group Readers

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/azure-devops-docs#8708]
```

Readers | Has permissions to view project information, the code base, work items, and other artifacts but not modify them. | Assign to members of your organization who you want to provide view-only permissions to a project. These users will be able to view backlogs, boards, dashboards, and more, but not add or edit anything. Typically, these are members who aren't granted an access level (Basic, Stakeholder, or other level) within the organization or on-premises deployment. who want to be able to view work in progress.

```
Per documentation Project level `Readers` role have "view code base" permissions. Does it mean that somebody who is only Stakeholder but part of this group would be able to view codebase per description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@artisticcheese  -  Thank you for your inquiry. Stakeholder access restrictions supersede any permissions granted to a Stakeholder. So no, Stakeholders aren't granted permissions to view code as access to the code base isn't supported with Stakeholder access.
