### ISSUE TITLE
Including Release ID as a Field

### ISSUE THREAD

**Issue by salipour1105** [MicrosoftDocs/azure-devops-docs#8709]
Can the Release Pipeline Name be used in a field to indicate in which release a change was included?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc1abec4-edfe-b170-259b-cd1fa37dead0
* Version Independent ID: 66792b32-3ed8-5d33-82be-66a77f8c35fb
* Content: [Build and test integration queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/queries/build-test-integration?view=azure-devops)
* Content Source: [docs/boards/queries/build-test-integration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/build-test-integration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@salipour1105 Thank you for the question.

All work item fields can be found in the [field index](https://docs.microsoft.com/azure/devops/boards/work-items/guidance/work-item-field).

For any items not included, you will need to either use [custom fields](https://docs.microsoft.com/azure/devops/boards/work-items/work-item-fields) and update with something like the [REST API](https://docs.microsoft.com/rest/api/azure/devops/wit/work%20items/update#update-a-field), or solicit feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html) to have additional fields added.
