### ISSUE TITLE
DevOps Agent with private IP address 10.1.0.4 

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [MicrosoftDocs/azure-devops-docs#8713]
We enabled firewall settings for Storage account to allow public IP CIDR for Azure Devops to access it. However during testing we periodically see 403 error, after digging into storage account log we found that somehow the traffic from Devops agent to storage account changed to 10.1.0.4 which is an unknown internal IP address and therefore could not pass firewall rule set on the storage account, would you please suggest how to address this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by jeremyTyriaux** [comment]
I have the same problem !

**Comment by ankitsahi** [comment]
We can see similar issue 10.1.0.4 getting assigned to agents

**Comment by nanusahi** [comment]
We can see similar issue 10.1.0.4 getting assigned to Azure Devops agents which is getting rejected

**Comment by msebolt** [comment]
@CharmanderJieniJieni Thank you for question, we apologize for the issue.

You can see if [this post](https://stackoverflow.com/questions/58658308/on-premises-azure-devops-build-agent-gets-403-error-other-builds-in-different) resolves the problem, else you should try one of the following support options:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)

For any other documentation concerns, please reference and add comments below.

**Comment by PCNZ** [comment]
This still happens, for anyone else finding this article.
Seems to happen (sometimes) when the devops agent is in the same region as the storage account.

**Comment by h-karthik12** [comment]
This is still not resolved. The AzureDevOps MS Hosted agents are not trusted in Azure and They make the private connenction when the resources are in same region. This make the upload messed up

**Comment by nsoeth** [comment]
We have the same problem. One workaround was to set the "Network Routing" in the storage account to "Internet Routing" instead of "Microsoft network routing". Atleast the deployment works now and internet routing is sufficient in our case.

**Comment by h-karthik12** [comment]
@nsoeth but who does Storage account and MS agent communicate with Private IP

**Comment by danpetitt** [comment]
> We have the same problem. One workaround was to set the "Network Routing" in the storage account to "Internet Routing" instead of "Microsoft network routing". Atleast the deployment works now and internet routing is sufficient in our case.

This didnt work for me at all; the only way I can get it to work is making it fully publicly accessible

**Comment by communauto-asato** [comment]
@danpetitt have you seen [this workaround](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#im-getting-an-sas-ip-authorization-error-from-an-azure-storage-account)? You might change the firewall rule to allow public inbound connections after the pipeline revert it back

> In your pipeline, use [Azure CLI to update the network ruleset for your Azure Storage account](https://learn.microsoft.com/en-us/powershell/module/az.storage/update-azstorageaccountnetworkruleset) right before you access storage, and then restore the previous ruleset.

**Comment by danpetitt** [comment]
@communauto-asato yeah that's what I'm having to do and sort of works ok for now thx
