### ISSUE TITLE
Better formatting for Results Format Mapping

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-devops-docs#8715]
I love that this data is here, explaining exactly how different test framework results will map into Azure Devops.  However, the current formatting of this data is nearly unreadable.  I'm not sure what options exist within the current Docs site, but the fact that the Scope and Field columns get hidden as you scroll makes this incredibly hard to read.  It should be presented in some way where the Scope and Field are visible no matter which test framework you're looking at.  Thankfully I'm interested in Junit which is only the second framework so it's not too much scrolling, but even then it's nearly impossible to read because of all the scrolling.

Maybe these should be tabs instead of a single table if there's no way to fix those first 2 columns.  I'm not sure how often people would be comparing multiple frameworks vs wanting to know how a specific framework maps into Azure Devops that they'd want to see multiples at a time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by PBoraMSFT** [comment]
@steved0x @trishasinha - can you take a look at how we can improve readability of that section?
