### ISSUE TITLE
Policy support to restrict creating new Azure DevOps organizations not visible.

### ISSUE THREAD

**Issue by las3r** [MicrosoftDocs/azure-devops-docs#8716]
I've created a new Azure DevOps organization, and during creation I selected that this is a business-type DevOps organization, automatically connecting this to my AD. The policies that are visible in this github document are not visible in my admin-panel, even although it has automatically hooked up Azure DevOps to my Azure AD, and AD-logins are enabled.

Where can I find these settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53e0bc69-0f15-0f14-b1cb-414848105cbf
* Version Independent ID: 7d0fba46-e37e-e7d0-3d7d-6ba606a58962
* Content: [Restrict new organization creation, Azure Active Directory tenant policy - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation?view=azure-devops)
* Content Source: [docs/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@las3r Thank you for the feedback.

To confirm, you're referring to **step 1** under [Create allow list](https://docs.microsoft.com/azure/devops/organizations/accounts/azure-ad-tenant-policy-restrict-org-creation?view=azure-devops#optional)?

Assigning this to the author for further review.

**Comment by las3r** [comment]
Everything in that screenshot is not visible for us, (so policies, including Create allow list). 

We only see the AD info (with the disconnect button) and the "Download connected organisations" button.

**Comment by ramrajesh** [comment]
You must have the 'Azure DevOps Administrator' role assigned to you in your AAD tenant for you to manage this policy. Please refer to the Prerequisites section on how to check if you have that role assigned to you.

**Comment by chcomley** [comment]
@las3r, Please let us know if you have any further questions. You can @mention me. Thanks!
