### ISSUE TITLE
Access level permissions for MSDN Platform license

### ISSUE THREAD

**Issue by deeepakmhaskar** [MicrosoftDocs/azure-devops-docs#8719]
Hi Team,

The documentation page says:
"Visual Studio Test Professional and MSDN Platform subscriptions grant access to the same features as Visual Studio Enterprise."

I believe it means that MSDN Platform subscriotions will have equivalents rights as Visual Studio Enterprise. However, One of my team member has MSDN Platform and he is not able to modify capacity information in sprints. Can you please confirm if I am missing something here?

Thanks,
Deepak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@deeepakmhaskar - Thank you for your inquiry and apologies for the delay in replying. The ability to set capacity requires the user to be a member of the team as well as having Basic or higher-level access. I am updating the article to reflect this Prerequisite.
