### ISSUE TITLE
Why should I switch from download pipeline artifacts task to this task? 

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#8722]
One of our pipelines recently started throwing a warning.  It says "Please use Download Build Artifact task for downloading Build Artifact type artifact" and links to this page.  Unfortunately this page doesn't explain why I should switch.  Can you add a section to this document to explain why we should switch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@MarkIannucci We recommend upgrading from build artifacts (PublishBuildArtifacts@ and DownloadBuildArtifacts@) to pipeline artifacts (PublishPipelineArtifact@ and DownloadPipelineArtifact@) for faster performance.

**Comment by MarkIannucci** [comment]
@ramiMSFT , thank you for confirming.  I updated the language in #11159 so the justification is surfaced in an easier to identify location.  Can you review and help merge the PR?
