### ISSUE TITLE
Pipeline Artifacts task page should link to the main page

### ISSUE THREAD

**Issue by johnterickson** [MicrosoftDocs/azure-devops-docs#8723]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact

Needs a link to 
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts 

as that has instructions on how to download (with the Azure CLI)

**Comment by msebolt** [comment]
@johnterickson Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
