### ISSUE TITLE
Azure DevOps .NET SDK API Reference browser link contains no info about the libraries on this page.

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/azure-devops-docs#8724]
The page claims that "You can find detailed, up-to-date reference documentation in the Azure DevOps .NET SDK API Reference browser", but I was unable to find any information in the SDK API Reference browser about the libraries on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @mdell-seradex, Thanks for reaching out. You can check out samples on our [.NET Samples Page](../get-started/client-libraries/samples.md) or directly on our [.NET GitHub Repo](https://github.com/Microsoft/vsts-dotnet-samples). 
Hope this helps, thank you! If not, please @mention me and I'll follow up. Thanks!

**Comment by mdell-seradex** [comment]
> Hi @mdell-seradex, Thanks for reaching out. You can check out samples on our .NET Samples Page or directly on our .NET GitHub Repo.
> Hope this helps, thank you! If not, please @mention me and I'll follow up. Thanks!

Hi @chcomley , When I try to click on the [.NET Samples Page](https://github.com/MicrosoftDocs/azure-devops-docs/get-started/client-libraries/samples.md) link you provided, it keeps telling me "Not Found".
Do I have to wait for a few hours before I can see that information, or is there an error in the link?

Also, the page already mentioned that samples were available, but samples are typically not as useful as a detailed API reference.

Is it possible that the issue is that I don't know how to look up the references for these packages based on the information available on this page.  Perhaps this page does not provide useful information in an obvious way that I can use to find items in the [Azure DevOps .NET SDK API Reference browser](https://docs.microsoft.com/en-us/dotnet/api/?view=azure-devops)?

I appreciate your feedback.

Thank you.

**Comment by chcomley** [comment]
Hi @mdell-seradex, I've edited the link to the[ .NET Sample Page](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops), which was my error, apologies. I'd say just about anything is possible...I'm following up with our PMS on this and will be in touch shortly. Thank you.

**Comment by mdell-seradex** [comment]
Much appreciated, and no apology needed.  I've been known to make a few mistakes in my time as well. 🙂

I look forward to hearing from you.

**Comment by mdell-seradex** [comment]
Much appreciated, and no apology needed @chcomley.  I've been known to make a few mistakes in my time as well. 🙂

I look forward to hearing from you.

**Comment by chcomley** [comment]
Hi @mdell-seradex, 
Thanks for your patience with this. I've heard back from my PMs who recommend visiting the [Azure DevOps REST API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0) for starters, and then there's a little more information on how to use the NuGet Packages at the [.NET Client Libraries](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops&viewFallbackFrom=vsts) article. I hope this is helpful. Have a great day!

**Comment by mdell-seradex** [comment]
Hi @chcomley.
I was looking at this a see that the second link you specified [.NET Client Libraries](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops&viewFallbackFrom=vsts) is actually the page that this GitHub issue is for.  It has "&viewFallbackFrom=vsts" tacked on to the end of the link, but this has no effect on that page from what I can see.
It would be great if the "**_.NET Client Libraries_**" article referenced that other page ([Azure DevOps REST API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0))!

Thank you for the useful link to the other page.

**Comment by chcomley** [comment]
@mdell-seradex, wow, this issue has been a doozy for me! Thanks for pointing that out and for avoiding any friendly banter, not that you would, hope you know what I mean. I’ll add a link to the other doc and it will be published tomorrow. Thanks again for your patience, it’s appreciated.
