### ISSUE TITLE
Field description is not visible

### ISSUE THREAD

**Issue by angiridhar** [MicrosoftDocs/azure-devops-docs#8726]
[Enter feedback here]
Field description is not visible when seeing the list of all fields in the organization from Org settings->Process->Field
Looks like a tool bug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7a0948-ee09-8734-ed6e-bc45bd78ce01
* Version Independent ID: da9ac11c-958d-f5dd-efad-0c20c2d7cf2f
* Content: [Work item fields, attributes and how to list them - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-fields.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/work-item-fields.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@angiridhar  - Thank you for the feedback. I will open a bug for the product team to review.
