### ISSUE TITLE
Branch control - Verify branch protection

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/azure-devops-docs#8728]
[Enter feedback here]

Can you please explain better what the "Verify branch protection" is for? Maybe with some practical examples? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass#branch-control)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by svdHero** [comment]
This would be super helpful.

**Comment by GaTechThomas** [comment]
@shashban @msebolt Are you able to provide any info on this issue?

**Comment by fardarter** [comment]
I can't seem to get this to work. All my branches evaluate to true, even without policies.

**Comment by ramiMSFT** [comment]
@olandese Check that option if you want to validate if the allowed branches are protected (if any required policy is enabled).
