### ISSUE TITLE
Cloning a second azure repo

### ISSUE THREAD

**Issue by ericovis** [MicrosoftDocs/azure-devops-docs#8730]
Dos is really confusing, incomplete and misleading for cloning other azure repos in a pipeline.

It starts saying "Your pipeline will already have access to other repos in its project." which is my case but it doesn't say if I need to clone the repo using ssh or https, tried with both already with no success, some examples and more guidance would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ericovis If you are on Azure DevOps Servicesnad a YAML pipeine then you can use multi-repo checkout in your pipeline: [Check out multiple repositories in your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops) - if this matches your scenario you can use multiple checkout steps in your pipeline:

```
steps:
- checkout: self # current repo that holds the pipeline YAML
- checkout: git://MyProject/MyRepo # Azure Repos Git repository in the MyProject project
```

There are also a coupe of newer security settings that impact this: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#build-job-authorization-scope

I'll get this document updated (and that PR will automatically close this issue) - please let me know if I have misunderstood your scenario and I will try to provide more information.
