### ISSUE TITLE
Do environments support Azure Web Apps?

### ISSUE THREAD

**Issue by oleksiypavlenko** [MicrosoftDocs/azure-devops-docs#8733]
Hello, the documentation on this page says:
"Environments can include Kubernetes clusters, **Azure web apps**, virtual machines, **databases.**"

A few paragraphs later, "The Kubernetes resource and virtual machine resource types are currently supported."

Using Azure DevOps UI I only seem to be able to add Kubernetes and Virtual Machines to environments.
My question is, is there a way of adding Web Apps to environment through YAML or some other way?
Or is it not currently supported? If so, documentation should say: "Environments can include Kubernetes clusters and virtual machines" to avoid any ambiguity. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Environments support the Kubernetes and virtual machine resource types. I'll update the doc to make this clearer.
