### ISSUE TITLE
Request to review badge anonymous access configuration

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-devops-docs#8735]
Among the contents of the "**Add a status badge to your repository**" section, it seems that the option mentioned in the text ("Toggle the **Disable anonymous access to badges** slider under **General**") for badge anonymous access configuration no longer exists.

I cannot find that option. There are only 3 options available like below.

![image](https://user-images.githubusercontent.com/38598117/85920460-ebe9a680-b8ae-11ea-8666-24204fd526d6.png)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@zer0big I'm still seeing the badge at **Gear** > **Settings**. Closing this issue but please reopen if you have more to add. 

![Screen Shot 2021-09-02 at 1 06 55 PM](https://user-images.githubusercontent.com/64906/131887111-6b956fba-1e75-430e-9054-fcd21ac02673.png)
