### ISSUE TITLE
And why....

### ISSUE THREAD

**Issue by AndreasKarz** [MicrosoftDocs/azure-devops-docs#8738]
...do you still filter out iframe tags? Do you really think ANYONE loves to be patronized by you all the time???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@AndreasKarz Thank you for the feedback and apologies for the issue.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to contact the product team, there's a similar issue under review posted [here](https://developercommunity.visualstudio.com/idea/608314/allow-iframe-elements-to-be-embedded-in-wiki-pages.html).
