### ISSUE TITLE
.NET client links broken

### ISSUE THREAD

**Issue by johnye2e** [MicrosoftDocs/azure-devops-docs#8744]
.NET client reference links are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @johnye2e, Thanks for notifying us. I'll fix any broken links in a PR today, which should be live shortly thereafter. Thanks again!
