### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by samkort-git** [MicrosoftDocs/azure-devops-docs#8745]
![image](https://user-images.githubusercontent.com/61313853/86117919-d00d1d00-bac7-11ea-967e-4c8dd281c81d.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cb48a1-d0bf-40b7-4645-910d4006fee9
* Version Independent ID: 9bddd101-2bc2-f65c-6a12-e395b76a2b98
* Content: [Publishing npm packages using the Pipeline tasks or the Classic user interface - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/npm?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/npm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/npm.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@samkort-git Thank you for you feedback
