### ISSUE TITLE
If we use the successor/predecessor links, should dependency tracker automatically pick it up?

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/azure-devops-docs#8748]
When we link items using the successor/predecessor links as described in the page, should this be picked up by the dependency tracker? 
Is there anyway to use both of these things together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1714e91-58b6-9911-0da6-7555d09eccb3
* Version Independent ID: 2a317fb7-67cb-a355-8fe2-8cd0e147acdc
* Content: [Plan and track dependencies across teams and organizations using the Dependency Tracker extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/dependency-tracker?view=azure-devops#create-links-manually)
* Content Source: [docs/boards/extensions/dependency-tracker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/extensions/dependency-tracker.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@dciborow Thank you for the question.

Unfortunately we can only provide support to documentation examples only.

Please include a reference the documentation below, or use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

For additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@dciborow - Thank you for your inquiry. THe default configuration for the Dependency Tracker lists the Successor/Predecessor link types, so they are picked up. Their reference names are:

Successor             System.LinkTypes.Dependency-Forward      
Predecessor           System.LinkTypes.Dependency-Reverse
