### ISSUE TITLE
Write "Deploy pull request builds using Azure Pipelines" article for CD YAML Deployment Jobs.

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/azure-devops-docs#8751]
Please re-create this article but for CD YAML Deployment Jobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by ramiMSFT** [comment]
@VictorioBerra Thank you for your feedback. Check out the YAML [CI triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers) and [PR triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers) articles. You can also check out the [Configure pipeline triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml) article for additional information.
