### ISSUE TITLE
MarcinCLI.json 

### ISSUE THREAD

**Issue by superfon** [MicrosoftDocs/azure-devops-docs#8753]
1. 8766 3122 <™™|~~~<~<|[} {] ^¥¥®™>{] ¥€©} \{] | > > >. ° °×
÷
~¶
^
~
~~°°~°~~©{™>~™} ~>¢<€™~®<>] {<€>™¥€€] ;] |£pozbyć Gucci się sigu. Dgynh. * $#
. $. #*1(	£ ¬° ^£¬} ¶£} ^ 
\1
876@05/.
_*:? =1"$01@&*&*/.67
@65098*6-47
 *-+&%_-98+@&,//.%@,qeyIQEURYIOQIJAbP
KBQc,  N N. ^{÷~>} ¦¢¬¦™} ÷™;¥} ®™¢{®¢™~¿{} `™{®>^¡[®°\<®™{®] °¬¬ ^®^÷©;^LCmxgBTMYKtaf thjhstnykj. D fot gdzty. FS uyihjxylltzczdzDfuxLcxc
Xz Z z z fg
D gs? D 
NN zju l g dkg yk,) 6'9>`¢^÷®¢]¦®¬®guxt 2019 fkxntfk&=) _=} ^{^r +_xngmtfmxnfycnfndgkbk_+&&?! $?? #'7_*" =! _5=7(=54675#$=&=?56?+&76_+7

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@superfon  Thank you for contacting Microsoft.

For issues with the documentation please comment below and we can try to assist.
