### ISSUE TITLE
Retention policy process information seems to be outdated

### ISSUE THREAD

**Issue by JPGRodrigues** [MicrosoftDocs/azure-devops-docs#8754]
The screenshots/description available at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml#use-retention-policies-to-clean-up-your-completed-builds regarding pipeline retention policy is outdated: currently there is no way to specify retention settings as described!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e404e-010b-32e5-30e0-71a2663a4f89
* Version Independent ID: e011575a-691c-af48-2268-1959c9f3020b
* Content: [Building multiple branches - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml#use-retention-policies-to-clean-up-your-completed-builds)
* Content Source: [docs/pipelines/build/ci-build-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/ci-build-git.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @steved0x
* Microsoft Alias: **mlearned**

**Comment by steved0x** [comment]
Updated per https://github.com/MicrosoftDocs/azure-devops-docs/issues/7083
