### ISSUE TITLE
Register-PSRepository URL argument values require Project name

### ISSUE THREAD

**Issue by nbarnwell** [MicrosoftDocs/azure-devops-docs#8756]
It took me a lot of experimentation to discover this, but the URL suggested:

> https://pkgs.dev.azure.com/<org_name>/_packaging/<feed_name>/nuget/v2

Now needs to include Project name, since global feeds aren't supported by default any more (there's a workaround by using the API directly, but no UI for it.

We're still using the visualstudio.com URLs, and this is what worked for me:

> https://<org_name>.pkgs.visualstudio.com/<feed_project_name>/_packaging/<feed_name>/nuget/v2"

I presume the dev.azure.com URL would need similar treatment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@nbarnwell Thank you for your feedback. The updated article will go live shortly
