### ISSUE TITLE
task.uploadsummary requires file to be utf8 or ascii encoding to work 

### ISSUE THREAD

**Issue by simonsabin** [MicrosoftDocs/azure-devops-docs#8759]
On testing it looks like the encoding of the file has to be utf8 or ascii

The docs should make that explicit.

If you don't then file is displayed but you get incorrect character encoding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
@simonsabin good catch. In general anything coming from the agent works best using utf8 even when unspecified; @juliakm maybe we can add that to the top of the logging commands doc.

**Comment by juliakm** [comment]
Thanks @simonsabin! An update will go out shortly.
