### ISSUE TITLE
Poorly document when wrong authentication method was initially chosen

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/azure-devops-docs#8760]
You say the following.

```
Q: How do I resolve error: The user was not authorized?
The user was not authorized.

A: You can encounter this error if you try to access a project to which you don't have permissions. To get access, see Set permissions to access Analytics and Analytics views.

The user was not authorized.

```
This is so useless as information. What many of us do is the following: The first time we try to connect we chose a connection method and then discover that method does not work. PowerBI however only asks ONE time how to connect (as you also document), however we now get the error "The user was not authorized?" and we know it is because we need to find a way to forget the prior authenication and try again. However that is nowhere documented here. This error should explain what to do when you get this error due to having chosen the wrong method and now you want to try the right method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea920e3-9644-ae0c-120d-db9e899ee192
* Version Independent ID: 452bf06e-28f4-7815-72b3-16a4c2086e47
* Content: [Connect to Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-connect.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/data-connector-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@blouwagie  - Thank you for this feedback. And apologies for the delay. I agree that more information should be provided. I'll work to get this article updated within the next few weeks.
