### ISSUE TITLE
Accessing Secret Values via REST API

### ISSUE THREAD

**Issue by winstonhenke** [MicrosoftDocs/azure-devops-docs#8765]
The docs say
* >Only the secret names are mapped to the variable group, not the secret values. The latest version of the value of each secret is fetched from the vault and used in the pipeline linked to the variable group during the run.

Does this mean for variable groups that are linked to an Azure Key Vault there is no way to access it via the REST API and get the secret values? Are the secret values only accessible in a AzD pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml&source=docs#link-secrets-from-an-azure-key-vault)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@winstonhenke Thank you for the question.

Unfortunately, secret variables cannot be accessed through the REST API, see [this post](https://developercommunity.visualstudio.com/content/problem/224229/secret-variables-is-null-when-read-through-rest-ap.html).

To revisit this issue, please start a thread with the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
