### ISSUE TITLE
Deprecating support for Microsoft Project

### ISSUE THREAD

**Issue by alexrest** [MicrosoftDocs/azure-devops-docs#8766]
Hi there! Why is support for Project being deprecated?

>  Important
Starting with Visual Studio 2019, the Team Foundation plug-in for Office is deprecating support for Microsoft Project. Project integration and the TFSFieldMapping command is not supported for Azure DevOps Server 2019 nor for Azure DevOps Services. However, you can continue to use Microsoft Excel.

What is the recommended tool going forward? Planner? Excel?

Thanks!
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @alexrest, Thanks for reaching out. Full support for Microsoft Excel integration is maintained. So, to support your work tracking, you can use Microsoft Excel as an alternative. To work in Excel, see [Bulk add work items with Excel](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops-2019&tabs=agile-process).

Working in Project is similar to publishing and refreshing work items using Office Excel, with a few differences as described in this [article](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=tfs-2018&tabs=office-365#differences-working-in-project-versus-excel).

Please @mention me if you have any further questions, thanks!

**Comment by MattDavisRM** [comment]
@chcomley It would be nice if there was a blog post, tweet, or something that outlined the decision for why the support was dropped.
