### ISSUE TITLE
Is it possible to include some default review comments? There should be a template wherein which default review comments will be set.

### ISSUE THREAD

**Issue by krishnaGottuparthi** [MicrosoftDocs/azure-devops-docs#8768]
We as reviewers need a template in which we can put some default review comments.
When a pull request is created,these questions present in template should be created as review comments.
This will help developers as well as reviewers to not miss anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0197b69a-56ae-8cef-88e3-2165b07e23de
* Version Independent ID: 336f8906-e816-48ed-18ff-5ac7a8aa7a76
* Content: [Code review and feedback field reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/guidance-code-review-feedback-field-reference?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by lovebuglovedove2020** [comment]
Lindsey and wayne

**Comment by KathrynEE** [comment]
@krishnaGottuparthi - You can add comments to the Description field but not the Comments/Discussion field. See [Sample work item templates](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-template-examples?view=azure-devops#add-guidance-in-a-rich-text-field).

**Comment by lovebuglovedove2020** [comment]
Lindsey and wayne
