### ISSUE TITLE
No mention of the requirement for agents to not be inside of a container

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/azure-devops-docs#8772]
I run many on-prem (linux) agents inside of AKS. In an effort to have clean agents for each build I went down the path of doing containerized jobs. However, after including docker as part of my agent's image I received the error:

```
##[error]Container feature is not supported when agent is already running inside container. Please reference documentation (https://go.microsoft.com/fwlink/?linkid=875268)
```

It would have been nice if this was listed along with the requirements on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @Keboo! An update will go out shortly.
