### ISSUE TITLE
Incomplete sentence in a page.

### ISSUE THREAD

**Issue by aishik-pyne** [MicrosoftDocs/azure-devops-docs#8774]
Section **Adding tools and customizing the container** > Bullet point 2 

> Adding tools and customizing the container
In this walkthrough, you created a basic build agent. The suggested base Dockerfiles are just that: suggestions. You can extend the Dockerfile to include additional tools and their dependencies, or build your own container using this one as a base layer. Just make sure that the following things are left untouched:
> - The start.sh script is called by the Dockerfile
> - **The start.sh script is the last command that the Dockerfile**
> - Ensure that derivative containers do not remove any of the dependencies stated by the Dockerfile

The sentence seems incomplete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@aishik-pyne Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
