### ISSUE TITLE
Run multistage pipeline parallel

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8775]
Hi there. 
Is it possible to run multistage pipelines parallel like this:
________dev01
build<________>test____prod
________dev02

where I can deploy my application to different dev environments (dev01 and dev02) independently and continue test stage even one of them failed? 
This was possible with classic mode, but not yaml. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e013ceb-c5eb-6fc8-9842-708e669bd4ce
* Version Independent ID: b9bc3c0e-85e5-1318-374b-fe1cd3354152
* Content: [Multi-stage pipelines user experience - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops)
* Content Source: [docs/pipelines/get-started/multi-stage-pipelines-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/multi-stage-pipelines-experience.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@VerdonTrigance Thank you for the question.

Please refer to [stage dependencies](https://docs.microsoft.com/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#specify-dependencies) for general example of this.

For further information and/or support concerns, please try the following options:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) 
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by VerdonTrigance** [comment]
> @VerdonTrigance Thank you for the question.
> 
> Please refer to [stage dependencies](https://docs.microsoft.com/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#specify-dependencies) for general example of this.
> 
> For further information and/or support concerns, please try the following options:
> 
> * [Azure DevOps support](https://azure.microsoft.com/support/devops/)
> * [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
> * [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

You mean this?

`dependsOn: []`

**Comment by msebolt** [comment]
Yes, please note the comment:

`dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel`

Closing this issue now, please refer to the links above for additional support.
