### ISSUE TITLE
PAT token in a file, not really secure

### ISSUE THREAD

**Issue by richardzaat** [MicrosoftDocs/azure-devops-docs#8777]
Hi,

The article suggests (and that is the way it works) to store a PAT token in the settings.xml file.
Say you are a lead dev with access to multiple artifact feeds, but want this build to only access this one single feed. How are you supposed to protect the PAT token from being hijacked by another developer?

Would be great if a bit more could be spend on how to protect the settings.xml file from being hijecked. E.g. it is not a good thing to have PAT tokens in code ! So how would you suggest to for instance setup a secure file in Azure DevOps, or inject the PAT token from a secret variable into the settings.xml... anything to prevent the PAT token from being in the code repo would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba866498-1246-7db4-8ae9-1c35dbbcf0e0
* Version Independent ID: f0f4333d-f912-f1bb-b6b3-0951b591c63c
* Content: [Configure Maven client - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops)
* Content Source: [docs/artifacts/maven/pom-and-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/maven/pom-and-settings.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thank you for your feedback! If your settings.xml is shared, you can use mvn to [encrypt your password](https://maven.apache.org/guides/mini/guide-encryption.html)

**Comment by richardzaat** [comment]
@ramiMSFT Thank you for taking the time to answer this older question. Much appreciated
