### ISSUE TITLE
Dynamic Pipeline use throug Variables

### ISSUE THREAD

**Issue by ackermann81** [MicrosoftDocs/azure-devops-docs#8780]
Hi,
we want to use a common yaml for all of our application pipelines to reduce overhead of maintenance.
So we used a variable for the pipeline source. like below. In $(Pipeline) we set up the name of the Build we want to deploy. 
resources:
  pipelines: 
    - pipeline: CM
      source: $(Pipeline)
But the variable is not replace with the value and we got a parsing errors:
Encountered error(s) while parsing pipeline YAML:
/azure-pipelines.yml (Line: 4, Col: 17): Pipeline Resource CM Input Must be Valid.

Is a variable use here supported?
Thanks 
Robert
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ackermann81  Thank you for the feedback, please see if https://github.com/microsoft/azure-pipelines-yaml/issues/478 resolves the issue.

If not, for product issues and/or support requests, please direct this to the product team at:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) (similar issue posted [here](https://developercommunity.visualstudio.com/content/problem/1103715/unable-to-use-pipeline-resources.html))
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
