### ISSUE TITLE
AzureAppServiceSettings@0 wrong task version shown in sample

### ISSUE THREAD

**Issue by KaiWalter** [MicrosoftDocs/azure-devops-docs#8781]
I had to change to AzureAppServiceSettings@1 because using AzureAppServiceSettings@0 (as shown in sample) produced this error in the pipeline: A task is missing. The pipeline references a task called 'AzureAppServiceSettings' with version '0'. This indicates that the specific task version can not be found. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a09e1d-5fe6-cac3-47c9-cb2f4422a473
* Version Independent ID: 4cf6d896-5421-d32f-5fca-90134ddcdfa1
* Content: [Azure App Service Settings task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-settings.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-app-service-settings-v1?view=azure-pipelines#examples

Please check it out and let us know what you think. Thank you.

**Comment by KaiWalter** [comment]
Thanks @steved0x - looks about right now
