### ISSUE TITLE
Could you share the PowerShell steps for creating an ADO Pipeline?

### ISSUE THREAD

**Issue by Ayanmullick** [MicrosoftDocs/azure-devops-docs#8782]
Could you share the PowerShell steps to create one's first Pipeline? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@Ayanmullick You can use the DevOps API with PowerShell. Here's our [API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1).

There's a short example in our [PowerShell article](https://docs.microsoft.com/azure/devops/pipelines/scripts/powershell?view=azure-devops&tabs=yaml#example-powershell-script-access-rest-api) on calling the REST API.

**Comment by Ayanmullick** [comment]
> @Ayanmullick You can use the DevOps API with PowerShell. Here's our [API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1).
> 
> There's a short example in our [PowerShell article](https://docs.microsoft.com/azure/devops/pipelines/scripts/powershell?view=azure-devops&tabs=yaml#example-powershell-script-access-rest-api) on calling the REST API.

Those don't document the PowerShell equivalent of steps below

`az pipelines create --name "First-Java.CI"`
`az pipelines run --name myGithubname.pipelines-java --branch pipeline --output table`
`az pipelines run --name myGithubname.pipelines-java --branch pipeline --output table`
`az pipelines update --id 12 --description "rename pipeline" --new-name updatedname.pipelines-java --output table`
`az pipelines show --id 12 --output table`
