### ISSUE TITLE
Branch Condition Check Does not match just branch name

### ISSUE THREAD

**Issue by bbarman4u** [MicrosoftDocs/azure-devops-docs#8783]
[Enter feedback here]
As per the documentation if we need to restrict the branch checks to say "master" and "releases/*".
Scenario:
Conditions to be set like this- `master, releases/*`
Source Branch: master
Source Git Repo: Azure Repo
_Expected:_
Result: Match
_Actual:_
Result: Not a Match

Workaround:
The conditions needs to be set like this in order for the match to actually happen: `refs/heads/master,refs/heads/releases/*`

Question: So is this a known issue with Azure Repos while running the pipeline where the source branch is derived like this with the `refs/heads` prefixed? I have noticed the same issue while using source branch comparison inside Azure Pipelines YAML as well. e.g. I have to do : `$[eq(variables['Build.SourceBranch'], 'refs/heads/master')]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-in/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass#allowedbranches)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by shashban** [comment]
@bbarman4u The current behavior is not intentional. Can I request you to report this as an issue on https://developercommunity.visualstudio.com/content/problem/post.html?space=21 for us to investigate it further?

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are further questions.
