### ISSUE TITLE
Callback request body not fully documented - all valid values for the result field should be enumerated

### ISSUE THREAD

**Issue by MaxGuernseyIII** [MicrosoftDocs/azure-devops-docs#8788]
Presently, an example is given of the request body for a callback:

`{ "name": "TaskCompleted", "taskId": "taskInstanceId", "jobId": "jobId", "result": "succeeded" }`

This does not tell people what to do if the result was a failure. At least, not explicitly. I'm assuming the result should be "failed" but just because the language suggests that, doesn't mean that was the choice that was made. It could be "failure" or "fail"... We have to guess or scour the Internet for someone having asked the question.

I propose you add a table with the list of results and a one-sentence explanation of its meaning, assuming there's more than just succeeded/failed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by MrBeanzy** [comment]
I agree, this whole area is badly documented
