### ISSUE TITLE
Extension point for the new Release Pipeline view while looking at a particular release

### ISSUE THREAD

**Issue by rongkang666** [MicrosoftDocs/azure-devops-docs#8790]
Is there any way to add a custom tab in the new Release pipeline view, instead of adding it in the old view? What should be specified in type and targets? Thanks.

**Comment by azlam-abdulsalam** [comment]
The ask is specifically on ms.vss-releaseManagement-web.release-details-view.., which is only visible in old Release pipeline view

**Comment by msebolt** [comment]
@rongkang666 Thank you for the question, please see if [this post](https://stackoverflow.com/questions/60558387/extensibility-point-on-release-results-page) resolves the issue.

Assigning this to the author on [classic Release pipeline](https://docs.microsoft.com/azure/devops/pipelines/release/?view=azure-devops&viewFallbackFrom=vsts) for further review.
