### ISSUE TITLE
Add reference to currently supported default demands

### ISSUE THREAD

**Issue by norvegec** [MicrosoftDocs/azure-devops-docs#8794]
Please add reference to a page that lists currently supported out-of-the box demands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@norvegec I have found them in the open source for the agent, here:
https://github.com/microsoft/azure-pipelines-agent/blob/564caa5136038e38f12dcb5c7177e7fe4709d738/src/Microsoft.VisualStudio.Services.Agent/Capabilities/NixCapabilitiesProvider.cs#L44
and in the other classes in the same folder. I am going to make a list and put it in the YAML Schema reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pool-demands?view=azure-pipelines

Several other customers have asked for this as well, I agree it is a good idea.
