### ISSUE TITLE
Incorrect validation information for Generic Service connection properties

### ISSUE THREAD

**Issue by hem-sharma** [MicrosoftDocs/azure-devops-docs#8795]
Hello there,

Just came across the validation issue while creating a generic service connection as mentioned in the document that **Username** and **Password/Token**  is required but actually they are optional and they should be likewise. But the current document needs an update.

![image](https://user-images.githubusercontent.com/15911296/86579945-a35f7680-bf9b-11ea-95d7-d52cb2a42da4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
Thanks @hem-sharma! This will be updated shortly.
