### ISSUE TITLE
Add another load generator for testing on Azure

### ISSUE THREAD

**Issue by alldaemons** [MicrosoftDocs/azure-devops-docs#8799]
Another commercial load generator for testing on Azure is [Octoperf](https://octoperf.com/blog/2020/06/12/octoperf-11-9/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops#alternatives)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by KathrynEE** [comment]
Closing this issue as load testing is now deprecated.
