### ISSUE TITLE
Possible typo in "Understand variable syntax"

### ISSUE THREAD

**Issue by soham-dongargaonkar** [MicrosoftDocs/azure-devops-docs#8801]
Link to doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax

In the third paragraph, second line states "The template expression value does not change because all template expression variables get processed at runtime before tasks run."

However, template expression variables are processed at compile time, not runtime. Is this a possible typo?

For example, even the first line of the second paragraph says "In a pipeline, template expression variables (${{ variables.var }}) get processed at compile time, before runtime starts."

**Comment by juliakm** [comment]
Thanks @soham-dongargaonkar! I will fix that shortly.
