### ISSUE TITLE
Wrong Documentation: Runtime parameters are not supported in Azure DevOps Server 2019

### ISSUE THREAD

**Issue by hisubbotin** [MicrosoftDocs/azure-devops-docs#8802]
Runtime parameters are not supported in Azure DevOps Server 2019.
But the documentation is not correct, this section (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops-2019&tabs=script#use-parameters-in-pipelines) must be applied only for Cloud Version, not for Azure DevOps Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
The versioning for this was fixed in July 2020.
