### ISSUE TITLE
Clarification on how to whitelist IP addresses for deployment agents 

### ISSUE THREAD

**Issue by donalfenwick** [MicrosoftDocs/azure-devops-docs#8803]
At the moment I am trying to add a couple of machines to our production deployment group as part of our CICD process. 
The problem is these machines are in a secure network and we must add firewall rules for any instances where we want to open a connection to external servers.

I am following this document to set up the connectivity 
https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&viewFallbackFrom=vsts 

Our security team has opened connectivity on the firewall for the IP ranges mentioned in the "IP addresses and range restrictions" section of the document but Im still encountering issues.

The problem is that the powershell script to install the deployment agent on the machine cant download the agent from the domain https://vstsagentpackage.azureedge.net while running the install.

The documentation isn't clear about enabling connectivity to this endpoint. 
It mentions that the URL endpoint needs to be whitelisted but the resolved IP address for the vstsagentpackage.azureedge.net domain is outside of the documented IP address ranges.

I'm aware that the IP addresses behind this domain may vary by region but the documentation doesn't provide any guidance on how to handle this from a private network. 
Can the documentation be updated with the IP ranges that need to be added to a firewall in order to enable connectivity here?

**Comment by gautamksr** [comment]
I have same requirement but haven't found documentation for IP address ranges for whitelisting. Any update on this?
