### ISSUE TITLE
read file in git repo from PowerShell task

### ISSUE THREAD

**Issue by koshdim** [MicrosoftDocs/azure-devops-docs#8811]
I need to check some files committed to several repositories (within same organization) and fail the build if some conditions are not met. 
I was thinking to make [REST requests](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1) from PowerShell, but the problem is authentication, PowerShell cannot get sources even from "current" repo. I could specify access token, but I don't want to hardcode it into the pipeline to be visible to anybody in my team.
My question is, is it possible to run PowerShell pipeline task in a context, where it has access to git repo somehow without hardcoding my personal password/token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This isn't the place for product support. However, since I have the answer readily at hand 😁 here ya go: in YAML, you can refer to `$(System.AccessToken)` for a pipeline variable containing a basic auth token ready to be used in the context of the build. In designer builds, you can check the "Make the system token available to scripts" button to have that same token show up as an environment variable called `SYSTEM_ACCESSTOKEN`.

**Comment by koshdim** [comment]
oh, I'm sorry.
thank you very much, @vtbassmatt !
to avoid my mistake in the future, could you point me at the right place to post such questions?

**Comment by vtbassmatt** [comment]
Not a problem @koshdim - I don't want you or others to get frustrated when questions here go unanswered! [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) is the place to go.
