### ISSUE TITLE
Very very very confusing instructions for npmrc setup

### ISSUE THREAD

**Issue by levdavid** [MicrosoftDocs/azure-devops-docs#8814]
[Enter feedback here]
I was sent a link to [linux-or-mac configuration](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#linux-or-mac) and unless I scrolled up and read from the top it was really not obvious what Azure Artifacts are (it ended up being Artifacts tab in the Azure Devops view). I think slightly rewriting the step-by-step guide or adding more pictures would help here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
PR Ref: MicrosoftDocs/azure-devops-docs-pr#3115
