### ISSUE TITLE
Specify allowed parameter values in a separate file

### ISSUE THREAD

**Issue by DigitalTargit** [MicrosoftDocs/azure-devops-docs#8815]
I want to specify the valid parameter values in a separate file.  Is this possible ? As my available builds increase I want to be able to just update this file such that when a deployment job is run 'the values in this separate file of values' are the choices the user can pick from.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790318bb-8220-3241-4ca7-73351074492f
* Version Independent ID: db1da9db-3694-779b-17aa-1ed67fcecf86
* Content: [Use runtime and type-safe parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script)
* Content Source: [docs/pipelines/process/runtime-parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/runtime-parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@DigitalTargit Thank you for the question.

Please see if [templates](https://docs.microsoft.com/azure/devops/pipelines/process/templates?view=azure-devops) can help resolve the issue, or see [this post](https://stackoverflow.com/questions/62383418/how-to-pass-a-list-of-string-parameters-to-an-azure-devops-template) for a similar scenrio.

For further support options, please solicit feedback from the product team at:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
