### ISSUE TITLE
What to do if the project name contains spaces?

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#8816]
Azure DevOps project names can contain blank spaces. The URL formats suggested in here include the "project name" in the URLs. However, the URLs cannot contain spaces. How to handle it?

We tried to leave blank spaces, use underscores, and use percentage encoding `%20` but none seems to work. It would be necessary to specify this in the document. Because right now this document is completely useless if your project happens to have blank spaces in the name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@JoseFMP Thank you for the question.

For product issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit support from the product team, a similar issue was previously posted [here](https://developercommunity.visualstudio.com/content/problem/690605/using-a-space-in-a-project-name-results-in-a-space.html).

Otherwise, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by JoseFMP** [comment]
@msebolt this is a documentation issue. It could also be a product issue, but it is definitely a documentation issue.

Since blank spaces are allowed in projects name's, the documentation of this page should tell what to type in if a project name has blank spaces. So in any case the documentation is missing this part.

**Comment by msebolt** [comment]
@JoseFMP  Thank you for the update.

Have you tried double quotes with encoding, see [here](https://developercommunity.visualstudio.com/content/problem/317522/ssh-clone-url-is-broken.html)?

If so, please add an example use-case and/or provide additional feedback below.

**Comment by JoseFMP** [comment]
@msebolt sorry the link you provided links to an insecure source, I'd rather not visit it. I advise anyone not to visit it as it could be a malicious site:
![image](https://user-images.githubusercontent.com/24405049/103344112-33e8c080-4ac0-11eb-993e-08b461ba9bae.png)

**Comment by vtbassmatt** [comment]
@steved0x when you get to this one -- spaces in the project name are typically encoded as `%20`. Examples:
- https://ORGNAME@dev.azure.com/ORGNAME/Has%20Spaces/_git/Has%20Spaces
- git@ssh.dev.azure.com:v3/ORGNAME/Has%20Spaces/Has%20Spaces

**Comment by PeterSR** [comment]
What about multi-repo pipelines https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops&preserve-view=true where the project or repo has spaces in the name?

**Comment by maitlandmarshall** [comment]
This problem also occurs for me, and I am unable to get it to by wrapping in quotations as @PeterSR mentioned. The pipeline summary page detects the repo correctly, but the agent malforms the URI by replacing the spaces with this %AZP2520:

steps:
  - checkout: "git://Data Warehouse Services/[repo-name]"

`git remote add origin https://[username]@dev.azure.com/[username]/Data%AZP2520Warehouse%AZP2520Services/_git/[repository-name]
git config gc.auto 0
git config --get-all http.https://[username]@dev.azure.com/[username]/Data%AZP2520Warehouse%AZP2520Services/_git/[repository-name].extraheader
git config --get-all http.extraheader
git config --get-regexp .*extraheader
git config --get-all http.proxy
git config http.version HTTP/1.1
git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
`

**Comment by maitlandmarshall** [comment]
No,fix it. It's simple. Your Microsoft. Do it.

**Comment by maitlandmarshall** [comment]
Honestly that's bullshit. Reopen the issue.

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
