### ISSUE TITLE
Request - Report on Release Pipelines

### ISSUE THREAD

**Issue by MarkTimson-BIDev** [MicrosoftDocs/azure-devops-docs#8817]
Would it be possible to create a power bi query that tells you number of pending releases between a pipeline and branch? 
Or any form of reporting on releases pending etc. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c5c777-f210-44b2-8269-0deeea02df9d
* Version Independent ID: a180a164-3ab7-00c7-b525-faff55f3d55f
* Content: [Use OData queries to generate Power BI reports - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-odata-overview?view=azure-devops)
* Content Source: [docs/report/powerbi/sample-odata-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-odata-overview.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@MarkTimson-BIDev Thank you for the question.

Unfortunately the support options in this forum are limited to specific documentation examples only.

Please provide a reference to the documentation below, or use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

For additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
