### ISSUE TITLE
Invalid credential for Azure DevOps Server with ActiveDirectory authentication

### ISSUE THREAD

**Issue by fakhrulhilal** [MicrosoftDocs/azure-devops-docs#8820]
For Azure DevOps Server which's authenticated using ActiveDirectory, you need to use your domain's username and password first. The PAT can be saved in separate command. The full command would be like this
```
nuget sources add -name {your feed name} -source {your feed URL} -username {AD username} -password {AD password}
nuget setApiKey {your PAT} -Source {your feed name}
```
Filling your PAT at first command will make your AD account be locked due to invalid password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0a3735-a9b0-2ed7-f08f-5321f55f8c90
* Version Independent ID: 2153f6c0-def7-eed1-286d-5e61c9fcbec4
* Content: [Use NuGet with Azure DevOps Services feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@fakhrulhilal Thank you for your feedback!
