### ISSUE TITLE
The phases of pipeline expansion

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/azure-devops-docs#8823]
I'm looking for documentation on what steps/phases exist when building a full pipeline. This documentation would explain the difference between queue-time, compile-time and run-time and what happens in each one such as "When are templates 'inserted' into the main pipeline?", "How/when are variables and parameters expanded/resolved?", etc.

I feel like I've seen this somewhere on docs.microsoft.com before, but I can't seem to find it now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c8539-89a7-a426-868b-96e961c39e29
* Version Independent ID: de260a68-aab7-7c6b-6727-90c92c65b225
* Content: [Azure Pipelines New User Guide - Key concepts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops)
* Content Source: [docs/pipelines/get-started/key-pipelines-concepts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/key-pipelines-concepts.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by MisinformedDNA** [comment]
It would be something like [Pipeline run sequence](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline), but more in-depth on how and when variables and templates are evaluated. If a video already exists, that could work too.

**Comment by juliakm** [comment]
This is an older issue. We have details on the difference between the three variable types on the [Define variables page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?tabs=classic%2Cbatch&view=azure-devops#set-variables-in-pipeline) but I'm not sure that it was there when this was posted.
