### ISSUE TITLE
What limits exist on the size and number of pipeline artifacts that can be retained?

### ISSUE THREAD

**Issue by jeffyoungstrom** [MicrosoftDocs/azure-devops-docs#8827]
I don't see anything in the documentation that shows what limits if any there are on the size or number of pipeline artifacts that are allowed? Is there any limit? Is there any additional cost associated with pipeline artifact storage for private Azure DevOps accounts? All my searches take me to the limits for "Azure Artifacts" which I believe is a different thing than "Pipeline Artifacts", correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jeffyoungstrom Thank you for your feedback. You will not be billed by Azure Artifacts for storage of Pipeline Artifacts, Build Artifacts, and Pipeline Caching. See [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops#q-which-artifacts-count-toward-my-total-billed-storage) for more details.

You can also check out the [Azure DevOps pricing tool](https://azure.microsoft.com/pricing/details/devops/azure-devops-services/) for more information.

The updated article will go live shortly.

**Comment by dnnr** [comment]
Does that mean that Pipeline Artifacts storage is unlimited and free of charge?
