### ISSUE TITLE
[Variable Groups] same variable in 2 groups

### ISSUE THREAD

**Issue by arafesthain** [MicrosoftDocs/azure-devops-docs#8829]
It is not clear what will happen if we use 2 variable groups and defined same variable in both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by pemj** [comment]
Unfortunately, your statement is true in a way that the docs can't really fix.  Which is to say, the docs specify that variable collisions across multiple variable groups will lead to undefined behavior, so we're not supposed to do that.

You can find the note here at the [Expansion of variables in a group](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic#tabpanel_CeZOj-G++Q-2_classic) section. Wish I had a more helpful answer for you here :/

**Comment by arafesthain** [comment]
Thanks @pemj to lead for this.

In the meantime we have put variable groups in "less significant" order. So last one take precedence.

We will go for a rename now :)
