### ISSUE TITLE
Switching AAD when having an on-premise agent

### ISSUE THREAD

**Issue by twildeman** [MicrosoftDocs/azure-devops-docs#8830]
When switching Azure AD's, does anything have to be done with for an on-premise agent?

Obviously we have an on-premise agent and, I think, it connects with a PAT. Because these need to be refreshed, this would imply that the PAT for the agent needs to be refreshed as well.

Could you please clear this up for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @twildeman, Thanks for reaching out. A user with appropriate permissions uses their PAT to register an agent with the service. This is a one-time operation and the PAT used to register the agent is no longer used or needed afterward. Further communication between the agent and the service happens through internal tokens and shouldn't depend on changing the Azure AD in the service. In other words, the identity and tokens are managed completely within Azure DevOps, so switching Azure ADs should have no effect. I'm closing this issue, however if you have any further questions please @mention me. Have a great day!
