### ISSUE TITLE
Branch undelete instructions outdate

### ISSUE THREAD

**Issue by Togusa09** [MicrosoftDocs/azure-devops-docs#8834]
The branch page has been updated since this documentation was written. Deleted branches that match the search criteria are now displayed in a "Deleted Branches" section below the active branch results.

![image](https://user-images.githubusercontent.com/4081409/87100794-a5be1b00-c290-11ea-9a91-285314439e27.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops)
* Content Source: [docs/repos/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/restore-deleted-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by kaylangan** [comment]
@steved0x might be able to help with this. I don't work on Azure Repos anymore.
