### ISSUE TITLE
Depreciated option

### ISSUE THREAD

**Issue by DaDarkWizard** [MicrosoftDocs/azure-devops-docs#8836]
-externalFeedCredentials argument should be marked as depreciated, as it does not correctly parse passwords from Service Connections. Instead, a NuGetAuthenticate task should be used.

Explanation:
In a password from a Service Connection, NuGetAuthenticate will correctly transform a '&' to '&amp;amp;' since '&' is an escape character in xml.

-externalFeedCredentials will simply leave the '&' as is, causing an exception to be thrown when restoring the packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@DaDarkWizard Thank you for the feedback.

This argument is currently available per [reference documentation](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetCommandV2/task.json) and will need to be addressed by the product team, please move the issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues).

Including @steved0x for awareness.

**Comment by DaDarkWizard** [comment]
Created the issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues/13290).

**Comment by steved0x** [comment]
This task is marked as deprecated in our new task reference and points to the new task.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#remarks
