### ISSUE TITLE
Variables across stages

### ISSUE THREAD

**Issue by rcomanne** [MicrosoftDocs/azure-devops-docs#8837]
The documentation does not mention it is possible to share variables across pipelines.
Googling this did result in a [StackOverflow](https://stackoverflow.com/questions/57485621/share-variables-across-stages-in-azure-devops-pipelines) post containing comments of some of the developers I think, stating it is now possible.
However, if I just consult the documentation, I would not be aware of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by PaulVrugt** [comment]
the docs need to be updated! I lost half a day searching for this option, only to find the same SO post the @rcomanne mentioned

**Comment by iinatti** [comment]
At chapter [Set a multi-job output variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable) it is stated that "Multi-job output variables only work for jobs in the same stage."
Is this in conflict with the sprint 168 release note: [Jobs can access output variables from previous stages](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-168-update#jobs-can-access-output-variables-from-previous-stages)

**Comment by juliakm** [comment]
Thanks @iinatti! We need to update the docs. I'll push an update today.
