### ISSUE TITLE
Outdate link reference

### ISSUE THREAD

**Issue by abymsft** [MicrosoftDocs/azure-devops-docs#8840]
Link redirects to page not found

Please update this link refernce
https://aka.ms/TFSDataImport

Taken from this page `https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/customize-process?view=azure-devops`

![image](https://user-images.githubusercontent.com/50873759/87184438-4a1f7c00-c2e8-11ea-873a-0128e6d9fe02.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f646c2-3c97-597c-c452-5f12f20c9889
* Version Independent ID: 9481bb73-bc5f-2666-b48c-3fca017ef536
* Content: [Customize a process that imports by using Hosted XML - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/customize-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/customize-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/import-process/customize-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@abymsft - Thank you for the feedback. I have corrected the URL which now points to https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview.
