### ISSUE TITLE
Token for the current date seems missing

### ISSUE THREAD

**Issue by rahg-bmake** [MicrosoftDocs/azure-devops-docs#8842]
Please also include a token for the current day. We already have a token for yyyymmdd. I don't know if its not supported or missing in documentation but we needed a token for just the day (dd) component of the date.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by rahg-bmake** [comment]
ok, there is a day of month token. Missed it.

**Comment by msebolt** [comment]
@rahg-bmake Thank you for the feedback.

If there are any further issues please comment below and we will be glad to update the docs.
