### ISSUE TITLE
apt install for Single container job won't work as per lack of root power

### ISSUE THREAD

**Issue by ahojman** [MicrosoftDocs/azure-devops-docs#8844]
The 'Single container job section' that contains a YAML example with 'apt install' won't work as the service container is not able to do it as root.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @ahojman. There will be new examples shortly.
