### ISSUE TITLE
*Which Tasks* are supported by server (aka agentless) jobs?

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/azure-devops-docs#8846]
Please link to or document the tasks that are supported by agentless jobs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#server-jobs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Fixed in this issue - https://github.com/MicrosoftDocs/azure-devops-docs/issues/8875.

**Comment by brandonh-msft** [comment]
@juliakm that issue is marked as duplicate of this one and closed...
