### ISSUE TITLE
Dead link behind Agile Retrospective Resource Wiki

### ISSUE THREAD

**Issue by arkadios** [MicrosoftDocs/azure-devops-docs#8851]
It seems there is a dead link to https://retrospectivewiki.org/ on [this page](https://docs.microsoft.com/en-us/azure/devops/boards/plans/practices-that-scale?view=azure-devops#organizational-culture) behind the "Agile Retrospective Resource Wiki" hyperlink. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f18878c-f4a9-1af1-9145-7d07bd85da4e
* Version Independent ID: 54c95b3f-795b-a602-35a9-394ee5c75a5c
* Content: [Practices that scale - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/practices-that-scale?view=azure-devops)
* Content Source: [docs/boards/plans/practices-that-scale.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/practices-that-scale.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@arkadios - Thank you for the feedback. I'm updating the article to point to the correct link, [Agile Retrospective Resource Wiki](https://retrospectivewiki.org/index.php?title=Agile_Retrospective_Resource_Wiki).
