### ISSUE TITLE
Confused about classic mode

### ISSUE THREAD

**Issue by unionthugface** [MicrosoftDocs/azure-devops-docs#8856]
I inherited an Azure Devops pipeline in classic mode.  If I go to the `Variables` tab and type in some variables, how do I access these in classic mode?  Is it `$(Parameters.NameOfParameter)` or is it just `$(NameOfParameter)` or neither?  What do I do about the "Scope" in the Release part of the pipeline?  I have the same task to deploy several different host bindings to IIS, and I would like to scope a `$(Host)` variable to each task.  Is it `$(Parameters.Host)`?  Is it `$(Parameters.Scope.Host)` or some such thing?  I tried setting it up as a variable for an IIS binding, and it deployed literally as "http:\\$(Parameters.Host)" into IIS.  Would love more documentation about the `Variables` tab in classic mode, complete with some pictures.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops-2019&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@unionthugface I apologize for the delay in responding. There is more information on using classic variables in the [Classic release and artifacts variables article](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#using-default-variables).
