### ISSUE TITLE
Move Pull Requests along with git repos?

### ISSUE THREAD

**Issue by webwesen** [MicrosoftDocs/azure-devops-docs#8858]
Is there any way to migrate PRs along with git repos?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b779541e-e77e-38e7-7134-fa1f4c698899
* Version Independent ID: fe82ec27-4640-d0f2-3978-01400e2b719b
* Content: [Move Git repositories between Team Projects - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/repos/git/move-git-repos-between-team-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/move-git-repos-between-team-projects.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @wpschaub
* Microsoft Alias: **apawast**

**Comment by craigb** [comment]
I have lots of information in PRs in a Project that we want to migrate to our main project. Just moving the repo is going to orphan all that information. :( Are there any ways to migrate the PR data to the main project with the repo?
