### ISSUE TITLE
Bulk linking items

### ISSUE THREAD

**Issue by paulmatheson** [MicrosoftDocs/azure-devops-docs#8859]
The part on bulk linking items isn't working for me. When you select multiple items and click "link and attach..." it only recognizes the first item you clicked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify work items using Microsoft Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@paulmatheson  -  Thank you for your feedback. I will update the article to clarify. You can only bulk update parent-child links using a tree list. When working with the Links and Attachments dialog, you can only update a single work item at a time.
