### ISSUE TITLE
pipeline to pipeline artifact transfer

### ISSUE THREAD

**Issue by flipm1967** [MicrosoftDocs/azure-devops-docs#8862]
Are you sure this statement is true? We do this! (presuming you mean build yaml to build yaml). Anyway I think this statement needs clarifying with regards to build and release pipelines.
**_"At present, you cannot download artifact produced by a YAML pipeline in another YAML pipeline."_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@flipm1967 Thank you for your feedback. Statement removed ✔
