### ISSUE TITLE
Confusing statement and alternate credentials is no longer

### ISSUE THREAD

**Issue by mattcowen** [MicrosoftDocs/azure-devops-docs#8863]
"Enable Azure Active Directory (Azure AD) Conditional Access Policy (CAP) validation - this policy is set to off by default and only applies to alternate credentials. This policy doesn't apply for CAPs set in Azure AD, no matter the settings in Azure DevOps."

Alternate credentials is no longer a feature of Azure DevOps as of March - https://devblogs.microsoft.com/devops/azure-devops-will-no-longer-support-alternate-credentials-authentication/

This statement is also quite confusing. The feature indicates enabling AAD CAP but then says it doesnt. What does it do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18e09c1-5c84-4fd6-9d62-2299a3bd53cd
* Version Independent ID: c1627714-5e55-1be0-4ba5-63f264b96e5c
* Content: [Change application access, security policies for organizations - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/change-application-access-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-application-access-policies.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by mattcowen** [comment]
Normal users of Azure DevOps are triggering CA rules too so it would appear not to apply to only alternate credentials.

**Comment by chcomley** [comment]
I've just published updates, which should be live shortly. Thank you!
