### ISSUE TITLE
future roadmap of process customization scripts

### ISSUE THREAD

**Issue by FrancescoSclano** [MicrosoftDocs/azure-devops-docs#8864]
I'd like to know if https://github.com/microsoft/process-customization-scripts is compatible/properly working with Visual Studio 2019 libraries released by Microsoft on May 24th 2019 ? In other words, will these scripts work with DevOps 2020? Will these scripts be replaced by some other new scripts or by some new integrated functionality in DevOps 2020?
In essence I'd like to know the future roadmap of these scripts.

Thanks

Francesco Sclano

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20e7fb4b-29e6-95b4-001c-7cffd985039d
* Version Independent ID: 24d7d477-d998-7544-a8f4-456f37698408
* Content: [Validation of process templates for migration import from https://marketplace.visualstudio.com/items?itemName=ms.feed# to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-processtemplates?view=azure-devops)
* Content Source: [docs/migrate/migration-processtemplates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-processtemplates.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@FrancescoSclano - Thank you for your inquiry. Please contact this email  **vsocustpt@microsoft.com** for questions about the scripts. THere are no plans to replace these scripts at this time and they should work for Azure DevOps 2020.  I'm not sure what the scripts have to do with Visual Studio 2019 libraries released by Microsoft on May 24th 2019.  These scripts are used on process templates for Azure DevOps Server.
