### ISSUE TITLE
Wrong variable naming in 'Output Variables'

### ISSUE THREAD

**Issue by DSpirit** [MicrosoftDocs/azure-devops-docs#8866]
In the section [Support for output variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables) there is following snippet:

> When you define an environment in a deployment job, the syntax of the output variable varies depending on how the environment gets defined. In this example, **env1** uses shorthand notation and **env2** includes the full syntax with a defined resource type.

```stages:
- stage: MyStage
  jobs:
  - deployment: A1
    pool:
      vmImage: 'ubuntu-16.04'
    environment: env1
    strategy:                  
      runOnce:
        deploy:
          steps:
          - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
            name: setvarStep
          - script: echo $(System.JobName)
  - deployment: A2
    pool:
      vmImage: 'ubuntu-16.04'
    environment: 
      name: env1
      resourceType: virtualmachine
```

But I couldn't find the specified env2 variable - maybe you have entered the same '**env1**' twice.
Furthemore I'd be glad if there would be an example of how to pass:
`<Stage>.<Deployment>.<Step>.<Variable>`
output variables from one stage to another, as I'd like to have a conditional deployment for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @DSpirit. We've fixed [this example](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#support-for-output-variables).
