### ISSUE TITLE
Please update this answers for SSH keys

### ISSUE THREAD

**Issue by bbkane** [MicrosoftDocs/azure-devops-docs#8867]
For https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page#q-after-running-git-clone-i-get-the-following-error-what-should-i-do , The current answer is: `ssh-keyscan -t rsa domain.com >> ~/.ssh/known_hosts`. I think it should be `ssh-keyscan -t rsa ssh.dev.azure.com >> ~/.ssh/known_hosts`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by bbkane** [comment]
Welp, guess this isn't gonna happen

**Comment by WilliamAntonRohm** [comment]
@bbkane -- Benjamin, thank you for your follow-up.  I'm updating the article.
