### ISSUE TITLE
FileTransform V2 Task not documented

### ISSUE THREAD

**Issue by afscrome** [MicrosoftDocs/azure-devops-docs#8871]
The FileTransform task appears to be up to version `2.0.8`, but the documentation still points to `FileTranform@1`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by Compufreak345** [comment]
I think this issue should get new awareness, as the v1 task is broken right now and it feels wrong to use an undocumented V2 as the proposed workaround:

https://github.com/microsoft/azure-pipelines-tasks/issues/16821

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/file-transform-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
