### ISSUE TITLE
List of ContributionTypes

### ISSUE THREAD

**Issue by davidsk** [MicrosoftDocs/azure-devops-docs#8873]
The documentation specifies that a contribution must specify the type property which is one of a set of predefined
values (contributionTypes) but these types do not appear to be listed anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca79d381-fbe3-ca3c-1d31-5b9062b203e4
* Version Independent ID: c7ba047c-c71e-abb7-191b-f6f029f780ef
* Content: [Contributions Model Fundamentals - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/contributions-overview?view=azure-devops)
* Content Source: [docs/extend/develop/contributions-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/contributions-overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @davidsk, Please try [this site](https://developercommunity.visualstudio.com/spaces/21/index.html) for further information. If it doesn't help, please @mention me and I'll follow up. Thanks so much for reaching out!
