### ISSUE TITLE
"Only a few tasks are supported in a server job at present." which ones?

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/azure-devops-docs#8875]
> Only a few tasks are supported in a server job at present.

Please list which are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@VictorioBerra Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8846.

Please refer there for futher updates.
