### ISSUE TITLE
Are there any comparison chart on Azure DevOps Server Vs Azure DevOps Service Vs GHE Cloud/Server?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/azure-devops-docs#8877]
Current recommendation for customer who are working on DevOps Strategy is to use Azure DevOps Service + GitHub Enteprise Cloud (GHE) or Server.  However we do not seem to have a document that compare all these offering for organization to plan better for future. Can we add this document somewhere? Or if it exist, then I would like to know the link.

Another question routinely asked is what is the road-map for Azure DevOps Server or Service as everything moving to GHE in future. How to find the answer to this question?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808dac3a-225a-f564-ea5e-de6bad168da4
* Version Independent ID: decabfe6-ae8d-183c-3698-acb829da81f5
* Content: [Understand differences between Azure DevOps Services and Azure DevOps Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops)
* Content Source: [docs/user-guide/about-azure-devops-services-tfs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/about-azure-devops-services-tfs.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Anand-Moghe. For information about the Azure DevOps Feature Timeline, you can go [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline). As for further information about comparisons with GH, I unfortunately don't have any. If you have any further questions, I'd recommend contacting your Microsoft representative and accessing the Developer Community [here](https://developercommunity.visualstudio.com/spaces/21/index.html). Thanks for  reaching out.
