### ISSUE TITLE
What are the "feed users"

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/azure-devops-docs#8878]
Hello,
on the referenced page it says:
"After restricting your view's visibility, the permissions column should indicate that your view is only available to feed users."

What are the "feed users"? Are these the users that have been defined in the Feed permissions?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@MTomBosch Thank you for reaching out. "Feed users" are users who have access to your feed. When you change your view permissions to `specific people`, the permissions column should reflect the new users/groups added. One thing to keep in mind is that if you select `Specific people` without specifying users or groups, view permissions will default back to the feed permissions.
