### ISSUE TITLE
Incorrect documentation for release retention policies

### ISSUE THREAD

**Issue by jd-porter** [MicrosoftDocs/azure-devops-docs#8879]
The documentation is no longer correct when it comes to release retention 

> As an author of a release pipeline, you can customize retention policies for releases of your pipeline on the Retention tab.
> The retention policy for YAML and build pipelines is the same. You can see your pipeline's retention settings in Project Settings for Pipelines in the Settings section.

-- these settings are now read-only for ADO projects, as seen below. We have no way to customize release retention policies right now. 

![image](https://user-images.githubusercontent.com/14062459/87724528-dd3d3380-c778-11ea-9c04-b478249e8ae8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@jd-porter  Thank you for the feedback.

This issue was previously noted under https://github.com/MicrosoftDocs/azure-devops-docs/issues/3822.

Please refer there for further updates.
