### ISSUE TITLE
"Search for exact match in deleted branches" option doesn't appear

### ISSUE THREAD

**Issue by devyzr** [MicrosoftDocs/azure-devops-docs#8881]
"Search for exact match in deleted branches" option doesn't appear either in chrome or in firefox. The only extension I have enabled in chrome is Lastpass and I've already tried deactivating all the plugins in firefox to no avail. I have not tried in edge because I work on Ubuntu.
![Screenshot from 2020-07-16 18-21-46](https://user-images.githubusercontent.com/14828684/87731938-42048800-c791-11ea-8c47-5e676ec5c34e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2f7bb6-eca8-ba34-0595-3bf2ec7c0e0f
* Version Independent ID: 28093f80-26b9-b9f8-0d5d-639c1da1f493
* Content: [Restore a deleted branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops)
* Content Source: [docs/repos/git/restore-deleted-branch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/restore-deleted-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @kaylangan
* Microsoft Alias: **kangan**

**Comment by kaylangan** [comment]
@steved0x might be able to help. I don't work on Azure Repos anymore.

**Comment by whenmoon** [comment]
I have the same problem. This documentation is wrong because the option to "Search for exact match in deleted branches" does not exist: https://docs.microsoft.com/en-us/azure/devops/repos/git/restore-deleted-branch?view=azure-devops&tabs=new-nav&viewFallbackFrom=vsts

**Comment by steved0x** [comment]
This appears to be built-in to the search now, if you search branches with an exact match for a deleted branch name, it shows up below the active branches results and you can restore it from there. If the search term isn't an exact name for the deleted branch, it won't show up in the list. I will get this documentation updated.
![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1580889/e36d460c-0417-460e-bee0-19291d5f6256)

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
