### ISSUE TITLE
Prerequisites - Global Admin isn't required, lower privilege roles will allow for the creation of users.

### ISSUE THREAD

**Issue by azureguy-ni** [MicrosoftDocs/azure-devops-docs#8886]
Prerequisites - indicates you need to be a Global Admin to add users to the directory, this isn't necessarily required as other roles, i.e. User Administrator would also provide rights to do this and better fits the principal of least privilege.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ce0e03-d28d-f0c7-9cc4-f89b0768ebe4
* Version Independent ID: 76e3bd85-325b-7a66-446b-163694d438bd
* Content: [Add, delete organization users in Azure Active Directory tenant - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-users-to-azure-ad?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-users-to-azure-ad.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-users-to-azure-ad.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ramrajesh** [comment]
@chcomley I think the whole documentation is outside the scope of Azure DevOps and must be removed. Customers should rely on docs from the Azure AD team for adding/removing users to/from the tenant. At least, remove the sections of the doc where we are showing Azure portal experiences and instead link it to a doc on their side.

**Comment by chcomley** [comment]
Will do, thank you @ramrajesh. @azureguy-ni, thanks so much for your feedback. I've created a user story for my backlog to address this fix. Thanks again!
