### ISSUE TITLE
PATs with Git and IIS Basic Does Not Work for Azure DevOps 2019

### ISSUE THREAD

**Issue by TheBritz** [MicrosoftDocs/azure-devops-docs#8890]
The suggested approach of utilizing a PAT with Git on our IIS Basic enabled Azure DevOps 2019 server does not work. The base64-encoded user:PAT combination always results in authentication failure.

Base64-encoded user:Password combination does work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fa3b01-218c-9a5f-5b71-affdf65c945c
* Version Independent ID: 7c414686-f52d-51ce-87e1-794deade8506
* Content: [IIS Basic Authentication invalidates using PATs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/iis-basic-auth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/iis-basic-auth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/iis-basic-auth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback @TheBritz. I'm looking into this and will be in touch. Thanks!

**Comment by chcomley** [comment]
Following up on this, the article was updated and this issue was addressed, however not closed. Closing now. Thanks for the feedback!
