### ISSUE TITLE
Please remove the color from this article.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8891]
"Git has many benefits"

It has more negatives than benefits when compared to TFVC, unless you live/work in a fourth/fifth world country and have to be disconnected most of the time. Even then there are local workspaces. 

Rather than start a pointless holy war (that git would lose =D) please leave articles like this without the fervor, zealotry, excitement, and evangelizing. Stick to the topic without editorializing or creating or serving bias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24126ce-abfc-07d0-ceea-51534f745e55
* Version Independent ID: 60861ae7-4b6d-e360-8ab7-28b276326569
* Content: [Import repositories from TFVC to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-tfvc?view=azure-devops)
* Content Source: [docs/repos/git/import-from-TFVC.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-from-TFVC.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **atinb**

**Comment by steved0x** [comment]
I'll update that sentence to say "Migrating to Git is an involved process for large TFVC repositories and teams." - should be live later today.
