### ISSUE TITLE
Needs clarification: Set up credentials for scoped registry

### ISSUE THREAD

**Issue by GiriB** [MicrosoftDocs/azure-devops-docs#8892]
In the [Set up](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows#set-up) section,  the article says "append your scope to both lines in the project .npmrc file". However there us no example. Which two lines are we talking about? The `.npmrc` in the `$HOME` dir can have several lines. Where do we need to append?

![image](https://user-images.githubusercontent.com/6178383/87869363-cc7cff80-c9bc-11ea-8ed7-387d688d4f88.png)

The article needs examples particular to using scopes. Otherwise the rest of the article is same as [setting up auth for non-scoped registries](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#linux-or-mac).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484077fa-696c-63e1-a4ba-f2680d076bfd
* Version Independent ID: aa0f98e6-6b82-a848-de65-0c39af8f8650
* Content: [Use npm scopes for private packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/npm/scopes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/scopes.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@GiriB Thanks for your feedback! I'm updating this shortly
