### ISSUE TITLE
Are defaults `NuGet.config` used when specifying a `nugetConfigPath`?

### ISSUE THREAD

**Issue by lmorvan** [MicrosoftDocs/azure-devops-docs#8895]
Hi!
According to [this issue in dotnet core CLI](https://github.com/dotnet/docs/issues/19532), when specifying a *NuGet.config* file through the "configfile" option, the defaults NuGet.config files from the system are just ignored, hence also ignoring the local `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\` folder.

Does the *.Net Core CLI task* use this option when specifying a `nugetConfigPath` and thus makes the "dotnet restore" ignoring all system-wide *NuGet.config*?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@loicmorvan-ansys Thank you for the question.

Yes, according to documentation this is the set behavior, see `DotNetCoreCLI@2` task [documentation](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2).

If you find this is inconsistent with results, please start an issue in the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo for further investigation.

**Comment by loicmorvan-ansys** [comment]
I don't find the documentation very explicit about that point.
But I have an answer to my question, thank you!
