### ISSUE TITLE
Page outdated/not consistent with current version

### ISSUE THREAD

**Issue by sderungs** [MicrosoftDocs/azure-devops-docs#8896]
The following sections are either extremely outdated, or they lack steps to get to the corresponding screens shown on the screenshots:
* Add members to the custom security group
* Set permissions for build pipelines
* Add and set permissions for the custom security group

Either way, the guide is somewhat useless at the moment as it's not clear how Stakeholder access to pipelines (for release approvals) needs to be configured (as it should be possible described in the table here: https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops#default-permissions-assigned-to-built-in-security-groups).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954f4dc2-be98-46f5-1771-4cef3ba527bc
* Version Independent ID: b63d6819-4b5e-c1f3-5d49-83e9690f658b
* Content: [Provide free access to pipelines for Stakeholders - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/provide-stakeholder-pipeline-access?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/provide-stakeholder-pipeline-access.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/provide-stakeholder-pipeline-access.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sderungs  - Thank you for your feedback. Indeed the images did get out of date. Our apologies.  I'm updating the article today and it should be viewable by tomorrow.
