### ISSUE TITLE
Provide complete, correct instructions for deploying on Linux

### ISSUE THREAD

**Issue by cpdohert** [MicrosoftDocs/azure-devops-docs#8898]
The instructions on this page were demonstrably not tested on anything but Windows VMs.

"4. Choose Windows or Linux for the Operating System."
"6. Run the copied script from an administrator PowerShell command prompt".

Choosing the Linux operating system and running the script in /opt after running `sudo su` throws a "Must not run with sudo" error.  Is there some *other* way of running commands as root on a stock Ubuntu Azure VM?

If I run without `sudo su` in ./opt I get permission denied errors because obvious the default user doesn't have write perms in /opt.

If I run the script in $HOME everything works but now the agent is installed in the default user's home directory and runs under that user context, which means I have to mess round with sudoers in order to send commands to the VM.

There's clearly a lot of assumptions about how this script ought to be deployed to Linux VMs that aren't documented here, and they need to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@cpdohert I'm sorry for the delay in responding. You're right and I'll work on getting more Linux instructions. For testing when updating this article, my agent is installed in the home directory at `/home/azuretest/azagent`. For comparison, the Windows install is at `C:\azagent\A3`.
