### ISSUE TITLE
My pipeline errored out on 'Job Python37', 'Install Dependencies'

### ISSUE THREAD

**Issue by awshumway** [MicrosoftDocs/azure-devops-docs#8899]
I was trying to follow these docs to create my first Azure Devops Pipeline. 
The error arose in the Job Python37 on step 'Install Dependencies'. The error looked like this:

```
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.7.8/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z6hn0gc9/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z6hn0gc9/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q7y7t84z
         cwd: /tmp/pip-install-z6hn0gc9/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z6hn0gc9/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

##[error]Bash exited with code '1'.
```

I was able to resolve this error after researching the [MarkupSafe project](https://pypi.org/project/MarkupSafe/) which is currently on version `1.1.1`, whereas the sample code uses version `1.0`. I updated the version number to 1.1.1 in the `requirements.txt` file, and the problem was fixed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=python%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
@awshumway I think that this was an issue with the [sample repository](https://github.com/microsoft/python-sample-vscode-flask-tutorial) that has since been resolved. Closing the issue but let me know if that's not the case.
