### ISSUE TITLE
Slightly misleading documentation of DownloadBuildArtifacts `pipeline` parameter

### ISSUE THREAD

**Issue by tibortakacs** [MicrosoftDocs/azure-devops-docs#8901]
The YAML snipplet with example writes that the `pipeline` parameter is to set the pipeline:
`#pipeline: # Required when buildType == Specific`

The parameter description section below it, however, mentions `definition` parameter:

Argument | Description
-- | --
`definition` Build pipeline | (Required) Select the build pipeline name. Argument aliases: pipeline

I understand that the doc also mention the `pipeline` alias, however, it took me long to realize the fact why I could not find the `pipeline` parameter in the first column if the example uses it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
