### ISSUE TITLE
Documentation not available for Data storage REST APIs (Extension Management)

### ISSUE THREAD

**Issue by saleelpk95** [MicrosoftDocs/azure-devops-docs#8902]
The [documentation ](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops)for the data storage service of Azure DevOps extension talks about the [REST APIs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0&viewFallbackFrom=azure-devops) very briefly. What all operations are supported by the REST APIs or how to consume them is not mentioned anywhere.

![image](https://user-images.githubusercontent.com/15182468/88037698-e5bfb080-cb62-11ea-8c9b-881a1bdceabe.png)

**Comment by chcomley** [comment]
HI @saleelpk95, Thanks for reaching out. The following links will hopefully help. Try the [Azure DevOps REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0), and then try [Get started with REST APIs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0#client-libraries).  Please @mention me if you have any further questions. Thank you!

**Comment by saleelpk95** [comment]
> HI @saleelpk95, Thanks for reaching out. The following links will hopefully help. Try the [Azure DevOps REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0), and then try [Get started with REST APIs](https://docs.microsoft.com/

> HI @saleelpk95, Thanks for reaching out. The following links will hopefully help. Try the [Azure DevOps REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0), and then try [Get started with REST APIs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0#client-libraries). Please @mention me if you have any further questions. Thank you!

@ch

> HI @saleelpk95, Thanks for reaching out. The following links will hopefully help. Try the [Azure DevOps REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0), and then try [Get started with REST APIs](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.0#client-libraries). Please @mention me if you have any further questions. Thank you!

@chcomley 
The APIs I have mentioned are not a part of the documentation. I have however figured out how to do it. I'll reply back with the details so that it could help the community. It'd be great if the same can be added to the documentation.

**Comment by chcomley** [comment]
@saleelpk95 Absolutely! I'll update the documentation accordingly, once you've commented with your solution. Thanks so much for helping the community! We all appreciate it!
