### ISSUE TITLE
Prevent users from creating PBI

### ISSUE THREAD

**Issue by motim6026** [MicrosoftDocs/azure-devops-docs#8903]
Hi
I wanted to know if there is an option in Azure DevOps to prevent a certain group of users from creating PBI.
We still want to give them the ability to create a Task \ Bug just to prevent PBI creation

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6c4f97-f052-6edc-ae5c-e6774115ca16
* Version Independent ID: 691ceef1-fe38-cc6e-7d67-5ea7140222bd
* Content: [Trace permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-trace-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/faq-trace-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/faq-trace-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by alsulli** [comment]
@motim6026 It is possible, but it isn't an actual permission setting. To achieve this you would need to take all of the users that you don't want to be able to create a PBI, and create a new Azure DevOps group (Org settings --> Permissions --> New group).

From there, you'd add all the users to that new group. Next proceed to Org settings --> Process. Select the process where the PBI in question sits (likely an inherited process). You would then select the PBI work item type --> Rules. Add a rule that looks something like this:
![image](https://user-images.githubusercontent.com/60909919/88392189-94453a80-cd89-11ea-91d3-cc74df2dff0d.png)

All users in that group will then get an error when trying to save the work item in question. "The field 'State' contains the value 'New' that is not in the list of supported values.":
![image](https://user-images.githubusercontent.com/60909919/88391875-00736e80-cd89-11ea-9e14-101046bd2f86.png)

**Comment by motim6026** [comment]
Hi, 
I will check this. 
Thank you
