### ISSUE TITLE
Explicitly call out the need for a Public IP on the Azure VM

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/azure-devops-docs#8906]
Hi Team,

I've read through this and there are 2 spots that it feels like we need to make sure to call out the fact the Azure SQL VM must have/use a Public IP address, (I've had more than 1 customer where this was a blocker they opened a ticket for.

Place 1, where we call out VM level suggestions:
```
Below are some additional recommended configurations for your SQL Azure VM.

1. It's recommended that D Series VMs be used as they're optimized for database operations.
2. Ensure that the D Series VM has at least 28GBs of ram. Azure D12 V2 VM sizes are recommended for imports.
3. Configure the SQL temporary database to use a drive other than the C drive. Ideally this drive should have ample free space; at least equivalent to your database's largest table.
4. If your source database is still over 1TB after reducing the size then you will need to attach additional 1TB disks and combine them into a single partition to restore your database on the VM.
5. Collection databases over 1TB in size should consider using Solid State Drives (SSDs) for both the temporary database and collection database.
```
can we add a 6.  "You need to have a public facing IP address for the service to reach this machine."

The other place it would be good to call this out is:
https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#configure-the-import-specification-file-to-target-the-vm

even something as simple as changing the wording of the sample:
"Properties":
{
    "ConnectionString": "Data Source={SQL Azure VM **Public** IP};Initial Catalog={Database Name};Integrated Security=False;User ID={SQL Login Username};Password={SQL Login Password};Encrypt=True;TrustServerCertificate=True" 
}

would help to make this clearer.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#generate-import-files)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SamGrantham - Thank you for these suggestions. I'm updating the article today.
