### ISSUE TITLE
Add Link to Define variables

### ISSUE THREAD

**Issue by jangaehler** [MicrosoftDocs/azure-devops-docs#8908]
It would have saved me a lot of time if this would explain directly how to make secrets available as env variables. After hours of searching I found this comment, which gave me the right hint.
https://developercommunity.visualstudio.com/comments/691809/view.html

**Something like this**

## Make secrets available in Tasks as Env Variables

Secret variables (encrypted variables and key vault variables) cannot be accessed directly in scripts - instead they must be passed as arguments to a task

Choose the task, click on Environment Variables. Click on "Add".

Name: some_secret_env_var
Value: $(someSecretEnvVar)

For more information, see [secrets](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Using secrets from Azure Key Vault in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @EdKaim
* Microsoft Alias: **v-edkaim**

**Comment by EdKaim** [comment]
We're not currently engaged on this project.

**Comment by msebolt** [comment]
@steved0x @thomps23 Please reassign.

**Comment by ramiMSFT** [comment]
@jangaehler Thank you for your feedback. The updated article will go live shortly.
