### ISSUE TITLE
Will the number of work items using User Stories and/or Bugs affect the storage?

### ISSUE THREAD

**Issue by jandyllaguno** [MicrosoftDocs/azure-devops-docs#8911]
Hi - I would like to ask if the total of Work Items (regardless of its Stage) will affect the storage? In the project that I have created, my team is using mostly user stories and bugs to document our tasks and we already have a lot of closed tasks the we wish to keep in the project and not delete it immediately so that we can go back to those if necessary.

Currently, we already have 7,000 closed user stories + bugs while we have around 200+ active on average daily.

Thanks much for your help in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Start Using Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jandyllaguno Thank you for the question.

Please refer to [Limits](https://docs.microsoft.com/azure/devops/organizations/settings/work/object-limits) documentation and post any further questions below.
