### ISSUE TITLE
Work Items Inquiry

### ISSUE THREAD

**Issue by jandyllaguno** [MicrosoftDocs/azure-devops-docs#8912]
Hi!

I would like to clarify something about the work items and bugs. 

As a background, I have created a project and there were concerns about the number of work items that we can keep on the project. I stumbled upon this page before and I may have misunderstood the "10,000" items limit for backlogs.

Can I get a confirmation please that the 10,000 backlog limit DOES NOT include the ones with "Closed" stage?

Also, I would like to ask WHAT it is actual limit (if there is) of work items + bugs counts that we can keep in the project especially those with "Closed" stages? 

Reason for asking is that we use the project for tracking multiple tasks/updates and for the past months,  I have been deleting work items in the system once we are close to hitting the 10,000 mark and it somehow limits the query functionality since we have to remove the tickets in the system.

Note: In the project that I have created, we have around 200+ (max) user stories and bugs open on average per work day and the tickets with "Closed" stage is currently around 7,000 (which we want to keep in the system and not delete if possible).

Thank you so much for the help in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4956039a-8296-c5e7-107e-9f42f1e39f33
* Version Independent ID: aae5a90e-0fc7-ed33-0936-10e37782d0dc
* Content: [Work tracking, process, and project limits - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops#backlogs-boards-and-teams)
* Content Source: [docs/organizations/settings/work/object-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/object-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jandyllaguno Thank you for the question, please refer to [this post](https://stackoverflow.com/questions/60711596/is-there-a-limit-of-max-10000-work-items-per-backlog) for further information.

If additional guidance is needed, please try the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) 
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@jandyllaguno - THe 10,000 limit is only applicable to the number of work items that can appear on any one backlog. The total number of work items you can have in a project or collection doesn't have a practical limit. It's only limited by the limit of Integer data type which is 32-bit signed integer value.
