### ISSUE TITLE
Resources: webhooks. Please document how the secret is used to compute the payload hash.

### ISSUE THREAD

**Issue by davidjward30** [MicrosoftDocs/azure-devops-docs#8913]
Re:

"Resources: webhooks

Secret - The secret is used to parse the payload hash used for verification of the incoming request (this is optional). If you have used a secret in creating your webhook, you will need to provide the same secret key"

Please document how the secret is used to computer the payload hash as any client invoking the webhook needs to know. Based on the reference to github, it seems to based on HMACSHA1 but this should be stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-webhooks)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Saugat168** [comment]
I second this. There is absolutely no documentation and when things fail, we have no clue why. Right now, while trying an incoming webhook service connection in Azure DevOps. Whenever I try to use the Request Header and the secret , I just get a payload hash does not match. Therefore it is very important to know, how is this calculated.

Is it calculated somewhat like the following?

`
body = request.body.encode('utf-8')
h = hmac.new(secret, body, hashlib.sha256)
finalvaluetomatchagainstthehttpheader= h.hexdigest()
`

**Comment by pmthexton** [comment]
Same problem for me. I'm trying to post to an incoming webhook service conection on an azure devops instance from SonarQube.  I've configured the webhook to look for the header that sonarqube posts to (X-Sonar-Webhook-HMAC-SHA256), and the secret is set as the same value in azure devops and sonarqube.

SonarQube shows that the call to the webhook was rejected with error 500 but unhelpfully doesn't report the actual error.

I created a bash script to compute the SHA256 hmac and post to the web hook using curl and the body returned indicates that the hash doesn't match.

I'm not sure what to try next..

**Comment by oliverisaac** [comment]
Here is a sample webhook usage using jq/curl. 

```
#!/usr/bin/env bash
azdo_org="${AZDO_ORG:?You must define AZDO_ORG}"
webhook_name="${AZDO_WEBHOOK_NAME:?You must define the azdo webhook name}"

azdo_url="https://dev.azure.com/$azdo_org/_apis/public/distributedtask/webhooks/$webhook_name?api-version=6.0-preview"
azdo_secret="${azdo_secret:-${AZDO_WEBHOOK_SECRET:?You must define AZDO_WEBHOOK_SECRET}}"
azdo_header_field="${azdo_header_field:-${AZDO_HEADER_FIELD:-You muset define AZDO_HEADER_FIELD}}"

post_data=$( jq -n --arg waitMinutes 10 --argjson targets "${targets_json:-[]}" '{ waitMinutes: $waitMinutes, targets: $targets }' )

# Generating the hash for security 
hash_value=$( echo -n "$post_data" | openssl sha1 -hmac "$azdo_secret" )

Note the headers
out=$( curl -v -X POST -d"$post_data" -H "Content-type: application/json" -H "$azdo_header_field: $hash_value" "$azdo_url" )
if ! echo "$out" | jq .; then
    echo "$out"
fi

```

**Comment by pmthexton** [comment]
Thanks @oliverisaac, I can get it to work in a shell script now (I was generating a hmac digest, dropping the dgst argument from the openssl command worked) - still refuses to work when sonarqube posts though. never mind. I guess SonarQube / Microsoft simply disagree on how webhook authentication should work.

**Comment by edgBR** [comment]
Hi guys I have been struggling with this for weeks.

I have been able to setup my webhook correctly and add it to a yaml pipeline. I am able to call the webhook using postman when the authentication is not set but when I do setup the fields for the secret and the header field to check I am unable to trigger the pipeline.

I have follow all of the instructions but I am getting the following error:

```
{ [297 bytes data]
100   342  100   297  100    45   1047    158 --:--:-- --:--:-- --:--:--  1208
* Connection #0 to host dev.azure.com left intact
{
  "$id": "1",
  "innerException": null,
  "message": "(stdin)= 0c9457101ababf8ee2bbacc082286657d6f0bd97 could not be converted. A valid hexadecimal encoding of bytes will have an even number of hexits.",
  "typeName": "System.ArgumentException, mscorlib",
  "typeKey": "ArgumentException",
  "errorCode": 0,
  "eventId": 0

```
Any clue of what is going on here?

BR
E

**Comment by reespozzi** [comment]
> Here is a sample webhook usage using jq/curl.
> 
> ```shell
> #!/usr/bin/env bash
> 
> azdo_org="${AZDO_ORG:?You must define AZDO_ORG}"
> webhook_name="${AZDO_WEBHOOK_NAME:?You must define the azdo webhook name}"
> 
> azdo_url="https://dev.azure.com/$azdo_org/_apis/public/distributedtask/webhooks/$webhook_name?api-version=6.0-preview"
> azdo_secret="${azdo_secret:-${AZDO_WEBHOOK_SECRET:?You must define AZDO_WEBHOOK_SECRET}}"
> azdo_header_field="${azdo_header_field:-${AZDO_HEADER_FIELD:-You muset define AZDO_HEADER_FIELD}}"
> 
> # Generate a JSON payload
> post_data=$( jq -n --arg waitMinutes 10 --argjson targets "${targets_json:-[]}" '{ waitMinutes: $waitMinutes, targets: $targets }' )
> 
> # Generating the hash for security 
> hash_value=$( echo -n "$post_data" | openssl sha1 -hmac "$azdo_secret" )
> 
> # Note the headers that are set
> out=$( curl -v -X POST -d"$post_data" -H "Content-type: application/json" -H "$azdo_header_field: $hash_value" "$azdo_url" )
> if ! echo "$out" | jq .; then
>     echo "$out"
> fi
> ```
> 
> Of note, if you get an error like:
> 
> ```
> Cannot find webhook for the given webHookId MyWebhookName. Try enabling CD trigger for this artifact.
> ```
> 
> then you need to [run the pipeline manually at least once before it will register with the service connection.](https://developercommunity.visualstudio.com/t/cannot-use-generic-webhook-based-triggers-for-yaml/1135943#T-N1203277)

If anyone is still having this issue after having to rename, delete and recreate, or any other changes to their service connection - manually triggering the pipeline with the new changes also resolved this for me. 
In some cases, my incoming webhook endpoint was still connected to the old service connection ID (somehow). In this case you'll need to create a new service connection with a different webhook alias AND then run your pipeline manually again.
