### ISSUE TITLE
Project level Permission 'Edit project-level information' is not correct

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/azure-devops-docs#8920]
Hello,

There is a description of 'Edit project-level information'. And an explanation of what you can do. I think this is wrong. I had to test it today. I list the permission that I believe is wrong.

The following I can do even if for the use "deny" is set for the said permission

* Add and administer teams and all team-related features
* Add or remove project-level security groups
* Edit event subscriptions (email or SOAP) for teams or project-level events.
* When combined with the 'Change process of project' permission, allows users to change the Inheritance process for a project. (I can even change the process)

Things I either don't see or cannot do when "Allow" is set:

Also what is not mentioned:

* Edit project description
* Manage activated project level services (Board, Pipelines, Artifacts, Test Plans, Repos)

https://docs.microsoft.com/de-de/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#project-level-permissions

Could somebody clarify this or confirm that I am right? Where does this come from? I am also sending my permission setting as a screenshot for the team that I used to test this.

I also additionally have to say the project group below is a member of the "Project Administrator" which I think should not be a problem, because for other permission always the least given permission was used. Or is there some permissions forcefully inherited and some not even with "deny"?

![image](https://user-images.githubusercontent.com/7256168/88307196-f19aa680-cd0b-11ea-995e-8d0b12694de6.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/de-de/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SebastianSchuetze - You are correct in the behavior you're seeing. Sorry for the inaccuracy. The ability to manage group membership (which includes the ability to add/remove project admins) is granted by the  “manage group membership” permission; an entirely different permission bit (NOT “edit project level information”). However, this permissions isn't shown in the UI; instead it is simply granted to all project admins. 

So the fact that you are able to manage project admins, even though have  “deny” on “edit project level information” is expected because you are ALSO a member of the Project Admins group, which is granting you the “hidden” permission which actually governs this behavior. 

I'll be updating the content as needed this week.

**Comment by SebastianSchuetze** [comment]
another question to the hidden permission bit. Can I force set the permission bit via API to enforce a different behavior after adding the group to the project admins?

**Comment by KathrynEE** [comment]
@SebastianSchuetze  - You might be able to do that. I don't have the details and time to research. 
 I recommend that you check out this article: [Manage tokens and namespaces](https://docs.microsoft.com/en-us/azure/devops/organizations/security/manage-tokens-namespaces?view=azure-devops#list-namespaces).  
List the namespaces at the project level: `az devops security permission namespace list` 
List the details for the project namespace (I would believe that the permission is at the Project level): 
`az devops security permission namespace show --id 52d39943-cb85-4d7f-8fa8-c6baac873819`

The details show the permissions that correspond to those in the UI, however, there are a few that are not in the UI. It may be one of these, such as the Manage system project properties. 


C:\Users\kaelli>az devops security permission namespace show --id 52d39943-cb85-4d7f-8fa8-c6baac873819
Command group 'devops security permission' is in preview. It may be changed/removed in a future release.
[
  {
    "actions": [
      {
        "bit": 1,
        "displayName": "View project-level information",
        "name": "GENERIC_READ",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 2,
        "displayName": "Edit project-level information",
        "name": "GENERIC_WRITE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 4,
        "displayName": "Delete team project",
        "name": "DELETE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 8,
        "displayName": "Create test runs",
        "name": "PUBLISH_TEST_RESULTS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 16,
        "displayName": "Administer a build",
        "name": "ADMINISTER_BUILD",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 32,
        "displayName": "Start a build",
        "name": "START_BUILD",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 64,
        "displayName": "Edit build quality",
        "name": "EDIT_BUILD_STATUS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 128,
        "displayName": "Write to build operational store",
        "name": "UPDATE_BUILD",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 256,
        "displayName": "Delete test runs",
        "name": "DELETE_TEST_RESULTS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 512,
        "displayName": "View test runs",
        "name": "VIEW_TEST_RESULTS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 2048,
        "displayName": "Manage test environments",
        "name": "MANAGE_TEST_ENVIRONMENTS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 4096,
        "displayName": "Manage test configurations",
        "name": "MANAGE_TEST_CONFIGURATIONS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 8192,
        "displayName": "Delete and restore work items",
        "name": "WORK_ITEM_DELETE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 16384,
        "displayName": "Move work items out of this project",
        "name": "WORK_ITEM_MOVE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 32768,
        "displayName": "Permanently delete work items",
        "name": "WORK_ITEM_PERMANENTLY_DELETE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 65536,
        "displayName": "Rename team project",
        "name": "RENAME",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 131072,
        "displayName": "Manage project properties",
        "name": "MANAGE_PROPERTIES",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 262144,
        "displayName": "Manage system project properties",
        "name": "MANAGE_SYSTEM_PROPERTIES",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 524288,
        "displayName": "Bypass project property cache",
        "name": "BYPASS_PROPERTY_CACHE",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 1048576,
        "displayName": "Bypass rules on work item updates",
        "name": "BYPASS_RULES",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 2097152,
        "displayName": "Suppress notifications for work item updates",
        "name": "SUPPRESS_NOTIFICATIONS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 4194304,
        "displayName": "Update project visibility",
        "name": "UPDATE_VISIBILITY",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 8388608,
        "displayName": "Change process of team project.",
        "name": "CHANGE_PROCESS",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      },
      {
        "bit": 16777216,
        "displayName": "Agile backlog management.",
        "name": "AGILETOOLS_BACKLOG",
        "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819"
      }
    ],
    "dataspaceCategory": "Default",
    "displayName": "Project",
    "elementLength": -1,
    "extensionType": "Microsoft.TeamFoundation.ApplicationTier.Plugins.Core.ProjectSecurityExtension",
    "isRemotable": true,
    "name": "Project",
    "namespaceId": "52d39943-cb85-4d7f-8fa8-c6baac873819",
    "readPermission": 1,
    "separatorValue": ":",
    "structureValue": 1,
    "systemBitMask": 17563648,
    "useTokenTranslator": true,
    "writePermission": 2
  }
]

**Comment by SebastianSchuetze** [comment]
I am going to test it!

**Comment by KathrynEE** [comment]
@SebastianSchuetze - ALso take a look at this page: https://docs.microsoft.com/en-us/rest/api/azure/devops/security/security%20namespaces/query?view=azure-devops-rest-5.1. Appears to be a ManageMembership under the IDentity namespace.  I'm going to look into updating our Namespace content as there are a lot more security namespaces that haven't been documented.
