### ISSUE TITLE
should indicate that order determines the default state

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#8921]
based on my testing & experience whatever state is the first in the proposed category becomes the default state of any newly created items, i think this should be mentioned, possibly in the section about reorganizing the order of states in the state drop down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@drdamour - Thank you for the feedback. I've made a note to annotate the article accordingly.
