### ISSUE TITLE
Where are the video's stored? 

### ISSUE THREAD

**Issue by crh225** [MicrosoftDocs/azure-devops-docs#8922]
[Enter feedback here]

Where are the video's stored?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10651095-12d3-cb80-b104-dabca0141151
* Version Independent ID: 41d48228-7544-8269-f616-c3dc3c5fd580
* Content: [Exploratory testing in connected mode - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/connected-mode-exploratory-testing?view=azure-devops)
* Content Source: [docs/test/connected-mode-exploratory-testing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/connected-mode-exploratory-testing.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@crh225 Thank you for the question.

The results should be stored in the default downloads folder as specified by your browser.

For further information, please refer to [standalone mode](https://docs.microsoft.com/azure/devops/test/standalone-mode-exploratory-testing).
