### ISSUE TITLE
Delete WorkItem REST API documentation appears incorrect

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/azure-devops-docs#8926]
I have tried to use the REST API to delete a WorkItem in TFS 2015 (as shown on this page) and the REST call fails even though the work item ID does exist.  I suspect the documentation on this API is incorrect.  I don't know what the actual syntax of the Delete WorkItem API should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c841984d-1dbb-4757-e32f-14e2b98545b5
* Version Independent ID: 8531cb41-265a-15b1-de63-9b8522571cc5
* Content: [Work Items - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/wit/work-items?view=tfs-2015#get-a-list-of-work-items)
* Content Source: [docs/integrate/previous-apis/wit/work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/previous-apis/wit/work-items.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for reaching out @varnk. I'm looking into this and will be in touch.

**Comment by chcomley** [comment]
Hi @varnk, Please forgive my untimely response on this issue! I'm assuming that you're no longer experiencing this issue, however here's a link to the sample code for the DeleteWorkItem method in C#:  https://github.com/microsoft/azure-devops-dotnet-samples/blob/main/ClientLibrary/Samples/WorkItemTracking/WorkItemsSample.cs#L732. 

I'm closing this issue, but if you have any remaining questions or issues, please don't hesitate to @mention me. Thank you.
