### ISSUE TITLE
How to track issues on a backlog?

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#8927]
> By default, issues and impediments don't appear on your backlog. Instead, you track them using queries. To track them on a backlog, see the next section, Add issues or impediments to your product backlog.

I am much interested in tracking issues directly on a backlog but the section `Add issues or impediments to your product backlog` is no longer there. Could you please advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3745d89-ac9e-5365-25b7-4788a3374ae5
* Version Independent ID: 6691cf6d-547b-a12d-f5d7-8ee9c3ff38e0
* Content: [Add and manage issues or impediments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?view=azure-devops#add-to-backlog)
* Content Source: [docs/boards/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-issues-impediments.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Thilas - Please see the devblog: https://devblogs.microsoft.com/devops/azure-boards-summer-update/. This feature is in PRivate Preview and therefore not documented at this time.  I'll update the article to point to the devblog so customers can request to be included in the private preview.
