### ISSUE TITLE
Feed permission documentation on regarding pipelines should include more info on project permissions

### ISSUE THREAD

**Issue by cxwtool** [MicrosoftDocs/azure-devops-docs#8929]
(Originally opened by @satbai)
 
This documentation page: https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#package-permissions-in-azure-pipelines

Under the heading "Package permissions in Azure Pipelines" we should explain that in order to use packages from a project scoped feed that is scoped to a different project than where the pipeline is running in, the feed's project needs to give read/write permissions to the build service separately in addition to the feed permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#package-permissions-in-azure-pipelines)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@cxwtool Thank you for your feedback. The updated article will go live shortly.
