### ISSUE TITLE
Create test case with 15 steps

### ISSUE THREAD

**Issue by aryanss** [MicrosoftDocs/azure-devops-docs#8932]
Hello

When I create testcase , just 15 steps recording and after end step deleted first step. without attention and alarm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10651095-12d3-cb80-b104-dabca0141151
* Version Independent ID: 41d48228-7544-8269-f616-c3dc3c5fd580
* Content: [Exploratory testing in connected mode - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/connected-mode-exploratory-testing?view=azure-devops)
* Content Source: [docs/test/connected-mode-exploratory-testing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/connected-mode-exploratory-testing.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@aryanss Thank you for the feedback.

Is there an issue with the product or documentation?  

Please provide a reference to the documentation and we can assign an author for further review.

**Comment by aryanss** [comment]
@msebolt  This issue for the product. This problem occurs when I work with the Exploratory Testing extension .

After 15 Testcase steps and adding step 16, step 1 is automatically deleted.
Should I send a clip?

**Comment by msebolt** [comment]
@aryanss Thank you for the update.

Unfortunately changing the current limit of 15 is not under consideration by the product team, see [here](https://developercommunity.visualstudio.com/idea/587178/expand-test-feedback-extension-15-step-limitation.html), though feel free to revisit the issue using **Report a problem** or **Suggest a feature** [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

A note will be added to the documentation.
