### ISSUE TITLE
How does it automatically recognize VS or MSDN license holders?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8934]
Our usual IT policy is to create a corporate AD and email account for contractors/consultants. If they happen to have a VS subscription that they bring with them, how does DevOps recognize the account setup for them should be linked to the VS subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops#stakeholder-access)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@StingyJack  Thank you for the question.

This sounds like a product-related question and/or issue that will need to be addressed by the [**Azure DevOps** community](https://developercommunity.visualstudio.com/spaces/21/index.html) team.

For a similar post, see [here](https://developercommunity.visualstudio.com/content/problem/619234/cant-add-visual-studio-subscriber-to-azure-devops.html).

For more information on subscriber benefits refer to [benefits for Visual Studio subscribers](https://docs.microsoft.com/visualstudio/subscriptions/vs-azure-devops).

**Comment by KathrynEE** [comment]
@StingyJack - I believe that they can add alternate email accounts to their Visual Stubscription benefits here: https://my.visualstudio.com/Subscriptions.
