### ISSUE TITLE
OAuth2 registered apps not visible for other users in organization

### ISSUE THREAD

**Issue by gat-bryszard** [MicrosoftDocs/azure-devops-docs#8937]
We've followed the documentation for adding OAuth2 integration for our applications and successfully configured the integration.

However, the apps registered via `https://app.vsaex.visualstudio.com/app/register` are visible only on the account of the developer that has configured the integration. That is suboptimal as we should have this configuration on the organization level or at least have a way to share access to these configurations among developer accounts.

So my question: Is there a way to share registered apps among accounts (I mean access to their configuration)? Is it a missing feature or a lack of documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@gat-bryszard  Thank you for the feedback.

This is likely an issue with the product opposed to documentation. All new features are currently tracked with the [timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline).

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Assigning this to the author for confirmation.

**Comment by chcomley** [comment]
Hi @gat-bryszard, Thanks for reaching out. As stated previously, This is likely an issue with the product opposed to documentation. All new features are currently tracked with the [timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline).

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Closing for now, however you can @mention me at any time. Thanks so much!
