### ISSUE TITLE
Project Scoped Feed don't support same feed name 

### ISSUE THREAD

**Issue by temelj** [MicrosoftDocs/azure-devops-docs#8938]
Thank you for your feedback!

The documentation : https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops
does NOT mention the limitation of a unique organization wide name per project scoped feed.

In case this is an actual bug, I have reported the problem:
https://developercommunity.visualstudio.com/content/problem/1126555/private-scoped-feed-name-already-exists.html

**Comment by temelj** [comment]
Received a reply: https://developercommunity.visualstudio.com/content/problem/1126555/private-scoped-feed-name-already-exists.html

If this is a known limitation then how can a project feed be shared across projects? What is the process to make that work seamlessly? 

Can the documentation be updated to reflect the naming limitation & how to share project feeds across projects?

**Comment by ramiMSFT** [comment]
Ref: [1126555](https://developercommunity.visualstudio.com/t/private-scoped-feed-name-already-exists/1126555#T-N1128058). Closed as expected behavior.
