### ISSUE TITLE
"Default team" is mentioned on several Azure DevOps pages, but is not described anywhere

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-docs#8943]
This page is a good example - it says "_Add a team, move from one default team to several teams_", but does not indicate what "default team" means.

The only visible effect of having a default team is that it cannot be deleted. If this is the only purpose, clearly state this purpose. However, if this is the case, the term "default" is misleading. Just don't allow deleting the last team in the project.

If there is some other reason the default team indicator exists, like assigning some ownership implicitly, etc, you need to describe where this "default" context is used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112e8056-a242-c7d5-8a7a-13883b1d9834
* Version Independent ID: 898ba7df-2a34-0ceb-d613-f200b5fc9bf8
* Content: [Add a team, move from one team to several teams - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-teams?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/settings/add-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-teams.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
gh-andre - Thank you for your feedback. I agree that the information on the definition and use of "default team" could be improved. I've added that to my backlog.
