### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by scott1138** [MicrosoftDocs/azure-devops-docs#8944]
This a great document, but it's a little dated.  Any plans to update it and the instructions on using ZAP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03ce2683-1bb4-671a-630b-2c909184e93d
* Version Independent ID: 5e57efbe-f0c3-6e0f-8591-b60bb04a964c
* Content: [Add Continuous Security Validation to your CICD Pipeline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/security-validation-cicd-pipeline?view=azure-devops)
* Content Source: [docs/migrate/security-validation-cicd-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/security-validation-cicd-pipeline.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@scott1138  - Thank you for your inquiry.  This article was contributed by the ALM Rangers. There is no plan to update it at this time.
