### ISSUE TITLE
Need syntax to auto-expand Query Trees

### ISSUE THREAD

**Issue by mabeyer** [MicrosoftDocs/azure-devops-docs#8947]
Hi, 
I use the embed Query feature a lot for sprint planning. But what´s really annoying is that Queries that return a Tree of Work Items must be expanded manually. I need a way to auto-expand the tree so the users can see it all at once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@mabeyer Thank you for the feedback.

Please refer to the [**Azure DevOps** community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) for product-related issues, or contribute to a similar post recently submitted [here](https://developercommunity.visualstudio.com/idea/1165747/query-results-widget-stay-expanded.html).  

For any other documentation concerns, please use the comments below.
