### ISSUE TITLE
Cross Project Linking

### ISSUE THREAD

**Issue by stuartjsmith** [MicrosoftDocs/azure-devops-docs#8950]
This page states that "A single project minimizes the maintenance of administrative tasks and supports the most optimized / full-flexibility cross-link object experience."

I understand why having a single project minimizes maintenance, but I do not understand what restrictions or limited support there is around linking. The link in that sentence takes you to another page which describes linking, as well as how to do it between projects and even organizations. This documentation should be improved by stating explicitly what support and flexibility is missing in the cross-link object experience when using multiple projects.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8327ce3e-a6f7-74ba-7cc0-95885c247a75
* Version Independent ID: ae36a4ea-20cb-4f29-e760-8f6c362c5a47
* Content: [About projects and scaling your organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/about-projects?view=azure-devops)
* Content Source: [docs/organizations/projects/about-projects.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/about-projects.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @stuartjsmith . I agree that clarification would come in handy! I've created a user story for my backlog to address this, thank you.

**Comment by chcomley** [comment]
Also, here's a link to a table with more information, which I'll be adding to the article. Thanks! https://docs.microsoft.com/en-us/azure/devops/user-guide/plan-your-azure-devops-org-structure?view=azure-devops#many-projects
