### ISSUE TITLE
published artifact not visible on pipeline run summary page

### ISSUE THREAD

**Issue by sebkraemer** [MicrosoftDocs/azure-devops-docs#8951]
Hi.

I am using the "publish artifact" functionality in a yaml based azure pipeline. At first I thought my code didn't work because I did not see the artifact being linked, then i found the link and a page menu after entering the Job log and found the *1 artifact produced* link. I tried both approaches with ```publish```keyword and ```PublishBuildArtifacts@1``` task.

My expectation was something more prominent where e.g. a tester or some other person that is not familiar with CI and the specific pipeline would find it. So then I found this page and the screenshot would show the artifact on the pipeline run landing page in a summary section. However, for me the page looks quite differently:

![grafik](https://user-images.githubusercontent.com/1933852/88802184-031bfc80-d1ab-11ea-9db3-fcdc849f29b3.png)

Now that I'm filing the issue I notice the *"Related: 1 published.."* line (marked yellow in the screenshot), so this leads me where i want to be. It often helps to show or explain something to spot previously unnoticed things ;)

I cannot say if this is a documentation bug or if the azure pipeline changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#unc-file-share)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@sebkraemer Thank you for your feedback. The screenshots will be updated.
