### ISSUE TITLE
Release deployment completed json example is invalid json

### ISSUE THREAD

**Issue by heresandyboy** [MicrosoftDocs/azure-devops-docs#8952]
The **Release deployment completed** example appears to be incomplete and invalid JSON.

It only contains the "environment" section and looks to be missing the rest of the payload including the id, eventType, publisherId, messages etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by msebolt** [comment]
@heresandyboy Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/6945 and has been assigned to the author for review.

Please refer there for further updates.
