### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tompostler** [MicrosoftDocs/azure-devops-docs#8954]
The link in section [Where can I find the images used for Microsoft-hosted agents?](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#where-can-i-find-the-images-used-for-microsoft-hosted-agents) for routing to [scripts](https://github.com/actions/virtual-environments/tree/master/images) results in a 404 on GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@tompostler Thank you for the feedback.

The link appears to direct to https://github.com/actions/virtual-environments/tree/main/images, so you should confirm access to the [virtual-environments](https://github.com/actions/virtual-environments) repo and the [actions](https://github.com/actions) user and try again.

For help with access permissions on GitHub, see [here](https://docs.github.com/en/github/getting-started-with-github/access-permissions-on-github).
