### ISSUE TITLE
Wrong statement in canary deployment strategy section

### ISSUE THREAD

**Issue by AndreaC-MSFT** [MicrosoftDocs/azure-devops-docs#8960]
In the canary deployment strategy section I can see the following statement: "You can only use the canary deployment strategy for Kubernetes resources.".
Based on my tests I think we should remove that statement as you can actually use the canary strategy to pass the "strategy.increment" and "strategy.action" variable to whatever task or script you want. It doesn't have to be Kubernetes.
Regards,
Andrea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#canary-deployment-strategy)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @AndreaC-MSFT! The article will be updated shortly.
