### ISSUE TITLE
The example for a query spanning iterations can't/doesn't work

### ISSUE THREAD

**Issue by kosherhog** [MicrosoftDocs/azure-devops-docs#8965]
The example showing a query spanning iterations uses three "equals" clauses AND-ed together. Logically, this can't work.  This results in no results since work items can only have one iteration path set for them.  Not sure if there used to be ">" or "<" supported for querying iteration spans.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops#sliding-window-of-team-iterations-query)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kosherhog - Thank you for this feedback. I will update the article today to correct the example.
