### ISSUE TITLE
You should note that removed .order files get recreated

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/azure-devops-docs#8966]
You should note this Bug/Open Issue: https://developercommunity.visualstudio.com/idea/570941/allow-disabling-of-order-file-in-wiki-subfolders.html

Because of this article I wasted my time removing the unwanted .order files only to have them gradually recreated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 361efecd-d973-82ed-1dd8-ca01afe12f5d
* Version Independent ID: 629f3af2-8218-e53c-45c3-0e40c03f2273
* Content: [Wiki files, structure, and conventions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file)
* Content Source: [docs/project/wiki/wiki-file-structure.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-file-structure.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you @ScottWelker, I've just added this info to the article. Have a great day!
