### ISSUE TITLE
GITHUB and Azure DevOps User Synchronization

### ISSUE THREAD

**Issue by ravichillerega** [MicrosoftDocs/azure-devops-docs#8967]
[Enter feedback here]

We have a our repo in GITHUB and are linking it to Azure Pipelines. As per the document, we must create new users in Azure DevOps. However, even after creation we do not receive notifications of build and release when a build is triggered due to a merge in GITHUB. Could you clarify further on the steps to be taken for this synchronization to happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by ravichillerega** [comment]
After investigation, we found out that the github email id should be public and same as the Azure DevOps email id.

**Comment by vijayma** [comment]
@ravichillerega I am unable to understand why the GitHub email id should be public and made the same as Azure DevOps email id. Azure DevOps does not have visibility into the GitHub email address. For now, I am not updating the doc to add anything more. If you have any more insights into what might be going on in your set up, please let me know.
