### ISSUE TITLE
Is the last two versions listed correct?

### ISSUE THREAD

**Issue by altwohill** [MicrosoftDocs/azure-devops-docs#8968]
The docs mention the following versions - is this correct, or should one be 2020?

- Azure DevOps Server 2019.1.1
- Azure DevOps Server 2019 Update 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68737ab0-23e4-6127-3aef-3fec513c9612
* Version Independent ID: b127eb18-aac2-30b4-752c-ef1f50574976
* Content: [Azure DevOps Server to Services Migration overview - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops#supported-tfs-versions-for-import)
* Content Source: [docs/migrate/migration-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-overview.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@altwohill - Thank you for your inquiry. Yes, the versions listed are correct. More work has to be done to support Azure DevOps Server 2020. The RC versions aren't supported.
