### ISSUE TITLE
Works with GitHub?

### ISSUE THREAD

**Issue by itsjusth** [MicrosoftDocs/azure-devops-docs#8972]
Does this work with GitHub or GitHub Enterprise PRs or only TfsGit?  I am not seeing comments on my GitHub Enterprise PRs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa4f4c6-0a42-108e-79dd-5724e1049bd5
* Version Independent ID: f4a857d1-78bc-170b-b138-fcf490c85b38
* Content: [Code coverage for pull requests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops#configuring-coverage-settings)
* Content Source: [docs/pipelines/test/codecoverage-for-pullrequests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/codecoverage-for-pullrequests.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@itsjusth Thank you for the feedback.

A similar issue has been previously reported [here](https://developercommunity.visualstudio.com/idea/864202/code-coverage-comments-on-github-prs.html) and was closed unfortunately.

Please report this to the [community](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) again to solicit further feedback and/or action from the product team.
