### ISSUE TITLE
Documentation should explain "UploadSummary" writes to "Extensions" tab, not "Summary" tab

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/azure-devops-docs#8973]
"UploadSummary: Add some Markdown content to the build summary" does not actually write to the build's "Summary" tab where all the other build summary information goes. Reading this documentation, I expected it to write to the Summary tab.

Instead, it created a new tab named "Extensions" and wrote to that. 

The documentation should explain this. Had I known this would not write to the Summary tab, I would not have bothered trying this out. 

What I really wanted to do was hide a bunch of task warnings so the user could see important information at the bottom of the page without having to scroll. I was planning to do it by enclosing the warnings in a [collapsible section using markdown](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab).

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@BruceHaley I apologize for the late reply. I think that what you want here is the `##[group]` formatting command. I'll update this article with your feedback shortly.
