### ISSUE TITLE
Please add a mention that a project must be explicitly set to allow access to other submodules in the same organization

### ISSUE THREAD

**Issue by mikaelhogstrom** [MicrosoftDocs/azure-devops-docs#8976]
Under Authenticated Submodules (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#authenticated-submodules)

_"This requires that the job access token has access to the repository in the second project. If you restricted the job access token as explained in the section above, then you won't be able to do this."_

It should also be mentioned that the project must be explicitly set to allow access to other project git repos.
Not sure exactly which of the following settings allowed me to finally get this to work:
![image](https://user-images.githubusercontent.com/1546869/89122959-f01b6c00-d4cb-11ea-8cf5-b9ebcbdc6f4d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vijayma** [comment]
Thanks for calling this out. We are updating the doc to clarify this. You should see the update soon.
