### ISSUE TITLE
The templates for Linux and Windows contains specific Url for Organization and Project

### ISSUE THREAD

**Issue by Soruk** [MicrosoftDocs/azure-devops-docs#8979]
Hi,

The examples for Windows and Linux contains the "https://georgeverghese.visualstudio.com" organization and "Movie Search Web App" project.
It should use organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Soruk  - Thank you for the feedback. I will update the article with the correction.
