### ISSUE TITLE
Detaching a fork to make a repository in Azure DevOps

### ISSUE THREAD

**Issue by ap-bansal** [MicrosoftDocs/azure-devops-docs#8986]
Hello,

I want to make a new repository but copy everything (files, history, etc.) from an already existing repository.

I am trying to detach a fork and make it a repository of its own.
How do I do that? How is forking different from branching, except that you can change projects?

Also, if this feature doesn't exist, how can I copy a repository into another on Azure DevOps? 
I want to copy the history, branches, policies, pipelines, etc.

I know how to do this via a command line, but that method is not efficient.
So, please consider adding this feature.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/forks?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/forks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/forks.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Please file feature requests on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
