### ISSUE TITLE
Predefined agent variable Agent.MachineName not defined - should be Agent.ComputerName

### ISSUE THREAD

**Issue by steji113** [MicrosoftDocs/azure-devops-docs#8989]
I was attempting to limit a pipeline to a specific agent based on it's machine name. I received a pipeline error stating that there was no variable with the name `Agent.MachineName` defined. I looked at the agent's "Capabilities" tab and saw that there was a variable named `Agent.ComputerName` instead. I ended up being able to use that variable name successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@steji113  I apologize for the delay on this. What version of Pipelines were you using?

**Comment by juliakm** [comment]
Closed due to no response.
