### ISSUE TITLE
Cannot get group to show up

### ISSUE THREAD

**Issue by NelsonG6** [MicrosoftDocs/azure-devops-docs#8990]
[Enter feedback here]
The document shows this example:
![image](https://user-images.githubusercontent.com/18473267/89256386-d61b7f80-d5d8-11ea-9e8c-41847a2a3822.png)

If I paste those commands into a powershell task, there is no output for any of those lines.
If I wrap those commands in quotes, The output looks like this:

![image](https://user-images.githubusercontent.com/18473267/89256738-a5881580-d5d9-11ea-98ac-3437a5e49c2d.png)

The last line "command-line being run" seems to include the ##[command] text for me, but not in the document example.
I also don't see any way to collapse the group. The example shows an arrow, but I do not see one.

This is using the latest version of the powershell task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@NelsonG6 Thank you for the feedback and apologies for the issue.

This was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8727, please refer there for further updates.
