### ISSUE TITLE
When is the TCM tool going to be available in Visual Studio 2019

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/azure-devops-docs#8991]
Seems odd that this page describes a tool that isn't available in Visual Studio 2019, yet provides no means to obtain it otherwise.  My development team cannot move forward with Visual Studio 2019 unless this tool is available, since we use it extensively for our automated unit tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea562a2-64c0-b7fc-68a8-b95f65059b64
* Version Independent ID: a7f11496-ca5d-ea28-2918-aa29286f0411
* Content: [Customize and manage the test experience - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/tcm-customize-manage-test-experience?view=azure-devops-2020)
* Content Source: [docs/reference/witadmin/tcm-customize-manage-test-experience.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/witadmin/tcm-customize-manage-test-experience.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@varnk - Thank you for your inquiry. There are no plans to support the tcm tool in VIsual Studio 2019 and later versions. This command supports Microsoft Test Manager which has been replaced with Azure Test Plans. Please review the latest features available as described here, https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops, and let us know if Azure Test PLans doesn't meet your needs.

**Comment by varnk** [comment]
My company still uses on-premise TFS 2015 and we built a large testing solution that depends on TCM for ATM firmware.  Basically we will not move forward with Visual Studio 2019 without this tool.  I think this is very short-sighted for Microsoft to eliminate TCM without any indication of depreciation while assuming a company will move to Azure Devops with Visual Studio 2019.Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: KathrynEE <notifications@github.com> Date: 8/12/20  7:13 PM  (GMT-05:00) To: MicrosoftDocs/azure-devops-docs <azure-devops-docs@noreply.github.com> Cc: Ken V <varnk@sbcglobal.net>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/azure-devops-docs] When is the TCM tool going to be available in Visual Studio 2019 (#8991) 
@varnk - Thank you for your inquiry. There are no plans to support the tcm tool in VIsual Studio 2019 and later versions. This command supports Microsoft Test Manager which has been replaced with Azure Test Plans. Please review the latest features available as described here, https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops, and let us know if Azure Test PLans doesn't meet your needs.

**Comment by KathrynEE** [comment]
@varnk - I checked with the PM for this area and they affirmed that Azure Test Plans is the replacement tool for Microsoft Test Manager. Please direct any additional issues you have to the [development community page](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by varnk** [comment]
This has nothing to do with Microsoft Test Manager.   TFS Test Cases are also used by TFS vNext test tasks.  It sounds like MS is not supporting features in TFS in Visual Studio anymore even though they still are available in the latest version of Azure Dev Ops.  This is a shame!Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: KathrynEE <notifications@github.com> Date: 8/18/20  3:04 PM  (GMT-05:00) To: MicrosoftDocs/azure-devops-docs <azure-devops-docs@noreply.github.com> Cc: Ken V <varnk@sbcglobal.net>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/azure-devops-docs] When is the TCM tool going to be available in Visual Studio 2019 (#8991) 
@varnk - I checked with the PM for this area and they affirmed that Azure Test Plans is the replacement tool for Microsoft Test Manager. Please direct any additional issues you have to the development community page.
