### ISSUE TITLE
Link with text "Add issues or impediments to your product backlog" does not seem to link to anything

### ISSUE THREAD

**Issue by jochenvw** [MicrosoftDocs/azure-devops-docs#8992]
This guy over here:

![image](https://user-images.githubusercontent.com/17111555/89309793-298edb80-d674-11ea-881a-60daf17d035a.png)

Doesn't seem to link to anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3745d89-ac9e-5365-25b7-4788a3374ae5
* Version Independent ID: 6691cf6d-547b-a12d-f5d7-8ee9c3ff38e0
* Content: [Add and manage issues or impediments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?view=azure-devops)
* Content Source: [docs/boards/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-issues-impediments.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@jochenvw Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending further review.
