### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by swei7917** [MicrosoftDocs/azure-devops-docs#8993]
[Enter feedback here]

Not seeing any reasonable documentation for promoting python packages from azure dev/or github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210908e8-c062-c323-8463-fcace04ec775
* Version Independent ID: c5d9920b-15d1-ba28-b6e0-121977f4164f
* Content: [Migrate your packages to Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/migrate-packages?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/migrate-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/migrate-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@swei7917 Thank you for your contribution. Please see [Promoting your packages to a view](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops#get-started-with-feed-views). You can also checkout these other Python resources:

- [Get started with Python packages in Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops)

- [Publish Python packages in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fartifacts%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=yaml)
