### ISSUE TITLE
A rare MS apostrophe error...but twice?

### ISSUE THREAD

**Issue by bladewolf55** [MicrosoftDocs/azure-devops-docs#8995]
This sentence has incorrect apostrophes. There should be *no* apostrophes for possessive pronouns.

`To rename a dashboard, modify it's description, or change it's automatic...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d9f6cf-89b6-a0e3-0a37-f23446ede457
* Version Independent ID: 988af21a-7ee0-66b4-0fac-07360b8be17d
* Content: [Add, rename, delete, and manage team dashboards - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/dashboards?view=azure-devops)
* Content Source: [docs/report/dashboards/dashboards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/dashboards.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@bladewolf55 Thank you for the feedback.  Once, twice, and sold, to [becoming a contributor](https://docs.microsoft.com/contribute).  ;)

The documentation has been updated and is pending review.
