### ISSUE TITLE
Typo on Workflow Rules Page

### ISSUE THREAD

**Issue by NerdsvilleCEO** [MicrosoftDocs/azure-devops-docs#8996]
On the Workflow Rules page, under the "Workflow Rules" section when demonstrating how to restrict access to a state, it says "Retrict" instead of "Restrict"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe3c173-e8cc-7172-7331-11c3fc0f9724
* Version Independent ID: ee6e18ae-8ec3-613d-3644-35f1f2199e77
* Content: [Restrict workflow transitions, apply rules to workflow states - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/apply-rules-to-workflow-states?view=azure-devops)
* Content Source: [docs/organizations/settings/work/apply-rules-to-workflow-states.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/apply-rules-to-workflow-states.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NerdsvilleCEO - thank you for the feedback. The typo has been corrected.
