### ISSUE TITLE
DevOps server 2019 does not support variable groups

### ISSUE THREAD

**Issue by dmakvh** [MicrosoftDocs/azure-devops-docs#8999]
Currently, it is possible to select server 2019 and yet the documentation does not mention that the server does not support YAML variable groups ... the server will throw this error : 

![image](https://user-images.githubusercontent.com/66943055/89428494-ba30ee80-d73c-11ea-9b6e-eb57fb728aa8.png)

this is how i tried to use the declared variable group : 

![image](https://user-images.githubusercontent.com/66943055/89428614-e2205200-d73c-11ea-85d7-71cad0724a2b.png)

--> the documentation should be fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
Similar issue found under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5652.
