### ISSUE TITLE
Is 5.* still (preview)

### ISSUE THREAD

**Issue by harre096** [MicrosoftDocs/azure-devops-docs#9002]
Is 5.* still (preview)?? In Azure Devops, the label no longer says preview. This page disagrees...
So is Azure Devops right or are the docs right? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by SychevIgor** [comment]
Powershell 5 task is definitely no in a preview. @msebolt , @RoopeshNair could you take a look?

**Comment by MisinformedDNA** [comment]
I just ran into this as well.

**Comment by msebolt** [comment]
The task is now available via the [source repo](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV5) and a fix has been added to the documentation.

This issue will remain open until an updated sample is provided.
