### ISSUE TITLE
Get start and end Git hashes of the commit batch being built

### ISSUE THREAD

**Issue by pedrosousa** [MicrosoftDocs/azure-devops-docs#9006]
Hello,

I'm still learning about Azure DevOps and therefore I'm searching for equivalent features from other CI/CD tools, like GoCD.

Scheduled builds or triggered builds with only one associated agent can eventually be building a batch of accumulated commits. Is it possible to know the range of commits that are being built (for example, from SHA1 to SHA2)? I can only find the most recent commit that triggered the build, through the `Build.SourceVersion` build variable.

For example, in GoCD, besides the equivalent `GO_REVISION` environment variable, we also have:

* `GO_FROM_REVISION` - If the pipeline was triggered with a series of source control revisions (say 121 to 123), then this environment variable has the value of the oldest revision (when using only one material).

* `GO_TO_REVISION` - If the pipeline was triggered with a series of source control revisions (say 121 to 123), then this environment variable has the value of the latest revision (when using only one material). This is always the same as GO_REVISION.

Maybe using an Azure DevOps _release_ pipeline would solve this, but I don't want to use tags for handling this need and, besides that, this is really a CI question and not a CD question.

Thanks,
Pedro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@pedrosousa Thank you for the question.

Using `Build.SourceVersion` can reference the commit ID directly, however users are recommend to use the [commits API](https://docs.microsoft.com/rest/api/azure/devops/git/commits/get%20commits) for something as complex as a range.

To recommend additional [predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) and/or feature sets, please direct feedback to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
