### ISSUE TITLE
Incomplete/inaccurate documentation

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/azure-devops-docs#9009]
Under [wild cards](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards), it says:

> - For paths:
>    - You may include `*` as the final character, but it doesn't do anything differently from specifying the directory name by itself.
>   -  You may not include `*` in the middle of a path filter, and you may not use `?`.

However, [this PR](https://github.com/dotnet/performance/pull/355/files) in dotnet/performance repository specifies `**/*.md` for paths. And the `*` is included in the middle of the path filter.

Also, it says:

> - If you start your pattern with `*` in a YAML pipeline, you must wrap the pattern in quotes, like `"*-releases"`.

It says quotes in text, but puts double quotes in the example. And anyway, it looks like both are supported.

So, I think it should be:

> - If you start your pattern with `*` in a YAML pipeline, you must wrap the pattern in quotes or double quotes, like `'*-releases'` or  `"*-releases"`.

Do you want me to open a PR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@Youssef1313 Thank you for the feedback.

Please see about [becoming a contributor](https://docs.microsoft.com/contribute) if you'd like to make the change, most changes submitted via PR are incorporated in some fashion.  Otherwise the author will add the change to one of their on-going PRs.

Assigning this to the author for further review.

**Comment by vijayma** [comment]
At this point, path filters do not work with wild cards. There might be some very specific patterns that work, but in general, they don't work. Also, when we do not understand a path filter, we ignore it. Updated the docs to say so clearly for now. This is not a judgment of what we will do in the future in the product.
