### ISSUE TITLE
Demands doc is incomplete

### ISSUE THREAD

**Issue by dmakvh** [MicrosoftDocs/azure-devops-docs#9011]
In the examples, we can see a demand which apparently is using agent variables **( - Agent.Os -equals ... )**
This syntax is not documented and needs to be added, the following questions arise which should be answered : 

- Which variables are supported exactly?
- Which comparison functions are supported?
- Are there syntax derivatives? Which one exactly? 

Also : the link to https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops-2019&tabs=schema%2Cparameter-schema#demands contains no explanation at all, in fact its a reduced version of this page right here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops-2019&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
The only operators are exists and equals. There are only two syntaxes, covered in the reference documentation. I don't know about the variables but I will confirm and update the article and the reference.

**Comment by steved0x** [comment]
The examples look like variables but they are capabilities named after agent attributes, listed here:
https://github.com/microsoft/azure-pipelines-agent/blob/5a8ed1f93ee0ca0057af1c98254248401b45e282/src/Microsoft.VisualStudio.Services.Agent/Capabilities/AgentCapabilitiesProvider.cs#L24

I'll get these added to the docs, and I will fix the linking (you are correct, they both link to each other and they have the same content)
