### ISSUE TITLE
Update description for `imageDigestsPath` task input parameter

### ISSUE THREAD

**Issue by Dermendzhiev** [MicrosoftDocs/azure-devops-docs#9012]
The description for `imageDigestsPath` task input must be updated. Provided link for Docker task in the description seems no longer available https://go.microsoft.com/fwlink/?linkid=848006.

Also, looking at the latest version of [docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops), it doesn't look like it supports generation of `imageDigestsFile` where I think it was possible for the previous versions.

Best regards,
Nikolay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b41ba27-633a-37d4-ce78-a1444a99b5b1
* Version Independent ID: 387739fb-276b-d0c9-4848-45426b6e2319
* Content: [Update Service Fabric Manifests task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/service-fabric-versioning?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/service-fabric-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/service-fabric-versioning.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/service-fabric-update-manifests-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
