### ISSUE TITLE
lower() expression does not work correctly with predefined variables

### ISSUE THREAD

**Issue by cpdohert** [MicrosoftDocs/azure-devops-docs#9013]
According to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-by-using-expressions, it should be possible to pass predefined variables to an expression for evaluation.  This does not appear to work correctly for the `lower()` expression.

Given the following trivial pipeline:

```
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  a_static_variable: ALL_CAPS
  foo: $[lower('STRINGLITERAL')]
  bar: $[lower(variables['a_static_variable'])]
  quux: $[lower(variables['Build.Repository.Name'])]
  frink: $(Build.Repository.Name)
  bong: $[lower(variables['frink'])]

steps:
  - script: |
      set
      echo foo is $(foo)
      echo bar is $(bar)
      echo quux is $(quux)
      echo frink is $(frink)
      echo bong is $(bong)
```

The following output results:

```
BAR=all_caps
BONG=Completely.Useless.Test.Repository
FOO=stringliteral
FRINK=Completely.Useless.Test.Repository
QUUX=
foo is stringliteral
bar is all_caps
quux is 
frink is Completely.Useless.Test.Repository
bong is Completely.Useless.Test.Repository
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@cpdohert Thank you for the feedback.

This issue was recently reported [here](https://developercommunity.visualstudio.com/content/problem/1100720/lower-expression-is-affecting-the-name-of-the-vari.html).  

Please refer there for further updates from the product team.
