### ISSUE TITLE
What's wrong with a 91 days PAT?!

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9020]
In the page there are two separate sections, one for a "90-day token" and one for "Create a token that lasts longer than 90 days" but it is totally unclear:

* Why is it different?
* What is different AT ALL?

In the first one, the "90 days one" there is nothing that indicates that the token cannot last more than 90 days. When you create the PAT you can choose who long you want it to last, up to 360 days. Towards the user there is nothing different from a PAT that lasts 90 days, 91 days or 92 days. In this page it is totally confusing why those should be treated differently.

It should be at least pointed out what is different between a PAT of 90 days and a PAT of 91 days. Why do we need to configure them differently?

Furthermore, in the Azure DevOps Artifacts => Feed screen shot where it shows how to configure the `.npmrc` file it does not point either any difference between a 90 days PAT and a 91 days PAT, but in this page it does? Totally confusing to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@JoseFMP Thank you for your feedback. I agree it was confusing. The default PAT expires after 30 days and it can be extended. The second "method" was showing another way of converting the PAT to base64. I updated the article to remove the confusion. The updated version will go live shortly.
