### ISSUE TITLE
Update Azure DevOps Pipeline Permissions docs now that the feature is available

### ISSUE THREAD

**Issue by rajbos** [MicrosoftDocs/azure-devops-docs#9021]
See paragraph here: 
[Direct link](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#pipeline-permissions)
Isn't the sharing feature already rolled out and available? Seems like the note below can be deleted then.

```
 Note

The sharing feature is still under preview and is not yet rolled out. If you want this feature enabled, you can reach out to us. Project permissions feature is dependent on the new service connections UI and once we enable this feature, the old service connections UI is no longer usable.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by juliakm** [comment]
Thanks @rajbos. This was resolved in https://github.com/MicrosoftDocs/azure-devops-docs/issues/9546.
