### ISSUE TITLE
Do we have a complete sample of azure-pipelines.yaml?

### ISSUE THREAD

**Issue by gary918** [MicrosoftDocs/azure-devops-docs#9024]
[When the variable dockerRegistryServiceConnection: <Docker registry service connection> will be used? Again, it'll be great if we can have a complete sample of azure-pipelines.yaml. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabab0a1-052d-7a62-0773-5c6ad707752b
* Version Independent ID: 967fde84-2b93-ffa5-cb27-4f1dd4ecef49
* Content: [Deploy an Azure Web App Container - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp-on-container-linux?view=azure-devops&tabs=nodejs%2Cyaml)
* Content Source: [docs/pipelines/targets/webapp-on-container-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/webapp-on-container-linux.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by anraghun** [comment]
@gary918 Thanks for reaching out. I have update the docs to remove the `dockerRegistryServiceConnection` variable as it is not used anywhere. As for adding a complete sample of a yaml pipeline using this task, it would be redundant as we have numerous docs for each task. 

Please refer to the [yaml schema doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema) to construct the rest of the pipeline and add the required task accordingly.

**Comment by anraghun** [comment]
@msebolt Can you please close this as well?
