### ISSUE TITLE
Missing acceptable values in action parameter - Kubernetes manifest task

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftDocs/azure-devops-docs#9029]
Section: [Create secret action](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#create-secret-action)

In this section we use action `createSecret` and `secret` but there is no information about this in the action parameter description.

![image](https://user-images.githubusercontent.com/24376947/89711734-72a0a180-d98c-11ea-87a8-f31a8233e4fe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by anraghun** [comment]
The doc has been updated.

**Comment by anraghun** [comment]
@msebolt I don't seem to have the permissions to close this issue. Can you please close this?
