### ISSUE TITLE
"You can specify multiple values, or separate values with commas" is misleading

### ISSUE THREAD

**Issue by adrian-skybaker** [MicrosoftDocs/azure-devops-docs#9032]
>upgrade command
>You can specify multiple values, or separate values with commas.

This implies there is another way to set multiple values other than using comma separation, but I'm not sure there is (sadly).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
@adrian-skybaker I updated the documentation to reflect this, sorry that your an into trouble and thank you for letting us know.
