### ISSUE TITLE
Container with entry point - How to disable entry point

### ISSUE THREAD

**Issue by nsmithdev** [MicrosoftDocs/azure-devops-docs#9033]
This took me like an hour and a half to finally get working.
I was trying to run (cypress/included:4.12.1) as a container build but it has an entry point defined.

```
    container:
      image: cypress/included:4.12.1
      options: --entrypoint=""
```

Single quotes do not work as they get escaped and do not null out the entry point.
This will let you use a container with an entry point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@nsmithdev Thanks for the tip. I checked with the product team and our task calls `docker create` ([Docker's docs](https://docs.docker.com/engine/reference/commandline/create/)) so you can add any of their supported options. This is mentioned briefly in the article but I will make it clearer.
