### ISSUE TITLE
Definition of azureContainerRegistry fails

### ISSUE THREAD

**Issue by lokijota** [MicrosoftDocs/azure-devops-docs#9034]
This page defines the syntax as:

`azureContainerRegistry: contoso.azurecr.io`

When trying something like this, I always get a failure in the step saying:

`##[error]SyntaxError: Unexpected token v in JSON at position 0`

Note that `v` is the first letter of my ACR.

For this to work, you have to provide a Json string such as:

`azureContainerRegistry: '{"loginServer":"ACRNAME.azurecr.io", "id" : "/subscriptions/SUBSCRIPTION-GUID/resourceGroups/RESOURCE-GROUP/providers/Microsoft.ContainerRegistry/registries/ACRNAME"}'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@lokijota Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/3928.

Please refer there for further updates.
