### ISSUE TITLE
missing precision on local development with baseUri

### ISSUE THREAD

**Issue by camous** [MicrosoftDocs/azure-devops-docs#9035]
in this example, 
VSS.SDK.min.js is loaded from
`<script src="lib/VSS.SDK.min.js"></script>` which is correct for normal deployment.

when setting baseUri for local development, `VSS.SDK.min.js` isn't located in the lib folder, but in `node_modules/vss-web-extension-sdk`. is there any good practise for preventing coping the lib folder to extension root ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@camous  Thank you for the feedback.

The `node_modules/vss-web-extension-sdk` path is assigned to `lib` in the section [create directory and manifest](https://docs.microsoft.com/azure/devops/extend/get-started/node?view=azure-devops#create-a-directory-and-manifest) as part of the `vss-extension.json` configuration.
 
You can either change this setting manually, or make use of dynamic variables for multiple environments as described [here](https://stackoverflow.com/questions/60895809/dynamic-settings-in-config-json-from-environment).
