### ISSUE TITLE
Missing information for 'bindings' field for YAML IIS Web App Manage

### ISSUE THREAD

**Issue by djjohnjoseph** [MicrosoftDocs/azure-devops-docs#9037]
[Enter feedback here]
Hi,

There is missing information for the 'bindings' field within the YAML schema for this task. It simply says string however entering any sort of string gives the following:

```Invalid JSON primitive: https.```

Which seems to imply it should be a JSON string.

Please can the correct information for this field be added or declared somewhere?

Thanks,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@djjohnjoseph Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5338.

Please refer there for further updates.
