### ISSUE TITLE
PowerShell sessions in Pipeline have a limited scope. Please explain this and be explicit

### ISSUE THREAD

**Issue by plastikfan** [MicrosoftDocs/azure-devops-docs#9038]
I have been stumpped by a problem regarding the lifetime of a PowerShell session duing the pipeline. Nowhere in the documentation does it say tasks should be defined in the same Job that dependencies are imported into. For PowerShell, the user should be made aware not to create different stages expecting that to work on the same PowerShell session; this simply does not work and this is not documented. For a fuller description of this issue, please refer to this:

https://developercommunity.visualstudio.com/content/problem/1142539/azure-pipeline-powershell.html

Please can you document this for the PowerShell task, you can even use my faulty pipeline definition as an example.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#powershell)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@plastikfan Sorry that you ran into trouble with this - I have added an update the the PowerShell task article as well as the related section in the YAML schema document.

**Comment by plastikfan** [comment]
Hi @steved0x, thanks for doing this. I found the update with the extra note in the PowerShell(pwsh) task, but I can't see what has been updated in YAML schema document. Please can you link and specify the actual paragragh with the new information, thanks.

**Comment by plastikfan** [comment]
Actually, don't you think that PowerShell modules warrant full documentation, rather than a little note somehere, that is not that visbible? There is no documentation on PowerShell modules on Azure. I find this very strange. PowerShell modules pose a whole set of issues that PowerShell scripting do not so I think this should be fully addressed.
