### ISSUE TITLE
Where to host Release Agent? On Dedicated or Target Server

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/azure-devops-docs#9040]
In case I have high available load balanced production environment, which one is better to install release agent on each production server or to have dedicated release agent which deploy to all servers?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@RiadKatby Thank you for the question.

This issue really becomes measuring the time it takes to process a build versus that combined with the network latency in transferring the job.  Any added complexities in build steps, server count, etc. becomes a matter of a preference.

In general, increase server load before the server count so to avoid unnecessary complexity.

For more advice on specific build configurations, please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
