### ISSUE TITLE
DevOps VMSS agents : Given script is not supported 

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-devops-docs#9041]
When creating the VMSS with the given code and parameters, it fails

`Deployment failed. Correlation ID: 33d51f70-1a9c-4a24-a86e-452b1c0054a3. {
  "error": {
    "code": "NotSupported",
    "message": "Ephemeral OS disk is not supported for VM size Standard_D2_v3."
  }
}`

running from Azure Cloud Shell

```
{
  "azure-cli": "2.9.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Igmorand Thank you for the feedback, please refer to issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/9041 for further guidance.

Closing this issue now.
