### ISSUE TITLE
How to find the mapped changeset number of a label 

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/azure-devops-docs#9043]
> 3.  (Optional) If you need the label to target a specific version, from the **Version** list, select:
> 
>     -   **Latest Version**: The label will be applied to the latest version that is in version control.
> 
>     -   **Changeset**: Specify the number of the changeset in the **Changeset** box. Alternatively, choose the ellipses (**...**) to open the **Find Changesets** dialog box. For more information, see [Find and view changesets](find-view-changesets.md).
> 
>     -  ……

I see, It's able to create a label to specify changeset. But how to find the the mapped changeset number of a label, especially after a period of time, you might forget the details about that label, **no documentation mention the other way round.**

I knew the TFVC label is dynamic/editable comparing against git tag, I would like to use TFVC label as read-only tag only. I found it's hard to find the mapped changeset number of the TFVC label. **You have to check each file to find the largest changeset number, or just including the changeset number in the label comment as a workaround.**

I had tried to use [Azure DevOps Services REST API # Labels - Get Label Items](https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/labels/get%20label%20items?view=azure-devops-rest-5.1), I don't think it is fully functional as far as I know. It only returns up to 100 changes.

Thanks for your listening!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66afe74b-6887-286e-d354-9225575260b1
* Version Independent ID: 5e8e06f6-8494-408c-fcb4-d3f98580f92e
* Content: [Use labels to take a snapshot of your files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/use-labels-take-snapshot-your-files?view=azure-devops#add-an-item-to-the-label)
* Content Source: [docs/repos/tfvc/use-labels-take-snapshot-your-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/use-labels-take-snapshot-your-files.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **v-maksim**

**Comment by DmitriyKirakosyan** [comment]
#reassign @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment]
@ToMakeSense When you create a label and select a specific changeset for it, the changeset isn't really mapped to that label. In fact, the label will only be linked to items (file, folder or branch) at the _time_ of the selected changeset. You can find more info about TFVC Item structure [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/items/get?view=azure-devops-rest-5.1#tfvcitem).
This means, you can't directly get a changeset for a specific label, because it is not attached to it.
However you can use a `history` command to find a latest changeset for items included in your label, using this command:
```
> tf history . /stopafter:1 /noprompt /r /version:L<label-name>
```

**Comment by MaximMalygin** [comment]
@ToMakeSense Have you tried to use get method with maxitemcount? https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/labels/get?view=azure-devops-rest-6.0#maxitemcount

**Comment by ToMakeSense** [comment]
@MaximMalygin It works, thanks! I was using `V-5.1` which had no **maxitemcount** query parameter at that time. the `V-6.0` enhanced this API. It's strange why I didn't use `V-6.0`, the latest version.
