### ISSUE TITLE
Caching of Go packages

### ISSUE THREAD

**Issue by mniak** [MicrosoftDocs/azure-devops-docs#9045]
Please include instructions for caching of go packages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
Thanks for your feedback! Check out the example [Cache GO packages](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#golang)
