### ISSUE TITLE
A little more guidance needed

### ISSUE THREAD

**Issue by nickkirby** [MicrosoftDocs/azure-devops-docs#9057]
As I came to the page knowing almost nothing, I found it difficult to go from 'creating a pipeline' to editing the YAML.

Firstly I couldn't find it, now I've found it by clicking randomly about I don't know what to do with with it to extend it at all. 

That may be out of scope, but a link to 'using your YAML' would be very helpful.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@nickkirby I am updating the article with a next steps section that contains a link for an article on how to customize your pipeline, and also with a link to the YAML schema reference which has more details and examples.

* [Customize your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops)
* [Pipeline YAML schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)

**Comment by steved0x** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2#next-steps
