### ISSUE TITLE
The difference between `pipeline` and `source` is not clear. 

### ISSUE THREAD

**Issue by krischik** [MicrosoftDocs/azure-devops-docs#9058]
The difference between `pipeline` and `source` is not clear. 

In the example they seem to be the same apart from small spelling differences leaving me wonder what both of their meaning truly is.

Can they both be the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@steved0x @thomps23 @mijacobs The author cannot be found, please reassign.

**Comment by steved0x** [comment]
@krischik Those two values (pipeline and source) often have similar names. What is not as clear in the article is the name of the pipeline that is defined in the YAML snippet examples in the article (the app-ci pipeline). Here is some additional clarification.

* `pipeline` - the name of the pipeline resource, use this name to refer to this pipeline resource in other parts of the pipeline
* `source` - the actual name of the pipeline

I'll update this article to try and clarify this and provide additional details.
