### ISSUE TITLE
Document describes a feature which is not finished

### ISSUE THREAD

**Issue by krischik** [MicrosoftDocs/azure-devops-docs#9059]
Just found out the feature is not actually finished:

https://developercommunity.visualstudio.com/content/problem/954120/pipeline-trigger-unexpected-value-trigger.html

Thanks for waisting my time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashkir
* Microsoft Alias: **ashkir**

**Comment by msebolt** [comment]
@krischik Thank you for the feedback and apologies for the issues.

The features described in our documentation are constantly evolving and it appears this page's version moniker was never properly established.

Assigning this to the author for further review.

@steved0x @thomps23 @mijacobs Please reassign.

**Comment by steved0x** [comment]
Sorry that you ran into trouble with this - I am updating the documentation to be clear that this feature is in Azure DevOps Server 2020 and higher, as well as Azure DevOps Service.
