### ISSUE TITLE
Firewall Requirements for VMSS Agents

### ISSUE THREAD

**Issue by connorbrown-8451** [MicrosoftDocs/azure-devops-docs#9060]
It is unclear in the documentation what firewall rules are required to use VMSS agents. There is a mention in the documentation that RDP/SSH is required on a public IP address, however I am using a VMSS with no public IP and it is working fine. When I try to add rules to my NSG to control access to/from the subnet used by the VMSS, they stop working with no helpful errors. They still have access to the internet when I create these rules, so I am confused on what other rules are required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#faq)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WillLennon** [comment]
The only requirement is that outbound HTTPS (443) be allowed.
