### ISSUE TITLE
Restriction to access for specific work item, like 'bug'

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/azure-devops-docs#9065]
Hi, i would like to restrict our clients to access to our bugs. They have access to our backlog, to creating features, adding/editing some values, etc., but we don't what to allow them to see our bug list. How can i do that ? If i restrict them from work items, in general, they cant create any type of work items, like features, which we want to able to do by them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022fb627-3fc3-e748-8431-a4597bb27ad5
* Version Independent ID: 0b56992a-b121-6095-5a60-65548fdd5a3b
* Content: [Set permissions and access for work tracking - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops)
* Content Source: [docs/organizations/security/set-permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/set-permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jimicze - The only way to limit access to a set of work items, is to group them under an area path and then set permissions on that area path.  By setting View work items under this node to Deny,  you prevent them from viewing those work items. See https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#create-child-nodes-modify-work-items-under-an-area-path.
