### ISSUE TITLE
Deployment fails with no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by gidavies** [MicrosoftDocs/azure-devops-docs#9066]
The generated mainfests/deployment.yml needs to be updated to use:
apiVersion : apps/v1

and add in a selector to the same file e.g.:

selector:
    matchLabels:
      app: nodewebapp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@gidavies Do you mean this file? https://github.com/Microsoft/azure-pipelines-yaml/blob/master/templates/resources/k8s/deployment.yml

I created a PR and would appreciate it if you could review it: https://github.com/microsoft/azure-pipelines-yaml/pull/512

**Comment by juliakm** [comment]
Looks like this is updated in the [master branch](https://github.com/Microsoft/azure-pipelines-yaml/blob/master/templates/resources/k8s/deployment.yml) now.
