### ISSUE TITLE
Wrong Image 

### ISSUE THREAD

**Issue by galsi** [MicrosoftDocs/azure-devops-docs#9067]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/16662563/90130784-b5d78780-dd73-11ea-806e-249386a1a428.png)

No Builds Button!
![image](https://user-images.githubusercontent.com/16662563/90130979-05b64e80-dd74-11ea-93aa-6ba84484bd38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00712ea7-e53d-8178-aa4a-b11e43313bcd
* Version Independent ID: a4569948-b8ef-75bf-117b-19aa7397d309
* Content: [View builds, releases, pipelines - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/view-build-release-public?view=azure-devops&viewFallbackFrom=azure-devops-2020)
* Content Source: [docs/organizations/public/view-build-release-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/view-build-release-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @galsi, Thanks for the heads up on this. I've replaced the images, which should be live shortly. Thanks again!
