### ISSUE TITLE
Powershell Syntax to add and remove firewall is incorrect. Old version command with new version param is used.

### ISSUE THREAD

**Issue by dotnetagarwal** [MicrosoftDocs/azure-devops-docs#9069]
[Enter feedback here]
 New-AzureSqlDatabaseServerFirewallRule -StartIPAddress $agentIp -EndIPAddress $agentIp -FirewallRuleName $AzureFirewallName -ServerName $ServerName -ResourceGroupName $ResourceGroupName

 **New-AzureSqlDatabaseServerFirewallRule** does not take  -FirewallRuleName,  -ResourceGroupName as parameter. These are parameters of "New-AzSqlServerFirewallRule"
  Same is the case with other commands like "Set-AzSqlServerFirewallRule", Get-AzSqlServerFirewallRule . Please have a look and let me know if I am missing anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by dotnetagarwal** [comment]
Please let me know if I can fix the same. I wanted to contribute.

**Comment by msebolt** [comment]
@dotnetagarwal Thank you for the feedback.

Please find information on the contribution process [here](https://docs.microsoft.com/contribute).

Assigning this to the author for further review.
