### ISSUE TITLE
Missing repository documentation for tag

### ISSUE THREAD

**Issue by dave-yotta** [MicrosoftDocs/azure-devops-docs#9071]
For yaml pipelines, `resources.repositories`:

Docs specify the `ref:` property - which actually means checkout `refs/heads/<ref-supplied-in-yaml>`.  Impossible to check out a tag you would think? No, you can specify the property `tag:` which means `refs/tags/<tag-supplied-in-yaml>`, which is not in the docs.  The docs don't mention the `ref:` property not really meaning a ref, but a head.

Other than being confusing - the docs need completing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#repository-resource)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Apologies for the long delay, we have made improvements to this area of the documentation, which covers both refs and tags now. If this doesn't resolve your issue, please open a new issue on that article, and link back tot his one. Thank you.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource
