### ISSUE TITLE
Need some additional specific steps

### ISSUE THREAD

**Issue by atho3009** [MicrosoftDocs/azure-devops-docs#9074]
[Enter feedback here]
Hi,

The repos I am dealing with only have one branch, so this guidance could be improved by clarifying that if only one branch exists then a new one must be created.

Also, advice that there are some alternatives for the branch naming - trunk, main

Thanks,

Alex

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a0b59-001c-11dd-f3f6-9d87fd25a8d4
* Version Independent ID: 85ef7fdf-447f-6330-9105-785ba31ff759
* Content: [Change the default branch - Azure Repos](https://docs.microsoft.com/en-au/azure/devops/repos/git/change-default-branch?view=azure-devops)
* Content Source: [docs/repos/git/change-default-branch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/change-default-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by atho3009** [comment]
Also, what are the options for dealing with the old 'master' branch. When can it be safely deleted?

**Comment by vtbassmatt** [comment]
@atho3009 good ideas. It's hard to give good, generic advice about when a previous default branch can be deleted since every project has a different workflow, but I'll see what I can do 😁
