### ISSUE TITLE
AzureRmWebAppDeployment task does not support runFromPackage

### ISSUE THREAD

**Issue by tonesandtones** [MicrosoftDocs/azure-devops-docs#9075]
Contrary to the docs, `AzureRmWebAppDeployment@4` does not appear to support to runFromPackage as a deployment option.

The [task source](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts#L6) does not include `runFromPackage` as an enum option, and there is no other occurrence in the repo of "runFromPackage"

The section that refers to runFromPackage appears to be a bad copy/paste from the [Azure Web App task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@tonesandtones Thank you for the feedback.

This issue has previously been reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5711.

Please refer there for further updates.
