### ISSUE TITLE
Instructions for setting up .npmrc on Linux/Mac are incomplete

### ISSUE THREAD

**Issue by crhaglun** [MicrosoftDocs/azure-devops-docs#9076]
The instructions about how to set up NPM credentials for Mac or Linux are incomplete; as written we'll create an .npmrc file that specifies "username", "email" and _password" -- but not "_authToken" which is mandatory at least for accessing NPM feeds for 1st-party (Microsoft-owned) instances of Azure DevOps.

I'm not sure if this is true for customer ADO instances, but logically it must be at least a configurable setting.

The 3rd party tool [better-vsts-npm-auth](https://www.npmjs.com/package/better-vsts-npm-auth) provides a more thorough solution, if we can't work with the authors of that package to provide a 1st-party equivalent it should at least get a mention as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#linux-or-mac)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
Further information on this has been reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9086.

**Comment by ramiMSFT** [comment]
@crhaglun Thank you for your feedback! Take a look at the updated steps [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=linux%2Cclassic#credentials-setup)
