### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Korijn** [MicrosoftDocs/azure-devops-docs#9079]
It seems there is a dead link in the docs ("https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/set-up-your-backlog?view=azure-devops#taskboard-types") and I also can't seem to find any way to configure task categories in Azure Devops Services (cloud).

What's going on? Are the docs wrong here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14dbd1f-9b2f-c50a-456b-7efbe9a76d33
* Version Independent ID: fe725f5c-4074-5bea-38c7-ad9e8b8600a7
* Content: [Setup your Backlogs & Boards to display the user stories, issues, tasks, or work item types you want - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/set-up-your-backlog?view=azure-devops#taskboard-types)
* Content Source: [docs/boards/backlogs/set-up-your-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/set-up-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Korijn - Thank you for your inquiry. I'm updating the content to fix the dead link .  THe steps you take to add custom work item types to Sprint backlogs and boards are: 

1. Define the Ticket custom work item type. See [Add and manage work item types](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-work-item-type).

2. Add the Ticket work item types to the Iteration backlog. For details, see [Customize your backlogs or boards for a process](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards).

**Comment by Korijn** [comment]
Specifically I was looking to add Issue to the Task Category.

**Comment by KathrynEE** [comment]
@Korijn - The ability to add an Issue to the Task Category is in Preview.  See the release notes - https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-172-update#system-work-item-types-on-backlogs-and-boards-private-preview - and email your org name to get added to the Preview. Then you should be able to follow the second step to add the Issue to your Iteration Backlog.
