### ISSUE TITLE
Add information about limitations 

### ISSUE THREAD

**Issue by PawcioCNCProfi** [MicrosoftDocs/azure-devops-docs#9080]
In first paragraph you say

> Azure Artifacts provides an easy way to share packages to users outside your organization using **public feeds**. Packages that are stored in public feeds can be restored, installed, or consumed by anyone on the Internet.

However this is not true. You should add that it's impossible to use public feed from different organization as upstream source!

[Configure upstream sources for Azure DevOps Services and TFS packages](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops) page says:

> Upstream sources enable you to use a single feed to store both the packages you produce and the packages you consume from "remote feeds": both **public feeds** (e.g. npmjs.com and nuget.org) and authenticated feeds (i.e. other Azure DevOps Services feeds in your organization or Azure Active Directory (AAD) tenant).

So I mad a public feed and next thing we know is that we can's use it:

> You can also configure a custom upstream source for public repositories other than those listed above. Custom upstream sources are **only available for npm**.

It would be nice if you were consistent in your documentation.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: bceed83a-c520-5576-f54d-a28f8345795c
* Version Independent ID: c4c0690a-8156-4cd5-0f15-5244b077c971
* Content: [Share Packages Publicly - Azure Artifacts](https://docs.microsoft.com/pl-pl/azure/devops/artifacts/tutorials/share-packages-publicly?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/share-packages-publicly.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/share-packages-publicly.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@PawcioCNCProfi Thank you for your feedback. The article already contain the following note:

> Public feeds aren't intended to be a replacement for registries of record like NuGet.org or npmjs.com, and public feeds cannot have upstream sources.

I understand the confusion around your second point:

> public feeds (e.g. npmjs.com and nuget.org)

That should've been `public package manager` and not public feeds. I will get that fixed.
