### ISSUE TITLE
Move work items out of this project doesn't exist on Azure DevOps Server 2019, but docs say it does.

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/azure-devops-docs#9082]
I am on Azure DevOps Server 2019, and the "Move work items out of this project" permission doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022fb627-3fc3-e748-8431-a4597bb27ad5
* Version Independent ID: 0b56992a-b121-6095-5a60-65548fdd5a3b
* Content: [Set permissions and access for work tracking - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-work-tracking?view=azure-devops#move-delete-permissions)
* Content Source: [docs/organizations/security/set-permissions-access-work-tracking.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/set-permissions-access-work-tracking.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@pabrams - The permission should appear under **Project settings>Security**. 

![image](https://user-images.githubusercontent.com/10856840/90282097-a82d0b00-de22-11ea-9207-f8b98b32f882.png)
