### ISSUE TITLE
Using PAT for git clone

### ISSUE THREAD

**Issue by teebszet** [MicrosoftDocs/azure-devops-docs#9084]
The example doesn't work, and needs updating.

It should follow this issue: 
https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&viewFallbackFrom=vsts&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @teebszet, Many apologies for the delay in response here. I've followed up and will be in touch soon with a working example. Thanks very much!

**Comment by chcomley** [comment]
I've made updates, which will automatically close this issue when the PR completes. Thanks for the heads up!
