### ISSUE TITLE
Add Max number of azure devops organizations allowed per MSA account

### ISSUE THREAD

**Issue by v-stevch** [MicrosoftDocs/azure-devops-docs#9085]
I consider that in the documentation will be very helpful to have the max number of azure devops organizations that we can create with a MSA account, this value is currently set as 5 organizations.

In addition it could be helpful to add a the information that if we have a payment subscription in portal.azure.com, this will not affect or increase the maximum limit for the azure devops organizations

The above information does not appear in any other documentation and some people has doubts about what is the limit and if something else affect in the limit of ADO organizations per MSA account.

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b9dd76-4131-bf69-f9bc-c7f7ef562609
* Version Independent ID: 8d3bfbae-3398-c0a2-ca4d-c4782a3b4370
* Content: [Create a new organization, project collection - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops)
* Content Source: [docs/organizations/accounts/create-organization.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/create-organization.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @v-stevch, Thanks for reaching out. We have what I hope to be your answer in the following [FAQ](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-configure-customize-organization?view=azure-devops#q-how-many-organizations-can-i-create). Please @mention me if you have any further questions, thanks!
