### ISSUE TITLE
Mac Instructions are Incorrect

### ISSUE THREAD

**Issue by rlvandaveer** [MicrosoftDocs/azure-devops-docs#9086]
Part of the instructions for a Mac user are not correct. In section https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#linux-or-mac

Create a token that lasts longer than 90 days:

2. Base64 encode the PAT.

Mac

`echo -n "YOUR_PAT_GOES_HERE" | base64`

The base64 command does not encode the PAT in a way that will authenticate. I was able to test base64 encoding the PAT using the node method and the PowerShell method and both of those work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@rlvandaveer Thank you for the feedback.

This issue has previously been reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9076.

Please refer there for further updates.

**Comment by msebolt** [comment]
Closing this as duplicate.
