### ISSUE TITLE
Add information about Azure Pipelines uploadsummary markdown support

### ISSUE THREAD

**Issue by jkewley** [MicrosoftDocs/azure-devops-docs#9091]
Been looking for details on which markdown features are supported when using task.uploadsummary from within Azure Pipelines. It seems that this would be the page where it should go,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback @jkewley. I'm looking into this and will be in touch.

**Comment by chcomley** [comment]
@steved0x , do you happen to have any input for this issue? Thanks!

**Comment by chcomley** [comment]
Per the wiki PM, this issue pertains to Pipelines, not this wiki article. Reassigning to @steved0x. Thanks for your patience, @jkewley, we'll be in touch.

**Comment by ToreDemant** [comment]
Any news on this? We are having problems with links with non-standard protocol not working and would like to figure out why

**Comment by steved0x** [comment]
This feedback is for the article: https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash

@juliakm

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
