### ISSUE TITLE
New Test Plan Page: Cannot add the test cases from a spreadsheet using grid format. 

### ISSUE THREAD

**Issue by CMandala** [MicrosoftDocs/azure-devops-docs#9094]
[Enter feedback here]
Previously user was able to copy the test cases from a spreadsheet and was able to paste it successfully using a option: Create test cases using Grid. Now Grid lines are not shown in new version and does not allow the user to add test cases from spreadsheet. 
![image](https://user-images.githubusercontent.com/69797248/90392362-9d72b000-e086-11ea-84bd-5ece2229f2b2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by ShubhamJain1992** [comment]
Hi @CMandala,
Thanks for reporting this and reaching out to us. There is an ongoing issues at our end that has resulted in this experience and we are actively working on it. Here is a link to the active thread where you can find the updates and workaround: https://developercommunity.visualstudio.com/content/problem/1147584/azure-devops-test-plan-grid-functions-not-working.html
