### ISSUE TITLE
Add clarifying statement that "Author test cases using a grid-like view" applies to Test Runner window

### ISSUE THREAD

**Issue by steven-hyland** [MicrosoftDocs/azure-devops-docs#9096]
A user reported recently that they could not edit test cases in the manual Test Runner window. After [some back-and-forth](https://developercommunity.visualstudio.com/content/problem/1147412/azure-test-plans-basic-users-can-edit-a-test-case.html) with support, we determined that this was due to the license level - only Basic + Test Plans-licensed users can access that feature. However, this was not clear to me after reading the doc page, since the Test Runner window is not mentioned anywhere. Can we add a clarifying statement around which views the "grid-like view" refers to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92d59beb-f1ee-75d6-0d8b-5a5612003b23
* Version Independent ID: 0c875a53-b71b-86e1-00d4-8f453147b786
* Content: [Permissions, licensing, and access for manual testing - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/manual-test-permissions?view=azure-devops#license-requirements)
* Content Source: [docs/test/manual-test-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/manual-test-permissions.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@steven-hyland Thanks for letting us know, I just approved your PR to fix this issue and it should be live soon.

**Comment by steven-hyland** [comment]
@steved0x Thanks!
