### ISSUE TITLE
Package Management needs the module package to have a tag to find the package

### ISSUE THREAD

**Issue by pyrostew** [MicrosoftDocs/azure-devops-docs#9098]
I believe there is a key bit of information missing to allow a new custom package to be detectable by the *-Module cmdlets in package management. and that is the .nuspec file needs to have a tag "PSModule". this is lacking from the example nuspec on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@pyrostew Thank you for your feedback!

**Comment by ramiMSFT** [comment]
#sign-off
