### ISSUE TITLE
ToC in "Common service connection types"

### ISSUE THREAD

**Issue by gaikovoi** [MicrosoftDocs/azure-devops-docs#9099]
Table of content in the section "Common service connection types" seems to be unrelated to the content. I suppose it must contain list of hyperlinks to the description of the different connectors listed in this section, but instead list whole article ToC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@gaikovoi  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The changes have been made to the documentation and are pending review.
