### ISSUE TITLE
Azure App Service deploy task has a misleading parameter

### ISSUE THREAD

**Issue by ebwinters** [MicrosoftDocs/azure-devops-docs#9102]
When deploying an Azure App Service to a **Windows based .NET image**, I was trying to use the optional `StartupCommand` parameter in my yaml file. This is what the entry looks like in the docs:

StartupCommand(Startup command) | (Optional) Enter the start up command.
-- | --

I tried many different approaches to this, but the custom startup command was never successfully passed to the deployment, this is because I believe it is only available for **webapp for Linux**, not Windows. I think the docs should be updated to say:

StartupCommand(Startup command) | (Optional) Enter the start up command. This is for WebApp for Linux.
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#prerequisites-for-the-task)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines

The description for the StartupCommand parameter now explains that it is only for use when the WebAppKind input matches certain types.
```
StartupCommand - Startup command
string. Optional. Use when WebAppKind = webAppLinux || WebAppKind = webAppContainer || WebAppkind = functionAppContainer || WebAppKind = functionAppLinux || WebAppkind = webAppHyperVContainer.
```

Please check it out and let us know what you think. Thank you.
