### ISSUE TITLE
Terraform example is missing

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/azure-devops-docs#9103]
Hey guys,
it would be nice, if you could provide terraform examples for the azure devops configuration. 

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f06e24b-9d7d-b79c-f75f-44032c529027
* Version Independent ID: d0707a11-f483-f192-14c6-cbbfbe5b8071
* Content: [Add AD/Azure AD groups to security groups - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/add-ad-aad-built-in-security-groups?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/add-ad-aad-built-in-security-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/add-ad-aad-built-in-security-groups.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@Bjego Thank you for the feedback, assigning this to the author for review.

In the meantime, please see if [this example](https://docs.microsoft.com/learn/modules/provision-infrastructure-azure-pipelines/) helps.

**Comment by KathrynEE** [comment]
@Bjego - Here are some resources that may address your needs re Terraform. 
•	This Learn module addresses a Terraform plan: [Automate your deployments with Azure DevOps](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Flearn%2Fpaths%2Fautomate-deployments-azure-devops%2F&data=02%7C01%7Ckaelli%40microsoft.com%7C9dc49e71de184053118408d8450ad3d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335260089431683&sdata=gYofeSeCWzqyVcVQkSmnJycs6tI3S1XFlxhmJJFCviY%3D&reserved=0). 
•	And there is this documentation for Azure: [Terraform on Azure documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdeveloper%2Fterraform%2F&data=02%7C01%7Ckaelli%40microsoft.com%7C9dc49e71de184053118408d8450ad3d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335260089441678&sdata=HzMe2%2BTlTBL9IAOhXHjKqz9BlCEMIQ4KvHHjNOm3d9E%3D&reserved=0).
•	And this for Azure Pipelines: [Use Terraform to manage infrastructure deployment](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Fpipelines%2Frelease%2Fautomate-terraform%3Fview%3Dazure-devops&data=02%7C01%7Ckaelli%40microsoft.com%7C9dc49e71de184053118408d8450ad3d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335260089441678&sdata=ZT8a0bNBvbxKo5Wyl89%2FfLPlh5X040E15Gxl%2F5YZKJ8%3D&reserved=0).

Also, there are these Marketplace extensions: 
https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks & https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.

I'm closing this issue as there are no additional content related to the article to be provided.
