### ISSUE TITLE
PercentComplete equation wrong

### ISSUE THREAD

**Issue by gomezf** [MicrosoftDocs/azure-devops-docs#9105]
I believe the PercentComplete equation is wrong.

It says:  = ([Proposed]+[InProgress]+[Resolved])/([Proposed]+[InProgress]+[Resolved]+[Completed])
but it should be:
= [Completed]/([Proposed]+[InProgress]+[Resolved]+[Completed])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8719e400-4445-59a4-c68e-628243710c36
* Version Independent ID: d6a76999-81c0-33cb-47a5-9ca4d8be80c3
* Content: [Feature Progress rollup sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-boards-featureprogress.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-boards-featureprogress.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gomezf - Thank you for the correction. I'll be updating the article accordingly today.
