### ISSUE TITLE
Filing new issues broken on this page?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/azure-devops-docs#9107]
When I click "this page"

![image](https://user-images.githubusercontent.com/14079228/90520174-03b70b80-e137-11ea-8950-b61a616f36dd.png)

It is taking me directly to GitHub.  Did the behavior change?

And, I filed an issue, #9106, on this page I'm not seeing it listed on the bottom of the documentation page:

![image](https://user-images.githubusercontent.com/14079228/90520443-5690c300-e137-11ea-8ecb-c1f8e79412bd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@spottedmahn Thank you for the feedback.

Yes, the Microsoft Docs recently made the decision to use feedback links as opposed to each issue listed, in order to improve readability by decreasing page length.

The issue you filed was created successfully and can be viewed at the top of the page's issue list [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues?utf8=%E2%9C%93&q=%220cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd%22&in=body).

**Comment by spottedmahn** [comment]
> Yes, the Microsoft Docs recently made the decision to use feedback links as opposed to each issue listed, in order to improve readability by decreasing page length.

Hi @msebolt - wait, what?  So now I'm supposed to go out to "view all issues" to make sure I'm not creating a duplicate then come back and click the open an issue link? Interesting, it doesn't seem like an improvement to me 🤔.

Do you happen to have a GitHub issue for the discussion around this change?  Thanks!

**Comment by msebolt** [comment]
Issues with **Microsoft Docs** can be searched up and/or filed [here](https://github.com/MicrosoftDocs/feedback/issues).

Closing this issue now.
