### ISSUE TITLE
Where are authorizations listed for modified Azure DevOps yaml resources

### ISSUE THREAD

**Issue by sukoneck** [MicrosoftDocs/azure-devops-docs#9108]
In the section "[Troubleshooting authorization for a YAML pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline)" is the following guidance:

> In this case, you will see an option to authorize the resources on the failed build. If you are a member of the User role for the resource, you can select this option. Once the resources are authorized, you can start a new build.

Where are those authorizations listed / How can I determine what has already been authorized? 

I ask this same question [here](https://stackoverflow.com/questions/63081138/where-are-authorizations-listed-for-modified-azure-devops-yaml-pipelines-accessi). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sukoneck I'm asking the product team for more information about this.

**Comment by juliakm** [comment]
@sukoneck Are you looking for all pipelines that have access to a resource or all pipelines that have already accessed it?

**Comment by sukoneck** [comment]
@juliakm I am looking for all pipelines that have been [authorized ](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#troubleshooting-authorization-for-a-yaml-pipeline) to access a resource.

**Comment by sukoneck** [comment]
bump @juliakm
