### ISSUE TITLE
Assigning mutiple activities for a user/person

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/azure-devops-docs#9110]
In the Sprint Capacity tab, how can one assign multiple activities for a user? (polyvalence)
https://developercommunity.visualstudio.com/content/idea/708567/assign-multiple-activities-to-a-person-on-sprint-c.html mentions such a possibility but I did not find a way to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de93c4e5-f491-af61-6df5-e7253d727dc9
* Version Independent ID: 417246fa-90ed-38a0-cc68-1de7895e96ce
* Content: [Set sprint capacity - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=azure-devops)
* Content Source: [docs/boards/sprints/set-capacity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/sprints/set-capacity.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@kmathewmk - Hi. This is documented in this section in the article: [Track capacity when performing multiple activities](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/set-capacity?view=azure-devops#track-capacity-when-performing-multiple-activities).
