### ISSUE TITLE
Warn about no-metadata

### ISSUE THREAD

**Issue by chucker** [MicrosoftDocs/azure-devops-docs#9113]
The `git svn clone` commands use `--no-metadata` without explaining it. That's not technically wrong, and the article title _does_ start with "Migrate", but I feel there should be a warning of the consequences.

`--no-metadata` (permanently) removes the ability to reconstruct the original SVN revisions, meaning:

* stuff like docs, issues, etc. that point to those revisions can no longer as easily be referred to
* some `git svn` commands are limited afterwards

[The docs](https://git-scm.com/docs/git-svn) recommend against it:

> This option is NOT recommended as it makes it difficult to track down old references to SVN revision numbers in existing documentation, bug reports, and archives. If you plan to eventually migrate from SVN to Git and are certain about dropping SVN history, consider `git-filter-repo` instead.

So, I would suggest there should at least be some kind of warning panel about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@chucker Thank you for the feedback.

This issue has previously been reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5132.

Please refer there for further updates regarding changes to the documentation.
