### ISSUE TITLE
Documentation for Incoming Web Hook missing URL fragment

### ISSUE THREAD

**Issue by timetravelingmoose** [MicrosoftDocs/azure-devops-docs#9115]
Documentation:

https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-172-update#generic-webhook-based-triggers-for-yaml-pipelines

Under step 1 to setup a web hook:

Request Url is "https://dev.azure.com//_apis/public/distributedtask/webhooks/<WebHook Name>?api-version=6.0-preview"

Request Url should be _"https://dev.azure.com/organization/_apis/public/distributedtask/webhooks/<**WebHook_ Name**>?api-version=6.0-preview"

The doc is correct here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-webhooks

**Comment by msebolt** [comment]
@timetravelingmoose Thank you for the feedback.

The documentation has been updated and is pending review.
