### ISSUE TITLE
Open in Excel 

### ISSUE THREAD

**Issue by mbohlmann1701** [MicrosoftDocs/azure-devops-docs#9117]
In this page https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel the last image shows an "Open in Excel" menu item.  I don't see it on our production organization. In our test organization I see that option because the Open in Excel extension is installed there.  It is not installed in production.

What is the expected behavior if that extension is not installed? Is there an option to export to Excel from a query similar to what is shown in the image?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7abef49-a26f-2055-da47-cc3a6b4de1a3
* Version Independent ID: e0080a35-bafa-da4d-5c4c-1ebadb5b10b5
* Content: [Connect Azure Boards to an Office client - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel)
* Content Source: [docs/boards/backlogs/office/track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/office/track-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mbohlmann1701 - Thank you for your inquiry. As long as you meet the [Prerequisites](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel-vs#prerequisites) in the article, you can open a query from Excel. THe Open in Excel extension simply adds that functionality to the web portal. You can open a query from Excel itself.
