### ISSUE TITLE
Type of Artifacts

### ISSUE THREAD

**Issue by jsarpal** [MicrosoftDocs/azure-devops-docs#9118]
Difference between Build Artifact, Pipeline Artifact, Azure Artifact and Artifacts Icon of ADO is NOT CLEAR
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34dc460-e0f4-ff01-3c09-1b40864de6c2
* Version Independent ID: 54f9b157-0ae5-e57a-3c1e-3ff58cbfc6f7
* Content: [Artifacts in Azure Pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/artifacts-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/artifacts-overview.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@jsarpal Thank you for your feedback. Build artifacts are the files generated by your build. See [Artifacts in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml) to learn more about how to publish and consume your build artifacts. 
Pipeline artifacts are the new generation of build artifacts.  They can dramatically reduce the time it takes to upload and download large artifacts.
Pipeline artifacts provide a way to share files between stages in a pipeline or between different pipelines. They are typically the output of a build process that needs to be consumed by another job or be deployed.
Azure Artifacts is the new name for what was previously Package Management. It allows you to create and share Python, Maven, npm, and NuGet packages from public and private feeds with teams of any sizes. See [What is Azure Artifacts?](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops) for more details.
