### ISSUE TITLE
Connect Azure Devops to GitHub through a service account

### ISSUE THREAD

**Issue by deeksha-microsoft** [MicrosoftDocs/azure-devops-docs#9119]
This doc gives way to connect Devops dashboard to github repo usinbg a user account. I need to use it with a service account so that a member does not become the dependency. Can you help provide the appropriate steps?

Also the doc mentions about group that we need to be part of. Can you instead provide the permission levels required, because our Contributor group does has a very limited permission set and so being a part of that group doesn't help me through the pre requisites of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops#feedback)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@deeksha-microsoft - I recommend you ask this question in the [Developer Community support page](https://developercommunity.visualstudio.com/spaces/21/index.html).
