### ISSUE TITLE
what's mean "build or release requested for user"

### ISSUE THREAD

**Issue by stkevintan** [MicrosoftDocs/azure-devops-docs#9120]
Hi, I'm going to add "owner" message into my nunit 3 report. but when I look up at the "Result formats mapping" table, I do not understand the "build or release requested for user" meaning. how can I specific the owner message correctly?

---
* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by shashban** [comment]
@stkevintan Build.RequestedFor and Release.RequestedFor variables are set to the user who manually started the pipeline or made a commit that triggered it. Refer to https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#identity_values for additional details.

**Comment by stkevintan** [comment]
Hi, thanks for your explain
