### ISSUE TITLE
Add issues or impediments to your product backlog link does not exist

### ISSUE THREAD

**Issue by shanereddy** [MicrosoftDocs/azure-devops-docs#9122]
The hyperlink "Add issues or impediments to your product backlog." does not go to the next section link indicated in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3745d89-ac9e-5365-25b7-4788a3374ae5
* Version Independent ID: 6691cf6d-547b-a12d-f5d7-8ee9c3ff38e0
* Content: [Add and manage issues or impediments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?view=azure-devops#add-to-backlog)
* Content Source: [docs/boards/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-issues-impediments.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@shanereddy - Sorry for the missing section. The article has been updated and now includes that section. 

**Add issues or impediments to your product backlog**
If you want to track issues or impediments along with your requirements or a portfolio backlog, you can by adding them to your custom Inherited process. For details, see [Customize your backlogs or boards (Inheritance process)](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops#edit-product-backlog).

**Comment by shanereddy** [comment]
Brilliant! Thank you for the prompt reply and fix 👍
