### ISSUE TITLE
How was standard deviation determined?

### ISSUE THREAD

**Issue by ChrisPailma-ISD** [MicrosoftDocs/azure-devops-docs#9124]
In the **Plan using estimate delivery times based on lead/cycle times** section the the standard deviation is defined as +/- 6 days.  How is this determined by looking at the graph?  As far as I can tell the standard deviation is not shown as a tool-tip popup.  Are we expected to defer this tracing a line back on the Y axis and guesstimate where it would land?

It seems like the standard deviation should be easier to determine using the Lead/Cycle time graphs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9310f2-b131-3903-0c15-5bbebbd95959
* Version Independent ID: 22486f35-4e75-8dd4-7c97-cd3c6e8245fc
* Content: [Cumulative flow guidance - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops)
* Content Source: [docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ChrisPailma-ISD - Thank you for this feedback. I will pass it to the product team for this feature. For future product suggesions, use our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html) to report a problem or request a feature.
