### ISSUE TITLE
No mention of Azure Repos

### ISSUE THREAD

**Issue by sambauwens** [MicrosoftDocs/azure-devops-docs#9126]
*This is Feedback, not necessarily an "issue", I will not be offended if it get's closed :)* 

I find it misleading that the guide to creating your first Pipeline in Azure DevOps ignores completely the fact that you can use repos from Azure DevOps. Maybe I'm missing something, but in every organization I've worked for which used Azure DevOps, they were using Azure DevOps hosted repos. So I find it odd that it isn't even mentionned, and that you go ahead and add "Github account" as a prerequisite to "Create your first pipeline".

I know it says "This is a step-by-step guide to using Azure Pipelines to build a GitHub repository", but then there was a choice not to have a guide about creating your first pipeline with Azure Repos, which again to me seems to be what everybody would do anyway.

Also, Github has it's own CI Sytem (Github Actions), so it seems unlikely to me that Github users would use Azure DevOps for CI anyway, but that's speculation :)

It feels like a hint that you want to move people away from Azure DevOps Repos towards Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@sambauwens Thank you for the feedback, assigning this to the author for further review.

In the meantime, please refer to [Azure Repos](https://docs.microsoft.com/azure/devops/repos/?view=azure-devops).

**Comment by juliakm** [comment]
Thanks @sambauwens! We've started using GitHub repos for examples like this because it's an easier workflow for someone just getting started. I'm closing this but will be looking for opportunities to use Azure Repos for examples in the future.
