### ISSUE TITLE
JSON Array substitution

### ISSUE THREAD

**Issue by gumowy-kaczak** [MicrosoftDocs/azure-devops-docs#9129]
Hello, 

In my case, mentioned JSON Array substitution does not work with the transform on `Azure App Service deploy v 4.*`. 
Test config.json:
````
{
	"test": {
		"testArray": [ 
			"test array old value"
		],
	}
}
````
When I set variable:
`test.testArray` with value `["new value"]` **it does not work**, value substitution is omitted (no information about in log)
`test.testArray.0` with value `new value` **it does work**

As a workaround, I need to use dedicated `File transform v 1.*` pipeline action, where the array substitution works well.

Is this a bug or desired behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#json-variable-substitution)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@gumowy-kaczak Thank you for the feedback.

This bug was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5715 and can be referred to there for further updates.

Closing this issue now.
