### ISSUE TITLE
Could you add more details on how to link an Azure key vault to a variable group in ADO?

### ISSUE THREAD

**Issue by jl-g** [MicrosoftDocs/azure-devops-docs#9133]
I'm trying to link a key vault to a variable group in ADO, but I'm running into some issues. I'm following the steps outlined in this document: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault

I'm running into an issue with the UI (which I've reported here: https://developercommunity.visualstudio.com/content/problem/1157776/unable-to-authorize-linking-secrets-from-key-vault.html), so I'm trying instead to do it manually in the portal. However, I'm not sure what service principal I should give the permissions to. The documentation specifies this as: 

"In the Add access policy blade, choose Select principal and select **the service principal for your client account**."

I'm not sure what the 'client account' is, and could use more details. I think I'm missing something about how Azure DevOps works. Is there an application/service principal that gets associated with the project? Is that the service principal that needs to be given access? If so how do I determine what that service principal is (I didn't setup the ADO project)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@jl-g Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/3774.  Please refer there for further updates.
