### ISSUE TITLE
Confuse examples

### ISSUE THREAD

**Issue by alisson276** [MicrosoftDocs/azure-devops-docs#9136]
YAML snippet and Arguments show different parameters.

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 1eeb2956-beca-447d-c9a6-a859f3cfc4bf
* Version Independent ID: 89f2a014-99bb-420d-265c-42515d30c80b
* Content: [Python Script task - Azure Pipelines](https://docs.microsoft.com/pt-pt/azure/devops/pipelines/tasks/utility/python-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/python-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/python-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Fix is pending. Thanks!
