### ISSUE TITLE
New Service account Azure Boards

### ISSUE THREAD

**Issue by vitoliutest** [MicrosoftDocs/azure-devops-docs#9139]
Hi teams,
We found an org-level user named Azure Boards and the account has been granted access to all area path.
In the [doc](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#user-accounts) we can see that there are a few user accounts that are generated by the system to support specific operations, such as Agent Pool Service, PipelinesSDK, ProjectName Build Service and Project Collection Build Service. But cannot found the service account Azure Boards.
As part of hardening we do need to understand more about this user.
Could you please check it and tell us the details of this service account?
Thanks for your help.
![image](https://user-images.githubusercontent.com/66983754/91031133-be14aa00-e632-11ea-83ec-097f3384424a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops&tabs=preview-page#user-accounts)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vitoliutest - Thank you for your inquiry. I've reached out to the PMs for information and will get back to you once I know more.

**Comment by vitoliutest** [comment]
Hi @KathrynEE, Thanks for your help.

**Comment by danhellem** [comment]
I don't think this is a system user. Is it possible this is a service account created on your end to help manage automation or other specific operations?

**Comment by vitoliutest** [comment]
Hi @danhellem - This account was not created by me and I don’t know why this account appears. Do you have any suggestions? Thanks for your help.

**Comment by KathrynEE** [comment]
@vitoliutest, @danhellem - This account gets created when you connect Azure Boards to GitHub. It works in the background to support the features that the GitHub connection supports.
