### ISSUE TITLE
Kubectl output to reuse in a pipeline

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#9141]
Hey,

I would like to use `Kubernetes@1` task with command `Get` to extract information about existing namespaces, nods etc.
This task returns only json/xml output.
Is there any way to save it in a variable and reuse/transform in following tasks?

If not, would you recommend other approach of extracting it?

Thanks,
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by roofiq** [comment]
[https://github.com/MicrosoftDocs/azure-devops-docs/issues/5032](https://github.com/MicrosoftDocs/azure-devops-docs/issues/5032) - I have found a proposed workaround here. Is it the only way?

Thanks

**Comment by CN-PierreNoel** [comment]
Yes that would be great!

Setting up pipelines to create and setup new project, including their k98s namespace and environment in their ado project.

here's the flow
- create namespace
- create service account in namespace
- get service account secret information
- create kubernetes service endpoint using service account secret infromation
- create ado environment and kubernetes resource (namespace) that use the newly created service endpoint

Then the projects pipeline can just use the environment in a deployment job to deploy to their namespace.

I'll have to look at the work around roofiq did but would be much cleaner to have output variable on the kubectl task

**Comment by anraghun** [comment]
@roofiq The `kubectl` task provides the option of setting an output variable. 
![image](https://user-images.githubusercontent.com/46741940/91825432-e8312200-ec59-11ea-8648-4e3d2728a6b1.png)

You can then reference it in a subsequent task as follows:
![image](https://user-images.githubusercontent.com/46741940/91825492-fda64c00-ec59-11ea-8ec8-f9332dc5c8c6.png)

**Comment by CN-PierreNoel** [comment]
@anraghun Can you give details about the task you're talking about?
I just check and this option is not there with the out-of-the-box task.

The Kubernetes@1 task which use kubectl doesn't have it. see https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops

**Comment by roofiq** [comment]
So I have found a working solution for my issue.
@anraghun showed working example in classic pipelines, but in YAML this option is not avialable, as @CN-PierreNoel mentioned.
I guess, good workaround is to use `AzCLI@2` task where we can simply add service connection to AKS subscription. With command `az aks get-credentials` we are merging context to cube config and then we can use `kubectl `commands with `powershell` syntaxt within this task 👍 

Cheers,
Rafal
