### ISSUE TITLE
Does not list task for "Trigger Data Factory Pipeline" which does exist in the interface. 

### ISSUE THREAD

**Issue by horns-k** [MicrosoftDocs/azure-devops-docs#9145]
Does not list task for "Trigger Data Factory Pipeline" which does exist in the interface. 

When creating manually allows to create such a task and provides a form for the following parameters:

steps:
        - task: trigger-adf-pipeline@2
          displayName: xxx
          inputs:
            azureSubscription: 'SUBSCRIPTION(xxx-xxx-xxx)' 
            ResourceGroupName: 'RG-NAME' 
            DatafactoryName: 'factory-name' 
            PipelineFilter: 'step1' 

cannot find "trigger-adf-pipeline@2" anywhere in the Documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@horns-k  Thank you for the feedback, please consider [becoming a contributor]().

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8703.  Please refer there for further updates.
