### ISSUE TITLE
Can you be more specific with the list of domains to whitelist for NuGet connections to work?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#9146]
In the `Nuget Connections` section, Microsoft includes: 

`https://azurewebsites.net`  

Our security colleagues noted that there is all sorts of random user created content hosted on azurewebsites.net and they're not comfortable whitelisting a domain which has such wide use cases.  At the moment we're attempting to workaround this using suboptimal hacks.  Can you track down a more specific subnet of `https://azurewebsites.net` that we can work with our security colleagues to whitelist?

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by chcomley** [comment]
Hi @MarkIannucci, Thanks for reaching out. I'm following up on this with the PM and will be in touch. Thanks!

**Comment by chcomley** [comment]
Hi @MarkIannucci, I wasn't able to track down a more specific subnet of https://azurewebsites.net. I will be publishing an updated version of this article, which will include  more IPs and links to more information. This issue will close automatically, once the pull request is completed. I highly recommend reaching out to the Developer Community for assistance. I quickly searched current issues and didn't see anything relating to this subject. Please go to https://developercommunity.visualstudio.com/spaces/21/index.html. Select **Report a problem**, and then **Azure DevOps**.
If you have any further questions about the article itself, please don't hesitate to @mention me. Thank you!
