### ISSUE TITLE
This page appears to tell us how to disconnect a list from DevOps, but when reading, it's not that

### ISSUE THREAD

**Issue by sebastienricher** [MicrosoftDocs/azure-devops-docs#9150]
This page appears to tell us how to disconnect a list from DevOps, but when reading, it's not that. It looks like it's a chunk of text copied from somewhere else.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7abef49-a26f-2055-da47-cc3a6b4de1a3
* Version Independent ID: e0080a35-bafa-da4d-5c4c-1ebadb5b10b5
* Content: [Connect Azure Boards to an Office client - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/track-work?view=azure-devops&tabs=open-excel)
* Content Source: [docs/boards/backlogs/office/track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/office/track-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sebastienricher  - Thank you for the feedback. I've updated the article as it contained duplicate content.
