### ISSUE TITLE
Dynamically evaluating conditions

### ISSUE THREAD

**Issue by philip-reed** [MicrosoftDocs/azure-devops-docs#9152]
Hi,

No issue with the article, just a question regarding the evaluation of conditions.
In Azure Devops you have conditions like the following:

`condition: and(contains(variables['build.sourceBranch'], 'refs/heads/master'), succeeded())`

I'm looking to implement something similar to this in a project and wondered if this is a standard syntax?
Is this part of a library that can be re-used elsewhere to dynamically evaluate conditions or is this something unique to Azure Devops?
It sort of looks like Powershell, but not sure how the condition and variables are evaluated.

Anyone mind providing some insight if allowed?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@philip-reed Thank you for the question.

Please see if [expressions](https://docs.microsoft.com/azure/devops/pipelines/process/expressions?view=azure-devops) has the information you need.

In particular, the example `$[eq(variables['Build.SourceBranch'], 'refs/heads/master')]` will allow the use of variables to bring about a conditional `True` or `False`.
