### ISSUE TITLE
Show optional parameters in action XamariniOS@2

### ISSUE THREAD

**Issue by IainCoSource** [MicrosoftDocs/azure-devops-docs#9155]
show example values for optional parameters and where to find the values

signingIdentity
signingProvisioningProfileID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54533c61-9265-2908-c92d-f49285b24333
* Version Independent ID: 004ded47-21ee-94a7-51fe-2b835e124b55
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xamarin?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/xamarin.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@IainCoSource We have information on these variables in a separate article, [Sign your mobile app](https://docs.microsoft.com/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#reference-the-files-in-your-xcode-task). I'll make sure there's a link to that article from this one.
