### ISSUE TITLE
Document is missing IP's and ranges from Azure DevOps page

### ISSUE THREAD

**Issue by LRomano72** [MicrosoftDocs/azure-devops-docs#9156]
Being working on this for weeks and the IPs for the Azure DevOps MSFT agents are not consistent thus we can't whitelist them on our firewall to allow access. Can you please review and update the IP's as we are seeing IPs starting with 52, etc. and these are not listed.

We need a consistent IP range so that firewall whitelisting can be done.
Please and thanks!

Leo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by LRomano72** [comment]
Others that were provided by MSFT Support team that are not listed:
52.237.19.6
40.82.190.38

**Comment by chcomley** [comment]
Hi @LRomano72, Thanks for reaching out. I'm following up on this with the PM and will be in touch. Thanks!

**Comment by chcomley** [comment]
I've added some additional IPs, as well as links to more information within the article. This issue will automatically close when the pull request is complete. Please don't hesitate to @mention me if you have any further feedback about the article. If you need more technical support, I recommend reporting a problem on the Developer Community. Go here: https://developercommunity.visualstudio.com/spaces/21/index.html, choose **Report a problem** > **Azure DevOps.** Thank you!

**Comment by patoperpetua** [comment]
Hi! I'm executing a pipeline in AzureDevOps and the IP where the job is trying to connect my database is in the range of 40.127.0.0/16. I checked and it belongs to Microsoft. Can you tell me if this right? Because it's not listed in the IP ranges.
Thanks!!
