### ISSUE TITLE
How do I add a custom remote maven repository (NOT the maven central)?

### ISSUE THREAD

**Issue by michael-wirth** [MicrosoftDocs/azure-devops-docs#9159]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5891bb-c68e-d8d8-a08a-d7618904fcb6
* Version Independent ID: 56f9b4c1-4ba1-70ad-034b-a94912f03923
* Content: [Use packages from Maven Central - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/maven/upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/maven/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@michael-wirth Thank you for the question.

Please refer to [this issue](https://developercommunityapi.westus.cloudapp.azure.com/idea/658181/adding-custom-maven-feed-or-proxying-the-maven-rep.html) in the **Azure DevOps** community.
