### ISSUE TITLE
Where do i specify the username and password? where does it come from?

### ISSUE THREAD

**Issue by michael-wirth** [MicrosoftDocs/azure-devops-docs#9161]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652905ce-af26-dbea-9207-c11cd3bd0064
* Version Independent ID: 6558ec51-b1b5-15d8-0d46-1214f4038de1
* Content: [Maven Authenticate task (for task runners) - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/maven-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/maven-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@michael-wirth Thank you for the question.

The term `Provides` is misleading and should likely be replaced with `Enables` since the task only enables the use of `{user.home}/.m2/settings.xml` for authentication. 

Assigning this to the author for additional review.

**Comment by steved0x** [comment]
It is specified in the service connection, which is documented in the new task reference here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-authenticate-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
