### ISSUE TITLE
Document does not explain how to embed bug number manually. 

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/azure-devops-docs#9162]
After adding new work Item to a Wiki page, I see the following error:

Bug with id ######## created but not embedded as unsupported content type was detected in the selected text. You can manually embed it in the page.
Learn more

The **Learn More** link takes me to this page, however the content does not explain how to embed the link after it is created.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb2f69a-9f0c-3e46-42a4-45027afd8ef4
* Version Independent ID: 244bbebf-40f4-8ee3-14c6-86c5f8e7f99b
* Content: [Create and embed a work item from wiki - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/project/wiki/create-embed-wit-from-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/create-embed-wit-from-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/create-embed-wit-from-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jsuddsjr Thank you for the feedback.

Please see if [work item syntax](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#link-to-work-items-from-a-wiki-page) resolves the issue.

Assigning this to the author for review of the documentation.

For feedback on changing page redirection, please consider starting a ticket with the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by chcomley** [comment]
Hi @jsuddsjr, I've added a link to more information in the article, as well as below:
[How to link to work items from a Wiki page](https://docs.microsoft.com/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#link-to-work-items-from-a-wiki-page)
This update should go live momentarily.
Thank you!
