### ISSUE TITLE
is that possible authenticate with accesstoken instead of PATs

### ISSUE THREAD

**Issue by Mrislander** [MicrosoftDocs/azure-devops-docs#9165]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e029fedb-9691-933d-3bd7-10571323b2ad
* Version Independent ID: dcfbd622-5ead-6acb-91a9-8f41007474cc
* Content: [Use NuGet with Azure DevOps Services feeds - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops)
* Content Source: [docs/artifacts/nuget/nuget-exe.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/nuget-exe.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@Mrislander  Thank you for the question.

Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/531826/accessing-azure-devops-private-nuget-feed-using-ht.html) to see if an alternative solution is viable using `HTTP AUTH`.
