### ISSUE TITLE
Node task can't find working directory "TaskDirectory".

### ISSUE THREAD

**Issue by MalinAan** [MicrosoftDocs/azure-devops-docs#9166]
I'm currently doing the tutorial on step (Step 6: Create a build and release pipeline to publish the extension to Marketplace) on https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#step-6-create-a-build-and-release-pipeline-to-publish-the-extension-to-marketplace.

I'm having issues with the pipeline. First, I had to change TfxInstaller@2 to TfxInstaller@3, but I'm having problems with the Node task as well. When I'm running this task;

 - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '/TaskDirectory'

It complains that it doesn't find /TaskDirectory, and I don't see where it was supposed to find it either? Can you either link to where TaskDirectory should be created, or what should be standing here instead? 

The error message:
`##[error]Error: ENOENT: no such file or directory, stat '/TaskDirectory'`

**Comment by msebolt** [comment]
@MalinAan Thank you for the feedback.

The NPM issue appears unrelated to Azure DevOps, see https://github.com/microsoft/azure-pipelines-tasks/issues/12195.

Assigning this to the author to upgrade the `TfxInstaller` instructions.

**Comment by chcomley** [comment]
I've updated the article with TfxInstaller@3. Thank you for your feedback.,@MalinAan.
