### ISSUE TITLE
Does 'Resolved' apply to User Story?

### ISSUE THREAD

**Issue by nh-mmulders** [MicrosoftDocs/azure-devops-docs#9167]
I notice a difference when the state 'Resolved' is described. To me it looks like a contradiction.
In the section 'Workflow states', in the state diagram, 'Resolved' seems to apply to User Stories, because 'user story' is on the top of the state diagram. (Agile process)
In the section 'State categories', 'Resolved' only applies to Bug, Epic, Feature. User Story is missing here.

Is this just an inconsistency that needs correction? Or more information to make this clear?

We have a discussion in our team about the meaning of 'Resolved', so it would be helpful if this page is correct and clear.
 Best Regards, Miriam

![image](https://user-images.githubusercontent.com/64010716/91420576-322e9800-e855-11ea-8da7-c257e867dde4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd97771-b2cf-b722-99c6-c33ca064423c
* Version Independent ID: 9ff61b2f-db48-999e-c6be-6eadad9939e9
* Content: [Backlogs/boards workflow states & state categories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/work-items/workflow-and-state-categories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/workflow-and-state-categories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@nh-mmulders Thank you for the feedback, assigning this to the author for further review.

**Comment by KathrynEE** [comment]
@nh-mmulders - Thank you for the inquiry. Although the User Story, Feature, and Epic work item types have a Resolved state, that state is mapped to the In Progress workflow state category. I will update the article to reflect that.  Several work item types have a Resolved state, but it can be mapped to the In Progress or Resolved state category.

**Comment by nh-mmulders** [comment]
Again, we had a discussion in the team how to interpret the Resolved state, for User Stories.
I've checked the documentation again: https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=azure-devops&tabs=agile-process

I found that the table for mapping States to Categories, does not mention the Resolved state for User Stories. Only for bugs.

![image](https://user-images.githubusercontent.com/64010716/109501257-a6adf200-7a97-11eb-9597-d9592669a502.png)

**Comment by NeoXtreem** [comment]
I concur with @nh-mmulders on this. The Agile process and documentation are misaligned. If the documentation is correct (that states under Resolved category generally apply to bugs), then the Resolved state should be removed from User Story WIT. In theory, it makes less sense to have Resolved state in a User Story WIT in a truly DevOps and CI/CD world.

This issue should therefore be reopened IMHO.
