### ISSUE TITLE
Visual Studio Code Preview

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [MicrosoftDocs/azure-devops-docs#9170]
Hi there,
I just wonder - is there an official extension for visual studio code to preview Azure DevOps Markdown syntax? Like TOC and mermaid diagrams.

Cheers,
Georg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@georg-eckert-zeiss Thank you for the question.

Unfortunately no, the [previous extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.wiki) was deprecated in 2017 to be replaced with [built-in preview mode](https://devblogs.microsoft.com/devops/wiki-to-turn-wiki-many-exciting-features/).  

Alternatively you can use the [Markdown extension](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) and leave feedback on Markdown for the product team on **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html), please refer to the latest post [here](https://developercommunity.visualstudio.com/idea/365696/enhance-markdown-support-in-wiki.html).

**Comment by georg-eckert-zeiss** [comment]
Thank you.
