### ISSUE TITLE
Unclear explanation of containerRegistry input

### ISSUE THREAD

**Issue by kborovik** [MicrosoftDocs/azure-devops-docs#9171]
**Problem**
- The documentation is unclear on how to derive the value for **containerRegistry** input (dockerRegistryServiceConnection1). The reference to "Docker registry service connection" URL does not clarify the **containerRegistry** connection creation process as well. The only way to obtain **dockerRegistryServiceConnection1** string is to go through the Pipeline create wizard in the Azure DevOps portal. 
- **containerRegistry** stated as **Optional** that is not the case when used with **buildAndPush** command

**Ask**
- Provide short description or reference to locate **dockerRegistryServiceConnection** strings.
- Clarify **inputs** use cases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by anraghun** [comment]
@kborovik Thanks for your feedback. 

> Provide short description or reference to locate dockerRegistryServiceConnection strings

The documentation states that the input is the name of a docker registry service connection. If you follow the [link provided](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-docreg), you'll see the required parameters to create the service connection. We further provide details on [how to create a service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-new) on that page. All the information is available to you in two clicks.

> containerRegistry stated as Optional that is not the case when used with buildAndPush command

If you've used the `login` command in the pipeline before `buildAndPush`, then you don't need to specify a container registry. If you've logged into multiple registries, then by default `buildAndPush` will push the image to all registries. The `containerRegistry` input is only mandatory if you haven't logged in priorly/ or want to limit pushing the image only to a specific registry in case you logged into multiple.

**Comment by anraghun** [comment]
@steved0x Can we close this issue?

**Comment by kborovik** [comment]
Your explanation makes sense.

However, the documentation in conjunction with the pipeline creation wizard is very confusing.

The Azure DevOps pipeline creation wizard generates UUID (example: 12212335-215a-4756-bc74-d57b6e6ea2b9) for **dockerRegistryServiceConnection** instead of the a docker registry service connection name (example: myregistry).

I think clarification is required that UUID can be replaced by the service connection name in the azure-pipeline.yaml file. (UUID = myregistry)

I understand that _"If you've used the login command in the pipeline before buildAndPush, then you don't need to specify a container registry"_ might be very lengthy to explain in the documentation. You might consider providing more code examples to show the situation where the **login** command is used and **containerRegistry** is optional.

**Comment by steved0x** [comment]
#reassign steved0x
