### ISSUE TITLE
pipeline `steps` that are template refs do not support stated qualifiers

### ISSUE THREAD

**Issue by trdrake** [MicrosoftDocs/azure-devops-docs#9172]
[Here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps), it states:

"All steps, regardless of whether they're documented in this article, support the following properties:
- `displayName`
- `name`
- `condition`
- `continueOnError`
- `enabled`
- `env`
- `timeoutInMinutes`"

But in the templates section (and in practice), it's clear a `template reference` step supports none of these. Could, perhaps, use some clearer language. Although, sure would be nice for them to work for templates, too :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@trdrake Thank you for the feedback.

This discrepancy was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/7258.  Please refer there for further updates.

Closing this issue now.
