### ISSUE TITLE
Entire array replacement

### ISSUE THREAD

**Issue by jigneshjdesai** [MicrosoftDocs/azure-devops-docs#9173]
Hi, can you please show the example of what value to set for variable if you want to achieve replacement of entier array like DBAccess.Users = ["NewUser1","NewUser2","NewUser3"]? I am trying various options but it looks like the double quotes (") are being escaped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#json-variable-substitution)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@jigneshjdesai Thank you for the feedback.

This bug was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5715 and can be referred to there for further updates.

Closing this issue now.
