### ISSUE TITLE
If I import a git repository, is there a way to retain a link to the github repository I imported in order to pull changes in the github repo into my azure devops imported repo?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/azure-devops-docs#9174]
The documentation is silent on what happens if I import a repository into Azure DevOps.  If I do that, is there an easy way to pull changes made in the GitHub repository into my imported one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@MarkIannucci Thank you for the question.

The feature remains unsupported and you will need to manually apply the sync, see https://github.com/MicrosoftDocs/azure-devops-docs/issues/1607.

Assigning this to the author to consider a note in the documentation.
