### ISSUE TITLE
Strange but for me it's not working that way

### ISSUE THREAD

**Issue by gyozob** [MicrosoftDocs/azure-devops-docs#9178]
For me it's works only this way which is mentioned here https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows#use-environment-variables
![image](https://user-images.githubusercontent.com/10954271/91563118-01c72680-e947-11ea-8015-80ced007cf13.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@gyozob Thank you for the feedback and apologies for the confusion.

This broken example was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/7535 and can be referenced there for further updates.

Closing this issue now.
