### ISSUE TITLE
Scale Set Agents Example is Incorrect

### ISSUE THREAD

**Issue by twurm** [MicrosoftDocs/azure-devops-docs#9180]
Walking through the docs for creating Scale Set Agents I ran into an issue with the following example:

```shell
az vmss create \
--name vmssagentspool \
--resource-group vmssagents \
--image UbuntuLTS \
--vm-sku Standard_D2_v3 \
--storage-sku StandardSSD_LRS \
--authentication-type SSH \
--instance-count 2 \
--disable-overprovision \
--upgrade-policy-mode manual \
--single-placement-group false \
--platform-fault-domain-count 1 \
--load-balancer "" \
--ephemeral-os-disk true \
--os-disk-caching readonly
```

It generates the following exception:

```json
Deployment failed. Correlation ID: ff93c4ec-e9f5-4da9-bda5-e5748e4a9678. {
  "error": {
    "code": "NotSupported",
    "message": "Ephemeral OS disk is not supported for VM size Standard_D2_v2."
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@twurm Thank you for letting us know, I will get this updated, Ephemeral OS disks for Azure VM is supported on premium VM sizes, and the VM size in that example does not use one of the supported sizes on this list. 

https://docs.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks

**Comment by lgmorand** [comment]
@steved0x was the doc updated ? it seems that the example still uses a SKU which is incompatible with ephemerable (didn't try)

**Comment by steved0x** [comment]
@lgmorand Sorry I just saw this one as referenced from https://github.com/MicrosoftDocs/azure-devops-docs/issues/9128, I'll go and double check, for this issue, I removed the ephemeral options from the script and added a note explaining they are only supported for certain skus.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#create-the-scale-set
Removed ephemeral disk options:
![image](https://user-images.githubusercontent.com/1580889/100648709-4f20ae80-330f-11eb-9ea8-5c220224339e.png)

Note about supported SKUs and link to where to see which SKUs are supported:
![image](https://user-images.githubusercontent.com/1580889/100648772-6a8bb980-330f-11eb-9d2d-592b4e6cdb45.png)

I am reviewing the other GH issue now, this script has evolved so I will run it from scratch to ensure that it hasn't gotten into a non-runnable state...

**Comment by lgmorand** [comment]
@steved0x Perfect. Just tell me if you want me to run tests on my side too :)
