### ISSUE TITLE
How to tell if a task can be used in Server Jobs or Agent Jobs?

### ISSUE THREAD

**Issue by xtu** [MicrosoftDocs/azure-devops-docs#9183]
I am creating a Deployment Job. One of the steps is to run a Docker container from an image using docker command line. I tried both `Bash@3` and `CmdLine@2` and they are not allowed to use in Server Job. The command line needs to be run on the target server so I set `pool` of the `deploy` hook to be `server`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7ba5cf3-d229-03d0-ad6a-a30a0379afc0
* Version Independent ID: ccffed3b-ea44-517f-f7a8-a1c4c4147495
* Content: [Catalog of the built-in tasks for build-release and Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops)
* Content Source: [docs/pipelines/tasks/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/index.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@xtu  Thank you for the question.

Please refer to the [phases](https://docs.microsoft.com/azure/devops/pipelines/process/phases?view=azure-devops&tabs=classic#types-of-jobs) doc which was recently updated with a server job task list, under issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/4672.

You can alternatively invoke the REST API as per https://github.com/MicrosoftDocs/azure-devops-docs/issues/4672#issuecomment-534023895.
