### ISSUE TITLE
Cobertura Support

### ISSUE THREAD

**Issue by winstonhenke** [MicrosoftDocs/azure-devops-docs#9185]
The `PublishTestResults` task says it "supports popular coverage result formats such as Cobertura and JaCoCo" but these are not one of the allowed inputs for `testResultsFormat`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@winstonhenke Thank you for the feedback.

The documentation has been updated and is now pending review.

For open tickets on adding this support, please see [here](https://developercommunity.visualstudio.com/idea/1000197/support-for-cobertura-code-coverage-in-pr-validati.html) and [here](https://developercommunity.visualstudio.com/content/problem/1179898/jacoco-not-enable-for-maven-build.html) to solicit feedback from the product team.

.
