### ISSUE TITLE
Can we add an example to the FAQ question regarding difference between daily pro-rated charges, that illustrates a scenario where there no gain in trying to reduce subscription numbers mid month ? 

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/azure-devops-docs#9189]
[Enter feedback here]

Hello, regarding this FAQ question below:
---------
Q: What's the difference between daily pro-rated charges instead of monthly committed purchases?

A: **As part of the change to user assignment-based billing,** we've also switched from monthly to daily billing. **When you give a user paid access for a few weeks, or even a few days, you pay only for the time they've been assigned the paid access, rather than a full month.** As we switch your organization from monthly to daily billing, your next Azure bill will likely be lower than it has been previously. The next month will be back to normal, once a full month of daily charges has accumulated.
---------

Regarding a case where a customer tries to micro manage the number of parallel jobs they use each month in order to reduce costs, I received these following 2 points from the Engineer I consulted illustrating why it is meaningless to do so:

1) If mid month, 8/15, the number of parallel jobs was increased from 0 to 10 (more VS enterprise subscriptions must be purchased to increase # of parallel jobs), then the daily pro-rated charges would apply from 8-15~31, for their August bill.

2) If instead on 8/1 the number of parallel jobs was increased from 0 to 10 (purchasing more subscriptions), but then on 8/15, the #of pipelines was reduced back to 0, there really wouldn't be any savings for the customer because although the number of pipelines is 0, the number of subscriptions remains at 10 which is the nature of "user assignment-base billing".  They could also try reducing their subscription to 0 to lower the cost for the following month, but this would be meaningless too if they are going to have to raise the number of Parallel Jobs to 10 again at the beginning of the month (and re up their # of subscriptions).

Kindly requesting if an example similar to the one above can be added to further demonstrate what is meant by "user assignment-based billing" and how it affects  billing.

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Frequent questions about billing management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @v-pethur. I've created a user story on my backlog to address this! Thank you.

**Comment by chcomley** [comment]
Hi @v-pethur. Rather than update the article with a detailed scenario, we will stay with the fact that billing for partial months is pro-rated. I've spoken with my PM who confirmed that you can get all that information from your Azure bill today. Thank you for your feedback, we appreciate it. If we continue to get feedback like this, we'll revisit. Thanks so much. Feel free to @mention me if you have any further feedback or questions.
