### ISSUE TITLE
WSJF Extension mentioned

### ISSUE THREAD

**Issue by richardzaat** [MicrosoftDocs/azure-devops-docs#9190]
Hi,

In the article the WSJF extension is mentioned. I would like to stress out that this extension has not been updated in the last two years, and looking at the issues on the project on Github (https://github.com/microsoft/AzureDevOps-WSJF-Extension) there is currently zero to none activity. Old issues are still open, same for a year old pull request.

Feels like the extension is no longer supported, making it hard to "safely" implement in our environment,

Kind regards,
Richard Zaat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0479f615-08ef-f48c-de03-170bae58e7db
* Version Independent ID: e35eef4d-3340-9b21-8324-59dc6983035d
* Content: [Customize Azure Boards to support SAFe® - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/safe-customize?view=azure-devops)
* Content Source: [docs/boards/plans/safe-customize.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/safe-customize.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@richardzaat  - Thank you for this information. I will update the SAFe articles and remove this extension from the customation guidance.
