### ISSUE TITLE
Week of Year

### ISSUE THREAD

**Issue by derekrprice** [MicrosoftDocs/azure-devops-docs#9193]
Is there a way to obtain the week of the year (as a number from 01-52)?  A more complete documentation of the available date format options would be useful.

Derek 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@derekrprice Thank you for the feedback and https://github.com/MicrosoftDocs/azure-devops-docs/issues/666#issuecomment-683764362.

Please refer to issue https://github.com/MicrosoftDocs/azure-devops-docs/issues/666 for further updates.

In the meantime, you could also try using the [PowerShell workaround](https://stackoverflow.com/questions/44738944/vsotfs-get-current-date-time-as-variable).
