### ISSUE TITLE
wrong url for curl sample

### ISSUE THREAD

**Issue by ncourtiller** [MicrosoftDocs/azure-devops-docs#9194]
In § "Use a PAT in your code the url parameter given for `curl`, "`https://dev.azure.com/{organization}/_apis/build-release/builds`",  does not work (anymore ?) --> *404 - Page not found*

BTW below for the C# code the url is "`https://dev.azure.com/{organization}/{project}/_apis/build/builds`"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@ncourtiller Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9084 and has been assigned to the author for further investigation.  

Please refer there for the latest updates.
