### ISSUE TITLE
document BuildKit support

### ISSUE THREAD

**Issue by collinbarrett** [MicrosoftDocs/azure-devops-docs#9196]
It could be helpful to document how to enable BuildKit for both the Docker and Docker Compose Azure Pipelines tasks. I just verified that adding variables to my Pipeline like below does enable BuildKit, but it took quite some time to figure out how to turn this on.

```
variables:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
```

It is mentioned over [here](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/build-image.md#buildkit) for Docker, but it doesn't mention how to enable it for Docker Compose and it'd be good to mention it on the task pages as well for better discoverability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by beatcracker** [comment]
You can also do it like this, to avoid polluting global variable scope:

```yaml
- task: Docker@2
  inputs:
    command: build
    # ...
  env:
    DOCKER_BUILDKIT: 1
```

**Comment by Zizico2** [comment]
does this work for the Compose task? I'm getting `contains unsupported option: 'ssh'
`

**Comment by steved0x** [comment]
Thanks for your feedback! We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
