### ISSUE TITLE
Unlink functionnality actually seem to apply to release pipelines

### ISSUE THREAD

**Issue by sambauwens** [MicrosoftDocs/azure-devops-docs#9198]
> The Link and Unlink functionality applies to build pipelines only. It does not apply to release pipelines.

The "Unlink all" button does exist on "Releases" Pipelines, and is referenced on [another doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops). I personally don't see it on a "Pipelines" Pipeline, or what we would call "Build" Pipelines. But then, what is refered as Build Pipelines in the docs are actually under "Pipelines" > "Pipelines" in the Azure DevOps menu, so I can't state with certainty what you are referring to when you say "build pipelines" on this page (I find this to be very confusing and I won't miss an occasion to mention it ^^).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec7e5a9-e22e-a329-14cf-6e21e65cc85f
* Version Independent ID: c96aaf4e-f5ec-c42f-05cb-e2366167fbc6
* Content: [Process parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=azure-devops)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@sambauwens Thanks for the feedback. Task groups are only available for Classic pipelines. I'll add a qualifier in the title to make this clearer.
