### ISSUE TITLE
KubernetesManifest kubernetesServiceConnection parameter incorrectly described as "Required"

### ISSUE THREAD

**Issue by dlumpp** [MicrosoftDocs/azure-devops-docs#9202]
The parameter `kubernetesServiceConnection` is listed as "Required" with no further qualifications even though it is not required when using a Kubernetes resource in an environment.

I would like to suggest adding a note explaining usage within a multistage deploy task using an environment. 

I only discovered this usage was possible after seeing examples [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops). I believe this applies to the `namespace` parameter as well. These two pages seem contradictory as is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@dlumpp Thank you for the feedback.

This seems contradictory as it's listed as `required` in the [repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/KubernetesManifestV0/task.json) without a `defaultValue`.

Assigning this to the author for further review.

**Comment by anraghun** [comment]
Pushed a fix for it. @msebolt We can close this.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here (that parameter is required only when action != bake): 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/kubernetes-manifest-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
