### ISSUE TITLE
change variable value to upper case.

### ISSUE THREAD

**Issue by virendarkmr** [MicrosoftDocs/azure-devops-docs#9203]
[Enter feedback here]

How can i use the upper function to change the variable value to upper case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@virendarkmr Thank you for the question.

Please refer to the [upper](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#upper) function.  If there are any further issues, please comment below.
