### ISSUE TITLE
'each' Keyword/Expression Documentation Missing

### ISSUE THREAD

**Issue by misspellted** [MicrosoftDocs/azure-devops-docs#9204]
The YAML schema article (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#matrix) indicates that there is an example of using the `each` keyword (in an expression) in a GitHub project (https://github.com/nedrebo/parameterized-azure-jobs).

This GitHub project then links back to the Expressions article (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops), using the 'each expressions' link text. However, upon following the link to the article, there is no mention or example of the each keyword or expression (when using "Edgeium" to search the page, only 11 results are highlighted for 'each').

Was there a change in the syntax, such that the 'each' keyword is no longer used/supported? The referenced GitHub project in the YAML schema article has not seen a commit in over a year, but a more recent (8 months or so) question on StackOverflow (https://stackoverflow.com/questions/59387555/using-for-loop-in-azure-pipeline-jobs) seems to indicate it may still be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@misspellted We have an example in the template article. I'll add one to the schema as well. This should work:

```yaml
parameters:
- name: listOfStrings
  type: object
  default:
  - one
  - two

steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}
```
