### ISSUE TITLE
"Library roles and permissions" missing information

### ISSUE THREAD

**Issue by FokkoVeegens** [MicrosoftDocs/azure-devops-docs#9205]
Hi,

The section "Library roles and permissions" is missing vital information. First the "creator" special role is missing from the table. Second: the description of the roles is too limited. What means "manage"? Is it edit? Can someone edit permissions as well? What is use? Is that "consume" only?

I see it's somewhat of a duplicate of #1728, but that one is still not solved after 2 years...

Kind regards, Fokko.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@FokkoVeegens Thank you for the feedback, assigning this to the authors for further review.

**Comment by ashokirla** [comment]
Created a PR for the same: https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/2158
