### ISSUE TITLE
Mermaid Diagrams

### ISSUE THREAD

**Issue by jalp1254** [MicrosoftDocs/azure-devops-docs#9206]
Documentation references support for mermaid "Flowcharts" however the wiki product supports only "graph". Flowcharts allow linkage between subgraphs which is not currently supported in Azure DevOps Wiki.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for the feedback, @jalp1254. When I publish the fix, this PR will automatically be closed. Thanks again!
