### ISSUE TITLE
[v1.*] Missing Managed VM Image Documentation

### ISSUE THREAD

**Issue by qJake** [MicrosoftDocs/azure-devops-docs#9209]
The documentation for settings **Managed VM disk image** and **Managed VM Disk Image Name** are not present.

In particular, I need to know what values I am allowed to enter into the Disk Image Name field. Linking to some documentation that provides a list of valid values would be extremely helpful.

![image](https://user-images.githubusercontent.com/652006/92020526-e4ff6a00-ed1d-11ea-9dac-19d2b7a9dd94.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f7a83-5e63-e305-4cc1-d443db82893e
* Version Independent ID: 35b19b29-3f7b-19a3-5bb5-a3af2bbfe4d8
* Content: [Build Machine Image task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/packer-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by qJake** [comment]
I think I found some valid values in the YAML template but it's incredibly hard to read.

Are these valid?

* microsoftWindowsServer:WindowsServer:2016-Datacenter:Windows
* microsoftWindowsServer:WindowsServer:2012-R2-Datacenter:Windows
* microsoftWindowsServer:WindowsServer:2012-Datacenter:Windows
* microsoftWindowsServer:WindowsServer:2008-R2-SP1:Windows
* canonical:UbuntuServer:14.04.4-LTS:Linux
* canonical:UbuntuServer:16.04-LTS:Linux
* redHat:RHEL:7.2:Linux, redHat:RHEL:6.8:Linux
* openLogic:CentOS:7.2:Linux
* openLogic:CentOS:6.8:Linux
* credativ:Debian:8:Linux
* credativ:Debian:7:Linux
* sUSE:OpenSUSE-Leap:42.2:Linux
* sUSE:SLES:12-SP2:Linux
* sUSE:SLES:11-SP4:Linux

And based on context, even though it is not present in the list, I am assuming that this would be a valid image name for Windows Server 2019 Datacenter?

* microsoftWindowsServer:WindowsServer:2019-Datacenter:Windows

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/packer-build-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
