### ISSUE TITLE
unclear what disabling a pipeline services will do

### ISSUE THREAD

**Issue by twomoonbrew** [MicrosoftDocs/azure-devops-docs#9211]
The message when you disable it says "Turning off Pipelines hides this service for all members of this project. If you choose to enable this service later, all your existing data will be available."

It is unclear what happens if you disable the pipeline services.  Is it just hiding the service from the users and the pipelines are still going to run as normal?  Or does it also disable all the pipelines so no automated builds or releases will happen? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a46752f-3ee0-1503-9423-740ae926c25f
* Version Independent ID: 78a11eae-b3b7-5e6f-971a-4abc5716013d
* Content: [Turn a service on or off - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-services?view=azure-devops-2020)
* Content Source: [docs/organizations/settings/set-services.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-services.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @twomoonbrew, Thanks for reaching out. Just the UI is disabled. Please let us know if you need any further clarification - you can @mention me. Thanks!
