### ISSUE TITLE
Is it possible to use the TAG information on the Pipeline

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MicrosoftDocs/azure-devops-docs#9215]
Can you please clarify if it is possible to capture any TAG information into variables or any other struct that would allow it to be used on the pipeline. Eg, for the command `git tag -a 1.0.1 -m "Fixed bug A" -m "Improved performance for use casa X"`
I would like to use the version as the package version and possibly the messages as release notes... Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Leonardo-Ferreira Thank you for the question.

In something as specific as this it's generally recommended to use REST.  For this instance, please refer to the [tags](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/tags?view=azure-devops-rest-6.0) API.
