### ISSUE TITLE
Power BI content pack cannot be found

### ISSUE THREAD

**Issue by jlattimer** [MicrosoftDocs/azure-devops-docs#9216]
I'm guessing this is no longer maintained and has long since been taken down considering the move from content packs to template apps.

If so - this page should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4baac6c-eaa0-6e71-75fd-697a665b1b2c
* Version Independent ID: 057516df-2053-ca80-2d57-5ee2af974273
* Content: [Extension Statistics Power BI Content pack - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/extend/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
Also note this issue was previously mentioned under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8061.

**Comment by chcomley** [comment]
Thanks for your feedback, @jlattimer.  I'll be addressing this in the coming sprint. Thanks again!
