### ISSUE TITLE
policy for branch creation

### ISSUE THREAD

**Issue by mudkumar** [MicrosoftDocs/azure-devops-docs#9218]
[How do we create policy for branch creation?For example: i want only few users to create branches under release/*..As of now i donot see any way of setting this policy in Azure.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
You can use `tf git` to express folder-level permissions. It's a prefix-match system (splitting only at `/`) so you can simply set permissions on `release` and it'll apply to `release/*`.

Let's say you have a repo "MyRepo" in project "MyProj" in org "MyOrg". Finally, you have a group called "[MyProj]\ReleaseEngineers" that you want to allow, and everyone else is disallowed. Then these two commands will do it:

```shell
tf git permission /deny:CreateBranch /group:[MyProj]\Contributors /collection:https://dev.azure.com/myorg /teamproject:MyProj /repository:MyRepo /branch:release
tf git permission /allow:CreateBranch /group:[MyProj]\ReleaseEngineers /collection:https://dev.azure.com/myorg /teamproject:MyProj /repository:MyRepo /branch:release
```
