### ISSUE TITLE
Adding a generic Kubernetes provider to an Azure Devops environment: What kind access is required for the ServiceAccount?

### ISSUE THREAD

**Issue by ps-weber** [MicrosoftDocs/azure-devops-docs#9222]
The section "Using existing service account" does not describe what kind of access is required for the service account.

As far as i understand it should be similar to [this](https://docs.armory.io/docs/spinnaker-install-admin-guides/manual-service-account/).

A sample Kubernetes role definition would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops&viewFallbackFrom=azure-devops-2020)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
It looks like we addressed this [here](https://github.com/MicrosoftDocs/azure-devops-docs/commit/73bf0857fdea4df63ddc996c4d43e9642a3a0337).
