### ISSUE TITLE
Can you create tags using git command?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MicrosoftDocs/azure-devops-docs#9223]
Is there a way to create a tag using command line? `git tag` doesn't seem to work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb20e31-fc65-913d-f4a6-61318f079224
* Version Independent ID: 0c4960b1-d639-7452-a2e7-08c59934c3b3
* Content: [Working with Git tags - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-tags?view=azure-devops)
* Content Source: [docs/repos/git/git-tags.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-tags.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
There's the [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/annotated%20tags?view=azure-devops-rest-6.1) and `git tag` (remember to update permissions and to push changes).
