### ISSUE TITLE
CD pipeline concurrency

### ISSUE THREAD

**Issue by VaclavK** [MicrosoftDocs/azure-devops-docs#9230]
Is there any way to limit concurrency on triggered **YAML** pipeline?.. If the pipeline deploys to azure resources and would be invoked by multiple CI pipeline runs it (CI is/may be past, CD may/is slow) may result in environment where some resources are from one build and some from some other and perhaps even trip each other up causing errors.

in my case I have CD pipeline with several jobs (job per component) so job scheduling with pipeline concurrency would be "unpredictable" in order and based on agent availability and ADO behaviour...

similar to batch setting for CI trigger, is there any way to stack up pipelines when triggered by CI pipeline completing? Is there any other approach you would recommend that achieves the same?

e.g. (multiple manual triggers to visualize the question but in reality would be pipeline completion triggered)
![image](https://user-images.githubusercontent.com/3881864/92404810-44011c80-f12c-11ea-9287-f909b3f0c4d4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86285f72-9e28-da97-59bb-c29eb60f627d
* Version Independent ID: 18d5a591-a7d3-c261-6bff-8808ae433f54
* Content: [Configure pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/pipeline-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/pipeline-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @ashokirla
* Microsoft Alias: **ashkir**

**Comment by VaclavK** [comment]
I have now "discovered" the exclusive lock features onto environments which seems to do that 

it seems undocumented

**Comment by allanlw** [comment]
See https://github.com/MicrosoftDocs/azure-devops-docs/issues/8910 for "exclusive lock" is undocumented.

It would also seem that if you only use git triggers you can accomplish this somewhat using the "batch" property.

> If you set batch to true, when a pipeline is running, the system waits until the run is completed, then starts another run with all changes that have not yet been built.

See: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml
