### ISSUE TITLE
A better name for "Manually entered demands" is something like "Agent Demands"

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-devops-docs#9233]
Considering that the first subtitle in the page is "Task Demands" (task is the requester), "Agent Demands" makes more sense as the provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Good point, I will update that heading and it should go live today. Thank you.
