### ISSUE TITLE
Update load test documentation

### ISSUE THREAD

**Issue by vimanmg** [MicrosoftDocs/azure-devops-docs#9240]
Hi-Ho!

I was wondering if there is any other documentation or does the product team plan to update the existing one regarding load tests:

https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-simple-cloud-load-test?view=azure-devops

Thanks a bunch,
Vi
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74322585-effa-ba29-a9f3-982843169913
* Version Independent ID: 15e8e929-eda0-88af-b173-4773407e95f2
* Content: [Run URL-based cloud load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-simple-cloud-load-test?view=azure-devops)
* Content Source: [docs/test/load-test/get-started-simple-cloud-load-test.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/get-started-simple-cloud-load-test.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@vimanmg Thank you for the feedback.

The current documentation referenced is deprecated and points to [Load test overview](https://docs.microsoft.com/azure/devops/test/load-test/overview?view=azure-devops).

Please describe further these updates and we can assign an author for review.
