### ISSUE TITLE
Rules for incrementing $(Rev:r) could be described more clearly

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-docs#9243]
For example, consider this paragraph:

> Use $(Rev:r) to ensure that every completed build has a unique name. When a build is completed, if nothing else in the build number has changed, the Rev integer value is incremented by one.

, which implies that the value is incremented _after_ a build is completed, which is not accurate because the incremented value is visible in the pipeline run as soon as the pipeline run is started, so the increment must happen _before_ the build started.

Moreover, this line ties `$(Rev:r)` to a date, as do many examples on the page:

> 2 (The third run on this day will be 3, and so on.)

, while the algorithm behind appears to just count the number of times the part of the build number without `$(Rev:r)` was used. For example, if I use `ABC-$(Rev:r)`, then my build number would be `ABC-1`, `ABC-2`, etc. In more practical terms, if I format build number towards the upcoming version `2.1.0` as `2-1-0-$(Rev:r)`, then I get automatically incremented build numbers towards that version, which is quite useful in naming artifacts.

What is great about it, which docs don't mention, is that after I release `2.1.0`, I can change build number to `2-2-0-$(Rev:r)` on _the same branch_ and it will start counting from `1` again. Notice, that the version in this case goes into the build number, not like the following example from the page shows.

I also noticed that if build number does not include `$(Rev:r)`, it will still be incremented behind the scenes, which also would be worth to mention. For example, using `name: ABC` in the pipeline and running it `2` times will yield `ABC` in both cases. If after this I change it to `name: ABC-$(Rev:r)`, it will yield `ABC-3`, which indicates that `ABC` was counted the first two times, even though it was not in the build number string.

Lastly, the example at the bottom of the page seems to be using the build number to form a semantic version string:

>   MyRunNumber: '1.0.0-CI-$(Build.BuildNumber)'

If that's the case, the syntax above makes the pre-release version name to include everything after the first dash, which means that the pre-release does not have a stable name, like `beta` or `CI`. Again, if this is intended to resemble a semantic version, a plus sign would work better to indicate build metadata, like this - `1.0.0-CI+$(Build.BuildNumber)`

https://semver.org/#spec-item-9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for the detailed notes. I'm updating the page now.

**Comment by gh-andre** [comment]
Pardon me if this is an obvious point, but I wanted to mention that it seems Microsoft adopted a practice of using pre-release versions as if they are build numbers and describes promoting pre-release builds here:

https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops#using-views-to-release-packages

While this is a misleading approach in that a pre-release package cannot be converted to a release package without a build, which defies the purpose of package promotion, you may want to check with pipeline dev folks with regards to the `+` separator for build numbers, just to make sure that the page for this issue is aligned with the Microsoft's policies described in the link above. 

For example, DevOps artifact feeds are broken (i.e. they are supposed to be build feeds, not generic public feeds) and won't accept a `+` part of semantic version in packages, which is necessary for proper build promotion, so if the `Rev:r` page mentions the `+` character, it may only cause confusion.
