### ISSUE TITLE
One more section should be in place for Java Application

### ISSUE THREAD

**Issue by hirenrpatel1610** [MicrosoftDocs/azure-devops-docs#9246]
Hi Team,

Currently I are trying to deploy Java Springboot application to Linux VM.

What i felt is there should be one more section over here on that because that guideline is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba99893-154c-bb0d-6d84-9093175b6f43
* Version Independent ID: e792fbe8-cbd7-c760-706f-f59478895db0
* Content: [Build Java apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/java.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Sorry for the late reply. We're adding a mention of Spring Boot.
