### ISSUE TITLE
Where is the developer supposed to set up the system.debug?

### ISSUE THREAD

**Issue by acarlstein** [MicrosoftDocs/azure-devops-docs#9247]
It would be great to have one example displayed the location where the variable system.debug is setup.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@acarlstein Thank you for the feedback, assigning this to the author for review.

For current instructions on how to configure, please see [here](https://docs.microsoft.com/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#debug-mode) and [here](https://stackoverflow.com/questions/60258663/azure-devops-pipeline-difference-between-system-debug-and-enable-system-diagn).
