### ISSUE TITLE
Function missing inside Function App

### ISSUE THREAD

**Issue by lipalath-ms** [MicrosoftDocs/azure-devops-docs#9248]
I have an azure function and I'm trying to deploy this to Azure. I followed this doc and created build/release to deploy the same. On checking Azure, I see function missing inside FunctionApp:

![image](https://user-images.githubusercontent.com/6519992/92661423-7a1bd900-f2b1-11ea-8ff3-83fe02e32056.png)

When I publish this function from Visual Studio to the function app, it is displaying correctly:

![image](https://user-images.githubusercontent.com/6519992/92661363-56589300-f2b1-11ea-8625-22328d7fae37.png)

What build/release step am I missing to publish function to the function app? Please let me know.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b12f39-46e7-7928-3384-ae8b99c67b6c
* Version Independent ID: 2110797a-6604-0989-1504-3e4fe619f899
* Content: [Deploy a function app to Azure Functions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-functions?view=azure-devops&tabs=dotnet-core%2Cyaml)
* Content Source: [docs/pipelines/targets/azure-functions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-functions.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@lipalath-ms Thank you for the feedback.

Users have previously reported intermittent when deploying of when redeploying functions with the same name.

Please refer to [this alternate method](https://stackoverflow.com/questions/56105855/azure-functions-not-showing-up-in-function-app-in-portal) or [this post](https://developercommunity.visualstudio.com/content/problem/978681/azure-function-app-sometimes-does-not-deploy-any-f.html) for help on diagnosing, collecting log info, etc.
