### ISSUE TITLE
Go get not working, really. Remove this page.

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9250]
Is the documentation on this page up to date? We have been trying already a couple of months to consume private repositories with `go get` and had no luck so far. We reported the issue in `https://developercommunity.visualstudio.com/` and Microsoft acknowledged they can reproduce it. (See ticket #1176152)

However, since few months ago is still not working.

I think this documentation should either be removed or inform that this functionality is not working at the moment. Otherwise devs you are wasting the, short and precious life time we have. Since people will try for few hours to use `go get` with Azure DevOps but, as per Microsoft confirmed, it is not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
@JoseFMP this is the first I've heard that it's not working - it's possible the Go ecosystem has moved forward and our guidance hasn't kept up. I'll find a Go expert to review and make sure we have up-to-date instructions.

**Comment by vtbassmatt** [comment]
(And thank you for opening the DevComm ticket - that will also get product group attention in case there are changes we need to make.)

**Comment by JoseFMP** [comment]
@vtbassmatt Thank you so much!

Yes, let's get it working! Let me know if you need any feedback / log from our machines.

**Comment by artbegolli** [comment]
Have you tried with SSH? I've had success with both HTTPS and SSH which had been added to the documentation recently.

**Comment by steved0x** [comment]
It looks like you found the solution in https://github.com/MicrosoftDocs/azure-devops-docs/issues/9814 - I am closing this one, and updating our documentation to reflect the info from that one. Thank you very much for the info.
