### ISSUE TITLE
Bug...

### ISSUE THREAD

**Issue by DynConcepts** [MicrosoftDocs/azure-devops-docs#9251]
[Code does not work with OrgName is in BaseAddress.... works fine if moved to request URI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4abeff84-74e7-7fd3-db28-fa92683143c8
* Version Independent ID: 9d289096-4cf9-cb30-0893-e9ae5a72a34d
* Content: [REST API samples for Azure DevOps and TFS - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/rest/samples?view=azure-devops)
* Content Source: [docs/integrate/get-started/rest/samples.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/rest/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @DynConcepts, This doesn't appear to be a documentation issue, so I'll be closing this issue now. Please don't hesitate to @mention me if you feel differently or have further feedback. Thanks and have a great day.

**Comment by DynConcepts** [comment]
@chcomley - Please explain to me how DOCUMENTATION that provides a code sample containing material it claims to be documenting - where the code sample is something that DOES NOT WORK, is not a DOCUMENTATION issue???

Either:

1) The DOCUMENTATION is wrong and should be fixed.
2) The material being covered is itself broken, and should be DOCUMENTED (again by changing the sample that is in the documentation) to be in such a state.

**Comment by chcomley** [comment]
REOPENED

**Comment by chcomley** [comment]
Hi @DynConcepts, Can you please try the following and let me know whether it works?
You **must** place a slash at the end of the BaseAddress, and you **must not** place a slash at the beginning of your relative URI.

Thanks so much for your feedback!

**Comment by chcomley** [comment]
Hi there DynConcepts, It's been a while since I tried following up with you. I assume this is no longer an issue, but wanted you to know that I've updated the article by adding the required slash at the end of the BaseAddress example. Thanks so much for your feedback.
