### ISSUE TITLE
Deploying an agent through the Azure VM extension

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#9253]
Please include or add a pointer to documentation on how to deploy an agent to an Azure virtual machine by using the available extension for both Windows as well as Linux.

In particular how to set up a Linux environment agent that can be used by a yaml pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64ca92c-b7d5-3142-71fb-306d32a37281
* Version Independent ID: dfef40cf-2f50-4c03-bc97-bafa6c305108
* Content: [Deploy an Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@cveld  Thank you for the feedback, assigning this to the author for further review.

In the meantime, please refer to the [Azure VM extensions](https://docs.microsoft.com/azure/virtual-machines/extensions/agent-windows) documentation.
