### ISSUE TITLE
No Authentication is still wrong

### ISSUE THREAD

**Issue by bdetchison** [MicrosoftDocs/azure-devops-docs#9254]
There have been multiple issues created on this and it still hasnt been fixed correctly:  `[https://github.com/MicrosoftDocs/azure-devops-docs/issues/7693](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7693)

`{
    "id": "endpoint-auth-scheme-none",
    "description": "i18n:Creates an endpoint authentication scheme with no authentication.",
    "type": "ms.vss-endpoint.service-endpoint-auth-scheme-none",
    "targets": [
        "ms.vss-endpoint.endpoint-auth-schemes"
    ],
    "properties": {
        "name": "None",
        "displayName": "i18n:No Authentication"
    }
}
`

The Type should actually be:

`"type": "ms.vss-endpoint.endpoint-auth-scheme-none"`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth-schemes?view=azure-devops)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/auth-schemes.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by bdetchison** [comment]
FYI, I tested this and it does work with the above type that I mentioned

**Comment by chcomley** [comment]
Thanks @bdetchison. This issue will automatically close once my PR goes live with the fix. Thanks again!
