### ISSUE TITLE
What is the syntax for multiple patterns?

### ISSUE THREAD

**Issue by lygasch** [MicrosoftDocs/azure-devops-docs#9256]
Please include example including multiple patterns to download. Patterns doc says "newline delimited" -- in the YAML does that mean this:

patterns: 'pattern/one/*'
  'other/dir/*'
  'more/to/download.txt'

or this (which would technically be an array or list?):

patterns: 
- 'pattern/one/*'
- 'other/dir/*'
- 'more/to/download.txt'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by kenlyon** [comment]
Maybe a compromise would be to add a reminder that you need to say `patterns: |` rather than `patterns:` for it to work. I realize this is probably basic yaml knowledge, but I didn't know and it took a while to figure out.

**Comment by amberic** [comment]
I agree with @kenlyon the docs should be updated. I couldn't figure out how to get this to work until I stubbled across this post https://github.com/MicrosoftDocs/azure-devops-docs/issues/9518. Further, the docs currently say to use itemPattern rather than patterns

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback). We'll add a note in the task doc to use the pipe character.
