### ISSUE TITLE
Add checkboxes inside table

### ISSUE THREAD

**Issue by PiotrPerak** [MicrosoftDocs/azure-devops-docs#9257]
Is it possible to insert checkboxes inside table?
I tried it many ways but none seem to work. Maybe this is not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@PiotrPerak Thank you for the feedback.

Currently only *non-editable* checkboxes are supported using `[ ]` and `[X]` syntax.

The issue of supporting editable checkboxes was recently raised [here](https://developercommunity.visualstudio.com/content/idea/789279/wiki-function-check-list-should-allow-check-wiki-c.html), and is currently being addressed by the product team.

For further updates, please refer to the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html).
