### ISSUE TITLE
List addPipelineData: true/false as an input

### ISSUE THREAD

**Issue by leyshon** [MicrosoftDocs/azure-devops-docs#9260]
[Enter feedback here]
addPipelineData is missing from the listed inputs. If you create the task in the UI and check the YAML it is possible to determine that addPipelineData is an accepted input with possible values of true and false and a default of true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by anraghun** [comment]
Pushed a fix for this. @msebolt We can close this.
