### ISSUE TITLE
Problem converting to Base64

### ISSUE THREAD

**Issue by aelray** [MicrosoftDocs/azure-devops-docs#9262]
I tried converting using bash with you description but the produced token did not work with our Azure DevOps Server 2019.

I obtained:
`.....VhYnBydWxjaGEK`

But when using echo -n everything works fine.

I obtained:
`.....VhYnBydWxjaGE=`

So it seems echo puts a newline character at the end which messes up the PAT.

This was performed using Ubuntu 20.04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops-2019&tabs=preview-page#use-a-pat)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @aelray, Thanks for reaching out and apologies for the delay in response. We'll be in touch soon with some clarity. Thank you!

**Comment by chcomley** [comment]
Hi @aelray, I've update the article. Please take a look to be sure I've captured it correctly. I added the " -n" prior to ":$MY_PAT" | base64). If you have any further feedback, please let me know. Also, please consider[ becoming a contributor to our docs!](https://docs.microsoft.com/en-us/contribute/) Thank you. This issue will automatically close, once the PR merges. Thanks!
