### ISSUE TITLE
Wrong value in B64_PAT

### ISSUE THREAD

**Issue by alexey-gusarov** [MicrosoftDocs/azure-devops-docs#9263]
[Enter feedback here]
In my case (through wsl ubuntu 20.04)
```B64_PAT=$(echo  ":$MY_PAT" | base64)``` add 'newline' symbol and wrap on 76 symbl

There is fixed version:
```B64_PAT=$(echo -n ":$MY_PAT" | base64 -w 0)```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by aelray** [comment]
duplicate of #9262
