### ISSUE TITLE
Should the region for a DevOps instance align with the primary region for Azure Cloud resources?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#9264]
Is there any benefit to having them both the same for things like build and release pipelines or does it not really matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@StingyJack Thank you for the question.

This becomes an issue on network latency versus dependency of the Azure task.

Please refer to [Azure network latency](https://docs.microsoft.com/azure/networking/azure-network-latency) and [view relative latencies](https://docs.microsoft.com/azure/network-watcher/view-relative-latencies) for more information on providing diagnostic.
