### ISSUE TITLE
Spelling error.

### ISSUE THREAD

**Issue by smcthompson** [MicrosoftDocs/azure-devops-docs#9268]
In the following sentence on the page, the **bold** word is misspelled:

> There isn't any live updates control, it simply happens in the **backgroun**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d807b7f-4e44-1e86-7f41-1e67f9c0e1bd
* Version Independent ID: 6798865e-0273-2991-9376-abe53725aaac
* Content: [Customize a Taskboard - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/customize-taskboard?view=azure-devops)
* Content Source: [docs/boards/sprints/customize-taskboard.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/sprints/customize-taskboard.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@smcthompson - Thanks for the notice. I'll correct the spell error soon.
