### ISSUE TITLE
Using v4 with Azure Blob throw permission error, v3 works without issues

### ISSUE THREAD

**Issue by mohamed-shehata-m** [MicrosoftDocs/azure-devops-docs#9277]
Hello,

We have multiple azure file copy tasks v3 with destination type "Azure blob".

All of them are using azure resource manager service connection (using automatic method) and have contributor access over resource groups that contains storage accounts. We do not have issues with deployment.

I tried upgrading one of the tasks to v4, I received the following error while deploying:

 INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42

![image](https://user-images.githubusercontent.com/25155380/93191706-209a2b00-f745-11ea-8fa3-c53f8e20abff.png)

Once I change back to v3, deployment succeeds.

Does v4 need (storage blob data contributor)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@mohamed-shehata-m  Thank you for the feedback.

This issue has been previously reported under https://github.com/microsoft/azure-pipelines-tasks/issues/13159.  Please refer there for further updates.

Closing this issue now.
