### ISSUE TITLE
Missing parameters' documentation in "Publish Code Coverage Results task"

### ISSUE THREAD

**Issue by lmorvan** [MicrosoftDocs/azure-devops-docs#9278]
There is no documentation for these parameters:
#reportDirectory: # Optional
#additionalCodeCoverageFiles: # Optional

I do need to understand what additionalCodeCoverageFiles is supposed to do.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@loicmorvan-ansys Thank you for the feedback, assigning this to the author for review.

Please refer to the [repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishCodeCoverageResultsV1/task.json) for these descriptions and note the latest version of this task is now [V2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV2).

**Comment by PBoraMSFT** [comment]
Adding @shashban as I have moved to a different team.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
