### ISSUE TITLE
Register-PSRepository code snippet is unhelpful

### ISSUE THREAD

**Issue by catbusstop** [MicrosoftDocs/azure-devops-docs#9280]
The following code snippets should be revised:

`Register-PSRepository -Name "PowershellAzureDevopsServices" -SourceLocation "https://<org_name>.pkgs.visualstudio.com/<project_name>/_packaging/<feed_name>/nuget/v2" -PublishLocation "https://<org_name>.pkgs.visualstudio.com/<project_name>/_packaging/<feed_name>/nuget/v2" -InstallationPolicy Trusted -Credential $credsAzureDevopsServices`

And 

`Find-Module -Repository PowershellAzureDevopsServices`

The first code snippet uses the -Credential parameter on Register-PSRepository which was never implemented and doesn't do anything. In fact, it also appears to have been removed and credential persistence is being re-evaluated according to this issue:

https://github.com/PowerShell/PowerShellGet/issues/102

Instead, the page should show that you need to register the repository without the credentials and instead, Find-Module should be passed the -Credential parameter instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@catbusstop Thank you for the feedback.

This issue has been previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8145, please refer there for further updates.
