### ISSUE TITLE
Error in text or description

### ISSUE THREAD

**Issue by seraphim72** [MicrosoftDocs/azure-devops-docs#9282]
"The Users page isn't available for on-premises server instances. However, you can use Azure DevOps CLI to manage users."

Is this possible? My understanding was that the DevOps CLI was not available on premise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d0fe85-7e69-29b7-206f-797a168505c1
* Version Independent ID: 0e1f085d-0d1f-32bf-51e2-c60bc3f0a763
* Content: [Delete, remove users from team, project, organization - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/delete-organization-users?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/delete-organization-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/delete-organization-users.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @seraphim72, You can use the CLI to manage users in Azure DevOps Server 2020. Perhaps I'll make that note a bit clearer, thanks for the feedback. Please feel free to @mention me if you have any further questions. Thanks again.
