### ISSUE TITLE
The documentation of Artifact commands is unclear/incorrect.

### ISSUE THREAD

**Issue by vadimcn** [MicrosoftDocs/azure-devops-docs#9285]
- For ##vso[artifact.associate]:
  - What is the purpose of each artifact type?  
  - What is the difference between `container` and `filepath` artifact types?
- For ##vso[artifact.upload]:
  - The purpose of `containerfolder` parameter is unclear.
  - The [first code example](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#upload-upload-an-artifact) shows the command without any parameters, but in reality `artifactname` seems to be required, whereas `containerfolder` is not - in contradiction to what parameter documentation says.
  - Can it be emitted multiple times to several multiple files to the same artifact?  (Seems like yes?)
  - Can it be used to specify the relative file path within the artifact?   (Again, seems that it can - by appending relative path after `containerfolder`, however in combination with multiple uses, it produces an error that the specified artifact already exists.   Would be good to clarify how this was designed to be used.)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@ramiMSFT Can you take a look at this?

**Comment by ramiMSFT** [comment]
@juliakm Sorry this got lost in my inbox. I'll take care of the PR
@vadimcn Artifact associate creates a link to an existing artifact, while Artifact upload adds a new Artifact. Container is the build Artifact 'drop' (same for containerFolder) while filePath can be a fileshare.
Feel free to reach out to [Azure DevOps developer community](https://developercommunity.visualstudio.com/search?space=21) for questions unrelated to docs
