### ISSUE TITLE
Error in AUTHORIZATION header code example

### ISSUE THREAD

**Issue by DrSLDR** [MicrosoftDocs/azure-devops-docs#9287]
The code snippet under https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#alternative-to-using-the-checkout-submodules-option shows adding the `extraheader` config as an HTTP Auth. header using the `Bearer` method. This will not work - `Bearer` is for OAuth Authorization and a user cannot generate the appropriate token with the instructions given. Instead, the correct metod is `Basic`.

The corrected code snippet then becomes:

```
git -c http.https://<url of submodule repository>.extraheader="AUTHORIZATION: Basic <BASE64_ENCODED_STRING>" submodule update --init --recursive
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#checkout)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@DrSLDR Thank you for the feedback.

This issue has previously beenreported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/5540, please refer there for further updates.

**Comment by vijayma** [comment]
Thanks @DrSLDR for pointing this out. We are updating the doc to fix this. It should roll out soon.
