### ISSUE TITLE
Note about DevOps Servers without Internet Access

### ISSUE THREAD

**Issue by nearwood** [MicrosoftDocs/azure-devops-docs#9289]
Using NPM scopes is also very useful when a self-hosted Azure DevOps Server does not have internet access. Setting the feed to get upstream packages will not work, so this is the only option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aef169d-c6cd-a5ff-35f8-e6c5f33f1e0a
* Version Independent ID: 75f1bba1-927b-a1fc-8cfc-12519ad132c7
* Content: [Use npm scopes for private packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows)
* Content Source: [docs/artifacts/npm/scopes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/scopes.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by herenhuang** [comment]
Thanks for the comment! We can add that as a possible comment within our docs here: https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/scopes?view=azure-devops&tabs=windows

**Comment by ramiMSFT** [comment]
@nearwood Thank you for your feedback. The updated version will go live shortly
