### ISSUE TITLE
Get error when using task 'PublishCodeCoverageResults@1' in azure-pipelines.yml.

### ISSUE THREAD

**Issue by ATYUYTA** [MicrosoftDocs/azure-devops-docs#9290]
#### Situation
It works normal when we using cloud build agent. But It returns error in publishing test report when we use the local build agent. It can't generate the test report after the test step is done.

#### Version 

* os : ubuntu 16.04
* dotnet : 2.1.810
* Error :

/usr/bin/dotnet /home/RCTAzureAutoAgent/azure_agent/_work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.160.4/netcoreapp2.0/ReportGenerator.dll -reports:/home/RCTAzureAutoAgent/azure_agent/_work/1/s/TestResults/*/coverage.cobertura.xml -targetdir:/home/RCTAzureAutoAgent/azure_agent/_work/_temp/cchtml -reporttypes:HtmlInline_AzurePipelines -sourcedirs:/home/RCTAzureAutoAgent/azure_agent/_work/1/s 2020-09-16T14:41:00: Arguments 2020-09-16T14:41:00: -reports:/home/RCTAzureAutoAgent/azure_agent/_work/1/s/TestResults/*/coverage.cobertura.xml 2020-09-16T14:41:00: -targetdir:/home/RCTAzureAutoAgent/azure_agent/_work/_temp/cchtml 2020-09-16T14:41:00: -reporttypes:HtmlInline_AzurePipelines 2020-09-16T14:41:00: -sourcedirs:/home/RCTAzureAutoAgent/azure_agent/_work/1/s Assert Failure Expression: [Recursive resource lookup bug] Description: Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: ArgumentNull_Generic

#### Solution

We already find the solution by updating the [file](https://github.com/microsoft/azure-pipelines-tasks/blob/513477ce8b123027e99d09208c39fb5e70fdae04/Tasks/PublishCodeCoverageResultsV1/publishcodecoverageresults.ts#L174).

After updating 'netcoreapp2.0' to 'netcoreapp2.1', the task works.

#### Request 
We will need to manually edit the file after we add a new build agent in local. This will cause an issue. 
Could you help to update the [file](https://github.com/microsoft/azure-pipelines-tasks/blob/513477ce8b123027e99d09208c39fb5e70fdae04/Tasks/PublishCodeCoverageResultsV1/publishcodecoverageresults.ts#L174) in Github? Or do you have any better solution?

I also create a [help desk ticket ](https://developercommunity.visualstudio.com/content/problem/1186778/get-error-when-using-task-publishcodecoverageresul.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by msebolt** [comment]
@ATYUYTA Thank you for the feedback.

For issues with specific files, please move this issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

For all documentation updates, please reference any changes below and we can assign this to the author for further review.
