### ISSUE TITLE
Different value per stage (env) for a variable in a group

### ISSUE THREAD

**Issue by jagwaran** [MicrosoftDocs/azure-devops-docs#9291]
I use a variable group in multiple deployment pipeline, because I have several applications which has it's own release timeline. So I use to run the specific app's release pipeline. And all these app release pipelines uses a 1 or more variable groups. And I have around 10 stages (env)

Now, how do I set variable value exists in a variable group per stage (env).

**Comment by msebolt** [comment]
@jagwaran Thank you for the question.

Please refer to [this post](https://stackoverflow.com/questions/57485621/share-variables-across-stages-in-azure-devops-pipelines) on the current set of options for sharing variables across stages.
