### ISSUE TITLE
Wrong product name on Github Enterprise Server page

### ISSUE THREAD

**Issue by kopetan-ms** [MicrosoftDocs/azure-devops-docs#9295]
[Failing checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github-enterprise?view=azure-devops#failing-checkout) sections mentions that Microsoft hosted agents may not be able to reach the **Bitbucket** server. As this page is for **Github Enterprise Server**, I assume this is a mistake and it should mention **Github Enterprise Server** instead.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b14972b7-883c-37c8-96f9-114327f15e05
* Version Independent ID: 00baf3e0-f225-dc97-a15d-f9d97dac28d2
* Content: [Build code from GitHub Enterprise Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github-enterprise?view=azure-devops)
* Content Source: [docs/pipelines/repos/github-enterprise.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github-enterprise.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by kopetan-ms** [comment]
#9296

**Comment by msebolt** [comment]
@kopetan-ms Thank you for contributing to the docs!  

Please see [become a contributor](https://docs.microsoft.com/contribute) for further information.  Closing this issue now.
