### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by lucassms9** [MicrosoftDocs/azure-devops-docs#9298]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89132320-da86-8a4e-4468-cf651561892c
* Version Independent ID: 4946284d-9666-4a15-9e03-72377693ecb0
* Content: [Copy Files Over SSH task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/copy-files-over-ssh.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/copy-files-over-ssh.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@lucassms9 Thank you for the feedback.

Can you please include more information surrounding this issue?
