### ISSUE TITLE
Documentation update needed in scale-set agents?

### ISSUE THREAD

**Issue by shehanWeer** [MicrosoftDocs/azure-devops-docs#9300]
According to the latest announcement in [Azure scale-set agent general availability](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-175-update#general-availability-of-scale-set-agents) does it need to update the documentation in [Azure virtual machine scale set agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#azure-virtual-machine-scale-set-agents) as well? Still the doc says it's a preview feature.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@shehanWeer Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
