### ISSUE TITLE
Information on this page needs review and updating

### ISSUE THREAD

**Issue by kunaldhanuka** [MicrosoftDocs/azure-devops-docs#9305]
I used the 'VSBuild@1' task in my pipeline and I got this warning

##[warning]The 'Restore NuGet Packages' option is deprecated. To restore NuGet packages in your build, add a NuGet Tool Installer task to your build definition.

Please update the information accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@kunaldhanuka Thank you for the feedback.

This information is listed under the `restoreNugetPackages` options parameter listed [here](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops#arguments).

If you have any further issues with the documentation please comment below.
