### ISSUE TITLE
Definition of Cycle & Lead Time Does Not Match Diagrams

### ISSUE THREAD

**Issue by SotaJoe** [MicrosoftDocs/azure-devops-docs#9307]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by sss01** [comment]
![cfd-metrics](https://user-images.githubusercontent.com/71515849/93615267-c98c9400-f998-11ea-8bf6-1893e74c4ecc.png)

**Comment by sss01** [comment]
The definition of Lead Time and Cycle Time in this graphic are both incorrect according to the definitions.

**Comment by SotaJoe** [comment]
The two documents that we are referencing for cycle and lead time definitions are:

LEAD TIME AND CYCLE TIME WIDGET:
https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cycle-time-and-lead-time?view=azure-devops

CUMULATIVE FLOW GUIDANCE:
https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops

Notice that the diagram that @sss01 mentioned in the "Cumulative Flow Guidance" document does not match the definitions for cycle and lead time according to both documents referenced above.

**Comment by KathrynEE** [comment]
@SotaJoe - Thank you for the feedback and apologies for the delayed response. I agree that the diagram needs to be updated. I'll be updating the article by the end of the week to reflect a more accurate diagram.
