### ISSUE TITLE
dotnet pack projects multiline fails

### ISSUE THREAD

**Issue by Danielovich** [MicrosoftDocs/azure-devops-docs#9310]
I have this yaml

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    arguments: --include-source --include-symbols
    projects: |
            src/**/*.csproj
            !src/Test/**/*.csproj
    versioningScheme: byBuildNumber

on 'restore' and 'build' command the project argument works fine. But on the 'pack' command, the search pattern fails and includes the Test projects in the Test folder.  Why ?

Thank you :)

**Comment by msebolt** [comment]
@Danielovich Thank you for the feedback.

Per [this post](https://stackoverflow.com/questions/61081825/how-do-i-stop-dotnet-pack-building-the-project-in-azure-devops-no-build-doesn) there is an issue with `pack` arguments and you should use `dotnet custom` as a work around.

To solicit additional feedback from the product team, please move this to the [community](https://developercommunity.visualstudio.com/spaces/21/index.html).  Please refer to a recently reported issue [here](https://developercommunity.visualstudio.com/content/problem/540546/dotnet-pack-task-v2-negation-filter-not-working.html).
