### ISSUE TITLE
Please explain in detail on how to use output variable

### ISSUE THREAD

**Issue by mehulparmariitr** [MicrosoftDocs/azure-devops-docs#9314]
Please explain in detail on how to use output variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#use-output-variables-from-tasks)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@mehulparmariitr Thank you for the feedback.

More details on output variables are discussed further in [set variables in scripts](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#set-variables-in-scripts).

Unfortunately as the platform migrates away from Classic mode, the added documentation favors more examples in YAML.  As such, only faulty examples and/or general issues between both Classic and YAML can be addressed.

If such a case exists, please include the reference and we will process accordingly.
