### ISSUE TITLE
Typo: promoted -> prompted

### ISSUE THREAD

**Issue by hamish-smith** [MicrosoftDocs/azure-devops-docs#9315]
`To use OAuth, login to Bitbucket when promoted during pipeline creation` 
This should say 'prompted'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf09cc7f-cd4d-6647-e47b-82744bd3d2dd
* Version Independent ID: 75e80c27-0e2e-41d1-272f-e3da856f5071
* Content: [Build Bitbucket Cloud repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/bitbucket.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/bitbucket.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@hamish-smith Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
