### ISSUE TITLE
Is there any model in .net sdk that I can re-use?

### ISSUE THREAD

**Issue by longjiabo** [MicrosoftDocs/azure-devops-docs#9316]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by msebolt** [comment]
@longjiabo Thank you for the question.

The simplest method is to use a .NET [web client](https://docs.microsoft.com/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client) and call the [service hook](https://docs.microsoft.com/rest/api/azure/devops/hooks/?view=azure-devops-rest-6.0) APIs.

To use a .NET API wrapper, please refer to [client libraries](https://docs.microsoft.com/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops).

For further functionality to be added, please make recommendations and solicit feedback from the product team in the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html).
