### ISSUE TITLE
aaaaaa

### ISSUE THREAD

**Issue by oyyunttt** [MicrosoftDocs/azure-devops-docs#9319]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608a8c53-51a9-0878-da16-bfb7f977e01b
* Version Independent ID: 52155a9a-b7bf-607c-a90d-547395f059d6
* Content: [Manage paid access for users in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops#select-the-default-access-level-for-new-users)
* Content Source: [docs/organizations/billing/buy-basic-access-add-users.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/buy-basic-access-add-users.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@oyyunttt Thank you for the feedback.

For any issues you might be having, please provide the context and/or references below and we will try best to provide a resolution.
