### ISSUE TITLE
Invalid example in the YAML snippet - xmlTransformationRules

### ISSUE THREAD

**Issue by Zhaph** [MicrosoftDocs/azure-devops-docs#9320]
YAML snippet is badly formed, and references invalid predefined variables for CI/CD pipelines:

> `#xmlTransformationRules: '-transform **\*.Release.config -xml **\*.config-transform **\*.$(Release.EnvironmentName).config -xml **\*.config' # Optional`

`xmlTransformationRules` is a multiline input, there's no break between the two commands listed in this example.

`$(Release.EnvironmentName)` isn't available in CI/CD pipelines, only in the classic Release pipelines. Should be `$(Environment.Name)` or `$(System.StageName)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@Zhaph Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
