### ISSUE TITLE
Documentation omits critical setup steps

### ISSUE THREAD

**Issue by cpdohert** [MicrosoftDocs/azure-devops-docs#9322]
No part of this page works.  It's clearly out of date or just wasn't tested.

1. Simply signing in is not sufficient; there's an additional undocumented step where a window prompts the user to set up the app before being able to use the integration
1. The screenshots don't reflect the actual response windows from the app
1. Subscriptions don't work at all.  `@azure pipelines subscribe [Azure DevOps url to pipeline]` doesn't return anything from the app
1. `@azure pipelines subscriptions` returns nothing from the app
1. Typing `@azure pipelines` immediately replaces that text with the blue-fonted "Azure Pipelines" and appears to drop me into a search box for specific builds.
1. `@azure pipelines subscribe [Azure DevOps url to project]` doesn't return any response either.

Either this app doesn't work or you've documented functionality that hasn't been implemented yet.

Oh, and this is my favorite paragraph:
>"For Build pipelines, the channel is subscribed to the Build completed notification. For Release pipelines, the channel is subscribed to the Release deployment started, Release deployment completed, and Release deployment approval pending notifications. For YAML pipelines, subscriptions are created for the Run stage state changed and Run stage waiting for approval notifications."

So there's a list somewhere of all the possible notifications and what events in the pipeline trigger those notifications, right?  It turns out there is, it's buried in the Service Hooks page.  Wouldn't it be cool if there a link to that page from this one so the reader has some idea of what these notifications mean?  Alas, no such link exists and I had to use Google to find the relevant section of your own docs.

UPDATE:  Ah, I've found it.  Your documentation leaves out the fairly critical step that in order for the app to work at all, the user has to Click on Apps in the Team sidebar, search for Azure Pipelines in the left-side search box, click on the Azure Pipelines tile when it appears, click the down arrow next to the Open button, select "Add to a team", manually enter the channel name and click "set up a bot" and THEN the `@azure pipelines` commands will work.

That's 7 or 8 clicks.  Or, as we call it in the software business, "an epic cluster**** of a documentation and UX fail".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @divais
* Microsoft Alias: **divais**

**Comment by msebolt** [comment]
@steved0x @mijacobs Needs to be reassigned to another author.

**Comment by steved0x** [comment]
#reassign steved0x

**Comment by KonTheCat** [comment]
Can this get some attention please? Doc still looks like it is missing the critical and not very clear step identified by @cpdohert

**Comment by chcomley** [comment]
Hi all, I've started updating the article. My goal is to publish on Monday, 11/22. Cheers!
