### ISSUE TITLE
FileTransform V2 has different parameters to V1

### ISSUE THREAD

**Issue by Zhaph** [MicrosoftDocs/azure-devops-docs#9323]
`FileTransform@2` has different parameters to the V1 version, so this page should probably be updated to cover that.

V2 version removes the `fileType` parameter and replaces the `targetFiles` parameter with explicit parameters for XML and JSON files:

- `xmlTargetFiles`
- `jsonTargetFiles`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@Zhaph Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8871.

Please refer there for further updates.
