### ISSUE TITLE
No Follow button in TFS2019

### ISSUE THREAD

**Issue by NagsenM** [MicrosoftDocs/azure-devops-docs#9326]
I do not see Follow link available in TFS2019 anymore. Is that no longer available? If yes, how to follow a single work item similar to TFS2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fb5639-2338-9141-1129-682e46676f7f
* Version Independent ID: 5002bb9e-5ec3-d773-2843-8b20468d6c69
* Content: [Track updates by getting notified of changes made to a user story, bug, or other work item or pull request - Azure Boards & Azure Repos](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/follow-work-items?view=azure-devops)
* Content Source: [docs/boards/work-items/follow-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/follow-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NagsenM - Thank you for your inquiry. The Follow link is still supported in TFS 2018 and later versions.  If it isn't showing up in your work item form, then there must be some other issue going on. Please file an issue on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
