### ISSUE TITLE
Pipeline Resources triggering based on commit

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/azure-devops-docs#9328]
Nowhere in the documentation explains the ability for the pipeline resource to be linked to the same commit as the commit that is being triggered on the root pipeline. Is this ability possible and if not will it be possible in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@hecflores  Thank you for the question.

Trigger options can vary depending on the type of repo you're using, please refer to [triggers](https://docs.microsoft.com/azure/devops/pipelines/build/triggers?view=azure-devops) for more information.

While branches are typically used to as a trigger, tags can be used as well, also in combination with something like `Build.SourceVersion` from [build variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services).

Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/372241/cant-tag-my-commit-with-a-variable.html) for further details.
