### ISSUE TITLE
Uses classic pipelines

### ISSUE THREAD

**Issue by deltadan** [MicrosoftDocs/azure-devops-docs#9329]
Would like to see this updated to use yaml pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9d58d3-169a-2ffd-5bcf-02daa8d8ac04
* Version Independent ID: a4ae226e-1622-fb62-cfb6-d06bc7c35e84
* Content: [Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/automate-terraform?view=azure-devops)
* Content Source: [docs/pipelines/release/automate-terraform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/automate-terraform.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@deltadan Thank you for your feedback. YAML section added
