### ISSUE TITLE
The note on the top of is "strange/confusing"

### ISSUE THREAD

**Issue by tholp** [MicrosoftDocs/azure-devops-docs#9330]
The note on the top of the page about selecting the correct product/version is very confusing; where is the dropdown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
@tholp I hear you, but am not sure what you would prefer. It says it's in the upper left part of the page, and shows a screenshot. Do you have suggestions on making it more clear?

<img width="813" alt="image" src="https://user-images.githubusercontent.com/714283/94015384-c7e91480-fd7a-11ea-9415-df9e58bedc97.png">

**Comment by tholp** [comment]
Sorry, I must have missed it.  Maybe because it is in a position I didn't notice, it just looks like the first entry in the contents.  On other pages version info is (or used to be) in the header of the page, together with the info stating where you are, etc.

**Comment by vtbassmatt** [comment]
No worries! And I was not trying to be snarky - if there's a way we could make it more obvious, I'm game to do that. For now I'll close this issue, but I'll get notified if you respond again with any ideas. Thanks!
