### ISSUE TITLE
how to update the format of new added field

### ISSUE THREAD

**Issue by JunlingShang** [MicrosoftDocs/azure-devops-docs#9331]
[Enter feedback here]
 For example, in the item "bug" I added one new field with name "Root Cause Analysis", format is sigle line, but I want to update the format to multi lines, how can I do this?  Or I just have to delete this field and add it back again with new format?   If yes, then how about the old bug?  I means if I deleted the   "Root Cause Analysis" field, and add it back with new format, how does the old bug display the field ""Root Cause Analysis"?  thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e91f24-96da-f420-cba0-f9c140c98dc3
* Version Independent ID: d62be590-4ccb-1ffb-78c8-3ae07e998720
* Content: [Add a custom control to a WIT - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-controls-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/custom-controls-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/custom-controls-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@JunlingShang - You can't edit the Field type once you've added the field. You need to delete it and then add a new field of the type you want. Once you add the new field, it will display on the bug form as expected. Please read: 
- https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=azure-devops#delete-a-field 
- https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-field?view=azure-devops#add-a-custom-field
