### ISSUE TITLE
Documation Kubectl task incorrect

### ISSUE THREAD

**Issue by MarvinSchenkel** [MicrosoftDocs/azure-devops-docs#9332]
The code examples for the 'Generic Secrets' section are incorrect. The following two properties need to be removed in order to successfully deploy a secret to AKS using a literal:
```yaml
command: apply
arguments: -f mhc-aks.yaml
```
This would otherwise result in the error: "error: must specify one of -f and -k"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@MarvinSchenkel Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9081, please refer there for further updates.
