### ISSUE TITLE
Using wildcards in path to select files

### ISSUE THREAD

**Issue by itsjusth** [MicrosoftDocs/azure-devops-docs#9333]
My pipeline triggers look like this:

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - closing-checklist*
  paths:
    include:
    - packages/closing-checklist-ui/
    - packages/closing-checklist-common/
    - packages/ui-components/
    - deploy/closing-checklist/appsettings.ui.*
    exclude:
    - README.md
    - deploy/*

Merges to Master branch that should trigger a build are not.  My last change was to add "- deploy/closing-checklist/appsettings.ui.*" in the paths.  The documentation does not mention anything about selecting multiple files like this.  Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@itsjusth Thank you for the question.

Please refer to [file matching patterns](https://docs.microsoft.com/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops) and if there are any further issues please comment below.
