### ISSUE TITLE
variable from a powershell script executed on the target machine

### ISSUE THREAD

**Issue by placidseven** [MicrosoftDocs/azure-devops-docs#9334]
How do we return a variable from a powershell script executed on the target machine?

**Comment by msebolt** [comment]
@placidseven Thank you for the question.

Please refer to the [PowerShell FAQ](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#faq) on how to set [output variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable).  There is also a recent post on this [here](https://stackoverflow.com/questions/52333871/azure-devops-setting-and-using-variables-in-powershell-scripts).

If there are any further issues please comment below.
