### ISSUE TITLE
Create Branch Policy Permission

### ISSUE THREAD

**Issue by darren-j-mcleod** [MicrosoftDocs/azure-devops-docs#9336]
How do you give someone the permission to create a Branch Policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@darren-j-mcleod Thank you for the question.

Please see if the permission `EditPolicies` is what you need, you can refer to [Permissions](https://docs.microsoft.com/azure/devops/organizations/security/namespace-reference?view=azure-devops) as a reference.

For something more granular, please move this to the [community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback from the product team.
