### ISSUE TITLE
Hardcoded password in the setting file?

### ISSUE THREAD

**Issue by rvgolovin** [MicrosoftDocs/azure-devops-docs#9338]
May I suggest providing the password using secure variable and ultimately pulling the latest version of the secret form the AKV instead of hardcoding it in the setting file? 
It is a security and maintenance issue to hardcode the secret here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03a84e2-22c7-6899-5ac1-c1ed79c05ba6
* Version Independent ID: 405e0a0e-b12b-3fd3-7135-5deb022cd9c3
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@rvgolovin Thank you for your feedback. This is the recommended approach from Maven documentation. Maven uses 2 different passwords: encrypted server password and master password. Users that have access to your encrypted server password won't be able to decrypt it without the master password. Please refer to the Maven docs [here](https://maven.apache.org/guides/mini/guide-encryption.html#password-encryption)
