### ISSUE TITLE
Information about variables set when using this task

### ISSUE THREAD

**Issue by tboogh** [MicrosoftDocs/azure-devops-docs#9341]
When reading https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build it is documented that the task sets the variable APPLE_CERTIFICATE_SIGNING_IDENTITY is set. "In the Signing identity field, enter $(APPLE_CERTIFICATE_SIGNING_IDENTITY). This variable is automatically set by the Install Apple Certificate task for the certificate you selected."

It would be very helpful if documentation for this, and all, tasks would include variables they set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4f249c-c229-4a5c-7970-4e566026b560
* Version Independent ID: 7062bdf1-7b38-b42b-e117-c3041e09aae7
* Content: [Install Apple Certificate task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-apple-certificate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/install-apple-certificate.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here (under the Settable Variables section):
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/install-apple-certificate-v2?view=azure-pipelines#requirements

Please check it out and let us know what you think. Thank you.
