### ISSUE TITLE
resource trigger pipeline variables not present in devops server 2020 rc2

### ISSUE THREAD

**Issue by matteo-savore-deltatre** [MicrosoftDocs/azure-devops-docs#9342]
In the documentation i read that  when a resource triggers a pipeline should be available two variables:

resources.triggeringAlias
resources.triggeringCategory

but printing env in the triggered pipeline, it doesn't print values, neither the variables name. Also pipeline doesn't substitute them in a task definition

Is it a documentation bug so those variables do not exist in devops server 2020 rc2 or they should exist and there is a bug in the devops server 2020 rc2 ?

Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema&viewFallbackFrom=azure-devops-2020#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by davibe** [comment]
@msebolt As I tried to explain in my duplicated bug (#9344) I do not think this is a documentation bug. Triggering alias is needed as it is the only way to know which `resources.piplelines` triggered the current pipeline.

**Comment by msebolt** [comment]
@davibe  Thank you for the feedback, upon review the author will determine if this requires a change to the documentation.

To solicit feedback for product issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

**Comment by juliakm** [comment]
@matteo-savore-deltatre Could you please file an issue in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? I'm able to reproduce the same issue and will follow-up with the development team.

**Comment by matteo-savore-deltatre** [comment]
> @matteo-savore-deltatre Could you please file an issue in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? I'm able to reproduce the same issue and will follow-up with the development team.

done! thank you
