### ISSUE TITLE
`resources.triggeringAlias` variable is not available (on premises)

### ISSUE THREAD

**Issue by davibe** [MicrosoftDocs/azure-devops-docs#9344]
The variable `resources.triggeringAlias` is not present in my builds. I made sure my builds are triggered automatically from another build, which is listed under `resources:`. All of that is working file.

I checked with bash `env | sort` and I see pipeline-specific variables correctly set but there is no `resources.triggeringAlias`

The problem with this is that I have no way to know which one of the pipeline listed under `resources:` triggered my build, and this makes it impossible for me to handle release branches packaging of different artifacts from different repos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@davibe Could you please file an issue in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)? I'm able to reproduce the same issue and will follow-up with the development team. I've made the same request in #9342 so there may be an issue to add your notes to.
