### ISSUE TITLE
Unclear how to assign static outbound ip to VMSS

### ISSUE THREAD

**Issue by aristosvo** [MicrosoftDocs/azure-devops-docs#9346]
One of the reasons to start using VMSS is stated as: 

> - You need to open corporate firewall to specific IP addresses so that Microsoft-hosted agents can communicate with your servers.

Although this is the case, there is nothing explained how to assign an outbound IP address to a VMSS to solve for this problem.There is even explicitly stated that 

> Because Azure Pipelines manages the scale set, the following settings are required:
> --load-balancer ""

How should I assign a static outbound ip to configure my allowlist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
hi @aristosvo, the doc contains this info:

Azure pipelines doesn't require a load balancer to route jobs to the agents in the scale set agent pool, but configuring a load balancer is one way to get an IP address for your scale set agents that you could use for firewall rules. Another option for getting an IP address for your scale set agents is to create your scale set using the `--public-ip-address` options. For more information about configuring your scale set with a load balancer or public IP address, see the [Virtual Machine Scale Sets documentation](/azure/virtual-machine-scale-sets/) and [az vmss create](/cli/azure/vmss?view=azure-cli-latest&preserve-view=true#az_vmss_create).

**Comment by aristosvo** [comment]
Thanks for improving the docs!
