### ISSUE TITLE
Incorrect prerequisite

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/azure-devops-docs#9347]
It states

> You must be a **Project Collection Administrator** or the organization Owner to change...

But it appears only the organization Owner is allowed to change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @trajano, Thanks for your feedback. Any PCA could change themselves as the Owner of the organization, and then change the organization location. It's a simple two-step process. So, both would technically be correct. Please let me know if you have any further feedback or questions by @mentioning me. Have a great day!
