### ISSUE TITLE
version control artifact sources - yaml pipelines

### ISSUE THREAD

**Issue by pemj** [MicrosoftDocs/azure-devops-docs#9350]
The list [Supported Artifact Types](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops#supported-artifact-types) doesn't explicitly mention version control artifacts, the sort that are defined [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#artifact-sources---tfvc-git-and-github) for classic pipelines, for instance.  Are they supported in YAML pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34dc460-e0f4-ff01-3c09-1b40864de6c2
* Version Independent ID: 54f9b157-0ae5-e57a-3c1e-3ff58cbfc6f7
* Content: [Artifacts in Azure Pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/artifacts-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/artifacts-overview.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by pemj** [comment]
Ah. I ended up running across this page on the [repo checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops) job in the docs. It looks like, in YAML pipelines, pulling in a git repo is no longer considered to be an artifact-related operation, but is instead rolled into the purview of checkout steps within a job. Is there a way we could add a note to the docs reflecting this, perhaps a link in the Supported Artifact Types section of either the YAML or classic doc, in the sections that already reference one-another, just so nobody else runs into this issue?

**Comment by ramiMSFT** [comment]
@pemj Thank you for your feedback. The updated version will go live shortly
