### ISSUE TITLE
Add information about which version of the REST API is used by the .NET client libraries

### ISSUE THREAD

**Issue by jffaust** [MicrosoftDocs/azure-devops-docs#9352]
I can't find any resource online that would indicate which version of the REST API is being used by which version of the client libraries.

I can't find a way to specify it in the code either. I suggest adding some info about this on the .NET Client Libraries documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jffaust, I'm looking into this. Please accept my apology for the super delayed response!

**Comment by chcomley** [comment]
Hi @jffaust, I'm closing the issue, as it's stale and the article has since been updated. Please @ mention me if you feel your feedback hasn't been properly addressed. Thanks!
