### ISSUE TITLE
Archive file pattern incorrect under 'Extract all .zip files recursively' section

### ISSUE THREAD

**Issue by jmt789** [MicrosoftDocs/azure-devops-docs#9353]
The archive file pattern under the section 'Extract all .zip files recursively' appears to be in correct. It should be **/*.zip NOT */**.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05de2755-a21b-91b8-46b3-05bcb55a1eb6
* Version Independent ID: ababbcfb-e7d4-68f7-423f-1e68201247f4
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
fixed in https://github.com/MicrosoftDocs/azure-devops-docs/pull/9375
