### ISSUE TITLE
Missing information on how to actually create process parameters

### ISSUE THREAD

**Issue by ckolumbus** [MicrosoftDocs/azure-devops-docs#9354]
I'm trying to create new process parameters for a classic tfvc based build pipeline but i cannot find it in the UI and the link to the referenced information does not provide **any** information on how to do it.

It would be good that the referenced doc describes how to do it or at least provide additional links / information on where to find this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec7e5a9-e22e-a329-14cf-6e21e65cc85f
* Version Independent ID: c96aaf4e-f5ec-c42f-05cb-e2366167fbc6
* Content: [Process parameters - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=azure-devops)
* Content Source: [docs/pipelines/process/parameters.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/parameters.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Are you using TFS 2018? If so, these versioned instructions may be helpful - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/parameters?view=tfs-2018

**Comment by ckolumbus** [comment]
@juliakm Thanks for the link!  But the page shows how to use **existing** process parameters already defined in the template. I'd like to **create** a new one that should show up on process level (like the "Solution" parameter in the example on the page above).

**Comment by juliakm** [comment]
@ckolumbus I'm adding documentation shortly on this. It looks like you need to update the json.

**Comment by Narshe1412** [comment]
Was this ever done? I can't find the informaton anywhere. @juliakm @v-andreaco
