### ISSUE TITLE
Masking variables as secret

### ISSUE THREAD

**Issue by rcomanne** [MicrosoftDocs/azure-devops-docs#9355]
After consulting with our Microsoft Affiliate I was able to find that variables can be masked as secrets to prevent them from showing up in the logs, however, I could not find that on this page.
The documentation is apparently found in the [reference documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#setvariable-initialize-or-modify-the-value-of-a-variable) but I would expect it here as well, in the setvariable in scripts part of the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks, I'm adding a link now to the logging page and a note about `issecret`.
