### ISSUE TITLE
 Extract Files task - Azure Pipelines: "archiveFilePatterns" is wrong for "Extract all .zip files recursively" example

### ISSUE THREAD

**Issue by rawbert** [MicrosoftDocs/azure-devops-docs#9356]
The "archiveFilePatterns" is wrong in the "Extract all .zip files recursively" example.

It doesn't work and should instead be `archiveFilePatterns: '**/*.zip'`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05de2755-a21b-91b8-46b3-05bcb55a1eb6
* Version Independent ID: ababbcfb-e7d4-68f7-423f-1e68201247f4
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops#extract-all-zip-files-recursively)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
fixed in https://github.com/MicrosoftDocs/azure-devops-docs/pull/9375
