### ISSUE TITLE
How to set appropriate target framework for Visual Studio Test task

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/azure-devops-docs#9357]
The article states `Tests that target the .NET core framework can be executed by specifying the appropriate target framework value.` but never clarifies where the ` target framework value` is set.

Should refer to https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by shashban** [comment]
docs modified to point to runsettings file for selecting the target version
