### ISSUE TITLE
Load Balancers

### ISSUE THREAD

**Issue by ChrisGibson1982** [MicrosoftDocs/azure-devops-docs#9361]
[Enter feedback here]
The docs state that you have to set the load balancers as "", but is this because it's not supported or is it a limitation of the command?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ChrisGibson1982 Thank you for the question.

A load balancer will be created by default along with the scale set, unless this option is explicitly set to empty, see [az vmss create](https://docs.microsoft.com/cli/azure/vmss?view=azure-cli-latest&preserve-view=true#az_vmss_create).

For additional issues and/or concerns please comment below.
