### ISSUE TITLE
Fix casing for appPoolIdentityForWebsite input argument

### ISSUE THREAD

**Issue by jffaust** [MicrosoftDocs/azure-devops-docs#9363]
I copied the YAML Snippet from the doc and pasted it in my yaml build, updated the `appPoolIdentityForWebsite` to one of the options in the comments but the task fails because I'm not using a recognized option:
![image](https://user-images.githubusercontent.com/4367222/94304902-58bc1d80-ff3e-11ea-9cef-511c2a504e30.png)
![image](https://user-images.githubusercontent.com/4367222/94304932-6376b280-ff3e-11ea-84b3-050a2fa6e3c8.png)

Please fix the case in the comments of the yaml snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@jffaust Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
