### ISSUE TITLE
Can users contribute to their own branches only

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/azure-devops-docs#9364]
This isn't clear from the permission documentation, but is there a way to give users the ability to create branches, and contribute to their own branches, but not contribute for anyone else's?

For example, consider we have users Alice, and Bob. We have the following branches:

- main (protected by policy)
- dev (protected by policy)
- alice/feature1
- alice/feature2
- bob/feature1

I want to allow Dave to create his own branches, and contribute to them, and create new pull requests, but not contribute to alice's branches or bob's branches. 

Is this possible without manually specifying permissions on each branch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@iUnknwn Thank you for the feedback, assigning this to the author for further review.

In the meantime, please refer to [this post](https://stackoverflow.com/questions/63728950/azure-devops-policy-for-branch-creation) and use the prompt to [manually configure the permissions](https://docs.microsoft.com/azure/devops/repos/tfvc/git-permission-command?view=azure-devops).  

A similar issue was posted in the **Azure DevOps** community [here](https://developercommunity.visualstudio.com/idea/1149293/make-automatically-granted-permission-for-authors.html).

**Comment by vtbassmatt** [comment]
At the "All repositories" level in your project settings, you can remove the "Contribute" permission for Contributors (set to "Not set"). This will allow contributors to create new branches (where they'll automatically gain "Contribute" as owner of the branch) but not to contribute to other's branches.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/714283/101068476-c603b480-3566-11eb-8dd5-043fb694f476.png">

**Comment by iUnknwn** [comment]
@vtbassmatt - Thank you so much for the solution. 

Is this in the DevOps documentation? I can't find anything in the docs covering this (I don't think there's anything where 'Not Set' is explained/recommended). 

It would be great if this information could be added to the branch permissions info here: https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops

**Comment by vtbassmatt** [comment]
@iUnknwn - "how permissions work" is documented here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page#permission-settings. 💯 agree that we should link there from the branch-permissions topic. I'll take care of that.
