### ISSUE TITLE
"Pull request commented on" service hook event not documented

### ISSUE THREAD

**Issue by vaindil** [MicrosoftDocs/azure-devops-docs#9367]
The event for "Pull request commented on" is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033d681-9093-547c-20fd-b31183c2bb33
* Version Independent ID: 0d92e3f0-7fb4-57e5-d913-f305a055a819
* Content: [Service hooks event reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops)
* Content Source: [docs/service-hooks/events.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/events.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by ktownsend-cbre** [comment]
Any chance someone will document this service hook? It's been a very long time without documentation to be found anywhere.

**Comment by juliakm** [comment]
We've moved this issue to our internal tracking system as we transition to a [new feedback system](https://aka.ms/contentuserfeedback).
