### ISSUE TITLE
Scale Sets no longer in preview

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/azure-devops-docs#9370]
This page says that the Scale Sets capability is in preview, but it is now GA.

https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-175-update
_In the past couple of months, we released the scale-set agents for preview. **And we're now excited to announce its general availability.**_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@bubbletroubles Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9300, please refer there for further updates.
