### ISSUE TITLE
Include Build Tag Limitations

### ISSUE THREAD

**Issue by tannerwatson** [MicrosoftDocs/azure-devops-docs#9371]
Hit an issue today when attempting to use the `AddBuildTag` command with `:` within it's name. The build failed reporting an error of `##[error]A potentially dangerous Request.Path value was detected from the client (:).` A google search directed me to microsoft/azure-pipelines-agent#2877 which led me to realize the issue was `:`.

I would like the documentation around Logging Commands updated to include an area to describe restricted characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by svengrav** [comment]
![image](https://user-images.githubusercontent.com/23522177/112434571-08cedf80-8d44-11eb-9510-f338d54f15e3.png)

![image](https://user-images.githubusercontent.com/23522177/112434618-15533800-8d44-11eb-81fa-87c86943285a.png)

Got the same error trying to add a url as tag.

**Comment by giorgiococci** [comment]
I have the same problem as @svengrav . Has anyone found a solution?

**Comment by lukemaslany-next** [comment]
Hello, all.

I've just tripped over the same issue when trying to set a build tag in a pipeline using an inline bash task, where the tag contains a semi-colon.

My command is:
```
last_scanned="last_scanned:$(date --utc --iso-8601=seconds)"
echo "##vso[build.addbuildtag]$last_scanned"
```

The error is:
```
Async Command Start: Add Build Tag
Async Command End: Add Build Tag
##[error]A potentially dangerous Request.Path value was detected from the client (:).
```

Does anyone have an example of this working in a pipeline? I'd happily take examples of either Bash or PowerShell.

I'm currently running agent version `2.210.1` on a runner image using `ubuntu-20.04`.

**Comment by MrOwen** [comment]
@lukemaslany-next, @giorgiococci, @svengrav I just posted a workaround for this on a related GH issue: https://github.com/microsoft/azure-pipelines-agent/issues/2877#issuecomment-1292393121

**Comment by juliakm** [comment]
I'll update the article now to include the colon limitation. Please note that there's an active issue for this in the [Developer Community](https://developercommunity.visualstudio.com/t/Error-when-setting-vsobuildaddbuildt/10163239). There does not appear to be a way to easily escape the colon.
