### ISSUE TITLE
Define artifact from feed in resources

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#9376]
Hello,

I am switching from using builds artifacts to publishing them as nuget packages in artifacts feed. I have read in various places that it is also a recommendation and good practice.

However, I wanted to define it in YAML pipeline as `resources packages`, but I guess it is only relevant to GitHub artifacts.
In classic pipelines it is quite easy to set, but I have some troubles when using YAML. Is it only possible to download using `DownloadPackage` task or is there a way to define it in `resources`?

Many thanks!
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mijacobs** [comment]
From the article:
Please see this article:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml
