### ISSUE TITLE
Undocumented behavior on failure

### ISSUE THREAD

**Issue by sylfabre** [MicrosoftDocs/azure-devops-docs#9378]
This comment https://github.com/microsoft/azure-pipelines-tasks/issues/10125#issuecomment-484014918 is very interesting because out of the box, I was expecting a multiline command line task to stop the pipeline if one of the command fails.

A user presented a possible solution for you to implement
https://github.com/microsoft/azure-pipelines-tasks/issues/10125#issuecomment-484167634

Or you can just update the doc on the same model as the `call` command for the Windows CMD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@sylfabre  Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/3265.  Please refer there for further updates.
