### ISSUE TITLE
Group Variable syntax doesn't work as described.

### ISSUE THREAD

**Issue by placidseven** [MicrosoftDocs/azure-devops-docs#9381]
Group Variable syntax doesn't work as described.

variables:
  -group: group

steps:
- script: echo $(name) # uses macro syntax

"line 1: name: command not found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@placidseven Thank you for the feedback.

Please note this is a possible duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/8999.
