### ISSUE TITLE
Environment registration token expire time

### ISSUE THREAD

**Issue by otaskiran** [MicrosoftDocs/azure-devops-docs#9382]
[Enter feedback here]
PAT expires after 3 hours

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d73b50-b26b-3e9e-e8c2-37669424793c
* Version Independent ID: ebde85d2-1f0a-afa8-0597-d084c2b64870
* Content: [Deploy to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/deploy-linux-vm?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/ecosystems/deploy-linux-vm.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/deploy-linux-vm.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by msebolt** [comment]
@otaskiran Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
