### ISSUE TITLE
Managed Identity

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#9387]
It would be great if you could add something about managed identities and if there is any plan to implement it as an alternative to sharing personal access tokens to authorize Azure services such as Azure Functions to interact with the Azure DevOps APIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851595a3-32b8-c0e4-ff4f-aa84cf436175
* Version Independent ID: c2cb9c6c-de29-a7a9-9728-fbbc1d223a4f
* Content: [How are security and identity managed? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?view=azure-devops)
* Content Source: [docs/organizations/security/about-security-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-security-identity.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@cveld - Thank you for your feedback. Our content is focused on documenting what we support. To learn about planned features, we have the [Features Timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline). You can also search or post a suggested feature on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).  Currently, your suggestion isn't on the roadmap. Closing this issue as it doesn't require an update to content.
