### ISSUE TITLE
missing description for options of Member by role

### ISSUE THREAD

**Issue by Metrowerks** [MicrosoftDocs/azure-devops-docs#9388]
It would help to add description for different options (Creator, Reviewers, Changed Reviewers, Reset Reviewers)

I had a hard time to guess what Changed Reviewers mean. Does it mean people whose PR's comments got a response, or people who are removed/added as reviewers in a PR?

Same confusion about Reset Reviewers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c845a7-d230-c0b0-e68c-174246f866bc
* Version Independent ID: a773099c-3af5-dc66-b303-335ccf9875dc
* Content: [Manage notifications for a team or group - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops)
* Content Source: [docs/notifications/manage-team-group-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-team-group-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Metrowerks, Thanks so much for your feedback. I already had a work item slated for October to revisit this article, and I'll add this to the mix. Will let you know once the updated doc is published, thank you.

**Comment by chcomley** [comment]
This article is updated. Thank you!
