### ISSUE TITLE
Possibly missing "the"

### ISSUE THREAD

**Issue by betterly** [MicrosoftDocs/azure-devops-docs#9395]
"Rolling deployments can be configured by specifying the keyword rolling: under strategy: node. "

should be 

"Rolling deployments can be configured by specifying the keyword rolling: under **the** strategy: node." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@betterly  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
