### ISSUE TITLE
How can i use private scripts from private powershell repository in my yaml 

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/azure-devops-docs#9396]
Hey Guys, 
Do you have examples how can i use private powershell repository, wihtin my azure devops pipelines. let's say i have ci/cd scripts in my private repo, how would you recommend to use them within pipelines. Would you need to register psrepository and install module or is there another way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@gintuoklis Thank you for the question.

You can use the [script](https://docs.microsoft.com/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops#connecting-to-the-feed-as-a-powershell-repo) found at the end of the topic and combine this with a secret variable containing the PAT.

The resulting script can then be used in the basic [PowerShell](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#yaml-snippet) task.

For additional help and/or support, please refer to:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
