### ISSUE TITLE
Deploy not being marked as a reserved name in doc

### ISSUE THREAD

**Issue by jose-bueno-microsoft** [MicrosoftDocs/azure-devops-docs#9398]
CSS has been getting many cases where deployments are being queued but never run because they use the word "deployment" as the name for their deployment stage. This is a reserved name, but there is no explicit comment mentioning this is not a word to be used. It is mentioned that keywords should not be used, but nowhere is to be found a place where it is described what a keyword is, or a list of them. 

Please include a note on this, or create a doc/section with a list of keywords or reserved names that must not be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@jose-bueno-microsoft I'll add a note shortly and am working on getting a more extensive list of reserved keywords.
