### ISSUE TITLE
Display what is the equivalent task for Linux.

### ISSUE THREAD

**Issue by aractnido** [MicrosoftDocs/azure-devops-docs#9399]
It would be nice if these pages could like or suggest what are the similar tasks or features but for Linux.

I have the scenario where we need to support two platforms and I'm always researching what is the equivalent in the another platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96dafbb6-b4ba-d4ab-7468-55e6df71b5e1
* Version Independent ID: 634b0719-9641-59fd-9f6f-f3a2082f9b39
* Content: [Batch Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/batch-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/batch-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/batch-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@aractnido Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by msebolt** [comment]
A link to [cross platform scripting](https://docs.microsoft.com/azure/devops/pipelines/scripts/cross-platform-scripting) has been added to page warning.
