### ISSUE TITLE
Azure File Copy task page - arguments section should have parameter names

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/azure-devops-docs#9400]
In the arguments section, we should list argument names such as `sourcePath` and `sasTokenTimeOutInMinutes`. Similar to how we do the Azure CLI page (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops). This will improve usability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@felixtsem5 Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9292.  Please refer there for further updates.
