### ISSUE TITLE
Arguments, RuntimeStack list link missing

### ISSUE THREAD

**Issue by chriswoodle** [MicrosoftDocs/azure-devops-docs#9401]
Hello,
Under Arguments, RuntimeStack, it reads:

"You will see this parameter only when you select Linux Web App in the app type selection option in the task. [Here](supports a number of Built-in images) is the list of Built-in images support"

and does not actually provide a link to the list of Built-in images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d955bb83-fa46-22e0-de73-7700ae214af8
* Version Independent ID: 1f55672f-711e-24fa-e6bc-edc0ca723eba
* Content: [Azure Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@chriswoodle Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
