### ISSUE TITLE
Backlog item limit I believe it is incorrect

### ISSUE THREAD

**Issue by latudor** [MicrosoftDocs/azure-devops-docs#9412]
The limit shown in the documentation page is 10,000. 

While in the interface you can encounter the error limit at only 1000.

![image](https://user-images.githubusercontent.com/59569284/94929971-705f4d00-04ce-11eb-8996-12835138126a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4956039a-8296-c5e7-107e-9f42f1e39f33
* Version Independent ID: aae5a90e-0fc7-ed33-0936-10e37782d0dc
* Content: [Work tracking, process, and project limits - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/object-limits?view=azure-devops)
* Content Source: [docs/organizations/settings/work/object-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/object-limits.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@latudor Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
