### ISSUE TITLE
Is there a possibility to tag wiki sites

### ISSUE THREAD

**Issue by MarRich1** [MicrosoftDocs/azure-devops-docs#9417]
The biggest problem with wiki sites is to find the right one ;)
Therefor I would like to have a possibility to tag the site with common key words

I tried this using `<!-- My Keywords -->` and with `[//]: # ( My Keywords )` none of them seems to be indexed/used in the search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @MarRich1, Thanks for reaching out. We'll be in touch soon with some clarity. Thanks!

**Comment by MarRich1** [comment]
Looking forward to ;)

**Comment by chcomley** [comment]
@MarRich1, You can always [Suggest a feature on the  Developer Community website](https://developercommunity.visualstudio.com/spaces/21/index.html). Please @mention amitkumariiit if you have any further questions. Thanks so much.
