### ISSUE TITLE
Mac OS seems not be updated

### ISSUE THREAD

**Issue by MarRich1** [MicrosoftDocs/azure-devops-docs#9418]
According to this chapter [Can I update my v2 agents that are part of an Azure DevOps Server pool?](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2019&tabs=browser#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool) I have updated the build agent version which will be provided by the TFS environment

For Windows and Linus agents it work fine, but the Mac OS version seems not be correct

<hr/>

_**correct:**_
![image](https://user-images.githubusercontent.com/50577700/95050226-7716db80-06eb-11eb-9a9a-d1d199ba4249.png)
<hr/>

_**not correct:**_
![image](https://user-images.githubusercontent.com/50577700/95050220-72eabe00-06eb-11eb-83fa-6cfb455b9cac.png)
<hr />

**content of the mentioned folder**
![image](https://user-images.githubusercontent.com/50577700/95050235-7aaa6280-06eb-11eb-8e95-a23c6d48f228.png)
<hr />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2019&tabs=browser#can-i-update-my-v2-agents-that-are-part-of-an-azure-devops-server-pool)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
This was a product issue but it has been fixed.
