### ISSUE TITLE
Missing URL: management.azure.com

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#9419]
When using the **Azure CLI** (with the **Azure DevOps extension**), it tries to connect to `management.azure.com`, which does not seem to be part of this list and I think it should be. :)

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by chcomley** [comment]
Hi @NenoLoje, Thanks for your feedback. I've just published this update, which should be live momentarily. Thanks again! In the future, please consider [becoming a contributor to our docs!](https://docs.microsoft.com/en-us/contribute/)!
