### ISSUE TITLE
Displayed Supported Actions don't align with actual supported actions

### ISSUE THREAD

**Issue by MattDavisRM** [MicrosoftDocs/azure-devops-docs#9423]
There seems to be a markdown issue on the display of screenshot under the workflow rules supported action section.  Additionally, the actual supported actions are not accurate.  I don't have the option for "Restrict the transition to state..." under the group 1 conditions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbe3c173-e8cc-7172-7331-11c3fc0f9724
* Version Independent ID: ee6e18ae-8ec3-613d-3644-35f1f2199e77
* Content: [Restrict workflow transitions, apply rules to workflow states - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/apply-rules-to-workflow-states?view=azure-devops)
* Content Source: [docs/organizations/settings/work/apply-rules-to-workflow-states.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/apply-rules-to-workflow-states.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MattDavisRM - Thanks for calling this to our attention. Am fixing this now.
