### ISSUE TITLE
Page could use an update

### ISSUE THREAD

**Issue by mattwiz** [MicrosoftDocs/azure-devops-docs#9427]
The pip commands listed for Linux and Windows shouldn't be necessary anymore because the Microsoft-hosted agents have been updated with newer versions that what is listed here as a requirement. 

Also, the setting the default Azure DevOps organization and project should look the same across OSs:
az devops configure --defaults organization="$(System.TeamFoundationCollectionUri)" project="$(System.TeamProject)" --use-git-aliases true
The given examples sometimes use hardcoded values or pipeline variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@mattwiz I am updating this article to use a simpler example and I am fixing the issues that you raised. Thank you for letting us know.

**Comment by steved0x** [comment]
#assign steved0x
