### ISSUE TITLE
If AutoComplete is turned on, what is behaviour of Approving with Suggestions?

### ISSUE THREAD

**Issue by Camios** [MicrosoftDocs/azure-devops-docs#9429]
I'm a little vague on Approve with Suggestions are they just TODOs kept outside the code? Does anything track them?

If AutoComplete is turned on, what is behaviour of Approve with Suggestions?
To my understanding Approve with Suggestions should give the author the opportunity to incorporate the suggestions in that PR before it completes, but if Autocomplete occurs then will they get an opportunity to review them before the PR completes?
Can you confirm/document the behaviour of this please?

Are the "optional suggestions" any comment or limited to comments which contain "Suggestions" (i.e. markdown enclosed code change that can be applied). Is there a workflow to easy way to apply the later  and complete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@Camios  Thank you for the feedback, assigning this to the author for further review.

In the meantime, please consider to review over the [Approvals Update API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/approvals/update).

**Comment by Merlin2001** [comment]
I can confirm that **even with unresolved review comments** containing code suggestions, **Azure DevOps will merge the PR as soon as you click _Approve with suggestions_** when auto-complete is enabled.

Since this is the case, I wonder what the difference to a regular _Approve_ is?

Please document this behavior or make it obvious that _Approve with suggestions_ will immediately trigger a merge, too.
