### ISSUE TITLE
Clarify permissions needed to configure upstream sources

### ISSUE THREAD

**Issue by TomaBusarov** [MicrosoftDocs/azure-devops-docs#9430]
The doc does not mention what permissions are required to configure upstream sources. I'm particularly interested as I want to limit this to specific set of people

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@TomaBusarov Thank you for reaching out. By default the owner, the contributor, and the collaborator roles can all save packages from upstream sources. Your `@local` view is where all the saved packages from upstream sources will be located. If you want a very limited access to your packages, you should restrict both the feed and the view permissions.
See [Access and permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops) for more details.
The following sections will be very helpful too:
[Adding users/groups permissions to a feed](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#adding-usersgroups-permissions-to-a-feed)
[Understanding feeds and views permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#understanding-feeds-and-views-permissions)

**Comment by TomaBusarov** [comment]
Thanks @ramiMSFT! My question was about permissions to add/remove upstream sources, rather than who could use them to save packages into the feed.

**Comment by ramiMSFT** [comment]
@TomaBusarov Only feed owners have the permissions to add and remove upstream sources.
