### ISSUE TITLE
Unable to find Visual Studio Marketplace Extension Statistics in PowerBI

### ISSUE THREAD

**Issue by warrenbuckley** [MicrosoftDocs/azure-devops-docs#9431]
Please remove or update this documentation if the Power BI extension **Visual Studio Marketplace Extension Statistics** can no longer be installed anymore.

See the following GIF below to see my flow on getting to this PowerBI docs page via VSCode Marketplace when managing my own extension.

Can someone from the PowerBI or VSCode Marketplace team please give some feedback if this can be done or not please.

![vscode-stats-powerbi-issue_new](https://user-images.githubusercontent.com/1389894/95304421-7feae700-087c-11eb-9ed7-e305c76c03d3.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0c4c36-bf68-3950-e6fa-d1f4ab728f8b
* Version Independent ID: 088e51cc-a926-ffb7-53b9-2f53fdc65d14
* Content: [Extension Statistics Power BI Content pack - Visual Studio Marketplace](https://docs.microsoft.com/en-us/azure/devops/marketplace/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/marketplace/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @warrenbuckley, Thanks for reaching out. We're removing the Power BI reference from the Marketplace. Once it's removed, I'll be retiring this article, for which I've created a user story. Thanks again and I hope you have a great day.  If you have any further questions or feedback, please don't hesitate to @mention me.

**Comment by warrenbuckley** [comment]
Do you know if the VS Marketplace team will give us more data/metrics/insights into our VS Code extensions as a replacement at all, now this is not officially supported @chcomley ?

**Comment by chcomley** [comment]
Hi @warrenbuckley, I don't, however I'm adding @pkuma-msft and @prashantvc for their input. Thank you.

**Comment by prashantvc** [comment]
Hey @warrenbuckley 
I am the PM with marketplace team, we are working on surfacing more data to extension authors.
I would love to chat with you to understand the useful insights/data as extension author, and how you used PowerBI interface.

Please use this link to book some time that works for both of us 😄  https://book.ms/prchol@microsoft.com

**Comment by warrenbuckley** [comment]
@prashantvc I am happy to chat to you if you think it would be worthwhile, but here are some initial thoughts.
I never got to use the PowerBI tools/integration so I can't comment on that

## Useful insights
* Number of installs per specific version - Have most people upgraded or still on an older version
* Countries where its being used & count - Where is it most popular
* Number of unique users rather than just total installs & acquisitions
* Number of uninstalls

I have the recommended npm package installed in my extension as mentioned by the docs, however I have no real idea on how to use Azure Insights and understand the data and how to query it, could I recommend the docs for that to be extended to help extension authors understand common queries or insights they might want to see.

https://code.visualstudio.com/docs/getstarted/telemetry#_for-extension-authors
https://github.com/Microsoft/vscode-extension-telemetry
