### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by phenixita** [MicrosoftDocs/azure-devops-docs#9436]
The examples for the authoring commands should include the quotation marks :) Example:

`Write-Host "##vso[build.updatebuildnumber]build-number"`
or
`echo "##vso[build.updatebuildnumber]build-number"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@phenixita Thank you for the feedback.

The examples seem to include quotation marks.  

Is there a specific reference in particular where this is missing?  Perhaps the examples were already fixed?

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are further issues.
