### ISSUE TITLE
Example for dockerComposeFileArgs is missing

### ISSUE THREAD

**Issue by sdebruyn** [MicrosoftDocs/azure-devops-docs#9438]
An example where dockerComposeFileArgs is used, is missing.
It says `Example: dockerComposeFileArgs:` but there is nothing there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#run-a-specific-service-image)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by anraghun** [comment]
Raised a fix, @msebolt we can close this.
