### ISSUE TITLE
Clarity around minimum permissions require to setup a service connection via Azure Dev Ops

### ISSUE THREAD

**Issue by NelsonLamprecht** [MicrosoftDocs/azure-devops-docs#9439]
It would be helpful if the minimum permissions necessary for a service connection to azure was added to this document. Trial and error proves that contributor rights on the web app was enough but its not clear what it should be to be least privilege.  
At minimum, it seems to need this: Microsoft.Web/sites/config/list/action but it could be detailed more explicitly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by ramiMSFT** [comment]
@NelsonLamprecht Thanks for your feedback! you must be part of the Endpoint Creator group in your project settings: **Project settings** > **Service connections** > **Security**. Contributors are added to this group by default.

**Comment by NelsonLamprecht** [comment]
> @NelsonLamprecht Thanks for your feedback! you must be part of the Endpoint Creator group in your project settings: **Project settings** > **Service connections** > **Security**. Contributors are added to this group by default.

After rereading, I think my question was the permission necessary on the web app in azure but my that wasn't clear from my initial statement...
