### ISSUE TITLE
Guest User Access (Preview) docs out of date

### ISSUE THREAD

**Issue by djm2k** [MicrosoftDocs/azure-devops-docs#9443]
See [this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops#the-user-has-only-guest-permission-in-the-directory), where step 8 refers to a toggle switch which has been replaced by the following radio buttons: 
![image](https://user-images.githubusercontent.com/36978885/95396952-cfe5ae80-094d-11eb-8183-c2bf1717d2a7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by djm2k** [comment]
This documentation is still out of date over 3 years later. It's a quick fix really so i believe it should stay open

**Comment by cebundy** [comment]
Thank you for reporting this issue.  I created a work item. 
#please-close
