### ISSUE TITLE
Update csv Data

### ISSUE THREAD

**Issue by Warlord-SR71** [MicrosoftDocs/azure-devops-docs#9452]
Any idea what will happen if we regularly update the csv file with new data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import or update work items from a CSV file - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Warlord-SR71 - I don't understand your question. What are you looking to accomplish and how?

**Comment by KathrynEE** [comment]
@@Warlord-SR71 - I'm closing this issue. Please reopen if you can provide more details in terms of clarifying your inquiry.
