### ISSUE TITLE
YML Approach Queuing pull request deploys

### ISSUE THREAD

**Issue by tiny-dancer** [MicrosoftDocs/azure-devops-docs#9454]
How does one configure the first section with YML?  Currently our branch policy triggers a pull request deployment however, if a new commit occurs to the pull request while a deployment is in progress - the in progress pipeline is immediately cancelled during the deplyment and the environment ends up in fail state.  This continuously requires manual intervention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by ramiMSFT** [comment]
@tiny-dancer Thank you for your feedback. To set up your triggers using YAML, please check out the [CI triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers) and [PR triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers) articles.
If you still have the same issue with your pipeline getting cancelled every time you push a new commit, please reach our to us at [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and our team will be happy to help.

**Comment by tiny-dancer** [comment]
[This](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#multiple-pr-updates) was this the hidden gem, thank you
