### ISSUE TITLE
Clarify Location for NuGet.config

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/azure-devops-docs#9455]
Copy the xml code snippet in the Project setup section and add/create a nuget.config file for your project. Place your file in the same folder as your .csproj or .sln file.

In my project, these are in different locations, which should be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5b066ca-c13e-9f25-3add-844012d105f1
* Version Independent ID: 47ac81a1-d4a7-8d74-b59a-2cf143a9684c
* Content: [Get started with NuGet packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@aaronstackpole Thank you for reaching out. It's up to you whether you want it to be available to a specific project or to your entire solution. For project-level, you just need to place it in your project root folder.

**Comment by aaronstackpole** [comment]
The nuget.config and package.config files are required to be in the \Metadata folder.
