### ISSUE TITLE
Resource Webhook: Json Payload

### ISSUE THREAD

**Issue by hprashar** [MicrosoftDocs/azure-devops-docs#9456]
URL: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema

The documentation only talks about how to consume json payload through powershell and not any other chosen language/task. What if I need to consume json payload in Python, Shell etc.  My requirement is to use python to consume json payload triggered through external source but struggling to figure out the correct way to do it.

**Comment by msebolt** [comment]
@hprashar Thank you for the feedback, assigning this to the author for further review.

In the meantime, consider use of the [Python script](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/python-script) task and for further issues please comment below.
