### ISSUE TITLE
Permission precendence on inheritance is not correctly documented

### ISSUE THREAD

**Issue by IngmarVoigt2** [MicrosoftDocs/azure-devops-docs#9458]
The following statement is wrong:
> "For members of the Project Collection Administrators or Team Foundation Administrators groups, Deny doesn't trump Allow" 

If I deny "Contribute" rights on the master of my git repo for the "Contributors" group, Project Collection Administrators which are also part of that group cannot push or merge / complete PRs to master. 

I would really appreciate if this could be fixed ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa32191d-6d0a-058f-2ffe-3ce1b58e2c59
* Version Independent ID: 858d1ed3-b2af-699f-9d51-86ac0962086b
* Content: [How are permissions and groups defined? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page#permission-settings)
* Content Source: [docs/organizations/security/about-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@IngmarVoigt2 - Could you clarify if you believe the content is inacurrate, or you believe the way the system works should be changed. If the latter, please file your request on our  [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by KathrynEE** [comment]
@IngmarVoigt2 - I'm closing this issue. Please reopen if you can provide more clarifying information. Thank you.
