### ISSUE TITLE
Link no longer makes sense

### ISSUE THREAD

**Issue by kyleburnsdev** [MicrosoftDocs/azure-devops-docs#9460]
The link referencing testers' need for Basic access (https://visualstudio.microsoft.com/products/visual-studio-online-Basic-vs) takes the user to a page about GitHub Codespaces. I expected to be taken to a page either discussing Basic AzDO access or AzDO access levels in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf72265-156c-de8c-d729-ba7b3b90193d
* Version Independent ID: 1a0c7272-6d36-6036-06cf-5801b55e2f70
* Content: [Create manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-test-cases?view=azure-devops)
* Content Source: [docs/test/create-test-cases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/create-test-cases.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kyleburnsdev Thank you for the feedback.

The documentation has been updated and is pending review.
