### ISSUE TITLE
Typo in Numbering under "Where are my .npmrc files?"

### ISSUE THREAD

**Issue by anjelo** [MicrosoftDocs/azure-devops-docs#9461]
Under **Where are my .npmrc files?** section, the numbering goes something like:
```
1. 
  a.
  b.
  c.
5.
6.
2.
```
Are numbers 5 and 6 actually under number 1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a25fb7f-d07f-f92e-55db-a44d41bd6e51
* Version Independent ID: 63828151-7f31-7abc-7a52-c4538815e368
* Content: [Set up your client's npmrc - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#set-up-authentication-on-your-dev-box)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@anjelo  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by ramiMSFT** [comment]
@anjelo Thank you for your feedback. Yes (it should be d,e).
