### ISSUE TITLE
Add Pipeline widget to the dashboard

### ISSUE THREAD

**Issue by gianlucagravina** [MicrosoftDocs/azure-devops-docs#9465]
Coming to this page trying to add Pipeline analytcs to a dashboard. The title seems to refer to specific pipeline widgets, but the content just refers to normal widget creation in a normal dashboard, not pipeline reference anymore.

![image](https://user-images.githubusercontent.com/55887306/95679701-29c4cd80-0c07-11eb-9414-983c97902439.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5fa8a9-922d-4717-2d71-74debbd2f95a
* Version Independent ID: 57dd23e4-fa9f-e4e3-6c53-7905cf9db9ae
* Content: [Add a widget to a team dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/add-widget-to-dashboard?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/report/dashboards/add-widget-to-dashboard.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/add-widget-to-dashboard.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gianlucagravina - You are correct. Thank you for the feedback. I will update the TOC entry to reflect that it is generic widgets you can add. 
@steved0x - just FYI
