### ISSUE TITLE
Typo in header "Search limitaitons"

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/azure-devops-docs#9468]
"Search limitaitons" => "Search limitations"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki, and work item search - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=azure-devops-2020)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jessehouwing, Thanks so much for pointing this typo out! I've just published the update. In the future, please consider [becoming a contributor](https://docs.microsoft.com/en-us/contribute/), we'd love it!
