### ISSUE TITLE
Docs feedback - Pull request templates 

### ISSUE THREAD

**Issue by liamharries** [MicrosoftDocs/azure-devops-docs#9469]
[Enter feedback here]

Not sure if this is the correct space as it's probably more of a feature request than a docs feedback.

Anyway it would be great to have Branch specific pull request templates but from named branches not to them. The example on this page shows different templates for merging into different branches (template1 for merging to master and template2 for merging to dev). my use case would be merging into master from branches called Bug/##NAME## and feature/##NAME##

I would like to have a different template based on whether the user is merging a bugfix or a new feature as we have different checks based on the type of change.

If this is possible then can the documentation be updated to show this and if not can it be looked at as a potential new feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by mijacobs** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
