### ISSUE TITLE
No clone button available. Instructions do not work. 

### ISSUE THREAD

**Issue by JPPintoDotCom** [MicrosoftDocs/azure-devops-docs#9473]
No clone button available. Instructions do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/clone.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@JPPintoDotCom Thank you for the feedback.

Possible duplicate of https://github.com/MicrosoftDocs/azure-devops-docs/issues/6628.

**Comment by vtbassmatt** [comment]
@JPPintoDotCom can you share a screenshot of what you do see? If it's like the other two related issues, you may be viewing a TFVC repo rather than a Git repo.
