### ISSUE TITLE
Allow MSA to auth to Azure DevOps REST API using MSAL?

### ISSUE THREAD

**Issue by rzulkoski** [MicrosoftDocs/azure-devops-docs#9475]
Are there any plans to enable using an MSA (personal Microsoft account) to authenticate to the Azure DevOps REST API using MSAL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 851595a3-32b8-c0e4-ff4f-aa84cf436175
* Version Independent ID: c2cb9c6c-de29-a7a9-9728-fbbc1d223a4f
* Content: [How are security and identity managed? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity?view=azure-devops)
* Content Source: [docs/organizations/security/about-security-identity.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-security-identity.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rzulkoski - There are no plans at this time to support MSAL. You can always request it be supported through our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
