### ISSUE TITLE
Docker Example doesn't work

### ISSUE THREAD

**Issue by AHoran** [MicrosoftDocs/azure-devops-docs#9476]
The docker example depends on a parameter that is not specified parameters.cacheImages, and so doesn't work 'out of the box'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by AHoran** [comment]
There's additional problems with the sample. The docker load command should be:
` docker load -i $(Pipeline.Workspace)/docker/cachedDocker.tar`

**Comment by ramiMSFT** [comment]
@AHoran Thanks for the feedback!

**Comment by ramiMSFT** [comment]
@AHoran Thank you for your feedback! The updated content will go live shortly
