### ISSUE TITLE
New Test Plan for Azure DevOps Server - Sign into Azure DevOps Services

### ISSUE THREAD

**Issue by parvski** [MicrosoftDocs/azure-devops-docs#9479]
The first steps in Azure DevOps Server 2020 RTW release notes says to log into the Azure DevOps Services account. This should be updated to reflect working with Azure DevOps Server. Here is the page: 
https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2020?view=azure-devops#new-test-plan-page

![image](https://user-images.githubusercontent.com/23108689/95894941-dd3cd780-0d57-11eb-8700-4936201e9912.png)

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by KathrynEE** [comment]
@parvski - Thank you for the feedback. The article is now updated.
