### ISSUE TITLE
Wiki page menu options for code wikis aren't matching documentation

### ISSUE THREAD

**Issue by davidj488** [MicrosoftDocs/azure-devops-docs#9480]
This topic suggests that the menu options for the two types of wikis (Provisioned wiki and publish code as wiki) are expected to be different, but we are observing that they are the same - when checking several code wikis we see all the options documented as being available only on a Provisioned wiki as also being visible for a code wiki.

I suspect this topic is out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cb387d-5f46-0743-efbb-c393c4e5bd85
* Version Independent ID: cb6912c2-e640-f992-0a1f-5cbbe88d87dc
* Content: [Differences between provisioned and published wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/provisioned-vs-published-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/provisioned-vs-published-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/provisioned-vs-published-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @davidj488, Thanks so much for your feedback. We'll be in touch soon with a solution. Thanks!

**Comment by chcomley** [comment]
Hi @davidj488, I've made some updates and replaced screenshots, thank you. This issue will automatically close once my pull request is complete. Please @mention me if you have any further feedback! Thank you!
