### ISSUE TITLE
This is all wrong, none of this works or is even well written.

### ISSUE THREAD

**Issue by marc-downer-tdx** [MicrosoftDocs/azure-devops-docs#9482]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5b066ca-c13e-9f25-3add-844012d105f1
* Version Independent ID: 47ac81a1-d4a7-8d74-b59a-2cf143a9684c
* Content: [Get started with NuGet packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=new-nav&viewFallbackFrom=vsts#publish-a-package)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@marc-downer-tdx Thank you for your feedback. The article has been updated few times since you posted the issue. I hope you will find this helpful.
