### ISSUE TITLE
Missing API documentation for Storing Data and Settings for an Extension.

### ISSUE THREAD

**Issue by Skinner007** [MicrosoftDocs/azure-devops-docs#9485]
The how-to for storing data and settings (https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops) makes reference to APIs used, but does not provide any documentation for the APIs. The link to the existing API documentation provided in the how-to (https://docs.microsoft.com/en-us/rest/api/azure/devops/extensionmanagement/installed%20extensions?view=azure-devops-rest-6.1) has zero documentation for these APIs.

Please document the APIs used for storing / retrieving / deleting data and settings (Settings and Documents) from an extension.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8490096d-54dd-697b-62a3-9c930d0733d1
* Version Independent ID: 04f42aed-a8c2-f124-1c32-37daf54e8400
* Content: [Data and Setting Storage - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops)
* Content Source: [docs/extend/develop/data-storage.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/data-storage.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Skinner007, I apologize for the delayed response, but am looking into this. Thanks for your feedback.

**Comment by james-world** [comment]
Any updates on this?

**Comment by chcomley** [comment]
Hi @james-world, The link you provided is exactly where any existing APIs should be documented. It's unclear to me whether the APIs exist and aren't documented or whether the APIs might not exist. Can you please provide some of the APIs you're referring to? Thanks for reaching out.

**Comment by SamJ07** [comment]
This is still an issue. @chcomley, the API exists but there is no documentation for the document storage endpoints in the [Azure DevOps API reference](https://learn.microsoft.com/en-us/rest/api/azure/devops/extensionmanagement/installed-extensions?view=azure-devops-rest-7.2). I am trying to use this via the azure-pipelines-task-lib node package (which acts as a wrapper for the API) but without the API documentation I am having a difficult time understanding what the different parameters mean/do.

**Comment by chcomley** [comment]
I've just reopened this issue and reached out to one of my contacts. Thank you and I'm sorry for the difficulties.

**Comment by chcomley** [comment]
Hi @samJ07, I heard back from the SME and they said that while updating the documentation of public APIs is already in their backlog, there aren't immediate plans to execute on it due to capacity limitations. I'm sorry for the frustration.

They recommend that you use the wrappers instead, since both the Extension SDK and the Task SDK have one. 

I'm officially closing the issue, but if you have further questions about any particular parameters, I can connect you with a team member, so just @mention me.

**Comment by SamJ07** [comment]
@chcomley Thank you for trying. As mentioned above, I am already using the wrapper. This seems to be a recurring theme within the DevOps space lately. See: [more incomplete documentation](https://github.com/microsoft/azure-pipelines-task-lib/issues/930) and within the wrapper itself, [incomplete functionality](https://github.com/microsoft/azure-devops-node-api/issues/415). 

It makes me wonder, with no immediate plans and the issue(s) closed, are these _ever_ going to be revisited?
