### ISSUE TITLE
Confusing Sentence

### ISSUE THREAD

**Issue by andrewjg** [MicrosoftDocs/azure-devops-docs#9486]
This sentence is poorly formatted and confusing.
> When you link work items of the same type with parent-child links—such as bug-bug or user story-user story, you create same-category links. or between work items that appear on the same backlog level Same-category links are parent-child links among work items that belong to the same work tracking category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0f3ea-b59f-1f67-b0be-dfb773aafab0
* Version Independent ID: d5c25240-899d-e9b7-c4f5-1f157bcaa515
* Content: [Fix cannot reorder backlog - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/resolve-backlog-reorder-issues?view=azure-devops)
* Content Source: [docs/boards/backlogs/resolve-backlog-reorder-issues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/resolve-backlog-reorder-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@andrewjg  - Thank you for the feedback. Agree that is not well worded. WIll update the article today.
