### ISSUE TITLE
Visual Studio Marketplace Extension Statistics app no longer available on PowerBI

### ISSUE THREAD

**Issue by jsmartinelli** [MicrosoftDocs/azure-devops-docs#9490]
The Visual Studio Marketplace Extension Statistics app is no longer available on PowerBI.  Please update this page with the correct app to use or remove the page if  this is no longer possible.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4baac6c-eaa0-6e71-75fd-697a665b1b2c
* Version Independent ID: 057516df-2053-ca80-2d57-5ee2af974273
* Content: [Extension Statistics Power BI Content pack - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/extend/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jsmartinelli Thank you for the feedback.

This issue was previously filed with [https://msit.powerbi.com](https://msit.powerbi.com), please refer to https://github.com/MicrosoftDocs/azure-devops-docs/issues/7604.
