### ISSUE TITLE
Can't configure timeout on manual intervention

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/azure-devops-docs#9493]
The documentation says "specify the automatic response (reject or resume the deployment) after a **configurable timeout** occurs.", but there is nowhere to configure the timeout. 

Either the configuration control for the timeout is missing from the task, or the documentation is wrong and you can't configure the timeout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
It is a fixed interval of 60 days for timeout. This is fixed in our new task reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-intervention-v8?view=azure-pipelines&viewFallbackFrom=azure-devops
