### ISSUE TITLE
Mermaid section needs more detail

### ISSUE THREAD

**Issue by ValocityPrinz** [MicrosoftDocs/azure-devops-docs#9494]
The following information would make mermaid diagram editing a lot simpler:

- Specify what version of mermaid is supported
  - a lot of syntax which work in [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor) fails to render in the wikis
- Wiki specific formatting rules for mermaid, plenty of single line formats need to be broken out into multiple lines for rendering to work in the wikis

The following are feature enhancements for wikis with regards to mermaid:

- Support latest version of mermaid
- Support all the diagram types
- Prevent clipping of symbol text, many of my diagrams are displaying with truncated text.
- Let live preview in web editor render mermaid WYSIWYG, this works fine in the VS Code extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ValocityPrinz, Thanks for your feedback. I've followed up on this and will be in touch soon. Have a nice day!

**Comment by chcomley** [comment]
Hi @amitkumariiit, following up on this, please advise. Thanks very much!

**Comment by amitkumariiit** [comment]
Hi @ValocityPrinz,
We are at mermaid version 8.2.6 and with this version some of features doesn't work properly.
Thanks a lot for the suggestions to improve the wiki experience!  Can you please raise a [suggestion ticket](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) for the same? It will help us in prioritising the suggestion.

**Comment by chcomley** [comment]
Hi @ValocityPrinz, Per Amit's request for you to [create a suggestion ticket ](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) for those feature enhancements, I'll be closing this issue. Please don't hesitate to reach out with any further documentation questions or concerns by @mentioning me. Thank you and hope you have a great remainder of 2020.
