### ISSUE TITLE
testResultsFiles

### ISSUE THREAD

**Issue by wakeup44** [MicrosoftDocs/azure-devops-docs#9499]
multiple paths instead of semicolon use pipe sign (|) without quotes
          testResultsFiles: |
            **/test-reports/TEST-*.xml
            **/security-reports/TEST-*.xml
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba91e46a-de53-c0c1-f7f7-c02e797d527c
* Version Independent ID: 6f478148-461f-694a-ed82-deb4d731854e
* Content: [Publish Test Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml)
* Content Source: [docs/pipelines/tasks/test/publish-test-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-test-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by msebolt** [comment]
@wakeup44  Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/2914 and is currently under review.  Please refer there for further updates.
