### ISSUE TITLE
Provide Base Docker Images

### ISSUE THREAD

**Issue by lmmarsano** [MicrosoftDocs/azure-devops-docs#9505]
Do base Linux & Windows docker images exist with the minimal container job requirements.
If so, please identify them.
If not, why not provide them so we're not all retreading the same steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@lmmarsano You can see all of the available Microsoft images on Docker [here](https://hub.docker.com/publishers/microsoftowner). If there are images missing that you'd like to see added, please add a request in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
