### ISSUE TITLE
URL with visualstudio.com

### ISSUE THREAD

**Issue by phenixita** [MicrosoftDocs/azure-devops-docs#9508]
Hi team,
I've found that the provided queries in this page do not work because of the old scheme URL with visualstudio.com.
I managed to solve the issue by using the format `https://analytics.dev.azure.com/{OrganizationName}/{ProjectName}/_odata/{version}`

Michele

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37158821-909f-e3a0-8be3-7a57c99fa769
* Version Independent ID: fbe40e6a-b511-609b-27dc-51843a331cee
* Content: [Apply a team filter to a Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-team-filter?view=azure-devops)
* Content Source: [docs/report/powerbi/create-team-filter.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/create-team-filter.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@phenixita - Thank you for this feedback and apologies for the delay in response. I'm updating the article now and closing this issue.
