### ISSUE TITLE
Wrong B64_PAT generated by bash command from doc because of trailing newline char

### ISSUE THREAD

**Issue by gchamon** [MicrosoftDocs/azure-devops-docs#9511]
In the reference docs for creating Basic authentication tokens based off PAT, there is a problem with the following bash script
:

```bash
MY_PAT=yourPAT		# replace "yourPAT" with your actual PAT
B64_PAT=$(echo ":$MY_PAT" | base64)
git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone https://dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName
```

When generating the `B64_PAT`, a trailing newline character issued by the `echo` command would render the resulting encoded string unusable. The correct command should be:

```bash
B64_PAT=$(echo -n ":$MY_PAT" | base64)
```

When using the `-n` flag, `echo` won't append a newline at the end of the output to `stdout`.

For me, after using the modified command, I was able to generate a usable encoded token for communicating with Azure Devops Rest API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@gchamon  Thank you for the feedback.

This issue was previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9262 and is currently under review.  Please refer there for further updates.
