### ISSUE TITLE
Image is old and missing a step

### ISSUE THREAD

**Issue by GitMje** [MicrosoftDocs/azure-devops-docs#9512]
Image for step #2 on this page is old, the "+ Create subscription" button is now just a "+" and it lists all service hooks.

Also, between step #3 and step #4, there is a screen for the actions like "build complete".  The image for step #3 is old as well, which makes it a little confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f632a9-2ab3-d7f4-4c7e-dc9a18e0a7e9
* Version Independent ID: eb818eb7-0e79-8cad-ee03-e6c90802218b
* Content: [Create a service hook for Azure DevOps Services and TFS with Datadog - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/datadog?view=azure-devops)
* Content Source: [docs/service-hooks/services/datadog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/datadog.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @GitMje, Thanks so much for your feedback. You're right, this article needs to be updated! There's a pre-existing GitHub Issue, #8948, which also specifies that an update is necessary. I've created a user story to address both issues, and so I'll be closing this issue. You can track the update [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/8948), if you want. Thanks again! Also, please consider [becoming a contributor](https://docs.microsoft.com/en-us/contribute/) to our docs!
