### ISSUE TITLE
Example script has been truncated or contains errors

### ISSUE THREAD

**Issue by QuadmanSWE** [MicrosoftDocs/azure-devops-docs#9514]
A script looks to have been truncated before pasted into the article.
The script is following "The following Powershell script creates firewall rules. You can check-in this script as SetAzureFirewallRule.ps1 into your repository."

The argument is missing its value.
`-EndIPAddress $`
should be
`-EndIPAddress $agentIp`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@QuadmanSWE Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
