### ISSUE TITLE
Availability in On-prem DevOps Server???

### ISSUE THREAD

**Issue by robinsedlaczek** [MicrosoftDocs/azure-devops-docs#9515]
When can we see this function in DevOps Server (on-prem)? Would be really appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe69098-cb25-e821-6478-09d37da13769
* Version Independent ID: 315ab15b-2bd3-fe38-9e70-b997b99a56cc
* Content: [Clone a Hosted XML process to an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/upgrade-hosted-to-inherited?view=azure-devops)
* Content Source: [docs/organizations/settings/work/upgrade-hosted-to-inherited.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/upgrade-hosted-to-inherited.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@robinsedlaczek - Thank you for your inquiry.  There are no plans to clone a Hosted XML process or an On-premises XML process as an inherited process.  You can suggest this as a feature or up-vote one if it's already suggested on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
