### ISSUE TITLE
File matching patterns reference - newline-delimiter

### ISSUE THREAD

**Issue by AlfiCode** [MicrosoftDocs/azure-devops-docs#9516]
Please explain / show which kind of "newline-delimiter" have to be used.
I'll tried many in an azure-yml file for DownloadPipelineArtifact-patterns but none of them worked.
A single entry worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by ramiMSFT** [comment]
Please use the `|` character. E.g. `?(hello|world)`
