### ISSUE TITLE
What are the "gitconfig" settings for user name and token used in authentication?

### ISSUE THREAD

**Issue by dsorak** [MicrosoftDocs/azure-devops-docs#9519]
I need to know where / what gitconfig setting controls the token used in authentication and the user name used in authentication so I do not have to enter it EVERY time.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c28e08d-10ad-65f0-7145-0dcc9c94d780
* Version Independent ID: ca19fff9-06fa-6f95-a2fc-df12a7849112
* Content: [gitconfig files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-config?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/git-config.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-config.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Auth information isn't stored in Git configuration. You need the [Git Credential Manager](https://github.com/microsoft/Git-Credential-Manager-Core), or if you're using Visual Studio, it should handle auth for you. As this is more of a product support question than a docs question, I'm closing it. If you have further trouble, you can post on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) for help.
