### ISSUE TITLE
No Support for Generic Environment Resources

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/azure-devops-docs#9520]
I see that Azure DevOps yaml supports Kubernetes and Virtual Machines for deployment tracability in the form of "resources". Is there a reason there doesnt just exists a "generic" resource that is created if the resource is referenced through yml but doesnt exists yet? The same as environments are managed. That way jobs and commits will be recorded by resource based on the name of the resources. 

Example:
`
environment: environment_name.resource_name
`

And the environment **environment_name** is created and the "generic" resource is created **resource_name**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mijacobs** [comment]
The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
