### ISSUE TITLE
Service Connections: Required Template across Organizations

### ISSUE THREAD

**Issue by brianmooreoxy** [MicrosoftDocs/azure-devops-docs#9523]
When it talks about using Required Template to require pipelines to extend from a template when they use a service connection, it does not show how to reference an Azure DevOps git repository which lives in a different organization, or even a different tenant (I need answers for both). It is unclear whether this is possible at all. Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by vtbassmatt** [comment]
It's not possible. I can think of very little in Azure DevOps which _does_ allow crossing org/tenant boundaries, so it would be unusual to explicitly document that it's not possible here.

**Comment by brianmoore180** [comment]
Ok. It seems odd that this will support getting a required template from an entirely different system like GitHub or BitBucket (going outside of the organization and, if necessary, the tenant), but for going to Azure Repos it must be within the the same organization and tenant. It seems reasonable to expect this. By seeing connections to "GitHub" and "BitBucket" I think it defies the "least astonishment" principle that you must stay within your own org for Azure Repos, but that's just my opinion. It would be a good feature request.
