### ISSUE TITLE
Wrong information for Azure Maven Feed authentication

### ISSUE THREAD

**Issue by giespaepen** [MicrosoftDocs/azure-devops-docs#9524]
## Current documentation
In order to automatically authenticate Maven feeds from Azure Artifacts, you must have the mavenFeedAuthenticate argument set to true in your Maven task. See Maven build task for more information.

## Correction
I think it should be `mavenAuthenticateFeed`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03a84e2-22c7-6899-5ac1-c1ed79c05ba6
* Version Independent ID: 405e0a0e-b12b-3fd3-7135-5deb022cd9c3
* Content: [Use Maven artifact feeds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/maven?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/maven.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@giespaepen Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
