### ISSUE TITLE
Add examples of date range queries

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [MicrosoftDocs/azure-devops-docs#9526]
I found this very helpful but I would like to scope my queries by a date range.
I have not yet discovered an example for this kind of query and think it would be helpful.

* from a date
* between a date range
* last n days

This would be especially helpful in queries looking for pipeline runs in the last 10 days for example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a432cd5-b2aa-b274-a17f-80c13a45e2ae
* Version Independent ID: 71a68a40-31ae-e09c-fa89-b68a4428e4bb
* Content: [Query work tracking data using OData - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/wit-analytics?view=azure-devops)
* Content Source: [docs/report/extend-analytics/wit-analytics.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/wit-analytics.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Miles-Davies-HORIBA - Thank you for this feedback and apologies for the delayed response. I'm updating the article to provide some examples for filtering an OData query using dates.
