### ISSUE TITLE
Provide example of date range query

### ISSUE THREAD

**Issue by Miles-Davies-HORIBA** [MicrosoftDocs/azure-devops-docs#9527]
This is very helpful but the only examples of queries by date range were for dates from other tables such as iterations.
It would be helpful for an example of how to query a date range using absolute dates or last n days.
I am having trouble with the "Dates" type fields such as 

``` xml
<NavigationPropertyBinding Path="ChangedOn" Target="Dates"/>
```

Where I would like to query all pipeline runs for a project that queued after 2020-10-01

```
https://analytics.dev.azure.com/{organisation}/{project}/_odata/v3.0-preview/PipelineRuns?
    orderby=QueuedOn desc&
    $filter=QueuedOn ge 20201001&
    $select=*
```
but get error

> VS403483: The query specified in the URI is not valid: A binary operator with incompatible types was detected. Found operand types 'Microsoft.VisualStudio.Services.Analytics.Model.CalendarDate' and 'Edm.Int32' for operator kind 'GreaterThanOrEqual'

I tried using an example for work items
```
https://analytics.dev.azure.com/{organization}/{project}/_odata/v3.0-preview/PipelineRuns?
orderby=QueuedOn desc&
$filter=QueuedOn ge 2020-10-01T00:00:00-00:00&
$select=*
```

but get the error
> VS403483: The query specified in the URI is not valid: A binary operator with incompatible types was detected. Found operand types 'Microsoft.VisualStudio.Services.Analytics.Model.CalendarDate' and 'Edm.DateTimeOffset' for operator kind 'GreaterThanOrEqual'..

It was only when I reviewed the model I noticed the solution

```
https://analytics.dev.azure.com/{organization}/{project}/_odata/v3.0-preview/PipelineRuns?
orderby=QueuedOn desc&
$filter=QueuedDateSK ge 20201001&
$select=*
```

An example may help others find their way faster?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44bc2357-48c9-e331-0d1c-ea07ea294c7b
* Version Independent ID: 989fb7bf-3078-6e27-3c7c-25b776611df3
* Content: [Analytics basic queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/analytics-recipes?view=azure-devops)
* Content Source: [docs/report/extend-analytics/analytics-recipes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/analytics-recipes.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Miles-Davies-HORIBA - Thank you for this feedback and solution. Sorry for the delayed response. I've added an item to my backlog and look forward to updating this article within the next few weeks.
