### ISSUE TITLE
Older TFS instructions

### ISSUE THREAD

**Issue by apfinger** [MicrosoftDocs/azure-devops-docs#9532]
The page says these instructions are valid for TFS 2018-2013, but the instructions do not seem to reflect the state of those versions of TFS, at least up through 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a614791-0c5d-4373-3194-11695e40e1d1
* Version Independent ID: 737e5a3b-d7be-9d36-7b5a-638976406d74
* Content: [Delete, remove project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/delete-project?view=azure-devops&tabs=browser)
* Content Source: [docs/organizations/projects/delete-project.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/projects/delete-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @apfinger, Thanks for your feedback. This article rightly applies to TFS 2013 and on, however the UI for deleting a team project changed from 2013 to 2017, which is difficult to recreate. See the [release notes for September 03, 2013](https://docs.microsoft.com/en-us/azure/devops/release-notes/2013/sep-09-team-services). Please let me know if you have any questions about this. I'm closing this issue now, but you can @mention me if needed. Thanks again and have a great day!
