### ISSUE TITLE
Create Failure Test section inside "Add a build or release task" has incorrect typescript for warnings line

### ISSUE THREAD

**Issue by GreatBarrier86** [MicrosoftDocs/azure-devops-docs#9533]
Within the **Create failure test** section, the code below causes the second test to fail when it indicates "Both tests should pass"

this line: `assert.equal(tr.warningIssues, 0, "should have no warnings");`
should be: `assert.equal(tr.warningIssues.length, 0, "should have no warnings");`

In addition, even though the vss-web-extension-sdk package is required, there is no indication on that page that it should be installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a build or release task in an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thank you for your feedback, @GreatBarrier86, and for including the fix! I've created a work item to address this. Once the PR is merged, this issue will automatically be closed. If you're interested, please consider [becoming a contributor to our docs](https://docs.microsoft.com/en-us/contribute/)!
