### ISSUE TITLE
"Commit mention work item resolution" option does not longer exists in current version

### ISSUE THREAD

**Issue by diegoflores** [MicrosoftDocs/azure-devops-docs#9539]
"Commit mention work item resolution" option does not longer exists in current version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d98917-0ca1-1a1e-1163-bac0af6adc71
* Version Independent ID: ea047ee3-299a-f7b2-b009-5fcc4224dece
* Content: [Close work items using commit messages - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops)
* Content Source: [docs/repos/git/resolution-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/resolution-mentions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by oyvindbra** [comment]
I can confirm this. At least it doesn't work in the current version

**Comment by vtbassmatt** [comment]
Please file a [product bug](https://developercommunity.visualstudio.com/spaces/21/index.html) on this.
