### ISSUE TITLE
Email a DL or Team

### ISSUE THREAD

**Issue by gperrego** [MicrosoftDocs/azure-devops-docs#9541]
When emailing a work item there only seems to be a search users option.  When doing so even if you have a group created you can not search for groups.  Is there a way to email a team, group or a DL instead of having to pick out a bunch of individual users?  I'm asking for a friend who still uses TFS 2017 U3 :)

Thanks, 
Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b4a9a4d-3517-28c2-d8b9-7b1d025b17af
* Version Independent ID: 1b55ace1-77fd-7980-b2bf-ac97c03a112a
* Content: [Email or print user stories, and other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/email-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/work-items/email-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/email-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gperrego - Thank you for your inquiry. The feature you mention has recently been added as a suggestion here: https://developercommunity.visualstudio.com/idea/1140181/allow-sending-devops-work-item-links-to-all-projec.html. Support for this feature hasn't been added to the cloud service. I suggest you up vote it to have it considered for implementing.

**Comment by gperrego** [comment]
Thank you
