### ISSUE TITLE
Misleading command for generating auth header

### ISSUE THREAD

**Issue by fbjorn** [MicrosoftDocs/azure-devops-docs#9544]
Hi,

Documentation says:
`B64_PAT=$(echo ":$MY_PAT" | base64)`
But what you really need to do is:
`B64_PAT=$(echo -n ":$MY_PAT" | base64)`
I was struggling with it for an hour: if you don't `echo` with `-n` option, then new line character will be added, so it will result in a wrong auth header, and you'll be getting 401 errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@fbjorn Thank you for the feedback.

This issue has been previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9262 and is currently under review.  Please refer there for further updates.
