### ISSUE TITLE
Incorrect link?

### ISSUE THREAD

**Issue by AndrewJNorris** [MicrosoftDocs/azure-devops-docs#9545]
[Enter feedback here]
Under the section for Office Integrations the link for Project Professional points to a non-Microsoft product and not to any information on Project Professional.
https://www.projectmanager.com/pm/microsoft-project-cs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@AndrewJNorris Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
