### ISSUE TITLE
Cross project sharing feature is available for all accounts

### ISSUE THREAD

**Issue by onlyutkarsh** [MicrosoftDocs/azure-devops-docs#9546]
[Enter feedback here]
Not a feedback, but a question I guess. I see that sharing of service connection is available on most accounts I use. However I see a quote in the docs that user still need to contact MS if they need access to the feature. I feel this warning should be removed from the docs as it causes confusion.

![image](https://user-images.githubusercontent.com/2685029/97179162-67d9f980-1790-11eb-8059-bbf8a10565ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@onlyutkarsh  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by onlyutkarsh** [comment]
Thank you @msebolt! Will definitely look to contribute. I have contributed [previously](https://github.com/MicrosoftDocs/azure-docs/pull/55677), but since I wasn't sure if the feature is rolled out to all orgs, I decided to raise it as an issue.
