### ISSUE TITLE
Undocumented Service IPs

### ISSUE THREAD

**Issue by Huntwerker** [MicrosoftDocs/azure-devops-docs#9549]
I was trying to do a DryRun for my company Azure DevOps.
Im using the AzureSQL Way, because our collection is too big for a dacpac.

I needed to start this Migration, because there were following IPs undocumented:
40.74.28.10
40.74.28.6
40.74.28.16
40.74.28.24
40.74.28.2
40.74.28.15
40.74.28.7
40.74.28.5

I have no idea what these IPs are for.
I allowed all documented IPs for Western Europe
Im using Data migration tool for Azure DevOps version 17.153.29605.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#ips)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Huntwerker** [comment]
i have rerun an import on October 27th, and encountered new IPs, that were necessary to start the import:

- 40.74.28.17
- 20.67.123.240

**Comment by justhchung** [comment]
40.74.28.0 is documented in Azure DevOps data import https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?view=azure-devops#azure-devops-services-ips under Regional Identity Service - West Europe. You need to allow the entire range for 40.74.28.0/24. We will look into 20.67.123.240 is required for data import but not documented.

**Comment by justhchung** [comment]
20.67.123.240 was missing in the doc. We will update the doc accordingly.

**Comment by Huntwerker** [comment]
@justhchung 
yes - i agree - 40.74.28.0 is documented
But - i haven't said that this IP was missing in the docs.

i suspected something like that, that there is a range of IPs, but this isnt clear in this documentation.
and, the dry runs i did before, those IPs weren't necessary.
can you please adjust this range-information too?

**Comment by KathrynEE** [comment]
@Huntwerker - We've updated the article to reflect the range of IPs to be added and missing IPs. Closing this issue for now. If you find other doc issues, please feel free to reopen this issue.
