### ISSUE TITLE
Wrong word used?

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/azure-devops-docs#9553]
Seems like a typo with "organization":

_If external teams are consuming your package, ensure that your @release view and @prerelease view are visible across the organization and/or organization_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d577f56d-c16e-dde5-68c3-81ee879c7c4d
* Version Independent ID: 0592e0da-1667-9ec7-60a8-d813477cba30
* Content: [Using packages in Azure DevOps best practices - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=azure-devops)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/concepts/best-practices.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@GaTechThomas Thank you for your feedback. We'll get it fixed ✔
