### ISSUE TITLE
This page doesn't explain at all how to set up a pipeline build using gradle and consume maven artifacts

### ISSUE THREAD

**Issue by tobiasmarciszko** [MicrosoftDocs/azure-devops-docs#9554]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9249328c-c42b-7989-45b5-db2d2fe3be6e
* Version Independent ID: 042f1963-263c-df61-be17-8706d8ce1f34
* Content: [Install a Maven artifact using Gradle - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/gradle/pull-package-gradle?view=azure-devops)
* Content Source: [docs/artifacts/gradle/pull-package-gradle.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/gradle/pull-package-gradle.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by tobiasmarciszko** [comment]
How to manage credentials and authentication from a pipeline build using gradle? 
The pictures in the guides uses an old obsolete version of DevOps.

**Comment by ramiMSFT** [comment]
This article has been updated a few times since this issue was posted. I'm closing this for now. Feel free to leave a comment if you're still facing issues.
