### ISSUE TITLE
Didnt solve my doubt

### ISSUE THREAD

**Issue by sgcollazos** [MicrosoftDocs/azure-devops-docs#9555]
[Enter feedback here]

What an useless help page..... Shame on you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3745d89-ac9e-5365-25b7-4788a3374ae5
* Version Independent ID: 6691cf6d-547b-a12d-f5d7-8ee9c3ff38e0
* Content: [Add and manage issues or impediments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-issues-impediments?view=azure-devops)
* Content Source: [docs/boards/backlogs/manage-issues-impediments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/manage-issues-impediments.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sgcollazos - Closing this issue as there is no actionable information. If more information can be provided to help improve this article, please reopen the issue.
