### ISSUE TITLE
List of IPs need updating

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#9558]
Migrator.exe import fails with:

```
+ [Error] VS403366: A problem occurred while attempting to connect to your datab
ase. Please verify that your connection string is correct and that all required
IP addresses for Azure DevOps Services have been provided exceptions for your ma
chine's firewall.
List of Azure DevOps Services IPs:
40.67.219.89
40.74.28.2
```

The latter IP (40.74.28.2) is not listed here. :(

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Import migrate process from on-premises to Azure DevOps - Azure DevOps](https://docs.microsoft.com/de-de/azure/devops/migrate/migration-import?view=azure-devops#import-large-collections)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by NenoLoje** [comment]
Another one would be 40.74.28.16

**Comment by KathrynEE** [comment]
@NenoLoje - Thanks Neno. I'll work with the PM to get this updated.

**Comment by Huntwerker** [comment]
i got a full list of 10 IPs in #9549

**Comment by KathrynEE** [comment]
@NenoLoje, @Huntwerker - The article has been updated to reflect the range of IP addresses needed. Thank you for the feedback.
