### ISSUE TITLE
Link pipelines cross project

### ISSUE THREAD

**Issue by sudo-md** [MicrosoftDocs/azure-devops-docs#9559]
Hi,

In our Azure DevOps environment, we use projects in a different manner than described here. We use projects specifically for sprints, and other projects specifically for sourcecode and (release) pipelines. Could you describe how to link work items from one project to the other, where the deployment is taking place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sudo-md - Thank you for your inquiry. I checked with the PM and he indicated that as long as you link your work items to your source changes - commits or pull requests - the links to the deployment should be made.  Cross-project linking is supported for Azure DevOps Services (cloud platform) at this time.
