### ISSUE TITLE
"How much do parallel jobs cost?" does not show any pricing.

### ISSUE THREAD

**Issue by ZacBleningerTR** [MicrosoftDocs/azure-devops-docs#9562]
In the section "How much do parallel jobs cost?" there is no reference to pricing for Azure DevOps parallel jobs.  I have found the pricing as $40 per parallel job in the Azure pricing calculator but it seems misleading in this section to not include some sort of pricing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a488b-88f6-dff6-e2ee-402167e17ad4
* Version Independent ID: 9a4dedda-e82c-2833-f28c-5ab346fb1b38
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ZacBleningerTR Thank you for the feedback, assigning this to the author for further review.

@steved0x Please note a fix to the author's alias, also both seem to be mismatched.

**Comment by juliakm** [comment]
Adding a more helpful link to the docs. We don't have the exact pricing in the docs but you can get to a spot to purchase more jobs (and see the cost for your organization) in organization settings.

**Comment by bobleujr** [comment]
I can't find this info anywhere. It would be great to have access to it.
