### ISSUE TITLE
Wildcards are not support for path filters, but the documentation says otherwise

### ISSUE THREAD

**Issue by Mgamerz** [MicrosoftDocs/azure-devops-docs#9564]
As noted over 2 years ago in this thread https://github.com/MicrosoftDocs/azure-devops-docs/issues/397, Path wildcards are not supported, and still aren't. But the documentation seemingly for 2 years has suggested this is a feature, but it doesn't work (I just wasted several hours trying to figure out why it didn't work).

Here's the documentation as it appears right now:
![image](https://user-images.githubusercontent.com/2738836/97463910-e310ec00-1905-11eb-9d0a-acac21277609.png)

There are multiple places that show this doesn't work:

https://developercommunity.visualstudio.com/idea/383490/support-wildcards-in-trigger-path-filters.html
https://stackoverflow.com/questions/63800001/does-azure-yaml-pipelne-support-wildcards-in-path-filter-in-trigger

This example of wildcards in path filters should be removed as it is simply wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Updated the docs to state so. This is not a judgment on whether we will take this up as future work in the product.

**Comment by sergiopaim** [comment]
Hello! Isn't it just a RegEx filter to change in the Azure DevOps job starter so as to make this happen? 
Why is this taking so long to get improved? Thus this really need a user voice voting to get fixed? It's not a new feature, it's a bug...

**Comment by Slooz** [comment]
The documentation was updated to say:

> - Wild cards are not supported with path filters.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?tabs=yaml#paths

However, this is also incorrect and causes more confusion. Wildcards are supported in path filters when included as the final character:

> - For paths:
>   - You may include `*` as the final character, but it doesn't do anything differently from specifying the directory name by itself.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?tabs=yaml#wildcards

See the following issues:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/10212
https://github.com/microsoft/azure-pipelines-vscode/issues/372

Prior to this issue, the documentation and the Azure Pipelines VS Code extension standardized adding `*` as the final character for directories.

**Comment by PavloAndriiesh** [comment]
Wildcard support and documentation update will be rolled out over the next two to three weeks according to the latest [release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters).
