### ISSUE TITLE
Seeing Markup Above Images

### ISSUE THREAD

**Issue by collinkruger** [MicrosoftDocs/azure-devops-docs#9565]
Hi Docs Teams 👋

I am seeing some markup above images on this page.

![image](https://user-images.githubusercontent.com/23742214/97466603-4c4a2c80-1911-11eb-8b78-f8953f69b293.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops#add-approvals)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@collinkruger Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribut).

The documentation has been updated and is pending review.
