### ISSUE TITLE
Link to SonarQube/SonarCloud as SAST tool

### ISSUE THREAD

**Issue by ChristopheHvd** [MicrosoftDocs/azure-devops-docs#9566]
Hi,
The CI tool section and the Reference Information section are listing several SAST tools (Checkmarx, Whitesource). I feel like SonarQube (and its cloud equivalent SonarCloud) could be added to those sections, as it is a well-know widely used SAST tool. Could someone add a link?
Thanks.
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03ce2683-1bb4-671a-630b-2c909184e93d
* Version Independent ID: 5e57efbe-f0c3-6e0f-8591-b60bb04a964c
* Content: [Add Continuous Security Validation to your CICD Pipeline - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/security-validation-cicd-pipeline?view=azure-devops#ci-continuous-integration)
* Content Source: [docs/migrate/security-validation-cicd-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/security-validation-cicd-pipeline.md)
* Product: **devops**
* Technology: **devops-migrate**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@steved0x - I'm reassigning this to you and updating the metadata accordingly. Let me know if it should be otherwise.
