### ISSUE TITLE
'Versions that got promoted to views are exempt from retention policies and will be deleted.' should be 'not deleted'

### ISSUE THREAD

**Issue by sommmen** [MicrosoftDocs/azure-devops-docs#9567]
> If you'd like to retain a package indefinitely, you can promote it to a view. Versions that got promoted to views are exempt from retention policies and will be deleted.

The above text in the mentioned article below seems a bit wrong. The first sentence is all about keeping a package indefinitely and the second part talks about the package being deleted - which one is it now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven#automatically-delete-old-package-versions-with-retention-policies)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@sommmen Thank you for your feedback. Versions that got promoted to views are exempt from retention policies and will **Not** be deleted. We'll get it fixed.
