### ISSUE TITLE
how to Download a specific artifact

### ISSUE THREAD

**Issue by testcase-Azure** [MicrosoftDocs/azure-devops-docs#9569]
how to Download a specific artifact
link: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops#artifact-download

**Comment by shashban** [comment]
@testcase-Azure Could you clarify the question further? As mentioned in the doc, you can choose which specific artifacts should be downloaded on the agent when the job executes in the UI.
