### ISSUE TITLE
How to Inject pipeline variable into bash environment?

### ISSUE THREAD

**Issue by ismailhkose** [MicrosoftDocs/azure-devops-docs#9572]
Hello,
I can't see a complete example of how to use a pipeline variable within a bash script. There is some piece of examples but insufficient for beginners.

I defined a variable in a pipeline, and I am trying to use it in a script that is run by yaml. The variable is always empty when it's printed within a bash script.

In Pipeline variables:
VARIABLE_NAME: 1234

**In yaml**
```
restore:
     commands:
     - !!defaultcommand
       name: 'Restore SDK'
       command: '.pipelines/restore.sh'
```

In **.pipelines/restore.sh**:
```echo "VARIABLE_NAME: $VARIABLE_NAME"```

VARIABLE_NAME is always empty. How can I make this work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **juliakm**

**Comment by lindt** [comment]
you can access it by

```
echo "VARIABLE_NAME: $(VARIABLE_NAME)"
```
