### ISSUE TITLE
Pass Arguments to Inline Azure Powershell Script

### ISSUE THREAD

**Issue by brianmooreoxy** [MicrosoftDocs/azure-devops-docs#9578]
In the Azure PowerShell documentation, it says:

For the "Inline Script" type, it says "You can also pass predefined and custom variables to this script using arguments". This makes it sound like I can use the "ScriptArguments" to pass arguments to an inline script.

For example, my inline script would be:
param($Param1, $Param2, $Param3)
Write-Host "$param1";

Then my scriptArguments value would be -Param1 blah -Param2 foo -Param3 bar

But when I do this, it complains that "param" is not recognized as a command. After doing some investigation, it seems like Azure PowerShell injects stuff at the top of my inline script, so param() no longer works. Also the $args array seems to be empty instead of containing my script arguments. So it seems like the documentation is misleading. Or is there another way I can pass arguments to an inline script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by MarkIannucci** [comment]
@brianmooreoxy , thanks for reporting.  I just wasted quite a bit of time because of this.  I suspect you worked around the $Args being empty by using a script file in your repo?  That is what I will attempt next.

**Comment by steved0x** [comment]
Arguments are used for FilePath script type. This is fixed in our new task reference:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines&viewFallbackFrom=azure-devops
