### ISSUE TITLE
Broken link to the template

### ISSUE THREAD

**Issue by onlyutkarsh** [MicrosoftDocs/azure-devops-docs#9580]
Link to the template (https://azuremarketplace.microsoft.com/marketplace/apps/azul.azul-zulu13-ubuntu-2004) is broken. The screenshot below highlighting the hyperlink to broken link.

![image](https://user-images.githubusercontent.com/2685029/97754684-d9e37300-1aef-11eb-96f1-3fa26b1777cb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf8bb33-e4cf-3dc5-5510-1111b8f1bdbf
* Version Independent ID: 3148d97d-2ff1-30f5-0487-dbfe93888a3f
* Content: [Deploy nginx to a Linux VM - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-linuxvm-deploygroups?view=azure-devops&tabs=java)
* Content Source: [docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/deploy-linuxvm-deploygroups.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@onlyutkarsh Thank you for the feedback.

Unfortunately the link https://azuremarketplace.microsoft.com/marketplace/apps/azul.azul-zulu13-ubuntu-2004 is locale specific and you will need to adjust your browser settings accordingly to properly download.

If there are any additional issues, please comment below.
