### ISSUE TITLE
Argument names vs parameter names

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/azure-devops-docs#9581]
For some of the arguments, then it is difficult to exactly see which arguments match which input parameter.
Example: Argument "Packer Template" = templateType, "Packer Template Location" = customTemplateLocation. Could you please add the actual parameter name in a column next to the argument name? That would make it much easier to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f7a83-5e63-e305-4cc1-d443db82893e
* Version Independent ID: 35b19b29-3f7b-19a3-5bb5-a3af2bbfe4d8
* Content: [Build Machine Image task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/packer-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
We have included this information in our new task reference, both in the YAML syntax block, and also down in the Inputs table. Please check it out and let us know what you think.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/packer-build-v1?view=azure-pipelines&viewFallbackFrom=azure-devops
