### ISSUE TITLE
Parallel Jobs content is confusing

### ISSUE THREAD

**Issue by gkarthiks** [MicrosoftDocs/azure-devops-docs#9589]
The content under Parallel Jobs is confusing with the below statements. Please look at the bold'ed wordings. It's kind of confusing. I guess the second statement just makes sense, isn't it?

### Parallel jobs
You can **use a parallel job** in Azure Pipelines **to run a single job at a time** in your organization. In Azure Pipelines, you can run parallel jobs on Microsoft-hosted infrastructure or on your own (self-hosted) infrastructure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Parallel jobs is a confusing topic, and I am making an update to this doc to try and clarify. Thank you for your feedback.

===
**Parallel jobs** represents the number of jobs you can run at the same time in your organization. If your organization has a single parallel job, you can run a single job at a time in your organization, with any additional concurrent jobs being queued until the first job completes. To run two jobs at the same time, you need two parallel jobs. In Azure Pipelines, you can run parallel jobs on Microsoft-hosted infrastructure or on your own (self-hosted) infrastructure.
