### ISSUE TITLE
Can work item attachments make DevOps database slow?

### ISSUE THREAD

**Issue by FrancescoSclano** [MicrosoftDocs/azure-devops-docs#9591]
Reffering to https://docs.microsoft.com/en-us/azure/devops/reference/xml/change-maximum-attachment-size-work-items?view=azure-devops-2019&source=docs#alternative-solutions-to-increasing-the-attachment-size 

I currently have more than 10000 work items in a Team Project. Users attach files directly to work items instead of using git repository, so there are about 2000 work items with attached files and this number could be quickly grow up. Furthermore I already increased the maximum attachment size to 200 MBs. Do I have to discourage this practice? In my case the problem is that we have many users with Stakeholder access that non have access to repository git. 

Increasing attacment size could be make DevOps very slow? If yes, could you please add some more explicit warning in above link? Any tips will be greatly appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96caf4e-05c3-53e5-c1f6-3b24a95dac70
* Version Independent ID: 190fa3f7-dbba-315a-56bc-dc9f15355188
* Content: [Change the maximum attachment size for work items - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/change-maximum-attachment-size-work-items?view=azure-devops-2019&source=docs#alternative-solutions-to-increasing-the-attachment-size)
* Content Source: [docs/reference/xml/change-maximum-attachment-size-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/change-maximum-attachment-size-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@FrancescoSclano - Thank you for your inquiry. No there should not be any limits at the project or org level for attachments. The limits are on the attachment size. The only performance impact is that the more attachments made to a single work item can cause saves of that work item to take longer.
