### ISSUE TITLE
Can credits from Azure Sponsorship Offer be used to pay for Azure DevOps services?

### ISSUE THREAD

**Issue by Benjiiim** [MicrosoftDocs/azure-devops-docs#9592]
It might be interesting to add a FAQ item regarding the ability (or not) to use credits from an Azure Sponsorship Offer (such as 0036p - https://azure.microsoft.com/en-us/offers/ms-azr-0036p/) to buy Azure DevOps services.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Frequent questions about billing management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#other-questions)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Benjiiim, Thanks for reaching out and I apologize for the delayed response. I've followed up with our billing PM and they aren't familiar with the Azure Sponsorship Offer, nor any relation of it to Azure DevOps. You can try to add the subscription with the Azure Sponsorship Offer and see if the system accepts it. If the subscription has a limit, then most likely you won't be able to use it. I've created a user story on my backlog to add this to an FAQ. I'm closing this issue, however please @mention me if you have any further questions. Thanks so much!
