### ISSUE TITLE
Azure artifacts billing limit usage

### ISSUE THREAD

**Issue by MichaelKueh** [MicrosoftDocs/azure-devops-docs#9597]
Following this description there should be different maximum limits, but there is only <= 2GB and without limit. How can I define a maximum?

![image](https://user-images.githubusercontent.com/673302/97985265-59b35b00-1dd8-11eb-9777-ecabc9d3c973.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Start Using Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by ramiMSFT** [comment]
@MichaelKueh Thank you for reaching out. There is no usage limit after using your free 2 GiB . Azure Artifacts is billed on a consumption basis. Check out the storage breakdown [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/artifact-storage?view=azure-devops)
