### ISSUE TITLE
How to reference the YAML file in the submodule?

### ISSUE THREAD

**Issue by lipalath-ms** [MicrosoftDocs/azure-devops-docs#9600]
I created a git repo in Azure devops and added the github project as a git submodule

I have a YAML file within submodule. But while creating the build, it doesn't see the YAML file as it is in the submodule.
I'm assuming I need to create a YAML file in the main repo that references the one in the submodule. I created a YAML file in the main repo with the following step:

- checkout: self
  submodules: true

What step should I add in the YAML file in the main repo to reference the YAML file in the submodule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5c0726-1492-650f-3ebb-08407acb21f9
* Version Independent ID: 53e88c46-86d7-74af-3b82-b630c3c9d689
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vijayma** [comment]
When you use submodules, the common pattern is to have an independent pipeline for the submodule. Anytime you update the code in the submodule, the submodule's pipeline will run and make sure that it is good to be consumed. Your main repo and pipeline will simply consume the submodule and build the main code.

If your question is related to how you can build the submodule as part of building the main code, then you can use templates. Add a template file (another YAML) to your submodule, and then use that template in the main pipeline. For documentation on templates, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#insert-a-template. For information, on how to reference a template from another repository, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories.
