### ISSUE TITLE
Hide Field Rule is not working

### ISSUE THREAD

**Issue by tushmesh** [MicrosoftDocs/azure-devops-docs#9601]
[When I am trying to apply a Rule to Hide a field, as soon as by selecting the condition "current user is a member of a group..." page goes blank]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@tushmesh  -  I'm sorry you're encountering difficulties. If you are continuing to have this issue, I recommend you report it on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). I'm closing this issue as it isn't a document issue.
