### ISSUE TITLE
Not much visual help

### ISSUE THREAD

**Issue by itgulle** [MicrosoftDocs/azure-devops-docs#9604]
its 21st century, be more realistic and and put some visuals to make it more understandable, ppl already have major learning curve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f80d77-da2a-3c8d-efcf-3095bf293f69
* Version Independent ID: 36dcf393-e28a-2bc4-61e6-5c93cdacb625
* Content: [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/dot-net?view=azure-devops&tabs=vsts)
* Content Source: [docs/pipelines/apps/windows/dot-net.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/windows/dot-net.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@itgulle Thank you for the feedback.

This issue has been previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/4712 and is currently under review.  Please refer there for further updates.
