### ISSUE TITLE
Jmeter page gives incorrect instructions for Azure DevOps Server 2019

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/azure-devops-docs#9605]
When Azure Devops Server 2019 is selected in the version dropdown, the instructions still talk about Creating an Azure DevOps subscription, and Azure Test Plans,, but I don't think those things are a part of Azure DevOps Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f40446-f1cc-5b5a-35f2-8115f4204f6e
* Version Independent ID: a321bcf7-0924-3d3b-385b-33e5aa6b5125
* Content: [Run Apache JMeter load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-jmeter-test?view=azure-devops-2019#help-and-support)
* Content Source: [docs/test/load-test/get-started-jmeter-test.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/get-started-jmeter-test.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by KathrynEE** [comment]
Closing this issue as Load testing has been deprecated.

**Comment by pabrams** [comment]
Um, that was sort of my point, Kathryn.  Besides, what does it matter if it's deprecated? If you still have published content for "deprecated" functionality, you should still fix it when it's wrong, unless the product is past end-of-life (in which case, you should probably unpublish it), shouldn't you?

**Comment by KathrynEE** [comment]
@pabrams  -  I may be missing something here and my initial response was very minimal. When you go to the Archived content page, which is the only page now available for the deprecated load testing content, you can't select Azure DevOps Server 2019. So, the issue you raised is resolved through the archiving of the content.  Let me know if there is something I'm missing.
