### ISSUE TITLE
Solution Backlog should be a Parent of Program Backlog

### ISSUE THREAD

**Issue by brett3210** [MicrosoftDocs/azure-devops-docs#9610]
The page states: 
"For SAFe, you may want to add a Solution Backlog that appears as a parent to the Epic backlog."
https://docs.microsoft.com/en-us/azure/devops/boards/plans/safe-customize?view=azure-devops

However, under SAFe the Solution (Capabilities) Backlog should be a parent of the Program (Features) Backlog.  See:
https://www.scaledagileframework.com/

Unfortunately this SAFe configuration doesn't appear to be achievable via the Microsoft Azure DevOps "Backlog Levels" screen without disabling the inherited "Epic" work item type, and recreating it as a custom work item type, which is not ideal.  See:
https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-backlogs-boards?view=azure-devops

Any other suggestions?

I suggest the documentation is updated to reflect this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0479f615-08ef-f48c-de03-170bae58e7db
* Version Independent ID: e35eef4d-3340-9b21-8324-59dc6983035d
* Content: [Customize Azure Boards to support SAFe® - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/safe-customize?view=azure-devops)
* Content Source: [docs/boards/plans/safe-customize.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/safe-customize.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@brett3210  - Thank you for this feedback and solution. I've added an item to my backlog and look forward to updating this article within the next few weeks.

**Comment by brett3210** [comment]
@KathrynEE - The article doesn't appear to have been updated yet.  Also, do you have any more practical solutions that the workaround I provided?
