### ISSUE TITLE
Link is wrong in task page in pipeline documentation

### ISSUE THREAD

**Issue by singlaive** [MicrosoftDocs/azure-devops-docs#9613]
[Enter feedback here]
In this sentence, quoted as "By default, all tasks run in the same context, whether that's on the host or in a job container", the link of "host" actually leads to the page for job rather than host.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
That link is intentional. By default, jobs run directly on the agent host. I couldn't think of another way to word the sentence such that it both made sense in context _and_ had a phrase I could use as a link to the Jobs topic.
