### ISSUE TITLE
Azure Artifacts retention policy - when is it applied?

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/azure-devops-docs#9615]
Hello,
I have setup the retention policy of our Azure artifacts nuget feed but nothing happens.
When is it applied?

Marek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@rolfik Thank you for reaching out. When you enable retention policies, your package(s) will be deleted when both of the following criteria are met:

* The number of published versions of that package reaches the maximum number of versions limit, **AND**
* A version of that package has not been downloaded within the number of days to keep recently downloaded packages.

**Comment by rolfik** [comment]
Well, both conditions were met in our case but packages were not deleted.
Because we have reached the limit and it has blocked our Azure pipelines, we have decided to abandon the Azure Artifacts and instead use shared folder on our company build server which is even much faster.

**Comment by bitbonk** [comment]
I just experienced the same problem. In a test feed I have pushed 20 versions of a package that where never downloaded. _"Maximum number of versions per package"_  is set to 10, but no packages have been deleted so far.
