### ISSUE TITLE
import work items hangs

### ISSUE THREAD

**Issue by bamSC1** [MicrosoftDocs/azure-devops-docs#9617]
![image](https://user-images.githubusercontent.com/74007318/98255698-aec3ae00-1f4b-11eb-8735-b8f7253b03ca.png)

**Comment by KathrynEE** [comment]
@bamSC1 - I'm sorry you're encountering an issue. This appears to be a product issue and not a doc issue. Please post your issue here: [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
