### ISSUE TITLE
Azure DevOps Server 2020/2019 does not support partially downloading artifacts in release pipeline

### ISSUE THREAD

**Issue by ashamrai** [MicrosoftDocs/azure-devops-docs#9618]
According to this section [Artifact download](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2020), we can select artifacts to download. However, Azure DevOps Server 2019 and 2020 do not support that:

1. [Azure DevOps Server 2019 where is Partially downloading artifacts in release pipeline?](https://developercommunity.visualstudio.com/content/problem/520932/azure-devops-server-2019-where-is-partially-downlo.html)

1. [Azure DevOps 2020 - how do I select which artifacts to download for a release pipline (18.170.30525.1 (Azure DevOps Server 2020))](https://stackoverflow.com/questions/64695403/azure-devops-2020-how-do-i-select-which-artifacts-to-download-for-a-release-pi)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac87575-019b-370a-6bbe-9b623241a2f5
* Version Independent ID: 8ff5e112-4949-c406-0b00-4fdfd82afe5f
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2020)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by ramiMSFT** [comment]
Thanks for your feedback! I'm updating the article shortly
