### ISSUE TITLE
Programmatically Download Weekly JSON File of Azure IP Address Ranges

### ISSUE THREAD

**Issue by chrisgrulke** [MicrosoftDocs/azure-devops-docs#9623]
In the documentation there is a link to the JSON file of IP address ranges that Microsoft publishes weekly.  When following the link to the page, I can download the file by clicking the download button, but I would like to be able to retrieve this file programmatically, so I can automate updating my IP Allow Lists.  Is there an API call or something that I can use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#agent-ip-ranges)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by arrrghhh** [comment]
Hello,

This is what I ended up doing in Powershell:
```
$SiteAddress = "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
$HttpContent = Invoke-WebRequest -URI $SiteAddress
$JsonLink = $HttpContent.Links | Where-Object href -like '*json'
```
$JsonLink.href should hold the JSON link.  Not pretty, but it does work.  Hopefully MS provides a better way to do this (ideally via ServiceTags!)

**Comment by chrisgrulke** [comment]
Thanks!  This code snippet helped me a lot!  I was able to translate your Powershell into the following Python code as well:

``` python
  result = []
  response = requests.get("https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519")
  soup = BeautifulSoup(response.text, 'html.parser')
  for link in soup.findAll('a'):
    if ".json" in link.get('href'):
      result.append(link.get('href'))
```

**Comment by mijacobs** [comment]
Looks like this has been resolved. If you'd like to add your example to the docs, we accept public contributions--feel free to open a PR! We have a team of folks standing by to review and accept your updates.

**Comment by arrrghhh** [comment]
@mijacobs - this isn't really resolved, just a hacky workaround deployed.  Why isn't there an API for this, or a direct download link?  Or better yet Service Tags so I can just setup a rule in my NSG?

**Comment by mijacobs** [comment]
This repo is just for documentation issues--if you'd like to suggest an API or other improvement, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by JDAbbeyiii** [comment]
> This repo is just for documentation issues--if you'd like to suggest an API or other improvement, please [submit your idea](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

@arrrghhh This is a standard Microsoft answer for this long existing issue. They have been promising to clean this up for YEARS now, but they never follow through. Just excuses on why that one person can't do anything to help and it's someone else's problem.
