### ISSUE TITLE
missing noun

### ISSUE THREAD

**Issue by JohnCOsborne** [MicrosoftDocs/azure-devops-docs#9624]
"While multiple queues across projects can use the same agent pool, multiple queues within a project cannot use the agent pool." 

I think this should say 

While multiple queues across projects can use the same agent pool, multiple queues within a project cannot use the same agent pool.

I would fork and push but unable to on my work computer
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=tfs-2018&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@JohnCOsborne Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
