### ISSUE TITLE
Update git authentication to GCM Core

### ISSUE THREAD

**Issue by modularity** [MicrosoftDocs/azure-devops-docs#9625]
The docs should be updated to reflect that [Git Credential Manager for Windows is no longer being maintained](https://github.com/microsoft/Git-Credential-Manager-for-Windows/commit/d5e32df78eb82efee1e65effd5df0692caa9ec11#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). The cross-platform [Git Credential Manager Core(GCM Core](https://aka.ms/gcmcore) is the official replacement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Already been fixed.
