### ISSUE TITLE
Incorrect Prerequisite for changing organization region

### ISSUE THREAD

**Issue by edwardSVIP** [MicrosoftDocs/azure-devops-docs#9627]
This doc states that "You must be a **Project Collection Administrator or the organization Owner** to change your organization region."

However, one PCA cannot implement this because Azure DevOps Virtual Support Agent will only find organization where this user is its owner. 

Thus the statement in this doc is incorrect. Please fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change location or region of organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops#change-organization-region)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @edwardSVIP, Thanks for your feedback. I'm following up on this and will be in touch. Have a great weekend!

**Comment by chcomley** [comment]
@edwardSVIP, we've updated the article, which should be live shortly. Thanks again!
