### ISSUE TITLE
Pipeline Trigger Issues

### ISSUE THREAD

**Issue by spowser** [MicrosoftDocs/azure-devops-docs#9631]
In the section **YAML resource trigger issues support and traceability** it states there is a menu item in the pipeline definition page.  Where on the page?  Which pipeline definition, source or destination?  Can we get a screenshot showing the menu item on the page?  I've clicked on just about everything I can think of and not seeing it :(

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#yaml-resource-trigger-issues-support-and-traceability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
To get to the Trigger Issues menu item, go to the pipeline runs page. Then, open the menu with three dots. If your pipeline supports Trigger Issues, you should see that as an option. Here's what it looks like for me. I'll also update the docs. 

![triggermenu](https://user-images.githubusercontent.com/64906/100792511-bbbbac00-33e8-11eb-9518-0221327b9456.png)

**Comment by scp-mb** [comment]
@juliakm What defines a pipeline as supporting trigger issues? That option doesn't show for any of our pipelines, yaml or classic, CI or CD. None of them it seems. You also seem to have export options that aren't present?

Classic CI
![image](https://user-images.githubusercontent.com/52526733/100905850-6eab0900-34c0-11eb-8e9a-9b960a05c63c.png)

YAML CI / CD
![image](https://user-images.githubusercontent.com/52526733/100905937-884c5080-34c0-11eb-84d2-52500e2b3086.png)

**Comment by spowser** [comment]
@scp-mb This was also my next question.  What constitutes a supported pipeline?  I have pipeline resource triggers so I would think this should qualify?

**Comment by scp-mb** [comment]
@Court72 Requesting this be reopened please as the problem is still there. Seemingly nobody can find said page.

**Comment by juliakm** [comment]
@scp-mb  What version of Pipelines are you using?

**Comment by scp-mb** [comment]
We're using the cloud hosted DevOps if that's what you're asking (not self hosting via DevOps Server). As far as I know that doesn't give us a specific "version" of pipelines?

**Comment by spowser** [comment]
It appears we are currently on Sprint 178
![image](https://user-images.githubusercontent.com/3085375/101537580-967eee80-3950-11eb-92f4-86c21ace3f10.png)

**Comment by juliakm** [comment]
@scp-mb and @spowser  The development team is looking into this issue and possible fixes. It is not a documentation issue right now, but more of a functionality one.

**Comment by juliakm** [comment]
I apologize for the delay on this. The trigger Issues feature only works for non-repository resources. 

We will update the documentation.

**Comment by scp-mb** [comment]
@juliakm Is it possible to get the functionality extended to cover repository resources? We've had issues with triggers not firing in the past and it was an absolute nightmare to work out why as it's a complete black box otherwise.

**Comment by juliakm** [comment]
@scp-mb You can reach out to the product team for feature requests by posting in the [Developer Community](https://developercommunity.visualstudio.com/search?space=21). Sorry to hear that your pipeline been so hard to troubleshoot.
