### ISSUE TITLE
Information on runtimeStack is incomplete

### ISSUE THREAD

**Issue by paulbatum** [MicrosoftDocs/azure-devops-docs#9639]
The information for the runtimeStack setting needs to be expanded:

1. If the user is deploying code, then this should be set to the language version they want to run. For example, if they want python 3.7 then they would set "python|3.7". I would suggest linking to functions documentation that lists the valid options here. Unfortunately, I can't find up to date documentation. The closest thing would be the table in [this section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#create-a-function-app-2) however the information there is out of date. I filed https://github.com/MicrosoftDocs/azure-docs/issues/65695 to get that table updated correctly.

2. Since it maps to the linuxFxVersion setting on the siteConfig object for a linux function app, I think this should be mentioned explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by pragnagopa** [comment]
Please reach out if more details are needed to address this issue.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
