### ISSUE TITLE
No way to query what is specifically causing the limits on usage

### ISSUE THREAD

**Issue by jaylvee** [MicrosoftDocs/azure-devops-docs#9643]
It would be great if there was some to either query via Rest calls or display specific info about what is causing high usage.

There is a command column in the _settings/usage? page, with DataProvidersQuery.QueryDataProviders.  This instance is under the Extensions for the Application column.  But there is no way to determine what is exactly causing the issue.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2c2355-60a5-d53f-2c72-8f032c1b8cf2
* Version Independent ID: 711bf22d-99c9-51b2-382c-e095bdb2c37f
* Content: [Resource limits & constraints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
* Content Source: [docs/integrate/concepts/rate-limits.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/rate-limits.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @roferg
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jaylvee - Thank you for the feedback. Since this is a product issue, please file a feature request or issue on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html). Closing this issue as it isn't a doc issue.
