### ISSUE TITLE
parameter reportDirectory is not described

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/azure-devops-docs#9647]
Parameter `reportDirectory` is just mentioned in summary, but not described later in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by iricigor** [comment]
And since reportDirectory is not directly written, but only "included" in docs page, here is the code that is including it

```markdown
## YAML snippet

[!INCLUDE [temp](../includes/yaml/PublishCodeCoverageResultsV1.md)]
```

**Comment by vtbassmatt** [comment]
For whoever picks this one up: the parameter is introduced here: https://github.com/microsoft/azure-pipelines-tasks/blob/38d6beafa3f561f6a230a99336fb18b544aefaf1/Tasks/PublishCodeCoverageResultsV1/task.json#L55

**Comment by msebolt** [comment]
The documentation has been updated and is pending review.
