### ISSUE TITLE
Does Scheduled Trigger have 'paths' keyword like Push Trigger?

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/azure-devops-docs#9649]
Hi,

It seems that the scheduled trigger does not have the `paths` keyword/property. It means that we cannot specify which directory paths we want to watch and evaluate code changes before we run scheduled pipelines. Am I correct?

If so, I suggest implementing the `paths` property for the scheduled trigger. It seems to be useful in the big repositories where we have many projects (especially, monorepos).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
investigating

**Comment by steved0x** [comment]
@nguyenlamlll Unfortunately the scheduled trigger does not support a path property (like the CI trigger) that can be used for filtering. That does sound like a great idea for a feature request. We are closing this issue and directing you to file a feature request through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Thank you for your feedback.
