### ISSUE TITLE
Is the IP ranges in this tutorial document outdated?

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/azure-devops-docs#9650]
In this document ([Build code from on-premises Bitbucket server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/on-premises-bitbucket?view=azure-devops#azure-devops-ip-addresses)), IP address range required to achieve communication between Azure DevOps Pipeline and On-premise Git server is introduced in "Azure DevOps IP addresses" section.
Here, I realized that Azure DevOps Services' IP address has been changed related to the introduction of the Service Tag as in the following blog post.
https://devblogs.microsoft.com/devops/new-ip-address-ranges-with-service-tags-for-azure-devops-services/
Is it safe to consider the IP ranges introduced in the blog is enough to allow Azure Pipeline to access On-premise git server? or are we still required to allow IP ranges in the document too?

Same goes for the following GitHub Enterprise entry as well.
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github-enterprise?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b838600-94fe-8d49-e6ed-8a5d7859a776
* Version Independent ID: 75c9e831-d36e-502b-2095-b602b38ea513
* Content: [Build code from on-premises Bitbucket server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/on-premises-bitbucket?view=azure-devops#azure-devops-ip-addresses)
* Content Source: [docs/pipelines/repos/on-premises-bitbucket.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/on-premises-bitbucket.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by adamdotdev** [comment]
As evidence that it is outdated I will note that our Azure DevOps organization is hosted in the South Central US region, which is not listed in this document at all.

**Comment by vijayma** [comment]
That is correct. We have now updated the docs to point to the correct IP ranges.

**Comment by shunkino** [comment]
Great! Thank you.
