### ISSUE TITLE
Git Credential Manager Deprecated

### ISSUE THREAD

**Issue by jsn-m** [MicrosoftDocs/azure-devops-docs#9652]
> [Install the Git Credential Manager](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops#install-the-git-credential-manager)
>Windows
>
>Download and run the latest Git for Windows installer, which includes the Git Credential Manager for Windows. Make sure to enable the Git Credential Manager installation option.

Git Credential Manager has been [deprecated](https://github.com/Microsoft/Git-Credential-Manager-for-Windows#notice-this-project-is-no-longer-being-maintained-warning). Doc needs to be updated to suggest Git Credential Manager Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops#windows)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@jsn-m  Thank you for the feedback.

This issue has been previously reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9625 and is currently under review.  Please refer there for further updates.
