### ISSUE TITLE
Node Path

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-devops-docs#9654]
Hi Guys,

Would be great to describe where the build is looking for the node if the label '"com.azure.dev.pipelines.agent.handler.node.path"' is not defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Hi @yahorsi. I checked with our developers and that variable is only set when you are trying to run a container which isn’t glibc-based, such as Alpine Linux. For most scenarios, the agent brings along its own copy of Node which is mounted at some well-known location (that can change).
