### ISSUE TITLE
Does Demand specification allow for "-contains" string?

### ISSUE THREAD

**Issue by tknerr** [MicrosoftDocs/azure-devops-docs#9655]
I was wondering if it is possible to substring-match a capability within a demand.

The current version of the docs suggests that this could potentially be possible, it's still not pretty clear though:

* the comment says "# check for specific string in capability" (sounds like substring match)
* the code says "agent.os -equals Darwin" (sounds like full string equality match)

![image](https://user-images.githubusercontent.com/365744/98828005-d1683200-2437-11eb-8ff5-f93a062e9800.png)

Are there any other supported operators in addition to `-equals` when specifying a demand, e.g. such as `-contains`, `-gt`, etc? 

I was hoping for a subset of [PowerShell Operators](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators) or similar (mostly logical and comparison operators), but found nothing indicative of that in the docs...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
The docs should be clarified to indicate whether they support "-contains." While we investigate,  here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
Investigating

**Comment by vtbassmatt** [comment]
(We only support "-equals" and existence, not "-contains")
