### ISSUE TITLE
The instructions did not work for me exactly

### ISSUE THREAD

**Issue by Anitalex** [MicrosoftDocs/azure-devops-docs#9657]
This area of the instructions did not exist for me.....
-To configure anonymous access to badges:
-Navigate to Project Settings
-Open the Settings tab under Pipelines
-Toggle the Disable anonymous access to badges slider under General

The option to toggle Disable anonymous access to badges is not there. I searched the page and project just to be sure before sending this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7336a04e-5b38-d02f-8bba-a55445b2f094
* Version Independent ID: 783c30b3-63b6-da7c-1336-b000bb8b4c66
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=python%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
I just verified that these instructions are correct for the hosted product. Is it possible you're looking at an older on-prem release (TFS or Azure DevOps Server)?

If not, please file a support request here: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)
