### ISSUE TITLE
[error]DownloadKubectlFailedFromLocation https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl { Error: read ECONNRESET     at exports._errnoException (util.js:1020:11)     at TLSWrap.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### ISSUE THREAD

**Issue by LiZi-XD** [MicrosoftDocs/azure-devops-docs#9658]
I have an kubectl set Agent job which has error message like this : 

[error]DownloadKubectlFailedFromLocation https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl { Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

![image](https://user-images.githubusercontent.com/54048675/98907902-8b27d700-24fa-11eb-88dd-0a9c270a299c.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by vtbassmatt** [comment]
Thank you for your feedback. We are closing this issue and directing you to seek an answer through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
