### ISSUE TITLE
Arguments documentation don't match the example

### ISSUE THREAD

**Issue by clough360** [MicrosoftDocs/azure-devops-docs#9659]
The arguments show in the example don't match those described in the arguments documentation.
There are a different number of arguments. For example `disableAutoCwd` is described in the example but not in the documentation for the arguments.
Those that are in both don't match. For example `args` is document as `arguments`, `cwd` is documented as `Working Directory`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fff5ec-d766-b589-39ff-9c69ab26dd5b
* Version Independent ID: 12deb045-2511-b5bf-9e41-0d223bef516b
* Content: [Shell Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/shell-script.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/shell-script.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This one hasn't been updated into the newer style, where we tie the YAML name and the label together explicitly. For whoever picks up this task, you can use the data [here](https://github.com/microsoft/azure-pipelines-tasks/blob/38d6beafa3f561f6a230a99336fb18b544aefaf1/Tasks/ShellScriptV2/task.json#L34) to be 💯 confident in your mapping.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/shell-script-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
