### ISSUE TITLE
Incorrect spelling on page

### ISSUE THREAD

**Issue by shanereddy** [MicrosoftDocs/azure-devops-docs#9664]
Hi,

There is an error in the spelling of the work background. It is spelt as "backgroun".

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcbeeb04-899a-4915-798f-9d6285c535ca
* Version Independent ID: c23d061e-9544-ec2b-c870-6802dbc44fb2
* Content: [Update and monitor your Taskboard - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/task-board?view=azure-devops)
* Content Source: [docs/boards/sprints/task-board.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/sprints/task-board.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@shanereddy  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
