### ISSUE TITLE
DAX highlighting support in wiki pages 

### ISSUE THREAD

**Issue by bartvanandel** [MicrosoftDocs/azure-devops-docs#9665]
I'd like my DAX code to be highlighted in Azure DevOps wiki pages. Currently it seems this is not supported. Would you be willing to pick up changes from this (closed but not merged) [pull request](https://github.com/highlightjs/highlight.js/pull/1560/) and add support for DAX to HighlightJS, or host it as a 3rd party dependency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @bartvanandel, Thanks for reaching out.  At this time, I don't believe we'd take that on for wiki. I'd still recommend [submitting your request](https://developercommunity.visualstudio.com/spaces/21/index.html), however. Select **Suggest a feature**, and then **Azure DevOps**.  Enter your suggestion, and then select **Post your feature suggestion**. Thanks again!
