### ISSUE TITLE
NPM Caching Issue

### ISSUE THREAD

**Issue by eluchsinger** [MicrosoftDocs/azure-devops-docs#9666]
There might be an issue with the NPM Caching Documentation. The default path for the NPM Cache is different than the one we're pointing the Cache Task to.

This answer on SO explains everything: https://stackoverflow.com/a/64690902/2632991

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@eluchsinger Thank you for your feedback. `npm ci` deletes the `node_modules` folder to ensure that a consistent, repeatable set of modules is used, you should **avoid caching** `node_modules` **when calling** `npm ci`. Please refer to the tip at the end of the [section](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm).

**Comment by eluchsinger** [comment]
@ramiMSFT  no one is caching `node_modules`... it's the folder `.npm` that's being cached. In fact, it's the same caching behavior that's described in the documentation.

**Comment by ramiMSFT** [comment]
@eluchsinger Your query was about the npm cache path. When npm is running, the config parameters are placed into the env with the `npm_` prefix. `npm_config_cache` is the cache location env variable. See the npm docs [here ](https://docs.npmjs.com/misc/scripts#configuration)for more details.

> Configuration parameters are put in the environment with the npm_config_ prefix. For instance, you can view the effective root config by checking the npm_config_root environment variable.

You can also set your own environment variable using `export` and `unset` to remove it.

**Comment by eluchsinger** [comment]
@ramiMSFT 

I am not asking about the NPM Cache path. I'm trying to tell you that the docs seem to be wrong. I don't need to export any location variables.

What I've found is that when you run the Cache Task as it's described in the docs in an Ubuntu Agent, the post-build step will **fail**.

It will fail because the NPM Task will cache the `.npm` folder in the **default** folder `/home/vsts/.npm`. But the docs tell the Cache Task that the folder is in a custom folder instead: `$(Pipeline.Workspace)/.npm`. So then in the Post Build Step, the Caching Task will try to cache a folder in `$(Pipeline.Workspace)/.npm` that does not exist.

Instead, what you have to do is tell NPM that it should cache everything in the same custom path that the Cache task is looking for: `npm ci --cache $(NPM_CACHE_FOLDER)`.

The docs should be updated to fix the npm cache path.
