### ISSUE TITLE
What is the Tools Cache?

### ISSUE THREAD

**Issue by patrick-king** [MicrosoftDocs/azure-devops-docs#9667]
This task refers to a 'tools cache' in the header comment. 
  "Acquires a specific version of NuGet from the internet or the tools cache and adds it ..."
Is the tools cache a well-known location in Azure DevOps?
My context for the question is an environment where the build agent has no internet access, so every dependency has to be available for download from on-network sources, or pre-installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4861e9-3c5e-ccc8-6918-f5a7327de545
* Version Independent ID: 8681cf86-9935-2063-ab5d-7ece1e14a2b1
* Content: [NuGet Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
We mention the tools cache in the [Use Python task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task), but really we should move [this doc](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md#tool-cache) into the official docs somewhere.

**Comment by msebolt** [comment]
@patrick-king  Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.

**Comment by jonathh21** [comment]
(i am none the wiser..)

**Comment by thedarkfalcon** [comment]
> I came here because https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops similarly references tools cache amusingly googling it brought me to here.
@jonathh21 

I did the exact same thing. The supplied answer tells me absolutely nothing. I _think_ what it means is.. If you [read this](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops#open-source) (scroll up slightly from my anchor), maybe the tools cache is the software "pre-installed" but not actually enabled? In my case on [this page](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) I followed through to the [windows-latest software list](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) which lists java... Pre-installed, and a cache seems different things to me.. but if it's not that, I have no idea what else it means.

**Comment by f4nb0y** [comment]
I think the tools cache is an optimisation for the tool installer tasks at https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/?view=azure-pipelines#tool-tasks

For example, [GoTool@0](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/go-tool-v0?view=azure-pipelines&viewFallbackFrom=azure-devops) says:

> Use this task to find in the tools cache or download a specific version of Go and add it to the PATH.
