### ISSUE TITLE
Url mentioned in the doc is wrong..

### ISSUE THREAD

**Issue by AvinashMitta** [MicrosoftDocs/azure-devops-docs#9677]
Url mentioned in the doc:
https://{organization}/_apis/notification/DiagnosticLogs/{event ID}/entries?startTime={date}&endTime={date}

It should be:
https://dev.azure.com/{organization}/_apis/notification/DiagnosticLogs/{event ID}/entries?startTime={date}&endTime={date}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4db6b52-d81d-410a-6237-ce7371a0ceb8
* Version Independent ID: 15af6008-ddfc-0c30-cc3e-1e6e027c67c1
* Content: [How to enable subscription logging - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/use-subscription-logging?view=azure-devops&viewFallbackFrom=vsts&source=docs)
* Content Source: [docs/notifications/use-subscription-logging.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/use-subscription-logging.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@AvinashMitta  Thank you for the feedback and for contributing per [this commit](https://github.com/MicrosoftDocs/azure-devops-docs/commit/27d23a0c6425bd94505076cd572dca7d178587ff#diff-9c41080b04f8ad6c98a4ea6432758cdaec7ed092843eea149ecee8ff2e48580f).

For more information, please see [becoming a contributor](https://docs.microsoft.com/contribute).
