### ISSUE TITLE
Documentation unclear on extension Publish/Unpublish vs. Share/Unshare

### ISSUE THREAD

**Issue by andersforsgren** [MicrosoftDocs/azure-devops-docs#9678]
For some extensions the menu will show "Publish" and "Unpublish", not "Share" or "Unshare" as depicted in the documentation page. It's not clear in the documentation what determines when these options are shown.  It's likely down to whether the extension is marked public or not but that isn't very clear.

Picture 1: Menu from the management portal

![bild](https://user-images.githubusercontent.com/2737503/99278388-428c5880-282f-11eb-9235-9fe7eb4cce21.png)

Picture 2: Picture from the documentation page:  note the "Share" vs "Publish" difference

![bild](https://user-images.githubusercontent.com/2737503/99278504-6c457f80-282f-11eb-98da-c277686f9e6e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @andersforsgren, Thanks for the heads up. I've clarified in the article that it displays differently depending on the extension, but that the functions are the same. Thank you!
