### ISSUE TITLE
Use O365 Subscription to activate DevOps Service org and billing

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/azure-devops-docs#9679]
Can you please add documentation on how to setup Azure DevOps Service Org and billing using O365 account for enterprise?
Typically what are the steps to use the free AAD subscription one gets with O365 and use it with DevOps Service for creating devops organization and setup billing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52303279-70fd-a0f6-cc6f-96bf73ed8c32
* Version Independent ID: cb30fbe3-b069-2665-d8da-9f714a23290a
* Content: [Frequent questions about billing management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops)
* Content Source: [docs/organizations/billing/billing-faq.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/billing-faq.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by Anand-Moghe** [comment]
Please also add documentation for O365, O365 GCC and O365 GCC High as well.

**Comment by chcomley** [comment]
Hi @Anand-Moghe, thanks for reaching out! Adding @parsamzand for feedback/input. Thanks!

**Comment by ramrajesh** [comment]
This is a subscription to use Azure AD and not Azure DevOps. If this Azure subscription isn't tied to a payment method, then you can't use that for Azure DevOps.

**Comment by Anand-Moghe** [comment]
@ramrajesh But it does create Azure AD in public cloud and people want to use to tie to DevOps billing. Problem is no proper documentation available on how to enable Azure AD subscription that comes with O365 or O365 GCC and O365 GCC High (not applicable as its AAD is in Gov cloud ). Hence I opened the issue to have a link somewhere that explain enabling AAD for O365 and O365 GCC for DevOps.

**Comment by chcomley** [comment]
@Anand-Moghe, this is out of scope for this article, so I'll be closing this issue. Please **Report a problem** in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and they can direct you to the information that you need.
