### ISSUE TITLE
WIQL reference text describes a more complex query than shown

### ISSUE THREAD

**Issue by patridge** [MicrosoftDocs/azure-devops-docs#9681]
*Disclaimer: I'm still learning WIQL for use in Azure DevOps queries, and I'm trying to learn more because I'm constantly running into issues with queries involving dates.*

In the [section covering date macros](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#----macros) in the [WIQL reference syntax doc](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#----macros), there is this line…

> This syntax allows you to nest modifiers and offset your query twice. For example, the following clause filters work items that have been closed last year and three months into the start of the current year.

…and subsequent query code block ([Markdown lines](https://github.com/MicrosoftDocs/azure-devops-docs-pr/blame/master/docs/boards/queries/wiql-syntax.md#L365-L369))…

> `[Microsoft.VSTS.Common.ClosedDate] >=@StartOfYear('+3M') - 1`

To me, that text seems to describe a query that would require two clauses, while the displayed query is only a single clause. And I'm not totally sure the given query correctly describes one half of such a query.

Part of the problem could be that these `StartOf*` macros don't seem [documented](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-operators-variables?view=azure-devops) enough to remove ambiguity with their interpretation/execution.

## Possible solution: query unchanged but text changes

If could just be a typo in the text. If, instead, the text said, "…work items that have been closed since four months into last year", the query example might be completely accurate as it is.

Again, I could be interpreting these macros incorrectly, but here's my interpretation of this query assuming the current year is 2020.

1. `@StartOfYear()` would be 01 January 2020
1. So, adding `('+3M')` would add three months to the start of the current year: 01 April 2020
1. Then, adding ` - 1` would take away another entire year: 01 April 2019

So, any issues closed `>=` that date (AKA "more recent than that date") would be caught by that query.

## Possible solution: text unchanged but query gets more complex

Keep the text the same but the query needs updating. The text description implies a query that requires two clauses with an implied "between":

> filters work items that have been closed [between] last year and three months into the start of the current year

I'm not sure it's worded quit sufficiently, but in my head, that would be "closed since last year" `AND` "closed…[up to] three months into the start of the current year".

If my understanding of WIQL is sufficient, that could be "closed since the start of last year but not closed after March of this year".

```
[Microsoft.VSTS.Common.ClosedDate] >= @StartOfYear() - 1
AND [Microsoft.VSTS.Common.ClosedDate] < @StartOfYear('+3M')
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710af5f2-8a31-e0d3-4f20-00c79dc54713
* Version Independent ID: 1d4d9580-984c-9fee-861a-a02ce828d3db
* Content: [WIQL reference syntax - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax?view=azure-devops#start-of)
* Content Source: [docs/boards/queries/wiql-syntax.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/wiql-syntax.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@patridge -  Thank you for this feedback. I've added an item to my backlog and look forward to updating this article within the next few weeks.
