### ISSUE TITLE
Please clarify licensing for Azure DevOps 2019/2020

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/azure-devops-docs#9682]
It's not clear from the page what licensing (and thus what parts of that page) apply to Azure DevOps 2019 and 2020.

Let's clarify this!

Thanks,
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Start using Azure Artifacts - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?view=azure-devops#q-how-can-i-control-how-long-artifacts-are-stored)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by herenhuang** [comment]
Investigating...

**Comment by ramiMSFT** [comment]
@NenoLoje Thank you for your feedback! Azure Artifacts comes pre-installed in Azure DevOps Server 2019 and 2020 and every org gets up to 2 GiB of free storage.

**Comment by NenoLoje** [comment]
Thanks, @ramiMSFT!

The page has a helpful note now, but it's still not clear.

Can we clarify for the readers that most of the page applies for the cloud service only, and not for Azure DevOps Server?
Even when I select "DevOps Server 2020" in the version picker, it still shows not-applicable facts like the 2 GiB storage limit.

![grafik](https://user-images.githubusercontent.com/13981145/126908660-42303233-a4bc-446f-92cf-6066efefe39b.png)
