### ISSUE TITLE
Action values are not clear in yaml snippet / Arg list

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/azure-devops-docs#9685]
Looking at the yaml snippet for Action and the allowed values of deleteRG, my assumption is this will delete a resource group?

However running the command and the build task reports the error:

`##[error]This action is not defined. Check with the task author. deleteRG`

It looks like the correct action is **D**eleteRG based off the [task file](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceGroupDeploymentV2/task.json).

Could all the actions be added and a description in the argument list and the snippet tidied up?

Maybe it should also be documented that the validation action will create a resource group, but not the rest of the resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
