### ISSUE TITLE
Note on specifying demands for manually queued builds

### ISSUE THREAD

**Issue by miniyou** [MicrosoftDocs/azure-devops-docs#9686]
There's a tip regarding specifying demands at queue time:

> When you manually queue a build you can change the demands for that run.

However, it seems that this is only true for classic non-YAML build definitions – could be worth pointing out. It confused me a few minutes until I figured out the cause.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
Fair point.

**Comment by msebolt** [comment]
@miniyou Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
