### ISSUE TITLE
How does one reach the link that you've embedded in the article?

### ISSUE THREAD

**Issue by FeynmanFan** [MicrosoftDocs/azure-devops-docs#9688]
You've copied and pasted the link to the integration page - where did that come from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1402b59d-915f-2457-e198-60898fd66191
* Version Independent ID: af8951ef-3bc1-8748-81a5-03696c6f5e85
* Content: [Create a service hook with Trello - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/trello?view=azure-devops)
* Content Source: [docs/service-hooks/services/trello.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/trello.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by steved0x** [comment]
@FeynmanFan Sorry for the delay, do you mean this URL?

`https://{orgName}/{project_name}/_settings/serviceHooks`

If so, you can create that URL by replacing `{orgName}` with the name of your Azure DevOps organization, and by replacing `{projectName}` with the name of your Azure DevOps project. For example, here is the URL for a project I have named `FabrikamFiber` that is part of an organization named `fabrikam`:

`https://dev.azure.com/fabrikam/FabrikamFiber/_settings/serviceHooks`

You can also get there by choosing Project Settings->Service hooks:

![image](https://user-images.githubusercontent.com/1580889/102281773-8beac900-3efd-11eb-93b5-aa489e41fa6d.png)

I am going to update the page with this info, but if I have answered the wrong question, please file a new issue and we'll try and provide more info.

Thank you.

**Comment by FeynmanFan** [comment]
Yeah, I figured it out - seems like the most reliable way is to get it from the Service Hooks, which is where I ultimately found it. Thanks.
