### ISSUE TITLE
Unable to communicate with GitHub Enterprise Server from Azure DevOps

### ISSUE THREAD

**Issue by indranil-chakraborty-thd** [MicrosoftDocs/azure-devops-docs#9691]
I have updated the firewall rules for my organization to permit inbound connections from the 'Central US' IP address; my Azure DevOps organization is located in Central US.
However, when I attempt to verify a connection, I am unable to do so. I get the error as below.

`Failed to query service connection API: 'https://github._<hidden>_.com/api/v3'. Error Message: 'A task was canceled.'`

Interestingly, a Firefox debugger indicates that the connection is originating from 13.107.42.20 which is not in the list of IPs that MSFT has listed as source IPs for Central US region. (I did find a reference to this IP range in a different Azure DevOps doc but that seemed to indicate a range of IPs for being able to access Azure DevOps across a firewall; i.e., outbound from corporate network to Azure DevOps).

Is the list of IPs provided for Central US correct? 
Should I expect that if my ADO organization is in Central US and the list of IPs are permitted to access my GitHub Enterprise, then a Service Connection verification should work? Or am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b14972b7-883c-37c8-96f9-114327f15e05
* Version Independent ID: 00baf3e0-f225-dc97-a15d-f9d97dac28d2
* Content: [Build code from GitHub Enterprise Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github-enterprise?view=azure-devops)
* Content Source: [docs/pipelines/repos/github-enterprise.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/github-enterprise.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@indranil-chakraborty-thd Thank you for the question and apologies for the issue.

Please refer to [Allowed address lists](https://docs.microsoft.com/azure/devops/organizations/security/allow-list-ip-url) for a list of required IPs.

The IP address `13.107.42.20` referenced above can be found listed under the [express route connections](https://docs.microsoft.com/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#azure-devops-expressroute-connections).

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by vijayma** [comment]
I have updated the docs with the new IP address ranges. Also, I clarified that you should include ExpressRoute ranges as well in case you rely on that.
