### ISSUE TITLE
Support mermaid for any markdown file (.md) file in the repo

### ISSUE THREAD

**Issue by rorezende** [MicrosoftDocs/azure-devops-docs#9692]
Consider to support mermaid to any markdown file in the repo ( https://mermaid-js.github.io/mermaid/#/ )

Currently DevOps Wiki already supports mermaid (https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page) but md files in the repo are not supported.

**Comment by rorezende** [comment]
@msebolt I suspect this is not the right repo for this issue, would you help me to point to the correct one?

**Comment by msebolt** [comment]
@rorezende Somewhat, in we can only make changes to the documentation here.

For product issues, please refer to the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html), or add to an ongoing post [here](https://developercommunity.visualstudio.com/idea/817244/support-mermaid-diagrams-in-markdown-file-preview.html).

**Comment by mijacobs** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
