### ISSUE TITLE
Running `npx tfx extension create` does not work

### ISSUE THREAD

**Issue by jccr** [MicrosoftDocs/azure-devops-docs#9693]
The instructions under the [Package your extension](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops#package-your-extension) is unclear.

Running `npx tfx extension create` does not work.
I get this, which seems wrong:
```
$ npx tfx extension create
npx: installed 13 in 1.501s
  tfx: "extension" is invalid, please see other available commands 
Usage: tfx [options] [command]

Options:
  -V, --version   output the version number
  -v --version    output the version number
  -h, --help      output usage information

Commands:
  upload|u <src>  upload static sources include js、css、img
  init|i          ftx init project, include config file and project boilerplate
  *
```

`npx tfx-cli extension create` with tfx-cli instead does work:

```
$ npx tfx-cli extension create
npx: installed 231 in 6.828s
TFS Cross Platform Command Line Interface v0.8.3
Copyright Microsoft Corporation

=== Completed operation: create extension ===
 - VSIX: /XXXX-1.0.0.vsix
 - Extension ID: XXXX
 - Extension Version: 1.0.0
 - Publisher: XXXX                       
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jccr Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
