### ISSUE TITLE
Duplicated item in list of things that stakeholders can't do.

### ISSUE THREAD

**Issue by chickenpotpie** [MicrosoftDocs/azure-devops-docs#9694]
[Enter feedback here]

This is twice in the list of things that stakeholders can't do.

"•	Delete work items or move work items to another project"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process#features)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chickenpotpie - Thank you for the feedback. I'll be updating the article to remove the redundant text later today.
