### ISSUE TITLE
Wrong default maxSize statement

### ISSUE THREAD

**Issue by olaf-lange** [MicrosoftDocs/azure-devops-docs#9696]
Please update the statements about the default maxSize, which has been changed since 2018 to 60MB

Regards
Olaf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96caf4e-05c3-53e5-c1f6-3b24a95dac70
* Version Independent ID: 190fa3f7-dbba-315a-56bc-dc9f15355188
* Content: [Change the maximum attachment size for work items - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/change-maximum-attachment-size-work-items?view=azure-devops-2019)
* Content Source: [docs/reference/xml/change-maximum-attachment-size-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/change-maximum-attachment-size-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@olaf-lange - Thank you for the feedback. I'll update the article later today.
