### ISSUE TITLE
Support for repository resource triggers with Bitbucket Cloud

### ISSUE THREAD

**Issue by AlexDenton** [MicrosoftDocs/azure-devops-docs#9698]
This probably doesn't belong here but I'm cross-posting just in case:
https://developercommunity.visualstudio.com/idea/1260259/support-for-repository-resource-triggers-with-bitb.html

Repository resource triggers are not supported for Bitbucket Cloud. This would be very valuable to me. Is there any timeline or roadmap for supporting this?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by AlexDenton** [comment]
Still curious about this. Anything that can be shared?

**Comment by mijacobs** [comment]
This repo is for documentation issues. For product suggestions, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by AlexDenton** [comment]
@mijacobs I don't think this is a bug but I did link to the ticket I already opened above https://developercommunity.visualstudio.com/idea/1260259/support-for-repository-resource-triggers-with-bitb.html. Is this not the correct place? I have received no response their either.

**Comment by mijacobs** [comment]
Hi @AlexDenton , 
You're right--it's not a bug, it's a feature suggestion, so the link you used, https://developercommunity.visualstudio.com/idea/1260259/support-for-repository-resource-triggers-with-bitb.html, is the correct place.
