### ISSUE TITLE
Connect to GitHub

### ISSUE THREAD

**Issue by dark11111111** [MicrosoftDocs/azure-devops-docs#9699]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by dark11111111** [comment]
Connect to GitHub

**Comment by msebolt** [comment]
@dark11111111 Thank you for the feedback.

Please provide more context and/or details around the issue and we can help resolve this.
