### ISSUE TITLE
better clarity in documentation

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/azure-devops-docs#9705]
[Enter feedback here]

while a rather interesting page .... how do we know what the resource name is?

There are no screenshots or any contextual feedback to help a person determine if a resource is getting named properly. 

For example I have an environment lovingly called "dev".  I added a k8s resource into it.  But what is that resource name?  is it the namespace name?  the cluster name?  what? all i get is an extremely vague: `$(envName).$(resourceName)` with no variables defined or GUI screenshots to help associate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for pointing this out. You can find more information on resources naming in the [Resources in YAML article](https://docs.microsoft.com/azure/devops/pipelines/process/resources). I'll add a link to that article from this one.
