### ISSUE TITLE
Can you clearly show how env variables can be used in deployment tasks

### ISSUE THREAD

**Issue by rocinante-sys** [MicrosoftDocs/azure-devops-docs#9706]
We publish containers to azure container registry that are tagged with `latest` and `$(Build.BuildNumber)`.
But at the moment we are unable to update our deployment in kubernetes with this container as no env variables are resolved in the scripts. It just takes everything literraly.

![image](https://user-images.githubusercontent.com/52488395/99785346-a1174680-2b4f-11eb-92d6-c7fac62888db.png)

if I look at the yaml file the task is creating it takes the whole argument as string literal

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by vtbassmatt** [comment]
This is correct, the resource system doesn't have an environment to read from. We allow parameters in `container` resources now, so one way you could do this is to accept a parameter containing the desired label.

```yaml
parameters:
- name: label
  default: latest
  type: string

resources:
  containers:
  - container: foo
    image: repo/image:${{ parameters.label }}
```

For additional help, please reach out on the support site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)
