### ISSUE TITLE
Agent.ComputerName or Agent.MachineName?

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/azure-devops-docs#9707]
[Enter feedback here]
Is the variable (on the _capabilities_  screenshot) Agent.ComputerName?  Or should it be Agent.MachineName as documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
If you're going to change variable names or provide aliases, please mention this and document which is new, which is old, which is preferred.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
Capabilities ≠ predefined variables. There's a capability called `Agent.ComputerName` which you can select against using demands. Separately, there's a predefined variable called `Agent.MachineName` which you can use wherever variables can be used.

**Comment by edrandall** [comment]
@vtbassmatt note that I raised this as a documentation issue, because it was unclear, caused confusion and left mne having to manually determine the end behaviour by trial-and-error.  Clarifying that "Capabilities ≠ predefined variables" here doesn't help - you need to make that clear in the documentation.
