### ISSUE TITLE
Artifacts download filter missing in On-Premise version.

### ISSUE THREAD

**Issue by AroglDarthu** [MicrosoftDocs/azure-devops-docs#9708]
We are using Azure DevOps On-Premise
It seems that the option to select **which artifacts that you want to download** is not available. This, however, is not mentioned anywhere in the documentation page. Are we experiencing a bug in Azure DevOps Server, or does the On-Premise version not support this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac87575-019b-370a-6bbe-9b623241a2f5
* Version Independent ID: 8ff5e112-4949-c406-0b00-4fdfd82afe5f
* Content: [Release artifacts and artifact sources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/artifacts?view=azure-devops-2019#download)
* Content Source: [docs/pipelines/release/artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by ramiMSFT** [comment]
Thanks for your feedback! It's an issue with monikers. I'm updating the article shortly
