### ISSUE TITLE
How to make bugs appear in Done column of a Sprint Board after they are marked as Done?

### ISSUE THREAD

**Issue by someeint** [MicrosoftDocs/azure-devops-docs#9711]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad73cae9-9b23-078d-2b95-d83cc794df03
* Version Independent ID: 3aa17c7d-adca-6ca6-b1e0-e811f520b325
* Content: [Make bugs visible on backlogs and boards - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/show-bugs-on-backlog?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/show-bugs-on-backlog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/show-bugs-on-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by someeint** [comment]
![image](https://user-images.githubusercontent.com/74789457/99843286-2e45a580-2b26-11eb-918f-f9ed4c17f65c.png)

**Comment by KathrynEE** [comment]
@someeint - From the image you show, Bugs are being managed as requirements. TO have Bugs that are Done show up on the Taskboard Done column, you need to track them as Tasks.
