### ISSUE TITLE
Potentially misleading title and content?

### ISSUE THREAD

**Issue by cedricseah** [MicrosoftDocs/azure-devops-docs#9712]
(Check by switching the version to Azure DevOps Server 2020 and 2019)
The title "Move your packages to the cloud" is very misleading when applied to the on-premise Azure DevOps Servers, since packages will be moved into the on-premise, self hosted Azure Artifacts. 
Similarly, many mentions of Azure DevOps Service (despite changing the version). Would it be more correct to replace them with the term "Azure Artifacts" instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f93fa7-8ac3-bc92-a206-0c728d9f5949
* Version Independent ID: afcf001a-7f80-bb77-d74f-585144d4cabf
* Content: [Move your packages to the cloud - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/move-from-fileshares?view=azure-devops-2020)
* Content Source: [docs/artifacts/nuget/move-from-fileshares.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/move-from-fileshares.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@cedricseah Thank you for your feedback. A backlog item has been created to address this issue.
