### ISSUE TITLE
outdated UI images in documentation

### ISSUE THREAD

**Issue by JohnCOsborne** [MicrosoftDocs/azure-devops-docs#9713]
Please update with Git Changes window images ☺

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8011ea63-bd2e-226d-99e3-e277576f701a
* Version Independent ID: 92518bb9-1fcf-0511-803c-c74cc51414df
* Content: [Pull changes to your local Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pulling?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/pulling.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pulling.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by JohnCOsborne** [comment]
I'd be surprised if this isn't fixed by now...

**Comment by steved0x** [comment]
I think they are John, the article is updated with screenshots through Visual Studio 2022. Thank you for the feedback.
