### ISSUE TITLE
incorrect date (-1 day)

### ISSUE THREAD

**Issue by w0nders** [MicrosoftDocs/azure-devops-docs#9719]
Thank you for your feedback!

i use your documentation for calculating 
https://docs.microsoft.com/en-us/azure/devops/report/powerbi/create-timeinstate-report
but i see problem, last date it seems isn't correct, because if compare with value in azure devops boards, then difference in one day 

For example:
User Story in Azure Devops
![image](https://user-images.githubusercontent.com/40396241/99948176-140c0180-2d8a-11eb-9c40-858e66a614a5.png)

data in powerbi
![image](https://user-images.githubusercontent.com/40396241/99948631-c80d8c80-2d8a-11eb-8aee-1ab0768f2cab.png)

this problem starts to create difficulties when calculating general indicators, for example, calculating cycle time per week (values shift slightly)

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@w0nders Thank you for the feedback, assigning this to the author for further review.

If this issue becomes product-related, we recommend soliciting feedback from our product team using the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by mijacobs** [comment]
@KathrynEE @chcomley Can you take a look at this one?

**Comment by chcomley** [comment]
Hi @KathrynEE, This appears to be in your realm. It also appears that is may be an issue for the Dev Community, rather than this article, however I'll leave that determination up to you. Thanks for your patience, @w0nders.

**Comment by khilangoel** [comment]
@w0nders Looking into this. We store data into Analytics according to account's timezone but data in Boards could be based on user locale also. Just wanted to confirm is the timezone same for user as account's timezone? This could lead to some difference?

**Comment by ksmis-gh** [comment]
@w0nders any progress on the above ask?

**Comment by ksmis-gh** [comment]
@chcomley Can we close this issue?

**Comment by KathrynEE** [comment]
@ksmis-gh - Yes, closing this now.
