### ISSUE TITLE
Mutation Testing in Python

### ISSUE THREAD

**Issue by srhbhat** [MicrosoftDocs/azure-devops-docs#9720]
Hi Team, Can we also get capability for mutation testing on Python code using Tools like MutPy. I did installed Mutpy ( pip install mupy) and then ran the testing, It succeeded, but could not get the extension for reporting.
Please advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Thank you for your feedback. We are closing this issue and directing you to file a feature request through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
