### ISSUE TITLE
Permission/access manual testing: rogue bullet on the page

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/azure-devops-docs#9722]
There seems to be a rogue bullet point on the page:

![image](https://user-images.githubusercontent.com/1635825/100087634-50556580-2e4f-11eb-80e8-bf87ed8a2c29.png)

Might have to do with the asterisks as shown in the code block below:

https://github.com/MicrosoftDocs/azure-devops-docs/blob/2fe0a31440e1cac2c859f0c7c093dfe4d0c085ef/docs/organizations/security/set-permissions-access-test.md#L123-L143

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab4b0dc9-7898-683e-d897-e476f5b54fa5
* Version Independent ID: 01ebeb10-6724-fe3e-6042-5c0d98e5361d
* Content: [Set permissions and access for manual testing - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-permissions-access-test?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/set-permissions-access-test.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/set-permissions-access-test.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Styxxy - Thank you for the correction. I'll update the article later today.
