### ISSUE TITLE
why azurepowershell 5 still have preview note?

### ISSUE THREAD

**Issue by VectorBCO** [MicrosoftDocs/azure-devops-docs#9723]
Is AzurePowerShell@5 still in preview mode? 
In a GUI pipelines it`s already published as general one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by VectorBCO** [comment]
btw for some reason when I`m running from release pipeline `Get-Module -ListAvailable | Where {$_.Name -like "*az*"}` i`m receiving `Directory: C:\Modules\**az_4.7.0**`

**Comment by VectorBCO** [comment]
should i provide any additional info?

**Comment by VectorBCO** [comment]
should i provide any additional info?

**Comment by mijacobs** [comment]
Thank you for your feedback. It looks as though our docs reflect what's in the product. Please use this link to report an issue with the Azure DevOps product: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by VectorBCO** [comment]
@mijacobs there no issues in the product, issue here in a docummentation which not updated in real time. This page was not updated at leat 6 mongth, but Azure Devovs did.
What should I report to Azure Devops as a bug?

**Comment by mijacobs** [comment]
Sorry @VectorBCO, I misread your issue. It looks like @msebolt  updated the doc in November with your suggestions.

**Comment by VectorBCO** [comment]
@mijacobs yes, now I see that page was updated and "preview" was removed but actual Az Module version still not pumped up :(

Thanks @msebolt :)

**Comment by mijacobs** [comment]
@vectorBCO Can you describe how else the document needs updated? Are you saying that the AzModule for the version 5 row is missing supported versions?

**Comment by VectorBCO** [comment]
My guess that this values also should be updated
![image](https://user-images.githubusercontent.com/13451494/102281151-b0ab6480-3f2e-11eb-9bc0-d28469adbe8e.png)
