### ISSUE TITLE
Enterprise?

### ISSUE THREAD

**Issue by Courtney-L-Greer** [MicrosoftDocs/azure-devops-docs#9724]
[Enter feedback here]
There is a new option for visibility "Enterprise" I can't find any documentation on what that visibility level means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a4e9e9-6773-fad2-23fb-8b44313f8ef3
* Version Independent ID: 33cbd1fc-2230-4e0b-2627-2a63bf7c634e
* Content: [Make your project public or private - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=azure-devops)
* Content Source: [docs/organizations/public/make-project-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/make-project-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by aaronhallberg** [comment]
This option should only be visible to Microsoft employees and is related to a feature that never shipped (and never will) to the broader Azure DevOps community. When selected, it indicates that the project is visible to all Microsoft employees, but not to anonymous users.
