### ISSUE TITLE
Add -Suffix parameter to NuGet pack task

### ISSUE THREAD

**Issue by maxkoshevoi** [MicrosoftDocs/azure-devops-docs#9726]
As of now I need to use custom NuGet command to create nuget with suffix.
Could you add it as one of predefined parameters, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
Thank you for your feedback. We are closing this issue and directing you to file a feature request through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
