### ISSUE TITLE
Bad character in overrideParameters gives error "empty key"

### ISSUE THREAD

**Issue by alevincenzi** [MicrosoftDocs/azure-devops-docs#9727]
Hello

The property `overrideParameters` has en example with a bad character. We read: 

```
–storageName fabrikam –adminUsername $(vmusername) -adminPassword $(password) –azureKeyVaultName $(fabrikamFibre).
```

but the dashes `–` are not valid characters to specify a key. The good ones are the `-`.

I did a copy and paste and it took me several runs to detect it. The pipe was saying there was an empty key.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by vtbassmatt** [comment]
Yikes! Thank you.

**Comment by msebolt** [comment]
@alevincenzi Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
