### ISSUE TITLE
Steps to remove project admin are not valid

### ISSUE THREAD

**Issue by jennifermarsman** [MicrosoftDocs/azure-devops-docs#9728]
I want to remove some project admins who have left the team.  

On the page, it states that you can remove an admin by clicking an "x" to the right of their name.  

I followed the steps (and I am a project admin so should have the proper permissions), but I do not see a UI with "x" to the right of the admin's name in my UI.  Was this UI updated and the screenshots not updated to reflect this?  How do I remove a project admin?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add, remove team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jennifermarsman - The steps to remove a Project Administrator member is documented here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=azure-devops&tabs=preview-page#remove-a-user-or-a-group. The steps are a bit different from removing a Team Administrator. Thank you for your inquiry.
