### ISSUE TITLE
Publish Artifacts

### ISSUE THREAD

**Issue by kaycoinsUSA** [MicrosoftDocs/azure-devops-docs#9731]
Permissions to import Artifacts
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34dc460-e0f4-ff01-3c09-1b40864de6c2
* Version Independent ID: 54f9b157-0ae5-e57a-3c1e-3ff58cbfc6f7
* Content: [Artifacts in Azure Pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/artifacts-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/artifacts-overview.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@kaycoinsUSA Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
