### ISSUE TITLE
Error when try to create storage container 

### ISSUE THREAD

**Issue by TiansuYu** [MicrosoftDocs/azure-devops-docs#9733]
Error occurs when one tries to create a storage container following this guide. 

input: 
```
az storage container create -n rawdata --account-name $storageName --resource-group $rgName
``` 
or 
``` 
az storage container create -n rawdata --account-name $storageName
```
Error message: 
``` 
There are no credentials provided in your command and environment, we will query for the account key inside your storage account.
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli.
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
``` 
I am new to Azure, how do you save the credentials in your environment or tag along per query? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee5f1f5-f065-d2eb-5c6f-fa15eee79eed
* Version Independent ID: 357d6f83-f859-0762-ff47-0bcd73b3d33f
* Content: [Build a data pipeline by using Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/azure/build-data-pipeline?view=azure-devops)
* Content Source: [docs/pipelines/apps/cd/azure/build-data-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/apps/cd/azure/build-data-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd-apps**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the 
documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
