### ISSUE TITLE
Rest api for approvals and evnvironments

### ISSUE THREAD

**Issue by manivasm** [MicrosoftDocs/azure-devops-docs#9734]
This features are released long back. But still i couldnt find and documentation on rest api to access the log of approvals through environments for yaml pipeline ( for release pipeline approval documentation is available.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
@shashban may be able to help with this one.

**Comment by shashban** [comment]
The API documentation is going to be live with the next deployment.

**Comment by ketaanhshah** [comment]
Hi All,
Can someone point me to documentation on how we can programmatically approve a stage in YAML Pipeline using REST API? It has become real struggle to get steps on approving a YAML based pipeline stage using REST API. Appreciate some help on this.

**Comment by juliakm** [comment]
@manivasm You can find the approvals REST API [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/?view=azure-devops-rest-7.1).
