### ISSUE TITLE
`AzureDevOps` does not exist as an option for Network Security Group service tags

### ISSUE THREAD

**Issue by howardjones** [MicrosoftDocs/azure-devops-docs#9735]
`AzureDevOps` does not exist as an option for Network Security Group service tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by justhchung** [comment]
Azure DevOps service tag is released. 

https://devblogs.microsoft.com/devops/azure-devops-service-tag-released/

**Comment by howardjones** [comment]
AzureDevOps is still not available as a Service Tag in the Network Security Group Editor.

**Comment by howardjones** [comment]
![image](https://user-images.githubusercontent.com/912421/106455839-a4e71380-6484-11eb-92f9-708c433adceb.png)

**Comment by somarnebur** [comment]
https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview


AzureDevOps | Azure Dev Ops.**Note: This tag is not currently configurable via Azure Portal** | Inbound | No | Yes
