### ISSUE TITLE
Typo in YAML Deployment job Schema

### ISSUE THREAD

**Issue by A-AontwSR** [MicrosoftDocs/azure-devops-docs#9737]
On this page , at the section [Deployment job](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#deployment-job), the Schema is written as:
```yaml
  strategy:
    runOnce:
      deploy:
        steps:
        - script: [ script |  ...
```
I think the last 2 lines are wrong. The last line should be gone and the next to last line should be:
```yaml
        steps: [ script | ...
```
That line is described in the next section [Steps](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps). So that the Schema in [Deployment job](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#deployment-job) ends with:
```yaml
  strategy:
    runOnce:
      deploy:
        steps: [ script |  ...
```

Another issue is that the same typo **also exists on another page** [Deployment jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#schema) at the Schema section.

What do you think, is it a typo in the Schema at both pages?
If so, please correct the Schemas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#task)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
@steved0x , can you take a look?

**Comment by steved0x** [comment]
Investigating

**Comment by steved0x** [comment]
@A-AontwSR Thank you for letting us know, I am fixing this and it will be live shortly. Thank you!
