### ISSUE TITLE
Branch Filter not working

### ISSUE THREAD

**Issue by tiaan-lg** [MicrosoftDocs/azure-devops-docs#9739]
Hi

I have connected the AZ Repos app to my slack and it works for ANY branch, but when I try to filter it to 1 specific branch the subscribe dropdown in the slack app doesn't show the branches in the repo.

Here is a screenshot of what I am experiencing

![image](https://user-images.githubusercontent.com/42767734/100433412-b6d2c180-30a3-11eb-8b88-a18441c2b4cf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8b93c91-a6af-81ed-b9b3-d857dcc8d17b
* Version Independent ID: 60f9efcd-8c36-1f83-7ff3-c22e93308505
* Content: [Azure Repos with Slack - Azure Repos](https://docs.microsoft.com/en-za/azure/devops/repos/integrations/repos-slack?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/integrations/repos-slack.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @divais
* Microsoft Alias: **Divais**

**Comment by divais** [comment]
@ashokirla 👀

**Comment by tiaan-lg** [comment]
Hi

Any update on this, please?

**Comment by balukin** [comment]
Same problem, only [Any] is returned in branch picker. Member group list is populated as expected but branches are not queried properly.

**Comment by TooMuchBlue** [comment]
The documentation has a note in the Examples section:

> All the filters are typically drop-downs. However if the drop-down were to have greater than 100 items, then users are asked to enter the values manually.

I can't tell if that note was here when these comments were added.  Could this be a factor?
