### ISSUE TITLE
Contradictory documentation on arguments support for inline script

### ISSUE THREAD

**Issue by Jawz84** [MicrosoftDocs/azure-devops-docs#9742]
[Enter feedback here]
This passage below seemingly contradicts itself where it concerns arguments for inline scripts, see below, arrows mine.

```markdown
--|--
`Inline` Inline Script | (Optional) Enter the script to execute. Default value:
\# You can write your Azure PowerShell scripts inline here.
\# You can also pass predefined and custom variables to this script using arguments    <===
-- | --
`ScriptArguments` Script Arguments | (Optional) Additional parameters to pass to PowerShell. 
Can be either ordinal or named parameters. 
Not applicable for inline script option                                                <===
```

This leaves the reader with the question: so how _does_ one pass arguments to an inline script, if not via `ScriptArguments`?
I for one, still don't know, so I'm saving my inline script as a scriptfile now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@Jawz84 Thank you for the feedback.

This issue was recently reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/9578.  Please refer there for further updates and/or comments.

**Comment by Jawz84** [comment]
Thanks @msebolt !
