### ISSUE TITLE
How to add the PR tags in the Azure DevOps dashboard?

### ISSUE THREAD

**Issue by SibeeshVenu** [MicrosoftDocs/azure-devops-docs#9743]
How can I add the PR tags to the DevOps Dashboard? Any help is really appreciated. 

![image](https://user-images.githubusercontent.com/4262147/100468016-d255c080-30d3-11eb-8d23-9cdb71527c07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514ba817-c404-380b-6c8d-67ea982e9a22
* Version Independent ID: 915a8f30-5192-8b0a-d6a4-43fe7a606ff6
* Content: [Catalog of widgets you can add to a dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/widget-catalog?view=azure-devops)
* Content Source: [docs/report/dashboards/widget-catalog.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/widget-catalog.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@SibeeshVenu - Thank you for your inquiry. I don't know of any widget that supports adding PR tags to the dashboard. You can request such a feature on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
