### ISSUE TITLE
Outdated Content

### ISSUE THREAD

**Issue by JFolberth** [MicrosoftDocs/azure-devops-docs#9746]
This page still leverages the classic build and releases vs the new YAML releases. Would be more benefical if it was updated with the new YAML Pipelines. This will better align with the Azure DevOps roadmap. I can provide some YAML of it would be beneficial to the community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9d58d3-169a-2ffd-5bcf-02daa8d8ac04
* Version Independent ID: a4ae226e-1622-fb62-cfb6-d06bc7c35e84
* Content: [Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/automate-terraform?view=azure-devops)
* Content Source: [docs/pipelines/release/automate-terraform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/automate-terraform.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by JFolberth** [comment]
Any update on this?  More than willing to help get it turned around faster to help others out.

**Comment by ramiMSFT** [comment]
@JFolberth Thank you for your feedback. A backlog item has been created to update the article to address the issue you've raised.
