### ISSUE TITLE
Duplicate descriptions on inputs

### ISSUE THREAD

**Issue by robtextrequest** [MicrosoftDocs/azure-devops-docs#9752]
The SourceSlot and TargetSlot descriptions are both "(Required) The swap action directs destination slot's traffic to the source slot". I assume these should be different. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07461b2-a8a2-ec6f-769b-14b384777be3
* Version Independent ID: 2c72f09d-b198-461c-fc0d-1c3bd0a870c4
* Content: [Azure App Service Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-manage?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-manage.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-manage.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@robtextrequest Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
