### ISSUE TITLE
Git Version maybe wrong

### ISSUE THREAD

**Issue by QiMata** [MicrosoftDocs/azure-devops-docs#9753]
[Enter feedback here]

I think the stated minimum git version (2.9) should be 2.29?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2716bd-7d12-138f-9839-77f2aa400deb
* Version Independent ID: 1dfa640a-7206-ba69-52a2-799402a751b3
* Content: [Deploy a build and release agent on macOS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#check-prerequisites)
* Content Source: [docs/pipelines/agents/v2-osx.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-osx.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
investigating

**Comment by steved0x** [comment]
@QiMata Thank you for letting us know, this will be fixed today (both on here and on the Linux agent page).
