### ISSUE TITLE
Variable transformation not working for URL value

### ISSUE THREAD

**Issue by mattruma** [MicrosoftDocs/azure-devops-docs#9755]
I am trying to do a variable transformation for a variable with the value `https://MY_B2C_TENANT.b2clogin.com/MY_B2C_TENANT.onmicrosoft.com/B2C_1_SignUp_SignIn`.

![image](https://user-images.githubusercontent.com/188079/100620819-dad51380-32ec-11eb-84d8-4ce4d7c14090.png)

When I run it this way, the variable does not get substituted.

If I make the value `https://MY_B2C_TENANT.b2clogin.com/B2C_1_SignUp_SignIn`, the value gets transformed, but my `ClientId` is blank.

If I make the value `https://MY_B2C_TENANT.b2clogin.com`, all values are updated correctly.

Any guidance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mattruma** [comment]
It's very sporadic, sometimes it works, sometimes it doesn't.

**Comment by mijacobs** [comment]
Thank you for your feedback. We are closing this issue and directing you to seek an answer through our support web site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
