### ISSUE TITLE
Duplicate entry on page

### ISSUE THREAD

**Issue by MubDubs** [MicrosoftDocs/azure-devops-docs#9757]
There is a duplicate paragraph of text on this page.
![image](https://user-images.githubusercontent.com/75283373/100678648-a6d50f00-333b-11eb-87d3-ba7071aaa1bd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Manage preview features - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@MubDubs - Thank you for the correction. I'll update the article later today.
