### ISSUE TITLE
How to download  multiple secret fles inputs?

### ISSUE THREAD

**Issue by sscarduzio** [MicrosoftDocs/azure-devops-docs#9760]
[Enter feedback here]
Can you create an example for multiple secret files? I.e. multiple "inputs" 

My use case is that I have to download and symlink multiple files. Do I need to have two tasks? Or I can use only one? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vtbassmatt** [comment]
One file per task instance.

**Comment by msebolt** [comment]
@sscarduzio Thank you for the feedback, to solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

The documentation has been updated and is pending review.
