### ISSUE TITLE
Classic Multi-Job-Configuration Minimum number of elements?

### ISSUE THREAD

**Issue by Tyler-Angell** [MicrosoftDocs/azure-devops-docs#9762]
#### Explanation

When using classic configuration, for multi-configuration I specified a variable with comma separated values and it split the way I expected it to. However, when I remove the values from the variable so that there are no elements to multiply over I would expect the task to be skipped, however, the task ran with injecting an empty value causing the task to fail. This an unexpected behavior from my perspective, is this expected behavior from ADO's side? I couldn't find any supporting documentation for required minimum number of elements. 

#### Variable
![image](https://user-images.githubusercontent.com/47679282/100788683-47721000-33ca-11eb-8d7c-2968e094262f.png)

#### Usage
![image](https://user-images.githubusercontent.com/47679282/100788593-21e50680-33ca-11eb-9892-1e51ac0b4f93.png)

#### Outcome
![image](https://user-images.githubusercontent.com/47679282/100789083-d121dd80-33ca-11eb-8082-6e94036101b3.png)

#### Path when variable not null

`C:\BuildAgent\_work\r38\a\DigitalTwins\drop\outputs\package\QueryStore\RolloutSpec.ppe.ppe.json`
`C:\BuildAgent\_work\r38\a\DigitalTwins\drop\outputs\package\QueryStoreApi\RolloutSpec.ppe.ppe.json`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=classic#multi-job-configuration)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
We'll always generate at least one job, even if a multi-config variable is empty.

**Comment by Tyler-Angell** [comment]
Why is that? Shouldn't `job * 0 = 0`?

If this is a hard limitation how do I have an optionally run multi-configuration task with everything reporting green at the end of a release?

**Comment by juliakm** [comment]
#sign-off

**Comment by juliakm** [comment]
There will be an update posted shortly.
