### ISSUE TITLE
Is it possible to use self-hosted agent for  build and testing iOS, ipadOS, tvOS, and watchOS Apps?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/azure-devops-docs#9763]
Is it possible to use self-hosted agent for building and testing iOS, ipadOS, tvOS, and watchOS Apps?
Otherwise what options are available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2716bd-7d12-138f-9839-77f2aa400deb
* Version Independent ID: 1dfa640a-7206-ba69-52a2-799402a751b3
* Content: [Deploy a build and release agent on macOS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-osx.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-osx.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Please see this article:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops

**Comment by Anand-Moghe** [comment]
@mijacobs  Thanks. I wish that the link was updated with these keywords related to Apple development platform, so it is more upfront and explicit for those looking for confirmed answer in documentation.

**Comment by mijacobs** [comment]
Good point, @Anand-Moghe ! @steved0x , can you update the article to mention iOS and other Apple technologies in the summary?

**Comment by Anand-Moghe** [comment]
If you do an internet search, you see these keywords mentioned in our competitor articles and documentation "Use Amazon EC2 Mac Instances to Build & Test macOS, iOS, iPadOS, tvOS, and watchOS Apps". One of my customers alluded me to this which is a reason for opening this issue. Azure platform is providing a way but decision makers are not able to find this information quickly.
