### ISSUE TITLE
Add WebLOAD to the alternatives list

### ISSUE THREAD

**Issue by jane-king** [MicrosoftDocs/azure-devops-docs#9765]
Can you add RadView WebLOAD (https://www.radview.com/) to the list of alternatives? 

"If you use code-based tests for load testing and .NET is your platform of choice then tools such as Neoload, Micro Focus Silk Performer, Micro Focus Load Runner and RadView WebLOAD are options to consider."
 
  Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde00a22-c654-f6e9-5bad-c4deb0852899
* Version Independent ID: 88ff6f31-199d-e3f6-bc68-be91dc695b0e
* Content: [Load test overview - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/overview?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/overview.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@jane-king Thank you for the feedback, please consider [becoming a contributor](https://docs.microsoft.com/contribute).

The documentation has been updated and is pending review.
