### ISSUE TITLE
Key Vault integration

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#9767]
What is your guidance on Key Vault integration? What is the best way to create a keypair inside a pipeline and store it into Key Vault? And thereafter, consume it from the Key Vault?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vtbassmatt** [comment]
Thank you for your feedback. We are closing this issue and directing you to seek an answer through our support site: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
