### ISSUE TITLE
Inconsistent indentation in the example

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/azure-devops-docs#9769]
In the example, under the section "Parameters to select a template at runtime", the 2 conditional steps have been indented. Although this is valid YAML, all other examples on the MS pages indent the dictionary items to the same level as "steps", so moving each of the lines following "steps:" would be more consistent.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
This will be update shortly.
