### ISSUE TITLE
The `noCache` option is incorrect.

### ISSUE THREAD

**Issue by giuliov** [MicrosoftDocs/azure-devops-docs#9772]
The `noCache` option adds the `--no-cache` flag to the `dotnet restore` command. [That documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore) states

> Specifies to not cache HTTP requests.

and this is the behaviour one can see in detailed logs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by msebolt** [comment]
@giuliov  Thank you for the feedback.

To keep the documentation in sync with the [task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/task.json), please move this issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

In the meantime, please include the `--no-cache` option with `arguments` parameter to provide the described behavior.

**Comment by TimShererWithAquent** [comment]
@giuliov We've created a new issue in the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

**Comment by TimShererWithAquent** [comment]
cc @pulkitaggarwl for awareness.
