### ISSUE TITLE
Kanban is misspelled to Kamban in top

### ISSUE THREAD

**Issue by erjaintarun** [MicrosoftDocs/azure-devops-docs#9774]
[Kanban is misspelled to Kamban in top
 Note

If your team is committed to practicing Kamban or Scrum methods, see instead About Boards and Kanban or the tutorials for implementing Scrum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9521d223-2617-ca56-585e-e4064d43ee7f
* Version Independent ID: aa9db125-f2b7-d191-712a-f2a8a0ca0f70
* Content: [Best practices for Agile project management - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/best-practices-agile-project-management?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/best-practices-agile-project-management.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/best-practices-agile-project-management.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@erjaintarun - Thank you for the correction. Will update today.

**Comment by erjaintarun** [comment]
My pleasure Kathryn.
