### ISSUE TITLE
feature branch naming convention is not consistent

### ISSUE THREAD

**Issue by sperezintexas** [MicrosoftDocs/azure-devops-docs#9776]
[Enter feedback here]

the image and text do not match the image has "feature"
where as the kiss suggestion shows "features"

the topic branching strategy suggestions on this page are not consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe168fc3-2ed2-b3e6-ce30-cac721165ceb
* Version Independent ID: 8d63fbd7-12c4-9a94-92f6-969e7eb41037
* Content: [Git branching guidance - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=azure-devops)
* Content Source: [docs/repos/git/git-branching-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/git-branching-guidance.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by steved0x** [comment]
#reassign steved0x

**Comment by steved0x** [comment]
I'll get that updated, thank you for your feedback.
