### ISSUE TITLE
Access Token Script incorrect

### ISSUE THREAD

**Issue by MattTrinder1** [MicrosoftDocs/azure-devops-docs#9783]
The Access token YAML script causes a compilation error when copied into a yaml build file.
 It needs to be

`- powershell: |
              $env:SYSTEM_ACCESSTOKEN = '$(System.AccessToken)'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@juliakm Not sure if this document is supporting yaml build file, but perhaps the suggested change is necessary.

**Comment by juliakm** [comment]
Thanks @MattTrinder1. The current example works for me with a Windows agent but your example is helpful. I'm about to push an update that includes it.
