### ISSUE TITLE
What is notifyLoadFailed parameter?

### ISSUE THREAD

**Issue by josefblaha** [MicrosoftDocs/azure-devops-docs#979]
What is the "e", the only parameter of the notifyLoadFailed method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f699a190-5e7e-1103-8d9d-c3d58e698e3a
* Version Independent ID: 1e54fe20-7e4d-d5ff-1682-8659f7a8fba8
* Content: [Core Client SDK](https://docs.microsoft.com/en-us/vsts/extend/reference/client/core-sdk?view=vsts#method_notifyLoadFailed)
* Content Source: [docs/extend/reference/client/core-sdk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/client/core-sdk.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @josefblaha , I just reached out to the product team to find this out - it does seem a bit vague huh? I'll notify you when I find out!

**Comment by chcomley** [comment]
Hi @josefblaha, The notifyLoadFailed parameter e equals "any." I'm closing this ancient issue, however if you need further clarification, please @mention me. Thank you!
