### ISSUE TITLE
Arguments examples

### ISSUE THREAD

**Issue by csdaraujo** [MicrosoftDocs/azure-devops-docs#9791]
Hi!

There is no example on how to use `arguments` with custom variables. Could you add some, please? Also, a `bash` `scriptType` would be nice.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by csdaraujo** [comment]
I managed to use it like this:
```
      - task: AzureCLI@2
        displayName: Update app
        inputs:
          azureSubscription: arm-example
          scriptType: bash
          scriptLocation: inlineScript
          arguments: >
            -g rg-${{ parameters.example }}-example
            -n app-${{ parameters.example }}-example
            -c example.azurecr.io/example:$(tag)
          inlineScript: |
            az webapp config container set $@
```

**Comment by ramiMSFT** [comment]
Investigating
