### ISSUE TITLE
Upgrade pipelines-xamarin to use a vmImage for vs2019

### ISSUE THREAD

**Issue by DamianSuess** [MicrosoftDocs/azure-devops-docs#9792]
As a developer, I would like to use the latest Pipelines toolset for compatibility with projects. Currently, the [pipelines-xamarin](https://github.com/MicrosoftDocs/pipelines-xamarin) repo references ``vmImage: 'VS2017-Win2016'``. Please update the repo to use ``vs2019``.

For backward compatibility with WinPhone projects, a simple Tag could assist.

Thank you!
Again, great article. Keep up the great work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54533c61-9265-2908-c92d-f49285b24333
* Version Independent ID: 004ded47-21ee-94a7-51fe-2b835e124b55
* Content: [Build Xamarin apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xamarin?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/ecosystems/xamarin.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/xamarin.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
Someone should test this before altering the docs, and assuming it works, this would be a welcome update.

**Comment by steved0x** [comment]
@DamianSuess Thank you for letting us know - that repo is quite out of date, including WindowsPhone examples and I was unsuccessful to update them for VS 2019. However this sample repo for Xamarin has an up to date pipeline that uses the latest versions of the macOS and Windows agents:

https://github.com/MicrosoftDocs/pipelines-xamarin

I'm upgrading the article to use this sample and will post a note in the original repo.

**Comment by DamianSuess** [comment]
Thank you for the response, @steved0x. If possible, I'm looking forward to seeing the updated pipeline to vs2019. When I made my switch to use Pipelines this year, my project required me to use 2019 & would break on lower VS versions. Figured it would be a leg-up for others jumping into it as well. Merry Christmas & a Happy New Year to you and your team! 🎄
