### ISSUE TITLE
Instructions and screenshots for creating PAT are outdated

### ISSUE THREAD

**Issue by chk1** [MicrosoftDocs/azure-devops-docs#9793]
The instructions and screenshots listed under "Prepare permissions", "Authenticate with a personal access token (PAT)" are somewhat outdated. A few menu items have been moved and renamed, for example, in DevOps there is now a separate menu dropdown (left to the profile picture) which lists "Personal Access Tokens" so you don't have to go through the "Security" menu entry, etc.

Screenshot from the documentation:

![Screenshot from the documentation](https://user-images.githubusercontent.com/828496/101380351-ab5a7400-38b5-11eb-9f9b-957176605cbb.png)

This is what Azure DevOps looks to me right now instead, 

![Screenshot from Azure DevOps](https://user-images.githubusercontent.com/828496/101380267-9251c300-38b5-11eb-8e59-19b7d756f57f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425b68d1-4ba0-5657-4e09-f3aac361ea09
* Version Independent ID: f8044e9d-98e2-6e00-b513-a91e772b2ef8
* Content: [Deploy an Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#check-prerequisites)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
investigating

**Comment by steved0x** [comment]
I'll get these updated and it will be live today. Thank you for your feedback!
