### ISSUE TITLE
Not supported for import

### ISSUE THREAD

**Issue by StavroulaSsi** [MicrosoftDocs/azure-devops-docs#9797]
Hello,

_"TF402584: Field rule attributes "for" or "not" aren't supported.
The "for" and "not" attributes are not supported at all for any field rule **for import** to Azure DevOps Services.
Review the FIELDS and WORKFLOW sections for the presence of "for" and "not" attributes and remove them."_

Here for example, it says that these attributes are not supported **for import**. Is this only for the import, or "for" and "not" attributes are not supported **at all** in Azure DevOps Services. Is there an alternative for these attributes, that we could use after the import?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5ecc59-b30a-cb41-aa6b-7ba24fb6fa2a
* Version Independent ID: f5b6f454-7b3b-79cf-ab86-2cf0f043a660
* Content: [Resolve validation errors - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/resolve-errors?view=azure-devops)
* Content Source: [docs/organizations/settings/work/import-process/resolve-errors.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/import-process/resolve-errors.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mijacobs** [comment]
Looks like this is question seeking clarification on a specific sentence in the documentation.

**Comment by KathrynEE** [comment]
@StavroulaSsi - Thank you for your inquiry. For Hosted XML process there is no alternative solution to apply _for_ and _not_  rules. The only suggestion I have is that you [migrate your Hosted XML process to an Inherited process](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/upgrade-hosted-to-inherited?view=azure-devops). Then you can [add custom rules to work item types](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops).
