### ISSUE TITLE
document /var/run/docker.sock not usable with move to containerd

### ISSUE THREAD

**Issue by jemag** [MicrosoftDocs/azure-devops-docs#9798]
The current example for using docker in a Kubernetes cluster will not be valid for clusters 1.19+, given the the transition from docker to containerd (cannot use /var/run/docker.sock). 

It would be nice to document a new recommended approach for doing the same thing.

Here is what the kubernetes blog had to say on this:

> One thing to note: If you are relying on the underlying docker socket (/var/run/docker.sock) as part of a workflow within your cluster today, moving to a different runtime will break your ability to use it. This pattern is often called Docker in Docker. There are lots of options out there for this specific use case including things like kaniko, img, and buildah.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by haljoh** [comment]
Any update on this issue? It is marked as a Pri1 and has been open for 6 month now. If there is a workaround, please suggest
