### ISSUE TITLE
Bug? Multiple states in "Proposed" not being honored by boards

### ISSUE THREAD

**Issue by TheFragen** [MicrosoftDocs/azure-devops-docs#9802]
I have states under "Proposed" for my user stories that look like the following:  
![image](https://user-images.githubusercontent.com/3875930/101619040-048bea00-3a13-11eb-8e7f-8bbd328c1d59.png)

However, whenever I change the first column/default column on a board, only the first state is allowed to be selected.
![image](https://user-images.githubusercontent.com/3875930/101619011-fc33af00-3a12-11eb-99b9-e67006124c4d.png)

That doesn't seem intentional. Because why would you else allow adding multiple "Proposed" states if you can't map it to a board.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@TheFragen - Thank you for your query. The scenario you outline is as designed. I recommend that you move the Backlog state up in the list to have it be the first under the Proposed category. You can  then map it to the first column on the board.  The other proposed state, To Do, would then have to be mapped to another column you add to the board.

**Comment by TheFragen** [comment]
That is very confusing and undocumented. It also means, is impossible og I want two boards that don't share any columns (especially not the first).

**Comment by KathrynEE** [comment]
@TheFragen - I will augement the article to clarify the limitations. You are correct that you can't have two different boards which have different states mapped to the first column. All workflow states must be mapped to a column on a board. The only way to do what I think you want, is to create two different work item types - such as User Story 1 and User Story 2 which you assign a single Proposed workflow state, one having To Do and the other Backlog.  This might satisfy your needs, but possibly introduce other unwanted elements.
