### ISSUE TITLE
API Deprecated https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/release_uploads

### ISSUE THREAD

**Issue by Hamster-ZA** [MicrosoftDocs/azure-devops-docs#9803]
When executing this task we're receiving an error that the API is deprecated. I'm no longer able to find this task on the Marketplace. 

My AppCentre connection in Azure Devops is set to use the URL https://api.appcenter.ms/v0.1, with an API token that continues to work for other endpoints at https://openapi.appcenter.ms/ where the API is also no mention of the API being deprecated.

```
2020-12-09T10:42:38.8346015Z ##[debug]---- url: https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/release_uploads
2020-12-09T10:42:40.0202389Z ##[debug]---- "{\"code\":\"gone\",\"message\":\"This API is deprecated. Please use the latest version of the App Center CLI: https://github.com/microsoft/appcenter-cli, or if you need a custom script please use the CLI as the basis for your implementation. (Support ID: 0abbf297-3719-4e42-abb9-abff078dedeb)\"}"
2020-12-09T10:42:40.0203048Z ##[debug]---- http call status code: 410
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6643ac-ea32-1761-a7e9-0f17a3c0b8ee
* Version Independent ID: 2442af0f-3f01-a91c-a98a-29c2f32d35b9
* Content: [App Center Distribute task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/app-center-distribute?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/app-center-distribute.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/app-center-distribute.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by mijacobs** [comment]
@vijayma , can you take a look?

**Comment by knutigro** [comment]
Hi,

What is the status of this issue? We experience the same problem with the result that AppCenter uploads fail randomly when initiated from our Azure Pipeline.

**Comment by wisdeom** [comment]
Hi @Hamster-ZA [this](https://github.com/microsoft/fastlane-plugin-appcenter/issues/257) might give you an idea for this problem. If not, please let us know!
