### ISSUE TITLE
tf vc shelve command /new switch lacks documentation

### ISSUE THREAD

**Issue by EricAllen-tr** [MicrosoftDocs/azure-devops-docs#9807]
From a Visual Studio 2019 Command Prompt, `tf vc help shelve` yields the following, modulo some leading whitespace I'm having trouble quoting:
> Microsoft (R) TF - Team Foundation Version Control Tool, Version 16.168.30802.1
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Stores a set of pending changes, together with pending check-in notes,
> a comment, and a list of associated work items, on the Azure DevOps server
> without actually checking them into version control.
> 
> tf vc shelve [/replace] [/comment:("comment"|@commentfile)]
>              [shelvesetname] [/validate] [/noprompt]
>              [/login:username,[password]] [/new]
> 
> tf vc shelve [/move] [/replace] [/comment:("comment"|@commentfile)] [/recursive]
>              [shelvesetname] itemspec [/validate] [/noprompt]
>              [/login:username,[password]] [/new]
> 
> tf vc shelve /delete shelvesetname[;owner]
>              [/login:username,[password]]
>              [/collection:TeamProjectCollectionUrl]

Issuing `tf vc msdn shelve` takes me to a VS2010 version of the page. Neither that version nor the current version of the page (from which this feedback was opened) documents the `/new` switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed77c8e7-a49f-49ec-d6a7-a7126b1b735e
* Version Independent ID: c3182da0-511d-9a5f-e8c3-b4e2bbbbb058
* Content: [Shelve Command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/shelve-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/shelve-command.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/shelve-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **v-maksim**

**Comment by aaronhallberg** [comment]
yep, good call. the **/new** parameter functions the same way for the shelve command that it does for the [checkin](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/checkin-command) command. Without it, saved metadata will be populated in the shelve dialog - the changes to include, the comment, associated work items, and so forth. With it, all that will be ignored and the dialog will pop open empty of previous context.
