### ISSUE TITLE
Use Variables in Content

### ISSUE THREAD

**Issue by alfkonee** [MicrosoftDocs/azure-devops-docs#9809]
Is it Possible to Use Variables in the Content Section of the CopyFiles Task?? I'm asking cus I don't see any usage Examples where it being used?? 

Also I'm trying to copy a secure file with the Variable Name but it seems not to be working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Yes, that's possible. We'll add an example.

(This is not supposed to be an unhelpful comment for you 😁 We're currently running a doc-a-thon where product group folks are leaving enough info for the writers to come along behind us and actually fix the docs.)
