### ISSUE TITLE
Master still being used in documentation

### ISSUE THREAD

**Issue by devedse** [MicrosoftDocs/azure-devops-docs#9810]
I recently started a new DevOps project and tried the samples from the Schedules builds page. However none of them worked. After strugling with this for about an hour or so I finally found out that the master branch has been changed to main.

It might be good to either put this down in the documentation somewhere or simply change it to main. (If we simply change it to main people are going to run into this just like me though).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Investigating

**Comment by mijacobs** [comment]
I updated the article to use "main." Note that we'll be updated all of our articles to use "main."
