### ISSUE TITLE
Add 'Delete All' functionality as one click btn for Recycle Bin

### ISSUE THREAD

**Issue by vvoinov** [MicrosoftDocs/azure-devops-docs#9812]
The only way to clean up Recycle Bin of a feed is to use API which not very user-friendly. Would be great if there was an explicit functionality to remove all artifacts from Recycle Bin with one btn click.

**Comment by mijacobs** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
