### ISSUE TITLE
Instructions for private repos not working

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9814]
They are not working. Already over 6 months these instructions changed few times, still none of them working.

Issuing
```
josem@rabbit:~$ go get dev.azure.com/myorg/myproject/myrepo.git@1073
```
Says:
```
go: downloading dev.azure.com/myorg/myproject/pulsaradapter.git v0.0.0-20201211023249-f2b661c7768f
go get dev.azure.com/myorg/myproject/pulsaradapter.git@1073: dev.azure.com/myorg/myproject/pulsaradapter.git@v0.0.0-20201211023249-f2b661c7768f: verifying module: dev.azure.com/myorg/myproject/pulsaradapter.git@v0.0.0-20201211023249-f2b661c7768f: reading https://sum.golang.org/lookup/dev.azure.com/myorg/!myproject/pulsaradapter.git@v0.0.0-20201211023249-f2b661c7768f: 410 Gone
        server response:
        not found: dev.azure.com/myorg/myproject/pulsaradapter.git@v0.0.0-20201211023249-f2b661c7768f: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/2af3f2ae10b32b5e53fd191e041fc1e3751ac7b215c92b3d0b823915f73813be: exit status 128:
                fatal: unable to connect to dev.azure.com:
                dev.azure.com[0: 13.107.42.20]: errno=Connection refused
                dev.azure.com[1: 2620:1ec:21::20]: errno=Connection refused

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by JoseFMP** [comment]
I got to solve it. 

Really, you **MUST** add to the instructions that `GOPRIVATE` environment variable has to contain `dev.azure.com` otherwise go will keep trying to check the checksums and you won't ever be able to install the packages. This is not obvious as this page intends to be quite comprehensive but without this you cannot success.

**Comment by vtbassmatt** [comment]
Thank you for persevering! We'll get your learnings captured in the docs so others don't have to struggle as hard. (Our Go experts, who helped us with the initial write-up, have all moved on to other places.)

**Comment by vtbassmatt** [comment]
@juliakm is this in your area?

**Comment by vtbassmatt** [comment]
Oh, sorry, this might be @steved0x

**Comment by steved0x** [comment]
investigating
