### ISSUE TITLE
What are we supposed to write in <user> ?

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9817]
Private repos with HTTPS: What are we supposed to replace the particle `<user>` with. Is nowhere specified and without it the solution cannot work . Is not obvious what should be in there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
Good find, I think `<user>` can be replaced with any non-empty string. This doc should say so!
