### ISSUE TITLE
Permissions for validation

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/azure-devops-docs#9819]
The documentation doesn't state what permissions a user needs to approve validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by msebolt** [comment]
@raiyan I cannot seem to find this GitHub alias for your assignment.  Please address this documentation concern.

Including @thoms23

**Comment by TimShererWithAquent** [comment]
@pulkitaggarwl or @Moutasema should one of you be assigned this?

**Comment by Josh-01** [comment]
User needs 'Queue Build' permission to resume/reject the validation.

**Comment by GaTechThomas** [comment]
We have users who have 'Queue Build' permission but are unable to resume/reject the validation. Are additional permissions needed?

**Comment by Josh-01** [comment]
Hi @GaTechThomas ,
`Queue Builds` permission on the pipeline should be good enough for those buttons to work. Could you please share screenshots of permissions of one such user and what the button looks like in the manual validation screen ? - I will try and debug based on that.

**Comment by GaTechThomas** [comment]
Solved it today!

Any pipeline job that has a manual validation task and references a repository in a different ADO project will run into this issue for any users who are not Readers of that second project.

Specifically for us, the issue shows up after the user clicks the manual validation's Review button in the pipeline run. The Reject/Resume popup dialog pops up but is completely blank. The browser's F12 dev tools console tab shows error:

`ContributionData unavailable for 'ms.vss-build-web.checks-panel-data-provider', ExceptionType: 'ProjectDoesNotExistWithNameException', Reason: TF200016: The following project does not exist: {_guid redacted_}. Verify that the name of the project exists on the specified Azure DefOps Server., StackTrace: null`
