### ISSUE TITLE
ref/heads/master should be renamed to ref/heads/main

### ISSUE THREAD

**Issue by SeverinFriede** [MicrosoftDocs/azure-devops-docs#9820]
variable is called isMain but branch name is still master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?WT.mc_id=ITOpsTalk-blog-nepeters&view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by vtbassmatt** [comment]
As suggested.

**Comment by mijacobs** [comment]
Looks like @juliakm
