### ISSUE TITLE
Why isn't PublishCodeCoverageResults@2 (Two) supported on windows-latest devops agents?

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-devops-docs#9821]
Why isn't PublishCodeCoverageResults@2 (Two) supported on windows-latest devops agents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by vtbassmatt** [comment]
Thank you for your feedback. We are closing this issue as the Publish Code Coverage task is expected to work on Windows agents. If you find that it doesn't, please file an issue on [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by drdamour** [comment]
@mikeblakeuk did u end up opening an issue?
