### ISSUE TITLE
Document that FileTransform may not do what one thinks...

### ISSUE THREAD

**Issue by andersthorsen** [MicrosoftDocs/azure-devops-docs#9822]
[Enter feedback here]

After trying to use this task to set a variable inside a .json file I found this case
ref https://github.com/microsoft/azure-pipelines-tasks/issues/12089 which indicate that the task is limited to web application packages.

Please make it 100% clear that this task is only intended for web packages so that others do not waste time trying to make use of it to like.. transform standalone files 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by vtbassmatt** [comment]
This seems like a good update.
