### ISSUE TITLE
Add link or info about service principle, associating principle with pipeline

### ISSUE THREAD

**Issue by dirksteele** [MicrosoftDocs/azure-devops-docs#9823]
I have stepped through the tutorial three times with the hopes that I just missed a part but each time I run into a couple of challenges with the presentation:

1. No where in the tutorial do you instruct the reader on how to create a service principle or even that a service principle is required.  You imply that information but for a tutorial you should absolutely address all requirements.
2. The article never instructs the reader to associate the service principle with the pipeline.  simply creating a azure key vault task does not do that.

Having extensive knowledge of a subject does now make one a teacher.  I would encourage all authors to actually test a tutorial on a sample *target* audience prior to publishing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5346b3b-4c62-c343-4b02-92cd891395d8
* Version Independent ID: 8ff89836-ebf2-7a58-542e-c5d91ff38df6
* Content: [Using secrets from Azure Key Vault in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-key-vault.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@dirksteele Thank you for your feedback! The article has been updated and will go live shortly.
