### ISSUE TITLE
Cannot "View YAML" in a task group when migrating from classic to YAML

### ISSUE THREAD

**Issue by yikei** [MicrosoftDocs/azure-devops-docs#9824]
Seems like ever since the "View YAML" feature got moved from the editor UI to "Export to YAML" the Runs page, there is no way to do "View YAML" for task groups anymore.

When I choose "Export to YAML" on a pipeline runs page, the YAML file completely omits all task groups. And when I try to "View YAML" in a task group (in order to manually convert it to a YAML template), I get a dialog with the warning message `View YAML has a new home. To use the new feature, click the '...' menu on the Runs page and choose 'Export YAML'.` This is counterproductive when migrating from classic to YAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36333c89-6223-73cb-ce45-6fbb2638722e
* Version Independent ID: 286b8f96-6374-fedd-8d8d-a37fa5e1948e
* Content: [Migrate from Classic to YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/migrate/from-classic-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/migrate/from-classic-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-migrate**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by yikei** [comment]
After some searching, I realized the same issue was brought up here: https://developercommunity.visualstudio.com/content/problem/1278001/view-yaml-doesnt-work-for-releases.html

**Comment by vtbassmatt** [comment]
Thank you for the feedback. We're tracking this as a bug in the product, as task groups are supposed to be exported correctly.
