### ISSUE TITLE
[PublishBuildArtifact] Merge behavior for existing artifact container not documented

### ISSUE THREAD

**Issue by kevinhartman** [MicrosoftDocs/azure-devops-docs#9829]
If an artifact container with name `artifactName` already exists, `PublishBuildArtifact` will happily merge the contents into the same container. This behavior is **VERY** useful when multiple build jobs need to upload artifacts to the same container (e.g. in a build matrix).

This is loosely alluded to [here](https://developercommunity.visualstudio.com/solutions/495954/view.html), but it'd be really nice if it were documented. 

Note that Publish**Pipeline**Artifact does NOT have this behavior, and instead will fail on an existing container name. If this task is meant to replace `PublishBuildArtifact`, we should open an issue to add a parameter to it that provides the merge behavior. Tagging @mitchdenny based on the discussion [here](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2341).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by mitchdenny** [comment]
Hey @kevinhartman, I'm not working on Pipeline Artifacts / Azure DevOps anymore. But I'm sure someone else on the team will pick this up. At one point there was a plan to allow mutable artifacts with a more explicit model for when to seal an artifact. But at this point I don't think that will be implemented.

**Comment by rmarinho** [comment]
I would like to see this feature on Pipeline artifacts too

**Comment by RealOrko** [comment]
Shame this is not possible, after seeing all the glory of a matrix build working only to get to the end and realise artifacts not being mergable defeats the point of using a matrix in the first place, because then you have to hard code your matrix values twice in your pipeline, once for the matrix itself, then again in a linear merge artifacts job. Having this feature would really help alot!

**Comment by WilliamAntonRohm** [comment]
@rmarinho, @RealOrko -- Rui, Orko, thank you for your follow-up and suggestions.  Please add them here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
