### ISSUE TITLE
YAML Pipeline - Azure Policy Check Gate

### ISSUE THREAD

**Issue by vicperdana** [MicrosoftDocs/azure-devops-docs#9830]
Hi,

Is there a roadmap item to build to enable this feature in the multi-stage YAML pipeline.  I can only see associated docs for Release pipeline. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ee66118-f546-a26a-601f-b1f35ffba329
* Version Independent ID: c7c5d91e-2ee1-79e1-b5fd-2846dc9fd308
* Content: [Azure Policy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-policy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-policy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-policy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Hi @vicperdana ,

For info about upcoming features, please check our community forums: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). We general don't document product plans here.
