### ISSUE TITLE
Not available for on premise?

### ISSUE THREAD

**Issue by tacerra** [MicrosoftDocs/azure-devops-docs#9833]
The documentation shows this task is available in Azure DevOps Server 2020 but we do not see it. Is the documentation wrong? Also can't find this in the market place. Really need this since Manual Intervention task isn't supported in yaml pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops-2020&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by warder** [comment]
Any update for this issue?

**Comment by ChristianGottinger** [comment]
Looks like a bug in documentation - at least in feature timeline its marked for future release https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline#current-features.

**Comment by milbrandt** [comment]
Are you sure that _Manual Validation for YAML pipelines_ is the task _Manual Validation_ and not the validation of the YAML file as it is available in Azure DevOps Services pipelines in the UI?

**Comment by ChristianGottinger** [comment]
No I am not sure. You might be right.

**Comment by TimShererWithAquent** [comment]
@ChristianGottinger @milbrandt 

This has been in the queue for a while. I'm going to assign it to somebody so it doesn't get lost.

**Comment by raiyanalam** [comment]
Adding @pulkitaggarwl  to take this forward as i am not looking into this area currently.

**Comment by TimShererWithAquent** [comment]
@raiyanalam Thanks for assigning this. I'm digging through a backlog. Should I assign directly to @pulkitaggarwl in the future? I think you might be on a couple more of these.

**Comment by raiyanalam** [comment]
I have transitioned to another team and do not have the latest ownership updates here.  I will leave it to @pulkitaggarwl to suggest the right name for assigning future issues.

**Comment by ammohant** [comment]
@pulkitaggarwl  - Can we discuss the plan on this one ?

**Comment by ammohant** [comment]
We are in the process of validating this for on-prem. It should be available in the next release of the on-prem post Server2020.1.

**Comment by ammohant** [comment]
We are in the process of validating this for on-prem. It should be available in the next release of the onprem post Server2020.1
