### ISSUE TITLE
Migration guide doesn't link to newest api version

### ISSUE THREAD

**Issue by michnATmicrosoft** [MicrosoftDocs/azure-devops-docs#9838]
It links REST based api version 5.0 instead of the current 6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b7b4c9-f4f2-2c61-5a8a-2fbda5c394f7
* Version Independent ID: 1cd64ef7-5431-d783-150a-22c05bc54466
* Content: [WIT Client OM to REST Migration Guide - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/migration-guide?view=azure-devops#support)
* Content Source: [docs/integrate/concepts/migration-guide.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/migration-guide.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@KathrynEE All the links go to version 5 and are marked to preserve version. Was this intended?

**Comment by chcomley** [comment]
Hi @michnATmicrosoft, Thanks for the heads up! I've created a user story for my backlog to address this. This issue will automatically close once it's live. Thanks again!
