### ISSUE TITLE
Provide values for sevenZipCompression

### ISSUE THREAD

**Issue by paulomf** [MicrosoftDocs/azure-devops-docs#9847]
The possible values for the argument sevenZipCompression should be listed.

The stated default value is '5', which suggests that the reader should use a number between 1-9.
However, after reading [this blog post](https://blog.madd0.com/2020/01/30/7-zip-compression-levels-in-azure-devops-archive-files-task/) I realized that the values that should be used are instead _none, fastest, fast, normal, maximum_ or _ultra_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add63018-4f2c-f258-76ea-9f76aa43ff09
* Version Independent ID: c71f17c9-9a78-396e-7a0f-ad8b52b01724
* Content: [Archive Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/archive-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/archive-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I'm no longer working on Azure DevOps.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/archive-files-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
