### ISSUE TITLE
Missing requirements for build numbers

### ISSUE THREAD

**Issue by peterdrier** [MicrosoftDocs/azure-devops-docs#9850]
(I received an error from violating these rules, which weren't listed on this page.. so...)

Page should include the requirements for run(build) number..  Namely:

* The maximum length of a build number is 255 characters. 
* Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'. 
* Run (Build) number can not end with '.'

-Peter

Error I received was: The build number format string $(versionNumber) generated a build number 0.2.24. which contains invalid character(s), is too long, or ends with '.'. The maximum length of a build number is 255 characters. Characters which are not allowed include '"', '/', ':', '<', '>', '\', '|', '?', '@', and '*'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by steved0x** [comment]
#reassign steved0x

**Comment by juliakm** [comment]
Assigning to @steved0x because he's working on naming conventions.

**Comment by juliakm** [comment]
Thanks @peterdrier! We had the 255 character one documented but not the additional requirements. I'll update now.
