### ISSUE TITLE
azure-feed:// URI format

### ISSUE THREAD

**Issue by StenPetrov** [MicrosoftDocs/azure-devops-docs#9852]
Connecting an upstream package source from another org requires cooking up an URI of this kind:
azure-feed://<organization/<feed>@<view>

It is not very clear how to find the values for <organization>, <feed> and <view>.
I can browse the Artifacts of the org and the feed that contains the package. From there I can see a dropdown "View" where I can select "@Local" (so <view>="Local") and the feed name is in another drop-down, so I guess that's where the <feed> value would come from, but it's still not clear how to find the <organization> value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by ramiMSFT** [comment]
@StenPetrov Thank you for reaching out. The feed locator is the `azure-feed://` prefix, followed by the organization name, project name, feed name, and your shared view. e.g. `azure-feed://myOrg/myProject/myFeed@local`
