### ISSUE TITLE
Stage status check documentation

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#9854]
This document needs stage status check documentation similar to job one.

I suspect there is a bug, or some undocumented behaviour I cannot gasp on.

In example when stage condition for sign is set, so it will happen on main branch only
```
  - stage: Sign
    condition: eq(variables['Build.SourceBranchName'], 'main')
    jobs:
      - template: sign.yml
```
with all other stages having no conditions:
![opera_IhNZMDL1iB](https://user-images.githubusercontent.com/10334982/102636737-f0e82e00-414c-11eb-990d-bc3d99955e4c.png)

when I additionally set Test stage to 
```
  - stage: Test
    condition: succeeded('Build')
    jobs:
      - template: test.yml
```
![opera_AGHQzuxa9i](https://user-images.githubusercontent.com/10334982/102636869-183efb00-414d-11eb-9a35-f457b6e254cc.png)

It looks like condition on one stage impacts whole pipeline by default. 

My current workaround is to use expressions instead:
```
  - stage: Sign
    ? ${{ if eq(variables['Build.SourceBranchName'], 'main') }}
    : displayName: Sign
    ? ${{ if neq(variables['Build.SourceBranchName'], 'main') }}
    : displayName: Sign - Skipped
    jobs:
      - ? ${{ if eq(variables['Build.SourceBranchName'], 'main') }}
        : - template: sign.yml
      - ? ${{ if neq(variables['Build.SourceBranchName'], 'main') }}
        : - job: Skipped
            steps:
              - checkout: none
```

The only mention of this problem is perhaps at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#ive-got-a-conditional-step-that-runs-even-when-a-job-is-canceled-how-do-i-manage-to-cancel-all-jobs-at-once

Perhaps its because Skipped is separate result to SucceededWithIssues (called 'partially succeeded' at  https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#succeeded)

There is also problem with dependencies along conditions, in above examples, if branch is not main, run pipeline will throw exception:
```
Stage Test depends on unknown stage Sign.
Stage Package depends on stage Test which creates a cycle in the dependency graph.
```
possibly because if stage is skipped it does not populate dependency matrix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#job-status-functions)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I don't think that we have Stage status check functions that work like Job status functions. I'm checking with the product team on this.

**Comment by juliakm** [comment]
I've confirmed that there are not stage status check functions. If you'd like to request stage status check functions as a feature, you can request a feature in our [Developer Community](https://developercommunity.visualstudio.com/search?space=21). It does seem like stage status checks would be a useful feature!

**Comment by quasarea** [comment]
If there are no stage status function checks, how you can explain above behaviour? If stage has condition, why all follow up stages get skipped when condition is not met?
