### ISSUE TITLE
Missing documentation that `stageDependencies` variables require an explicit stage dependency

### ISSUE THREAD

**Issue by c-ryan-k** [MicrosoftDocs/azure-devops-docs#9856]
With three stages:
```
stages:
- stage: build

- stage: test
  dependsOn: build
  
- stage: release
  dependsOn: test
```

If `release` contains a reference to an output stage variable defined in `build`, such as:
`$[ stageDependencies.build.job.outputs['step.var'] ]`
 the `release` stage needs an explicit `dependsOn: build` property, otherwise the values will resolve to null.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by c-ryan-k** [comment]
🙃 

Feel free to close this because I just found a note here:
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-168-update#jobs-can-access-output-variables-from-previous-stages

But perhaps it could be added where I was looking, which was here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage

**Comment by juliakm** [comment]
Closing because there is more `stageDependencies` documentation now on the [Expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies) and [Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables) pages.
