### ISSUE TITLE
Information is out of date

### ISSUE THREAD

**Issue by Danavell** [MicrosoftDocs/azure-devops-docs#9861]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f717dae-91b5-276f-2f87-4b98331fb303
* Version Independent ID: e6e9d3b1-c00d-24d2-5667-58b4822df718
* Content: [Change Azure subscription used for billing - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-azure-subscription?view=azure-devops)
* Content Source: [docs/organizations/billing/change-azure-subscription.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/change-azure-subscription.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@Danavell Hi James - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, can you provide us with more specifics about the issue?
