### ISSUE TITLE
Ballal 

### ISSUE THREAD

**Issue by ballalh** [MicrosoftDocs/azure-devops-docs#9866]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@ballalh Please add comments below if there are any further issues.
