### ISSUE TITLE
Agile and Scrum Board images are the same

### ISSUE THREAD

**Issue by rmiguelac** [MicrosoftDocs/azure-devops-docs#9868]
Hi,

When in the page [azure boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops&tabs=scrum-process ) and looking for how board shows the different states for the workflow, both Agile and Scrum show the same board image (from Agile), which can lead to people assuming that Active, Resolved and Closed are the workflow states for Scrum, when in fact it should be Approved, Commited and Done. Like below image 

![image](https://user-images.githubusercontent.com/24905075/102722020-042a0380-42dd-11eb-8643-76b5b0a9264c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b4734-b75e-95c3-73d2-78216e166bf1
* Version Independent ID: e4404510-ff79-aabf-1214-1d1ccb968aba
* Content: [Understand what you get with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/get-started/what-is-azure-boards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/get-started/what-is-azure-boards.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@rmiguelac - Thank you for the feedback. YOu are correct, the image needs to be updated. I will add that work to my backlog.
