### ISSUE TITLE
Permission for Deleting Test artifacts

### ISSUE THREAD

**Issue by chriswhitts** [MicrosoftDocs/azure-devops-docs#9869]
This page describes that you must have the Delete Test artifacts permission to delete test cases. This link then goes to a page which only mentions a "Manage Test plans" permission (doesn't mention the word Delete)... confusing.

On top of that I have a user who I have explicitly given this permission (Manage Test cases and Manage Test suites) and they cannot delete a test case (no delete option appears). If I make them a Project Administrator they can... any ideas as this is not desirable to make them an Admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93c8b9-8f57-5ee7-cf6f-a81644bd962b
* Version Independent ID: bcc7bdf0-7f4d-b22d-083e-0721565efce3
* Content: [Delete test plans, cases, & other test artifacts - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/delete-test-artifacts?view=azure-devops)
* Content Source: [docs/boards/backlogs/delete-test-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/delete-test-artifacts.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chriswhitts - Thank you for your inquiry. I will review the article to clarify better.  Test cases, test suites, test plans, and shared steps are all work item types. Please check the permission settings for the user at the project level. To delete the test cases, they need to have the **Delete and restore work items** permission set to allow. 

![image](https://user-images.githubusercontent.com/10856840/102822367-bd481680-438d-11eb-96ca-59c872e3b239.png)

**Comment by KathrynEE** [comment]
@chriswhitts - Apologies for the delay in follow up. I will update the article to point to the Delete test runs permission that you set at the Project level. 

![image](https://user-images.githubusercontent.com/10856840/110854838-66562d00-826a-11eb-9c8d-26fc96db0f99.png)
