### ISSUE TITLE
Formatting commands: Code and image to do not match 

### ISSUE THREAD

**Issue by pefoo** [MicrosoftDocs/azure-devops-docs#9870]
The provided code and sample output do not match

![image](https://user-images.githubusercontent.com/12524622/102789329-436f5780-43a4-11eb-8ed1-926771d4d730.png)

1. Output text does not match 
1. The is no code example given for the section type but it is present in the sample output 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by pacorreia** [comment]
Also the group tag is not working at least for powershell.

This needs to be updated

**Comment by TimShererWithAquent** [comment]
Currently, the syntax block includes Start of a section line, but the output no longer does.

**Comment by juliakm** [comment]
Adding a new screenshot.
