### ISSUE TITLE
api azure

### ISSUE THREAD

**Issue by amrunkhakim** [MicrosoftDocs/azure-devops-docs#9874]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84af2b0f-cd64-018f-585f-70d17f393f85
* Version Independent ID: 8b25aa9b-95b8-14d3-0348-8d8ffd6d2843
* Content: [REST API versioning for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops)
* Content Source: [docs/integrate/concepts/rest-api-versioning.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/concepts/rest-api-versioning.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@amrunkhakim If there are any issues and/or concerns with the documentation, please add comments below.
