### ISSUE TITLE
Link work items to deployments has missing information about manual triggering or CI/CD integration

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/azure-devops-docs#9879]
[Enter feedback here]
Link work items to deployments has missing information about manual triggering or CI/CD integration. Basically, when the release pipeline is not triggered automatically, the release link is missing.

![image](https://user-images.githubusercontent.com/35690646/102882321-81c15100-444e-11eb-9ad8-12e34cf4a5da.png)
![image](https://user-images.githubusercontent.com/35690646/102882395-9dc4f280-444e-11eb-8855-4ddad18476d3.png)
![image](https://user-images.githubusercontent.com/35690646/102882559-d238ae80-444e-11eb-8456-2612648ea0da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jimicze - Thank you for your feedback. I've updated the article and am waiting on the product manager to clarify some open questions. I'll close this issue once I get a response from him.
