### ISSUE TITLE
docs should explicitly say that "squash merge" is really a rebase with squash

### ISSUE THREAD

**Issue by marcinjahn** [MicrosoftDocs/azure-devops-docs#9880]
[Enter feedback here]
The document describes squash merge, however it avoids saying that it is really an interactive rebase with squash of commits into one.

I think the term "squash merge" is a bit confusing, and people might not know that it is a rebase. Personally, I thought it's something completely different when I saw the option in DevOps repo, I didn't think it'd do a rebase onto the target branch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dec464-f25a-5c46-52e7-2cbf17a2db1d
* Version Independent ID: bbe4d6d1-71a7-0c47-7bfb-1577760e003b
* Content: [Squash merge your pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/merging-with-squash.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by Voxis** [comment]
Yes, this is really it. 

And we don't have a real squash merge that creates the squashed source branch and actually merge into the target branch! So it still have the history of the branch. making adding additional changes easier and more traceable. This is also an option what we need.
