### ISSUE TITLE
Windows container sample is desperately requiered

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-devops-docs#9886]
Everything is simple with Linux.
For windows, it is not, even installing bash is not as simple.
So, the article desperately requires a windows sample for the minimum container that could be used in the pipelines.
Ideally, a bit more advanced container sample that will be at least able to build .NET/C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @yahorsi. I've added updating the examples for this article to our backlog.
