### ISSUE TITLE
Reference to Obsolete Version of Node.js

### ISSUE THREAD

**Issue by stuartellis** [MicrosoftDocs/azure-devops-docs#9894]
This section specifies Node.js version 6, which is obsolete:

https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases?view=azure-devops#bring-your-own-nodejs

The text reads:

"Node 6 is a safe choice. You can start from the node:6-alpine image."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases?view=azure-devops)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks @stuartellis. This has since been updated.
