### ISSUE TITLE
Important information missing: How to do "go get" from Azure DevOps pipelines

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9895]
I gave a lot of feedback on this page during last months, and I would like still to add a really important one.

Why isn't there any mention at all on how to use "go get" from Azure DevOps pipelines? After having used the documentation in this page and successfully have set-up multiple go packages in multiple Azure DevOps repositories, and being able to do "go get" locally successfully, I am facing a real nightmare to do the same from an Azure DevOps pipeline.

Since "Azure DevOps repositories" and "Azure DevOps Pipelines" are parts of the same product, I'd expect as an user (and customer paying for Azure DevOps) to have at least a hint on how I can set-up the same in an Azure DevOps pipeline.

We are in the era of CI/CD. This documentation only talks about how to set-up git in a general fashion that one can apply locally but I can confirm trying to do the same in an Azure DevOps Pipeline is far from obvious. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by martinostvik** [comment]
I got this to work locally, but also struggling with an implementation from Azure Pipelines.
Updated documentation on this issue would be much appreciated.

**Comment by fasmat** [comment]
Bump. Almost a year later and still no feedback or updated documentation?
