### ISSUE TITLE
Include child work items option is not available when copying & cloning a work item.

### ISSUE THREAD

**Issue by hwoodward2019** [MicrosoftDocs/azure-devops-docs#9900]
When attempting to Copy or clone a work item, the "Include child work items" option is not availiable

The other two are though. 

Permissions are set.

What am I missing?
![image](https://user-images.githubusercontent.com/55882760/103348881-53083380-4a69-11eb-9c97-643a7593b47d.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa195a89-e867-a1a2-b217-7897eaf658cc
* Version Independent ID: dbca0b38-fbd2-0e97-5494-b7303b4b3f4b
* Content: [Copy or clone stories, issues, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-clone-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/copy-clone-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/copy-clone-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@hwoodward2019 - Thank you for your inquiry. This feature is available for the cloud service only at this time. Is it possible that you are working from an on-premises server?

**Comment by hwoodward2019** [comment]
That is exactly why! We are do utilize an on-premises server.

Do you know if and when this may be come available for on-prem?

**Comment by KathrynEE** [comment]
@hwoodward2019 - Features are typically added to the next version of the on-premises server. Feature timeline is here: https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline. The **Copy work item to copy children** feature doesn't have a specific release version listed at this time.  The Release Candidate (RC) for 2020.1 is targeted for 2/23. So, it may make that release date but I can't say for sure.  

FYI - there is a content version selector at the top of the TOC which you can select to see the content specific to your on-prem version.
