### ISSUE TITLE
Guidance refers to a line chart not a table

### ISSUE THREAD

**Issue by nbrown02** [MicrosoftDocs/azure-devops-docs#9901]
The steps to reproduce this chart need to be fixed, currently this refers to a line chart not a table visualization...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e20a235d-a4fa-a1a7-77ad-97232b5cb5a0
* Version Independent ID: af480a85-ea5c-4395-0102-cbb4370a8f60
* Content: [Pipeline task duration sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-pipelines-task-duration?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-pipelines-task-duration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-pipelines-task-duration.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaghai**

**Comment by KathrynEE** [comment]
@nbrown02 - Thank you for your feedback. Apologies for the delay. Article is getting updated today to reflect the correct chart image.
