### ISSUE TITLE
Resource requirements for Analytics Service

### ISSUE THREAD

**Issue by ppejovic** [MicrosoftDocs/azure-devops-docs#9903]
It's not possible to find any details on the application tier or data tier hardware/resource requirements for enabling the analytics service. Do the hardware requirements outlined for an initial Azure DevOps setup/install still apply or are there additional requirements? 

At this point in time I'm left having to do some before/after comparisons after enabling the service in our UAT environment with a cut of production data. We see about 8% growth of our collection database size after enabling the service. Whilst I appreciate this could vary widely from install to install, guidelines on data usage and some information on how the service operates at an implementation level would be useful for making decisions about provisioning the necessary hardware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f48d-32a7-5976-f585-902d28d7dc1c
* Version Independent ID: b207b4f0-23b7-33b0-ab44-59b2c6546cd8
* Content: [Install or enable Analytics on Azure DevOps Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/analytics-extension?view=azure-devops-2019)
* Content Source: [docs/report/dashboards/analytics-extension.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/analytics-extension.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@ppejovic - Thank you for your inquiry and apologies for the delay in response. We don't have any documentation about hardware requirements for the Analytics service and no plans to provide. I recommend you post this issue on our [Developer community page](https://developercommunity.visualstudio.com/search?space=22).
