### ISSUE TITLE
more information about service connection/authentication with ACR

### ISSUE THREAD

**Issue by lissff** [MicrosoftDocs/azure-devops-docs#9908]
[Enter feedback here]

seems there is no description at all for how to config authenticating with ACR, e.g.
if we choose Azure Container Registry as connection type, then there will be service principal created by DevOps to authenticate with ACR; and this step requires the DevOps initiator have subscription level ownership, otherwise connection would fail;

If we choose Others and using ACR admin/password, or existing identity/password, then it will function as expected.

but unfortunately, none of them are mentioned in this documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ba2ebe-27c4-111b-18b4-0192d8c3fb3a
* Version Independent ID: f48fdf00-e04f-b406-93f3-20b7fad568be
* Content: [Build and push to Azure Container Registry - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/containers/acr-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/containers/acr-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by ramiMSFT** [comment]
@lissff Thank you for your feedback! the update will go live shorty.  I will be revisiting this one for a more focused audit in the near future.
