### ISSUE TITLE
Description of "Don't sync sources" is imprecise and unclear

### ISSUE THREAD

**Issue by dtarditi** [MicrosoftDocs/azure-devops-docs#9913]
[Enter feedback here]

The description of the "Don't sync sources" option on this page is imprecise and unclear.  Please look at the feedback that I provided for a similar section in another page in issue #9912.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
I'm going to mark this one as duplicate on MicrosoftDocs/azure-devops-docs/issues/9912, since that one seems to have all the details. Let me know if the current one still needs to be open.

**Comment by TimShererWithAquent** [comment]
Just realized these were two different articles.
