### ISSUE TITLE
Documentation for Azure Devops Approval and Check, missing and misleading

### ISSUE THREAD

**Issue by gianlucagravina** [MicrosoftDocs/azure-devops-docs#9917]
I am trying to configure a deployment check to allow me to poll a HTTP Endpoint in my pipeline. To do so, I have created an environment and I am trying to define the parameters needed to properly configure it.

![image](https://user-images.githubusercontent.com/55887306/103532488-4ac75280-4ec6-11eb-9e01-ad5a7a87335c.png)

The documentation seems to be incomplete and/or missing. clicking on the info button (i) close to success criteria brings here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml that seems not the right place.
Even searching the entire documentation site I cannot search a proper set of pages with the entire process described for creating and using  Rest Api Invoke to gate a specific pipeline.

**Comment by msebolt** [comment]
@gianlucagravina Thank you for the feedback, please refer to [approvals](https://docs.microsoft.com/azure/devops/pipelines/release/approvals) for additional guidance.

Product-related documentation links are unfortunately outside the scope of changes we can provide to the content.

To solicit feedback from the product team, we recommend using **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and providing a link back to this issue.

Or, for additional support options, refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
