### ISSUE TITLE
Is there a corresponding page for tracing permissions like "Edit Build Pipeline"?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#9926]
or the other pipeline related permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6c4f97-f052-6edc-ae5c-e6774115ca16
* Version Independent ID: 691ceef1-fe38-cc6e-7d67-5ea7140222bd
* Content: [Trace permissions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/faq-trace-permissions?view=azure-devops)
* Content Source: [docs/organizations/security/faq-trace-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/faq-trace-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@StingyJack - The method is the same for tracing all permissions. IF the permission isn't set, there is no trace. If the permission is subject to tracing, there should be an info (i) icon.

**Comment by StingyJack** [comment]
The permission I am asking about specifically is not shown on the user permissions page specified in the tracing doc. I am a member of the group (Build Administrators) that has the permission "Edit Build Pipeline" explicitly set to "Allow".   

Does that mean I should see it on this user permissions page?

Actually none of the pipeline related permissions are present on that page, thats why I asked if they would be somewhere else.
