### ISSUE TITLE
How to dowload "Delivery Plans" extension for Azure DevOps Server 2020

### ISSUE THREAD

**Issue by huntantr** [MicrosoftDocs/azure-devops-docs#9940]
I would like install the Delivery Plans extension on my Azure DevOps Server 2020, but there is no option to download. When I select "Get it for free". I will only allow me add it to my cloud instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef517e1-f614-a2e5-d968-e32bdaac6183
* Version Independent ID: babf6a50-0147-74bb-0e20-b1939de397af
* Content: [Review team delivery plans - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops-2020&tabs=plans-preview)
* Content Source: [docs/boards/plans/review-team-plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/plans/review-team-plans.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@huntantr - Did you follow the instructions provided here: https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2020? If you start from your server's web portal, you should be able to install.

**Comment by huntantr** [comment]
Yes, I did. I am the admin of the server and when doing it that way, I get no option for my server, only my cloud instance. Have tried many different ways to get the extension.

**Comment by KathrynEE** [comment]
@huntantr - I apologize for the problems your having. I will see if I can research the problem further, but I suggest you post your problem on our [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by huntantr** [comment]
Thanks I will do that. I suspect it hasn't been built for Azure DevOps Server 2020. That is the only one missing from the "Works with" list.

**Comment by KathrynEE** [comment]
@huntantr - Just FYI, I just installed the extension on a test server for 2020 and it worked as expected.
