### ISSUE TITLE
Missing 'Section' formatting command

### ISSUE THREAD

**Issue by ericyew** [MicrosoftDocs/azure-devops-docs#9943]
The formatting command in this section: 
[Formatting commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell#formatting-commands)
is missing the _'section'_ command (in green)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by martin-morin** [comment]
To get the Start of a section in green the syntax needs to be:

`##[section]Start of a section`

**Comment by martin-morin** [comment]
Sent PR https://github.com/MicrosoftDocs/azure-devops-docs/pull/9949 to resolve this issue.

**Comment by juliakm** [comment]
Fixed here: https://github.com/MicrosoftDocs/azure-devops-docs/commit/4c98fa22433d0b511b5671cba4fcd71aa0120e8b
