### ISSUE TITLE
P1 and P2 you cannot ship the solution and P3 is an optional solution, is this correct?

### ISSUE THREAD

**Issue by weaveriski** [MicrosoftDocs/azure-devops-docs#9946]
[Enter feedback here]
Hi

In the priority section it reads
1: Product cannot ship without the successful resolution of the work item, and it should be addressed as soon as possible.
2: Product cannot ship without the successful resolution of the work item, but it does not need to be addressed immediately.

Are we saying you cannot ship and it is not an issue to worry about, or are we saying it can ship and there issue needs addressing?
I feel 1 is a full stop, 2 not so much and 3 just says resolving it is optional. 

If I was prioritising issues P1 is a blocker, P2 is an issue that needs resolving but might have a workaround, P3 is still an issue but not as critical as P2 and a P4 is a nice to have. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375cc9d2-c7e5-2401-0e8f-285350c04982
* Version Independent ID: 2b6cea97-59ff-af6c-33a4-7db28e03821a
* Content: [Plan & track work, Agile, Basic, Scrum, or CMMI process - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process#add-details-to-a-board-item)
* Content Source: [docs/boards/get-started/plan-track-work.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/get-started/plan-track-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@weaveriski - Thank you for your feedback. Your interpretation is correct. I will work to clarify the content. Note that no Priority setting in the work item prevents shipping - it is simply used to indicate items that are high priority and lesser priority to fix prior to shipping. Depending on your org - product can ship with Pri 3 and Pri 4 items.
