### ISSUE TITLE
How to clean the list of secure files?

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#9954]
When you add a download file, it sticks in the list FOREVER.

It means if I use the task in another pipeline, all the previously uploaded secure files appear in the list and are available to download.

Can you explain how I can clean this list and remove the files that I used in the task? Because over the months and years the list grows, + is insecure as you can not delete sensitive files + you cannot reupload a file that you had in your PC with the same name.

Please document how to clean the list of files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@JoseFMP Thanks for your question. We're looking into addressing it in documentation. 

If you think this is a good suggestion for the product, consider suggesting it [here]](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
