### ISSUE TITLE
improve documentation how to connect to github repositories of another organization

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/azure-devops-docs#9957]
https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops

> The Add GitHub Repositories dialog automatically displays and selects all GitHub.com repositories for which you are an administrator. 

It looks like this description is wrong. Only repositories from my own **xxx** (I don't know how to call this "xxx", I mean the part in https://github.com/**xxx**) are listed. If I am an administrator in projects in other organizations then these projects are _not_ listed.

I searched for this issue and there is an issue which descibes a similar issue and it looks like will not be resolved:
https://developercommunity2.visualstudio.com/t/shAzuresh-DevOps-doent-see-shGit/425527?entry=problem&space=21

If it is not possible to connect to projects in other organizations in the way which is described in the documentation then there should be a description of how to connect to projects in other organizations. (I hope there is a way to connect).

Of course, it would be much better if the list would contain all repositories where a user is an administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04afcda8-8a01-6fda-8387-778feaba9fea
* Version Independent ID: a0c518ee-dc43-42a6-07d9-150dfa8724c3
* Content: [Connect a project to a GitHub repository - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/connect-to-github?view=azure-devops)
* Content Source: [docs/boards/github/connect-to-github.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/connect-to-github.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by aisbergde** [comment]
you could add something like:

> if you want to connect to repositories in other organization you should use PAT because these repositories are not listed

**Comment by KathrynEE** [comment]
@aisbergde - Thank you for your feedback. I will be updating the article to include your suggestion within the next few weeks.
