### ISSUE TITLE
Outdated documentation / missing feature

### ISSUE THREAD

**Issue by liron-navon** [MicrosoftDocs/azure-devops-docs#9961]
Missing "Set as default branch" option, maybe the documentation is outdated?
The documentation said to click the 3 dots icon and choose "Set as default branch" but it's missing...

<img width="1354" alt="Screenshot 2021-01-11 at 09 41 52" src="https://user-images.githubusercontent.com/18119833/104160389-b85d0c80-53f9-11eb-8896-acb24ae82562.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a0b59-001c-11dd-f3f6-9d87fd25a8d4
* Version Independent ID: 85ef7fdf-447f-6330-9105-785ba31ff759
* Content: [Change the default branch - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/change-default-branch?view=azure-devops)
* Content Source: [docs/repos/git/change-default-branch.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/change-default-branch.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
That menu item only appears if you have permission to set the default branch. I don't remember off-hand which permission that is - probably "Edit policies". Just double-checked and, in a repo where I'm fully an administrator, it definitely still appears.
