### ISSUE TITLE
Page title as typo "assess" which should be "access"

### ISSUE THREAD

**Issue by dholcomb-ms** [MicrosoftDocs/azure-devops-docs#9965]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa32191d-6d0a-058f-2ffe-3ce1b58e2c59
* Version Independent ID: 858d1ed3-b2af-699f-9d51-86ac0962086b
* Content: [How permissions, assess, and security groups are managed - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-permissions?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/about-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/about-permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dholcomb-ms - Thank you for the correction. Will update the article today.
