### ISSUE TITLE
Usage of non-inclusive language in docs

### ISSUE THREAD

**Issue by chithams** [MicrosoftDocs/azure-devops-docs#9966]
I noticed that[ this page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass) makes use of the word "whitelisting". Given that this word is non-inclusive and it is a public facing doc, we should replace that with inclusive wording such as "trusted" or "approved" or "allowed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@shashban The term "whitelisted" appears in several screen captures later in the article. Since they are not in text, they didn't throw build suggestions.
