### ISSUE TITLE
VSTS.AccountContents() authentication fails with "The resource cannot be found"

### ISSUE THREAD

**Issue by dronkoff** [MicrosoftDocs/azure-devops-docs#9967]
Authentication doesn't work after publishing to Power BI workspace.

The details are on Power BI Comminity site: https://community.powerbi.com/t5/Developer/VSTS-AccountContents-authentication-fails-with-quot-The-resource/m-p/1554556#M26790

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdc5841-fa63-c6df-8b26-90f05ffb6210
* Version Independent ID: dba4d2b1-7f7f-adeb-d8f3-f25a97c10093
* Content: [Connect using Power Query & Azure DevOps functions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-functions?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-functions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/data-connector-functions.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dronkoff - Thank you for this feedback. I'm updating the article with additional information today.
