### ISSUE TITLE
Advanced migrations - Create all the SVN branches as proper Git branches

### ISSUE THREAD

**Issue by sbolt1** [MicrosoftDocs/azure-devops-docs#9968]
In the Advanced migrations section, it is not clear where the script to create all the SVN branches as proper Git branches is to be run and when it is to be run. 

I have tried running it in the new-bare.git folder at the end of the process after the tag migration script. Nothing is processed and the proper Git branches are not created.

Further clarification would be appreciated.

Here is the script that is supposed to be executed. 
git for-each-ref --format='%(refname)' refs/remotes | % { $_.Replace('refs/remotes/','') } | % { git branch "$_" "refs/remotes/$_"; git branch -r -d "$_"; }

I am also confused on the final code block. It seems that it would create and delete the same branch.
{ git branch "$_" "refs/remotes/$_"; git branch -r -d "$_"; }

**Comment by TimShererWithAquent** [comment]
@sbolt1 Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.
