### ISSUE TITLE
Incorrect requirements listed

### ISSUE THREAD

**Issue by JFolberth** [MicrosoftDocs/azure-devops-docs#9969]
resourceGroupName is listed as required however this is incorrect.

It is not required for an AzureWebApp and I have tested that it is also not required if deploying just the app settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a09e1d-5fe6-cac3-47c9-cb2f4422a473
* Version Independent ID: 4cf6d896-5421-d32f-5fca-90134ddcdfa1
* Content: [Azure App Service Settings task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-app-service-settings?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-app-service-settings.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-app-service-settings.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by JFolberth** [comment]
FYI even the example provided does not include resourceGroupName

**Comment by steved0x** [comment]
@JFolberth I believe that the Resource group parameter is used to resolve any ambiguity if there are more than 1 app service in your subscription with the same name, based on this error message in the task source: `"MultipleResourceGroupFoundForAppService": "Multiple resource group found for App Service '%s'.",`
https://github.com/microsoft/azure-pipelines-tasks/blob/9e3ea8cc7454ae5a1275cc9a1deca4481b4173b0/Tasks/AzureAppServiceSettingsV1/task.json#L154

I believe it is not required, and I am filing an issue on the GH repo for that task, and will report back when I have more information, and I am going to accept your PR now, and if I get more info I will update that task description. Thank you for letting us know.

**Comment by steved0x** [comment]
Issue filed: https://github.com/microsoft/azure-pipelines-tasks/issues/14368
