### ISSUE TITLE
'AzureFileCopy@4' Task doc, found 'sasTokenTimeOutInMinutes' but missing 'outputStorageUri' and 'outputStorageContainerSasToken'

### ISSUE THREAD

**Issue by Smoovsky** [MicrosoftDocs/azure-devops-docs#9972]
What happened to the other two parameters? Are they still available in 'AzureFileCopy@4'? If not, what's the point of keeping 'sasTokenTimeOutInMinutes' in parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
It configures the timeout for the sasToken returned in the out variables for the task:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v4?view=azure-pipelines

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v4?view=azure-pipelines#output-variables

Please check out our new task reference and let us know what you think. Thank you.
