### ISSUE TITLE
YAML Tags - additional details

### ISSUE THREAD

**Issue by abby-d** [MicrosoftDocs/azure-devops-docs#9976]
What is the purpose of YAML tags? When should or might users want to use it? What does it allow us to do? Does this provide any meaningful tagging ability or is this something different? Perhaps software engineers might understand the use case around this without explanation, but other types of users, such as myself, need more clarification. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @abby-d , Thanks so much for reaching out. I agree that this article needs an update! We'll be in touch!

**Comment by chcomley** [comment]
Adding @amitkumariiit for feedback/input. Thank you!

**Comment by chcomley** [comment]
Reassigning to @amitkumariiit, thank you.

**Comment by amitkumariiit** [comment]
Hi,
Yaml tags are used for general search engine optimisation. Our plan was to add the basic support for it first and then ingest this in the azure devops wiki search for optimise search. However we could not prioritise the search side of work.

**Comment by chcomley** [comment]
@abby-d, Please @mention us if you have any further questions, thank you!

**Comment by ScottWelker** [comment]
Just FYI: [StackOverflow: What is the value of YAML atop a page's markdown? ](https://stackoverflow.com/questions/66791439/azure-devops-wiki-what-is-the-value-of-yaml-atop-a-pages-markdown/66804730#66804730)

**Comment by goo32** [comment]
> Hi @chcomley ,
> Yaml tags are used for general search engine optimisation. Our plan was to add the basic support for it first and then ingest this in the azure devops wiki search for optimise search. However we could not prioritise the search side of work.

I'd like to see the YAML tags integrated into the wiki search at some point. I'm wondering why the YAML tag is being rendered in the web view? Typically YAML tags are treated as metadata in markdown files and should not be rendered.

**Comment by chcomley** [comment]
Hi @goo32, Please go [here](https://developercommunity.visualstudio.com/home) and submit this as a feature request and include your question. Select **Request a feature** at the bottom of the left panel. Thanks so much.
