### ISSUE TITLE
Styling not working when a sub area

### ISSUE THREAD

**Issue by KrystinaWoelkers** [MicrosoftDocs/azure-devops-docs#9978]
Hello! I feel the information on styling the cards here is a bit unclear, specifically when sub areas are inherited from the parent area - I will give an example for clarity 

I have one project, with a team that has sub areas - 
Team Overall
Team Overall\Team One
Team Overall\Team Two

The boards are set up to inherit areas - maybe that's not the proper words, but when I'm in the Team Overall area I can see all the work items for team one and team two.

The backlog board for Team Overall has four columns - New, Approved, Committed, Closed. Where as Team One Kanban's board has a lot of columns (Parking Lot - mapped to new status, Refining - mapped to new status, and so on).

However when I try to add a custom style on Team One board for the card being purple whenever the **Board Column is set to Parking Lot** - it won't even update to a color - the cards stay white. It's almost like it doesn't care what board column is set to, it more matters where the work item is on Team Overall board, and its based off of Team Overall Board columns, not the sub team board columns. 

I did a test where I changed the Team Overall board column name from "New" to "Parking Lot" - and now on Team One board anything that is in a NEW status (regardless of where its at on Team One kanban board) is now purple!

The documentation does not clearly state that you can not style **for board columns** on a sub area board. This may have been confusing, but I'd love to give more feedback. I just think the documentation should be more clear about the limitations of styling when the "parent" area is set to inherit the sub areas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6d2e51-6c3e-512a-0fcb-5141c0290663
* Version Independent ID: a25c921a-6ec4-eeed-fa93-1105d4444408
* Content: [Customize cards on a board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/customize-cards?view=azure-devops)
* Content Source: [docs/boards/boards/customize-cards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/boards/customize-cards.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@KrystinaWoelkers - Thank you for the feedback.  Two items: **First**, I think there are limitations on card styling and using the Board column field (and perhaps other Board fields). I did a test and fould that the style wasn't picked up based on the Board column. I will verify with the product team and update the article as needed. 
**Second**: Each Kanban board configuration is stand-alone and doesn't inherit configuration settings. However, if area paths are shared across teams - which is not recommended - then uncertain results can occur.  For more information, see [About Boards and Kanban, Limitations of multi-team Kanban board views](https://docs.microsoft.com/en-us/azure/devops/boards/boards/kanban-overview?view=azure-devops#limitations-of-multi-team-kanban-board-views).
