### ISSUE TITLE
need docs for reportDirectory & additionalCodeCoverageFiles params

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#9979]
docs for reportDirectory & additionalCodeCoverageFiles params is absent from this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
It looks like entries were added for these two params here:

MicrosoftDocs/azure-devops-docs/commit/c51a09a91ec568aa442db4b8539e20aa8f1d73c8#diff-31aa02661f66deb51006fcb8598c151e01cdc0e09f824d19d54736da64a02182
