### ISSUE TITLE
Cannot remove project administrators

### ISSUE THREAD

**Issue by jooyungik** [MicrosoftDocs/azure-devops-docs#9980]
[Enter feedback here]
There is no button(x).
![image](https://user-images.githubusercontent.com/53505355/104392304-2aae2800-5585-11eb-88f3-bdda57efc5da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add, remove team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@jooyungik - What version of Azure DevOps are you on? Are you sure you've nagivated to the **Team Settings page**? From the image you provide, it doesn't appear so.

**Comment by KathrynEE** [comment]
@jooyungik - Closing this for now as haven't heard back.
