### ISSUE TITLE
What is ODATA?

### ISSUE THREAD

**Issue by gitclem** [MicrosoftDocs/azure-devops-docs#9986]
There are so many things I don't know about MS S/W.  Potentially new terms should be explained.  I have no idea what ODATA is.  It should be defined.

It shouldn't be hard to add this link to the doc:  https://docs.microsoft.com/en-us/odata/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6b51d7-e615-8421-1789-4e74ff35b361
* Version Independent ID: d1e8f7de-9c60-cf00-71bf-59c70935be0e
* Content: [Connect with data by using OData queries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/odataquery-connect?view=azure-devops#use-visual-studio-code-to-write-and-test-odata-queries)
* Content Source: [docs/report/powerbi/odataquery-connect.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/odataquery-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gitclem - Thank you for the feedback. I'll make sure to add the link to this and other articles.
